### ISSUE TITLE
[FIELDS] setFieldOrder()

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#10]
The programmer should have the ability to choose the order the fields, after the fact. 

This function in Crud.php should be completed:
$this->crud->setFieldOrder(['field_1', 'field_2', 'field_3'], 'update/create/both');

**Comment by tabacitu** [comment]
Then these need to be done too:

```php
$this->crud->setColumnOrder(['column_1', 'column_2', 'column_3']);
$this->crud->setButtonOrder($stack, ['column_1', 'column_2', 'column_3']);
```

**Comment by tabacitu** [comment]
On second thought, the order is self-evident. You type the columns/fields in an order and that's the order they're shown. 

I say... drop it like it's hot.

**Comment by tjventurini** [comment]
If you need to change the order or fields lateron you can simply remove or comment out the `$this->crud->setFromDb();` so the fields are listed as used in the controller.

Thought that might help someone :slightly_smiling_face:
