### ISSUE TITLE
active filter (css class) for inactive filter

### ISSUE THREAD

**Issue by kolep8** [Laravel-Backpack/CRUD#1006]
No matter how much custom filters are, if I dont select any or select some or press "Remove filters", last filter always have css class added "active", and filters who are actually selected dont have "active" class.
No matter what only last filter always is marked as "active" and filters who should have this class  dont have it.

**Comment by adriallongarriu** [comment]
This has been fixed update your Backpack/Base
more info: https://github.com/Laravel-Backpack/Base/issues/155

**Comment by lloy0076** [comment]
Closed due to a fix.
