### ISSUE TITLE
daterangepicker-bs3.css missing?

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/CRUD#102]
I've gone through all the publish commands and I cant find any more that I could run, however the issue is when on the dashboard/admin area there is a css file 404ing

![dashboard____bravo_admin](https://cloud.githubusercontent.com/assets/1094740/18342618/9115b0c6-75a7-11e6-875a-2f63c86ca372.png)

its looking for `daterangepicker-bs3.css` but that is not in the folder published

![_users_owen_sites_bravo_public_vendor_adminlte_plugins_daterangepicker](https://cloud.githubusercontent.com/assets/1094740/18342633/a2bdf914-75a7-11e6-956e-9de45139e9ec.png)

for the time being i've adjusted the blade template to include the other one

**Comment by BinaryBlock** [comment]
I believe I experienced the same issue. I just found the file online and put in folder.
![image](https://cloud.githubusercontent.com/assets/8375856/18399058/5974f130-769d-11e6-9aa8-82f9604700ca.png)
This is where I got the file: https://almsaeedstudio.com/themes/AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css
You will need the daterangepicker-bs3.js too, I believe:
https://almsaeedstudio.com/themes/AdminLTE/plugins/daterangepicker/daterangepicker.js

**Comment by tabacitu** [comment]
Hi guys,

Thanks for the issue. AdminLTE changes the names of the files sometimes and we just have to keep up.

On second thought, we don't _need_ that CSS file on all pages. Nor a few others. They aren't used, so in ```Backpack\Base v0.7.1``` I've [removed them entirely](https://github.com/Laravel-Backpack/Base/commit/d74fd8ecf4c913602a247915a5265035b5305e68).

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by tabacitu** [comment]
**Note:** In case you've already published the Backpack\Base views, you will be using your own layout.blade.php (in ```resources/views/vendor/backpack/base/layout.blade.php```) so you need to [do the same change in your file](https://github.com/Laravel-Backpack/Base/commit/d74fd8ecf4c913602a247915a5265035b5305e68).
