### ISSUE TITLE
Not working removeColumns and beforeColumn

### ISSUE THREAD

**Issue by eddilou** [Laravel-Backpack/CRUD#1020]
After the upgrade to version 3.2.20, the function removeColumns stopped working.
I use to hide the columns that are displayed in details_row
And not working addColumn()->beforeColumn().

**Comment by valetzyzy** [comment]
+ have the same problem

**Comment by tabacitu** [comment]
@tumf87  any idea why?

**Comment by tabacitu** [comment]
@eddilou can you give me more details about how you're using removeColumn() or removeColumns()? Copy-paste your setup maybe? I just tested both and they seem to work fine to me: https://cl.ly/1Z2P1u093N2Q

@valetzyzy the same from you would help a lot.

Thanks, cheers!

**Comment by eddilou** [comment]
@tabacitu hi, in setup
```php
        $this->crud->removeColumns([
            'Job',
            'LastChange',
            'comment',
            'amount',
            'timeframe',
            'affid',
            'clickid',
            'cid',
            'mail_confirm',
            'mail_welcome',
            'agent',
            'is_approved',
            'fee_half',
            'delivery_date',
        ]);

        $this->crud->addColumn([
            'name' => 'Id',
            'label' => 'Id'
        ])->beforeColumn('Gender');

        $this->crud->setColumnDetails('Status', [
            'type' => 'radio',
            'options' => config('lead_statuses'),
        ]);

        $this->crud->enableDetailsRow();
        $this->crud->allowAccess('details_row');

        $this->crud->enableAjaxTable();

        $this->crud->addClause('where', 'is_approved', 1);

        $this->crud->addFilter([
            'name' => 'date',
            'type' => 'date_hidden',
            'label' => 'Contract Send Date',
        ],[],
            function($value) {
                $this->crud->addClause('whereDate', 'date', $value);
                $this->crud->addClause('where', 'Status', 5);
            });

        $this->crud->orderBy('Id','desc');

```

in function showDetailsRow
```php
        $this->crud->hasAccessOrFail('details_row');

        $this->data['entry'] = $this->crud->getEntry($id);
        $this->data['crud'] = $this->crud;
        $this->data['list_columns_details'] = [
            'Job' => 'Job',
            'LastChange'=> 'Last Change',
            'comment' => 'Comment',
            'amount' => 'Amount',
            'timeframe' => 'Timeframe',
            'mail_confirm' => 'Mail Confirm',
            'mail_welcome' => 'Mail Welcome',
            'agent' => 'Agent',
            'monthly' => 'Monthly',
            'fee' => 'Fee',
            'fee_half' => 'Fee 50% Only',
        ];

        $this->data['dates_columns'] = [
            'date',
            'LastChange',
        ];

        $calc = $this->data['entry']->getCalculatedData();
        $this->data['entry']['monthly'] = $calc['rate'];
        $this->data['entry']['fee'] = $calc['fee'];

        return view('vendor.backpack.crud.details_row_lead', $this->data);
```

**Comment by tabacitu** [comment]
Hi @eddilou ,

Thanks for the code. I now see that you mentioned "_I use to hide the columns that are displayed in details_row_". I bet that is a custom feature right there :-) The view ```vendor.backpack.crud.details_row_lead ``` is not part of Backpack, we just provide a bogus detail row to start with.

Here's what I understand:
- ```removeColumns()``` does do what it's supposed to - it removes the columns you specify from the ```$crud->columns``` stack
- it did NOT do this properly until now, but no it does; it's a bug we've only discovered when writing the unit tests; you've started using it when it didn't do this correctly for all columns, and now that it's fixed it "breaks" your app;

If so, I'm very sorry for having pushed a half-baked feature. There's been a few months in Backpack when PR requests have overwhelmed me and I've hit "merge" on a few without properly testing them. I don't do that anymore - as you can see there are always plenty of PRs and issues, no matter how much time I spend on this. This might be annoying to some, but at least we don't push half-features anymore - I think it's for the better. So it won't happen again.

Sorry for having this broken feature all this time. Please modify your ```vendor.backpack.crud.details_row_lead ``` accordingly. Let me know if you think I'm wrong and there's a bug in ```removeColumns()``` (as in, it does not remove the columns).

Cheers!

**Comment by eddilou** [comment]
@tabacitu Before the update on 3.2.20, everything worked fine

**Comment by eddilou** [comment]
@tabacitu in details_row_lead only the text display is rewritten and the display of icons is added, it is made on the basis of details_row therefore this error is excluded, I have completely eliminated the function and still does not work properly, I repeat that before get updates all worked, and now even without enableDetailsRow() and allowAccess('details_row'); does not work removeColumns

**Comment by eddilou** [comment]
@tabacitu if you think that I am lying and that purposely create a problem then the problem is not only for me :)
details_row_lead.blade.php
```blade
<div class="m-t-10 m-b-10 p-l-10 p-r-10 p-t-10 p-b-10">
	<div class="row">
		<div class="col-md-12">
            @foreach($list_columns_details as $k=>$v)
                @if($k == 'Status')
                    <p><label>{{ $v }}:</label> {{ $entry->getStatusName() }}</p>
                @elseif($k == 'fee_half')
                    <p><label>{{ $v }}:</label> <span class="glyphicon glyphicon-{{ !empty($entry->{$k})? 'ok' : 'remove'}}"></span></p>
                @else
                    <p><label>{{ $v }}:</label> @if(in_array($k, $dates_columns) && !empty($entry->{$k})){{ \Carbon\Carbon::parse($entry->{$k})->format('Y-m-d') }}@else {{ $entry->{$k} }}@endif</p>
                @endif
            @endforeach
		</div>
	</div>
</div>
<div class="clearfix"></div>
```

**Comment by eddilou** [comment]
@tabacitu when using the function of beforeColumn and afterColumn within these functions, the moveColumn function is called, possibly a problem in it, in the condition if (array_key_exists($targetColumnName, $this->columns)) look carefully for the index(assoc) in the indexes (numbered)

**Comment by eddilou** [comment]
@tabacitu in 3.3.21 fix, thank

**Comment by tabacitu** [comment]
Pfiew :-)
