### ISSUE TITLE
New CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1025]
We've been blessed with so many contributions, that it's humbling. A lot of people have been helping with Backpack, and I'm trying to figure out ways we can recognize their good work. 

I think until now [Github's contributors page](https://github.com/Laravel-Backpack/CRUD/graphs/contributors) has been ok, but sometimes it would be more useful for contributors to promote a product, a company or their personal website, rather than their Github profile. When trying to promote something, one link from a project like Backpack could really help SEO. Plus, you never know when one link turns into a customer/whatever.

I think an easy start would be to create a CONTRIBUTORS.md file in the root, where we invite [contributors](https://github.com/Laravel-Backpack/CRUD/graphs/contributors) to submit a PR with whatever they want to promote. Just one line of markdown for anyone that has something to promote, otherwise just a link to their github profile. So something like:

--- 

# Contributors

We have been blessed with many wonderful people in our community. They help Backpack become better every day, week, month or whenever they can. It's not easy finding time to pitch in, and we're very _very_ grateful for their support, so here's a list of them all. 

> If you've pitched in on Github/StackOverflow to Backpack but aren't featured here, please submit a PR with your line and whatever you want to promote. Try to insert yourself as you currently appear on the [Github contributors](https://github.com/Laravel-Backpack/CRUD/graphs/contributors) page. Please try to fit everything into one line, using the same syntax.

Contributors:

- **[Cristian Tabacitu](https://github.com/tabacitu), Romania** - [himself](http://tabacitu.ro); creator of [Backpack for Laravel](https://backpackforlaravel.com/) and [ScheduleThatEmail](http://schedulethatemail.com/), CEO at [:DigitallyHappy](http://digitallyhappy.com/) and Managing Partner [UPDIVISION](http://updivision.com/)

- **[Owen Melbourne](https://github.com/owenmelbz), UK** - creator of [ConsoleWatch](https://www.consolewatch.io/?utm_source=backpack_contributors_md&utm_medium=cpc), [freelancer](https://www.owenmelbourne.com/) and developer at [Selesti](https://www.selesti.com/)

---

So syntax would be:

- **[Fullname or Nickname](github link), Country** - short description of what he/she does, [with links](http://google.com), ideally on one line

It's small, but it's a start...

PS. Since it's [Hacktoberfest](https://hacktoberfest.digitalocean.com/), I think this is a great opportunity for someone's first PR.

**Comment by OwenMelbz** [comment]
Seems like a nice sentiment :) I'm sure everybody would appreciate it

**Comment by ZackTaylor** [comment]
Id like to take a shot at this!
