### ISSUE TITLE
Can not pass variable to Config::set in elfinder

### ISSUE THREAD

**Issue by allam2002** [Laravel-Backpack/CRUD#1039]
i am creating a project for listing Departments and their Clients and i want to use elfinder to connect to each client folder when i edit the client , So i created a middleware for elfinder to create the client folder and to change the elfinder.dir to that directory the first part of creating dir is done but the problem is in Config::set is not working ,My Code is:

The Middleware :

```
public function handle($request, Closure $next)
{
   $iid = $request->client;

    if (!Storage::disk('doc')->exists('$iid')){
    Storage::disk('doc')->makeDirectory($iid);
     }

     \Config::set('elfinder.dir', $iid);

    return $next($request);
}
```
The Route:

`Route::get('admin/client/{client}/edit', 'Admin\ClientCrudController@edit')->middleware('elfindernew');`
The ElfinderController :

```
public function showConnector()
{
    $roots = $this->app->config->get('elfinder.roots', []);
    if (empty($roots)) {
        $dirs = (array) $this->app['config']->get('elfinder.dir', []);
        foreach ($dirs as $dir) {
            $roots[] = [
                'driver' => 'LocalFileSystem', // driver for accessing file system (REQUIRED)
                'path' => storage_path('doc')."/".$dir,
                'URL' => url($dir), // URL to files (REQUIRED)
                'accessControl' => $this->app->config->get('elfinder.access') // filter callback (OPTIONAL)
            ];
        }
```
I don't Know what is wrong Can someone Help me.....

**Comment by lloy0076** [comment]
Might be besked at [SO](https://stackoverflow.com/search?q=laravel+backpack) - I think the problem you're experiencing is that `(array) $this->app['config']->get('elfinder.dir', []);` ends up being an empty array even though you think it contains something?

**Comment by allam2002** [comment]
First i did asked at SO and here is the link https://stackoverflow.com/questions/46516191/can-not-pass-variable-to-configset-in-laravel-elfinder 

Second you are right about the array and i am completely lost here , can you  @lloy0076 please help me in that issue

**Comment by allam2002** [comment]
No body can help me ?????

**Comment by lloy0076** [comment]
What is your middleware meant to be doing?


```
public function handle($request, Closure $next)
{
   $iid = $request->route('client');
    // What the world is THAT?

    if (!Storage::disk('doc')->exists('$iid')){
        Storage::disk('doc')->makeDirectory($iid);
    }

     \Config::set('elfinder.dir', $iid);

    return $next($request);
}
```

I think if you can answer the question "What the world is THAT" you might find the issue.

i.e. what do you *think* `$request->route('client'`)` should be returning?

Is it mean to be the client ID?
