### ISSUE TITLE
PHPUnit version upgrade from 4.x to 6.x

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1040]
On the ```upgrade``` branch we need to upgrade the PHPUnit version we use, since Laravel 5.5 requires PHPUnit 6+ and that's the only version we support.

**Comment by lloy0076** [comment]
I'm fairly convinced this will break something in the tests.

**Comment by tumf87** [comment]
Done, forgot to link the issue in the PR: #1044.

**Comment by tabacitu** [comment]
Fixed. Thank you @tumf87 .
