### ISSUE TITLE
select_mutliple/select2_multiple work, but don't display the values

### ISSUE THREAD

**Issue by mxmtsk** [Laravel-Backpack/CRUD#1042]
I'm currently evaluating laravel backpack for a customer and it's working great so far but I can't get the select_multiple field type get work properly.

```php
    $this->crud->addField([
      'label' => "Artists",
      'type' => 'select2_multiple',
      'name' => 'artists', // the method that defines the relationship in your Model
      'entity' => 'artists', // the method that defines the relationship in your Model
      'attribute' => 'name', // foreign key attribute that is shown to user
      'model' => "App\Artist", // foreign key model
      'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
    ]);
```

Relationship:
```php
    public function artists()
    {
        return $this->belongsToMany(Artist::class, 'artist_spot');
    }
```

When I select an Artists in my case and save the entity it works - it actually does get saved, but when I go back to editing it is not selected. Did I do something wrong?
One thing to note though: The project is using UUIDs as primary keys, not regular integer ids, but I don't know if this is why it fails.

Edit:
I've checked the blade code and checked some of the values used for the `selected` status.
`isset($field['value'])` returns false. `old($field['name'])` is `null` although there is one entity related.

**Comment by mxmtsk** [comment]
never mind, this was a naming issue collision with a column

**Comment by tmtung144** [comment]
Has this error been fixed? It is very important for users to distinguish whether they have successfully saved instead of looking at the database :(

**Comment by tmtung144** [comment]
After finding a solution, I gave the following option:

```
$this->crud->addField([
            'label' => "Category",
            'type' => 'select2_multiple',
            'name' => 'categories', // the db column for the foreign key
            'entity' => 'categories', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Category",
            'pivot' => true,
            'value' => Post::find(1)->categories()->where('post_id', 1)->get() // <-- Add the default value from the database
]);
```

**Comment by tabacitu** [comment]
@tmtung144 I'm not aware of any problems here. The OP had a user error - probably two fields with the same name. Are you sure you don't have the same problem? What I see you've done for ```value``` should NOT be necessary...

The saved values get loaded on Edit just fine in my tests:
![Screenshot 2019-05-07 at 13 15 49](https://user-images.githubusercontent.com/1032474/57292411-50094400-70ca-11e9-80fd-3c4acd2bfdde.jpg)

**Comment by iMokhles** [comment]
@tabacitu for some reason the value saved in database doesn't work while editing the crud with select2 ( CRUD Package version 3.6 )
i had to use solution similar to @tmtung144 to add 

```
[  
                'label' => trans('admin.category'),
                'type' => 'select2',
                'name' => 'category_id', 
                'entity' => 'category', 
                'attribute' => 'name', 
                'model' => Category::class, 
                'value' => $this->crud->getCurrentEntryId() ? Recipe::find($this->crud->getCurrentEntryId())->category->id : null,
                'tab' => trans('admin.tags'),
            ]
```
without this ` 'value' => $this->crud->getCurrentEntryId() ? Recipe::find($this->crud->getCurrentEntryId())->category->id : null,` the value saved in database becomes null in editing page.

**Comment by tabacitu** [comment]
@iMokhles I think it's just a matter of missing quotes in Javascript. So when the key is integer, it works. When it's not integer, it does not. 

Could you please try:
1. publishing the select2_multiple field to your project using ```php artisan backpack:publish crud/fields/select2_multiple``` 
2. making this change in _your_ ```select2_multiple``` field?

```diff
                        @if (count($options))
                            @foreach ($options as $option)
-                                options.push({{ $option->getKey() }});
+                                options.push('{{ $option->getKey() }}');
                            @endforeach
                        @endif
```

Let me know if this fixed it for you. Unfortunately we're no longer pushing updates to 3.6.

**Comment by tmtung144** [comment]
Try to upgrade to Laravel 6.x and Backpack 4.x will fix this
