### ISSUE TITLE
Array of Values for enableReorder

### ISSUE THREAD

**Issue by cvassios-ekko** [Laravel-Backpack/CRUD#1049]
Is there a way to make multiple values for the db column names displayed on reorder. 

Something like `$this->crud->enableReorder(['title','sub_title'], 1);`

**Comment by lloy0076** [comment]
There is but it's going through a PR at the moment.

https://github.com/Laravel-Backpack/CRUD/pull/1015

**Comment by cvassios-ekko** [comment]
Thanks for pointing that out to me @lloy0076 

For anybody else who comes across this, I figured out an alternate solution:

In the `reorder.blade.php` file located in `vendor/backpack/crud/src/resources/views` directory,
I changed 

`echo '<div><span class="disclose"><span></span></span>' . object_get($entry, $crud->reorder_label) . '</div>';` (line 28 for me), to:

`echo '<div><span class="disclose"><span></span></span>' /*. object_get($entry, $crud->reorder_label) . ' '*/ . $entry->sub_title . ' ' . $entry->title .'</div>';`

**Comment by tabacitu** [comment]
Has since been fixed. Thanks @cvassios-ekko for spotting it, and suggesting the solution. Cheers!

**Comment by tifaahmed** [comment]
i ' m using localization to show the right language in  enableReorder 

`        $this->crud->enableReorder(' '.trans('static.name_en').' ', 2);
`
in resources/lang/en/static.php
```
<?php 
return [
	"name_en"=>"name_en",
]
```
in resources/lang/ar/static.php
```
<?php 
return [
	"name_en"=>"name_ar",
]
```

but `$this->crud->enableReorder(['title','sub_title'], 1);`  didn't work
