### ISSUE TITLE
Filemanager infinite loop!?

### ISSUE THREAD

**Issue by AbanoubNassem** [Laravel-Backpack/CRUD#1051]
following this docs , https://laravel-backpack.readme.io/v3.0/docs/install-on-laravel-55#section-3-install-backpackcrud, literally step by step to the point of installing  , Backpack\CRUD , after making the uploads dir, publishing the configs etc , adding the disk , and adding the link to the menu 

`<li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . '/elfinder') }}"><i class="fa fa-files-o"></i> <span>File manager</span></a></li>`

once I click on the filemanager url , the pages keep refreshing forever , causing the browser and apache to lag , due to the heavy use of the cpu , not sure what is causing this issue!

**Comment by tabacitu** [comment]
Hi @AbanoubNassem ,

That's very odd. I just installed Backpack myself on a MAMP server and got none of that. What's your server stack? Have you managed to find out the issue in the meantime?

Cheers!

**Comment by AbanoubNassem** [comment]
@tabacitu am using XAMPP , and nope , I couldn't solve the issue , and I'm using Chrome as a browser!

**Comment by dboscanv** [comment]
The same happens to me! I am using homestead, this is the console log in the browser:
![error elfinder](https://user-images.githubusercontent.com/13837852/32858652-f381df36-ca2a-11e7-9127-7a1c425332bd.JPG)

Anyone know about this?

**Comment by tabacitu** [comment]
Hmm... doesn't seem like Backpack-specific issue, must be an elFinder one. @dboscanv does this help you debug it? https://stackoverflow.com/questions/5584810/iis-gives-502-error-using-elfinder-how-to-debug-it

**Comment by tabacitu** [comment]
PS. I just tried it on homestead and it works fine for me.

**Comment by Magweb06** [comment]
Same issue on MAMP PRO, files manager makes an infinite loop ... and the server goes down.
Anyone to help ? Thanks.

**Comment by tabacitu** [comment]
Pff... sorry to hear that @Magweb06 . No idea how to debug this, though. Just tried it on MAMP Pro again, and on Homestead, and it worked fine for me: https://cl.ly/153Y0q32122M

This should be either a server config issue, or a Laravel-Elfinder one, since most Backpack users haven't had this issue. Sorry I can't be of more help...

**Comment by tabacitu** [comment]
@OwenMelbz sure - I'll take a look but no guarantees I find something :-) How about Thursday my 2pm - your noon I assume?

**Comment by silnychyi** [comment]
Same here. Constantly making requests to connector endpoint. This happens only in Chrome btw. Safari and Firefox works fine.

<img width="1774" alt="Screenshot 2024-02-15 at 12 14 44" src="https://github.com/Laravel-Backpack/CRUD/assets/34551449/abef8e1d-4b14-420b-9cd2-8790e6e58f4f">
<img width="1771" alt="Screenshot 2024-02-15 at 12 15 14" src="https://github.com/Laravel-Backpack/CRUD/assets/34551449/3b14f5c7-74b7-4cbe-b619-cbf5998d443f">

Any update on that?
