### ISSUE TITLE
Cant go to Create page

### ISSUE THREAD

**Issue by edwinnsan** [Laravel-Backpack/CRUD#1052]
Hello. 
I sync my laravel 5.5 with laravel backpack.
Then i create some model, controller and everything work fine. 
Then i go to my menu to try to create some data.

But When i Click button "Add data"

i get this error "Backpack \ CRUD \ Exception \ AccessDeniedException
Unauthorized access - you do not have the necessary permissions to see this page."

![permission](https://user-images.githubusercontent.com/17553775/31266361-995a7060-aa9d-11e7-983e-8ac8b8c9c1e1.png)

this is my code for controller, model and request
Model
![model](https://user-images.githubusercontent.com/17553775/31266555-88049164-aa9e-11e7-9c12-e40f71008e00.png)

Controller
![controller](https://user-images.githubusercontent.com/17553775/31266470-1f080b64-aa9e-11e7-9aad-6217b05e3cd9.png)

Request

![request](https://user-images.githubusercontent.com/17553775/31266561-8b111bde-aa9e-11e7-8c3d-9c7351f99e3a.png)

**Comment by edwinnsan** [comment]
[SOLVED]

**Comment by lloy0076** [comment]
I assume that's because of the:

```
public function authorize()
{
    return false;
}
```

...in the request?

**Comment by krtrth** [comment]
how is it solved can you give me a clue

**Comment by AbbyJanke** [comment]
@krtrth do you have any errors? What does your controller code look like? we need more information.

**Comment by krtrth** [comment]
I was getting this same error while trying to delete but when I moved it to server it worked somehow
