### ISSUE TITLE
Image Column does not have Prefix Option

### ISSUE THREAD

**Issue by mxmtsk** [Laravel-Backpack/CRUD#1054]
This issue is appeared with the introduction of the image column (PR #913)

The image column is missing the prefix option.

I'm saving all my uploaded assets in a Amazon S3 bucket and only save the key to the file in the database for example `user_avatars/file.jpg`. To display the image correctly in my edit form I can pass a `prefix` attribute that gets prepended to the value. So you'd ultimately would need the prefix option whenever you save the assets on a different server.

Example:
```php
    $this->crud->addField([
      'name' => 'image',
      'label' => "Image",
      'type' => 'image',
      'upload' => true,
      'prefix' => 'https://cloud.myurl.com/', // the domain of my bucket
      'crop' => true,
      'aspect_ratio' => 0,
    ]);
```
https://github.com/Laravel-Backpack/CRUD/blob/6e31f985e902bd8d0b5891db143cad8d79427e6e/src/resources/views/fields/image.blade.php#L19

Now, when I want to use the image column introduced by the PR above I am unable to display the image, because the image column does not have a `prefix` option. I think the image column should be streamlined with the how the image field works - what do you think?

**Comment by lloy0076** [comment]
Would that be a breaking change?

**Comment by mxmtsk** [comment]
@lloy0076 no, as it would only get prepended when you actually pass a prefix property it would not be a breaking change. I might provide a PR with a fix when I'm less busy in case no one else has time right now :)

**Comment by bul-ikana** [comment]
I opened PR #1056 to address this. 

@mxmtsk Could you please check if it solves the problems you are having?
