### ISSUE TITLE
Custom and fake primaryKey problem with save_and_edit insert mode

### ISSUE THREAD

**Issue by sistemaswebbrasil** [Laravel-Backpack/CRUD#1057]
I'm using the `protected $ primaryKey = 'code'` property on my model, it's a fake key.In my controller I'm incrementing the value of the key manually like this:
```
    public function store(StoreRequest $request) {
       ...
        //select max(code)+1 from client
        $code = DB::table("client")->select(DB::raw("MAX(code)+1 AS code"))->first();
        $request['code'] = $code->code;
      ...    }
```
works correctly for save button options save_and_back and save_and_new , in the save_and_edit action it saves correctly in the database, but the redirect url uses the actual key code of the database and not the key defined in the model.

Debugging the code I discovered that the problem happens in Backpack\CRUD\PanelTraits\Create,php in method create exactly in this line:

``` $item             = $this->model->create(array_except($data, $nn_relationships));```

To work around I'm saving the value of the variable item with the actual value of the fake key.

```
    public function create($data) {
        ...
        $item = $this->model->create(array_except($data, $nn_relationships));
        $key  = $this->model['primaryKey'];
        $item[$key] = $data[$key];
        ...
    }
```

I wonder if you have any other way to solve this problem?I am using an old database, with no possibility to change the structure.thanks!

**Comment by lloy0076** [comment]
I'm not sure I understand the actual problem - I seem to be lost in `but the redirect_url ... and not the key defined in the model`.

**Comment by tabacitu** [comment]
Hm.... don't see another solution for this particular use case, sorry.
