### ISSUE TITLE
[Feature proposal] Alternative select_multiple

### ISSUE THREAD

**Issue by xdasty** [Laravel-Backpack/CRUD#1060]
Hi Guys
I congratulate you on tabacitu's work
I put my code on the FIELD TYPES I hope I can serve someone
this is a multiselect version select_multiple (n-n relationship)
Below you find a picture of the result obtained
![multi_select](https://user-images.githubusercontent.com/32037075/31437736-98b0dd6a-ae86-11e7-8160-d36b8f9bbb79.jpg)

-----------------------------------------------------------------------------------
------------------------------- UserCrudController -------------------------------
-----------------------------------------------------------------------------------
class UserCrudController extends OriginalUserCrudController
{
    public function setup()
    {
		parent::setup();

    	$this->crud->addColumn([
            'label' => 'Categorie',
            'type' => 'select_multiple',
            'name' => 'categorie',
            'entity' => 'categorie',
            'attribute' => 'nome',
            'model' => "App\Models\Categorie",
    	]);

    	$this->crud->addField([
	    		'label'     => 'Categorie',
	            'type'      => 'select3_multiple',
	            'name'      => 'categorie',
	            'entity'    => 'categorie',
	            'attribute' => 'nome',
	            'model'     => "App\Models\Categorie",
	            'pivot'     => true,
	            'number_columns'   => 3, //can be 1,2,3,4,6
        ]);

    	$this->crud->removeField('user_role_permission', 'update/create/both');  
    	$this->crud->addField([
            // two interconnected entities
            'label'             => trans('backpack::permissionmanager.user_role_permission'),
            'field_unique_name' => 'user_role_permission',
            'type'              => 'select3_multiple_dependency',
            'name'              => 'roles_and_permissions', // the methods that defines the relationship in your Model
            'subfields'         => [
                    'primary' => [
                        'label'            => trans('backpack::permissionmanager.roles'),
                        'name'             => 'roles', // the method that defines the relationship in your Model
                        'entity'           => 'roles', // the method that defines the relationship in your Model
                        'entity_secondary' => 'permissions', // the method that defines the relationship in your Model
                        'attribute'        => 'name', // foreign key attribute that is shown to user
                        'model'            => config('laravel-permission.models.role'), // foreign key model
                        'pivot'            => true, // on create&update, do you need to add/delete pivot table entries?]
                        //'number_columns'   => 3, //can be 1,2,3,4,6
                    ],
                    'secondary' => [
                        'label'          => ucfirst(trans('backpack::permissionmanager.permission_singular')),
                        'name'           => 'permissions', // the method that defines the relationship in your Model
                        'entity'         => 'permissions', // the method that defines the relationship in your Model
                        'entity_primary' => 'roles', // the method that defines the relationship in your Model
                        'attribute'      => 'name', // foreign key attribute that is shown to user
                        'model'          => "Backpack\PermissionManager\app\Models\Permission", // foreign key model
                        'pivot'          => true, // on create&update, do you need to add/delete pivot table entries?]
                    ],
                ],
        ]);

    }

}

-----------------------------------------------------------------------------------
- project_name\resources\views\vendor\backpack\crud\columns\select3.blade.php - (select3.blade1.php)
-----------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
- project_name\resources\views\vendor\backpack\crud\fields\select3.blade.php -
-----------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
- project_name\resources\views\vendor\backpack\crud\fields\select3_multiple.blade.php -
-----------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
- project_name\resources\views\vendor\backpack\crud\fields\select3_multiple_dependency.blade.php -
-----------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
- project_name\public\js\duallistbox.js -
-----------------------------------------------------------------------------------

-----------------------------------------------------------------------------------
- project_name\public\css\duallistbox.css -
-----------------------------------------------------------------------------------
[multi_select.zip](https://github.com/Laravel-Backpack/CRUD/files/1375381/multi_select.zip)

**Comment by tabacitu** [comment]
Hi @xdasty ,

This looks like some great work. 

The interface is a bit crowded for my taste, I prefer select2's tinier visual footprint, but it's definitely a matter of personal preference and I bet you'll save some people a lot of time. 

I propose we publish this on [the Backpack blog](https://backpackforlaravel.com/articles), in your name. That way others will be able to reuse your code. I plan on putting a lot more snippets there, for developer to easily use. What do you say? If you agree, please:
- write a small introduction and an example usage (like above) in markdown, wherever you want; if you need to put CSS and JS (multiple files) a good place to store all the files would be [a Github gist](https://gist.github.com/);
- feel free to promote yourself, your services, or your company in the article, and link to your website/github/linkedin/etc; you never know when one link turns into $$$ :-)
- register on [BackpackForLaravel.com](https://BackpackForLaravel.com), so I can post the article in your name;
- send me an email with the article link at hello@tabacitu.ro and I'll post it for you;

Thanks, cheers!

**Comment by xdasty** [comment]
Thank you @tabacitu , it is an honor to hear these words, and I will continue to contribute.
