### ISSUE TITLE
[ASK] Data based on user login

### ISSUE THREAD

**Issue by edwinnsan** [Laravel-Backpack/CRUD#1062]
hello i want ask..
in backpack I want to display data which is only owned by the user
i can do this by do $this->crud->addClause('where', 'user_id', Auth::user()->user_id);
example if data in database -> A,B,C,D,E and User1 just have data -> A,B,C
but when user go to edit page like http://..../public/admin/event/A/edit 
user can replace the id with everything the user want, 
like http://..../public/admin/event/E/edit, but this data is not for that user
how to make abort 403 if user access other data?
thank you

**Comment by lloy0076** [comment]
This question comes up quite frequently and there really should be an FAQ about it 😄 

Do a:

```
% php artisan route:list
```

You'll see the routes for show etc. etc. there; you can override these methods (and if they can edit whatever it is, just do `parent::NAME_FUNCTION($request)`.

You'll need to check them in update and save.

Just for good measure, I also throw observers on my Models too but be aware that `create`, `update(array $data)` and such don't trigger the observers and working with pivot tables is a pain ATM.

**Comment by edwinnsan** [comment]
sorry im still confused hahah..

so i must override show method like this?

`public function show(ShowRequest $request)
    {
       if(condition) {
       }
       else
       {
        return parent::showCrud();
       }
    }`

like that in my crudcontroller? 
or can i get the example please? thank you for your reply

**Comment by edwinnsan** [comment]
I try this in my crudcontroller
![show](https://user-images.githubusercontent.com/17553775/31533648-80267dc0-b01d-11e7-9e64-b054fe23af0b.png)

and i create trait 
![trait](https://user-images.githubusercontent.com/17553775/31533671-9fd36034-b01d-11e7-9ffa-812cc1fa38ce.png)

i try to dd($id) but when i click edit button still show my data not return of dd($id).
am i wrong? still need your advice

**Comment by lloy0076** [comment]
Traits and me don't always mix so well - call it an odd `quirk`; your trait problem is a PHP problem 🙉 

However, you're on the right track.

Make sure to wrap the `store` and `update` methods as well.

The `addClause` will stop users from having pre-filled data in the edit form _if_ it works at all (I can't remember) so you're doing the right thing there too.

Honestly, I'd avoid using the trait until you got it working on one single concrete controller and THEN take up a fight with traits.

**Comment by edwinnsan** [comment]
i still dont know how to use show() method hahahah

> $event_id = \Route::current()->parameter('event_id');
>  $this->crud->setRoute(config('backpack.base.route_prefix') .'/event'.$event_id);

is this true or not?
and how to override the show function?

and i already delete my trait too hahaha

**Comment by lloy0076** [comment]
If the edit field is still getting field, then I think you're doing something odd but I have to go now - we have a gitter community where you can ask (and slack on laracasts), as well as SO.

**Comment by edwinnsan** [comment]
i ask at gitter but no one answer it haha..
oke oke i hope you still can help me after you on home thanks :D

**Comment by edwinnsan** [comment]
[FINALLY SOLVED]
with override edit function
