### ISSUE TITLE
Model attribute cast problem

### ISSUE THREAD

**Issue by Chrysanthos** [Laravel-Backpack/CRUD#1067]
When an attribute is stored as json in mysql and casted by default using the $casts variable in the model I get the error below and the crud won't load.

> DataTables warning: table id=crudTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7

`protected $casts = [
        'availability' => 'array'
    ];`

**Steps to reproduce:**
1) Create a model and CRUD for the model with a json attribute
2) Automatically cast the variable using $casts in the model
3) Reload Crud

**Comment by lloy0076** [comment]
There's obviously something afoot here - I suspect some type of double encoding/decoding.

What's in `storage/logs/laravel.log`?

**Comment by Chrysanthos** [comment]
@lloy0076 My laravel.log is empty.

**Comment by tabacitu** [comment]
Hi @Chrysanthos ,

How do you show ```availability``` in the table? Using what column? Are you using [the array column](https://laravel-backpack.readme.io/docs/crud-columns-types#section-array)?

Cheers!

**Comment by Chrysanthos** [comment]
Hi @tabacitu,

I tried using both array and text without luck. Both produce the same error.

**Comment by tabacitu** [comment]
Hi @Chrysanthos ,

I just tested the column and it works well for me, either that column is casted or not. Here's my video experience here: https://cl.ly/2d440Q082l2g

But I _think_ I figured out what might be wrong in your case. Are you trying to use the ```array``` column for a multiple-level array? Something that you put in with a ```table``` field perhaps? If so, that won't work, no. 

The ```array``` column is only to show information from a simple JSON array stored in a database column. Example value: ```["one", "two", "three"]```

I just tested all use cases and it seems to work fine, so I\m pretty sure it's a misunderstanding, misusage or docs issue. So I'll close this. Feel free to reopen if I'm wrong and it's a bug in the software. Let me know if that was the case - you were trying to use it on an attributive/complicated array.

Cheers!
