### ISSUE TITLE
Breadcrumbs with nested resources

### ISSUE THREAD

**Issue by adriandmitroca** [Laravel-Backpack/CRUD#1071]
I noticed that breadcrumbs aren't correctly working when it comes to nesting resources.

No matter how deeply nested the resource is, it always shows up as the first level in breadcrumbs and whole nesting path is lost. 

Reference: https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud

**Comment by lloy0076** [comment]
Define "correctly working" - or rather, what are they doing that is unexpected? A screenshot might be useful.

**Comment by adriandmitroca** [comment]
Currently, let's say when we have resource under URL: `/users/1/posts/` (like in article)

Breadcrumbs look like:
`Admin » Posts » List`

When in fact, it should be more like:
`Admin » Users » Posts » Lists`
or even:
`Admin » Users » {custom field, like email} » Posts » Lists`

**Comment by lloy0076** [comment]
@AbbyJanke I noticed a PR from you re: breadcrumbs; you probably can figure out if this is a bug, expected, unexpected or what-not?

**Comment by lloy0076** [comment]
If this is still an issue, please re-open?

**Comment by priyankagadhiya** [comment]
Hi @lloy0076,
I am new at Backpack. And I have the same requirement Admin » Users » Posts » Lists.
can you suggest me what should I do for that?

Thanks in advance

**Comment by dilneiss** [comment]
same here, that breadcrumb is wrong:

When i am at: Admin > Users > Posts > Lists 
The breadcrumb is to: Admin > Posts > Lists
But i'd like to have a link to previous page (Users) too..

**Comment by diegobas** [comment]
> same here, that breadcrumb is wrong:
> 
> When i am at: Admin > Users > Posts > Lists
> The breadcrumb is to: Admin > Posts > Lists
> But i'd like to have a link to previous page (Users) too..

You can set your custom breadcrumbs in your CrudController defining $this->data['breadcrumbs']. Example:

```
$this->data['breadcrumbs'] = [
        	trans('backpack::crud.admin')     => backpack_url('dashboard'),
        	Parent => backpack_url('parent_route'),
        	Children => backpack_url('children_route'),
           	trans('backpack::crud.list') => false,
        ];
```

**Comment by tabacitu** [comment]
Thank you for pitching in @diegobas . Indeed we have a solution for this in Backpack v4, the one you outlined above. I feel like it's a good idea to also link the breadcrumbs docs here, for more info: https://backpackforlaravel.com/docs/4.0/base-breadcrumbs#about

Cheers!
