### ISSUE TITLE
Multiple attributes on select2 field

### ISSUE THREAD

**Issue by bouffekai** [Laravel-Backpack/CRUD#1072]
Hello,

Is it possible to show multiple attributes in a select2 field ? For example : "attribute" => "firstname lastname" ?

Thanks

Jérémy

**Comment by lloy0076** [comment]
Not specifically like that - you could make an accessor (see here)[https://laravel.com/docs/5.5/eloquent-mutators].

**Comment by simonecicognani** [comment]
It doesn't work for custom accessors
