### ISSUE TITLE
Bug while using custom column

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#1077]
With the sample code, when I try to retrieve the data from the model (just coordinator_id and responsible_id) I get null, but only while retrieving from model_function.

I've got a Migration like this:

```
Schema::create('agencies', function (Blueprint $table) {
    $table->increments('id');
    $table->integer('coordinator_id')->nullable()->unsigned();
    $table->integer('responsible_id')->nullable()->unsigned();

    $table->foreign('coordinator_id')->references('id')->on('users')->onDelete('set null');
    $table->foreign('responsible_id')->references('id')->on('users')->onDelete('set null');

    // coordinator
    $table->string('name');
    $table->string('email');
    $table->string('vat');
    $table->string('tax_code');
    $table->string('address');
    $table->string('zip_code');
    $table->string('city');
    $table->string('province');
    $table->string('phone')->nullable();
    $table->string('fax')->nullable();
    $table->timestamps();
});
```
On the CrudController:
```
$this->crud->addColumns([
     [
         'name' => 'coordinator_id',
         'label' => 'Coordinatore',
          // run a function on the CRUD model and show its return value
         'type' => "model_function",
          'function_name' => 'getAgencyCoordinatorUserLink', // the method in your Model
     ]);
```
And if I do this in my model all works fine:
```
public function getAgencyCoordinatorUserLink(){
        return $this->id;
}
```

but, when I do
```
public function getAgencyCoordinatorUserLink(){
        return $this->coordinator_id;
}

or

public function getAgencyCoordinatorUserLink(){
        return $this->responsible_id;
}
```

I always get a null. But while retrieving the model from Tinker or in other ways it works fine getting all the values.

**Comment by lloy0076** [comment]
I suspect this is because you're using this when AJAX is enabled but can you confirm?

#710 purports to fix many issues re: AJAX tables.

**Comment by EmanueleCoppola** [comment]
Yes, exactly that, it works as expected removing AJAX.

**Comment by tabacitu** [comment]
Hi @EmanueleCoppola ,

If your project is still in development ,can you please try using the ```upgrade``` branch - it should be fixed there. Just use ```dev-upgrade``` for Backpack\Crud in your composer.json file, then run ```composer update```.

By the end of the week I expect it to be launched on master and you can undo the composer.json modifications.

Cheers!

**Comment by EmanueleCoppola** [comment]
Yes, @tabacitu it works with the upgrade branch.
