### ISSUE TITLE
No option to use local css instead of CDN css

### ISSUE THREAD

**Issue by palamike** [Laravel-Backpack/CRUD#1081]
Hi,

I'm using backpack for an intranet project which can not access cdn.
I found that many field use CDN Css/Js for example "select2", "datetime_picker" and others. 

The work around is to copy the field view file and override it but when the backpack/crud package update view file. this modification need to update again and again.

I think it would be better if we have an option to select "use CDN" or "use Local" assets.

**Comment by lloy0076** [comment]
See #1007 for a discussion.

@tabacitu I think there might be a middle step between what we have **and** #1007:

1. Have an option that simply does not include **any** of the JS includes over all the views.

**Comment by lloy0076** [comment]
Closing in favour of #1007.
