### ISSUE TITLE
[Discussion] Access\hasAccessToAll?

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1083]
I have been reviewing the majority of the code for Backpack for personal growth and understanding of it all. I noticed a function called "hasAccessToAll" under "PanelTraits\Access" however it is only used within tests. Is this something we really need, planning to implement further or is it something we can cut out to help have less useless functionality?

**Comment by AbbyJanke** [comment]
Seems that `PanelTraits\Access\hasAccessToAny()` is the exact same code and still only used in tests..

**Comment by lloy0076** [comment]
But because -we- don't use it other than in unit tests doesn't imply no-one else uses it...

**Comment by AbbyJanke** [comment]
Correct, I didn't say it couldn't be a potential "breaking change" but Repetitive code/unused code just adds clutter, more processing the CPU does, etc.

**Comment by lloy0076** [comment]
Just to unclatter the boards, I'm going to close this:

- Firstly, if it were going to "disappear" it probably should have in the latest upgrade;
- Secondly, even then it probably should have been deprecated a lot earlier;
- Thirdly, we don't know who out there uses it.

Feel free to re-open again if it seems it should be deprecated.
