### ISSUE TITLE
Session expire

### ISSUE THREAD

**Issue by ericsts** [Laravel-Backpack/CRUD#1088]
Somebody can help me?

If I do not use the system for some time, this error happens when I click anywhere

(4/4) ErrorException
Trying to get property of non-object (View: /home/sites/myweb/resources/views/backLayout/sidebarMenu.blade.php) (View: /home/sites/myweb/resources/views/backLayout/sidebarMenu.blade.php) (View: /home/sites/myweb/resources/views/backLayout/sidebarMenu.blade.php)

I think the session expires, but I dont know how to fix it

**Comment by lloy0076** [comment]
This sounds much more like a Laravel or even PHP session issue at the moment...

https://github.com/GeneaLabs/laravel-caffeine maybe?

**Comment by ericsts** [comment]
Thanks, but I would like to redirect user to login page instead of display a error

**Comment by lloy0076** [comment]
https://duckduckgo.com/?q=laravel+redirect+user+to+login+on+session+expiry&t=ffab&ia=web
