### ISSUE TITLE
Filter simple active class bug

### ISSUE THREAD

**Issue by Donkfather** [Laravel-Backpack/CRUD#1089]
Hi. I added a simple filter that is a boolean but the active class is set even if it is selected or not. I have tried to modify the simple.blade.php file but the class set if Request::get('filter.name') is in addition to the active class that sticks to the `li` tag no matter what.

**Comment by tabacitu** [comment]
Hi @Donkfather - yes, there was a bug with the simple filter at the time. Sorry for answering so late - it has since been fixed.

Thank you. Cheers!

**Comment by Donkfather** [comment]
Hi @tabacitu  I have updated to crud 3.4 and the base to 0.9 and copied the simple.blade.php and the filters_navbar.blade.php from the vendor but the filter still appears active by default. I tried to click remove filters but doesn't do anything.. What should I do to update? what am I missing?

**Comment by tabacitu** [comment]
Huh... that's weird - it doesn't do so in my tests, with the latest Backpack: https://cl.ly/153f2p3p1f0V

Let's see... The issue must have been in javascript, in ```list.blade.php```, so if you've customized/overwritten that file, that might be the issue. Your ```list.blade.php``` file.

Another option would be the ```layout.blade.php``` file - do you have a custom one for that?
