### ISSUE TITLE
Problem with elFinder

### ISSUE THREAD

**Issue by eddilou** [Laravel-Backpack/CRUD#1091]
# Bug report

### What I did: 
look the step https://laravel-backpack.readme.io/v3.0/docs/install-on-laravel-55#section-3-install-backpackcrud

### What I expected to happen: 
work page elfinder (filemanager)

### What happened:
blank page and in devtool network error 404 loading files: /public/packages/barryvdh/elfinder/css/elfinder.min.css
/public/packages/barryvdh/elfinder/js/elfinder.min.js
why the path /public/packages/barryvdh/elfinder/* if there is nothing transferred by the command vendor:publish?

### Backpack, Laravel, PHP, DB version:
Backpack CRUD 3.2.26
Laravel 5.5.19
PHP 7.1.10
DB  libmysql - mysqlnd 5.0.11-dev - 20120503

**Comment by eddilou** [comment]
The problem is solved by calling the command in the console 
`php artisan elfinder:publish`

**Comment by lloy0076** [comment]
That's not a bug - the steps for installing do indicate that command should be run.

**Comment by tabacitu** [comment]
@eddilou thanks for sharing your solution! Cheers!

**Comment by nickyskills** [comment]
I checked with Laravel 7.0 and i encounter the same issue
That ->  The command "elfinder:publish" does not exist.

Solution measure i took

- Open elFinder Package for Laravel 5.


- Require this package with Composer

` composer require barryvdh/laravel-elfinder`

- Add the ServiceProvider to the providers array in app/config/app.php

 Barryvdh\Elfinder\ElfinderServiceProvider::class

 - You need to copy the assets to the public folder, using the following artisan command:

 `php artisan elfinder:publish`


- After installing this  you may now re-run 

 `php artisan backpack:install --elfinder yes`

**Comment by pxpm** [comment]
Just for reference if anyone searches and find this. It's been fixed in: #2528
