### ISSUE TITLE
$this->crud->enableAjaxTable(); stops custom buttons working properly

### ISSUE THREAD

**Issue by stevecrossuk** [Laravel-Backpack/CRUD#1095]
When I added in $this->crud->enableAjaxTable(); my custom button for "View" stopped working - 

This looks like: `<a target="_blank" href="{{ url('categories/'.$entry->slug) }}" class="btn btn-xs btn-default"><i class="fa fa-eye"></i> View</a>`

I now only get categories/ but no entry from the slug field.

I'm using Laravel 5.4, "backpack/base": "^0.7.21", and "backpack/crud": "^3.2".

Is this a bug, or is there a way to send data through to the custom button view?

Thank you

**Comment by lloy0076** [comment]
This is almost certainly one of the bugs fixee in #710.
