### ISSUE TITLE
Slow response/render time when showing many items

### ISSUE THREAD

**Issue by alashow** [Laravel-Backpack/CRUD#1098]
# Bug report

### Backpack, Laravel, PHP, DB version:
3.3.0, 5.5, 7.1.8, 5.7.17

### What I did:
Show/list 15k items.
### What I expected to happen:
Faster response time.
### What happened:
Very slow response time.
### What I've already tried to fix it:

I tried to modify [Search.php](https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/Search.php) and just return column value like this on [getCellView](https://github.com/Laravel-Backpack/CRUD/blob/0be2bae4a58ce417ddd5f8865b1b6e38ee87879d/src/PanelTraits/Search.php#L133):
```php
public function getCellView($column, $entry)
{
        return $entry->{$column['name']};
}
```

**15k** items:
Response time _without_ my edit: **29.92 seconds**
Response time _with_ my edit: **1.69 seconds**

**38426** items:
Response time _with_ my edit: **3.87 seconds**

Clearly, the problem is with template rendering (column views). I have 10 columns, so it renders 150k templates. I believe Laravel already have blade files caching. Don't know why it's that slow.

Is there a way to improve this?

### Records per page

With 3.3.0, there is now an option for showing 'All' items. I think it should be customizable, just like `$crud->getDefaultPageLength()`. I will send a PR soon for it.
Also, maybe we also need a backend validation for page limiting?

**Comment by lloy0076** [comment]
I can't decide if this should be a "bug" or note.

**Comment by diskortsev** [comment]
Revisions may also slow down the response time.

**Comment by alashow** [comment]
@diskortsev It's not enabled in my case.

**Comment by diskortsev** [comment]
In 3.3 the crud table is ajax by default. So it should be rendering PageLength items. Not all the 15k items.
Have you checked query timings?

**Comment by alashow** [comment]
I have modified that limit to show 15k items (it shows all 15k items in one page).
Yes, query timings are okay (**~277ms** for 15k items).

**Comment by alashow** [comment]
It looks like it's Laravel's issue:
**13.249924:**
```php
\PHP_Timer::start();
$data = [];
for ($i = 0; $i <= 150000; $i++){
    array_push($data, view('text', ['data'=>$i])->render());
}

return response()->json([\PHP_Timer::stop()]);
```

**0.017539:**
```php
\PHP_Timer::start();
$data = [];
for ($i = 0; $i <= 150000; $i++){
    array_push($data, $i);
}

return response()->json([\PHP_Timer::stop()]);
```

**Comment by tabacitu** [comment]
@alashow , so if I understand correctly, this is the change you made in ```Search.php:133```?

```diff
+public function getCellView($column, $entry)
+{
+        return $entry->{$column['name']};
+}
-    public function getCellView($column, $entry)
-    {
-        // if column type not set, show as text
-        if (! isset($column['type'])) {
-            return \View::make('crud::columns.text')
-                            ->with('crud', $this)
-                            ->with('column', $column)
-                            ->with('entry', $entry)
-                            ->render();
-        } else {
-            // if the column has been overwritten show that one
-            if (view()->exists('vendor.backpack.crud.columns.'.$column['type'])) {
-                return \View::make('vendor.backpack.crud.columns.'.$column['type'])
-                                ->with('crud', $this)
-                                ->with('column', $column)
-                                ->with('entry', $entry)
-                                ->render();
-            } else {
-                // show the column from the package
-                if (view()->exists('crud::columns.'.$column['type'])) {
-                    return \View::make('crud::columns.'.$column['type'])
-                                    ->with('crud', $this)
-                                    ->with('column', $column)
-                                    ->with('entry', $entry)
-                                    ->render();
-                } else {
-                    return \View::make('crud::columns.text')
-                                    ->with('crud', $this)
-                                    ->with('column', $column)
-                                    ->with('entry', $entry)
-                                    ->render();
-                }
-            }
-        }
-    }
```

If so, I'm afraid this isn't something everybody can use. The whole point of using columns is _using the column blade files_ to customize how the column would look. From what I understand, your change removes this feature, and would not work for relationships.

The way I see it, long response time for showing a table with 10 columns and 15k items on one page isn't actually a bug - I would have expected it to be very slow. I really really don't recommend doing this. In any UI, showing 15k rows of something is overwhelming. What's the user to do with so many rows? He only has two eyes. There are very few use cases I can imagine where this would be a good idea. I would recommend against showing 15k rows.

I would definitely agree to optimizations that speed this up, but since I don't think this is a bug, and I don't think think the solution is feasible, as it removes the entire ```columns``` functionality, I'm going to close this issue.

Please feel free to reopen this if you think I'm wrong - I make mistakes all the time.

Cheers!

**Comment by alashow** [comment]
Hi,

Sorry, I made those changes to find a bottleneck, to find out what makes it slow. I do not plan to show 15k items on one page either. 
Yes, this is not Backpacks issue, [but Laravels](https://github.com/Laravel-Backpack/CRUD/issues/1098#issuecomment-345136493). Any ideas to improve it? It would be a good improvement when showing few rows too. That's why I didn't close the issue just yet.

Cheers!

**Comment by tabacitu** [comment]
Only the suggestion above, unfortunately...
