### ISSUE TITLE
"use Traversable;" missing in CrudTrait.php

### ISSUE THREAD

**Issue by fredrlx** [Laravel-Backpack/CRUD#1105]
While searching for a way to make a "select2_from_array"-type field work through a fakeColumn (saved as json string in our database), I found that there was a use statement missing from CrudTrait to have the "instanceof Traversable" bit of code work as expected in the addFakes method. I had to override the "addFakes" method in my model to make it work.

https://github.com/Laravel-Backpack/CRUD/blob/0be2bae4a58ce417ddd5f8865b1b6e38ee87879d/src/CrudTrait.php#L83

Quite a bit of of code is required at the moment to solve my use case, but I'll be glad to explain if anyone is interested.

**Comment by tabacitu** [comment]
Hi @fredrlx ,

Thank you for taking the time to tell us. This looks like a bug generated by a recent PR. Could you please confirm this would fix it? 

https://github.com/Laravel-Backpack/CRUD/pull/1107

Thanks, cheers!

**Comment by fredrlx** [comment]
Yes just this simple fix was required, either via a use statement or specifying global namespace for Traversable. :+1:
