### ISSUE TITLE
BUG : FakeFields cannot retrieve data back

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#1108]
Hello all,

# Bug report
I create "FakeFields". When I save, everything looks good in database, but there is no data that appears in the "update" view.

### What I did:

For the test and not to pollute my current installation, I created a new backpack installation and I added a quick template and PageManager (which comes with basic FakeFields). And I see the same problem.

PageManager users seem to have the same problem.

https://github.com/Laravel-Backpack/PageManager/issues/56

### Backpack, Laravel, PHP, DB version:
```
       "php": ">=7.0.0",
        "backpack/base": "^0.8.2",
        "backpack/crud": "^3.3",
        "backpack/pagemanager": "^1.1",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
```

Thank you for your help !

**Comment by Jimmylet** [comment]
I resolve this bug with https://github.com/Laravel-Backpack/CRUD/pull/1109

**Comment by tabacitu** [comment]
Great! Thank you for shouting out. Merging now. Cheers!
