### ISSUE TITLE
Cache hasColumn response in crud->addColumn

### ISSUE THREAD

**Issue by diskortsev** [Laravel-Backpack/CRUD#1118]
# Proposal
In CRUD method addColumn does not cache \Schema::hasColumn response. It should be cached.

### What happened:
In query log I see many repetitive queries like
`select column_name as  column_name from information_schema.columns where table_schema=...`

### Backpack, Laravel, PHP, DB version:
Backpack 3.3.0, L5.5, PHP 7.1

**Comment by lloy0076** [comment]
#923

**Comment by tabacitu** [comment]
Hi @diskortsev ,

We've introduced some sort of caching for ```hasColumn()```  in an update, a while back. It is now:
```php
    protected function hasColumn($table, $name)
    {
        static $cache = [];

        if (isset($cache[$table])) {
            $columns = $cache[$table];
        } else {
            $columns = $cache[$table] = $this->getSchema()->getColumnListing($table);
        }

        return in_array($name, $columns);
    }
```

So it will make a query to see if it has the columns, but only once.
Hope this is what you were looking for.

Thanks, cheers!

**Comment by diskortsev** [comment]
@tabacitu, thank you! The code is what I expected. 
Will update my installation later and check it.
