### ISSUE TITLE
Audit users CRUD

### ISSUE THREAD

**Issue by guillermohaad** [Laravel-Backpack/CRUD#112]
It would be great if you could CRUD also record the user ID to interact with the process Create / Update / Deleted. I mean an audit.

This is brief explanation:

![image](https://cloud.githubusercontent.com/assets/12921805/18608465/a0c01f52-7caf-11e6-9c37-4e4b996a90e1.png)

**Comment by tabacitu** [comment]
Hi @guillermohaad ,

Sorry - still don't understand. What would the user see and be able to do?

**Comment by OwenMelbz** [comment]
I'm assuming this would be a list-like or similar to the log page, where it simply shows the actions of users, so if somebody says "why has url X changed" they can see the log to see which user did it. 

I Guess how WP Security Audit does it is simple enough

![WP Security Audit](https://ps.w.org/wp-security-audit-log/assets/screenshot-1.png?rev=1428047)

**Comment by guillermohaad** [comment]
Hi friend @OwenMelbz , Thank you
you are right, just what you samples used the image is what I need.

**Comment by tabacitu** [comment]
Yup, it's not only on the books, it's almost ready. About it:
- it's called Revisions
- @se1exin has built it from scratch and has already submitted a pull request
- I've tried it and it works perfectly
- I only need to check it a few more times before I merge it. 

I expect tomorrow it will be in the stable release of Backpack/CRUD.

Check out [this issue](https://github.com/Laravel-Backpack/CRUD/issues/100#issuecomment-245556850) to see how it looks. I'll close this issue, reply there if you have any comments.

Cheers!

**Comment by guillermohaad** [comment]
Thank you @tabacitu , I will review the issue
