### ISSUE TITLE
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111 "Connection refused")

### ISSUE THREAD

**Issue by joaco1826** [Laravel-Backpack/CRUD#1125]
Help!
It only happens when I save a product.

Thanks for your support

**Comment by lloy0076** [comment]
The MySQL server is configured to listen on a local Unix socket but it's not listening; I'm not seeing this happen all over the place so I suspect it is most likely something to do with the configuration you're using **and** it sounds more like a generic Laravel problem than Backpack one.

**Comment by joaco1826** [comment]
If it's a mysql configuration issue, it should be in all the files, but it only happens when I want to save, view, delete and edit without problems

**Comment by lloy0076** [comment]
It would help, of course, if we knew the minimum of what backpack version you have installed, which Laravel version and so forth...and what database type you think it should be using.

**Comment by joaco1826** [comment]
"require": {
    "php": ">=5.6.4",
    "backpack/base": "^0.7.23",
    "backpack/crud": "^3.2",
    "doctrine/dbal": "^2.6",
    "laravel/framework": "5.4.*",
    "laravel/tinker": "~1.0"
  },

Thanks!

**Comment by tabacitu** [comment]
Hi @joaco1826 ,

It sounds like a Laravel misconfiguration too me too, not a Backpack-related problem, so I'm going to have to close this. 

In case you're using the latest MacOS & MAMP, this is something I've had to do to force Laravel to use the right socket:
```
DB_CONNECTION=mysql
DB_HOST=localhost;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock
DB_PORT=3306
DB_DATABASE=backpack_demo2
DB_USERNAME=root
DB_PASSWORD=root
```

Maybe it helps. But again, does not sound like a Backpack bug.

Cheers!

**Comment by joaco1826** [comment]
It was not a socket issue. the problem was that the database field updated_at was not by default current_timestamp.

Thanks for the help
