### ISSUE TITLE
CrudTrait PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Darival** [Laravel-Backpack/CRUD#1126]
# Bug report
hi everyone =3
### What I did:
install php7.2

### What I expected to happen:
count(null): 0
### What happened:
count(null): Parameter must be an array or an object that implements Countable

at count(null)in CrudTrait.php (line 83)

### What I've already tried to fix it:
workaround by downgrading to php7.1
### Backpack, Laravel, PHP, DB version:
backpack/crud                         3.2.22
laravel/framework                     v5.4.36
PHP 7.2
mysql  5.7.20

**Comment by Darival** [comment]
"backpack/crud": "^3.2"
upgrading to 
"backpack/crud": "^3.3"
fixed my issue

**Comment by tabacitu** [comment]
Hi @Darival  - thanks for sharing the solution!

**Comment by obrunsmann** [comment]
Thanks @Darival same issue to me. `backpack/crud` upgrade solves for me as well 👍

**Comment by Hemantkumawat** [comment]
I Still have This Issue..
