### ISSUE TITLE
How to access the data in the view list and make the display conditions

### ISSUE THREAD

**Issue by KnokDigi** [Laravel-Backpack/CRUD#1127]
I would like to hide buttons in laravel-backpack (in list view) only if a certain condition is true.
This condition, I would like to do with a data one of my items.
For example, if the status of the article is "Published", remove the edit button.
But I can't access this data in my ItemCrudController.

What I would like to do:

```php
public function setup()
{
  if(myData == 'published'){
    $this->crud->removeAllButtons();
  }
}
```
Do you have an idea of how? Thanks guys!

**Comment by AurelDragut** [comment]
I don't think you can do that in the setup() or any other method, the only way would be adding the condition in the button view content, or maybe create a custom button_stack view.

**Comment by lloy0076** [comment]
This seems to be an often enough asked request, though; I wonder if we should think of a more generic way to allow this.

**Comment by KnokDigi** [comment]
I resolve this problem with a custom button ! Thanks guys!

**Comment by tabacitu** [comment]
@lloy0076 it does seem to appear lately. Maybe it's a bit confusing that you can't do the conditionals in the setup() method now... Hmm... don't see a solution right now, but I'll think about it.
