### ISSUE TITLE
Malformed JSON in "table" field when casting

### ISSUE THREAD

**Issue by gavinhewitt** [Laravel-Backpack/CRUD#1130]
The issue was closed in #259 but it seems this has not been resolved yet. Fake fields are not working on my end and I'm pretty sure I followed all steps in the docs. The data is being (wrongly) encoded, but is also not showing up in my forms after save.

In the DB: `"{\"url\":\"http:\\\/\\\/some.url\"}"` (including the outside double quotes!)

Also I'm not sure why casting to array is necessary since the second parameter of json_decode (used in CrudTrait.php to decode the JSON in the extras field) can be utilized to return an array?

### Backpack, Laravel, PHP, DB version:
BP 3.3.1, Laravel 5.5, PHP 7.1, MySQL 5.7.19

**Comment by gavinhewitt** [comment]
**Update:**

fake fields work correctly for me when I ditch the casting to array and set the second parameter of json_decode to true (return as assoc array)

```
// vendor/backpack/crud/src/CrudTrait.php

public function addFakes($columns = ['extras'])
    {
        foreach ($columns as $key => $column) {
            $column_contents = $this->{$column};

            if (! is_object($this->{$column})) {
                $column_contents = json_decode($this->{$column}, true); // TRUE here
            }

            if ((is_array($column_contents) || $column_contents instanceof Traversable) && count($column_contents)) {
                foreach ($column_contents as $fake_field_name => $fake_field_value) {
                    $this->setAttribute($fake_field_name, $fake_field_value);
                }
            }
        }
    }
```

**Comment by lloy0076** [comment]
So, the long and the short of this, @gavinhewitt, is that without a change to `CrudTrait` (or providing a similar but different implementation), it's still broken for you?

**Comment by gavinhewitt** [comment]
Precisely @lloy0076

**Comment by gavinhewitt** [comment]
Related #478

**Comment by OliverZiegler** [comment]
See also PR #1116 which seems to be related

**Comment by tabacitu** [comment]
I just tested PR #1116 for hours and hours, and I can confirm it fixes this issue. Will merge it soon, so let's close the issue.
