### ISSUE TITLE
Column select will not work properly

### ISSUE THREAD

**Issue by KnokDigi** [Laravel-Backpack/CRUD#1131]
Hello all,

# Bug report

I'm trying to display the user's name in a column. To do this, I use the "select" type. But each time I have an AJAX error 'DataTables warning: table id= CrudTable - Ajax error'. However, I took the same values as for another select (but a field).

### What I did:

```php
    $this->crud->addColumns([
      [
        'name'  => 'title',
        'label' => 'Nom'
      ],
      [
        'name'  => 'status',
        'label' => 'Statut'
      ],
      [
        'label' => 'Auditeur', // Table column heading
        'type' => 'select',
        'name' => 'user_id', // the column that contains the ID of that connected entity;
        'entity' => 'user', // the method that defines the relationship in your Model
        'attribute' => 'name', // foreign key attribute that is shown to user
        'model' => 'App\Models\Circuit', // foreign key model
      ]
    ]);
```

My method user() in my model 
```php
  public function user()
  {
    return $this->belongsTo('User', 'user_id');
  }
```

### What I expected to happen:

I need to display the name of the linked user (in the user_id column, there is only his ID ID)

### What happened:

There was an AJAX error, as explained above.

### Backpack, Laravel, PHP, DB version:

```json
 "backpack/base": "^0.8.2",
        "backpack/crud": "^3.3",
        "laravel/framework": "5.5.*",
       php7
```

**Comment by tabacitu** [comment]
Hi @KnokDigi ,

Looks to me like a misconfigure select column. If you're connecting to the USER, your model on that column should be ```App\Models\Circuit```. Or erase it completely, Backpack\CRUD 3.3 should be able to pick it up automatically from the relationship in your model.

Hope it helps. CHeers!
