### ISSUE TITLE
Schema call with default db connection, without considering the model's connection

### ISSUE THREAD

**Issue by idanpt** [Laravel-Backpack/CRUD#1136]
# Bug report

in Backpack\CRUD\PanelTraits\Columns trait, addColumn() method.

there is a call to:

`\Schema::hasColumn($this->model->getTable(), $column_with_details['name'])`

you assume that this model uses the default db connection. in my case i have couple of db connections, which is specified in each model itself.

### What happened:
column in table are not sortable

### What I've already tried to fix it:
1 possible solution will be setting the connection of schema by the model's connection like:

`\Schema::setConnection($this->model->getConnection())->hasColumn($this->model->getTable(), $column_with_details['name'])`

### Backpack, Laravel, PHP, DB version:
php7.1
laravel 5.5
backpack/crud 3.3.1

**Comment by lloy0076** [comment]
I can't see why your proposed fix would *not* work but it's not a PR :)

**Comment by idanpt** [comment]
I've also created a PR

**Comment by tabacitu** [comment]
PR #1141 has since been merged. Closing this. Thanks again @idanpt for reporting AND fixing this. Cheers!
