### ISSUE TITLE
Problem with Column select with getRelationModel

### ISSUE THREAD

**Issue by tarmo1979** [Laravel-Backpack/CRUD#1138]
# Bug report

I am trying to display related model attribute data, but either there's a bug or I have done something wrong. :)

### What I did:

<img width="327" alt="screenshot 2017-11-28 19 41 04" src="https://user-images.githubusercontent.com/5405691/33334877-19244b68-d474-11e7-9239-7a30e701b58d.png">

### What I expected to happen:

wanted to display related model object attribute value

### What happened:

nothing was displayed

### What I've already tried to fix it:

Made temporary new custom column type
and this way data was displayed when original     if ($entry->{$column['entity']}) { failed

<img width="560" alt="screenshot 2017-11-28 19 40 14" src="https://user-images.githubusercontent.com/5405691/33334847-00cea888-d474-11e7-8cf5-20b53358f04f.png">

### Backpack, Laravel, PHP, DB version:
`
"backpack/base": "^0.8.2",
        "backpack/crud": "^3.3",
"laravel/framework": "5.5.*",

php 7
`

**Comment by MilitaruC** [comment]
@tarmo1979 if you have model relations ready. I used this way:

`$this->crud->addColumn([// n-n relationship (with pivot table)
           'label' => "Types", // Table column heading
           'type' => "select_multiple",
           'name' => 'types', // the method that defines the relationship in your Model
           'entity' => 'types', // the method that defines the relationship in your Model
           'attribute' => "name", // foreign key attribute that is shown to user
           'model' => "App\Models\EventTypes", // foreign key model
        ]);`
It is a `'model' => "App\Models\EventTypes"` there and you can add `'pivot' => true`
Also you can use model functions:
`$this->crud->addColumn([// run a function on the CRUD model and show its return value
           'name' => "count",
           'label' => "Users", // Table column heading
           'type' => "model_function",
           'function_name' => 'countEventUsers', // the method in your Model
        ]);`
