### ISSUE TITLE
elfinder image URL not absolute path, some token based path

### ISSUE THREAD

**Issue by packytagliaferro** [Laravel-Backpack/CRUD#1140]
# Bug report

### What I did:

Clicked on WYSIWIG to add image in text

### What I expected to happen:

Add image with correct url to the image (https://acoolsite.nyc3.digitaloceanspaces.com/posts/10578_432266693547706_1658074314_n.jpg)

### What happened:

Get some funky url that will only work if user is signed in. It needs to be the absolute path to the image. (http://acoolsite.dev/admin/elfinder/connector?_token=uTw17WEtWI4oZM8fvAHK6riPs8mwIEquK0zt1Kzd&cmd=file&target=fls2_cG9zdHMvMTI3MTEzMDhfMTAxNTI5NjM2NTI3ODI4MjRfNjcxMTM1ODEzMjMzMTIzNjExOF9vLmpwZw)

### What I've already tried to fix it:

Config the elFinder and ask on StackOverflow

### Backpack, Laravel, PHP, DB version:

Laravel 5.5 | Backpack ^3.2

**Comment by packytagliaferro** [comment]
To fix this I had to add a URL to my disk in Elfinder.php

```
'disks' => [
        'spaces' => [
            'URL' => url('https://mydomain.nyc3.digitaloceanspaces.com'),
        ],
    ],
```

**Comment by lloy0076** [comment]
The above appears to be a valid solution; closing.
