### ISSUE TITLE
[FEATURE REQ] Summer Note elFinder option

### ISSUE THREAD

**Issue by packytagliaferro** [Laravel-Backpack/CRUD#1142]
# Bug report

### What I did:

Changed field to Summernote. Clicked on "image" to input inline image. It let me select the image but using only the standard file upload, not elFinder. 

### What I expected to happen:

Be similar to tinymce or wysiwyg field option where you click the image icon to add an image and it lets me browse my Digital Ocean Spaces for images or upload new one. 

### What happened:

It embeds a data:image/png local file. 

### Backpack, Laravel, PHP, DB version:

Laravel 5.5 | Backpack ^3.2

**Comment by tabacitu** [comment]
I agree this could be an option. This could help us out: https://github.com/semplon/summernote-ext-elfinder

**Comment by lloy0076** [comment]
If there is a PR, please reopen.
