### ISSUE TITLE
Add button on stack throw error

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#1145]
# Bug report

### What I did:
I've followed the doc:
https://laravel-backpack.readme.io/v3.0/docs/crud-buttons#section-example-model_function-usage

I did exactly what the doc mentioned by copy/paste.

### What I expected to happen:
To see a new button appear.

### What happened:
But then I got error: ErrorException: Undefined variable: entry

### What I've already tried to fix it:
Nothing yet as this is core from Backpack. But it seems to have issue here:
![2017-12-06 002396](https://user-images.githubusercontent.com/26375917/33660533-b2f3822a-dab6-11e7-8950-3a697d9951e0.png)

### Backpack, Laravel, PHP, DB version:
Backpack 3.2.27
Laravel 5.4.36
PHP 7.1.9
DB MySQL 5.7.19

**Comment by tabacitu** [comment]
Hi @MickaelTH ,

Where did you add that button? In what stack? Can you please copy-paste your addButton declaration?

**I've seen this error before, when people used the ```$entry``` variable in their button, but they placed the button in the  ```top``` or ```bottom``` stacks.** If this is the case here too, you can't use an ```$entry``` variable in the top or bottom stacks, those stacks are not entry-related. Only ```line``` is. The ```top``` and ```bottom``` stacks are mostly used for bulk actions, or opening different forms, stuff like that. So eliminating the ```$entry``` from your button's code should fix it.

Cheers!

**Comment by tabacitu** [comment]
PS. Closing this as I\m pretty sure that's it. Of course, please reopen it if I'm wrong. Not your first tango :-)
