### ISSUE TITLE
Bug on $this->crud->getEntry(id)

### ISSUE THREAD

**Issue by swingywc** [Laravel-Backpack/CRUD#1147]
# Bug report

### What I did:
I try to get the entry of a table with specific id (9) using :  

    $extract_entry = $this->crud->getEntry(9);
    dd($extract_entry);

### What I expected to happen:
It should give me the entry which it's id should be 9.

### What happened:
It give me the first entry of the table.

### What I've already tried to fix it:
I try out two lines of code together:  

    $old_entry = $this->crud->getEntries()->where('id', 9)->first();
    $old_two_entry = $this->crud->getEntry(9);
    dd($old_entry, $old_two_entry);

The first line give me the correct entry while second line give me the wrong entry.

### Backpack, Laravel, PHP, DB version:
PHP                      -> 7.1.7
Laravel                 -> 5.5.* 
Backpack/Base   -> ^.0.8.2 
Backpack/CRUD -> ^3.3 
mysql server       -> 5.7.20 homebrew

Appreciate for any suggestion and fix.

**Comment by tabacitu** [comment]
Hi @swingywc - this is weird, just double-checked the unit test, plus tested it manually and it works fine for me. Check out my video here please: https://cl.ly/2P3D07012P0Y As you can see, both options seem to work fine for me. 

Are you sure it's not something else you did in ```setup()``` or other methods? Other ```where``` or other conditionals you've placed on the query, that might affect your result? Or maybe in your Model, some global scopes or something?

Cheers!

PS. Closing this as I\m pretty sure there's no bug here. Please reopen if you think I\m wrong, and it's not just inside your app.

**Comment by seedgabo** [comment]
i getting the same error only when updated the model

**Comment by tabacitu** [comment]
@seedgabo can you please copy-paste your controller?

**Comment by seedgabo** [comment]
sure 
`<?php

namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\EventRequest as StoreRequest;
use App\Http\Requests\EventRequest as UpdateRequest;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Auth;

class EventCrudController extends CrudController
{

    public function setUp()
    {

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('\App\Models\Event');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/events');
        $this->crud->setEntityNameStrings(trans('literals.event'), trans('literals.events'));
        $this->permissions('events');
        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */

        $this->crud->setFromDb();
        $this->crud->removeColumns(['price','limit_user', 'privacity','description','group_id','vibility','color','url','reservation_id','notified_at','reminded_at']);
        $this->crud->removeFields(['reservation_id','notified_at','reminded_at']);

        $this->crud->setColumnDetails('title', [
            'name' => 'title',
            'label' => trans('literals.title'),
            'type' => 'text',
        ]);

        $this->crud->setColumnDetails('description', [
            'name' => 'description',
            'label' => trans('literals.description'),
            'type' => 'text',
        ]);
        $this->crud->setColumnDetails('allDay', [
            'name' => 'allDay',
            'label' => trans('literals.all_day'),
            'type' => 'check',
            'hint' => trans('set to true to indicate this event duration is all day')
        ]);
        $this->crud->setColumnDetails('start', [
            'name' => 'start',
            'label' => trans('literals.start_date'),
            'type' => 'datetime',
        ]);
        $this->crud->setColumnDetails('end', [
            'name' => 'end',
            'label' => trans('literals.end_date'),
            'type' => 'datetime',
        ]);
        $this->crud->setColumnDetails('type', [
            'name' => 'type',
            'label' => trans('literals.type'),
            'type' => 'literals',
        ]);
        $this->crud->setColumnDetails('privacity', [
            'name' => 'privacity',
            'label' => trans('literals.privacity'),
            'type' => 'literals',
        ]);
        $this->crud->setColumnDetails('visibility', [
            'name' => 'visibility',
            'label' => trans('literals.visibility'),
            'type' => 'literals',
        ]);
        $this->crud->setColumnDetails('creator_id', [
            'label' => trans('literals.creator'),
            'type' => 'select',
            'name' => 'creator_id',
            'entity' => 'creator',
            'attribute' => 'name',
            'model' => 'App\User'
        ]);
        $this->crud->setColumnDetails('residence_id', [
            'label' => trans('literals.residence'),
            'type' => 'select',
            'name' => 'residence_id',
            'entity' => 'residence',
            'attribute' => 'name',
            'model' => 'App\Models\Residence'
        ]);

        $this->crud->addColumn([
            'label' => trans('literals.zones'), // Table column heading
            'type' => "select_multiple",
            'name' => 'zonez', // the method that defines the relationship in your Model
            'entity' => 'zones', // the method that defines the relationship in your Model
            'attribute' => "name", // foreign key attribute that is shown to user
            'model' => "App\Models\Zone", // foreign key model
        ]);

        if (config('modules.reservations')) {
            $this->crud->setColumnDetails('reservable', [
                'name' => 'reservable',
                'label' => trans('literals.reservable'),
                'type' => 'check',
            ]);
            $this->crud->setColumnDetails('available_for_defaulter', [
                'name' => 'available_for_defaulter',
                'label' => trans('literals.available_for_defaulter'),
                'type' => 'check',
            ]);
        }

		if(!Input::has('order')){
        	$this->crud->orderBy('created_at','desc');
		}

        $this->crud->addField([
            // 'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'title',
            'label' => trans('literals.title'),
            'type'  => 'text',
            'attributes' => ['required' => 'required'],
            'tab' => trans('literals.event'),
        ]);
        $this->crud->addField([
            // 'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'description',
            'label' => trans('literals.description'),
            'type'  => 'textarea',
            'attributes' => [],
            'tab' => trans('literals.event'),
        ]);
        $this->crud->addField([
            // 'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'allDay',
            'label' => trans('literals.all_day'),
            'type'  => 'checkbox',
            'attributes' => [],
            'tab' => trans('literals.event'),
        ]);
        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'start',
            'label' => trans('literals.start_date'),
            'type'  => 'datetime',
            'attributes' => ['required' => 'required'],
            'default' => 'now',
            'tab' => trans('literals.event'),
        ]);

        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'end',
            'label' => trans('literals.end_date'),
            'type'  => 'datetime',
            'attributes' => ['required' => 'required'],
            'default' => 'now + 1Day',
            'tab' => trans('literals.event'),
        ]);

        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'url',
            'label' => trans('literals.url'),
            'type'  => 'url',
            'attributes' => [],
            'tab' => trans('literals.aditional'),
        ]);

        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'type',
            'label' => trans('literals.type'),
            'type'  => 'select_from_array',
            'attributes' => ['required' => 'required'],
            'tab' => trans('literals.event'),
            'options' => \App\Models\Event::types
        ]);
        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'privacity',
            'label' => trans('literals.privacity'),
            'type'  => 'select_from_array',
            'attributes' => ['required' => 'required'],
            'tab' => trans('literals.event'),
            'options' => \App\Models\Event::privacies,
            'hint' => trans('Indicate all the others neighbors if your event is public or not')
        ]);
        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'visibility',
            'label' => trans('literals.visibility'),
            'type'  => 'select_from_array',
            'attributes' => ['required' => 'required'],
            'tab' => trans('literals.event'),
            'options' => \App\Models\Event::visibilities,
            'hint' => trans('If the event show on the public calendar')
        ]);

        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'name'  => 'color',
            'label' => trans('literals.color'),
            'type'  => 'color',
            'default' => '#0052ff',
            'attributes' => [],
            'tab' => trans('literals.aditional'),
            'hint' => 'color of the event on the  calendar'
        ]);
        
        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'label' => trans('literals.creator'),
            'type' => 'select2',
            'name' => 'creator_id',
            'attribute' => 'name',
            'model' => "\App\User",
            'tab' => trans('literals.event')
        ]);

        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'label' => trans('literals.residence'),
            'type' => 'select2',
            'name' => 'residence_id',
            'attribute' => 'name',
            'model' => "\App\Models\Residence",
            'tab' => trans('literals.event')
        ]);
        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],
            'label' => trans('literals.group'),
            'type' => 'select2',
            'name' => 'group_id',
            'attribute' => 'name',
            'model' => "\App\Models\Zone",
            'hint' => 'only for privacity/visibility group',
            'tab' => trans('literals.additional')
        ]);
        
        if (config('modules.reservations')) {
            $this->crud->addField([
                'wrapperAttributes' => ['class' => ' form-group col-md-6'],
                'name'  => 'reservable',
                'label' => trans('literals.reservable'),
                'type'  => 'checkbox',
                'attributes' => [],
                'tab' => trans('literals.reservations'),
            ]);
            $this->crud->addField([
                'wrapperAttributes' => ['class' => ' form-group col-md-6'],
                'name'  => 'limit_user',
                'label' => trans('literals.limit user'),
                'type'  => 'number',
                'tab' => trans('literals.reservations'),
                'hint'=> __('0 para ilimitados')
            ]);

            $this->crud->addField([
                'wrapperAttributes' => ['class' => ' form-group col-md-6'],
                'name'  => 'available_for_defaulter',
                'label' => trans('literals.available_for_defaulter'),
                'type'  => 'checkbox',
                'default' => '1',
                'tab' => trans('literals.reservations'),
            ]);

            $this->crud->addField([
                'wrapperAttributes' => ['class' => ' form-group col-md-6'],
                'name'  => 'price',
                'label' => trans('literals.price'),
                'type'  => 'number',
                'default' => '0',
                'attributes' => ['min'=>0],
                'tab' => trans('literals.reservations'),
            ]);
        }

        $this->crud->addField([
            'wrapperAttributes' => ['class' => ' form-group col-md-6'],       // Select2Multiple = n-n relationship (with pivot table)
            'label' => trans('literals.zones'),
            'type' => 'select2_multiple',
            'name' => 'zones', // the method that defines the relationship in your Model
            'entity' => 'zones', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Zone", // foreign key model
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
            'tab' => trans('literals.aditional'),
            'hint' => trans('reserved zones'),
        ]);

        // ------ REVISIONS
        // You also need to use \Venturecraft\Revisionable\RevisionableTrait;
        // Please check out: https://laravel-backpack.readme.io/docs/crud#revisions
        $this->crud->allowAccess('revisions');

        // ------ AJAX TABLE VIEW
        // Please note the drawbacks of this though:
        // - 1-n and n-n columns are not searchable
        // - date and datetime columns won't be sortable anymore
        $this->crud->enableAjaxTable();

        // ------ DATATABLE EXPORT BUTTONS
        // Show export to PDF, CSV, XLS and Print buttons on the table view.
        // Does not work well with AJAX datatables.
        $this->crud->enableExportButtons();
    }

    public function store(StoreRequest $request)
    {
        $this->crud->hasAccessOrFail('create');

        // fallback to global request instance
        if (is_null($request)) {
            $request = \Request::instance();
        }

        // replace empty values with NULL, so that it will work with MySQL strict mode on
        foreach ($request->input() as $key => $value) {
            if (empty($value) && $value !== '0') {
                $request->request->set($key, null);
            }
        }

        // insert item in the db
        $item = $this->crud->create($request->except(['save_action', '_token', '_method']));
        $this->data['entry'] = $this->crud->entry = $item;

        // show a success message
        \Alert::success(trans('backpack::crud.insert_success'))->flash();

        // save the redirect choice for next time
        $this->setSaveAction();
        return $this->performSaveAction($item->id);
        return $redirect_location;
    }

    public function update(UpdateRequest $request,$id)
    {
        $this->crud->hasAccessOrFail('update');

        // fallback to global request instance
        if (is_null($request)) {
            $request = \Request::instance();
        }

        // replace empty values with NULL, so that it will work with MySQL strict mode on
        foreach ($request->input() as $key => $value) {
            if (empty($value) && $value !== '0') {
                $request->request->set($key, null);
            }
        }
        // update the row in the db
        $item =  \App\Models\Event::findorFail($id);
	    $item->update($request->except('save_action','_token','_method'));
        $this->data['entry'] = $this->crud->entry = $item;
        // show a success message
        \Alert::success(trans('backpack::crud.update_success'))->flash();

        // save the redirect choice for next time
        $this->setSaveAction();
        return $this->performSaveAction($item);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }
    public function permissions($model)
    {
        $user = Auth::user();
        if ($user->hasRole('SuperAdmin') or $user->hasRole('Manage '. $model)) {
            return ;
        }
        if (!$user->can('add '. $model)) {
            $this->crud->denyAccess(['create']);
        }
        if (!$user->can('update '. $model)) {
            $this->crud->denyAccess(['update']);
        }
        if (!$user->can('delete '. $model)) {
            $this->crud->denyAccess(['delete']);
        }
    }
}`

**Comment by tabacitu** [comment]
@seedgabo I don't see ```getEntry``` anywhere in your controller, so I don't see how you can have the same problem as above...
