### ISSUE TITLE
Problem with saving checkboxes

### ISSUE THREAD

**Issue by timdiels1** [Laravel-Backpack/CRUD#115]
### Bug Description
In Laravel v 5.3 saving an item with a checkbox fails when leaving the checkbox empty because the database column does not allow nullable values.

### Fix
On the storeCRUD and updateCRUD in the CrudController we need to change the code that is changing empty (also '0' string) to null.

So we need to go from:

```
if (empty($value)) {
    $request->request->set($key, null);
}
```

to

```
if (empty($value) && $value !== '0') {
    $request->request->set($key, null);
}
```

Note: I have tested this only on MySQL, and not on other databases, but I don't think this should cause issues.

**Comment by tabacitu** [comment]
You're totally right, @timdiels1 

Thanks for the fix, I've implemented it.

Cheers to you! Keep 'em coming!
