### ISSUE TITLE
How should I be using the messages() method in EntityRequest?

### ISSUE THREAD

**Issue by tedsecretsource** [Laravel-Backpack/CRUD#1151]
Adding a custom message on failed validation seems to fail with the default message being displayed.

In the EntityRequest class (e.g.: MemberProfileRequest), in the `messages` method, the failing field has been defined with a custom message, e.g.: 

```
return [
    'dimensions' => 'The profile picture must be at least 400px wide.'
]
```

In the `rules` method I have:

```
return [
    'profile_pic' => 'dimensions:min_width=400,min_height=400'
]
```

The rule doesn't work. Images are always failing validation regardless of their size.

What am I doing wrong?

Thanks in advance.

Ted Stresen-Reuter

**Comment by tedsecretsource** [comment]
I think I figured it out. The predefined image type (and the base64 image type) upload the image base64 encoded. Since validation happens in the controller, and the data is an encoded string (rather than an actual file), the dimensions test fails ([Validator.php:359](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Validation/Validator.php#L359)).

Before I make a request or try to implement my own solution in vain, can you clarify why images are uploaded as base64 and if it is possible to disable that behavior? I realize I can create my own custom validation in the controller, but I'm hoping for a shortcut on this.

Thanks!

Ted Stresen-Reuter

**Comment by lloy0076** [comment]
Whilst I'm not entirely certain, I think that this:

* https://github.com/fengyuanchen/cropper

...which is used to crop the images makes it into base64; I could be wrong.

**Comment by froid24** [comment]
Any clear answer on how to use the messages() method in CRUD request classes? 

I've set a message for 'required', but I want it to **include the field label that was used in the controller** (since that is what the user sees in the form, and that is what he should be referred to), and not the field name in the database.

I didn't find any clear example or tutorial on this.

**Comment by lloy0076** [comment]
@froid24 You'd need to override the CRUD update itself - it's not easy atm.

This isn't really a bug - it could be a feature request but it's not that without a PR either.

Closing.

**Comment by tabacitu** [comment]
@froid24 Backpack uses simple [Laravel Form Requests](https://laravel.com/docs/5.5/validation#creating-form-requests). Nothing changed there. So anything you can do with a form request, you can do with a crud form request.  You just be able to customize the error messages with the [standard procedure here](https://laravel.com/docs/5.5/validation#customizing-the-error-messages). Hope it helps. Cheers!
