### ISSUE TITLE
Class 'CRUD' not found

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/CRUD#1161]
# Bug report

### What I did:
`composer update`

### What I expected to happen:
Update all dependencies, and everything should continue to work.

### What happened:
![image](https://user-images.githubusercontent.com/1476365/33990569-1907c5b2-e0d4-11e7-9b2f-c25a12d88744.png)
![image](https://user-images.githubusercontent.com/1476365/33990671-7389d66a-e0d4-11e7-8870-bb2b67a03366.png)

### What I've already tried to fix it:
Comment the line out manually, and it solves the problem but still auto optimize.

### Backpack, Laravel, PHP, DB version:
Latest backpack, L5.5, PHP 7.1, MariaDB 10.2

**Comment by cristianuibar** [comment]
Also when updating on remote production server (DO using Forge)
![image](https://user-images.githubusercontent.com/1476365/33990943-69bf6ed2-e0d5-11e7-99a7-89f9f0a520ed.png)
with same error at the end as on local. Class 'CRUD' not found.

Can there be some kind of dependency incompatibility?

**Comment by kiddtang** [comment]
@cristianuibar you can refer the issue for temporary fix...
https://github.com/Laravel-Backpack/Settings/issues/64

**Comment by tabacitu** [comment]
Thanks @cristianuibar and @kiddtang - just merged the PR in Settings that fixes this, so a ```composer update``` should do it for you guys.

Please reopen the issue if you're still having this problem.

Cheers!
