### ISSUE TITLE
addColumns() displays column parameters as labels in list view

### ISSUE THREAD

**Issue by tedsecretsource** [Laravel-Backpack/CRUD#1162]
# Bug report

### What I did:
in EntityCrudController I added the following:

```php
$this->crud->addColumns(
    [
        'label' => "First",
        'name' => 'member_profile_id',
        'entity' => 'memberProfile',
        'attribute' => 'first_name',
        'model' => 'App\Models\MemberProfile',
        'type' => 'select'
    ],
    [
        'label' => 'Last',
        'name' => 'member_profile_id',
        'entity' => 'memberProfile',
        'attribute' => 'last_name',
        'key' => 'last_name',
        'model' => 'App\Models\MemberProfile',
        'type' => 'select'
    ]
);
```

### What I expected to happen:
The list view would have two columns with the labels "First" and "Last"

### What happened:
Each item in each column array was used as a column heading (label - see attached).
![image](https://user-images.githubusercontent.com/28703641/34133440-8facbb3e-e44c-11e7-83f7-971b07a2be46.png)

### What I've already tried to fix it:
Embedding column arrays in a single array, e.g.: [['name' => 'first_name'…],['name' => 'last_name'…]]

Listing column definitions as associative arrays (**which worked**, FAICT), e.g.:
```php
$this->crud->addColumns([
    'member_profile_id' => [
        'label' => 'First',
        'entity' => 'memberProfile',
        …
    ],
    'last_name' => [
        'label' => 'Last',
        'entity' => 'memberProfile',
        …
    ]
]);
```

### Backpack, Laravel, PHP, DB version:
Backpack: (most recent, not sure where to find the version number)
Laravel: 5.5
PHP: 7.1.5

I think this bug report might be a red herring and the issue is really a minor lack of API documentation for addColumns. Here's an example you might consider adding near the top of the [Column Types page](https://laravel-backpack.readme.io/docs/crud-columns-types):

### Adding columns to your list display

Columns can be added individually by passing an associative array to addColumn or an associative array of associative arrays to addColumns (with an **s**). Here is an example of adding a single column (use these in your EntityCrudController):

```php
$this->crud->addColumn([
  'name' => 'email',
  'label' => 'Preferred Email Address',
  'type' => 'email'
]);
```

Here is an example of adding multiple columns in a single addColumns call:

```php
$this->crud->addColumns([
  'full_name' => [
    'label' => 'First and Last Names'
  ],
  'email' => [
    'label' => 'Preferred Email Address',
    'type' => 'email'
  ]
]);
```
----
I sure hope this helps someone else in my spot. This is an add-on to a thread started in case #1113.

**Comment by tabacitu** [comment]
Damn... Thanks @tedsecretsource . Red herring indeed, but it's an annoying one :-) Still can't manage to replicate it though. I tried ```addColumns()``` in a bunch of ways, they all work for me:

This works:
```php
        $this->crud->addColumns([
            'textarea',
            [
               // run a function on the CRUD model and show its return value
               'name' => "getTextAndEmailAttribute",
               'label' => "Text and Email", // Table column heading
               'type' => "model_function",
               'function_name' => 'getTextAndEmailAttribute', // the method in your Model
               'searchLogic' => function ($query, $column, $searchTerm) {
                    $query->orWhere('email', 'like', '%'.$searchTerm.'%');
                    $query->orWhere('text', 'like', '%'.$searchTerm.'%');
                }
            ]
        ]);
```


This works too:
```php
        $this->crud->addColumns([
            'textarea' => 'textarea',
            'getTextAndEmailAttribute' => [
               // run a function on the CRUD model and show its return value
               'name' => "getTextAndEmailAttribute",
               'label' => "Text and Email", // Table column heading
               'type' => "model_function",
               'function_name' => 'getTextAndEmailAttribute', // the method in your Model
               'searchLogic' => function ($query, $column, $searchTerm) {
                    $query->orWhere('email', 'like', '%'.$searchTerm.'%');
                    $query->orWhere('text', 'like', '%'.$searchTerm.'%');
                }
            ]
        ]);
```

**[Q1] Can you please check your Backpack\CRUD version?** It should be the value on top in the changelog you'll find in your ```vendor/backpack/crud/changelog.md```

I dont't remember ever fixing this, but I hope a ```composer update``` fixes it for you. Because the ```addColumns()``` method is a very simple one - I couldn't see where the problem would be:
```php
    /**
     * Add multiple columns at the end of the CRUD object's "columns" array.
     *
     * @param [array of columns]
     */
    public function addColumns($columns)
    {
        if (count($columns)) {
            foreach ($columns as $key => $column) {
                $this->addColumn($column);
            }
        }
    }
```

**[Q2] Have you overwritten the CrudPanel class or its traits in any way?**

Thanks, cheers!

**Comment by tedsecretsource** [comment]
Thanks for taking a look.

CRUD version 3.3.3

I haven't overwritten the CrudPanel (that I'm aware of) nor any of its traits. I am using the debugbar and a few other modules that may be interfering, so, I would suggest closing this unless someone else can confirm this is an issue.

Thanks for looking into it.

**Comment by tabacitu** [comment]
Sure, thanks. 

If you manage to try it without debugbar and find something new one way or the other, please let us know ;-)

Cheers!
