### ISSUE TITLE
[FEATURE REQ] Ability to update fields attributes

### ISSUE THREAD

**Issue by mgralikowski** [Laravel-Backpack/CRUD#1165]
Hi,

setFromDb() is very nice feature but sometimes you need make custom changes.
Would be nice to add something like setColumnDetails() but for adding/overwrite attributes.
For example:
```
$this->crud->setFromDb();
$this->crud->updateField('name', ['type' => 'email]);
```

It could by similar to setFieldLabel() but more flexible.

**Comment by mgralikowski** [comment]
I figure out i can can use:
`$this->crud->create_fields['name']['type'] = 'email';`
but is a little hard to multiple fields and you need use twice (for create and update).

**Comment by tabacitu** [comment]
Hi @mgralikowski ,

Agreed. I think that would be a nice feature too, thanks. Let's leave this open until we get to it.
Glad you found a workaround.

Cheers!

**Comment by lloy0076** [comment]
PS. PRs are always welcome :)

**Comment by tabacitu** [comment]
Great PR from @AbbyJanke for this - #1349 . Let's move the conversation there guys.

Cheers!
