### ISSUE TITLE
Changing column heading text

### ISSUE THREAD

**Issue by PhouvanhKCSV** [Laravel-Backpack/CRUD#117]
I've searching for the solution but could not found any, Could you please help me how can i change column heading text? Like i want to change column "Name" to "Fullname".

<img width="1170" alt="screen shot 2559-09-20 at 11 20 52 am" src="https://cloud.githubusercontent.com/assets/10794184/18657502/f97eb546-7f24-11e6-9655-f0a941a486de.png">

Thanks

**Comment by tabacitu** [comment]
Hi @PhouvanhKCSV ,

In your entity's EntityCrudController, you've [added the columns](https://laravel-backpack.readme.io/docs/crud-columns-types) using ```$this->crud->addColumn()```. Right? Well, if you specify "label" that will be the the column heading.

So:
```php
$this->crud->addColumn([
   'name' => 'name', // The db column name
   'label' => "Fullname", // Table column heading
   'type' => 'text
]);
```

**Comment by PhouvanhKCSV** [comment]
Thank you so much @tabacitu, it work!. Because i am using:

`$this->crud->setFromDb();`

and what i do now is to remove and re-add the columns, it would be better to have some function to modify the label.

**Comment by tabacitu** [comment]
Hi @PhouvanhKCSV ,

Glad it worked for you. ```setFromDb()``` isn't at all a mature/complete functionality - it does display some columns and fields, but it's by no means "smart" right now. It will be in the future, but right now it's usually best to delete ```setFromDb()``` and specify the fields you like manually. At least that's how I prefer it.

Cheers!
