### ISSUE TITLE
Tabbed form with differend table in every tab

### ISSUE THREAD

**Issue by cangak** [Laravel-Backpack/CRUD#1170]
Hallo all
Im new in laravel, but this backpack help me a alot.
And can i use different table in every tab, a little code for explain please..
Thanks so much

**Comment by lloy0076** [comment]
As far as I can tell, this isn't **easily** possible.

**Comment by cangak** [comment]
ok thanks, ill  try to use "native" laravel instead, and btw thanks for the respon
