### ISSUE TITLE
Multiple Select issue and Entity order issue

### ISSUE THREAD

**Issue by gnkevadia** [Laravel-Backpack/CRUD#118]
How Backpack will work with multiple select? I have integrate it will poplate list properly but when try to save it will create issue with array 

Error preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

One more thing regarding entity order by in select entiry with order by custom field? how we can achive it.

Please advise!

**Comment by OwenMelbz** [comment]
hi @gnkevadia would you be able to give an example of your construct to see how you're setting up your fields please?

Thanks

**Comment by gnkevadia** [comment]
Hello @OwenMelbz,

Need to capture multiple author it is generating error. And need to populate name in alphabetical order not based on id.

Table architecture
----------------------------------------------------------

CREATE TABLE `textbooks` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `author_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `publisher_id` int(10) UNSIGNED NOT NULL,
  `icon` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1=Active,0=Inactive',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

I have specified in controller 
----------------------------------------------------------
$this->crud->addField([
				'label' => "Author *",
				'type' => 'select2_multiple',
				'name' => 'author_id', // the db column for the foreign key
				'entity' => 'author', // the method that defines the relationship in your Model
				'attribute' => 'name', // foreign key attribute that is shown to user
				'model' => "App\Models\Author", // foreign key model
				'text' => "- Select -",
		]);

-------------------------------------------------------------
And model Author.php 
-------------------------------------------------------------
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;
use URL;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
	use CrudTrait;
	use SoftDeletes;

     /*
	|--------------------------------------------------------------------------
	| GLOBAL VARIABLES
	|--------------------------------------------------------------------------
	*/

	protected $table = 'authors';
	protected $primaryKey = 'id';
	// public $timestamps = false;
	// protected $guarded = ['id'];
	protected $fillable = ['name','icon','status'];
	// protected $hidden = [];
    // protected $dates = [];

	/*
	|--------------------------------------------------------------------------
	| FUNCTIONS
	|--------------------------------------------------------------------------
	*/
	public function getStatus()
	{
		if($this->status == "1")
			$status = "Active";
		else
			$status = "InActive";
		return $status;
	}
	public function getIcon()
	{
		if(isset($this->icon) && !empty($this->icon))
			return "<img src='".URL::to('\/').$this->icon."' height='25'>";
		return '';
	}

	/*
	|--------------------------------------------------------------------------
	| RELATIONS
	|--------------------------------------------------------------------------
	*/

	/*
	|--------------------------------------------------------------------------
	| SCOPES
	|--------------------------------------------------------------------------
	*/

	/*
	|--------------------------------------------------------------------------
	| ACCESORS
	|--------------------------------------------------------------------------
	*/

	/*
	|--------------------------------------------------------------------------
	| MUTATORS
	|--------------------------------------------------------------------------
	*/
}

Please advise!

Thanks

**Comment by gnkevadia** [comment]
Hello @OwenMelbz,

Need to capture multiple author it is generating error. And need to populate name in alphabetical order not based on id.
Table architecture

CREATE TABLE textbooks (
id int(11) UNSIGNED NOT NULL,
name varchar(255) COLLATE utf8_unicode_ci NOT NULL,
author_id varchar(255) COLLATE utf8_unicode_ci NOT NULL,
publisher_id int(10) UNSIGNED NOT NULL,
icon varchar(255) COLLATE utf8_unicode_ci NOT NULL,
status tinyint(1) NOT NULL DEFAULT '1' COMMENT '1=Active,0=Inactive',
created_at timestamp NULL DEFAULT NULL,
updated_at timestamp NULL DEFAULT NULL,
deleted_at timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
I have specified in controller

$this->crud->addField([
'label' => "Author *",
'type' => 'select2_multiple',
'name' => 'author_id', // the db column for the foreign key
'entity' => 'author', // the method that defines the relationship in your Model
'attribute' => 'name', // foreign key attribute that is shown to user
'model' => "App\Models\Author", // foreign key model
'text' => "- Select -",
]);
And model Author.php

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;
use URL;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
use CrudTrait;
use SoftDeletes;

 /*
|--------------------------------------------------------------------------
| GLOBAL VARIABLES
|--------------------------------------------------------------------------
*/

protected $table = 'authors';
protected $primaryKey = 'id';
// public $timestamps = false;
// protected $guarded = ['id'];
protected $fillable = ['name','icon','status'];
// protected $hidden = [];
// protected $dates = [];

/*
|--------------------------------------------------------------------------
| FUNCTIONS
|--------------------------------------------------------------------------
*/
public function getStatus()
{
    if($this->status == "1")
        $status = "Active";
    else
        $status = "InActive";
    return $status;
}
public function getIcon()
{
    if(isset($this->icon) && !empty($this->icon))
        return "<img src='".URL::to('\/').$this->icon."' height='25'>";
    return '';
}

/*
|--------------------------------------------------------------------------
| RELATIONS
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| SCOPES
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| ACCESORS
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| MUTATORS
|--------------------------------------------------------------------------
*/

}

Please advise!

Thanks

**Comment by tabacitu** [comment]
Hi @gnkevadia ,

1) For your errors, I believe you haven't defined your Eloquent relationships on your models. You need to do that. Afterwards, please make sure your addField definition and your database is correct. 
 - if a textbook can have multiple authors, you don't need an author_id column in Textbooks, but a different table to store the connections (say... textbook_author); then it's ok to use select2_multiple;
 - if a textbook can have only one author, it's not ok to use select2_multiple; you should use select2;
You can see an example of both type of relationships (1-n and n-n) in the [NewsCRUD documentation](https://laravel-backpack.readme.io/docs/newscrud). An article can have one category (1-n relationship, using select2 field), but an article can have multiple tags (n-n relationship, using select2_multiple field).
2) If you want to order the Authors by name every time you get them, I think you can do that with a [global scope](https://laravel.com/docs/5.3/eloquent#global-scopes) on your Author model:
```php
/**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('ordered', function(Builder $builder) {
            $builder->orderBy('name');
        });
    }
```

Cheers!

**Comment by tabacitu** [comment]
Hi @gnkevadia,

Still struggling with this? I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

Cheers!
