### ISSUE TITLE
mkdir public/uploads -> syntax incorrect

### ISSUE THREAD

**Issue by mikael1000** [Laravel-Backpack/CRUD#1183]
I'm following the installation instructions on the webpage and it says:
**3. Backpack\CRUD**
2) Run these command in this exact order:

The first command is:
**mkdir public/uploads**

I get the response:
The syntax of the command is incorrect.

What is it doing and why isn't it working? I copy the command from the website and I try to write it myself. It don't work.

The page I follow:
laravel-backpack.readme.io/v3.3/docs/install-on-laravel-55

:(

**Comment by lloy0076** [comment]
My guess is that you are on Windows or some other operating system without a Unix like file system.

Try:

```
mkdir public
cd public
mkdir uploads
```

Or

```
mkdir public\uploads
```

**Comment by lloy0076** [comment]
@tabacitu I'd propose a doc change but there's no way to change the docs...so the docs don't work under a Windows command prompt.

**Comment by mikael1000** [comment]
For confirmation that's what it was. I stopped programming and started to watch Vikings and in the middle of the show it just hit me about the backslash. Of course it worked. The documentation should be more clear about alternative for Windows. A lot Windows users are using Laravel.
