### ISSUE TITLE
Developer Experience: utility method/function to get supported crud fields. https://laravel-backpack.readme.io/docs/crud-fields

### ISSUE THREAD

**Issue by chriscalip** [Laravel-Backpack/CRUD#1194]
Who wants it? Can we have it?

Developers using/extending backpack could use this utility function/method.

**Comment by tabacitu** [comment]
Hmm... I'm not sure I understand. What do you mean @chriscalip ? Could you please give me a few details about the implementation, so I can understand?

Thanks, cheers!

**Comment by chriscalip** [comment]
@tabacitu I started to use backpack and explore its uses that it was originally intended.
For example imagine a situation for a crud gui where an administrator gets to build forms by point-and-click. I goto a newly created model then "Manage Attributes" and for each attribute pick a corresponding crud field. Now imagine a model called profile made up questions and each question an administrator can manage its crud field type like "select-from-array" and manage the allowed-values.
![profile-screenshot](https://user-images.githubusercontent.com/479454/36497911-5a7b0af4-1702-11e8-8f0c-ca5f73f2e8aa.png)

**Comment by tabacitu** [comment]
Oh, I get now, thanks. Yes, a GUI for creating CRUDs is planned, but we're quite a while from that. We're currently focused on delivering the best UX possible in code. Only after we're happy with that, will we start building the GUI. This polishing phase should take another few months, imho. As an intermediary step, which will be coming sooner than the GUI, we're building better generators, which will automatically generate full models, requests and controllers. No _need_ to code for most simple CRUDs, if you setup the database structure right. After that, it's just a matter of creating a point-and-click interface for those generators.

Hope this clears up the roadmap a little bit. Cheers!
