### ISSUE TITLE
Resources with subdirectories (e.g. /SUBDIR/the_resource) cause datatables list view to fail to render.

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/CRUD#1196]
# Bug report

When a resource is setup like so:

```
CRUD::resource('/DIRECTORY/resource', 'ResourceCrudController');
```

Backpack configures datatables to call back to:

```
https://APP_URL/resource/search?
```

But this causes an HTTP 404!

### What I did:

The above.

### What I expected to happen:

The list view etc. would work.

### What happened:

It didn't work.

### What I've already tried to fix it:

Evilly added the required view just to work around this.

### Backpack, Laravel, PHP, DB version:

```
        "backpack/base": "^0.8.4",
        "backpack/crud": "^3.3",
```

It may even be earlier. It probably only affects AJAX tables (but modern CRUD only uses AJAX tables).

Kudos so @mpixelz for finding this.

### Workaround

```
CRUD::resource('submissions/exampleResource', 'exampleResourceCrudController);
CRUD::resource('exampleResource', 'exampleResourceCrudController', ['only' => 'search']);
```

**Comment by mpixelz** [comment]
@lloy0076 you'r a life saver! 👍 
thanks alot for all the help getting this fixed :)

**Comment by tabacitu** [comment]
Hmm... @lloy0076 are you sure the route has been set correctly in the EntityCrudController?

```diff
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\MonsterRequest as StoreRequest;
// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\MonsterRequest as UpdateRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;

class MonsterCrudController extends CrudController
{
    public function setup()
    {
        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('App\Models\Monster');
-       $this->crud->setRoute(config('backpack.base.route_prefix').'/monster');
+       $this->crud->setRoute('DIRECTORY/monster');
        $this->crud->setEntityNameStrings('monster', 'monsters');
```

**Comment by tabacitu** [comment]
@lloy0076 and @mpixelz , is this still an issue?

**Comment by tabacitu** [comment]
Going to close this as my tests show it isn't an issue. Please reopen if I'm wrong.
