### ISSUE TITLE
Mutator doesn't fire properly

### ISSUE THREAD

**Issue by jahardner** [Laravel-Backpack/CRUD#1197]
Trying to upload an image to s3, and as far as I can tell the mutator in my model never fires:

```
public function setThumbnailAttribute($value)
    {
        $attribute_name = "Thumbnail_URL";
        $disk = "s3";
        $destination_path = "images";
		
	$this->attributes[$attribute_name] = time().'.'.$value->image->getClientOriginalExtension();

        $this->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
    }
```

My add field in the controller:

```
$this->crud->addField([
        'name' => 'Thumbnail',
        'label' => 'Thumbnail',
        'type' => 'image',
        'upload' => true,
        'disk' => 's3' 
    ]);
```

And my 's3' disk in filesystems.php:

```
's3' => [
        'driver' => 's3',
        'key' => env('AWS_KEY'),
        'secret' => env('AWS_SECRET'),
        'region' => env('AWS_REGION'),
        'bucket' => env('AWS_BUCKET'),
    ],
```

Whenever the file is 'uploaded' it shows a 'C:\Windows\Temp\php6803.tmp' as the location and nothing is in the S3 bucket. I've also tried not calling uploadFileToDisk and using Storage calls and they don't trigger either. Thumbnail_URL is fillable, and the info in the .env file is correct. I'm really hoping anyone has thoughts?

**Comment by lloy0076** [comment]
Try:

`name' => 'thumbnail'`

**Comment by iMokhles** [comment]
+1 as @lloy0076 suggested i faced same issue early 
but why `$attribute_name = "Thumbnail_URL";` and not just `$attribute_name = "thumbnail";` like what you type in 

```
$this->crud->addField([
        'name' => 'Thumbnail',
        'label' => 'Thumbnail',
        'type' => 'image',
        'upload' => true,
        'disk' => 's3' 
    ]);
```

**Comment by jahardner** [comment]
I have it as Thumbnail_URL because that's the field in the DB. Am I missing something? Sorry if so, very new to this.

I can manage to perhaps make progress if I make them all "Thumbnail_URL" because if I do that I hit a SQL error that it's trying to place all the image data in the database...so perhaps it's the uploadFileToDisk call that isn't working somehow?

**Comment by jahardner** [comment]
@iMokhles Update, tried this, same results as before, the file path is set to CTemp in the db and nothing gets uploaded to the s3. Could all this be trouble with the underscore?

**Comment by iMokhles** [comment]
mmm i cannot figure out why your s3 setup break uploading :(

**Comment by jahardner** [comment]
So I followed a hunch on this and tried all the same code just changed the name to match another field in my db...it's actually the underscore that screws things up somehow. I've renamed the attribute Thumbnail and now it works, just in case someone hits this same issue again.
