### ISSUE TITLE
Manipulate fake fields to not store base64 encoded images.

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#1198]
# Help needed

### What i want to achieve:

I'm trying to use an image field type to store image path to database and not base64 image.
Currently it stores the field as base64.

### What I expected to happen:

I expect to find some way, even if hacky, to catch my image fake field, and if, for example there is a "save_path_to_db => true" key on image field, i can run some code to upload image to server and save path to database.

Can you @tabacitu point me in some direction this could be achieved?

Thanks in advance

**Comment by lloy0076** [comment]
A code example of some sort would come in handy.

**Comment by pxpm** [comment]
Simply add a field:
```
$this->crud->addField([
                        'name' => 'about_us_picture',
                        'label' => 'Imagem sobre nós',
                        'type' => 'image',
                        'upload' => true,
                        'crop' => true, // set to true to allow cropping, false to disable
                        'aspect_ratio' => 0, // ommit or set to 0 to allow any aspect ratio
                        'prefix' => 'uploads/profile-pictures/',
                        'fake' => true,
                        'store_in' => 'extras',
                        'save_path_to_database' => true, //newly created flag, not used
                    ]);
```
Define a mutator:
```
public function setAboutUsPictureAttribute($value)
    {
        $attribute_name = "about_us_picture";
        $disk = "uploads";
        $destination_path = "pages-pictures/";

        // if the image was erased
        if ($value==null) {
            // delete the image from disk
            \Storage::disk($disk)->delete($this->{$attribute_name});

            // set null in the database column
            $this->attributes[$attribute_name] = null;
        }

        // if a base64 was sent, store it in the db
        if (starts_with($value, 'data:image'))
        {
            // 0. Make the image
            $image = \Image::make($value);
            // 1. Generate a filename.
            $filename = md5($value.time()).'.jpg';
            // 2. Store the image on disk.
            \Storage::disk($disk)->put($destination_path.'/'.$filename, $image->stream());
            // 3. Save the path to the database
            $this->attributes[$attribute_name] = $filename;
        }
    }
```
If i remove the store as fake, i get image saved to disk and path saved to database. If i try with fake field, it will save the image to database as a base64 enc. image in my extras column. 

My question is how would it be possible to catch those fake fields,and it's fake and has the flag i created "save_path_to_database" present, it would run:  store the file in disk and return the path to be saved in database as fake field.

Maybe it can be achieved checking for that flag on compactFakeFields() ? 

Or there is a better not so hacky solution for this problem ?

Thanks in advance.

**Comment by lloy0076** [comment]
The solution is not to store images in fake fields in the short term.

The short term would be one of the "hacky" solutions (which would work, I think).

In the long term, the solution would be to redo image storage completely (whether for fake or not fake fields) because it's currently too confusing.

**I** lean on the "why are we storing images in fake fields" camp?

**Comment by pxpm** [comment]
Hey @lloy0076 .
Thanks for answering. 
First i will give you my use case:

I'm creating a template for "Pages" (Backpack package). 
I would like that page to have 3 images. (Image_top, Image_middle, Image_footer), in other page i could have (Image_left, Image_right) etc etc. I could not predict in advance what images i would need in a page, so the solution would be to store the images in fake field with `key => value`, but the value could not be a base64 encoded image. 
I have no problems of writing a PR, and if that could be done for my project and released to community i would do it, i just asked for some direction of what needs to be changed without breaking code. 

I see we must implement ourselfs the saving image function and make it configurable. (choosing disk, prefix etc etc).

When i asked for guidance on this i thought it would be helpful to have the main developers looking on this, as it's not the first time someone asks about it, and the behavior is strange at least. 

We can have a config value like "auto_store_images" to keep backward compatibility.

I would like to go deep on this issue if you and other main develops seems it should be looked at. 

Let me know about it, if you still want me to look on SOF i will, no problem.

Best regards and sorry for some english typo, i'm not native. 

Thanks

**Comment by brynnb** [comment]
I am also having this same issue - it seems to me that fake fields are designed for when a Page of a certain template has fields that no other templates need. This way you don't have to create a custom database field for every single piece of information on every single page template. It then seems to follow that in addition to these extra text fields, that certain page templates would need image uploading that other pages don't. That is why I'm trying to store in image in a fake field.

My hacky solution is to simply have "image_1" and "image_2" and "image_3" fields in the database for a Page. And then the template has to simply use the "Label" property in the CRUD to let the user know what each image is for.
