### ISSUE TITLE
custom column not orderable 

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#1201]
# Bug report
when i try to make custom field "name" 
ex: in database table i have 2 fields "name_ar" ,"name_en" 
orderable column not working well in "list view"

But its working with normal fields that is not custom
is there any way to fix this?

### What I did:
i did create new custom field  => name
in database it was name_ar and name_en
i did make append attribute to append "Name"

i did created the setAttributeName() in model
i did created the getAttributeName() in model

```
        $this->crud->addColumn([
  	'name' => 'name',
   	'label' => 'Name',
                    'searchLogic' => function ($query, $column, $searchTerm) {
                              $query->orWhere('name_'.\App::getLocale(), 'like', '%'.$searchTerm.'%');
                           }, 
   	]); 
```

Also i did try to make sure if there's bug by use order by another column in list view
and when i  click in order asc /desc it works only with asc but when i click more than time it gives me the same asc order

### What I expected to happen:
Name column should have its own orderable in list view 

### What happened:
it does not appear any line to order the name colum 
### What I've already tried to fix it:

```
    $this->crud->addColumn([
  	'name' => 'name',
  	'label' => 'Name',
                     'searchLogic' => function ($query, $column, $searchTerm) {
                              $query->orWhere('name_'.\App::getLocale(), 'like', '%'.$searchTerm.'%');
                         }, 
                    'orderable' => true,        
 	]); 
```

### Backpack, Laravel, PHP, DB version:

but still did not work well

**Comment by tabacitu** [comment]
@c1t1zen My guess is that it doesn't work for you because you used ```name``` as the column name, when your database column is actually ```name_ar``` or ```name_en```. Something like this should work better for you, without using any accessors and mutators:

```diff
    $this->crud->addColumn([
-  	'name' => 'name',
+  	'name' => 'name_'.\App::getLocale(),
  	'label' => 'Name',
                     'searchLogic' => function ($query, $column, $searchTerm) {
                              $query->orWhere('name_'.\App::getLocale(), 'like', '%'.$searchTerm.'%');
                         }, 
                    'orderable' => true,        
 	]); 
```
