### ISSUE TITLE
Filters using AjaxTable return 200 code but results not filtered

### ISSUE THREAD

**Issue by Sidjoo** [Laravel-Backpack/CRUD#1203]
Hello,

I'm using Backpack/Base ans Backpack/Crud. It's working well on my localhost but as soon as I push it on the production environment, all the filters aren't working anymore.
When I check the request in my Network (search?myVar=xxx), I have a 200 with results but results that aren't filtered. So I have all my table back.

It's problaby an environment issue. But I don't see where i'm wrong.

Here is my localhost configuration :
- MAMP Pro with PHP 7.1.1
- Backpack/Base 0.8.7
- Backpack/CRUD 3.3.6
- MySql 5.6.35

My production environment :
- Heroku
- PHP 7.1.13
- Backpack/Base 0.8.7
- Backpack/CRUD 3.3.6
- MySql (don't know the version, can't find it).
I have also tried with Postgres, but it's the same, it's not working too.

On both of them, datas are generated by seeders, so datas are the same.

Is there anyone who had the same issue ?

Thanks.

**Comment by b8ne** [comment]
@Sidjoo Perhaps show us some of your code so we can test it?

**Comment by aheissenberger** [comment]
**I do have the exact same problem - works local but not on production server.**

Here is the Network Call of one of my filters:
https://www.xxxxx.xx/admin/mytest/search?campaign_id=test&campaign_id_text=test

**Result:**
```
{"draw":8,"recordsTotal":26464,"recordsFiltered":26464,"data":[["<td>79J43O<\/td>",....
```
This will always return the not filtered list and not the filtered list on production but does filter the list on my local host.

Using the Filter Input Box works but the input is transferred as POST Request to the server

Can you give me some help on how I can debug this problem?

**Comment by JLGouwy** [comment]
@aheissenberger where do you use app('request')->setTrustedProxies ? 
I have the same problem. I don't understand everything what you explain :D but I would like to test  your solution.

**Comment by JLGouwy** [comment]
Ok got it the solution thanks to heroku documentation. 
https://devcenter.heroku.com/articles/getting-started-with-laravel#trusting-the-load-balancer

thanks @aheissenberger

**Comment by Pegasus260985** [comment]
I had the same problem. I'm running laravel Backpack in ELB and it wasn't enough with the [`fideloper/proxy`](fideloper/proxy) package. I used this article to fix the problem: [Laravel 5 : SSL routes behind a load balancer](http://www.code-examples.com/laravel-5-ssl-routes-behind-a-load-balancer/)
