### ISSUE TITLE
Crud entry id in list view replaced by joined id after addClause

### ISSUE THREAD

**Issue by captainkirkoff** [Laravel-Backpack/CRUD#1205]
Hello,
I use this code in the setup() method of my DocumentCrudController:

```
            if (\Auth::user()->hasRole('CompanyManager')) {
                $this->crud->addClause(
                    'join',
                    'users',
                    function ($query) {
                        $companyId =  \Auth::user()->company->id;
                        $query->on('documents.user_id', '=', 'users.id')
                        ->where('users.company_id', '=', $companyId);
                    }
                );
            }

```

I just need a company manager being able to view download documents owned by any company user, so I use a button from a view which call $entry->getKey() as parameter for a download route: it works perfectly well If I don't add any join clause. 
When the "users" table comes into play via the join clause, the document id just gets replaced by the user id, so that I cannot access the document anymore.
I can I get rid of this behaviour?

### Backpack, Laravel, PHP, DB version:
Backpack  bae 0.8.6, CRUD 3.3.5, Laravel 5.5.29, PHP 7.1.8, MySQL 5.7.19.

**Comment by captainkirkoff** [comment]
Sorry, found solution by myself: appending
$this->crud->addClause('select', 'documents.*');
it solved.

**Comment by tabacitu** [comment]
Thanks for sharing your solution too, @captainkirkoff . You'll definitely help someone who searches for the same thing. Cheers!

**Comment by NoorA-cogapp** [comment]
In my case if I apply filters on a crud controller, the id of the project get's replaced by the filter id for example manager_filter_id. Which was causing wrong filter id in the button link here:   <a href="{{ '/route?project_id='.$entry->getKey() }}" class="btn btn-sm btn-link">

Using $this->crud->addClause('select', 'projects.*'); in the ProjectCrudController right before adding link buttons solved the issue.
