### ISSUE TITLE
Load fields with AJAX on click on a tab

### ISSUE THREAD

**Issue by KnokDigi** [Laravel-Backpack/CRUD#1208]
Hello,

I would like to know if it is possible to load the fields with AJAX when we click on the "tabs"? In fact, I have several fields in several tabs, and that by clicking on a tabs, it loads the corresponding part.

There is a way to do that with Backpack? If no, what tracks can you give me?

**Comment by lloy0076** [comment]
This isn't handled natively by Backpack - given that Backpack uses Bootstrap I'd suggest:

- https://duckduckgo.com/?q=loading+fields+into+a+bootstrap+tabs+field+using+AJAX
- https://www.google.com/search?q=loading+fields+into+a+bootstrap+tabs+field+using+AJAX
