### ISSUE TITLE
Problem with htmlspecialcharts()

### ISSUE THREAD

**Issue by snakom23** [Laravel-Backpack/CRUD#1210]
this is my two fns stored in model. I call these in view.

```
    public static function getPosition($in_array){
      $array = [];
      if (\DB::table('headerlinks')->count() > 0){
        $array = static::buildTreeArray(json_decode(\DB::table('headerlinks')->get(), true));
      }
      $result = array();
      $success = static::array_find_deep($array, $in_array, $result);
      return array_slice($result,0,count($result)-1);
    }

    public static function buildTreeArray(array $array, $idField = 'id', $parentIdField = 'parent_id', $childNodesField = 'children'){
        $indexed = array();

        foreach ($array as $row) {
            $indexed[$row[$idField]] = $row;
            $indexed[$row[$idField]][$childNodesField] = array();
        }

        $root = array();
        foreach ($indexed as $id => $row) {
            $indexed[$row[$parentIdField]][$childNodesField][$id] =& $indexed[$id];
            if (!$row[$parentIdField]) {
                array_push($root,$id);
            }
        }
        $final_array = array();
        foreach ($root as $key => $value) {
          array_push($final_array,$indexed[$value]);
        }
        return $final_array;
    }
```

and this is the error:

![senza titolo-2](https://user-images.githubusercontent.com/6834308/35534206-0eff82c2-0540-11e8-8c91-eeb8291f0aa8.jpg)

**Comment by lloy0076** [comment]
Can you get the rest of the stack trace? Preferably copy and paste it (or attach it).

Use **three** back ticks (the things next to the number one `1` on most US QWERTY keyboards) to post blocks of preformatted text.

I've fixed the original post :)

**Comment by iMokhles** [comment]
sorry but where's `treeview.blade` the file which has `htmlspecialcharts` inside it ? i wan't able to locate it insde the`Backpack/Crud` package

**Comment by snakom23** [comment]
this is my treeview.blade.php
`
<div @include('crud::inc.field_wrapper_attributes') >
    <label>{!! $field['label'] !!}</label>
    @include('crud::inc.field_translatable_icon')
    <?php $entity_model = $crud->model; ?>
    <div>
      {{ $field['model']::getPosition(11) }}

        </div>

    {{-- HINT --}}
    @if (isset($field['hint']))
        <p class="help-block">{!! $field['hint'] !!}</p>
    @endif
</div>

{{-- ########################################## --}}
{{-- Extra CSS and JS for this particular field --}}
{{-- If a field type is shown multiple times on a form, the CSS and JS will only be loaded once --}}
@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))

    {{-- FIELD CSS - will be loaded in the after_styles section --}}
    @push('crud_fields_styles')

    @endpush

    {{-- FIELD JS - will be loaded in the after_scripts section --}}
    @push('crud_fields_scripts')

    @endpush

@endif
{{-- End of Extra CSS and JS --}}
{{-- ########################################## --}}
`

**Comment by snakom23** [comment]
i'm solved.
