### ISSUE TITLE
Select2 for showing images list

### ISSUE THREAD

**Issue by michelvambattu** [Laravel-Backpack/CRUD#1216]
I have a CRUD menu 'Students'. I have another CRUD menu 'Avatars' for storing some common icons. 

During the creation of a new student, I want to choose an avatar from a list of icons (from the model- Avatar), likewise we do in a 'select2' field. Is there a way for choosing images from 'select2' field ?

Currently the only possible way is to choose only the 'id' of an icon. But selecting 1-4 is a little strange
when we cannot see what we're choosing.

**Comment by lloy0076** [comment]
There's no current field that does precisely what you'd like - however creating a custom field is possible (see the [docs](https://laravel-backpack.readme.io/docs/crud#section-custom-field-types-roll-your-own-)).
