### ISSUE TITLE
Allow customization for Summernote

### ISSUE THREAD

**Issue by FrittenKeeZ** [Laravel-Backpack/CRUD#1217]
Basically just replace the initialization in its field file `summernote.blade.php` with
```
$('.summernote').summernote(@json($field['options'] ?? []));
```

**Comment by pxpm** [comment]
No BC, lean and clean. +1

**Comment by tabacitu** [comment]
Totally! Simple change, just made it on ```master```, it will be available publicly on the next patch update (0-3 days).

Thank you, cheers!

**Comment by yingliangzhang** [comment]
This doesn't seem to be working?
Added
```
'options' => [
                    'height' => '400px',
                    'minHeight' => '400px',
                ],
```
but has no effect
