### ISSUE TITLE
can i pass a variable to curd router?

### ISSUE THREAD

**Issue by iwillhappy1314** [Laravel-Backpack/CRUD#122]
I want to filter date in crud list, then I write a router like this:

`CRUD::resource( 'keywords/{status?}', 'KeywordsCrudController' );`

and, in controller, I write this:

`$this->crud->addClause( 'where', 'status', '=',  $status );`

but I can acess the $status in controller, is there any way?

**Comment by tabacitu** [comment]
Hi @iwillhappy1314 ,

I think you're on the right track. 
1) Can't you access the status with ```\Route::current()->parameter('status')```?
2) If not, can you access it in the constructor within a middleware closure?
```php
$this->middleware(function ($request, $next) {
            $this->crud->addClause('where', 'status', '=', \Route::current()->parameter('status'));
            return $next($request);
        });
```

Cheers!

**Comment by iwillhappy1314** [comment]
Hi @tabacitu ,

I can aceess the `$status`  with both method 1 and 2.

Thanks a lot !

**Comment by tabacitu** [comment]
Happy to help. Cheers!

**Comment by mpixelz** [comment]
Hi,
this works perfectly.. thanks..

but there is one issue using the method above..
when i enable details row on the crud using this it passes status value in the id as well on showdetails method.

my crudcontroller:
```
<?php
namespace App\Http\Controllers\Admin;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use App\User;
class StudentListsController extends CrudController {
	public function setUp() {
        $status = \Route::current()->parameter('userstatus');
        $this->crud->setModel("App\User");
        $this->crud->setRoute("admin/student/".$status."");
        $this->crud->setEntityNameStrings('Student '.$status.'', 'Students '.$status.'');
        $this->crud->enableAjaxTable();
        $this->crud->enableDetailsRow();
		$this->crud->setFromDb();
    }
    public function showDetailsRow($id)
    {
        dd($id);
        $user = User::where('id', $id)->first();
        return view('partials.student_details_row')->with('user', $user);
    }
}
```
and my route file:
```
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function()
{
CRUD::resource( 'student/{userstatus}', 'StudentListsController' );
});
```
so on the above  dd($id) instead of getting user-id i get {userstatus} value.

**Comment by tabacitu** [comment]
@mpixelz try to do a ```dd(\Request::input());``` - both variables should be there, and you can use the one you need.

Cheers!
