### ISSUE TITLE
Feature request: dependent Select2 fields

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#1221]
Use Case:
- Model 'company'
- Model 'contact'
- company (1 -n) contacts

I have an API for gathering contacts of a given company, eg
/ajax/company/{company_id}/contact -> returns all contacts for company with {company_id}
 
Now in my view I want to have two dependent select2 fields, 
- one for company 
- one for contacts
Of course when the value of company changes the corresponding contacts should be listed

I've got it working overwriting the select2 javascript in the view and repopulating the data_source url with the updated value using the correct company_id, eg /ajax/company/1234/contact upon the change trigger of the company select2 field

however I believe there should be an easier way to do this, eg by passing company_id (or any other parent model id of course) as a parameter, a bit like the search function does

**Comment by lloy0076** [comment]
How "evil" is your solution? Is it something that could be turned into a PR?

Is it something that #132 would fix?

**Comment by timbertens** [comment]
I believe it would be quite straightforward to add it to the select2_from_ajax field. 
My thoughts (so I won't forget)
- add attribute 'parent_select2_name' 
- add attribute 'pre_parent_placeholder' to show a placeholder before the parent select2 is selected (eg. 'First select the company')
- have the datasource attribute to be something like => url("ajax/account/" . %parent_id%  "/contact")

And then in the javascript part, only when the parent_select2_name is filled in: listen the to the change event of the parent_select2_name field and basically have pretty much the same jquery as the currently in the select2_for_ajax file, but where the url = the datasource attribute with the parent_select2_name.val() filled in as the %parent_id% placeholder. 

Not sure how https://github.com/Laravel-Backpack/CRUD/pull/132 would benefit from it, to be honest.

**Comment by tabacitu** [comment]
@timbertens we have a beta fix for this here https://github.com/Laravel-Backpack/CRUD/pull/1484

Check it out!
