### ISSUE TITLE
[3.6][Bug] select2_from_array with allows_multiple "null" saves incorrectly

### ISSUE THREAD

**Issue by TheJester12** [Laravel-Backpack/CRUD#1224]
# Bug report
When using the select2_from_array field type. If you clear all existing (saved) values and update, the database is left with `[null]` rather than a real `NULL` value.

### What I did:
Field configuration:
```
[
      'name' => 'benefit_exclusions',
      'label' => "Exclude Benefits From This Market",
      'type' => 'select2_from_array',
      'options' => $benefitsArray,
      'allows_null' => true,
      'allows_multiple' => true,
],
```
In the model I also have:
```
protected $casts = [
      'benefit_exclusions' => 'array',
];
```

### What I expected to happen:
Save with a `NULL` value.

### What happened:
It saves with a value of `[null]`

### What I've already tried to fix it:
As a temporary workaround, I changed my update function at the bottom of my CrudController to this:
```
public function update(UpdateRequest $request)
{
    $redirect_location = parent::updateCrud($request);
    if (empty($request->benefit_exclusions)) {
        $this->crud->entry->benefit_exclusions = null;
        $this->crud->entry->save();
    }
    return $redirect_location;
}
```

### Backpack, Laravel, PHP, DB version:
backpack/base: 0.7.25
backpack/crud: 3.2
Laravel: 5.5.24
PHP: 7.1.8
MySQL: 5.6.35

**Comment by johnharris4p** [comment]
It's not A real null
But this can solve the problem

`
            if ($values !== "null") {
                foreach (json_decode($values) as $key => $value) {
                    $this->crud->addClause('where', 'column', $value);
                }
            }
`

**Comment by pxpm** [comment]
Isn't this fixed by: https://github.com/Laravel-Backpack/CRUD/commit/fa0dc8296198739389f70278ac7b5ca7eb197637

? @tabacitu ?

**Comment by pxpm** [comment]
Thanks for the report @TheJester12  and sorry for taking so much time to get a solution for this. 

As you can see in #3243 it's not an easy one, but I think this could be a long term one. 

Let's keep any discussion related to this in the PR thread. 

Thanks again,
Pedro
