### ISSUE TITLE
how to use s3 as storage disk with laravel backpack?

### ISSUE THREAD

**Issue by Himani-Bhatt** [Laravel-Backpack/CRUD#1225]
# Bug report

**Comment by b8ne** [comment]
https://laravel.com/docs/5.6/filesystem

**Comment by Himani-Bhatt** [comment]
i want sample code not getting how to use s3 disk to store images on aws

**Comment by lloy0076** [comment]
I'm sorry but this is the issue tracker to track bugs, issues and enhancements for `laravel-backpack/CRUD`; it would be polite to attempt to answer some of the questions which we have helpfully provided in the default **bug** creation template yet you have not even done this.

Please ask this question elsewhere.

**Comment by tabacitu** [comment]
Rephrase: @Himani-Bhatt using S3 as storage in Backpack is no different from the usual Laravel procedure. Backpack just picks up whatever Laravel has. The link the guys have provided should get you started, and there a quite a few tutorials out there too, depending on preferences. This doesn't look like a Backpack issue or bug, more of a general Laravel question, so I think @lloy0076 did well to close this fast. We're trying to limit Github issues to Backpack bugs only, so we can move relatively fast in fixing them. Cheers!
