### ISSUE TITLE
Multiple Records on click

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1229]
# Bug report

When clicking the "save" button multiple times it creates a record for everytime you click it. If you click it twice, it creates two, click it 4, creates it 4, click 7, creates 7. etc.. Not sure why this is at the moment, looking into it but want to create a record of it.

### What I did:
Clicked on "save" multiple times.

### What I expected to happen:
Single record created.

### What happened:
a duplicate record created for every click.

### What I've already tried to fix it:
_looking into it currently_

### Backpack, Laravel, PHP, DB version:
Backpack/Base: 0.8.9
Backpack/Crud: 3.3.8
Laravel: 5.5
PHP: 7.1.7
DB: MySQL 5.7.18

**Comment by tabacitu** [comment]
On it!

Thank you @AbbyJanke . I guess the only thing we _can_ do is write a JS that disables the button after the first click. The page will be reloaded in case of errors anyway, so it _should_ just prevent people from clicking twice. Right?

https://stackoverflow.com/questions/36767731/how-to-prevent-double-click-event-on-submit-button

Downside: not sure if the JS is fast enough to prevent a fast second click. But I hope so :-)

**Comment by tabacitu** [comment]
Done! https://cl.ly/2J2D3Y080x3g

Will be launched shortly, in the next patch update. Thank you!
