### ISSUE TITLE
create and edit views to large forms

### ISSUE THREAD

**Issue by AgnusTI** [Laravel-Backpack/CRUD#1230]
# Bug report

### What I did:
edit create.blade.php and edit.blade.php
change 
`<div class="col-md-8 col-md-offset-2">`
 to 
`<div class="col-md-12">`

### What I expected to happen:
large forms

create a setup to this

**Comment by tabacitu** [comment]
Hi @AgnusTI ,

Seems like a customization issue to me, not a Backpack bug, so I'm going to close this.

Cheers!
