### ISSUE TITLE
barryvdh/laravel-debugbar with AJAX datatables

### ISSUE THREAD

**Issue by ghost** [Laravel-Backpack/CRUD#1235]
Hi,

This is more like a "how to" question:

Is there any way to make full use of the package `barryvdh/laravel-debugbar` using the AJAX dataTables?
I'd like to get, for example, queries that are being executed and so on.

Thanks.

**Comment by tabacitu** [comment]
Hi @maaxxicarvalho ,

Good question :-) I've had a difficult time figuring this out too. DebugBar _does_ have this feature, to track AJAX requests, and it's enabled by default. You just have to click the "folder" icon to the right, and choose your request. Here's a quick video I made to show you how it works. Hope it helps.

https://cl.ly/0u1R3W442z1i

Cheers!

**Comment by maaxxicarvalho** [comment]
Thanks @tabacitu 
I got a nice auto-reply from the Github bot and could get the answer from the guys using Gitter.

**Comment by siyei** [comment]
Thank you very much, this was really helpful

> Hi @maaxxicarvalho ,
> 
> Good question :-) I've had a difficult time figuring this out too. DebugBar _does_ have this feature, to track AJAX requests, and it's enabled by default. You just have to click the "folder" icon to the right, and choose your request. Here's a quick video I made to show you how it works. Hope it helps.
> 
> https://cl.ly/0u1R3W442z1i
> 
> Cheers!

**Comment by karandatwani92** [comment]
Hi @tabacitu,

I think we should have this in docs. The video link is not accessible anymore.❌

**Comment by tabacitu** [comment]
Here's a GIF of it - that way Github stores it for a long time:

![CleanShot 2023-03-24 at 13 51 55](https://user-images.githubusercontent.com/1032474/227514264-0a95ac8f-1bfa-4009-86c4-3c8313ca3399.gif)

**Comment by tabacitu** [comment]
I didn't quite agree with you at first @karandatwani92 because... this isn't exactly about Backpack, it's about how to do that in Laravel in general. But it is something many people struggle with, so ok, I've added it to our docs - https://github.com/Laravel-Backpack/docs/pull/415
