### ISSUE TITLE
Many to many relationship field type

### ISSUE THREAD

**Issue by m5taha5m** [Laravel-Backpack/CRUD#1242]
Thanks for your great job, guys. You have implemented a really great system.
After a total comparison of the Laravel-CRUD frameworks, I chose Backpack for many reason including beautiful coding. But the lack of many to many relationship field-type is a disadvantage. Which I've found in Laravel-Admin implemented really good. I suggest to see this [demo](http://laravel-admin.org/demo/painters/create)(for login use admin/admin) to get idea for implementing a many to many field type.

Thanks again :)

**Comment by lloy0076** [comment]
Thank you for your feedback.

PR #132 might be something similar.

It is something, I believe, that we are quite aware of.
