### ISSUE TITLE
Unable to change json_encode options for fake fields

### ISSUE THREAD

**Issue by codercms** [Laravel-Backpack/CRUD#1250]
# Bug report
There is no any way to change behavior for encoding of fake fields.

### What I did:
Just used fake fields functionality.

### What I expected to happen:
My model will apply my rules to store JSON (overridden asJson metod).
My model ofcource have an "casts" attribute (to cast my fake fields storage field into array).
Overriden method:
```php
    /**
     * Encode the given value as JSON.
     *
     * @param  mixed $value
     * @return string
     */
    protected function asJson($value): string
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }
```

### What happened:
Backpack encode fake fields by himself.
https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/FakeFields.php#L41

### What I've already tried to fix it:
Overload model addFakes method
```php
public function addFakes(array $columns = ['extras']): void
{
    foreach ($columns as $key => $column) {
        $columnContent = $this->{$column};

        if (!\is_object($this->{$column}) && !\is_array($this->{$column})) {
            $columnContent = json_decode($this->{$column}, true);
        }

        if (\is_array($columnContent) || \is_object($columnContent) || $columnContent instanceof \Traversable) {
            foreach ($columnContent as $fake_field_name => $fake_field_value) {
                $this->setAttribute($fake_field_name, $fake_field_value);
            }
        }
    }
}
```
And create workaround to save unescaped json:
```php
public function setDataAttribute($value): void
{
    if (\is_string($value) && ($encoded = json_decode($value, true))) {
        $this->attributes['data'] = $this->asJson($encoded);

        return;
    }

    $this->attributes['data'] = $value;
}
```

But maybe JSON columns serialization should be performed in a Model layer (i mean really use eloquent functionality)?

### Backpack, Laravel, PHP, DB version:
Backpack CRUD - 3.3.10, Laravel - 5.6.4, PHP - 7.1.x, DB - PostgreSQL 9.4

**Comment by tabacitu** [comment]
@codercms sounds like PR https://github.com/Laravel-Backpack/CRUD/pull/1116 would fix it for you. I'll let you know when it's merged.

**Comment by codercms** [comment]
@tabacitu okay, thanks 👍

**Comment by tabacitu** [comment]
Merged and launched. Should be available to you after a ```composer update```. Cheers!
