### ISSUE TITLE
Typecast the HasTranslations::getLocale() method to a string

### ISSUE THREAD

**Issue by remibrandcube** [Laravel-Backpack/CRUD#1253]
# Bug report

### What I did:
The basemodel uses the Spatie\HasTranslations trait. The model that is used in the controlpanel extends the basemodel. That child class uses the Backpack\HasTranslations trait.

### What happened:
Declaration of Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations::getLocale() must be compatible with App\Models\Category::getLocale(): string

### What I've already tried to fix it:
The Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations::getLocale() method should be using a return type (string) declaration to be compatible with the Spatie trait.

### Backpack, Laravel, PHP, DB version:
Backpack crud 3.3, laravel 5.6, php 7.1, mysql 5.7

**Comment by tabacitu** [comment]
Hi @remibrandcube ,

Thanks for reporting this. I've just merged a PR and tagged a release yesterday. A ```composer update``` should fix it for you.

Cheers!
