### ISSUE TITLE
Custom table for user page

### ISSUE THREAD

**Issue by gasparyanyur** [Laravel-Backpack/CRUD#1256]
I need to add only one column in the  table which lists all users. So I have overwrite `/admin/user` in my `routes/web.php` file, and have call the `getUser` function from my `AdminController`. My `AdminController` extends from `Backpack\CRUD\app\Http\Controllers\CrudController` and in my `getUser` function I have call the `parent::index` function but the response I have got the error look like this

>htmlspecialchars() expects parameter 1 to be string, object given (View: /Users/pc/blog/vendor/backpack/crud/src/resources/views/list.blade.php)

**Comment by lloy0076** [comment]
This is a support request, not a bug; it would be easier if you provided a gist or archive of what you describe.
