### ISSUE TITLE
SQL Server - Blank List Pages

### ISSUE THREAD

**Issue by bsaunders73** [Laravel-Backpack/CRUD#1264]
I started creating my Backpack application with MySQL, and had to switch to SQL Server. I had created 4 tables and corresponding CRUD elements, so I wasn't too far into things.

I switched the database in the env file after installing the driver, and things connected. I migrated the database from MySQL to SQL Server, and now the application loads. However, for a few tables, the list view looks like this:

![sqlserver](https://user-images.githubusercontent.com/28276447/37005677-ebd48030-20a2-11e8-89fd-2304b753cb6a.PNG)

It is obviously making the database connection, and it is retrieving the correct amount of entries. I am also querying data out of this same table for a dashboard that is working correctly. 

Does anybody have any ideas?

Thank you.

Backpack: v.0.8.9
Laravel: 5.6
PHP: 7.1
DB: SQL Server 2016

**Comment by tabacitu** [comment]
Hi @bsaunders73 ,

That's _very_ weird. Looks to me like for some reason Eloquent isn't getting the attributes properly. 

Q1) If you click Edit, I assume the fields are empty? Or do they get filled with the right information? 
Q2) Are all the necessary columns in ```$fillable``` in your models?

Cheers!

**Comment by bsaunders73** [comment]
Tabacitu, thank you for the response. This is definitely not a backpack issue, it turns out that SQL Server was a little stricter with case sensitivity regarding column names.
