### ISSUE TITLE
Edit and Delete buttons position and recreate : question

### ISSUE THREAD

**Issue by jbowm2** [Laravel-Backpack/CRUD#1265]
Not sure this is the right place to ask how to do something

My rows in the CRUD list are extremely long, and i would like to add the "Actions" buttons to the beginning of the line along with the ones that appear on the end of the row also. 

Read through the documentation about adding buttons and columns and cannot seem to figure this one out. 
Do i need to add a column Actions and add buttons to this column?

**Comment by lloy0076** [comment]
If you look in `vendor/backpack/crud/src/resources/views/list.blade.php` and then publish that.

I'm not sure you can easily do this on a controller by controller basis.

That said, this seems more a support question.

**Comment by tabacitu** [comment]
@jbowm2 There's no quick way to do that. But you CAN extend the ```CrudPanel``` class and modify how that's done. Currently it's done in one of the CrudPanel traits - ```Search::getRowViews()```:

```php
    public function getRowViews($entry)
    {
        $row_items = [];
        foreach ($this->columns as $key => $column) {
            $row_items[] = $this->getCellView($column, $entry);
        }

        // add the buttons as the last column
        if ($this->buttons->where('stack', 'line')->count()) {
            $row_items[] = \View::make('crud::inc.button_stack', ['stack' => 'line'])
                                ->with('crud', $this)
                                ->with('entry', $entry)
                                ->render();
        }

        // add the details_row buttons as the first column
        if ($this->details_row) {
            array_unshift($row_items, \View::make('crud::columns.details_row_button')
                                           ->with('crud', $this)
                                           ->with('entry', $entry)
                                           ->render());
        }

        return $row_items;
    }
```

I'd recommend against it, though. This method has suffered changes in the newest update (coming in a few days) so when you'll need to update, you'll need to make changes to it too.

The CRUD 3.4 update (again, coming in a few days) will bring the ability to specify a ```maxlength``` for you ```text``` columns. I think that's an easier solution for you.

Cheers!
