### ISSUE TITLE
Additional feature: select2 with the ability to use scope of model

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#1266]
As the title says, it is not possible today to use scopes in the 'select2' or 'select' field types.  A small addition make it possible without introducing breaking changes.  

2 properties are additionally available in the addField method for this field:

scope: fill in the scope name (string) as defined in the model
scope_params: fill the parameters (array) you can pass to the scope in the model
```
$this->crud->addField([
            'name' => 'vat_tariff_id',
            'label' => 'VAT Tariff',
            'type' => 'select2',
            'entity' => 'vat_tariff',
            'attribute' => 'nameAndPercentage',
            'model' => 'App\Models\VatTariff',
            'scope' => 'instanceCountry',
            'scope_params' => [
                '56'
            ]
        ]);
```

I've added a PR for the select2 field (the other similar fields should of course get the same) https://github.com/Laravel-Backpack/CRUD/pull/1262

**Comment by tabacitu** [comment]
Thanks a lot for the issue & PR @timbertens ! Used your great work to put together https://github.com/Laravel-Backpack/CRUD/pull/1694 .

Let's move the conversation there please.
