### ISSUE TITLE
after_script not working on custom CRUD views

### ISSUE THREAD

**Issue by yingliangzhang** [Laravel-Backpack/CRUD#1267]
# Bug report

### What I did:
Create a custom CREATE view using `$this->crud->setCreateView('your-view');`, 
![image](https://user-images.githubusercontent.com/3793091/37067655-f4d0aef4-21fe-11e8-8bc5-2f12ca49bf9b.png)

Then I added after scripts:
```
@section('after_scripts')
    <script type="text/javascript">
        alert('hahahah');
    </script>
@endsection
```
### What I expected to happen:
Alert shows "hahahah"

### What happened:
Nothing happened. After scripts not loaded into the page

### What I've already tried to fix it:
Everything

### Backpack, Laravel, PHP, DB version:
Backpack: 3.2.19
Laravel: 5.5.13
PHP: 7

**Comment by yingliangzhang** [comment]
Thanks @lloy0076, you might be right. I also tried `@push` also didn't work.

**Comment by tabacitu** [comment]
@yingliangzhang - Backpack\Base 0.9.0 (to be launched in a few days) will allow you to use ```@push``` inside any custom view. It has both sections and stacks. Register on [backpackforlaravel.com](https://backpackforlaravel.com/) and you'll receive the newsletter as soon as it's launched. You'll then be able to upgrade your project to the latest version and use this feature.

Cheers!

**Comment by tabacitu** [comment]
Until then, you can modify your ```layout.blade.php``` with this change: under  ```@section('after_scripts')``` insert a line ```@stack('after_scripts')```.

**Comment by yingliangzhang** [comment]
@tabacitu Nice. Thank you😀

**Comment by sdebarun** [comment]
This problem still persists. I am trying to add some custom scripts in custom create file but nothing is happening.

**Comment by tabacitu** [comment]
@sdebarun you should be able to use both ```@push``` and ```@section``` in your custom blade files that extend the default layout:

```php
@push('after_scripts)
  <script>alert('got here');</script>
@endpush
```


```php
@section('after_scripts)
  <script>alert('got here');</script>
@endsection
```

Double-check for typos when writing ```after_scripts```.
