### ISSUE TITLE
Apply a middleware on Login , Register, Forgot Password routes

### ISSUE THREAD

**Issue by michelvambattu** [Laravel-Backpack/CRUD#1268]
How to apply a middleware on Login , Register, Forgot Password routes ?

I'm using Backpack's default Auth controllers. Since the email is case sensitive, I have created a middleware for make it lowercase. And now the biggest question is, where could I apply this middleware??? Where could I find those routes?

Laravel 5.4 ,Backpack base version 0.7.25

**Comment by lloy0076** [comment]
In that version of Backpack, you'd configure Backpack to **not** set the default routes for authentication and configure the relevant routes yourself, adding the necessary midddleware.

**Comment by tabacitu** [comment]
https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-customizing-the-routes
