### ISSUE TITLE
Setting a timestamp and creator id to a Table Field

### ISSUE THREAD

**Issue by emperorjm** [Laravel-Backpack/CRUD#1271]
I like the idea of the table field as it allows for creation of a new record easily within the main CRUD without having to create a sub CRUD to manage the records.

I want to know if after the data is submitted if I can add additional fields such as a timestamp and a user_id to show which user created the table record?

**Comment by lloy0076** [comment]
In the relevant controller, you'd do this in the overridden `update` method.
