### ISSUE TITLE
Populating field value through a different model

### ISSUE THREAD

**Issue by emperorjm** [Laravel-Backpack/CRUD#1272]
I am combining multiple related items into one form so that the user does not have to create the entity from another CRUD screen before being able to select the record. I got that to work by manually getting the field values from the request object and saving the record before saving the main entity.

When someone clicks the **"Edit"** button those fields won't show because they are in another table. Is there are way to tell the "$this->crud->addField()" method to use a different model to bring back the results for particular fields?

Say for example;
$this->crud->addField([
            'name' => 'address_line_1',
            'label' => 'Address Line 1',
            'type' => 'text',
            **'model' => 'App\Address'**
        ], 'update');

**Comment by lloy0076** [comment]
The short answer is **no**.

You can use a [mutator](https://laravel.com/docs/5.6/eloquent-mutators) to achieve this.
