### ISSUE TITLE
Column visibility: Show only few columns by default in listing and add extra columns in list from ColumnVisibilty option of export button

### ISSUE THREAD

**Issue by bhavinvora** [Laravel-Backpack/CRUD#1274]
### What I did:
I have displayed few column data in view using setColumns method like this:

$this->crud->setColumns([
                           
                            (['name'=>'expire_date','lable'=>'Expire Date']),
                            (['name'=>'username','lable'=>'User']),
                            (['name'=>'prize_id','lable'=>'Prize']), /* New Column(must be hidden by default) */
                            (['name'=>'gifted_from','lable'=>'Gifted From'])  /* New Column(must be hidden by default) */
        ]);

### What I expected to happen:

now in the same list I want to add few more columns to be shown in list view. But by default this columns should be hidden in list view and what I expect that new added hidden columns (in the above list) i can make visible through "column visibility" options provided through $this->crud->enableExportButtons();

@tabacitu @tumf87 @OwenMelbz  Is there any way to do this in laravel backpack?

**Comment by bhavinvora** [comment]
I have posted this question in gitter chatroom and stackoverflow. Thank you for responding and guiding.

**Comment by tabacitu** [comment]
Thank you for being a good sport @bhavinvora . Short answer - at the moment there's no way to _easily_ do that. It would be an interesting feature though :-)

**Comment by bhavinvora** [comment]
@tabacitu thank you. I think this feature will be very useful. Kindly consider this as a new feature request and will try if we can develop this new feature as soon as possible.

**Comment by bhavinvora** [comment]
@tabacitu I have used your modules and later on implementing few features i came across few issues which are not available as of now in backpack. Above is one example, I have few more new feature requests or new issues which I found implementing new things in backpack.

**Comment by tabacitu** [comment]
@bhavinvora glad to hear that. Please submit each Feature Request / idea as a separate issue, so they can get separate feedback / PRs / etc. Cheers!
