### ISSUE TITLE
Password field is ignored when creating

### ISSUE THREAD

**Issue by Alexgmin** [Laravel-Backpack/CRUD#128]
The storeCrud method ignores the password field.
`$item = $this->crud->create($request->except(['redirect_after_save', 'password', '_token']));`

This doesn't happen on the updateCrud method.
`$this->crud->update($request->get($this->crud->model->getKeyName()),
                            $request->except('redirect_after_save', '_token'));`

On a basic user crud like this one:
```
[
    'name' =>'name',
],
[
    'name' =>'password',
    'type' => 'password',
],
[
    'name' =>'email',
    'type' => 'email'
],
```

You cannot create a password for a new user, but you can update the password of an existing user.

**Comment by tabacitu** [comment]
Hmm... you're right... 

@mariusconstantin2503 - do you remember what the purpose of that is?
@OwenMelbz  - you've recently been there. Your 2 cents? you think removing that from CRUD will break anything other than PermissionManager?

Thanks!

**Comment by OwenMelbz** [comment]
@tabacitu I cant see a clear cut reason for it being there, unless it was to prevent accidental plain text passwords being saved? or incase there was something within the Register method for new users that sign up from the register webpage?

**Comment by tabacitu** [comment]
Hi @Alexgmin ,

It's now fixed, you can the 'password' input like any others. Of course, for passwords you should probably [have a mutator in your model](https://laravel.com/docs/5.3/eloquent-mutators) to bcrypt() it.

Cheers!

**Comment by GregaUNK** [comment]
I am still having issues with that. When I create a new user and set its password, it's not working. I have to enter it again and resave it. Then it's working. What could be wrong? I have the latest Backpack Crud Pro.
