### ISSUE TITLE
count(null) with PHP7.2

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/CRUD#1281]
# Bug report

### What I did:

Update my PHP version to php 7.2

### What I expected to happen:

nothing special

### What happened:

errors:
* found one in buttons/revision.blade.php with `count($entry->revisionHistory)` if it's null.

## What to do:

We need to identify more issues like that in the backpack sources. This is an unfortunate breaking change from php 7.1 to 7.2... :/

**Comment by tabacitu** [comment]
Thank you @OliverZiegler ! Let me know if you encounter any more issues on 7.2.

**Comment by OliverZiegler** [comment]
should I create a PR with working on it?

probably we have more points where count will not work as it did...
as of the php 7.2 changelogs I don't think there will be other issues...
but hey: "who knows" 😅

**Comment by tabacitu** [comment]
Yes, please do.

Always a pleasure to tackle PHP compatibility issues. But considering PHP 7.2 is so freaking fast... I think it's worth it.

**Comment by lloy0076** [comment]
PHP 7.2 breaks so many packages, though - I'd hardly call a PHP error page **fast** except if one measures **fast** by how quickly one's web -app/-page crashes.

**Comment by tabacitu** [comment]
Yup, that's why in ```.travis.yml``` I've allowed PHP 7.2 to fail. Interestingly... [it does NOT...](https://travis-ci.org/Laravel-Backpack/CRUD)

**Comment by indra1** [comment]
This is a known issue. There is a bug report opened on php and laravel. I reverted to 7.1 meanwhile

**Comment by tabacitu** [comment]
Guys, I've been running on 7.2 for a few months now, no issues. Plus TravisCI seems to be ok with everything. So I say this is ready to be closed.

Reopen if I'm wrong.

Cheers!
