### ISSUE TITLE
how to install for laravel 5.6  ? 

### ISSUE THREAD

**Issue by OdaiTu** [Laravel-Backpack/CRUD#1284]
hey
i want to ask how to install backpack CRUD for laravel 5.6 ?

**Comment by tabacitu** [comment]
There's a [section in the docs called "Installation"](https://laravel-backpack.readme.io/docs/install-on-laravel-55).

If it's your first time using Backpack, I heavily recommend you go through the "getting started" series by registering on [backpackforlaravel.com](https://backpackforlaravel.com). In ~25 minutes you'll understand how Backpack works & learn 90% of its features. It's an important step, that saves many hours down the road. We have a drip email course too (if you don't have time now).
