### ISSUE TITLE
Css won't get applied in datatable column. Is transmitted from server.

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/CRUD#1286]
I created a new column type and wanted to apply some css styles to it depending on the value.

```php
// Some logic to get the correct css class. $cssClass is never empty
<td class="{{ $cssClass }}">{{ $entry->{$column['name']} }}</td>
```

It gets transmitted `<td class="text-red">error</td>` but it won't appear in the table.

The table column is just `<td>error</td>` without the class. Altoughit it appears in the JSON response.

I'm using Laravel 5.5
"backpack/base": "^0.8",
"backpack/crud": "^3.3",

**Comment by tabacitu** [comment]
Hi @sheriffmarley ,

As far as I know, the DataTables jQuery library will strip the ```<td>```. Try replacing ```<td>``` with ```<span>``` in your custom column view. That should work.

```diff
// Some logic to get the correct css class. $cssClass is never empty
-<td class="{{ $cssClass }}">{{ $entry->{$column['name']} }}</td>
+<span class="{{ $cssClass }}">{{ $entry->{$column['name']} }}</span>
```

Cheers!
