### ISSUE TITLE
Problem belongsToMany query on search

### ISSUE THREAD

**Issue by xdasty** [Laravel-Backpack/CRUD#1291]
# Bug report

this is the query where the problem occurs:

SQL: select * from `type` where exists (select * from `categories` inner join `type_has_categories` on `categories`.`id` = `type_has_categories`.`categories_id` where `type`.`id` = `type_has_categories`.`type_id` and `type_has_categories`.`categories_id` = ) and exists (select * from `categories` inner join `type_has_categories` on `categories`.`id` = `type_has_categories`.`categories_id` where `type`.`id` = `type_has_categories`.`type_id` and `categories_id` = 1) limit 25

### What I did:

I'm adding a search filter:

// Controller
-------------------------------------------------- -------------
$this->crud->query->whereHas('categories', function ($query) use ($value) {
	$query->where('categories_id', '1');
});

or

$this->crud->addClause('whereHas', 'categories', function($query) {
        $query->where('categories_id', '=', '1');
});
-------------------------------------------------- -------------

// model type
-------------------------------------------------- -------------
public function categories()
{
	return $this->belongsToMany('App\Models\Categorie','type_has_categories','types_id','categories_id');
}
-------------------------------------------------- -------------

### What I expected to happen:

I wanted the list of types that belonged to the categorie 1

### What happened:

the query does not return anything because it has an error:
- `type_has_categories`.`categories_id` = ) (is missing)

looking at the query I think it can be simplified

---------------------------
PHP Version 7.2.1
Laravel Framework 5.5.39
backpack/base 0.8.9
backpack/crud 3.3.12
backpack/generators 1.1.13

any suggestions?

**Comment by xdasty** [comment]
I think I found the problem
will update

**Comment by xdasty** [comment]
I reviewed the code, I recalled a superclass, but the id did not pass
now solved

**Comment by tabacitu** [comment]
Great to hear that @xdasty . Hope it helps someone. Ok to close this, right? Doesn't sound like a bug in the framework.

Cheers!
