### ISSUE TITLE
Irregular primary key columns causing some problems

### ISSUE THREAD

**Issue by emperorjm** [Laravel-Backpack/CRUD#1300]
# Bug report
There a bug within the system that does not show a column if the primary key is Capitalized. For example I have an application that has a "currency_codes" table but the Primary key is "Currency_Code" of type Varchar(20). Irregular yes but I can't change it so I have to get Laravel working with it.

### What I did:
I wanted to show the Primary Key column "Currency_Code" and it just would not show using the following:

`$this->crud->addColumn([
            'name' => 'currency_code',
            'label' => 'Curr. Code',
            'type' => 'text',
        ]);`

I tried everything I could but then decided to change the **name** of the column within the table to "**currency_code**" and it worked. Once I change the column name back to "Currency_Code" and set back the primary key in the model to "Currency_Code" and the same thing for the name property in the addColumn function the column disappears from the listing view. The strange this is, if I set the primary key in the model to "currency_code" the column is shown in the list view but no data is shown.

### What I've already tried to fix it:
Within the crud\src\PanelTraits\Columns.php file I see where the "hascolumn" does a check using the
"in_array" function which is case sensitive "in_array($name, $columns)" so I thought that might be the issue but when I print out the $name and $columns values they show the same values.

Within the "addColumn()" function the "$column_with_details" array shows the following for that field to show that the table has the column:
[
  "name" => "Currency_Code"
  "label" => "Curr. Code"
  "type" => "text"
  "key" => "Currency_Code"
  "tableColumn" => true
]

**Comment by emperorjm** [comment]
Did some additional debugging and I realize that within the $column_with_details array was modifying the "Currency_Code" array later down:

 "Currency_Code" => array:10 [▼
    "label" => "Currency Conv. Rate"
    "type" => "select"
    "name" => "Currency_Code"
    "entity" => "current_currency_rate"
    "attribute" => "Conv_Rate"
    "model" => "App\Models\Currency\CurrencyRate"
    "key" => "Currency_Code"
    "tableColumn" => true
    "orderable" => true
    "searchLogic" => true
  ]
  "currency_symbol" => array:7 [▶]
  "Description" => array:7 [▶]
  "Local_Currency" => array:7 [▶]
  "status_id" => array:10 [▶]
]

I then realized that I had a column later in the listing that was using the same name as the Currency Code column because that column uses a select list and the Currency_Code was the means connecting the two tables.

So I found this section of the documentation to use the same name for multiple columns and it works: https://laravel-backpack.readme.io/docs/advanced-features#section-multiple-columns-with-the-same-name. This took me hours to figure out.

**Comment by tabacitu** [comment]
Sorry to hear this was an annoyance to you @emperorjm . Thanks for sharing your solution - it might save hours for someone who's having the same issue.
