### ISSUE TITLE
On saving a record with a relation an update is being done on the relation

### ISSUE THREAD

**Issue by emperorjm** [Laravel-Backpack/CRUD#1301]
# Bug report
I have a CRUD that allows for saving a record to a **"user_groups"** table. This table has a "user_id" linked to the "users" table and a **"group_id"** linked to the **"groups"** table. I have created two select2 fields to get the list of records from the respective tables.

When I am saving a new User Group record the record is saved in the database but I am getting an error that column "group_id" is not found in the "groups" table when the following update is being done "Update groups set updated_at=2018-03-25, group_id = 3 where id = 3".

This update is not suppose to happen and all this started with the use of the latest Updated version of Backpack 3.4.2. This was not happening before I ran that update.

### Backpack, Laravel, PHP, DB version:
Backpack Crud: 3.4.2
Laravel: 5.5
PHP: 7.1.11
DB: Maria DB 10.1.28

**Comment by tabacitu** [comment]
On it! Thank you for reporting this @emperorjm !

**Comment by tabacitu** [comment]
Hi @emperorjm ,

This is a bit atypical... ```user_groups``` sounds like a connection table to me, which is handled automatically by CRUD. I assume:
- you have the proper relations on the Group and User models
- you have Crud Panels for the Group and User entities

In this case, people don't _usually_ create a CRUD for user_groups too. That information is handled automatically by the Group and User CRUDs. I have never seen anyone create a CRUD for that connection table.

I might not understand your use case right, though.

---

That being said, the two select2s should work anyway, even if it's atypical. Can you please copy-paste your UserGroup model, UserGroupCrudController and Group model? Might be a misconfiguration - maybe there's a ```group_id``` as fillable on the Group model or something.

Cheers!

**Comment by emperorjm** [comment]
It's a bit atypical compared to most of the implementations that would require a pivot table but they require some additional information to be placed on the pivot table like if the group is the primary group and the expiry date for each group. So it makes sense to create the CRUD for the pivot table in this case unless there is a better option:

On the Group model I only had the guardered set t: **protected $guarded = ['id'];** which means that all the other fields should be fillable. Based on your response above I decided to set the fillable fields manually and it now works.

Once I remove the fillable fields and just set the guarded it fails with that additional update.

**Comment by tabacitu** [comment]
Got it. Yes, imho ```$fillable``` is always safer than ```$guarded```.
