### ISSUE TITLE
Array to string conversion on show template

### ISSUE THREAD

**Issue by mserralta** [Laravel-Backpack/CRUD#1303]
# Bug report

The show controller sets all columns from DB to show them in show template. In AutoSet Trait method getFieldTypeFromDbColumnType sets to textarea when a string or text in database is found.

This text can be casted toJson or array inside Model, then textarea column partial fails.

### What I expected to happen:
I expected my array was printed

### What happened:
Array to string conversion FatalException

### What I've already tried to fix it:
In crud/resources/views/columns/textarea.blade.php I added:

@if(is_array($entry->{$column['name']}))
    @include('backpack::crud.columns.array')
@else
    <td>{!! $entry->{$column['name']} !!}</td>
@endif

### Backpack, Laravel, PHP, DB version:
backpack/base                         0.8.9              
backpack/crud                         3.3.17

**Comment by tabacitu** [comment]
Hi @mserralta ,

Thank you for the PR, but the ```textarea``` column isn't supposed to show arrays - that's what the array column is for. If we'd go this route, ```textarea``` would also need to support objects etc. And that's beyond the purpose of the ```textarea``` column, I'm afraid.

Cheers!

**Comment by mserralta** [comment]
Yeap! You're right. The problem is when you have a column in database
called, for instance, "images" which at the same time it is a
browse_multiple field type.

Inside CrudController::show it executes $this->crud->setFromDb() and it
deduces "well, *images *attribute is a text, so I will use textarea partial
to render that column".

Images in DB is really a text or string but this attribute is casted to
array. So when trying to render the textarea column partial you got: Array
to string conversion (View:
.../vendor/backpack/crud/src/resources/views/columns/textarea.blade.php)

You're right that my solution is mixing two different concepts but it is
clear some logic whould be added to some part to avoif this behaviour I've
described. I can do it if you tell me where would you work with it.

Cheers!



2018-03-28 7:41 GMT+02:00 Cristian Tabacitu <notifications@github.com>:

**Comment by tabacitu** [comment]
Well I think this could be mostly solved by the next generators update, which will probably no longer use ```setFromDb()``` by default, but use an ```addField()``` for each column in the db. That way you'd be able to easily change "textarea" to "array" - just change one word in one line. I recommend you do the same for your project - use ```addField()```s instead of ```setFromDb()```, like so: https://laravel-backpack.readme.io/docs/2-the-anatomy-of-a-crud-10-minutes
