### ISSUE TITLE
Browse button in ckeditor field is missing when upgrade

### ISSUE THREAD

**Issue by mics8128** [Laravel-Backpack/CRUD#1309]
# Bug report

### What I did:
upgrade backpack from 3.3 to 3.4, follow documents.

### What I expected to happen:
Field type ckeditor elfinder button should be there

### What happened:
Field type ckeditor elfinder button is missing
![image](https://user-images.githubusercontent.com/1339265/38008931-26ca8ef8-3284-11e8-8329-bf41a769a274.png)

### What I've already tried to fix it:
i tried below:
composer update

republish assets
> 8. Delete your public/vendor/backpack and public/vendor/adminlte folders; we will republish them shortly;
> 9. Run php artisan backpack:base:install; this might take a few minutes, but it will republish all assets needed;
already installed elfinder, every other field need elfinder part is normal.

and

> php artisan elfinder:publish

### Backpack, Laravel, PHP, DB version:
backpack/base 0.9.1
backpack/crud 3.4.2
Laravel v5.5.39
PHP 7.2.3 (cli) (built: Feb 28 2018 05:47:26) ( ZTS MSVC15 (Visual C++ 2017) x64 )
DB Ver 10.2.13-MariaDB for Win64 on AMD64 (mariadb.org binary distribution)

I missing any part of upgrade?

**Comment by mics8128** [comment]
Update: 
i tried to install fresh new project (use laravel 5.5)
and install newscrud as package.
that button still missing.

**Comment by tabacitu** [comment]
@mics8128 , thanks a lot for reporting this. AND providing a solution. This is great - I had no idea this was happening, must have slipped through the cracks.

Merged, thanks a lot! Cheers!
