### ISSUE TITLE
Option to enable row number in the first column

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/CRUD#1314]
Hi everyone!
I needed a feature like this for my project so I implemented.
I tried to do it on the client side, using [DataTables API - Index column](https://datatables.net/examples/api/counter_columns.html) but since backpack tables are fed by ajax, there is no easy way to do it on the client.

So I implemented this way (very similar to the details row):

**CrudPanel.php**

    public $index_column = false;

**PanelTraits/Read.php**
_Methods to enable and disable the index column_

    public function enableIndexColumn() ...
    public function disableIndexColumn() ...

**app/Http/Controllers/CrudFeatures/AjaxTable.php**
_Calculates the `$startIndex` based in already existing inputs from the request_

    public function search() {
    ...
    $startIndex = $this->request->input('start') ?: 0 * ($this->request->input('length') ?: 0);
    return $this->crud->getEntriesAsJsonForDatatables($entries, $totalRows, $filteredRows, $startIndex);

_`$startIndex` is a new parameter in `getEntriesAsJsonForDatatables`_

**PanelTraits/Search.php**
_`getEntriesAsJsonForDatatables` receives the `$startIndex` and sends it to `getRowViews()` while is also incrementing it in the for cycle_

    $rows[] = $this->getRowViews($row, ++$startIndex);

_`getRowViews` adds the $index to the beginning of the row itens array in case the index column is enabled_

    public function getRowViews($entry, $index)
    {
        $row_items = [];
        if($this->index_column)
                $row_items[] = $index;

**resources/views/list.blade.php**
_List will add a `<th>` dom element to the table header and footer, after validating the index column is enabled_

    <thead>
    ...
    @if ($crud->index_column)
        <th data-orderable="false" style="width: 12px;"></th>
    @endif

    <tfoot>
    ...
    @if ($crud->index_column)
        <th></th>
    @endif

By adding `$this->crud->enableIndexColumn();` on CrudController, here is the result:

![index_column](https://user-images.githubusercontent.com/1838187/38258559-b5203ede-375a-11e8-8048-8965512aee22.PNG)

If you guys think this is OK I can create a PR, if you have any suggestions I can change it.

_Edit: this was discussed here: #1096_

**Comment by AbbyJanke** [comment]
Hi @promatik just quick question that i' am unclear of. Is it the record ID within the database you are looking to display or simply the Index ID of the record from the total number of search results?

**Comment by promatik** [comment]
Hi @AbbyJanke!
This is the index, if you want the serialized ID, you just need to add a column of the ID.

In my case, I have a table without a serialized ID, and I want it always ordered by a "score" column, so by having this index, I can have a representation of the position of each record, without having it on the database, and without extra query parameters.
With this option, you can reorder the table, the column will always be an index.

**Comment by AbbyJanke** [comment]
Hi @abewartech there are a lot of features requests and improvements that the core team is looking to add. I try to cover some PRs and make additions as i can. but if @promatik or yourself is open to submitting it will help speed up the process.

**Comment by tabacitu** [comment]
Just merged the functionality for this into ```master```. Check it out here: https://github.com/Laravel-Backpack/CRUD/pulls

It'll be available in a few hours/days, after I bundle it with a few more non-breaking changes. Thanks a lot for your work on this @promatik !

Have a good one!
