### ISSUE TITLE
Select Field for Polymorphic Relationship

### ISSUE THREAD

**Issue by simplusgroup** [Laravel-Backpack/CRUD#1317]
Hey @tabacitu!

Do you have an approach for polymorphic relationships in a select field?

Using the Laravel example... if I have a comment, and I want to be able to select either a post or a video to apply it to, I would need a selectbox that produces results from both models. 

For the current selection of selectboxes, even the ajax options, they require a single model to be defined. Have you encountered this issue before? Something in the works?

Thanks for your help!

James

**Comment by pxpm** [comment]
Dunno if it will help you, or if it is the write solution ... i use custom field type and use this code:

```$this->crud->addField([
								'label' => 'Status', 
								'type' => 'select2', 
								'morph' => true,
								'name' => 'status', 
								'entity' => 'status', 
								'attribute' => 'visible_name', 
								'model' => 'App\Models\Status', 
								'pivot' => true,
								'scope' => function ()
								{
							return Status::WithDomainScope('App\Models\Article');
								}
						
                            ],'create');```

```
public function scopeWithDomainScope($query, $scope)
	{
		return $query->whereHas('domains', function($q) use ($scope) {
			$q->where('domain',$scope);
		});
	}
```

In this example i have "statable" entities ...

**Comment by simplusgroup** [comment]
Awesome, thank you!  





On Wed, Apr 4, 2018 4:46 PM, Pedro Martins notifications@github.com  wrote:
Dunno if it will help you, or if it is the write solution ... i use custom field
type and use this code:

								'label' => 'Status', 
								'type' => 'select2', 
								'morph' => true,
								'name' => 'status', 
								'entity' => 'status', 
								'attribute' => 'visible_name', 
								'model' => 'App\Models\Status', 
								'pivot' => true,
								'scope' => function ()
								{
							return Status::WithDomainScope('App\Models\Article');
								}
						
                            ],'create');```



public function scopeWithDomainScope($query, $scope)
{
return $query->whereHas('domains', function($q) use ($scope) {
$q->where('domain',$scope);
});
}


In this example i have "statable" entities ...
