### ISSUE TITLE
setLocale called on Collection with a 1:1 relationship with hasTranslation trait

### ISSUE THREAD

**Issue by mamarmite** [Laravel-Backpack/CRUD#1321]
# Bug report
When I create a new entry for a Model that has a relation to Model that have hasTranslation trait. I got an error that setLocale on Collection doesn't exist.

### What I did:
Store an entry on a Model with one on one relation to a model that have hasTranslation trait.

### What I expected to happen:
Save the entry.

### What happened:
Error : setLocale on Collection doesn't exist.

### What I've already tried to fix it:
Temporarely I add in `Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations __call method` a check of is_array() and is_object and assume there is only one.
```
if (is_array($item)) {
  $item[0]->setLocale($translation_locale);
} elseif (is_object($item)) {
  $item[0]->setLocale($translation_locale);
} elseif ($item) {
  $item->setLocale($translation_locale);
}
```

### Backpack, Laravel, PHP, DB version:
- Laravel : 5.6
- BP/Base : 0.9.2
- BP/CRUD : 3.4.4
- PHP: 7.2
- DB: MySQL 5.7

**Comment by OliverZiegler** [comment]
Also encountered this issue today. Currently not quite sure when this first appeared but I think I provided a working solution to fix this one.

@mamarmite please take in account that your solution will break the translation feature for 1:n and n:n relations I think.

**Comment by OliverZiegler** [comment]
Closing this issue in favour of PR #1330

**Comment by mamarmite** [comment]
@OliverZiegler  Thanks! Yep, I did that to pass to the next step, And I was in a 1:1 rel.

**Comment by tabacitu** [comment]
Merged and tagged. Thank you so much @OliverZiegler !
