### ISSUE TITLE
model_function dosent work after update

### ISSUE THREAD

**Issue by OdaiTu** [Laravel-Backpack/CRUD#1322]
# Bug report

### What I did:

update backpack:crud to 3.4
update backpack:base 0.9.2

### What I expected to happen:
every thing work fine

### What happened:

all is good but all the columns with type model_function that returned <a> tag now doesnt return anything
### Backpack, Laravel, PHP, DB version:

backpack:base 0.9.2
backpack:crud: 3.4
laravel : 5.6

**Comment by OdaiTu** [comment]
sorry guys its working but i have to remove the target="_black" alos removing inline style for the <a> tag
i still confused why this happens it was working in the past

**Comment by tabacitu** [comment]
Huh... that's very weird. No idea why that would happen after the update... Thanks for letting us know @OdaiTu !

**Comment by tabacitu** [comment]
Ouch. You're right. Done, thank you!
