### ISSUE TITLE
Nested CRUDs within Route Groups result in 404s for /edit and /delete but index and create both work

### ISSUE THREAD

**Issue by simplusgroup** [Laravel-Backpack/CRUD#1323]
# Bug report

Here is a detailed description with code:
https://stackoverflow.com/questions/49685758/laravel-backpack-404-no-query-results-for-model-on-cruds-nested-within-route-g

### What I did:
Using Route::Group with prefixes to nest cruds

### What I expected to happen:
Work as expected.

### What happened:
The first level of nesting is working as expected. However, the 2nd level does not work. 

### What I've already tried to fix it:
Many variations of prefixes and route configurations

### Backpack, Laravel, PHP, DB version:
Backpack v 3.4; Latest Laravel; PHP 7

**Comment by simplusgroup** [comment]
@tabacitu This was based on the Nested Resources blog post, which I believe I followed quite closely... works very well with first level CRUDs, just having an issue with edit and delete on 2nd/3rd level cruds

https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud

**Comment by simplusgroup** [comment]
OK... I may have solved this... 

I added this to the top of my crud to retrieve and store the user id from the route parameter: $this->crud->user_id = \Route::current()->parameter('user');

Then, I copied the edit($id) function from the CrudController class and overwrote the $id variable with my $this->crud->user_id. 

This seems to have worked. But, wondering if the CrudController should be revised to be able to deal with nested parameters. 

Thanks!

James

**Comment by jrpub** [comment]
A dirty solution here: #252 
linked also to #307 

@simplusgroup I agree, a better and native solution would be good.

**Comment by tabacitu** [comment]
@jrpub , thanks a lot for your solution! 

I've just implemented an official patch here: https://github.com/Laravel-Backpack/CRUD/pull/1339 , which I'll be merging after a bit more feedback & testing. Let me know what you think, and if it's a good fix for you guys. Cheers!
