### ISSUE TITLE
Responsive DataTables on/off toggle

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/CRUD#1327]
As of Backpack/Crud 3.4 we have this greatly improved responive UI with dataTables and a popup.

No one of our customers has a crud with about 20 columns and wants to scroll left/right again to see them all (without opening the popup).

Could we implement an easy way of toggling responsiveness on/off for some CRUDs?

**Comment by pxpm** [comment]
+1 thanks @axelzuzek for teh hack!

**Comment by tabacitu** [comment]
Totally agree @OliverZiegler - I see where this might be needed. Tested @axelzuzek 's solution and it worked for me - thank you @axelzuzek .

What would be a good name for this method? What do you think about one of these
- ```$this->crud->disableReponsiveList()```
- ```$this->crud->disableResponsiveTable()``` 
- ```$this->crud->disableResponsiveDataTable()```

Or maybe a 
- ```$this->crud->setTableResponsive(false)```; we could use ```getTableResponsive()``` in ```datatables_logic.blade.php``` and by default it would return ```true```;

?

Let me know what you think in this PR: https://github.com/Laravel-Backpack/CRUD/pull/1380

Cheers!
