### ISSUE TITLE
Soft Deletes

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#133]

**Comment by tabacitu** [comment]
We could easily achieve this by adding a new button in one of the existing button stacks, that says "[icon] Trash (25)". Upon click, this would go to the same page, but with the GET parameter ?deleted=1 or ?trash=1, where you'd see the soft deleted items and 
- an extra button in the "line" stack for each item, which would say "Recover from Trash" (or "Recover"?), which would work with AJAX, like the "delete" button does (confirmation, than Ajax);
- instead of the "Delete" button, a button that says "Delete from Trash", which would hard delete it (confirmation, than ajax);

A developer could enable this by specifying $this->crud->enableTrash(); Which would:
- addClause() to only show soft deleted items;
- set $this->crud->trash = true; which would make the "Recover from trash" and "Delete from trash" buttons visible;

We also need:
- the CrudController::recoverFromTrash() ajax method and route;
- the CrudController::hardDestroy() ajax method and route;
- to check if trashing a soft delete entry triggers a revision in the timeline;
- to check if untrashing a soft delete entry triggers a revision in the timeline;

**Comment by tabacitu** [comment]
Since we already need to introduce 2 more routes for the trash functionality, it might be better to move the extra logic we need from the CrudController::index() method to its own method. That would probably be cleaner. 

That would make the routes we need:
- GET    admin/product/trash -> getTrash()
- POST admin/product/trash/delete/4 -> deleteTrashItem()
- POST admin/product/trash/recover/4 -> recoverTrashItem()

We could encapsulate all these CrudController methods in a trait, called Trash. If we can put the previously mentioned $this->crud->enableTrash() logic in the boot() method of this trait:
- all the trash functionality would be contained in a Trait, a separate PHP file;
- using the trash functionality would still be a one-step process (just specify use Trash; in your ProductCrudController);

What bothers me is that this would register those 3 routes even for EntityCrudControllers that don't have the trash functionality. For a medium/big project, this would quickly become bothersome and fill up the _php artisan route:list_ with nonsense.

So I'm wondering: Would it make sense to make the route definition more complex, or would it just be a drag? I'm thinking of something like:
A) CRUD::resource('car', 'CarCrudController');
 - we keep it as it is, it registers all routes, including the new trash ones

B) CRUD::routes('car', 'CarCrudController') which would only register the absolute necessary (the CRUD routes) and would allow you to do something like this:
- CRUD::routes('car', 'CarCrudController')->withTrash();
- CRUD::routes('car', 'CarCrudController')->withReorder();
- CRUD::routes('car', 'CarCrudController')->withRevisions();
- CRUD::routes('car', 'CarCrudController')->withDetailsRow();
- CRUD::routes('car', 'CarCrudController')->withTrash()->withReorder()->withRevisions();

We could separate all these Route methods from the CrudServiceProvider, into a Trait (CrudRoutingServiceProvider), which we'd use on CrudServiceProvider to preserve backwards-compatibility. The resource() method would of course also live there.

Any feedback? Ideas? Complaints?

**Comment by OwenMelbz** [comment]
@tabacitu abstracting it into `withTrash` etc, does sound a nice way to keep it separated, however it just adds an extra barrier for users to figure out how to use it, but if thats okay, then seems a nice way to do it

**Comment by tabacitu** [comment]
Well... it would only do so for developers that hate having a bunch of useless routes. ```CRUD::resource('car', 'CarCrudController');``` would still work the same way, registering all the routes.

We'll come back here when we implement this, see if we see it a different way then.

Cheers!

**Comment by OwenMelbz** [comment]
I had just thought that the frontend of this could get linked in with the "filter" functionality? as the trash button would effectively be a filter?

**Comment by tabacitu** [comment]
So this can be easily achieved now using the [simple filter](https://laravel-backpack.readme.io/docs/filters#section-simple). In most cases this will be the code you'd be using:

```php
$this->crud->addFilter([ // simple filter
  'type' => 'simple',
  'name' => 'trashed',
  'label'=> 'Trashed'
], 
false, 
function() { // if the filter is active
    $this->crud->addClause('trashed'); 
} );
```

So I'll close this issue.

**Comment by aaranmcguire** [comment]
... Even with this, you don't get the custom buttons to restore or permanently delete. Correct? - If so, can this be re-opened? Depending on my time I may take this on.

**Comment by OwenMelbz** [comment]
You'd still need to make a "restore" custom button which would hit an endpoint to restore it

**Comment by aaranmcguire** [comment]
@OwenMelbz Would you be willing for this to be merged into master as an enhancement? so users could just say $this->crud->enableSoftDelete() (or similar) and everything is done for them.

**Comment by OwenMelbz** [comment]
Would be a nice feature :)

Although I'm nothing to do with the merging! I just make the occasional PR and lend a hand when I can

**Comment by jrbecart** [comment]
If someone need it, now it should be like this: (replace 'trashed' by 'withTrashed')

```php 
$this->crud->addFilter([ // simple filter
  'type' => 'simple',
  'name' => 'trashed',
  'label'=> 'Trashed'
], 
false, 
function() { // if the filter is active
    $this->crud->addClause('withTrashed'); 
} );`
