### ISSUE TITLE
Command backpack:crud:install mkdir() error on Windows 7 PRO x64

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#1333]
# Bug report

### What I did:

I tried to install backpack crud using command line tool. The error occurs when i say 'yes' to install elfinder.

### What I expected to happen:

Create a directory 'uploads' in public folder.

### What happened:

 Exception trace:

 1   Backpack\Base\app\Console\Commands\Install::executeProcess("mkdir -p public/uploads")
     C:\wamp\www\basetest\vendor\backpack\crud\src\app\Console\Commands\Install.php:51

### What I've already tried to fix it:

Nothing.

### Backpack, Laravel, PHP, DB version:

Laravel 5.6, Backpack 3.4, PHP 7.1, mysql db.

**Comment by pxpm** [comment]
Sorry, i will close this issue as it is already on issue tracker.

REFS: #1299

**Comment by tabacitu** [comment]
Thank you for helping us keep the issues clean @pxpm ! Kudos to you!
