### ISSUE TITLE
Datatable filter reset causes Uncaught RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by oranog** [Laravel-Backpack/CRUD#1335]
# Bug report

### What I did:
Hello, my model contains column named "date". It is in MySQL "Date" type. I would like to filter it with default filter method.
My code:
```
		$this->crud->addFilter(
			[
				'type' => 'date',
				'name' => 'date',
				'label'=> __('backend.date')
			]
		);
```

### What I expected to happen:
Properly working filters.

### What happened:
It works fine except for one thing.
If i push reset filter button, it causes following error in console and creating endless amount of ajax requests.

```
Uncaught RangeError: Maximum call stack size exceeded
    at y (jquery.dataTables.min.js:76)
    at Ba (jquery.dataTables.min.js:110)
    at jquery.dataTables.min.js:111
    at Za (jquery.dataTables.min.js:109)
    at s.<anonymous> (jquery.dataTables.min.js:111)
    at s.iterator (jquery.dataTables.min.js:99)
    at s.<anonymous> (jquery.dataTables.min.js:111)
    at s.rows (jquery.dataTables.min.js:102)
    at s.<anonymous> (jquery.dataTables.min.js:116)
    at s.row (jquery.dataTables.min.js:102)
```

### What I've already tried to fix it:
That only happens if data column is named "date", if i use column with different name it works fine, for certain reasons i cant just rename that column name for now, so any tips would be appreciated.
### Backpack, Laravel, PHP, DB version:
Backpack - 3.4
Laravel - 5.6
PHP 7.1

Thank you.

**Comment by tabacitu** [comment]
Hi @oranog ,

Thanks for the bug report. I can confirm that is happening, and I'll be working on it ASAP. As far as I can tell, this bug must have been introduced here: https://github.com/Laravel-Backpack/CRUD/commit/9602491865ecf4c46363afde41eb0784f8be0e4a

But I don't see how. On it!

**Comment by tabacitu** [comment]
Hi @oranog ,

Just fixed this, it's currently in PR https://github.com/Laravel-Backpack/CRUD/pull/1433
I'm going to close this issue as I'm going to merge the PR today.

Cheers! Thanks for letting us know about the issue.
