### ISSUE TITLE
how to get the current Admin id ?

### ISSUE THREAD

**Issue by OdaiTu** [Laravel-Backpack/CRUD#1340]
# Bug report

### What I did:

i want to check the current admin

### What I expected to happen:

get the id of admin

**Comment by tabacitu** [comment]
Hi @OdaiTu ,

You should be able to use ```backpack_user()->id``` anywhere inside your app, in the latest Backpack. It will also apply a custom authentication guard, if you've specified one in your ```base.php``` config file. If you're running an old Backpack\Base version, it's the normal ```Auth::user()```, with no auth guard applied.

Hope it helps.
Cheers!

**Comment by OdaiTu** [comment]
@tabacitu 
im not sure if i get it
right im using the last version
using backpack_user()->id gives me an call to undefined function
i have i users table and admins table
which i use is the admins table for backpack login and register
i want to send notifications to these admins base in there id`s 
so i can display the notifications for each admin base on his id

i did this 
 Auth::guard(admin)->user();

but i miss something here
i dont know what it is

**Comment by iMokhles** [comment]
check your guard in config/backpack/base.php config file

**Comment by OdaiTu** [comment]
@iMokhles  its admin

**Comment by sagar03d** [comment]
`use Auth;`
`Auth::guard('admin')->user()->id;`

**Comment by emilushi** [comment]
For me

`Auth::guard('backpack')->user()` work perfectly.

**Comment by sh-eer** [comment]
> `use Auth;`
> `Auth::guard('admin')->user()->id;`

I have been working on something for 2 hours and your code helped me get it done man. Bless you
