### ISSUE TITLE
select2_from_ajax_multiple - if using a pivot table for M-M, why need to specify column name

### ISSUE THREAD

**Issue by simplusgroup** [Laravel-Backpack/CRUD#1345]
# Bug report

### What happened:

The Many to Many Ajax field type requires column name for connected entity even though when using pivot one doesn't exist.

[
            // n-n relationship
            'label' => "End", // Table column heading
            'type' => "select2_from_ajax_multiple",
            'name' => 'city_id', // the column that contains the ID of that connected entity
            'entity' => 'city', // the method that defines the relationship in your Model
            'attribute' => "name", // foreign key attribute that is shown to user
            'model' => "App\Models\City", // foreign key model
            'data_source' => url("api/cities"), // url to controller search function (with /{id} should return model)
            'placeholder' => "Select a city", // placeholder for the select
            'minimum_input_length' => 2, // minimum characters to type before querying results
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
 ]

### What I expected to happen:

'Name' would be an optional field if 'pivot' = true.

### What I've already tried to fix it:

Manually duplicating and adjusting the field code

### Backpack, Laravel, PHP, DB version:

Latest stable of all

**Comment by simplusgroup** [comment]
Sorry! Stupid mistake on my side... caught it shortly after I posted this, wish I could delete ;-)

**Comment by tabacitu** [comment]
No problem, thanks for closing it. Cheers!
