### ISSUE TITLE
Default checked

### ISSUE THREAD

**Issue by wtime** [Laravel-Backpack/CRUD#135]
Hi, is it possibile to set the checkbok default value to checked? Many thanks. Ps. Great job!!!

**Comment by OwenMelbz** [comment]
Not currently! However you could copy the `/vendor/backpack/crud/src/resources/views/fields/checkbox.blade.php` into `/app/resources/views/vendor/backpack/crud/fields/checkbox.blade.php`and over-write it with the above pull request.

However you could wait for @tabacitu to see if he wants to merge the [PR#137](https://github.com/Laravel-Backpack/CRUD/pull/137) and wait for it to be released?

**Comment by tabacitu** [comment]
Bam!! Merged :-) That's some great teamwork right there :-)

You can now use "default" => 1

Great job, guys.
Cheers!

**Comment by wtime** [comment]
WoW! Many thanks!
