### ISSUE TITLE
no way to recover relation 1 & 1 , some ideas ?

### ISSUE THREAD

**Issue by FelipeOneHouse** [Laravel-Backpack/CRUD#1359]
# Bug report

### What I did: 
i have a relation 1 & 1 in  in ddbb, table children have a foreign key to parent, i want retrieve the info of parent in a view

### What I expected to happen:
I want show the parent fields linked, the we can say that the info is cutted in 2 tables but is the model eloquent, then i have a first table with the basic info, and i have a second table with full details , more of 30 colums, and in the first the parent i have 5 fields , the foreign key is defined on children, i want load the info in same time and can edit save in the same view

### What happened:
No way to do undestood the library what i want load the related parent, relation have been added 
public function options()
    {
        return $this->hasOne('App\PortfolioOption', 'id_Portfolio');
    }
If i update same if i put the name of key
$this->crud->with('id_PortfolioFK'); // eager load relationships
or 
$this->crud->with('options'); // eager load relationships

i have message

### Backpack, Laravel, PHP, DB version:
backpack/backupmanager                1.4.0              Admin interface for managing backups in B...
backpack/base                         0.9.3              Laravel Backpack's base package, which of...
backpack/crud                         3.4.6              Quickly build an admin interface for your...
backpack/generators                   1.1.13             Generate files for laravel projects
backpack/langfilemanager              1.0.25             An interface to edit language files, for ...
backpack/logmanager                   2.3.18             An interface to preview, download and del...
backpack/pagemanager                  1.1.23             Create admin panels for presentation webs...
backpack/permissionmanager            2.1.26             Users and permissions management interfac...
laravel version 5.6
 Server type: MariaDB
Server version: 10.1.30-MariaDB - Source distribution
Protocol version: 10

**Comment by tabacitu** [comment]
Hi @FelipeOneHouse ,

Actually, 1-to-1 relationships have been supported for a month or so, but they're a "hidden feature" right now. You should be able to use your secondary table columns just like if they were in your primary table, by using a dot notation for the ```entity```. Ex:

```php
$this->crud->addField([
            'type' => 'select2',
            'label' => 'Category',
            'name' => 'category_id',
            'entity' => 'productDetails.category', // here's where the magic happens
            'attribute' => 'name',
        ]);
```

Does it work for you like that?
