### ISSUE TITLE
[IE] [javascript] file datatables_logic.blade.php line 18 : keyword function must be used.

### ISSUE THREAD

**Issue by mamarmite** [Laravel-Backpack/CRUD#1364]
# Bug report
[IE] [javascript] file datatables_logic.blade.php : keyword function must be used line 18

### What I did:
Run crud list view in IE 11

### What I expected to happen:
Loading as expected

### What happened:
error in console (js)

### What I've already tried to fix it:
change the line: 18 to : 
`responsiveToggle: function(dt) {` instead of `responsiveToggle(dt) {`

### Backpack, Laravel, PHP, DB version:
BP 3.4.6
Laravel : 5.6
Php : 7.1

Sorry, I was to lazy for a pull request. 
Was is the method you like the best for PR ? Branches for each issue ? Or another way ?

Thanks and have a good day

**Comment by mamarmite** [comment]
Already a PR #1306, by @Nutbolt52, for this.

**Comment by tabacitu** [comment]
Merged! Thanks a lot @mamarmite and @Nutbolt52 !
