### ISSUE TITLE
Multibyte title is lowercase in page title

### ISSUE THREAD

**Issue by justnero-ru** [Laravel-Backpack/CRUD#1370]
# Bug report
`ucfirst` doesn't work with multibyte strings
### What I did:
I've created CRUD controller and changed entity names:
`$this->crud->setEntityNameStrings( 'книга', 'книги' );`
### What I expected to happen:
Title on list page should be `Книги :: Backpack Admin`
### What happened:
Title is `книги :: Backpack Admin` 
### What I've already tried to fix it:
I have overloaded method `Backpack\CRUD\app\Http\Controllers\CrudController@index`
Line 67 was:
`this->data['title'] = ucfirst($this->crud->entity_name_plural);`
Became: 
`this->data['title'] = mb_convert_case($this->crud->entity_name_plural, MB_CASE_TITLE);`
### Backpack, Laravel, PHP, DB version:
Backpack CRUD 3.4.6
Laravel 5.6.18
PHP 7.2.5 
MySQL 5.7.21

**Comment by tabacitu** [comment]
Thank you @justnero-ru - let's continue the conversation in your PR. Cheers!
