### ISSUE TITLE
# Oops Please fill out the form correctly : The akhir m is not a valid date.

### ISSUE THREAD

**Issue by enhemh** [Laravel-Backpack/CRUD#1373]
# Bug report

i import thousand row in mysql, where date format is yyyy-mm-dd, after i create new module with this new imported table, update form in datepicker get message invalid validation : Please fill out the form correctly : The akhir m is not a valid date, i try to create new row in form, and update form is work fine,. 

My question is when the date row imported from mysql (phpmyadmin) , that date can't updated in form update by datepicker....

**Comment by tabacitu** [comment]
@enhemh - consider using casts on your models. That's a Laravel best practice. There's a special cast for dates - [the $dates property](https://laravel.com/docs/5.6/eloquent-mutators#date-mutators).
