### ISSUE TITLE
Internet Explorer - jquery error "crud is not defined"

### ISSUE THREAD

**Issue by nielvrom** [Laravel-Backpack/CRUD#1376]
# Bug report

### What I did:

Open admin panel in Internet Explorer. Go to an entity to see all the results.

### What I expected to happen:

See an overview all of the rows of that model in my database.

### What happened:

The data didn't show and a jquery error was shown in console. Jquery error: "crud is not defined". 

![afbeelding1](https://user-images.githubusercontent.com/2797731/39634189-6d56f278-4fba-11e8-8c73-33e9ec3c5689.png)

### Backpack, Laravel, PHP, DB version:

- Laravel version: 5.5
- Backpack version: 3.4
- PHP version: 7.2

**Comment by tabacitu** [comment]
PS. Just merged a patch for IE11 - https://github.com/Laravel-Backpack/CRUD/pull/1306

Please check if after a ```composer update``` you're still having the issue.

Cheers!

**Comment by mamarmite** [comment]
This bug happen before #1306. 
On my side the console got more errors, but in the end, crud wasn't defined.
Tested in IE11 Admin LTE works like Bootstrap 3.3.7 so > 9. 
I wish I can forget about IE and old safari.

**Comment by tabacitu** [comment]
Hi guys,

Just got to a Windows computer and tested it - worked fine for me:
![img_7340](https://user-images.githubusercontent.com/1032474/40924196-513dc9a4-681f-11e8-8b83-05c473164cab.jpeg)

After a ```composer update```, maybe also try ```php artisan cache:clear``` and running in an Incognito Window?

Cheers!
