### ISSUE TITLE
The "records per page" combo only works with default values

### ISSUE THREAD

**Issue by androidedev** [Laravel-Backpack/CRUD#1378]
# Bug report
Don't sure if is a bug or working as intended.

The "records per page" combo is empty if you set PageLength to a size diferent of (10,25,50,100,all)

### What I did:
In setup() put :

this->crud->setDefaultPageLength(14);

### What I expected to happen:
The combo should show 14, perhaps  (10,14,25,50,100,all) or something like that

### What happened:
The combo is blank (unable to select the value). The page size is set to 14 and paginator works ok, but you can't establish a "14" value again couse is not in combo values.

### What I've already tried to fix it:
None, is not something I need or think is important, simply open the issue just in case the creators are not aware of it.

### Backpack, Laravel, PHP, DB version:
"backpack/crud" : "version": "3.4.6",
"laravel/framework": "5.5.*|5.6.*",

**Comment by androidedev** [comment]
@mamarmite wow thx for the quick response. I wonder why this is not in the default code base, seems a useful feature and you have coded it yet. ;)

**Comment by tabacitu** [comment]
Hi @androidedev ,

Thanks for letting us know about this, we had no idea. 

@mamarmite , your fix worked great, I've just applied it on master here https://github.com/Laravel-Backpack/CRUD/commit/30a69853b84b0ba6d027dbf31233f1fc9cd6471f and it'll be available in the next patch version, later today, with a ```composer update```.

Cheers!
