### ISSUE TITLE
Check that all fields have the optional field attributes

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#138]
- default
- hint
- attributes
- wrapperAttributes

Also, these optional attributes should be documented.

**Comment by OwenMelbz** [comment]
@tabacitu I noticed whilst looking at this, the `parentAttributes` you mention is actually called `wrapperAttributes` which is camelish cased, most other addField properties are underscored, so just something to think about :)

**Comment by OwenMelbz** [comment]
Think I've made a good start -> https://github.com/Laravel-Backpack/CRUD/pull/155 just need to have somebody run over them I guess to check!

**Comment by tabacitu** [comment]
Oh, yeah, ```parentAttribute``` was the first name for that, it didn't stick :-)

Ok, great, I will check, thank you!
