### ISSUE TITLE
"Property [episodes] does not exist on this collection instance'' on hasMany relationship field

### ISSUE THREAD

**Issue by paperscissors** [Laravel-Backpack/CRUD#1381]
# Bug report

### What I did:
Trying to create a field for a `hasMany<->belongsTo` relationship on my Podcast CRUD controller, following the documentation on https://laravel-backpack.readme.io/docs/crud-fields#section-select2_multiple-n-n-relationship

```
$this->crud->addField([       // Select2Multiple = n-n relationship (with pivot table)
            'label' => "Episodes",
            'type' => 'select2_multiple',
            'name' => 'episodes', // the method that defines the relationship in your Model
            'entity' => 'episodes', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'tab' => 'Details',
            'model' => "App\Models\Episode", // foreign key model
            'pivot' => false, // on create&update, do you need to add/delete pivot table entries?
        ], 'update');
```

###Podcast.php model
```
public function episodes()
    {
        return $this->hasMany('App\Models\Episode');
    }
```
###Episode.php model
```
public function podcast() {
        return $this->belongsTo('App\Models\Podcast');
    }
```

### What I expected to happen:
Field should pull in Episode relationships and display them on the `select2_multiple` field.

### What happened:
Get exception "Property [episodes] does not exist on this collection instance."

### What I've already tried to fix it:
Tried the implementation of 1-n relationships instead, but then just get errors about the foreign key: Property [etc etc etc] does not exist on this collection instance.

Tried changing name and entity to singular version of the name of the relationship. Then the edit page loads and the select2 field is loading in Episode model results for me to select. I hit save and I get this exception, because there is no episode relationship: 

`Method Illuminate\Database\Query\Builder::episode does not exist.` The `updateCrud` method also appears to be trying to insert a new model instead of just setting the proper podcast_id on the selected models on an update.

I've tried subsequently changing the relationship method to match singular, but I get the same error.

### Backpack, Laravel, PHP, DB version:

"php": "^7.1.3",
"backpack/crud": "^3.4", 
"laravel/framework": "5.6.2"
mysql  Ver 14.14 Distrib 5.7.20

**Comment by tabacitu** [comment]
Hi @paperscissors ,

N-n relationships seem to work out of the box for me, so it must be some misconfiguration on your project that's the problem. On first sight, it looks like your n-n relationship should have ```belongsToMany('App\Models\Podcast')``` instead of ```belongsTo('App\Models\Podcast')```. [Just like the Laravel docs recommend](https://laravel.com/docs/5.6/eloquent-relationships#many-to-many).

Does it work for you then?

Cheers!
