### ISSUE TITLE
Making this package an official laravel package (BASE + CRUD + Others)

### ISSUE THREAD

**Issue by bab55z** [Laravel-Backpack/CRUD#1386]
### This is not a bug
# Making this package an official Laravel package
Among all laravel admin packages i can find, i think this one is by far the most robust, flexible and advanced, especially the **CRUD** which offers tons of field types. (this is my own reflexion, please comment if you agree or not with concrete examles)

# My idea
Because of the arguments in the first point, I think [@taylorotwell](https://github.com/taylorotwell) , the laravel) creator should make this package official. I don't know how both creator of this package and laravel creator would arrange the deal.

# Why 
Laravel is missing a robust and reliable admin panel. This is a disadvantage when compared to **Symfony** and other frameworks. **Laravel** having an **official admin panel** which is robust and flexible will blow **Symfony** and other frameworks far far away :)

## What do you think of this?

Thanks

**Comment by tabacitu** [comment]
Hi @bab55z ,

I get butterflies in my stomach when I think of becoming **_the official_** Laravel admin panel, so thank you so much :-) That's definitely our short-term aim. I'm not sure how this fits into his bigger picture, but I hope it does :-) I've never proposed this to Taylor, so I don't know what he thinks about that, but I'll be sure to mention it when we talk.

I do think we still have some work to do before we can make such a claim. The way I see it, and judging by the feedback we've gotten so far, we need at least ```theme support in Base```, ```matrix/repetable/table fields (CRUD in CRUD)``` and ```bulk actions```, to finally be able to say we're at 99% feature-completeness. So I hope we'll be able to make such a proposal in ~6 months, when we have those features.

:-) Thanks a lot for mentioning this, it's good to know others see the same path as I do.

Cheers!

**Comment by bab55z** [comment]
Hummm, it seems [@taylorotwell](https://github.com/taylorotwell) went here in furtive mode.
[Laravel Nova](https://nova.laravel.com)

**Comment by tabacitu** [comment]
Thanks @bab55z . We're well aware of it :-))

We still like Backpack best, though, so Backpack will still be around for a long time. Here's [the gist of our plans here](https://backpackforlaravel.com/articles/news/what-s-next-for-backpack-august-2018).
