### ISSUE TITLE
How to Access Data / Field just One User

### ISSUE THREAD

**Issue by imansugirman** [Laravel-Backpack/CRUD#1395]
# Need Information About Permission 

### What I did:

I was create Crud Controller 

### What I expected to happen:
Permission Can be Spesific by user ( ID )

### What happened:

I was create crud data with Laravel backpack And confuse about limited access data for just one people with delegation. I try using Request file

```
public function authorize()
{
    // only allow updates if the user is logged in
    return \Auth::check()->user_id;
}

```

### Backpack, Laravel, PHP, DB version:
Backpack : "backpack/crud": "^3.4",
Mysql : mysql  Ver 14.14 Distrib 5.7.21, for osx10.13 (x86_64) using  EditLine wrapper
PHP : 7.2

**Comment by AbbyJanke** [comment]
Hi there, just wanted to clarify what you were looking for? You are asking how you can limit access to certain CRUD actions based on a user's permission? Are you using the Laravel-Backpack/PermissionManager package or your own? Are you looking to limit the access on a custom CrudController you made or one of the built in ones?

**Comment by imansugirman** [comment]
Yes i am. i use laravel backpack permission manager. i use default config. I create tagcrudcontroller and example from laravelbackpack tutorial https://laravel-backpack.readme.io/docs/crud-example

How for limit access for this controller or this CRUD. for just 1 user only ( example maybe like project manager assign task application ).

Example : 
1. Admin Create file for just **User A,** and **User A** can access that. 
2. Admin Create **User B** and just can access that file. can't access **File User A** 
![topo](https://user-images.githubusercontent.com/38036171/40750441-86bac348-6491-11e8-85d8-4a24d9eff4a6.jpg)

**Comment by pxpm** [comment]
Define a user_id field on document table, when creating a document use a
select2 for example to select a user for document. Don't forget to add the
relation on document model  (belongs to user model).

Override crud functions on document controller:

```
public function  index()  {
$this->crud->addClause('where','user_id',backpack_user()->id);
return parent::index();
}

```
This Will only hide documents that are not assigned to current user from
list view...
Hope it helps you!

A Qua, 30/05/2018, 23:14, Iman Sugirman <notifications@github.com> escreveu:

**Comment by imansugirman** [comment]
Yeah...!! thanks @pxpm

**Comment by tabacitu** [comment]
@imansugirman you might also want to prevent your users from Editing or Deleting other user's entries, by manually typing an ID in the URL. You can do that by overwriting the ```edit()``` and ```delete``` methods. Something like:

```php
public function edit($id) {
  if ($this->crud->getEntry($id)->user_id != backpack_user()->id) { abort(503); }

  return parent::edit();
}

**Comment by imansugirman** [comment]
Thanks @tabacitu

**Comment by tabacitu** [comment]
Hi @imansugirman - it should be just a matter of tweaking the condition inside your IF statement. If you want to deny access to ALL operations do your IF statement inside the ```setup()``` method, it's called by the constructor.

Hope it helps.
Cheers!

**Comment by ghazi-kawashita** [comment]
> ```
> public function destroy($id) {
>   if ($this->crud->getEntry($id)->user_id != backpack_user()->id) { abort(503); }
> 
>   return parent::destroy($id);
> }
> ```

I think you meant abort(403) and not abort(503) cuz it's a forbidden access not related users
