### ISSUE TITLE
There are no commands defined in the "backpack:crud" namespace. 

### ISSUE THREAD

**Issue by wwardaww** [Laravel-Backpack/CRUD#1402]
# Bug report
```bash
There are no commands defined in the "backpack:crud" namespace.  
                                                                   
  Did you mean one of these?                                       
      backpack                                                     
      backpack:base  
```
### What I did:
i called first `php artisan backpack:base:install` when its success i call `php artisan backpack:crud:install`

### What happened:
Artisan coudnt find crud:install its only `php artisan crud <name>` about crud

### Backpack, Laravel, PHP, DB version:
- Backpack : 3.4
- Laravel: 5.6
- PHP: 7.2
- DB: Mysql 5.7.21

**Comment by tabacitu** [comment]
Hi @wwardaww ,

For that command to be registered, Backpack/CRUD needs to be installed. Are you sure you've run ```composer require backpack/crud``` and NOT ```composer require backpack/base```? You're following [these installation instructions](https://laravel-backpack.readme.io/docs/install-on-laravel-56), right?

Cheers!

**Comment by wwardaww** [comment]
thx,

i ran `composer require backpack/base` then now i call `composer require backpack/crud` it's fixed
