### ISSUE TITLE
[4.0][Feature req] No longer publish CSS & JS assets

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1404]
So here's a crazy idea. The fact that we publish CSS & JS assets:
- forces us to have the same files twice (once in ```vendor```, once in ```public```)
- makes it very difficult for us to push js/css updates in Backpack, because then assets need to be republished for the changes to take effect

Previously, we've thought that loading everything from CDNs would be an easy way out. But there have been a number of people that use Backpack on intranets, and they can't use CDNs, 'cause they don't have access to the Internet. Plus, it's out of our control, so if one CDN fails (somehow), a lot of Backpack-powered admin panels would go down.

**_What if_ we no longer publish the css/js assets, and just load them from the vendor folder?** _Theoretically_, there's no need for anyone to edit most CSS/JS files. And I've just done a dirty test, doing a ```symlink(public_path('vendor/backpack'), base_path('vendor/backpack/crud/src/public'));``` on installation seems to do the trick - as long as that folder is deleted, the files are then picked up from ```vendor/backpack/crud/src/public``` instead of ```public/vendor/backpack```.

This would of course be a breaking change, because we need to reorganize the ```backpack``` assets folder, since it doesn't seem to have a sound logic right now:

![screen shot 2018-05-14 at 17 49 12](https://user-images.githubusercontent.com/1032474/40004813-28a67ddc-579f-11e8-9a54-23e88fead860.png)

The way I see it, it should be more like this (as similar as possible with how views are organized):
![screen shot 2018-05-14 at 17 52 06](https://user-images.githubusercontent.com/1032474/40004975-9ad3ccc0-579f-11e8-9bb3-08298551dcf8.png)

The only downside I see here is that developers will have a hard time overwriting JS/CSS, since it's not published anymore. They will basically go there, see there's a symlink (hopefully, if their operating system doesn't show it as a simple folder), and say "wtf". If they want to make any changes to those files, they'd need to not use the file from the package, and use their file, from a different location (say... ```public/vendor/backpack/crud/custom```). They could do that by changing the path in all views that load that file. So if you want to replace the select2 version, for example, you'd have to:
- create a folder with CSS/JS assets, say ```public/vendor/backpack/crud/custom/select2``` and put all new assets there;
- create custom views for all fields that use select2 and use _your_ file instead of _the original_ file;

**Any thoughts on this - if it's a good idea or not?**

**Comment by tswonke** [comment]
@OliverZiegler we talked about this some other time. Maybe you want to give some input

**Comment by OliverZiegler** [comment]
@tswonke here I am ;)

So in my opinion we should try to achieve this via mix.

## Some things i see as benefits:
* users could use "versioning" of assets so there are no more issues of cache busting after new version deployments.
* there is a more elegant way to change/update/customize the assets like one wishes.
* Users could easily update dependencies if they wish (but this could lead to incompatible states, so on own risk)
* no more "complete" dependency folders inside vendor, public, your git repo (this btw. also leads to smaller application sizes)
* ability to minimise **all** required assets
* achieving complete local usability of backpack regarding points like
  * intranets without external internet connections
  * the new GDPR in the EU where external content loads could lead to legal issues
  * easier development for us "on the road" where internet connections are slow or not present

## The downside:
* wil not solve the "republish"-issue if we make changes and users did publish the assets, but with a good solution in 5. to remove the need of publishing this gets way more comfortable for alle the "default" users ;)
* requires more maintenance as we also will deal with mix issues (but this should mostly affect expert users that know what they are doing, I think)
* requires changes in the way we publish updates (as all precompiled files need to be compiled first)
* this will be a **HUGE** breaking change (more on the "how we deal with stuff"-side than on code side I think)

## The way we could try to do this:

1. provide precompiled files in bundled folders for the assets and all required fonts
here I think we should try to clever bundle things.
So fore example the select2 field currently requires `select2.min.css`, `select2-bootstrap.min.css`(via cdn) which could be compiled into on single `backpack_select2.min.css` and also the required js could be in on single compiled file. (This way we would also get more clean blade files)
2. add an artisan command that triggers the installation of dependencies via `npm install` (and alternatively via `yarn`) 
**or** 
create an NPM package that requires all the current dependencies (this is just for the dependencies, perhaps there is some solution directly in the composer package I'm currently not aware of) 
but this could also make updating dependencies quite difficult as of version conflicts 🤔 
**or** 
we could provide just a plain json file to copy to the users `package.json`. this way users that want to recompile everything can easily get the current dependencies (but this seems the badest decision here)
3. provide the plain resources files in the composer package, that **can** but may not be published into `resources/assets/vendor` 
4. add a new NPM package that can be imported to the mix file and recompiles the assets (so users don't need to type all the paths to all the backpack resources). This would also check if assets were published or should be compiled through the `vendor` folder and will be required via 2.
5. add a `backpack_mix` helper function that checks if assets in the mix.manifest exists and if not falls back to our precompiled files (here we could think of something that could work without publishing these files)
6. Update all asset links to use the `backpack_mix` helper from 5.


@tswonke thats what we talked about, isn't it?

@tabacitu what do you think? If this sounds good to you I would try to get this more concrete with better examples and kind of "documentation" to clearify my thoughts a bit more. And as soon as you give me the **GO** there will be a new branch (with sub-branches) trying to implement this. And I'm sure @tswonke wants to help 😅

**Comment by tabacitu** [comment]
@OliverZiegler I just wanted to tell you that I read your reply, thank you so much for taking the time. But I don't know... I'm still not convinced introducing Laravel Mix is a good idea - seems like it would add A LOT of complexity, for not many benefits (when compared to symlink). I can already see the flood of support requests, people not knowing how to use npm, compiling errors, etc - pretty scarry.

I'm going to prototype a dirty solution using Mix, see if I like it better afterwards. I have to admit I haven't used Mix to its full potential so far, so I'd better dive deeper before any decision. Thank you for the suggestion @OliverZiegler @androidedev @tswonke !

**Comment by shez1983** [comment]
any thoughts on this? surely like other packages, this should be published when we deploy and not sit/committed in the git...

**Comment by tabacitu** [comment]
Hmm… @shez1983 what other packages publish it on deployment? Do you have a few examples that do so without mix? Would be interested in taking a look how they do it. Thanks!

**Comment by promatik** [comment]
Hi everyone!
@tabacitu you said here: https://github.com/Laravel-Backpack/CRUD/issues/1653#issuecomment-432592056 you were able to create a symlink on mac. I just step by to say I was able to create it on windows too.

Also, I created a script to run after a composer install `post-install-cmd`, so every time anyone installs the project the link is going to be created. Admin LTE is now on git-ignore 🙂

**Comment by tabacitu** [comment]
@promatik indeed, it’s definitely possible to make a symlink on all operating systems. Filesystem has [a ```link()``` method](https://laravel.com/api/5.7/Illuminate/Filesystem/Filesystem.html#method_link), and [Laravel already uses it](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Foundation/Console/StorageLinkCommand.php) for ```php artisan storage:link```.

We could definitely use that. Just not sure if we _should_. 

I have found _zero_ Laravel packages that link to their assets from the ```/vendor``` folder, which scares me. Either we’ve stumbled upon a _great_ solution and we’re the first ones to use it OR it’s a big no-no and we haven’t figured out why it’s a bad idea...

Right now this _still_ sounds like a super-simple idea that would save us a lot of trouble, and save the user some disk space. I still think it’s a good one. If anybody can figure out a security issue or something, please let me know.

**Comment by vesper8** [comment]
I think it's best to follow the practice of official laravel packages.

Laravel Telescope which is the latest release handles this by actually including this step as part of their "upgrade process"

```php artisan vendor:publish --tag=telescope-assets --force````

I think that's how it should be for Backpack as well.

Maybe as an extra Backpack could somehow detect if the user has out-of-date assets and show a warning somehow.. you could achieve this by adding a version.txt file and check if it contains the latest content against the version.txt in the vendor folder

**Comment by drionix** [comment]
> I think it's best to follow the practice of official laravel packages.
> 
> Laravel Telescope which is the latest release handles this by actually including this step as part of their "upgrade process"
> 
> `php artisan vendor:publish --tag=telescope-assets --force`
> 
> I think that's how it should be for Backpack as well.
> 
> Maybe as an extra Backpack could somehow detect if the user has out-of-date assets and show a warning somehow.. you could achieve this by adding a version.txt file and check if it contains the latest content against the version.txt in the vendor folder

The problem is not only whether the user has out-of-date assets or not, but publishing the whole adminlte vendor folder is creating too much files. In Google App Engine, an application is limited to 10k files, and Laravel Backpack (with admintlte assets) is generating around 7k+ files (~70% of the limit). In every other ordinary hosting, inodes are also limited to 10k (which is the same as 10k files). This makes it impractical to develop a huge application with Laravel Backpack. I think we need another solution to minify the total file size generated by Laravel Backpack.

**Comment by tabacitu** [comment]
Update: 

PR https://github.com/Laravel-Backpack/Base/pull/402 installs all assets using NPM. Then using Laravel Mix:
- Base assets are bundled into a ```bundle.js``` and ```bundle.css```; since all pages use them;
- CRUD assets are copied from ```node_modules``` to a ```public/packages``` folder, so that they can be used by fields/columns/operations/etc, by directly referencing LOCAL files, instead of CDNs;

I think it might be the sweet spot, but it has its downsides:
- 68mb of js&css files in the Backpack package now; that get published upon installation;

Then again, I don't see a better way to do this - having a huge bundle with CRUD fields js&css is definitely not an option - the files would be too big, and you don't need all of them on each page load.

It might still make sense to "_no longer publish CSS & JS assets_" like this thread first suggested (create an alias instead). Which will be SUPER easy now that we have all assets in one folder, in the package. So we _can_ decide to do that.But I think we'll be inviting some problems with different systems, and maybe even security issues (maybe accidentally expose PHP assets through public URLs). Like @vesper8 said - I think the safest course of action here is to go the "laravel" way: that we do ```php artisan vendor:publish --force``` when running ```composer update```.

We can do that automatically by asking people upon installation to add this to their app's ```composer.json``` file's ```scripts``` section:
```diff
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
+        "post-update-cmd": [
+            "@php artisan vendor:publish --provider='Backpack\\Base\\BaseServiceProvider' --tag=public --force"
+        ]
    }
```

Just tested it - works like a charm. Or maybe we add it automatically upon package installation? Don't know how I feel about editing the app's main ```composer.json``` file automatically... 😄 Let me know what you think.

In the meantime, let's close this, since I think the original idea no longer holds water, and the other ideas mentioned in the thread are now implemented. Thank you so much everyone for the solutions and feedback. Great work here 😄 

Cheers!

**Comment by FatimaEzzahraaAbdelhak** [comment]
lay3tikom l3adab lmobin
