### ISSUE TITLE
defaultDate in datetime_picker overwrites existing value

### ISSUE THREAD

**Issue by patrickreck** [Laravel-Backpack/CRUD#1413]
# Bug report
When adding the `defaultDate` option to a datetime_picker field type, it will overwrite the existing value of the date field when editing a model

### What I did:
Added the field with a defaultDate

```
$this->crud->addField([
    'name' => 'start_at',
    'label' => 'Start date',
    'type' => 'datetime_picker',
    'allows_null' => false,
    'datetime_picker_options' => [
        'defaultDate' => (new Date())->toDateString()
    ],
]);
```

### What I expected to happen:
It'd set the defaultDate value if it was empty. If not empty, it should display the existing value

### What happened:
It overwrites the existing value with the default value

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4.8
Laravel: 5.6.20
PHP: 7.2.4
Mysql: 5.7.22

**Comment by pxpm** [comment]
You add 2 fields, one for update and another for create. 

```
$this->crud->addField(['field' => 'att_with_default'], 'create');
$this->crud->addField(['field' => 'att_without_default'], 'update');

```

Dunno if the best solution, but it will work ..

**Comment by patrickreck** [comment]
You can get around it by doing that, but it does not solve the problem

**Comment by tabacitu** [comment]
Hi @patrickreck ,

I just replied to your other issue too. Try using Backpack's ```default``` attribute instead. It works, and is available for all fields, not just this one:
```php
        $this->crud->addField([   // DateTime
            'name'  => 'datetime_picker',
            'label' => 'Datetime picker (jQuery plugin)',
            'type'  => 'datetime_picker',
            'allows_null' => true,
            'default' => '1989-05-12 11:59:59',
            // optional:
            'datetime_picker_options' => [
                'format'   => 'DD/MM/YYYY HH:mm',
                'language' => 'en',
            ],
        ]);
```

Let me know if this still doesn't work for you, and we should reopen the issue. @pxpm - thanks for providing a workaround.

Cheers!
