### ISSUE TITLE
Old does not work for a field that has a name of this form name[key]

### ISSUE THREAD

**Issue by abarta** [Laravel-Backpack/CRUD#1414]
# Bug report

### What I did:
I was checking for a selected field that has a name of the form name[key], when editing an entry, after receiving validation errors.

### What I expected to happen:
To have the previously selected value still selected.

### What happened:
Itt was not selected on the page that returned with validation errors. 
The select_from_array field has a check for old($field['name]), which does not match the field name in this case.
This is because the name of the old field becomes old('name.key') as opposed to old('name{key]'). 

### What I've already tried to fix it:
Added a new field to the addField Crud method for this cases and checked for that field in the old input.
It works but maybe you can figure out a different solution.

### Backpack, Laravel, PHP, DB version:
Backpack 3.3.2

**Comment by tabacitu** [comment]
Heads up: this gets fixed by https://github.com/Laravel-Backpack/CRUD/pull/1692
