### ISSUE TITLE
Using orderBy in a crud controller setup stops datatables sorting by clicking on a column

### ISSUE THREAD

**Issue by abarta** [Laravel-Backpack/CRUD#1415]
# Bug report

### What I did:
Click on a column header in a Datatable with various entries.
### What I expected to happen:
Expected it to sort by that column.
### What happened:
Did not sort, figured out this was because I had added $this->crud->orderBy('id', 'desc'); in my Crud setup.
### What I've already tried to fix it:
Added this function in CrudController fixes the issue in this case as the order field is not present in the initial loading of the Datatable.

    public function search()
    {
        if (!\Request::has('order')) {
            $this->crud->orderBy('id', 'desc');
        }

        return parent::search();
    }

### Backpack, Laravel, PHP, DB version:
Backpack 3.3.2

**Comment by abarta** [comment]
Yes it has ajax enabled and this happends for both columns with or without relationships, regardless. You can check on a clean 3.3.2 version, actually try the latest one and see if this happens there too. Thanks for replying!

**Comment by tabacitu** [comment]
Thank you for writing about this @abarta ! I know the two of us already talked about this. 

So the fix would be really simple, in Query.php:51 we could do:

```diff    /**
     * Order the results of the query in a certain way.
     *
     * @param  [type]
     * @param  string
     *
     * @return [type]
     */
    public function orderBy($field, $order = 'asc')
    {
+      // do not apply orderBy, if datatable already wants the entries ordered a certain way
+      // (when the user has clicked on a column header) 
+      if ($this->request->has('order')) { return $this->query; }
+
        return $this->query->orderBy($field, $order);
    }
```

The question is _should we do it?_ Is there a use case where we'd break people's apps? I don't see how - so I'm inclined to do this. Please let me know, anyone, if you can find a way this would break your app (or someone else's).

Thanks, cheers!

**Comment by AbbyJanke** [comment]
Possible breaking:

Say you have a create or edit form with one of the fields being called “order.” (Psst i do have one) and after i create the new record in the DB i display a new list that is ordered by a different DB column and that would overwrite my current orderBy.

2 options for fix:

1) Instead of setting the orderBys in the query instead we do it on the datatables itself? 

2) add a third param to orderBy function called $checkRequest default with default to true and then anybody that needs my type of case can pass the false.

**Comment by tabacitu** [comment]
Hmm... @AbbyJanke I don't think in that case, the ```order``` input would influence ```orderBy``` in any way:
- when the create/edit form is submitted, the request goes to ```EntityCrudController::store()``` or ```EntityCrudController::update()```; 
- both of those methods return ```performSaveAction()``` which, ultimately, does a ```redirect()```;
- so when the user sees the list page again, it's actually a different request, where applying the ```order``` is now ok;

**Comment by AbbyJanke** [comment]
Typically yes it would redirect, however im not using the default store function in this case it returns a view rather then a redirect overriding the default functionality. It may be a minimum use case but it is a way that would ultimately break apps that did that.

**Comment by tabacitu** [comment]
@AbbyJanke Damn :-) Thank you.

**Comment by tabacitu** [comment]
Created PR https://github.com/Laravel-Backpack/CRUD/pull/1535 for this, so I'm going to close the issue. We'll only get to merge this in 3.5 though, I think.
