### ISSUE TITLE
Empty model list after creating new crud and adding an item

### ISSUE THREAD

**Issue by KuenzelIT** [Laravel-Backpack/CRUD#1427]
# Bug report

### What I did:
With a fresh Laravel installation, I installed Backpack and added a `location` model and crud for it. I used the following tutorial site about tags just with another model name:
https://laravel-backpack.readme.io/v3.4/docs/crud-example

### What I expected to happen:
I expected a list of models with create/update/delete actions.

### What happened:
Creating and updating works, but the model list is always empty. I created multiple models with the crud form, but the list stays empty and I don't know where to look. The data was successfully saved to the database.

### What I've already tried to fix it:
I don't really know where to look for this. I did not change the created controller.

### Backpack, Laravel, PHP, DB version:
Backpack base: 0.9.5
Backpack crud: 3.4.11
Laravel: 5.6.23
PHP: 7.1.17 on Homestead, Mysql also from Homestead

This is the created setup method from the LocationCrudController:
```
public function setup()
    {

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('App\Models\Location');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/location');
        $this->crud->setEntityNameStrings('location', 'locations');

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */

        $this->crud->setFromDb();
}
```

**Comment by KuenzelIT** [comment]
Alright, I "figured" it out. I didn't see that external scripts were blocked and since I block all external requests, also datatables.net was blocked.

It would be awesome if backpack would not rely on any external sources for scripts/fonts/...

**Comment by tabacitu** [comment]
Glad you figured it out @KuenzelIT . Yes, we're trying to figure out how to avoid CDNs in the future. Cheers!
