### ISSUE TITLE
Success Message

### ISSUE THREAD

**Issue by wtime** [Laravel-Backpack/CRUD#143]
How can I display a success message after a custom controller request? I have created a stack inline button to send a mail. After that I would like display a success message like delete operation. Many thanks.

**Comment by tabacitu** [comment]
Backpack uses prologue/alerts for that, so you can use [the procedure right here](https://github.com/prologuephp/alerts#usage). You're totally right, this isn't documented. Thanks for the heads-up.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by wtime** [comment]
Thank you so much!
