### ISSUE TITLE
Return to the last tab after save & edit 

### ISSUE THREAD

**Issue by aleksei-budaev** [Laravel-Backpack/CRUD#1430]
Hello! 

At the moment I don't know how to do this, but what I expect from the save & edit action in CRUD. 
I chunked fields in my form on some tabs. After clicking save & edit I want to come back to this tab after save, but I see the first tab. 
I think it can be useful to return user to the last tab he used before save. 
Maybe someone know any hints to do this. 
If I realize how to fix this problem I will update this issue. 

What do you think? Is it necessary or not?

**Comment by AbbyJanke** [comment]
Hello @aleksei-budaev I think this is a decent expectation that it would return you to the current tab when selecting "save and edit" I have submitted a PR for this #1446

**Comment by tabacitu** [comment]
Completely agree. Thank you for raising the issue @aleksei-budaev and creating the PR @AbbyJanke . I just merged it into ```master```. It'll be available in a few hours/days after I bundle it with a few more changes.

Have a good one!
