### ISSUE TITLE
How to make a Show record using Date function in laravel 5.5 ?

### ISSUE THREAD

**Issue by alishahbaz344** [Laravel-Backpack/CRUD#1431]
hi i made a form in index.blade.php the form look like this:
<input id="selectedSearchBy" name="selectedSearchBy" type="hidden" value="" />
	<input id="startDatePostBack" name="startDatePostBack" type="hidden" value="" />
	<input id="endDatePostBack" name="endDatePostBack" type="hidden" value="" />

    <div class="form-horizontal" style="margin-bottom: 15px;">
    	<form action="posts/index" method="get">
		    <div class="form-inline" style="margin-left: -20px;">
			    <div class="col-md-2 col-lg-2">
				    <select id="searchBy" name="searchBy" class="form-control btn btn-secondary">
				     <option selected>Choose a filter</option>
				     <option id="1" value="ThisWeek" >This Week</option>
				     <option id="2" value="ThisMonth"> This Month</option>
				     <option id="3" value="ThisYear"> This Year</option>
				     <option id="4" value="CustomPeriod"> Custom</option>
					</select>
				</div>
				<div id="CustomSearchFields" style="display:none;">
				<div class=" col-lg-3 col-md-3">
					<div class="input-group date" id='startDate'>
						<span class="input-group-addon">From</span>
						<input type="text" id="startDateTextBox" class="form-control" name="startDate">
						<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
					</div>
				</div>

				<div class="col-lg-3 col-md-3">
					<div class="input-group date" id='endDate'>
						<span class="input-group-addon">To</span>
						<input type="text" id="endDateTextBox" class="form-control" name="endDate">
						<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
					</div>
				</div>
			</div>
			</div>
			<div class="col-lg-1 col-md-1 adminTaskIndexSeachBtn">
				<button class="btn btn-primary" type="submit">Search <span class="glyphicon glyphicon-search"></span></button>
			</div>
		</form>
	</div>

and i made a Controller:
public function date(Request $request,$id){
        
        $request->session()->put('search', $request
              ->has('search') ? $request->get('search') : ($request->session()
              ->has('search') ? $request->session()->get('search') : ''));

              $request->session()->put('field', $request
                      ->has('field') ? $request->get('field') : ($request->session()
                      ->has('field') ? $request->session()->get('field') : 'title'));

                      $request->session()->put('sort', $request
                              ->has('sort') ? $request->get('sort') : ($request->session()
                              ->has('sort') ? $request->session()->get('sort') : 'asc'));

        $date = Post::find($id);

        return view('posts.index',compact('posts'));
    }
i made a Route like this:
Route::get('date/{id}',"PostController@date");

please help me i'm new in laravel. i really don't know how to show the data when user click on the one of the options in the form.

**Comment by tabacitu** [comment]
Hi @alishahbaz344 ,

Sorry, this does not look Backpack-related. Please keep this Github repo for Backpack\CRUD issues only. I'd recommend you ask on StackOverflow or laracasts - those are the official places to ask this kind of general Laravel questions.

Cheers!
