### ISSUE TITLE
Image field type: Prefix being ignored

### ISSUE THREAD

**Issue by justincone** [Laravel-Backpack/CRUD#1434]
# Bug report

### What I did:
I created a new image field type with the following settings:

```php
$this->crud->addField([ // image
  'label' => "Cover image",
  'name' => "cover_image",
  'type' => 'image',
  'upload' => true,
  'crop' => true, // set to true to allow cropping, false to disable
  'aspect_ratio' => 1, // ommit or set to 0 to allow any aspect ratio
  'prefix' => 'uploads/images/covers' 
]);
```

### What I expected to happen:
Because I set `uploads/images/covers` for the prefix attribute, I expected the image path in the database to be `uploads/images/covers/[filename].jpg`.

### What happened:
The actual path saved to the database is not using the prefix path:

![image](https://user-images.githubusercontent.com/2482050/40718109-7934556c-63d4-11e8-861d-dbfefcd9d43d.png)

The path saved to the the db is using the $destination_path set in the Model's mutator. The problem seems to be with this line:

```php
// 3. Save the path to the database
$this->attributes[$attribute_name] = $destination_path.'/'.$filename;
```

❓ **Shouldn't the previously set prefix attribute be passed in here?**

### What I've already tried to fix it:
I've read through the documentation for the image field type, but there is no explanation for why the prefix might be ignored. 

### Backpack, Laravel, PHP, DB version:
Backpack 3.4
Laravel 5.6
PHP 7.1
Mysql 5.7.21

**Comment by tabacitu** [comment]
Hmm… you’re right @justincone and @lloy0076 - the description of ```prefix``` in the docs is pretty confusing. I’ve just [updated it to be clearer](https://backpackforlaravel.com/docs/3.4/crud-fields#image).

Yes, the ```prefix``` will only add that string to the HTML before it’s shown to the user. NOT in the database. That’s the mutator’s job.

Cheers! Sorry for not getting to this sooner.
