### ISSUE TITLE
I could by display only those products from the table that have column with the flag true?

### ISSUE THREAD

**Issue by st3r30t1p** [Laravel-Backpack/CRUD#1435]
I could by display only those products from the table that have column with the flag true?

**Comment by tabacitu** [comment]
I think you're looking for [advanced queries](https://laravel-backpack.readme.io/docs/crud-full-api#section-often-used). You can do things like this in you ```setup()``` method:

```php
// ------ ADVANCED QUERIES
$this->crud->addClause('active'); // apply local scope
$this->crud->addClause('type', 'car'); // apply local dynamic scope
$this->crud->addClause('where', 'name', '=', 'car');
$this->crud->addClause('whereName', 'car');
$this->crud->addClause('whereHas', 'posts', function($query) {
     $query->activePosts();
 });
```

PS. Please keep the Github issues section for bugs & features, not Q&A.
