### ISSUE TITLE
[Feature Request] setFromDBColumn/setFromDBFields

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1436]
Current we have `setFromDB` which is extremely helpful. But what if you need to change say one `type` in the field, but the column is just fine as is. This connects to being able to overwrite fields/columns as being discussed in PR #1353 but adds more to it. Maybe a simple variable on `setFromDB()` called `$stack` which defaults to both and has options for `columns` and `fields`. The variable is an easy solution without breaking changes. Not sure if this would be useful to others or just me so wanted some thoughts.

**Comment by tabacitu** [comment]
I agree, ```setFromDb()``` could call ```setColumnsFromDb()``` and ```setFieldsFromDb()``` which could each do their thing. That being said, I do plan to deprecate ```setFromDb()``` as soon as we massively improve the Generators, so I say... if we do this let's keep it undocumented :-)

**Comment by AbbyJanke** [comment]
since plan is to eventually remove setFromDB just going to close it.
