### ISSUE TITLE
[Feature Request] Column Type: Decimal

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1437]
In a current project of mine I have a decimal column in my Database stores something such as `1.9.9` current the column type of `number` does not support that and comes back with an error:

```php
"A non well formed numeric value encountered (View: /Users/abby/Sites/cord/vendor/backpack/crud/src/resources/views/columns/number.blade.php)"
```

yes I suspected that since its not really a number.. but some may consider it a number since it kind of is (ie: version number) should we add a check and allow for decimals in version, or maybe just in the documentation have a link that says "decimal" and directs them to just text with a notice saying to use that?

**Comment by pxpm** [comment]
I really don't think 1.0.1 it's a decimal number. .. more of a float?

Sorry if i'm wrong...

A Sex, 1/06/2018, 03:01, Abby <notifications@github.com> escreveu:

**Comment by AbbyJanke** [comment]
Correct that it is a float, It was simply an example as my field is basically a "version" number. feel like mixing it into the `number` as it is only a single attribute that needs to be added to the number field type:

```html
step="any"
```

If you just want to only allow positive numbers it would be `step="0"`. I would like to maybe see us set the default of `step` to 0 to only allow positive numbers but also have an option when adding the field to set a custom variable for `step` to cover all situations.

I haven't had a chance to get to a PR yet, but wanted to see if anybody else thought this was worth while?

**Comment by pxpm** [comment]
> The step attribute specifies the legal number intervals for an <input> element. Example: if step="3", legal numbers could be -3, 0, 3, 6, etc.

To validate positive numbers we should add:

`min=0`

To validate decimal numbers we should add:

`step=0.1 or step=0.01`

Maybe two attributes on number field like:

```
$this->crud->addField([
'name' => 'name',
'type' => 'number',
'step' => '1',
'positive' => true
]);
```

Thanks hope it helps,

Pedro

**Comment by AbbyJanke** [comment]
Adding the positive option seems pointless since “step” needs to be 0 or greater to require that. Step being able to set to whatever you want is the best scenarior. If you want negative you can put any, want 2 points just set it to 2.

**Comment by lloy0076** [comment]
**1.0.1** or any other versoin **STRING** is not a number; we just call it that.

Let's not try to change the rules of mathematics or language here.

**Comment by tabacitu** [comment]
:))

**Comment by niladam** [comment]
@AbbyJanke - i found a really clever solution to this. I was in a situation where i couldn't alter all the records.

I found a [stackoverflow response](https://stackoverflow.com/a/48444826/1064703) that provided me with a function that i can reuse and so, i've turned that into an accessor that i can safely reuse.

Anyways, i'm posting this here as i'm sure people have encountered this (or will encounter it) in the future as i'm sure @tabacitu knows that romanian prices are strange :)

Here's the accessor that i shamefully _borrowed_ from the above stackoverflow response: 

```php
    public function getColumnAttribute($value, int $precision = 2)
    {
        $input = str_replace(' ', '', $value);
        $number = str_replace(',', '.', $input);
        if (strpos($number, '.')) {
            $groups = explode('.', str_replace(',', '.', $number));
            $lastGroup = array_pop($groups);
            $number = implode('', $groups) . '.' . $lastGroup;
        }
        return bcadd($number, 0, $precision);
    }
```

**Comment by tabacitu** [comment]
Thanks for sharing your solution @niladam !
