### ISSUE TITLE
May I add the filter for searching via select? There will be a search only  by the name when entering the query in the search field  if it was selected by the name.

### ISSUE THREAD

**Issue by st3r30t1p** [Laravel-Backpack/CRUD#1440]
May I add the filter for searching via select? There will be a search only  by the name when entering the query in the search field  if it was selected by the name. http://joxi.ru/Rmz1DPPi0vwPpr (Screen)

**Comment by st3r30t1p** [comment]
May I add the filter for searching via select? There will be a search only  by the name when entering the query in the search field  if it was selected by the name.

**Comment by tabacitu** [comment]
Hi @st3r30t1p ,

There's no ready-built way for you to do this in Backpack - very niche use case, this one. You _can_ do it by extending Backpack, take a look at the ```list.blade.php``` file and the ```CrudController::search()```, but Backpack won't help you with this, I'm afraid. By default the DataTables search will search within all columns shown. I personally think that's way better - more intuitive and less clicks for the user.

Cheers!
