### ISSUE TITLE
[4.0][Feature][Ready] select2_multiple for 1:n relations eg. select2_many?

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/CRUD#1442]
Hey guys,

we currently wanted to use an 1:n relation to edit the multiple connected entities out of the "one" side.

So assume we have a User who manages multiple Groups. So Group has the foreign key `user_id` and we have the following relations:

In the User model:

```php
public function groups() 
{
    return $this->hasMany(Group::class)
}
```

and in Group model:

```php
public function user()
{
    return $this->belongsTo(User::class)
}
```

Now we can easily select the User on Group edit with the `select2` field. 
But what we also needed was selecting the Groups on User edit, which would be a new field.
Something like `select2_many`?

Has anyone already achieved this? Is it worth the effort creating a new field or is this some kind of "very special case" and should not be part of backpack?

If this can be useful I could try to solve this, implement the field and create a PR.

**Comment by OliverZiegler** [comment]
@pxpm this was just an example to illustrate the issue ;)

**Comment by pxpm** [comment]
Ok :)

I got your point.

In my humble opinion it's worth as 1-n relations are common.

If i can help you with something let me know.

Pedro

A Ter, 5/06/2018, 17:33, Oliver Ziegler <notifications@github.com> escreveu:

**Comment by androidedev** [comment]
Is a new field type, an improvement, a non breaking change, and besides that not a marginal use case, I think definitely will be cool to have it.

**Comment by OliverZiegler** [comment]
So I managed to make a PR with select2_many and select2_one field types.
Would be nice if someone could give feedback.

**Comment by tabacitu** [comment]
Hmm... this is a very very good question.

My position in the past has been that **an edit form should only edit that entity**. I always thought it's the only intuitive way. But this use case that you've pointed out is intuitive as well. **I might have been wrong.** As an admin/user, I have no idea that it's a 1-n relationship and what not. So it doesn't really matter to me (admin) where the change is made, in this entity that I'm editing or in a connected entity. Plus, like you guys said, I don't think it's such a niche use case, so we should probably support it.

Thanks a lot for the excellent PR @OliverZiegler . Great work.

**Comment by tabacitu** [comment]
Let's merge all talks about this into https://github.com/Laravel-Backpack/CRUD/pull/1453

Closing the issue in the hope that we can devote some attention to this in 4.1

Thanks again @OliverZiegler ! It's much appreciated.
