### ISSUE TITLE
Hiding columns in list view

### ISSUE THREAD

**Issue by GregaUNK** [Laravel-Backpack/CRUD#1455]
Hi,

I have many columns in list view. On mobile or when minimizing app some of columns get hidden. Is this a function or a bug? I would rather see horizontal scroller at the bottom.

Iam using latest versions on php7.1

Thanks!

**Comment by tabacitu** [comment]
@GregaUNK - that's actually a feature :-) Tables on mobile/tablet is a difficult thing to do, and I'm particularly proud of how Backpack achieves this :-) So be gentle. But if you don't like it you can disable the responsive-datatables plugin by overwriting your ```list.blade.php``` file. 

We also have a PR somewhere around here that brings an API call something like ```$this->crud->disableResponsiveDatatable()``` that does what you want. You can wait around for that one, it'll probably be merged before you go to production anyway.
