### ISSUE TITLE
Backpack not working with swoole

### ISSUE THREAD

**Issue by george-kar** [Laravel-Backpack/CRUD#1456]
I was playing with Swoole (High Performance PHP) and this package Laravel package

https://github.com/swooletw/laravel-swoole

It looks like that Backpack doesn't play nice with it. In the default backpack demo when you select Demo Entities -> Monster you get an error "Sorry, you can't have two filters with the same name."

Also clicking on "Pages" produce a Laravel error

"htmlspecialchars() expects parameter 1 to be string, object given (View: /home/forge/backpack.cafepro.gr/vendor/backpack/crud/src/resources/views/list.blade.php ▶"

**Comment by tabacitu** [comment]
@george-kar Backpack should work with Swoole just fine. I just fixed the Monsters error - seems to have been one in the package (missing range filter). A ```composer update``` should fix it for you.

Let me know if it doesn't and reopen the issue.

Cheers!

**Comment by george-kar** [comment]
Monsters is fixed but it still has the pages bug. If you click pages and then you go somewhere else and you click pages again it gets an error

"htmlspecialchars() expects parameter 1 to be string, object given (View: /home/forge/backpack.cafepro.gr/vendor/backpack/crud/src/resources/views/list.blade.php ▶"

**Comment by george-kar** [comment]
Monsters is fixed but it still has the pages bug. If you click pages and then you go somewhere else and you click pages again it gets an error

"htmlspecialchars() expects parameter 1 to be string, object given (View: /home/forge/backpack/vendor/backpack/crud/src/resources/views/list.blade.php ▶"

**Comment by tabacitu** [comment]
Hmm... Where exactly? What's the line? I can't get the same error.

**Comment by george-kar** [comment]
http://take.ms/n0Mlg

The problem exists only if you click page second time
Click pages then click menus then click pages again

**Comment by george-kar** [comment]
I guess it comes from this line
        <li><a href="<?php echo e(url($crud->route)); ?>" class="text-capitalize"><?php echo e($crud->entity_name_plural); ?></a></li>

**Comment by george-kar** [comment]
I guess it comes from that line

`        <li><a href="<?php echo e(url($crud->route)); ?>" class="text-capitalize"><?php echo e($crud->entity_name_plural); ?></a></li>
`

**Comment by codercms** [comment]
@tabacitu hey, i got the same error.
```
htmlspecialchars() expects parameter 1 to be string, object given (View: /var/www/app/vendor/backpack/crud/src/resources/views/list.blade.php)
```

Problem line is:
```
<li><a href="<?php echo e(url($crud->route)); ?>" class="text-capitalize"><?php echo e($crud->entity_name_plural); ?></a></li>
```
Link: https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/list.blade.php#L11

Argument passed to "e" function is instance of UrlGenerator class.

You can just override index method of CrudController and check logs:
```
public function index()
{
    \Log::info('permissions index crud', ['route' => $this->crud->route]);

    return parent::index();
}

// logs:
// first attempt to access
[2018-08-15 01:36:44] local.INFO: permissions index crud {"route":"admin/permissions"}
// second attempt to access
[2018-08-15 01:36:46] local.INFO: permissions index crud {"route":null}
```

**Comment by codercms** [comment]
Hotfix is an overriding constructor of CrudController:
```
public function __construct(\Illuminate\Http\Request $request)
{
    $this->crud = app()->make(\Backpack\CRUD\CrudPanel::class);
    $this->request = $request;
    $this->crud->request = $request;
    $this->setup();
}
```

**Comment by codercms** [comment]
@tabacitu @george-kar  So, i found a bug, those code caused an errors.
```
public function __construct()
{
    if (! $this->crud) {
        $this->crud = app()->make(CrudPanel::class);

        // call the setup function inside this closure to also have the request there
        // this way, developers can use things stored in session (auth variables, etc)
        $this->middleware(function ($request, $next) {
            $this->request = $request;
            $this->crud->request = $request;
            $this->setup();

            return $next($request);
        });
    }
}
```

Middleware \Closure code is still in memory and it's called before than new CrudController class was instantinated.
See logs:
1st request
```
[2018-08-15 10:58:58] local.INFO: __construct called begin
[2018-08-15 10:58:58] local.INFO: __construct called end
[2018-08-15 10:58:58] local.INFO: middleware called
```
2nd request
```
[2018-08-15 10:59:15] local.INFO: middleware called
[2018-08-15 10:59:15] local.INFO: __construct called begin
[2018-08-15 10:59:15] local.INFO: __construct called end
```

I finally fixed it under Swoole without any side-effects.
1. Create new base controller for custom Laravel Backpack CRUD controllers with empty __construct
```php
<?php

class CrudController extends \Backpack\CRUD\app\Http\Controllers\CrudController
{
    public function __construct()
    {
    }
}
```
2. Inherit all custom Laravel Backpack CRUD controllers from new CrudController.
3. Create new middleware, for example BackpackCrud.php
```php
<?php

/**
 * Class BackpackCrud
 * @package App\Http\Middleware
 *
 * Created to fix Laravel Backpack under Swoole
 * Should by included in middleware section in routes/backpack/custom.php file
 */
class BackpackCrud
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure $next
     *
     * @return mixed
     */
    public function handle($request, \Closure $next)
    {
        /* @var \App\Http\Controllers\Admin\CrudController $controller */
        $controller = $request->route()->getController();
        if ($controller instanceof CrudController) {
            $crud = \app()->make(\Backpack\CRUD\CrudPanel::class);
            $crud->request = $request;
            $controller->request = $request;

            $controller->crud = $crud;
            $controller->setup();
        }

        return $next($request);
    }
}
```
4. Attach those middleware to Laravel Backpack CRUD controllers
```php
Route::group([
    'prefix' => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin'), \App\Http\Middleware\BackpackCrud::class],
    'namespace' => '\App\Http\Controllers\Admin',
], function (\Illuminate\Routing\Router $routes) {
    // Backpack\CRUD: Define the resources for the entities you want to CRUD.

});
```

**Comment by tabacitu** [comment]
Thank you for your solution @codercms ! Quite a clean one too.

**Comment by dauvray** [comment]
Hello,

I'm using backpack crud 3.5 and swoole 2.6.2 and the "Sorry, you can't have two filters with the same name." always here.

Thank you!
