### ISSUE TITLE
Range filter not applied if just one value entered

### ISSUE THREAD

**Issue by bilfeldt** [Laravel-Backpack/CRUD#1458]
# Bug report
Using the new range filter, makes it possible to set a minimum and a maximum value. See the [documentation](https://laravel-backpack.readme.io/docs/filters#section-range)

The problem is that the minimum and maximum values are only appended to the AJAX call as query parameter if **both** the minimum and maximum values are entered.

I propose that the values are added to the query even if only one of the fields is entered, as it will be possible to limits results by a single parameter or require both in the filter it self (the documentation has a check that both values should be set). That way the filter can be used for searches like:

- numbers greater than X
- numbers less than Y
- numbers between X and Y

Right now, we can only use the last search using this filter.

### What I did:
Create a range filter like this:
```
$this->crud->addFilter([
  'name' => 'number',
  'type' => 'range',
  'label'=> 'Range',
  'label_from' => 'min value',
  'label_to' => 'max value'
],
false,
function($value) { // if the filter is active
  $range = json_decode($value);
  if ($range->from && $range->to) {
    $this->crud->addClause('where', 'number', '>=', (float)$range->from);
    $this->crud->addClause('where', 'number', '<=', (float)$range->to);
  }
});
```

I then only filled out the minimum field (min value) with a value of 2

### What I expected to happen:
I expected that the AJAX call should be made as `POST: /search?number={"from":"2","to":""}

### What happened:
An AJAX call was made without query parameter `POST: /search

### What I've already tried to fix it:
I looked at the documentation, which implements a check for both fiels presence, but apparantly they will always be there:
```
  if ($range->from && $range->to) {
    $this->crud->addClause('where', 'number', '>=', (float)$range->from);
    $this->crud->addClause('where', 'number', '<=', (float)$range->to);
  }
```

### Backpack, Laravel, PHP, DB version:
backpack/base: 0.9.6
backpack/crud: 3.4.13
laravel/framework: 5.6.22

**Comment by lloy0076** [comment]
Seems like an easy enough PR to me (and probably should add to one of the unit tests too, though).

**Comment by tabacitu** [comment]
You're totally right. Thank you @bilfeldt - it makes perfect sense for this filter to also support min-only and max-only filtering. Just merged @pxpm 's PR which allows this. It'll be tagged in a few hours/days along with a few more improvements.

Cheers!

**Comment by tabacitu** [comment]
@bilfeldt do note that this to take advantage of this, you should change you query altering to:

```php
            $range = json_decode($value);
            if ($range->from) {
                $this->crud->addClause('where', 'number', '>=', (float) $range->from);
            }
            if ($range->to) {
                $this->crud->addClause('where', 'number', '<=', (float) $range->to);
            }
```

Just updated the docs with that too.

**Comment by Rinaldi91** [comment]
how make limits number just 1 until 3, if more then can't
![limit](https://user-images.githubusercontent.com/41364340/42991561-2b014826-8c30-11e8-9532-13cfe69297db.JPG)
