### ISSUE TITLE
Filter select2_ajax error

### ISSUE THREAD

**Issue by matteoventuri7** [Laravel-Backpack/CRUD#1459]
# Bug report
This filter is break: https://laravel-backpack.readme.io/docs/filters#section-select2_ajax
### What I did:
Add select2_ajax filter like docs.
### What I expected to happen:
Can use filter on the data table
### What happened:
Filter does not work.
Browser inspector tell me: "Uncaught Error: No select2/compat/initSelection"
### Backpack, Laravel, PHP, DB version:
"php": "^7.1.3",
"backpack/crud": "^3.4",
"laravel/framework": "5.6.*",

**Comment by tabacitu** [comment]
You're totally right, thank you @matteoventuri7 ! Looks like the ```select2_ajax``` filter did not load select2 from a correct location. Just pushed a fix on ```master```. It'll be available with a ```composer update``` in a few hours/days, after we bundle it with a few more changes.

Cheers!
