### ISSUE TITLE
How to view button read row details in new model?

### ISSUE THREAD

**Issue by Butthry-GDNT** [Laravel-Backpack/CRUD#1460]
# Bug report
1- Controller
 $this->crud->addButtonFromModelFunction('line', 'open_google', 'openGoogle', 'beginning'); // add a button whose HTML is returned by a method in the CRUD model
2- Model
    public function openGoogle($crud = false)
    {
        return '<a class="btn btn-xs btn-default" target="_blank" href="http://google.com?q='.urlencode($this->text).'" data-toggle="tooltip" title="Just a demo custom button."><i class="fa fa-search"></i> Google it</a>';
    }

### What I did: I have created task Manager via backpack. There are many list in my table included with button edit show and delete. I want to view a row detail on a new page per model. How can I do? Thank you in advance for your help. 

![image](https://user-images.githubusercontent.com/40291501/41458518-0a531888-70b1-11e8-8212-9e020106c4a3.png)

**Comment by tabacitu** [comment]
Hi @Butthry-GDNT ,

There's an experimental featured called "Show", which you can enable with:
```$this->crud->allowAccess('show');```

Hope it helps.
Cheers!

**Comment by imansugirman** [comment]
I Like this.

**Comment by tabacitu** [comment]
Thank @AbbyJanke for it - she's the mastermind behind it ;-)

**Comment by Butthry-GDNT** [comment]
Dear @tabacitu,

It's work correctly now. Big thank you for your support.
