### ISSUE TITLE
"Call to a member function parameters()" when editing or deleting

### ISSUE THREAD

**Issue by nicolas-t** [Laravel-Backpack/CRUD#1461]
# Bug report

### What I did:
I tried to edit an entity, it openned this page : 
https://domain.com/admin/user/1/edit

### What I expected to happen:
See the edition page 

### What happened:
Got an error message : 
```
 Call to a member function parameters() on null {"userId":55,"email":"email@email.om","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function parameters() on null at /xxx/vendor/backpack/crud/src/PanelTraits/Read.php:24)"} []
```

The line in question : 
https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/Read.php#L24

### What I've already tried to fix it:
Searched issues on this repository;

### Backpack, Laravel, PHP, DB version:
backpack/base 0.9.5
backpack/crud 3.4.10
php 7.2
laravel 5.5

----

I also get this error message when I try to delete something.

In my config I have : 
```
    'setup_auth_routes' => true,
    'setup_dashboard_routes' => false,
```

And in my routes : 

```
Route::group([
    'prefix' => config('backpack.base.route_prefix'),
    'middleware' => ['role:can_access_admin'],
], function () {
    Route::get('dashboard', 'AdminController@dashboard');
    Route::get('/', 'AdminController@redirect');

    Route::get('user/{userId}/login', 'Admin\UserCrudController@login');
    CRUD::resource('user', 'Admin\UserCrudController');
});
```

**Comment by tabacitu** [comment]
Hmm... I suspect you also need the ```web``` middleware for your routes. Does that fix it for you?

**Comment by nicolas-t** [comment]
Nope,

I've tried tons of things, adding / removing middlewares, i've reinstalled base and crud, and moved my routes to a `routes/admin.php` as you recommend in the docs.

If I do : 

```php
# routes/admin.php
<?php
dd(Route::current());

Route::get('dashboard', 'AdminController@dashboard');
Route::get('/', 'AdminController@redirect');

...
```

`Route::current()` is null, even on the dashboard page. But as the function `getCurrentEntryId` (from the trait) is not called it works.

I think this is related to me moving my whole backend to a subdomain. But I have now idea how to solve it yet.

**Comment by tabacitu** [comment]
Oh ok, I understand. Thanks for sharing your solution @nicolas-t .

Cheers!
