### ISSUE TITLE
AddClause cuts of parameters if query method accepts more than 3

### ISSUE THREAD

**Issue by chancezeus** [Laravel-Backpack/CRUD#1468]
# Bug report

### What I did:
When using the "extended" version of whereHas (including operator and count) the count is "array_slice"'ed off (since array_slice is set to length 3 and the count is in this case the fourth operator).

### What I expected to happen:
The count is also applied

### What happened:
The count is not applied (ie. it defaults to 1).

### What I've already tried to fix it:
I manually removed the length from the `vendor/backpack/crud/src/PanelTraits/Query.php` and it currently works, but since this is a "manual" hack of a vendor package I would like/suggest it to be included as part of backpack (ie. remove the length since (future) query methods might require even more parameters).

**Comment by sulfo** [comment]
I've created my first PR in the repository, with a fix for the issue. 👍

**Comment by tabacitu** [comment]
Just merged the PR, thank you @chancezeus and @sulfo . Honestly, I don't see any reason for that to be there either. Nor do I _remember_ why it's there :-)

So off with it.

Thanks, cheers!
