### ISSUE TITLE
[Feature Request] Print Single CRUD Entity

### ISSUE THREAD

**Issue by MarioVillani** [Laravel-Backpack/CRUD#1473]
Hi,
i did not see anything in the documentation about printing a single CRUD Entity. Actually is only possible to print the entire list by putting 

`$this->crud->enableExportButtons();`

in the CrudController. 
Is there a fast way to pretty print what is shown in a single entry? Thank you.

**Comment by tabacitu** [comment]
I agree we can do more for the individual entry. Preview and maybe Download as PDF / Print should be top of the list.

@MarioVillani we have an experimental feature called show/preview you can use. It will show a "Preview" button next to Edit / Delete. The user can then Print that page, or you can add a button to that page to download the current print preview page as PDF with JS.

Here's a quick video of the feature after you do ```$this->crud->allowAccess('show');```:
![screen recording 2018-06-28 at 09 51 am](https://user-images.githubusercontent.com/1032474/42017872-1b8345da-7ab9-11e8-8dbe-2df2bb6bfb84.gif)

**Comment by MarioVillani** [comment]
That's nice. Thank you very much. How long will it take (estimate) to implement something like printing in the list view in the entity view?
I'm available to add the new functionality, all the code needed (as i think) is in  `backpack/crud/resources/views/list.blade.php`. Could you please tell me where could i send you a PM? Thanks.

**Comment by tabacitu** [comment]
5 minutes, to be honest :-) Done, take a look here: https://github.com/Laravel-Backpack/CRUD/pull/1479 . Will merge in a few hours or days, along with a few more changes.

It adds the button in the top-right corner:
![screen shot 2018-06-28 at 12 16 09](https://user-images.githubusercontent.com/1032474/42025372-1753e302-7acd-11e8-84f6-7a5700c5d7e1.png)


Downloading as PDF, however, would take a lot more time.

**Comment by tabacitu** [comment]
This is no longer the case, but you can find me at hello@tabacitu.ro
