### ISSUE TITLE
[Feature Request] Display Value if Date is not actual Date

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1475]
So I added an accessor to my model that if the "date type" is null it needs to return the string 'lifetime' but because of how we display dates we aren't checking if its a string just if it is not empty so i got an error saying invalid date. This may be a niche case which is why i wanted to open a discussion and maybe figure out best way to do it. Currently I made a custom column view to say if it is empty just display the text but that skips over any mutators.

Current view code:

```php
{{-- localized date using jenssegers/date --}}
<span data-order="{{ $entry->{$column['name']} }}">
    @if (!empty($entry->{$column['name']}))
	     {{ Date::parse($entry->{$column['name']})->format(($column['format'] ?? config('backpack.base.default_date_format'))) }}
    @else
	     {{ trans('cord::license.lifetime') }}
    @endif
</span>
```

My current thought process is on the original `if` is we check if its empty, and check if it as an actual date, if not just display the value.

**Comment by AbbyJanke** [comment]
Another point of view is think about this. So on any `select` types of columns we display `-` by default if it is null, basically expanding on that. so maybe we go `if date` then `if has value` then display `-` ?basically so i'm going:

```php
if($isDate) {
 // do date things
elseif($hasValue) {
 // display plain value
} else {
 echo "-"
}
```

**Comment by tabacitu** [comment]
Hmm... sounds pretty niche to me, tbh. 

Storing forever/lifetime as NULL sounds like a cool hack to me - will keep in mind :-)

**Comment by AbbyJanke** [comment]
Alrighty i’m i was 50/50 on my thoughts of it so just like to throw out ideas. Will close this.
