### ISSUE TITLE
Installation Guide 404 (README.md)

### ISSUE THREAD

**Issue by bachhuberdesign** [Laravel-Backpack/CRUD#1477]
Not adding a commit for this since the 404 should probably be fixed on the documentation site.

# Bug report

### What I did:
Clicked "Install Backpack on Laravel 5.5"

### What I expected to happen:
Taken to installation guide.

### What happened:
Taken to 404 doc page.

### What I've already tried to fix it:
n/a

### Backpack, Laravel, PHP, DB version:
n/a

**Comment by tabacitu** [comment]
Updated! Thank you @bachhuberdesign . [Go here](https://laravel-backpack.readme.io/v3.4/docs/install-on-laravel-56). The process is the same as L5.6 - the current version supports both 5.5 and 5.6. But my recommendation - update your Laravel to 5.6. You're going to have to do it anyway - better now than later.

Cheers!
