### ISSUE TITLE
Still Confuse about Select2 Ajax

### ISSUE THREAD

**Issue by imansugirman** [Laravel-Backpack/CRUD#1483]
# Bug report

### What I did:
I was Create Database and Crud File with Model Relationship

### What I expected to happen:
Just Show City with Relationship ( Province ID)

### What happened:
I don't know for ```select2_from_ajax``` in select city with depend province selected

### What I've already tried to fix it:

This my crudcontroller
```
[
                'label' => "Province", // Table column heading
                'type' => "select2_from_ajax",
                'name' => 'province_id', // the column that contains the ID of that connected entity
                'entity' => 'province', // the method that defines the relationship in your Model
                'attribute' => "province_name", // foreign key attribute that is shown to user
                'model' => "App\Models\Province", // foreign key model
                'data_source' => url("api/searchprovince"), // url to controller search function (with /{id} should return model)
                'placeholder' => "Select a Province", // placeholder for the select
                'minimum_input_length' => 2, // minimum characters to type before querying results
            ],
            // 1-n relationship
            [
                'label' => "City", // Table column heading
                'type' => "select2_from_ajax",
                'name' => 'city_id', // the column that contains the ID of that connected entity
                'entity' => 'city', // the method that defines the relationship in your Model
                'attribute' => "city_name", // foreign key attribute that is shown to user
                'model' => "App\Models\City", // foreign key model
                'data_source' => url("api/searchcity"), // url to controller search function (with /{id} should return model)
                'placeholder' => "Select a City", // placeholder for the select
                'minimum_input_length' => 2, // minimum characters to type before querying results
            ],
```
Province Select ( Select Province First But not Show City on That Province )
![fase1](https://user-images.githubusercontent.com/38036171/42054564-fbc0127e-7b3e-11e8-9a21-f9b8975ce563.jpg)

I want this ( Just Show Only City with Relation ID in Province or province_id )
![fase2](https://user-images.githubusercontent.com/38036171/42054679-3b6647e0-7b3f-11e8-9ce4-0b326d4df34d.jpg)

Database Relations Table
![fase3](https://user-images.githubusercontent.com/38036171/42054725-57560972-7b3f-11e8-8868-6569231a6f01.jpg)

City With Relation ( province_id )
![fase4](https://user-images.githubusercontent.com/38036171/42054735-5e83f66e-7b3f-11e8-91b4-5e49320ed34e.jpg)

### Backpack, Laravel, PHP, DB version:
"backpack/crud: "^3.4",
PHP : 7.2
Mysql : 5.7.21

**Comment by imansugirman** [comment]
And This my API / Json Output with relation province id

![jepretan layar 2018-06-29 pada 01 55 35](https://user-images.githubusercontent.com/38036171/42054793-8e8eeea4-7b3f-11e8-8553-849ba2050c4a.png)

**Comment by tabacitu** [comment]
@imansugirman from what I can tell, you're looking to create a ```select2``` whose results depend on another ```select2```.

This is NOT a supported Backpack feature, yet. Solutions:

1) You'll have to [create a custom field type](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types) for your second select2, that also passes the first input through AJAX, then adapt your PHP method that returns the results to take that into account.

2) Overwrite the ```select2_from_ajax``` field by running ```php artisan backpack:crud:publish fields/select2_from_ajax```, then make the [modifications here](https://github.com/Laravel-Backpack/CRUD/pull/1484) to it. Then filter your result set in PHP like I did in the example in the PR. I expect this PR to be merged in a few hours/days, since it's non-breaking. When we do, you can delete your custom ```select2_from_ajax``` file from your project.

Thank you for submitting the issue, it's what made me think of this solution and submit the PR :-)

Cheers!

**Comment by tabacitu** [comment]
In Developer Tools, you can **go to the Network tab** and click on that actual request to see what the exact problem is in your PHP code. You'll be able to see your error message.

**Comment by imansugirman** [comment]
XHR Problem
![jepretan layar 2018-06-29 pada 16 20 00](https://user-images.githubusercontent.com/38036171/42090432-a5dd407e-7bcb-11e8-8730-13e0796a4bbb.png)

**Comment by OwenMelbz** [comment]
@imansugirman There is your error.

```
Undefined index: province
```

Something in your code is using province without testing it exists first.

Try replacing things like `$form['province']` with `data_get($form, 'province')`

**Comment by imansugirman** [comment]
hi @OwenMelbz still error 500

**Comment by imansugirman** [comment]
Any Solution for this issue?

**Comment by imansugirman** [comment]
This was Solved. change 

```
if (! $form['province_id']) {
            return [];
        }

        // if a category has been selected, only show articles in that category
        if ($form['province_id']) {
            $options = $options->where('province_id', $form['province_id']);
        }

        }
```
