### ISSUE TITLE
Access auto increment id inside store function after storeCrud call

### ISSUE THREAD

**Issue by Athuli7** [Laravel-Backpack/CRUD#1486]
# Bug report
Inability to access auto-increment id inside store function.

### What I did:
Used the info available in the docs about store and update and the way UserCrudController handles password_confirmations to accept 5 additional fields meant to create related model instances. but in order to do that I need the current id. but the storeCrud returns only the Redirect.

### What I expected to happen:
If it returned an object with more information, like the autoincrement id, then I could create the relationships.

### Backpack, Laravel, PHP, DB version:
Backpack : v3.4.15 CRUD on v0.9.6 Base
Laravel : v5.6.26
PHP 7.1
MySQL 5.6

**Comment by AbbyJanke** [comment]
Soo you my biggest love of backpack is you can overwrite just about anything. Why mot take the code from the store function, add it ti your controller, change what you need and bam you have what you need.

**Comment by Athuli7** [comment]
@AbbyJanke, 

1. EntityCrudController(mine) extends Backpack\CRUD\app\Http\Controllers\CrudController
CrudController uses SaveActions ( Trait )
How do you overwrite a function in that? Can you help?

2. Backpack lets you overwrite everything. But overwriting often breaks a lot of things as new versions are released. That's why I'm hesitant to overwrite something like this.

**Comment by OwenMelbz** [comment]
@Athuli7 you can use the IoC container to decorate/inject alternative classes based on certain requestments, e.g "if user crud controller requests crud model, then give them the crud model with this extra functionality"

HOWEVER.

Why can't you use `$this->crud->entry` which is provided in the `store` and `update` ? you can see in the generated controller this

```
    /**
     * @param UpdateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::updateCrud($request);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry

        return $redirect_location;
    }
```

**Comment by tabacitu** [comment]
I second that. @OwenMelbz 's solution is what I use all the time.

@Athuli7 , you already have the ```store()``` and ```update()``` methods in your UserCrudController. After ```parent::storeCrud()``` is called you can do ```$this->crud->getCurrentEntry()``` and ```$this->crud->getCurrentEntryId()```.

Cheers!
