### ISSUE TITLE
Buttons Links 

### ISSUE THREAD

**Issue by romulosousa27** [Laravel-Backpack/CRUD#1498]
Hello, I need some help on the backpack, the buttons.
I have a list of products, and in the edit and delete buttons I have added two more to the `nutrient` of a` product` and its `price`. Using the backpack I do not know how to load the `id` of the product in question to put this additional information. How can I do it?

**Comment by tabacitu** [comment]
Hi @romulosousa27 ,

You can easily [add a button like so](https://laravel-backpack.readme.io/docs/crud-buttons). Inside that view file, you have ```$entry``` so you can do ```$entry->getKey()```.

Hope it helps.
Cheers!
