### ISSUE TITLE
[Refactoring req] Rename "update" form to "edit"

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1514]
There's a small inconsistency in how we add fields:
- we currently do ```$this->crud->addField($array, 'create');``` and they're used by the ```create()``` method, when showing the New Entry form; granted, they're also used in ```store()``` when they're saved;
- we currently do ```$this->crud->addField($array, 'update');```and they're used by the ```edit()``` method, when showing the Edit Entry form; granted, they're also used in ```update()``` when they're saved;

This might be nitpicking, but by OCD tells me this isn't consistent. A quick solution would be to use ```edit``` instead of ```update``` when adding fields.

But since we now have a way to determine the current controller method ([actions, check it out here](https://github.com/Laravel-Backpack/CRUD/pull/1507)), I think it would make more sense to map fields on the methods where they're actually used. Don't know if there's a good way to do that, though, since ```create``` fields are used by 2 methods and ```update``` fields are used by 2 methods too.

Food for thought.

**Comment by AbbyJanke** [comment]
Ill be the first to say it that this will obviously be a breaking change, will break every app and every package if we change from “update” to “edit” and yeah. Just making it known.

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/1516

I'm going to wait a bit before merging it, get feedback if possible and see if we don't figure out a better way to do this.
