### ISSUE TITLE
Make CrudPanel macroable

### ISSUE THREAD

**Issue by OliverZiegler** [Laravel-Backpack/CRUD#1536]
Hey folks.

Just wondering if it would be a nice feature to make CrudPanel macroable.

This way custom packages could register stuff that will be available in CrudControllers, crud views etc. for easier extendability.
As this won't provide possibilities to *override* methods (as `__call` and `__callStatic` get only called if a method does not exist [more info](http://php.net/manual/de/language.oop5.overloading.php#language.oop5.overloading.methods) this shouldn't become an issue for future updates.

See [this](https://unnikked.ga/understanding-the-laravel-macroable-trait-dab051f09172) for a short introduction on macroable.

**Comment by tswonke** [comment]
#1518

**Comment by OliverZiegler** [comment]
As I searched but clearly was kind of blind i will close this one 🙈

**Comment by tabacitu** [comment]
:-)) good colab here

**Comment by tabacitu** [comment]
Would love your input on the PR, @OliverZiegler and @tswonke  - whether it's a good idea to do it, or something that will bring more trouble in the future.

**Comment by tswonke** [comment]
🤣

**Comment by tswonke** [comment]
my smiley was intended to be above your second comment!! ;-)
