### ISSUE TITLE
[Bug] Edit about now broken after automatic "required fields"

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/CRUD#1539]
# Bug report

### What I did:
Updated Backpack
Visited https://www.mysite.dev/edit-account-info

### What I expected to happen:
To see the edit form and it works

### What happened:
Got a stack trace from a crash
![whoops__there_was_an_error_](https://user-images.githubusercontent.com/1094740/42622649-c6bf56be-85b8-11e8-9f4e-5295d2396c56.jpg)

### What I've already tried to fix it:
Not a lot

### Backpack, Laravel, PHP, DB version:
```
mysql  Ver 14.14 Distrib 5.7.21, for osx10.12 (x86_64) using  EditLine wrapper
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
laravel/framework                     v5.6.26            The Laravel Framework.
backpack/base                         0.9.6              Laravel Backpack's base package, which offers admin authentication and a blank admin panel using AdminLTE
backpack/crud                         3.4.22             Quickly build an admin interface for your Eloquent models, using Laravel 5. Build a CMS in a matter of min...
backpack/generators                   1.2.3              Generate files for laravel projects
backpack/logmanager                   2.3.21             An interface to preview, download and delete Laravel log files.
backpack/permissionmanager            2.1.27
```

**Comment by tabacitu** [comment]
@OwenMelbz that's so weird:
- it shows and it works for me, on the latest version, no error: https://cl.ly/2p1n3v3b3Z03
- that form is just a plain old Laravel form; no connection to CRUD; so a CRUD change should _not_ break Base in any way; CRUD depends on Base, not the other way around;
- that form works by going to ```MyAccountController::getAccountInfoForm()```, which loads the view ```auth.account.update.info```; which DOES NOT LOAD ```field_wrapper_attributes```; 

The error makes no sense to me... are you sure you don't have any changes in your /vendor/ that have generated this error?

PS. How did you get such a nice output for MySQL, PHP, Laravel, Backpack versions? Would love to instruct people to do so on every bug report.

**Comment by tabacitu** [comment]
Oh and also - the [actions PR](https://github.com/Laravel-Backpack/CRUD/pull/1507/files) only added a few getters. No changes in blade files... That makes it _even weirder_ :-)

**Comment by OwenMelbz** [comment]
I've got a custom controller actually because we needed to add other fields - so that might be it... however would still be good to have anyway xD

---

regards to version outputs I just ran these commands lol

```
mysql --version
php -v
composer show | grep "backpack\|laravel/framework"
```

**Comment by tabacitu** [comment]
Pretty sure that's it. Let me know if it's not.

Thank you for the command, I think that's actually _all_ we need when people submit bug reports. Right? So I've created a PR for Base to have a command that has that output https://github.com/Laravel-Backpack/Base/pull/300

**Comment by tabacitu** [comment]
@OwenMelbz did you manage to figure this one out? It still looks like an implementation issue to me - no error for me.

Thanks!

**Comment by tabacitu** [comment]
Going to merge it anyway - doesn't hurt.
