### ISSUE TITLE
Validation rules as array cause Exception

### ISSUE THREAD

**Issue by mark-win** [Laravel-Backpack/CRUD#1542]
# Bug report

### What I did:
Defined request rules as array (to make use of [closures](https://laravel.com/docs/5.6/validation#using-closures) or [custom rule objects](https://laravel.com/docs/5.6/validation#custom-validation-rules)) as described in the Laravel docs.
Example from any Request class:
```php
...
    public function rules()
    {
        return [
            'name' => [
                'required',
                'min:5',
                'max:255',
            ]
        ];
    }
...
```

### What I expected to happen:
Working validation of array rule set.

### What happened:
ErrorException:
`ErrorException(code: 0): strpos() expects parameter 1 to be string, array given at .../vendor/backpack/crud/src/PanelTraits/RequiredFields.php:30)`
The problem is not usage of closures or rule objects, but to define a rule set as array, rather than pipe separated string.

### What I've already tried to fix it:
Really simple fix in trait `RequiredFields` incoming via PR.

The only currently working workaround I figured out, is to write a second version of each request, in which `rules()` returns a rule set only containing `required` rules on required inputs. This second request can then be passed to `$this->crud->setRequiredFields()` while `create()` and `update()` hint the original request classes. Among workarounds, this is one of the worst :smile: 

### Backpack, Laravel, PHP, DB version:
backpack/base                         0.9.6
backpack/crud                         3.4.23
mysql                                       5.7.22
PHP                                         7.2.7

**Comment by lloy0076** [comment]
It's almost certainly a bug - #1543 would fix it but it should use `===`. See the PR.
