### ISSUE TITLE
laravel backup raising 404 to return a view

### ISSUE THREAD

**Issue by pythondevman** [Laravel-Backpack/CRUD#1573]
# Bug report

### What I did:

In short what is happening is, when I try to access a route, Laravel shows a 404 error, with a short description "**Page not Found, No query results for model [App\Models\Product] teste** ".

Inside of my model I have the method "teste" which invokes a route.

```
    public function teste($crud = false)
    {
        return '<a class="btn btn-xs btn-default" href="product/teste" data-toggle="tooltip" title="Just a demo custom button."><i class="fa fa-search"></i> Add Item</a>';
    }
```
Inside of custom.php I have tried already:

```
CRUD::resource('product/teste', 'ProductCrudController@teste');
Route::get('product/teste', 'ProductCrudController@teste');
```
Inside of my Controller I have my method named teste

```
public function teste(){
    return view('vendor/backpack/crud/teste');
}
```
And finally inside of this path I have my view "which is pretty simple" and only returns a simple hello.

### What I expected to happen:
I need to build a form which allows the user to add "a component" for the product once that the product is always customized. This means, a combination of components makes up a new product. What I need is: Add a new button in the product line which when clicked gonna redirect the user to add all components which makes up this product. Same idea of an order which contain items.

### What happened:
**404 - Page not found. No query results for model [App\Models\Product] teste**

### What I've already tried to fix it:
I have tried different ways to invoke the route, even trying to use a route which works "for example a working view used to display details regarding the line" still have the same error.

### Backpack, Laravel, PHP, DB version:
PHP= 7.0.10
Laravel = 5.6
MySql = 5.7.14
Backpack = 3.4

**Comment by tabacitu** [comment]
Hi @pythondevman ,

My 2 cents on this: your resource route should NOT include the controller method. Just the controller. So I assume it should be ```CRUD::resource('product', 'ProductCrudController');```; your second route (teste) should then work. [Take a look here for a full example of a CRUD](https://laravel-backpack.readme.io/docs#section-doing-it-all-very-fast).

What you're trying to achieve is definitely possible with Backpack (and easy) - you must have misconfigured something. My guess is the above.

Cheers!

**Comment by ajinzrathod** [comment]
I think there is a hacky way to do this. But this will not show the default error page of Laravel. But we can hide the description of the Error and I think this looks cooler than the default one.

Open this file **resources/views/errors/layout.blade.php**
```php
@if ($staff_designation == 'admin')  // <- add this line
    <small>
        @yield('description')
    </small>
@endif   // <- add this line
```

To check whether the user is Admin is not, I have used a custom service provider.

**app/Providers/MyServiceProvider.php**
```php
    public function boot()
    {
        view()->composer('*', function($view) {
            $staff_designation = '';
            if (Auth::check()) {
                // write your admin logic here
                $id = auth()->user()->id;
                $staff_designation = auth()->user()->staff_designation;
            }
            return $view->with('staff_designation', $staff_designation);
        });
    }
```

> Remember to edit the Admin Logic

And add the service provider in **config/app.php**
```php
    'providers' => [
         // .....
        App\Providers\MyServiceProvider::class,
   ];
```

In this way, Error Description is viewed only to those who are admin. And all other users just get a 404 page without a Description.
