### ISSUE TITLE
Nested Resources : update and delete not saved in DB 

### ISSUE THREAD

**Issue by maxliguge** [Laravel-Backpack/CRUD#1585]
Hi, 
First of all, I'm using laravel 5.5 and backpack/crud 3.4.5 

I've followed [this](https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud) in order to create a nested ressource to only have contacts of a specified partner, with something like this **admin/partner/1196/contact** for a list of all contact for a specified partner(PartnerId = 1196) and this **admin/partner/1196/contact/1308/edit** for editing the contact with with the Id 1308.

Here is my **route** : 

```
Route::group(['prefix' => 'partner/{Id}'], function()
{
    CRUD::resource('offer',     'PartnerOffersCrudController');
    CRUD::resource('contact',   'PartnerContactCrudController');

});
```

And here is my **PartnerContactCrudController** : 

```
<?php

namespace App\Http\Controllers\Admin\Partners;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Support\Facades\Auth;

use App\Http\Requests\BasicRequest as StoreRequest;
use App\Http\Requests\BasicRequest as UpdateRequest;

class PartnerContactCrudController extends CrudController
{
    public function setup()
    {

        $Id = \Route::current()->parameter('Id');

        $this->crud->setRoute("admin/partner/".$Id."/contact");
        $this->crud->addClause('where', 'PartnerId', $Id)

        $this->crud->setModel('App\Models\PartnerContact');
        $this->crud->setEntityNameStrings('contact', 'contacts');
        $this->crud->orderBy('ContactId', 'ASC');

        // Column
          [...]

        // Field
        $this->crud->addField([
            'label'   => 'First Name',
            'name'    => 'FirstName',
            'type'    => 'text',
        ]);

        $this->crud->addField([
            'label'   => 'Last Name',
            'name'    => 'LastName',
            'type'    => 'text',
        ]);

        $this->crud->addField([
            'name' 		=> 'Civility',
            'label' 	=> 'Civility',
            'type' 		=> 'select',
            'entity' 	=> 'civility2',
            'attribute' => 'Name_EN',
            'model' 	=> "App\Models\Civility",
        ]);

        $this->crud->addField([
            'label'   => 'email',
            'name'    => 'MailAddress',
            'type'    => 'email',
        ]);

        $this->crud->addField([
            'label'   => 'Mobile Phone',
            'name'    => 'MobilePhoneNumber',
            'type'    => 'number',
        ]);

        $this->crud->addField([
            'label'   => 'Phone Number',
            'name'    => 'PhoneNumber',
            'type'    => 'number',
        ]);

        $this->crud->addField([
            'name'  => 'PartnerId',
            'type'  => 'hidden',
            'value' => $Id,
        ]);

        $this->crud->addField([
            'name'  => 'PartnerId',
            'type'  => 'hidden',
            'value' => $Id,
        ]);
    
        $this->crud->allowAccess('revisions');

    }


    public function store(StoreRequest $request)
    {

        // your additional operations before save here
        $redirect_location = parent::storeCrud($request);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }

    public function update(UpdateRequest $request)
    {
        // your additional operations before save here
        $redirect_location = parent::updateCrud($request);
        // your additional operations after save here
        // use $this->data['entry'] or $this->crud->entry
        return $redirect_location;
    }

}
```

While the listview got no problem and the edit panel is linked with the good Id (contactId), when i try to update or create a new partnerContact, it either update nothing or create a new item with missing elements (in fact everything except Civility and Id/Hash). As an exemple here is what i've got in mysql after a a new insert : 
![image](https://user-images.githubusercontent.com/31342440/43829904-627b3fe4-9b00-11e8-9a82-613897b4dcaf.png)

One of the solution would be to create another "normal" ContactController and to link edit/create button to it but, that seems a bit ugly to me ...

Any idea on how to solve this issue ?

**Comment by tabacitu** [comment]
Hi @maxliguge ,

I recommend you use a different parameter name than ```id``` in your route and controller. I'm not sure, but that may be a reason it's failing for you - there's an ```id``` for partner and an ```id``` for contact too (defined by the CRUD resource routes). I recommend you replace with ```partner_id``` in your route and controller.

Hope it helps.
Cheers!

**Comment by nioumaxime** [comment]
Hi @tabacitu ,
Thanks for your quick reply, i must agree naming it `id` was not the best idea.
I've switched my parameter to PartnerHash as it's a bit more logic, but i still have the same error tough. ...

**Comment by pxpm** [comment]
Hi @nioumaxime ,

It might be a long shot, but i notice a some pattern on the fields that are not saved on the database the naming is allways camelCase, could you try switching to snake_case field names (in crud and in database fields) and see if that works ? Also don't forget to check the $fillable property in your model.

MC,
Pedro

**Comment by nioumaxime** [comment]
Hi @pxpm ,

I double checked my Models & $fillable and everything looks fine.
For the snake_case camelCase thing i've tried to switch everything to snake_case (fields, models and DB) and unfortunately the result is still the same.

**Comment by maxliguge** [comment]
Ok,
I've updated backpack to the latest version plus rewrote from scratch my Controller/Model/Route and everything seems to work now (I still need the hidden field though), except the delete option which throw me a 403 error but it looks more like of server side problem so i'll close this issue.

Thanks for your time and keep up the good work here with backpack!
Cheers!
