### ISSUE TITLE
Typo or Something? 'update' to 'show' show.blade.php

### ISSUE THREAD

**Issue by rayrizqie** [Laravel-Backpack/CRUD#1588]
### What I did: change to 
@if ($crud->hasAccess('update')) to
 @if ($crud->hasAccess('show'))
on button show.blade.php

### What I expected to happen:
remove button preview

### Backpack, Laravel, PHP, DB version: 
 backpack/crud (3.4.28)

**Comment by tabacitu** [comment]
Definitely a typo! Thank you @rayrizqie ! Just pushed an update to fix it - please do a ```composer update``` and it'll be fixed for you.

Cheers! Thanks for bringing this up.
