### ISSUE TITLE
Crud-fields page in official documentations have error

### ISSUE THREAD

**Issue by amovsisyan** [Laravel-Backpack/CRUD#1590]
# Bug report
[Crud-fields](https://laravel-backpack.readme.io/docs/crud-fields) page in official documentations have error.

![screenshot from 2018-08-12 19-34-40](https://user-images.githubusercontent.com/25100181/44003642-f470eb24-9e66-11e8-8e30-b7dd325f5f5a.png)

### Backpack, Laravel, PHP, DB version:
Backpack version above 3.0

**Comment by tabacitu** [comment]
Thank you Arto! 

It looks like readme.io, where our docs are hosted, have pushed a bug in production, very sorry for that. We're investigating the problem and have reached out to them. 

In the meantime here's a zip of the current docs: https://cl.ly/3O3T1F090W2O
Hope i'll have a much better solution for you soon.

Cheers!

**Comment by tabacitu** [comment]
FIXED! Apparently they pushed a bug to the "code snippet" block. It breaks some pages, some it does not. I've changed that content type to regular markdown everywhere I saw it was broken, so the docs content is now visible again.

Thank you for bringing this up @amovsisyan !
Cheers!

**Comment by amovsisyan** [comment]
@tabacitu 
Amazing work !!
Thanks.
