### ISSUE TITLE
[Feature req] Image column and field source should be defined the same way

### ISSUE THREAD

**Issue by amovsisyan** [Laravel-Backpack/CRUD#1591]
There are difference in `Image` type columns and `Image` type fields related to image source.
In `Image` columns is written
`src="{{ asset( (isset($column['prefix']) ? $column['prefix'] : '') . $entry->{$column['name']}) }}" `
so it means you use only prefix.

But in `Image` fields your code is different.

`$image_url = $value`
        `? preg_match('/^data\:image\//', $value)`
           ` ? $value`
           ` : (isset($field['disk'])`
             `   ? Storage::disk($field['disk'])->url($prefix.$value)`
              `  : url($prefix.$value))`
       ` :'';`
.
.
.

         `   <img id="mainImage" src="{{ $image_url }}">`

Here you consider also Storage disk.

I expected that both of them will consider Storage disk.

As we know we can overwrite those, but this bug is for you to make project better.

Backpack version 3.4 (not sure), php version if needed 7.1

**Comment by tabacitu** [comment]
Hmm... you're right @amovsisyan , this is quite an annoying inconsistency between ```image``` field and column - and you'd expect them to work the same.

Thanks, will do!

**Comment by flartet** [comment]
Hi,
I was about to create a pull request about this. I was wondering why my BLOB image was not displayed in the column but was right in the edit form. It's because of that "asset" call in every case.
Adding the preg_match makes it work properly. (_resources/views/vendor/backpack/crud/columns/image.blade.php_)
Backpack 3.5 PHP 7.2

`  @elseif (preg_match('/^data\:image\//', $value))
      <a href="{{ $value }}" target="_blank">
          <img src="{{ $value }}" style="
            max-height: {{ isset($column['height']) ? $column['height'] : "25px" }};
            width: {{ isset($column['width']) ? $column['width'] : "auto" }};
            border-radius: 3px;"
        />
      </a>
  @else
`

**Comment by tabacitu** [comment]
Hi @flartet ,

I think you're talking about different things:
- @flartet is talking about being able to show base64 images
- @amovsisyan is talking about being able to show images from an external disk (like s3 bucket)

Either way, I've just added support for both - just pushed the update, it's a non-breaking one.
It'll be available with a ```composer update``` later today, after I push a few more changes and tag the release.

Cheers! Thanks for speaking up about this.
