### ISSUE TITLE
[Feature req] How I can activate filters logic to a route other than index and search ?

### ISSUE THREAD

**Issue by drashoor** [Laravel-Backpack/CRUD#1601]
First its not a bug its a question or improvement :)

# Bug report
In Filters.php

`

    public function doingListOperation()
    {
        $route = $this->route;

        switch ($this->request->url()) {
            case url($this->route):
                if ($this->request->getMethod() == 'POST' ||
                    $this->request->getMethod() == 'PATCH') {
                    return false;
                }

                return true;
                break;

            case url($this->route.'/search'):
                return true;
                break;

            // Here I want to return true to another route, like this:
            // case url($this->route.'/counters'):
            //    return true;
            //    break;

            default:
                return false;
                break;
        }
    }

`

**Comment by tabacitu** [comment]
Hmm... you're right, you make a good point @drashoor , thank you. ```doingListOperation()``` does prevent people from re-using the filters in their own operations...

Let me think about a solution...

**Comment by hanmuja-juango** [comment]
Hi, any update about this?, for my own project I modified the doingListOperation function and add my route, but I think is a very ugly solution...

Thanks

**Comment by tabacitu** [comment]
Hi guys,

There has been a PR in the meantime that fixes this - https://github.com/Laravel-Backpack/CRUD/pull/1886

It's been merged, so you should be able to use filters outside the list view. Let me know if that's not the case.

Cheers!
