### ISSUE TITLE
Model observer not triggering events.

### ISSUE THREAD

**Issue by tdgroot** [Laravel-Backpack/CRUD#1607]
# Bug report
I'm trying to get an observer to work with the CRUD, but am getting stuck right now. Models being saved outside of the CRUD are firing the events as expected. 

Please let me know what kind of information you'd need to investigate this problem. 

If there seems to be an issue in the CRUD package, I'm willing to contribute.

### What I did:
Added observers for a model when saved using the CRUD.

### What I expected to happen:
The observer would be called.

### What happened:
The observer didn't get called.

### What I've already tried to fix it:
- Add more methods to the observer. Currently, I'm having `saved`, `updated` and `deleted`.
- Look for similar issues, like https://github.com/Laravel-Backpack/CRUD/issues/235. In that issue it turned out the data wasn't being changed. In my case it doesn't fire the event whether I'm changing data or not. 

### Backpack, Laravel, PHP, DB version:
- `backpack/base 0.9.7`
- `backpack/crud 3.4.30`
- `laravel/framework 5.6.33`
- `PHP 7.1.21`

**Comment by lloy0076** [comment]
If they're on relations (i.e. might use the `sync` method) they won't fire events - can you be more specific (e.g. a gist or code sample)?

**Comment by tdgroot** [comment]
@lloy0076 here's a gist: https://gist.github.com/tdgroot/53a0e59f8063cf894b09742243872e47. The events aren't being fired by `parent::updateCrud()`, which shouldn't be a relation save.

**Comment by tdgroot** [comment]
@lloy0076 I let it sink in for the weekend and I found the problem. The model that the crud controller uses looks like this:

```
<?php

namespace App\Models;

class Dimension extends \App\Dimension
{
}
```

But the application observes `\App\Dimension`.

I fixed the problem in my application, it works great now. 

Sorry for the inconvenience!
