### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Mobius1** [Laravel-Backpack/CRUD#1608]
Caught a mistake in the [reorder documentation page](https://backpackforlaravel.com/docs/3.4/crud-operation-reorder#how-to-use).

This line:
```
To enable it, you should use $this->crud->allowAccess('disabled');
```

should read:

```
To enable it, you should use $this->crud->allowAccess('reorder');
```

**Comment by tabacitu** [comment]
Totally! Fixed, thank you @Mobius1 !

Our new docs are now actually on Github - so whenever you find a typo or something you can click the "Edit" button in the top-right corner of the page, and submit a PR through Github's interface. 

It should:
- be faster for you to fix than submitting a bug report;
- be faster for us to accept;
- lead to better and better documentation, in time;

Thanks again. Cheers!
