### ISSUE TITLE
reorder AJAX URL wrong scheme when using https proxy

### ISSUE THREAD

**Issue by gboor** [Laravel-Backpack/CRUD#1618]
# Bug report

### What I did:
I enabled reordering on some table, clicked the link, reordered some stuff and tried to save it.

### What I expected to happen:
The new order to be saved.

### What happened:
I received an error, the order was not saved.

### What I've already tried to fix it:
I have fixed it by overriding reorder.blade.php and changing the AJAX URL from Request::url() to URL::current() - this might be a bug in Laravel itself, but this solves the issue. URL::current() generates the correct httpS URL when forceScheme is set to HTTPS. Request::url() does not.

### Backpack, Laravel, PHP, DB version:
PHP 7.1.9
Backpack/CRUD 3.4.28
DB version irrelevant

**Comment by tabacitu** [comment]
@gboor , I see you've mentioned [here](https://github.com/Laravel-Backpack/CRUD/issues/1623) that it was the same problem as here, but the solution was setting your trusted proxy to different IPs.

Does the solution fix this problem too? Sounds like it.

Thanks!

**Comment by gboor** [comment]
@tabacitu I just checked and you are correct. This issue and the merge request can be closed.
