### ISSUE TITLE
Invalid/messy/wrong PHPDoc

### ISSUE THREAD

**Issue by AegirLeet** [Laravel-Backpack/CRUD#1624]
The PHPDoc is invalid, messy or simply wrong in a number of places. This interferes with IDEs and static analysis tools.

I'm gonna try and fix it (at least the most important, public facing stuff) and submit a PR.

Some random examples of invalid/messy/wrong PHPDoc I found:

(No types or parameter names specified)
 ```
    /**
     * Limit the number of results in the query.
     *
     * @param  [number]
     * @return [type]
     */
```

(/ instead of |, closure instead of \Closure or callable)
```
    /**
     * Add a filter to the CRUD table view.
     *
     * @param array         $options        Name, type, label, etc.
     * @param array/closure $values         The HTML for the filter.
     * @param closure       $filter_logic   Query modification (filtering) logic when filter is active.
     * @param closure       $fallback_logic  Query modification (filtering) logic when filter is not active.
     */
```

([Number] is not a valid type, false is mentioned in the description but bool isn't specified as a possible return type)
```
    /**
     * Find and retrieve the id of the current entry.
     *
     * @return [Number] The id in the db or false.
     */
```

(IDEs/static analysis will think "JSON" is the return type and look for a class named JSON in the current namespace)
```
    /**
     * The search function that is called by the data table.
     *
     * @return  JSON Array of cells in HTML form.
     */
```

**Comment by tabacitu** [comment]
Merged! Thanks a lot @AegirLeet !
