### ISSUE TITLE
date range filter 'to' date needs time

### ISSUE THREAD

**Issue by jordangottlieb-ych** [Laravel-Backpack/CRUD#1629]
Add '23:59:59' to $dates->to or filter won't work as expected, E.g.:

```
$this->crud->addFilter([
            'label' => 'Submitted',
            'type'  => 'date_range',
            'name'  => 'created_at',
        ],
        false,
        function ($value) {
            $dates = json_decode($value);
            $this->crud->addClause('where', 'created_at', '>=', $dates->from);
            $this->crud->addClause('where', 'created_at', '<=', $dates->to . " 23:59:59");
        });
```

**Comment by tabacitu** [comment]
You're totally right. Thank you @jordangottlieb-ych ! Just updated the example in the docs.

Cheers!

**Comment by jordangottlieb-ych** [comment]
🍻

**Comment by breizhwave** [comment]
funny I just spent 10 minutes on this deviant  solution :) then I searched github. Should walk backwards

`                $this->crud->addClause('where', 'created_at', '<=',date("Y-m-d",  strtotime($dates->to) + (3600*24) ));
`


and Bonus, while I'm at it, here is a hack for the date_range filter that displays last 12 months range : 

resources/views/vendor/backpack/crud/filters/date_range.blade.php:107
` <?php for ($i=0; $i<=12; $i++)
                        {?>
                        '<?= date("M Y",mktime(0, 0, 0, date("m")-$i, date("d"),   date("Y"))) ?>' : [moment().subtract(<?=$i?>, 'month').startOf('month'), moment().subtract(<?=$i?>, 'month').endOf('month')],
                         <?php }?>`

and good night everybody
