### ISSUE TITLE
Custom fields wrong documentation

### ISSUE THREAD

**Issue by pdifeo** [Laravel-Backpack/CRUD#163]
Hi,

in custom field example you wrote

`<div @include('crud::inc.fieldWrapperAttributes') >`

Must be

`<div @include('crud::inc.field_wrapper_attributes') >`

**Comment by OwenMelbz** [comment]
@pdifeo can you please click the "suggest edits" button on the documentation so it can be pin pointed please?

<img width="241" alt="screen shot 2016-10-04 at 14 58 31" src="https://cloud.githubusercontent.com/assets/1094740/19091803/f7921892-8a7b-11e6-9d33-8ede7b9cd946.png">

**Comment by pdifeo** [comment]
Done !

Regards
Pasquale
