### ISSUE TITLE
When bulk operations are enabled, the bulk checkbox label is displayed as raw HTML in the preview page

### ISSUE THREAD

**Issue by dandarie** [Laravel-Backpack/CRUD#1631]
# Bug report

### What I did:

Enabled previews and bulk operations in a CRUD controller

```
$this->crud->allowAccess(['show']);
$this->crud->enableBulkActions();
```
### What I expected to happen:

Not having a bulk operations checkbox in the preview page.

### What happened:

A HTML label and a checkbox is displayed.

![screenshot-oferte avoid work-2018 09 08-21-06-10](https://user-images.githubusercontent.com/9036450/45257353-a55f4b00-b3ad-11e8-9165-659017080b82.png)

### What I've already tried to fix it:

Removed the _blank_first_column_ and _bulk_actions_ columns in `\Backpack\CRUD\app\Http\Controllers\Operations\Show`

```
@@ -43,6 +43,9 @@ trait Show
         $this->crud->removeButton('show');
         $this->crud->removeButton('delete');
 
+        // remove bulk actions colums
+        $this->crud->removeColumns(['blank_first_column', 'bulk_actions']);
+
         // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
         return view($this->crud->getShowView(), $this->data);
     }

```

### Backpack, Laravel, PHP, DB version:

- Backpack 3.4
- Laravel 5.6
- PHP 7.2
- MySQL 5.7

**Comment by tabacitu** [comment]
You're totally right. Thank you @dandarie - such an obvious bug on my end, very sorry. Your PR fixes it perfectly, merged, thank you!
