### ISSUE TITLE
Translatable models and multi-language CRUDs form values not saved

### ISSUE THREAD

**Issue by hocklai8** [Laravel-Backpack/CRUD#1633]
# Bug report

### What I did:
Followed the documentation here 
https://backpackforlaravel.com/docs/3.4/crud-operation-update#translatable-models 

**app\Http\Controllers\Admin\PageCrudController.php**
```php
    public function setup()
    {
        $this->crud->setModel('App\Models\Page');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/page');
        $this->crud->setEntityNameStrings('page', 'pages');

        // COLUMNS
        $this->crud->addColumn([
            'name' => 'title',
            'label' => 'Title',
        ]);
        $this->crud->addColumn([
            'name' => 'status',
            'label' => 'Published',
        ]);

        // Fields
        $this->crud->addField([
            'name' => 'title',
            'type' => 'text',
            'label' => 'Title'
        ]);
        $this->crud->addField([
            'name' => 'slug',
            'label' => 'Slug (URL)',
            'type' => 'text',
            'hint' => 'Will be automatically generated from your title, if left empty.',
            // 'disabled' => 'disabled'
        ]);
        $this->crud->addField([
            'name' => 'description',
            'label' => 'Meta Description',
            'type' => 'text',
            'fake' => true,
            'store_in' => 'meta',
        ]);
        $this->crud->addField([
            'name' => 'keywords',
            'label' => 'Meta Keywords',
            'type' => 'text',
            'fake' => true,
            'store_in' => 'meta',
        ]);
        $this->crud->addField([
            'name' => 'content',
            'label' => 'Content',
            'type' => 'ckeditor',
        ]);

        // add asterisk for fields that are required in PageStoreCrudRequest
        $this->crud->setRequiredFields(StoreRequest::class, 'create');
        $this->crud->setRequiredFields(UpdateRequest::class, 'edit');
    }
```

**app\Models\Page.php**
```php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\Sluggable;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\SluggableScopeHelpers;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations;

class Page extends Model
{
    use CrudTrait;
    use Sluggable, SluggableScopeHelpers;
    use HasTranslations;

    protected $table = 'pages';
    protected $primaryKey = 'id';
    public $timestamps = true;
    // protected $guarded = ['id'];
    protected $fillable = ['title', 'slug', 'meta', 'content', 'status'];
    protected $fakeColumns = ['meta'];
    // protected $hidden = [];
    // protected $dates = [];
    protected $translatable = ['title', 'slug', 'meta', 'content'];

    protected $casts = [
        'title' => 'json',
        'slug' => 'json',
        'meta'  => 'json',
        'content' => 'json',
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_or_title',
            ],
        ];
    }

    // The slug is created automatically from the "name" field if no slug exists.
    public function getSlugOrTitleAttribute()
    {
        if ($this->slug != '') {
            return $this->slug;
        }

        return $this->title;
    }
}
```

### What I expected to happen:
The basic CRUD functionality for translatable models as per documentation

### What happened:
Does not save the values entered in the field. Affects both create or update. Check on DB records will just show value to be null e.g. {"en": null, "zh_Hans": null}

A little debugging trail
- Browser on submit post params of the form correctly.
- Checked Backpack\CRUD\app\Http\Controllers\Operations\Update updateCrud() $request value is correct
```php
$request->except('save_action', '_token', '_method', 'current_tab');
array:7 [
  "locale" => "en"
  "title" => "test title"
  "slug" => null
  "description" => "test"
  "keywords" => "key"
  "content" => "<p>content</p>"
  "id" => "1"
]
```
- Check Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations update() $attributes does not have the values entered in the form (all null).
```php
array:5 [
  "title" => null
  "slug" => null
  "content" => null
  "id" => "1"
  "meta" => array:2 [
    "description" => null
    "keywords" => null
  ]
]
```

### What I've already tried to fix it:
None

### Backpack, Laravel, PHP, DB version:
backpack/crud 3.4.33, Laravel 5.6.38, MySQL 5.7, spatie/laravel-translatable 2.2.1

**Comment by hocklai8** [comment]
Hi @OliverZiegler,
I've tested as per your suggestion. `title` removed from `$casts` array, and changing the `$casts` to `array `or `object` (my bad on this, just double checked Laravel docs there isn't `json` cast). But the issue still persist. Fake fields values are saved into DB correctly but the values are not displayed in the fields on edit.

The non-fake translatable fields were saved as null too

**Comment by OliverZiegler** [comment]
Thanks for testing. 
Will check on this later (and try to validate if your PR works and doesn't introduce new issues).

**Comment by tabacitu** [comment]
Hi @hocklai8 , @OliverZiegler ,

Sorry for getting to this so late - but it seems like a documentation issue, rather than implementation.

@hocklai8 , you have:
```php
    protected $casts = [
        'title' => 'json',
        'slug' => 'json',
        'meta'  => 'json',
        'content' => 'json',
    ];
```

But I don’t see any of them needing to be cast. From Eloquent’s point of view, they are simple text attributes. SpatieTranslatable acts as a secondary layer, and returns the proper string from the _actual_ JSON array in the db. I know it’s more complicated than it should be… but… that’s the way it works… SpatieTranslatable’s whole Unique Selling Proposition is that you can add it on top of an existing model with very little change - just use the class and define ```$translatable```. No changes to ```$fillable``` / ```$casts``` / etc.

**Could you please confirm that **removing all casts** fixes this for you?** This is what my test show - that that’s the issue. I’ve [updated the documentation](https://github.com/Laravel-Backpack/Docs/commit/3c93d82c6b6e96549a1fdc363ccef2d365a3b417) for this to be clear - I agree it could be confusing from the way I’ve previously phrased it.

Cheers!
