### ISSUE TITLE
Select2_multiple can't get selected all data with data more than 1000

### ISSUE THREAD

**Issue by ridwankustanto** [Laravel-Backpack/CRUD#1639]
# Bug report
Can't get all data in the array from select2_multiple.

### What I did:
I was selecting all data through select2_multiple and dd the request.

### What I expected to happen:
The array can contain all data when I click "select all" button on select2_multiple.

### What happened:
It was just containing 997 data which is it has a limit, bcs my actual data is more than 1000.

### What I've already tried to fix it:
Set the limit to 2000 on select2_multiple component.

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4
Laravel: 5.6
PHP: 7.1.17
DB: mysqlnd 5.0.12-dev

**Comment by tabacitu** [comment]
Hi @ridwankustanto ,

For your use case, it might work to [overwrite this field type](https://backpackforlaravel.com/docs/3.4/crud-fields#overwriting-default-field-types) and set ```maximumSelectionLength``` on the select2 to any number you want. 

BUT:
- by default there is no such limitation, not that I'm aware of
- I would NOT recommend using select2_multiple when you have 1000 entries or more; I recommend using [select_from_ajax_multiple](https://backpackforlaravel.com/docs/3.4/crud-fields#select2_from_ajax_multiple) instead
- the fact that your admins can add an entry that is _instantly_ related to 1000 entries smells a little bit - you should consider thinking whether there's something wrong with how you designed the database

Sorry I couldn't be of more help.
Cheers!

**Comment by hellodit** [comment]
it is possible to set `maximumSelectionLength` without  overwrite this field type?

**Comment by pxpm** [comment]
@hellodit afaik no there isn't. 

PR's are welcome, but can't guarantee it will make it to core.

Best,
Pedro
