### ISSUE TITLE
Displaced table headers while not using responsive_table

### ISSUE THREAD

**Issue by tswonke** [Laravel-Backpack/CRUD#1640]
# Bug report

### What I did:

`'responsive_table'        => false,`

### What I expected to happen:

I can resize the window and table headers are moving correctly

### What happened:

Table headers are displaced until reload

### Backpack, Laravel, PHP, DB version:

Latest Backpack, latest Safari/Chrome

**Comment by tabacitu** [comment]
Hmm... @tswonke what do you mean by displaced? Can you provide a screenshot please?

**Comment by tswonke** [comment]
Sure:

When I open the Crud it looks like this:

![bildschirmfoto 2018-09-24 um 11 04 04](https://user-images.githubusercontent.com/6401044/45944247-b92fc180-bfe9-11e8-85d8-96d96313079c.png)

After resizing the window horizontally it looks like this:

![bildschirmfoto 2018-09-24 um 11 04 26](https://user-images.githubusercontent.com/6401044/45944271-d19fdc00-bfe9-11e8-8a38-9c08f37802e2.png)

**Comment by tabacitu** [comment]
Oh, you're right. Thank you @tswonke - I can confirm that happens. 

Apparently when using AJAX Datatables there's not _one_ table, there's multiple:
- one for the headings
- one for the content
- one for the bottom headings

So when the window gets resized, HTML resizes the tables according to content, which is always different from content to headings. Only solution I see is to recalculate after window resizing has stopped.

Just pushed a PR for it here - https://github.com/Laravel-Backpack/CRUD/pull/1651 . Let me know if that fixes it for you too, with no side-effects. I'll merge it into master.

Cheers!

**Comment by tswonke** [comment]
Hi @tabacitu 

thanks, that seems to work! 👍

**Comment by tswonke** [comment]
Just realized: this still happens when using the button to hide the sidebar ;-)

**Comment by tabacitu** [comment]
Great! Thank you @tswonke ! Also fixed it on sidebar change - let’s move the conversation to PR #1651 if anything else shows up.

Cheers!
