### ISSUE TITLE
Using Relations in addField and addColumn as name

### ISSUE THREAD

**Issue by ahmetanbar** [Laravel-Backpack/CRUD#1645]
# Bug report
I try to use relationships in name state as DB column name. I could in addColumn, but I couldn't in add Field.

### What I did:
`public function setup()
    {
        $this->crud->setModel('App\Models\Article');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/article');
        $this->crud->setEntityNameStrings('article', 'articles');

        $this->crud->addColumn(['name' => 'user.username', 'type' => 'text', 'label' => 'Author']);

        $this->crud->addField(['name' => 'user.username', 'type' => 'text', 'label' => 'Author_id']);
        
        $this->crud->setRequiredFields(StoreRequest::class, 'create');
        $this->crud->setRequiredFields(UpdateRequest::class, 'edit');
}`

### What I expected to happen:
As I can see in columns, reaching to user.username in Fields
### What happened:
Columns work, I can see user.username in columns but I can't see user.username in Fields. When I write 
`$this->crud->addField(['name' => 'user', 'type' => 'text', 'label' => 'Author_id']);` 
I can see all the fields of user. But user.username doesn't work in fields.
### What I've already tried to fix it:
name=> user->username
### Backpack, Laravel, PHP, DB version:
Backpack 3.4
Laravel 5.5.43
PHP 7.0.27
 

It is my first issue.

**Comment by tabacitu** [comment]
Hmm I see why you'd think that might work for ```text``` fields. Thank you.

But it doesn't, unfortunately. Please use [the select field type](https://backpackforlaravel.com/docs/3.4/crud-fields#select).

Cheers!

**Comment by ahmetanbar** [comment]
Now , I use select field type. Thank you for corretting my issue.

**Comment by williamodiomonafe** [comment]
Why is this closed when the issue persists. I still face the same challenge and followed through the documentation: https://backpackforlaravel.com/docs/4.0/crud-columns#text

**Comment by pxpm** [comment]
@williamodiomonafe The issue reported earlier is identified and we provide a solution (use select) .

If your issue is different than this, please open a new PR, or paste your code/error you are getting so we can help you out.

Best,
