### ISSUE TITLE
[Bug] Select_from_array column cannot display multiple values

### ISSUE THREAD

**Issue by danielbidala** [Laravel-Backpack/CRUD#1648]
I have a multiselect field in my controller for example with the options below:
`'options' => ['S' => 'Small', 'M' => 'Medium', 'L' => 'Large']`

The values (array keys S, M, L) stored in the db as json. When I display the column as array I get a comma separated list for example L, M

My question that how to display the $values ( Large, Medium ) instead of $keys. Thanks in advance!

**Comment by jsvini** [comment]
You could use the <a href="https://laravel-backpack.readme.io/v3.3/docs/crud-columns-types#section-model_function">model_function</a> column type, in the function you can do the transformations you need.

**Comment by danielbidala** [comment]
Thanks @jsvini, I figured it out but my solution is not too elegant:

`public function getServiceAttributes() {
        $service_keys = $this->service;
	$service_labels = [1 => "pdf bizonyítvány", 2 => "nyomtatott bizonyítvány", 3 => "beszabályozás", 4 => "gravírozás", 5 => "minősítés" ];
	$service = array_combine($service_keys, $service_keys);
	$service = array_intersect_key ($service_labels, $service);
		
	return implode(', ', $service);
 }`

I think a **select_from_array_multiple** column type is a must have...

**Comment by danielbidala** [comment]
Maybe can I get the defined field options from my Controller in the above model function?

**Comment by pxpm** [comment]
Maybe you can use `$this->crud->getCreateFields()` or `getUpdateFields()` and work it from there.

Hope it helps you.

Br,
Pxpm

**Comment by tabacitu** [comment]
Hi @danielbidala ,

Help me understand your use case - it sounds like something we could improve in Backpack:
- you're using a ```select_from_array``` field type, with ```'allows_multiple' => true```;
- but neither ```select_from_array``` column nor an ```array``` column won't show the value properly;

Is this correct?

Thanks!

PS. If so, I think the most _intuitive_ thing to do would be to make the ```select_from_array``` column support multiple values too (```if {is array} echo {imploded string with enumeration}```). I think it's reasonable to expect the ```select_from_array``` column to be the best way to show the ```select_from_array``` field.

**Comment by danielbidala** [comment]
HI @tabacitu ,

Thanks for your interest. I have a `select2_from_array` field defined as below:

```
$this->crud->addField([
	'name' => 'service',
	'type' => 'select2_from_array',
	'label' => 'Szolgáltatások',
    	'options' => [1 => "pdf bizonyítvány", 2 => "nyomtatott bizonyítvány", 3 => "beszabályozás", 4 => "gravírozás", 5 => "minősítés" ],
	'allows_multiple' => true
	]);
```
(The field is casted to array)

If I use `array` column type I get the `array $keys` (1,2,3 etc) in list view. But I need a comma separated list of `array $values` (pdf bizonyítvány, nyomtatott bizonyítvány etc.)

With 'select_from_array' column type I get a pnotify error in list view: Error loading page. Please refresh the page. And my list table is totally empty...

**Comment by tabacitu** [comment]
Fixed! A ```composer update``` should fix it for you - ```select_from_array``` can now correctly display multiple values, if that’s the case.

Thank you for opening this issue @danielbidala !
