### ISSUE TITLE
Too many files in the public/vendor folder

### ISSUE THREAD

**Issue by Athuli7** [Laravel-Backpack/CRUD#1653]
# Bug report
The public/vendor folder is too big and polluted. It's almost 9K files. I tried to remove the unwanted files without 

### What I did:
Deploy to Google App Engine Standard Env PHP 7.2

### What I expected to happen:
The site to work

### What happened:
I ran into the 10K files limit

### What I've already tried to fix it:
1. Base href, stupid idea, I know
2. return 301 on a wildcard route to handle assets after uploading the files to s3.
3. Deleting files and/or using gcloudignore (similar to gitignore) to not upload unwanted files.
4. Implement the static files implementation in AppEngine, but apparently, even that's counted in the limit.

### Backpack, Laravel, PHP, DB version:
        backpack/base: 0.9.0
        backpack/crud: 3.4.0
        laravel/framework: 5.7
        php: 7.2
        MySQL: 5.7.14 (Google CloudSQL)

**Comment by AbbyJanke** [comment]
While i will agree 9k files is alot for the public/vendor folder here is my next question, how many are in the “vendor” folder creates by laravel, depending on what other packages you installed probably quite abit tbh. Just curious if its more then just the public/vendor.

**Comment by Athuli7** [comment]
Vendor has a lot more. The vendor/backpack alone should house more than 9k as public/vendor is published from vendor. But that doesn't create too much of an issue as dependencies aren't counted by App Engine. public/vendor is counted and you really can't git ignore it and publish it at deploy.

**Comment by promatik** [comment]
I agree, the main problem is publishing adminlte, isn't it possible for backpack to use adminlte from `\vendor\almasaeed2010\adminlte` ?

**Comment by Athuli7** [comment]
Can't be done. Asset files are best served from public folder

**Comment by tabacitu** [comment]
@promatik - AdminLTE could be used from the vendor folder, actually, either with a symlink or with a custom filesystem disk that points there… I thought that would be a good solution too… my thoughts and the feedback I received on it here - https://github.com/Laravel-Backpack/CRUD/issues/1404 Please check it out if you have the time.

@Athuli7 , I think you could delete your ```public/vendor/adminlte``` folder and just add a symlink to ```vendor/almasaeed2010/adminlte``` instead. That should reduce the number of files by A LOT. Let me know if that works for you.

**Comment by tabacitu** [comment]
In Mac OS to create a symlink you do ```ln -s /path/to/source /path/to/destination```

**Comment by tabacitu** [comment]
Let’s move the conversation to [this existing issue](https://github.com/Laravel-Backpack/CRUD/issues/1404) please - since there’s already a lot of feedback there.
