### ISSUE TITLE
How to make enableAjaxTable work?

### ISSUE THREAD

**Issue by BobbyBorisov** [Laravel-Backpack/CRUD#1657]
Hey guys! I like a lot Backpack for Laravel. I have one question though.

It turned out I have a lot of records in one of the tables and I want to use the enable the ajax in order to not fetch everything at once. I saw i need to use enableAjaxTable function but in the documentation it says some fields won't be sortable & searchable anymore. Currently I have plenty of model_function in this CrudController.  Is there any workaround to make it searchable & sortable? maybe make this model_function .. custom attribute function e.g. getSomethingAttribute? What I need to do to make it happen? Any experience with this?

I would appreciate any tips for making this happen cause otherwise I am clueless what to do. Is it used in a commercial product so we have a licence.

Kind Regards

**Comment by tabacitu** [comment]
Hi @BobbyBorisov ,

Actually, Ajax Datatables have been active by default for over a year now, so you're probably already using them, if you're on a relatively new Backpack version.

Unfortunately searching thorough something that has been generated in PHP, not database, is impossible using Eloquent - it's a technology limitation. But you can make the columns searchable by adding your own search logic, basically telling Backpack where to search and how, for those columns. Take a look at [custom search logic for columns](https://backpackforlaravel.com/docs/3.4/crud-columns#custom-search-logic-for-columns).

Hope it helps.
Cheers!

**Comment by BobbyBorisov** [comment]
Hey @tabacitu

The project I am working on is using older version, I just cloned the demo repo of backpack and playing with it! Will try to upgrade to the newest version and see how it goes! 

Multumesc for the tip! 
Cheers, frate!
