### ISSUE TITLE
addclause with where in (1,2,5,4,10) inside the crud controller

### ISSUE THREAD

**Issue by passodeluz** [Laravel-Backpack/CRUD#1660]
Iam trying to use addclause, but instead of use a filter in my where that get only one value, I need to use a list of values, like this

$this->crud->addClause('where', 'customer_id', 'in', [1,3,5,6,7]);

Its possible? how to make it happen?

thanks in advance.

I did a question in stackoverflow also:

https://stackoverflow.com/questions/52816364/how-do-i-specify-an-in-clause-in-laravel-backpack/52830835#52830835

**Comment by tabacitu** [comment]
![source](https://user-images.githubusercontent.com/1032474/47411772-7ab92e00-d772-11e8-9096-2a6ae2e74b44.gif)

Larave’s ```whereIn``` should do the trick - https://laravel.com/docs/5.7/queries#where-clauses


![screenshot 2018-10-24 at 09 53 44](https://user-images.githubusercontent.com/1032474/47411864-b81dbb80-d772-11e8-916b-a671de4b7664.png)
