### ISSUE TITLE
Using a column which is not 'id' within the CRUD

### ISSUE THREAD

**Issue by GonrasK** [Laravel-Backpack/CRUD#1666]
# Bug report

### What I did: 
I have 2 models - One for websites and other is for countries. The relationship is one-to-many (one country for many websites). The migrations were set up just fine, and the models were created with the right relationships as well.
The website model has -

`public function countries()
	{
		return $this->belongsTo('App\Country');
	}`

And the country model has -

`public function websites()
	{
		return $this->hasMany('App\Website'); }`

The relationships were defined with foreign keys within the migrations as well.

### What I expected to happen:

When I use backpack's crud and i'm willing to add/edit/view my website entries - I would like to see the country's name, instead of its' id number which doesn't help me a lot..

### Backpack, Laravel, PHP, DB version:

Laravel Framework 5.7.9
PHP 7.2.2 (cli) (built: Feb 15 2018 06:03:56) 
Backpack 3.4

**Comment by AbbyJanke** [comment]
Did you define the “attribute” on the field? Thats what determines which database column is played on select fields.

**Comment by GonrasK** [comment]
How do I set it?

**Comment by AbbyJanke** [comment]
https://backpackforlaravel.com/docs/3.4/crud-fields#select-1-n-relationship
