### ISSUE TITLE
Loading and populationg dropdowns hierarchically 

### ISSUE THREAD

**Issue by GonrasK** [Laravel-Backpack/CRUD#1668]
I was wondering if there's any feature within backpack itself that would allow me load a dropdown after a dropdown, according to the selected option in the first dropdown.

For example - I have a 'Website' model which hold a foreign key to the 'Industry' model.. And now comes the third model called 'Campaign' - which depends on on both industry -and- website models.
What I'm willing to achieve is that while creating a new campaign - first, an 'industry' dropdown will let me choose an industry from the database.. after I chose the industry - I would like the second dropdown to get populated as a result of the chosen industry.. and after I select the website - There'll be a third dropdown with the website pages in the chosen website.. and so on.

**Comment by tabacitu** [comment]
Hi @GonrasK ,

This is a common scenario, so it’s something we’re actively working on making easier. Until now, the preferred solution has been to just [create your own field type](https://backpackforlaravel.com/docs/3.4/crud-fields#creating-a-custom-field-type) for those interconnected selects. But [we now have a PR to make this easier using existing selects](https://github.com/Laravel-Backpack/CRUD/pull/1484). If you like this solution, I suggest you [publish and overwrite the select2_from_ajax field](https://backpackforlaravel.com/docs/3.4/crud-fields#overwriting-default-field-types) and make those minor modifs in your file. 

To use the updated file, once the PR is merged, just delete the file you’ve created now. You’ll find out we’ve published the feature from the monthly newsletter (I expect in 1-2 weeks).

Hope it helps.
Cheers!
