### ISSUE TITLE
Filter select2_multiple

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/CRUD#1671]
# Bug report
 I want to filter my datatable with multiple values, for instance i want to filter my users where their relational model USERINFO have degree_id from the selection i made in the filters.
### What I did:
```
$this->crud->addFilter([ // select2_multiple filter
                  'name' => 'degree_id',
                  'type' => 'select2_multiple',
                  'label'=> 'Degree'
                ], function() { // the options that show up in the select2
                    return Degree::get()->pluck('name', 'id')->toArray();
                }, function($values) { // if the filter is active
                    foreach (json_decode($values) as $key => $value) {
                        $this->crud->query = $this->crud->query->whereHas('UserInfo', function ($query) use ($value) {
                            $query->where('degree_id', $value);
                        });
                    }
                });
```
my users have degree_id for bachlor, masters, mphil or phd. so i want to filter to those users which either are in masters or mphil. but once i select one value, the next value filters the filtered results instead of showing for both.
### What I expected to happen:
from the filters, i selected masters and mphil, i wanted to show all users which belongs to either master or mphil (both in the table)
### What happened:
it filtered for masters first and when i selected other value, it tried to filter from within the filtered results so it got to 0 results.
### What I've already tried to fix it:
tried with ``$query->whereIn('degree_id', $value);``
### Backpack, Laravel, PHP, DB version:
"php": ">= 7.0",
"laravel/framework": "5.5.*",
"backpack/base": "^0.8.0",
"backpack/crud": "^3.3.0",

**Comment by tabacitu** [comment]
Hi @mpixelz ,

I think that's got more to do with your query, rather than Backpack. Sounds like you need to use OR, not AND, when multiple items are selected. Something like ```orWhereHas()``` instead of ```whereHas()```. Don't know if it actually exists.

Sorry.
Cheers!

**Comment by mpixelz** [comment]
@tabacitu 
sorry to bother you.. but ive tried everything i could but still can't seem to get it to work..
```
$this->crud->addFilter([
                  'name' => 'campus',
                  'type' => 'select2_multiple',
                  'label'=> 'Campus'
                ], function() {
                    return Campus::get()->pluck('name', 'id')->toArray();;
                }, function($values) {
                    foreach (json_decode($values) as $key => $value) {
                         $this->crud->addClause('WhereHas', 'UserInfo', function($query) use ($value){
                            $query->where('campus_id', $value);
                        });
                    }
                });
```
this works when i use only one value.. but when i select second value.. result is 0 because i think it is trying to filter from within the previously filtered results. and when i try this:

```
$this->crud->addFilter([
                  'name' => 'campus',
                  'type' => 'select2_multiple',
                  'label'=> 'Campus'
                ], function() {
                    return Campus::get()->pluck('name', 'id')->toArray();;
                }, function($values) {
                    foreach (json_decode($values) as $key => $value) {
                         $this->crud->addClause('orWhereHas', 'UserInfo', function($query) use ($value){
                            $query->where('campus_id', $value);
                        });
                    }
                });
```
it doesn't work at all.. no error.. no filter.. nothing at all..
there is nothing in the docs, stackoverflow or even on gitter.. 😢

**Comment by johnpuddephatt** [comment]
@mpixelz quick shot in the dark but have you tried looping inside the addClause rather than adding multiple clauses? i.e. something like:

```
function($values) {
    $this->crud->addClause('WhereHas', 'UserInfo', function($query) use ($value){
        foreach (json_decode($values) as $key => $value) {
            $query->orWhere('campus_id', $value);
        });
    }
}
```

**Comment by johnpuddephatt** [comment]
Looks like `where` must be used before `orWhere`, so try the below:

```
function($values) {
    $this->crud->addClause('WhereHas', 'UserInfo', function($query) use ($values){
        foreach (json_decode($values) as $key => $value) {
            if($key === 0) {
                $query->where('campus_id', $value );
            }
            else {
                $query->orWhere('campus_id', $value);
            }
        });
    }
}
```

**Comment by mikiman2028** [comment]
> Looks like `where` must be used before `orWhere`, so try the below:
> 
> ```
> function($values) {
>     $this->crud->addClause('WhereHas', 'UserInfo', function($query) use ($values){
>         foreach (json_decode($values) as $key => $value) {
>             if($key === 0) {
>                 $query->where('campus_id', $value );
>             }
>             else {
>                 $query->orWhere('campus_id', $value);
>             }
>         });
>     }
> }
> ```

I'm getting "Undefined variable: key" error using this code. Any hint? Thanks
