### ISSUE TITLE
[Feature request][4.0] Modal Table Details Row

### ISSUE THREAD

**Issue by tiagosimoesdev** [Laravel-Backpack/CRUD#1672]
Table Details Row is great , but maybe should be an option to choose if we want inside the table the details or in a modal ? IMO a modal is easier for the eyes.

**Comment by tabacitu** [comment]
Hmm… I think you make a good point @tiagosimoesdev . Modal might be better. However:
- the responsive functionality now shows any columns that didn’t fit the viewport (in a modal); this should render the details_row useless in 99% of use cases;
- it should be pretty easy to create a custom “details” button that opens a modal, if you need to show something super-specific;

So I don’t think we should rework details_row into opening a modal. Sorry.

Maybe a better thing would be to have a tutorial / template about [creating a custom button](https://backpackforlaravel.com/docs/3.4/crud-buttons#adding-a-custom-button-with-a-blade-file) that opens a modal. @tiagosimoesdev if you do create a tutorial/example for this, please share it with us (link or code) - happy to promote it.

PS. I might be wrong about this. Let me know if you think that, and please anybody who disagrees jump in with your opinion. Everybody's wrong at least once a day - I’m not the exception :-)

**Comment by tabacitu** [comment]
This looks great! Good job - and thanks for sharing. I’m sure people will find it useful.

Alternatives would probably be [DataTables Editor](https://editor.datatables.net/) and maybe [x-editable](https://vitalets.github.io/x-editable/demo-bs3.html) - but I’m not sure Backpack ill implement any of these in the core any time soon...
