### ISSUE TITLE
SimpleMDE Field

### ISSUE THREAD

**Issue by jacobzlogar** [Laravel-Backpack/CRUD#1673]
# Bug report

### What I did:
- Added a SimpleMDE field
- Attempted to edit
- Editing doesn't work, and no console errors

### What I expected to happen:
- To be able to edit

### Backpack, Laravel, PHP, DB version:
- Backpack/Base 3.4.0
- Laravel 5.7
- Mysql 5.7.23

**Comment by tabacitu** [comment]
Hi @jacobzlogar ,

That’s weird - it totally works in my tests: https://cl.ly/e0eb1095dc45

Any chance you can post a video of your experience - maybe I can figure out what’s wrong that way.

Cheers!

**Comment by tabacitu** [comment]
Just tried it again and it worked for me, so I can't replicate the bug. @jacobzlogar , if you're still having this issue please let me know and we'll reopen this.

Cheers!
