### ISSUE TITLE
select2_from_ajax fields pagination not working

### ISSUE THREAD

**Issue by bauersfeld** [Laravel-Backpack/CRUD#1676]
# Bug report

Select2 v4 expects a **pagination.more** value in the response, but you are just returning **more**.  This affects the select2_from_ajax.blade.php and select2_from_ajax_multiple.blade.php fields.  I needed to change the following code from

```
var result = {
    results: $.map(data.data, function (item) {
        textField = "{{ $field['attribute'] }}";
        return {
            text: item[textField],
            id: item["{{ $connected_entity_key_name }}"]
        }
    }),
    more: data.current_page < data.last_page
};
```

to the following

```
var result = {
    results: $.map(data.data, function (item) {
        textField = "{{ $field['attribute'] }}";
        return {
            text: item[textField],
            id: item["{{ $connected_entity_key_name }}"]
        }
    }),
   pagination: {
         more: data.current_page < data.last_page
    }
};
```

**Comment by tabacitu** [comment]
Ouch! You’re totally right @bauersfeld !

Thanks a lot, I’ve just pushed the fix on ```master```, it’ll be available with ```composer update``` later today, after I bundle it with a few more non-breaking changes.

Cheers! Keep ‘em coming.
