### ISSUE TITLE
Allow textarea columnType to be searchable by default

### ISSUE THREAD

**Issue by ryancwalsh** [Laravel-Backpack/CRUD#1678]
# Bug report

### What I did:
I tried to use the ajax search for a table that had a column of textarea type.

### What I expected to happen:
I'd see results that matched my query.

### What happened:
There was no filtering at all. ALL records continued to show in the results list.

### What I've already tried to fix it:
I seemed to be able to fix it by editing the code in your library: Adding `case 'textarea':` under `case 'text':` in https://github.com/Laravel-Backpack/CRUD/blob/3.4.35/src/PanelTraits/Search.php#L69 **seems to fix it. Is there a good reason for it not to be there? Thanks.**

### Backpack, Laravel, PHP, DB version:
^3.4, Laravel 5.7.*, PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli), MySql 5.7.21-0ubuntu0.16.04.1 (Ubuntu)

**Comment by ryancwalsh** [comment]
Adding the following to the `public function setup()` of my `ContactNoteCrudController` was an alternative solution, but I'm just curious whether you meant to also write `case 'textarea':` as I mentioned in the bug report above.

    $this->crud->addColumn([
            'name' => 'note',
            'label' => 'Note',
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhere('note', 'like', '%' . $searchTerm . '%');
            }
        ]);

**Comment by tabacitu** [comment]
Hmm... thank you for the bug report and suggestion @ryancwalsh . You're totally right - I see no reason why ```textarea``` wouldn't have the same default search logic. Yes, some people might actually use this to show HTML - and search queries within HTML might _not_ work properly every time. But it's still better than _no_ default search logic.

Definitely. Done, just pushed the update on ```master```. Will be tagged and launched later today, after I bundle it with a few more non-breaking changes.

Thanks again! Cheers!

**Comment by ryancwalsh** [comment]
@tabacitu Wow, you're awesome! That's the fastest response I've ever gotten on a repo. Your library is amazing, by the way.

**Comment by tabacitu** [comment]
Thank you :-)

Full disclosure: the fast response was just luck - unfortunately we’re plagued by the same problems as everybody else - lots and lots of issues and very little time to tackle all of them. So… don’t expect a quick answer every time. Bummer, I know :(

Cheers!
