### ISSUE TITLE
Display hasMany() relation in a table

### ISSUE THREAD

**Issue by bouffekai** [Laravel-Backpack/CRUD#1685]
Hello,

I have a Giftcard Model with this relation : 
`public function histories()
    {
        return $this->hasMany(History::class, 'giftcard_id_id', 'id')->with('giftcard');
    }`

I would like to display all the history lines related to one giftcard (in the edit view).
How can I do that ?

**Comment by tabacitu** [comment]
Hi @bouffekai ,

There are no default field types to show related entries in a table. But you should be able to [create a custom field type](https://backpackforlaravel.com/docs/3.4/crud-fields#creating-a-custom-field-type), and use that one to see/create/edit data in the forms.

Cheers!
