### ISSUE TITLE
Request: Allow slug or hash in URL for edit/view

### ISSUE THREAD

**Issue by natezeevo** [Laravel-Backpack/CRUD#1696]
We have a multi-user system using Backpack. We would like to stop users from 'guessing' the URLs to access other users' items.

Solution: Allow backpack to use an item hash field. This would be a uniquely generated field on create, which would then be used in links to view/edit/delete an item.

e.g. localhost:8000/admin/user/gwp48vup3uhc4ico784/edit

It could be enabled either as simply as adding a hash column in the database table and telling the config what this field is (e.g. if(isset(config.hash_column)) else use ID )

**Comment by AbbyJanke** [comment]
Why not just use UUID in place of an Incrementing ID rather then complicate it with a hash?

**Comment by tabacitu** [comment]
Hi guys,

@natezeevo , it sounds like what you’re looking for it exactly what @AbbyJanke recommends - UUIDs. Backpack does support UUIDs - whatever your model’s primary key is, that’s what Backpack will use for URLs. There are a bunch of “Use UUIDs in Laravel” tutorials and packages, but I’m afraid I can’t recommend a particular one.

---

That being said, it sounds like you’re not handling access to items properly. Please _please_ make sure you don’t let people see other people’s items, _even if_ they guess the URL. This can be done with a simple
```php
public function setup() {
   if ($this->crud->entry && !$this->crud->entry->canBeSeenBy(backpack_user()->id)) {
       abort(403, “You’re not allowed to see this entry.”);
   }
}
```

You can have that ```canBeSeenBy($user_id)``` method on your model, to check that the item is visible. There are plenty of other ways to do this (policies, etc), but the main thing is - DO NOT rely on users not trying different URLs than their own. Implement some privacy & security feature.

Hope it helps.
Cheers!

**Comment by natezeevo** [comment]
Thank you, that is exactly what I needed. I have the security aspect in place, it's the extra layer on top to help :)

I'll have a gander at some "Use UUIDs in Laravel" tutorials now
