### ISSUE TITLE
Using Eloquent relationship with in Select in column

### ISSUE THREAD

**Issue by Lzxe92** [Laravel-Backpack/CRUD#1697]
Let's say i have three model, Country(country_id,country_name), User(user_id,user_name) and Post(post_id,post_name)
A Post must belong to only one user, a user must have only country. 
I am trying to show a CRUD view the post model, that include the country_name which is from the country model. 

How do i get the column data of country to be shown in the column when viewing a post list.? 
I know i can set a accesor in user for each country's attribute. Is there an alternate way to access it through select method? like user.country? 

        $this->crud->addColumn([
            // 1-n relationship
            'label' => "country name", // Table column heading
            'type' => "select",
            'name' => 'country_name', // the column that contains the ID of that connected entity;
            'entity' => 'user.country', // the method that defines the relationship in your Model
            'attribute' => "country_name", // foreign key attribute that is shown to user
            'model' => "App\Models\Country",
        ]);

found the solution, as above

**Comment by tabacitu** [comment]
@Lzxe92 - an accessor sounds like the good way to go. I don’t think Laravel has a ```hasOneThrough``` relationship, only [```hasManyThrough```](https://laravel.com/docs/5.7/eloquent-relationships#has-many-through).

**Comment by JacoboDominguez** [comment]
It has now https://laravel.com/docs/7.x/eloquent-relationships#has-one-through
Any recomendations to show this information in a column or edit via a field?
Cheers
Jacq

**Comment by tabacitu** [comment]
@JacoboDominguez great to hear that - if there's a `hasOneThrough` relationship between them, then it should work as standard, using a `select` column, so either:
```php
    $this->crud->addColumn([
        'label' => "Country Name", // Table column heading
        'type' => "select",
        'name' => 'country', // name of the relationship function inside the model;
        'attribute' => "name", // foreign key attribute that is shown to user
    ]);
```

Or:
```php
    $this->crud->addColumn([
        'label' => "Country Name", // Table column heading
        'type' => "select",
        'name' => 'user.country.name', // dot notation going though relationships, then the last element being the column to show
    ]);
```

Let me know if this doesn't work for you - it should.
Cheers!

**Comment by v-s-public** [comment]
Hello. I have the same problem. I'm using Backpack 4.1, Laravel 8, PHP 7.3. 
My tables:
`
+---------+		+-------------+		+---------+
|  users  |		|  user_file  |		|  files    |
+---------+		+-------------+		+---------+
| id         |		| user_id     |		| id         |
| name   |		| file_id       |		| name   |
+---------+		+-------------+		+---------+`
I'm using reletionship `hasOneThrough`

`
public function memberFile() : HasOneThrough
{
    return $this->hasOneThrough(File::class, UserFile::class, 'user_id', 'id', 'id', 'file_id');
}
`
My setupCreateOperation() fragment with related field:
`
$this->crud->addField([
    'name'      => 'memberFile',
    'label'     => 'File',
    'type'      => 'upload',
    'upload'    => true,
    'disk'      => 'member_files',
    'attribute' => 'name'
]);
`
In this case in my form in memberFile field I see JSON:
 {"id":4,"name":"face5.jpg","disk":"member_files","created_at":"2021-07-26T12:31:38.000000Z","updated_at":"2021-07-26T12:31:38.000000Z","laravel_through_key":19}

In case when I'm using `'name' => 'memberFile.name'` it`s works fine for me, I see hte correct filename, but now field element has attribute `data-field-name="memberFile[name]"`. So, in my code I have to check file something like this:
`
$request->file('memberFile.name')
`
This may become a problem in the future, this approach may not be understood by other developers.

Maybe I am missing something and am doing something wrong?
