### ISSUE TITLE
Call of a field on collection on a 1-n relation

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/CRUD#1700]
# Bug report
I upgraded to 3.4 from 3.3 and expirience a weird behaviour.  I'm using Laravel 5.5.
If have a model `Collection`. A collection can has multiple entries. Each `Entry` belongs to max. one collection. 
It's an 1-n relation. 

Collection.php
```php
public function entries(){
     return $this->hasMany(Entry::class, 'collection_id', 'collection_id');
}
```

Entry.php
```php
public function collection(){
    return $this->belongsTo(Collection:class, 'collection_id', 'collection_id');
}
```

Also i created a custom list where I display it, called `entry_table`.

In the `CollectionCrudController` i add it like
```php
$this->crud->addField([
   'label' => 'Entries',
   'type'  => 'entry_table',
   'name' => 'collection_id', // Why is this even needed if the entity is called?
   'entity' => 'entries'
]);
```

### What I did:
Upgraded from 3.3 to 3.4.

### What I expected to happen:
I expected it to work

### What happened:
Throws an Exception: `Property [collection_id] does not exist on this collection instance.`
The execption is thrown in `PanelTraits\Update.php` at line 97. There it tries to access an eloquent collection and not an single object.

### What I've already tried to fix it:
I modified line 96 in `Update.php` and added
```php
&& !$relatedModel->{$relationMethod}() instanceOf HasMany
```
to the if query.
This solved the issue for me. I cannot tell if it has effects on other relations.

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4.40
Laravel: 5.5. latest
php: 7.1.3
MySQL: 5.7.17

**Comment by tabacitu** [comment]
Hi @sheriffmarley ,

That’s very weird. Because ```class HasMany extends HasOneOrMany``` - which we checked for. So the result should be true for both ```HasMany``` and ```HasOne```.

Don’t know exactly what could cause this difference… maybe some PHP setting…. I don’t know… I’ve just checked myself on the following system and it did NOT throw and error for me:

```shell
### PHP VERSION:
PHP 7.2.7 (cli) (built: Jun 22 2018 06:27:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies

### BACKPACK PACKAGES VERSION:
backpack/backupmanager                1.4.4              Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/base                         0.9.12             Laravel Backpack's base package, which offers admin authentication and a blank admin panel using AdminLTE
backpack/crud                         3.4.40             Quickly build an admin interface for your Eloquent models, using Laravel 5. Build a CMS in a matter of minutes.
backpack/generators                   1.2.4              Generate files for laravel projects
backpack/logmanager                   2.3.23             An interface to preview, download and delete Laravel log files.
backpack/menucrud                     1.0.13             An admin panel for menu items, using Backpack\CRUD on Laravel 5.
backpack/newscrud                     2.1.6              An admin panel for news with categories and tags, using Backpack\CRUD on Laravel 5.
backpack/pagemanager                  1.1.23             Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
backpack/permissionmanager            2.1.27             Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                     2.1.1              Application settings interface for Laravel 5 using Backpack CRUD.
eduardoarandah/backpacklogviewer      1.0.5.1            Integrate ArcaneDev/LogViewer in your Laravel-Backpack project
laravel/framework                     v5.7.13            The Laravel Framework.

### MYSQL VERSION:
mysql  Ver 14.14 Distrib 5.7.22, for osx10.13 (x86_64) using  EditLine wrapper
```

I’ll check on a few other systems and get back to you - thank you.

Cheers!

**Comment by ariaenggar** [comment]
@tabacitu, 

I am using 3.6, and facing the same issue when implementing select2_from_ajax, my concern is why why it's accessing `$relatedModel->{$relationMethod}->{$field['name']}` directly when `$relatedModel->{$relationMethod}` returns Collection instance?
Am I missing something on implementing the relationships? I already have both hasMany and belongsTo methods

**Comment by tabacitu** [comment]
Hi @ariaenggar ,

As far as I can tell, we're using ```$relatedModel->{$relationMethod}->{$field['name']}``` there because we don't need to return the collection. We need to return the actual content for that column.

What similar problem are you facing with ```select2_from_ajax```, @ariaenggar ? Can you please provide more details.

PS. I'll close the issue as it seems the problem was happening for a custom field type - which of course is out of the scope of Backpack. Also, 8 months have passed and we could not confirm the bug, nor has anybody else hit the same wall.

**Comment by ariaenggar** [comment]
@tabacitu 
I'll make it brief:

### What I did:
Projects model:
```
class Project extends Model
{
    use CrudTrait;

```

What I expected to happen:
I expected it to work

What happened:
Throws an Exception: Property [collection_id] does not exist on this collection instance.
The execption is thrown in PanelTraits\Update.php at line 97. There it tries to access an eloquent collection and not an single object.
