### ISSUE TITLE
[BUG] Image field not working with custom wrapperAttributes

### ISSUE THREAD

**Issue by bl8m** [Laravel-Backpack/CRUD#1716]
I was stuck on image upload that didn't worked. No data was sent for the image field. 
After some debug I found that the cause was my custom *wrapperAttributes* property.

**MY CRUD CONTROLLER**
`
$this->crud->addField([ 
            'label' => "Immagine",
            'name' => "picture",
            'type' => 'image',
            'upload' => true,
            'crop' => false,
            'aspect_ratio' => 0,   
            'tab' => 'Altre informazioni',
            'wrapperAttributes' => [
               'class' => 'form-group col-sm-3'
             ] 
        ]);`

My custom attributes ovverrided the original one, and so I've lost the **image** class that is mandatory for the uploader javascript to work.

**ORIGINAL FILE vendor/backpack/crud/src/resources/views/fields/image.blade.php**

***Line 2***
`
if (!isset($field['wrapperAttributes']) || !isset($field['wrapperAttributes']['class']))
    {
        $field['wrapperAttributes']['class'] = "form-group col-md-12 image";
    }
`

***Line 125***
`
jQuery(document).ready(function($) {
                // Loop through all instances of the image field
                $('.form-group.image').each(function(index){
[...]
`

There is a simple solution to this issue, wrap every image field in an outer element using a new class (I'll commit a new version of the file ASAP), but for now it would be useful to report in the documentation that the wrapperAttributes must contain *form-group* and *image*

**Comment by pxpm** [comment]
I'v checked and it's true. The workaround proposed by bl8m (wrap the images in an outer class) should do the trick. Or in image field we can check if wrapper attributes contains "image", if not we can add it.

**Comment by tabacitu** [comment]
Done - added to the docs! Thank you @bl8m & @pxpm !
