### ISSUE TITLE
Add class to datables row

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/CRUD#1718]
Datatables offers an option to hook in `createdRow`
```js
  createdRow: function (row, data, dataIndex) {
                  // Do stuff with the row 
    },
```

Is it possible to do this with crud without modifying the source? Maybe a hook or sth? 
I checked the DataTables documentation but couldn't find anything helpful.

**Comment by tswonke** [comment]
You can copy the list.blade.php and datatables_logic.blade.php to your project (don't forget to overwrite the call of the datables_logic in the list blade). Then you can make your changes with `createdRow`.

This would affect all of your list views.

You can also rename it to `yourname_list.blade.php` or something like that and call it in the CrudController where you need the modified view.

**Comment by tabacitu** [comment]
Yup, totally agree with @tswonke - I personally would recommend using ```$this->crud->setListView('your-view');```.
