### ISSUE TITLE
setColumns() with a foreign key

### ISSUE THREAD

**Issue by GonrasK** [Laravel-Backpack/CRUD#1719]
How can I retrieve a different attribute from a foreign model in the main crud table view?
For example - I have a a 'websites' table and a 'countries' table, and this is how my setColumns is constructed right now - 

` $this->crud->setColumns([
                    'website_name', 'website_description',
		    [   'name' => 'country_id',
			    'label' => 'Country',
			    'entity' => 'country',
			    'model' => 'App\Models\Country',
			    'attribute' => 'name'],
`

And still within the view itself I see only the countries' ids and not their names as expected.

Website model is related to the countries table like this - 

`	public function country()
	{
		return $this->belongsTo('App\Models\Country','country_id');
	}`

**Comment by AbbyJanke** [comment]
https://backpackforlaravel.com/docs/3.4/crud-columns#select

You are looking for the select column type.
