### ISSUE TITLE
[BUG] Fields - type = 'table' can only be used once

### ISSUE THREAD

**Issue by sina-rzp** [Laravel-Backpack/CRUD#172]
When adding a field using `addField()`, the '[table](https://github.com/Laravel-Backpack/CRUD/blob/52bd27d1949a5397062b50029194ba585c8e997d/src/resources/views/fields/table.blade.php)' type can only be used once. If it's used more than once, the 2nd table's add button will not work, and no items would be rendered in it either.

Things I have tried:
- Switching up the tables (let's imagine we have 2 tables, I switched table 1 with 2), and the first table always works, no matter what it is.
- The `$items` array is rendered **fine**, through **PHP**, but **not rendered on Angular** (doesn't show anything on items  = something).
- Casting both as `array`s instead.

Note, my code as below:

```
$this->crud->addField([ // Table
                                'name' => 'steps',
                                'label' => 'Steps',
                                'type' => 'table',
                                'entity_singular' => 'step', // used on the "Add X" button
                                'columns' => [
                                    'desc' => 'Description',
                                ],
                                'max' => 15, // maximum rows allowed in the table
                                'min' => 1 // minimum rows allowed in the table
                            ]);


        $this->crud->addField([ // Table
                                'name' => 'ingredients',
                                'label' => 'Ingredients',
                                'type' => 'table',
                                'entity_singular' => 'ingredient', // used on the "Add X" button
                                'columns' => [
                                    'name' => 'Name',
                                    'quantity' => 'Quantity',
                                ],
                                'max' => 15, // maximum rows allowed in the table
                                'min' => 1 // minimum rows allowed in the table
                            ]);
```

And in my model:

```
protected $fillable = ['name' , 'steps', 'ingredients'];
protected $casts = [
        'steps'  			=> 'object',
        'ingredients'      	=> 'object',
    ];
```

Anybody has a clue what's the matter? I have even tried to **save it into another blade**, yet again, it does not work.

**Comment by tabacitu** [comment]
Hi @sina-rzp 

I think it's most likely a javascript misconfiguration in ```table.blade.php```. **This bug should have been fixed about a week ago.** Can you please run a ```composer update``` and see if that fixes it? 

If not, please check if you have the following views published and they differ from the ones in the package - you might need to republish them:
- resources/vendor/backpack/crud/create.blade.php
- resources/vendor/backpack/crud/edit.blade.php
- resources/vendor/backpack/crud/form_content.blade.php
- resources/vendor/backpack/crud/fields/table.blade.php

Cheers!

**Comment by sina-rzp** [comment]
Hi @tabacitu,

Thanks for your swift reply.

Well, `composer update` did not work. Nor did, copying the files. Are [these ](https://github.com/Laravel-Backpack/CRUD/tree/52bd27d1949a5397062b50029194ba585c8e997d/src/resources/views)the latest views I should be adopting?

Please let me know. Thanks!

**Comment by OwenMelbz** [comment]
@sina-rzp no those are the old files, either your composer update did not update, or you have published views which are over-writing the package files.

The table.blade.php should look like -> https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/fields/table.blade.php (notice the angular bootstrapping at the bottom)

To check you have not got a custom template file you cannnn

1. Check manually and delete it
2. Search your project for the `table.blade.php` file and make sure there is only 1
3. find the table.blade.php within the `vendor/backpack/CRUD/src/resources/views/fields/table.blade.php` delete everything from within it, and write something obvious like "IM HERE IM HERE IM HERE" and if your webpage doesnt show that, then you definately have a custom template file that you need to locate and delete from somewhere

**Comment by sina-rzp** [comment]
@OwenMelbz, wizard! Just copying the files over #fixed it all, thanks heaps.
