### ISSUE TITLE
Call to undefined method Backpack\CRUD\CrudPanel::getHeading()

### ISSUE THREAD

**Issue by neilodiaz** [Laravel-Backpack/CRUD#1721]
# Bug report
Cannot find method `getHeading` when setting custom list view

### What I did:
Added this line of code on the CRUD controller:
`$this->crud->setListView('vendor.crud.list');`

Add a new file on my directory `views/vendor/crud/list.blade.php` where the `list.blade.php` file is from `https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/list.blade.php`

### What I expected to happen:
Should show the list but rendered the custom file.

### What happened:
Error: Call to undefined method Backpack\CRUD\CrudPanel::getHeading() (View: {my-directory-here}\inventory\resources\views\vendor\crud\list.blade.php)

### What I've already tried to fix it:
NONE

### Backpack, Laravel, PHP, DB version:

"php": "^7.1.3",
        "backpack/crud": "^3.4",
        "backpack/permissionmanager": "^3.12",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0"

**Comment by pxpm** [comment]
I think getHeading() was introduced in 3.5 and you are using 3.4 with a list.blade.php from 3.5 version.

Let me know if that's the problem.

**Comment by tabacitu** [comment]
BINGO @pxpm ! :-)) I think so too. @neilodiaz let us know if it wasn't that and we'll reopen this. Cheers! Thank you @pxpm !

**Comment by cdoouteiro** [comment]
If you retrograded from 3.5 to 3.4, run :  **php artisan view:clear** (got the same error today)
