### ISSUE TITLE
[4.1][Package / Custom Field] New field type - Pill Switch / On Off It

### ISSUE THREAD

**Issue by adoptavia** [Laravel-Backpack/CRUD#1724]
It would be great to have a toggle/pill switch instead of boring checkboxes!
I am not good enough coder to do it but it is def a would be nice!

**Comment by adoptavia** [comment]
This was actually stupidly simple! (as I am finding manythings in backpack)
I created custom field in /vendor/backpack/crud/fields/toggle.blade.php
modified the code from checkbox.blade.php in vendor file

`
<link href="{{ URL::asset('css/toggle.css') }}" rel="stylesheet" type="text/css" >
<div @include('crud::inc.field_wrapper_attributes') >
    @include('crud::inc.field_translatable_icon')
    <div class="checkbox">
        <label class="switch">

            <input type="hidden" name="{{ $field['name'] }}" value="0">
            <input type="checkbox" value="1"

                   name="{{ $field['name'] }}"

                   @if (old(square_brackets_to_dots($field['name'])) ?? $field['value'] ?? $field['default'] ?? false)
                   checked="checked"
            @endif

            @if (isset($field['attributes']))
                @foreach ($field['attributes'] as $attribute => $value)
                    {{ $attribute }}="{{ $value }}"
                @endforeach
            @endif
            >
            <span class="slider round"></span>
        </label><span>{!! $field['label'] !!}</span>

        {{-- HINT --}}
        @if (isset($field['hint']))
            <p class="help-block">{!! $field['hint'] !!}</p>
        @endif
    </div>
</div>
`
then included css in public css folder (toggle.css)
`

/* The switch - the box around the slider */
.switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 34px;
}

/* Hide default HTML checkbox */
.switch input {
    opacity: 0;
    width: 0;
    height: 0;
}

/* The slider */
.slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: .4s;
    transition: .4s;
}

.slider:before {
    position: absolute;
    content: "";
    height: 26px;
    width: 26px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
}

input:checked + .slider {
    background-color: #2196F3;
}

input:focus + .slider {
    box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
    border-radius: 34px;
}

.slider.round:before {
    border-radius: 50%;
}`

**Comment by tabacitu** [comment]
@vesper8 yes, that's planned for v4 - can't wait.

Installing a field like this should be as easy as installing the package - afterwards Backpack will auto-load the field. Death to copy-paste!!! :-)

**Comment by tabacitu** [comment]
Thanks for sharing your code @adoptavia !

**Comment by dilneiss** [comment]
thankyou very much for sharing!

**Comment by tabacitu** [comment]
I've just created a separate package with the Toggle field type you've provided @adoptavia ! Thanks again. It's super-easy to install in your own project and use.

Indeed, creating a custom backpack field isn't difficult at all. But _creating a package_ to share that field with everybody has never had a clear guide. I intend to fix that ASAP :-)

For everybody that wants a ```toggle``` field: use [this package](https://github.com/DigitallyHappy/toggle-field-for-backpack)
For everybody that wants to share their custom field with the world: fork [this package](https://github.com/DigitallyHappy/toggle-field-for-backpack); Docs coming soon! Can't wait to make this easier for everybody. Can't wait to see what you guys have built 🎉

**Comment by tabacitu** [comment]
I've just posted a [tutorial on how to create a Backpack add-ons](https://backpackforlaravel.com/docs/4.0/add-ons-tutorial). It's much better than before, but I'm still not 100% happy with the process. Will try to improve the process over time.

**Comment by tabacitu** [comment]
Let's close this since the [DigitallyHappy/toggle-field-for-backpack](https://github.com/DigitallyHappy/toggle-field-for-backpack) package completely fixes this, and I've put it up on the add-ons page so everybody can see it.

For more visibility, I guess we could add it to the docs... not sure where to draw the line though...

Thanks again for this @adoptavia !
