### ISSUE TITLE
[OPINION] Remove breadcrumbs?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1727]
Like @johnpuddephatt mentioned [here](https://github.com/Laravel-Backpack/CRUD/pull/1675#issuecomment-441395529), I don't think breadcrumbs serve any real purpose right now. They don't help with visual hierarchy, since we only go one level deep (monster > edit, monster > reorder, etc), and they're the only place to offer back functionality, since we have "back" buttons everywhere.

Should we eliminate them? Thoughts?

**Comment by promatik** [comment]
I agree, it's just visual noise since it doesn't add functionality, every button on the breadcrumb is somewhere on the page **Admin** (Dashboard) > **Entity** (is also on the Sidebar)

**Comment by AbbyJanke** [comment]
I personally like having them there, in my application i’ve customized it abit where its not a single level. What about a config option, disabled by default but can be turned on for those who like them?

**Comment by pxpm** [comment]
Agree with @AbbyJanke , it should be disabled by default, but could be enabled as optional.

**Comment by mamarmite** [comment]
Breadcrumbs are a need for neophite (in admin space). So the @AbbyJanke option is a good way I think. Config can be inifinite and messy, but wihtout having an .env vars, it could be as simple as a commented line in blade maybe ?

**Comment by tabacitu** [comment]
Thanks for the feedback everyone! I think you're right - sometimes they really _are_ needed. Ok, I've made them opt-in in v4. I think that's for the better:
- most developers don't need them
- if you do, you have them 

PR here: https://github.com/Laravel-Backpack/Base/pull/381

I'll also be working on a System to add/remove links from the breadcrumb, from the controller. I think that's important for nested CRUDs.
