### ISSUE TITLE
List table is hiding the lang menu

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/CRUD#1728]
# Bug report
List table can't have the overflow to hidden otherwise it will hide the lang menu on Edit button.

![image](https://user-images.githubusercontent.com/1838187/49006336-c7709a00-f160-11e8-894c-542cead06043.png)

![image](https://user-images.githubusercontent.com/1838187/49006378-e1aa7800-f160-11e8-91d6-4681d4b121f2.png)

**Comment by tabacitu** [comment]
Totally! Thanks again @promatik  for saving the day. Just pushed the update, please do:
```php
composer update
php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag=public --force
```

Let me know if you find anything else with this freshly-baked version. There are usually a few kinks in the first few days, but usually not as big as this one or the export buttons not showing - hope this was it :-)
