### ISSUE TITLE
[Ramblings / Discussion] 3.5 How to do nested reordering Sections/Lessons

### ISSUE THREAD

**Issue by adoptavia** [Laravel-Backpack/CRUD#1729]
I am wondering if there is a way to do this ( my brain started having a meltdown!)
I want to be able to have data from two tables (sections and lessons) and be able to make them reorder-able (is that a word) so basically being able to use the reorder function to have

Section 1
  Sub Section 1.1
     Lesson 1
     Lesson 2
  Sub Section 1.2
Section 2
Lesson 3

Or any sort of mix of the above
Any ideas how to achieve this? (Thanks for any suggestions!)

**Comment by tabacitu** [comment]
Hmm... where do you need that? As a custom operation - Like the "reorder" button that shows up next to "add new"? Or inside the create/update form?

**Comment by adoptavia** [comment]
Like the reorder  button i would think?
Basically I was thinking of adding a custom button on the detail row (or elsewhere) allowing a user to modify a curriculum structure of a course, I can reorder sections easily (or lessons for that matter) but i am trying to figure how to do both in same place (Ideal world would be in the update view of the course crud - but thats not a deal breaker

**Comment by adoptavia** [comment]
Ahh yes your a genius Doh! Thanks so much i hit a brain block ( I will go with second option - makes total sense!)
Thanks!!

**Comment by tabacitu** [comment]
Glad to help!
