### ISSUE TITLE
Discussion about custom total entries

### ISSUE THREAD

**Issue by chemitaxis** [Laravel-Backpack/CRUD#1730]
Hi, I'm using Backpack 3.5 and I have some questions about how calculation entries is done with group by.

We are using a filter for check users that has more or less invoices than X number, something like this:

```
$this->crud->addFilter([
            'name'       => 'number',
            'type'       => 'range',
            'label'      => 'Number of Invoices',
            'label_from' => 'min value',
            'label_to'   => 'max value',
        ],
            false,
            function ($value) { // if the filter is active

                $range = json_decode($value);
                if ($range->from) {
                    $this->crud->query = $this->crud->query->select('users.*')->leftJoin('invoices', 'users._id', '=', 'invoices.IdUser')->groupBy('users._id')->havingRaw('COUNT(invoices."IdUser") >= ' . (float) $range->from);

                }
                if ($range->to) {
                    $this->crud->query = $this->crud->query->select('users.*')->leftJoin('invoices', 'users._id', '=', 'invoices.IdUser')->groupBy('users._id')->havingRaw('COUNT(invoices."IdUser") <= ' . (float) $range->to);

                }
            });
```

The filter works fine, and I have the correct information, but I have a problem with the total of elements for the pagination... I have checked that it show the first number of invoices to show the total of users that pass the filter.

I know where is the problem, because backpack use a _custom query_ for count how much rows are in total to make the pagination works, with a query like this (this is checking users with more or equal than 100 invoices):

```
select count(*) as aggregate from users."users" 
left join users."invoices" on users."users"."_id" = users."invoices"."IdUser" 
group by users."users"."_id" 
having COUNT(users.invoices."IdUser") >= 100
```

The output of this query is a lot of rows, and I don't know why it don't get the total rows sum.

<img width="140" alt="screenshot 2018-11-26 at 16 08 46" src="https://user-images.githubusercontent.com/1420409/49022634-99597d00-f195-11e8-8e5a-894afd2de247.png">

If you see this picture carefully you will see that my total is not correct, it should show 19 entries, and not the 233 entries, that is the the result always of the first row.

<img width="199" alt="screenshot 2018-11-26 at 16 11 24" src="https://user-images.githubusercontent.com/1420409/49022825-1b49a600-f196-11e8-8168-eb7da4c588ff.png">

My question is... is this a bug? Or Backpack not works very well with this kind of filters... find something similar here (https://github.com/Laravel-Backpack/CRUD/issues/1519), but I would like please a response from @tabacitu. Can I overwrite this result entries total to make my pagination works fine?

Thank you much for this amazing product. We started to work last week with it, and except this issue, all works like a charm.

**Comment by chemitaxis** [comment]
Hi, I have been deeping on the code, and I think it would be greeat if I caould overwrite the totalRaws in method.

https://github.com/Laravel-Backpack/CRUD/blob/03261b30046dca5a4d19403924aaf2807290a542/src/PanelTraits/Search.php#L312

**Comment by chemitaxis** [comment]
Ok, the problem is here... https://github.com/Laravel-Backpack/CRUD/blob/8b094c1e691deea8a9ae89181bcfb9c28c9d0930/src/app/Http/Controllers/Operations/ListOperation.php#L34

You are making here the calculation... but this is not correct "always"... maybe we need to count the total of the rows in some cases... any ideas? Thanks.

**Comment by tabacitu** [comment]
Hi @chemitaxis ,

You can actually _easily_ overwrite how that happens. Just place a ```search()``` method inside your ProductCrudController, and Backpack will pick it up instead. There, you can copy-paste the original code, and change ```$totalRows``` to whatever you'd like.

**Comment by tabacitu** [comment]
Oups - sorry, I missed the point here :-)) You don't want to customize it for yourself, when filters are applied the count isn't quite right. 

Yes, I do think this is a small bug. Let me figure investigate and I'll get back to you :-)

Thanks, cheers!

**Comment by tabacitu** [comment]
Done! Just pushed a fix for it, the total should now show the right amount - it's always the number of rows in the database. Don't know how everybody missed this until now :-)

Thank you @chemitaxis !

**Comment by chemitaxis** [comment]
Thanks @tabacitu I have added this to my custom search, and works fine in ALL cases... I think it solves the problem with clauses GROUP_BY. 

```
$items = $this->crud->query->get()->count(); 
$filteredRows = $items > 1 ? $items : $this->crud->count();
```

**Comment by codercms** [comment]
@tabacitu here is work-around with GROUP BY statements:
```php
    /**
     * The search function that is called by the data table.
     *
     * @return array JSON Array of cells in HTML form.
     */
    public function search()
    {
        $this->crud->hasAccessOrFail('list');
        $this->crud->setOperation('list');

        $totalRows = $this->crud->model->count();

        $query = clone $this->crud->query;
        $query->select = [];
        $query->selectRaw('COUNT(*) as aggregate');

        $filteredRows = \DB::selectOne("SELECT SUM(aggregate) FROM ({$query->toSql()}) t", $query->getBindings())->sum;

        // ....
```

**Comment by codercms** [comment]
@tabacitu I think it will be great, if you will add check for GROUP BY statement to:
```
/**
 * Count the number of results.
 * @return int
 */
public function count()
{
    return $this->query->count();
}
```

And then apply the correct way to count when GROUP BY is used in query.

**Comment by ManuDoni** [comment]
Hello, after a year (v4.0.60) I can't make it work yet.
Using `groupBy` the count and the pagination stop working.
What can I do?
Thanks in advance.
