### ISSUE TITLE
Escaped text in select column ?

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#1733]
# Bug report

### What I did:
I setup a select column that the returned value from attribute is an anchor.

```
[
  'name' => 'proc_id',
  'label' => trans('starter::fields.process'),
  'type' => 'select',
  'model' => 'Pxpm\DocStore\Models\Proc',
  'entity' => 'process',
  'attribute' => 'idWithClient'
  ]
```

In my Proc Model i got the acessor to the attribute:

```
 public function getIdWithClientAttribute() {
        return '<a href="'.backpack_url('process/'.$this->id).'"># ' .$this->id . '</a> - <a href="'.backpack_url('client/'.$this->client->id).'">' . $this->client->name .'</a>';
    }
```

### What I expected to happen:

I would like to have an anchor displayed in my column instead of raw html.

In the docs it reads that the value will not be escaped.

### What happened:

It displays raw html, you can see in image: 

[http://prntscr.com/lo7llk](url)

### What I've already tried to fix it:

Nothing atm.

### Backpack, Laravel, PHP, DB version:

BP 3.5, LV 5.6, PHP 7.1

**Comment by promatik** [comment]
Hi @pxpm!
Check this: https://backpackforlaravel.com/docs/3.5/crud-columns#model_function

I don't know if it should work with the `select`, but I use `model_function` when I need html on my columns, the example provided in the Documentation shows you exactly how to create an `<a>` link on a column.

```
public function getSlugWithLink() {
    return '<a href="'.url($this->slug).'" target="_blank">'.$this->slug.'</a>';
}
```

**Comment by tswonke** [comment]
Maybe https://backpackforlaravel.com/docs/3.5/crud-columns#closure is even easier to output the html you want

**Comment by pxpm** [comment]
Thanks @promatik and @tswonke for the tips, i already solved it.

Just reported because as i said, in docs it states that select column will not be escaped. 

With closure or model function i had to include the relation model or in controller or in the current model depends on which type of column i'm going to use.

With select i provide the model, entity and the attribute i would like to get, without explicit having to include the related model.

Am i thinking wrong about this?

Thanks

**Comment by tabacitu** [comment]
Hmm... you're right @pxpm - I don't know when that notice started being there, but it's definitely not accurate now. I've removed it, the texts _are_ escaped. Thanks!

I think ```model_function``` is the best way to output HTML in the column cell, imho. You could just have that method ```return $this->proc->getIdWithClientAttribute()```, and keep the logic inside Proc if you're using it elsewhere too.

Cheers!

**Comment by tabacitu** [comment]
Let me know if you guys think we should _unescape_ the select column. Do keep in mind that it would be a breaking change, though... Others might have used the escaping feature _specifically_.

**Comment by tswonke** [comment]
I think it should stay unescaped. We have other ways to get unescaped HTML, working for us.
