### ISSUE TITLE
Cast String as Integer in Fields

### ISSUE THREAD

**Issue by seyacat** [Laravel-Backpack/CRUD#1739]
# Bug report
 AddColum and AddFiled have problems to recognice strings with leading zeros

### What happened:
Assign null vaues to fields when its not

### Backpack, Laravel, PHP, DB version:
backpack/base ( 1.0.2): 
backpack/crud ( 3.5.9): 
![image](https://user-images.githubusercontent.com/403917/49390694-a1ff0580-f6f7-11e8-8053-b341deeb20ca.png)

**Comment by seyacat** [comment]
protected $primaryKey = "dpa_id";
public $incrementing = false;  <---- SOLVES THE PROBLEM

**Comment by tabacitu** [comment]
Thanks for sharing your solution @seyacat . I'm sure somebody will stumble upon this and be grateful.

Cheers!
