### ISSUE TITLE
The form only displays the first image when editing an element with multiple image fields.

### ISSUE THREAD

**Issue by Alexgmin** [Laravel-Backpack/CRUD#174]
**vendor/backpack/crud/src/resources/views/fields/image.blade.php**
```
<img id="mainImage" src="{{ (isset($field['value']))?asset($field['value']):'' }}">
```
```
var $mainImage = $(this).find('#mainImage');
```
Since ids are supposed to be unique, the js only loads the first one.

I have not tested the croppping with multiple images, but everything else works fine with multiple images on the same model.

**Comment by OwenMelbz** [comment]
There is a PR waiting to be merged that addresses these sort of issues -> https://github.com/Laravel-Backpack/CRUD/pull/124

**Comment by Alexgmin** [comment]
Oh, sorry, my bad for not checking.

**Comment by OwenMelbz** [comment]
No probs, I believe @tabacitu is just pretty busy with client projects at the moment so PR will slowly but surely get merged :)

**Comment by tabacitu** [comment]
So true... so sad... :( :-)
