### ISSUE TITLE
Validation request always return string type

### ISSUE THREAD

**Issue by tepsothea** [Laravel-Backpack/CRUD#1743]
# Bug report

### What I did:.
I want Laravel backpack validation to return integer.

### What I expected to happen:
+request: ParameterBag {#1400 ▼
    #parameters: array:23 [▼
      "_token" => "**************"
      "http_referrer" => "http://***********t/create"
      "customer_code" => "KB1234"
      "name" => "technology"
      "name_local" => "welcome shop"
      "contact_name" => "welcome shop"
      "contact_name_local" => "welcome"
      "phones" => "0123456789" 
      "address" => "pp"
      "outlet_type" => 136
      "province_id" => "LA-HO"
      "district_id" => 3029  
      "commune_id" => 3029  
      "village_id" => NULL
      "location_gps" => NULL
      "outlet_size" => "S"
      "is_visit_outlet" => 1
      "channel" => 71
      "commercial_status" => 99
      "customer_status" => 49
      "status_request_reason" => ""
      "is_active" => 0
      "save_action" => "save_and_back"
    ]
  }
### What happened:
+request: ParameterBag {#1400 ▼
    #parameters: array:23 [▼
      "_token" => "**************"
      "http_referrer" => "http://***********t/create"
      "customer_code" => "1234"
      "name" => "technology"
      "name_local" => "welcome shop"
      "contact_name" => "welcome shop"
      "contact_name_local" => "welcome"
      "phones" => "0123456789" // always string not integer
      "address" => "pp"
      "outlet_type" => "136"
      "province_id" => "LA-HO"
      "district_id" => "3029"  // always string not integer
      "commune_id" => "3029"  // always string not integer
      "village_id" => ""
      "location_gps" => ""
      "outlet_size" => "S"
      "is_visit_outlet" => "1"
      "channel" => "71"
      "commercial_status" => "99"
      "customer_status" => "49"
      "status_request_reason" => ""
      "is_active" => "0"
      "save_action" => "save_and_back"
    ]
  }
### What I've already tried to fix it:

function checkIfColumnInteger($array,$request) {
    foreach ($array as $key => $value) {
        if ( isset($request[$value]) && $request[$value] == "") { 
            unset($request[$value]); 
        } 
    }
}
### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.4",

sorry everyone! this is my first issue report.

**Comment by pxpm** [comment]
I think this issue is related with #1739 and handling leading zero number.

I don't think zero leaded numbers (0123, 001) are validated as integers.

What's your field type in database? When i add 0123 in an integer column type in MySQL it's leading zeros are removed.

For now, you can try to create your own validation rule. Check laravel documentation on how to achieve that. And validate that field agains your custom integer validation.

**Comment by tabacitu** [comment]
Hi @tepsothea ,

Sorry to be so late to the issue - some things have fallen through the cracks.

Validation isn't Backpack-specific, it's entirely up to Laravel, so I recommend you [double-check the validation docs](https://laravel.com/docs/5.8/validation) if you haven't solved this already.

Sorry I couldn't be of any help.
Cheers!
