### ISSUE TITLE
Crud Permission in wrong model

### ISSUE THREAD

**Issue by seyacat** [Laravel-Backpack/CRUD#1746]
# Bug report
I have crud in develop and works perfect, but when upload to server crud assing wrong permissions model
![image](https://user-images.githubusercontent.com/403917/49705133-0800f680-fbea-11e8-8836-6c650641642a.png)

### What I did:
Copy of laravel not work as spected
### What I expected to happen:
Crud use Model 
Backpack\Base\app\Models\BackpackUser

### What happened:

Crud use model App\Models\BackpackUser

**Comment by tabacitu** [comment]
Hi @seyacat - that doesn't look like standard Backpack at all - must be something in your custom code.

**Comment by seyacat** [comment]
I solve permissions looks right on crud panel, change user model on backpak conf, base.php
but now the problem its $user = auth()->user(); return NULL;
![image](https://user-images.githubusercontent.com/403917/49737971-2acbf300-fc5c-11e8-836e-aa49dc02e6bc.png)

**Comment by seyacat** [comment]
For some reason, on working copy 
laravel auth its separately than backpack auth, i dont know much about this
solution was
// $user = auth()->user;
$user = backpack_user();

and in blade template;
//@hasRole("****")
@if(backpack_user()->hasRole("****"))
