### ISSUE TITLE
addColumn from relation table

### ISSUE THREAD

**Issue by Lenskiy-e** [Laravel-Backpack/CRUD#1752]
Hi everyone!

In my project i have two tables for product object: products (where sku,price,available, etc...) and product_description (name,description, etc...).

Tables structure
products
https://prnt.sc/lu03kg

product_description
https://prnt.sc/lu0436

I try to add column by this code in ProductDescriptionCrudController.

$this->crud->addColumn([
            'label' => 'Price',
            'type' => 'number',
            'name' => 'id',
            'entity' => 'product',
            'attribute' => 'price',
            'model' => 'App\Models\Product'
        ]);

But I get the id of product. What i'm doing wrong?

The addField for price method work right

$this->crud->addfield([
                'label' => 'Price',
                'name'  => 'price',
                'tab'   => 'Prices',
                'type' => 'number',
                'entity' => 'product',
                'model' => 'App\Models\Product'
            ]);

Thank you!

**Comment by tabacitu** [comment]
I think you're looking for the [select column type](https://backpackforlaravel.com/docs/3.5/crud-columns#select), which helps you show an attribute from a relationship.

Keep in mind "name" should be the name of the column in the database. If you put "id" there, and you use a non-relationship column (text, number, etc), it'll show the id.

Hope it helps.
