### ISSUE TITLE
Loss of the reference in the register.

### ISSUE THREAD

**Issue by romulosousa27** [Laravel-Backpack/CRUD#1755]
In my application you are entering product prices, for each quantity of it. Being that at the time of registration he asks for the reference, and returns to a general listing, instead of a listing of that certain product that received a price.

![image](https://user-images.githubusercontent.com/16408742/50035839-192f7600-ffe3-11e8-946f-d643ffa12174.png)

![image](https://user-images.githubusercontent.com/16408742/50035843-1fbded80-ffe3-11e8-9a80-79296bf903e8.png)

**Comment by tabacitu** [comment]
Hi @romulosousa27 ,

Sorry but I don't understand you question. It doesn't sound like a bug though so I'm going to close this. 
But shot in the dark here - you might be able to turn off persistent table in order NOT to have the GET parameters in the URL, if that's what you're looking for - https://backpackforlaravel.com/docs/3.6/crud-operation-list-entries#persistent-table

Cheers!
