### ISSUE TITLE
Image column from relation table

### ISSUE THREAD

**Issue by Lenskiy-e** [Laravel-Backpack/CRUD#1758]
# Bug report

Hi all!
I try to add image column from relation table, but get null.
But if I add text column from save relation table, i get expected result.
### What I did:

In ProductDescriptionCrudController

$this->crud->addColumn([ 
           'label' => "Photo",
           'type' => 'image',
           'name' => 'product.image'
 ]);

### What I expected to happen:

Somethink like this (in demo)

https://prnt.sc/lwjqhn

### What happened:

I get a NULL

### What I've already tried to fix it:

This code return expected value from price column
$this->crud->addColumn([   // Select
            'label' => "Price",
            'type' => 'text',
            'name' => 'product.price',
 ]);

### Backpack, Laravel, PHP, DB version:

"backpack/crud": "3.5",
PHP 7.1.3
MariaDB 10.3.11

**Comment by tabacitu** [comment]
Hi @Lenskiy-e ,

I think it's totally fair to assume if ```product.price``` works, that ```product.image``` would also work. However, when we introduced this functionality we only had the ```text``` column in mind, so the ```text``` column is currently the only one that supports that dot notation.

**I've just pushed an update with dot notation support for the ```image``` column type too, so you can use it after a ```composer update```**. I'll follow-up with another PR shortly, that adds support for all _other_ columns too.

Thanks for speaking up about this - it makes total sense to have this for all column types, that's more intuitive.

Cheers!

**Comment by Lenskiy-e** [comment]
Thanks for answer!
Have a nice day!

**Comment by ahmadmrj** [comment]
> Hi @Lenskiy-e ,
> 
> I think it's totally fair to assume if `product.price` works, that `product.image` would also work. However, when we introduced this functionality we only had the `text` column in mind, so the `text` column is currently the only one that supports that dot notation.
> 
> **I've just pushed an update with dot notation support for the `image` column type too, so you can use it after a `composer update`**. I'll follow-up with another PR shortly, that adds support for all _other_ columns too.
> 
> Thanks for speaking up about this - it makes total sense to have this for all column types, that's more intuitive.
> 
> Cheers!

What if you want to show one of the pictures (or maybe the first one) from related table?
For example if you have a separate table for product pictures and want to show one of them in grid.

**Comment by tabacitu** [comment]
@ahmadmrj hmmm I would probably create a [Laravel accessor](https://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators) for the first image, on the model. So then I'd be able to do something like `$product->first_image`. Then I'd use `first_image` as a column, just like it were an _actual_ column in the db. 

Bonus points - if you add `first_image` to `appends` on the Model, so `$appends = ['first_column'];', then Laravel will pick up that column as it were a real column _everywhere_, in the front-end too, not inside Backpack alone.
