### ISSUE TITLE
More than one select only show last one

### ISSUE THREAD

**Issue by tresero** [Laravel-Backpack/CRUD#1759]
# Bug report

### What I did:
I have two relationships. Partner and Status in a project. They are linked in project as partner_id and status_id. When I add them to either the addFields or addColumns, only the last one entered shows up. This only appears to affect selects.

### What I expected to happen:
Both of the fields show up.

### What happened:
Only the latest field shows up.

### What I've already tried to fix it:
```
$this->crud->addColumns([
           'status_id' => [
            'label' => 'Status',
            'type' => 'select',
            'name' => 'id',
            'entity' => 'status',
            'attribute' => 'status',
            'model' => 'App\Models\Status'],
          'partner_id' => [
            'label' => "Partner",
            'type' => "select",
            'name' => 'id',
            'entity' => 'partner',
            'attribute' => "name",
            'model' => "App\Models\Partner"]
            ]);
```
As you can see by the screenshot, only Partner displays. If I remove it, then Status shows. 

### Backpack, Laravel, PHP, DB version:
Backpack is 3.5, Laravel is 5.7, php is 7.2, DB is Postgresql 9

![image](https://user-images.githubusercontent.com/1476286/50191804-49795c00-02e4-11e9-9afc-4d6fb0855a34.png)

**Comment by tresero** [comment]
Never mind, I found the answer. I didn't recognize it. For future reference.

[https://backpackforlaravel.com/docs/3.5/crud-how-to#use-the-same-column-name-multiple-times-in-a-crud](url)

**Comment by tresero** [comment]
I spoke too soon. That works fine on addColumns, but doesn't work when used on addFields.

```
        'partner_id' => [
          'label' => 'Partner',
          'type' => 'select',
          'name' => 'id',
          'key' => 'partner_id',
          'entity' => 'partner',
          'attribute' => 'name',
          'tab' => 'Info',
          'model' => 'App\Models\Partner'],
        'status_id' => [
          'label' => 'Status',
          'type' => 'select',
          'name' => 'id',
          'key' => 'status_id',
          'entity' => 'status',
          'attribute' => 'status',
          'tab' => 'Info',
          'model' => 'App\Models\Status'],
```
![image](https://user-images.githubusercontent.com/1476286/50193568-fc998380-02eb-11e9-9831-dfbc7703b28d.png)

**Comment by AbbyJanke** [comment]
Even if it were to display both it wouldnt work when you hig submit, thats how php handles html processes forms. Just call the fields “status_id” and “partner_id” and it will work fine.

**Comment by tresero** [comment]
Thanks, that worked perfect. I'm coming from GroceryCrud and code igniter so I have a little bit of a curve.
