### ISSUE TITLE
Persistent table : wrong redirection in case of multiple CRUD for same entity

### ISSUE THREAD

**Issue by 7ute** [Laravel-Backpack/CRUD#1763]
# Bug report
This is a really edge case, but still ^^
When having multiple CRUD pointing to the same entity, and persistant tables, the JS redirects to the first view whose list url has been saved in localstorage.

### What I did:
Define 2 CRUDs with the same `$crud->entity_name_plural`, with different access roles.
Some user might change access roles during a session, and access the 2 CRUDs one at the time

### What I expected to happen:
The user can access each CRUD normally

### What happened:
The user can access the first CRUD, but is redirect when accessing the second one.
Due to list entry filter persistance (https://github.com/Laravel-Backpack/CRUD/pull/1702), when accessing the second CRUD, and as the localstorage key for storing persistant filter list is the entity_name_plural, the user is redirected to the first CRUD. In my case, if the user also changed roles, he ends up getting a 403.

### What I've already tried to fix it:
- Turning off Persistant storage of one of the CRUD.
--> but that's a loss of a really cool feature!

- Changing the localstorage key with the slugified route seems to do the job.
Something like this made it work, but hasn't been tested thoroughly :

in  `CRUD/src/resources/views/inc/datatables_logic.blade.php` line **12-15**
<pre>
var saved_list_url = localStorage.getItem('{{ <b>$crud->entity_name_plural</b> }}_list_url');
if (saved_list_url && saved_list_url!=window.location.href) {
    window.location.href = localStorage.getItem('{{ <b>$crud->entity_name_plural</b> }}_list_url');
}
</pre>
changed by
<pre>
var saved_list_url = localStorage.getItem('{{ <b>str_slug($crud->getRoute())</b> }}_list_url');
if (saved_list_url && saved_list_url!=window.location.href) {
    window.location.href = localStorage.getItem('{{ <b>str_slug($crud->getRoute())</b> }}_list_url');
}
</pre>

in  `CRUD/src/resources/views/inc/datatables_logic.blade.php` line **42**
<pre>localStorage.setItem('{{ <b>$crud->entity_name_plural</b> }}_list_url', new_url);</pre>
changed by
<pre>localStorage.setItem('{{ <b>str_slug($crud->getRoute())</b> }}_list_url', new_url);</pre>

### Backpack, Laravel, PHP, DB version:
3.5, 5.7, 7.1, 5.7

**Comment by tabacitu** [comment]
Wow - indeed a niche problem but I'm very happy you've provided a solution. Thank you @7ute let's move the conversation inside the PR - which I'm merging now.

Thanks again, cheers!
