### ISSUE TITLE
Back button should have absolute paths

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/CRUD#1765]
# Bug report

### What I did:
When clicking "« Back to all {entity}", it don't always work, for instance, if you are editing an entry, and you do click on "Save and edit this item", then the back button is going to redirect to the previous page, which is also the same as you are, the Edit page.

![image](https://user-images.githubusercontent.com/1838187/50376588-b7849280-0606-11e9-9d34-3aa1237add3a.png)

### Backpack, Laravel, PHP, DB version:
BP 3.5, Laravel 5.7

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/CRUD/pull/1777 - thanks a lot!
