### ISSUE TITLE
Error: ReflectionException (-1) Class App\Http\Middleware\CheckIfAdmin does not exist

### ISSUE THREAD

**Issue by ifyboy60** [Laravel-Backpack/CRUD#1766]
# Bug report

After installation of backpack on laravel 5.6, admin page doesnt show up but displays the following error -
 Class App\Http\Middleware\CheckIfAdmin does not exist.
Any help will be appreciated

**Comment by tabacitu** [comment]
Hi @ifyboy60 ,

I'm pretty sure you missed a step upon [installation](https://backpackforlaravel.com/docs/3.5/installation#install-core-packages). Make sure you've run BOTH these commands. The first one should publish the file you're missing - you must have not run it.

```zsh
php artisan backpack:base:install
php artisan backpack:crud:install
```

Cheers!

**Comment by fianman** [comment]
sip

**Comment by deepkh3** [comment]
It states that the CheckIfAdmin Middleware is missing. So simply creating the missing Middleware will solve the problem.
Here is the Command: 
php artisan make:middleware CheckIfAdmin

**Comment by rinabaral** [comment]
@deepkh3  thanks it was of great help

**Comment by TamangSanish** [comment]
@deepkh3  Wow I tried everything possible from my side but i couldnt find the solution but thank god 
You saved my ass

**Comment by tabacitu** [comment]
Note: If you do what @deepaksp , please make sure the middleware actually checks the user is an admin :-) An empty middleware won't do anything. Cheers!

**Comment by deepaksp** [comment]
> Note: If you do what @deepaksp , please make sure the middleware actually checks the user is an admin :-) An empty middleware won't do anything. Cheers!

haha lol .. yes please do the needful 🙏
