### ISSUE TITLE
Access the model itself on *CrudController

### ISSUE THREAD

**Issue by apair** [Laravel-Backpack/CRUD#1768]
The scenario is I want to add an array as a default value for an element of `$this->crud->addFields()` method and this array should be filled with data of the current model.
so how can I access the current model in *crudController?

My solution is to use `Route` to find out what is the ID of the model : (my model is Coupon)

```

\Route::current()->parameters['coupon'])

```

that return 208 as an ID of the model from its path  *admin/coupon/208/edit*

**Comment by tabacitu** [comment]
Hi @apair ,

Inside the controller you'll always have access to ```$this->crud```, so you can do ```$this->crud->getModel()```. But if you need the actual entry, inside an operation like EDIT, you should be able to use ```$this->crud->getCurrentEntry()```.

If you need the CRUD inside a view (like a custom field view), you'll have ```$crud``` instead of ```$this->crud```. 

Hope it helps.
Cheers!
