### ISSUE TITLE
[Feature Request] Combined Columns

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1773]
Looking to possibly have one column on the 'list' view but using multiple columns to make it happen.

Here's my thought on how to make it work:

```php
$this->crud->addColumn([
    'name' => 'name',
    'label' => 'Name',
    'type' => 'multiple_text',
    'columns' => [
        'first_name',
        'last_name',
    ]
]);
```

something i'm working on but wanted some feedback from others.

**Comment by AbbyJanke** [comment]
Created a new PR for this, Also added a "spacer" option to it so you can define how the database columns are connected. Defaults to space but can be assigned as anything such as '-'.

**Comment by imansugirman** [comment]
Hi @AbbyJanke Can this idea using https://github.com/spatie/laravel-query-builder ?

**Comment by AbbyJanke** [comment]
I don’t really see the need for it. I feel like that will just add another unncessary function to a CRUD resource.

**Comment by tabacitu** [comment]
Let's move the conversation to the PR #1774 please, since we already have it ;-)

Thanks @AbbyJanke !
