### ISSUE TITLE
"Remove Filters" displayed when all filters cleared.

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#1775]
![screen shot 2018-12-30 at 7 55 07 pm](https://user-images.githubusercontent.com/487798/50554299-ef29b500-0c6c-11e9-987c-df0521e82796.png)

Single filter, i added the filter to test it, then removed it by clicking the "-" option for dropdown but the "remove filters" persisted. not a major issue just documenting for future improvements. Likely related to my previous PR #1343

**Comment by tabacitu** [comment]
Fixed! Finally :-) 

Thanks for reporting this @AbbyJanke !
