### ISSUE TITLE
show() should not call setFromDB()

### ISSUE THREAD

**Issue by Patabugen** [Laravel-Backpack/CRUD#1779]
# Bug report

### What I did:
Setup my CRUD controller - removing setFromDB() to define things specifically.
Then I started using the preview/show() method.
I've over-written show() to fiddle a bit with the details to be output.

Background: I'm actually working on a version of show() which uses fields instead of columns - so the show() represents the edit screen.

### What I expected to happen:
I expected show() to use the columns/fields I'd added, or at least for me to be able to block it being called.

### What happened:
When my final line `return parent::show($id);` is called - the parent method calls setFromDB() and adds more fields which I didn't want.

### What I've already tried to fix it:
I've had to not call parent::show() and duplicate the rest of the code in my own controller.

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4
Laravel: 5.7
PHP: 7.2

### Other
I note this issue about depreciating setFromDB:
https://github.com/Laravel-Backpack/CRUD/issues/1436
but also this one saying it's going to stay:
https://github.com/Laravel-Backpack/CRUD/issues/1173

**Comment by tabacitu** [comment]
Hi @Patabugen ,

Indeed, ```setFromDb()``` is most likely to be deprecated (or removed) in 4.0. But for now, it's the best solution we have for a working "show" screen with zero effort. Which is what I expect 80% of Backpack developers want. 

One rule I use when making difficult decisions like this is a modified 80-20 rule. Make it super easy for how 80% of the people would want it. Then make it possible for the 20% who want it another way to change it. **What you've done is exactly what we had in mind for the show operation - it's perfectly OK to remove  ```parent::show()``` and add your own columns.** Looks like it the 20% in this case :-) Hope it wasn't too painful to change.

We don't plan on ever having fields inside the show method, but I guess you can do that too with a little more customization.

Cheers!
