### ISSUE TITLE
Delete Item Problem

### ISSUE THREAD

**Issue by A-Ronagh** [Laravel-Backpack/CRUD#178]
when delete button clicked in row show this message:

There's been an error. Your item might not have been deleted.

<img width="360" alt="screen shot 1395-07-22 at 15 35 47" src="https://cloud.githubusercontent.com/assets/6532492/19348442/cc6f707a-915a-11e6-948d-9b739b8bf863.png">

how can i fix this ?

**Comment by tabacitu** [comment]
Hi @A-Ronagh ,

This is odd. I've just checked the package and the delete functionality works, it throws me a green success message. You should open your network tab in Developer Tools to debug the problem - see what the ajax response is for that delete call - it should say the actual error.

If you've overwritten the ```destroy()``` method in your EntityCrudController that might be the culprit.

Cheers!

**Comment by A-Ronagh** [comment]
tnx for answer 
in Network Tab request return 405 Method Not Allowed

<img width="540" alt="screen shot 1395-07-22 at 20 12 27" src="https://cloud.githubusercontent.com/assets/6532492/19358123/8bc2553e-9181-11e6-9754-ea45d0ddd7a7.png">

**Comment by tabacitu** [comment]
Have you used CRUD::resource() in your routes file? Can I see it?

**Comment by A-Ronagh** [comment]
yes I Use CRUD::resource()

Route::group(['prefix' => 'adminpanel', 'middleware' => 'admin'], function()
{
//    Route::get('dashboard', 'Admin\AdminController@index');
    Route::get('config', 'Admin\AppConfigController@showEditForm');
    Route::post('config/addCoin', 'Admin\AppConfigController@addCoin');
    Route::post('config/addMessage', 'Admin\AppConfigController@addMessage');
    Route::post('config/updateAppConfig', 'Admin\AppConfigController@updateAppConfig');
    // [...] other routes

    // Dick CRUD: Define the resources for the entities you want to CRUD.
//    CRUD::resource('app-config', 'Admin\AppConfigCrudController');
    CRUD::resource('app-user', 'Admin\AppUserCrudController');
    CRUD::resource('channel-list', 'Admin\ChannelListCrudController');
    CRUD::resource('channel-reported-list', 'Admin\ChannelReportedListCrudController');
    CRUD::resource('channel-user-list', 'Admin\ChannelUserListCrudController');
    CRUD::resource('price-list', 'Admin\PriceListCrudController');
    CRUD::resource('question-list', 'Admin\QuestionListCrudController');
    CRUD::resource('request-list', 'Admin\RequestListCrudController');
    CRUD::resource('user-payment', 'Admin\UserPaymentCrudController');
});

<img width="765" alt="screen shot 1395-07-22 at 21 38 03" src="https://cloud.githubusercontent.com/assets/6532492/19360914/6168eea4-918d-11e6-872b-47c9a1d0bd1c.png">

**Comment by tabacitu** [comment]
Does a composer update fix it?

**Comment by A-Ronagh** [comment]
I check this tnx for answer :)

**Comment by nhuebnereagle** [comment]
I ran into this due to nesting my CRUD models, so I had to add the following functions (edit and destroy) because the $id was returning as null.

Nested being:

Course  ->  Course Chapters  -> Course Chapter Pages

This is from my Course Chapter Pages controller, where the general CRUD was not picking up the "last" ID in the chain of nested CRUDs.

```
    public function edit($id)
    {
        return parent::edit($this->page);
    }

    public function destroy($id)
    {
        return parent::destroy($this->page);
    }
```

**Comment by MilitaruC** [comment]
Yea... deleting is a problem. I had to add a route before the MyCrudController route resouce: `Route::('/myroute/{id}/delete', 'MyCrudController@destroy');`
And I edited the delete button link and added `/delete` at the end.
