### ISSUE TITLE
How to test Admin crud routes by PhpUnit Test?

### ISSUE THREAD

**Issue by siberfx** [Laravel-Backpack/CRUD#1780]
# TestCase with PhpUnit

-I want to test create/edit/delete/preview assertions for example;
//    /** @test */
//    public function may_admin_can_create_article_page(): void
//    {
//        $this
//            ->get(route('admin.article.create'))
//            ->assertStatus(302)
//            ->assertRedirect(route('admin.article'));
//    }
// 
// any advice/help will be appreciated.

**Comment by tabacitu** [comment]
Hi @siberfx ,

Testing that the routes return a certain HTTP code shouldn't be any different from any other route test in Laravel. Sorry I couldn't be of more help.

Cheers!
