### ISSUE TITLE
Ability to remove "My account" link

### ISSUE THREAD

**Issue by howest-ward** [Laravel-Backpack/CRUD#1784]
I use Azure active directory to login into backpack.

Next to the profile image there is a link "My account" that is fixed.
I would like to have the option to remove this, because the user should edit the profile in office365, not backpack.

**Comment by AbbyJanke** [comment]
This is more of a Backpack/Base question but if you overwrite the “views/inc/sidebar_user_panel.blade.php” under the Base views the link is in there and you can just remove it or redirect it to office 365.
