### ISSUE TITLE
Backpack issue with swoole

### ISSUE THREAD

**Issue by dauvray** [Laravel-Backpack/CRUD#1786]
Hello,

I'm trying to use backpack with the laravel-swoole package.

php : 7.2
Laravel: 5.7
Swoole : 2.6.2
backpack crud : 3.5

I've got this error when a return on a page already loaded : 500 : "Sorry, you can't have two filters with the same name."

i try this solution : Laravel-Backpack/CRUD#1456 ( #1456 )

But no result
Does Swoole can work with backpack ?

Thank you.

UPDATE:

Backpack work great with swoole. it was a mistake of mine.
Issue #1456 give me the way but works only on controllers who extends CrudController.

My controller extends PageCrudController then extends CrudController.
To correct this i use : 

    if (is_a($controller, '\Backpack\CRUD\app\Http\Controllers\CrudController'))  

instead of 

     if ($controller instanceof CrudController)

**Comment by Athuli7** [comment]
@dauvray, this looks ambiguous. And it's still open.
Comment that it was a mistake. If you think someone else could make this mistake, document it.
And then close it.
Please don't edit the title like this. People will have to visit the issue, then look at the edit.

**Comment by dauvray** [comment]
@Athuli7 Sorry, you're right.
