### ISSUE TITLE
Checkboxes for bulk actions are not shown

### ISSUE THREAD

**Issue by timbertens** [Laravel-Backpack/CRUD#1788]
# Bug report

### What I did:
added $this->crud->enableBulkActions(); to crud controller

### What I expected to happen:
checkboxes appearing the first column to be able to make selection

### What happened:
no checkboxes appeared

### What I've already tried to fix it:
tried to add other similar functions, like $this->crud->enableExportButtons(); 
no problems occured

### Backpack, Laravel, PHP, DB version:
backpack crud: 3.5.13
backpack base: 1.0.4 
laravel: v5.6.39
php: PHP 7.1.10 (also tried on 7.2)
db: mysql  Ver 14.14 Distrib 5.7.23

**Comment by tabacitu** [comment]
Hi @timbertens ,

That's weird, it works fine for me, with the same versions of the software:

![screenshot 2019-01-24 at 15 56 46](https://user-images.githubusercontent.com/1032474/51682680-a9a0a380-1ff0-11e9-8dea-0d4e5d3b3084.jpg)


Where did you call ```$this->crud->enableBulkActions();``` ? In ```setup()``` I assume? Any particularities for this CrudController? Can you copy-paste it?

Is this a project that has been upgraded to CRUD 3.5? Possible you've missed a step in the upgrade guide, maybe?

Cheers!

**Comment by timbertens** [comment]
Ok, found the issue (a case of PEBKAC, I'm afraid)
For others as reference (maybe it can be added to the documentation)

When using 
`$this->crud->setColumns()`
it overwrites the output of the function (adding the checkbox bulk_actions column)
`$this->crud->enableBulkActions()`

You still need it though to set the bulk_actions variable to true

To actually output the bulk_actions columns this is what I have done
```
$this->crud->setColumns(
            ['bulk_actions', 'company_name', 'name', 'quantity', 'price_ex_vat', 'ready_to_invoice', 'is_invoiced'
        ]);

        $this->crud->setColumnDetails(
            'bulk_actions', 
            [
                'type' => 'checkbox',
                'label' => ' <input type="checkbox" class="crud_bulk_actions_main_checkbox" style="width: 16px; height: 16px;" />',
                'priority' => 1,
                'searchLogic' => false,
                'orderable' => false,
                'visibleInModal' => false, 
            ]
        );

// other settings for column details
```

When you don't use 
`$this->crud->setColumns()`
then it works as expected indeed

**Comment by thomascharbit** [comment]
...or use `$this->crud->addColumns` instead of `$this->crud->setColumns`
