### ISSUE TITLE
How To Set Custom Primary Key for CRUD

### ISSUE THREAD

**Issue by A-Ronagh** [Laravel-Backpack/CRUD#179]
class UserPayment extends Model
{
    use CrudTrait;
    /*
   |--------------------------------------------------------------------------
   | GLOBAL VARIABLES
   |--------------------------------------------------------------------------
   */
    protected $table = 'user_payment';
    protected $primaryKey = 'token';
    public $timestamps = true;
    protected $guarded = ['token'];
.....
}

I Create Model Like This But When need Edit Curd

The Link is generated like this: 
http://localhost:8000/adminpanel/user-payment//edit

primary key is token not id 

how can i fix this problem?

**Comment by tabacitu** [comment]
Hmm. This has been fixed a long time ago. What version of Laravel and Backpack\CRUD are you using?

**Comment by tabacitu** [comment]
A composer update might fix it.

**Comment by A-Ronagh** [comment]
I use laravel 5.3 and Backpack v 3.1.17

**Comment by A-Ronagh** [comment]
I Update Laravel and Backpack\CRUD to last version but not fix the issue 
The token is string primary key and this work only with integer value

**Comment by tabacitu** [comment]
Oh. You should't use a string as primary key. It's bad practice. The search is much much slower so it defeats the purpose.

**Comment by A-Ronagh** [comment]
tnx i will change database primary key to id

**Comment by tabacitu** [comment]
**Later update:** it IS possible to use strings as primary keys. Define ```public $incrementing = false;``` on your model, and the result to ```$entry->getKey()``` will be the correct one.
