### ISSUE TITLE
How to show JSON fields from the database?

### ISSUE THREAD

**Issue by mersockatwork** [Laravel-Backpack/CRUD#1793]
# Bug report
I want to show data from a database that has a JSON type.

### What I did:
With Controller.
`       $this->crud->addColumn([
        'name' => 'shop_name',
        'label' => 'Shop name',
        'type' => "name",
        'store_as_json' => true
        ]);`
and
`        $this->crud->addColumn([
            'name' => 'shop_name',
            'label' => 'Location',
            'type' => "location",
            'store_as_json' => true
        ]);`

With  Model.
`    protected $casts = [
        'shop_name' => 'array',
    ];`

### What I expected to happen:
In the example.This is data as a JSON array in database.
`{"name":"Coffee Name","location":"USA"}`

### What happened:
I try to used it by $this->crud->addColumn() but not working.

### Backpack, Laravel, PHP, DB version:
Backpack V : "backpack/crud": "^3.5"
Mysql : 5.7
Laravel : 5.6
PHP : 7.2

**Comment by tabacitu** [comment]
Hi @mersockatwork ,

Looks like you're using custom column types - there is no "name" or "location" column type in the default Backpack. But if your ```shop_name``` database column has a JSON like ```{"name":"Coffee Name","location":"USA"}``` as a value, and it's cast as array, you should be able to get the results with ```$entry->shop_name->name``` and ```$entry->shop_name->location```.

This isn't a Backpack thing, though, it's pure Laravel - that's how casts work in Laravel.

Hope it helps.
Cheers!
