### ISSUE TITLE
[3.6][Bug] MS SQL columns cannot be ordered

### ISSUE THREAD

**Issue by howest-ward** [Laravel-Backpack/CRUD#1797]
The columns are default non sortable.

I added 'orderable' => true to the column. Then the order icon is visible, but clicking on the column name does not sort the result.

![orderable-problem](https://user-images.githubusercontent.com/37362431/51598499-f22b6480-1efd-11e9-8580-2c175d3cfa8a.gif)

I'm using backpack/crud 3.5.13 and laravel v5.7.19.

**Comment by tabacitu** [comment]
Hmm... seems to be working for me: https://cl.ly/2b8443ff28b2

**What type of column have you added and cannot sort?** The simple ```text``` column type should definitely work, but there are types that cannot be ordered (some relationships, model_function, etc).

**Comment by howest-ward** [comment]
The ordering is not working on any fieldtype.

All my columns are by default not sortable, I have to set it explicitly. But even then I can click on it, but it does not order. Can I change this default behaviour? All column should be sortable by default.

I'm using MS sql server as database. Could that be the issue?

**Comment by tabacitu** [comment]
@howest-ward , I haven't tested this with MS SQL Server, and I have no way of doing so. That _may_ be the problem, if Eloquent's drivers don't support ```$this->getSchema()->getColumnListing($table);```.

Ok let's drill down and see the possible problems. When you add a column with ```addColumn()```, this bit makes sure it has ```orderable``` no matter what:
```php
        // make sure the column has a orderable boolean
        if (! array_key_exists('orderable', $column_with_details)) {
            $column_with_details['orderable'] = $columnExistsInDb ? true : false;
        }
```
So it _can_ be ```false``` by default, if the column does not exist in the database table. So either you're using strictly fake columns (JSON, or from another database table), which I doubt, OR ```$columnExistsInDb``` does not compute correctly for you. To debug this, please go to your ```Columns.php``` file, and dump the results like so:

```diff
    /**
     * @param string $table
     * @param string $name
     *
     * @return bool
     */
    protected function hasColumn($table, $name)
    {
        static $cache = [];

        if (isset($cache[$table])) {
            $columns = $cache[$table];
        } else {
            $columns = $cache[$table] = $this->getSchema()->getColumnListing($table);
        }
+       dd($this->getSchema()->getColumnListing($table));

        return in_array($name, $columns);
    }
```

If it's empty - it's most likely a MSSQL issue...

**Comment by howest-ward** [comment]
Unfortunately this returns an empty array.
Thanks for the help. I will check if there is any laravel fix for this.

**Comment by howest-ward** [comment]
The problem is that the variable $table contains the schemaname ('comm.DataSource')

`dd($this->getSchema()->getColumnListing('comm.DataSource'));`

Returns an empty array.

`dd($this->getSchema()->getColumnListing('DataSource'));`

Returns the correct array.

**Comment by tabacitu** [comment]
Wow - thanks a lot for getting to the bottom of this @howest-ward & @brianjohnhanna . As you know MSSQL is not _officially_ supported by Backpack (only MySQL), but 98% of the features do work, and I know a lot of people use it with MSSQL nevertheless. 

I'm glad to merge PR #2183, and bring this to 99% 😄 
Thanks again for the PR @brianjohnhanna !

Cheers!
