### ISSUE TITLE
export button : top of grid ?

### ISSUE THREAD

**Issue by breizhwave** [Laravel-Backpack/CRUD#1798]
Hi, just a question I'd love to see the export button on top of list like it was before, column selection tool is actually very useful too and when at bottom requires scroll of page, not handy

anyone has tried that ?thanks

**Comment by tabacitu** [comment]
Hi @breizhwave ,

You should be able to do that by using a custom ```datatables_logic.blade.php``` file (just place one in the ```resources/views/backpack/crud/inc/``` folder. Here are the exact lines that need changing: https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/inc/datatables_logic.blade.php#L129-L131

AFAIK you should move the "p" to the first highlighted line - very weird DataTables syntax here.

Hope it helps.
Cheers!

**Comment by breizhwave** [comment]
Great news thanks here's the deal 👍 
`  dom:
            "<'row hidden'<'col-sm-6 hidden-xs'i><'col-sm-6 hidden-print'f>>" +
            "<'row m-t-10'<'col-sm-6 col-md-4'l><'col-sm-2 col-md-4 text-center'B><'col-sm-6 col-md-4 hidden-print'p>>"+ //BREIZHWAVE20190124
            "<'row'<'col-sm-12'tr>>" +
            "<'row m-t-10'<'col-sm-6 col-md-4'l><'col-sm-2 col-md-4 text-center'B><'col-sm-6 col-md-4 hidden-print'p>>",`

**Comment by rochiey** [comment]
Hello can i open this @tabacitu , it works and the export is now on top, the problem about @breizhwave code snippet above is that the "records per page" drop down and "pagination numbers" coincide with the export button. How to put the export button 'only' to the top?

**Comment by tabacitu** [comment]
@rochiey to only move the export buttons on top (without records per page and pagination) you can do:

```php
          dom:
            "<'row hidden'<'col-sm-6 hidden-xs'i><'col-sm-6 hidden-print'Bf>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row mt-2 '<'col-sm-6 col-md-4'l><'col-sm-2 col-md-4 text-center'><'col-sm-6 col-md-4 hidden-print'p>>",
```

And then below, add this line to move the export buttons right after the search bar:

```diff
  @include('crud::inc.export_buttons')

  <script type="text/javascript">
    jQuery(document).ready(function($) {

      crud.table = $("#crudTable").DataTable(crud.dataTableConfiguration);

      // move search bar
      $("#crudTable_filter").appendTo($('#datatable_search_stack' ));
      $("#crudTable_filter input").removeClass('form-control-sm');
+      $("#crudTable_wrapper .dt-buttons.btn-group").appendTo('#datatable_search_stack');

      // move "showing x out of y" info to header
      $("#datatable_info_stack").html($('#crudTable_info'));

      // move the bottom buttons before pagination
      $("#bottom_buttons").insertBefore($('#crudTable_wrapper .row:last-child' ));

```

It should end up looking something like this:
![Screenshot 2019-11-08 at 11 39 35](https://user-images.githubusercontent.com/1032474/68466134-71cfb900-021c-11ea-932d-c30f32cfefa6.png)

**Comment by jrbecart** [comment]
Hi, I am trying do to the same, I couldn't make it work on BP 4.

```javascript 
dom:
    "<'row hidden'<'col-sm-6 hidden-xs'i><'col-sm-6 hidden-print'Bf>>" +
    "<'row'<'col-sm-12'tr>>" +
    "<'row mt-2 '<'col-sm-6 col-md-4'l><'col-sm-2 col-md-4 text-center'><'col-sm-6 col-md-4 hidden-print'p>>",
```
Is this part need to be changed ?

**Comment by mamarmite** [comment]
I encounter that need on one project. 
And in BP 4.1 If you put the buttons (Export + columns), the dropdown direction is up, and you get weird behaviour.

You have to edit `inc.export_buttons.blade.php`, and put `dropdown: true` instead of `dropup: true`. to get the dropdown behaviour ok.

And that change, make the bottom buttons not working either. It's only one of the positions for quick change.
I've decided to remove the bottom buttons, because I didn't find a quick way to create 2 sets of buttons in the datatable plugin.
`B` = the buttons plugin within the markup.

```javascript
//from @breizhwave and @tabacitu 
dom:
"<'row hidden'<'col-sm-6 hidden-xs'i><'col-sm-6 hidden-print'f>>" +   
"<'row m-t-10'<'col-sm-6 col-md-4'l><'col-sm-2 col-md-4 text-center'B><'col-sm-6 col-md-4 hidden-print'p>>"+ 
"<'row'<'col-sm-12'tr>>" +
"<'row m-t-10'<'col-sm-6 col-md-4'l><'col-sm-2 col-md-4 text-center'><'col-sm-6 col-md-4 hidden-print'p>>",
```
