### ISSUE TITLE
Error in method removeButton: Undefined variable: name

### ISSUE THREAD

**Issue by franciscocorrales** [Laravel-Backpack/CRUD#180]
This function, in _src/PanelTraits/Buttons.php_:

    public function removeButton($name)
    {
        $this->buttons->reject(function ($button){
            return $button->name == $name;
        });
    }

Gives me the error:
```
ErrorException in Buttons.php line 80:
Undefined variable: name

```

Note: If I try with _removeButtonFromStack_ I get the same error.

If I try to edit the line with:
`$this->buttons->reject(function ($button) use($name) {`
I don't get the error, but the button is not removed!.

This is my code:
```
 $this->crud->removeButton('preview');
 $this->crud->removeButton('update');
 $this->crud->removeButton('delete');
```

Background: what I am trying to achieve, is to stop showing the _Actions_ column empty in the list view, when there's no action (button, I denied most access) there. Also, this column always gets printed, even if there are no buttons (I run this to hard reset the buttons `$this->crud->buttons = collect();`).

**Comment by tabacitu** [comment]
Hi @franciscocorrales ,

This is very weird. I tried it myself and ```$this->crud->removeButton('delete');``` (preview, update, revisions, etc) works perfectly for me. And it shouldn't throw any errors there, ```$name``` is definitely defined, it's one of the parameters. **Are you sure you haven't called ```$this->crud->removeButton()``` (without parameters) anywhere before that?**

One bug, though, was that if I removed all buttons from the line stack, it was still showing. I fixed that in ```3.1.31```. If you've overwritten the ```list.blade.php``` file you need to also make [the changes I made to it here](https://github.com/Laravel-Backpack/CRUD/commit/962c492b03dc3799a932b2b911aff26c5fd48a0e).

Also, I've added two new methods:
- ```$this->crud->removeAllButtons();```
- ```$this->crud->removeAllButtonsFromStack('line');```

**Please run a ```composer update```** and tell me if this fixes it.

Cheers!

**Comment by tabacitu** [comment]
Oh, I just re-read your answer. Yes, it's possible that was a first draft of the function, but it's long been fixed - $name is there and I just checked on a second machine, different project: it works :-)

It's something that a ```composer update``` will definitely fix. If you could confirm, that would be great.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by franciscocorrales** [comment]
Confirmed. 

Thanks.
