### ISSUE TITLE
Using multidimensional arrays in fake fields

### ISSUE THREAD

**Issue by Brotzka** [Laravel-Backpack/CRUD#1805]
# Bug report

### What I did:
I've created a json-column for my fake fields. During create, I've created a nested attribute:

`
    [
                'name'  => 'fake_attribute1[dings]',
                'label' => 'Fake Attribut 1.1',
                'type' => 'text',
                'fake'  => true,
                'store_in' => 'fake_test'
            ]
`
Those values are stored as expected in the database.

### What I expected to happen:
I've expected to see the values in the update form.

### What happened:
Error:

> htmlspecialchars() expects parameter 1 to be string, array given

### Backpack, Laravel, PHP, DB version:
Backpack: 3.4
Laravel: 5.7
PHP: 7.2
DB: MySQL 5.7

**Comment by tabacitu** [comment]
Hi @Brotzka ,

Sorry for the late reply, but maybe it helps someone else with the same problem that stumbles into this thread. ```fake_attribute1[dings]``` is not the way we intended for fake fields to be defined. They should be defined as regular fields (so no square brackets - neither ```[``` nor ```]```).

Fake fields are stored in a JSON you specify, but they're then pulled out just like they were _real_ attributes. So you don't need to do ```$article->extras->fake_attribute```, you can just do ```$article->fake_attribute```. Same with defining the field, you should just specify the fake attribute in the field name, you don't need the column name there.

Hope it helps someone.
Cheers!
