### ISSUE TITLE
Compatibility with Parental 0.6

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#1807]
Parental 0.6 got released, would be great if backpack allows upgrade to 0.6 of parental as composer update throws an error message

https://github.com/tightenco/parental

**Comment by ziming** [comment]
I opened a pull request on Base for it

**Comment by tabacitu** [comment]
Closing - let's move the conversation to the PR https://github.com/Laravel-Backpack/Base/pull/359
