### ISSUE TITLE
Laravel Backpack with translation store special character in unicode/ainsi format

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#1808]
# Bug report
I use laravel backpack in multilingual. All special characters that I store in database are replaced by unicode/ainsi. This is a problem because when I want to search the database with the word `héllo`, it can not find my match. On the other hand, it appears well when I make an "echo".

I do not have problems with columns that are not translated.

### What I did:
I wrote `Héllo` in my "title" field.

### What I expected to happen:
In the database, it should be written like this:
`{"fr":"Héllo"}`

### What happened:
But he writes it like that :

`{"fr":"H\u00e9llo sa"}`

### What I've already tried to fix it:
I checked my encoding. I am in utf8mb4, in my database and in my database.php

```
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
```

### Backpack, Laravel, PHP, DB version:
I use homestead
`"backpack/crud": "^3.3",`
innoDB, utf8mb4_unicode_ci

Thanks!

**Comment by DiyanDesigns** [comment]
Hello, I had a similar issue with Greek characters on MariaDB and I fixed it by modifying the **asJson** function in my translatable model as follows:
```
protected function asJson($value){
    return json_encode($value, JSON_UNESCAPED_UNICODE);
}
```

**Comment by tabacitu** [comment]
Totally. Thank you for the detailed explanation @Jimmylet , and for the solution @DiyanDesigns . I've put together PR #1871 which fixes it, and just merged it. It's a non-breaking change so you'll be able to get it with a ```composer update``` later today, after I bundle it with a few more non-breaking changes.

Thanks again.
Cheers!
