### ISSUE TITLE
search on ListEntries fails with boolean/tinyInt field displayed as "check"

### ISSUE THREAD

**Issue by flartet** [Laravel-Backpack/CRUD#1809]
# Bug report

### What I did:
added in a XXCrudController.php/setup() on a tinyInt(1) mysql field
`        $this->crud->addColumn([
            'name' => 'active',
            'type' => 'check',
            'label' => 'Actif ?',
        //    'visibleInTable' => false,
        //    'searchLogic' => false
        ]);
`

### What I expected to happen:
search working

### What happened:
error message with a huge not helpful stack trace in JSON as http response

### What I've already tried to fix it:
I changed the type to "text", same error. Changed to "number" and it works. I guess this is highly related.
I thought that adding _searchLogic => false_ would avoid it but it seems all fields are searched even with this. Also the error with _disabled => disabled_ and also with _visibleInTable => false_, these parameters don't seem to affect the search behaviour.
I then remembered that I forgot to use `
    protected $casts = [
        "active" => "boolean"
    ]
`
in my Model but it is not better.
### Backpack, Laravel, PHP, DB version:
BP 3.5, Laravel 5.7, MySQL 5.5.52

So, any idea ? Real bug ?
(( Thanks a lot by the way, I'm discovering Backpack and enjoying it. ))

**Comment by tabacitu** [comment]
Hi @flartet ,

I think the problem might be somewhere else. I couldn't get the same issue as you, no matter how much I tried doing the exact same thing:
- tinyint(1) column

![Screenshot 2019-03-13 at 11 03 37](https://user-images.githubusercontent.com/1032474/54266221-9e450f80-457f-11e9-830a-384acfa4f64d.jpg)

- simple check column, with searchLogic or without

![Screenshot 2019-03-13 at 11 04 29](https://user-images.githubusercontent.com/1032474/54266284-bf0d6500-457f-11e9-9486-df5278ed90f8.jpg)


They don't mess up the search at all, it works fine for me:
https://cl.ly/1f65225e2406

Sorry I couldn't be of more help, but it doesn't look like the ```check``` column itself is the problem. Let me know if you figure this out. Might help others.

Cheers!

**Comment by flartet** [comment]
Thanks a lot for the research. At the moment, I figured it out by removing the column :)
