### ISSUE TITLE
upload_multiple posible issue

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#181]
Hey,

I tried to add

$this->crud->addField([
            'name' => 'photos',
            'label' => 'Photos',
            'type' => 'upload_multiple',
            'upload' => true,
        ]);

to a page template, also adding 

public function setPhotosAttribute($value)
    {
        $attribute_name = "photos";
        $disk = "photos";
        $destination_path = "/uploads/galleries";

        $this->uploadMultipleFilesToDisk($value, $attribute_name, $disk, $destination_path);
    }

    public static function boot()
    {
        static::deleting(function($obj) {
            if (count((array)$obj->photos)) {
                foreach ($obj->photos as $file_path) {
                    \Storage::disk('public')->delete($file_path);
                }
            }
        });
    }

to the page model.

My 'public' disk is configured like:

'photos' => [
            'driver' => 'local',
            'root' => public_path(''),
        ],

if i click on the X to "remove" the photo and then Save the page, when i get back it looks like i didnt remove the photo from db.

**Comment by tabacitu** [comment]
Hmm... You're right. I don't know why I didn't see this before. Unless you upload something, the ```setPhotosAttribute()``` mutator does not get called _at all_, so nothing gets removed.

This is a big deal. It's now fixes with a hack - I added a hidden input with the same name before it, so it always has a value and the mutator is always triggered.

If anyone has a better idea, I would love to hear it.

Cheers!
