### ISSUE TITLE
updating italian translation

### ISSUE THREAD

**Issue by roberto-butti** [Laravel-Backpack/CRUD#1810]
# Bug report

### What I did:
in the CRUD list the button Export is not translated in Italian language

### What I expected to happen:
The button for export in italian language needs to be translated

### What happened:
The button shows:  backpack::crud.export.export

**Comment by tabacitu** [comment]
Just merged your PR https://github.com/Laravel-Backpack/CRUD/pull/1811 - thank you! Will be available with a ```composer update``` later today.
