### ISSUE TITLE
Select2 Field Does Not Work on Mobile Devices

### ISSUE THREAD

**Issue by maaxxicarvalho** [Laravel-Backpack/CRUD#1813]
# Bug report
When trying to edit/add a record that has a Select2 field from a mobile device the select2 wont open.

I tried from a real mobile device (iOS using Chrome and Safari) and also using Chrome Dev Tool emulator. The Select2 field wont open and no error is shown on the Chrome Dev Tools console.

I searched over the Github issues and also StackOverflow but I couldn't find any related issue yet.

**Comment by tabacitu** [comment]
Hmm... sorry to hear that @maaxxicarvalho . Just tried it again and it works for me - both real iOS and in Chrome Dev Tools. Maybe you tried it before the JS had loaded?... I don't know...

**Comment by maaxxicarvalho** [comment]
Hello @tabacitu 
I sorry about the confusion here. I closed the issue because I found the problem.
The Bootstrap 3 does not have a fallback styling system, so I have to set the sizes of the columns for all screens, that's why it wasn't working.

Any plans to move to Bootstrap 4?

Thanks.

**Comment by tabacitu** [comment]
Got it. Yes, Bootstrap 4 will be included in Backpack v4 - due in a few months.
