### ISSUE TITLE
Column type: relationship attribute

### ISSUE THREAD

**Issue by mauxtin** [Laravel-Backpack/CRUD#1814]
# Bug report
I am looking for a way to display a relationship attribute in a column.

I have a product crud which _belongs to_ a category and want to basically show that a products belongs to this category name.
### What I did:
```
            [
                'name'          => 'category',
                'label'         => 'Category', // Table column heading
                'type'          => 'model_function_attribute',
                'function_name' => 'category', // the method in your Model
                'attribute'     => 'name'
            ],
```
### What I expected to happen:
Call the relationship and get the attribute.

### What happened:
Error since the model_function_attribute calls **[a function](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/columns/model_function_attribute.blade.php#L3)** so my method returns a belongTo Instance.

### What I've already tried to fix it:
The reason I am submitting it here is to ask if there is a way to do that right now or if this would be open for a PR.

I try to keep my models clean and do not want to add method for such a basic thing.

### Backpack, Laravel, PHP, DB version:
*

**Comment by mauxtin** [comment]
Also there is a small typo in the text above :)

> If you issue is not a bug/feature, 
> If you**R** issue is not a bug/feature,

**Comment by tabacitu** [comment]
Hi @mauxtin ,

Yes, you can use [the ```select``` column type](https://backpackforlaravel.com/docs/3.6/crud-columns#select), which does exactly what you want. I know it's a little unintuitive, it assumes you've already used the ```select``` or ```select2``` field for the same attribute, so the name is for it to be similar with that.

For 4.0 we're working on a column called ```relationship``` which would work for ALL relationship types. But until then we're stuck with "select" and "select_multiple".

Cheers!
