### ISSUE TITLE
Fields from json as model fields

### ISSUE THREAD

**Issue by dormadekhin** [Laravel-Backpack/CRUD#1815]
how can i define fields from json fields as properties?
when I try to enclose a record, those fields that are stored in json are not displayed in the form as filled

Is there any other way than to create a method for each field?
```
function getNameAttribute () {
    retutn $this->arrayFromJson[$key];
}
```
json field added inf $casts as array

**Comment by tabacitu** [comment]
Hi @dormadekhin ,

I'm afraid that's the only way I know - a method for every field. But you should be able to also use ```$entry->json->name``` if you cast your json field as object - that should be easier to work with.

Hope it helps.
Cheers!
