### ISSUE TITLE
Pagination Problem 

### ISSUE THREAD

**Issue by A-Ronagh** [Laravel-Backpack/CRUD#182]
I Have 30,000 record in my table and create crud for this table but when laod this data i get error after minute
<img width="1036" alt="screen shot 1395-07-23 at 20 12 50" src="https://cloud.githubusercontent.com/assets/6532492/19395497/bbfa0714-924a-11e6-8637-4f247e8a6798.png">

i check setModel Method in CrudPannel and select (*)
```
 public function setModel($model_namespace)
    {
        if (! class_exists($model_namespace)) {
            throw new \Exception('This model does not exist.', 404);
        }

        $this->model = new $model_namespace();
        $this->query = $this->model->select('*');
    }

```
i think its load all data then shown in table rather than select 10 last item and then select page 2 
how can i fix this problem ?

**Comment by franciscocorrales** [comment]
Have you enabled AJAX ?

You have to add `$this->crud->enableAjaxTable();` in your index() method

**Comment by A-Ronagh** [comment]
Thanks 
When I Use $this->crud->enableAjaxTable(); in table without relation its work 
but when use this in table with relationship and extend search method like this 

`
public function search()
    {
        $this->crud->hasAccessOrFail('list');

        // add the primary key, even though you don't show it,
        // otherwise the buttons won't work
        $columns = collect($this->crud->columns)->pluck('name')->merge($this->crud->model->getKeyName())->toArray();

        // HERE'S WHAT I'VE JUST ADDED
        $this->crud->addClause('with', 'app_user');
//        $this->crud->orderBy('username');
//        $columns = $columns->merge(['username', 'products.name']);
        // END OF WHAT I'VE JUST ADDED

        // structure the response in a DataTable-friendly way
        $dataTable = new DataTable($this->crud->query, $columns);

        // make the datatable use the column types instead of just echoing the text
        $dataTable->setFormatRowFunction(function ($entry) {
            // get the actual HTML for each row's cell
            $row_items = $this->crud->getRowViews($entry, $this->crud);

            // add the buttons as the last column
            if ($this->crud->buttons->where('stack', 'line')->count()) {
                $row_items[] = \View::make('crud::inc.button_stack', ['stack' => 'line'])
                    ->with('crud', $this->crud)
                    ->with('entry', $entry)
                    ->render();
            }

            // add the details_row buttons as the first column
            if ($this->crud->details_row) {
                array_unshift($row_items, \View::make('crud::columns.details_row_button')
                    ->with('crud', $this->crud)
                    ->with('entry', $entry)
                    ->render());
            }

            return $row_items;
        });

        return $dataTable->make();
    }
`
but when see page in browser
<img width="506" alt="screen shot 1395-07-24 at 01 07 44" src="https://cloud.githubusercontent.com/assets/6532492/19409374/97b43808-92df-11e6-880e-1c90f1100523.png">


<img width="1629" alt="screen shot 1395-07-24 at 13 48 42" src="https://cloud.githubusercontent.com/assets/6532492/19409375/a75ce30e-92df-11e6-9daa-1bc639399da7.png">

search method return 500 
how can i fix this
