### ISSUE TITLE
Decimal Separator on Number FieldType

### ISSUE THREAD

**Issue by jorgepires** [Laravel-Backpack/CRUD#1823]
Hi, I have the code below to add a number field, but on the screen for the decimals separator it only accepts "dot" , and I would like to change to "comma", but can't find anywhere on the documentation on the decimals separator parameter.

`$this->crud->addField([
			'label' => "Total Value",
			'type' => 'number',
			'name' => 'total', 
			'prefix' => '€', 
			'attributes' => ["step" => "any"],
		]);`

**Comment by pxpm** [comment]
That is not a Backpack problem, it's an HTML spec.

You can read about it here: [LINK](https://www.ctrl.blog/entry/html5-input-number-localization)

**Comment by tabacitu** [comment]
Totally - thank you @pxpm . Backpack uses a simple "number" field - you should be able to do whatever you can with an input type=number.

**Comment by raja245** [comment]
ffffffffffff
