### ISSUE TITLE
[4.1][Idea] SoftDelete operation

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1827]
@mgralikowski mentioned using soft deletes with Backpack, and letting the admin soft delete / hard delete / restore entries - which I think is a pretty cool use case, though rare. Usually you wouldn't let the admin hard delete something, that's the whole point. But you _could_ let him restore. Food for thought. I'll dump by thoughts below, in response to PR #1761 

--

I think we could have a different operation that provides full support for soft deletes. Maybe called SoftDeleteOperation, used interchangeably with Delete. In my opinion, on top of this, an additional button to "Hard delete" would also be good. But then... that would require two more actions, each with its own route and controller method:
- restore
- hard delete

### Interface

Default:
- Delete button (if it has softdelete trait a dropdown shows with the "Hard Delete" option)

If soft delete button enabled:
- Delete button disabled, dropdown shows Restore and Hard Delete options

### Routes
- /id/destroy (soft delete)
- /id/destroy?type=hard (hard delete)
- /id/destroy?type=restore
- /id/destroy?type=soft (soft delete, just like no parameter set)

Thoughts? :-)

**Comment by DelightedD0D** [comment]
I can dig it. We are using Backpack to build an internal application which has a lot of tools for our development teams which have associated CRUD pages. Effectively, we use Backpack as our frontend/dashboard for this application rather than as a traditional "Admin" dashboard. Because of this, I could see Soft delete functionality being really useful to us.

@tabacitu I'd be interested in helping with this if needed, once the community has weighed in

**Comment by pxpm** [comment]
@tabacitu from your comment on #2282 

I am not really fan of neither options. 

There is the option to keep only one button for delete, and add a button if entry is softdeleted to restore! Might change the text from `Delete` to `Force Delete` or something. 

1º When going to list 'usually' you will not mix trashed with active items. Maybe have a filter to show the trashed, but i don't see why would anyone want to show a mix of active/trashed items. 
If they mix, the restore button will appear near the delete, then you know, delete is delete for __GOOD__ and restore will restore the item. 

2º For a developer it might make sense to have the delete -> hard delete -> restore  etc etc. But I think for a regular user (the ones who are going to use the backend) they will never have access to trashed items, or if they do they will do like in Windows or Mac, you go to `trash bin` and there you don't have a hard delete or whatever, you still have a delete, but you know you are on trash ..

I think we just need to add a new permission for crud that is HardDeletes, the user can delete an item, can view hard deleteds (like a filter eg.) but can/can't HardDelete.

I am trying to not over-engineer here. Let me know your thoughts.

Best,
Pedro

**Comment by tabacitu** [comment]
Thank you for your input @pxpm . Let's move the conversation to #2282 then since it's newer, and has the proposed solutions there. I no longer agree with the first proposal in this thread, and #2282 is more up to date.

**I'm afraid I don't quite understand how your proposition is different from (Solution 1) there, seems to me like we're saying the same thing. Please explain/rephrase in #2282 what the differences are from Solution 1.**

---

> 1º When going to list 'usually' you will not mix trashed with active items. Maybe have a filter to show the trashed, but i don't see why would anyone want to show a mix of active/trashed items.
If they mix, the restore button will appear near the delete, then you know, delete is delete for GOOD and restore will restore the item.

Totally agree. By default CRUDs show non-deleted items. Trashed items are only visible with a filter. You click "Trash" and you get to see the items in the trash. Only then do you get to see items that have the "Hard Delete" or "Recover" buttons, when you're in the trash bin.

> 2º For a developer it might make sense to have the delete -> hard delete -> restore etc etc. But I think for a regular user (the ones who are going to use the backend) they will never have access to trashed items, or if they do they will do like in Windows or Mac, you go to trash bin and there you don't have a hard delete or whatever, you still have a delete, but you know you are on trash ..

I think that's a great way to put it. We should do it just as it's done in Windows/Mac/Linux, since that's what the user is used to. And it sounds to me like Solution 1 is the one that best copies the flow. Maybe we just need to rename the buttons to "Delete" (soft delete), "Recover", "Remove from Trash" (Hard Delete). With a filter called "Trash" it would make sense to:
1. Go to Trash.
2. Inside the Trash, either recover items or remove them entirely.

> I think we just need to add a new permission for crud that is HardDeletes, the user can delete an item, can view hard deleteds (like a filter eg.) but can/can't HardDelete.

I agree, in addition to "delete", there should be a separate "hard-delete" permission. And while we're at it, a "recover" permission. So that developers can easily choose for each CRUD who would be able to perform these actions.

**Comment by pierluromani** [comment]
Hi guys, has this been implemented?

**Comment by tabacitu** [comment]
@pierluromani sorry, no, we still don't have a built-in solution for this (or an addon). It's totally doable using [custom operations](https://backpackforlaravel.com/docs/4.1/crud-operations#creating-a-custom-operation) but not something that's provided by default.

Note - since the links above broke, here's the current open issue about this - https://github.com/Laravel-Backpack/ideas/issues/38

**Comment by pierluromani** [comment]
Ok, no problem, after all that's not a major feature at the moment.
By the way keep up the good work! I've been digging Backpack for a few months now and it's just amazing.

**Comment by tabacitu** [comment]
Nah sorry, just closed it because there's another issue open for it here - https://github.com/Laravel-Backpack/ideas/issues/38

For now I say... roll your own! 😀
