### ISSUE TITLE
[3.6][Bug] Using the parameter select_all on a second select2_multiple breaks the buttons events

### ISSUE THREAD

**Issue by edhelas** [Laravel-Backpack/CRUD#1828]
# Bug report

### What I did:

Add a 'select_all' parameter to a second select2_multiple field in the same form. The first one doesn't has the 'select_all' parameter.

### What I expected to happen:

The 2 added buttons to have a click event to trigger their related behavior.

### What happened:

The click events are not set on the buttons.
Related JS there https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/fields/select2_multiple.blade.php#L79

### What I've already tried to fix it:

Reverse the two select2_multiple fields to declare the one that has 'select_all'  first. It fixes the behavior (but will need a proper fix)

### Backpack, Laravel, PHP, DB version:

Laravel 5.5, Backpack 0.3

**Comment by pxpm** [comment]
Hello @edhelas 

I am so sorry for taking so much time to handle this one. 

I am really happy you found a fix, but as you said it was a temporary one.

I have now submited a PR #2243 that fixes this issue for good. 

So i will be closing this now, if you need to add something to this issue please report on PR #2243 thread. 

Once again, thank you very much for bring this up to the table.

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
Ouch! Took so long to fix this, indeed sorry @edhelas ! Must have slipped through the cracks.

Thank you @pxpm . We're finally getting to fix minor issues that I've neglected for so long, I LOVE THIS!

**Comment by edhelas** [comment]
No problem ;) Happy to see that it's now resolved!
