### ISSUE TITLE
Event cancels delete but backpack reports item deleted

### ISSUE THREAD

**Issue by basdog22** [Laravel-Backpack/CRUD#1829]
Ok, I set up a crud controller and works as expected. 

### What I did:
For some reason, we need an observer on the crud model to check if an item can be deleted. So, i created one  and if the item cannot be deleted i return false:
```public function deleting(DedicatedPackage $hostingPackage)
    {
        if(Dedicated::hasActiveFor($hostingPackage->id)){
            \Alert::warning(trans('app.services_active_cant_delete'))->flash();
            return false;
        }
    }
```

which does the job as expected. 
### What I expected to happen:
Backpack to show a notification that the item cannot be deleted... (services_active_cant_delete)
### What happened:
Backpack shows a notification that the item was deleted and when i reload the page i get my warning notification.

### Backpack, Laravel, PHP, DB version:
Laravel 5.7, PHP 7.2

**Comment by basdog22** [comment]
Ok. I think i found it. The delete button view (delete.blade.php) file does not handle the result at all:

$.ajax({
 url: route,
	              type: 'DELETE',
	              success: function(result) {
	                  // Show an alert with the result
                          new PNotify({
                              title: "{{ trans('backpack::crud.delete_confirmation_title') }}",
                              text: "{{ trans('backpack::crud.delete_confirmation_message') }}",
                              type: "success"
                          });
	                  // Hide the modal, if any
	                  $('.modal').modal('hide');
	                  // Remove the details row, if it is open
	                  if (row.hasClass("shown")) {
	                      row.next().remove();
	                  }
	                  // Remove the row from the datatable
	                  row.remove();
	              },
	              error: function(result) {
	                  // Show an alert with the result
	                  new PNotify({
	                      title: "{{ trans('backpack::crud.delete_confirmation_not_title') }}",
	                      text: "{{ trans('backpack::crud.delete_confirmation_not_message') }}",
	                      type: "warning"
	                  });
	              }
	          });


I override the button now and i add my logic for handling the result

**Comment by Athuli7** [comment]
@tabacitu, any take on this? This is one of the easiest ways to handle it without deviating from the Laravel way to things. 

@basdog22, We should probably also have the option to show the reason inside the notification. Otherwise, the mistake will be unknown to the end user.
Eg, my financials CRUD, disables the delete option once the record is confirmed or if there aren't enough funds to reverse the record.

This type of logic can be implemented in the event, but how to show them? Throwing an exception and displaying the error on the notification is an option, but that just throws errors, which is not a great idea.

**Comment by tabacitu** [comment]
Hmm... you're right guys. Thanks for the heads-up. I've just pushed an update to the ```delete.blade.php``` button, so that when the even does NOT happen, a warning bubble shows up instead.

@Athuli7 indeed you can't reply with a custom message... not with the current API...
