### ISSUE TITLE
undefined method fire

### ISSUE THREAD

**Issue by jeanbelhache** [Laravel-Backpack/CRUD#1831]
Hi,

I updated my project for laravel 5.8 and backpack 4.6.
But now, when i add a new entry which is translatable, i got this error :
Call to undefined method Illuminate\Events\Dispatcher::fire()

(vendor/backpack/crud/src/ModelTraits/SpatieTranslatable/SluggableObserver.php line 78).

Any idea ?

Regards

**Comment by tswonke** [comment]
@tabacitu AFAIK the `fire()` method is deprecated since Laravel 5.4 and was removed in 5.8. It was replaced by `dispatch()`.

This is a simple change. But I currently don't know if this is the only thing we have to fix.

**Comment by robertotcestari** [comment]
Same  problem here. This is a bug in the Venturecraft/revisionable package (which doesn't look in very active development). There is  a bug issue opened there.

**Comment by tabacitu** [comment]
Thank you for reporting this guys! Apparently there was this bug in Backpack\CRUD too, I've just merged a PR that fixes it https://github.com/Laravel-Backpack/CRUD/pull/1830#issuecomment-471906981

Cheers!
