### ISSUE TITLE
Can i've export pdf with image.

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/CRUD#1834]
My view have thumbnail column and want to export pdf with thumbnail. But have not show thumbnail when export.

**Comment by tabacitu** [comment]
Hi @gumpon ,

That sounds like a custom feature you can easily create. Check out the docs for [creating a new column type](https://backpackforlaravel.com/docs/3.6/crud-columns#creating-a-custom-column-type) or [creating a new button](https://backpackforlaravel.com/docs/3.6/crud-buttons#creating-a-custom-button).

Cheers!
