### ISSUE TITLE
Image upload is not disabled on update view

### ISSUE THREAD

**Issue by ravor44** [Laravel-Backpack/CRUD#1841]
# Bug report
Image Upload is not disabled on update view

### What I did:
Had this code:
 $this->crud->addField([ // image
                'label' => "Signature",
                'name' => "signature_data",
                'type' => 'image',
                'upload' => false,
                'crop' => false, // set to true to allow cropping, false to disable
                'attributes' => ['disabled' => 'disabled']
        ]);

### What I expected to happen:
Upload should have been disabled

### What happened:
Upload/delete button is still present

### Backpack, Laravel, PHP, DB version:
Backpack v 3.6 / Laravel 5.8 / PHP 7.2 / MySQL 5.7

**Comment by tabacitu** [comment]
Hi @ravor44 ,

You're right, that feature doesn't exist. I checked, it's nowhere in the docs. I agree it would perhaps be intuitive to work the way you explained... but. It doesn't really make sense to include all that JS and CSS for cropping, if you intend to disable it though.

A simple [custom field](https://backpackforlaravel.com/docs/3.6/crud-fields#creating-a-custom-field-type) that just shows the image in question is the best solution for this, I think. 

Cheers!
