### ISSUE TITLE
[BUG] Revisionable Marked as Abandoned

### ISSUE THREAD

**Issue by markacianfrani** [Laravel-Backpack/CRUD#1842]
https://github.com/VentureCraft/revisionable/pull/321

After trying to fix the event fire issue with Laravel 5.8, I found out the package is actually officially abandoned. 

Just wanted to bring it to your attention since it wasn’t very clear and it’s a dependency.

**Comment by breizhwave** [comment]
very true. what about switching to http://laravel-auditing.com

**Comment by tabacitu** [comment]
Ouch. Thanks for the heads-up @markacianfrani & @breizhwave . Yes, we should definitely move to a different package. I intend to split this Operation into its own package in Backpack v4.

Until then let's see if we can add L5.8 support. It would be great if you guys could pitch in here to convince the maintainer to add L5.8 support or let us do it: https://github.com/VentureCraft/revisionable/pull/344

**Comment by borisson** [comment]
Updated the issue there, there needs to be a change in the pull request before that can be merged. The maintainer seems open to the idea of the change that allows backpack to keep using this package.

**Comment by tabacitu** [comment]
The PR has recently been merged. Thanks a lot for this everyone!
