### ISSUE TITLE
Error loading page. Please refresh the page

### ISSUE THREAD

**Issue by mauro-gallo** [Laravel-Backpack/CRUD#1843]
# Bug report

### What I did:
i have cloned a project into laradock container.

### What I expected to happen:
i aspect that it work as in past.

### What happened:
in all my crud index page i have:
![image](https://user-images.githubusercontent.com/36051344/54871982-367f9780-4dbd-11e9-8c75-576485cf79c5.png)

I have no javascript error messages and the search result file seem ok. this is very strange for me. i have no log to study because laravel has no error logs and i can't see javascript errors.

### What I've already tried to fix it:
composer update and composer dump-autoload. npm run production.

### Backpack, Laravel, PHP, DB version:
backpack crud is 3.6, php is 7.2.16, laravel 5.8, and mysql is 5.7

**Comment by tabacitu** [comment]
Hi @mauro-gallo .

Strage indeed. What does your Network tab look like? Anything red there?

**Comment by mauro-gallo** [comment]
i'm using laradock with default settings.

**Comment by imansugirman** [comment]
Same problem with relationship

**Comment by tabacitu** [comment]
@mauro-gallo in Chrome Dev Tools if you leave the Network tab open and then refresh the page, it should show all requests. One of them should be red (because it errored). Please click it and show the error here so I can help. It should give a clear error message for us to debug.

Cheers!

**Comment by sokvebolkol** [comment]
You have to make sure, you have done command ==php artisan migrate==

**Comment by Fab-TOK** [comment]
I had the same problem and it blocked me for days.
All you have to do is change the "APP_URL" variable in the .env file of the Laravel project.

Mine used to be "APP_URL=localhost", but that didn't work.
Then I changed it to "APP_URL=http: //movie.test" and it worked.
knowing that "http: //movie.test" is the local domain name I created for my project.

So all you have to do is change the "APP_URL" variable to the correct address. :-)
