### ISSUE TITLE
Filter Error 500 

### ISSUE THREAD

**Issue by imansugirman** [Laravel-Backpack/CRUD#1846]
[#](url) Bug report

### What I did:
I Use Filter on UserCrudControlller ( Copy from permissionmanager)

### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.6",
"backpack/permissionmanager": "^4.0",

Any wrong from me? 

```
$this->crud->addFilter([ // select2_ajax filter
          'name' => 'roles_id',
          'type' => 'select2_ajax',
          'label'=> 'Role',
          'placeholder' => 'Pick a category'
        ],
          url('api/roles'), // the ajax route
        function($value) { // if the filter is active
            $this->crud->addClause('where', 'roles', $value);
        });

        $this->crud->addFilter([ // daterange filter
           'type' => 'date_range',
           'name' => 'from_to',
           'label'=> 'Date range'
         ],
         false,
         function($value) { // if the filter is active, apply these constraints
           $dates = json_decode($value);
           $this->crud->addClause('where', 'date', '>=', $dates->from);
           $this->crud->addClause('where', 'date', '<=', $dates->to);
         });
```

![Jepretan Layar 2019-03-29 pukul 04 26 10](https://user-images.githubusercontent.com/38036171/55194030-1dbb1b80-51db-11e9-8de2-d4417f8d3946.png)

**Comment by tabacitu** [comment]
Hi @imansugirman ,

If you have the Network tab open, then refresh the page, you should see a list of all requests. Then you'd see AJAX request that failed, it will be in bright red. Click it and it'll show the PHP error. That should help you debug your issue.

Cheers!
