### ISSUE TITLE
Differences from Wordpress

### ISSUE THREAD

**Issue by zsvendo** [Laravel-Backpack/CRUD#1848]
Before buying I would like to know the difference of this CMS for Wordpress?

**Comment by tabacitu** [comment]
Hi @zsvendo ,

Well for starters, Backpack is not a CMS. It's a _framework_ that helps you build your own CMS :-) So the differences are quite large:
- Wordpress is aimed at _non-programmers_ who want to hack something into existence. It gives _a lot_ of customization options through its interface, and has _a lot_ of plugins;
- Backpack is aimed at _programmers_ who want to create something _custom_ that is easy to build, solid, but also easy to maintain;

If you're looking for an admin panel close to what Wordpress can offer, use Wordpress.
If you're a Laravel developer and want your admin panels to be as enjoyable to build and maintain as the rest of your app, use Backpack. 

Hope it helps.
Cheers!
