### ISSUE TITLE
cdn.rawgit.com is reaching the end of its lifespan October 2019

### ISSUE THREAD

**Issue by tomaszbrunarski** [Laravel-Backpack/CRUD#1851]
# Bug report
This isn't a tipical bug report. We are using the backpack CRUD for admin and just learned that cdn.rawgit.com is not goint to be there after October 2019.
### What I did:
Use backpack
### What I expected to happen:
That the file src/resources/views/inc/export_buttons.blade.php:6  and other cdn related libs would work after October 2019
### What happened:
Nothing yet
### What I've already tried to fix it:
Change the cdn to somehting else
### Backpack, Laravel, PHP, DB version:
CDN for sources

**Comment by tabacitu** [comment]
Thanks for the heads-up, @tomaszbrunarski ! Just pushed a fix for this - switched to CDNJS for that one file we loaded from there. It'll be available with a  ```composer update``` later today.

Cheers!

**Comment by tomaszbrunarski** [comment]
@tabacitu I also noticed that one of the dependencies user rawgit 
//cdn.rawgit.com/google/code-prettify - its in elfinder.full.js
public/packages/barryvdh/elfinder/js/elfinder.full.js:9189 , 9191, 9192, 9193
Would be worth mentioning this to them or seeing if Backpack cannot use a newer version that doesnt have that dependency

**Comment by tabacitu** [comment]
Hmm... I guess the best course of action would be to tell them about it first. Like us, they might not even be aware this is a problem. I only found out thanks to you.

**Comment by tomaszbrunarski** [comment]
Ok well will you let them know @tabacitu ? I think it will have more impact if they see a real product is using their solution and will make them prioritize this a bit higher. 
All in all October is going to be a very interesting month :) 
Cheers

**Comment by tomaszbrunarski** [comment]
also you can point them here
https://www.jsdelivr.com/rawgit

**Comment by tabacitu** [comment]
Good news @tomaszbrunarski - elfinder JS seems to have already migrated away from rawgit. In the version I'm using (2.1.48) there's no mention of rawgit.

You should be able to get it by re-installing barryvdh/elfinder, or re-installing Backpack/Crud (it'll ask you if you want to install the elfinder package). The important thing is to re-publish the elfinder assets.

I agree... October will not be a good month to be a package maintainer :-)

Cheers!
