### ISSUE TITLE
[4.1][Feature Request] Enable allows_null for select2 field, so that it can be used with fake attributes too

### ISSUE THREAD

**Issue by enniosousa** [Laravel-Backpack/CRUD#1856]
# Bug report
When use select2 and fake attribute a error show up informing that the attribute doesn't exists.
`There is no column with name 'organ' on table 'employers'.`

### What I did:
```php
$this->crud->addField([
            'tab' => 'Documentos',
            'fake' => true,
            'name' => 'organ',
            'type' => 'select2',
            'label' => "Orgão",
            'entity' => 'organ',
            'attribute'=>'acronym',
            'model' => 'App\Models\Organ',
            'store_in' => 'rg',
            'wrapperAttributes' => ['class' => 'form-group col-md-3']
          ]);
```
### What happened:
in select2.blade.php check if column is nullable on database
```blade
@if ($entity_model::isColumnNullable($field['name']))
            <option value="">-</option>
@endif
```
Obviously this column doesnt exists becouse it's a fake column of `rg` column

### What I've already tried to fix it:
I recomend check if is passed `allows_null` on field array
```blade
@if (
	(  isset($field['allows_null']) && $field['allows_null'] === true  )
	|| (  (!isset($field['allows_null']) || isset($field['allows_null']) && is_null($field['allows_null'])) && $entity_model::isColumnNullable($field['name'])  )
)
	<option value="">-</option>
@endif
```

### Backpack, Laravel, PHP, DB version:
"backpack/crud": "^3.6",
"laravel/framework": "5.8.*",
PHP 7.2.14
MySQL 5.7.24

**Comment by pxpm** [comment]
Hello, hello.

Just doing some issue cleanup. 

Thanks for the report @enniosousa and so sorry we didn't manage to provide you with an answer.

Fortunatelly I bring you good news, this had already been fixed. If column does not exist in database, we just return `true`, so you should be able to use select2 with any fake column.

https://github.com/Laravel-Backpack/CRUD/blob/ac1241b82e1e5a9516300171486ba4e686032cc9/src/app/Models/Traits/HasRelationshipFields.php#L80

Wish you the best,
Pedro
