### ISSUE TITLE
submit data to multiple table from the same form

### ISSUE THREAD

**Issue by ridislam** [Laravel-Backpack/CRUD#1860]
# Bug report
I have an employee module, in this module, I am trying to create a user first then and save some extra fields into the employee table with that user table id from the employee module form
### What I did:
Create From 
<img width="789" alt="Screenshot 2019-04-14 at 7 25 34 PM" src="https://user-images.githubusercontent.com/7835820/56093538-cfe92780-5eeb-11e9-8d10-189915f7e89f.png">
index page 
<img width="1093" alt="Screenshot 2019-04-14 at 7 25 01 PM" src="https://user-images.githubusercontent.com/7835820/56093547-d9728f80-5eeb-11e9-9312-8b2f28516033.png">
Edit Page
<img width="810" alt="Screenshot 2019-04-14 at 7 32 11 PM" src="https://user-images.githubusercontent.com/7835820/56093553-0a52c480-5eec-11e9-8ce5-d35058d2d6de.png">

### What I expected to happen:
In backed in EmployeeCrudController first i have saved a user then i saved the employee, but in edit page users table data are not populating.
### Backpack, Laravel, PHP, DB version:
backpack 3.5, laravel 5.7, php 7.3

**Comment by tabacitu** [comment]
Hi @ridislam ,

If I understand correctly, you have a 1-n relationship between Employee and something like EmployeeDetails. If that's true:
- make sure the relationship is properly defined on both models;
- use a dot notation for the ```name``` of those fields (ex: if you have the religion column in the employee_details table, and the relationship is named ```details``` in the Employee model, then the proper name for that field should be ```details.religion```, NOT just ```religion```);

Hope it helps.
Cheers!

**Comment by chheng22** [comment]
[Laravel Backpack, i want to add widgets to dashboard (ex: col-6 widgets card and col-6 table of row) how to do ? can or not to do?](https://stackoverflow.com/questions/71371813/laravel-backpack-i-want-to-add-widgets-to-dashboard-ex-col-6-widgets-card-and)

**Comment by kaylafaith** [comment]
Hi! I am having the same issue with update. the customer info tab fetch the data from the users table but its relationship with address table doesn't fetch its respective value. I tried to use the dot notation, yes it shows the address that belongs to the user but i can't save the form. Need help pls

i am using 1-1 relationship
![ss](https://user-images.githubusercontent.com/95120529/159703305-41432e8d-6c17-42d8-9ffb-b7ccc5832107.png)
