### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by tengfei31** [Laravel-Backpack/CRUD#1861]
backpack\CRUD v3.6.13

error line : vendor\backpack\crud\src\CrudTrait.php:83 line

    /**
     * Add fake fields as regular attributes, even though they are stored as JSON.
     *
     * @param array $columns - the database columns that contain the JSONs
     */
    public function addFakes($columns = ['extras'])
    {
        foreach ($columns as $key => $column) {
            $column_contents = $this->{$column};

            if (! is_object($this->{$column})) {
                $column_contents = json_decode($this->{$column});
            }

            if (count($column_contents)) {
                foreach ($column_contents as $fake_field_name => $fake_field_value) {
                    $this->setAttribute($fake_field_name, $fake_field_value);
                }
            }
        }
    }
为什么不判断$column_contents == NULL 呢？因为这样导致count()使用不同的PHP version会有error（PHP7.2以上貌似都会有问题）

**Comment by tabacitu** [comment]
Hi @tengfei31 ,

That's weird, I'm getting no such error in my tests.
Are you sure you've cast your ```extras``` attribute to ```array```? In your model?

Cheers!

**Comment by pxpm** [comment]
The problem resided in your PHP version.

I submited a PR to deal with this specific issue. #1882

**Comment by tabacitu** [comment]
Thank you @tengfei31 & @pxpm . Merging the PR now.
