### ISSUE TITLE
overlapping fields when viewport is xs

### ISSUE THREAD

**Issue by marconett** [Laravel-Backpack/CRUD#1862]
# Bug report

CRUD: 3.6.13
Laravel: 5.8.12

The fields `image`, `base64_image` and `checklist_dependency` could overlap other fields above them when viewport size is <= xs, making it impossible to move focus to those fields via mouse.

**viewport size xs:**
![xs](https://user-images.githubusercontent.com/3315507/56371405-5b6cfc00-61fd-11e9-8275-01578aef523c.png)
**viewport size md:**
![md](https://user-images.githubusercontent.com/3315507/56371414-5dcf5600-61fd-11e9-94fa-6b18d6c87693.png)

**Comment by tabacitu** [comment]
Totally! Thanks a lot for reporting this, and for the PR, @marconett ! Merging it now.
