### ISSUE TITLE
Displaying count

### ISSUE THREAD

**Issue by sheriffmarley** [Laravel-Backpack/CRUD#1866]
I'm not sure if it's a bug, a missing features, or if I'm just to dumb to find it in the docs.

I want to display the `comments_count` of  the `Comment` class in the table. 

Normally you would do it this with `->withCount('comments')` but i'm not able to find a way to do this in crud. Also adding `$withCount` to the `user` class wouldn't load it.

I tried 
```php
        $this->crud->addColumn([
            'name' => 'comments_count',
            'label' => '# of comments',
            'type' => 'text'
        ]);
```
and 
```php
        $this->crud->addColumn([
            'name' => 'comments.count',
            'label' => '# of comments',
            'type' => 'text'
        ]);
```
but without success. 

Since `$this->crud->with()` is just a wrapper and i wasn't to find method in the QueryTrait, i wonder how to display the `count`?!?

**Comment by tabacitu** [comment]
Hi @sheriffmarley ,

I think the best way to do this would be to use the [model_function](https://backpackforlaravel.com/docs/3.6/crud-columns#model_function) column type. If you have something like this in your model:

```php
    // the relationship 
    public function comments()
    {
        return $this->hasMany('Comments', 'article_comment');
    }
   
   // add a getter for the comment count
   public function getCommentsCount()
   { 
        return $this->comments()->count();
   }
```

and then you'd do:

```php
$this->crud->addField([
   // run a function on the CRUD model and show its return value
   'name' => "comments",
   'label' => "Comments", // Table column heading
   'type' => "model_function",
   'function_name' => 'getCommentsCount', // the method in your Model
   // 'function_parameters' => [$one, $two], // pass one/more parameters to that method
   // 'limit' => 100, // Limit the number of characters shown
]);
```

Hope it helps.
Cheers!

**Comment by tabacitu** [comment]
Another way would be to [use the closure column type](https://backpackforlaravel.com/docs/3.6/crud-columns#closure):

```php
$this->crud->addColumn([
    'name' => 'comments_count',
    'label' => 'Comments',
    'type' => 'closure',
    'function' => function($entry) {
        return $entry->comments()->count().' comments';
    }
]);
```

On second thought, this one might actually be shorter and better :-)
