### ISSUE TITLE
Issues with the "address" field type

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#187]
@OwenMelbz ,

I've found some issues here, wondering if you could take a look sometime, you know this part best.

1) I can't go to EDIT an entry, empty the address field and the save that empty value to the database. It does not get saved, probably because that doesn't clear the hidden input.

2) I get a javascript error on the CREATE screen, about parsing the JSON. I used attribute casting to array (not that it matters, I think - it's the create screen, there is no value).
![screen shot 2016-10-17 at 18 15 43](https://cloud.githubusercontent.com/assets/1032474/19443554/c4f93b94-9495-11e6-8113-9d9a171e8120.png)
![screen shot 2016-10-17 at 18 15 50](https://cloud.githubusercontent.com/assets/1032474/19443555/c4fd2678-9495-11e6-86d9-8d12383c2d5a.png)

Cheers!

----

Also, figured out a way for us to better test that nothing breaks when we make changes: we create an entity with ALL the field types and we include it in the Demo. So when we want to test a field, we just Add and Edit a new "Foo".

**Comment by OwenMelbz** [comment]
@tabacitu well spotted :) Should now be able to clear old saved entries, and it wont try parse empty values with https://github.com/Laravel-Backpack/CRUD/pull/188
