### ISSUE TITLE
[4.0][Feature] Drag-and-drop page builder field type aka layout field type

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1873]
It should:
- allow admins to resize columns
- allow admins to add blocks of different types (which could contain multiple fields)
- allow admins to reorder move said blocks
- store contents as JSON in a hidden input
- use a clear and simple hierarchy for the JSON, so that it can be easily converted into HTML blocks, either Bootstrap 4 (provided), 3, Bulma,  Tailwind or whatever’s next

I don’t think it’s important to have the fields visible at all times. I’d rather have them shown in a modal upon block click. That should keep the create/update form clean.

WIP.

**Comment by pxpm** [comment]
I have some kind of that setup, but not drag and drop.

I created settings, that could be attached to components, those components could have settings like: title (text), sub_title(text), main_image (img), content (wysiwyg), main_image_side (toggle) (each of this settings is a field). I can add those components to pages, and reorder them. I also created some advanced settings like "folder", dropzone multiple images (easy peasy for carousels).

The thing is that components are a fixed thing (like, parallax_image_and_text), you can choose the image, you can write the text, but it still a forced parallax image and text component.

For the dialogs, i'v a bit of work on that. I extended the angular table field we already have, and added angular-dialog to it. With that, i created buttons on the table that opens a dialog that let me edit every row of the table as a separate item, and store them all on database.

[video](http://recordit.co/XavpCY9zIS)

Hope i made myself clear.

**Comment by tabacitu** [comment]
The new table field looks great. Good job. Similar to what we had in mind with the always-coming-soon-but-never-done [matrix field type](https://github.com/Laravel-Backpack/CRUD/issues/771).

But it's not exactly what I had in mind. Something more like [this video](https://cl.ly/b128ab1a3f8c) that @eugentudorache made of the prototype. The idea is to be able to organize blocks of content into a layout, for presentation pages. Maybe a better name for it would be _layout_builder_, not _page_builder_.

**Comment by tabacitu** [comment]
Let's close the issue, since PR https://github.com/Laravel-Backpack/CRUD/pull/1987 already has working code for this.
