### ISSUE TITLE
Revision doesn't work

### ISSUE THREAD

**Issue by PeterKravets** [Laravel-Backpack/CRUD#1875]
I'm using a demo installation right now.
By default, 'Icon' entity already has 'Revision' on.
When I try to update an entity I get the next error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Illuminate\Events\Dispatcher::fire()
…/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php237

I've also tried to add Revision behavior to another entity, but the same.

**Comment by tabacitu** [comment]
Hi @PeterKravets ,

Thanks for the issue. You're right, there _was_ an error with the Revisions functionality after the update - the revisions package did not support Laravel 5.8. That's been fixed now, I've just run ```composer update``` on the demo and it works now. I've pushed the fix onto the demo.

Please run ```composer update``` on your project. That should fix it. Let me know if it doesn't.

Cheers!

**Comment by PeterKravets** [comment]
There is no issue during update anymore.
But there is an error, when I go to the 'Revisions' page

Class 'Date' not found (View: /home/peter/backpack-demo/vendor/backpack/crud/src/resources/views/inc/revision_timeline.blade.php) (View: /home/peter/backpack-demo/vendor/backpack/crud/src/resources/views/inc/revision_timeline.blade.php)

**Comment by tabacitu** [comment]
Hmmm.... Weird, I'm not getting any such error. What versions are you running? Can you please copy-paste the output of ```php artisan backpack:base:version```?

**Comment by ihsanberahim** [comment]
```
backpack/base                            1.1.5              
backpack/crud                            3.6.24             
backpack/newscrud                        2.1.10             
backpack/permissionmanager               4.0.4             
laravel/framework                        v5.8.30
```

**Comment by jrbecart** [comment]
My 2 cents:
It's because Date was removed for Carbon instead.
Try not adding a Date alias in your config/app.php but check if you have not overridden the revision_timeline template in \resources\views\vendor\backpack\crud\inc\revision_timeline.blade.php
