### ISSUE TITLE
[4.0][Proposal] Load Js/css assets from a PHP array

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1887]
This has been mentioned before as a solution that would not use webpack / mix.

Basically:
- you can add the css&js assets to an array, when you are anywhere inside a blad file
- if the file / key exists, it won’t be added a second time
- when outputting the css and js, there will no longer be duplicates

It looks like a package just came out which does this for Laravel: https://github.com/KosmosX/frontend

PROs:
- This would solve the duplicate assets problem in create/update forms, while needing zero knowledge of webpack or mix.
- It would probably work very well when HTTP2 requests are enabled, since assets will be loaded concurrently. 
- It won’t create massive JS and CSS files that need to be downloaded on first page load. So faster first page load.

CONs:
- Will probably be slower page-to-page than compiling assets using Mix.
- For people who want to use Mix anyway, this will look “old-school” and require them to do all the Mix work themselves (though we could make it easier for them with a pre-defined mix file and an alternative layout blade file).

Thoughts?

**Comment by Jamesking56** [comment]
Would it be a large stretch to support both? As in, the user can turn on / off "Inline Asset Loading"?

That way we could leave Mix instructions in the docs and tell them to turn inline asset loading off if they want to do it that way?

**Comment by tabacitu** [comment]
@Jamesking56 that sounds like the most sensible solution - supporting both. On it!

**Comment by tabacitu** [comment]
PR https://github.com/Laravel-Backpack/CRUD/pull/1890 fixes this using a homegrown solution, so let's close this.
