### ISSUE TITLE
Generating to much files

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/CRUD#1897]
# Bug report

### What I did:
Install Laravel Backpack normally

### What I expected to happen:
Laravel Backpack generate few files to work normally (~2k files is tolerable)

### What happened:
Laravel Backpack publishes the whole adminlte vendor folder to public, generating too much files (contributing to around 7k+ files, just by itself), thus making it impractical to develop huge app and deploy it to Google App Engine (max 10k files per application) or any other ordinary hosting (which is limited to 10k inodes/files+folder). 

By the way, it seems like some of the generated files are not really needed/duplicated (such as adminlte's bower_components ckeditor folder, which has also been published by laravel backpack as its assets).

### What I've already tried to fix it:
Nothing, since i still haven't found an idea to minimize the file counts.

### Backpack, Laravel, PHP, DB version:
Backpack : 3.6,
Laravel : 5.8,
PHP : 7.2

**Comment by tabacitu** [comment]
Hi @drionix ,

I agree with you - I think we can do better. And we're taking action in v4, the upcoming version.

Indeed, in v3 we are publishing the entire AdminLTE folder, but we don't use every single file. We're not going to do the same thing in v4, we'll just publish the aprox 10 files you actually need. I'm sure you'll love it :-)

Until then, I'm afraid we're not going to change this in Backpack v3 - too big of a change when v4 is just around the corner and will fix this. 

You can delete whatever you find unnecessary if you want to fit into the 10k file limit. Sorry I couldn't be of more help.

Cheers!
