### ISSUE TITLE
performSaveAction resets the editing locale

### ISSUE THREAD

**Issue by rampol** [Laravel-Backpack/CRUD#1902]
# Bug report
performSaveAction resets the editing locale
### What I did:
Multilanguage is active. Default locale is 'en'. I'm editing a record in another language. The editing route looks like `/admin/article/1/edit?locale=ja#seo`
### What I expected to happen:
When I "save and edit" i expect to keep editing in 'ja', the last editing locale, but it jumps back to 'en'.
### What happened:
After refreshing the page, now the url looks like:
`http://nero.test/admin/article/1/edit#seo?locale=ja` and this prevents both from anchoring to the tab seo and from editing in 'ja'.
This used to work properly, and checking with a previous version of backpack I see some lines swapped inside the `SaveActions.php` file:
Before, the ` if (\Request::has('locale'))` was the first line. In this version 3.6 this line is after `if (\Request::has('current_tab'))`. That's why the URL gets changed.

Let me know please if someone else found this behaviour, or the URL as is built now (url#anchor?locale=ja) should work anyway. Thanks!

**Comment by tabacitu** [comment]
Thank you for bringing this up @rampol . I've just merged @pxpm 's PR to fix this, it was like you said - just inverting two things fixed it. It'll be available with a ```composer update``` later today, as ```3.6.25```, after I merge a few more non-breaking changes.

I'm surprised this bug didn't annoy more people - once I tested it to confirm it, it was super-annoying to me.

Thanks again.
Cheers!
