### ISSUE TITLE
Table field won't reordering

### ISSUE THREAD

**Issue by Mehdiisnotanobject** [Laravel-Backpack/CRUD#1904]
# Bug report

### What I did:

Hello, i add 'table field' in my CRUD but it seems bugged.

### What I expected to happen:

I expected reordering rows by clicking on arrow buttons.[here screen](https://imge.to/i/Pjlt4)

### What happened:

Nothing, i cannot reorder the rows.

### What I've already tried to fix it:

...how ? ^^

### Backpack, Laravel, PHP, DB version:

Backpack : 3.6
Laravel : 5.8
PHP : 7.3
DB : MySQL

**Comment by pxpm** [comment]
Console errors might help ?

**Comment by tabacitu** [comment]
Hi @Mehdiisnotanobject - I just double-checked and the table field does reorder using the arrows (drag & drop). Might be some javascript error you introduced on page, if you have custom fields? That's the only idea I have, I'm afraid.
