### ISSUE TITLE
Can't display two fields with same name

### ISSUE THREAD

**Issue by sergunik** [Laravel-Backpack/CRUD#1905]
## What I have: ##
Tables in DB:
```lang-php
Schema::create('orders', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->unsignedBigInteger('primary_person');
    $table->unsignedBigInteger('secondary_person');
});
```
```lang-php
Schema::create('persons', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->string('first_name', 255);
    $table->string('last_name', 255);
});
```

Model:
```lang-php
class Order extends Model
{
    use CrudTrait;

    protected $table = 'orders';
    protected $fillable = [
        'primary_person',
        'secondary_person',
    ];

    public function primaryPerson()
    {
        return $this->hasOne(Person::class, 'id', 'primary_person');
    }

    public function secondaryPerson()
    {
        return $this->hasOne(Person::class, 'id', 'secondary_person');
    }
}
```

## What need to do: ##
On page *edit order* I want to display information about two persons:

* First name of Primary person
* Last name of Primary person
* First name of Secondary person
* Last name of Secondary person

## What I did: ##
In OrderCrudController.php added:
```lang-php
$this->crud->addFields([
    [
       'label' => 'First Name of Primary person',
       'type' => 'text',
       'name' => 'first_name',
       'entity' => 'primaryPerson',
       'model' => 'App\Models\Person',
    ],
    [
        'label' => 'Last Name of Primary person',
        'type' => 'text',
        'name' => 'last_name',
        'entity' => 'primaryPerson',
        'model' => 'App\Models\Person',
    ],
    [
        'label' => 'First Name of Secondary person',
        'type' => 'text',
        'name' => 'first_name',
        'entity' => 'secondaryPerson',
        'model' => 'App\Models\Person',
    ],
    [
        'label' => 'Last Name of Secondary person',
        'type' => 'text',
        'name' => 'last_name',
        'entity' => 'secondaryPerson',
        'model' => 'App\Models\Person',
    ]
]);
```

## What I receive: ##
Only latest two fields (secondary person information).

[![enter image description here][1]][1]

## The main problem: ##
I couldn't display Fields with the same *"name"*, because *"name"* - the attribute (column in the database), which will also become the name of the input.<br />
In Columns this situation handled with *"key"* attribute. **But in Fields it doesn't work.**

  [1]: https://i.stack.imgur.com/cDLN5.png

## Env:
* "php": "^7.2",
* "laravel/framework": "5.8.*",
* "backpack/crud": "^3.6",

**Comment by pxpm** [comment]
You can give it different names `primary_first_name, primary_last_name` and use mutators and acessors to manipulate that data. `getPrimaryFirstNameAttribute()` or `setPrimaryFirstNameAttribute()`

**Comment by sergunik** [comment]
> You can give it different names `primary_first_name, primary_last_name` and use mutators and acessors to manipulate that data. `getPrimaryFirstNameAttribute()` or `setPrimaryFirstNameAttribute()`

Thank you @pxpm !
It could be as a solution. But maybe somebody will suggest more elegant way.

**Comment by tabacitu** [comment]
@sergunik the problem is with HTML forms in general - you can only send _one_ value through GET/POST so the second form element with the same name will basically overwrite the value of the first. 

**I know for sure @pxpm 's solution will work - I would recommend you go with that one.** I think it's a good one.

You could also try doing:

```diff
$this->crud->addFields([
    [
       'label' => 'First Name of Primary person',
       'type' => 'text',
-       'name' => 'first_name',
+       'name' => 'primaryPerson.first_name',
       'entity' => 'primaryPerson',
       'model' => 'App\Models\Person',
    ],
    [
        'label' => 'Last Name of Primary person',
        'type' => 'text',
        'name' => 'last_name',
-        'name' => 'primaryPerson.last_name',
+        'entity' => 'primaryPerson',
        'model' => 'App\Models\Person',
    ],
    [
        'label' => 'First Name of Secondary person',
        'type' => 'text',
-        'name' => 'first_name',
+        'name' => 'secondaryPerson.first_name',
        'entity' => 'secondaryPerson',
        'model' => 'App\Models\Person',
    ],
    [
        'label' => 'Last Name of Secondary person',
        'type' => 'text',
-        'name' => 'last_name',
+        'name' => 'secondaryPerson.last_name',
        'entity' => 'secondaryPerson',
        'model' => 'App\Models\Person',
    ]
]);
```

I think you can also skip defining ```entity``` and ```model``` in this case. I'm not 100% sure it'll work - I remember leaving an opening for something like this to work when implementing 1-1 relationships, but I haven't tried it in quite a while now. Let me know.

Cheers!

**Comment by JoepdeJong** [comment]
Test
