### ISSUE TITLE
Tab navigation deliberately disabled on Date picker field?

### ISSUE THREAD

**Issue by patlamontagne** [Laravel-Backpack/CRUD#1910]
Using the latest version, what's the reason behind [these lines](https://github.com/Laravel-Backpack/CRUD/blame/master/src/resources/views/fields/date_picker.blade.php#L86) except for preventing default tab navigation? :

```
$fake.on('keydown', function(e){
       e.preventDefault();
       return false;
});
```

**Comment by pxpm** [comment]
Not  sure, but i think that without preventing keydown something weird happens to datepicker. 

I think i remember some talk about it some time ago, here or in gitter. You can try to remove and see by yourself the effects it produces.

BR,
Pedro

**Comment by patlamontagne** [comment]
Yeah I removed it and have yet to notice anything unusual.

I know it's not a priority but if this snippet's goal is to fix an unwanted behavior in a specific browser or older versions it would be interesting to make it some kind of shim for the targets browsers/version in order to prevent breaking keyboard accessibility for the other browsers.

**Comment by tabacitu** [comment]
Hi @patlamontagne ,

Yup, as @pxpm said, that's disabled for a reason (and I found the issue, it's here - https://github.com/Laravel-Backpack/CRUD/issues/1878). As I explained there, the plugin actually:
- DOES support keyboard navigation;
- DOESN'T support typing in your own date;

Removing the restriction we're talking about here would allow users to do both.

That being said, I found a way around it. Let's move the conversation to the PR here please:
