### ISSUE TITLE
[3.6][Bug][Has Fix] Image Field on validation of another field

### ISSUE THREAD

**Issue by dimitrisdnr** [Laravel-Backpack/CRUD#1915]
# Bug report

### What I did: 

Submitted a form leaving a required field empty (not image field, but another field).

### What I expected to happen: 

Display values of all fields on validation failure and redirect.

### What happened: 

Image field URL got duplicate and broken. Broken value is stored as flashed value inside old().

### What I've already tried to fix it:

Replaced this line (154): 
```
$hiddenImage.val($mainImage.attr('src'));
```
With this fix:
```php
@if (isset($field["value"]))
// Initialize hidden form input in case we submit with no change
$hiddenImage.val("{{ $field['value'] }}");
@endif
```

**Comment by pxpm** [comment]
Hello @dimitrisdnr ,

i really could not replicate your issue, at least the part where image name is duplicated, maybe i'm doing something different.

This is what i did:

1- Created an entity that has an image field (not required) and a name, that is required.
2- I pick an image and left the name empty so it breaks the validation.

As expected, i'm redirected to create page, with a image (correct one, displaying ok) and a validation error on the name field. I saved it to database.

I got to /entity/1/edit and everything is there as expected. 

BR,
Pedro

**Comment by dimitrisdnr** [comment]
It seems I provided you with confusing feedback. I'm sorry for that.

Here is the thing. My 'image' field stores an image in the filesystem, and also stores the path to use inside storage disk, in database as a string (e.g. avatars/t453dffd34.jpg). Later, while an image is already stored for that specific record, if I move to that record once more and set a required field as empty (e.g. an input text field) and validation fails, img element for displaying my image will try to display an image from invalid URL after redirect. I hope you manage to reproduce it.

**Comment by pxpm** [comment]
Hello @dimitrisdnr 

Thank you for taking time too clarify this issue.

I can confirm it's happening. I tried to stop the problem before it occurs 

(The way you are doing is hacking into the value of the image, that might not be correct in every scenario)

I came up checking if value is a valid url before proceding with encoding in case it's not.

This is the complete php top at image.blade.php

```
    if (!isset($field['wrapperAttributes']) || !isset($field['wrapperAttributes']['class']))
    {
        $field['wrapperAttributes']['class'] = "form-group col-md-12 image";
    }

    $prefix = isset($field['prefix']) ? $field['prefix'] : '';
    $value = old(square_brackets_to_dots($field['name'])) ?? $field['value'] ?? $field['default'] ?? '';
    if (filter_var($value, FILTER_VALIDATE_URL)) {
        $image_url = $value;
    }else{
    $image_url = $value
        ? preg_match('/^data\:image\//', $value)
            ? $value
            : (isset($field['disk'])
                ? Storage::disk($field['disk'])->url($prefix.$value)
                : url($prefix.$value))
        :''; // if validation failed, tha value will be base64, so no need to create a URL for it
}
```

Could you apply this fixes and check if it's working now as expected ?

I'm a little concerned into pushing a PR to this without proper testing, working with urls is never easy, and from my research i will leave this here for future reference: [idn_to_ascii](https://www.php.net/manual/en/function.idn-to-ascii.php)

**Comment by dimitrisdnr** [comment]
Yes, I admin that I shared a fast & dirty fix, and this solves the problem in a way, but let me express my dissagreement at one thing.
The reason that old() method returns a full URL as a flashed value is because this full URL was set as value to hidden field input element before form submission.

I honestly believe we should fix this from its root.
My new suggestion after taking a more cautious look is removing line 154 completely: $hiddenImage.val($mainImage.attr('src'));
and modify field element itself:
<input type="hidden" id="hiddenImage" name="{{ $field['name'] }}">
to get value stored on initialization:
<input type="hidden" id="hiddenImage" name="{{ $field['name'] }}" value="{{ $value }}">
which also gives the possibility of storing default field value upon submitting form (e.g. a link set by developers for a default image).

BR,
dimitrisdnr

**Comment by pxpm** [comment]
This one had already been fixed in: https://github.com/Laravel-Backpack/CRUD/commit/a941d7939fe3763899509a0cae14b61a8c5e4021#diff-831905e64cecad2153bbcb0f931349cc

Best,
Pedro
