### ISSUE TITLE
[4.0][Feature] Editable Relation Field

### ISSUE THREAD

**Issue by pestopancake** [Laravel-Backpack/CRUD#1920]
I've seen a few requests about editing a related entity, so thought I'd dump my solution here in-case it's useful to anyone...

I've not tested all field types, and so far I have had to override date_picker and select2_from_ajax. The main problem being that the fields use the 'name' attribute in contexts other than the field name, e.g. db column name, id of html element, in javascript code. In this scenario the name will be something like "member[beneficiary][0][name]", so the brackets break any javascript.

https://gist.github.com/pestopancake/746ccb4d98f20cc51b6794b576ed6292#file-relationfields-blade-php

<img width="1010" alt="Screenshot 2019-07-01 at 16 14 07" src="https://user-images.githubusercontent.com/596881/60447410-54aa2e80-9c1b-11e9-868a-87899e72780a.png">

**Comment by tabacitu** [comment]
Thank you for sharing this @pestopancake ! I'm working hard on v4 right now, and I'll take a had look at it.

**Comment by tabacitu** [comment]
Closing this because we have a working solution for this in #2311 (relationship field) and #2266 (repeatable field), which will be finished and merged in a few weeks.

Thanks again for taking the time to build and share this with us @pestopancake ! It was helpful.
