### ISSUE TITLE
Toggle Field Visibility in the Laravel-Backpack demo

### ISSUE THREAD

**Issue by tifaahmed** [Laravel-Backpack/CRUD#1925]
# 'type' => 'toggle', is not working in the demo 
and i want to Hides/Shows  fields based on a radio selection

### What I did:

>        'type' => 'toggle', is not working 
            $this->crud->addField([
            'label' => 'Product Category',
            'name' => 'choice', // can be a real db field, or unique name
            'type' => 'toggle',
            'options' => [ // same as radio, these act as the options, the key is the radio value
                0 => 'Category',
                1 => 'Product'
            ],
            'hide_when' => [ // these fields hide (by name) when the key matches the radio value
                0 => ['subject'],
                1 => ['']
            ],
            'default' => 0 // which option to select by default
        ]);

//            $table->boolean('choice')->default(0);
//            $table->text('subject')->nullable();

### What I expected to happen:
i expecte when choce Category the subject hide and its value not stored in the database and wil be visible when i select Product

### What happened:
i get .
ERROR
500
View [fields.toggle] not found. (View: C:\xampp2\htdocs\atqannew\14 mag\dmg\vendor\backpack\crud\src\resources\views\inc\show_fields.blade.php)

**Comment by tabacitu** [comment]
Hi @tifaahmed ,

Indeed, we don't have that - the ```toggle``` that's why blade file does not exist.
But you can use the field that Owen built in this PR: https://github.com/Laravel-Backpack/CRUD/pull/165

It's reported to work like a charm.

Cheers!
