### ISSUE TITLE
[4.0][Improvement] Usage stats reported version not matching composer package version

### ISSUE THREAD

**Issue by mttjohnson** [Laravel-Backpack/CRUD#1927]
# Bug report
Possible bug in reported versions on usage stats.

### What I did:
I was trying to diagnose getting the BACKPACK_LICENSE key installed, and while digging through code found that `\Backpack\CRUD\CrudUsageStats::sendUsageStats` is sending out `$_SERVER['BACKPACK_BASE_VERSION']` and `$_SERVER['BACKPACK_CRUD_VERSION']` and those values appear to be set in the respective service providers `\Backpack\Base\BaseServiceProvider::boot` and `\Backpack\CRUD\CrudServiceProvider::boot`

### What I expected to happen:
I expected `\Backpack\CRUD\CrudServiceProvider::VERSION` to match the version of the composer package `backpack/crud` I have installed `3.6.21`. 
I expected `\Backpack\Base\BaseServiceProvider::VERSION` to match the version of the composer package `backpack/base` I have installed `1.1.4`. 

### What happened:
`\Backpack\CRUD\CrudServiceProvider::VERSION` has a constant set to `3.5.1` https://github.com/Laravel-Backpack/CRUD/blob/3.6.21/src/CrudServiceProvider.php

`\Backpack\Base\BaseServiceProvider::VERSION` has a constant set to `1.0.0` https://github.com/Laravel-Backpack/Base/blob/1.1.4/src/BaseServiceProvider.php 

### What I've already tried to fix it:
I haven't tried to change anything because I wasn't sure if this was deliberate, or in need of correcting. I figure if you're going to collect/track usage stats, you might as well get accurate information.

### Backpack, Laravel, PHP, DB version:
Backpack: 3.6.21
Laravel: 5.8.24
PHP: 7.1
DB: MySQL 5.7

**Comment by mttjohnson** [comment]
You may be able to avoid hard coding a version number into a class constant by using a package that queries the composer.lock file to determine the version of an installed package.

https://packagist.org/packages/ocramius/package-versions

**Comment by tabacitu** [comment]
Hi @mttjohnson ,

Indeed, the system we're using right now doesn't work very well - we forget to update it all the time. The package you suggested looks like the best solution - at the time we didn't want an extra dependency, but it looks like that's the best solution we can actually use.

We don't care about the stats recording the exact version, we're more interested in 3.5.x vs 3.6.x - that kind of stuff. But this _is_ something that doesn't work very well - and I agree we should improve it.

Thanks for the suggestion. Will do. I'll follow-up here when the PR is ready.
Cheers!

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/1947
Will merge soon in the v4 branch.

Thanks again @mttjohnson !
