### ISSUE TITLE
WYSIWYG field is not working on mobile devices

### ISSUE THREAD

**Issue by andrewdudu** [Laravel-Backpack/CRUD#1928]
# Bug report
On Mobile device, WYSIWYG is not working properly, all input field can't focus.
### Backpack, Laravel, PHP, DB version:
Backpack 3.5

**Comment by tabacitu** [comment]
Hi @andrewdudu ,

I'm afraid I can't confirm the bug. My tests all show that all wysiwyg editors are focusing: https://share.getcloudapp.com/12uOePNl

It must have been something you were doing. Have you gotten to the bottom of this?

Cheers!
