### ISSUE TITLE
Including list view of relationship entity on update page

### ISSUE THREAD

**Issue by BatGuy74** [Laravel-Backpack/CRUD#1929]
I am trying to extend an update view to include a list view of some related items below the edit form.

I have two models, Publishers and Volumes, which have a many to many relationship. What I am trying to do is this.... when a user clicks on the edit button for a publisher, I want them to go to a page with the standard edit fields, but also have a list view below the form that lists all of the volumes that are connected to that publisher via their relationship.

Is there an easy way to do this?

I hope this makes sense.

**Comment by DelightedD0D** [comment]
Hi @BatGuy74 Did you get enough of an answer at https://stackoverflow.com/questions/56977461/including-list-view-of-relationship-entity-on-update-page that we can call this issue resolved for now?

**Comment by tabacitu** [comment]
Great solution @DelightedD0D . Closing this as it's more of a stack-overflow kind of question - and we've already answered there.

Cheers!
