### ISSUE TITLE
[4.0][Refactor][To do] Clean up CrudPanel object

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1942]
Right now most settings for an operation are put directly inside the CrudPanel object. 

![Screenshot 2019-07-22 at 09 25 21](https://user-images.githubusercontent.com/1032474/61610746-a8c89180-ac62-11e9-8f07-56bce38aa0a0.png)

We have:

- ```$crud->model``` - for all operations
- ```$crud->route``` - for all operations
- ```$crud->settings``` - which stores settings per operation name (create, update, reorder, show, etc);
- ```$crud->access``` - which gives access to operations, so it should probably be moved inside ```$crud->settings```
- ```$crud->reorder```, ```$crud->reorder_label```, ```$crud->reorder_max_level```- only for Reorder
- ```$crud->bulk_actions``` - only for List
- ```$crud->page_length_menu``` - only for List
- ```$crud->titles``` - which stores titles per operation

The object is in dire need of a cleanup. And since this means many breaking changes, this is the time to do it.

I see two options to structure everything here:

### 1) By Feature

(closer to how the object is now)

```php
class CrudPanel {
    public $settings = [
        'create' => [],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
    public $fields = [
        'create' => [],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
    public $columns = [
        'create' => [],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
    public $titles = [
        'create' => [],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
    public $headings = [
        'create' => [],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
    public $filters = [
        'create' => [],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
}
```

### 2) By Operation

```php
class CrudPanel {
    public $operations = [
        'create' => [
            'access' => false,
            'fields' => [],
        ],
        'update' => [],
        'list' => [],
        'delete' => [],
        'clone' => [],
        'reorder' => [],
        'revisions' => [],
        'show' => [],
    ];
}
```

Even easier than that would be for each Operation to be a class (not an array). That would make it easier to further drill down, and add settings for a particular Action of an Operation (ex, Create operation has ```create()``` and ```store()``` - you might want to add a setting for one of those, but not both). Like in my rant here https://github.com/Laravel-Backpack/CRUD/issues/1578#issuecomment-513664703

**Comment by DelightedD0D** [comment]
I like this idea, for what its worth, "2) By Operation" feels cleaner to me.

**Comment by tabacitu** [comment]
Related: https://github.com/Laravel-Backpack/CRUD/issues/1941

**Comment by tabacitu** [comment]
Started working on this in PR https://github.com/Laravel-Backpack/CRUD/pull/1997
Let's move the conversation there please.
