### ISSUE TITLE
Add Backpack CRUD max_image_size field

### ISSUE THREAD

**Issue by mauricioPisabarro** [Laravel-Backpack/CRUD#1956]
# Proposal

### What I did: 

uploaded an image bigger than what is possible to post to the PHP server.

### What I expected to happen: 

expected my custom laravel request to validate the image size before anything else.  

### What happened: 

the image was to be sent to the PHP server causing an exception stating the post max size was exceeded is thrown. This prevented the custom laravel request from validating the image size.

### What I've already tried to fix it: 

I made a max image size validation on Javascript's end which prompts an alert when it fails, and prevents the image from being sent to the PHP server. I created the following pull request for it: https://github.com/Laravel-Backpack/CRUD/pull/1955/commits/17d3fe0241a914dac2005d040aaeb656cdc28410

### Backpack, Laravel, PHP, DB version: 

3.6.*, 5.8.3, ^7.1.3, N/A

**Comment by tabacitu** [comment]
Merged https://github.com/Laravel-Backpack/CRUD/pull/1955 into v4! Thanks again @mauricioPisabarro !
