### ISSUE TITLE
[4.0][Refactor][Proposal] Should we merge Base and CRUD into one repository?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#1960]
Does it actually make sense to have two packages, with separate versions?
- You can't use CRUD without Base.
- You can use Base without CRUD, but nobody does.

### If we merge Base into CRUD:

**Developers** would be able to:
- create views in one folder instead of two (no distinction between base and crud)

**Package developers** would be able to:
- create themes that include CRUD views; 
    - themes could provide new fields, columns, filters, buttons, operations;
    - themes could overwrite existing CRUD views (ex: all fields are VueJS instead of jQuery)

**Maintainers** would be able to:
- maintain one version number for the Backpack software (v4.x)
- have all lang files under one "backpack" namespace, instead of two (currently  ```trans('backpack::login')``` and ```trans('crud::save')```);
- have one Laravel Mix file, in one Backpack project, that generates multiple CSS and JS bundles (ex: ```backstrap.js``` for everything outside CRUD, and ```field_vendors.js``` for all fields - thought it will definitely be a HUGE file);

---

**Thoughts anyone?** @Laravel-Backpack/veterans ? Any reasons we shouldn't merge them? I've been thinking about it for a while and I really can't see why... maybe I'm missing something...

Thanks!

**Comment by OwenMelbz** [comment]
Merge it

**Comment by eduardoarandah** [comment]
yes

**Comment by vesper8** [comment]
yes I think it would be cleaner and more organized if it was one repo. Installation issues would be easier to troubleshoot too

**Comment by parse-code** [comment]
just do it

**Comment by xlstefan** [comment]
It definitely has sense to merge it since they are dependent on each other (as you wrote base is independent but could be used alone, but it's rarely used like that).

I vote for merging.

**Comment by tabacitu** [comment]
Thanks for the feedback everyone! It's done, PR https://github.com/Laravel-Backpack/CRUD/pull/2028 - let's close this issue then.
