### ISSUE TITLE
[3.6][Possible Bug] Having an attribute with same name that entity_name generates a 404 error

### ISSUE THREAD

**Issue by Gaspertrix** [Laravel-Backpack/CRUD#1961]
# Bug report

### What I did:
Tried to update a record

### What I expected to happen:
Record is updated

### What happened:
Got a 404 error message

That's happen because entry's id is read first from input using entity_name:
https://github.com/Laravel-Backpack/CRUD/blob/4d02090ec80f7a91aa833aa0064f1090164e34c9/src/PanelTraits/Read.php#L18

### What I've already tried to fix it:
Change `entity_name` value

### Backpack, Laravel, PHP, DB version:
`FieldValue` attributes:
-id (int)
-name (string)
-value (string)

`FieldValueCrudController`:
```
...

public function setup()
{
	/*
	|--------------------------------------------------------------------------
	| CrudPanel Basic Information
	|--------------------------------------------------------------------------
	*/
	$this->crud->setModel('App\Models\FieldValue');
	$this->crud->setRoute(config('backpack.base.route_prefix') . '/field-values');
	$this->crud->setEntityNameStrings('value', 'values');

	...
}

...
```
--------------------

**Comment by tabacitu** [comment]
Hi @Gaspertrix ,

Hmm... I suspect your error comes from something else.

The Backpack Demo has an "Icon" entity that also has an "icon" attribute, and it works fine:

```php
class IconCrudController extends CrudController
{
    public function setup()
    {

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel('App\Models\Icon');
        $this->crud->setRoute(config('backpack.base.route_prefix').'/icon');
        $this->crud->setEntityNameStrings('icon', 'icons');

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */

        // $this->crud->setFromDb();

        $this->crud->addColumns(['name', 'icon']);
        $this->crud->addField('name');
        $this->crud->addField([
            'label'   => 'Icon',
            'name'    => 'icon',
            'type'    => 'icon_picker',
            'iconset' => 'fontawesome', // options: fontawesome, glyphicon, ionicon, weathericon, mapicon, octicon, typicon, elusiveicon, materialdesign
        ]);
```

**Comment by Gaspertrix** [comment]
> 
> 
> Hi @Gaspertrix ,
> 
> Hmm... I suspect your error comes from something else.
> 
> The Backpack Demo has an "Icon" entity that also has an "icon" attribute, and it works fine:
You are right. I can't reproduce this with the demo.

I am going to debug more. Somehow it is reaching this:
https://github.com/Laravel-Backpack/CRUD/blob/4d02090ec80f7a91aa833aa0064f1090164e34c9/src/PanelTraits/Read.php#L28

Do you have any idea why may it reach that line?

**Comment by tabacitu** [comment]
No, sorry... What does your URL look like?

**Comment by tabacitu** [comment]
@Gaspertrix I'm going to close this, since enough time has passed, and I think you've solved it one way or the other. If you remember how, please reply here - might be helpful to someone who stumbles upon the issue.

Cheers!
