### ISSUE TITLE
Дополнительные поля из pivot-таблицы

### ISSUE THREAD

**Issue by dormadekhin** [Laravel-Backpack/CRUD#1967]
Появилась ли возможность создавать отношения many-many с заполнением дополнительных полей в pivot-таблицы?
Например: есть таблица товаров,  и таблица пользователей, в  pivot-таблице есть id-товара, id-пользователя, и количество товара
Появилась ли встроенный тип для вывода поля ввода количества товара, чтобы записывалось в pivot-таблицу, в поле количество?

**Comment by tabacitu** [comment]
Hi @dormadekhin ,

Technically it's possible but we don't have a field type that does that yet. Check out [this issue](https://github.com/Laravel-Backpack/CRUD/issues/1061) - the author has created a field type that promises a solution.

Cheers!
