### ISSUE TITLE
Miss export translation in fr/crud.php

### ISSUE THREAD

**Issue by Benoit75** [Laravel-Backpack/CRUD#1970]
Hello, 
# Bug report
I'm using version 3.6.28 of CRUD and it missing translation for "export" in french (and  french Canadian too)

in en/crud.php   https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/lang/en/crud.php#L105-L112

We need to add :  ` 'export'            => 'Exporter',`
In fr/crud.php 
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/lang/fr/crud.php#L105-L110
in fr_CA/crud.php
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/lang/fr_CA/crud.php#L93-L100

### Backpack, Laravel, PHP, DB version:
backpack/base                         1.1.7  
backpack/crud                         3.6.28
Thank's

**Comment by tabacitu** [comment]
Thank you @Benoit75 . Will do. 

Do you want to submit a PR so you become an official contributor on Github? You should be able to make such a small change from the Github interface:
- fork
- make change in your fork
- make a pull request from your fork to the ```master``` branch

Cheers!

**Comment by Benoit75** [comment]
Hi @tabacitu, i will submit this PR. 
Many thank's for your amazing code. 
BTW any timeline for V4 ? 
Cheers.
B.

**Comment by Benoit75** [comment]
So it's done (my first PR !) https://github.com/Laravel-Backpack/CRUD/pull/1973
Cheers.
