### ISSUE TITLE
var_dump  in select2_from_array.blade.php

### ISSUE THREAD

**Issue by goodrespect** [Laravel-Backpack/CRUD#1972]
# Bug report
select2_from_array.blade.php remove var_dump please
Last backpack version. https://prnt.sc/ow6mjj

**Comment by tabacitu** [comment]
Ouch! Sorry for leaving that in. Thank you for reporting this @goodrespect - just pushed a hot fix, it should be fixed after a ```composer update```.

Thanks again. Cheers!
