### ISSUE TITLE
composer require backpack/base 

### ISSUE THREAD

**Issue by dormadekhin** [Laravel-Backpack/CRUD#1974]
# Bug report

after install v4 and run command `composer require backpack/base`
I get error: Command "backpack:crud" is not defined. 

Backpack version: 4

**Comment by tabacitu** [comment]
Hi @dormadekhin ,

v4 isn't ready for prime-time yet, it's currently in alpha. 

But if you're curious, here are the steps to install v4-alpha on a clean Laravel app:

```
composer require backpack/base:"v4.x-dev as 1.1.99"
composer require backpack/crud:"v4.x-dev as 3.6.99"
php artisan backpack:base:install
php artisan backpack:crud:install
```

Cheers!
