### ISSUE TITLE
how to add 180 days

### ISSUE THREAD

**Issue by trungleminh1698** [Laravel-Backpack/CRUD#1978]
# Bug report

### What I did:
```
use Illuminate\Support\Carbon;
$this->crud->addColumn([
                    'label'=>'Date Export'
                    ,'type'=>'date'
                    ,'name'=>'date_export'
                    ,'options'=>(addDays(180))
                    ,'format'=>'d-m-Y'
                ])
```
but doesn't working
### What I expected to happen:
I want to this column will add 180 days in list 
example: instead of August 28, 2019, so I want to see is February 21, 2020.
### What happened:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function App\Http\Controllers\Admin\addDays()

### Backpack, Laravel, PHP, DB version:
backpack crud :3.6.29 ,
laravel 5.8.33, 
Mysql MariaDB :10.1.38

**Comment by tabacitu** [comment]
Hi @trungleminh1698 ,

If it's a valid option, it should work - I don't know. But make sure your options are between quotes thought. Please ask help questions on Stack-Overflow, not Github - we're using Github issues as our to-do list.

Cheers!
