### ISSUE TITLE
Laravel backpack Search

### ISSUE THREAD

**Issue by sandeepchowdary7** [Laravel-Backpack/CRUD#1980]
Hello guys, I'm using Laravel backpack in my project. I’m trying to enable the case-insensitive search functionality. here is my code
 ```
$this->crud->addColumn([
            'name' => 'name',
            'label' => 'name',
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhere('name', 'like', '%'.$searchTerm.'%');
            }
        ]);
```
somehow it is not working as expected. any help that would be great. Thanks!

**Comment by brynnb** [comment]
@sandeepchowdary7 This is the first result for this issue - might be helpful for future people if you included what the fix was :)

**Comment by sandeepchowdary7** [comment]
@brynnb here is the fix

```
$this->crud->addColumn([
           'name' => 'name',
           'label' => 'name',
           'searchLogic' => function ($query, $column, $searchTerm) {
               $query->orWhere('name', 'ilike', '%'.$searchTerm.'%');
           }
       ]);
```

Cheers! :)

**Comment by brynnb** [comment]
Thanks Sandeep! Additionally I found in another result that the issue is sometimes the database collation - apparently some are case sensitive and others aren't. I believe this was the issue for me (two identical sites deployed on two different databases - MySQL and Postgres - and one was being case sensitive and the other wasn't).

**Comment by sandeepchowdary7** [comment]
@brynnb I'm using Postgres DB. The above code was fixed my problem.

**Comment by brynnb** [comment]
It's a good solution for postgres, but it will throw 500 errors if using MySQL which doesn't have "ilike". For a project like mine that may be deployed on a variety of databases, this wouldn't work - but using the migrations to ensure the collation for columns in case insensitive will work regardless of database. 

Thanks again!

**Comment by tabacitu** [comment]
Thanks for sharing your solution @sandeepchowdary7 !

**Comment by vishaltarkar** [comment]
Is there any way to put this change on every column search?
my whole project search with case sensitive and I want to make it case insensitive.

**Comment by tabacitu** [comment]
@vishaltarkar I expect you're having a collation problem - try changing the collation of your tables/columns. By default, Backpack's search is case INsensitive. You search "box", you get "Box" too.

**Comment by vishaltarkar** [comment]
@tabacitu : I'm using `postgresql `

So for now I have added this to columns where I have search enable. 
```

'searchLogic' => function ($query, $column, $searchTerm) {
    $query->orWhere('name', 'ilike', '%' . $searchTerm . '%');
},
```

**Comment by joelmellon** [comment]
#4277 will fixes this issue across all searches in PostgreSQL and maintains support for MySQL `LIKE`.
