### ISSUE TITLE
[3.6][Bug] "AutoSet" doesn't follow model connection.

### ISSUE THREAD

**Issue by fzhantw** [Laravel-Backpack/CRUD#1982]
# Bug report

### What I did:
Using a model that using different db connection with default,
and I have a column which type is "enum".

when I call CrudPanel::setFromDb, "enum" type mapping doesn't register to doctrine type mapping.

### What I expected to happen:
"AutoSet" should set from connection of the model.

### What happened:
So I get an error: "Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it."

### What I've already tried to fix it:
Set default connection before setFromDB,
And I'm gonna make a PR to fix this.

### Backpack, Laravel, PHP, DB version:
Backpack 3.6.29
Laravel 5.8.33
5.7.24 - Homebrew

**Comment by tabacitu** [comment]
Thank you for reporting this, @fzhantw , and providing the PR! 🎉
