### ISSUE TITLE
Bug: Edit with multiple tabs - after "save and edit this item" selected tab got reset

### ISSUE THREAD

**Issue by tomsb** [Laravel-Backpack/CRUD#2006]
# Bug report

### What I did:
Fresh backpack install, simple CRUDController with fields definition like this:
```
        $fields = [
            [
                'name'  => 'name',
                'label' => 'field1',
                'tab'   => 'first',
            ],
            [
                'name'  => 'text',
                'label' => 'field 2',
                'tab'   => 'second',
            ],
        ];
        $this->crud->addFields($fields);
```
User tries to edit item multiple times like this:

- Open item in edit mode
- Click on "second" tab
- Edit "text" field
- Click "Save and edit this item" button
- Saved successfully and redirected back to this page with "second" tab selected.
- Edit "text" field again
- Click "Save and edit this item" button again
- Saved successfully and redirected back to this page **with "first" tab selected**.
User should remain in selected tab after subsequent saves.

### What I expected to happen:
- ...
- Saved successfully and redirected back to this page with "second" tab selected.
- Edit "text" field again
- Click "Save and edit this item" button again
- Saved successfully and redirected back to this page **with "second" tab selected**.

### What I've already tried to fix it:
View file: form_content.blade.php
After the second save/redirect there is incorrect value in "current_tab" hidden field. current_tab value is updated only when user clicks on the tab.
Fix: set "current_tab" value after page load if hash found in URL like this:
```
      if (window.location.hash) {
          $("input[name='current_tab']").val(window.location.hash.substr(1));
      }
```
This fix makes sure user remains in selected tab after multiple saves.
Already created the pull request: https://github.com/Laravel-Backpack/CRUD/pull/2007

**Comment by tomsb** [comment]
This bug exists also in v4 branch. Should I create pull request for v4 branch too?

**Comment by tabacitu** [comment]
Thanks a lot for reporting this, and taking the time to submit the PR, @tomsb ! It's now merged and tagged.

No need to submit another PR for v4, thank you, I've already merged the change into the v4 branch too. So you're running v4 already, huh? :-) Glad to hear that, how do you like it so far?

**Comment by tomsb** [comment]
Actually I looked at the v4 source code for this bug on github, not running v4 yet. I could start a new project with v4 tomorrow, is it already usable? Was waiting for official v4 launch.

**Comment by tabacitu** [comment]
Not really, no. One more thing to do before everybody can install v4beta - [merging Base and CRUD](https://github.com/Laravel-Backpack/CRUD/issues/1960). Then there are more changes we'll be pushing, but only to the blade files, which I assume you won't be overwriting much, and the generators package.

If you plan to start a new project:
- this week you probably _can't_ use L6 & Backpack v3 (dependencies need to support L6 too)
- this week you probably _can't_ use L6 & Backpack v4 (dependencies need to support L6 too) 
- next week you probably _can_ use L6 & Backpack v3
- next week you probably _can_ use L6 & Backpack v4 (public beta)

**Comment by tomsb** [comment]
OK, I'll wait for v4 public beta. Next week also is my deadline to start this project :)
