### ISSUE TITLE
browse field store "uploads/filename" without considerate real upload path

### ISSUE THREAD

**Issue by reeslo** [Laravel-Backpack/CRUD#201]
![image](https://cloud.githubusercontent.com/assets/2724844/19682623/c5066db8-9aae-11e6-8119-f8702ea6fe0f.png)

How to change that path  ?

**Comment by tabacitu** [comment]
Hi @reeslo ,

If you change it you won't know how to find the file afterwards. So you cannot change that path. It's being set by elFinder. If you want to upload files to custom paths you can use the [upload field type](https://laravel-backpack.readme.io/docs/crud-fields#upload), without the file manager UI.

Cheers!
