### ISSUE TITLE
number column should show nothing if value is null

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#2010]
Currently if a value is null, the number column type casts it to 0.

Better for it to not display anything actually.

**Comment by tabacitu** [comment]
Hmm... that doesn't seem to happen for me: https://share.getcloudapp.com/04ur6zvY
Are you sure it's not an accessor or mutator in your model doing this @ziming ?

**Comment by ziming** [comment]
I mean the column type number. Not the field type number.

I used the column type number because I wanted the thousand separator to be shown when there is a value above 999

Currently column type number casts null into 0 in the column display.

**Comment by tabacitu** [comment]
Oh the _column_! :-) Sorry I misread. I totally agree, _null means null_. I've just pushed the fix, a ```composer update``` should do it for you. Thanks for reporting this, cheers!

**Comment by ziming** [comment]
Thank you :)
