### ISSUE TITLE
[4.1][Proposal] GrapeJS field type

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2023]
Page builder field using GrapeJS... maybe?
https://grapesjs.com/

**Comment by dauvray** [comment]
I tried  as custom field but it took a lot of effort. there are often changes that break the code incomprehensibly. I then tried Gutemberg via the Laraberg package and it works much better.

**Comment by dauvray** [comment]
Gutemberg via laraberg is a good choice for a custom field

**Comment by tabacitu** [comment]
Yup - there's an open issue for that too 😄 https://github.com/Laravel-Backpack/CRUD/issues/1872

**Comment by dauvray** [comment]
Maybe grapejs is good for the pagemanager package
