### ISSUE TITLE
Cant install Backpack 4.0 on Laravel 6.0

### ISSUE THREAD

**Issue by rodrigouriarte05** [Laravel-Backpack/CRUD#2024]
# Bug report

New project on Laravel6 and following backpack doc, do **composer require backpack/crud** and composer try to install BP3.6, installation failed.
There is a way to install BP4.0 on L6.0, its stable? Or maybe BP3.6 on L6.0? Im starting a new project and want to be updated.
Thanks

**Comment by tabacitu** [comment]
Hi @rodrigouriarte05 ,

I've just pushed support for Laravel 6 in Backpack 3.6. The v4 branch will get it soon enough (later today).

Cheers!

**Comment by tabacitu** [comment]
Haha. Smooth :-) 

Yes, you can go back to it looking like CoreUI (sidebar and header) by changing two config values in ```config/backpack/base.php```:
```diff
    // Horizontal navbar classes. Helps make the admin panel look similar to your project's design.
-    'header_class' => 'app-header bg-transparent border-0 navbar position-relative',
+    'header_class' => 'app-header border-0 navbar position-relative',

    // Sidebar element classes.
-    'sidebar_class' => 'sidebar sidebar-pills sidebar-bg-transparent',
+    'sidebar_class' => 'sidebar',
```

The success/error/warning/info colors will still be Backstrap, though - we tweaked those a little bit. and how the inputs look. But I don't think those will be the thing people have a problem with, but the transparent sidebar and header. Which is... better in my opinion. Since it helps the design draw attention to the content, not the menus. But it's opinionated nonetheless, so expect plently of people will want to change it :-)

**Comment by martijnb92** [comment]
> I am having similar issues when installing the v4 beta on a clean install of laravel 6 running php 7.2. My packages folder looks like the one above.
> 
> The source code shows there are still css files and javascript files trying to be pulled from vendor/adminlte This is what my page looks like:
> 
> <img alt="Screen Shot 2019-09-12 at 5 26 37 AM" width="841" src="https://user-images.githubusercontent.com/106914/64780628-1fc12e80-d51e-11e9-91af-435850f04df8.png">
> 
> <img alt="Screen Shot 2019-09-12 at 5 34 36 AM" width="1493" src="https://user-images.githubusercontent.com/106914/64781013-16849180-d51f-11e9-8d82-c1b97a879f69.png">

Experiencing the same (looks exactly like this screenshot). Tried upgrading 3.6 to 4 using the upgrade guide. AdminLTE is installed by composer for some reason. HTML looks like a hybrid 3.6/4 and I have no custom views.

**Comment by tabacitu** [comment]
@martijnb92 that's great! (that we can debug this now; not that you're having problems 😄  )

How about after a ```php artisan view:clear``` and ```php artisan cache:clear``` ?

**Comment by martijnb92** [comment]
Unfortunately that did not change anything. Also tried removing the whole vendor folder. Maybe it has something to do with de base/crud merge? backpack/base is also being installed by composer. Lastly I tried `php artisan backpack:install` but that didn’t help either, except that I got two new blade topbar left/right files.

**Comment by tabacitu** [comment]
Hmm.... can I please see your ```composer.json``` file?

**Comment by martijnb92** [comment]
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "backpack/crud": "v4.x-dev",
        "barryvdh/laravel-dompdf": "^0.8.4",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "backpack/generators": "^1.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laracasts/generators": "dev-master",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --provider='Backpack\\CRUD\\BackpackServiceProvider' --tag=public --force"
        ]
    }
}

**Comment by martijnb92** [comment]
"backpack/generators": "^1.2"
Appears to be causing the trouble! :)

**Comment by tabacitu** [comment]
Exactly! Thanks a lot this back-and-forth @martijnb92 . I've updated the upgrade guide to mention that you also need ```"backpack/generators": "^2.0"``` in require-dev.

Cheers!

**Comment by tabacitu** [comment]
@tomsb just added more docs for changing the top menu and sidebar colors, for a different look & feel. Ended up documenting [a few good examples too, with screenshots](https://backpackforlaravel.com/docs/4.0/base-how-to#customizing-the-design-of-the-menu-sidebar-footer).

**Comment by vesper8** [comment]
I just stumbled on this issue as well.. I did not realize Backpack 4 was still in Beta since there seems to be no obvious indication of this anywhere. Maybe I'm just blind but the only place I even see 'beta' is as part of these instructions 

```
# Note during v4 beta - this might NOT have v4 support yet
composer require webfactor/laravel-generators --dev
```

Which lead to an error

@tabacitu Why not remove this line of instructions altogether since it just doesn't work at the moment?

**Comment by vesper8** [comment]
Note that using `"webfactor/laravel-generators": "dev-master"` works as a result of https://github.com/webfactor/laravel-generators/commit/e325b434b8e199539ab1635fabbd85ee632037f3, so the instructions should be changed to 

```
composer require webfactor/laravel-generators:dev-master --dev
```

**Comment by tabacitu** [comment]
@vesper8 v4 is not in beta right now - it's stable. Just forgot that notice since it _was_ in beta (the beta docs have become the v4 docs). I've removed them like you suggested, you're right.

As far as I know, ```webfactor/laravel-generators``` does provide V4 support on dev-master, but the controllers aren't updated for v4, I'll make sure to spend some time and help the guys upgrade too. I do plan to improve how we generate things A LOT in the coming months.
