### ISSUE TITLE
[4.1][Feature] Remove all possible dependencies

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2025]
Currently it's difficult to provide support for new Laravel versions because dependencies are slow to upgrade. While people who use those dependencies have to wait, not everybody does.

We should remove feature dependencies, and isolate those features into separate packages, that are installed only by the Backpack users who want those features.

For example:
- ```spatie/laravel-translatable``` - not everybody uses it
- ```venturecraft/revisionable``` - not everybody uses it
- ```intervention/image``` - I'd have to check, but I don't think we're using it anywhere

**Comment by ziming** [comment]
I think dependencies that has a great track record of being regularly updated can remain.

**Comment by tabacitu** [comment]
In fact:
- ```spatie/laravel-translatable``` is not a dependency - we instruct people to install it when they want to use multi-language CRUDs. So we're good on that;
- ```venturecraft/revisionable``` - we have https://github.com/Laravel-Backpack/CRUD/issues/2430 which talks about separating this into its own operation;
-  ```intervention/image``` has never caused problems, but we could remove it as a dependency, issue here - https://github.com/Laravel-Backpack/CRUD/issues/2538
- ```laravel/helpers``` has been removed with PR https://github.com/Laravel-Backpack/CRUD/pull/2521

Since we have individual issues for each problem here, let's close this one.
