### ISSUE TITLE
Does not redirect with error

### ISSUE THREAD

**Issue by RamiMustaklem** [Laravel-Backpack/CRUD#204]
$errors are always returned empty in form_content.blade.php when redirected back.

**Comment by tabacitu** [comment]
It's possible that the "web" middleware is registered twice - known Laravel issue.

Check your routes file - if it's in web.php, you shouldn't specify the web middleware anymore.

**Comment by RamiMustaklem** [comment]
Yes sir that is exactly the issue. 2 web middlewares.
@tabacitu you're awesome.
