### ISSUE TITLE
404 Page not found.  for "Employee" CRUD

### ISSUE THREAD

**Issue by UncleCom** [Laravel-Backpack/CRUD#205]
I've created a full CRUD for "Employee" and add this Route:
"CRUD::resource('Employee', 'EmployeeController');"
To web.php.and added it to Sidebar,When I click "Manage Employees" it results me this error:
Error:"404
Page not found.
Please return to our homepage."

**Comment by tabacitu** [comment]
Are you sure it's called EmployeeController and not EmployeeCrudController? If you've generated it using [the generators package](https://laravel-backpack.readme.io/docs/crud-example#doing-it-all-very-fast) that's what it should be called.

Also, please check if your route is inside the "Admin" namespace closure, if your controller is in ```App\Http\Controllers\Admin\```.

Cheers!

**Comment by UncleCom** [comment]
I checked and modified it to 'EmployeeCrudController' but still same error. Am I missing something?
Side note:I used backpack with laravel 5.2 (months ago), and the generator was  working smoothly the same way I did with 5.3 project.  ( I don't want to use something outdated if possible)

**Comment by UncleCom** [comment]
Notation: Try to do the steps in 5.2 installation, there are many commands that doesn't work anymore. it's almost unusable..
Error#1(in 3.1 after excuting composer require backpack/crud ):
long error on comptiblity. 
Solution#1:(2.0.X need to be added at the end of the command)

Error#2 (in 3.3 after excuting php..elfinder:publish):
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "elfinder" namespace.
 Solution#2: None..

**Comment by tabacitu** [comment]
Hi @UncleCom ,

If backpack/base 0.6.x has been installed on a Laravel 5.2 instance, the CRUD installation should go fine (no need for specifying 2.0.x). You should [follow the steps in the 5.2 installation guide](https://laravel-backpack.readme.io/docs/installation).

That being said, the Laravel 5.2 version should work out of the box, but it's deprecated and I can no longer help out with it. My recommendation is to upgrade to Laravel 5.3 and latest backpack, if you can. Any small-medium app can be upgraded in 1 hour and you'd have all the new features of both laravel and backpack.

If you're still having this issue, try [posting on stackoverflow with the backpack-for-laravel tag](http://stackoverflow.com/questions/tagged/backpack-for-laravel). Someone there could still run L5.2 instances and may be able to help.

Cheers!
