### ISSUE TITLE
[4.1][Bug] In CoreUI sidebar dropdowns, click on list item span or icon doesn't trigger dropdown

### ISSUE THREAD

**Issue by Mu9tafa-Online** [Laravel-Backpack/CRUD#2055]
# Bug report
**Click On list item doesn't toggle menu, but arrow does!**
See Image Below
.
![back](https://user-images.githubusercontent.com/5323832/64924399-9d1dc500-d7e4-11e9-89d8-487f83bc1528.jpg)

.
Backabck 4.0, Laravel 6.0, PHP 7.2.0, MySQL 5.7

**Comment by tabacitu** [comment]
Hmm... that's weird. It seems to be working for me @Mu9tafa-Online :

![2019-09-17 10 43 57](https://user-images.githubusercontent.com/1032474/65021593-1da10a80-d938-11e9-9a27-2b5df36f21f4.gif)


Maybe it's been fixed between you installing Backpack v4 and now? Try a ```composer update``` please and let me know if that fixes it for you ;-)

**Comment by Mu9tafa-Online** [comment]
@tabacitu - It doesn't work when you click on the **text it self**!
Try Clicking on the word "News" for example (which is inside **span** tag).

**Comment by tabacitu** [comment]
Oh right! True, just tried it myself. **If the text is within a ```span```, the click won't trigger the dropdown**. Looks like I haven't migrated the HTML structure of the CoreUI dropdowns doesn't like spans. I think there's an easy solution and a difficult solution:

**(1) Remove the spans**. I've just done so for the Backpack v4 demo, and will go through the docs to make sure we don't have spans.

**(2) Overwrite the CoreUI JS to also trigger the dropdown on span click**. I don't really like this one tbh. Would require us to maintain it something that's almost identical.

**(3) Create a PR for CoreUI to support span click**. Response time tends to be very very long though. So I'd rather just do solution 1 for now.

Thanks for raising the issue.
Cheers!

**Comment by Mu9tafa-Online** [comment]
Just Go With Solution 1

**Comment by tabacitu** [comment]
On second thought. Maybe ```span``` is not a big issue. But clicking on the icon doesn't trigger the dropdown either. Which is really annoying to me now that I know of it :-)

I think long-term we should do solution 3 - and help CoreUI on this one. So let's reopen it.

**Comment by tabacitu** [comment]
Just tested this again - and it now works. In Backpack 4.1 clicking on the arrow toggles the submenu just fine. Honestly I don't remember when we did anything to fix this - maybe it was us, maybe it was CoreUI, but what matters is that it's now fixed 😄 🥳 

Closing the issue. Cheers!
