### ISSUE TITLE
[3.6][Bug] type auto-set for "tinyint" is "active" which is not a existed type

### ISSUE THREAD

**Issue by fzhantw** [Laravel-Backpack/CRUD#2057]
# Bug report

### What I did:
I have a column which type is tinyint(boolean),
And I use auto-set on CrudController

### What I expected to happen:
The column should be treat as checkbox

### What happened:
The type of this column is active, which is not existed on current version.

### What I've already tried to fix it:
Edit "AutoSet.php", replace "active" to checkbox 

### Backpack, Laravel, PHP, DB version:
Backpack 3.6.31
Laravel 5.8
PHP 7.3.9
MySQL 5.7.24

**Comment by tabacitu** [comment]
Totally! Thank you @fzhantw , details inside your PR.
