### ISSUE TITLE
This is in tag 3.6.28 😞

### ISSUE THREAD

**Issue by pestopancake** [Laravel-Backpack/CRUD#2066]
https://github.com/Laravel-Backpack/CRUD/blob/fa0dc8296198739389f70278ac7b5ca7eb197637/src/resources/views/fields/select2_from_array.blade.php#L3

**Comment by tabacitu** [comment]
Indeed, sorry for that @pestopancake , it's been removed in 3.6.29 . Run a ```composer update``` - should fix it for you along with a few more stuff.

Cheers!
