### ISSUE TITLE
[4.1][Feature Request] CRUD Field Type

### ISSUE THREAD

**Issue by axelzuzek** [Laravel-Backpack/CRUD#2070]
Is or will there be a way in 3.6 or 4.* to edit fields of a related model in the edit view?

In other words: the current table field as user interface, but the data is saved in a related model instead of json.

(Back in the days Symfony 1 Admin Generator could do this:
```
class ArticleForm  {
...
$pricePerGroup = new Object...
$subForm = new PricePerGroupForm($pricePerGroup);
$this->embedForm('pricePerGroup', $subForm);
```)

**Comment by tabacitu** [comment]
Hi @axelzuzek ,

Yes, we do plan to do this in v4. We call it a "crud" field type. You just point to a different CrudController, and a table will show up inside Edit.

No progress so far. Let's leave this issue open until we make progress.

**Comment by samuk190** [comment]
> Hi @axelzuzek ,
> 
> Yes, we do plan to do this in v4. We call it a "crud" field type. You just point to a different CrudController, and a table will show up inside Edit.
> 
> No progress so far. Let's leave this issue open until we make progress.

it wont be easier if you just pull from the instant field extension and just fix the compatibility? its everything done already :)

**Comment by tabacitu** [comment]
The new ```relationship``` field in 4.1 should fix this nicely https://github.com/Laravel-Backpack/CRUD/pull/2311 - let me know if it doesn't and we'll reopen and clarify.

But just to tease, here's quick preview of the relationship field in action:
![2020-03-23 08 56 45](https://user-images.githubusercontent.com/1032474/77290235-6e792d80-6ce4-11ea-92d3-f230f9d9c975.gif)
