### ISSUE TITLE
[4.0] Filters: Issue With First Item In Filter Select!

### ISSUE THREAD

**Issue by Mu9tafa-Online** [Laravel-Backpack/CRUD#2071]
# Bug report
When I'm trying to choose the first item in filter select menu it just don't work as expected.
you can click on the second, third ones ..etc but not the first item

### What I expected to happen:
It should work fine
...
See Image Below
....
![Opera Snapshot_2019-09-19_130431_back-demo test](https://user-images.githubusercontent.com/5323832/65239054-64306980-dade-11e9-995e-3547b551177c.png)

**Comment by tabacitu** [comment]
Right! Thank you @Mu9tafa-Online , just pushed a fix for it (and a few other select2 filter quirks). You can get it with ```composer update```.

Cheers!
