### ISSUE TITLE
[4.0][BUG] Custom style in custom widget not working

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/CRUD#2074]
# Bug report

### What I did:
Created a custom style for custom widget in the dashboard by following the docs in [https://backpackforlaravel.com/docs/4.0/base-widgets#creating-a-custom-widget-type](https://backpackforlaravel.com/docs/4.0/base-widgets#creating-a-custom-widget-type).

### What I expected to happen:
According to the docs, I could include custom CSS and JS, by pushing to the stacks in the layout using `@push('after_styles')`.

### What happened:
I find out that `@push('after_styles')` is not working. The custom style/CSS is not included in the dashboard. On the other hand,  `@push('after_scripts')` works totally find and is included in the dashboard.

### Backpack, Laravel, PHP, DB version:
Backpack v4 Beta
PHP 7.2

**Comment by drionix** [comment]
I found out the cause. In the `top_left.blade.php` layout, `@stack('before_styles')` and `@stack('after_styles')`, which is located in `head.blade.php` layout, is rendered before `@push('before_styles')` and `@push('after_styles')`.

However, laravel does not allow `@stack` to appear before `@push`. 

To be clear, this is `top_left.blade.php` layout structure:
```
<head>
  @include(backpack_view('inc.head')) ##### @stack('after_styles') is located here
</head>

<body class="{{ config('backpack.base.body_class') }}">

  @include(backpack_view('inc.main_header'))

  <div class="app-body">

    ...
          
          @if (isset($widgets['before_content']))
            @include(backpack_view('inc.widgets'), [ 'widgets' => $widgets['before_content'] ]) ##### @push('after_styles') is located here
          @endif
          
   
    ...
```

@tabacitu I think custom widget style should be implemented in another way

**Comment by tabacitu** [comment]
Hi @drionix ,

You're right, of course... Thanks for bringing this up. I just tested and can confirm - using the ```after_styles``` stack inside widgets doesn't work. I remember facing this problem in fields too - and we did find a solution. There are a number of fields that load their CSS inside ```<head>```. I just can't put my finger on the solution :-) I'll take another look tomorrow, maybe a fresh perspective will help.

Until we figure this out, please push your styles to the ```after_scripts``` stack. That should work fine, right?

Cheers!

**Comment by drionix** [comment]
Any updates with this issue?

By the way, after some thoughts, I don't think that `@push('after_styles')` is suitable to be included in custom field blade file. I just realized that the current implementation caused everything inside `@push('after_styles')` to be duplicated for as many times as the number of the custom widget used. 

For example, if I created a 'fancy card' widget with some custom style in it and included 4 'fancy card' widgets in the dashboard, then the custom style inside `@push('after_styles')` is duplicated 4 times.

As I previously suggested, maybe the custom styling could be separated from the custom widget file itself, such as "fancycard.blade.php" and "fancycard_style.blade.php" to solve both of these problems (`@push('after_styles')` not working and `@push('after_styles')` duplication)

**Comment by pxpm** [comment]
@tabacitu is this a `$widget->markWidgetTypeAsLoaded()` problem ? If that's the case, widget must be structured like fields with js init functions etc right ? Is this something we aim to pursue ?

Best,
Pedro

**Comment by tabacitu** [comment]
![https://media.giphy.com/media/3o7abA4a0QCXtSxGN2/giphy.gif](https://media.giphy.com/media/3o7abA4a0QCXtSxGN2/giphy.gif)

We finally have a fix for this issue. And AFAIK it's non-breaking. So I'll be merging it into 4.0 ASAP. Let me know what you think - https://github.com/Laravel-Backpack/CRUD/pull/2592

Cheers!
