### ISSUE TITLE
[4.0][BUG] Two select2_multiple filters not working together

### ISSUE THREAD

**Issue by martijnb92** [Laravel-Backpack/CRUD#2075]
# Bug report

### What I did:
Upgraded Backpack 3.6 to 4, my 3.6 installation had multiple 'select2_multiple' filters working fine on one page.
`$this->crud->addFilter([
            'name' => 'demo1',
            'type' => 'select2_multiple',
            'label'=> 'Demo1'
        ],
 $this->crud->addFilter([
            'name' => 'demo2',
            'type' => 'select2_multiple',
            'label'=> 'Demo2'
        ]`

On 3.6 this worked fine. In v4 the filter that is applied is like ?demo1=%5B"1"%5D&demo2=%5B"1"%5D when I select either demo1 or demo2.
### What I expected to happen:
When is select an option from demo1 I expect that the filter is only applied to demo1.
e.g. "?demo1=%5B"1"%5D"

### What happened:
The option that I select for demo1 is also applied to demo2
?demo1=%5B"1"%5D&demo2=%5B"1"%5D, manually changing the url by removing the demo2 parameter filter gives my the expected behavior.

Additionally clicking "remove filters" is really slow, it first sends 9 search requests to the server.
### Backpack, Laravel, PHP, DB version:
v4-dev, 6.0.3, 7.3.9

**Comment by Athuli7** [comment]
Setting `persistentTable` to `false` in `config/backpack/crud.php` helps but at the cost of that feature.

**Comment by martijnb92** [comment]
> Setting `persistentTable` to `false` in `config/backpack/crud.php` helps but at the cost of that feature.

Unfortunately that does not help, still the same behavior.

**Comment by GregaUNK** [comment]
I got the same problem.

**Comment by misiekch** [comment]
Me too. In addition "remove filters" button hangs the browser due to many requests.

**Comment by misiekch** [comment]
There is a glitch in select2_multiple blade code. It can be solved by adding the following line 

`if (filterName !== parameter) { return; }`

right after

`var parameter = '{{ $filter->name }}';`

in the resources/views/crud/filters/select2_multiple.blade.php

**Comment by prodixx** [comment]
Is there any solution for 3.5.0?

**Comment by tabacitu** [comment]
@prodixx no, sorry - 3.5 is no longer supported. But I don't think these particular files have changed much between 3.5 and 4.0. So you should be able to copy-paste the files from your ```vendor/backpack/crud/src/filters``` to your ```resources/views/vendor/backpack/crud/filters``` and make [these changes](https://github.com/Laravel-Backpack/CRUD/commit/ecf1a6764ec81100e5f6596a731043187a9a8811), they're pretty small. That should do it for you.
