### ISSUE TITLE
[4.0] Still looking at backpack/base package version

### ISSUE THREAD

**Issue by onkbear** [Laravel-Backpack/CRUD#2083]
# Bug report

### What happened:

Following source code is still looking at `backpack/base` package version.
So, I am getting an error if it hits one-hundredth and in production environment.

### What I've already tried to fix it:

src/Stats.php

``` diff
            'LARAVEL_VERSION'       => $this->app->version() ?? false,
-            'BACKPACK_BASE_VERSION' => \PackageVersions\Versions::getVersion('backpack/base') ?? false,
            'BACKPACK_CRUD_VERSION' => \PackageVersions\Versions::getVersion('backpack/crud') ?? false,
```

### Backpack, Laravel, PHP, DB version:

backpack/crud: master
laravel/framework: 6.0.4
PHP: 7.3.10

Thanks,

**Comment by tabacitu** [comment]
Ouch! Thanks for reporting this @onkbear ! Fixed, a ```composer update``` to 4.0.2 should fix it for you.

Cheers!
