### ISSUE TITLE
[4.0.1] More documentation for Upload Multiple in docs

### ISSUE THREAD

**Issue by zachweix** [Laravel-Backpack/CRUD#2085]
# Feature Request

### What I did:
I searched for how to set temporary URL's in upload multiple, when there are already files uploaded in S3.
### What I expected to happen:
The documentation at https://backpackforlaravel.com/docs/4.0/crud-fields#upload_multiple should tell me how I can do so.
### What happened:
There was nothing in the documentation on how to do so
### What I've already tried to fix it:
I looked in the code to see if there was a way, and I saw that you can set an integer value called "temporary" to create a temporary link. Can you please add that functionality to the documentation?
### Backpack, Laravel, PHP, DB version:
Backpack 4.0.1, Laravel 6.0

**Comment by tabacitu** [comment]
Sorry for the lack of documentation, and thank you for fixing that yourself @zachweix !
