### ISSUE TITLE
Cannot redeclare maximumServerUploadSizeInBytes()

### ISSUE THREAD

**Issue by sklazer** [Laravel-Backpack/CRUD#2086]
# Bug report

### What I did:
Added two or more "image" fields 

### What I expected to happen:
Proper page render

### What happened:
Cannot redeclare maximumServerUploadSizeInBytes() (previously declared in ....

### Backpack, Laravel, PHP, DB version:
Backpack 4, Laravel 6.0.3

**Comment by sklazer** [comment]
PR created: https://github.com/Laravel-Backpack/CRUD/pull/2087

**Comment by tabacitu** [comment]
Thanks again for the PR! Merged. It'll be available later today as ```4.0.2```, after I merge a few more bug fixes.
