### ISSUE TITLE
[4.0] [Bug] Relation property in text column not working

### ISSUE THREAD

**Issue by jsvini** [Laravel-Backpack/CRUD#2088]
# Bug report

### What I did:
Add a text column where the name is a relation 1-1 property in dot notation.
```php
$this->crud->addColumn([
    'name'  => 'unit.name',
    'label' => 'Unit name',
    'type' => 'text',
]);
```
### What I expected to happen:
Show the relation property in the Unit name column.

### What happened:
`Facade\Ignition\Exceptions\ViewException
Undefined index: orderable (View: .../vendor/backpack/crud/src/resources/views/crud/list.blade.php)`

### What I've already tried to fix it:
What I cant tell is that when I use dot notation in the column name, the `$column` array in `list.blade.php` doesn't have the `orderable` key:

https://github.com/Laravel-Backpack/CRUD/blob/4.0.0/src/resources/views/crud/list.blade.php#L57

See below the values of `$column` in the `list.blade.php` when:

The column name doesn't have dot notation ( name = 'name' ):
![image](https://user-images.githubusercontent.com/4185886/65797024-882a2580-e144-11e9-9e7e-a3eabad9339f.png)

The column have dot notation ( name = 'unit.name' ):
![image](https://user-images.githubusercontent.com/4185886/65797116-c9bad080-e144-11e9-947c-6a3055d641c9.png)

### Backpack, Laravel, PHP, DB version:
"php": "7.2",
"backpack/crud": "4.0",
"laravel/framework": "6.0",
and MySQL 8

**Comment by tabacitu** [comment]
Ouch! You're totally right @jsvini . Thanks a lot for raising such a detailed issue. Indeed,  because operation settings are now stored using a dot notation, there was a confict. It's now fixed, please do a ```composer update``` and make sure you get 4.0.3 or higher, where it's fixed. I'll be tagging it in a little while after I push a few more fixes.

Cheers!
