### ISSUE TITLE
Mix of models

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#209]
Hey,

Let's say i have five models and i would like to get an array/collection containing latest 50 objects from each model sorted by date.

My first approach would be to get arrays of each group of 50 objects, concatenate them, then sort final array and finally get the first x objects from that array.

How would you do that easier (is there an easier way)?

**Comment by tabacitu** [comment]
I don't think there's another way... you could use collect() on the array to turn it into a collection and sort it mkre easily, though...

**Comment by AurelDragut** [comment]
Yeah, thanks!

**Comment by AurelDragut** [comment]
I did this but i would need a tip on how to add model information to the collection or how can i read it (at least the model name of every object)

```
class PagesController extends Controller
{
    public function index() {
        $dir = app_path('Models');
        $files = scandir($dir);

        $models = array();
        $namespace = 'App\Models\ ';
        foreach($files as $file) {
            //skip current and parent folder entries and non-php files
            if (strpos($file,'.php') === false) {
                continue;
            } else {
                $models[] = substr($namespace, 0, -1) . substr($file, 0, -4);
            }
        }
        $collection = collect();
        foreach ($models as $model) {
            $collection = $collection->merge($model::all());
        }
        return view('index', compact('collection'));
    }
}
```
