### ISSUE TITLE
Field image

### ISSUE THREAD

**Issue by mabilbao** [Laravel-Backpack/CRUD#210]
Hey Guys!

I am starting to use Backpack CRUD and I have a problem for maintain the image fields when I use the laravel validation in a request.

For example:
I have two field:
- `name` --> type: text
- `photo` --> type: image

`name` is required but suppose that I only completed the photo and press save.
The form shows the error message ('name is required') but the field photo is empty.

Do you have some idea for fix this? For now, my only idea is extend `edit.blade.php` and add the validations by javascript only for this CRUD.

Thanks and the tool is very util!

**Comment by tabacitu** [comment]
Unfortunately there's no way to prefill the image (basically upload/upload_multiple) after refresh. It's a HTML5 limitation.

But what you CAN do, even though it's a little ugly, is add the html5 attribute "required" to it. That should run a html5 validation to it, before rhe form is submitted.

"Attributes" => [
  "Required" => "required"
]

On both name and image.

Does that work for you?

**Comment by OwenMelbz** [comment]
Tidying up the place :) Feel free to re-open if you still need help
