### ISSUE TITLE
(1/1) FatalErrorExceptionTrait 'Backpack\CRUD\CrudTrait' not found

### ISSUE THREAD

**Issue by edwardleoni** [Laravel-Backpack/CRUD#2100]
# Bug report

### What I did

Upgraded from 3.4 to 4.0

### What happened

```

(1/1) FatalErrorExceptionTrait 'Backpack\CRUD\CrudTrait' not found
--
in User.php line 14

```

**Comment by tabacitu** [comment]
Hi @edwardleoni . 

Indeed you should **replace Backpack\CRUD\CrudTrait with Backpack\CRUD\app\Models\Traits\CrudTrait**, like it says in [step 1 in the upgrade guide](https://backpackforlaravel.com/docs/4.0/upgrade-guide#models).

But please note that if you're upgrading from 3.4 to 4, you need to pass through two more upgrade guides, before you do this one:
- [3.4 to 3.5](https://backpackforlaravel.com/docs/3.5/upgrade-guide)
- [3.5 to 3.6](https://backpackforlaravel.com/docs/3.6/upgrade-guide) (this is minor)
- only afterwards [3.6 to 4.0](https://backpackforlaravel.com/docs/4.0/upgrade-guide)

Cheers!
