### ISSUE TITLE
laravel backpack table type set columns browse_multiple?

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/CRUD#2105]
# Bug report

### What I did
laravel backpack table type set columns browse_multiple type?

```php
$this->crud->addField([
			'name' => 'content',
           
            'type' => 'table',
            'label' => 'Option',
            'entity_singular' => 'option', // used on the "Add X" button
            'columns' => [
                [
                    'name'     => 'image_url',
                    'label' => 'Image URL',
                    'type'=> 'browse'
                ],
                [
                    'name'     => 'group',
                    'label' => 'Gallery ID',
                    'type'=> 'text'
                ],
            ],
            'max' => 5, // maximum rows allowed in the table
            'min' => 0, // minimum rows allowed in the table
              'tab' => 'Content'
			  
          ]);
```

??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version
BP4.0
L6.0
PHP7.2
When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
I'm afraid I don't understand your problem. Can you please rephrase / give more details?

**Comment by gumpon** [comment]
I want to add fields have 2 column 
first column use browse field type
second column use text filed type

**Comment by tabacitu** [comment]
Ah, I understand now. The table field does not allow for that. We'll soon be launching a different field (currently called "multiply" but will probably named "repeatable" in production) that can do that. Working on testing and docs for it. 

But the gist of it is:
```php
		[
			'name' => 'entries',
			'label' => 'Entries',
			'type' => 'multiply',
			'fields' => [
				[
					'name' => 'number',
					'label' => 'Number',
					'type' => 'number',
					'wrapperAttributes' => [
		               'class' => 'form-group col-md-2'
		             ],
				],
				[
					'name' => 'title',
					'label' => 'Title',
					'type' => 'text',
					'wrapperAttributes' => [
		               'class' => 'form-group col-md-4'
		             ],
				],
				[
					'name' => 'description',
					'label' => 'Description',
					'type' => 'textarea',
					'wrapperAttributes' => [
		               'class' => 'form-group col-md-6'
		             ],
				],
			],
		],
```

If you're running on Backpack v4, you should already have it in your project, but it's undocumented, and might suffer some changes upon launch.

Hope it helps.
Cheers!

**Comment by sandeepchowdary7** [comment]
@tabacitu I'm using Backpack Version-4 I'm trying to use `type => multiply` somehow I'm getting this err 
```
View [fields.multiply] not found.
```
Do you have any idea why I'm getting this err. Is not yet existed in the latest version? Thanks in Advance

**Comment by tabacitu** [comment]
@sandeepchowdary7 that was just an example of the upcoming syntax. We didn't actually add the multiply field (as hidden and undocumented) like I said above - it had quite a few bugs.

The multiply field is something we've been working on for a long long time but it's not yet launched. I've pushed a PR here https://github.com/Laravel-Backpack/CRUD/pull/2266 for it, and I've been actively working on it for the past 1-2 weeks, trying to resolve all issues. I expect it to be ready in a few weeks - but then again none of my Backpack estimates have been correct :smile: . It's now called "repeatable" btw. Take a look there.

Cheers!
