### ISSUE TITLE
Error upgrading 3.6 to 4.0

### ISSUE THREAD

**Issue by jfelixoptimiumnc** [Laravel-Backpack/CRUD#2121]
Hi all,

I got the following error upgrading from 3.6 to 4.0:

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)

Package operations: 3 installs, 1 update, 3 removals
  - Removing composer/installers (v1.7.0)
  - Removing backpack/base (1.1.13)
  - Removing almasaeed2010/adminlte (v2.4.3)
  - Updating backpack/generators (1.2.7 => 2.0.4): Downloading (100%)
  - Installing spatie/laravel-permission (3.0): Downloading (100%)
  - Installing backpack/permissionmanager (5.0.0): Downloading (100%)
  - Installing backpack/langfilemanager (dev-master 130dc7c): Downloading (100%)
Writing lock file
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   BadMethodCallException  : Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::resource does not exist.

  at /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:104
    100|      */
    101|     public function __call($method, $parameters)
    102|     {
    103|         if (! static::hasMacro($method)) {
  > 104|             throw new BadMethodCallException(sprintf(
    105|                 'Method %s::%s does not exist.', static::class, $method
    106|             ));
    107|         }
    108|

  Exception trace:

  1   Backpack\CRUD\app\Library\CrudPanel\CrudPanel::__call("resource")
      /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:239

  2   Illuminate\Support\Facades\Facade::__callStatic("resource")
      /home/vagrant/code/routes/backpack/custom.php:18

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Thx for your work and help.

Regards.

Jerome

**Comment by tabacitu** [comment]
Hmm that's odd. What if you do [steps 2.0, 2.1 and 2.2 from the upgrade guide](https://backpackforlaravel.com/docs/4.0/upgrade-guide#routes) first?

**Comment by Uteev** [comment]
Hello! Just got exactly the same error while updating Backpack from 3.6 to 4.0.  I will try to do steps 2.0, 2.1 and 2.2 first and then update. I'll update on the results.

**Comment by Uteev** [comment]
I did steps 2.0, 2.1 and 2.2 and after this run again composer update and it seems it worked out.

**Comment by jfelixoptimiumnc** [comment]
Hi all,

I think I've done the steps  2.0, 2.1 and 2.2 ok but the error is the same.

Any idea ?

BR 

Jerome

**Comment by tabacitu** [comment]
@jfelixoptimiumnc hmm maybe your have the old CRUD manually class registered in your providers? in you ```config/app.php```? Otherwise please copy-paste the error.

**Comment by jfelixoptimiumnc** [comment]
Hi,

Here is the error:

composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   BadMethodCallException  : Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::resource does not exist.

  at /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:104
    100|      */
    101|     public function __call($method, $parameters)
    102|     {
    103|         if (! static::hasMacro($method)) {
  > 104|             throw new BadMethodCallException(sprintf(
    105|                 'Method %s::%s does not exist.', static::class, $method
    106|             ));
    107|         }
    108|

  Exception trace:

  1   Backpack\CRUD\app\Library\CrudPanel\CrudPanel::__call("resource")
      /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:239

  2   Illuminate\Support\Facades\Facade::__callStatic("resource")
      /home/vagrant/code/routes/backpack/permissionmanager.php:18

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Thx 
Jerome

**Comment by adampogany** [comment]
@jfelixoptimiumnc you need to replace CRUD::resource with Route::crud in your routes\backpack\permissionmanager.php file also (see line 2 of exception trace for the source of error).

**Comment by jfelixoptimiumnc** [comment]
Indeed, just found my error in parallel.

Thanks for your help.

Jerome

**Comment by QusaiFarraj** [comment]
If you still have issues with `composer dump-autoload -o`, try to clear your cached routes. `php artisan route:clear`
