### ISSUE TITLE
Filter for CRUD (DateRange) not working

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2125]
$this->crud->addFilter([ // daterange filter
           'type' => 'date_range',
           'name' => 'created_at',
           'label'=> 'Date range'
         ],
         false,
         function($value) { // if the filter is active, apply these constraints
            $dates = json_decode($value);
            $this->crud->addClause('where', 'date', '>=', $dates->from);
            $this->crud->addClause('where', 'date', '<=', $dates->to . ' 23:59:59');
         });

I used this and uncommented the function. It says error, I'm trying to filter by created_at . Any clue?

**Comment by tabacitu** [comment]
@samuk190 out of curiosity - what was the issue? Cheers!
