### ISSUE TITLE
[4.1][Feature Request] Extend export functionality

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2127]
Im using the `$this->crud->enableExportButtons();` function to generate reports
I wonder if a method already exists or if a way to add a header or footer could be implemented. Currently I need to generate a report of the datatables with the great filters that backpack provides. But I need to add which user generated the report, page number, company name and other data. 
I did not find information in the documentation, github, gitter. Or someone who needs this same functionality. 
Thanks in advance

**Comment by johnpuddephatt** [comment]
My response to issue #2134 contains some information you might find useful. Though unfortunately customisation is not straightforward at the moment.
