### ISSUE TITLE
how filter entire project per company_id with backpack crud controller? 

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2128]
I made a foreign key for all tables -> company_id, and I want to filter by company id, but the company id is previously set(integer) when user is created by admin.
how to show all cruds, (users, permission manager permissions) per company_id? 

Example: I'm a user or admin(whatever) (which have special permissions) but my company_id is 1, so I can only see data that is linked with company_id 1

**Comment by tabacitu** [comment]
@samuk190 for important query changes like this I recommend you [global scopes](https://laravel.com/docs/6.x/eloquent#global-scopes) on models. This would not only make sure the CRUDs filter by company_id, but everything else inside your app. I think that's safer.

For the few places where you don't need the global scope (the superadmin), you can deactivate it.

Hope it helps.
Cheers!

**Comment by samuk190** [comment]
> @samuk190 for important query changes like this I recommend you use [global scopes](https://laravel.com/docs/6.x/eloquent#global-scopes) on models. This would not only make sure the CRUDs filter by company_id, but everything else inside your app. I think that's safer - there will be no way a User can get to something that doesn't belong to his company. If he tries to do so, he'll be greeted by a Not Found exception.
> 
> For the few places where you don't need the global scope (the superadmin), you can deactivate it.
> 
> Hope it helps.
> Cheers!

Thanks for your answer! this helped me alot!
