### ISSUE TITLE
[4.x] [Feature Request]  Allow the additional custom request merged in the CreateOperation and UpdateOperation

### ISSUE THREAD

**Issue by tsaiyihua** [Laravel-Backpack/CRUD#2131]
I has field setting for multiple selection via binary format.
It likes:

- selection A : 0001 as 1
- selection B : 0010 as  2
- selection C : 0100 as 4

if the filed value is 3, it means has both selection A and selection B.

so, in my CRUD controller, I will replace this request from array to string by sum of the value in the 3.x version.
but in 4.x, it cant not work anymore.

Could you allow the additional custom request merged in the CreateOperation and UpdateOperation?

**Comment by pxpm** [comment]
Hello @tsaiyihua 

Sorry for late reply.

Indeed some changes were made from v3 to v4, one of this is the way operations work.

You can [read here in backpack documentation](https://backpackforlaravel.com/docs/4.0/crud-operation-update#callbacks) how to add/remove data from your request.

I am going to close this, if you think i am wrong please re-open it.

Best,
Pedro
