### ISSUE TITLE
Connection Oracle Database with error

### ISSUE THREAD

**Issue by Ramaniks** [Laravel-Backpack/CRUD#2137]
# Bug report or not

### What I did

The Form Crud with connection to Oracle Database;

### What I expected to happen

Load the form crud.

### What happened

```
Error Code : 942 Error Message : ORA-00942: a tabela ou view não existe Position : 43 Statement : select column_name from information_schema.columns where table_schema = :p0 and table_name = :p1 Bindings : [public,tablename] (SQL: select column_name from information_schema.columns where table_schema = public and table_name = tablename)
```

### What I've already tried to fix it

The connection to oracle is working correctly. I made a normal loading screen and it works normal. When I come to Backpack this happens. Could it be any oracle permissions that the DBA should execute?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
[### PHP VERSION:]
PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

[### LARAVEL VERSION:]
You are running Composer with SSL/TLS protection disabled.

laravel/framework                       v6.1.0   The Laravel Framework.

[### BACKPACK VERSION:]
You are running Composer with SSL/TLS protection disabled.

backpack/crud                           4.0.7    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                     2.0.4    Generate files for laravel projects
backpack/logmanager                     3.0.0    An interface to preview, download and delete Laravel log files.
backpack/permissionmanager              5.0.1    Users and permissions management interface for Laravel 5 using Backpack CRUD.
```

**Comment by jsvini** [comment]
@Ramaniks Laravel doesn't support Oracle database.

Oracle doesn't provide the [`information_schema`](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Library/CrudPanel/Traits/Columns.php#L396) view that your query is looking for, maybe the custom db driver you are using is missing something. 

You can check the supported databases here:
https://laravel.com/docs/6.x/database#introduction

**Comment by Ramaniks** [comment]
@jsvini I use Oracle database very well with manual crud, not with backpack.

In Oracle there is no such table / view. And as it is not approved, you should not have a process in eloquent ORM to search for some information that Backpack needs and makes use of this query.
I will have to keep doing the CRUDs manually for these situations.

Thanks!

**Comment by Ramaniks** [comment]
Yes. Show all Columns, with this:
use Illuminate\Support\Facades\Schema;

In the Controller:
$table = Schema::Connection('NotDefaultConnection')->getColumnListing('MyTableOracle');
print_r($table);

The Backpack not search in another connection and not find in my Oracle Connection, but in my Postgres Connection, or not!

In my Model, add this:
protected $connection = 'NotDefaultConnection';

Sorry in the first moment, I am not watching this:
Oracle doesn't provide the [information_schema](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Library/CrudPanel/Traits/Columns.php#L396) view that your query is looking for, maybe the custom db driver you are using is missing something.

I am change this line, I am a noob:
$columns = $cache[$table] = $this->getSchema()->connection($this->getModel()->getConnection())->getColumnListing($table);

And show this:
Call to undefined method Illuminate\Database\Schema\PostgresBuilder::connection();

I better stop testing.

Thanks @jsvini

**Comment by tabacitu** [comment]
@Ramaniks to make sure I understand - does adding the ```$connection``` attribute to the model fix it for you?

**Comment by Ramaniks** [comment]
@tabacitu Not even adding $ connection to $ model solved. It seems that backpack core connects to Postgres to log in, it performs some functionality when loading data when I refer to another database, in this case Oracle.
Just could not yet understand a way to follow the flow of data to capture the moment that occurs that should pass the connection from Oracle and is passing the connection from Postgres and thereby generating the error in Schema. I will see to upload a Demo application only in Oracle to see if the same thing occurs.

**Comment by tabacitu** [comment]
Hmm I think @jsvini 's question was very relevant: **What DB driver are you using for your Laravel DB connection?** 

- What's in your ```.ENV``` as ```DB_CONNECTION```
- For that connection name, what does the configuration look like in ```config/database.php```, under ```connections```?

**Comment by tabacitu** [comment]
No answer in a long time, so I'm going to close this.

@Ramaniks if you managed to solve this, please post your solution here - I'm curious what it was, and I think it would be helpful to others too.

Cheers!
