### ISSUE TITLE
How to add relations in table fields?

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2139]
I'm trying to add a field which the main objective is to add a table with information.
but one of my informations is retrievable from another table through foreign key.

> https://prnt.sc/phi2qz
```

[ // Table
    'name' => 'options',
    'label' => 'Options',
    'type' => 'table',
    'entity_singular' => 'option', // used on the "Add X" button
    'columns' => [
//here is where I want to select name from another table
        'name' => 'Name',
        'desc' => 'Description',
        'price' => 'Price'
    ],
    'max' => 5, // maximum rows allowed in the table
    'min' => 0, // minimum rows allowed in the table
],
```

How I can add a select2(n-n) into column option into table field or something like that? it is possible?

**Comment by tabacitu** [comment]
Hi @samuk190 ,

No, you can't add relationship columns to the ```table``` field. Only text. We have a different field type for this, that we called ```matrix```, ```multiply``` or ```repeatable```, where you can add any type of Backpack field - but I'm afraid it isn't published yet, it still has a few quirks. Will probably launch it in 1-2 weeks.

Cheers!
