### ISSUE TITLE
[4.0.7][Possible bug][CoreUI] Missing .hidden styling for check.blade.php column

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/CRUD#2142]
# Bug report

### What I did

Include a check.blade.php column in ListOperation

### What I expected to happen

Shows only fa-check-circle or fa-circle icon

### What happened

It shows the icon with "Yes" or "No" text beside the icon, which based on `check.blade.php` column should be hidden. (Actually, it is also hidden in Backpack 3.6, where the `.hidden` style is included in bootstrap css)

### Possible solution

Add `.hidden` style to backpack/base/css/bundle.css or in other loaded css
```
.hidden {
    display: none!important;
}
```

### Backpack, Laravel, PHP, DB version
Backpack 4.0.7
Laravel 6.2
PHP 7.2

When I run ```php artisan backpack:version``` the output is:

**Comment by johnpuddephatt** [comment]
I'd suggest we switch the class to `.sr-only`; this is Bootstrap's suggested way of hiding things while retaining them for users of screenreaders.

**Comment by pxpm** [comment]
Hi @drionix 
Thanks for pointing this out. 

Also thank you @johnpuddephatt  for the solution. 

I have sent a PR #2218  to fix this issue. 

Please if you have something to add on this matter do it on the PR thread. I am going to close this one :)

Best,
Pedro
