### ISSUE TITLE
[4.0.9] [BUG] select2_multiple breaks with UUID

### ISSUE THREAD

**Issue by JasperSijgers** [Laravel-Backpack/CRUD#2149]
# Bug report

When using a related model with a UUID as primary key, and attempting to insert a select2_multiple field into a CRUD controller, an error comes up in the console and the field isn't displayed properly. The issue doesn't occur when using a regular ID (unsignedBigIncrements) as id. There are no issues creating models (of either type) or saving the relations. The select2_multiple field also appears normal when no results are found for the related model.

### Model
```
public function yearclubs()
{
    return $this->belongsToMany(Yearclub::class)->withTimestamps();
}
```

### Related model
Model:
```
protected $primaryKey = 'uuid';
public $incrementing = false;

public function users()
{
    return $this->belongsToMany(User::class)->withTimestamps();
}
```

Migration:
```
Schema::create('yearclubs', function (Blueprint $table) {
            $table->uuid('uuid')->primary();
            $table->string('name');
            $table->date('founding_date')
                ->default(now());
            $table->timestamps();
        });
```

### Crud controller
```
[
    'label' => "Yearclub",
    'type' => 'select2_multiple',
    'name' => 'yearclubs',
    'entity' => 'yearclubs',
    'attribute' => 'name',
    'model' => "App\Models\Groups\Yearclub",
    'pivot' => true,
    'tab' => 'Groups',
]
```

### Expected result
![](https://i.imgur.com/Ts06U2M.png)

### Actual result
![](https://i.imgur.com/oIb0wzK.png)

### Result without related models
![](https://i.imgur.com/GswU9C4.png)

### Error in console:
`Uncaught SyntaxError: Invalid or unexpected token edit:2708`

### Code
![](https://i.imgur.com/ISvQhvv.png)

### Versions
Backpack version 4.0.9
Laravel version 6.2.0
PHP version 7.3.4

**Comment by pxpm** [comment]
Hello @JasperSijgers 

I just don't want to let you without response as i have had no time to dig into this issue. I am sorry for that. 

Also i am not sure that this is the only field 'breackable' by changing default id. 

I will get back to it when possible.

Best,
Pedro

**Comment by pxpm** [comment]
@JasperSijgers 

Did a little look at here.

Have you tried also setting the `$keyType` in model ? I think by default laravel casts it to int. 

Best,
Pedro

**Comment by JasperSijgers** [comment]
> @JasperSijgers
> 
> Did a little look at here.
> 
> Have you tried also setting the `$keyType` in model ? I think by default laravel casts it to int.
> 
> Best,
> Pedro

Unfortunately that doesn't fix it, but it's probably good practice to set it anyways. Thanks for your suggestion!

**Comment by tabacitu** [comment]
@JasperSijgers thanks for letting us know. Excellent bug report, btw. 

I personally don't often use UUIDs in my projects - hence the omission. But I agree this _should_ be something Backpack works out-of-the-box with. We'll take a closer look.

Until we have this fixed, there's [a workaround here](https://github.com/Laravel-Backpack/CRUD/issues/1042) you could implement, basically manually loading the value inside the Update operation.

Cheers!

**Comment by tabacitu** [comment]
Update: I just pushed a fix for this, it'll be available with ```composer update``` later today, as 4.0.26.

It was just a matter of leaving out the quotes in JS. So when the key was integer, it worked. When it was a string, it didn't.
