### ISSUE TITLE
Ckeditor Options Issue

### ISSUE THREAD

**Issue by lhoucinecherif** [Laravel-Backpack/CRUD#2152]
# Bug report
Hi,
When I set options in CKeditor field, it doesn't show, there are a javascript error shown in the console window "Uncaught SyntaxError: Unexpected token ','"

### What I did

 $this->crud->addField([
            'name' => 'content',
            'label' => trans('backpack::pagemanager.content'),
            'type' => 'ckeditor',
            'options'=>['extraAllowedContent'=> 'div(*)' ],
            'placeholder' => trans('backpack::pagemanager.content_placeholder'),
        ]);

### What I expected to happen

Show Ckeditor loaded with options I've set

### What happened

An HTML Textarea shown instead of CKeditor

### What I've already tried to fix it

I've Overrided the Field, removed the last comma at line 44:
replaced this:
`"embed_provider": '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}',`
with this : 
`"embed_provider": '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}'`

### Backpack, Laravel, PHP, DB version
Backpack 4
Laravel 6.0
PHP 7.3

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.10 (cli) (built: Sep 24 2019 11:59:22) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.2.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.7      Quickly build an admin interfaces using Laravel 6, CoreUI, Bo...
backpack/generators                   2.0.4      Generate files for laravel projects
backpack/menucrud                     2.0.2      An admin panel for menu items, using Backpack\CRUD on Laravel 6.
backpack/pagemanager                  2.0.1      Create admin panels for presentation websites on Laravel, usi...
backpack/permissionmanager            5.0.1      Users and permissions management interface for Laravel 5 usin...
backpack/settings                     3.0.0      Application settings interface for Laravel 5 using Backpack C...

**Comment by drionix** [comment]
This issue is caused by double comma (,) in `ckeditor.blade.php` fields file.

I'll create a pull request in a moment.

**Comment by tabacitu** [comment]
Ugh. Don't you just hate it when one character messes up everything? Thank you for reporting this @lhoucinecherif , and fixing it @drionix ! Merging now.
