### ISSUE TITLE
Use value from field to manipulate another field.

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2158]
I dont know if this is a repeated question, but here we go:

I have two selects
 models -> state, city

how I can filter select2_->city  when I select state on select2_ -> state

Because if I choose a state this must show Only citys that it belongs
? 

Eg: State -> x -> select * from city where 'x'

**Comment by johnpuddephatt** [comment]
This how to on the website might help: https://backpackforlaravel.com/docs/4.0/crud-how-to#add-a-select2-field-that-depends-on-another-field

**Comment by samuk190** [comment]
> This how to on the website might help: https://backpackforlaravel.com/docs/4.0/crud-how-to#add-a-select2-field-that-depends-on-another-field
Thanks, so select2 isnt possible to do that right?

**Comment by samuk190** [comment]
> This how to on the website might help: https://backpackforlaravel.com/docs/4.0/crud-how-to#add-a-select2-field-that-depends-on-another-field

Thanks!
