### ISSUE TITLE
[4.0.9][BUG] 'visibleInTable' column attribute not working

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/CRUD#2159]
# Bug report

### What I did

Added `visibleInTable => false` attribute to a column

### What I expected to happen

The column is hidden in list (table view)

### What happened

The column is not hidden in list (table view)

### Backpack, Laravel, PHP, DB version
Backpack 4.0.9
Laravel 6.2
PHP 7.2

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Heeelo @drionix 

Thanks for spotting this out. 

I have sent a PR to try to fix this. I would like if you have time to give it a look. It's here: #2220 

I will be closing this issue, we can continue the conversation on the PR thread :) 

Best,
Pedro

**Comment by maganius** [comment]
I have same problem, I have this
```
$this->crud->addColumn([
            'label' => "Empresa", // Table column heading
            'type' => "text",
            'name' => 'empresa_nombre', // the column that contains the ID of that connected entity;
            'visibleInTable' => false, // no point, since it's a large text
        ]);
```

but the column still is visible

**Comment by pxpm** [comment]
@maganius check if you are using the latest BP version and clear your browser localStorage. 

Best,
Pedro

**Comment by maganius** [comment]
@pxpm you're right, this was localStorage, I disabled it and works, thanks you.

**Comment by pxpm** [comment]
@maganius I would not advise you to disable it, might break other functionality. 

It's enough to clear it and everything should work.

Best,
Pedro
