### ISSUE TITLE
Select 2 console issue

### ISSUE THREAD

**Issue by LaktionovaHelen** [Laravel-Backpack/CRUD#216]
When searching with select2 (with data that we do not have in relation), we get an error -
"this.showSearch is not a function"
 http://storage2.static.itmages.com/i/16/1102/h_1478094410_6502285_2c80991b92.png

This is select2 bug.

Need to update select2 in package. (Can use  3.5.4 version )

**Comment by OwenMelbz** [comment]
Hi @LaktionovaHelen thanks for bringing this to our attention, it will be added to a list which you can view here https://github.com/Laravel-Backpack/CRUD/issues/285
