### ISSUE TITLE
BackPack Instant Field Extension -> ShareReportController error after v4

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2160]
I'm using backpack instant fields and after backpack v4 ->   ShareReportController is not found when using with() -> function ajax in route controller
https://github.com/webfactor/laravel-backpack-instant-fields

I know that it is a extension but I want to know what changed backpack v3.5 to v4 so I can fix and do a pull request, and what causes ShareReportController error can be.

**Comment by Athuli7** [comment]
ShareReportController is an ignition error.
