### ISSUE TITLE
[4.0.x] Issue with setSubheading function

### ISSUE THREAD

**Issue by dachieu1996** [Laravel-Backpack/CRUD#2161]
I did not see any change when use function setSubheading()
I find a bug at file crud/src/Library/CrudPanel/Traits/HeadingsAndTitles.php
You forget ' . ' before 'subheading' at row 118. The code I fixed below:
public function setSubheading($string, $action = false)
    {
        if (! $action) {
            $action = $this->getActionMethod();
        }
        return $this->set($action . '.subheading', $string);
    }

**Comment by jsvini** [comment]
@dachieu1996 make a pull request 😁

**Comment by pxpm** [comment]
Thank you @dachieu1996 for bringing this up to our atention .

@justinmoh just sent a PR that will fix this. 

I have already tested and approved the changes in #2206 

I will be closing this as the solution is already provided and any further discussion on this matter should be done in PR thread itself. 

Thanks again guys. Wish you the best.

Pedro
