### ISSUE TITLE
How to insert view Create inside another Create view?

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2163]
I need to make a table(like table field but non json) which make it possible to add and remove products from a  machine.
For example

table->
--> id: 01, machine: Test, numbermachine:53 

table(disabled/hidden)->
,id,productname,(foreign key machine_id hidden)

Message: Please create a machine!

ListView
table->
--> id: 01, machine: Test, numbermachine:53 

table(enabled)->
,id,productname,(foreign key machine_id hidden)

But I dont know how to insert a CrudView->create  inside the create or list views.

**Comment by tabacitu** [comment]
@samuk190 you can only do that using a custom field - https://backpackforlaravel.com/docs/4.0/crud-fields#creating-a-custom-field-type You can then overwrite the create() and update() methods in your CrudController and save the additional entity.

I think for Backpack v3 there was this package https://github.com/webfactor/laravel-backpack-instant-fields that helped, but I don't know if they've provided v4 support already.

**Comment by samuk190** [comment]
> @samuk190 you can only do that using a custom field - https://backpackforlaravel.com/docs/4.0/crud-fields#creating-a-custom-field-type You can then overwrite the create() and update() methods in your CrudController and save the additional entity.
> 
> I think for Backpack v3 there was this package https://github.com/webfactor/laravel-backpack-instant-fields that helped, but I don't know if they've provided v4 support already.

Thanks but the problem is that backpack instant fields doesnt work for v4 and I dont know why. IT give share report controller error so I dont have idea how to fix it.
It would made things a lot easier with instant fields than creating from zero a function because in my project I need to save the table fields content after user is created or in edit and by another entity.

**Comment by GregaUNK** [comment]
As Iam aware of "instant fields" are on the roadmap for native Backpack implementation?
#2070 
Is that it? Any ETA?
