### ISSUE TITLE
session timeout redirect login page

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/CRUD#2164]
# Bug report

### What I did
How to auto redirect login page when session expire
??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version
Laravel 6.0
PHP7.3
DB MySql

When I run ```php artisan backpack:version``` the output is:
backpack 4.0

**Comment by tabacitu** [comment]
Hi @gumpon ,

The user should already be automatically redirected to the Login page when the session expires and he tries to access a new page (effectively he's being logged out). Let me know if that's not what you were looking for. If so, please describe your issue using more words. More words, more changes people understand what you mean 😄 

Cheers!
