### ISSUE TITLE
[4.0][Feature] Persistent table for arbitrary number of hours

### ISSUE THREAD

**Issue by Uteev** [Laravel-Backpack/CRUD#2165]
Persistent table is a cool feature of Backpack. But **is there way to make tables persistent for arbitrary number of hours or "forever"?**

If there is no way, can this feature be added in the future?

**Comment by Uteev** [comment]
Any ideas on this?

**Comment by tabacitu** [comment]
Hi @Uteev - I agree, there's no reason why we wouldn't let devs decide how much time the table should persist. Will do.

I've [found the PR](https://github.com/Laravel-Backpack/CRUD/pull/1702/files), given it a thorough look, but I can't for the life of me see _where_ the ```localStorage``` is cleared... It says two hours in the comments, but nowhere in the code... I'll check again later, I must be missing something obvious. Let me know if you take a look and find anything in this PR - I can then instruct you on how to change it for you project before the feature gets implemented.

Cheers!

**Comment by Uteev** [comment]
Thank you! I will look the PR on weekend and inform if I find something.

**Comment by pxpm** [comment]
Hey guys!!! Nice to see this back up on table. 

I have just submited the PR that really enables this feature on crud :)

Let me now what you guys think in #2220 

I will be closing this so we can keep the discussion of this issue in a single place !

If you feel i am wrong about it, please re-open!

Best,
Pedro

**Comment by tabacitu** [comment]
Merged! The feature will be available later today as 4.0.18.
