### ISSUE TITLE
Undefined index: columns (View: .... vendor/backpack/crud/src/resources/views/crud/fields/table.blade.php)

### ISSUE THREAD

**Issue by rabol** [Laravel-Backpack/CRUD#2170]
# Bug report

### What I did

STEP 1. create migration
php artisan make:migration:schema create_tags_table --model=0 --schema="name:string:unique"
add a json filed
$table->json('tag_features')->nullable()
php artisan migrate

STEP 2. create crud
php artisan backpack:crud tag

### What I expected to happen

being able to add a new record

### What happened
Exception was thrown
Facade\Ignition\Exceptions\ViewException
Undefined index: columns (View: /home/vagrant/code/backpack/vendor/backpack/crud/src/resources/views/crud/fields/table.blade.php)

### What I've already tried to fix it

Nothing so far

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.3.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.9      Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.4      Generate files for laravel projects

**Comment by tabacitu** [comment]
Hi @rabol ,

Looks like a misconfigured [table field](https://backpackforlaravel.com/docs/4.0/crud-columns#table). Configuring it as explained in the docs linked above should fix it for you.

It's weird though - the "table" field is loaded for you automatically? When using ```setFromDb()``` in your controller? Or have you manually added it in your controller?

Cheers!

**Comment by rabol** [comment]
Hi

I did not add anything the first time, pure 'default' code that was created with the backpack:crud command


I found out that I needed to configure the table field manually, but still I think that it's a 'bug' that one have to make 'special' code for a specific field type.

**Comment by tabacitu** [comment]
I think you're totally right, thank you @rabol . Just pushed a fix so if nothing is defined a simple "value" column will be used, for both fields and columns. Will most likely not be what people are looking for (they'd still need to properly configure their fields), but at least they won't be met with a nasty error.

Thanks, cheers!

**Comment by ogiogiovictor** [comment]
Hi I am having problems with the CKeditor. When i remove it from the setupCreateOperation() the forms shows but when i add the ckeditor options the form breaks
 CRUD::field([   
                'name' => 'about_the_game',
                'label' => 'About The Game',
                'type' => 'ckeditor',
            ]);
       

see error
![image](https://user-images.githubusercontent.com/46789910/190860250-2eccb45a-ee15-4c74-bf61-de7bd63636cf.png)

**Comment by tabacitu** [comment]
@ogiogiovictor can't really tell from the screenshot, the error is a bit obscure. Can you please click the Share button there, and copy-paste the error link here? That will give us access to the full error stack, to better understand what's going on.

**Comment by ogiogiovictor** [comment]
I noticed that the each time i add addFields either ckeditor, tinymce or
summertone   to setupCreateOperation() I get    Class
'Composer\InstalledVersions' not found (View:
/home/ogiogiovictor/projects/laravel/games/vendor/backpack/crud/src/resources/views/crud/inc/show_fields.blade.php)

$this->crud->addField([
                'name'  => 'about_the_game',
                'label' => 'About',
                'type'  => 'tinymce',
                // optional overwrite of the configuration array
                'options' => [
                    'selector' => 'textarea.tinymce',
                    'skin' => 'dick-light',
                    'plugins' => 'image,link,media,anchor',
                    'toolbar' => 'undo redo formatselect fontsizeselect
bullist numlist link image bold italic underline forecolor',
                ],
            ]);



See Error below:
[image: image.png]
