### ISSUE TITLE
Errors since updating to V4: ErrorException (E_ERROR) View [layout] not found. 

### ISSUE THREAD

**Issue by ApexMuse** [Laravel-Backpack/CRUD#2176]
# Bug report

### What I did

Since updating to Backpack V4, each time I have an error I get the following message:

ErrorException (E_ERROR)
View [layout] not found. (View: /resources/views/errors/layout.blade.php) 

### What I've already tried to fix

I've isolated the error to the following line of code in errors/layout.blade.php:

@extends(backpack_user() && (starts_with(\Request::path(), config('backpack.base.route_prefix'))) ? 'backpack::layout' : 'backpack::layout_guest')

I've also triple-checked the upgrade guide to make sure I didn't miss anything.

I've spent about 4 hours trying to figure this out and I'm feeling pretty stupid right now.  I'm quite certain I'm doing something boneheaded, so **please**...someone...throw me some wisdom!

### Backpack, Laravel, PHP, DB version

PHP 7.2.16
Laravel 6.2.0
Backpack 4.0.12
MySQL 5.7.28

**Comment by martijnb92** [comment]
Make sure you remove any custom views from the v3 version. That solved this issue for me.

**Comment by ApexMuse** [comment]
Thank you @martijnb92 - I didn't have any custom views but your reply led me to the problem.  The old V3 "resources/views/errors" folder from [Backpack Base](https://github.com/Laravel-Backpack/Base/blob/0f6246a174f071e81b0ca9e6dcec65dae9823210/src/BaseServiceProvider.php#L210) was the problem.  Seems like publishing the files during the upgrade didn't overwrite the old error views...not sure why.

If anyone else comes across this issue, overwrite the first line in layout.blade.php.  The code should look like this:

`@extends(backpack_user() && (starts_with(\Request::path(), config('backpack.base.route_prefix'))) ? 'backpack::layouts.top_left' : 'backpack::layouts.plain')`

**Comment by ApexMuse** [comment]
This probably should have been posted on Stackoverflow so I'm going ahead and closing it.

**Comment by jefffairson** [comment]
Hi @ApexMuse,
I know the issue is closed but I had the same issue when updating from 4.0 to 4.1, you spotted the issue but the line you placed is wrong it should look like this :
```@extends(backpack_user() && (Str::startsWith(\Request::path(), config('backpack.base.route_prefix'))) ? 'backpack::layouts.top_left' : 'backpack::layouts.plain')```

```starts_with```was an old Laravel helpers which was replaced by ```Str::startsWith```

In case you've got the issue, apply this fix or if you didn't customize the views, publish the errors views again.
Hope this helps.
