### ISSUE TITLE
[4.x]Documentation Missing: Backpack Crud Elfinder show folders only for each crud

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2180]
I have 5 cruds
1-> Products
2-> Tickets

and so on.. I want the admin when click browse to only upload/select/view files from the folder "products" when on crud products. Also I need it to hide the file for other products, so you don't misclick and select a report.pdf that doesnt belong to your product. 

Also if possible how to delete the file when clicking on the trash icon on the edit view instead of opening the Elfinder and clicking to remove it.

or just a way to simple upload multiples files, and a download button on view,  without need to elfinder or such

**Comment by pxpm** [comment]
Hello @samuk190 

Thank you for your interest on this. I will be closing this as this is not really a bug report. 

However i can see this become a feature that people maybe look for. If you dig on this issue let us know your results. 

Maybe we could find a way to implement in core or teach other developers how to implement your solution per project need.

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
@samuk190 sounds to me like you don't really need elFinder at all. I think it's better for you to take a look at the [upload field type](https://backpackforlaravel.com/docs/4.0/crud-fields#upload). It will be MUCH easier to customize that one, instead of elFinder.

Hope it helps. Cheers!
