### ISSUE TITLE
About the capabilities of Backpack

### ISSUE THREAD

**Issue by Wulfheart** [Laravel-Backpack/CRUD#2184]
Hello, I'm just evaluating Backpack. 
So far it seems quite practical. Is it possible to show a user only his own data, for example only his entries.
And I want one entry to have multiple related entries which can be declared in the entry itself. Is this also possible?
Thank you in advance

**Comment by ApexMuse** [comment]
@Wulfheart - Yes, that is all possible.  I just finished doing this with my company's application.

We have 220 store locations, each with their own customizable website and their own admin console.  All data is kept in one global DB, with an identifier in each table that identifies which store the row belongs to.  When a user visits their admin console they only see the data pertaining to their store.  

In each CRUD controller you simply add an addClause() to the query.  For example:

$this->crud->addClause('where', 'store_id', '=', config('local.store_id');

You can also add other clauses to find related entries.

Get Backpack.  You won't regret it.

**Comment by Wulfheart** [comment]
Ok, thank you really much.
If I have a person and want that person to have multiple vacation dates, is it possible to make them ordered by date in a table field?

**Comment by ApexMuse** [comment]
@Wulfheart - Certainly!  [Backpack makes it easy](https://backpackforlaravel.com/docs/4.0/crud-api#custom-queries-api).  You would do something like this:

$this->crud->orderBy('vacation_start_date', 'ASC');

**Comment by samuk190** [comment]
You can also use global scopes to make it easier

**Comment by pxpm** [comment]
@Wulfheart Thanks for your interest in Backpack.

I hope you already started exploring around, it's really easy to get started. 

Here we use Github Issues to track BUG's, Features and that kind of stuff. 

More general questions it's better to ask on [our gitter channel](https://gitter.im/BackpackForLaravel/Lobby)

If it's about licencing or other sales information please reach out on [our contact page](https://backpackforlaravel.com/contact)

I will be closing this, if you need something just let us know :)
