### ISSUE TITLE
How to disable Save and New Action on setupCreate

### ISSUE THREAD

**Issue by samuk190** [Laravel-Backpack/CRUD#2186]
How I can disable the button action save and new on setupCreate
and enable it as default on setupCreate, I didnt found any method on documentation to remove the buttons of save, I read here on github that it was a feature planned for 4.0 so?

**Comment by pxpm** [comment]
Hello @samuk190 yes, it is planned.

The PR has some time, and probably will have modifications, but the thread is here: #658 

I will close this one, please subscribe to that PR thread so you get notified when i get back to it.

If you have a good idea how that could be achieved please write there in commments, I promisse I will read them all before doing anything. :)

Best,
Pedro
