### ISSUE TITLE
Filters based on the current list of entries

### ISSUE THREAD

**Issue by maxacarvalho** [Laravel-Backpack/CRUD#2189]
## Overview
I don't think this is a bug and maybe it's an implementation help, I'm sorry for that.  
I spent quite a few hours trying to figure it out on my own and searching on the proposed channels but I couldn't find the answer to my problem so I'm trying here.

### What I did:
Created filters for a grid listing, basically a `date` filter and a bunch of `select2` ones.

### What I am trying to get:
Filters based on the current items that are listed.  
So, for example, if I select a filter to be applied, I'd like to have the other filters to have their contents also affected by the filter that IS applied.

Let's say I have a dropdown with statuses: **enabled**, **disabled**.  
And then another dropdown that shows clients **A**, **B** and **C**.  
The list items related to client **B** are all **disabled**, so when I select the `status -> enabled`, I'd like to have the clients' dropdown to show ONLY the clients **A** and **C**

is there any known solution for that?

### Apart from the above, this 👇 looks like a bug:

The **date** filter cannot be cleared. When I select a date that date stays there even after I click on the **Remove Filters** button.

I'd expect to click on the X within the date filter and have the filtered date removed but that's not happening.

### What I've already tried to fix it:

Tried to use the `$this->crud->getEntries()` to play around bu that doesn't work and break my page.  
Searched a lot here on the repo's issues and also Google and StackOverflow, no success though, perhaps I'm typing the wrong questions.

Thanks for your help!

### Backpack, Laravel, PHP, DB version:
backpack/crud 4.0.12
laravel/framework v6.4.1
PHP 7.3.11

**Comment by pxpm** [comment]
Closing this. Check my comment on gitter.
BR

**Comment by tabacitu** [comment]
Thank you for taking care of this @pxpm . 

Haven't followed your discussion on Gitter, but if I were you @maxacarvalho I'd use [the select2 filter](https://backpackforlaravel.com/docs/4.0/crud-filters#select2). It allows you to return whatever values you want for the filter, in the second parameter, inside the closure. So you could return a filtered set of options for that filter, depending on GET variables of the other filters.

Hope it helps!
