### ISSUE TITLE
ajaxdatatables and whereclause issue

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/CRUD#219]
hi.. very quick question.. in backpack crud controller.. if i enable the ajaxdatatable.. where do i define my where clause?
currently im doing this:
```php
public function prospective()
    {
    $this->crud->setEntityNameStrings('New Student', 'Student List - Prospective');
    $this->crud->hasAccessOrFail('list');

    $this->data['crud'] = $this->crud;
    $this->data['title'] = ucfirst($this->crud->entity_name_plural);
    $userallocation = User::all()->filter(function (User $user) { return $user->hasPermissionTo('user_allocation'); });
    // // get all entries if AJAX is not enabled
    if (! $this->data['crud']->ajaxTable()) {
        $this->data['entries'] = $this->data['crud']->getEntries()->where('registrationstep', null);
    }
    return view('StudentLists', $this->data)
    ->with('userallocation', $userallocation)
    ;
    }
```
it works without the ajaxtable as its inside the `if (! $this->data['crud']->ajaxTable()) { $this->data['entries'] = $this->data['crud']->getEntries()->where('registrationstep', null); }`
but when i enable ajax.. it skips this if statement and shows all the entries without the filter where clause.

**Comment by Ghitu** [comment]
Hi @mpixelz 
$this->data['crud']->ajaxTable() returns **true** if AjaxTable is enabled using $this->data['crud']->enableAjaxTable();

So if you enable AjaxTable then of course it will skip your code in the if statement since **!$this->data['crud']->ajaxTable()** === false.

Can you tell us more about what do you want to do? Maybe we can help you with that.

Regards

**Comment by mpixelz** [comment]
this is what im trying to do?
`$this->data['entries'] = $this->data['crud']->getEntries()->where('registrationstep', null);`
i need to be able to filter the results displayed using the where clause when ajaxDataTables in enabled..

**Comment by Ghitu** [comment]
@mpixelz  then ` if (! $this->data['crud']->ajaxTable()) {` should be  `if ($this->data['crud']->ajaxTable()) {`

**Comment by mpixelz** [comment]
i know i tried that.. but then whats the use of enabling ajaxdatatables if we are still going to do the query manually..

im just trying to have the `->where('registrationstep', null);` clause in my ajax enabled method.

**Comment by tabacitu** [comment]
Hi @mpixelz ,

You can use ```addClause()``` for filtering (pretty undocumented feature). You can find [the syntax here](https://laravel-backpack.readme.io/docs/crud-full-api#usage-level-2-often), under ADVANCED QUERIES.

I think for your case this should work:
```diff
-$this->data['entries'] = $this->data['crud']->getEntries()->where('registrationstep', null);
+$this->crud->addClause('where','registrationstep', null);
```

or maybe

```php
$this->crud->addClause('whereNull','registrationstep');
```

**Comment by mpixelz** [comment]
does not work..
it ignores the where clause and shows all the results instead

**Comment by Ghitu** [comment]
@mpixelz 
So what you want to achieve is filtering the results making an ajax request to this method from your controller? 
Did you changed anything in the JavaScript files for this?

**Comment by mpixelz** [comment]
yes something like that.. the ajax part is handled automatically by backpack... thats how i am using it on the above mentioned method.. but the enableAjaxDatatables method doesn't work on that and i dont know where i need to put the clause for it to pick it up.

@tabacitu your above mentioned method should have worked as they do make sense but they dont work for some reason.
any other suggestion? or should i just ignore the ajax datatables for now?
thanks.

**Comment by tabacitu** [comment]
That's odd. The ```CrudController::search()``` method, which returns all AJAX results, uses ```$this->crud->query``` to build the results. You could 
- do a ```var_dump($this->crud->query);``` before and after your ```$this->crud->addClause();```
- try different clauses and see what actually filters the results;

Cheers!

**Comment by mpixelz** [comment]
i think it works but i have custom buttons and using it on a overwritten view file.. may be that is causing all this hassle.. im going to implement it on a separate page as see if something changes.
thanks alot thou! really appreciate all the help :)
cheers

**Comment by tabacitu** [comment]
Sorry I couldn't be of more help. Cheers!
