### ISSUE TITLE
[4.0][Bug] Custom Order Logic for Columns stopped working

### ISSUE THREAD

**Issue by misiekch** [Laravel-Backpack/CRUD#2192]
# Bug report

### What I did

I am using `orderByRaw` method in column `orderLogic`.

### What I expected to happen

I wanted to sort the list by column with custom order logic.

### What happened

I am getting below response:

{
"message": "**Undefined index: column**",
"exception": "ErrorException",
"file": "[...]\\vendor\\backpack\\crud\\src\\app\\Http\\Controllers\\Operations\\ListOperation.php",
"line": 116,
"trace": [...]
}

### What I've already tried to fix it

In `vendor\backpack\crud\src\app\Http\Controllers\Operations\ListOperation.php`
- replace
`if ($item['column'] == $this->crud->model->getKeyName()) {`
with
`if (isset($item['column']) && $item['column'] == $this->crud->model->getKeyName()) {`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @misiekch 

Thank you very much for reporting this issue. 

Another user also reported this issue and submited an PR, so i will be closing this in favour of the thread with PR open. Feel free to join the discussion at #2196 

Best,
Pedro
