### ISSUE TITLE
[4.0] [BUG] Datatables visibility and export inconsistencies.

### ISSUE THREAD

**Issue by axelzuzek** [Laravel-Backpack/CRUD#2193]
# Bug report

visibleInExport = true && visibleIeInTable = false:
column is not listed in export

### What I did
```
$this->crud->setColumns([
   [ 
     'name' => "street", 
     'label' => "street", 
     'visibleInTable' => false , 
     'visibleInExport' => true
  ],...

```
### What I expected to happen
regarding to 4.0 docs "add a column that's hidden from the table view, but WILL get exported;" 
column street should be listed in XLSX export

### What happened

column street is not present in export, the user has to select "street" in column visibility chooser, that is not very intuitive. 

### What I've already tried to fix it

?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.0.4             The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.12             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.4              Generate files for laravel projects
backpack/langfilemanager              2.0.1              An interface to edit language files, for Laravel Backpack.
backpack/permissionmanager            5.0.2              Users and permissions management interface for Laravel 5 using Backpack CRUD.

**Comment by Mutahhar** [comment]
This issue is also reported here #2159, but no solution yet.

**Comment by pxpm** [comment]
Hello @axelzuzek !

Thank you very much for raising this issue.

I tried to tackle it in PR #2220 

Can you give there your thoughts ? I will be closing this so we keep the conversation on the solution proposal. 

Please feel free to re-open if you think it's not solved.

Best,
Pedro
