### ISSUE TITLE
Error loading Custom Page Panel Length when Laravel Api Boilerplate is installed 

### ISSUE THREAD

**Issue by ssmusoke** [Laravel-Backpack/CRUD#2194]
# Bug report

### What I did

1. Installed backpack, created custom tag as in the CRUD tutorial 
2. Installed https://github.com/specialtactics/laravel-api-boilerplate

### What I expected to happen

Everything to work fine 

### What happened

"in_array() expects parameter 2 to be array, null given (View: /Users/project/project-api/vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php)"

#1 /Users/project/project-api/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Read.php(206): in_array(10, NULL)
#2 /Users/project/project-api/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Read.php(245): Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel->addCustomPageLengthToPageLengthMenu()
#3 /Users/project/project-api/storage/framework/views/4ee47ec8d4ed8d5515d9ac5e6bbdf60a93669eb3.php(91): Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel->getPageLengthMenu()

### What I've already tried to fix it

Looking into the backpack config, but its not clear why the pageLengthMenu configuration is not not being read 

### Backpack, Laravel, PHP, DB version
When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.24 (cli) (built: Oct 25 2019 11:13:56) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.27.1~mac-x64-non_zts72, https://blackfire.io, by Blackfire

### LARAVEL VERSION:
laravel/framework                       v6.4.1     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                           4.0.12     Quickly build an admin...
backpack/generators                     2.0.4      Generate files for lar...

**Comment by tom075395** [comment]
https://github.com/Laravel-Backpack/Docs/blob/master/4.0/crud-cheat-sheet.md

try this : $this->crud->setPageLengthMenu( [[]] );

**Comment by pxpm** [comment]
Hello @tom075395 i am not sure where your error is beeing triggered, i just tried in a CRUD: 

```
public function setupListOperation() {
        $this->crud->setPageLengthMenu([[10,-1],[10,"backpack::crud.all"]]);
    }
```

Works as expected, only 2 available options 10 and All. Also tried with yours `$this->crud->setPageLengthMenu([[10,25,50,100,-1],[10,25,50,100,"backpack::crud.all"]]);` and got the expected result.

I don't have the api-boilerplate package installed. But i don't expect it to have some kind of interference with crud panel. 

BR

**Comment by ssmusoke** [comment]
@tom075395 I am using the default configurations with nothing changed. 

For some reason the error is being triggered in this a backpack file /Users/project/project-api/vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php 

Looks like when I install the specialtactics/laravel-api-boilerplate package, the specific configurations are not read any more - not sure why this changes with a different package

**Comment by pxpm** [comment]
@ssmusoke  You are not using a "clean laravel install with backpack", you are using backpack on top of that boilerplate. It `SHOULD` not make any difference tbh but who knows.

Could you try:

 `php artisan cache:clear`
`php artisan route:cache`
`php artisan config:cache`

Let me know how it goes.

**Comment by tom075395** [comment]
Your route is "Router:crud()" or "get\post"?
"Router:crud” will call path to get default setting.

**Comment by ssmusoke** [comment]
@pxpm Actually I am, as in the description I installed backpack first, got it working with the tag from the tutorial before installing laravel-api-boilerplate code at https://github.com/ssmusoke/laravel-backpack-test

@tom075395 the route is  Crud see here https://github.com/ssmusoke/laravel-backpack-test/blob/f4183901db9b6ce9723b92e08d6bd14df7e424d2/routes/backpack/custom.php#L14

**Comment by tom075395** [comment]
@ssmusoke 
Try to check route list? Maybe the plugin has create a route first, so no call crud route to get setting.

**Comment by pxpm** [comment]
Hello @ssmusoke 

I am doing issue cleanup, so this is one i am going to close because i think it is not a backpack bug. 

However i might be wrong, so feel free to keep the conversation going if needed, i will be around :)

Best,
Pedro
