### ISSUE TITLE
[4.0][BUG] ListOperation@search exception when using orderByRaw/inRandomOrder 

### ISSUE THREAD

**Issue by kritsot** [Laravel-Backpack/CRUD#2195]
# Bug report
When using raw orderby e.g **$this->crud->query->orderByRaw** the list is not loaded and an error message is shown.
The error shown in the log is 

_Undefined index: column at vendor/backpack/crud/src/app/Http/Controllers/Operations/ListOperation.php:116_

**Comment by pxpm** [comment]
Hello @kritsot . Thank you very much for reporting this issue. Please see my comment in the PR you have submited.

This is a duplicate of #2192 but i will let this open as this already as a link to the PR #2196

**Comment by tabacitu** [comment]
Merged! Thanks again guys - good work!
