### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by mpf101112** [Laravel-Backpack/crud#22]
I am receiving this error and do not know how to fix it.

Invalid backend configuration.
Readable volumes not available.

Help please

Thanks

**Comment by tabacitu** [comment]
I'm assuming this error is just in the File Manager view. 

Did you:
1) publish the elFinder config file, like instructed in step 3?
```php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="elfinder"```
2) do step 5?

This error is usually thrown when there's an issue either in config/filesystems.php or in config/elfinder.php. This is how config/elfinder.php should look:


```

    /*
    |--------------------------------------------------------------------------
    | Upload dir
    |--------------------------------------------------------------------------
    |
    | The dir where to store the images (relative from public)
    |
    */
    'dir' => ['uploads'],

    /*
    |--------------------------------------------------------------------------
    | Filesystem disks (Flysytem)
    |--------------------------------------------------------------------------
    |
    | Define an array of Filesystem disks, which use Flysystem.
    | You can set extra options, example:
    |
    | 'my-disk' => [
    |        'URL' => url('to/disk'),
    |        'alias' => 'Local storage',
    |    ]
    */
    'disks' => [
    ],

    /*
    |--------------------------------------------------------------------------
    | Routes group config
    |--------------------------------------------------------------------------
    |
    | The default group settings for the elFinder routes.
    |
    */

    'route' => [
        'prefix' => 'admin/elfinder',
        'middleware' => ['web', 'auth'], //Set to null to disable middleware filter
    ],

    /*
    |--------------------------------------------------------------------------
    | Access filter
    |--------------------------------------------------------------------------
    |
    | Filter callback to check the files
    |
    */

    'access' => 'Barryvdh\Elfinder\Elfinder::checkAccess',

    /*
    |--------------------------------------------------------------------------
    | Roots
    |--------------------------------------------------------------------------
    |
    | By default, the roots file is LocalFileSystem, with the above public dir.
    | If you want custom options, you can set your own roots below.
    |
    */

    'roots' => null,

    /*
    |--------------------------------------------------------------------------
    | Options
    |--------------------------------------------------------------------------
    |
    | These options are merged, together with 'roots' and passed to the Connector.
    | See https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1
    |
    */

    'options' => array(),

    /*
    |--------------------------------------------------------------------------
    | Root Options
    |--------------------------------------------------------------------------
    |
    | These options are merged, together with every root by default.
    | See https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#root-options
    |
    */
    'root_options' => array(

    ),
```

**Comment by mpf101112** [comment]
Hi, I’m new with Laravel and appreciate the response.

 

I went  through all the steps and this is what I have.

 

// config/filesystems.php

 

  |

    */

 

    'disks' => [

 

        'local' => [

            'driver' => 'local',

            'root' => storage_path('app'),

        ],

 

        'public' => [

            'driver' => 'local',

            'root' => storage_path('app/public'),

            'visibility' => 'public',

        ],

 

        's3' => [

            'driver' => 's3',

            'key' => 'your-key',

            'secret' => 'your-secret',

            'region' => 'your-region',

            'bucket' => 'your-bucket',

        ],

 

        'uploads' => [

            'driver' => 'local',

            'root' => public_path('uploads'),

        ],

    ],

 

];

 

//--config/elfinder.php

 

|--------------------------------------------------------------------------

    | Upload dir

    |--------------------------------------------------------------------------

    |

    | The dir where to store the images (relative from public)

    |

    */

    'dir' => ['uploads'],

 

    /*

    |--------------------------------------------------------------------------

    | Filesystem disks (Flysytem)

    |--------------------------------------------------------------------------

    |

    | Define an array of Filesystem disks, which use Flysystem.

    | You can set extra options, example:

    |

    | 'my-disk' => [

    |        'URL' => url('to/disk'),

    |        'alias' => 'Local storage',

    |    ]

    */

    'disks' => [

        // 'uploads',

    ],

 

   /*

    |--------------------------------------------------------------------------

    | Routes group config

    |--------------------------------------------------------------------------

    |

    | The default group settings for the elFinder routes.

    |

    */

 

    'route' => [

        'prefix'     => 'admin/elfinder',

        'middleware' => ['web', 'auth'], //Set to null to disable middleware filter

    ],

 

    /*

    |--------------------------------------------------------------------------

    | Access filter

    |--------------------------------------------------------------------------

    |

    | Filter callback to check the files

    |

    */

 

    'access' => 'Barryvdh\Elfinder\Elfinder::checkAccess',

 

    /*

    |--------------------------------------------------------------------------

    | Roots

    |--------------------------------------------------------------------------

    |

    | By default, the roots file is LocalFileSystem, with the above public dir.

    | If you want custom options, you can set your own roots below.

    |

    */

 

    'roots' => null,

 

    /*

    |--------------------------------------------------------------------------

    | Options

    |--------------------------------------------------------------------------

    |

    | These options are merged, together with 'roots' and passed to the Connector.

    | See https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1

    |

    */

 

    'options' => [],

 

];

 

Thanks

**Comment by tabacitu** [comment]
Ok, I'll investigate, maybe the file publishing doesn't work any more.
In the meantime, please use the configuration I've posted above.

Cheers!

**Comment by tabacitu** [comment]
Checked, installed multiple times, works as expected.
