### ISSUE TITLE
Don't assume boolean when column type not specified and value is 0

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#2201]
In Backpack 4, when a column value is 0 and show settings is set, backpack 4 appears to assume it is a boolean and display 'No'. in the Preview (show) page

I think that is not the common expectation. This happens when value is 10 too.

**Comment by pxpm** [comment]
Hello @ziming thanks for reporting this issue to us.

Can you provide me a little more info so i could reproduce the issue ? 

This is what i'v done so far:

- Created one text and one number field in a CRUD.
- Set those fields values to 0.
- Added them to columns whitout specifying it's type `$this->crud->addColumns([['text'],['number']]);`
- Went to show view and saw

**Text: 0**
**Number: 0**

Can you help me here to reproduce this ?

Thanks in advance,
Pedro

**Comment by ziming** [comment]
Ah i mean u don't even have setupShowOperation() method. u just have the trait only.

**Comment by pxpm** [comment]
Hello @ziming . Thanks for quick reply.

I removed the `setupShowOperation()` to make sure it's uses `setFromDb()`

My `number` and `text` field from above still show 0.

The only `Yes` or `No` i have in page are `checkbox fields`.

Maybe i am just doing something wrong help me here with some sample code, so we can go through and close this issue.

Best,
Pedro

**Comment by ziming** [comment]
I'm on the train now. what about 10?

**Comment by pxpm** [comment]
No problem man. Tried 10. Expected results. 

When you have time let me know your field setup in database, your model fillable and casts and your crud field. 

We must be doing something different, but we will get there :) 

Best,
Pedro

**Comment by ziming** [comment]
Hi @pxpm

Ok replicated it in my local development.

- I set that column value to 10 or 5
- in my model class, my cast for that column is integer
- In my CrudController. If my setupShowOperation() is empty it shows No (boolean)
- If I remove setupShowOperation(), it also shows No (boolean)
- If I have setupShowOperation() and I define that column as number type, then it shows the number
- In my migrations, that column type is **unsignedTinyInteger**

Hope it helps and thanks for the hardwork

**Comment by pxpm** [comment]
@ziming Thanks for helping me reproducing this issue.

I can confirm it, but i am afraid it's not 100% Backpack fault on this. If you don't specify the setupShowOperation  like you said, Backpack will use the setFromDb functionality, It has a built in Laravel schema mapper. 

The thing is that mapper assumes tinyInt as boolean. In fact Laravel is using the alias `$table->boolean` for tinyInt. 

You can [check here](http://prntscr.com/pxc7vq) the results for that specific table column, `number is the name of my field on db (unsignedTinyInt)`.

I hope i made myself clear on the explanation. 

I will be closing this issue, but please feel free to keep the discussion if you think we can do something about it.

Best,
Pedro
