### ISSUE TITLE
[4.0] The select_from_array column breaks on the Preview screen if there is only one option

### ISSUE THREAD

**Issue by nahuelmino** [Laravel-Backpack/CRUD#2219]
# Bug report

### What I did

I used the "select_from_array" column with only one option in the array of the "options" attribute. For example, I have a column named Sizes, which I used to show them on the Preview screen:

```
[
    'name' => 'sizes',
    'label' => "Sizes",
    'type' => 'select_from_array',
    'options' => [1 => 'S'],
],
```

In the database, the sizes column is a JSON one, and it is saved like this: `["1"]`. The attribute is also added to the `$casts` property to cast it as array. 

This works properly when multiple options are chosen (and the value on the database look something like this: `["1", "2", "3", "4"]`). I'm also not exactly sure if the options attribute value is correct, since on the documentation the example uses an array of two elements.

### What I expected to happen

In the preview screen, the column should read: 

Sizes: S

As an added note, when multiple options are chosen, the column reads like this (which is correct):

Sizes: S, M, L

### What happened

I get an Array to string conversion error.

### What I've already tried to fix it

So from looking at the `select_from_array.blade.php` file on the `views/columns` folder inside the Backpack package, I find this bit of code starting from line 9:

```
if (is_array($values)) {  
        $array_of_values = [];

        foreach ($values as $key => $value) {
              $array_of_values[] = $column['options'][$value];
        }

        if (count($array_of_values) > 1) {
             echo implode(', ', $array_of_values);
        } else {
            echo $array_of_values; // This tries to print the array directly.
        }
} else {
       echo $column['options'][$values];
}
```

Because $array_of_values has only one option, this executes the else block, which tries to echo an array. Unless I'm doing something wrong with how the options are passed when defining the column on the CrudController or how the value is saved to the database, looks like there are two solutions here:

1) Instead of checking if the count is > 1, it should be >= 1.
2) On the else block, it should echo $array_of_values[0].

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP version: 7.2.1
Laravel version: 6.5.1
Backpack CRUD version: 4.0.14
MySQL version: 5.7.23

Also, just wanted to let you know that this is a great library, thank you for the excellent work on this!

**Comment by pxpm** [comment]
Hello @nahuelmino 

Thank you for spotting this issue. 

I could indeed confirm and submit a PR to fix it. 

I will be closing this issue as we already have a working solution, please if you have something to add on this conversation do it [here in PR #2229](https://github.com/Laravel-Backpack/CRUD/pull/2229)

One more time, thank you very much.

Best,
Pedro

**Comment by tabacitu** [comment]
Merged! Thank you @nahuelmino & @pxpm .
