### ISSUE TITLE
Only one simplemde at a time

### ISSUE THREAD

**Issue by MarcBrillault** [Laravel-Backpack/CRUD#222]
I encountered a bug, where only one simplemde editor is allowed on a page.

I'm quite new to github, I don't know how to push a corrected version of the file yet, but here is what I've done to fix it:

In src/resources/views/fields/simplemde.blade.php, the "new SimpleMDE" has to be out of the checkIfFieldIsFirstOfItsType, or it will only be triggered once.
```php
@if ($crud->checkIfFieldIsFirstOfItsType($field, $fields))

    {{-- FIELD CSS - will be loaded in the after_styles section --}}
    @push('crud_fields_styles')
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    @endpush

    {{-- FIELD JS - will be loaded in the after_scripts section --}}
    @push('crud_fields_scripts')
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    @endpush

@endif

@push('crud_fields_scripts')
    <script>
        var simplemde = new SimpleMDE({ element: $("#simplemde-{{ $field['name'] }}")[0] });
    </script>
@endpush
```

**Comment by tabacitu** [comment]
Totally right, @MarcBrillault , my bad. Thanks, fixed. A ```composer update``` should fix it for you too.

Cheers!

**Comment by MarcBrillault** [comment]
Thanks !

**Comment by MarcBrillault** [comment]
I'm sorry @tabacitu but it doesn't work: as you didn't add the code into the @push('crud_fields_snippets'), no simpleMDE are displayed anymore !

**Comment by tabacitu** [comment]
Oh crap. Thanks a lot, really messed this up. Fixed and tested, thank you for the heads-up.

Cheers!

**Comment by MarcBrillault** [comment]
Thanks, it works perfectly now.
