### ISSUE TITLE
[4.1.x][Proposal] EditorJS field type

### ISSUE THREAD

**Issue by SamSebastien** [Laravel-Backpack/CRUD#2222]
I've been loving the way EditorJS ([editorjs.io](url)), ( ([https://github.com/codex-team/editor.js](url) formats blocks as JSON and is really light in the database and flexible in the presentation layer compared to typical WYSIWYG editors and even the Markdown field that I previously loved. 

I noticed you were considering GrapeJs #2023 here, and this seems like a really simple "in between" as it frees users up to build and add their own "blocks" with most of the work happening on the view end of the process.

I'm working on a custom field so happy to do a PR, but I think you guys would do a much better job than I can haha.

**Comment by pxpm** [comment]
Hello @SamSebastien .

Thanks for bring this up to the table . Indeed we are considering a move to add that kind of field. 

Would love if you could share your solution when you are done just to see the field in action. Maybe @tabacitu never considered this option, and will be good if we show him the work in progress. :)

Don't mind if your code is not the prettiest or there are better solution. If you are in need of that field and have time to make it happen just do it. Polishing the things is done in end :) 

Even if it don't get merged to core, BP is planning to give devs a simpler way to share custom fields and columns and i can see this field fits there atleast. 

Best,
Pedro

**Comment by tabacitu** [comment]
Hi @SamSebastien , @pxpm ,

Not sure about this - let's see how popular the idea gets. If it's popular, and a lot of people use it, we could include it in the core, of course. However, the best place to start would probably be a custom field type - like @pxpm suggested we'll soon be working on a "community area" on our website, where developers can share bits of code with each other, and store them for later use. This would be a great addition to that.

Cheers!

**Comment by imcodingideas** [comment]
The issue with editor.js is that you need to support all types of attributes, what people copy and paste in. For me, it's not worth it.
