### ISSUE TITLE
reorder setup

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#223]
Guys, i still have problems with the reorder feature. 
I have setup strict to false in the mysql config, but i also saw something about some parent_id, lft, rgt, depth fields added to the model?!

**Comment by tabacitu** [comment]
Hi @AurelDragut ,

Could you be more specific, please? What's the problem you're facing?

Cheers!

**Comment by AurelDragut** [comment]
Sure, @tabacitu,

I made a fresh install of backpack, i added a CRUD for "sections", i changed "strict" from true to false (i remembered you once told me about it) and i tried to reorder the sections (not before setting those two lines about item to reorder, level and access). I have received the same error regarding the "item_id" that i wrote about here before. 

So i went on the documentation site to see if maybe i missed something and so i have seen this...

![image](https://cloud.githubusercontent.com/assets/7759267/20040223/3a571f2a-a45c-11e6-9802-30ad84cd075c.png)

so i did something like this 

![image](https://cloud.githubusercontent.com/assets/7759267/20040236/5dfb949c-a45c-11e6-847f-2bcb850254c8.png)

(i even added my self "order" data but with no luck - the page column is empty because of missconfigured select column but that's another story)

**Comment by tabacitu** [comment]
That all sounds good to me. That's the correct procedure. But you forgot to say what the error/problem is. Again :-))

So Here's a shot in the dark - have you used the CrudTrait on the model?
```php
<?php

namespace Backpack\MenuCRUD\app\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;

class MenuItem extends Model
{
    use CrudTrait;

    protected $table = 'menu_items';
    protected $fillable = ['name', 'type', 'link', 'page_id', 'parent_id'];

```

**Comment by AurelDragut** [comment]
When i push Save after reordering i get the alert (Your order nas not been saved) and in the logs i see this:

[2016-11-06 18:33:39] local.ERROR: exception 'ErrorException' with message 'Undefined index: item_id' in /home/menduit/public_html/vendor/backpack/crud/src/PanelTraits/Reorder.php:25

**Comment by tabacitu** [comment]
Hmm... ```item_id``` is the input name used by NestedSortable (the js plugin). Without that, no way it would work.

1) Do you have any javascript errors in your console?
2) Have you modified the reorder.blade.php in any way?
3) Have you modified the ```saveReorder()``` method in your CrudController in any way?

Cheers!

**Comment by AurelDragut** [comment]
1) i get this in the console:
![image](https://cloud.githubusercontent.com/assets/7759267/20040589/b4ef268c-a462-11e6-9412-be8b049c51b8.png)

2)i didn't modify any of the reorder.blade.php or CrudController

**Comment by tabacitu** [comment]
Okaaay. Now we're onto it. So it's an error in the ```saveReorder()``` method or when trying to call it.  And if you click the URL what does the error say?

**Comment by AurelDragut** [comment]
I think it might be a server security issue, let me check with the hosting company and i will get back to you. (I see something about a xhr error when i click there)

**Comment by AurelDragut** [comment]
Wow, it seems it was a problem with the PHP version (i guess i had a previous version configured that they changed to 5.6)
