### ISSUE TITLE
[4.0][BUG] Trying to pre-filter an entity list using url filters does not work if persistency is active.

### ISSUE THREAD

**Issue by bnxio** [Laravel-Backpack/CRUD#2231]
Two entities: User and Recipe

I have a custom User view, with a button that jumps to the Recipe list and applies a filter based on that Users ID: 
`<a href="{{ route('recipe.index', ['user_id' => $entry->id, 'user_id_text' => urlencode($entry->name)]) }}" class="btn btn-success">View Recipes</a>`

So lets say I'm on `/user/4/show` and click a "View Recipes" button who's URL is `/recipe?user_id=4&user_id_text=User+Name` - esentially applying a filter automatically. (The filter exists on this list already as select2_ajax so I'm mimicking its behaviour.)

This works fine as long as you've not applied filters to the Recipe list beforehand.

Specifically if the key/value `recipe_list_url` exists in my browsers local storage it *always* overrides the link. 

If I've used the "Remove Filters" button on this list it sets that key/value and the link from the User page will be cancelled out every time.

If I clear this key/value the link will work again.

I've tried `disablePersistentTable()` in my RecipeCrudController but it had no effect for this.

I don't see any redirects in the network console so I assume this is happening in Javascript but haven't traced it any further yet.

Thanks!

### PHP VERSION:
PHP 7.3.10 (cli) (built: Sep 24 2019 09:20:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.5.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.13     Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5      Generate files for laravel projects
backpack/permissionmanager            5.0.2      Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                     3.0.0      Application settings interface for Laravel 5 using Backpack CRUD.

**Comment by pxpm** [comment]
Hello @bnxio 

Thanks for reporting this. Luckly today i was working on Datatables when your issue came and i decided that it was better to try to tackle it now. :)

I have added a commit to the PR I was already working on. that i think i will solve this problem scenario.

You can see the PR here #2220 

I will be closing this issue as a solution has already been provided. 

Please feel free to re-open if you think i might be wrong :)

Best,
Pedro
