### ISSUE TITLE
[4.0][Bug] setPersistentTable not working

### ISSUE THREAD

**Issue by misiekch** [Laravel-Backpack/CRUD#2233]
# Bug report

### What I did

I am using `setPersistentTable` method in controller.

### What I expected to happen

I wanted to change the global setting locally.

### What happened

I was still getting the global setting.

### What I've already tried to fix it

Created pull request: #2232 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
Totally. Thank you for PR #2232 @misiekch . And sorry for the dumb mistake.

Cheers!
