### ISSUE TITLE
Is there any way for using the base view to show any message? 

### ISSUE THREAD

**Issue by ingeday** [Laravel-Backpack/CRUD#2254]
# I have this...
```
public function store(StoreRequest $request)
    {
        $idnumber=$request->idnumber;
        $person=\App\Models\Person::where("idnumber",$idnumber)->get();
        
        if($person->count()>0)
            return view(" ");  //  ? ? ?
   
        $redirect_location = parent::storeCrud($request);
  
        return $redirect_location;
    }
```

### What I did

How I can show a custom message with the base view ?

For example, for saying that the register exists.

![Captura de pantalla 2019-11-21 a la(s) 7 46 52 p  m](https://user-images.githubusercontent.com/10622765/69388708-db79a980-0c97-11ea-896c-1da928238cdd.png)

Thank you

**Comment by pxpm** [comment]
Hello @ingeday 

I have already replied to you in gitter. And is there one of the appropriate channels to ask for this kind of help.

If you need something i am around :)

Best,
Pedro

**Comment by tabacitu** [comment]
Not sure what this is about, but [Widgets](https://backpackforlaravel.com/docs/4.0/base-widgets) can also be used to show stuff on a CRUD view.

But as @pxpm said - we keep Github for bugs and features, and this doesn't look like one, sorry @ingeday !
