### ISSUE TITLE
[5.0][Feature request] Templates in Fake Fields

### ISSUE THREAD

**Issue by andreidragomir** [Laravel-Backpack/CRUD#2258]
Hi,
First of all congratulation for this awesome CMS. I've worked a lot with CodeIgniter and now I moved to Laravel. I've been searching on Laravel a CMS that has the features and easiness of FuelCMS and until now I think Backpack is the closest. But still is a very nice feature on FuelCMS that is missing from Backpack: Templates in Forms (https://docs.getfuelcms.com/general/forms#template)
I used that feature A LOT in my projects and I didn't find it in any CMS in Laravel...
It will be very nice to find this in Backpack CRUD - Fields as a more complex Fake Field. All the information from that field will be store as JSON.
Thank you!

**Comment by pxpm** [comment]
Hello @andreidragomir 

Sorry for late response. I think i don't fully understand what you mean by templates? Maybe something related to: #2266 ?

Best,
Pedro

**Comment by tabacitu** [comment]
Yup - I think that's exactly our "repeatable" field (aka multiply; aka matrix; aka "template" now I guess). We're currently working on making it compatible with all our other field types. 

Thank you for the suggestion, we're on it! 😄
