### ISSUE TITLE
image field 

### ISSUE THREAD

**Issue by flexelektro** [Laravel-Backpack/CRUD#2259]
# Bug report
image field is broken due to wrapper is missing attribute `data-init-function="bpFieldInitCropperImageElement"`

### What I did

added 
```
 $this->crud->addField(
            [
                'label' => "Teaser Image",
                'name' => "teaser_image",
                'type' => 'image',
                'upload' => true,
                'crop' => true,
                'aspect_ratio' => 1
            ]
        );
```
 in crud-controller

### What I expected to happen

a working image field

### What happened

i can not add images

### What I've already tried to fix it

adding missing attribute data-init-function="bpFieldInitCropperImageElement" which provides a solution.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### LARAVEL VERSION:
laravel/framework                         v6.5.2     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                             4.0.21     Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                       2.0.5      Generate files for laravel projects
backpack/menucrud                         2.0.2      An admin panel for menu items, using Backpack\CRUD on Laravel 6.
backpack/pagemanager                      2.0.2      Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
webfactor/laravel-backpack-instant-fields 3.0.1      Instant fields to create/edit/delete related entities on the fly in Laravel Backpack

```

**Comment by flexelektro** [comment]
This issue was created by commit 5124170215b660a0a281ce077173132b6d2e461d
I do not understand what the motivation was behind this...

**Comment by pxpm** [comment]
Hello @flexelektro .

Thank you very much for spoting this. And i am sorry for any inconvenience it caused. 

What is wrong you already figured it out: `data-init-function="bpFieldInitCropperImageElement"` in wrapper attributes is the solution, function name was wrongly typed and sliped when reviewing the PR. 

I did it and missed the changing name when updating the field operation. :(

The motivation behind this PR's is explained in this issue: #2188 

I am sending a PR to fix this, @tabacitu will merge asap. 

Thanks again, and sorry for that. 

Best,
Pedro

**Comment by flexelektro** [comment]
Hello @pxpm , and thank you for your fast reaction.
I am also a bit sorry, for my tone, as i reacted too quickly without understanding that data-init-function was in fact still added as attribute by `$field['wrapperAttributes']`

Thanks for changing this.

**Comment by pxpm** [comment]
No problem at all @flexelektro 

When something is working and suddenly brokes it is not the best of the feelings. 

You did nothing wrong man, i am the one to blame on this one. 

Happy you came foward to report it. 

Best,
Pedro

**Comment by tabacitu** [comment]
@pxpm I've just merged and tagged the fix - thank you! 

A ```composer update``` should fix it for you @flexelektro . Thank you for a perfect bug report. I wish all reports were this clear, and all bugs this easy to fix :-)
