### ISSUE TITLE
crud problem

### ISSUE THREAD

**Issue by youcef-dz35** [Laravel-Backpack/CRUD#2263]
# Bug report
hello guys I have problem with creating CRUDs it worked just fine in the first tow of them but when
I tried to create more CRUDs I stumbled on an error 405 and when I tried to find out what happened I saw this link http://stock.dz/admin/new_cat/search? is red how can I fixe it

**Comment by pxpm** [comment]
Hello @youcef-dz35 .

This is a general support question and we try to keep github to bug/features only. Go ahead to stackoverflow or our gitter channel to get some help on this topics.

You might want to check your laravel.log to see the real error happening in search function.

Best,
Pedro

**Comment by tabacitu** [comment]
@youcef-dz35 usually clicking the red link in your Developer Console also shows the actual output of the page. There you should be able to see what went wrong.
