### ISSUE TITLE
[4.0][BUG] The select2_from_ajax field does not save a null value when the column is nullable and the old value is removed

### ISSUE THREAD

**Issue by nahuelmino** [Laravel-Backpack/CRUD#2264]
# Bug report

### What I did

I have a Product that has a `select2_from_ajax` field, which is linked to a nullable column. This field had a value set, but I wanted to change it to null by clicking on the "Clear" button that appears at the end of the field. I clicked "Clear" and then saved the form.

### What I expected to happen

After saving the form, this column should have `null` as the value, and on the panel it should display a '-' on the table.

### What happened

After saving the form, the column had the same value as before (didn't change).

### What I've already tried to fix it

Looked through the `select2_from_ajax.blade.php` to see if I could find something that can give me a hint at what's going on, but I had no luck there.

However, I saw that after clicking on "Clear", the old `<option>` of the `<select>` element was still there, and had the property `selected` as `true` (same as the first `<option>` which has no value). When dumping the request to see what is being sent, the field had the old value still.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

Laravel Framework version: 6.5.2
Backpack CRUD version: 4.0.22
PHP version: 7.2.9
MySQL version: 5.7.23

Hopefully this made sense. Thank you for the hard work!

**Comment by pxpm** [comment]
Hello @nahuelmino 

Thank you very much for reporting this. 

I submited a PR #2267  that I think will solve this issue and some other minors.

If you have time, give it a look, test in your app and give us feedback. (It's just one file changed, just copy the whole PR file to your APP to test).

It will really help us on testing more user scenarios. :+1: 

I am going to close this issue so any discussion should be addressed in the PR.

If you feel this should be re-opened please be our guest, sometimes we are wrong :)

Best,
Pedro
