### ISSUE TITLE
[4.x] Mutator not hit on checkbox field

### ISSUE THREAD

**Issue by GrigoreAlexandru** [Laravel-Backpack/CRUD#2269]
# Bug report

### What I did

Make a checkbox field

```
            [
                'name' => 'probation',
                'type' => 'checkbox',
                'label' => 'On Probation',
                'tab' => 'Info'
            ],
```

Make a mutator:

```
    public function setProbationAttribute($val)
    {
        dd($val);
    }
```

### What I expected to happen

Mutator should've been called

### What happened

Mutator is not called, the edit request finishes successfully (success msg)

### What I've already tried to fix it

I've narrowed it down to the checkbox field, other field work correctly, I did try to change the attr name.

### Backpack, Laravel, PHP, DB version
Laravel 6, php 7.2, Backpack 4

The solution I found was to override the update method:

```
    public function update()
    {
        $request = $this->crud->validateRequest();
        $user = BackpackUser::find($request->id);
        $user->probation = $request->probation;
        $user->save();
        return $this->traitUpdate();
    }
```

**Comment by pxpm** [comment]
Hello @GrigoreAlexandru .

Thanks for reporting it, but i am afraid i could not reproduce it.

```
$this->crud->addField([
                'name' => 'trycheck',
                'type' => 'checkbox',
                'label' => 'On Probation',
                'tab' => 'Simple'
            ]);

//model

public function setTrycheckAttribute($value) {
        dd($value);
    }

```

>Add Trycheck to $fillable

Expected 0 or 1 returned from dd();

Maybe you forget about the fillable part ? 

Let me know how it goes so we can close this if it confirms it's not a bug.

Best,
Pedro

**Comment by GrigoreAlexandru** [comment]
@pxpm 

Ugh, you are right ! I forgot I was using a different name in the fillable array, definitely not a bug!
Thanks a lot!
