### ISSUE TITLE
Unable to upload file in local environment

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#2271]
# Bug report

### What I did

Create a simple upload field (or multiple) with this in my controller 

`[   // Upload
'name' => 'image',
'label' => 'Image',
'type' => 'upload',
'upload' => true
],`

### What I expected to happen

Upload the file

### What happened

The destination page is an ERR_FAILED. 
No errors iun the dev console or Laravel
No file is uploaded at all

### What I've already tried to fix it

php artisan storage:link
Verify if directories exists
Try differents disks 'public', 'local'
If I comment the field it's working

### Backpack 4.0.2, Laravel 6.6, PHP 7.2

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.6.0   The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.22   Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5    Generate files for laravel projects
backpack/permissionmanager            5.0.2    Users and permissions management interface for Laravel 5 using Backpack CRUD.

**Comment by tabacitu** [comment]
@t-prod the uploading isn't done automatically - you have to do that using a mutator in your model. Did you do that, as instructed in [the ```upload``` field docs](https://backpackforlaravel.com/docs/4.0/crud-fields#upload)?

**Comment by pxpm** [comment]
Hello @t-prod 

I am sorry, but without any info from logs/app debug i could not be of many help.

In general the upload field is working, __usually__ if it's broken you will have errors on network tab (in request) or in laravel.log.

Check if you have your app set to local and debug enabled. Try catching the request in controller before saving. 

Best,
Pedro

**Comment by t-prod** [comment]
Sorry for that. I have a misconfiguration in config/filesystem.php. I was unable to have an error message ;)
Everything is working fine and sorry again for the false positive issue.
