### ISSUE TITLE
How to render fields from a pivot table in a CRUD ?

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#2277]
# Bug report

### What I did

Display tabs from Model named Product. Product has a pivot table with User (product_user and many to many relationship).

### What I expected to happen

I would like to set fields from the pivot table in Product CRUD fake fields 

### What happened

Nothing I try to get the pivot table values and set values on fake fields

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.6.0   The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.22   Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5    Generate files for laravel projects
backpack/permissionmanager            5.0.2    Users and permissions management interface for Laravel 5 using Backpack CRUD.

**Comment by pxpm** [comment]
Hello @t-prod .

Sorry but i cannot be much help here. I think it's better to ask this kind of questions in gitter or slack. 
Also it would help alot if you can provide code, like relations, field definition, what error are you getting etc. 

It would help who tries to help you :)

If you find any bug feel free to report it using our bug report template :+1: 

Best,
Pedro
