### ISSUE TITLE
page_or_link Not saving to extras/fake field

### ISSUE THREAD

**Issue by tuxdalinuxpenguin** [Laravel-Backpack/CRUD#228]
I am currently using the page_or_link to save a link to the extras field, it only appears to save the page_or_link which would be Page, Internal or External links. It does not save the page_id or the link. I am using the PageManager to handle the different views I need and since some require more or less links depending on the template I figured that would be the best way to handle it. I do not see anything regarding the page_id or the link field in the documentation.

Below is the generated output:
![generated-output](https://cloud.githubusercontent.com/assets/17648612/20143119/562bef0c-a65d-11e6-81cf-4d8985d4a05c.JPG)

**Comment by OwenMelbz** [comment]
Hi @tuxdalinuxpenguin as theres been no movement on this, I can just suggest running a `composer update` to make sure everything is up to date.

If you're still having issues then feel free to come back!
