### ISSUE TITLE
[4.0][Bug] isColumnNullable throws error on column not found

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#2285]
# Bug report

### What I did

Added a field to crud and setup a mutator to manipulate the field and insert data in other table. 

### What I expected to happen

My mutator runs smooth! :+1: 

### What happened

isColumnNullable() is throwing error when column does not exist in database. 

### What I've already tried to fix it

Hey there guys. Dunno if i am misunderstand something, but `isColumnNullable()` should not throw error if column does not exist in database right ? I could add a field to crud and don't have a field in this table to store it ? Nor in any table, i could just want to setup some cron job or send some email or wtv. 

```

    public static function isColumnNullable($column_name)
    {
        // create an instance of the model to be able to get the table name
        $instance = new static();

        $conn = DB::connection($instance->getConnectionName());
        $table = Config::get('database.connections.'.Config::get('database.default').'.prefix').$instance->getTable();

        // MongoDB columns are alway nullable
        if ($conn->getConfig()['driver'] === 'mongodb') {
            return true;
        }

        // register the enum, json and jsonb column type, because Doctrine doesn't support it
        $conn->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', 'string');
        $conn->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('json', 'json_array');
        $conn->getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('jsonb', 'json_array');
        try {
            //check if column exists in database
            $conn->getDoctrineColumn($table, $column_name);
            return ! $conn->getDoctrineColumn($table, $column_name)->getNotnull();
        } catch (Exception $e) {
            return true;
        }
    }
```
So i changed this function to a try block. In case the try fails (column does not exist in database) we return true for nullable. We are not checking, nor we require that the column exists in database, that's a developer option right ? 

Best,
Pedro

**Comment by tabacitu** [comment]
I agree! It should not throw an error - just fall back to ```"nullable" => true``` if no column is there.

Question: **what if there's a mutator to a _real_ database column?** What would ```isColumnNullable()``` return then?

**Comment by pxpm** [comment]
@tabacitu i think i don't really get your question but here is my answer from my understanding:

```
return ! $conn->getDoctrineColumn($table, $column_name)->getNotnull();
```

isColumnNullable does not care about about mutator or whatever. It's all about database column. isColumnNullable just checks if the column in __DATABASE__ is nullable. 

We are throwing error if it does not exists.
 
If it exists this function will return just that info, is nullable in database or not. 

We are not accessing any `->attribute` to fire mutators or whatever here. If there is a mutator it will fire upon attribute set/get, does not matter if column is nullable or not.

Best,
Pedro

**Comment by tabacitu** [comment]
Great! So it's just a matter of not throwing an error. 

**Can you please help put together a PR to fix this?**

Cheers!
