### ISSUE TITLE
[4.0][FEATURE REQUEST] Allow developers to configure LOGO link

### ISSUE THREAD

**Issue by azaricstefan** [Laravel-Backpack/CRUD#2289]
# Proposal
File on this path: backpack/crud/src/resources/views/base/inc/**main_header.blade.php** line 6 should be modifiable.

Developers would like to modify this URL in logo in some cases.

Line 6: 
  `<a class="navbar-brand" href="{{ url('') }}">`

### What I did

Changed it to this:
  `<a class="navbar-brand" href="{!! config('backpack.base.project_logo_url') !!}">`

Defined URL in base.php under key backpack.base.project_logo_url and put URL which I want to.

If you think this could be useful, I can create this small PR.

**Comment by pxpm** [comment]
Hello @azaricstefan 

If it's usefull to you, there is already some need for it. But i really never saw anyone else asking for that feature. 

After you grab my attention i could say i agree with you. I don't want my user to leave admin panel upon logo click, i want it to go to the dashboard. 

If you have the time, please provide a PR, also why you changed from `{{ ]}}` escaped to `{!! !!}` non-escaped ?

Best,
Pedro

**Comment by azaricstefan** [comment]
@pxpm have a look and give some feedback. 

It was just copy paste, I used escaped of course. 👍

**Comment by AbbyJanke** [comment]
I remember this being discussed before and if I remember correctly the decision was that the blade files could easily be overwritten and was to avoid unnecessary configurations. I personally have my admin panel as the main root so the current URL structure is perfect for me.

**Comment by azaricstefan** [comment]
Those are 2 different approaches. I wouldn't discuss that at all.

We should give all users an option to change that behaviour.

I don't want to change vendor files just because of 1 line which is hard coded to a page which someone said "this works for me".

If it's configurable I will leave it as configurable.
This way it can work for both approaches and not just yours.

Thanks!

**Comment by tabacitu** [comment]
Totally agree - it's something I've needed on [demo.backpackforlaravel.com](http://demo.backpackforlaravel.com) but haven't gotten to solving it yet. Thank you @azaricstefan & @pxpm ! PR #2292 is now merged!
