### ISSUE TITLE
Relationship issue... i think

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#229]
Hello, 

i did this over and over again and something is wrong or missing. i have made a fresh install, added two CRUD models and tried to make a relationship between them using pivots...

this is the commands list:
```
php artisan make:migration:schema create_teams_table --schema="name:string:unique" --model=0
php artisan make:migration:schema create_players_table --schema="name:string:unique" --model=0
php artisan make:migration:pivot players teams
php artisan migrate
php artisan backpack:crud team
php artisan backpack:crud player
```
this is what i added in the Player model:

```
public function teams() {
        return $this->hasMany('App\Models\Team');
    }
```
and this is the config in the controller:

```
$this->crud->addFields([
            [
                'name' => 'name',
                'label' => 'Player\'s Name'
            ],
            [
                'name' => 'teams',
                'label' => 'Favorite team',
                'type' => 'select2_multiple',
                'entity' => 'teams', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model' => "App\Models\Team", // foreign key model
                'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
            ]
        ], 'update/create/both');
        // $this->crud->removeField('name', 'update/create/both');
        // $this->crud->removeFields($array_of_names, 'update/create/both');

        // ------ CRUD COLUMNS
        // $this->crud->addColumn(); // add a single column, at the end of the stack
        $this->crud->addColumns([
            [
                'name' => 'name',
                'label' => 'Player\'s Name'
            ],
            [
                'name' => 'favorite_team',
                'label' => 'Favorite team',
                'type' => 'select2_multiple',
                'entity' => 'teams', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model' => "App\Models\Team", // foreign key model
                'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
            ]
        ]); // add multiple columns, at the end of the stack
```

and this is the error: 

![image](https://cloud.githubusercontent.com/assets/7759267/20179852/a8a22fa4-a760-11e6-8e0f-74789bab94ba.png)

**Comment by indra1** [comment]
Does it work like this?

$this->crud->addField([
                'name' => 'name',
                'label' => 'Player\'s Name'
                'type' => 'text'
]);
$this->crud->addField([
                'name' => 'teams', // the method that defines the relationship in your Model
                'label' => 'Favorite team',
                'type' => 'select2_multiple',
                'entity' => 'teams', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model' => "App\Models\Team", // foreign key model
                'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
            ]
        ], 'update/create/both');


        // ------ CRUD COLUMNS
      
        $this->crud->addColumn([
            [
                'name' => 'name',
                'label' => 'Player\'s Name',
               'type' => 'text'
            ],
);
$this->crud->addColumn([
                'name' => 'teams',
                'label' => 'Favorite team',
                'type' => 'select2_multiple',
                'entity' => 'teams', // the method that defines the relationship in your Model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'model' => "App\Models\Team", // foreign key model
                'pivot' => true, // on create&update, do you need to add/delete pivot table entries? no
            ]
        ]); 

Also can I nee the migrations for these tables?

**Comment by AurelDragut** [comment]
@indra1, thanks for your time, but from what i can see you just splitted the fields (am i missing something?). As you may see in the command list i only used two tables containing just names for the start, the rest of the information can be added later.

**Comment by indra1** [comment]
I also changed the second column. Please try this. I got this error a lot of times before and every time was something i misspelled. If you have the name column then there should be no issue.

**Comment by AurelDragut** [comment]
Yeah, i allready did that in Team Model. And, yes, field name change did the job. Now it works like a charm.

**Comment by AurelDragut** [comment]
It seems some of the field types need some improvements, i will try tio help on that.

**Comment by indra1** [comment]
You can create your own fields. Just add yourfield.blade.php to resources/view/vendor/backpack/crud/fields

**Comment by AurelDragut** [comment]
Yeah i know :) (now its time to develop these controllers :) )
