### ISSUE TITLE
[4.0][Bug] Stale request in feature testing

### ISSUE THREAD

**Issue by abm-devmonk-purple** [Laravel-Backpack/CRUD#2293]
# Bug report

### What I did

I created a `Feature` test against a `CrudController`. The test performed two requests to simulate an edit. For example:

```php
    public function testUpdateEmail()
    {
        $user = factory(User::class)->create();
        $id = $user->id;
        $this->actingAs($user)->get("/users/$id/edit")->assertOk();
        $data = [ 'id' => $id, 'email' => 'a@b.com' ];
        $this->put("/users/$id", $data)->assertRedirect('/users');
        $this->assertEquals('a@b.com', $user->fresh()->email);
    }
```

### What I expected to happen

The test to work.

### What happened

The test reporting that the date wasn't being updated. After investigation, the `CrudPanel` in the `CrudController` was using the same `Request` object from the previous request.

### What I've already tried to fix it

I'm creating a pull request to address the problem.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
PHP 7.3.12-1+0~20191128.49+debian10~1.gbp24559b (cli) (built: Nov 28 2019 07:36:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12-1+0~20191128.49+debian10~1.gbp24559b, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.7.0             The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.23             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5              Generate files for laravel projects
```

**Comment by tabacitu** [comment]
Thank you for surfacing this, and taking the time to put together the PR @abm-devmonk-purple ! It's great. Let's move the conversation inside the PR please.
