### ISSUE TITLE
Setting default page length does nothing.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/CRUD#2317]
# Bug report

### What I did

I attempted to set the default page length from within the listOperation via
`$this->crud->setDefaultPageLength(100);`

### What I expected to happen
The list view to show 100 results.

### What happened
Nothing changed. This table has over 200k results so it should show 100 without a problem.

### What I've already tried to fix it
I tried placing this call in other areas i.e. setup()

### Backpack, Laravel, PHP, DB version
When I run ```php artisan backpack:version``` the output is:

PHP 7.4.0 (cli) (built: Nov 28 2019 07:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v5.8.35            The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.23             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5              Generate files for laravel projects

**Comment by tabacitu** [comment]
Hi @selected-pixel-jameson ,

I've just tested it and it worked fine, both:

```php
    public function setup()
    {
        // ..
        $this->crud->operation('list', function () {
          $this->crud->setDefaultPageLength(25);
        });
    }
```
and
```php
    public function setupListOperation()
    {
        $this->crud->setDefaultPageLength(25);
     }
```

**I bet it's a caching issue** because you have ```'persistentTable' => true,``` in your ```config/backpack/crud.php``` (which is the default). **Please try it in an incognito window - the page length should be 100 there.** Let me know if it's not.

Cheers!

PS. To bust the cache you can also set the ```persistentTable``` config I mentioned above to ```false```, refresh, then set it back to ```true```.

**Comment by selected-pixel-jameson** [comment]
Clearing the cache fixed the problem. Thank you.

**Comment by Mageistral** [comment]
Hi, for the record, I've just done
`protected function setupListOperation()
    {
        $this->crud->setPersistentTable(false);
        $this->crud->setDefaultPageLength(50);
    }
`
But this way, you loose customization by the user on that table.

**Comment by pxpm** [comment]
> Hi, for the record, I've just done
> 
> ```
> protected function setupListOperation()
> {
>     $this->crud->setPersistentTable(false);
>     $this->crud->setDefaultPageLength(50);
> }
> ```
> 
> But this way, you loose customization by the user on that table.

I'd suggest you clear your browser caches while working with this settings as they interact with information stored on the user browser storage. 

It's the browser caches, not the application caches (that shouldn't be enabled on development anyway). 

Let me know if you are still experiencing issues. 

Cheers
