### ISSUE TITLE
ViewComposer not working with Dashboard template per documentation. 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/CRUD#2318]
I'm attempting to register a View Composer for the Laravel Backpack libraries dashboard template, which is located at `resources/views/vendor/backpack/base/dashboard.blade.php` within my project. 

I'm doing so via 

```
View::composer(
   'vendor.backpack.base.dashboard', 'App\Http\View\Composers\DashboardComposer'
);
```

I know that the Composer is working correctly, because if I change the template to

```
View::composer(
   '*', 'App\Http\View\Composers\DashboardComposer'
);
```

the dashboard page loads correctly with the variable I'm setting in the composer. 

I've tested to see if the view reference is correct by using

```
if (View::exists('vendor.backpack.base.dashboard')) {
    //
}
```

which returns successfully.

I'm registering my provider, ```App\Providers\ViewServiceProvider::class,``` within the config as the very last provider. 

PHP 7.4.0 (cli) (built: Nov 28 2019 07:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v5.8.35            The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.23             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5              Generate files for laravel projects

**Comment by pxpm** [comment]
Hello @selected-pixel-jameson 

I think this is not related to backpack, you should have a look at views from packages in laravel. [overriding package views](https://laravel.com/docs/6.x/packages#views)

To correct your problem you should use the view path as follow: (not necessarily use it as callback if you have some file that is the view composer): 
```
View::composer('backpack::dashboard', function ($view) {
            return $view->with('test','test');
        });
```
For future reference this kind of questions should be asked in other channels like gitter or stackoverflow. We keep github for bugs/features. 

Best,
Pedro
