### ISSUE TITLE
Polymorphic OneToMany relationship

### ISSUE THREAD

**Issue by Mamatlatomate** [Laravel-Backpack/CRUD#2327]
I have some troubles in a Polymorphic OneToMany relationship. Here is the scenario :

I have 3 entities : Offers, Sectors, Services All of them can have multiple steps. Models are OK but I have some trouble in how to use widget to create the form. I want to have a form which give the possibility to the user to choose which type of entity is linked to the step and which entity is used.

Here are my models

```
// Same models for Service and Sector

Class Offer extends Model
{
    // Fillable are OK

    public function steps()
    {
        return $this->morphMany(Step::class, 'stepable');
    }
}
```
```
Class Step extends Model
{
    // Fillable are OK

    public function stepable()
    {
        return $this->morphTo();
    }
}
```

Simple OneToMany polymorphic ... But I really don't know how to do my form to create this kind of relation. ManyToMany relationships like "taggable" case is OK to me but I don't succeed in this one :(

Thanks a lot for all your help.

Mamat

**Comment by pxpm** [comment]
Hello @Mamatlatomate 

This is how i would go for it:

- Create a custom field. (Use select as example, select2_nested to check how it is done in JS).
- Give the available options (entities) in the first select.
- On change, query some api endpoind with the selected entity to get the available options for second select.
- Get the form submited data and manually create the relations on controller.

Hope it helps. 
Best,
Pedro
