### ISSUE TITLE
Error when public/uploads folder already exists on Windows install

### ISSUE THREAD

**Issue by lcloss** [Laravel-Backpack/CRUD#2338]
# Bug report

### What I did

```php artisan backpack:install```

### What I expected to happen

Installation should proceed normally.

### What happened

Error because public/uploads folder already exists.
```Symfony\Component\Process\Exception\ProcessFailedException  : The command "" failed.```

### What I've already tried to fix it

Fix this error on src/app/Console/Install.php on method executeProcess to not execute command if command is empty.
I can make a PR to fix this.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.3.7 (cli) (built: Jul  3 2019 14:34:10) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.9.0      The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                2.0.2       Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         dev-develop Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5       Generate files for laravel projects
```

**Comment by pxpm** [comment]
Hey @lcloss 

Thanks for reporting in. 
I have sent a PR to fix this issue, sorry for any inconvenience. 

Best,
Pedro

**Comment by lcloss** [comment]
Thank you, @pxpm !

**Comment by tabacitu** [comment]
Thank you @lcloss & @pxpm . I've just merged the fix into ```master```. It'll be available later today with a ```composer update```, in 4.0.31, after I merge a few more non-breaking PRs and tag it.

Thanks again. Cheers!
