### ISSUE TITLE
[BUG][4.0] HTML5 Validation not applied on save actions dropdown items.

### ISSUE THREAD

**Issue by shealavington** [Laravel-Backpack/CRUD#2339]
# Bug report

Changing the primary save option to another other than the current primary, browser validation isn't ran.

### What I did

I have a field that's required, when I click the primary action "Save and back" I correctly get warned to "Please fill in this field" (by the browser), however, when I change that primary action through the dropdown to "Save and edit this item" or "Save and add new", the browser validation doesn't appear to be run and I get redirected to a SQL error stating that the field can't be null.

Error Message:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null
```

Field Setup:
```
        $this->crud->addField([
            'name' => 'name',
            'label' => 'Friendly Name (only seen by admins)',
            'type' => 'text',
            'wrapperAttributes' => [
                'class' => 'form-group col-md-6',
            ],
            'attributes' => [
                'required'=>'required',
            ]
        ]);
```

### What I expected to happen

Clicking either the primary "Save and back" option or the secondary "Save and edit" or "Save and new" options should all run the browser validation.

### What happened

SQL error as noted above.

### What I've already tried to fix it

Currently I've not attempted a fix, I'll PR if I find one.

### LARAVEL VERSION:
laravel/framework                     v6.7.0     The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.23
backpack/pagemanager                  2.0.2
chrome                  79.0

**Comment by pxpm** [comment]
Hello @shealavington 

Thanks for reporting it, i could confirm this bug. 

The problem relies on the fact that the actions inside the dropdown are not "really" submit buttons like the first option (no mater if it's save and back or save or new), the first selected option will always be a `button type submit` and the others are anchor tags.

I am submiting a PR right way to fix this issue. 

Thanks again. 

Best,
Pedro

**Comment by tabacitu** [comment]
Thank you @shealavington for reporting this, and @pxpm for fixing it. Let's close this issue and move the conversation to PR https://github.com/Laravel-Backpack/CRUD/pull/2340 please.

Cheers!
