### ISSUE TITLE
Any way to translate / rename model in the backend?

### ISSUE THREAD

**Issue by tommica** [Laravel-Backpack/CRUD#2354]
# Bug report

### What I did

I have my models names in english, but the sites language is in another - is there a way to translate / rename the model, without having to change the file name?

### What I expected to happen

-

### What happened

-

### What I've already tried to fix it

    $this->crud->setHeading('custom model name')

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
laravel/framework                     v6.10.0   The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.31    Quickly build an admin in...
backpack/generators                   2.0.6     Generate files for larave...

**Comment by tommica** [comment]
Closing issue, as this seems to be in fact the wrong place to ask - will try gitter

**Comment by tabacitu** [comment]
@tommica - in your CrudController (ex: ProductCrudController) you'll notice in the ```setup()``` method you have something like:

```php
        $this->crud->setEntityNameStrings('product', 'products');
```

Change those strings to your translated strings, and Backpack will use those everywhere inside your CRUD.

Hope it helps.
Cheers!

**Comment by MeerKatDev** [comment]
What about the menu on the left? It doesn't translate it there..

**Comment by tabacitu** [comment]
@MeerKatDev you can use Laravel's `__('translation.string')` helper in your `sidebar_content.blade.php` file. What I mean is that wherever you would write out "Product" for example, just write out `__('your_translation_file_name.product')` and Laravel will translate it to the current language.

There reasons this isn't done by default is that _translatable_ admin panels are very _very_ rare. They're only really needed when the admins themselves speak multiple languages and do NOT speak a common language. Which is rare. We've avoided adding this extra bit of complexity to _all_ admin panels, just to account for this small number of projects, which can easily add the logic themselves using a search&replace.

**Comment by MeerKatDev** [comment]
That's ok, thank you very much. It'd be still good adding it to the docs :)
