### ISSUE TITLE
[4.0][Package conflict] El-Finder install error on PHP 7.4

### ISSUE THREAD

**Issue by lamzaks** [Laravel-Backpack/CRUD#2360]
# Bug report

### What I did

Installed backpack

### What I expected to happen

Will install backpack

### What happened

Error
![image](https://user-images.githubusercontent.com/13777865/71987811-8a1d7d80-3237-11ea-92c5-fd45f8ed6a6b.png)

### Backpack, Laravel, PHP, DB version
Backpack for Laravel 4.0
Laravle 6.2 
PHP 7.4

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @lamzaks 

Thanks for reporting. I think the error is in el-finder code not in backpack. Could you try install without el-finder?

I think backpack don't have problems with php 7.4, but el-finder does (atleast the version we are using). It migth worth to check if that is the case.

Once again, thanks for bring this to our attention.
Best,
Pedro

**Comment by lamzaks** [comment]
Installation without El-Finder worked! Case closed! Thanks everyone! :)
![image](https://user-images.githubusercontent.com/13777865/72100521-72bfbc80-332b-11ea-81c1-5892b411c936.png)
