### ISSUE TITLE
Table with only one column and it's a unique key - how to use with the Backpack CRUD?

### ISSUE THREAD

**Issue by dantheman99** [Laravel-Backpack/CRUD#2361]
I have created a table/migration with one column. The column is unique. The up() method in the Migration:

```
 public function up()
 {
        Schema::create('titles', function (Blueprint $table) {
            $table->string('title')->unique();
            $table->timestamps();
        });
    }
```

Then ran `php artisan backpack:crud title`.

When I visit the Titles page in admin, I get an error "Error loading page. Please refresh the page.".

I've tried playing around with the protected attributes in the model. I set `$primaryKey` to `'title'`. Now I don't get the error when I visit the Titles page, but `0` is shown in the Title column for all the titles in the list.

**Comment by dantheman99** [comment]
My fault sorry, not a bug in Backpack.

I overlooked a Laravel-native thing. I needed to set add `public $incrementing = false;` to the model - this needs to be done for non-AI primary keys for models in Laravel.

**Comment by tabacitu** [comment]
Indeed, ```public $incrementing = false;``` in your model is a MUST when using Eloquent with non-integer primary keys! Glad you figured it out, sorry we couldn't answer in time.

Cheers!
