### ISSUE TITLE
[4.X][Request] Ckeditor upload image directly from computer not el-finder connector

### ISSUE THREAD

**Issue by tifaahmed** [Laravel-Backpack/CRUD#2368]
ckeditor don't work like the original website 
https://ckeditor.com/ckeditor-4/demo/#article
 upload image  from the computer  not working in backpack package
### What I did

        $this->crud->addFields([
        ['name'  => 'subject_ar','label' => ' الموضوع  ','type'  => 'ckeditor',]    
        ]);

### What I expected to happen

![2020-01-12_140951](https://user-images.githubusercontent.com/35181458/72218614-6616b080-3545-11ea-8a22-66fc2110a3a1.png)

### What happened

![2020-01-12_141048](https://user-images.githubusercontent.com/35181458/72218615-7169dc00-3545-11ea-809c-f2e174ba37c9.png)

**Comment by pxpm** [comment]
Hello. 

Thanks for reporting. Can you set your crud in English? Or it's a design fault only?

Did you published crud assets? It's an upgrade? What version are you running?

Best,
Pedro

**Comment by tifaahmed** [comment]
i'm using  backpack version 4 with laravel version 6  
i created new project again now i get the same page with no button  to  upload image 
i don' know hot to  set my crud to  English it always  open in  Arabic 
 i tried  ->composer update ,
when i tried -> php artisan backpack:version

### PHP VERSION:
PHP 7.3.12 (cli) (built: Nov 19 2019 13:58:02) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
'grep' is not recognized as an internal or external command,
operable program or batch file.


   Symfony\Component\Process\Exception\ProcessFailedException  : The command "composer show | grep "laravel/framework"" failed.

Exit Code: 255(Unknown error)

Working directory: C:\xampp\htdocs\free\blog

Output:
================


Error Output:
================
'grep' is not recognized as an internal or external command,
operable program or batch file.


  at C:\xampp\htdocs\free\blog\vendor\backpack\crud\src\app\Console\Commands\Version.php:62
    58|         });
    59|
    60|         // executes after the command finishes
    61|         if (! $process->isSuccessful()) {
  > 62|             throw new ProcessFailedException($process);
    63|         }
    64|     }
    65| }
    66|

  Exception trace:

  1   Backpack\CRUD\app\Console\Commands\Version::runConsoleCommand("composer show | grep "laravel/framework"")
      C:\xampp\htdocs\free\blog\vendor\backpack\crud\src\app\Console\Commands\Version.php:36

  2   Backpack\CRUD\app\Console\Commands\Version::handle()
      C:\xampp\htdocs\free\blog\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by tabacitu** [comment]
@tifaahmed you should be able to change the language of your app by making this change in your ```config/app.php``` file:

```diff

    /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

-    'locale' => 'ar',
+    'locale' => 'en',
```

I'm afraid we can't debug this if you don't switch to English and re-send the screenshots, neither @pxpm nor I read Arabic, and we have no idea what's written on those buttons to compare with our screens 😄 

Cheers!

**Comment by tifaahmed** [comment]
my code 
![2020-01-15_191317](https://user-images.githubusercontent.com/35181458/72455248-1d702900-37cb-11ea-8269-08e66231c8af.png)

the result i get 
![2020-01-15_190922](https://user-images.githubusercontent.com/35181458/72455273-282abe00-37cb-11ea-9d2a-13151bf59075.png)

the wanted result (from ckeditor  website     https://ckeditor.com/ckeditor-4/demo/#article 
![2020-01-15_191045](https://user-images.githubusercontent.com/35181458/72455326-3bd62480-37cb-11ea-8dd8-10b0a3c41841.png)

**Comment by tifaahmed** [comment]
i get elfinder  wendow 
![2020-01-15_192050](https://user-images.githubusercontent.com/35181458/72455893-4c3acf00-37cc-11ea-8ca9-c8eeb609a553.png)

but i want upload image wendo 
![2020-01-15_191936](https://user-images.githubusercontent.com/35181458/72455945-6379bc80-37cc-11ea-8680-c2eee4085cb2.png)

**Comment by pxpm** [comment]
Now i got it :)

Thanks for clarification. 

Atm, the only solution i can think of is copy the ckeditor field from vendor to your app resources and adjust your ckeditor settings there. That way your field changes will not be un-done when you update your backpack.

Best,
Pedro

**Comment by tabacitu** [comment]
Yup. [Here's a tutorial](https://www.itsolutionstuff.com/post/laravel-5-ckeditor-image-upload-exampleexample.html) on how you can code the Upload functionality in Laravel, for the CKEditor upload button. Haven't followed it myself, but I gave it a quick look and it seems ok.

Keep in mind that in order for this to work you also need to change the ckeditor config file, to tell it to NOT use elfinder for uploads, but your own implementation. And ckeditor tends to cache that file pretty heavily. So after you change the config file, try it in an incognito window instead. Or do Ctrl+R like a crazy person. Or clean the browser cache.

Hope it helps.
Cheers!

**Comment by tifaahmed** [comment]
I changed it. Thank you 
![2020-01-20_111126](https://user-images.githubusercontent.com/35181458/72713479-c923cb00-3b75-11ea-9f70-ce9765dbcf27.png)

**Comment by tabacitu** [comment]
Glad to hear that. Feel free to post about your experience doing that here. I'm sure others who want the same thing will be delighted if you help them out. Cheers!
