### ISSUE TITLE
Column not found: 1054 Unknown column

### ISSUE THREAD

**Issue by nistlrooy** [Laravel-Backpack/CRUD#237]
I have two table users and announcement(1-n).
in anouncement' model:
```
public function user()
{
        return $this->belongsTo('App\User','id','user_id');
}
```
in App\Http\Controllers\Admin\AnnouncementCrudController.php
```
$this->crud->addColumn
(
            [
                // 1-n relationship
                'label' => "author ", // Table column heading
                'type' => "select",
                'name' => 'user_id', // the column that contains the ID of that connected entity;
                'entity' => 'user', // the method that defines the relationship in your Model
                'attribute' => "name", // foreign key attribute that is shown to user
                'model' => "App\User", // foreign key model
            ]
        );
```
when goto url  'xx.com/admin/announcement'show error: 'ErrorException in Connection.php line 769: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.user_id' in where clause (SQL: select * from `users` where `users`.`user_id` = 8 limit 1)
but in users table,there is not user_id field , only id , and the 8 is the id of announcement , not user id.

who can tell me what's wrong with it ???

**Comment by indra1** [comment]
Unknown column 'users.user_id' in where clause This is what is wrong. Your column is user.id not user.user_id. 
this public function user()
{
        return $this->belongsTo('App\User','id','user_id');
}

can become 
public function user()
{
        return $this->belongsTo('App\User');
}
Also in the user model:
public function announcements()
{
        return $this->hasMany('App\Announcement');
}
what version of laravel are you using?

**Comment by nistlrooy** [comment]
thank you ,indra1! problem solved!!

**Comment by cgsaavedrac** [comment]
Estimados, me pueden ayudar, porque esto no me esta funcionando

$quotation = Quotation::whereColumn([
                    ['client_id', $request->client_id],
                    ['token', $request->_token]
                ])->get();

SQLSTATE[42S22]: Column not found: 1054 Unknown column '1' in 'where clause'

Siendo que las dos columnas si existen en la DB

**Comment by lloy0076** [comment]
@cgsaavedrac - asking on a closed issue is not terribly great etiquette, not using backticks or quoting the code just makes the code hard to read and, sadly, the lingua franca (ironically) seems to be English; although I do understand what you are saying.

I would try:

```
$quotation = Quotation::whereColumn([
['client_id', '=', $request->client_id],
['token','=', $request->_token]
])->get();
```

From what I can tell, the method that eventually adds where clauses for `whereColumn` needs the operator (i.e. the `=` or `!=` or whatever).
