### ISSUE TITLE
[3.6] searchLogic in attribute of a 1-1 relationship

### ISSUE THREAD

**Issue by kpapag** [Laravel-Backpack/CRUD#2373]
# Bug (maybe my mistake?) report

I have a model called User, and a model called UserApplications, related via 1-1 relation. In the UserApplicationsCrudController, i am trying to get the searchbar to work for user.name (from users table), and not the user_id of the (userapplications ) table.

### What I did

`$this->crud->with('user'); //eager loading`

`$this->crud->setColumns([
            [
                'label' => 'User',
                'name' => 'user.name',
                'type' => 'text',
                'orderable' => true,
                'orderLogic' => function ($query, $column, $columnDirection) {
                return $query->join('users', 'user_id', '=', 'users.id')
                ->orderBy('users.name', $columnDirection);
                },
'searchLogic'   => function ($query, $column, $searchTerm) {
                 $query->orWhere('user.name', 'like', '%'.$searchTerm.'%');
                 },
]`

### What I expected to happen

To get the search to work when typing the name, not the id of the user

### What happened

im getting 500 in network inspector, and the error pnotify

### What I've already tried to fix it

`'searchLogic'   => function ($query, $column, $searchTerm) {
                $query->join('users', 'user_id', '=', 'users.id');
                $query->orWhere('users.name', 'like', '%'.$searchTerm.'%');
                },`

`'searchLogic'   => function ($query, $column, $searchTerm) {
                 $query->orWhere('user_id', 'like', '%'.$searchTerm.'%');
                 },`

`'searchLogic' => true,`

`'searchLogic' => 'text'`

I cant get it to work with name attribute. However, orderable and orderLogic when sorting with name, works ok. If anyone can provide the simple answer that's driving me nuts, I'd be more than thankful!

### PHP VERSION:
PHP 7.3.5 (cli)

### MYSQL VERSION:
mysql  Ver 14.14 Distrib 5.7.26

When I run ```php artisan backpack:version``` the output is:

backpack/base                         1.1.13             Laravel Backpac...
backpack/crud                         3.6.33             Quickly build a...
backpack/generators                   1.2.7              Generate files ...
backpack/langfilemanager              1.0.26             An interface to...
backpack/logmanager                   2.3.27             An interface to...
backpack/menucrud                     1.0.14             An admin panel ...
backpack/newscrud                     2.1.10             An admin panel ...
backpack/pagemanager                  1.1.28             Create admin pa...
laravel/framework                     v5.8.36            The Laravel Fra...

**Comment by pxpm** [comment]
Hey @kpapag 

Thanks for raising this issue. 

I think there were some issues related to search logic that were found and corrected in V4.0. 

Unfortunatelly we have no way of mantaining two package versions so i don't think any fix will be pushed to 3.x anymore. (unless a security risk or something critical).

Updating to V4 has alot of benefits, apart from bug fixing/feature development. 

Apart from that, would be interesting knowing exactly what error are you getting in your laravel logs or console inspector. 

I am going to close this, but feel free to continue the discussion further or join us in some alternative channel like gitter. 

Best,
Pedro

**Comment by kpapag** [comment]
I did not ask for a fix or maintenance of an older version, rather some useful hints as to how to track the problem myself, which files are being used, etc, so maybe i can push a patch myself. That would be great.

PS some projects in production just don't have the luxury to be updated..unless the project was to update that project. In that case i would already use the v4.0.

Maybe @tabacitu can help me as to how can i track this down

Thanks.

**Comment by pxpm** [comment]
Hey @kpapag 

Sorry if my answer did not point you in the right direction. I just stated that this is probably fixed in v4 but the fix wont be pushed to v3. I didn't have bad intentions saying, but if i offended you in someway i am also sorry for that. 

I am here to help you and others. Hope I can help you on this, but as we use github as a issue tracker I pointed you out to a channel where we can have a chat about your problem and try to solve it. If it's still a bug in v4 we are going to fix it for sure.

Apologies apart, in my previous reply I asked about the error you are getting. We can start from there? 

Best,
Pedro

**Comment by kpapag** [comment]
Hello @pxpm 

I searched further and found the issue and solution, it was just bad documenting.

https://github.com/Laravel-Backpack/CRUD/issues/1114#issuecomment-349598290

So no problem on that part of search logic, even in v3.6.

Apology accepted, what bothered me was that your first answer was kind of automated-like but still, we all have bad days.

Cheers

**Comment by pxpm** [comment]
Hey @kpapag 

Happy you found the solution. I admit it was a kind of automated answer for two main reasons:

- It's for a version we are not suporting anymore.
- It's a question and we use github to track issues/features.

Anyway i have no intention in ofending you anysort of way, so thanks for the comprehension.

Best,
Pedro
