### ISSUE TITLE
[4.X][FEATURE REQUEST] Set custom header and footer for print

### ISSUE THREAD

**Issue by jualahmed** [Laravel-Backpack/CRUD#2378]
# question

**Comment by tabacitu** [comment]
@jackfruh what do you mean? Please give more details.

If you mean that you want something to show up in header/footer when the user does Ctrl+P to print the current page, you should be able to easily insert sections on the page using [Backpack Widgets](https://backpackforlaravel.com/docs/4.0/base-widgets). 

You can [create custom widgets](https://backpackforlaravel.com/docs/4.0/base-widgets#creating-a-custom-widget-type), one for your Print Header, one for your Print Footer. Where you'd use Boostrap's CSS classes:
- ```d-print-none``` - will hide the element when printing;
- in BS3 we had ```visible-print``` to show the element only when printing; don't know the exact class in BS4 but I'm sure there is one; I expect ```d-print-block``` to work;

Hope it helps. Cheers!

**Comment by jackfruh** [comment]
@tabacitu I think this was meant for @jualahmed

**Comment by tabacitu** [comment]
Oups 😄  You're right, sorry.

**Comment by zaghadon** [comment]
@tabacitu I want to know if it's possible to remove the Footer Credits, Handcrafted by Cristan Tabacitu. I'm using a Pro License and I'm deploying a live admin for our Organization, I want to know if the footer credit is optional and how I can override it or if any license clause forbids me.

**Comment by tabacitu** [comment]
Of course! Take a look at `config/backpack/base.php`. You'll find not only that, but a bunch of other configuration options!

**Comment by zaghadon** [comment]
Great, thanks for the Pointer Cristan.
