### ISSUE TITLE
create new field does not save the value in the database

### ISSUE THREAD

**Issue by marcoz2102** [Laravel-Backpack/CRUD#2379]
# Bug report

### What I did

hi I wanted to report a problem I can not save the valre in the database after creating the field.

\ Vendor \ backpack \ newscrud \ src \ app \ Http \ Controllers \ Admin \ ArticleCrudController.php

new field to insert description

`$ This-> crud-> addField ([
                     'name' => 'description',
                     'label' => 'Description',
                     'type' => 'text',
                     'placeholder' => 'Description meta tag`

when I go to insert or modify the value in the form admin / article / create I don't modify or save the value in the database
how can I do?

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### PHP VERSION:
PHP 7.2.24 (cli) (built: Oct 22 2019 11:18:58) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
### LARAVEL VERSION:
laravel/framework                     v6.11.0   The Laravel Framework.
### BACKPACK VERSION:
backpack/backupmanager                2.0.3     Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         4.0.32    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6     Generate files for laravel projects
backpack/newscrud                     3.0.1     An admin panel for news with categories and tags, using Backpack\CRUD on Laravel 5.

**Comment by pxpm** [comment]
Hello @marcoz2102 

My guess is that you didn't add the field to the $fillable array in your model. 

Please use gitter or stackoverflow to ask this kind of questions. We keep github only for bug tracking and features.

I am going to close this, if you still feel this is a bug please re-open so we can re-evaluate it.

Best,
Pedro
