### ISSUE TITLE
[4.0][Bug] The "Remove filters" link does not clear a previously selected option in Dropdown filter

### ISSUE THREAD

**Issue by daverru** [Laravel-Backpack/CRUD#2390]
# Bug report

### What I did

Selected an option in the Dropdown filter and clicked to a "Remove filters" link.

### What I expected to happen

A previously selected option in a options list should be cleared after "Remove filters" (css class "active" should be removed) 

### What happened

Css class "active" didn't remove, the previously selected option is still selected (class="active") in the options list.

### What I've already tried to fix it

There is no 'li' html element within `<ul class="dropdown-menu">` in crud/filters/dropdown.blade.php
So I've changed the line:
`$("li[filter-name={{ $filter->name }}] .dropdown-menu li").removeClass('active');`
to:
`$("li[filter-name={{ $filter->name }}] .dropdown-menu a").removeClass('active');`
in the crud/filters/dropdown.blade.php
(put an existing "a" element instead of "li")

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
backpack/crud                         4.0.34

**Comment by pxpm** [comment]
Hey @daverru 
Thanks for reporting this issue.

It's actually nothing functional, it's aesthetically, when clearing the filters we were not removing active class from selected item. 

@daverru solution works perfectly, I converted it into a PR and it's here #2401 

Thanks again man! :+1: 

Best,
Pedro
