### ISSUE TITLE
[4.0][Feature Request] JSON Field type

### ISSUE THREAD

**Issue by sjsiegel001** [Laravel-Backpack/CRUD#2398]
I was surprised to find there isn't a JSON field type for editing key value pairs like

`{"city": "Groton", "email": "john@example.com", "phone": "555-221-3343", "state": "CT", "country": "US", "address_1": "42 Thorne Ave.", "last_name": "Doe", "first_name": "John"}`

I think this would make a useful addition. I did manage to roll my own by bastardizing the 'table' field type:
https://gist.github.com/sjsiegel001/e7f057e27c6fb064e7f8306847658248

**Comment by ziming** [comment]
Hi @sjsiegel001 

Interesting. For I have build a json editor field before which you may be interested.

https://github.com/Laravel-Backpack/CRUD/pull/1655

I haven't try your field yet but is it more like nova KeyValue field?

https://nova.laravel.com/docs/2.0/resources/fields.html#keyvalue-field

**Comment by sjsiegel001** [comment]
The JSON editor is a little overkill for my immediate purposes although I can think of another use case where it would be useful.

Something just like that nova KeyValue field would be perfect.

Thanks!

**Comment by tabacitu** [comment]
I'm using @ziming 's json editor field type too - works like a charm :-) Indeed, let's reopen that that conversation and consider including it in the core. Thanks @sjsiegel001 & @ziming !

**Comment by tabacitu** [comment]
@sjsiegel001 if this works better for you, how would you like to create a quick post on [backpackforlaravel.com](https://backpackforlaravel.com) to share your field with others? I'm sure they'd appreciate it. And if you just paste the code there, or send people to a gist that you own, you won't have to do maintenance like it's a package.

It could be as simple as explaining what you needed, why you chose this solution, including a screenshot and the link to the code.

What do you think, interested? Another option would be to post on your own blog / medium / whatever and cross-post on BackpackForLaravel.com - that way you can get some eyeballs to something you want.
