### ISSUE TITLE
Can not add button when "stack" is "top"

### ISSUE THREAD

**Issue by PhouvanhKCSV** [Laravel-Backpack/CRUD#240]
In my EntityCrudController, i add a button to "line stack" and it worked

```php
$this->crud->addButtonFromView('line', 'send_email', 'delete');
```

but when i change "stack" to "top"

```php
$this->crud->addButtonFromView('top', 'send_email', 'delete');
```

I got ErrorException

<img width="989" alt="screen shot 2016-11-17 at 5 22 36 pm" src="https://cloud.githubusercontent.com/assets/10794184/20385576/83f92074-acea-11e6-86d9-1b7cab98fa81.png">

**Comment by tabacitu** [comment]
Hi @PhouvanhKCSV ,

The ```$entry``` variable is only available in the ```line``` stack. In the ```top``` and ```bottom``` stacks you can't can have an ```$entry```. Those stacks are for general-purpose or bulk buttons.

Create your own button, that does not use ```$entry```, and it will work in the ```top``` stack ;-) You can look at the "create" button for inspiration.

Cheers!

PS. I've updated the docs to mention this, thanks!

**Comment by promatik** [comment]
For future reference;
You can not use `addButtonFromModelFunction`, nor `addButton` with the view as `model_function`.
Both will throw an Exception of undefined `$entry`.
