### ISSUE TITLE
Feature Request: Adding custom buttons to Show view

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [Laravel-Backpack/CRUD#2403]
I notice that it is possible to add buttons to a List view but not to a Show view. In my case, I have implemented a deep cloning custom operation on the current record. However, the criteria that I use for determining which row to clone cannot be adequately shown in the List view, as I need to see all records in a 1-n relationship to determine the record to clone.

If the row of buttons in the Show view is not implemented as a stack with a name, passed as the first argument to the "addButton*" family of functions, then this is a feature request to make it so.

If the row of buttons has a name, then please post an issue in LaravelBackpack/Docs asking that the name be published in the documentation.

**Comment by ssimo3lsuhsc** [comment]
I figured out that the Action row is in fact the "line" stack; however, I had forgotten that I needed to add a line to my operation trait implementation. Closing issue.

**Comment by tabacitu** [comment]
Hi @ssimo3lsuhsc ,

You should totally be able to add a button to the Show page alone. It's the same name as in the List operation - ```line```. For inspiration, [look at the Clone operation](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/Operations/CloneOperation.php#L36-L38).

You can add a button to the Show view in the setup method:

```php
        $this->crud->operation(['show'], function () {
            $this->crud->addButton('line', 'clone', 'view', 'crud::buttons.clone', 'end');
        });
```

or (preferrably) directly in the ```setupShowOperation()``` method:

```php
$this->crud->addButton('line', 'clone', 'view', 'crud::buttons.clone', 'end');
```
