### ISSUE TITLE
Why is the style different? something's missing?

### ISSUE THREAD

**Issue by marcoz2102** [Laravel-Backpack/CRUD#2411]
# Bug report

### What I did

hi I don't know if this can be a bug, before writing in this section I also asked on stackoverflow.com, but the problem has not been solved, I wanted to create a new field in the form to add posts, but the graphic style is not the same than the default

### What I expected to happen

- in this file: newscrud \ src \ app \ Models \ Article.php I added the new field (description), to make sure that the value of the field is written in the database

`protected $fillable = ['slug', 'description','title', 'content', 'image', 'status', 'category_id', 'featured', 'date'];`

- in this file: ArticleCrudController.php I added the field

`  $this->crud->addField([
                    'name' => 'description',
                    'label' => 'Description',
                    'type' => 'text',
                    'placeholder' => 'Description meta tag',
                    'attributes' => [
                          'required' => true,
           ],
                ]);`

- in this file: app \ Http \ Requests \ ArticleRequest.php I wrote the validation rules. In this case, seeing the suggestions that I have been given backpack, he should do everything, apply the default style, instead it doesn't work can you check?

`  public function rules()
    {
        return [
            'title' => 'required|min:2|max:255',
            'slug' => 'unique:articles,slug,'.\Request::get('id'),
            'content' => 'required|min:2',
            'date' => 'required|date',
            'status' => 'required',
            'category_id' => 'required',
            'description'=> 'required|min:2|max:255',
        ];
    }`

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

laravel/framework                     v6.11.0   The Laravel Framework.

### BACKPACK VERSION:
PHP Warning:  Module 'zip' already loaded in Unknown on line 0

backpack/backupmanager                2.0.3     Admin interface for mana...
backpack/crud                         4.0.32    Quickly build an admin i...
backpack/generators                   2.0.6     Generate files for larav...
backpack/newscrud                     3.0.1     An admin panel for news ...

**Comment by pxpm** [comment]
Hello @marcoz2102 

I am not sure by the time i answered you i gave you the full picture. I opened an issue here so we keep track of it. #2396 

The problem relies on two different types of validation, browser and server. When you use `required => true` you are applying browser validation. Remove it from your field attributes and you should have the same validation that you have in the other field that relies on server validation.

Feel free to add any comments to the discussion in the PR #2396 

If that's not the problem, please re-open this issue and try to clarify what you expect to happen and what is not happening. 

Best,
Pedro
