### ISSUE TITLE
Bug in Select column not displaying attribute.

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#2415]
# Bug report

### What I did

```
            // Polymorphic type. But We only attach it to user record currently.
           // It's part of a package hence not proper foreign key.
            [
                'name' => 'model_id',
                'label' => 'uID',
            ],
            [
                'name' => 'model_id',
                'label' => 'Full Name',
                'key' => 'full_name',
                'entity' => 'user',
                'attribute' => 'name',
                'model' => User::class,
            ],
```

I also have a user() method on the model that is like this

```php
public function user() {
    return $this->belongsTo(User::class, 'model_id');
}
```
### What I expected to happen

1st column to show id of the user, 2nd column to show name attribute of the user

### What happened

Both column show id of the user.

### What I've already tried to fix it

I could use a closure select but that is more of a stop gap measure, not a proper fix.

### LARAVEL VERSION:
laravel/framework                      v6.13.1          The Laravel Frame...

### BACKPACK VERSION:
backpack/crud                          4.0.36           Quickly build an ...
backpack/generators                    2.0.6            Generate files fo...

**Comment by ziming** [comment]
So sorry! I just noticed I forgotten to add the type key for select...

**Comment by tabacitu** [comment]
No prob, glad you figured it out 😄
