### ISSUE TITLE
[4.0][Bug] "Aborted" error when trying to install on Windows - sometimes...

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2416]
# Bug report

### What I did

As reported [here](https://stackoverflow.com/questions/59964625/error-installing-backpack-for-laravel-6-problem-with-elfinder), the user ran ```php artisan backpack:install```, and apparently for the "_Install elFinder?_" prompt they just hit Enter.

### What I expected to happen

Install with no elFinder.

### What happened

The installation process stopped - but in a weird frustrating way, with no extra info, it just says "Aborted".

![qhGlQ](https://user-images.githubusercontent.com/1032474/73428571-48698980-4342-11ea-95f1-f75d79f9d3eb.png)

### What I've already tried to fix it

I've tested on my machine (Mac OS, Laravel Valet), at it worked fine:
![Screenshot 2020-01-30 at 09 16 10](https://user-images.githubusercontent.com/1032474/73428590-55867880-4342-11ea-8989-e031f3de95bc.png)

I'm wondering if it's environment-related. I see they're using Windows & WAMP. 
@pxpm can you please test the installation in Windows and see if you get the same thing?

### Backpack, Laravel, PHP, DB version

"_I'm running backpack 4.0 on Laravel 6_"

**Comment by tabacitu** [comment]
I've searched for ```Aborted.``` in the vendor folder. The only thing that came up was very relevant, and it's probably why this happened, but I also understand very little of it:

https://github.com/symfony/console/blob/67fa5c6f5c986986f6a2cf3ce5407727889a0156/Helper/QuestionHelper.php#L137

From the little I do understand, it looks like there is no "fallback" available. No idea if the "fallback" is supposed to be provided by the environment, the terminal, Symfony, Laravel or Backpack. Because we _did_ provide a "default value", ```false```:

https://github.com/Laravel-Backpack/CRUD/blob/fc29b4237a96e547882cceed24fc99b62700ff64/src/app/Console/Commands/Install.php#L44

I'm wondering. If we're able to reproduce the issue. **Would changing the default value to ```no``` instead of ```false``` in the line above fix it?**

**Comment by pxpm** [comment]
Hello guys.

I am sorry i could not reproduce this issue in Win7, Wamp, PHP 7.2.

After running `php artisan backpack:install`, when asking for el-finder I just pressed enter and it worked fine.

Any more tests i should be running ?

Best,
Pedro

**Comment by tabacitu** [comment]
Well then, I'm pretty sure something's wrong with the dev environment. I saw there are quite a few mentions online of _other_ Artisan commands (non-backpack) that are greeted with an "Abort" out of the blue. No solutions there either. So it doesn't look backpack-related, more likely env-related.

Let's close this. Thanks @pxpm !

**Comment by mamprogr** [comment]
Same issue here.
Windows 10, Wamp, PHP 7.4, backpack 4.0, Laravel 6.

`php artisan migrate` is working well but `php artisan backpack:install` is not.

![image](https://user-images.githubusercontent.com/734475/76160723-93df3680-613d-11ea-995b-68d9f0cd8bcd.png)

**Comment by mamprogr** [comment]
### Solution 1
I tried to skip the error by replacing the line:
https://github.com/Laravel-Backpack/CRUD/blob/fc29b4237a96e547882cceed24fc99b62700ff64/src/app/Console/Commands/Install.php#L44
by:
`$shouldInstallElfinder = true;`

And now the installer is working fine :)

### update
You can skip the error by using: `php artisan backpack:install --elfinder yes`

**Comment by tabacitu** [comment]
Hmmm thank you for the update @mamprogr . Does this help you track down the issue and fix it on Windows @pxpm ?

**Comment by pxpm** [comment]
@tabacitu I don't have win 10 machine. On windows 7 is not happening. 

You can check my SS at #2517

**Comment by tabacitu** [comment]
@mamprogr I see you've gotten around this issue, and have reached the ```elfinder:publish``` step. How did you get around the ```Aborted``` problem? It could save some people A LOT of frustration if you share.

Cheers!

**Comment by tabacitu** [comment]
@sergeev so you're still having this issue? And @mamprogr 's trick fixed it for you?

**Comment by tabacitu** [comment]
It look like the issue hasn't happened in one month, so I'm going to close it. If anybody has this problem again, please let us know and we'll reopen it. Please also let us know the output of your ```php artisan backpack:version```.
