### ISSUE TITLE
AddColumnn Type Select

### ISSUE THREAD

**Issue by erbaafidotama** [Laravel-Backpack/CRUD#2427]
# Bug report
I try to show column in my table from relationship. But its not show and show message "Error Loading Page. Please Refresh the Page". Please help my problem.
This is my database table structure:
Income
id	|	nama_income	| show |

Jurnal
id	|	jenis_income_id	|	Price	|	desc    |	date_transaction|

### What I did
protected function setupListOperation()
    {
        // TODO: remove setFromDb() and manually define Columns, maybe Filters
        // $this->crud->setFromDb();

        $this->crud->addColumn([  // Select
            'label' => "jenis Pemasukan",
            'type' => 'select',
            'name' => 'jenis_income_id', // the db column for the foreign key
            'entity' => 'income', // the method that defines the relationship in your Model
            'attribute' => 'name_income', // foreign key attribute that is shown to user
            'model' => "App\Models\Income" // foreign key model
         ]);
    }

??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:48) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.13.1   The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.37    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6     Generate files for laravel projects
backpack/menucrud                     2.0.2     An admin panel for menu items, using Backpack\CRUD on Laravel 6.
backpack/pagemanager                  2.0.5     Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
backpack/permissionmanager            5.0.6     Users and permissions management interface for Laravel 5 using Backpack CRUD.

**Comment by pxpm** [comment]
Hello @erbaafidotama 

Please open browser developer tools, go to network tab and check the error in the request. Or in laravel.log. 
The error you provided is the general default backpack error message. 

Best,
Pedro

**Comment by erbaafidotama** [comment]
![image](https://user-images.githubusercontent.com/22489268/73652028-658eb700-46b8-11ea-9c4f-005b31b1b0e3.png)

thats my error. But sorry, i cant understand what i must do

**Comment by pxpm** [comment]
The error is clear. In your `App\Models\Journal` you don't have a method named `income` that returns the relationship. So the solution is to create that method in your Model, something along this lines:
```php
public function income() {
return your relation;
}
```

I would suggest your start by learning about laravel/eloquent relationships: https://laravel.com/docs/6.x/eloquent-relationships

I am going to close this, we use github only for bugs and feature request. 

For this kind of questions you better ask on stackoverflow, gitter or backpack reddit. I am around those places to help however I can :)

Wish you the best,
Pedro
