### ISSUE TITLE
Item not deleted

### ISSUE THREAD

**Issue by Sikyn** [Laravel-Backpack/CRUD#243]
Hi Tabacitu,

When delete button clicked in row show this message:

![](https://cloud.githubusercontent.com/assets/6532492/19348442/cc6f707a-915a-11e6-948d-9b739b8bf863.png)

Firebug :
![image](https://cloud.githubusercontent.com/assets/22341460/20386942/0f091656-acbe-11e6-81bd-1dbda322a688.png)

![image](https://cloud.githubusercontent.com/assets/22341460/20386986/476df6b0-acbe-11e6-9785-83ddd9394d3d.png)

How can i fix this plz ?

Thank's for your job !

**Comment by tabacitu** [comment]
Looks like your server does not allow DELETE requests. You should be able to change this in your server configuration.

If you can't do that, you can use a POST request for the delete button by:
- changing DELETE to POST in the AJAX call of your ```resources/views/vendor/backpack/crud/list.blade.php```;
- adding a special route for POST in your routes file that directs to the ```delete()``` method;

Hope this helps.

Cheers!
