### ISSUE TITLE
Backpack and Dingo/api routing conflict

### ISSUE THREAD

**Issue by lemonlover** [Laravel-Backpack/CRUD#2431]
# Bug report

Problems with operation routes 

### What I did

Routes for Backpack

```
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
    Route::crud('book', 'BookCrudController');
   
});
```

Dingo routes

```
use Illuminate\Http\Request;
use Dingo\Api\Routing\Router;
use App\Http\Controllers\Api\RatingController;


$api = app(Router::class);
$api->version('v1', function ($api) {

    //$api->post('user/get_token', 'App\Http\Controllers\Api\UserController@getTokenById');
    $api->resource('rating', RatingController::class);
});

```

### What happened

```
{
"message": "in_array() expects parameter 2 to be array, null given (View: /private/var/www/rating/vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php) (View: /private/var/www/rating/vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php)",
"status_code": 500
}
```

The problem is that
\Route::getCurrentRoute() returns null on every admin route

### PHP VERSION:
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v5.8.36            The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.38             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6              Generate files for laravel projects

### UPDATE:
This method in Library/CrudPanel/Traits/Operations.php
 causes issue
   ```
 /**
     * Get the current CRUD operation being performed.
     *
     * @return string Operation being performed in string form.
     */
    public function getCurrentOperation()
    {
        return $this->currentOperation ?? \Route::getCurrentRoute()->action['operation'] ?? null;
    }
```

Because \Route returns instance of 
Illuminate\Support\Facades\Route
which doesn't have getCurrentRoute() method 
```

array:10 [▼
  0 => "resolved"
  1 => "spy"
  2 => "shouldReceive"
  3 => "swap"
  4 => "getFacadeRoot"
  5 => "clearResolvedInstance"
  6 => "clearResolvedInstances"
  7 => "getFacadeApplication"
  8 => "setFacadeApplication"
  9 => "__callStatic"
]

```

**MAIN POINT** 
How I can fix \Route to resolve properly?

**Comment by pxpm** [comment]
I am afraid that the problem does not rely on `getCurrentRoute()` you can check laravel docs on that: https://laravel.com/api/6.x/Illuminate/Routing/Router.html#method_getCurrentRoute

**Comment by lemonlover** [comment]
> I am afraid that the problem does not rely on `getCurrentRoute()` you can check laravel docs on that: https://laravel.com/api/6.x/Illuminate/Routing/Router.html#method_getCurrentRoute

Have no ideas how to fix it well =/

**Comment by tabacitu** [comment]
@lemonlover when are you getting the ```"in_array() expects parameter 2 to be array```? When you're accessing the Book listing page (built using Backpack)? If so, what does that have to do with the Dingo routes? I don't see a route conflict from what you copy-pasted.

Please try to rephrase your problem, I'm afraid I don't quite understand what the issue is. From your original post I can't tell how Dingo and Backpack are related in any way.
