### ISSUE TITLE
Image loaded from s3 not using absolute url

### ISSUE THREAD

**Issue by Yarob50** [Laravel-Backpack/CRUD#2435]
# Bug report
I have a proble with showing the image while using s3 bucket url (it gives me 404 not found error message)
### What I did
I used the following code of image column in my crud controller:
```
 $this->crud->addColumn([ //image
            'name' => 'image', // The db column name
            'label' => "Image", // Table column heading
            'type' => 'image',
            'disk' => 's3'
            // optional width/height if 25px is not ok with you
            // 'height' => '30px',
            // 'width' => '30px',
        ]);
```
my s3 image is loaded in url like the following:
image.mywebsit.com/<image-id>

### What I expected to happen

I am exepecting backpack to deal with the image url as absolute url to get the image and show it without errors.
### What happened
Backpack is using my absolute url as relative url appended to the current url, for example in localhost it uses the following url:

localhost:8000/image.mywebsit.com/<image-id>
however it should be:
http://image.mywebsit.com/<image-id>
how can I solve the issue?

### Backpack, Laravel, PHP, DB version
Backpack: 3.6
Laravel: 5.8

**Comment by Yarob50** [comment]
I solved the problem by adding the url of my website with http in config/filesystem.php

**Comment by tabacitu** [comment]
Thank you for sharing your solution @Yarob50 !
