### ISSUE TITLE
Does not save defined field with attribute in the model

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#2436]
The data is displayed correctly, but when saving it does not save the record in the table

In the model I define the following fields with the attributes

```php
class ContactName extends Model
{
    use CrudTrait;
protected $table = 'contact_data';
    protected $fillable = [
        'contact_id', 
        'mimetype', 
        'data1', 
        'data2', 
        ];

    protected $appends = [
        'name_mimetype', 
        'name_display', 
        'name_first', 

        ];
  
    Public function getNameMimetypeAttribute()
    {
        return $this->mimetype;
    }

    Public function getNameDisplayAttribute()
    {
        return $this->data1;
    }

    Public function getNameFirstAttribute()
    {
        return $this->data2;
    }

    Public function setNameMimetypeAttribute($value)
    {
        $this->attributes['mimetype'] = strtoupper($value);
    }

    Public function setNameDisplayAttribute($value)
    {
        $this->attributes['data1'] = $value;
    }

    Public function setNameFirstAttribute($value)
    {
        $this->attributes['data2'] = strtoupper($value);
    }
}
```

In crud controller I define Field

```php
class ContactCrudController extends CrudController
{

    //NAME
        $this->crud->addField([ 
            'name'  => 'name_mimetype',
            'label' => 'mimetype',
            'type'  => 'hidden',
            'tab'   => 'Name',
            'value' => 'Name',
            'entity' => 'names',
            ], 'create');       

        $this->crud->addField([
            'name'  => 'name_display',
            'type'  => 'text',
            'tab'   => 'Name', 
            'entity' => 'names', 
            ]);

        $this->crud->addField([
            'name'  => 'name_first',
            'label' => trans('contact.name.name'),
            'type'  => 'text',
            'tab'   => 'Name',
            'attributes' => ['id' => 'name_first'],
            'wrapperAttributes' => ['class' => 'form-group col-md-6'], //resizing
            'entity' => 'names', 
            ]);
}
```

Could you help me ?

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.14.0   The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                2.0.3     Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         4.0.38    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6     Generate files for laravel projects
backpack/logmanager                   3.0.3     An interface to preview, download and delete Laravel log files.
backpack/permissionmanager            5.0.6     Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                     3.0.2     Application settings interface for Laravel 5 using Backpack CRUD.

**Comment by tabacitu** [comment]
Hi @DanielKimmich . I've only looked at the ```nameDisplay``` field, but it looks like it should work:

You code here:
```php
        $this->crud->addField([
            'name'  => 'name_display',
            'type'  => 'text',
            'tab'   => 'Name', 
            'entity' => 'names', 
            ]);
```

Will create an input with the ```name=name_display``` in the create/update view. That input will be sent to the create/update method in the CreateOperation / UpdateOperation trait, which will perform the ```save()``` action on your ```ContactName``` model, for the ```name_display``` attribute. So there's nothing special _Backpack_ does to save the entry - all the performed logic lies in your Model. If something's not getting stored to the DB, I recommend you debug the Model, specifically the accessors and mutators you have. 

Now, I see you have:
```php
    Public function setNameDisplayAttribute($value)
    {
        $this->attributes['data1'] = $value;
    }
    Public function getNameDisplayAttribute()
    {
        return $this->data1;
    }
```
Which, to be honest, look fine to me. 

I recommend you do a ```dd($value)``` inside your mutator, start your model debugging from there. Sorry I can't be of more help.
