### ISSUE TITLE
inline editing of data from show.blade

### ISSUE THREAD

**Issue by mrkz55** [Laravel-Backpack/CRUD#244]
I've forked your repo and setup rudimentary inline editing inside the datatable using x-editble for the text based fields and select2. It implements the original controller with minor modifications to allow it to update via ajax calls.  Saves a lot of time when dealing with the editing of large existing datasets. Pretty much all the changes are non breaking, are you interested in my tidying the code up for you to include or you feel there'd not be much interest for this feature?  Thanks :)

**Comment by tabacitu** [comment]
Hi @mrkz55 ,

Sounds cool, I'm sure some people will be interested in that, but I don't know if we should implement this as a core feature, an extension or a tutorial. 

How did you approach building it? Can I take a look at the code, to see if it would represent a major/breaking change?

Thanks, cheers!

**Comment by pushamaku** [comment]
This is actually pretty cool.

Would appreciate more info on this. Is there a write up anywhere, or could you refer me to all the files that were changed?

**Comment by mrkz55** [comment]
Sorry I've not had time to reply, been uber busy playing catchup for the end of the year rush! I need to tidy the code up a little first, but given the interest in it I'll try and get onto it asap :)

**Comment by tabacitu** [comment]
Sure, no rush. Might be a pretty cool feature, though :-)
