### ISSUE TITLE
Filtering a 'with' clause

### ISSUE THREAD

**Issue by sijones-uk** [Laravel-Backpack/CRUD#245]
According to @tabacitu's reply in #101, it's possible to add an eager-loaded relationship clause (i.e. a 'with' clause) to the query via `addClause()`. I've got a Campaign model and CampaignSession model with the 'campaign_id' column on the campaign_sessions table being a foreign key of the 'id' column on the campaigns table. The basic 'with' clause in my CampaignsCrudController is then:

```
$this->crud->addClause('with', 'campaignSessions');
```

This works fine, but I need to specify additional query constraints for the eager-loaded query. I tried something like this without success:

```
$this->crud->addClause('with', ['campaignSessions' => function ($query) {
	$query->select(['campaign_id', 'name AS campaign_name']);
}]);
```

Using this constrained clause, I looked at the contents of `$this->crud->query` and found that although the 'eagerLoad' closure's parameters contained a `$query` object, the latter was empty.

Is it possible to have a constrained 'with' clause?

**Comment by tabacitu** [comment]
Hi @sijones-uk ,

Never tried it myself, but it should work. Maybe try a different operation in the closure, see if that one applies?

If not, since the $crud property is public, you can also do this:
```php
$this->crud->query = $this->crud->query->with(['campaignSessions' => function ($query) {
    $query->where('title', 'like', '%first%');
}]);
```

Does this fix it?

Cheers!

**Comment by sijones-uk** [comment]
Thanks Christian. I tried both of the following without success:

```
$this->crud->addClause('with', ['campaignSessions' => function ($query) {
	$query->where('id', '=', 1);
}]);
```

```
$this->crud->query = $this->crud->query->with(['campaignSessions' => function ($query) {
	$query->where('id', '=', 1);
}]);
```

When I looked at the query output via `dd($this->crud->query);` for the latter, I got the result you can see here (`$query` is empty):

![laravel_backpack_eager_load](https://cloud.githubusercontent.com/assets/13103339/20426017/2a56e4c6-ad75-11e6-8177-be77b15252a5.gif)

The weird thing is that the eager loading works, but the closure function containing the constraints is never used.

**Comment by sijones-uk** [comment]
Thanks Christian. I tried both of the following without success:

```
$this->crud->addClause('with', ['campaignSessions' => function ($query) {
	$query->where('id', '=', 1);
}]);
```

```
$this->crud->query = $this->crud->query->with(['campaignSessions' => function ($query) {
	$query->where('id', '=', 1);
}]);
```

When I looked at the query output via `dd($this->crud->query);` for the latter, I got the result you can see in the attached image.

**Comment by sijones-uk** [comment]
After more investigation, I found that if I create an Eloquent Builder object and attempt to add the eager loading via the `setEagerLoads()` method, the constraint isn't added. It seems that there's a wider problem, so I reported it [here](https://github.com/laravel/framework/issues/16463). The only way I'd be able to add the constraint using Backpack would be if I could somehow add a 'with' clause to `$this->crud->model`. It doesn't look like that's possible though.

**Comment by OwenMelbz** [comment]
@sijones-uk tried using scopes?

**Comment by OwenMelbz** [comment]
Just closing to tidy up, if you need more help feel free to shout :)

**Comment by tabacitu** [comment]
@sijones-uk ,

Just pushed an update:
- relationships used in columns are now automatically eager loaded;
- you can now use this syntax too: ```$this->crud->with('campaignSessions')```, if campaignSessions is a relationship on a model;

Cheers!

**Comment by sijones-uk** [comment]
Thanks @tabacitu

**Comment by victorlap** [comment]
@sijones-uk Have you had any luck constraining the eager loaded relationship?

**Comment by jasins25** [comment]
@victorlap I may be late, but hope it helps someone who needs to constrain a eager loading query. 

As @tabacitu  has suggested in this thread above, I eager loaded with constraint and assigned to the crud's query builder. 
`$this->crud->query = $this->crud->query->with(['followings' => function($query) {
                    $query->where('journey_user.deleted_at', null);
                }
            ]);`
When I dumped my $this->data['entries'], i found all the objects from my parent model was loaded along with relationships which were empty (thanks to the constraints). So later I rejected the entries which had the relations object empty.

So this is how I did:
`public function index()
    {
        
        $this->crud->hasAccessOrFail('list');

        $this->crud->query = $this->crud->query->with(['followings' => function($query) {
                    $query->where('journey_user.deleted_at', null);
                }
            ]);
        $this->data['crud'] = $this->crud;
        $this->data['title'] = ucfirst($this->crud->entity_name_plural);
       
        // get all entries if AJAX is not enabled
        if (!$this->data['crud']->ajaxTable()) {
            $this->data['entries'] = $this->data['crud']->getEntries();
            $this->data['entries'] = $this->data['entries']->reject(function ($value, $key){
                return $value->followings->count() < 1;
            });
        }
        
        return view($this->crud->getListView(), $this->data);
    }`

**Comment by seyacat** [comment]
It work for me

                
                

> $this->crud->addClause('orWhereHas', 'juego' , function ($query) use($permission) {
>                     $query->where('nombre', '=', $permission);
>                     });
