### ISSUE TITLE
[4.1.0] Fields - rename "wrapperAttributes" to "wrapper"

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2474]
If we end up implementing Solution 3 in https://github.com/Laravel-Backpack/CRUD/pull/2448, and add ```wrapper``` to Columns, we would have:
- ```wrapper``` in Columns;
- ```wrapperAttributes``` in Fields;

For consistency, we should probably rename Fields' ```wrapperAttributes``` to ```wrapper``` too. It wouldn't be a difficult change, but it would be a HUGE change because:
- it's breaking; people have to search&replace ```wrapperAttributes``` with ```wrapper```;
- people have to change ALL their custom field types to do:

```diff
-<div @include('crud::inc.field_wrapper_attributes') >
+@include('crud::inc.field_wrapper_start')
    <label>{!! $field['label'] !!}</label>
    @include('crud::inc.field_translatable_icon')

    @if(isset($field['prefix']) || isset($field['suffix'])) <div class="input-group"> @endif
        @if(isset($field['prefix'])) <div class="input-group-prepend"><span class="input-group-text">{!! $field['prefix'] !!}</span></div> @endif
        <input
            type="text"
            name="{{ $field['name'] }}"
            value="{{ old(square_brackets_to_dots($field['name'])) ?? $field['value'] ?? $field['default'] ?? '' }}"
            @include('crud::inc.field_attributes')
        >
        @if(isset($field['suffix'])) <div class="input-group-append"><span class="input-group-text">{!! $field['suffix'] !!}</span></div> @endif
    @if(isset($field['prefix']) || isset($field['suffix'])) </div> @endif

    {{-- HINT --}}
    @if (isset($field['hint']))
        <p class="help-block">{!! $field['hint'] !!}</p>
    @endif
-</div>
+@include('crud::inc.field_wrapper_end')
```
- we have to change the docs accordingly (but that's the easy part);

I'm not sure if we should do this in 4.1, or in 5.0.

**Comment by tabacitu** [comment]
**Note:** This would also fix an existing inconsistency in 3.x and 4.0 - AFAIK ```wrapperAttributes``` is the only freakin' thing you can define on a field that's ```camelCase```. Everything else is ```snake_case```. Which is... you know... mildly annoying...

For this reason alone I'm moving this to the 4.1 launch board, so we _consider it_.

**Comment by tabacitu** [comment]
Note: It looks like we DO have camelCase attributes in ```columns``` though. A lot of them. Most of them. We should do a breakdown of all documented attributes for fields, columns, filters and buttons, and see what we can do about it...

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/CRUD/pull/2601
So let's close this.

**Comment by uochagas** [comment]
> I'm not sure if we should do this in 4.1, or in 5.0.

Tem que se observar a estrutura das pastas no vendor/backpack/crud/src/resources/views/crud/fields/inc/, no meu caso @include('crud::fields.inc.wrapper_start') e @include('crud::fields.inc.wrapper_end') funcionaram.

php artisan backpack:version
### PHP VERSION:
PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.6@ecdafad1dda3c790af186a6d18479ea4757ef9ee

### BACKPACK VERSION:
4.1.71@03a0ad4a8d7182d6ee9cf9c86d784d171a942484
