### ISSUE TITLE
[4.0][Bug] Multiple images upload to the File Manager

### ISSUE THREAD

**Issue by jakubnorkiewicz** [Laravel-Backpack/CRUD#2480]
# Bug report

### What I did

I've tried to upload multiple files (.png) in a field that has `'type' => 'browse_multiple'` using backpack's file manager.

### Steps to reproduce

<pre><code>
$this->crud->addField([
            'name' => 'images',
            'label' => 'Additional Images',
            'type' => 'browse_multiple',
            'mime_types' => ['image']
            'multiple' => true,
            'sortable' => true,
            'tab' => 'Images',
        ]);
</code></pre>

On the demo installation monsters crud set `'mime_types' => ['image']` on the `browse_multiple`, then try to upload a file via drag and drop.

### What I expected to happen

Images to be uploaded to that particular field.

### What happened

Upload files progress bar is stuck.
There is an error:
<pre><code>
bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1 Uncaught TypeError: Cannot use 'in' operator to search for 'length' in ["image"]
    at T (bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1)
    at Function.each (bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1)
    at W (elfinder.min.js:11)
    at elfinder.min.js:11
    at l (bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1)
    at Object.fireWith [as resolveWith] (bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1)
    at Object.Deferred.x.each.o.<computed> [as resolve] (bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1)
    at d (elfinder.min.js:11)
    at elfinder.min.js:11
    at l (bundle.js?v=4.0.31@27c5d9dd2d01b8b3ada5ba29cc587c5e546f5959:1)
</code></pre>

Ajax request:
<pre><code>Request URL: {base_url}/elfinder/connector?_token=0wtKSSVnWMjGQUWIBL04SXlaoZxJTFQZye0rr8kj&mimes=%5B%22image%22%5D&cmd=ls&target=l1_Zm9vdGVy&intersect%5B%5D=Ford%20S-Max.PNG&intersect%5B%5D=Ford%20Mondeo%20Hybrid.PNG&intersect%5B%5D=Ford%20Mondeo%20Estate.PNG&intersect%5B%5D=Ford%20Mondeo.PNG&intersect%5B%5D=Ford%20Focus%20Estate.PNG&intersect%5B%5D=Ford%20Focus.PNG&reqid=17076fd6110308</code></pre>

Response:
<pre><code>{"list":[]}</code></pre>

### What I've already tried to fix it

I have not attempted to fix this.

### Backpack, Laravel, PHP, DB version

<pre><code>
### PHP VERSION:
PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.10.1   The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.31    Quickly build an admin in...
backpack/generators                   2.0.6     Generate files for larave...
backpack/menucrud                     2.0.2     An admin panel for menu i...
backpack/pagemanager                  2.0.4     Create admin panels for p...
backpack/permissionmanager            5.0.3     Users and permissions man...
backpack/settings                     3.0.1     Application settings inte...

mysql version 5.7.29
</code></pre>

**Comment by jakubnorkiewicz** [comment]
I've found the temporary solution: 
in the monster crud the field has a setting `'mime_types' => ['image']`, remove it.
[Documentation](https://backpackforlaravel.com/docs/4.0/crud-fields#browse_multiple) says it should work with this setting.
I tried to upload .png files.

**Comment by tabacitu** [comment]
Hmmm I'm not very familiar with the problem and how elfinder works, but I'm wondering, maybe you need to specify each mime type individually for it to work? eg ```image/png```?

**Comment by jakubnorkiewicz** [comment]
It doesn't work either.
I've tried to reproduce the error on Backpack Demo and it appears there, so I guess my setup is not the reason for the bug to appear.

Steps to reproduce:
1. Setup [demo](https://github.com/Laravel-Backpack/Demo) on your local machine.
2. Uncomment line no 617 in MonsterCrudController.php and set `'mime_types' => ['image']`

**Comment by tabacitu** [comment]
Oh I get it. Indeed - I've tested and I can confirm it's a bug. Thanks for reporting this @jakubnorkiewicz .

Rephrasing the issue, using my words: **when using the ```browse_multiple``` field, specifying ```'mime_types' => 'image',``` is supposed to limit the files that are visible inside elFinder to ONLY that type of file. However, it doesn't seem to do anything.** 

I wasn't able to track down the problem just now. It seems like the mime types get passed to elFinder, but it doesn't do anything with them. More digging is needed.

**Comment by jakubnorkiewicz** [comment]
Yeah, this is the first issue, the second one is:
Steps to reproduce:

1. Setup demo on your local machine.
2. Uncomment line no 617 in MonsterCrudController.php and set 'mime_types' => ['image'].
3. Go to Backpack Admin Panel.
4. Edit monster entities item.
5. Go to uploads tab.
6. Try to browse multiple, but instead of choosing the files that are already in the database, try to upload file/files using elfinder's upload files option.
7. The items are not being uploaded, the upload files progress is stuck, please find attached screenshot.

![image](https://user-images.githubusercontent.com/36455698/75240027-99db2c00-57bb-11ea-9040-9a489c80bbc2.png)

I'm sorry I didn't include it in my previous message.

**Comment by pxpm** [comment]
Hello @jakubnorkiewicz as @tabacitu already pointed out the `'mime_types' => ['image']` was not filtering out the files in elfinder. 

I did not reproduce your second error, but anyway, after PR #2505 the error is gone. 

Could you confirm on your side ? For easy testing just go to that PR, copy the contents of the only changed file `browse_multiple.blade.php` and paste in `resources/views/vendor/backpack/crud/fields/browse_multiple.blade.php` this will overwrite the default package file with the one with the fix. If you do it, would you mind providing feedback on the [PR Thread](https://github.com/Laravel-Backpack/CRUD/pull/2505)??

Best,
Pedro

**Comment by pxpm** [comment]
Closing this as #2505 had already been merged.
