### ISSUE TITLE
Need 0.7.x for CRUD

### ISSUE THREAD

**Issue by erenergul** [Laravel-Backpack/CRUD#249]
Hi , I try to install crud but I've got an error. 

` - backpack/crud 3.1.19 requires backpack/base ^0.7.0 -> satisfiable by backpack/base[0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6] but these conflict with your requirements or minimum-stability.`

But I install 0.6.x because of laravel 5.2 installation guide looks like that. Please How can I fix this issue ? Thanks

**Comment by tabacitu** [comment]
Hi @erenergul ,

Did you follow [this installation guide](https://laravel-backpack.readme.io/docs/installation)?

Cheers!

**Comment by erenergul** [comment]
Hi @tabacitu ,

Yes , I follow this guide

**Comment by erenergul** [comment]
@tabacitu 

Will you help me guys. I am waiting your response..

**Comment by AurelDragut** [comment]
try to install crud 3.0.18 its the latest version that requires base 0.6.7

**Comment by tabacitu** [comment]
Hi @erenergul .

Just tried the L 5.2 installation guide and it worked for me. Are you sure you followed all the steps? Also, consider upgrading your app to Laravel 5.3. It's a 1 hour task, but it will make it easier for you to upgrade to Laravel 5.4, when it comes around (December-January). Also, [Laravel Shift](https://laravelshift.com/) can help.

Cheers!

**Comment by anglyeds** [comment]
I faced this problem as well, and i tried @AurelDragut  method, it worked for me.

command:
composer require backpack/crud 3.0.18

**Comment by OwenMelbz** [comment]
As this seems to be okay, closing up now :)
