### ISSUE TITLE
traitMethod method setupUpdateRoutes has not been applied

### ISSUE THREAD

**Issue by shashikiranraifox** [Laravel-Backpack/CRUD#2492]
Hi folks,
        I am trying to install[composer install] on my production server machine[Ubuntu 18.04]. Everything was fine in my Development machine, Now in this server machine, I am getting the following error:

"
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error: Trait method setupUpdateRoutes has not been applied, because there are collisions with other trait methods on n App\Http\Controllers\Admin\MyCrudController "

any ideas how to fix this?

**Comment by shashikiranraifox** [comment]
The issue was because I had the below two statements in my controller:

use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation {update as updateStore; 

p.s: Somehow this worked in Development

**Comment by tabacitu** [comment]
Thanks for sharing the resolution @shashikiranraifox - I'm sure it'll help someone someday 😄 Indeed, an Operation trait should only be used _once_.  No idea why that worked for you in dev 😆
