### ISSUE TITLE
Browse field type and wrong iframe URL to elFinder

### ISSUE THREAD

**Issue by fede91it** [Laravel-Backpack/crud#25]
The **browse** field type works fine when Laravel is installed in a root folder, but not when the site is located in a subfolder.

Example:

On `http://localhost/` the URL of the browse iframe point correctly to elFinder popup layout.
On `http://localhost/MySite/public/` the URL is `/admin/elfinder/popup/image-filemanager` instead of `/MySite/public/admin/elfinder/popup/image-filemanager`

**Comment by tabacitu** [comment]
Hi, Federico, you're right, I didn't test it like that. It's now fixed in fef25699bbb8e906e3095f4a5e664e44fafad0c6, or version 2.0.10. A **composer update** should fix it.

Thanks for reporting it, keep it up!
