### ISSUE TITLE
Support 1-1 relationships

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#250]
Right now Backpack does support 1-1 relationships. It's generally preferred to NOT move columns away from the parent table, because it saves a JOIN, but some people prefer it, because it's more object-oriented.

Since [Laravel supports them](https://laravel.com/docs/5.3/eloquent-relationships#one-to-one), Backpack should too.

Here's one solution for it: https://gist.github.com/ChrisThompsonTLDR/c83b21a6f7c9041b680be880c2a21ff0

Next step: figure out best way to do it (syntax) and implement the solution.

**Comment by OwenMelbz** [comment]
I don't understand what's going on 😂

**Comment by tabacitu** [comment]
So if you have a model, say Product (id, name, price, discount, author). Instead of storing everything in the "products" table, some prefer to split it up into multiple tables:
- products (id, name, author_id)
- product_details (product_id, price, discount, description)

It sounds absurd for such a small table, but when one table would have 20-30 columns, it kind of makes sense.

One product has one detail. So it's a 1-1 relationship. Backpack currently has no easy way to handle that, the only way is having mutators for each detail attribute.

**Comment by OwenMelbz** [comment]
Ah okay yes, I understand this now :D

**Comment by MDEvo** [comment]
Nice! Almost give up searching on backpack for almost two weeks to find if this is already existed on backpack... haha

**Comment by scottgrayson** [comment]
```
Backpack currently has no easy way to handle that, the only way is having mutators for each detail attribute.
```
Are the `mutators` you are talking about, eloquent model mutators? or does backpack have its own mutators?

I have a polymorphic relation. Many of my resources have an `App\Address`. I would like to update the address from the `App\User` edit page. This issue also includes this situation (polymorphic one to one), correct?

**Comment by tabacitu** [comment]
@scottgrayson , yup, we're talking about standard [eloquent mutators](https://laravel.com/docs/5.3/eloquent-mutators). And yes, this feature will also fix the polymorphic 1-1). I expect it to be done by the end of the week, as it's quite a bummer I forgot to include the easiest relationship of them all :-)

Cheers!

**Comment by mbaierl** [comment]
Hi!
I kind of followed that conversation and have a similar problem where I am not sure of how to solve it...

Imagine a table `users` (user_id etc) and another one called `pictures`. Each picture is assigned to a single user and there is no way that a picture is moved to another user. Also there are plenty of pictures for each user, which should be sortable.
So the problem is this - how do I implement a nice, smart way where I as admin can go to the user and then view all pictures assigned to him, and eventually sort them? As I said, there is no use case where the pictures change the user and viewing a list of all pictures does not make any sense... 

Any way to solve this? Is this included in the request above?

**Comment by victorlap** [comment]
What is the status of this issue? In december you said it would be there within a week. I am willing to help if you could give an explanation of the current situation.

**Comment by dj-fiorex** [comment]
Hi all, is there any news about this important works??
Thanks!

**Comment by mariavilaro** [comment]
Bump! I need this!

**Comment by dj-fiorex** [comment]
@tabacitu is there any news? I want to help if possible :)

**Comment by EmanueleCoppola** [comment]
Any news on this?

**Comment by tumf87** [comment]
Hi, you checkout the [pull request](https://github.com/Laravel-Backpack/CRUD/pull/865) for this issue. It's still in review but it's close to being done.

**Comment by tabacitu** [comment]
Thank you @tumf87 . Let's close this issue and move the conversation in your PR, if needed.

Cheers!
