### ISSUE TITLE
[4.1] Remove laravel/helpers dependency

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2502]
There's no reason to keep ```laravel/helpers``` as a dependency, since inside our package we can use ```Str::smth()``` and ```Arr::smth()```. I'm now trying to provide Laravel 7 support, and it's very difficult because ```laravel/helpers``` doesn't _officially_ support it yet. 

To do: 
- [x] go through [all helpers in 5.6](https://laravel.com/docs/5.6/helpers), see if we use them in first-party Backpack package, and replace them with their ```Str``` or ```Arr``` equivalent.

Too bad there's no Laravel Shift for this - would buy that in a second.

**Comment by jasonmccreary** [comment]
@tabacitu Give me just a bit and I'll run this for you.

Next time mention me or @laravel-shift directly for a faster response.

**Comment by tabacitu** [comment]
That's great news @jasonmccreary , thanks a lot!

**Comment by ziming** [comment]
Awesome!

**Comment by tabacitu** [comment]
Gets fixed in https://github.com/Laravel-Backpack/CRUD/pull/2521 using magic 😄 Will get merged into 4.1. Closing - let's move the conversation there.
