### ISSUE TITLE
Can't install anymore

### ISSUE THREAD

**Issue by giojkd** [Laravel-Backpack/CRUD#2506]
Installed as usual tried laravel 7,6,5.8 

The command "'php' 'artisan' 'backpack:add-sidebar-content' '"<li' 'class="nav-item"><a' 'class="nav-link"' 'href=\"{{' 'backpack_url('\''elfinder'\'')' '}}\"><i' 'class=\"nav-icon' 'fa' 'fa-files-o\"></i>' '<span>{{' 'trans('\''backpack::crud.file_manager'\'')' '}}</span></a></li>"'" failed.

**Comment by tabacitu** [comment]
Thank you for raising the issue @giojkd ! Indeed, there was a problem with the installation process - we were not correctly using the new Symphony\Process syntax. 

I've just pushed a fix as ```4.0.45```. Please run ```composer update``` and ```php artisan backpack:install``` again, it should work fine this time. If it doesn't, please let us know.

Cheers!
