### ISSUE TITLE
override the login. blade but when I update I lose the changes

### ISSUE THREAD

**Issue by marcoz2102** [Laravel-Backpack/CRUD#2507]
# Bug report

### What I did

hello I override the login. blade but when I update I lose the changes

### What I expected to happen

I wanted to put the logo in place of the writing it does but when I update the version the changes are not maintained
with the jumbotron it works mail rest of the pages no

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version
laravel/framework                     v6.18.0   The Laravel Framework.
backpack/backupmanager                2.0.3     Admin interface for mana...
backpack/crud                         4.0.43    Quickly build an admin i...
backpack/generators                   2.0.6     Generate files for larav...
backpack/newscrud                     3.0.1     An admin panel for news ...

**Comment by tabacitu** [comment]
Hi @marcoz2102 ,

I don't think I understand what you're saying. Please expand. 

Make sure you answer the following questions too:
1. Did you change the ```login.blade.php``` file by creating a new file inside ```resources/views/vendor/backpack/base/auth/login.blade.php``` OR did you modify it in ```vendor/backpack/crud/src/...```?
2.  Does your ```login.blade.php``` file get overwritten? Does it get deleted?
3. This happens when you update what package? From what version to what version?

Cheers!

**Comment by marcoz2102** [comment]
hello I apologize I put it in this path resources / views / vendor / backpack / base / as written here Customize the dashboard

The dashboard is shown from Backpack \ Base \ app \ Http \ Controller \ AdminController.php :: dashboard (). If you take a look at that method, you'll see that the only thing it does is to set a title, breadcrumbs, and return a view: backpack :: dashboard.

In order to place something else inside that view, like widgets, simply publish that view in your project, and Backpack will pick it up, instead of the one in the package. Create a resources / views / vendor / backpack / base / dashboard.blade.php file
I thought it was fine for all pages.
Thanks Marco

**Comment by tabacitu** [comment]
2. Does your login.blade.php file get overwritten? Does it get deleted?
3. This happens when you update what package? From what version to what version?

**Comment by marcoz2102** [comment]
hello I did a test at the next update I tell you if it works. I saved in this path: resources \ views \ vendor \ backpack \
