### ISSUE TITLE
[4.0][Possible bug] Updating n-n relations happens twice because of order it's being called in

### ISSUE THREAD

**Issue by Staedion** [Laravel-Backpack/CRUD#2511]
# Bug report

### What I did

update operation
field 1 from null to 1 (with select2_from_ajax) and 
field 2 from 1 to null

### What I expected to happen

the update is performed

### What happened

the update from 1 to null is not written to postgres db
db has a constraint field1 is null and field2 is not null or field 1 is not null and field2 is null.
due to use of 2 seperate queries for updating the 2 fields this gives an error.

both field are belongsTo relationships to other model

### PHP VERSION:
PHP 7.4.1 (cli) (built: Dec 18 2019 14:44:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.17.0   The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.41    Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.6     Generate files for laravel projects

**Comment by tabacitu** [comment]
Hi @Staedion ,

If I understand correctly, this case is very specific to your application, and it's an expected way for the Update process to behave. It failed because your DB constraints did not allow it. I recommend you take a closer look at your validation, in your CrudRequest - and make sure you cover this edge case there too.

That being said, please note that the attributes are NOT saved using two queries. They're saved using just one. The AJAX call from the ```select2_from_ajax``` field does not actually save anything - it just uses AJAX to fetch the entries. The saving is then done after you click the Save button.

Hope it helps. I don't think we can help in any way here, since it looks like an application issue, not a Backpack issue. Let me know if I'm mistaken.
Cheers!

**Comment by Staedion** [comment]
@tabacitu if it's not intended to update one to many relations in more than a single query i suppose there is a bug. 

Backpack\CRUD\app\Library\CrudPanel\Traits\Update functions different from the Create trait.

on creation there's one insert query on update all belongsto relations are updated in a seperate query one by one. I suppose this should only be the case with n-n relations.

**Comment by Staedion** [comment]
Under here the correct function for n-n as 1-n to function properly

```
public function update($id, $data)

    {
        $data = $this->decodeJsonCastedAttributes($data);
        $data = $this->compactFakeFields($data);
        $item = $this->model->findOrFail($id);

        // omit the n-n relationships when updating the eloquent item
        $nn_relationships = array_pluck($this->getRelationFieldsWithPivot(), 'name');
        $updated = $item->update(array_except($data, $nn_relationships));

        // if there are any relationships available, also sync those
        $this->createRelations($item, $data);

        return $item;
    }
```

**Comment by tabacitu** [comment]
Hmm... thank you @Staedion , we'll investigate!

**Comment by Staedion** [comment]
@tabacitu : the problem is that many to one relations are updated as they are many to many relations in seperate queries. They should be updated in a single update query after which the many to many realtions should be updated as happens at the create operations which works correctly.

**Comment by tabacitu** [comment]
Thank you @Staedion - I've just created PR https://github.com/Laravel-Backpack/CRUD/pull/3210 using your code, and have asked @pxpm to give his opinion and review, to make steps towards a fix on `master`. Let's move the conversation there, please.

Cheers!
