### ISSUE TITLE
[4.0][Bug] "php artisan backpack:version" is not working

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2518]
# Bug report

### What I did

I installed backpack using `php artisan backpack:install --elfinder yes`.

### What I expected to happen

`php artisan backpack:version` to work.

### What happened

Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in ...\vendor\backpack\crud\src\app\Console\Commands\Version.php on line 51
![image](https://user-images.githubusercontent.com/734475/76161303-28986300-6143-11ea-96b4-4402fefb84c6.png)

### What I've already tried to fix it

I tried to reinstall laravel and backpack but the same error appears.

### Backpack, Laravel, PHP, DB version

Windows, Wamp, Backpack 4.0, PHP 7.4

**Comment by tabacitu** [comment]
Thank you for raising this @mamprogr ! Just created a fix, merging it now.
