### ISSUE TITLE
Can't add style in "model_function" column type

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2522]
# Bug report

### What I did

In the controller:
![image](https://user-images.githubusercontent.com/734475/76172197-76918300-61a4-11ea-9bdf-7f68ef58c411.png)
In the model:
![image](https://user-images.githubusercontent.com/734475/76172222-ae98c600-61a4-11ea-8539-693e560b66ba.png)

### What I expected to happen

Like this:
![image](https://user-images.githubusercontent.com/734475/76172260-f61f5200-61a4-11ea-9421-3d5dabcba5fd.png)

Note: I made the color my self in the dev. tools in Chrome to show it.

### What happened

![image](https://user-images.githubusercontent.com/734475/76172277-17803e00-61a5-11ea-9645-17ad551e419a.png)

### What I've already tried to fix it

The column content show if I removed the style attribute.
This is a working example:
![image](https://user-images.githubusercontent.com/734475/76172289-40a0ce80-61a5-11ea-8685-2cd2a9da1067.png)
![image](https://user-images.githubusercontent.com/734475/76172293-4eeeea80-61a5-11ea-8e4a-883bb1fd8c15.png)

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.0 (cli) (built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.0.8@d71ba61d51aec79a0a0f907991ec215dc24b09d4

### BACKPACK VERSION:
4.0.49@986f5e69593eab33e567787e0c28efb6747cd7b5

**Comment by tabacitu** [comment]
That's weird @mamprogr . I've just tried it:
![Screenshot 2020-03-09 at 09 06 54](https://user-images.githubusercontent.com/1032474/76190314-6352d780-61e5-11ea-8086-fdbbdecfb70a.png)

And it worked fine for me:
![Screenshot 2020-03-09 at 09 06 33](https://user-images.githubusercontent.com/1032474/76190328-6a79e580-61e5-11ea-9fd3-de7d473bf7ed.png)
![Screenshot 2020-03-09 at 09 06 25](https://user-images.githubusercontent.com/1032474/76190345-71a0f380-61e5-11ea-81d7-b3810ea11c3a.png)
![Screenshot 2020-03-09 at 09 06 12](https://user-images.githubusercontent.com/1032474/76190350-749be400-61e5-11ea-9fe7-1edb107d7c48.png)


So I don't think it's a bug in Backpack. 

Maybe it's not the ```style``` getting stripped, but you're hitting the upper character limit? If no limit is specified Try setting ```limit => 100``` on your column, see if that fixes it. Let me know.

Cheers!

**Comment by mamprogr** [comment]
Thanks a lot, as you said, it was a `limit` issue. It is working now :)
