### ISSUE TITLE
[4.1][Improvement] Remove PUT route for Create operation

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2525]
Inside the CreateOperation we have two routes pointing to the ```store()``` method:
- POST on ```admin/product```
- PUT on ```admin/product/create```

And they both have the same name:
<img width="1502" alt="Screenshot 2020-03-09 at 12 58 25" src="https://user-images.githubusercontent.com/1032474/76207076-ce140b00-6205-11ea-9d64-e6a7f11f7d21.png">

But we're only actually using the POST one inside the create form. So we _could_ remove the PUT route in 4.1. 

@pxpm what do you think about this? Any idea why this was introduced in the first place? At first I though it was to match [Laravel Restful resource routes](https://laravel.com/docs/5.1/controllers#restful-resource-controllers), but no - they only have one PUT route and it's for updating, not creating.

**Comment by pxpm** [comment]
I have no clue why it was introduced. We actually use the POST. 

This was causing the issue in #2523 

I sent a PR #2529  with this change, that fixed the mentioned problem. 

Best,
Pedro

**Comment by tabacitu** [comment]
I've gone through the file history, looks like:
- initially the Create operation only used 2 routes: GET on /create, and PUT on /create;
- [in Aug 2019](https://github.com/Laravel-Backpack/CRUD/commit/fb007a8aa439ace286c8e8df55bef5c660a2d22a#diff-6b339fbea17903d0ec0681c64f0cb038) we've added the POST route on / . No mention why that was done. But it was probably because that was the route that was actually used inside the create _view_. Or for the routes to be similar to [Laravel's Resource Controllers](https://laravel.com/docs/7.x/controllers#resource-controllers).

Not helpful, I know 😄 I'm just posting so nobody else gets the idea to go down the rabbit hole in hopes of finding a reason - you probably won't.

**Comment by tabacitu** [comment]
Merged and tagged. To fix this, get 4.0.52 - fresh out of the oven. ```composer update```. 

Now let's wait and if anybody used that route 🤞  for what, and how much they hate us for removing it as a non-breaking change 🙄 😇
