### ISSUE TITLE
[4.0][Bug] Elfinder menu item is not working

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2531]
# Bug report

### What I did

I installed a fresh version of Backpack via `php artisan backpack:install --elfinder yes`

### What I expected to happen

`File Manager` menu item to work.

### What happened

`File Manager` menu item is not working in the menu.

### What I've already tried to fix it

I think the problem in the quotations here:
![image](https://user-images.githubusercontent.com/734475/76260003-e583e000-6267-11ea-9057-145b70f80de3.png)
It works fine after removing the repeated quotations.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.0 (cli) (built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.0.8@d71ba61d51aec79a0a0f907991ec215dc24b09d4

### BACKPACK VERSION:
4.0.52@574eb04050fbc8e073202fe0c38ed6bbb3718bfb

**Comment by pxpm** [comment]
@mamprogr can you confirm you are using Windows ?

**Comment by mamprogr** [comment]
Yes, Windows and Wamp

**Comment by pxpm** [comment]
Can you test my solution in #2532 if it fixes ? 

If it does fix, please leave a comment in the PR thread so when @tabacitu sees it, it knows it had been tested atleast by two persons, and would make it easy for him to merge the change.

I would like to thank you very much for submiting this issues, the upgrade to Laravel 7 should have not been so broken, a lot of stuff changed in Laravel dependencies and not all are documented, so we only know about them when we get the errors .

For that bad experience we apologize! Hope next weeks will bring better news than this! :)

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
I've just merged #2532 - which hopefully fixes this. Please let us know if after a ```composer update``` you get any more issues @mamprogr . And just like @pxpm said - thanks a lot. Very helpful.

Cheers!
