### ISSUE TITLE
Export Button to PDF and Excel

### ISSUE THREAD

**Issue by asicambo** [Laravel-Backpack/CRUD#2533]
I have a few problem with Export to PDF and Excel with Export Button:

1 - Export Button - PDF : I got almost blank PDF file (Please see my attachment). I believe that the problem come from the Unicode Khmer Font (Cambodia language).

[សកម្មភាពស្ថាប័នអប់រំ  CSD Administration.pdf] (https://github.com/Laravel-Backpack/CRUD/files/4310625/CSD.Administration.pdf) 

Please kindly point out the block of code that produce the output for PDFMake to generate the PDF file.

2 - Export Button - Excel : it is working fine but I would like to know how to display full text instead of text was trimmed out with ...

Thanks
Borin

**Comment by tabacitu** [comment]
Hi @asicambo ,

1 - the export is done using the DataTables JS plugin, it indeed seems to use pdfmake - look for ```resources/views/crud/inc/export_buttons.blade.php```.

2 - to not show trimmed text, you can only set ```'limit' => 200``` on that column; or a bigger limit if you need to; but be aware that will also show 200 characters in the main view, not only in the export;

Hope it helps. Let us know if you manage to figure it out, and it's something we can fix for everybody.
Cheers!

**Comment by asicambo** [comment]
@tabacitu 

It is Khmer Unicode Character UTF-8 encoding issue. 
Look like DataTables does not currently have UTF-8 support from what I checked for a whole day in their forum. I am sad! ;( but I will keep searching for the solution.

**Comment by asicambo** [comment]
@tabacitu 

- DataTables button: pdfHTML5 using PDFMake which support custom font via vfs_fonts.js (Detail [Link](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/))
- I got vfs_fonts.js but I don't know how can I set the rest of the setting in backpack according to PDFMake document.  1 - assign pdfMake.fonts 2 - specify the font in your doc-definition

Any advise? 

Best Regards,
Borin

**Comment by tabacitu** [comment]
@asicambo you can copy-paste the ```export_buttons``` file from the package to your project folder, inside ```resources/views/vendor/backpack/crud/inc/export_buttons.blade.php```

Backpack will then load _your_ file, instead of the one in the package. 

There, you can add the JS file you want, and change the JS calls. You can do the same with the ```datatables_logic.blade.php``` file if you need to.

Hope it helps!

**Comment by asicambo** [comment]
@tabacitu 

1 - The custom font is on pdfMake which I could not find any single line of code in backpack related with pdfMake at all. I need to 1 - assign pdfMake.fonts with the font that I generate with  vfs_fonts.js file, 2 - specify the font in your doc-definition of pdfMake.

2 - is Datatables trimmed the text or backpack setting in column is the one who trimmed the text? How it work? The export to (Print, CVS, Excel) was trimmed the text. How not to trim the text in export?

your advise is highly appreciated.
Borin

**Comment by tabacitu** [comment]
I've never worked so deep with pdfMake so I'm afraid I can't help much.

All I know is that the pdfMake JS is loaded here - https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/inc/export_buttons.blade.php#L5-L6

And that file configures dataTables in such a way to show the export buttons. I don't know how pdfMake works, how it's loaded by dataTables, and how you can modify anything about it, sorry. Best to refer to dataTables or pdfMake docs for that.

It might also be helpful to know that all other dataTables configuration is here https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/inc/datatables_logic.blade.php

Sorry I can't be of more help.
Cheers!

**Comment by asicambo** [comment]
@tabacitu 

1 - Generated vfs_fonts.js and put in 

<script src="{{ asset('packages/pdfmake/vfs_fonts.js') }}" type="text/javascript"></script>

2 - DataTables button have 'customize' option where we can pass the custom font to PDFMake.
     Example from the my search is like this....
           `customize: function (doc) {
                       doc.defaultStyle = 
                            {
                                font: 'fontname'
                            }
             },`

3 - So i try to add the 'customize' option inside this code:

`{
                    name: 'pdfHtml5',
                    extend: 'pdfHtml5',
                    exportOptions: {
                        columns: function ( idx, data, node ) {
                            var $column = crud.table.column( idx );
                                return  ($column.visible() && $(node).attr('data-visible-in-export') != 'false') || $(node).attr('data-force-export') == 'true';
                        }

                    },
                    orientation: 'landscape',
                    action: function(e, dt, button, config) {
                        crud.responsiveToggle(dt);
                        $.fn.DataTable.ext.buttons.pdfHtml5.action.call(this, e, dt, button, config);
                        crud.responsiveToggle(dt);
                    },

                    
                },`

but I am not sure 

           customize: function (**???**) {
                       **???**.defaultStyle = 
                            {
                                font: 'KhmerOS'
                            }
             },

So I can't still make it work....

Please advise.
Thanks and Regards,
Borin

**Comment by tabacitu** [comment]
Sorry @asicambo - I have no idea, never done this before, never had to deal with Khmer character issues, or with changing the font inside the export... Maybe someone on StackOverflow can help?

**Comment by asicambo** [comment]
@tabacitu 

For custom font for PDFMake in Backpack:

1 - Generate the vfs_fonts.js (Documents how to do that [Link](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/))

2 - In export_buttons.blade: 
---> Change the URL to the vfs_fronts.js file
--->  Add this code in

```
this.pdfMake.fonts = {

fontname: {
      normal: 'fontname.ttf',
      bold: 'fontname.ttf',
      italics: 'fontname.ttf',
      bolditalics: 'fontname.ttf'
     }
}
```

----> Insert this code in the block for button pdfHtml5

```
customize: function (doc) {
         doc.defaultStyle.font = 'fontname';
}
```

Hope this will help other people.

**Comment by tabacitu** [comment]
Thank you for sharing @asicambo ! I'm sure this has been a major pain in the a$$ to solve,  I'm sure this will save someone _someday_ a lot of hours and frustration. Props to you!
