### ISSUE TITLE
[4.0][Feature Request] action button for 1-n relation in list page

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2534]
Hi Guys,
Is there any way to add an `action` button for 1-n relation?

For example, I want to add an `action` button for related articles in the category list page, as shown here:
![image](https://user-images.githubusercontent.com/734475/76300153-514c6400-62cd-11ea-9727-b92806dc2732.png)
If we click on this action button, I expect to open the articles list page filtered by the category.

I'm not sure if there is a workaround solution in this version.

Thanks.

**Comment by pxpm** [comment]
To open some crud fitered by something, create the filter in the related crud, and then append the query parameters to your url like, `https://test.example.com/admin/articles?active=1`

**Comment by mamprogr** [comment]
Thanks a lot :)
