### ISSUE TITLE
[4.0] Deleting the old image while replacing is missing in docs.

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2539]
# Bug report

### What I did

I added a field with the type of `image` for the `Article` model. I used the function `setImageAttribute` from the docs here: [https://backpackforlaravel.com/docs/4.0/crud-fields#image](url)

### What I expected to happen

When I replace the image while updating the `article`, the old image should be removed.

### What happened

When I replace the image while updating the `article`, the old image does not remove.

### What I've already tried to fix it

I solved the issue by adding
```
// delete the old image from disk
\Storage::disk($disk)->delete($this->{$attribute_name});
```
inside the if statement
```
if (starts_with($value, 'data:image'))
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.0 (cli) (built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.0.8@d71ba61d51aec79a0a0f907991ec215dc24b09d4

### BACKPACK VERSION:
4.0.49@986f5e69593eab33e567787e0c28efb6747cd7b5

**Comment by pxpm** [comment]
Hello once again @mamprogr :)

So .. this is a documentation issue ? 

I think it's safer check if `Storage::has()` before you delete it ?

**Comment by mamprogr** [comment]
Yes, the problem in deleting from disk. The database part is working well.
As you said, it is a documentation issue.

> I think it's safer check if Storage::has() before you delete it?

Yes, here is the final piece of code:

```
if (\Storage::disk($disk)->exists($this->{$attribute_name}))
{
    \Storage::disk($disk)->delete($this->{$attribute_name});
}
```

**Comment by pxpm** [comment]
Once again, thank you very much @mamprogr . I'v just submited [THIS PR](https://github.com/Laravel-Backpack/Docs/pull/106) 

Going to close this. :+1:
