### ISSUE TITLE
export buttons is not working

### ISSUE THREAD

**Issue by rzaglinskij** [Laravel-Backpack/CRUD#254]
this
$this->crud->enableExportButtons();
is not working
Call to undefined method Backpack\CRUD\CrudPanel::enableExportButtons()

**Comment by OwenMelbz** [comment]
Does the documentation suggest that you need to add a trait to make it exportable?

**Comment by tabacitu** [comment]
Hi @rzaglinskij ,

1) Are you using Backpack on Laravel 5.2 or 5.3?
2) Have you updated Backpack to its latest version? ```composer update```

Cheers!

**Comment by rzaglinskij** [comment]
my model
class Subscriber extends Model
{
    use CrudTrait;

my controller
class SubscribersCrudController extends CrudController
{
    public function __construct()
    {
        parent::__construct();
        $this->crud->enableAjaxTable();
        $this->crud->enableDetailsRow();
        $this->crud->enableExportButtons();

php 7.0.8
Laravel - "laravel/framework": "5.2.*",
Backpack :
    "backpack/base": "^0.6.7",
    "backpack/permissionmanager": "^2.1",
    "backpack/crud": "^3.0",

**Comment by tabacitu** [comment]
Yup, that's what I thought. I'm afraid the export feature has been introduced in CRUD 3.1, so it only works for Laravel 5.3.

If you really really need it, I suggest you [upgrade Laravel and Backpack](https://laravel-backpack.readme.io/docs/upgrade-guide-30-to-31) to the latest version.

The only solution without an upgrade is more complicated: you should go through the commits, see where the export functionality has been introduced and try to replicate it in your project. 

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
