### ISSUE TITLE
[4.1] Split CrudTrait into more files, one for each concern

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2546]
So that:
1) it's easier to read
2) it's easier to use a concern/ability without using the entire CrudTrait

Similarly to how we've added ```HasIdentifiableAttribute``` in 4.1 we could have:
- ```HasEnumFields```
- ```HasRelationshipFields```
- ```HasNullableFields```
- ```HasUploadFields```
- ```HasFakeFields```
- ```HasTranslatableFields```

So it would end up being:

```php
<?php

namespace Backpack\CRUD\app\Models\Traits;

use DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Config;
use Traversable;

trait CrudTrait
{
    use HasIdentifiableAttribute;
    use HasEnumFields;
    use HasRelationshipFields;
    use HasNullableFields;
    use HasUploadFields;
    use HasFakeFields;
    use HasTranslatableFields;

    public static function hasCrudTrait()
    {
        return true;
    }
}

```

**Comment by pxpm** [comment]
I like it! It's easier to understand what's happening under the hood. :+1:

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/CRUD/pull/2550
Closing
