### ISSUE TITLE
How to store current user_id and uid

### ISSUE THREAD

**Issue by squierll** [Laravel-Backpack/CRUD#255]
I'm new in laravel Backpack. In my note entity i want store current user notebook id and uniqid. 
I don't know how to include in laravel backpack crud.
Before i used this store function in my controller:
```
public function store(TodoCreateRequest $request)
    {
        
        $uid = uniqid(true);

        $todolist = $request->user()->todolist()->first();

        $todo= $todolist->todos()->create([
            'uid' => $uid,
            'todo' => $request->todo,
            'status'=> $request->status,
        ]);

        if ($request->ajax()) {
            return response()->json(null, 200);
        }

        return redirect()->back();
    }
```

**Comment by tabacitu** [comment]
Hi @squierll ,

You can do things before or after an entry is created/updated using:
A) The controller's [store() and update() methods](https://laravel-backpack.readme.io/docs/crud#section-callbacks) (quick, but will only works in the admin panel);
B) [Eloquent Observers](https://laravel.com/docs/5.3/eloquent#observers) to listen on the events (creating, created, updating, updated, saving, saved, deleting,  deleted, restoring, restored) - will also work when you create/update/etc entries from the front-end;
C) [A mutator](https://laravel.com/docs/5.3/eloquent-mutators#defining-a-mutator) - will also work in the front-end, but it's more hacky;
D) By [overwriting the model's save method](https://stackoverflow.com/questions/40004213/how-add-a-request-item-to-backpack-laravel) - will also work in the front-end;

Hope it helps. Cheers!

**Comment by OwenMelbz** [comment]
@tabacitu I'm starting to think maybe more and more to add an abstract function into the store/update methods which users can extend like callbacks for simplicity.

Especially as the methods extend and evolve over time it makes it harder to maintain. So suggesting people to copy the function out and overwrite them it means they might miss out or have clashes with future features??

Or am i missing something haha

**Comment by zschuessler** [comment]
For any kind of "log current user ID to table row" operations, you might consider automating it on your model. Here's an implementation I did:

```php
class Product extends Model
{
    public function __construct(array $attributes = [])
    {
        $this->creating([$this, 'onCreating']);

        parent::__construct($attributes);
    }

    public function onCreating(\App\Models\Product $row)
    {
        if (!\Auth::user()->id) {
            return false;
        }

        $row->setAttribute('created_by_user_id', \Auth::user()->id);
    }
```

Above, the `creating` method allows you to hook into your own custom event (`onCreating` in this case) when a row is being created for the first time.

This way you aren't extending the function from the real model.

+1 for adding an abstract method to make it easier!

**Comment by tabacitu** [comment]
@OwenMelbz I'm open to a more abstract approach. What do you have in mind?

**Comment by OwenMelbz** [comment]
I'm literally thinking of something as simple as

```php
public function store(Request $request){
    $this->beforeStore($request);
    //all other code here
    $this->afterStore($request, $entity);
}
```

**Comment by OwenMelbz** [comment]
basically this PR https://github.com/Laravel-Backpack/CRUD/pull/283

**Comment by OwenMelbz** [comment]
As I'm consolidating things, I'm going to close this up as there is another list and a PR for it.

You can see the list https://github.com/Laravel-Backpack/CRUD/issues/285
