### ISSUE TITLE
permission manager in laravel backpack

### ISSUE THREAD

**Issue by sokvebolkol** [Laravel-Backpack/CRUD#2551]
# Bug report
 Error: config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding.

### What I did
I followed that document : https://github.com/Laravel-Backpack/PermissionManager
??

### What I expected to happen
Will create permission table and can migrate it
??

### What happened
I cannot migrate permission table into database
??

### What I've already tried to fix it
I try to check what I am wrong with this table, but still not yet fix. Anyone can help me?

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
Hi @sokvebolkol ,

I bet you probably haven't installed spatie/laravel-permissions. Please take another look at the [Installation steps](https://github.com/Laravel-Backpack/PermissionManager#install) and make sure you've done on all of them correctly.

If you find a bug inside the package, please post and issue on that package's Github.
If you run into problems, please use Gitter/StackOverflow/Reddit. We use Github for bugs and features only.

Cheers!

**Comment by sokvebolkol** [comment]
Hi @tabacitu, Thank you for help me. Now I just run php artisan config:cache, route:clear and view:clear. I solve my problem:)
