### ISSUE TITLE
pagination issue

### ISSUE THREAD

**Issue by rzaglinskij** [Laravel-Backpack/CRUD#256]
When I am on 20-th page and I edit something, after I click ok SAVE I am redirected to the first page. Are there an option to be redirected to the 20-th page after saving ?

**Comment by OwenMelbz** [comment]
Hi @rzaglinskij 

Currently not, it literally sends you back to the listing page.

Are you using Ajax listing or normal?

**Comment by rzaglinskij** [comment]
Ajax, because I have 800000 records in a table

**Comment by OwenMelbz** [comment]
Okay, well I think this is something @tabacitu will need to add to the feature backlog

**Comment by OwenMelbz** [comment]
I'm closing this off now, have added it to a list :)

**Comment by Jakhongir91** [comment]
Hi, is there workaround for now? I also have lots of rows and redirection to the first page is a bit not comfortable

**Comment by OwenMelbz** [comment]
I think that now all CRUDs are datatables this is important to try get working

**Comment by wirecamp** [comment]
No update on this
