### ISSUE TITLE
[4.0][Bug/Proposal] AddSidebarContent.php should be clearing cache. 

### ISSUE THREAD

**Issue by genesiscz** [Laravel-Backpack/CRUD#2565]
# Bug report

### What I did

php artisan backpack:crud user

### What I expected to happen

To see new CRUD in sidebar_content

### What happened

I didn't see the sidebar_content, probably because it doesn't clear cache.

### What I've already tried to fix it

```
Artisan::call('cache:clear');
Artisan::call('view:cache');
```

It would probably be sufficient enough to add these into somewhere [here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Console/Commands/AddSidebarContent.php#L51)

I am not sure enough it is not a problem with my Laravel settings since I am not an expert, I am coming from Nette which was clearing the cache when the template contents changed. Am I missing something?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

> 
> ### PHP VERSION:
> PHP 7.4.3 (cli) (built: Feb 24 2020 18:39:14) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
> 
> ### LARAVEL VERSION:
> v6.16.0@b47217e41868d3049ec545cbb713aa94c6f39e55
> 
> ### BACKPACK VERSION:
> 4.0.53@2305b74390a58dc1b7e9b2c5798a663f60cdcd62
>

**Comment by tabacitu** [comment]
Hmm... Doesn't sound like a bad idea at all. And it would be an easy fix. I'm just wondering why I never had this problem - it always shows the sidebar item right away for me. @pxpm did you ever have this problem?

@genesiscz are you using any extra caching package, or have you changed your Laravel caching settings in any way?

Cheers!

**Comment by genesiscz** [comment]
I kinda have to admit this was probably done by my mistake. I am working on remote host with my local IDE so the file was uploaded BUT the cache was not cleared. This was caused by "preserve timestamps" option in development settings.
