### ISSUE TITLE
Hide the Add button

### ISSUE THREAD

**Issue by sonoftheweb** [Laravel-Backpack/CRUD#257]
Is there anywhere I can hide the Add button in CRUD page? I know `$this->crud->removeAllButtonsFromStack('line');` removes the button stack to the right.

**Comment by AurelDragut** [comment]
Yes, i remove the "create" from "create/update/both" in the controller when i want that.

**Comment by sonoftheweb** [comment]
@AurelDragut Great! I found that the key I used "add" was not the correct one *facepalm*. I changed that to 

`$this->crud->removeButton('create');`

**Comment by AurelDragut** [comment]
http://card.beautysalonbucuresti.ro/wp-admin/

user: admin
parola: pass

cand esti gata vorbim de implementarea landingpage-ului

**Comment by priyankmaniar** [comment]
In the latest version, the following worked for me.

```
$this->crud->denyAccess('create');
```
