### ISSUE TITLE
Use friendly message when there is no items on list

### ISSUE THREAD

**Issue by francescobianco** [Laravel-Backpack/CRUD#2570]
# Bug report
The message, when there are no items, is ugly.

![Schermata da 2020-03-16 18-46-35](https://user-images.githubusercontent.com/472171/76786141-f7f5a080-67b6-11ea-8700-b12111ef721f.png)

### What I did

Simply create an empty model/table

### What I expected to happen

A friendly message like: "No items" istead of "There is 0 items from 0 items by 0 items"

### What happened

Strange message

### What I've already tried to fix it

Nothing

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

Laravel Framework 7.1.3

**Comment by tabacitu** [comment]
Hmm... I think you're right @francescobianco . Now that you mention it, I do think it's ugly 😄 I don't know why this hasn't bothered anyone until now. Thanks for reaching out. I've created PR https://github.com/Laravel-Backpack/CRUD/pull/2571 to fix this, which will soon get merged into ```master```.

Cheers!

**Comment by francescobianco** [comment]
Thanks, @tabacitu, nice to have interacted with you in person.
