### ISSUE TITLE
[4.1.x][Proposal] Change image column to open a modal, instead of tab

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#2588]
For any 'images' that are included in the list table what if it opened in a modal instead of a new window? Feels cleaner then opening a whole new browser window/tab.

**Comment by tabacitu** [comment]
Hmm.. Makes perfect sense, I agree. Technically it's perfectly possible - just like the ```checkbox``` column has javascript, the ```image``` can have it too. 

Don't know how that would work with the rewrite we're doing inside https://github.com/Laravel-Backpack/CRUD/pull/2448 though (where we make it possible for all columns to have links). So let's postpone this to 4.1.x - it'll give us time to gather more feedback and make the changes after custom links are already implemented. Safer that way I think.

Thank @AbbyJanke !

**Comment by tabacitu** [comment]
@AbbyJanke I've thought about this and I don't really see a reason to complicate the `image` column with javascript logic when it can just open a tab instead. So I'm going to close the issue.

I could be wrong, of course. If anybody else thinks differently please reply here with arguments and we'll gladly reopen it. 

Cheers!
