### ISSUE TITLE
[Suggestion] Add "Closure" type for setupUpdateOperation()

### ISSUE THREAD

**Issue by alucard001** [Laravel-Backpack/CRUD#2594]
I have 2 fields that are using the same `id` column of a table.

One field is hidden for update purpose.

Another field is read-only and for display only.

Since if I use the same `name` attribute, either one of the field will not be display, so I would like to use `closure` type to just return the ID of the field for display purpose.

However, only `setupShowOperation()` has closure field available, but not update.

So I hope that can be added.

Thank you.

**Comment by pxpm** [comment]
Hello @alucard001 

ShowOperation does not use fields as Create or Update, it uses columns, the same you use in ListOperation.

Have a look at available fields: https://backpackforlaravel.com/docs/4.0/crud-fields

You might be looking for `custom_html` https://backpackforlaravel.com/docs/4.0/crud-fields#custom_html

Best,
Pedro
