### ISSUE TITLE
select_multiple works, select2_multiple don't

### ISSUE THREAD

**Issue by fede91it** [Laravel-Backpack/crud#26]
When I try to use a **select2_multiple** field instead of a **select_multiple** field, I get this error:

`ErrorException in b58d2ac85e3cfb89e50920aa215a69bd96d9acac.php line 25:
Array to string conversion (View: D:\Progetti\instalmec.it\Instalmec\vendor\backpack\crud\src\resources\views\fields\select2_multiple.blade.php) (View: D:\Progetti\instalmec.it\Instalmec\vendor\backpack\crud\src\resources\views\fields\select2_multiple.blade.php) (View: D:\Progetti\instalmec.it\Instalmec\vendor\backpack\crud\src\resources\views\fields\select2_multiple.blade.php)`

I changed nothing else the field type, from `select_multiple` to `select2_multiple`

**Comment by tabacitu** [comment]
That's very odd, I've just tested and it works perfectly for me. I've even used it in [PageManager](https://github.com/laravel-backpack/pagemanager).

Here's my syntax:
```php
$this->crud->addField([       // Select2Multiple = n-n relationship (with pivot table)
                                'label' => "Tags",
                                'type' => 'select2_multiple',
                                'name' => 'tags', // the method that defines the relationship in your Model
                                'entity' => 'tags', // the method that defines the relationship in your Model
                                'attribute' => 'name', // foreign key attribute that is shown to user
                                'model' => "Backpack\NewsCRUD\app\Models\Tag", // foreign key model
                                'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
                            ]);
```

What's yours?

**Comment by tabacitu** [comment]
Also, have you defined your relationships on your models? That might be the issue.

**Comment by fede91it** [comment]
`App\Http\Controllers\Admin\ProductCrudController`

```php
$this->crud->addField([
	'label'     => 'Tags',
	'type'      => 'select2_multiple',
	'name'      => 'tags',
	'entity'    => 'tags',
	'attribute' => 'name',
	'model'     => 'App\Models\Tag',
	'pivot'     => true,
]);
```

`App\Models\Product`

```php
public function tags()
{
	return $this->belongsToMany('App\Models\Tag');
}
```

`App\Models\Tag`

```php
public function products()
{
	return $this->belongsToMany('App\Models\Product');
}
```

The strange is that the normal select works, it is only the **select2** that doesn't.

**Comment by crameep** [comment]
Same exact issue.

**Comment by fede91it** [comment]
Maybe some directive for tags is hard coded in the CRUD core and goes in conflict?

**Comment by tabacitu** [comment]
EUREKA! Who knew it was a mistake that small? :-) 
You were testing on PHP 7, I was not.

**Comment by fede91it** [comment]
Magic happens switching to PHP 7! 😂

**Comment by joshlewis** [comment]
So, is Backpack not PHP 7 compatible?
