### ISSUE TITLE
"Call to a member function url() on null" when adding an ajax filter with url

### ISSUE THREAD

**Issue by RamiMustaklem** [Laravel-Backpack/CRUD#260]
Filter.php -> line 129

```php
    public function doingListOperation()
    {
        $route = $this->route;

        switch ($this->request->url()) {
            case url($this->route):
                if ($this->request->getMethod() == 'POST' ||
                    $this->request->getMethod() == 'PATCH') {
                    return false;
                }
                return true;
                break;

            case url($this->route.'/search'):
                return true;
                break;

            default:
                return false;
                break;
        }
    }
```

and when you remove this code the container ignores the namespace of the controller and always tries to go through App\Http\Controllers\Admin\EntityCrudController, it does not consider the namespace of the controller.

**Comment by OwenMelbz** [comment]
I'm pretty confused as to what your problem actually is? Its probably best to share your code so people can see what you're trying to do

**Comment by RamiMustaklem** [comment]
I had CRUD package working well, but I did composer update to get the crud updates including the filters stuff, when I addFilter in my controller from the examples provided it gives me this error... 
so basically the request in `switch ($this->request->url()) {` is null.

**Comment by tabacitu** [comment]
Hmm... Can you please provide the code to your EntityCrudController, where you're having the issue? Are you doing everything inside ```__construct()```? What if you rename it to ```setup()```?

**Comment by OwenMelbz** [comment]
@RamiMustaklem we've got a similar issue over [here](https://github.com/Laravel-Backpack/CRUD/issues/268) would you please be so kind to follow the advise, then carry on in the other thread please.

many thanks
