### ISSUE TITLE
Is Backpack 3.6 compatible with Laravel 7 ?

### ISSUE THREAD

**Issue by KevinRignault** [Laravel-Backpack/CRUD#2603]
Hello,

I need to know if it's possible to have Backpack 3.6 with Laravel 7 ?

Thanks for you answer,

**Comment by tabacitu** [comment]
No, unfortunately [Backpack 3.6 only supports Laravel 5.8 and Laravel 6](https://github.com/Laravel-Backpack/Base/blob/master/composer.json#L21). For Laravel 7, you can only use Backpack 4.0, or 4.1 which we plan on releasing very very soon (free upgrade). 

Cheers!
