### ISSUE TITLE
[Feature request] set default value in select2_from_ajax

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2605]
Hello,

I think it is nice to be able to set `default` attribute for the `select2_from_ajax` field.

Thanks.

**Comment by mamprogr** [comment]
As I see, it is working but missing in docs [select2_from_ajax](https://backpackforlaravel.com/docs/4.0/crud-fields#select2_from_ajax)

**Comment by tabacitu** [comment]
Indeed, ```default``` is available for ALL field types. We'll see how we can make that more obvious. Cheers!
