### ISSUE TITLE
[4.0] select2_from_ajax "Collection::getKey does not exist"

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2606]
# Bug report

### What I did

I used `select2_from_ajax` field.

`['name' => 'city'            	, 'label' => trans('admin.city'), 'type' => 'select2_from_ajax', 'minimum_input_length' => 0, 'include_all_form_fields' => true, 'placeholder' => "Select a city", 'entity' => 'city', 'attribute' => "name", 'data_source' => url("api/city"), 'default' => '1']`

### What I expected to happen

The update page to work.

### What happened

The insert page is working fine, but the update page shows an error.
![image](https://user-images.githubusercontent.com/734475/77834710-a276a780-7157-11ea-9a7b-a616ad812426.png)

### What I've already tried to fix it

Adding `[0]` here solves the error:
![image](https://user-images.githubusercontent.com/734475/77834798-61cb5e00-7158-11ea-808e-ecf283bd2a75.png)

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.0 (cli) (built: Nov 27 2019 10:14:18) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.0.8@d71ba61d51aec79a0a0f907991ec215dc24b09d4

### BACKPACK VERSION:
4.0.53@2305b74390a58dc1b7e9b2c5798a663f60cdcd62

**Comment by tabacitu** [comment]
@mamprogr  it works fine on [demo.backpackforlaravel.com](https://demo.backpackforlaravel.com/admin/monster) - so I'm pretty sure it's not a bug in Backpack.

Your error most likely stems from what you've done inside the method that actually returns the results (the api). Take a closer look at the [example in the docs](https://backpackforlaravel.com/docs/4.0/crud-fields#select2_from_ajax) and [the example in the demo](https://github.com/Laravel-Backpack/demo/blob/master/app/Http/Controllers/Api/ArticleController.php). I'm glad you fixed it yourself, but I think it's better you take a closer look at your API, and not overwrite this field just to fix this.

Cheers!
