### ISSUE TITLE
[4.1-beta][Feature] A different field for editing markdown, retire SimpleMDE

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2613]
SimpleMDE has not received an update in 4 years, and recently I've started receiving security alerts about it. Nothing we should worry about _yet_, but considering it's abandoned, we can be pretty sure that when a big problem will be discovered, it won't be fixed.

We should retire ```simplemde``` in favour of some other editor for markdown. I've done a little research and found:
- [tui editor](https://github.com/nhn/tui.editor/tree/master/apps/jquery-editor) - seems to look & work great;
- [editor.md](https://pandao.github.io/editor.md/index.html) - seems a bit targeted at Chinese developers; we should double-check if the documentation is all in English and everything's ok;

If anybody knows of a better Markdown WYSIWYG editor - please let me know.

**Comment by ziming** [comment]
The thing i like about simplemde is how it doesn't assume user know how to bold text or do bullet points through shortcut keys and provide icons to click for them. Hopefully the replaced markdown editor is do that too.

**Comment by tabacitu** [comment]
[EasyMDE](https://github.com/Ionaru/easy-markdown-editor) seems to be a very well-maintained fork of SimpleMDE. I think it's best to use this one.

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/CRUD/pull/2737
