### ISSUE TITLE
[Help] Sending data to custom view 

### ISSUE THREAD

**Issue by rUriarteDev** [Laravel-Backpack/CRUD#2616]
Good morning, I know that this is not the place to be and it is one more question for stackoverflow, but maybe someone here can give me a quick hand with this.
I need to send data to a custom view, is this possible? In the documentation it only appears as overwriting the view with the API. But it doesn't specify if we can send data to that custom view. 
Try to do it like this but it didn't work.
Inside setup method in my crudController
```
$menus = Menu::where('comedor_id', backpack_user()->persona->comedor_id)->get();
$this->crud->setListView('personalizadas.vistaMenuAsignado', ['menus'=>$menus]);
```

**Comment by pxpm** [comment]
Indeed this is not the right place for this kind of questions, and if you know that, you shouldn't have done it :stuck_out_tongue_closed_eyes: 

Anyway, one approach would be using a view composer. https://laravel.com/docs/7.x/views#view-composers

Also you can ovewrite the index() in ListOperation. Check how it's done there and adapt to your scenario.

Best,
Pedro

**Comment by rUriarteDev** [comment]
Sorry for the inconvenience, I'll take a look at it, thanks in advance for your support @pxpm

**Comment by tabacitu** [comment]
Heads-up, if you're inside a CrudController, everything inside the ```data``` property on that controller will get sent to the view. So you can do:

```php
public function setup()
{
    // ..
    $this->data['custom_smth'] = 'smth';
    // ..
}
```

and you'll have ```$custom_smth``` inside the view.

**Comment by rUriarteDev** [comment]
Excellent and simple, as always. Thanks
