### ISSUE TITLE
[4.0][Bug] Cannot set the setting value using in CrudController

### ISSUE THREAD

**Issue by shadowbane** [Laravel-Backpack/CRUD#2617]
# Bug report

Error when trying to set 'settings' value, using `$this->crud->setting('key', 'val')`
The error is caused by wrong function call on line 77 of `Backpack\CRUD\app\Library\CrudPanel\Traits\Settings`.

### Backpack, Laravel, PHP, DB version
```
### PHP VERSION:
PHP 7.4.1 (cli) (built: Dec 18 2019 14:46:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.3.0@36d8958b5b8058ef0641806e490f91102fdea70d

### BACKPACK VERSION:
4.0.57@fd2fbb2ffae3eb6ee520317c83b0516f9fe91f01
```

**Comment by tabacitu** [comment]
Fixed by https://github.com/Laravel-Backpack/CRUD/pull/2618

Thanks @shadowbane !
