### ISSUE TITLE
[4.0][Bug] Don't format zero value in listview

### ISSUE THREAD

**Issue by giordo** [Laravel-Backpack/CRUD#2622]
# Bug report
in listview, using decimals, dec_point, thousands_sep, don't format a number if it is '0' ( I need to view 0,00)

### What I've already tried to fix it

change line 4 in vendor\backpack\crud\src\resources\views\crud\columns\number.blade.php

-- if ($value != null) {
++  if  (!is_null($value)) {

### Backpack, Laravel, PHP, DB version
backpack 4.0
When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.12 (cli) (built: Nov 19 2019 13:58:02) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.2.2@de01e2926a7560c43fb763d86de134a52b46928b

### BACKPACK VERSION:
4.0.57@fd2fbb2ffae3eb6ee520317c83b0516f9fe91f01

**Comment by tabacitu** [comment]
Thank you @giordo , i agree that's the intuitive behaviour, let's change it.

Wouldn't you like to submit a PR with this change, so that _you_ show up as a contributor inside Backpack? Since it's such a small change I think you can do it all from the Github interface.

Or should I just go ahead and make the change myself?

Cheers!

**Comment by pxpm** [comment]
Thank you very much @giordo for raising the issue and submitting a possible fix.

@tabacitu I see this has been addressed in 4.1 https://github.com/Laravel-Backpack/CRUD/commit/c3e094066d1b34d59a1622138f6f99b6c11948c1 , why not in 4.0 directly ? 

Best,

**Comment by tabacitu** [comment]
Well... I probably _thought_ we'll be launching 4.1 soon enough then. But... it got delayed. Again 😄 Let's fix it in 4.0 too, I agree. Can you please create a PR for this @pxpm so we can close this issue?

**Comment by tabacitu** [comment]
Oorr... on second thought. Since issue has been there for YEARS and nobody complained until now. It might be perfectly fine to only have it fixed only in 4.1 😄 So I'll close the issue now, even if there's no PR to fix it in 4.1.

Thanks again for reporting this @giordo !

**Comment by eberjblanco** [comment]
saludos!
Para corregir los errores de  dec_point y  thousands_sep en backpack vaya a la ruta 

\backpack\crud\src\resources\views\columns\number.blade.php

Y sustituya todo el codigo por este:

{{-- regular object attribute --}}
<span>{{ (array_key_exists('prefix', $column) ? $column['prefix'] : '').
	number_format(
	$entry->{$column['name']}, 
		array_key_exists('decimals', $column) ? $column['decimals'] : 0, 
		array_key_exists('dec_point', $column) ? $column['dec_point'] : 0,
		array_key_exists('thousands_sep', $column) ? $column['thousands_sep'] : 0,
	)
	
	.(array_key_exists('suffix', $column) ? $column['suffix'] : '') }}</span>
