### ISSUE TITLE
Can't edit colums in setupShowOperation

### ISSUE THREAD

**Issue by categoryshell** [Laravel-Backpack/CRUD#2626]
# Bug report

### What I did

I modified a column so it will get its value from an relation

### What I expected to happen

The existing column will get a new value

### What happened

The column remained unchanged

### What I've already tried to fix it

I can add colums, with normal values or values from relations.
I cannot modify or remove existing columns in the show view.

### Backpack, Laravel, PHP, DB version
PHP 7.4.3 (cli) (built: Feb 20 2020 21:53:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

mysql  Ver 15.1 Distrib 10.4.12-MariaDB, for debian-linux-gnu (x86_64) using rea
dline 5.2

When I run ```php artisan backpack:version``` the output is:
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.3.0@36d8958b5b8058ef0641806e490f91102fdea70d

### BACKPACK VERSION:
4.0.58@03432680d8ed839bcbd99ce57aed61bcf7a1b695

**Comment by categoryshell** [comment]
Okay, i found a workaround.

In `setupShowDefaults()` i had to set the operationsetting setFromDb to false:
```
$this->crud->setOperationSetting('setFromDb', false);
```

Then in setupShowOperation, re-set it with:
```
 $this->crud->setFromDb();
```

After that, i could remove/modify the colums.

**Comment by tabacitu** [comment]
Thanks for sharing your solution, @categoryshell . Note that if you want that behaviour for all CRUDs, you can add that setting to your ```config/backpack/crud.php``` file:

```diff
    'operations' => [

        /*
         * Show Operation
         */
        'show' => [
            // Define the size/looks of the content div for all CRUDs
            // To override per Controller use $this->crud->setShowContentClass('class-string')
            'contentClass' => 'col-md-8',
+
+           // Should the Show operation try to add all columns using setFromDb()?
+           'setFromDb' => false,
        ],
```

**Comment by DanielBalsalobre** [comment]
I found a problem related to this.
If you include 'model' => in modify/add column on setupShowOperation then ignores the modification.
Removed 'model' attribute on  modifyColumn/addColumn and its show the name instead id of relationship.
