### ISSUE TITLE
Add Field Names As Classes To Each Field Template Wrapper

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/CRUD#263]
If frontend devs want to quickly style a field template without extending it, they currently cannot as they do not have a unique class to identify each form field as.

As an example, here's what a current output looks like for a field:

```html
<div class="form-group col-md-12">
    <!-- My field's custom HTML -->
</div>
```

Here's an alternative:

```html
<div class="form-group col-md-12 form-field_{{MY-FIELD-IDENTIFIER}}">
    <!-- My field's custom HTML -->
</div>
```

Now as a frontender, I can target `.form-field_{{identifier}}` without touching code.

Two solutions:

1. Update _every_ field template to add the inflected field identifier as a class.
2. Change field views to be partials of a `field-wrapper.blade.php` template. The wrapper has the sole job of adding the first line in the examples above, and then yields the field template.

**Comment by zschuessler** [comment]
I see that the `inc` folder in crud has a couple interesting ideas already!

Files:

1. `field_attributes.blade.php`
2. `field_wrapper_attributes.blade.php`

Only two issues knowing this new information. First, no way to dynamically have the classes set for you. And second, most of the actual field templates don't make use of these wrapper templates. (I've only stumbled upon them after seeing one field template use it)

**Comment by tabacitu** [comment]
Hi @zschuessler ,

Indeed, those are the two options, they're a little bit hidden in the [fields documentation](https://laravel-backpack.readme.io/docs/crud#section-fields).  You can do this:
```php

$this->crud->addField([
     // MANDATORY
    'name'  => 'address', // DB column name (will also be the name of the input)
    'label' => 'Street address', // the human-readable label for the input
    'type'  => 'text' // the field type (text, number, select, checkbox, etc)
    
     // OPTIONAL + example values
    'default'    => 'some value', // default value
    'hint'       => 'Some hint text', // helpful text, show up after input
    'attributes' => [
       'placeholder' => 'Some text when empty',
       'class' => 'form-control some-class'
     ], // extra HTML attributes and values your input might need
     'wrapperAttributes' => [
       'class' => 'form-group col-md-12'
     ] // extra HTML attributes for the field wrapper - mostly for resizing fields using the bootstrap column classes
]);
```

What version of Backpack/CRUD are you using? I know we've already gone through them and made sure all fields have the ```attributes``` and ```wrapper_attributes``` functionality.

Cheers!

**Comment by zschuessler** [comment]
> What version of Backpack/CRUD are you using? I know we've already gone through them and made sure all fields have the attributes and wrapper_attributes functionality.

Ah you're right! Very sorry, my version was a bit too old. Will try to make sure I'm looking at dev-master before filing any other issues in the future. Thanks!
