### ISSUE TITLE
I want to add a specific js file to a page of specific entity crud

### ISSUE THREAD

**Issue by meysamm22** [Laravel-Backpack/CRUD#2634]
I want to add a specific js file to a page of specific entity crud. (example: I want to add Tag-insert.js to the insert page of Tag crud)

Is there any way to do this?

**Comment by pxpm** [comment]
Hello @meysamm22 

You could use a widget to insert custom javascript in the crud page. 

Check out the docs for widgets. Focus on after_scripts section. 

Best,
Pedro
