### ISSUE TITLE
[4.1][Bug] Field with autofocus error in create

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#2637]
# Bug report
Facade\Ignition\Exceptions\ViewException
Undefined index: value (View: C:\laragon\www\crudContact\vendor\backpack\crud\src\resources\views\crud\form_content.blade.php)

$focusFieldName = !is_iterable($focusField['value']) ? $focusField['name'] : ($focusField['name'] . '[]');

### What I did
```
        $this->crud->addField([
            'name'  => 'name_first',
            'label' => trans('contact.name.first'),
            'type'  => 'text',
            'tab'   => trans('contact.names'),
            'attributes' => ['id' => 'name_first'],
            'wrapperAttributes' => ['class' => 'form-group col-md-6'], //resizing
            'entity' => 'names', 
            'auto_focus' => 'true',
            ]);
```

### What I expected to happen

focus in field "name_first"

### What I've already tried to fix it

add the value in the field and not fail. But editing this field loses its value saved in the registry.

```
        $this->crud->addField([
            'name'  => 'name_first',
            'label' => trans('contact.name.first'),
            'type'  => 'text',
            'tab'   => trans('contact.names'),
            'attributes' => ['id' => 'name_first'],
            'wrapperAttributes' => ['class' => 'form-group col-md-6'], //resizing
            'entity' => 'names', 
            'auto_focus' => 'true',
            'value' => '',
            ]);
```

I have also tried adding the create / update option and it doesn't work for me.

```
        $this->crud->addField([
            'name'  => 'name_first',
            'label' => trans('contact.name.first'),
            'type'  => 'text',
            'tab'   => trans('contact.names'),
            'attributes' => ['id' => 'name_first'],
            'wrapperAttributes' => ['class' => 'form-group col-md-6'], //resizing
            'entity' => 'names', 
            'auto_focus' => 'true',
            'value' => '',
            ], 'create');
        $this->crud->addField([
            'name'  => 'name_first',
            'label' => trans('contact.name.first'),
            'type'  => 'text',
            'tab'   => trans('contact.names'),
            'attributes' => ['id' => 'name_first'],
            'wrapperAttributes' => ['class' => 'form-group col-md-6'], //resizing
            'entity' => 'names', 
            'auto_focus' => 'true',
            ], 'update');
```

### PHP VERSION:
PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v6.18.3@4e48acfaba87f08320a2764d36c3b6a4a4112ccf

### BACKPACK VERSION:
4.1.x-dev@05bf67462133fce32b6239e8637ba6ed68383011

**Comment by tabacitu** [comment]
Wow @DanielKimmich - I'm impressed. How did you learn about the ```auto_focus``` feature? It's super-undocumented. Even I forgot all about it 😆 

Anyway, thanks for the bug report. It's now fixed in 4.1 since https://github.com/Laravel-Backpack/CRUD/commit/80e375eb2b667fcfe36e4f907e3188e12069552c .

Cheers!

**Comment by tabacitu** [comment]
Also, I know you installed 4.1 two weeks ago or something. If you do a ```composer update``` to get the latest 4.1, please note that this past week we've pushed the last of the breaking changes - so your app might crash. A relatively easy way to see what we've pushed since you installed it is to take a look at [the commits of our Docs repo](https://github.com/Laravel-Backpack/docs/commits/master), and see what we've changed since you last ran ```composer update```.

Most notable breaking changes this week:
- [Step 9](https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-9) - we've removed BackpackUser;
- [Step 12](https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-12) - fields ```wrapperAttributes``` was renamed to ```wrapper```;

Hope it helps. 

PS. We're at feature-freeze so no more breaking changes on 4.1 starting today. Only bug fixes. So this won't happen again.

**Comment by DanielKimmich** [comment]
Thank you very much for always keeping updated and with new functionalities. Although I had some problems with 4.1, in case I can't solve it, I report the case to you, I hope this doesn't bother you.
Cheers,

**Comment by tabacitu** [comment]
Not at all @DanielKimmich . That's why we're keeping it in beta for now - to find & squash bugs before thousands of people install it. You're doing us a big service, keep at it!
