### ISSUE TITLE
Allow Setting CRUD View Template By Creating File in App

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/CRUD#264]
I should be able to use a custom template for any CRUD action by adding a template file alone.

Example: a file `edit.blade.php` placed in my local `resources/views/{$myBackpackPrefix}/{$myEntityName}/` should be autoloaded without any further configuration of the controller.

May be accomplished with something like this:

**CrudController.php**
```php
public function edit($id)
{
    ...
    /**
     * Check For User-Extended View
     *
     * A blade file in `resources/views/{base_prefix}/{entity_name}/ will override
     * the default view.
     */
    $extendedViewPath = $this->crud->getRoute() . '/edit';
    if (\View::exists($extendedViewPath)) {
        return view($extendedViewPath, $this->data);
    }

    // render default view
    return view('crud::edit', $this->data);
```

Any issues with this implementation?

**Comment by tabacitu** [comment]
Hi @zschuessler ,

I did have this in mind when creating the packages :-) ```return view('crud::edit', $this->data);``` should already be doing that. That's what the [laravel docs](https://laravel.com/docs/5.3/packages#views) say and I've just tested it and it works. Just place your view into your app's ```/resources/views/backpack/crud/```.

Or do you mean you'd like different "edit.blade.php" files, for different entities?

Cheers!

**Comment by jsiebach** [comment]
You can create this functionality by over-writing the show method on the crud controller:

    public function show($id)
    {
        $this->crud->hasAccessOrFail('show');

        // get the info for that entry
        $this->data['entry'] = $this->crud->getEntry($id);
        $this->data['crud'] = $this->crud;
        $this->data['title'] = trans('backpack::crud.preview').' '.$this->crud->entity_name;

        if(\View::exists('crud::' . $this->crud->entity_name . '.show'){
          return view('crud::' . $this->crud->entity_name . '.show', $this->data);
        }

        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view('crud::show', $this->data);
    }

I use this pattern in my application as well and think this would be great to build into all of the `CrudController` methods!

**Comment by zschuessler** [comment]
@tabacitu Correct on the per-entity files! I now see I wasn't abundantly clear on that, sorry.

Something like @jsiebach did, but perhaps using the `getRoute()` method for the path instead. That allows you to get the controller name, too.

So with implementing the `getRRoute()` in my specific case, the path is `views/account/product/show` instead of `views/product/show`. Could be useful for when you have multiple controllers sharing an entity, I suppose.

**Comment by OwenMelbz** [comment]
maybe something like

```php
return view($this->getTemplate('show'), $this->data);
```

this way you can add your own `getTemplate` function which returns customised views
