### ISSUE TITLE
Securing select2_from_ajax API calls

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2641]
Hello,

When I use `select2_from_ajax `, I put `Route::get('/api/category', 'Api\CategoryController@index');` for example in routes/api.php

I want to allow the API call for logged in users only. How to do that?

If I use a middleware, the ajax request return `401 Unauthorized`.

**Comment by tabacitu** [comment]
We recommend you add your routes in the same route file as your CRUDs - ```routes/backpack/custom.php```. That way they're protected by the same middleware. That's what we recommend [in the docs](https://backpackforlaravel.com/docs/4.0/crud-filters#select2_ajax), that's what I recommend to you too 😉
