### ISSUE TITLE
[4.1.x] Fluent syntax FieldGroup

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2642]
For when you want to apply a change/definition to multiple fields. The syntax I have in mind is something like this:

```php
        CRUD::fieldGroup([
            CRUD::field('text'),
            CRUD::field('number')->type('number'),
            CRUD::field('email')->type('email'),
        ])
        ->tab('Simple')
        ->size(6);
```

The name might still need some work:
```php
CRUD::fieldGroup([]); // singular
CRUD::fieldGroup([]); // plural maybe?!?!
CRUD::fields([]); // this already exists as a getter though
```

For this to happen, we need to create a new object, ex FieldGroup or FieldCollection, which would be Fluent to allow subsequent calls on it, and each call would basically forward that call to the fields inside that group, to modify their definition.

**Comment by sergeyugai** [comment]
hi @tabacitu,
here i am again with my backpack-fields package :)
I did something similar here: https://github.com/sergeyugai/backpack-fields-as-classes#field-collections - so once #2604 is resolved (or, well, when documentation is updated), I can re-generate my backpack fields and add your syntax as well.

**Comment by tabacitu** [comment]
Update: there's a working PR for this from @pxpm . Anybody who stumbles upon this please check out #2951 . Especially you @sergeyugai - you have the most experience with this 😄 

I'll close this issue since it's best to talk about it inside the PR.
Cheers!
