### ISSUE TITLE
Unable to update in 4.1 composer.json conflict

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#2646]
# Bug report

### Just try to update from version 4.x 

`
"backpack/crud": "^4.1.0",
"backpack/permissionmanager": "4.1.x-dev as 5.0.99|^6.0.0",
"spatie/laravel-translatable": "^4.0",
"barryvdh/laravel-elfinder": "^0.4.3",
`

### What I expected to happen

Just upgrade to 4.1

### What happened

 [UnexpectedValueException]
  Invalid version string "5.0.99|^6.0.0" in "4.1.x-dev as 5.0.99|^6.0.0", the alias must be an exact version

### What I've already tried to fix it

Make prefer-stable to false but I think it's not a solution

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.8 (cli) (built: Jul 30 2019 12:44:06) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.9.0             The Laravel Framework.

### BACKPACK VERSION:
backpack/crud                         4.0.31             Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.5              Generate files for laravel projects
backpack/permissionmanager            5.0.3              Users and permissions management interface for Laravel 5 using Backpack CRUD.

**Comment by DanielKimmich** [comment]
I also had problems, see this link on how to install. Hope this can help you.

https://github.com/Laravel-Backpack/Generators/issues/67#issuecomment-606417804

**Comment by t-prod** [comment]
Thanks Daniel for your help. I closed this one ;)

**Comment by tabacitu** [comment]
Right! It should be the other way around, sorry. First the final version, then fall back to 4.1.x-dev with alias. Changed the [docs](https://github.com/Laravel-Backpack/docs/commit/59af2f332ce446adfb1be6912770da960d12f75d). The requirements should be:

```php
// require

        "backpack/newscrud": "^4.0.0|4.1.x-dev as 3.0.99",
        "backpack/permissionmanager": "^6.0.0|4.1.x-dev as 5.0.99",

// require-dev

        "backpack/generators": "^3.0|4.1.x-dev as 3.0.0",

```
