### ISSUE TITLE
[4.1] [Fix] repeatable field with new wrapper includes

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#2648]
Hi, 

I've done a PR for this but how can I send it to you ? Can you five me permissions to add pull requests ?
The repeatable field is not with the good wrapper includes. When do you plan a 4.1 final version ?

![image](https://user-images.githubusercontent.com/1824638/78599434-6925f200-7851-11ea-9486-b8cbf08381ee.png)

**Comment by tabacitu** [comment]
Sure, I've sent an invite. But it should be possible to send a PR without it too - that's how many people send PRs. After accepting the PR you should be able to do:

```php
git checkout -b add-wrapper-to-repeatable-field
git add .
git commit -m "added wrapper to repeatable field"
git push origin/add-wrapper-to-repeatable-field
```

Then you'll be able to open the PR from the Github UI, there should even be a notification on https://github.com/Laravel-Backpack/CRUD

Backpack 4.1 is officially in beta now. We're testing & bug fixing, but it's ready for action, we expect no breaking changes until launch. I guess it depends on how many bugs we find, but we'll probably launch in ~2 weeks or so. By then, all our personal projects will be upgraded, to make sure we find all bugs we can, and battle-test the upgrade guide. 

Thank you for joining us - the more people use 4.1 while in beta, the better it gets before launch. Thanks a lot for the help!

**Comment by t-prod** [comment]
Hi Cristian,

My first PR is sent and added by you  ;) Thanks for your answer.

Regards
