### ISSUE TITLE
Filters not cleaning properly

### ISSUE THREAD

**Issue by telemaco230** [Laravel-Backpack/CRUD#2653]
# Bug report

### What I did

I setup a controller, as usual. For instance a subclass of UserCrudController, in order to setup some filters.

### What I expected to happen

I access the section for user administration, apply some filter's (email, username, etc.) and the filters are working as expected.

### What happened

When I click on "remove filters" button, filters are cleared but table shows no data.
No errors registered at any log;

### What I've already tried to fix it

Nothing.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.24-1+0~20191026.31+debian9~1.gbpbbacde (cli) (built: Oct 26 2019 14:18:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-1+0~20191026.31+debian9~1.gbpbbacde, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.4.0@dafdd1e19f86add02e48fa9f6cac9be2c5329772

### BACKPACK VERSION:
4.0.58@03432680d8ed839bcbd99ce57aed61bcf7a1b695

**Comment by pxpm** [comment]
Please complete the remain info of the issue. Especially the part of `php artisan backpack:version`

Also it would help to see how you'd setup your filters. Any console errors ? Any error in laravel logs??

**Comment by telemaco230** [comment]
Already included the required information.
The only thing I could do is to call "document.location.reload()" on "remove filters" click event (filters_navbar.blade.php)):

      // button to remove all filters
      jQuery(document).ready(function($) {
      	$("#remove_filters_button").click(function(e) {
            e.preventDefault();

            // behaviour for ajax table
            var new_url = '{{ url($crud->route.'/search') }}';

            console.log('URL para datatable: ' + new_url);

            var ajax_table = $("#crudTable").DataTable();

            // replace the datatables ajax url with new_url and reload it
            ajax_table.ajax.url(new_url).load();

            // clear all filters
            $(".navbar-filters li[filter-name]").trigger('filter:clear');

            // remove filters from URL
            crud.updateUrl(new_url);
            document.location.reload();
      	});

**Comment by pxpm** [comment]
Check if it's the same problem as #2645 .

Clear browser storage. If you are starting a new project we encourage you to start from 4.1 branch, it as also a reset button that may come handy in this scenarios. 

Let me know how it goes.

**Comment by telemaco230** [comment]
Following the installation instructions, once you setup a brand new laravel project (also with database configuration), how do I instruct composer to install 4.1 branch, instead of 4.0?

Thanks.

**Comment by telemaco230** [comment]
Nevermind.

Found the doc. I'll give a try and come back to you with the results.

**Comment by telemaco230** [comment]
Had a problem deploying PermissionManager: BackpackUser is not being generated on laravel 7.3

**Comment by pxpm** [comment]
@telemaco230 BackpackUser has been removed in 4.1 branch. You should point it to your user model instead. 

I am going to close this. If you need help you better asking in gitter or stackoverflow, we use github for bugs/features.

I will let the bot close this one so you get the links to other mediums :)

**Comment by telemaco230** [comment]
Thank you Pedro for all the support!

**Comment by tabacitu** [comment]
Update: Re-discovered this same issue. Fixed by #3177 hopefully.

**Comment by telemaco230** [comment]
Thanks!

 

De: Cristian Tabacitu [mailto:notifications@github.com] 
Enviado el: miércoles, 2 de septiembre de 2020 14:22
Para: Laravel-Backpack/CRUD <CRUD@noreply.github.com>
CC: telemaco230 <telemaco230@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [Laravel-Backpack/CRUD] Filters not cleaning properly (#2653)

 

Update: Re-discovered this same issue. Fixed by #3177 <https://github.com/Laravel-Backpack/CRUD/pull/3177>  hopefully.
