### ISSUE TITLE
[4.0]menu.blade.php should use named route for login

### ISSUE THREAD

**Issue by juventus18** [Laravel-Backpack/CRUD#2657]
The `vendor\backpack\crud\src\resources\views\base\inc\menu.blade.php` file should use a named route for login link instead of the `url()` generator. The "register" link already uses a named route. Doing so allows the developer to override the named route (i.e. "/login" instead of "/admin/login") without resorting to modifying the  `vendor\backpack\crud\src\resources\views\base\inc\menu.blade.php` file.

I will submit a PR in a few minutes.

**Comment by tabacitu** [comment]
Fixed by #2658
