### ISSUE TITLE
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error

### ISSUE THREAD

**Issue by h3ndro** [Laravel-Backpack/CRUD#266]
Hi, 
I'm a newbie and using Postgresql as my database and also checking out NewsCrud to see how Backpack works. I've come across below exception when i try to create new articles.

`ErrorException in Connection.php line 769:
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "FROM"
LINE 1: SHOW COLUMNS FROM articles WHERE Field = "status"
^ (SQL: SHOW COLUMNS FROM articles WHERE Field = "status")` 

in the `App/Http/Controllers/Admin/ArticleCrudController.php`, we can see this `        $this->crud->addField([ 'name' => 'status', 'label' => 'Status', 'type' => 'enum',]);`.

This maybe related to #114 . Could you help me with this? thank you

**Comment by OwenMelbz** [comment]
Does this only happen with enum types?

**Comment by h3ndro** [comment]
yes,..every time i enable enum type it throw above exception.

**Comment by OwenMelbz** [comment]
After a brief googling, it seems that Postgres and enum in Laravel have limited compatibility, and can sometimes prove tricky.

This is not a CRUD issue as far as I can tell.

My recommendation is just use `varchar` as the column instead

**Comment by h3ndro** [comment]
well,..thank you @OwenMelbz,...i'll see about it in Laravel doc,...thanks again
