### ISSUE TITLE
how to use && in controller of laravel backpacker?

### ISSUE THREAD

**Issue by sokvebolkol** [Laravel-Backpack/CRUD#2661]
# Bug report
Load message error. Because of the wrong condition in function setup(){};
### What I did
I use this addClause:
![image](https://user-images.githubusercontent.com/44717892/78882719-ac1adc00-7a82-11ea-954c-d89ccac9330e.png)

??

### What I expected to happen
I hope I can see all of the records that own user created, but an only normal user. And admin user can see all records of all users.
??

### What happened
I got a message error from the wrong addClause in setup(){}.
??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @sokvebolkol 

We use github for bugs and features only. For any questions regarding help you should use any other available medium like gitter or stackoverflow. 

This seems simple to me:

```php
if(!backpack_user()->hasRole('admin')) {
    $this->crud->addClause( .... );
}
```
