### ISSUE TITLE
[4.1.x] New relationship field

### ISSUE THREAD

**Issue by Athuli7** [Laravel-Backpack/CRUD#2665]
# Bug report

### What I did

Upgraded to v4.1 on staging env

### What happened

Select2 fields and relationship fields fail to work.
The relationship is set properly on Model.

Err:-

```Unable to process relationship data: JudgmentStatus```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.12 (cli) (built: Nov 29 2019 20:07:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.12, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.5.2@3a3b3f7fea69813f5a03449c6314bfb42c3ccf78

### BACKPACK VERSION:
4.1.x-dev@4c1110915362063419c2f7cc5f778237dfcceaa3

**Comment by tabacitu** [comment]
Hi @Athuli7 ,

Seems to be working for me. And in the [4.1 live demo](http://demo-beta.backpackforlaravel.com/admin/login). 

Can you please copy-paste the ```addField()``` statements, and you relationships?

Cheers!

**Comment by tabacitu** [comment]
PS. Notice that for the ```relationship``` field, the name has to be the _relationship name_. Not the foreign key. For example, you have to pass ```category```, not ```category_id``` as you did for ```select2```.

**Comment by Athuli7** [comment]
```
            [
                // 'label' => "Judgment Status",
                'type' => "relationship",
                'name' => 'JudgmentStatus',
                // 'entity' => 'JudgmentStatus',
                // 'attribute' => "val",
                // 'model' => "App\Models\Generic",
                // 'options'   => (function ($query) {
                //     return $query->where('key', 'Judgment Status')->get();
                // }),
                'tab' => 'Management',
            ],
```
```
public function JudgmentStatus() { return $this->belongsTo('App\Models\Generic', 'judgmentstatus') }
```

**Comment by tabacitu** [comment]
@pxpm what do you think? Does it look like a problem with the guessing functionality? Or is it misuse?

**Comment by pxpm** [comment]
Hello @tabacitu 

I think this  implementation issue, at first I tought it was related of having CamelCase, then I tested in demo setting up a relation CamelCased and it worked. 

You don't even need to specify relationship field type, it will be guessed if the field name is a model relation.

**Comment by tabacitu** [comment]
Hmmm... In this case - can you please explain what you did different here when upgrading @Athuli7 ? You just changed the field type from ```select2``` to ```relationship```? Does it still work using ```select2```? If not, what error does it throw then?

**Comment by pxpm** [comment]
No news for past 15 days, probably it's safe to close. 

If this stills an issue please re-open :rotating_light:
