### ISSUE TITLE
[4.1.x][Feature] Filters dependencies 

### ISSUE THREAD

**Issue by soufiene-slimi** [Laravel-Backpack/CRUD#2669]
We should make filters have some dependencies with other filters, for example, if I checked the filter **Only Approved Members** maybe another filter will become useless or will have fewer items, I think this is really useful for UX and for optimization.

**Comment by tabacitu** [comment]
I agree - it sounds like a cool feature. I'll close this in favour of #2640 - let's move the conversation there please, since we're talking about the same thing.

Cheers!
