### ISSUE TITLE
[4.1][Bug] Relationship and addEagerConstraints error

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#2674]
Hi,

With a parent category relationship (in the same model), I have this column
```
$this->crud->addColumn([
                'label' => "Parent Category",
                'type' => "select",
                'name' => 'product_category_id',
                'entity' => 'category',
                'attribute' => "title",
                'model' => "App\Models\ProductCategory"
            ]);
```
Same thing with field by the way

Title is a translatable field and this is the error :

![image](https://user-images.githubusercontent.com/1824638/79310134-b9f5b480-7efb-11ea-85d6-072c755c368b.png)

Maybe 4: {function: "search", class: "App\Http\Controllers\Admin\ProductCategoryCrudController", type: "->"}

When you have a field in translatable I think it causes the error.

Regards

**Comment by t-prod** [comment]
I think it's the same problem with select2_nested, if you have translatable attribute you have error 500 : Unable to process relationship data: parent_id
```
[
                        'type'      => "select2_nested",
                        'label'     => 'Parent Category,
                        'name'      => 'parent_id',
                        'entity'    => 'parent',
                        'attribute' => "title",
                        'model'     => "App\Models\ProductCategory",
                    ],
```

**Comment by tabacitu** [comment]
@t-prod would this be fixed by #2670 ? If so, I propose we close this issue, and move the conversation there.

Thanks a lot for reporting the issues, and providing the PR - it helps A LOT.
Cheers!

**Comment by t-prod** [comment]
Hi @tabacitu  unfortunately it's not the same thing despite the PR #2670

**Comment by pxpm** [comment]
I cannot follow this thread i dunno how to test it.

I tried adding a select column for a translatable attribute, it works.

I think this might be fixed will last batches of fixes. 

Going to close this, if the problem persists please re-open and try to clarify your issue. 

Also in the code you provided there are typo errors. 

Best,
