### ISSUE TITLE
[4.1] TinyMCE elFinder not working

### ISSUE THREAD

**Issue by eronisko** [Laravel-Backpack/CRUD#2678]
# Bug report

### What I did

1. ```composer require backpack/filemanager```
2. ```php artisan backpack:filemanager:install```
3. Added a `tinymce` field:

        [
                'name' => 'description',
                'type' => 'tinymce',
        ]

### What I expected to happen

`Insert` -> `Image ...` dialog should have a 'Source' (browse) button.

### What happened

There was no 'Source' (browse) button present.

### What I've already tried to fix it

[barryvdh/laravel-elfinder](https://github.com/barryvdh/laravel-elfinder) already has a fix for TinyMCE5, so **I'll be submitting a PR to implement it.**

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.2.26 (cli) (built: Dec 17 2019 15:29:44) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.5.2@3a3b3f7fea69813f5a03449c6314bfb42c3ccf78

### BACKPACK VERSION:
4.1.x-dev@4c1110915362063419c2f7cc5f778237dfcceaa3
```

**Comment by tabacitu** [comment]
Thank you so much for taking the time to report AND send a PR for this @eronisko ! I'll close this issue so we continue the conversation inside the PR, if needed. I'll take a look at it shortly.

Cheers!
