### ISSUE TITLE
Register Custom Doctrine Column Type Mappings

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/CRUD#269]
When using the `enum` or `json` types (or any others doctrine doesn't map natively, yet), an uncatched fatal error results.

This isn't _necessarily_ a problem with CRUD, but for a more dev-friendly experience we could add defaults for these column types.

Column maps are called here:
https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/AutoSet.php#L17

Here's a hacky solution (need something more user-extensible, but you get the idea)

```php
public function setFromDb()
    {
        $this->addCustomDoctrineColumnTypes(); // let's add some defaults, eh?
        $this->getDbColumnTypes();
```
```php
public function addCustomDoctrineColumnTypes()
    {
        $dbPlatform = \Schema::getConnection()->getDoctrineSchemaManager()->getDatabasePlatform();
        $dbPlatform->registerDoctrineTypeMapping('enum', 'string');
        $dbPlatform->registerDoctrineTypeMapping('json', 'json_array');
    }
```

Not sure what implications this could have since I'm not aware of the full CRUD architecture. I will say, though, that native support in Laravel&dbal is a hot topic that probably[ won't resolve soon](https://github.com/laravel/framework/issues/1186).

If you want to reproduce this problem, just make a json or enum column in a migration, and try to view a CRUD list page. I'm running on MySQL 5.7.16, which has json column support.

**Comment by OwenMelbz** [comment]
Hi @zschuessler 

I'm just consolidating a list of issues like this which can be seen https://github.com/Laravel-Backpack/CRUD/issues/285 so I'm going to close this to keep the area tidy, but it will still be referenced :)

**Comment by muya** [comment]
In case anyone's looking, I detailed my implementation of @zschuessler's fix here: https://goo.gl/ac3Eks

**Comment by zschuessler** [comment]
Well done! Nice post :)
