### ISSUE TITLE
We want to use setupCreateOperation function for setValidation(StoreRequest::class) or else?

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2698]
I plan to upgrade backpack 3.6 to 4.0. So that i looked the upgrade guide. I noticed now we want to use FormRequest validation in v4 then we want to use like 
`protected function setupCreateOperation()
{
      $this->crud->setValidation(StoreRequest::class);
}
protected function setupUpdateOperation()
{
     $this->crud->setValidation(UpdateRequest::class);
}`

Here my question is if i use FormRequest validation for storing When i use `setupCreateOperation()` function or if you have anything call `setupStoreOperation()` function?
 What about this?

**Comment by tabacitu** [comment]
Sorry @senthu1994 , I don't understand. Could you please rephrase?

**Comment by senthu1994** [comment]
@tabacitu i updated my question. Thanks.

**Comment by pxpm** [comment]
Yes, you should setup the validators inside create and update operations. 

Create operation is both responsible for setting up the form and validating on submission.

Going to close this. It's not an issue. If I am wrong please re-open, sometimes I am :)  

Best,

**Comment by senthu1994** [comment]
> Yes, you should setup the validators inside create and update operations.
> 
> Create operation is both responsible for setting up the form and validating on submission.
> 
> Going to close this. It's not an issue. If I am wrong please re-open, sometimes I am :)
> 
> Best,

@pxpm Thanks I got it.
