### ISSUE TITLE
[4.0][BUG] User avatar link on navbar is center aligned.

### ISSUE THREAD

**Issue by ahmadmrj** [Laravel-Backpack/CRUD#2701]
# Bug report
On rtl theme "user avatar link" is supposed to be on left top corner but it's center aligned.

The problem is when RTL is active, both ```margin-left: auto !important;``` and ```margin-right: auto !important;``` apply on the section.

I think, adding a ```mr-0``` on RTL mode class can solve the problem.
### Backpack, Laravel, PHP, DB version
Backpack 4.0

**Comment by tabacitu** [comment]
Thanks for the PR @ahmadmrj ! Merged.
