### ISSUE TITLE
[4.1] Fetch search multiple attributes, doc identifiable attribute

### ISSUE THREAD

**Issue by Evanslooten** [Laravel-Backpack/CRUD#2704]
# Bug report

### What I did

Searched a relationship field in the Create screen

### What I expected to happen

Entities for the targeted model to be listed in the Select2 field

### What happened

SQL query failed. Without explicitly defining the 'identifiableAttribute' on the target Model, the CRUD field definition is ignored. In my case, created_at was used to search, possibly because it was the first column in the table.

### What I've already tried to fix it

Declared identifiableAttribute on the target Model. Cannot overwrite the searched column by passing a value to the CRUD field definition.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.11-0ubuntu0.19.10.4 (cli) (built: Apr  8 2020 18:58:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.4, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.7.1@4de129177f889cd7672e732d8808020adfb7b121

### BACKPACK VERSION:
4.1.x-dev@78a89604e4d8571671bb9ec6f2d626a1e8150078

### Field Definition ###

$this->crud->addField([
            'type' => 'relationship',
            'attribute' => 'Common_Name',
            'entity' => 'species',
            'name' => 'species',
            'model' => 'App\Models\Plant\Species',
            'label' => 'Species',
            'placeholder' => 'Select Species',
            'ajax' => true,
            'incline_create' => true,
            'include_all_form_fields' => false
        ]);

### AJAX Response ###

"SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: 'Amer' (SQL: select count(*) as aggregate from `Species` where `created_at` = Amer)"

**Comment by pxpm** [comment]
Hello, @Evanslooten .

Thanks for your report. 
You could override the searchable attribute in you `fetchEntity()` function definition. 

```php
return $this->fetch([
'model' => 'App\Model',
'searchable_attributes' => 'attribute'
]);
```
We are working on `identifiableAtrribute` documentation. 

You could setup the property `public $identifiableAttribute = 'attribute';` in the model. 

Let me know.
Best

**Comment by Evanslooten** [comment]
Thank you, I was able to specify a single attribute using the searchable_attributes syntax. 

You mentioned you are working on the documentation so you are likely already aware, but for what its worth the Fetch documentation shows the syntax below. The camel case version does not work for me using both a single string and an array of strings as values. The case you indicated above works for singular columns only, as either a string or a single element array, but not for multiple columns.

```
return $this->fetch([
            'model' => App\Models\Tag::class, // required
            'searchableAttributes' => ['name'],
            'paginate' => 10, // items to show per page
            'query' => function($model) {
                return $model->active();
            } // to filter the results that are returned
        ]);
```

**Comment by pxpm** [comment]
Once again thank you very much for taking time to bring this to our attention. I will ping @tabacitu about the documentation part and I will have a look at multiple searchable attributes. 

Wish you the best. 
Pedro

**Comment by pxpm** [comment]
Going to close this, both issues have been fixed. #2722 and https://github.com/Laravel-Backpack/docs/pull/119

Once again, thank you very much @Evanslooten for bring this up.
