### ISSUE TITLE
How to use $this->getSaveAction() method in backpack 4.0?

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2710]
I used `$this->getSaveAction()` method in `backpack 3.6` and it located in `Backpack\CRUD\app\Http\Controllers\Operations\SaveActions` traits. After i upgrade to `backpack 4.0` there is no `SaveActions` traits in `Backpack\CRUD\app\Http\Controllers\Operations`. So How to use `$this->getSaveAction()` method in `backpack 4.0`? I fully go throw the **upgrade guide** i didn't get anything related this.

Backpack 3.6 i include button in `resources/views/vendor/backpack/base/inc/content_header.blade.php` base blade like `@include('crud::inc.button_stack', ['stack' => 'top'])` . But after upgrade to Backpack 4.0 it didn't work. How to change it? But base change `@include('backpack::inc.sidebar_content'))` to `@include(backpack_view('inc.sidebar_content'))` .

**Comment by tabacitu** [comment]
Indeed, SaveActions are no longer an operation trait, but a CrudPanel trait - the file is still named ```SaveActions```.

The same `inc.sidebar_content` is loaded in 4.0 too. What `backpack_view()` does is that it just prefixes the right folder name to the view. Some people create themes, in that case it prefixes the theme name. By default it prefixes `backpack::` so `@include(backpack_view('inc.sidebar_content')` translates to `@include(backpack::inc.sidebar_content`.

If you've used `getSaveAction` you might be interested in the new [docs for SaveActions](https://backpackforlaravel.com/docs/4.1/crud-save-actions) - it's now much easier to add/remove/change SaveActions.

Cheers!
