### ISSUE TITLE
How to add new field to $this->crud->getStrippedSaveRequest() array before store?

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2713]
I have a auto generate value field in database. If that value field filled by system auto generating not from user.
In Backpack 3.6 before call `parent::storeCrud($request)` i added to the request like 
`$request->merge(
                [
                    'key' => 'value',
                ]
            );`
It work fine. 
In Backpack 4.0 before call `$this->traitStore();` above way not work so that i add like in documentation. 
`
$this->crud->request->request->add(['key'=>'value']);
`
But it add the value in `$this->crud->request->request` not in the `$this->crud->getStrippedSaveRequest()`. So i can't get the value in `$this->crud->getStrippedSaveRequest()`.

My question is how to add the value in `$this->crud->getStrippedSaveRequest()` in backpack 4.0?

**Comment by tabacitu** [comment]
You can do ```$this->crud->set('saveAllInputsExcept', false)``` to go back to the previous behaviour, and it will no longer strip the request, to only leave inputs that have CRUD fields.

But. If you need to add something like that, I think a better place for it would be outside the Backpack logic, in the actual Model. Ask yourself this - would this be needed if that entry were created from a user-facing interface? Not an admin-facing interface? If so, a better place for it - I would argue, would be inside the Model, which would be used by all interfaces.

Hope it helps.
Cheers!

**Comment by senthu1994** [comment]
> You can do `$this->crud->set('saveAllInputsExcept', false)` to go back to the previous behaviour, and it will no longer strip the request, to only leave inputs that have CRUD fields.
> 
> But. If you need to add something like that, I think a better place for it would be outside the Backpack logic, in the actual Model. Ask yourself this - would this be needed if that entry were created from a user-facing interface? Not an admin-facing interface? If so, a better place for it - I would argue, would be inside the Model, which would be used by all interfaces.
> 
> Hope it helps.
> Cheers!

still i have same error. `$this->crud->set('saveAllInputsExcept', false)` didn't affect anything.

**Comment by tabacitu** [comment]
Ah sorry. I might have given the wrong direction. The default is ```false``` so your call did nothing indeed. How about using the [directions here](https://github.com/Laravel-Backpack/CRUD/issues/2404#issuecomment-578383703)? Basically specifying all those inputs that get ignored.

**Comment by senthu1994** [comment]
> Ah sorry. I might have given the wrong direction. The default is `false` so your call did nothing indeed. How about using the [directions here](https://github.com/Laravel-Backpack/CRUD/issues/2404#issuecomment-578383703)? Basically specifying all those inputs that get ignored.

@tabacitu i actually want other side. It mean I want to add some additional input to the request. How to do that. Thanks.

**Comment by tabacitu** [comment]
Something like this should work for you:

```php
$this->crud->setOperationSetting('saveAllInputsExcept', ['my_input_name', '_token', '_method', 'http_referrer', 'current_tab', 'save_action']);

request()->add(['key'=>'value']);
```

**Comment by senthu1994** [comment]
> Something like this should work for you:
> 
> ```
> $this->crud->setOperationSetting('saveAllInputsExcept', ['my_input_name', '_token', '_method', 'http_referrer', 'current_tab', 'save_action']);
> 
> request()->add(['key'=>'value']);
> ```

@tabacitu I used same as you mention but it shows error `BadMethodCallException
Method Illuminate\Http\Request::add does not exist.` Why? Please help me.

What do you mean by `request()->add(['key'=>'value']);`. Because before i try `$this->crud->request->request->add(['key'=>'value']);` I mentioned in the question as well. it add the value in `$this->crud->request->request` not in the `$this->crud->getStrippedSaveRequest()`. So i can't get the value in `$this->crud->getStrippedSaveRequest()`.

My question is how to add the value in `$this->crud->getStrippedSaveRequest()` in backpack 4.0?
