### ISSUE TITLE
[4.2][BUG] select_and_order does not respond to touch events.

### ISSUE THREAD

**Issue by Moaz-e** [Laravel-Backpack/CRUD#2716]
Hi ..
I added a field of type "select_and_order" in my project, which is a great feature when I open the control panel on desktop...
But when I open it on mobile :

-  I can't move items between lists.
-  I can't scroll item in lists.

I tried opening the control panel with more than one phone and more than one browser, and it gives the same problem.

Does anyone know solve the problem ??

Thank you very much for your help

![Screenshot_٢٠٢٠٠٤٢٧-١١٢٤٢٥](https://user-images.githubusercontent.com/37017532/80350890-118c0c80-887a-11ea-82f9-983e7ed780d2.png)

**Comment by pxpm** [comment]
Hello guys. 

I think I have found the culprit. So here it goes my findings:

### 1 - we need to remove blocking css. 
This css is located in field file.
```
.ui-sortable-handle {
            -ms-touch-action: none;
            touch-action: none;
}
```

### 2 - making sortable work on touch devices.

we need http://touchpunch.furf.com/ to make the drag and drop work on mobile. (at least is one of the solutions, i tested and works great). 

### 3 - solving asset loading

- This js library needs to be loaded after `jquery` and `jquery-ui`. Problem is when you have multiple fields in the same CRUD and any of them require `jquery-ui` after `select_and_order`. No more drag for you with touch.

You can test my solution by:

- removing the css i told you before. 
- making this the last field in crud
- added `<script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.2/jquery.ui.touch-punch.min.js"></script>` after the `jquery-ui` load. 

and .. BAM https://recordit.co/ke51U14bsH

@tabacitu if you search for: `jquery sortable touch` most of top results point to that package. it hasn't been updated for years, but well in our scenario, i just pulled it and it worked.

**Comment by Moaz-e** [comment]
@pxpm Yes, it works for me. Thank you very much.
But for the scroll problem, it is logically not possible to make a scroll with drag when touched, so I reduced the width of the items in list to the possibility of scroll from the side .

**Comment by pxpm** [comment]
Maybe we should apply the drag only to the `'multi-arrow icon'` and not to the full element. 

That way we probably can scroll on the element body ? Thing is to drag you would need to click on the icon instead of the full element. 

But we have other re-orders that works on icon too so I think this is probably the right way to do it.

**Comment by promatik** [comment]
I've just open #4018 to fix this issue 🙌
Thank you @pxpm for the suggestions, let's move the conversation there.
