### ISSUE TITLE
[Bug] Fields: hardcode use field[name] as HTML ID element

### ISSUE THREAD

**Issue by makss** [Laravel-Backpack/CRUD#2719]
# Bug report

1. If there is an ID element on the html page with the same name as the name of the form field, the html page is broken. (css/js not working correctly).
2. It is not possible to redefine the ID using `crud::inc.field_attributes`.

https://github.com/Laravel-Backpack/CRUD/blob/95a2e41f4fd3e314696f04652d36a101cddab2cf/src/resources/views/crud/fields/number.blade.php#L8-L14

**Line 11:** `id="{{ $field['name'] }}"`

### A similar problem in other templates:

https://github.com/Laravel-Backpack/CRUD/blob/95a2e41f4fd3e314696f04652d36a101cddab2cf/src/resources/views/crud/fields/base64_image.blade.php#L46

https://github.com/Laravel-Backpack/CRUD/blob/95a2e41f4fd3e314696f04652d36a101cddab2cf/src/resources/views/crud/fields/image.blade.php#L69

**Comment by tabacitu** [comment]
Thanks for the heads-up @makss . We've rewritten all fields in Backpack 4.1 and I _believe_ we're no longer using IDs anywhere. What version of Backpack are you using? What's the output of your ```php artisan backpack:version```?

**Comment by makss** [comment]
@tabacitu , Thank you for developing a convenient admin interface.

In branch 4.1, the number field problem was resolved, but the problem still remained in the image fields. Probably need to add a suffix to the ID.

Branch 4.1

https://github.com/Laravel-Backpack/CRUD/blob/7d06aa06df4123ef052f81eb324444b2bd25543a/src/resources/views/crud/fields/base64_image.blade.php#L35

https://github.com/Laravel-Backpack/CRUD/blob/7d06aa06df4123ef052f81eb324444b2bd25543a/src/resources/views/crud/fields/image.blade.php#L71

---

Now I am using Backpack 4.0.57, I will upgrade to 4.0.60 very soon.
```
### PHP VERSION:
PHP 7.2.23 (cli) (built: Sep 25 2019 07:48:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v6.18.2@9425a2f410d05d5bba493f62cff03854a8b19559

### BACKPACK VERSION:
4.0.57@fd2fbb2ffae3eb6ee520317c83b0516f9fe91f01
```

**Comment by pxpm** [comment]
Going to close this, i think every field has it's id removed/re-worked to work inside repeatable. 

If i am wrong, please re-open.

**Comment by tabacitu** [comment]
I can confirm, I've re-written both `image` and `base64_image` last week and now they don't have IDs anymore. So defining an attribute on any of them should be possible now - thanks for opening this @makss .
