### ISSUE TITLE
Reorder fields not working and multiple checkbox not selecting second in repeatable fields

### ISSUE THREAD

**Issue by dilneiss** [Laravel-Backpack/CRUD#2720]
found something i need in this moment:
i have multiple checkbox, in the repeatead item when i click on the label of the second item, it only check the first checkbox, not the clicked one

reorder the item is missing too, i want the second item to be the first for example, and it is missing

_Originally posted by @dilneiss in https://github.com/Laravel-Backpack/CRUD/pull/2266#issuecomment-614366952_

**Comment by tabacitu** [comment]
Hi @dilneiss ,

Thanks for raising the issue.

Sorting is not currently supported by the repeatable field. But it's a good idea indeed, I agree, it'll be worked on after 4.1 is launched. Check out the PR here - https://github.com/Laravel-Backpack/CRUD/pull/2711

The checkbox field has been fixed to work inside repeatable - https://github.com/Laravel-Backpack/CRUD/commit/bb0329c53a5ed4ab3fa5709edb0e3086c1472a98 - so a ```composer update backpack/crud``` should fix it for you.

Cheers!
