### ISSUE TITLE
`address_google` field occasionally encounter script loading issue

### ISSUE THREAD

**Issue by kiddtang** [Laravel-Backpack/CRUD#2721]
# Bug report

### What I did
use `address_google` field
```
[
    'name'          => 'address',
    'label'         => 'Address',
    'type'          => 'address_google',
    'store_as_json' => true
],
```
with more fields in a CRUD - it might increase the load time and increase the chance of loading issue

### What happened
In DevTools Console Log...
```
ReferenceError: google is not defined
    at bpFieldInitAddressGoogleElement
```
When it happened...
1. it will affect the loading script of `repeatable` for loading existing data.
2. if the  `checklist_dependency` after the `address_google`, the `roles` sometime become missing when i `dd()` in the `store` function with `$this->crud->getRequest()`. So it won't update/store accordingly.

### What I've already tried to fix it
Remove the `async defer`
Result: 
```
<script src="https://maps.googleapis.com/maps/api/js?key={{config('services.google_places.key')}}&libraries=places&callback=initGoogleAddressAutocomplete"></script>
```
Of course this is not the elegant way to fix, any expert could provide better fix?

### Backpack, Laravel, PHP, DB version
Backpack: 4.1.x-dev
Laravel: v7.6.2
PHP: v7.4.4
MariaDB: v10.4.12

**Comment by Evanslooten** [comment]
I am seeing this issue 100% of the time when trying to inline create a model that has the address_google CRUD field in its createOperation.

**Comment by tabacitu** [comment]
I believe this is the same one as https://github.com/Laravel-Backpack/CRUD/issues/3161 which just got a PR and fix 🥳
