### ISSUE TITLE
Why Uncaught ReferenceError: swal is not defined error come when click delete button?

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2727]
After I upgrade to Backpack 4.0 from 3.6 and when i click delete button in the list action it shows `Uncaught ReferenceError: swal is not defined` error in `console`. Why this error come how to solve this?

**Comment by pxpm** [comment]
@senthu1994 in 4.0 swal was added. I think you missed publising some assets, or if you have overritten some backpack_views() you might have to look what's changed. 

Also clearing you view cache with `php artisan view:clear`

**Comment by senthu1994** [comment]
> @senthu1994 in 4.0 swal was added. I think you missed publising some assets, or if you have overritten some backpack_views() you might have to look what's changed.
> 
> Also clearing you view cache with `php artisan view:clear`

@pxpm I did `php artisan backpack:install` and `php artisan view:clear`. But it didn't work. I have overwritten backpack views but not to delete. Then why is not working?
I check my `public/packages` there is no packages for `swal`

**Comment by senthu1994** [comment]
I didn't get any solution for my question. If anyone know please help me. Thanks.
