### ISSUE TITLE
[4.1.0]Problems with relationship field type,custom model accessor and ajax=true

### ISSUE THREAD

**Issue by kritsot** [Laravel-Backpack/CRUD#2731]
# Bug report
After submitting the form and having a validation error, the **fetch.blade.php** queries the database to fetch the $current_value. However **$field['attribute']** is not a column inside the database table and it throws an exception.

### What I did

Eg for model Category that uses nested sets and wants to present the full nested name of the category.
In this case I have a custom accessor

**public function getNestedNameAttribute(){
...
}**

I use **relationship** field with 'attribute'='nestedName'

I can override **fetch** function from **FetchOperation** to support this so that the result includes this property and it works properly. 
I select a category, and leave some other fields of the form with validation errors on purpose, so that I'm redirected back to this page. 

### What I expected to happen

I should be returned to the form page with the category correctly pre-populated.

### What happened

I'm presented with an database exception that informs me that cannot find **nestedName** in the categories table.

### What I've already tried to fix it

**fetch.blade.php**

**pluck** method inside the **$current_value** switch block should be applied after calling **get()**,
so that pluck is applied on the eloquent collection instead of the database.

### PHP VERSION:
PHP 7.3.7 (cli) (built: Jul  9 2019 22:58:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.9.2@757b155658ae6da429065ba8f22242fe599824f7

### BACKPACK VERSION:
4.1.x-dev@75c50e7d7142b40e42fafa5dae9aca62db66fcb8

When I run ```php artisan backpack:version``` the output is:

**Comment by kritsot** [comment]
https://github.com/Laravel-Backpack/CRUD/pull/2732

**Comment by tabacitu** [comment]
Excellent. Thanks for taking the time to submit a proper bug report AND a PR @kritsot ! Let's close the issue so we can continue the conversation inside your PR #2732
