### ISSUE TITLE
Getting 405 (Method Not Allowed) when ajax table is enabled

### ISSUE THREAD

**Issue by sonoftheweb** [Laravel-Backpack/CRUD#274]
When I add `$this->crud->enableAjaxTable();` to the CRUD controller, the table loads with an error and no data. This is what I see in console: 

http://localhost:8000/admin/collection_request/search 405 (Method Not Allowed).

**Comment by tabacitu** [comment]
Hi @sonoftheweb ,

What Laravel & Backpack\CRUD version are you using? It might be that you're using an old version, that didn't have ajax tables and a ```composer update``` would fix it.

Cheers!

**Comment by sonoftheweb** [comment]
In composer.json I have this

`"backpack/base": "^0.7.0",
 "backpack/crud": "^3.1.0",`

Laravel version is 5.3

**Comment by OwenMelbz** [comment]
@sonoftheweb have you tried running `composer update` ? As i'd suggest trying out `backpack/crud 3.1.45` and `backpack/base 0.7.7`

**Comment by sonoftheweb** [comment]
@OwenMelbz I have ran composer update several times and cannot seem to get it to work. I'll switch out the version numbers and report back, see if I get something.

**Comment by OwenMelbz** [comment]
@sonoftheweb also can you please type `php artisan route:list` and copy the results here please :)

**Comment by sonoftheweb** [comment]
@OwenMelbz Sorry I was away for some time. Surprisingly when I do `php artisan route:list` I get this error:

`[ReflectionException]                                           
  Class App\Http\Controllers\Auth\LoginController does not exist `

**Comment by tabacitu** [comment]
@sonoftheweb have you updated Laravel 5.2 to 5.3 recently? If so, you should also [upgrade Backpack](https://laravel-backpack.readme.io/docs/upgrade-guide-30-to-31).

**Comment by sonoftheweb** [comment]
Oh dear! I have found the issue. I did not set `$this->crud->setRoute("admin/collections");` correctly. I need to pay more attention when working.

Thanks @tabacitu and @OwenMelbz
