### ISSUE TITLE
Disable exception message on error page

### ISSUE THREAD

**Issue by quannetwork** [Laravel-Backpack/CRUD#2754]
# Bug report
Is there any way to hide the exception message on the error view templates provided by Backpack?

I think deleting the HTML on the blade files is the last resort, so it would be better to find some better ways to solve it.

### What I've already tried to fix it

I set `APP_DEBUG` to `false`
`APP_ENV` is `production`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 23 2020 16:50:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.8.1@cdc6d7e6c744f4d8f7d61102aea9b111550cd297

### BACKPACK VERSION:
4.0.60@3c6116bce3c90ef9850d3d07de5c7b8f41a7b6cd
```

**Comment by tabacitu** [comment]
Sorry, I see no solution other than deleting the HTML inside the blade files.

But if you don't prefer not to have those messages, I'd argue **you can delete the error files entirely**:
- that's the only reason the custom error files exist, to add that feature;
- we plan to remove the custom error files entirely, in a next version, probably 4.2; or at least make them optional but not default;

Then it'll fall back to Laravel's default error pages, which look pretty nice starting with Laravel 6.

Hope it helps.
Cheers!
