### ISSUE TITLE
'Reset' filters link name is harcoded

### ISSUE THREAD

**Issue by pkuzz** [Laravel-Backpack/CRUD#2756]
Yesterday I've upgraded to current 4.1-beta.
New 'Reset' button (which is `crudTable_reset_button` defined inside `datatables_logic.blade.php`) text is not localized.
I suppose it should be and it would be very good to have this in final 4.1 release.

**Comment by tabacitu** [comment]
You're totally right, of course! Thanks for letting us know @pkuzz .

It's done, 4.1 now has that translated.  You can get it with a ```composer update backpack/crud```

Cheers!
