### ISSUE TITLE
restoreRevision with revisionFormattedFieldNames

### ISSUE THREAD

**Issue by skatsaounis** [Laravel-Backpack/CRUD#276]
Hello Cristian,

I need your help. I found out that when using revisions I have a problem if `$revisionFormattedFieldNames = array('key' => 'value')` is set in my model.

Function `restoreRevision()` of backpack crud in ViewsAndRestoresRevisions uses `$revision->fieldName()` of Venturecraft/Revisionable.

But `fieldName()` returns 'value' instead of 'key', where 'key' is the column of my table.

As a result I get an error from database that 'value' column does not exist.

Do you think that it is an issue or a mistake of mine?

**Comment by mtb3** [comment]
Hello, I am encountering this same problem when using revisions and `$revisionFormattedFieldNames ` is set in my model.

I believe this is a bug in Backpack/CRUD that needs to be addressed.

**Comment by tabacitu** [comment]
Hi guys,

Thanks for the bug report. You're right, it should have been ```$revision->key```. I've just pushed the fix, a ```composer update```` should do it for you.

Cheers!
