### ISSUE TITLE
[Feature request] Browse multiple with files description

### ISSUE THREAD

**Issue by mamprogr** [Laravel-Backpack/CRUD#2770]
Hi,

I think it is useful if we are able to add a description for each file in `browse_multiple` or `upload_multiple`.

Usecase: I want to upload images with their captions in the article. The images will be shown in a slider, each slide has an image and its description.

Thanks.

**Comment by mamprogr** [comment]
Actually, we can do it using `repeatable` field.
I saw this [Issue #2709](https://github.com/Laravel-Backpack/CRUD/issues/2709) but I don't how to handle the image upload in the Model, i.e., the mutator.

**Comment by tabacitu** [comment]
![https://media.giphy.com/media/3o6MbqNPaatT8nnEmk/giphy.gif](https://media.giphy.com/media/3o6MbqNPaatT8nnEmk/giphy.gif)

Use `image` instead of `upload` - image works inside repeatable, upload does not. Set "crop" to false on the field to not have cropping functionality at all.

It shouldn't be too difficult in the mutator. You just need to loop through the variable, and [do the same thing you did if it were an image field](https://backpackforlaravel.com/docs/4.1/crud-fields#image). Start with the empty mutator and a `dd($value)` and work your way up.

If you end up with something that works well, please consider sharing your code here - maybe it helps someone else who's trying to achieve the same thing.

Cheers!

**Comment by mamprogr** [comment]
Thanks for your reply,

I made the mutator as follows:
```
public function setPhotosAttribute($items)
	{
		$items = json_decode($items);
		$attribute_name = "photos";
		$disk = 'public';
		$destination_path = "uploads/photos/{$this->category->id}";

		for ($i = 0; $i < count($items); $i++) {
			$value = $items[$i]->image;

			// TODO #1
			// if ($value==null) {
			// 	\Storage::disk($disk)->delete($this->{$attribute_name});
			// 	$this->attributes[$attribute_name] = null;
			// }
			
			if (\Str::startsWith($value, 'data:image')) {
				
				// TODO #2
				// if (\Storage::disk($disk)->exists($this->{$attribute_name}))
				// 	\Storage::disk($disk)->delete($this->{$attribute_name});

				$image = \Image::make($value)->encode('jpg', 90);
				$filename = md5($value . time()) . '.jpg';
				\Storage::disk($disk)->put($destination_path . '/' . $filename, $image->stream());
				$public_destination_path = \Str::replaceFirst('public/', '', $destination_path);
				$items[$i]->image = $public_destination_path . '/' . $filename;
			}
			$this->attributes[$attribute_name] = json_encode($items);
		}
	}
```

The image uploading and storing in the database are working fine.

There still 3 issues:
1. Deleting the old image (mentioned in code # TODO #1).
2. Replacing the old image (mentioned in code # TODO #2).
3. Explained in the next comment.

To solve 1 & 2, I need to access the old value of the current item. The problem is that the count and order of the `repeatable` son array may change based on the newly added or removed items. Do you suggest any way to access the old value?

**Comment by mamprogr** [comment]
Issue #3:
The image doesn't show because the prefix is not set.

On this page, I have `name=photos|type=image` which is in a `repeatable` and another `image` field below.
The normal `image` is shown correctly, but the one inside the `repeatable` is not correct because of the incorrect URL prefix.
![image](https://user-images.githubusercontent.com/734475/81138883-42e89480-8f6c-11ea-91e0-81f78c6a6a1c.png)

Both are set correctly in the database.
![image](https://user-images.githubusercontent.com/734475/81138973-a8d51c00-8f6c-11ea-8e9d-31250b90a4b0.png)

**Comment by mamprogr** [comment]
My final solution for all previous problems is:
```
	public function getPhotosAttribute($items)
	{
		$items = json_decode($items);
		for ($i = 0; $i < count($items); $i++) {
			$items[$i]->image = asset($items[$i]->image);
		}
		$items = json_encode($items);
		return $items;
	}

	public function setPhotosAttribute($items)
	{
		$items = json_decode($items);
		$attribute_name = "photos";
		$disk = 'public';
		$destination_path = "uploads/photos/{$this->category->id}";

		for ($i = 0; $i < count($items); $i++) {
			$value = $items[$i]->image;
			if (\Str::startsWith($value, asset(''))) {
				$value = preg_replace('/^' . preg_quote(asset(''), '/') . '/', '', $value);
				$items[$i]->image = $value;
			} else if (\Str::startsWith($value, 'data:image')) {
				$image = \Image::make($value)->encode('jpg', 90);
				$filename = md5($value . time()) . '.jpg';
				\Storage::disk($disk)->put($destination_path . '/' . $filename, $image->stream());
				$public_destination_path = \Str::replaceFirst('public/', '', $destination_path);
				$items[$i]->image = $public_destination_path . '/' . $filename;
			}
		}

		$old_images = array_map(function ($item) {
			return $item->image;
		}, json_decode($this->getAttributes()[$attribute_name]));

		$new_images = array_map(function ($item) {
			return $item->image;
		}, $items);

		$images_to_delete = array_diff($old_images, $new_images);

		foreach ($images_to_delete as $img) {
			if (\Storage::disk($disk)->exists($img))
				\Storage::disk($disk)->delete($img);
		}

		$this->attributes[$attribute_name] = json_encode($items);
	}
```

Notes:
1. I think there should be a more optimal solution.
2. I'm calculating the difference images between the old and new images and delete them.
