### ISSUE TITLE
When i call $this->crud->getSaveAction() i got array_filter() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2781]
After i upgrade backback 4.1 and i got error `array_filter() expects parameter 1 to be array, null given`. Then i check it in my code it come when i call `$this->crud->getSaveAction()` in edit custom function why? How to solve?

```
public function sample()
    {
        $sampleId = app(Sample::class)->getSample()->id;
        $user = backpack_auth()->user();
        $this->crud->hasAccessOrFail('update');
        // get the info for that entry
        $this->data['entry'] = $this->crud->getEntry($sampleId);
        $this->data['crud'] = $this->crud;
        $this->data['saveAction'] = $this->crud->getSaveAction();
        $this->data['fields'] = $this->crud->getUpdateFields($sampleId);
        $this->data['title'] = trans('backpack::crud.edit') . ' ' . $this->crud->entity_name;
        $this->data['id'] = $sampletd;
        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view($this->crud->getEditView(), $this->data);
    }
```

variable and function name modified for privacy reason.
Error image 
![Screenshot from 2020-05-07 09-59-41](https://user-images.githubusercontent.com/25341255/81255587-a85f8280-904b-11ea-8353-bdbc474d18a1.png)

**Comment by tabacitu** [comment]
Screenshot of the error and copy-paste of the custom method please?

**Comment by senthu1994** [comment]
> Screenshot of the error and copy-paste of the custom method please?

@tabacitu updated question with custom function and error

**Comment by pxpm** [comment]
Hey @senthu1994 

We use it in `create() function` 

`$this->data['saveAction'] = $this->crud->getSaveAction();`

My guess is that you are creating some custom operation and did not add any save action ?

**Comment by senthu1994** [comment]
@pxpm It isn't `create() function` it is `edit() function`. It have `save action` like `save and back, save and edit this item`. It works perfectly in backpack 4.0 after upgrade to 4.1 it shows above error.

**Comment by pxpm** [comment]
we also use it on edit. 

```php
    public function edit($id)
    {
        $this->crud->hasAccessOrFail('update');
        // get entry ID from Request (makes sure its the last ID for nested resources)
        $id = $this->crud->getCurrentEntryId() ?? $id;
        $this->crud->setOperationSetting('fields', $this->crud->getUpdateFields());
        // get the info for that entry
        $this->data['entry'] = $this->crud->getEntry($id);
        $this->data['crud'] = $this->crud;
        $this->data['saveAction'] = $this->crud->getSaveAction();
        $this->data['title'] = $this->crud->getTitle() ?? trans('backpack::crud.edit').' '.$this->crud->entity_name;

        $this->data['id'] = $id;

        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view($this->crud->getEditView(), $this->data);
    }

```

I don't know why that error is happening because i could not reproduce it. You must have something different from me for sure.

What i advise you is to go down the rabbit hole in you project. 

Like you can see in error, you call `getSaveAction()` and internally we call `getCurrentSaveAction()` .. maybe you can start dd() in those functions to see where it breaks.

Bare with me that i am not saying it's not a bug, it could be, but unfortunatelly i was not able to reproduce it.

**Comment by senthu1994** [comment]
@pxpm In `getSaveAction()` function first line `$saveOptions = $this->getVisibleSaveActions();` After this i put `dd($saveOptions)`. It output will come empty array `[]`. I think here is the problem. What is going wrong?

**Comment by senthu1994** [comment]
Normally system admin can do crud for team. But team leader only can do edit the attribute of the team. so that editing we used above customize edit function. It works fine in backpack 3.6 and it look like same as above function and only different is 
`
$this->data['saveAction'] = $this->getSaveAction();
`
But it didn't work in backpack 4.0. so i did small change in the code like 
`
$this->data['saveAction'] = $this->crud->getSaveAction();
`
and it work without error but old values are not comes to edit fields. But after backpack 4.1 upgrade it shows above error. What can do for this? cc: @tabacitu @pxpm
