### ISSUE TITLE
[4.0][Possible BUG] upload_multiple - not clearing deleted images

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#2783]
# Bug report

$files_to_clear = request()->get('clear_'.$attribute_name);
returns null when you remove uploaded file.

**Comment by tabacitu** [comment]
Does it happen in 4.1 too? I know I tacked this or merged something about this at some point...

**Comment by pxpm** [comment]
Going to test it. I am sure we merged something for browse_multiple #2400 , not sure about `upload_multiple`. I will give it a go in a second, just installing clean branches of 4.1 :)

**Comment by AbbyJanke** [comment]
maybe i'm mistaken but Laravel returns it as null with when an item is returned emptied. I believe that was intentional with Backpack so you can write code to delete a file from storage (from whatever provider used?) Maybe I missed something? but that seems logical based on past information from Laravel and Backpack.

**Comment by pxpm** [comment]
@AbbyJanke thanks for pitching. 

I don't think in this scenario that is the case. The `clear_attribute` should be populated with the image name you deleted. 

From `HasUploadFields.php` trait: 

```php
$files_to_clear = request()->get('clear_'.$attribute_name);

        // if a file has been marked for removal,
        // delete it from the disk and from the db
        if ($files_to_clear) {
            foreach ($files_to_clear as $key => $filename) {
                \Storage::disk($disk)->delete($filename);
                $attribute_value = Arr::where($attribute_value, function ($value, $key) use ($filename) {
                    return $value != $filename;
                });
            }
        }
```

**Comment by pxpm** [comment]
I ** COULD NOT ** reproduce this in 4.1 

Going to close AFAIK it's not a bug.

**Comment by tabacitu** [comment]
Yeah don't worry about it @pxpm . Sometimes people post bug reports that aren't actually bugs, but implementation problems - happens to us all, easier to shift the blade on the software. Who is this @pxpm guy anyway, who posted the bug report?! Screw him.

**Comment by pxpm** [comment]
I also hate this guys that open "possible bug reports" too .. they are just ... meh! hehehe :smile: 

Cheers \o
