### ISSUE TITLE
[4.1][Bug] relationship column doesn't work - 

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2788]
# Bug report

### What I did

Count Dracula on Gitter reported this. He used the `relationship` column as documented. 

### What happened

```php
local.ERROR: Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::relationAllowsMultiple does not exist. \
(View: /home/vagrant/Sites/myproject/vendor/backpack/crud/src/resources/views/crud/columns/relationship.blade.php)  \
{"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): \
Method Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel::relationAllowsMultiple does not exist. \
(View: /home/vagrant/Sites/myproject/vendor/backpack/crud/src/resources/views/crud/columns/relationship.blade.php) \
at /home/vagrant/Sites/myproject/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103)
```

### What I've already tried to fix it

Dug down to see if the method exists in my build. And indeed it does not. Gone through the `Relationship.php` file history to see when it was removed, and here it is, April 6th:
![Screenshot 2020-05-08 at 17 34 21](https://user-images.githubusercontent.com/1032474/81416542-8866b680-9152-11ea-952b-cfe0c11546ce.png)

I've replaced the call to `relationAllowsMultiple()` with `guessIfFieldHasMultipleFromRelationType()` like it's called now. But when testing the relationship column I've also discovered that it doesn't work without `entity` and `attribute`, which is NOT the documented way. Apparently the attribute guessing only happens for `fields`, not for `columns` too. Don't know why I though we did that for `columns` too.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```php
### PHP VERSION:
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.10.3@6e927e78aafd578d59c99608e7f0e23a5f7bfc5a

### BACKPACK VERSION:
4.1.1@91a8093ad1e55ad329d74994eaa2ed943fb0ec6a
```

**Comment by dickalexei** [comment]
Hi,
My configuration:

```
### LARAVEL VERSION:
v8.83.8@cf430301ad17656b3d918995bcdd0454c3c119b9

### BACKPACK VERSION:
5.0.14@1e355c4c046a34423a1a3e3150120245a4bfd8e9
```

I still have the issue, there is a call to relationAllowsMultiple line 14 in
vendor/backpack/pro/resources/views/fields/relationship.blade.php

**Comment by pxpm** [comment]
Hello @dickalexei can you update to 5.1.x ? It should be a non-breaking update, and then if the error persist please let me know your relation setup and column definition.

Thanks
