### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by readergirltracey** [Laravel-Backpack/CRUD#279]
I keep getting Call to a member function get() on null this error on new laravel 5.2 project

**Comment by OwenMelbz** [comment]
If it's a new project, you should probably use laravel 5.3. As I don't think there's much active support for 5.2, especially with 5.4 around the corner.

Have you followed the documentation on the website relating to 5.2? It's your best bet.

**Comment by readergirltracey** [comment]
okay that's what i did
