### ISSUE TITLE
[4.1][Bug] Fluent Field Unknown DB Type

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#2790]
# Bug report

### What I did

Converted a field from array to fluent syntax.

### What I expected to happen

Work/appear the same way

### What happened

`Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.`

### What I've already tried to fix it

Still looking into it, but I had no problem with fluent syntax until this controller. 

https://gist.github.com/AbbyJanke/d9abe3f03b894f6f1920f17d7c58aecf

### Backpack, Laravel, PHP, DB version

```### PHP VERSION:
PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.10.3@6e927e78aafd578d59c99608e7f0e23a5f7bfc5a

### BACKPACK VERSION:
4.1.2@7084182b38bff6b19624788ff143bb249ecdc758
```

**Comment by tabacitu** [comment]
Thanks for reporting this @AbbyJanke ! Indeed, I was able to replicate the issue and I have a fix for it in #2974 . Cheers!
