### ISSUE TITLE
Fluent text columns with 1-1 relationships don't save correctly

### ISSUE THREAD

**Issue by rmarshall9n** [Laravel-Backpack/CRUD#2797]
# Bug report

### What I did
I tried to add a text column with a 1-1 relation:

CRUD::column('user.full_name')->type('text')->label('User');

### What I expected to happen

The column would display with the 'User' label.

### What happened

The column displayed with the 'User.full name' label.

### What I've already tried to fix it

CrudColumns@save() calls $this->crud()->hasColumnWhere('key', $key) which always returns false.

I think this is because the column key is user.full_name, however, backpack stores it as user__full_name.

```
"user__full_name" => array:8 [▼
    "name" => "user.full_name"
    "label" => "User.full name"
    "type" => "text"
    "key" => "user__full_name"
    "tableColumn" => false
    "orderable" => false
    "searchLogic" => false
    "priority" => 1
  ]
```

### PHP VERSION:
PHP 7.2.27-6+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  5 2020 16:52:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.27-6+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.10.3@6e927e78aafd578d59c99608e7f0e23a5f7bfc5a

### BACKPACK VERSION:
4.1.2@7084182b38bff6b19624788ff143bb249ecdc758

**Comment by tabacitu** [comment]
Thank you @rmarshall9n - excellent bug report. 

Indeed the problem was the one you identified. I've put together PR #2805 which fixes this, and I'll be merging and tagging it later today, so I'll close this issue.

Cheers!

**Comment by tabacitu** [comment]
Merged and tagged. A `composer update backpack/crud` will fix it. Thanks again!
