### ISSUE TITLE
Ability to add cols or fields before or after existing.

### ISSUE THREAD

**Issue by b8ne** [Laravel-Backpack/CRUD#280]
Just like migrations, it would be handy to be able to add columns and fields before or after existing columns. ie
```
$this->crud->addColumn([
            'name'  => 'phone',
            'label' => 'Phone Number',
            'type'  => 'text',
])->beforeColumn('email');
```

**Comment by OwenMelbz** [comment]
Hi @b8ne , I'm consolidating all the issues into 1 list, we've got your PR which @tabacitu will get around to seeing, until then you can monitor its progress in https://github.com/Laravel-Backpack/CRUD/issues/285
