### ISSUE TITLE
[BUG] Validation message do not show when field uses hidden inputs.

### ISSUE THREAD

**Issue by rmarshall9n** [Laravel-Backpack/CRUD#2814]
# Bug report

### What I did

Added a date_picker or datetime_picker field to a crud panel with a  'required' validation rule. The form was submitted with no date present (create/edit).

### What I expected to happen

A red outline would be applied to the date field and the .invalid-feedback message would be visible.

![image](https://user-images.githubusercontent.com/13203179/81788507-84dc8200-94fa-11ea-9c62-bfaa8e861930.png)

### What happened

The error feedback is not visible on the form control.

![image](https://user-images.githubusercontent.com/13203179/81788548-9aea4280-94fa-11ea-9ce6-bdcb4810f6fb.png)

### What I've already tried to fix it

In form_content.blade.php:134, It looks like the .is-invalid class is applied to the hidden input instead of the date input. 

The .invalid-feedback div is also outside of the input group.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.2.27-6+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  5 2020 16:52:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.27-6+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

### BACKPACK VERSION:
4.1.3@02988a0d14b09e55949781d729060df910f0d94b

**Comment by pxpm** [comment]
@rmarshall9n thank you very much for your submition. 

I'v just tested and confirmed it's happening. 

We will have to take a deeper look how we can solve this issue. 

If in the meanwhile you found a solution for it please let us know :)

Wish you the best,
Pedro

**Comment by pxpm** [comment]
Fixed by #2910
