### ISSUE TITLE
[4.1][BUG] Every button on page works as submit

### ISSUE THREAD

**Issue by GregaUNK** [Laravel-Backpack/CRUD#2843]
# Bug report

### What I did

In edit view I added custom fields which includes buttons like that:
<button class="btn btn-block btn-warning">Download from remote server</button>

I have jquery click handler in place to take care of this actions.

### What I expected to happen

I expect not to save crud item when I press this button.

### What happened

It saves the crud item.

### What I've already tried to fix it

/

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.1 (cli) (built: Dec 18 2019 14:46:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

### BACKPACK VERSION:
4.1.4@4303aa07ec0c597abfcfe83896558ca6e98f0d6a

**Comment by tabacitu** [comment]
Hmm that's weird @GregaUNK - Backpack has quite a few fields with buttons too - `browse`, `browse_multiple`, `image`, `table`, etc. And it doesn't happen for them. Are you sure you haven't coded in a `button type=submit`? Cause that won't work - if you put one of those inside a form, that's what's going to happen, it will submit it.

Can you copy-paste your custom field here to see if we can spot the problem?

Cheers.

**Comment by pxpm** [comment]
This seems like the issue we had with icon picker. 
Please, if you add buttons make sure you define the `type=""` be it `button, submit, reset` 

Going to close, i don't think this is a bug. 

If I am wrong, and be sure that sometimes I am, please re-open. 

Best,
