### ISSUE TITLE
Custom row

### ISSUE THREAD

**Issue by alexeydg** [Laravel-Backpack/CRUD#2846]
How do custom row? Example: i want set color to row.

**Comment by tabacitu** [comment]
Sorry @alexeydg , this is one of those things that might prove more difficult than it's worth. I recommend you take a look inside the List operation trait (that you use on your CrudController). In there you'll find the search() method, that you can overwrite however you want in your CrudController just by specifying a method with the same name. 

Another option, if you're using Backpack 4.1, would be to [add style or class to the column wrapper](https://backpackforlaravel.com/docs/4.1/crud-columns#custom-wrapper-for-columns).

Hope it helps.
Cheers!
