### ISSUE TITLE
[4.1][Bug] custom order not respected for relationship field

### ISSUE THREAD

**Issue by kritsot** [Laravel-Backpack/CRUD#2847]
# Bug report

### What I did

When using 'options' to change the order e.g.
```php 
'options' => function ($query) {
   return $query->orderBy('name');
 }
```
This in the case of **relationship_select** could set $field['options'] to
```php
[
  2=>"A",
  1=>"B",
]
```

**data-options-for-select="{{json_encode($field['options'])}}"**

should store it as 
```json
{"2":"A","1":"B"}
```

The problem is with the following line

**var $optionsForSelect = JSON.parse(element.attr('data-options-for-select'));**

JSON.parse is known to change the order of the keys, so the object is converted to
```json
{"1":"B","2":"A"}
```

and the initial order is lost

**Comment by pxpm** [comment]
This have a PR #2867 

You might want to help test @kritsot if you have the time ? You could copy the code from that PR, use it in your project and let us know in PR if it fixed the problem ?

Thanks again for raising the issue. 

Best,
Pedro
