### ISSUE TITLE
[Bug] Number fields do not accept decimals

### ISSUE THREAD

**Issue by laxsmi** [Laravel-Backpack/CRUD#2859]
# Bug report

### What I did

Setup a "number" field in `createOperation()`, with a specific number of decimals, like so:

```php
$this->crud->addField(['name' => 'price', 'type' => 'number', 'label' => 'Price', 'decimals' => 2]);
```

### What I expected to happen

The input field should accept a float number but HTML validation only allows to input integers.

### Possible solution

Add `step="{{ '.' . str_repeat('0', $field['decimals'] - 1) . '1' }}"` to the input field in `backpack/crud/src/resources/views/crud/fields/number.blade.php`

Perhaps there is a prettier solution. But this one seems to work... Another solution would be to add `step="any"` to the field and rely on server-side validation only.

**Comment by pxpm** [comment]
Hello @laxsmi 

From the docs: https://backpackforlaravel.com/docs/4.1/crud-fields#number

You are not implementing the field corretly, could you try with the solution we provide in the docs ? 

Best,

**Comment by laxsmi** [comment]
Sorry, I mixed up the field and column implementations...
