### ISSUE TITLE
Limit data 

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#286]
Hi
Is there anyway to  determine that specific data load from table instead of all data in the admin panel ?

**Comment by OwenMelbz** [comment]
Sorry don't quite understand? Could you maybe give an example of what's wrong please?

**Comment by M0H3N** [comment]
By default this package load all data from a table  . for example we have a Book Model . I want just load the books with specific category in panel not all books ? Is  it clear ?

**Comment by OwenMelbz** [comment]
Ah okay, yes I think I understand.

You can use the `addClause` functionality or filters.

Clauses look like

```php
// ------ ADVANCED QUERIES
$this->crud->addClause('active');
$this->crud->addClause('type', 'car');
$this->crud->addClause('where', 'name', '==', 'car');
$this->crud->addClause('whereName', 'car');
$this->crud->addClause('whereHas', 'posts', function($query) {
     $query->activePosts();
 });
$this->crud->orderBy();
$this->crud->groupBy();
$this->crud->limit();
```

and filters are documented here -> https://laravel-backpack.readme.io/docs/filters

Hopefuly that should give what you're after, I'll close the thread now to keep the place tidy, feel free to reply
