### ISSUE TITLE
[Feature] Attributes in pivot tables

### ISSUE THREAD

**Issue by Dzale** [Laravel-Backpack/CRUD#2860]
# Bug report

### What I did

Trying to create Attach/Detach between two entities connected with M:N relation (pivot table has additional attributes).

I've tried couple of different field types (select2_multiple, select_multiple), i even tried to create repeatable field. 

Having attributes in pivot tables is like really common (don't recall project when i didn't have this)...

### What I expected to happen

To be able to specify pivot attributes for each entity i select in select2_multiple, or to have a way to add some custom button with modal where you can attach relation with some additional attrbutes.

### What happened
When i was using select_multiple or select2_multiple, additional fields were not showing and application was throwing exceptions (as expected). 

When i was trying to use repeatable, data sent to server was in json format, and **syncPivot** method wasn't well coded to handle this. 

### What I've already tried to fix it

I've just tried different field types. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.3 (cli) (built: Feb 18 2020 17:29:46) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.3, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.12.0@c2fff1e9879494a6f853593b3c517dc9922bbb51

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by mauricoder** [comment]
OMG, Nova has the same issue open. Actually.. I found Backpack searching for a Laravel Nova alternative not having this issue and... here it is (hope lost!)

**Comment by Dzale** [comment]
Backpack is adding features all the time, i think they will handle this fast. ;)

If you are in big hurry you can checkout https://voyager.devdojo.com , not sure if they have the same problem..

**Comment by pxpm** [comment]
Hello guys. 

Indeed this is something we have discussed and probably we will attempt to provide a solution for this. 

I have corretly labeled it, and will have a discussion with @tabacitu about this. 

Repeatable https://backpackforlaravel.com/docs/4.1/crud-fields#repeatable might work in this scenario, because you can intercept the request in controller and do whatever you want with it. 

Maybe what is missing here is to set the max items a repeatable field can have, so you can set it to only one, am i right ? @Dzale ?

**Comment by Dzale** [comment]
Hey @pxpm, thanks for quick response. I haven't tried to intercept request, but that might be the way to go. 

I actually would like to be able to attach multiple M:N relations from one request (exactly as repeatable works now) so i don't think that we need limitation for that (max items).

At the moment i also had a problem that if i add relation field inside repeatable, id adds multiple select (because relation in model is belongsToMany) where it should be single select, each of my sections represent one Actor entity that i want to attach to Movie. Also you are calling `sync` function on Laravel relation, this will detach all entities which are not sent from front-end, so if we add this option on update operation, we need to be certain that entities previously attached would be sent through request as well. 

Ill try to share my thoughts of how i would imagine attach/detach functionality in Admin panel. If we look at following simple database structure: 

Table **movies**
- id
- name

Table **actors**
- id
- name

Pivot table **movies_actors**
- id
- movie_id
- actor_id
- role

I think that in this scenario, if we are creating MovieCrudController, i should be able to add repeatable field where i have relation select (i select **single** Actor here) and i have classic text field where i can enter role. 

In some ideal case (if i were to create Admin panel from scratch) attach/detach functionalities would be implemented like this: 

On Show/Update Movie operation, i would have a separate section where i list all Actors (table view) for currently selected Movie (this can be completely separate tab on designs, or it can just be new section below basic movie attributes). I have option to attach new Actor to Movie (a button that opens modal, where we have repeatable section to Attach multiple ), i have options to search Actors that are attached to selected Movie, and each row of Actors table has 3 actions (show, edit, delete). Show is just a link to show page of Actor entity, edit opens a modal to edit pivot attribute tables (role in this case), and delete detaches Actor from Movie (but it doesn't delete Actor entity). 

On Show/Update Actor operation, i would do the same just in reversed way. 

These are some of my thoughts i hope you find it helpful ;)

**Comment by pxpm** [comment]
Hello @Dzale and @mauricoder 

I just pushed a PR that might address this issue. 

Would you like to give it a go and check if it fits your needs ? 

It's here: #2938 

Best,

**Comment by Dzale** [comment]
Hey @pxpm,

this looks awesome. From your example it looks like it resolves issue i stated above!

I have one question. Will this work if we have file upload in pivot table? 

Maybe it will work out of the box if we create Pivot class for our M:N relation and add mutator there ? 

Like described here https://backpackforlaravel.com/docs/4.1/crud-fields#upload_multiple ? 

Again, thank you a lot!

**Comment by tabacitu** [comment]
I'm eager to have this feature. Great work @Dzale & @pxpm . Let's move the conversation to the PR please - #2938 and close this issue, no use having two conversations open for one thing.
