### ISSUE TITLE
[4.1][Bug] String field wrapper attribute values interpreted as functions

### ISSUE THREAD

**Issue by nbolender** [Laravel-Backpack/CRUD#2861]
# Bug report

### What I did

Created a field with a custom wrapper attribute with the value `range`:

```
$this->crud->addField([
	'name' => 'ticket_price_minimum',
	'label' => 'Minimum Ticket Price',
	'type' => 'text',
	'wrapper' => [
		'data-ticketing-type' => 'range',
	],
]);
```

### What I expected to happen

Field is added to form with the custom wrapper attribute, like so:

```
<div data-ticketing-type="range">
  <label>Minimum Ticket Price</label>
  <input type="text" name="ticket_price_minimum">
</div>
```

### What happened

Due to new functionality in `wrapper_start.blade.php`, the value is checked by `is_callable()` and thus, Backpack tries to execute `range($crud, $field, $entry)` because `range` is a built-in PHP function. PHP tries to coerce `$entry` (an Eloquent model) into a numeric value and causes an exception.

### What I've already tried to fix it

I've created a pull request to check whether the attribute value is a string before attempting to execute it. This should allow closures to be executed and preserve any explicit string values. If anyone was using this to pass a function name as a string, that will now fail–but I don't think that was documented or intended to work.

### PHP VERSION:
PHP 7.3.13-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Dec 18 2019 14:48:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.13, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.13-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.12.0@c2fff1e9879494a6f853593b3c517dc9922bbb51

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by pxpm** [comment]
Thanks again @nbolender for submiting the issue and the PR. 

It's been merged in #2862 so I am going to close this.

Wish you the best,
Pedro
