### ISSUE TITLE
[Bug] required field "red star" after <label> tag disappears when wrapper added into field

### ISSUE THREAD

**Issue by siberfx** [Laravel-Backpack/CRUD#2868]
# Bug report

when we adding in Crud file for fields
```
'wrapper' => [
     'class' => 'my-2 col-md-4'
],
```

### What I expected to happen

required fields should be marked with "red star" after label 

### What happened

it disappears.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
4.1.6

**Comment by pxpm** [comment]
Hello @siberfx can you show me your field definition ? 

We use wrapper in an required field in demo and it still have the red asterisk there. 

https://github.com/Laravel-Backpack/demo/blob/604201bf076bb8e03ae1fd701d5de07d1d132e9b/app/Http/Controllers/Admin/MonsterCrudController.php#L398

**Comment by siberfx** [comment]
![image](https://user-images.githubusercontent.com/10257240/82819727-8a967800-9ea9-11ea-84bf-f3c16779f18f.png)
![image](https://user-images.githubusercontent.com/10257240/82819803-aef25480-9ea9-11ea-85c6-e3d83395a61d.png)
![image](https://user-images.githubusercontent.com/10257240/82819842-c2052480-9ea9-11ea-8939-32dd7841f4df.png)
 here you go.

**Comment by pxpm** [comment]
I am sorry, but I am still unable to reproduce this. 

### Field
```php
[ // select_from_array
                'name'              => 'select_from_array',
                'label'             => 'Select_from_array (no relationship, 1-1 or 1-n)',
                'type'              => 'select_from_array',
                'options'           => ['one' => 'One', 'two' => 'Two', 'three' => 'Three'],
                'allows_null'       => false,
                'tab'               => 'Selects',
                //'allows_multiple'   => false, // OPTIONAL; needs you to cast this to array in your model;
                'wrapper' => ['class' => 'form-group col-md-6'],
            ],
```
### Request
```php
    public function rules()
    {
        return [
            'select_from_array' => 'required'
        ];
    }
```

### Result

![Screenshot_10](https://user-images.githubusercontent.com/7188159/83163736-469eaf80-a103-11ea-97e7-c52475dccf25.png)

**Comment by siberfx** [comment]
you can close this issue, I will investigate it myself and I can create another report with the exact reason that causing this issue. thank you for your time.

**Comment by tabacitu** [comment]
Thank you for being so understanding @siberfx !
