### ISSUE TITLE
[Bug] Field name of 'date' breaks CRUD panels

### ISSUE THREAD

**Issue by tibbsa** [Laravel-Backpack/CRUD#2869]
# Bug report

**UPDATE:** The _real_ problem in this case was that I still had the setFromDb() call.  Perhaps the documentation [or the comment on that] should more clearly warn that the default setFromDb() call will make guesses as to the type of field involved, but that those guesses may be so incorrect that the create/edit form won't even load?

### What I did

I have a table with a 'date' file that is actually a text string (since this 'date' could be anything from simply a year, to a month and year, to a specific date, and we are not sorting on that basis).  

### What I expected to happen

The field, which is a JSON field (to facilitate translation), would be treated as any other.

### What happened

However, this breaks the display of the CRUD create/edit forms with an error:

> Facade\Ignition\Exceptions\ViewException
date() expects at most 2 parameters, 3 given (View: /home/.../vendor/backpack/crud/src/resources/views/crud/fields/inc/wrapper_start.blade.php)

### What I've already tried to fix it

The problem can be traced to this code in the aforementioned file:

```
    // each wrapper attribute can be a callback or a string
    // for those that are callbacks, run the callbacks to get the final string \
to use
    foreach($field['wrapper'] as $attributeKey => $value) {
        $field['wrapper'][$attributeKey] = is_callable($value) ? $value($crud, \
$field, $entry ?? null) : $value ?? '';
    }
```

Date() is of course "callable" even though the field name 'date' is not in any way related to the same. Obviously, renaming the field would avoid the problem, but this use of is_callable() seems to invite any number of problems with any number of potential field titles.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.6 (cli) (built: May 14 2020 10:02:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

### BACKPACK VERSION:
4.1.5@e2c166b065f6b405747db5a5f4d36a2a88f8dc22

**Comment by tabacitu** [comment]
@tibbsa , indeed `setFromDb()` can be wrong a lot. That's why we don't recommend using it very much. In fact, we're phasing it out - starting this month we'll probably even generate individual lines for each Field and Column, like in [this PR](https://github.com/Laravel-Backpack/Generators/pull/84), to spare people the frustration of learning "_this is setFromDb(), but we recommend you don't use it_".

Will do @tibbsa , thanks!
