### ISSUE TITLE
[4.1][Bug] translatable fake field - unexpected behavior or documentation issue

### ISSUE THREAD

**Issue by lotarbo** [Laravel-Backpack/CRUD#2878]
# Bug report

### What I did

My field
```
CRUD::field('text')->type('summernote')->label('Text')->fake(true)->store_in('content_i18n');
```
My model
```
namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations;
use Illuminate\Database\Eloquent\Model;

class ProjectContent extends Model
{
    use CrudTrait;
    use HasTranslations;

    protected $table = 'project_contents';
    protected $guarded = ['id'];
    protected $translatable = ['content_i18n'];
    protected $casts = ['content_i18n' => 'array'];
    protected $fakeColumns = ['content_i18n'];
```

### What I expected to happen
Works as expected, 
`$model->content_i18n` - return array
in admin - showing storing data

### What happened
**If i add content_i18n to $cats and $translatable:**
`$model->content_i18n` - return string
admin: data not showing
db: ```{"ru": {"text": "<p>asdfasdfasfd</p>"}}```

**If i add content_i18n to $translatable only:**
`$model->content_i18n` - return string
admin: data showing
db: ```{"ru": {"text": "<p>asdfasdfasfd</p>"}}```

### What I've already tried to fix it
nothing

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.4.6 (cli) (built: May 14 2020 10:38:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f
```

**Comment by pxpm** [comment]
Hey @lotarbo 

I think this might be a documentation issue, you should cast the field to `object`

Here you have an example in demo: 

https://github.com/Laravel-Backpack/demo/blob/604201bf076bb8e03ae1fd701d5de07d1d132e9b/app/Models/Product.php#L28

Could you give it a try and let me know ? Maybe it's breaking on some specific field ?

Best,

**Comment by lotarbo** [comment]
@pxpm i try this. This is different field as in demo. Because:

- translatable
- fake

So when cast field as object i have this result:
**admin** - data not showing after save and open
**db** - `{"ru": {"text": "<p>Some test</p>"}}`
**`dd($model->content_i18n);`** -  `"{"text":"<p>Some test<\/p>"}"`

**Comment by pxpm** [comment]
I tried without casting to array and it works.

Could you give it a try ?

**Comment by lotarbo** [comment]
@pxpm i try this, i wrote behavior with cast and without cast in issue details. 
`dd($model->content_i18n);` return string, its normal or not?)

**Comment by pxpm** [comment]
The demo I showed you has `extras` translatable, the metas are translatable and fake, forget about the object I was thinking wrong. 

I test by also adding a summernote, and it works. 

Please have a look:

https://recordit.co/VUPVohLjz4

**Comment by lotarbo** [comment]
@pxpm thank you for this big explanation, but I know, without cast - its works) I describe this in issue details.
My last question about what Model return. Without casts - it returns string, which need `json_decode`. It's not about admin area. It's about front controller or blade files.
So - it is normal that field returned as string?

**Comment by pxpm** [comment]
I don't think so, please test here: 

https://github.com/Laravel-Backpack/CRUD/blob/f2d0249c12f499b51115a0d6ca8f54417c71f170/src/app/Library/CrudPanel/Traits/Update.php#L106

If you `dd($model->meta_title);` (if you are testing in demo like i showed you) it returns only the value in the current language. 

But I think it depends on how you get the `$model` from database. Try getting a collection of models or a `->first()`, i think they differ.

**Comment by lotarbo** [comment]
@pxpm look at this line https://github.com/Laravel-Backpack/CRUD/blob/f2d0249c12f499b51115a0d6ca8f54417c71f170/src/app/Models/Traits/SpatieTranslatable/HasTranslations.php#L39

when i remove it, and cast content_i18n as array, all works how expected.

**Comment by lotarbo** [comment]
@pxpm i forked demo and add some sample code, pliz check
https://github.com/lotarbo/demo/commit/a2b1ad1025b40f5b0038724e79f9e02c4312946f

when i visit /test url i get this 
![image](https://user-images.githubusercontent.com/1766890/83199202-6a84e400-a149-11ea-87d9-30ad8528717d.png)

**Comment by pxpm** [comment]
Oh I see now @lotarbo, it's outside the crud panel. Sorry you already wrote it, but I was mislead by the title.

You need to get the entry with the fake fields parsed, like we do on CRUD. 

```php
Route::get('test', function() {
$product = \App\Models\Product::whereNotNull('extras')->orderBy('id','desc')->first()->withFakes();
dd($product->meta_title);
});
```
This should get you going. :-)

Going to close this as I think there is no bug here. 

If i am wrong, please re-open.

Best,
Pedro
