### ISSUE TITLE
[Bug] Field with same name as a function in model but not related.

### ISSUE THREAD

**Issue by robertotcestari** [Laravel-Backpack/CRUD#2885]
# Bug report
If a model has a method with the same name as the db, it assumes that it is a relationship and this method is called. 

### What I did

My table have a `searchable` column and one of my fields name (in `CrudController`) is called `searchable`. 
However, Backpack thinks that searchable is a relationship, since it is also a method in my Model (from Scout to be precise). 

### What I expected to happen

A field without a relationship should be treated as a field without a relationship 

### What happened

A field without a relationship was guessed as a field **with** a relationship.
The method is called and the app crashes. 

### What I've already tried to fix it

The only solution would be change my db to a name that is not the same as a method in my model. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
PHP 7.4.5 (cli) (built: Apr 23 2020 02:25:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f
```

**Comment by robertotcestari** [comment]
Just to make clear, Backpack's troublesome method is `makeSureFieldHasEntity()` inside `FieldsProtectedMethods.php` trait.

**Comment by robertotcestari** [comment]
Also, this is a Backpack 4.1 bug. Previous versions were ok!

**Comment by pxpm** [comment]
Hello @robertotcestari 

Indeed this is something we changed in 4.1 to allow us to add fields quicker, with less attrition to the developer. 

When we did it, I did not expect and I still don't expect that much people use a field in the database with the same name of a relation that the field is not related with.

We introduced this change mainly to allow us to 'guess' relationship data from model. If you do: `CRUD::addField('relation_name')` we will check if there is a function in the model with the same name as `relation_name`, but **we only do this check if there is no entity in field**. 

I think there are three possible solutions here:

### Change database field name if you are still developing and can afford it. 

### Use a different field name and then use a mutator/acessor to manipulate the field.

### Use `'entity' => false` in your field definition.

I think using `'entity' => false` solves the problem. But we could agree that it's not an elegant solution, nor a ver intuitive one. 

Me and @tabacitu already talked about it and we discussed the possibility of checking if field name exists as a database column. It might introduce other unwanted caveats, so maybe not the best solution. Also this might not need a solution at all, I think this is a very uncommon scenario. 

I will leave this open for a while, please give me your feedback on the solutions provided @robertotcestari so if anyone bumps in the same error they could fix it too.

Also if anyone else bumps into this same issue, please comment bellow :)

Best,

**Comment by robertotcestari** [comment]
Hi @pxpm, thanks for the prompt message! 

Tried `'entity' => false` , but that lead to other errors. 

I agree having the same name for DB column and Model method would be a rare situation. 
But in this case, my DB field is named `searchable`, which is a method from Laravel Scout. It would be rare to have such collision, but not so much, since searchable is plausible for a db column name. And adding more traits and methods into the Model could increase this probability.  

If you agree, i could look into the error generated by `'entity' => false`, and maybe propose a PR such as when `entity` is set to `false`, Backpack would no further try to guess a relationship. 

What are your thoughts?

**Comment by tabacitu** [comment]
Update: #2971 just got merged, which fixes this by allowing `entity => false`. Thanks a lot @robertotcestari !
