### ISSUE TITLE
[Bug] The wrapper argument for the chart widget is ignored

### ISSUE THREAD

**Issue by dandarie** [Laravel-Backpack/CRUD#2887]
# Bug report

### What I did

I wanted to make a chart widget take half the available width, so I set the wrapper class like suggested:

```
'wrapper' => [
    'class' => 'col-md-6'
],
```

### What I expected to happen

The wrapper class should have been set to col-md-6.

### What happened

The wrapper argument was ignored. Only the old syntax (wrapperClass) is supported.

### What I've already tried to fix it

src/resources/views/base/widgets/chart.blade.php, line 15:
```
- $widget['wrapper']['class'] = $widget['wrapperClass'] ?? 'col-sm-6 col-md-4';
+ $widget['wrapper']['class'] = $widget['wrapper']['class'] ?? $widget['wrapperClass'] ?? 'col-sm-6 col-md-4';
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 20 2020 13:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f
```

**Comment by pxpm** [comment]
Thank you very much for the issue report and the PR @dandarie .

It's merged in master you can grab the fix with a `composer update backpack/crud` in a few moments when it gets tagged with some other bug fixing. 

Best,
Pedro
