### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Davidinho241** [Laravel-Backpack/CRUD#2889]
# Bug report

### What I did

Hi Team, I have use Backpack like this :

The controller

`/**
 * Class UserCrudController
 * @package App\Http\Controllers\Admin
 * @property-read \Backpack\CRUD\app\Library\CrudPanel\CrudPanel $crud
 */
class UserCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation { show as traitShow; }

    public function setup()
    {
        $this->crud->setModel('App\Models\User');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/user');
        $this->crud->setEntityNameStrings('user', 'users');
        $this->crud->addField([
            'label' => "Photo de profile",
            'name' => "image",
            'type' => 'image',
            'crop' => true, // set to true to allow cropping, false to disable
            'upload' => true,
            'aspect_ratio' => 1, // ommit or set to 0 to allow any aspect ratio
            // 'disk' => 's3_bucket', // in case you need to show images from a different disk
            // 'prefix' => 'uploads/images/profile_pictures/' // in case your db value is only the file name (no path), you can use this to prepend your path to the image src (in HTML), before it's shown to the user;
        ]);
        $this->crud->addField([
            'label' => "Poste occupé",
            'type' => 'select',
            'name' => 'role', // the db column for the foreign key
            'entity' => 'role', // the method that defines the relationship in your Model
            'attribute' => 'label', // foreign key attribute that is shown to user
            'model' => "App\Models\Role",
            'default' => 6,

            // optional
            'options'   => (function ($query) {
                return $query->orderBy('label', 'ASC')->get();
            }),
        ]);

        $this->crud->addField([
            'label' => "Sexe",
            'type' => 'select',
            'name' => 'gender', // the db column for the foreign key
            'entity' => 'gender', // the method that defines the relationship in your Model
            'attribute' => 'label', // foreign key attribute that is shown to user
            'model' => "App\Models\Gender",

            // optional
            'options'   => (function ($query) {
                return $query->orderBy('label', 'ASC')->get();
            }),
        ]);

    }

    protected function setupListOperation()
    {
        // TODO: remove setFromDb() and manually define Columns, maybe Filters
        $this->crud->setFromDb();
    }

    protected function setupCreateOperation()
    {
        $this->crud->setValidation(UserRequest::class);

        // TODO: remove setFromDb() and manually define Fields
        $this->crud->setFromDb();
    }

    protected function setupUpdateOperation()
    {
        $this->setupCreateOperation();
    }

    public function show($id)
    {
        //Create the Qr-code before print the user information

        $url = route('user.qr-code.show', $id);

        $user = User::find($id);

        $image = base64_encode(QrCode::format('png')->merge('http://mo-partners.com/logo.png', 0.2, true)
            ->size(200)->errorCorrection('H')
            ->generate($url));

        $final_file_path = 'images/users/qr-codes/_avatar_'.'name'.'_'. $user->name . '.png';
        $base = base64_decode($image);
        file_put_contents(public_path($final_file_path), $base);

        $user->qrcode = $final_file_path;

        $user->save();

        $content = $this->traitshow($id);

        return $content;
    }
}
`
The model 
`class User extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'users';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname', 'name', 'email', 'phone', 'image', 'role', 'gender', 'qrcode', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'qrcode', 'image'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    public function getRoleAttribute($role){
        return Role::find($role)->label;
    }

    public function getGenderAttribute($gender){
        return Gender::find($gender)->label;
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    /**
     * Get the role record associated with the user.
     */
    public function role()
    {
        return $this->hasOne('App\Models\Role');
    }

    /**
     * Get the gender record associated with the user.
     */
    public function gender()
    {
        return $this->hasOne('App\Models\Gender');
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */

    public function setImageAttribute($value)
    {
        $attribute_name = "image";
        $disk = config('backpack.base.root_disk_name'); // or use your own disk, defined in config/filesystems.php
        $destination_path = "public/images/users/avatars"; // path relative to the disk above

        // if the image was erased
        if ($value==null) {
            // delete the image from disk
            \Storage::disk($disk)->delete($this->{$attribute_name});

            // set null in the database column
            $this->attributes[$attribute_name] = null;
        }

        // if a base64 was sent, store it in the db
        if (Str::startsWith($value, 'data:image'))
        {
            // 0. Make the image
            $image = \Image::make($value)->encode('jpg', 90);

            // 1. Generate a filename.
            $filename = md5($value.time()).'.jpg';

            // 2. Store the image on disk.
            \Storage::disk($disk)->put($destination_path.'/'.$filename, $image->stream());

            // 3. Delete the previous image, if there was one.
            \Storage::disk($disk)->delete($this->{$attribute_name});

            // 4. Save the public path to the database
            // but first, remove "public/" from the path, since we're pointing to it from the root folder
            // that way, what gets saved in the database is the user-accesible URL
            $public_destination_path = Str::replaceFirst('public/', '', $destination_path);
            $this->attributes[$attribute_name] = $public_destination_path.'/'.$filename;

        }
    }
}`

### What I expected to happen
I expected to create a user

### What happened
The user is create successfully but a get this : 

Call to a member function update() on string

Backpack\CRUD\app\Library\CrudPanel\CrudPanel::createRelationsForItem
vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Create.php:183

### What I've already tried to fix it

Cancel the project 2 times and restart

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
My guess is that you have a `role` as attribute and a `role` as relation. 

You could use for attribute `getRoleNameAttribute` for example. 

I am going to close this as I don't think this is a bug with backpack. 

If I am wrong, and sometimes I am, please re-open.

Best,
Pedro

**Comment by Davidinho241** [comment]
I have remove the function getRoleAttribute and getGenderAttribute but the issue remain.

I have also try to use the getRoleNameAttribute but nothing.

I have clear the cache but nothing

Please help

**Comment by Davidinho241** [comment]
I think the issue is because, the store function try to insert the value of the role

**Comment by Davidinho241** [comment]
> My guess is that you have a `role` as attribute and a `role` as relation.
> 
> You could use for attribute `getRoleNameAttribute` for example.
> 
> I am going to close this as I don't think this is a bug with backpack.
> 
> If I am wrong, and sometimes I am, please re-open.
> 
> Best,
> Pedro

I have remove the function getRoleAttribute and getGenderAttribute but the issue remain.

I have also try to use the getRoleNameAttribute but nothing.

I have clear the cache but nothing

I think the issue is because, the store function try to insert the value of the role

$item->{$relationMethod}->update($relationData['values']);

Please help
