### ISSUE TITLE
Add Backpack CRUD stylesheet

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/CRUD#290]
Backpack/CRUD has grow considerably and probably needs its own CSS stylesheet.

If you look at the an [example field](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/fields/image.blade.php#L48) you'll see inline styles being common for each Field.

My use case is I'm adding CSS to [make broken images look nicer](https://codepen.io/ire/pen/xVxgeo/). (Image field right now shows an ugly broken image view if the image no longer exists) I think this type of addition belongs in CRUD and fear inline styles for fields will grow unwieldy. 

Beyond fields, I suspect CRUD-specific components will benefit from a stylesheet too.

I can do a PR if this is desired.

**Comment by OwenMelbz** [comment]
As it happens theres 2 PR already for this lol, so maybe just need to give @tabacitu time :)

https://github.com/Laravel-Backpack/CRUD/pull/224 and https://github.com/Laravel-Backpack/CRUD/pull/148

Personally I've modified the `resources/views/vendor/backpack/base/layout.blade.php` file and added

```html
<link rel="stylesheet" href="{{ elixir('css/admin.css') }}">
<script src="{{ elixir('js/admin.js') }}"></script>
```

then in my `gulpfile.js` i've got

```js
    .sass('admin.scss')
    .webpack('admin.js')
```

So all our custom admin css/js goes in those files.

But yes as backpack is growing, we definitely need a layer of separation between

- Base styles
- Crud styles
- Bespoke base/crud styles

One day it will happen!!!

**Comment by zschuessler** [comment]
Ah! Should've reviewed the PRs first, my apologies (and thanks).

**Comment by alashow** [comment]
@OwenMelbz is it possible to configure backpack to compile all js & css into one files (e.g admin.js, admin.css)? (except the ones that require php inside js.)

with Webpack maybe.
That would be an awesome feature.

#148 looks promising though.

**Comment by OwenMelbz** [comment]
It is of course possible, feel free to do that on your project :)

However reason it's not done in here is because it introduces another barrier for users, they might have their own elixir/mix already. So if they want they can integrate it.

Baring in mind with http2 lots of small files are preferred over few big ones, and performance in an admin area isn't that big of a deal
