### ISSUE TITLE
Error Call to a member function update() on string

### ISSUE THREAD

**Issue by Davidinho241** [Laravel-Backpack/CRUD#2907]
> My guess is that you have a `role` as attribute and a `role` as relation.
> 
> You could use for attribute `getRoleNameAttribute` for example.
> 
> I am going to close this as I don't think this is a bug with backpack.
> 
> If I am wrong, and sometimes I am, please re-open.
> 
> Best,
> Pedro

I have remove the function getRoleAttribute and getGenderAttribute but the issue remain.

I have also try to use the getRoleNameAttribute but nothing.

I have clear the cache but nothing

I think the issue is because, the store function try to insert the value of the role

$item->{$relationMethod}->update($relationData['values']);

Please help

_Originally posted by @Davidinho241 in https://github.com/Laravel-Backpack/CRUD/issues/2889#issuecomment-637537275_

**Comment by Davidinho241** [comment]
@pxpm

**Comment by pxpm** [comment]
@Davidinho241 Please don't open multiple issues with same subject. You can comment or re-open previous issues, just don't open new ones with the same topic.

Are you sure HasOne is the relation you want ? Maybe it's a belongsTo, so you can select from the roles table, one role to attach to that user ?

BelongsTo, you have role_id in your user table.
HasOne you have user_id in your Role table. 

To create an HasOne relation, imagine that the role table has user_id and role_name, you would add the crud field -> `CRUD::addField('role.role_name')`, that would save the role_name associated with user_id in the roles table.
