### ISSUE TITLE
Custom order logic produces error with search

### ISSUE THREAD

**Issue by lilessam** [Laravel-Backpack/CRUD#2908]
# Bug report

### What I did

I created a custom order logic to order by a relationship field like the following:

```
return $query->leftJoin('users', 'users.id', '=', 'rooms.user_id')
                        ->orderBy('users.email', $columnDirection)->select('rooms.*');
```

### What I expected to happen

I expect that it doesn't affect any other functionality in the CRUD.

### What happened

Whenever I do a search query in the CRUD while the sorting of that relationship field is triggered .. I get the following error in the Ajax.

```
"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select `rooms`.* from `rooms` left join `users` on `users`.`id` = `rooms`.`user_id` where (`id` like %a% or exists (select * from `users` where `rooms`.`user_id` = `users`.`id` and `email` LIKE %a%) or `bedrooms` like %a% or `bathrooms` like %a% or `roommates` like %a% or `gender` like %a% or `rent` like %a% or `plan` like %a% or `status` like %a%) and `rooms`.`deleted_at` is null order by `users`.`email` asc, `id` desc limit 10)"
```
If I remove the search query from the search field and try to order by the relationship column it works well.

### What I've already tried to fix it

Tried to debug the issue and follow the documentation but no luck.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.3.17 (cli) (built: Apr 16 2020 13:00:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v5.8.38@78eb4dabcc03e189620c16f436358d41d31ae11f

### BACKPACK VERSION:
4.0.61@1977e0cc52fa7cf9547eaeadf03f5cd88402b574
```

**Comment by pxpm** [comment]
Hello @lilessam and thank you for the issue submition. 

I think this is related to: #2112 

You can read my comment there https://github.com/Laravel-Backpack/CRUD/issues/2112#issuecomment-559802908 and let me know if it also fixes for you. 

If it's the same issue, please comment there so we can close this one and make that fix globally available.

Best,
Pedro

**Comment by lilessam** [comment]
Hi @pxpm .. Thanks for your reply.
The issue wasn't that actually but your solution inspired me. The issue in the query is in this part `where (`id` like %a% or exists ` .. it seems even if I join the two tables, it still searches with `id` not `table.id` .. so the way to solve it was to add a custom search logic for the ID column I have in the controller like the following:
```
'searchLogic' => function ($query, $column, $searchTerm) {
    $query->where('rooms.id', 'LIKE', '%'.$searchTerm.'%');
 },
```
But I think that should have been handled automatically by the package that if there's a join and there's a search query with any field it should use `table.field` notation right?

**Comment by tabacitu** [comment]
I agree @lilessam - if the package _can_ handle that automatically, it should. So I'm going to put this on the list of things to do, thanks!

**Comment by tabacitu** [comment]
I see @pxpm just submitted #3015 which fixes this, so let's move the conversation there please! 
Thanks for raising the issue @lilessam !
