### ISSUE TITLE
select2 filter for booleans

### ISSUE THREAD

**Issue by pushamaku** [Laravel-Backpack/CRUD#291]
I have setup a select2 filter for a boolean/tinyint(1) DB column:

```
$this->crud->addFilter([ // select2 filter
  'name' => 'is_online',
  'type' => 'select2',
  'label'=> 'Network Status'
], function() {
	return [
		0 => 'Offline',
		1 => 'Online',
		];
}, function($value) { // if the filter is active
	$this->crud->addClause('where', 'is_online', $value);
});
```
When used it works fine for selecting "Online" rows, but "Offline" shows all rows. How can one tweak this filter to show only the "Offline" rows (is_online == 0) ? I'd prefer not to use 2 simple type filters for each case.

Thank you for any advice on this! :)

**Comment by OwenMelbz** [comment]
Hmm this might be because 0 is resolving to false, so it doesn't detect a filter.

Could you possibly set your offline value to 2 and see if that works?

If it works as expected then there's a bug which needs fixing.

Thanks

**Comment by pushamaku** [comment]
Hi OwenMelbz,

Thanks for checking into this.

I set it to 2, and it does work. I would rather not keep this change as it breaks the "check" type Column in the list.

**Comment by OwenMelbz** [comment]
Oh sure, wouldn't expect you to :) but it's just confirming where the issues lays!

One last test, could you try changing your filter definition from 1/0 to true/false please and let us know what happens?

Thanks

**Comment by OwenMelbz** [comment]
@pushamaku I've put in a PR for @tabacitu to review and merge when he has time, I believe he's a bit sick at the moment so you might have to hold out! (maybe when he see's this/gets time he can also merge the table/video/address fixes in one go!)

https://github.com/Laravel-Backpack/CRUD/pull/292

**Comment by pushamaku** [comment]
Great thank you!
