### ISSUE TITLE
[Bug]  Route parameter problem after upgrade from laravel 5.8 to laravel 6.0 with backpack crud 3.6.33

### ISSUE THREAD

**Issue by yvesnetalis** [Laravel-Backpack/CRUD#2913]
# Bug report

Hello,

I'm try to upgrade from laravel 5.8 to laravel 6 and stay with backpack version 3.6.33 (our project is large and the transition to backpack 4 is complex :wink: ) and I'have strange issue

Now, when I use

```php
route ('crud.opportunity.edit', ['id' => 'x'])
```

I have the following error:

_Missing required parameters for [Route: crud.opportunity.edit] [URI: opportunity / {**opportunity**} / edit]_

But with

```php
route ('crud.opportunity.edit', ['opportunity' => 'x'])
```

That's work fine

Do you have some idea **why the required parameter name have changed**?

* before (laravel 5.8): {id}
* after (laravel 6): {opportunity}

Thanks for your help

### Backpack, Laravel, PHP, DB version

* PHP 7.2.28-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:01) ( NTS )
* backpack/base                         1.1.13                             
* backpack/crud                         3.6.33                                  
* backpack/generators                   1.2.7                                      
* laravel/framework                     v6.18.18                                   
* Database : PostgreSQL

**Comment by pxpm** [comment]
Hello @yvesnetalis 

Indeed I allways used the parameter name in `route()` helper as the same name in route, and from laravel documentation that's how it's supposed to work: https://laravel.com/docs/7.x/routing#required-parameters

This is not something we can help you with, nor a Backpack bug. You might want to look for Laravel upgrade guide for references about it or whatever you can find, **but my best advise to you is just to fix it.** I think that's the way it's supposed to work.

Best,
Pedro

**Comment by yvesnetalis** [comment]
Hello @pxpm 

Thank you to your answer

I had read Laravel's upgrade page but it didn't help much. I have not found what has changed in Laravel's code.
 
But I found how to fix this in backpack :smile: 

In `crud/src/CrudRouter.php`, I added the following code on `$options_with_defaut_route_names` array

```php
'parameters' => [
    $this->name => 'id',
]
```

![Capture du 2020-06-05 11-59-08](https://user-images.githubusercontent.com/34710601/83864571-3307d000-a725-11ea-84de-d5fc947b3574.png)

Problem solved !

Have a good day,
Yves

**Comment by yvesnetalis** [comment]
(https://laravel.com/docs/6.x/controllers#restful-naming-resource-route-parameters)

**Comment by pxpm** [comment]
Well done @yvesnetalis very nice and clean solution.

Thank you very much for making it public, it might help someone that struggles with same problem. 

Best,
Pedro
