### ISSUE TITLE
[Bug] Relationship dependencies

### ISSUE THREAD

**Issue by dividy** [Laravel-Backpack/CRUD#2914]
# Bug report

Tried to specify the dependencies option of a relationship field but I get this error : 

> Call to undefined function array_wrap() (View: C:\laragon\www\effigia\vendor\backpack\crud\src\resources\views\crud\fields\relationship\fetch_or_create.blade.php)

### What I did

field option : 
```php
'dependencies' => ['customer_id'],
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

> ### PHP VERSION:
> PHP 7.2.11 (cli) (built: Oct 10 2018 02:04:07) ( ZTS MSVC15 (Visual C++ 2017) x64 )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
> 
> ### LARAVEL VERSION:
> v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f
> 
> ### BACKPACK VERSION:
> 4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by dividy** [comment]
I guess maybe **array_wrap** became **Arr::wrap()** in latest Laravel version?

**Comment by pxpm** [comment]
I am sorry @dividy 
You are not doing wrong, we did. :hammer: 

Laravel helpers were removed but we didn't removed it from fetch. 

I am submitting a PR to fix it, meanwhile just replace line 95 of `fetch_and_create.blade.php` with: 
`data-dependencies="{{ isset($field['dependencies'])?json_encode(Arr::wrap($field['dependencies'])): json_encode([]) }}"`

Best,
Pedro

**Comment by dividy** [comment]
I fixed it by installing the helpers, because they have been moved to a separate package ?

> composer require laravel/helpers

**Comment by pxpm** [comment]
It's one way to do it, but they have been removed by laravel https://laravel-news.com/laravel-5-8-deprecates-string-and-array-helpers

The prefered option now is using the facades `Arr::` and `Str::`

Ofcourse adding the helpers to your composer is a fix, but is one that you should not need when PR gets merged, so it's up to you to have an extra package in your composer. 

Best,
Pedro

**Comment by dividy** [comment]
I like the nice way you say "If you want to be dumb, it's up to you" haha.

Thanks for pointing out the deprecation, I wasn't aware of that and thanks for the quick reply!

Once again when you get this kind of bug... Better Call Pedro!

**Comment by pxpm** [comment]
Haaa it wasn't meant to be "be dumb if you want", it's more like "from our side we are not going to use the helpers, but you can install them and use them wherever you want if that is your preference" hehe

Thanks @dividy :+1:

**Comment by tabacitu** [comment]
Oups! Just merged the fix, thanks guys!
