### ISSUE TITLE
[Feature Request] Sort By Column

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#2917]
Currently I have a column that looks like this. Where 'age' is a computed assessor (that is getAgeAttribute from date_of_birth database column).

```php
[
                'name'  => 'age',
                'label' => 'Age (From DOB)',
                'type'  => 'number',
],
```

Given that it is computed, there is no sorting on the column. I wonder if there is any way for me to specify that i want this to be able to be sort by date_of_birth?

Thank you

**Comment by tabacitu** [comment]
Hi @ziming ,

For computed columns there's no way for Backpack to know how it can sort it - as you imagine, the PHP processing comes _after_ MySQL has already done its job. 

But for _any_ column, including columns that point to an Eloquent accessor, you can specify the search logic. In fact, the default search logic is very basic - we don't expect it to be perfect 100% of the time. Use the [searchLogic attribute in columns](https://backpackforlaravel.com/docs/4.1/crud-columns#custom-search-logic-for-columns).

Similarly, we have [the `orderLogic` attribute in columns](https://backpackforlaravel.com/docs/4.1/crud-columns#custom-order-logic-for-columns) which helps you do exactly what you're looking for - provide a way for the column to be ordered.

Hope it helps. Let me know if it doesn't and we'll reopen.
Cheers!
