### ISSUE TITLE
FilePond Field Type - alternative to dropzone

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#2926]
# Feature Request

### What's the feature you think Backpack should have?

https://pqina.nl/filepond/

Similar to dropzone.

### Have you already implemented a prototype solution, for your own project?

No i have not 😀

### Do you see this as a core feature or an add-on?

Not sure yet.

**Comment by ziming** [comment]
Filepond is pretty nice. Used it in 2 of my projects so far. (The non admin pages)

**Comment by martijnb92** [comment]
Looks great, however the list of dependencies is getting huge. Maybe do some tree-shaking before creating another field type?

**Comment by tabacitu** [comment]
Thanks for the reality check @martijnb92 ! 🤣 You're right, of course 😄
