### ISSUE TITLE
Problem with SQLite

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2928]
Migrating: 2016_07_24_060017_add_slug_to_categories_table

In Connection.php line 671:

SQLSTATE[HY000]: General error: 1 duplicate column name: slug (SQL: alter table "categories" add column "slug" varchar not null)

In PDOConnection.php line 66:

SQLSTATE[HY000]: General error: 1 duplicate column name: slug

In PDOConnection.php line 64:

SQLSTATE[HY000]: General error: 1 duplicate column name: slug

What I did:
Fresh install of demo with sqlite as DB

Backpack, Laravel, PHP, DB version:
All latest versions

**Comment by martijnb92** [comment]
This is a Laravel problem. Same type of error occurs when trying to create a json type column with MariaDB 10.1. You can try upgrading SQlite to the latest version, maybe that fixes it.

**Comment by srigurubyo** [comment]
I am already on latest sqlite v3

**Comment by srigurubyo** [comment]
`rajan@saelifebook:/usr/bin$ sudo apt upgrade sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlite3 is already the newest version (3.31.1-4ubuntu0.1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

**Comment by srigurubyo** [comment]
rajan@saelifebook:/usr/bin$ sudo apt upgrade sqlite3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlite3 is already the newest version (3.31.1-4ubuntu0.1).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by pxpm** [comment]
Are you sure slug column does not exists when altering the table ?

does a `php artisan migrate:refresh` solve it ?

**Comment by srigurubyo** [comment]
A fresh install of sqlite and backpack solves the issue.

Thanks for your time here.

**Comment by srigurubyo** [comment]
A fresh install of sqlite and backpack solves the issue.

Thanks for your time here.
