### ISSUE TITLE
[Bug] Multiple listener declaration in crud image field's javascript

### ISSUE THREAD

**Issue by tpra** [Laravel-Backpack/CRUD#2934]
JS bug in the crud/fields/image.blade.php file :

Click listeners shouldn't be located in $uploadImage.change function.
This way, each time the user changes the image he's manipulating, the generated listener function is added to the list of functions that are executed when the event fires.

Concrete example : the way it is at the moment, if the user changes the image 4 times, there will be 4 click listeners for each manipulation button.

One should either :
- Not declare a listener inside another one. That's a good practice btw, there's absolutely no need to do that whatever the context.
- If it's absolutely required, which it shouldn't, be sure to call $('the_element').unbind('click') before re-assigning the listener to avoid multiple identical callbacks to be triggered.

**Comment by tabacitu** [comment]
That sounds like a sensible change, thanks for picking up on this one @tpra . Would you like to submit a PR with this improvement?

Cheers!

**Comment by pxpm** [comment]
Hello @tpra 

Sorry for the time it took to reach here. Hope now we fix this for good. 

I'v just submitted PR #3274 that addresses this issue and I'm going to close here. 

If you think there is something we should also address please let us know in the PR thread. 

Wish you the best,
Pedro
