### ISSUE TITLE
Polymorphic Relation Problem

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#294]
Hi 
I have two models  , POST , Tag and polymorphic relation between them . I tried this code in postCrudController :  
```
$this->crud->addField([
            'label' => "تگ ها",
            'type' => 'select2_multiple',
            'name' => 'tags', // the method that defines the relationship in your Model
            'entity' => 'tags', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Tag", // foreign key model
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
        ]);
```
but this error happened :

```

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list' (SQL: insert into `posts` (`title`, `content`, `category_id`, `tags`, `author_id`, `photos`, `status`, `comment_status`, `updated_at`, `created_at`) values (asd, <p>ads</p>
, 1, 2, 1, [], 1, 1, 2016-12-08 20:00:33, 2016-12-08 20:00:33))`

```
then I tried this code :  

```
$this->crud->addField([
            'label' => "تگ ها",
            'type' => 'select2_multiple',
            'name' => '', // the method that defines the relationship in your Model
            'entity' => 'tags', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Tag", // foreign key model
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
        ]);

```
but this time , this error happened : 

```
BadMethodCallException in Builder.php line 2440:
Call to undefined method Illuminate\Database\Query\Builder::()`
```

what is the problem ? I'm confused completely .

**Comment by OwenMelbz** [comment]
To start with, within your `Post` Model, do you have `'tags'` inside your `$fillable` ? 

If you do, I think you need to remove it first, then see what happens

**Comment by M0H3N** [comment]
no  the Post model doesnt have 'tags' inside $fillable

**Comment by OwenMelbz** [comment]
What about the second part of my reply? are you 100% sure your relationships are setup correct? Might be worth pasting your `Post` model and `Tag` model

**Comment by M0H3N** [comment]
In  Post Model : 
 '''  public function tags()
        {
            return $this->morphToMany('App\Models\Tag', 'taggable');
        } '''
and in Tag Model : 
'''public function posts()
        {
            return $this->morphedByMany('App\Models\Post', 'taggable');
        } '''

**Comment by OwenMelbz** [comment]
try changing

```
        public function tags()
        {
            return $this->belongsTo('App\Models\Tag');
        } 
```

and see what happens?

Also are you using a joining table like `postTags` ?

**Comment by M0H3N** [comment]
as I said ...  the Tag Model used by POST and other Models and the appropriate relation is polymorphic not belongsTo ! 
I'm using taggables table for join ,  with this fields : 
id,taggable_id,taggable_type,created_at,updated_at

**Comment by OwenMelbz** [comment]
I know you said that.

I'm asking if it works with a belongsTo.

Because that way we can tell if it's a bug in backpack or your code.

**Comment by M0H3N** [comment]
I tried that code but nothing happend .

**Comment by M0H3N** [comment]
the error still happens .... any idea ?

**Comment by M0H3N** [comment]
I changed my codes to this :  
`$this->crud->addField([
            'label' => "تگ ها",
            'type' => 'select2_multiple',
            'name' => 'tags', // the method that defines the relationship in your Model
            'entity' => 'tags', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => "App\Models\Tag", // foreign key model
            'pivot' => true,
            'morph' => true,
        ]);`
and this time this error happened : 

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'taggable_id' in 'where clause' (SQL: select `tag_id` from `taggables` where `taggable_id` = 17 and `taggable_type` = App\Models\Post)`

**Comment by tabacitu** [comment]
Hi @M0H3N , 

Have you found the solution to your problem? If so, it might be useful to write it here. You would be helping others with the same problem.

Thanks, cheers!

**Comment by M0H3N** [comment]
Hi 
yes of course.... 
 
the problem was structure of my   taggables table  . its must be : 
    tag_id
    taggable_id
    taggable_type

**Comment by tabacitu** [comment]
Great, thanks!
