### ISSUE TITLE
[Bug] setOperationSettings does not exist

### ISSUE THREAD

**Issue by Bazoli** [Laravel-Backpack/CRUD#2942]
# Bug report

### What I did

Tryed to remove all Save Action Buttons on Edit form with removeAllSaveActions function.

### What I expected to happen

BadMethodCallException
Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::setOperationSettings does not exist.

### What I've already tried to fix it

setOperationSettings method does't exist. Whene I changed it to setOperationSetting it's turnd to right.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.15.0@739c44a3f7041430a3fb357f2dcfdb78f55005d7

### BACKPACK VERSION:
4.1.8@393a054490c97721186deb9faed20c6ed70ef6ef

**Comment by pxpm** [comment]
Thanks for report @Bazoli 

Just sent a PR to fix this. #2944 it will be available as soon as @tabacitu merges it. 

It must have slipped :| so sorry.

Going to close this, if you feel there is something more, please re-open.

**Comment by tabacitu** [comment]
Merged! Will be tagged later today and be available with a `composer update`.
