### ISSUE TITLE
[Bug] Widgets with namespace

### ISSUE THREAD

**Issue by Bazoli** [Laravel-Backpack/CRUD#2943]
# Bug report

### What I did

Tried to create custom Widget in a package, with namespace. 

### What I expected to happen

Undefined variable: widgetsViewNamespace in 
vendor\backpack\crud\src\resources\views\base\inc\widgets.blade.php line 10

### What I've already tried to fix it

Change the $widgetsViewNamespace to $currentWidget['viewNamespace'];

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.15.0@739c44a3f7041430a3fb357f2dcfdb78f55005d7

### BACKPACK VERSION:
4.1.8@393a054490c97721186deb9faed20c6ed70ef6ef

**Comment by pxpm** [comment]
@tabacitu did this get lost in Widget refactor ? 

I could not find any reference to `$widgetsViewNamespace` unless in this file. 

At first I though it's some variable that comes from parent view, but not, not any reference to that variable anywhere.

**Comment by pxpm** [comment]
Thanks for the report and a solution @Bazoli .

I'v just submitted a PR with the fix for it, should be available with a composer update after merge, probably next Monday.

I am closing this issue, if you need to address anything related to this issue you can do it in PR #2954 thread.

Best,
Pedro
