### ISSUE TITLE
Error: Unexpected token ? in bpFieldInitSelect2FromAjaxElement

### ISSUE THREAD

**Issue by kornellRus** [Laravel-Backpack/CRUD#2957]
When initializing select2_from_ajax, an error appears: https://prnt.sc/t487fg
Error: https://prnt.sc/t485jn
Can I fix it myself or wait for the update?

**Comment by tabacitu** [comment]
Hmm @kornellRus how do you define this particular field? Can you please copy&paste the addField statement?

**Comment by kornellRus** [comment]
> Хм @kornellRus, как вы определяете это поле? Можете ли вы скопировать и вставить инструкцию addField?

`        $this->crud->addField([
            'name'  => 'country_id',
            'label' => "Страна",
//            'entity' => 'country',
            'attribute' => 'name',
            'model' => "App\Models\Country",
            'placeholder' => "Выберите страну",
            'minimum_input_length'    => 0,
            'include_all_form_fields' => true,
            'type'  => 'select2_from_ajax',
            'data_source' => url("/api/country")
        ]);`

Does js have such syntax for "if"?
`var $selectedOptions = JSON.parse(element.attr('data-selected-options') ?? null);`
If used like this, then everything works fine.:
`var $selectedOptions = JSON.parse(element.attr('data-selected-options') ?element.attr('data-selected-options'): null);`

**Comment by tabacitu** [comment]
That's interesting @kornellRus , thanks for the details! From what I understand, for some reason, the null coalescing operator doesn't work in your browser. I see [browser support for it is pretty good](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) so I'm wondering - **what browser did you test on? Name and version please**.

If this fails for you here, and it's a popular browser, we might need to replace this null coalescing operator everywhere else we're using it in JavaScript...

**Comment by kornellRus** [comment]
> That's interesting @kornellRus , thanks for the details! From what I understand, for some reason, the null coalescing operator doesn't work in your browser. I see [browser support for it is pretty good](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) so I'm wondering - **what browser did you test on? Name and version please**.
> 
> If this fails for you here, and it's a popular browser, we might need to replace this null coalescing operator everywhere else we're using it in JavaScript...

browser: Google Chrome 74 https://prnt.sc/t4ehye

**Comment by pxpm** [comment]
Indeed Chrome 74 does not support it. Only 80+ chrome. 

What do you think @tabacitu ? Push changes aimed for backwards compatibility instead of readability of code ?

Best,
Pedro

**Comment by tabacitu** [comment]
Ah, ok, I get it now. Yes, @pxpm , sounds good, let's make it backwards-compatible please. 

@kornellRus would you like to submit a PR with this so you show up a contributor? Or should @pxpm or I do it?

Cheers!

**Comment by kornellRus** [comment]
> Ах, хорошо, теперь я понял. Да, @pxpm , звучит хорошо, давайте сделаем его обратно совместимым, пожалуйста.
> 
> @kornellRus Вы хотели бы отправить PR с этим, чтобы вы нашли автора? Или @pxpm, или я делаю это?
> 
> Ура!

I cannot make edits at this time. To whom it will be more convenient, please make corrections.

**Comment by pxpm** [comment]
I just pushed a PR #3024 that addresses this.

Let's keep the discussion in PR if needed. 

If you feel there is something more we should account for, please re-open if needed. 

Wish you the best,
Pedro
