### ISSUE TITLE
validation issue on upload_multiple feild

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#296]
Hi 
when the validation of  upload_multiple field didn't pass(actually when upload_multiple field is sent empty) this errors happens : 

```
ErrorException in helpers.php line 519:
htmlspecialchars() expects parameter 1 to be string, array given (View: E:\Engineering Organization\vendor\backpack\crud\src\resources\views\fields\upload_multiple.blade.php) (View: E:\Engineering Organization\vendor\backpack\crud\src\resources\views\fields\upload_multiple.blade.php) (View: E:\Engineering Organization\vendor\backpack\crud\src\resources\views\fields\upload_multiple.blade.php)
```
my validation rules is : 
 'photos' => 'file|image|max:1000'

what is the problem ?

**Comment by tabacitu** [comment]
Hi @M0H3N ,

Just pushed an update that should fix it. Could you please confirm?

Cheers!

**Comment by M0H3N** [comment]
Hi 
I updated it but this time another issue happened .
in admin/post/create route this error happened :  

ErrorException in 4383a02f7de3dc5a7680cf9aceb3fd6814eaa807.php line 19:
Undefined index: value (View: D:\project\WebProgramming\MyWorks\Laravel\Engineering Organization\vendor\backpack\crud\src\resources\views\fields\select_from_array.blade.php) (View: D:\project\WebProgramming\MyWorks\Laravel\Engineering Organization\vendor\backpack\crud\src\resources\views\fields\select_from_array.blade.php) (View: D:\project\WebProgramming\MyWorks\Laravel\Engineering Organization\vendor\backpack\crud\src\resources\views\fields\select_from_array.blade.php)

**Comment by OwenMelbz** [comment]
Just to check something.

If you find where you're creating the crud field that uses `select_from_array` what happens if you add a `value` attribute to it? for example.

```
$this->crud->addField([
    'value' => null,
    // all you other stuff in here also
]);
```

**Comment by M0H3N** [comment]
yes Its fixed after I added  'value' => null

**Comment by RamiMustaklem** [comment]
If you send an empty (not required) photos field, it still gives the first error which is 
`htmlspecialchars() expects parameter 1 to be string, array given`
and if you dd() the request value it gives
`array:1 [▼
  0 => ""
]`

It triggers the exception before entering the store method of the controller.
The exception is triggered within the request class used for the store method.

**Comment by tabacitu** [comment]
@RamiMustaklem , the input the upload_multiple field should be an array, so I think [validating it as such](https://laravel.com/docs/5.3/validation#validating-arrays) should fix the problem for you.

Cheers!

**Comment by tabacitu** [comment]
P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
