### ISSUE TITLE
[Bug] address_google field does not work well inside inline create popup

### ISSUE THREAD

**Issue by kenjilabs** [Laravel-Backpack/CRUD#2962]
# Bug report

### What I did

added address_google to the inline field model

### What I expected to happen

to show suggestions of typed address 
![image](https://user-images.githubusercontent.com/2118549/85523898-97c59480-b618-11ea-8c0b-54389b176dcd.png)

### What happened

address_google send ajax request to map but suggestion popup is not showing

![image](https://user-images.githubusercontent.com/2118549/85523803-7c5a8980-b618-11ea-9952-5d7052d8619c.png)
![image](https://user-images.githubusercontent.com/2118549/85523861-8e3c2c80-b618-11ea-8af0-39c5cc8950dd.png)

###  Quick fix solution

**File:** vendor\backpack\crud\src\resources\views\crud\fields\address_google.blade.php
**Line:** 70

`.modal-open .pac-container{
                z-index: 99999;
            }`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.7 (cli) (built: Jun 12 2020 07:44:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.17.1@6633c4017b311d3aaae842edabd567c637afc39c

### BACKPACK VERSION:
4.1.11@acc4df836505a612d1dd15a39ce02be87e36577d

**Comment by pxpm** [comment]
Hello @kenjilabs thanks for report. This is an known issue. I am not 100% sure what is the error with this field inside repeatable, I know that @tabacitu found something here: #2758 

Hey @tabacitu do you think `.modal-open .pac-container{ z-index: 99999; }` it's the solution to our problem ?

@kenjilabs is the field working as expected now after applying your solution ? 

Best,
Pedro

**Comment by kenjilabs** [comment]
after applying the solution field is working as expected

**Comment by pxpm** [comment]
Hello @kenjilabs 

I was not able to fully work it out. Indeed the options show, but I am not able to close the options dropdown if I click outside of it without selecting an option. 

Did you have same problem ?

**Comment by pxpm** [comment]
@kenjilabs 

We did some changes in the way repeatable fields are initialized. 

Could you update (at least to 4.1.20) and give it another try ? 

Wish you the best,
Pedro

**Comment by promatik** [comment]
Hi @kenjilabs thank you for your report and suggestion 🙌

I've just created a PR to solve this, I followed your logic, moving the google places API container up in z until it's higher than the modal.

Let's move conversation to https://github.com/Laravel-Backpack/CRUD/pull/3477
