### ISSUE TITLE
[Feature Request] send form data to inline create popup

### ISSUE THREAD

**Issue by kenjilabs** [Laravel-Backpack/CRUD#2964]
# Feature Request

### What's the feature you think Backpack should have?

Send form data to inline create modal

### Have you already implemented a prototype solution, for your own project?

added  var form = element.closest('form') on line 239 and 'form': form.serializeArray() // all other form inputs on line 257

vendor\backpack\crud\src\resources\views\crud\fields\relationship\fetch_or_create.blade.php

### Do you see this as a core feature or an add-on?

core future for fetch_or_create.blade.php file

**Comment by pxpm** [comment]
Hello @kenjilabs 

Thanks for raising this issue. We already have a PR to address it: #2912 

I just reviewed and I think this will get merged soon. 

I will close this as it's an already asked feature and we are about to provide it. 

Best,
Pedro
