### ISSUE TITLE
[Bug] storeInlineCreate function cannot pass value to the entity

### ISSUE THREAD

**Issue by kenjilabs** [Laravel-Backpack/CRUD#2965]
# Bug report

In the storeInlineCreate function, I'm trying to assign  customer_id with 
` $this->crud->getRequest()->request->add(['customer_id' => $customer_id]) `

the method, but for some reason, it's not adding it entity 

I tried to follow the following steps from the documentation 
[(https://backpackforlaravel.com/docs/4.1/crud-operation-create#callbacks]

` $this->crud->request->request->add(['customer_id' => $customer_id])` when i use  `$this->crud->request` insted of  `$this->crud->getRequest()` it gives error protected method

```
class AddressCrudController extends CrudController
{
  ...
use InlineCreateOperation {
        storeInlineCreate as inlineTraitStore;
    }

public function storeInlineCreate()
    {

        $customer_id = $this->crud->getRequest()->get('customer_id');

        $this->crud->getRequest()->request->add(
            [
                'customer_id' => $customer_id
            ]
        );
        $response = $this->inlineTraitStore();
        // do something after save
        return $response;
    }
}
```

### What I expected to happen

customer_id to be saved in database with rest of the fields 

### What happened

customer_id gets ignored 

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by kenjilabs** [comment]
forgot to add below

```
 $this->crud->setOperationSetting('saveAllInputsExcept',
            ['_token', '_method', 'http_referrer', 'current_tab', 'save_action']
        );
```

**Comment by tabacitu** [comment]
Thanks for posting your solution too @kenjilabs - I'm sure someone someday will stumble onto this and be grateful 😄
