### ISSUE TITLE
select2_from_ajax_multiple multiple population inside repeatable

### ISSUE THREAD

**Issue by warton** [Laravel-Backpack/CRUD#2967]
# Bug report

### What I did

I have `select2_from_ajax_multiple` field inside `repeatable`. Then I add e.g. 5 elements inside `repeatable` with this `select2_from_ajax_multiple` and selecting some options and save. After opening update page, initialization of each repeatable is not correct, as it seems like initializing all previously initialized elements again. So first is initialized 5 times, second 4 times, third 3 times, fourth 2 times and only last once. This results into having 5 times duplicated selected options in first element, etc.

![image](https://user-images.githubusercontent.com/4300753/85685330-38768b80-b6cf-11ea-9e82-b2bb5fea1384.png)

### What I expected to happen

Each selected option should be initialized only once.

### What happened

Each selected option initialized many times according the number of repeatable elements as described above.

### What I've already tried to fix it

Solution is very easy. File `resources\views\crud\fields\repeatable.blade.php`: 184:

```
initializeFieldsWithJavascript(container);
```

needs to be changed to:

```
initializeFieldsWithJavascript(new_field_group);
```

It is wrongly initializing whole repeatable each time. Fix will initialize only newly added element.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
C:\www\nrz-admin>php artisan backpack:version
### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.17.2@d16ff3a0a66d98e04163456b39c4b7302cf50a40

### BACKPACK VERSION:
4.1.11@acc4df836505a612d1dd15a39ce02be87e36577d

**Comment by pxpm** [comment]
Hello @warton 

I am not sure what is causing the issue for you, but I think it's not related to initializing the whole container. After the initialization fields get an `element.attr('data-initialized', 'true');` so that element will not be initialized twice.

I tested with:

```php
CRUD::addField([
            'name'     => 'my_teste_field',
            'label'    => 'yeah',
            'type'     => 'repeatable',
            'fake'     => true,
            'store_in' => 'extras',
            'fields'   => [
                [ // Select2_from_ajax_multiple: n-n relationship with pivot table
                    'label'                => 'Select2_from_ajax_multiple', // Table column heading
                    'type'                 => 'select2_from_ajax_multiple',
                    'name'                 => 'articles', // the column that contains the ID of that connected entity;
                    'entity'               => 'articles', // the method that defines the relationship in your Model
                    'attribute'            => 'title', // foreign key attribute that is shown to user
                    'model'                => "Backpack\NewsCRUD\app\Models\Article", // foreign key model
                    'data_source'          => url('api/article'), // url to controller search function (with /{id} should return model)
                    'placeholder'          => 'Select one or more articles', // placeholder for the select
                    'minimum_input_length' => 2, // minimum characters to type before querying results
                    'pivot'                => true, // on create&update, do you need to add/delete pivot table entries?
                    //'tab'                  => 'Relationships',
                    'wrapperAttributes'    => ['class' => 'form-group col-md-6'],
                ],
            ],
        ]); 


public function articles()
    {
        return $this->belongsToMany(\Backpack\NewsCRUD\app\Models\Article::class, 'monster_article', 'monster_id', 'article_id');
    }
``


The issue does not occur: 

![Screenshot_12](https://user-images.githubusercontent.com/7188159/85869483-a4d2b700-b7c3-11ea-820b-ece47373d015.png)

Any more info you can provide ? Maybe it's conflicting with something else...

Best,
Pedro

**Comment by warton** [comment]
Hi @pxpm ,
Thanks for your feedback. I will try to check my code for possible conflicts. I had to do few custom modifications and own fields so the issue might be somewhere there.
I'll get back once I have more simulations..

**Comment by tabacitu** [comment]
Thanks for posting about this @warton . And especially thanks for the solution 😄 
Closing thanks to PR #3052 which will be merged and tagged later today.

Cheers!
