### ISSUE TITLE
entity attribute not calling method defined

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#297]
$this->crud->addField([    // SELECT
                                'label' => 'Category',
                                'type' => 'select2',
                                'name' => 'category_id',
                                'entity' => 'category', // the method that defines the relationship in your Model
                                'attribute' => 'name',
                                'model' => "App\Models\ProductCategory",
                            ]);

**entity property** is not being used. either we assign it or remove it, we get the same result returning all records.

i want to use it to get some filtered records.

**Comment by tabacitu** [comment]
Hmm... you could use a different model, say ```App\Models\FilteredProductCategory```, which extends ```App\Models\ProductCategory``` and sets a [global scope](https://laravel.com/docs/5.3/eloquent#global-scopes). 

Would that work for you?

Cheers!
