### ISSUE TITLE
[Help] Pulling quantity of a material 'selected'

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2973]
I have a requirement where in I have two fields material_id and material_quantity need to be filled in a form for processing.  

While I have managed to create select2 type for the material_id field (using appropriate belongsTo() relationship with the processing entity) I am not able to pull the CORRESPONDING material_quantity dynamically (of the same material_id).  

I believe this can be achieved using ajax calls, but wanted to check with experts is there any simpler way of achieving this functionality?

Table structure:
**Material**
    id
    quantity

**Process**
    id
    material_id

**Comment by pxpm** [comment]
Hello @srigurubyo 

Indeed the best way would be using an Ajax fields with the option to pass all form fields.
In the search function you could check if the other field is filled and return the related entries. 

Best,
Pedro
