### ISSUE TITLE
[Bug] Wrapper does not work for CREATE and UPDATE

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2976]
# Bug report
Applying styles to CREATE and UPDATE through 'wrapper' doesn't work

### What I did

```
CRUD::addField([
           'name'      => 'status',
           'label'     => 'To status',
           'type'      => 'radio',
           'options'   => CommonHelper::getFurtherStatuses($this->crud->getCurrentEntry()->status),
           'inline'    => true,
           'wrapper' => [
               'element' => 'span',
               'class' => function ($crud, $column, $entry, $related_key) {
                               return CommonHelper::getStatusColor($column);
                          },
           ],
       ]);
```

### What I expected to happen
The options for the 'radio' should have been changed according to the style applied through the wrapper.

### What happened
Error while running

`Too few arguments to function app\Http\Controllers\Admin\MaterialCrudController::app\Http\Controllers\Admin\{closure}(), 3 passed in /home/srigurubyo/work/laravel/usip/storage/framework/views/abe1029fcf60c5304a40f480b0fe73be4c6245f8.php on line 7 and exactly 4 expected (View: /home/srigurubyo/work/laravel/usip/vendor/backpack/crud/src/resources/views/crud/fields/inc/wrapper_start.blade.php)`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

#### PHP VERSION:
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

#### LARAVEL VERSION:
v7.17.2@d16ff3a0a66d98e04163456b39c4b7302cf50a40

#### BACKPACK VERSION:
4.1.11@acc4df836505a612d1dd15a39ce02be87e36577d

**Comment by srigurubyo** [comment]
I just realized that there is a reddit channel to ask questions, so closing this here.

[https://www.reddit.com/r/BackpackForLaravel/comments/hig88h/wrapper_does_not_work_for_create_and_update/](url)

**Comment by pxpm** [comment]
Hello @srigurubyo 

The problem is that you are adding a field and using a `column wrapper` definition. 

For fields is a little bit different:

`=> function ($crud, $field, $entry )`

Remember that in fields the wrapper apply to the whole field, not by option as in some columns like `select`.

Best,
Pedro

**Comment by srigurubyo** [comment]
You mean to say, I can not use below syntax ?

```
                    if ($field['key'] == USIPConstants::$STATUS_REJECTED) {
                        return 'badge badge-danger';
                    }
```
If so, is there a way I can differentiate between the various options to make it visible to user (GREEN and RED example)?
