### ISSUE TITLE
[Help] Show content dynamically for the selected

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2978]
# Report
When I select (say customer) using Dropdown I would want to show users all the properties (of the customer) on a side table or division. Essentially, displaying the selected customer's fields on the same page for the users to verify/read.

Any help is greatly appreciated from the experts.

**Comment by pxpm** [comment]
Hello @srigurubyo 

One way I see that beeing done is by using an event listener on the select, having the table already in the page with some placeholders with id of the fields, when the listener fires (user selected a customer) you query another ajax endpoint, grab that customer information and display it in the table.

You can also use another event to clear the table if the user clear the selection. 

This might be an interesting addon for backpack, a `select_with_info` field type. If you come up with something that can be shared please let us know. 

Best,
Pedro

**Comment by srigurubyo** [comment]
Thanks @pxpm for your inputs. Let me try to implement this custom field and shall you keep you posted.

**Comment by pxpm** [comment]
@tabacitu I would like to move this to the addons repo, but I am unable to select it. There is no addons repo to select in list nor searching finds nothing. Could you move it please ? I like the concept of some field like this.

Best,

**Comment by tabacitu** [comment]
Oups! Looks like I forgot to give the Veterans team the permission to manage the add-ons repo. Fixed and moved!
