### ISSUE TITLE
[Bug] If i give denyAccess to update and delete but still Action column is available without button

### ISSUE THREAD

**Issue by senthu1994** [Laravel-Backpack/CRUD#2985]
# Bug report

### What I did

In the crud controller i add below code in setupListOperation method
`$this->crud->denyAccess(['create', 'update', 'delete']);`

### What I expected to happen

Action column will be fully hide.

### What happened

Only button removed and Action column still there.

### What I've already tried to fix it

In crud/list.blade.php
I tried to get `$crud->buttons()->where('stack', 'line')->count()` it give 2 as output and i tried to get `$crud->buttons()->where('stack', 'line')` it gives output as below.
`{"2":{"stack":"line","name":"update","type":"view","content":"crud::buttons.update","position":null},"3":{"stack":"line","name":"delete","type":"view","content":"crud::buttons.delete","position":null}}  `

### Backpack, Laravel, PHP, DB version
Backpack 4.1, Laravel 7.x, PHP 7.3

**Comment by pxpm** [comment]
Hello @senthu1994 

Denying access is different than removing the buttons. 

To properly remove the buttons you should use the button api available at: [backpack button api](https://backpackforlaravel.com/docs/4.1/crud-buttons#buttons-api)

If you don't want the user to be able to access those features after button deletion you should still deny access like you are doing.

There is also an extra feature that is not mentioned there I think that is `removeAllButtonsFromStack('stack_name')` in your scenario that would be `line`.

Best,
Pedro
