### ISSUE TITLE
[Bug] Creatie operation command fails

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2986]
# Bug report
Running `php artisan backpack:crud-operation CheckIn` fails

### What I did

`php artisan backpack:crud-operation CheckIn`

### What I expected to happen

Operation class should have been generated automatically

### What happened
```
   RuntimeException 

  Unable to detect application namespace.

  at vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1304
    1300|                 }
    1301|             }
    1302|         }
    1303| 
  > 1304|         throw new RuntimeException('Unable to detect application namespace.');
    1305|     }
    1306| }
    1307| 

      +17 vendor frames 
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

```

### What I've already tried to fix it

Manually generated the Operation class

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS ) Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION: 
v7.18.0@116b508bafd81de97b1c09744445d32a91076b60

### BACKPACK VERSION:
4.1.12@e5e3efc89775574fff03ef0000677e9a85903c9b

**I have renamed my 'app' folder to 'App' for consistency and not sure that is the root cause of this issue**

**Comment by srigurubyo** [comment]
Laravel framework has 'app' hardcoded inside so changing the default package name to App will not work.  Closing this.

**Comment by benyaminl** [comment]
@srigurubyo Wow, this still the same for laravel after several years. But thanks for point this out. it's hard to debug why App change in composer.json cause error but can show 404. 

Thanks!
