### ISSUE TITLE
[HowTo] Copy Text to clipboard from CRUD list?

### ISSUE THREAD

**Issue by AlexanderWM** [Laravel-Backpack/CRUD#2987]
Hello!

I'm want to copy to clipboard the value of a column by clicking on this value. But in the documentation I didn't find how to use javascript in "wrapper". Any examples?

When I run ```php artisan backpack:version``` the output is:

**Comment by martijnb92** [comment]
You probably mean the list view,
To copy column content to the clipboard you should add some custom javascript
This can be done using the `list.js` file, [details here](https://stackoverflow.com/questions/48926221/copy-element-content-to-clipboard-on-click-using-jquery)
Here is an example of the js code, https://stackoverflow.com/a/48927455 make sure you adjust element selector. Then it should work.
For more questions please ask them on stackoverflow or another channel.

**Comment by pxpm** [comment]
Thanks @martijnb92 for pitching in.

I would just add that you can pass a string or a function to the wrapper.

Something like: 

```php
'onClick' => "(function(){
    alert('Hey i am calling');
    return false;
})();return false;";
```

Not sure this is the solution that you need, it might need more work that adding js into the wrapper.

Best,
Pedro
