### ISSUE TITLE
Consider Using Laravel Collective's Form Fields API

### ISSUE THREAD

**Issue by zschuessler** [Laravel-Backpack/CRUD#299]
Form fields are tightly coupled to the CRUD functionality. Some reasons that is an issue:

1. Can't use form field templates outside of CRUD without code duplication.
2. Can't easily modify form fields as objects
3. Setting custom options/attributes is more organized and predictable

CRUD already uses [Laravel Collective](https://laravelcollective.com/docs/5.3/html#custom-components), so while adding in the API would be a lot of work, there is much to be gained.

**Comment by OwenMelbz** [comment]
Hey, I think something like this is already planned for v4, as would require a large rewrite.
You can see an example setup https://github.com/Laravel-Backpack/CRUD/issues/41

**Comment by tabacitu** [comment]
Hmm... I don't think I understand very well... @zschuessler could you please give more details about the implementation? Would this imply calling the fields you want from the blade files instead of the EntityCrudController?

Thanks, cheers!
