### ISSUE TITLE
[Help] Using Backpack Admin UI template for application as well

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#2990]
# Report
I am able to successfully install and configure backpack to greater extent.  The admin UI is built nicely, so I would like to use it for the application as well. I mean both the 'admin' as well the actual application will have same UI (but of course with necessary permissions and restrictions).

Can any experts provide some pointers here how to do that? (Reusing backpack 'admin' UI/CSS/JS etc for the actual application as well)

**Comment by tabacitu** [comment]
Sure just make sure your blade files extend the same blade file as the admin does: `@extends(backpack_view('blank'))`. For more info see https://backpackforlaravel.com/docs/4.1/getting-started-videos#the-admin-interface

**Comment by tabacitu** [comment]
Also I've just added a section to the docs that explains this in a little more details - https://backpackforlaravel.com/docs/4.1/base-how-to#use-the-html-css-for-the-front-end-backstrap-for-front-facing-we
