### ISSUE TITLE
[Bug] Google Places API Key possible leak 

### ISSUE THREAD

**Issue by maverickvn360** [Laravel-Backpack/CRUD#2998]
# Bug report

### What I did

Possible API key leak (Google)

### What I expected to happen

Write doc not exposing the API key

### What happened

An API key is leaked (possible false positive) in the crud-fields.md file

### What I've already tried to fix it

--

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
--

**Comment by tabacitu** [comment]
Hi @maverickvn360 ,

Thanks for raising the issue. You mean the one from the `address_google` field type here https://backpackforlaravel.com/docs/4.1/crud-fields#address_google ? The fact that we have our own API key as fallback?

Cheers!

**Comment by maverickvn360** [comment]
Hi @tabacitu ,
Not actually that, but in the 'video' section of the doc v4.1..

**Comment by tabacitu** [comment]
Ah, right! Same thing. 

No worries - that's an API key that has no credit card attached to it. It's for people to try it without going through the process of creating a Google API Key themselves. When it hits the free limit ceiling every month, it stops working. But at least _some_ people got to try it easily, until that limit is reached 😄 

I've updated the docs to explain this - to better convince people to use their own API Key - https://github.com/Laravel-Backpack/docs/commit/bc31b233b8c189a36f15a5fedbb4d8044f6ca66c

Thanks for the heads-up!
