### ISSUE TITLE
provide demo resources

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3]
A few resources to help people get started / quickly create new files. Those resources should be stored in the plugin and published with the "demo" tag.

// publish demo resources:
            // - Auto Models: Article, Category, Tag
            // - Auto Requests: Article, Category, Tag
            // - Auto Controllers: Crud/ArticleController, Crud/CategoryController, Crud/TagController
            // - MANUAL routes
            // - MANUAL migration for those entities

**Comment by codydh** [comment]
Am I correct that this doesn't currently run as-is? Would be happy to help generate some documentation and demo resources once the base project is working!

**Comment by tabacitu** [comment]
Hi Cody,

It does run, but right now it's just a fork of https://github.com/tabacitu/crud (version 1). In the following 2 weeks there will be a lot of changes to the API, to make it a lot better than its parent (syntax will be testable, introducing column types, matrix fields, etc).

Please sign up to the newsletter http://laravelbackpack.us13.list-manage.com/subscribe?u=481cc18afdb1e440e3dbfc3a4&id=fc930b1077 and I'll ping you when the API is stable (in about 2 weeks). The first newsletter will be a shout out for feedback, testing and help on bug fixing and documentation.

Cheers and thanks for the interest!
