### ISSUE TITLE
passing value in crud route but issue with details row

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/CRUD#301]
Hi,
im using the method given here:
https://github.com/Laravel-Backpack/CRUD/issues/122
this works perfectly.. 

but there is one issue using that method
when i enable details row on the crud using this it passes status value in the id as well on showdetails method.

my crudcontroller:
```
<?php
namespace App\Http\Controllers\Admin;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use App\User;
class StudentListsController extends CrudController {
	public function setUp() {
        $status = \Route::current()->parameter('userstatus');
        $this->crud->setModel("App\User");
        $this->crud->setRoute("admin/student/".$status."");
        $this->crud->setEntityNameStrings('Student '.$status.'', 'Students '.$status.'');
        $this->crud->enableAjaxTable();
        $this->crud->enableDetailsRow();
		$this->crud->setFromDb();
    }
    public function showDetailsRow($id)
    {
        dd($id);
        $user = User::where('id', $id)->first();
        return view('partials.student_details_row')->with('user', $user);
    }
}
```
and my route file:
```
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function()
{
CRUD::resource( 'student/{userstatus}', 'StudentListsController' );
});
```
so on the above  dd($id) instead of getting user-id i get {userstatus} value.

**Comment by mpixelz** [comment]
@tabacitu sorry for posting another thread for this.. but i thought it would be better to open this as an issue..
i've tried dd(\Request::input()); instead of dd($id);
and it shows ``[]`` as the result as there is nothing in there.

**Comment by tabacitu** [comment]
How about Request::all() then?

**Comment by OwenMelbz** [comment]
`request:all()` inside `showDetailsRow` will be empty unless you post to it.

Are you creating a new entity, or updating an existing one?

**Comment by mpixelz** [comment]
its a list of users where ive added some addclause to filter the results.. now need detailsrow to show details about the users..

**Comment by OwenMelbz** [comment]
then what would you expect `$id` to be? if your not accessing an entity, and your not posting to a resource, both `id` and `request` will be empty, as you're not using them.

What is it that you're trying to actually achieve?

**Comment by mpixelz** [comment]
it should have id of the entity im accessing.. it works on all other pages except on this controller as they are based on the method mentioned in the opening post.

**Comment by OwenMelbz** [comment]
But you said up top that its a list of users? if its a list then why would you have a single entity? 

So confused here haha xD

**Comment by OwenMelbz** [comment]
Sorted.

Was using a custom routing system which meant that the first param of `showDetailsRow` was no longer `$id`, it shuffled it across so `$id` was the 2nd param

**Comment by maganius** [comment]
I have the same issue (i think), in the list operator I have a list with `orders` and I need display in the detail row the `items` of each order its easy I can use `$order->items` in the controller, but when I need filter by `companies` the first list table works correctly but I can't access to filters in the detail row to prepare the query `order()->where('company_id', $company_id)`.

my filter is:

```
$this->crud->addFilter([
            'name' => 'company',
            'type' => 'select2_multiple',
            'label' => 'Empresas'
        ], function () {
            return Empresa::all()->pluck('nombre', 'id')->toArray();
        }, function ($values) { // if the filter is active
            $this->crud->query->select('empresas.nombre as empresa_nombre', 'empresa_id');
            foreach (json_decode($values) as $key => $value) {
                $this->crud->addClause('orWhere', 'empresa_id', $value);
            }
            $this->crud->query->orderBy('empresa_id');
            $this->crud->query->groupBy('empresa_id', 'item_id');
        });
```

Detail row

```
public function showDetailsRow($id)
    {
        $this->crud->hasAccessOrFail('list');
        // get entry ID from Request (makes sure its the last ID for nested resources)
        $id = $this->crud->getCurrentEntryId() ?? $id;
        $this->data['crud'] = $this->crud;
        
        // here I need same filters as parent list, I need filter orders by company but its ajax request I can't access to filters values
        $this->data['entry'] = $this->crud->getCurrentEntry()->Ordenes->groupBy('Empresa.nombre');
        return view('backend.partial.report.detail', $this->data);
    }
```

**Comment by tabacitu** [comment]
Oh that's trickier @maganius . Indeed, since the details_row functionality uses an AJAX request, you don't have access to the same filters. But you _could_ look at the referer using ```request()->headers->get('referer')```, and infer the filters from that.

Here's what I got, when I did ```dd(request()->headers->get('referer'))``` inside a details row view:
![Screenshot 2020-01-30 at 10 00 55](https://user-images.githubusercontent.com/1032474/73430780-8cab5880-4347-11ea-8dd5-cc24f0f35bcd.png)

You can see the filter is in the URL as a GET parameter.
Hope it helps.
Cheers!
