### ISSUE TITLE
[Bug] Error in Image column using custom disk (s3).

### ISSUE THREAD

**Issue by robertotcestari** [Laravel-Backpack/CRUD#3010]
# Bug report

### What I did

Using Image field with a s3 disk.  

### What I expected to happen

Show images thumbnails - and when there were no images in a specific entry, don't show any images.  

### What happened

Error when there is an entry without image. No entries are shown. 

### What I've already tried to fix it

This is only fixed changing the Image view. 
The problem is with this line of code in `crud/columns/image.blade.php` :
```php
$href = $src = Storage::disk($column['disk'])->url($column['prefix'].$value);
```

When `$value` is `null` (that happens when the entry has no image), then it throws an error and no entries are listed. 
Let me know what you think and i can make a pull request for this bug. 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 23 2020 02:25:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
```

**Comment by tabacitu** [comment]
Yes please! A PR would be most welcome. Thank you @robertotcestari for raising this, and for offering to submit a PR.

Am I wrong, or is it the same issue as https://github.com/Laravel-Backpack/CRUD/pull/2936 - just a different fix?

**Comment by robertotcestari** [comment]
@tabacitu the #2936 refers to the image _field_, this is a bug regarding image _column_. I will make a PR today for the column! 

:)

**Comment by tabacitu** [comment]
Oh _right_! Column, not field. Got it, thanks! Merged.
