### ISSUE TITLE
[Bug] Multiple table fields inside repeatable duplicate rows 

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3012]
Apparently, when adding a table field into a repeatable one. When you add a repeatable group and after that you add a row in the table field, rows are duplicated, triplicated, etc... Only the last repeatable element is working normally. The other ones are adding unnecessary rows like they were accumulating the number of rows to add when button is clicked depending on the repeatable position.

![Captura de pantalla 2020-06-23 a las 18 12 09](https://user-images.githubusercontent.com/28789386/85428816-0bff2a00-b57e-11ea-8a6c-7b152ac7631d.png)

_Originally posted by @chivomd in https://github.com/Laravel-Backpack/CRUD/issues/2761#issuecomment-648270255_

**Comment by chivomd** [comment]
Thanks for separating this bug. I have tested the solution mentioned in #2967. Changing the initialization in repeatable from _container_ to _new_field_group_ seems to be working.

**Comment by tabacitu** [comment]
Fixed by merging https://github.com/Laravel-Backpack/CRUD/pull/3052 - thanks a lot for the issue and feedback @chivomd !
