### ISSUE TITLE
Problem with relationship field with inline_create attribute

### ISSUE THREAD

**Issue by dauvray** [Laravel-Backpack/CRUD#3025]
# Bug report

### What I did

When i'm using the relationship field type, the ajax query don't load my items, when i set the inline_create attribute.
All is good when i remove the attribute

### What I expected to happen

The list item must load

### What happened

no result, no ajax query

### What I've already tried to fix it

the problem come from the file : crud/fields/relationship/fetch_or_create.blade.php

**line 113 : if i remove the class select2_field , everything works fine**

maybe a relation with : #2597

### PHP VERSION:
PHP 7.3.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jun 12 2020 07:48:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v7.19.0@67d6d9688122dcf6c449b74ddc873fc9934e81e6

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by ikkebra** [comment]
I have this same issue.

**Comment by pxpm** [comment]
Hey guys, thanks for report.

I don't think that a css class could be related with the field not working. In fact that class is present from the beggining and the field works as you can see in https://demo.backpackforlaravel.com/

Could you please provide field definition ? Any error message in console or laravel logs ?

I could not reproduce this, in fact we have some relationship fields with inline create working. 

I wait for more input from you guys.

Best,

**Comment by dauvray** [comment]
Ok, after some tests everythings works fine. you're right. It's a good job.
Removing the css class allows to keep a uniformity with the other fields in my case.

**Comment by pxpm** [comment]
If there is some other issue please feel free to open an issue request for that specific issue.

Thanks for letting us know that this is solved.

Wish you the best,
Pedro
