### ISSUE TITLE
[Bug] Multiple Select2_multiple, cannot use select all button

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#3028]
# Bug report

### What I did

I have 2 select2_multiple on same content, but when i click on select all button (I have 'select_all' => true on both fields) this doesn't work as expected

### What I expected to happen

Select all should be select all items

### What happened

the second Select all button selects a number of items equal to the count of the elements of the first select2_multiple

### What I've already tried to fix it

No

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.19.1@4f373c373915ec828e3374029919a6fe946ed6d9

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by pxpm** [comment]
Hello @bedoz 

Thanks for raising the issue. I could easily confirm and pushed a fix for it in #3042 .

Let's move any further conversation about it into the PR thread. 

Wish you the best,
Pedro
