### ISSUE TITLE
[Bug] Readonly attibute not working for relationship (select2)

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#3029]
# Bug report
I have two fields (text and relationship) on a form and applying readonly works only on text. 

![image](https://user-images.githubusercontent.com/10773464/87418914-375ebd00-c5f0-11ea-98d4-6ceff5dfbd9e.png)

### What I did

Applied readonly attribute to the relationship field.

### What I expected to happen
Both fields should have become readonly

### What happened
Only text turned readonly 

### What I've already tried to fix it
Making 'relationship' field disabled.  But the problem is during 'Edit' the validation is run against it as the value is not posted via form (PUT). 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.19.1@4f373c373915ec828e3374029919a6fe946ed6d9

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by pxpm** [comment]
Hello @srigurubyo 

From my understanding of this issue, the `<select>` tags does not have the read-only mode, it has indeed the disabled but prevents the value from beeing sent. 

What you could do is to use `sometimes` in your laravel validation rule. So if the input is present it is validated, if not, it is not validated and the validation does not fail. https://laravel.com/docs/7.x/validation#conditionally-adding-rules

I don't think this is a Backpack bug. 

Best,
Pedro
