### ISSUE TITLE
Remove Actions Column

### ISSUE THREAD

**Issue by skatika** [Laravel-Backpack/CRUD#303]
I'm trying to remove the Actions Column with the following code but it doesn't seem to have any affect.

`$this->crud->removeColumn('action');`

**Comment by tabacitu** [comment]
Hmm... Do you have ajax datatables enabled?
```$this->crud->enableAjaxTable(); ```

**Comment by skatika** [comment]
That gives me an error
`DataTables warning: table id=crudTable - Ajax error.`

I have been able to remove any custom columns with the removeColumn method but just not the action column

**Comment by skatika** [comment]
It seems the buttons preview and revisions are disabled by default. Even though they don't show in the actions column, they are still being passed to the front end.
Adding the following code to my controller removed the Actions column, as it checks the count of buttons as a check to display the column.

`            $this->crud->removeButton( 'preview' );
            $this->crud->removeButton( 'revisions' );`

**Comment by tabacitu** [comment]
Damn. You're right, @skatika , those buttons _are_ there even if they're hidden. I'll see how we can fix this for the future without breaking people's apps... Thank you.

**Comment by tabacitu** [comment]
Hmm... I think we have a pretty good workaround already, please use:
```php
$this->crud->removeAllButtons();
```

This will definitely remove them all, and the actions column. Cheers!

**Comment by skatika** [comment]
@tabacitu What if I want to remove the actions column but keep the Add button at the top?

**Comment by tabacitu** [comment]
@skatika ,

This should do it for you:

```php
$this->crud->removeButton( 'preview' );
$this->crud->removeButton( 'update' );
$this->crud->removeButton( 'revisions' );
$this->crud->removeButton( 'delete' );
```

Cheers!

**Comment by nhuebnereagle** [comment]
Thanks for posting this, fixed my need to remove them as well. It's not like I don't want the Actions column, I'm just using this specific page as a way to filter through a large set of data for "researching" - no actions can be done except filters.

**Comment by doncadavona** [comment]
Works for me:
`$this->crud->removeAllButtonsFromStack('line');`

**Comment by webboty** [comment]
How can a button be deleted based on a row value?
Like hide a delete button for elements that had been soft deleted (deleted_at column IS NOT NULL).

**Comment by tabacitu** [comment]
The easiest way to do that would be inside the blade file, if you ask me. You can just [publish the delete view file](https://backpackforlaravel.com/docs/4.1/crud-how-to#publish-a-column-field-filter-button-and-modify-it) and add that bit of logic on top.

If you only need it in one CRUD, you should also rename it to something else, so it's not used by all CRUDs, to do that, inside your controller:
```php
        $this->crud->operation(['list', 'show'], function () {
            $this->crud->deleteButton('delete');
            $this->crud->addButton('line', 'delete', 'view', 'path.to.your.custom.view', 'end');
        });
```

Hope it helps @webboty !

**Comment by masssoud** [comment]
is it way to reorder actions column and put it at first??

**Comment by tabacitu** [comment]
@masssoud there's no simple solution, no, it's not something Backpack supports by default. 

But it shouldn't be terribly difficult to do as a customization - you can overwrite the `search()` method in your CrudController, which returns the columns... and just switch the order there. So something like this:

```php

    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation { search as originalSearch };

    public function search() 
    {
         $columns = $this->originalSearch();

         // TODO: do what you want with the columns

         return $columns;
     }
```

If you need this in multiple CRUDs, you can create a Trait out of it, and use your CustomListOperation instead of the stock one...

Hope it helps!

**Comment by ivictor777** [comment]
Hello! Is there a way to remove not only the buttons, but also the Actions column?

**Comment by tabacitu** [comment]
If you remove all buttons, the actions column should disappear. See https://github.com/Laravel-Backpack/CRUD/issues/303#issuecomment-364672409
