### ISSUE TITLE
Checklist error with pluck

### ISSUE THREAD

**Issue by vamsi381** [Laravel-Backpack/CRUD#3035]
In my crud controller, There is one field called "roles (Multiple checklist)", While before saving the roles, I am converting array into string like 1,2,3 using implode. Ex: CrudController setUp() method

```
$options = [
                'name' => 'roles',
                'label' => 'Roles',
                'type' => 'checklist',
                'entity' => 'roles',
                'attribute' => 'name',
                'model' => "Backpack\PermissionManager\app\Models\Role",
            ];
        $this->crud->addField($options);
```
In Store method,

```
public function store(StoreRequest $request)
    {
        $sel_roles = $request->input("roles");

        $roles = !empty($sel_roles) ? implode(",",$sel_roles) : "";

        $request->request->set("roles",$roles);       

        //dd($request);
        return parent::storeCrud($request);
    }

```
Edit Method looks like this,

```
public function edit($id) {

        $this->crud->hasAccessOrFail('update');
        // get the info for that entry
         $this->data['entry']= $this->crud->getEntry($id);
         $options = [
            'name' => 'roles',
            'label' => 'Roles',
            'type' => 'checklist',
            'entity' => 'roles',
            'attribute' => 'name',
            'model' => "Backpack\PermissionManager\app\Models\Role",
        
        ];
    
        $this->crud->addField($options);

         $this->data['crud'] = $this->crud;
         $this->data['fields'] = $this->crud->getUpdateFields($id);

         $this->data['id'] = $id;

         return view('crud::edit', $this->data);

    }
```
If am trying to access, Edit page, I am getting below error,

**ErrorException in line 15: Call to a member function pluck() on string (View: /var/www/html/app/vendor/backpack/crud/src/resources/views/fields/checklist.blade.php)**

**Comment by pxpm** [comment]
Hello @vamsi381 

Sorry but i cannot follow your issue. 

What's the output of `php artisan backpack:version` ? 

Line 15 does not have any pluck, my guess is that is related with line 17 where we have:

```php
 if ($field['value'] instanceof Illuminate\Database\Eloquent\Collection) {
    $field['value'] = $field['value']->pluck($key_attribute)->toArray();
  }
```

So that pluck will only be called if the field value is a collection, if it's a string we don't call. 

My guess is that you are using an outdated version, that might have that bug layin' around. 

Let me know.

Pedro

**Comment by vamsi381** [comment]
Hi @pxpm ,

Thank you very much.
I am sending the value in the collection format, Now the checkbox lists are displaying again in the edit page.

Thank you.

**Comment by pxpm** [comment]
Nice to know @vamsi381 

Best,
Pedro
