### ISSUE TITLE
[Bug] InlineCreate operation does not work for Models having $appends attribute

### ISSUE THREAD

**Issue by srigurubyo** [Laravel-Backpack/CRUD#3036]
# Bug report

The InlineCreate operation fails to load the page when the (to be inline created) model has $appends attribute definition.

![image](https://user-images.githubusercontent.com/10773464/87694356-b77d5200-c7ab-11ea-9cf4-a7d40d4e2972.png)

### What I've already tried to fix it

Removed the $appends clause

### PHP VERSION:
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.19.1@4f373c373915ec828e3374029919a6fe946ed6d9

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by pxpm** [comment]
Hello @srigurubyo why would inline create fail for models that have `$appends` ?

What's the error you get ? I mean, the error stack trace. 

Some field in the inline create is in `$appends` ? It should be in `$fillable`. 

I'v just added in demo, Icon Model: 

```php
    protected $fillable = ['name', 'icon'];
    // protected $hidden = [];
    // protected $dates = [];
    protected $appends = ['special_name'];

    public function identifiableName()
    {
        return 'icon';
    }

    public function getSpecialNameAttribute() {
        return $this->name;
    }
```

And in MonsterCrud there is an inline create for icon, and I am able to use it. 

When you add something to `$appends`, laravel expect you to create an acessor for it.

I am going to close this as I think this might be bad implementation. I might be wrong, if that is the case please re-open. 

Wish you the best,
Pedro
