### ISSUE TITLE
[Feature Request] Tabs in the show view

### ISSUE THREAD

**Issue by soufiene-slimi** [Laravel-Backpack/CRUD#3037]
# Feature Request

### What's the feature you think Backpack should have?

Tabs like the create/edit views

### Have you already implemented a prototype solution, for your own project?

Not yet

### Do you see this as a core feature or an add-on?

Core feature

**Comment by tabacitu** [comment]
Hmm... this might be a good idea @soufiene-slimi - thanks! For large CRUDs one single page is sometimes overwhelming. I'll leave this open to see if more people agree to it.

Cheers!

**Comment by ziming** [comment]
More easy ways to customize the show page is a plus for me :).
