### ISSUE TITLE
[Bug] Checkbox field type does not show custom options labels

### ISSUE THREAD

**Issue by nbolender** [Laravel-Backpack/CRUD#3039]
# Bug report

### What I did

Added a boolean field, with custom labels as specified in the docs:

```
[
    'name'  => 'name',
    'label' => 'Status',
    'type'  => 'boolean',
    // optionally override the Yes/No texts
    'options' => [0 => 'Active', 1 => 'Inactive']
],
```

### What I expected to happen

Radio buttons or a select box are shown with Active and Inactive

### What happened

Only a checkbox is shown with the label 'Status'. Actually, this field is just a straight up include of the checkbox field.

### PHP VERSION:
PHP 7.3.18 (cli) (built: May 14 2020 10:54:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.18, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.18, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.20.0@682ea946bc136aa686d5a64940ab3d4a24d5a613

### BACKPACK VERSION:
4.1.14@f4a6ad91f2aa3760ffe963c5cd87d2b533803323

**Comment by tabacitu** [comment]
@nbolender there must be some misunderstanding here - the `boolean` field type is just an alias for [the `checkbox` field type](https://backpackforlaravel.com/docs/4.1/crud-fields#checkbox). And its definition does NOT include `options`, it's just a simple checkbox with a label next to it.

You must looking for the [`select_from_array` field type](https://backpackforlaravel.com/docs/4.1/crud-fields#select_from_array) or the [`radio` field type](https://backpackforlaravel.com/docs/4.1/crud-fields#radio)? Those indeed have an `options` attribute.

Cheers!
