### ISSUE TITLE
Reordering of non-nested tables

### ISSUE THREAD

**Issue by alashow** [Laravel-Backpack/CRUD#304]
Hello.

In docs I see, 
"If your model has the proper fields (parent_id, lft, rgt, depth), you can use the built-in reorder" and "specify 1 for no nesting, just reordering (MAX_TREE_LEVEL)."

What if don't have parent_id, lft, right, depth fields? If I just want the sorting. Will I still need to add these fields to my table?

I want something like https://github.com/spatie/eloquent-sortable

Does it already work without all fields? (only 'depth')

Thank you.

**Comment by tabacitu** [comment]
This will be a bummer for you, but no, there's currently no "reordering only" option, without nesting. You'll still need to have all fields in your db (parent_id, lft, right, depth) and use 1 as MAX_TREE_LEVEL. It will only do sorting then (no nesting) - so it's the result you want on the front-end, but you'll have unnecessary table columns, yes.

Sorry.

**Comment by floristenhove** [comment]
Was looking for this as well. Are there any plans on implementing something like this? I can work with the current solution but would be really awesome. Cheers!

**Comment by tabacitu** [comment]
@floristenhove yes, we'll probably implement some way of disabling the nesting in the future, and only need one column "order".

**Comment by pavoltanuska** [comment]
@tabacitu I took a look at this and came up with a possible solution, I'm just not sure if there aren't any surprises.

I noticed, that the items in request are sent via an array, keyed by it's order as it appears in the UI. From that, it seems straightforward:


1. Add an `updateFlatOrder()` method to `PanelTraits/Reorder.php` (very similar to the `updateTreeOrder()` one)
```
// PanelTraits\Reorder->updateFlatOrder()

$count = 0;
        
foreach ($request as $key => $entry) {
    if ($entry['item_id'] != '' && $entry['item_id'] != null) {
        $item = $this->model->find($entry['item_id']);
        $item->lft = $key;
        $item->save();
        $count++;
    }
}

return $count;
```
Note: I'm using `lft` here to be backwards compatible with the current solution, but it could be changed to `order` if necessary.

2. Change the if statement in `saveReorder()` method in `app/Http/Controllers/CrudFeatures/Reorder.php` slightly:
```
if (count($all_entries)) {
    if ($this->crud->reorder_max_level == 1) {
        $count = $this->crud->updateFlatOrder($all_entries);
    } else {
        $count = $this->crud->updateTreeOrder($all_entries);
    }
} else {
    return false;
}
```

And that should be it. I'm also open to making a PR for this, if you consider this to be a viable solution :)

**Comment by tabacitu** [comment]
Hi @pavoltanuska ,

Hmm... That sounds like an elegant solution. So basically we would have two functionalities:
- reorder (old one)
- flat reorder (the new one)

And the ```saveReorder()``` method would work for both, depending on what you've "enabled", I presume? ```$this->crud->enableReorder()``` or ```$this->crud->enableFlatReorder()```?

**Comment by pavoltanuska** [comment]
As for the 2 functionalities - yes - separate method for `updateFlatOrder()`

As for the "enabling", I see more options, but it'd be best to stay consistent with how things are (or will be) done in general.

1. `enableReorder() `and `enableFlatReorder()`, like you said
2. `enableReorder()` and `enableReorder()->flat()`
3. `enableReorder($label = 'name', $max_level = 1, $flat = false)`
4. The "implicit" decision based on `$this->crud->reorder_max_level` i.e. `if($this->crud->reorder_max_level == 1) { updateFlatOrder() } else { updateOrder() }`

I guess I'll let you guys decide :)

**Comment by alashow** [comment]
What about simple reordering with arrow buttons? Down/Up arrow button actions in the table. When up button clicked, increment row's `order` field by one (and when Down button clicked, decrease by one).

**Comment by pavoltanuska** [comment]
@alashow with flat order, that should be quite simple. With leveled ordering, it's a little bit tougher nut to crack (correctly and UX friendly).

Another thing (it's just the semantics), but increment/decrement doesn't suffice here, you should swap the `order` values with the higher or lower item. But that should still be easy enough.

**Comment by adriandmitroca** [comment]
Hey guys,

Any update on this one? Would be really handy to have simple reordering.

**Comment by emperorjm** [comment]
I took the approach of extending the CrudController and creating a new Trait that override the "saveReorder()" function and have the new updateFlatOrder() function above. I did this because I didn't want to edit the package directly which would get overwritten when updates are installed.

I am using a "sort_order" field within my database tables and so I hardcoded that field in the "updateFlatOrder()" function but it would be better to add a new field to the request object using "$request->request->set('sort_order_field', 'sort_order');" and then use that field within the function to make it more dynamic.

**Controller:**
`namespace App\Http\Controllers;

// Adrian (): Extend the Backpack CRUDController
use Backpack\CRUD\app\Http\Controllers\CrudController as BaseController;

use App\Http\Traits\CRUD\Reorder;

class Controller extends BaseController
{
    use Reorder;
}`


**Trait:**
`namespace App\Http\Traits\CRUD;

use Doctrine\Common\Util\Debug;

trait Reorder
{
    /*
    |--------------------------------------------------------------------------
    |                                   REORDER
    |--------------------------------------------------------------------------
    */

    /**
     *
     * @param  [Request] The entire request from the NestedSortable AJAX Call.
     *
     * @return [integer] The number of items whose position in the tree has been changed.
     */
    public function updateFlatOrder($request)
    {
        $count = 0;

        foreach ($request as $key => $entry) {
            if ($entry['item_id'] != '' && $entry['item_id'] != null) {
                // Adrian (): Changed this to call the model property accessible by the crud property
                $item = $this->crud->model->find($entry['item_id']);
                // Adrian (): The soirting will be done on the field "sort_order"
                $item->sort_order = $key;
                $item->save();
                $count++;
            }
        }

        return $count;
    }

    /**
     * Save the new order, using the Nested Set pattern.
     *
     * Database columns needed: id, parent_id, lft, rgt, depth, name/title
     *
     * @return
     */
    public function saveReorder()
    {
        $this->crud->hasAccessOrFail('reorder');

        $all_entries = \Request::input('tree');

        /**if (count($all_entries)) {
        $count = $this->crud->updateTreeOrder($all_entries);
        } else {
        return false;
        }**/

        if (count($all_entries)) {
            if ($this->crud->reorder_max_level == 1) {
                // Adrian (): Changed this to call the function within this trait
                $count = $this->updateFlatOrder($all_entries);
            } else {
                $count = $this->crud->updateTreeOrder($all_entries);
            }
        } else {
            return false;
        }

        return 'success for '.$count.' items';
    }
}`
