### ISSUE TITLE
[Bug] Cant assign middleware to routes

### ISSUE THREAD

**Issue by OwenMelbz** [Laravel-Backpack/CRUD#305]
Due to the way the `CRUD::resource` works it doesn't allow the use of middleware (and possibly other things).

Think this should be addressed before any LTS version is launched :)

Probably need to rethink the router - as laravel 5.4 comes with a new fluent route syntax, we might be able to benefit from this

**Comment by tabacitu** [comment]
Hmm... What do you mean? Wouldn't this count as using middleware?

```php
// Admin Interface Routes
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function()
{
	CRUD::resource('test', 'TestCrudController');
});
```

You mean not placing the middleware on a group, but directly on the CRUD::resource? Yeah, that would be awesome and I believe [Laravel 5.4 will make it so easy for us](https://laravel-news.com/route-improvements) :-) If this is what you meant, I wouldn't go as far as calling it a bug :-) Enhancement might be a better name. Though I do agree this should be included in the LTS.

**Comment by OwenMelbz** [comment]
Yeah I guess I could create a custom group for a singular route, however that would seem odd!

Well typically you could assign a middleware on a controller

```
public function __construct()
{
        $this->middleware('admin');
}
```

but as we're high-jacking the construct for the custom middleware, you cant do that, which means you cant do it like that, and because we're using a custom route mechanism, you cant do that either! meaning you could only do it at route group level!

----

As a way to solve this issue, do you think it would be better to have a single group? or just paste

```
        $user = \Auth::user();
        if (!$user || ($user && !$user->is_admin) || ($user && !$user->enabled)) {
            return abort(401);
        }
```

at the top of each function...im leaning towards the lonely route group!

**Comment by tabacitu** [comment]
Lonely route group, definitely. We'll make this nice and clear when L 5.4 comes around.

**Comment by scottjs** [comment]
Hey,

I'm just starting out with Laravel Backpack, I'm extremely impressed and enjoying it so far!

I'm facing this exact same issue, is there any reason why I can't use parent::__construct() to deal with the hijacked constructor issue mentioned by OP?

```
public function __construct() {
	$this->middleware('permissions:manage-tags');
	parent::__construct();
}

public function setup() {
	$this->crud->setModel("App\\Tag");
	$this->crud->setRoute("admin/tag");
	$this->crud->setEntityNameStrings('tag', 'tags');

	$this->crud->setColumns(['name']);
	$this->crud->addField([
		'name' => 'name',
		'label' => "Tag name"
	]);
}
```

It seems to work, but I'm not sure if there will be side-effects.

**Comment by tabacitu** [comment]
Hi @scottjs ,

As far as I know, you can't use ```$this->middleware()``` inside the ```__construct()``` in Laravel 5.4+ anymore, because the middleware now needs to be loaded BEFORE  ```__construct()```. So I think the best way to achieve this would be with a lonely route group, as Owen mentioned.

Hope it helps. Cheers!
