### ISSUE TITLE
[4.1][Bug] Image field default_class 'hide' prevents upload button from working

### ISSUE THREAD

**Issue by MarcosBL** [Laravel-Backpack/CRUD#3057]
# Bug report

### What I did

Clic the Select button to upload a new image

### What I expected to happen

Select file dialog opening

### What happened

Nothing at all

### What I've already tried to fix it

If I change the 'hide' value to 'visible', button starts working again, so I had to change my code to **'class'      => 'visible'**:

````php
        $this->crud->addField([
        	'label'        => "Logotipo del evento",
        	'name'         => "logo",
        	'type'         => 'image',
        	'upload'       => true,
        	'crop'         => true,
        	'aspect_ratio' => 0,
        	'attributes'	=> [
        		'class'      => 'visible'
        	],
        ]);
````
Tested in 

* Chrome Linux / Versión 83.0.4103.116 (Build oficial) (64 bits)
* Firefox 78.0.2 (64-bit)

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.20-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jul  9 2020 16:34:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.20-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.13.0@6fa69bfbd57744a5bbec5538ce483919b3fd625f

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

BTW, hi all ! Long time no see ! :D

**Comment by tabacitu** [comment]
Hi @MarcosBL - long time no see indeed! Eager to see what you think about 4.1.x 😉 I think Backpack has been maturing nicely, finally reached a "feature complete" status, but then again I'm too close to the subject to know if I'm right or wrong 🙄 

I couldn't get the same problem, the Select button worked fine for me. Here's what I did:
![2020-07-22 09 44 25](https://user-images.githubusercontent.com/1032474/88143710-62ed3300-cc00-11ea-8ba1-5e99f7e9c937.gif)

The addField code is:
```php
       [ // image
            'label'        => 'Image - includes cropping',
            'name'         => 'image',
            'type'         => 'image',
            'upload'       => true,
            'crop'         => true, // set to true to allow cropping, false to disable
            'aspect_ratio' => 1, // ommit or set to 0 to allow any aspect ratio
            'tab' => 'Uploads',
        ]
```

The only difference I'm seeing between your setup and mine is the fact that you're testing from Linux, but that really shouldn't be a problem... Pff... I bet this'll be a tricky one to track down. Let's give it a go 😄 

1) Have you published and changed the `image` field in any other way? Maybe this project is upgraded from 3.x or 4.0?
2) Does this happen to you inside [the demo](https://github.com/laravel-backpack/demo), inside the MonsterCRUD, too?

Cheers!

**Comment by MarcosBL** [comment]
## First of all

I **fXckXng love** Backpack, even if I hadn't the time to contribute more (2 small child now competing for the available time), I  have been evangelizing last 3 years like crazy !

It's a superb product, and I really hope you can do a living of it, **it's more than well deserved**. The fact that despite Laravel itself having it's own admin package, we still prefer Backpack features talks for itself :smiley: 

## Ok, I think I tracked it down.

In my CSS I have a rule for hidden elements:

````css
.hide { display: none !important; }
````

This conflicts with the Image element CSS:

````css
.hide {
    display: none;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    ....
    display: block;
}
````

In the element, the `.hide` class is applied if you don't specify a `default_class` attribute, but as it doesn't have an `!important` attribute, it is overwritten by the `display: block;`  of the more specific `.btn-file input[type=file]`, so in fact, **it was never applied in the image field**

Now, as my rule have an `!important` attribute, it is applied to the field, **and then it doesn't receive the click event**; that's why it works in the Monsters demo and not in my project: as soon as you use a `!important` rule in a `.hide` class, it makes the field invisible, and so, not receiving events, not in Chrome nor Firefox.

## A simple fix

As the class itself doesn't seem to do anything (it is never really applied by default because of the `display:block` later), and `.hide` is almost a global CSS rule in every CSS framework out there, a solution could be to remove the `.hide' from the default attributes and CSS altogether: it is not being used, because of specify field rules, and conflicts with CSS frameworks.

<img src="https://i.imgur.com/lxFLpaL.png">

Fix applied, confirmed working fine in both Chrome and Firefox

<img src="https://i.imgur.com/MzVTwzx.png">

**Comment by tabacitu** [comment]
> I fXckXng love Backpack, even if I hadn't the time to contribute more (2 small child now competing for the available time), I have been evangelizing last 3 years like crazy !

Haha - glad to hear that! Both the love for Backpack, and the 2 small children, congrats!

> As the class itself doesn't seem to do anything (it is never really applied by default because of the display:block later), and .hide is almost a global CSS rule in every CSS framework out there, a solution could be to remove the `.hide' from the default attributes and CSS altogether: it is not being used, because of specify field rules, and conflicts with CSS frameworks.

Ok, I think I understand now, thanks for drilling down on the issue. I've put together PR https://github.com/Laravel-Backpack/CRUD/pull/3070 - please let me know what you think about it. Personally I don't see this breaking anything, it's just a clean-up PR with your suggestion.

Let's close this issue then, in favour of PR #3070 . Hopefully after review we'll get to close that pretty soon too.

Cheers!
