### ISSUE TITLE
[Bug] model_function Column with enableAjaxTable

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#306]
Hi 
in enableAjaxTable mode if we have model_function Column ,  it doesn't work and the data of table not show.

**Comment by OwenMelbz** [comment]
If you get an alert with an error, can you copy/paste the AJAX call error, this will be a 500 internal server error style in your developer console.

We'd need to have that to determine if there is an error

**Comment by M0H3N** [comment]
yes this is the error :  

QueryException in Connection.php line 764:
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'field list' (SQL: select `` as ``, `title` as `title`, `content` as `content`, `category_id` as `category_id`, `author_id` as `author_id`, `publish_status` as `publish_status`, `comment_status` as `comment_status`, `view_count` as `view_count`, `id` as `id` from `posts` where `posts`.`deleted_at` is null limit 25 offset 0)

**Comment by OwenMelbz** [comment]
Ha pretty funny, we had the exact same issue this morning :)

@tabacitu There is a problem with relational fields I think when using ajax and datatables.

Imagine the following scheme

```
books: id, name
categories: id, name
book_categories: book_id, category_id
```

When using something like the "select" column type in a similar fashion to

```
$this->crud->addColumn([
    'name' => 'category_id',
    'label' => 'Category',
    'model' => App\Category:class
]);
```

The query for the `/search` tries to add the `select category_id as category_id` into the query to return the results.

As this column is in the pivot table it fails.

I'm not really familiar with that area of the code so not sure best way to fix it.

However I know a "work around" for it - as long as you define the `name` property on the addColumn call as an existing column, it wont error. e.g

```
$this->crud->addColumn([
    'name' => 'id',
    'label' => 'Category',
    'model' => App\Category:class
]);
```

This prevents the error and seems to work, however its obviously not a proper fix

**Comment by OwenMelbz** [comment]
Consolidating the issue into the other topic
