### ISSUE TITLE
Add variable to resource route 

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#307]
how do I add a variable to resource route with no problem in project . 
for  example I have  CRUD::resource('{termId}/category', 'Admin\CategoryCrudController'  in my project but my app doesn't work correctly .

**Comment by OwenMelbz** [comment]
You cant, `CRUD::resource`is not designed to work like that.

You'll need to define your own Route::resource/get/post etc to change the default route functionality

**Comment by M0H3N** [comment]
But I want to use the variable in my crudController

**Comment by OwenMelbz** [comment]
Yes you said that, however the `CRUD::resource` function is NOT designed to do that, it assumes its a url slug - which will match the slug defined in the controller.

So it will be custom functionality you'll need to figure out.

You'll need to potentially create your own route NOT using `CRUD::resource` using native laravel.

You might also need to have a custom methods in your controller which is explained https://laravel.com/docs/5.3/controllers#resource-controllers

Your best bet is to NOT try change backpack/crud as its not designed for that.

Try using query strings instead - these can be read via your PHP much more easily.

Then if you're worried about the url looking messy, either use mod_rewrite to clean them up, or decide if a custom url is really worth the extra cost to your project

**Comment by M0H3N** [comment]
thanks .. I think that  I should use  query strings .

**Comment by tabacitu** [comment]
Hi @M0H3N ,

I think what happens is that for some routes your termID gets picked up instead of the regular ID.  So a fix for you would be to have this in your EntityCrudController:

```php
    public function show($id)
    {
        return parent::show($this->request->id);
    }

    public function listRevisions($id)
    {
        return parent::listRevisions($this->request->id);
    }

    public function restoreRevision($id)
    {
        return parent::restoreRevision($this->request->id);
    }

    public function showDetailsRow($id)
    {
        return parent::showDetailsRow($this->request->id);
    }
```

**Comment by tabacitu** [comment]
@OwenMelbz , do you see any reason why we shouldn't use ```$this->request->id``` instead of ```$id``` in the package? Might save people some headache...

**Comment by jrpub** [comment]
Any news on this? 

I think it would be a good feature to be able to customize Crud::resource with other parameters.
