### ISSUE TITLE
[Bug] input type text for boolean column

### ISSUE THREAD

**Issue by adal6a** [Laravel-Backpack/CRUD#3072]
# Bug report

### What I did

Add column type boolean into table

### What I expected to happen

Input type checkbox

### What happened

Showing input type text

### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )

### LARAVEL VERSION:
v6.18.14@503d1511d6792b0b8d0a4bfed47f7c2f29634e1c

### BACKPACK VERSION:
4.0.61@1977e0cc52fa7cf9547eaeadf03f5cd88402b574

**Comment by pxpm** [comment]
If you want a checkbox better use https://backpackforlaravel.com/docs/4.1/crud-columns#check
