### ISSUE TITLE
[BUG] Alerts does not goes along with persistent table redirection. 

### ISSUE THREAD

**Issue by maganius** [Laravel-Backpack/CRUD#3075]
When `persistentTable` is enabled the `Alert flash` not work, when I disable `persistentTable` the `Alert` work as excepected.

I use this alert to display a message.

`Alert::add('success', 'message here')->flash();`

The alert is setted in the controller and redirected to list page.

Laravel version: 7
Backpack crud version: 4.1

-----------------------------------------------------

I think its not showing because the persistent is redirecting the page, check image.

https://i.imgur.com/aqTBSr5.png

**Comment by pxpm** [comment]
Hello @maganius thanks for the report.

I think I get it now after some research about it.

Indeed the message goes to the first request, but then persistent table redirects to the intended and final url and does not carry the alerts with it. 

I think this is indeed a bug. I just submited PR: #3079 to address this issue. 

If you can please give it a try and let me know if it's working on you side. 

Best,
Pedro

**Comment by maganius** [comment]
@pxpm perfect the PR works as expected
