### ISSUE TITLE
[Bug]  $this->crud->removeButton('Edit') is not working in version 3.4

### ISSUE THREAD

**Issue by mosam** [Laravel-Backpack/CRUD#3083]
# Bug report

### What I did

??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
@mosam I am sorry but versions 3.4 is somehow outdated. We had 3.5, 3.6, 4.0.

We are currently on v4.1 with alot of new features it might worth to check it out. 

I don't think I can be much help here, try debugging the error message. 

Best,
Pedro
