### ISSUE TITLE
[4.X] CORS prevents video field from working

### ISSUE THREAD

**Issue by Alexrubl** [Laravel-Backpack/CRUD#3084]
Today did not work field video, bug cors, google something changed again
jsonp does not help

**Comment by czerniachowicz** [comment]
I'm seeing this too, in a preproduction site I'm putting together. I swear this used to work but now upon entering a URL into the video field I get the following error in the console:

`Access to XMLHttpRequest at 'https://www.googleapis.com/youtube/v3/videos?id=NrBkg2Dg-gQ&key=XXXXXX&part=snippet' from origin 'https://YYYYYYYY.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by pxpm** [comment]
@Alexrubl and @czerniachowicz thanks for the report.

I could confirm the issue. It's not something that we changed in Backpack, it was browser implemented or youtube api implementation. 

I'v just submited PR: #3096 

If you guys have time it would help alot if you could test it and give your feedback. It will speedup the merging process alot. 

Best,
Pedro

**Comment by tabacitu** [comment]
Thanks a lot guys! Let's move the conversation to PR #3096 please - would love your input on it.

Cheers!
