### ISSUE TITLE
[Bug]? The select field relationship "hardcodes" the related model key to the value of the option

### ISSUE THREAD

**Issue by maxacarvalho** [Laravel-Backpack/CRUD#3086]
# Bug report

### What I did

Created a field type `select` which points to an external model but that relationship does not rely on the related model's key.  
For example, the Model `Schedule` relates to the Model `Status`, linked by the `Status->status` and **not** the `Status.id`.

### What I expected to happen

When I set the field's `name` property to `status` I expect the `<option value=""></option>` to be the `Status->status`.

### What happened

The `<option value=""></option>` is being set to `Status->id` (`Status->getKey()`).

### What I've already tried to fix it

Checked the `vendor/backpack/crud/src/resources/views/crud/fields/select.blade.php`, no way to fix apart from overwriting the template.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.6 (cli) (built: May 14 2020 10:02:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.15@6c751de946a9c8511dd32eb7bfa3ca6a568849f5
```

**Comment by tabacitu** [comment]
Hi @maxacarvalho - not sure what the problem here is and why you closed it, but just wanted to mention that for complicated relationships you can use a dot notation for the field name. For example you can do `tag.category.id` if there are relations from the current entity to Tag, from Tag to Category, which has an ID as primary key. Maybe it helps.

Cheers!

**Comment by maxacarvalho** [comment]
No worries @tabacitu 

I saw that what I was trying to do is not available at all.

I have a two models, related.  
- Model A has `id|slug|label`
- Model B has `id|model_a_slug|...`

So the relation points to the `slug` field, and not the `id`.  
In that situation, as far as I saw by checking the blade templates, the `select` field cannot help me, since if calls the Model A `getKey()` method, which will always return the `id` field.

I solved by
1. Extended the `select` field template.
2. Added an extra setting to the field configuration `relationship`.
3. I check if there's a `relationship` defined for the field and get that from the Model when available.

Example:

```php
// crud controller
...
            ->addField([
                'label' => 'Status',
                'type' => 'select',
                'name' => PatientScheduleModel::APPOINTMENT_STATUS,
                'relationship' => PatientScheduleStatusModel::STATUS,
                'entity' => 'status',
                'attribute' => PatientScheduleStatusModel::LABEL,
                'model' => PatientScheduleStatusModel::class,
                'attributes' => [
                    'readonly' => 'readonly',
                    'disabled' => 'disabled',
                ],
            ])
...
```

```html
<!-- resources/views/vendor/backpack/crud/fields/select.blade.php -->
<!-- select -->
@php
	$current_value = old(square_brackets_to_dots($field['name'])) ?? $field['value'] ?? $field['default'] ?? '';
    $entity_model = $crud->getRelationModel($field['entity'],  - 1);


    //if it's part of a relationship here we have the full related model, we want the key.
    if (is_object($current_value) && is_subclass_of(get_class($current_value), 'Illuminate\Database\Eloquent\Model') ) {
        $current_value = $current_value->getKey();
    }

    if (!isset($field['options'])) {
        $options = $field['model']::all();
    } else {
        $options = call_user_func($field['options'], $field['model']::query());
    }
@endphp

@include('crud::fields.inc.wrapper_start')

    <label>{!! $field['label'] !!}</label>
    @include('crud::fields.inc.translatable_icon')

    <select
        name="{{ $field['name'] }}"
        @include('crud::fields.inc.attributes')
        >

        @if ($entity_model::isColumnNullable($field['name']))
            <option value="">-</option>
        @endif

        @if (count($options))
            @foreach ($options as $connected_entity_entry)
                @if(isset($field['relationship']))
                    @if($current_value == $connected_entity_entry->{$field['relationship']})
                        <option value="{{ $connected_entity_entry->{$field['relationship']} }}" selected>{{ $connected_entity_entry->{$field['attribute']} }}</option>
                    @else
                        <option value="{{ $connected_entity_entry->{$field['relationship']} }}">{{ $connected_entity_entry->{$field['attribute']} }}</option>
                    @endif
                @else
                    @if($current_value == $connected_entity_entry->getKey())
                        <option value="{{ $connected_entity_entry->getKey() }}" selected>{{ $connected_entity_entry->{$field['attribute']} }}</option>
                    @else
                        <option value="{{ $connected_entity_entry->getKey() }}">{{ $connected_entity_entry->{$field['attribute']} }}</option>
                    @endif
                @endif
            @endforeach
        @endif
    </select>

    {{-- HINT --}}
    @if (isset($field['hint']))
        <p class="help-block">{!! $field['hint'] !!}</p>
    @endif

@include('crud::fields.inc.wrapper_end')
```

**Comment by pxpm** [comment]
I think it would be enough to define in the model the new primary key and
update the relations to use the new primary instead of Id.

Just ask Google: change model primary key laravel

A segunda, 3/08/2020, 23:48, Max Carvalho <notifications@github.com>
escreveu:

**Comment by maxacarvalho** [comment]
Hi @pxpm 

In this case there's no **new primary key**. The `slug` column is not the primary key, the `id` one is.  
The relationship is already set to point to the `slug` column, Laravel allows us to define whatever column we need when configuring relationships, even a subselect-based column, it does not require it to be the `id` of the column.

I thought about using the field's `name` attribute, but that does not work since when working with the normal and expected relationships you usually have `model_a.id = model_b.model_a_id`. So, as far as I see, the use of an extra attribute is inevitable.

**Comment by pxpm** [comment]
Thing is, if you have unique slug, and work them as if primary, why you use auto-incrementing ids ? 

Sorry for the question, there must be a reason that I am currently not aware of. 

Best,
pedro

**Comment by maxacarvalho** [comment]
In this particular case I could change it to be the primary key. The decision to use the slug was made later in the process.

But still, you might have to work with some complex scenarios where the `value` property of the `<option>` element cannot be the primary key.

I understood that's a peculiar situation and that's why I closed the ticket, but maybe, an optional attribute could be added to the field's definition to allow such flexibility.

**Comment by pxpm** [comment]
Something like `identifier => 'slug'` ... `$model_key => $field['identifier'] ?: $model->getKeyName()`; ??

Hum... @tabacitu ?

**Comment by maxacarvalho** [comment]
@pxpm looks to me like a quick and easy change, no chance of breaking anything unless someone is already doing that with the exact same array key.

**Comment by tabacitu** [comment]
@pxpm I'm open to it, if more people ask for it. But for now, since it's the first I hear about it in 4-5 years, I think it's best to keep it as a "could-have". Should be a simple enough change, but if we do it, we'd need to do it to ALL relationship fields, right? 😆
