### ISSUE TITLE
Support additional form types other than create/update

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/CRUD#309]
I think it would be helpful if we could support any number of form field sets other than just create/update.  The example I have come up with would be for Users - instead of just Create/Update, we could have Edit Profile/Change Password/Edit Permissions, etc, as separate field sets. Then in the table view, we could add buttons for each of these separately.  Each of those buttons would go to a different form that had its own unique list of fields.  This would help to reduce the size of the Edit User form, because Users often have a lot of options or other entities attached to them that can cause this form to get unwieldy.

This could also be helpful if certain users should have the ability to update aspects of an entity, but not others.  So they could access the update user profile view, but not the change user password or permissions views.  There could also be a situation where you have multiple workflows that create an entity - maybe for instance, a way to add an "Address" entity through Google Maps integration, or through manual entry.  These would be 2 different "create" buttons on the list view.

In order to do this, I think we would need to change the attributes on the CrudPanel from `$this->update_fields` and `$this->create_fields` to just `$this->fields['update']` and `$this->fields['create']` that way additional field sets could be added to, for instance, `$this->fields['password']`.  

The functionality of `$crud->addField()` could be updated easily, with a `null` argument or `"both"` still adding to the `create` and `update` lists by default.

To register the routes, we could add a parameter to `CRUD::resource` called `$customRoutes` that would take something like `['update' => ['password','permissions']` to indicate those routes should be registered.

We would need to map these routes to custom functions on the controller, or come up with a way to let the update function check if it is a custom route.  Then in the view, we simply replace all instances of `$crud->getFields('update', $entry->getKey()` with `$crud->getFields($fieldset, $entry->getKey()`.  Maybe we could add a function to run in the `setup()` function where we could map the name of a route to the field set name.  Something like `$this->addFieldSet('password', 'crud.user.password')` so then the `update()` function would load the fields for `password` if the name of the current route was `crud.user.password` which would have been registered in `CRUD::resource`.

Just an idea that I think could make the crud system more flexible!  If there is interest in this I would be happy to help in any way I can.

**Comment by jsiebach** [comment]
I wonder if this could be rolled into the solution for https://github.com/Laravel-Backpack/CRUD/issues/250

In the app I'm building, I record an entry in the table "leads" when someone fills out a webform.  Then I have a separate table for "lead_ratings" where users can add feedback to a lead.  This would be an easy way to define a second fieldset for rating a lead entity.  It doesn't solve the issue of how the `update()` function would work without mutators, but it could be a way to update those 1-1 entities without having to make a separate crud controller for the details table.

**Comment by lloy0076** [comment]
@jsiebach - at the moment I'm inclined to close this without a PR; please reopen if there is one.

I'm not sure if I'd muddle a 1-1 relationship PR with this suggestion although I agree that a person working on it might see the right code to be able to make a separate PR.

(On the basis that PRs are easier to merge/test with just one "major" fix at once).
