### ISSUE TITLE
[Bug] Filters not working as it does not find views

### ISSUE THREAD

**Issue by iamraju** [Laravel-Backpack/CRUD#3093]
# Bug report
Filters are not working.
### What I did
I did upgraded from 4.0 to 4.1, I tried all the steps mentioned in the documentation and tried to visit my listing page (ListOperation). I have couple fields to be available to search/filter.

### What I expected to happen
I had expected to work the filters as it is working with 4.0.

### What happened
In ListOperation (Listing page), I found the following error message:

```
InvalidArgumentException
View [text] not found. (View: resources/views/vendor/backpack/crud/inc/filters_navbar.blade.php)

```

### What I've already tried to fix it

When I tried to look at file filters_navbar.blade.php, there is a loop:

```php
@foreach ($crud->filters() as $filter)
    @include($filter->view)
@endforeach
```
Here `$filter->view` is returning only view name i.e. `text`, `select2`, etc, rather  it expects something like `crud:filters.text`. I found the Trait Filters has been modified a lot and I did not find extra classes in it.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
```
PHP 7.4.8 (cli) (built: Jul 13 2020 16:46:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.0.61@1977e0cc52fa7cf9547eaeadf03f5cd88402b574
```

Not sure what I missed to perform.

**Comment by pxpm** [comment]
Hello @iamraju 

Actually the code for getting the filters is:

https://github.com/Laravel-Backpack/CRUD/blob/15e921d41aa15ceb5757a42516490d8a75ba37b9/src/resources/views/crud/inc/filters_navbar.blade.php#L12

```php
    			@foreach ($crud->filters() as $filter)
    				@include($filter->getViewWithNamespace())
    			@endforeach
```

My guess is that you have that file published and backpack is picking the one you override in resources instead of the one in the package. 

It could be a cache problem `php artisan cache:clear` or some composer issue. Try `composer dump-autoload`.

I don't think this is a bug, so I am going to close this. If you still feel this is a bug, please re-open.

Best,
Pedro

**Comment by iamraju** [comment]
Hi There,

Thanks for taking care of the issue I posted.

Yes, later I found that the code is changed but strange part is; even when published new views, is there a way to re-publish all the view files ? I see a command `backpack:publish <subpath>` for publishing one particular view though.

**Comment by pxpm** [comment]
@iamraju There is no command to publish all the the Backpack view files. I don't think publishing ALL Bacpack views is a good pratice. I think publishing only the ones you are going to change makes more sense.

Best,
Pedro

**Comment by iamraju** [comment]
@pxpm I do totally agree in general it is not good to publish all but I am not sure what files are/were modified and hence I just wanted to republish all.

Now the filter fields problem resolved, it works but now buttons giving trouble. Like I cannot see button to Create New model in the listing page. I tried re-publishing the `crud/inc/button_stack` file but that did not help.

By the way, one small correction you guys need to make is; the example in arguments <subpath> of the command `backpack:publish` says `fields/text` but that did not help in case of `inc/button_stack` instead I had to do `crud/inc/button_stack`

Thank you again for responding.

**Comment by pxpm** [comment]
@iamraju if you are not doing customization in the files you could just delete them from your resources folder and backpack will pick the ones in the package. It's kind of the same of publishing all files and overwrite the changes so ... 

About the publishing you should look at backpack folder structure and give the appropriate path to the file you want to publish. `fields/text` is just an example for the text field.

Best,
Pedro

**Comment by iamraju** [comment]
Thanks @pxpm for continuous reply !

But even when I deleted all the published files/folders, I cannot see buttons, not sure where and what happened. I am exploring myself the codebase but if you have any direction to point to, that would save my time !

**Comment by pxpm** [comment]
My guess then is that you need to re-publish backpack assets and clear caches.

Check step 13 of upgrade guide: https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-13

Then clear your caches: `php artisan view:clear`

Best,
Pedro

**Comment by iamraju** [comment]
That did not help either. I tried that running the commands in step 13.

Actually I tried `dd($this->crud->buttons());` in `setup()` function of a controller lets say `EmployeesCrudController` then it returns :
```
Illuminate\Support\Collection {#2343 ▼
  #items: []
}
```

So it should be something in the framework itself or another doubt permission stuffs on which I am yet to check in details.

By the way, this is happening only in my upgraded project (4.0 to 4.1), but it is working in fresh/new installation.
