### ISSUE TITLE
[Bug] web_middleware list causes errors

### ISSUE THREAD

**Issue by hirakujira** [Laravel-Backpack/CRUD#3094]
# Bug report

### What I did

I followed the instruction in: 

https://github.com/Laravel-Backpack/CRUD/blob/91a8093ad1e55ad329d74994eaa2ed943fb0ec6a/src/config/backpack/base.php#L181-L189

I commented `'web_middleware' => 'web',` and use the list below it

### What I expected to happen

Backpack load the middlewares in the list

### What happened

It shows `Illegal offset type in isset or empty` error.

### What I've already tried to fix it

I think it's because when Backpack loads middleware

https://github.com/Laravel-Backpack/CRUD/blob/91a8093ad1e55ad329d74994eaa2ed943fb0ec6a/src/routes/backpack/custom.php#L9-L14

If I use custom `web_middleware` list, the middleware would be like this:

```
'middleware' => [
        [
             \App\Http\Middleware\EncryptCookies::class,
             \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
             \Illuminate\Session\Middleware\StartSession::class,
             \Illuminate\View\Middleware\ShareErrorsFromSession::class,
             \App\Http\Middleware\VerifyCsrfToken::class,
        ],
        config('backpack.base.middleware_key', 'admin'),
    ],
```

As you can see, it's an array in another array, which causes this bug.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 17 2020 12:02:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.15@6c751de946a9c8511dd32eb7bfa3ca6a568849f5

**Comment by pxpm** [comment]
Hi @hirakujira 

I think you have an outdated config file.

The current config files goes like this: 

https://github.com/Laravel-Backpack/CRUD/blob/master/src/config/backpack/base.php

```php
    // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of clases
    'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        // \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],

    // Alias for that middleware
    'middleware_key' => 'admin',
    // Note: It's recommended to use the backpack_middleware() helper everywhere, which pulls this key for you.
```
I don't think there is a bug here. If I am wrong please re-open.

Best,
Pedro

**Comment by hirakujira** [comment]
Thanks for your explanation, @pxpm !

However when I check the code, I still feel confused.

In [https://github.com/Laravel-Backpack/CRUD/blob/master/src/config/backpack/base.php](https://github.com/Laravel-Backpack/CRUD/blob/master/src/config/backpack/base.php), there are two middleware groups, one is `admin`, and another one is `web`. 

As you can see, in [https://github.com/Laravel-Backpack/CRUD/blob/master/src/routes/backpack/custom.php](https://github.com/Laravel-Backpack/CRUD/blob/master/src/routes/backpack/custom.php
), the route loads both `web` and `admin` middleware groups.


So the problem is that your solution is for the `admin` middleware group, if I want to make a custom array for `web` middleware in `/config/backpack/base.php`, it would cause errors. And also, modifying `web_middleware` to array object is what the code recommends me to do (please look the comments in the code)

https://github.com/Laravel-Backpack/CRUD/blob/d9e6201350260006ecbf4dec087a8c7639666eaf/src/config/backpack/base.php#L178-L222
