### ISSUE TITLE
[Bug] - 2 fields with same entity

### ISSUE THREAD

**Issue by JulienCASTERA** [Laravel-Backpack/CRUD#3110]
# Bug report

### What I did

I tried to add 2 fields on the setupCreateOperation with the same entity.

```php
$this->crud->addField(['name' => 'founder', 'entity' => 'users', 'attribute' => 'fullname', 'type' => 'select2', 'label' => 'Créateur']);

$this->crud->addField(['name' => 'users', 'entity' => 'users', 'attribute' => 'fullname', 'type' => 'select2_multiple', 'label' => 'Membres']);
```

In my model : 

```php
    public function founder(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsToMany
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }
```

### What I expected to happen

Put the founder field in the "founder_id" column of my table "Club"
And the "users" field on the table "Club_User"

### What happened

Invalid argument supplied for foreach()

Stack trace : 

```php
                // if a JSON was passed instead of an array, turn it into an array

                if (is_string($values)) {

                    $values = json_decode($values);

                }

                $relation_data = [];
                foreach ($values as $pivot_id) {
                    $pivot_data = [];
                    if (isset($field['pivotFields'])) {

                        foreach ($field['pivotFields'] as $pivot_field_name) {

                            $pivot_data[$pivot_field_name] = $data[$pivot_field_name][$pivot_id];

                        }

                    }
```

### What I've already tried to fix it

I removed the field "founder" of the CRUD, it works but I need to get this founder_id field too 😿 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.8 (cli) (built: Jul  9 2020 23:43:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.15@6c751de946a9c8511dd32eb7bfa3ca6a568849f5
```

**Comment by tabacitu** [comment]
Hmm that's weird @JulienCASTERA - that definitely shouldn't be happening. But I don't think it's a Backpack bug, at least not in terms of using the same `entity` multiple times per form - I see it's working fine in our online demo, see [the Monsters CRUD, the Relationships tab](https://demo.backpackforlaravel.com/admin/monster/create#relationships). 

At first glance, I think you should put `founder` for your `entity` for the first field. As stated in the docs, `entity` should be the name of the relationship method - and I see yours is `founder`. Also you can remote that completely and Backpack will guess it.

I'm pretty sure that's your problem, and it's not a Backpack bug, so I'm going to close the issue. Feel free to reopen if I'm wrong.

Cheers!

**Comment by tabacitu** [comment]
PS. Yes I know "relationship" would have been a better name than "entity" 😆 ... we left it "entity" for backwards-compatibility - but maybe we should consider also supporting `relationship`, which would be clearer. And it would set the same thing (so maybe 4.2 supports both but only documents one of them). **What do you think @pxpm - should we rename the `entity` attribute to `relationship`?**

**Comment by pxpm** [comment]
Hello @tabacitu 
as part of contious work in #3065 , I don't think it's related to this specific issue, but I found an use case where using two fields with same entity were failing with current code.

```php
 $this->crud->addField([
            'name' => 'address.icon_id', 
            'entity' => 'address.icon', 
            'type' => 'relationship', 
            'tab' => 'Relations',
            'wrapper' => [
                'class' => 'form-group col-md-6'
            ],
        ]);

        $this->crud->addField([
            'name' => 'select',
            'type' => 'select2',
            'entity' => 'address.icon',
            'tab' => 'Relations'
        ]);
```

The first is a `HasOne` relation, the second is a `BelongsTo`.

With current code, specifically the one within PR: #3116 the `BelongsTo` relation name gets changed to `address[icon_id]` the same as the first field, that will prevent one of the fields beeing present in the crud because they both have the same name.

PR: #3116 fixes this because we would only change `HasOne` relation fields and not `BelongsTo`.
