### ISSUE TITLE
[Bug] bulk_clone.blade.php file has hardcoded strings

### ISSUE THREAD

**Issue by leocharrua** [Laravel-Backpack/CRUD#3112]
# Bug report

bulk_clone.blade.php file has not translated strings:

```
    var message = "Are you sure you want to clone these :number entries?";
    message = message.replace(":number", crud.checkedItems.length);

    // show confirm message
    swal({
           title: "{!! trans('backpack::base.warning') !!}",
	   text: message,   // here
           ...

```
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:23) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.16@4c2264f8dd52381aa891136edb61e8d4083a033d

**Comment by tabacitu** [comment]
Totally! Thank you for reporting this @leocharrua - I've just created #3114 which fixes this. It'll be merged and tagged on Monday the latest, you starting then (the latest) you'll be able to get this using `composer update`.

Cheers! Keep 'em coming.
