### ISSUE TITLE
[Bug] Url change to not routable path, when using CRUD filters with url which contains "/search" part

### ISSUE THREAD

**Issue by anclywen** [Laravel-Backpack/CRUD#3117]
# Bug report

### What I did

Using filters in CRUD table when route contains "/admin/searchquery/"

### What I expected to happen

It should properly change path

### What happened

After using filters, my url  change from "/admin/searchquery" change to "/admin/query/search" which is not routable. 
I have to turn off persistant table because it constantly redirect to not routable path

Problem is for all paths which contains "/search"

### What I've already tried to fix it

It's a new application so I  workaround problem and change my route path to sth without /search in pathname.

I look into the code and problem is in this line [resources/views/crud/inc/datatables_logic.blade.php:79](https://github.com/Laravel-Backpack/CRUD/blob/e977d534b106a6fec65707450f843ff55d31d282/src/resources/views/crud/inc/datatables_logic.blade.php#L79)

`        new_url = new_url.replace('/search', '');`

It change the first occurence of /search so path "/admin/searchquery/search" was changed to "/admin/query/search"

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.2.24-0ubuntu0.19.04.2 (cli) (built: Jan 14 2020 13:26:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.19.04.2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

### LARAVEL VERSION:
v7.24.0@71bfb1f2f89e4e31fba539d43fe287143e635e68

### BACKPACK VERSION:
4.1.16@4c2264f8dd52381aa891136edb61e8d4083a033d

**Comment by pxpm** [comment]
Hello @anclywen 

I think I get the problem. 

One way I think we could solve this is instead replacing the first ocurrence in the URL, we should get all `search` words in url, and only replace the one that is preceded by `/` and followed by empty char, or an `?` if the url has more query parameters. 

Do you foresee any problems using this technique ? 

Best to you,
Pedro

**Comment by tabacitu** [comment]
@anclywen thanks for reporting the issue. @pxpm just raised the issue in a meeting we had and I think we found a great solution together - _splitting the URL before we do the string replacing_, into:
- `$crud->route` (in your example `/admin/searchquery`)
- everything else that's after `$crud->route` (in your example `/search?category_id=smth#exampleTabName`)

If we do `.replace('/search', '')` on just the second part, that should allow CRUD entity names to include `search` too, without a problem.

We weren't aware this was happening, thanks for reporting it @anclywen !
I expect we'll have a solution for you by the end of the week - @pxpm is working on it.

Cheers!

**Comment by anclywen** [comment]
@tabacitu @pxpm 

I think splitting in two parts (route & else) it's a very good direction. It's very safe  and I don't see any problems with it.

Thx for high priority,

Best regards

**Comment by tabacitu** [comment]
Thank you for your patience @anclywen . And for putting together a great bug report 😄  I've just submitted https://github.com/Laravel-Backpack/CRUD/pull/3129 which should fix this. If you could please check it out and let us if it's a good solution for you, that'd help a lot.

Cheers!
