### ISSUE TITLE
[4.1][Bug] Mobile listOperation does not show the Export button

### ISSUE THREAD

**Issue by DanielKimmich** [Laravel-Backpack/CRUD#3135]
# Feature Request

### What's the feature you think Backpack should have?

From a mobile, the Export button is hidden, this happens when the "BulkDeleteOperation" option is enabled.

![Screenshot_20200815-200047_Chrome](https://user-images.githubusercontent.com/44840413/90763818-bca75280-e2bd-11ea-8b7a-1795a5a77304.jpg)

Another semanagement is that the header that comes out at the bottom can be disabled, since it remains at the top in modal mode.

If the "disableResponsiveTable ()" function is enabled, the top header is not output in modal mode.

**Comment by tabacitu** [comment]
Sounds like a bug to me, thanks @DanielKimmich ! I've tagged it appropriately so we fix it, thanks.

**Comment by pxpm** [comment]
Hello @DanielKimmich 

I am trying to figure out a solution for this. 

Would you mind testing my solution on #3181  ?

Add the css to your `public/packages/backpack/crud/css/list.css` file and the pagination class in the `datatables_logic.blade.php`

Let me know how it goes for you.

Thanks in advance,
Pedro

**Comment by tabacitu** [comment]
Just ended up submitting PR #3203 too, for this. So we have both #3181 and #3203 to fix this - let's close the issue to continue the conversation in one of those threads. Your feedback there would be very appreciated @DanielKimmich .

Thanks for letting us know about this. Cheers!
