### ISSUE TITLE
[Bug]  CKEditor not showing 

### ISSUE THREAD

**Issue by ckhandla94** [Laravel-Backpack/CRUD#3141]
# Bug report

### What happened

CKEditor not showing
![image](https://user-images.githubusercontent.com/27082896/90949472-d5eb0300-e465-11ea-8ccf-c301c4913eab.png)

![image](https://user-images.githubusercontent.com/27082896/90949476-dd121100-e465-11ea-9f41-4d95eb3f039a.png)

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**PHP VERSION:**
PHP 7.4.7 (cli) (built: Jun 12 2020 00:04:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**LARAVEL VERSION**
v6.0.4@372e0add8a58e0e3deb78f87cbb2dc40d3e0ff08

**BACKPACK VERSION**
4.1.18@8109ca0d308e47fb24c8baa8bd9893e21a187214

**Comment by tabacitu** [comment]
@ckhandla94 I'm happy to tell you that @pxpm fixed this in https://github.com/Laravel-Backpack/CRUD/pull/3148 - which will be merged later today. After I tag it as 3.1.19 this'll be fixed for you (later today), after a `composer update`. So I'm going to close the issue - let us know if it doesn't actually fix it in your case.

Cheers!
