### ISSUE TITLE
[Feature Request] InlineEdit a short list of related entities

### ISSUE THREAD

**Issue by DinoTD** [Laravel-Backpack/CRUD#3146]
# Feature Request

### What's the feature you think Backpack should have?
The same as InlineCreatte but also with InlineEdit.

We have two tables here: orders and invoices. One order has zero or a short list of invoices. An invoice belongs to an order.
In an order create/update page I have an select(from a short list of invoices) with InlineCreate and a modal.
I want to transform it in a custom field as a list with InlineCreate and InlineEdit. This looks similar with a table field.
In this create/update page I want to see an "+ Add invoice" and also a short list of existing invoices with an "Edit" button for every invoice and the possibility to edit each invoice in a modal as I do now with InlineCreate.
How hard is to separate the logic from this select and InlineCreate.
What is the best way to do that? 

### Have you already implemented a prototype solution, for your own project?
For now I'm trying to implement this as a custom field for create and update.

### Do you see this as a core feature or an add-on?

It can be a core feature next to InlineCreate.

**Comment by tabacitu** [comment]
@DinoTD I'll let @pxpm answer this since InlineCreate is his baby, he knows best how difficult it would be to create an InlineEdit.
