### ISSUE TITLE
[Bug] Multiple Repeatable Field save content of the first one in every field

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#3153]
# Bug report

### What I did

After updating from 4.1.15 to 4.1.19 content with multiple repeatable field save for every field the content of the first one losing data.

### What I expected to happen

Every field should save self data.

### What happened

Seems js of repeatable overwrite value of input

### What I've already tried to fix it

No

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.3 (cli) (built: May 26 2020 12:24:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.26.0@f64299a11dedaaadf1cfff07b2b3220a9b791837

### BACKPACK VERSION:
4.1.19@a47eeda32d08d0d47a3c820416c8a8f880752b80

![image](https://user-images.githubusercontent.com/3725174/91287531-24fba580-e790-11ea-8258-ebab19059f34.png)

Look at fields: interview, personalData, career, social

Before save content was:
![image](https://user-images.githubusercontent.com/3725174/91288088-dbf82100-e790-11ea-9096-c1ebb6d01c1d.png)

**Comment by pxpm** [comment]
I am on it. Pretty sure it's a bug I introduced yesterday. It should be an easy fix. Sorry for that, I will let you know here when I come up with a solution.

Best

**Comment by bedoz** [comment]
Thank you for a quick reply.
I'm looking with various version of crud at exactly which version it broke.

**Comment by bedoz** [comment]
Yeah, i can confirm that everything work well 'till 4.1.18.

**Comment by DanielKimmich** [comment]
The same thing happens to me after the update too.

**Comment by tabacitu** [comment]
Thank you @pxpm !

**Comment by pxpm** [comment]
Hello @bedoz and @DanielKimmich 

Sorry for the introduction of the bug, it slipped me :upside_down_face: 

I'v submitted PR #3156 that address this issue. It's a very small change you can do it manually in your project until it gets merged (it should not take long) .

Also if you did try it, let your approval/refusal in the PR to make sure it fixed the problem described. It would help us a lot.

Going to close this, lets keep any discussion in the PR thread. 

Wish you guys the best,
Pedro

**Comment by tabacitu** [comment]
Merged and tagged - if you get 4.1.20 you should have this fixed. 
Thanks again @pxpm , @bedoz & @DanielKimmich !

**Comment by DanielKimmich** [comment]
It is verified that it was solved. Thank you very much.
