### ISSUE TITLE
[Bug] Checklist not checked old data

### ISSUE THREAD

**Issue by abewartech** [Laravel-Backpack/CRUD#3175]
Checklist not checked old data

![image](https://user-images.githubusercontent.com/29395602/91930828-0a837800-ed0c-11ea-8c2e-01d518a33c59.png)

![image](https://user-images.githubusercontent.com/29395602/91930843-12dbb300-ed0c-11ea-99ea-aade7166a2d8.png)

**Comment by pxpm** [comment]
@abewartech thanks for the report. 

Could you provide me your checklist field definition ? Thanks

**Comment by abewartech** [comment]
![image](https://user-images.githubusercontent.com/29395602/91978563-86061900-ed4e-11ea-8011-393abecca967.png)

Thanks

**Comment by pxpm** [comment]
Hello @abewartech 

Testing this I figured out that you need to add `engine` to your model `$casts`. 

`protected $casts = ['engine' => 'array'];`

I checked and it's missing in the docs. I am submitting an PR to the docs so we can clarify people that when using `pivot => false` or just don't setup `pivot` at all, will default to false, you need to cast the db column to array in your model.

Sorry for missing info on docs. 

I am going to close this, if I am wrong, please re-open. 

Best,
Pedro
