### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by DelightedD0D** [Laravel-Backpack/CRUD#3176]
# Bug report

### What I did
- Logged into the [Backpack Demo](https://demo.backpackforlaravel.com/admin/dashboard)
- Navigated to some other page, like the [Backpack homepage](https://backpackforlaravel.com/)
- Navigated directly to a CRUD edit link like [this news item](https://demo.backpackforlaravel.com/admin/article/1031/edit)
- Clicked "Save and back"

### What I expected to happen
- Expected that after the save, I'd be redirected back to the list page for the edited CRUD entity. 

### What happened
- I was redirected back to the  [Backpack homepage](https://backpackforlaravel.com/)

### What I've already tried to fix it
- scratched my head for a bit
- debugged for a bit and tracked the cause to  `src/resources/views/crud/form_content.blade.php`

`<input type="hidden" name="http_referrer" value={{ session('referrer_url_override') ?? old('http_referrer') ?? \URL::previous() ?? url($crud->route) }}>`

Specifically,  ` \URL::previous()`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```

### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.26.0@f64299a11dedaaadf1cfff07b2b3220a9b791837

### BACKPACK VERSION:
4.1.20@132be56989a23fd16e0957ed40775c4fba0dfef3
```

I'm not certain this is considered a "bug" per se. Given that `\URL::previous()` only cares about where we came from, ie the HTTP_REFERER  header, the code behavior isn't "wrong" though for me, it was "unexpected" and cost me a few hours of digging to work out what was happening (I thought it was something I'd misconfigured)

For context, I ran into this when a client sent me an edit link like https://demo.backpackforlaravel.com/admin/article/1031/edit to look at a record. When saving, I expected to get the list for that entity but got the homepage instead.

**Comment by pxpm** [comment]
Hello @DelightedD0D 

Indeed, that is the expected behaviour. `Save and go back wherever you are`.

If you want a custom `Save and go to list page` you can create your default save action with that behaviour. 

Also save actions provide a way of manipulating the refereer url. 

```php
[
                'name' => 'save_and_edit',
                'visible' => function ($crud) {
                    return $crud->hasAccess('update');
                },
                'redirect' => function ($crud, $request, $itemId = null) {
                    $itemId = $itemId ?: $request->input('id');
                    $redirectUrl = $crud->route.'/'.$itemId.'/edit';
                    if ($request->has('locale')) {
                        $redirectUrl .= '?locale='.$request->input('locale');
                    }
                    if ($request->has('current_tab')) {
                        $redirectUrl = $redirectUrl.'#'.$request->get('current_tab');
                    }

                    return $redirectUrl;
                },
                'referrer_url' => function ($crud, $request, $itemId) { //this is the key used to override the refereer url. 
                    return url($crud->route.'/'.$itemId.'/edit');
                },
                'button_text' => trans('backpack::crud.save_action_save_and_edit'),
            ],
``` 

Take a better look at docs: https://backpackforlaravel.com/docs/4.1/crud-save-actions#save-actions-api

### PS: I just noticed in docs it says `referrer` instead of `referrer_url`. Use the last `referrer_url`, I am submiting a PR to fix the docs.

Going to close this, as I think there is no bug here. 

If I am wrong, and sometimes I might be, please re-open :+1: 

Wish you the best,
Pedro

**Comment by DelightedD0D** [comment]
Thanks @pxpm, that's fair I had a feeling that'd be the case.
