### ISSUE TITLE
[Bug] Filter fallbacks doesn't work

### ISSUE THREAD

**Issue by hirakujira** [Laravel-Backpack/CRUD#3183]
# Bug report

### What I did

I tried to make a filter with fallback closure.

### What I expected to happen

Fallback function should work when my simple filter doesn't active.

### What happened

Nothing happens when the filter is not active.

### What I've already tried to fix it

https://github.com/Laravel-Backpack/CRUD/pull/3182

### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 17 2020 12:02:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.27.0@17777a92da9b3cf0026f26462d289d596420e6d0

### BACKPACK VERSION:
4.1.21@187bb0c3ce52ac2bfefeb9cd7518fec27a82ebcc

**Comment by pxpm** [comment]
Hello @hirakujira and thank you very much for the bug report and the fix for it. 

I am going to close this one so we keep the discussion related with this issue in the PR thread you provided. 

Wish you the best,
Pedro
