### ISSUE TITLE
LicenseCheck failure in the private IP address

### ISSUE THREAD

**Issue by vonsogt** [Laravel-Backpack/CRUD#3184]
# Bug report
LicenseCheck in the private IP address

### What I did
- turn off APP_DEBUG to false
- then `php artisan serve --host 0.0.0.0`
- access from another computer using the local IP address
and also, I tried:
- copy my project to xampp/htdocs
- custom to local domain
- still the same

### What I expected to happen
- Should check the $_SERVER if private IP address should not show alert

### What I've already tried to fix it
- update this code (is that necessary?)
`vendor\backpack\crud\src\LicenseCheck.php`

### PHP VERSION:
PHP 7.3.7 (cli) (built: Jul  3 2019 14:34:10) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.26.1@fad3e5f03b9ae89853c8a0925231d2b3ce07a9c3

### BACKPACK VERSION:
4.1.21@187bb0c3ce52ac2bfefeb9cd7518fec27a82ebcc

**Comment by pxpm** [comment]
Hello @vonsogt :) how are you ?

Can you please post the error you get ? Is specific to the ip address ? Or you don't get any error but the message is displayed when it shouldn't ? 

Best,
Pedro

**Comment by vonsogt** [comment]
I'm fine @pxpm, thx for asking

Okay, the problem is I go this alert when serving the project
![image](https://user-images.githubusercontent.com/35516476/92320244-47bc7280-f04a-11ea-876c-c554d0413a24.png)
because of this line:
https://github.com/Laravel-Backpack/CRUD/blob/2671bd4c773b556c36e2d861471fc6fe13de2b67/src/LicenseCheck.php#L31-L33

and I did this:
- set APP_DEBUG to false
- runs command `php artisan serve --host 0.0.0.0`

So another computer that connected to the router can access through the IP address. I tried to move the project folder to `xampp/htdocs` it will return the same.

I would suggest that we should add more line to check if the `$_SERVER['REMOTE_ADDR']` using a private IP address (local).

like this answer:
https://stackoverflow.com/a/13818126/8653054
or I should request the license code for non-commercial? btw my project was running in office only to administrate the jobs.

**Comment by tabacitu** [comment]
Hi there,

I think I understand your use case, but correct me if I'm wrong please. You're creating something that will be hosted on a local computer, then others on the same network will have access to it. So... an intranet software. But you're getting the yellow "unlicensed software" bubble.

In this case... it's normal. For intranet software, this is what "going to production" looks like, and in production Backpack needs a license code to work. So yes, please apply for a license code on pur website if it's non-commercial (hobby, study, friend) or you've contributed to Backpack.

Let me know if I've misunderstood your use case and we'll reopen.

Cheers!
