### ISSUE TITLE
[Feature Request] new field type text_with_options

### ISSUE THREAD

**Issue by DinoTD** [Laravel-Backpack/CRUD#3186]
# Feature Request

### What's the feature you think Backpack should have?

Input text field but with autocomplete similar as select or select_from_array.
We can call this text_with_options.
When I write a few characters I will get a select box with a few options. I can choose one option or write a new word.
Ex: I have an input field "Places to visit". I write a few characters, and I can choose one from the list, or I can write a new one.
This is similar to a search box from a shopping site.
This will be save to db as a varchar.

### Have you already implemented a prototype solution, for your own project?

We are working on a solution. Are you interested in a PR for this as a core field?

### Do you see this as a core feature or an add-on?

Another core create/update field.

**Comment by tabacitu** [comment]
Hi @DinoTD 

I think what you're aiming for is exactly https://github.com/Laravel-Backpack/CRUD/pull/2347 - am I right? There should already be working code there, inside this PR, which does exactly that. 

I've just replied there that I don't quite see this as a core feature - but I do understand how common the pattern is, and I wish there was an add-on for it for Backpack. Maybe you can help create/maintain the package if @liquid207 decides to create it?

Cheers!

**Comment by tabacitu** [comment]
I'll close this issue in favour of continuing the conversation inside #2347 ... or hopefully 🙄 inside an add-on 😉
