### ISSUE TITLE
Documentation Failure? There doesn't seem to be a way to tie junction tables to Select dropdowns.

### ISSUE THREAD

**Issue by christopher-wilson** [Laravel-Backpack/CRUD#319]
I have three models, `writers`, `books`, and `events`. The `events` table joins the other two. In the CRUD interface it is displayed as two columns with the IDs, where is logically there should a select box displaying either all the IDs or a custom field from each model/table.

Laravel's relationships handle this just fine, but there doesn't seem to be anything in the docs or the comments that indicate that this is supported.

**Comment by christopher-wilson** [comment]
OK, this is a little tricky to find. I actually found it by Googling a phrase instead of seeing it in the documentation, which is no the worst thing in the world.

However, my question is, is it possible to do this automatically?

**Comment by OwenMelbz** [comment]
Not entirely sure what you mean really.

Are you looking to just have a select menu which lets you manage entity relationships?

If so you can do this using the the select or checkbox relationships which are explained in the docs under the field type section

**Comment by christopher-wilson** [comment]
This is the goal yes, and I have it working after I found it in the docs. However, I'm now asking if it is possible to do some of this automatically. The relationships are already defined in the application, it knows the columns to find, it should know the table to look at and be able to automatically choose an appropriate column.

Hypothetically.

**Comment by OwenMelbz** [comment]
What bit of it would you want to be done automatically? 

As far as I'm aware you couldn't automatically

- label the field 
- detect which relationship to use
- know which property to display as the value to pick 
- know what sort or relationship it is

However it already maps the relationships for you, you just have to define the field.

Are you using the Automatic from DB thing in the controller. Or defining the fields yourself? As the automatic one is just really basic and should use the full alternatives ideally

**Comment by tabacitu** [comment]
Hi @christopher-wilson , @OwenMelbz ,

Yup, that's the plan for ```autoSetFromDb()```. It's rather difficult so I don't expect it to be ready until June-July, but I think it's possible:
- when generating a model using [Backpack\Generators](https://github.com/laravel-backpack/generators) we'll make sure
   - all columns are placed in "fillable";
   - the primary key is properly set;
   - the Eloquent relationships are defined, based on foreign keys and naming conventions (pivot tables are "article_tag");
 
    => fully accurate models
- autoSetFromDB() will pick up on those and create the appropriate fields for those relationships (will be searching for some default columns to use: name, title, etc; if none found, just use the first varchar column);

That _should_, in theory, be possible. And I think it will speed up development for most admin panels A LOT, with zero overhead for the developer. It's one of the things that will come in the "optimizations" stage of the project, when we're done introducing new horizontal features.

Here's the github issue for it: https://github.com/Laravel-Backpack/Generators/issues/18

Cheers!
