### ISSUE TITLE
[Bug] Values function in fluent API not working

### ISSUE THREAD

**Issue by mahasadhu** [Laravel-Backpack/CRUD#3193]
# Bug report

### What I did

using fluent API to build filter

### What I expected to happen

select2 values filled with function's result

### What happened

select2 values empty

### What I've already tried to fix it

https://github.com/Laravel-Backpack/CRUD/pull/3192

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.16.1@dc9cd8338d222dec2d9962553639e08c4585fa5b

### BACKPACK VERSION:
4.1.21@187bb0c3ce52ac2bfefeb9cd7518fec27a82ebcc

**Comment by pxpm** [comment]
Thank you very much @mahasadhu 

I'v just written my thoughts about this in your PR #3192 

I am going to close this so we keep the discussion only in the PR thread. 

Wish you the best,
Pedro
