### ISSUE TITLE
Laravel 8.x Support

### ISSUE THREAD

**Issue by filipbekic01** [Laravel-Backpack/CRUD#3194]
Backpack is blocking me to upgrade Laravel.

**Comment by pxpm** [comment]
Hello @filipbekic01 

We are aware that Laravel 8 just came out yesterday. 

We already have a WIP to make sure we support Laravel 8. 

Have a look at: https://github.com/Laravel-Backpack/CRUD/pull/3189 

There is instructions on how you can help us speeding up this process, any help would be much apreciated. 

Wish you the best,
Pedro
