### ISSUE TITLE
[Feature Request] select2_from_ajax with optional relationship

### ISSUE THREAD

**Issue by Sammi89** [Laravel-Backpack/CRUD#3195]
# Feature Request
### What's the feature you think Backpack should have?
It would be useful to have the ability to use the **select2_from_ajax** field without having to use a relationship. 
Eg: I need a select field that depends on another select field but does not refer to any model, to then manage the values with a mutator.

### Have you already implemented a prototype solution, for your own project?
Not yet but I'm thinking about.

### Do you see this as a core feature or an add-on?
Is already a core feature, but it may be updated.

PS: I have searched if this possibility already exists but I have not found anything, but correct me if I'm wrong.

**Comment by pxpm** [comment]
Hello @Sammi89 

`select2_from_ajax` does not require a relationship, but indeed it requires a model. 

You have the `select_from_array` option where you can provide the options without any relation.

I think you are looking for something like: `select2_from_api` that would basically be a `select2_from_array` but the options are provided by API call on user input, so it's an ajax field, but the results only query the api endpoint and don't rely in any model ? If that's the case, we don't have nothing with that atm. But I see some value on it, if you come up with a solution share it with us, it might help other people. 

Otherwise I might see this as a core field, but can't give you an E.T.D for it. 

The dependant fields rely on field name, does not matter what field type it is. 

Wish you the best,
Pedro

**Comment by Sammi89** [comment]
Hi @pxpm 

Thanks for replying so quickly.
You are right, I need something similar to what you described. I try to better define what I need. 
I need a select field where:
1. The options are taken from a DB table modeled with an Eloquent model. There is no relationship between this model and the current entity.
2. The options to show change in relation to an other field value. So when the field on which it depends change, the options must also change.

I hope I explained myself.
I don't know if this type of field already exists. Maybe I don't know how to configure one of the existing fields to replicate this behavior.

Thanks for the help!

**Comment by pxpm** [comment]
If you have a model you can use select2_from_ajax (do not setup entity only model) and setup 'dependencies' key. Check in the docs 'dependant fields' on how dependencies work. 

I think this will fulfill your needs. 

Let me know. 

Pedro

**Comment by Sammi89** [comment]
Hi @pxpm 
I tested the solution you recommended me and works fine. Thank you.
Out of curiosity I tried to use the same solution with a [(select field)](https://backpackforlaravel.com/docs/4.1/crud-fields#select-1-n-relationship) specifying the model and omitting the entity attribute but it returns an error: "Missing entity index". I don't know if is a bug or a a desired behavior because the docs specify that the entity attribute is optional.
Thank you so much for your help.

I have one more question to ask: I have implemented the solution inside a repeatable field but when get the form input inside the autocomplete controller, the values of fields inside the repeatable group are missing. I did something wrong with the implementation?
The following code show how I've implemented the form fields. Maybe can be useful.
```
$this->crud->addField([
    'name'  => 'attributes',
    'label' => 'Attributes',
    'type'  => 'repeatable',
    'fields' => [
        [
            'label' => 'Field',
            'type' => 'select2',
            'name' => 'field_id',
            'model' => 'App\Models\Field',
            'attribute' => 'label'
        ],
        [
            'label' => 'Value',
            'type' => "select2_from_ajax",
            'name' => 'option_id',
            // 'entity' => 'option',
            'attribute' => 'value',
            'data_source' => url('autocomplete/deal/option'),
            'minimum_input_length' => 1,
            'model' => 'App\Models\Option',
            'dependencies' => ['field_id'],
            'include_all_form_fields' => true,
            'placeholder' => trans('deals.placeholders.option_id'),
        ],
    ],
    'new_item_label'  => 'Add Attribute',
]);
```

Thank you.

**Comment by pxpm** [comment]
My guess is that using 'attributtes' as the name may conflict with some internal 'attributtes'. 

Didn't test, is just a guess. Could you test with other name? 

Best, Pedro

**Comment by Sammi89** [comment]
Nothing happens. I've change the name and set the attribute fake to true to check if in the request input data of the autocomplete api call were found the repeatable field data but is always null.
I've update the backpack version from 4.1.3 to 4.1.22 with the hope that was a resolved bug but not works.
I don't know if there is a special way to get the repeatable field data from the request inside the controller of ajax call.
let me know if someone know the answer. I will try to find a solution.
Thank you.

Sam

**Comment by Sammi89** [comment]
I found what causes the problem of missing values from repeatable fields in the autocomplete controller called via ajax with the property _include_all_form_fields_ set at true in **select2_from_ajax** (and probably the others ajax fields). 

Data passed in select2_from_ajax.blade.php are these:
```js
{
    q: params.term, // search term
    page: params.page, // pagination
    form: form.serializeArray() // all other form inputs
};
```
The `serializeArray()` function from [JQuery](https://api.jquery.com/serializeArray/) returns an array with values for each fields in for that have the **name** property. Fields inside the repeatable fields don't have it. So when you need to use a repeatable field value in autocomplete controller, you miss it.

I'm trying to change **repeatable.blade.php** file to add the name property but don't know if is the best solution.
Maybe someone have a better idea.
Thanks

**Comment by pxpm** [comment]
Hello @Sammi89 

I'v submitted PR: #3313 that should fix this last issue for you without need to add name in repeatable. I hope it gets merged by monday the next.

I am going to close this as both solution are provided. 

Wish you the best,
Pedro
