### ISSUE TITLE
[Bug] Filters select2_multiple and  text not working correctly together

### ISSUE THREAD

**Issue by AndresLealColon** [Laravel-Backpack/CRUD#3201]
# Bug report

### What I did

Add two filters (select2_multiple, text) in list view but not working together.

  $this->crud->addFilter([
              'name'  => 'status_id',
              'type'  => 'select2_multiple',
              'label' => 'Status'
            ], [
              1 => 'Bloq/Apartado',
              2 => 'Anticipado',
              3 => 'Cerrado',
              4 => 'Liquidado',
              8 => 'Cancelado',
            ], function($values) {
              foreach (json_decode($values) as $key => $value) {
                $this->crud->addClause('orWhere', 'status_id', "$value");
              }
            });
            $this->crud->addFilter([
                'name'  => 'fecha_salidas_id',
                'type'  => 'text',
                'label' => 'fid'
              ],false,
              function($value) {
                $this->crud->addClause('where', 'fecha_salidas_id', '=', $value);
              });

### What I expected to happen

-Filter list view with the user filter selection. 
-Url with paramether should filter correctly, example:         /admin/reserva?statusId=%5B"1"%2C"2"%5D&fechaSalidasId=5588

### What happened

Only work with one filter not both and it depends of the order you set filters.  

### What I've already tried to fix it

Change filter order but same behavior

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.19 (cli) (built: Jul  1 2020 19:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.19, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.23.0@17cbce101f2fc78e61a6135861823563c7cfb50b

### BACKPACK VERSION:
4.1.16@4c2264f8dd52381aa891136edb61e8d4083a033d

**Comment by pxpm** [comment]
Hello @AndresLealColon 

I think this is not a Backpack problem, but it's the way you apply your filter. 

Correct me if I am wrong, but you expect `where 'text' = 'some_text' OR/AND (select_multiple = 1 OR select_multiple = 2)` 

You can build your filter to match your expectations. 

```php
$this->crud->addFilter([ // select2_multiple filter
            'name' => 'select2_multiple',
            'type' => 'select2_multiple',
            'label'=> 'S2 multiple',
        ], function () {
            return \Backpack\NewsCRUD\app\Models\Category::all()->keyBy('id')->pluck('name', 'id')->toArray();
        }, function ($values) { // if the filter is active
            
                $this->crud->query->orWhere(function($query) use ($values) {
                    foreach (json_decode($values) as $key => $value) {
                        $query->where('select2', $value); //you can use orWhere here
                    }
                });
            
        });
```

This would produce the following SQL:

`select * from `monsters` where `text` LIKE ? or (`select2` = ? and `select2` = ?) order by monsters.id DESC limit 10"`

I am going to close this, as I don't think this is a Backpack bug but rather a bad implementation.

If I am wrong, and sometimes I can be, please re-open.

Best,
Pedro
