### ISSUE TITLE
The backpack_view should contain one param only

### ISSUE THREAD

**Issue by EricKwan2014** [Laravel-Backpack/CRUD#3206]
https://github.com/Laravel-Backpack/CRUD/blob/dc88fb5ab3128e4389f0d65a69c1a22f0e2a6c2b/src/app/Http/Controllers/Auth/ForgotPasswordController.php#L37

should be
``` php
return view(backpack_view('auth.passwords.email'), $this->data);
```

instead of
``` php
return view(backpack_view('auth.passwords.email', $this->data));
```

**Comment by tabacitu** [comment]
You're right! Thanks @EricKwan2014 - it's now fixed by #3208, which will be tagged most likely early next week (Monday/Tuesday) the latest. So after that you'll be able to get it using `composer update`

Cheers!
