### ISSUE TITLE
select2_multiple 'array to string conversion' error - tries to save on parent model

### ISSUE THREAD

**Issue by robinmoisson** [Laravel-Backpack/CRUD#321]
I'm using select2_multiple field on a n-n relationship, but I'm getting

    QueryException in Connection.php line 770:
    Array to string conversion (SQL: update "associations" set "updated_at" = 2016-12-26 09:02:07, "causes" = 1 where "id" = 1)
    in Connection.php line 770
    at Connection->runQueryCallback('update "associations" set "updated_at" = ?, "causes" = ? where "id" = ?', array('2016-12-26 09:02:07', array('1', '3'), '1'), object(Closure)) in Connection.php line 726

These are my models:

    class Association extends Model
    {
        use CrudTrait;
        public function causes()
        {
            return $this->belongsToMany('App\Cause');
        }
    }

and

    class Cause extends Model
    {
        use CrudTrait;

        public function associations()
        {
            return $this->belongsToMany('App\Association');
        }
    }

I'm setting up the field that way in `AssociationCrudController`:

        $this->crud->addField([
            // Select2Multiple = n-n relationship (with pivot table)
            'label' => "Causes",
            'type' => 'select2_multiple',
            'name' => 'causes', // the method that defines the relationship in your Model
            'entity' => 'causes', // the method that defines the relationship in your Model
            'attribute' => 'value', // foreign key attribute that is shown to user
            'model' => 'App\Cause', // foreign key model
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
        ]);

I get the error when I try to update or insert the association with one or more causes. After investigation on an 'update' it seems the queries are following this order:

- update the pivot table by deleting/adding the necessary rows (this works ok, so when I reload the page the modification I made has been saved)
- try to update directly the `association` model, filling `causes` field with an array - this fails.

Am I doing something wrong? Shouldn't we automatically skip the n to n fields when updating the model's table, updating the pivot table being enough?

I'm on Laravel 5.3, PHP7 and postgres. Thanks !

**Comment by OwenMelbz** [comment]
Just to confirm, few things

- are you using a pivot table? 
- Do you have a column called 'value' in your causes table 
- backpack tends to put your models in App\Models\Cause rather than App\Cause - so are you sure that correct?
- finally! There might be a slight chance the "associations" name could be causing a conflict. Could you try another to confirm it's not?

Thanks :)

**Comment by robinmoisson** [comment]
Thanks for the answer ! After testing with another name:

- I am using a pivot table, named `association_cause` (all names following conventions, the insertion into the pivot table works fine)
- I do have a column named `value` in `causes`, and the values are displayed correctly in the select2 widget/column view
- Laravel 5.3 puts the models straight in `App`, so I used those in backpack as well by:

    - deleting the model generated in `App/Model` by the `php artisan backpack:crud cause` command
    - adding the `CrudTrait` to my models in `App`
    - changing first line of setup in `AssociationCrudController` to 

          $this->crud->setModel('App\Association');

      And doing the same to `CauseCrudAssociation`.
- I tried using the `select2_multiple` on another n-n relation I have, between entities named `job` and `worktype` -> I run into the same error...

**Comment by tabacitu** [comment]
Hmm... everything seems ok to me in the controller. Perhaps try manually specifying the pivot table in the relationships?

```php
    public function causes()
    {
        return $this->belongsToMany('App\Cause', 'association_cause');
    }
```

and
```php
    public function associations()
    {
        return $this->belongsToMany('App\Association', 'association_cause');
    }
```

I found it's best to be as clear as possible about what you want, in order to avoid relationship problems. Works for Laravel _and_ women :D

**Comment by robinmoisson** [comment]
Thanks for the advice, I tried it but no change... 

It seems that after calling `syncPivot` in the update trait ([here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/Update.php#L28)):

        $this->syncPivot($item, $data, 'update'); // $data = [ 'causes' => [ 1, 3], ... ]
        $updated = $item->update($data); // $data = [ 'causes' => [ 1, 3], ... ], error thrown

we try to update the model with a nested array, which fails. I tried in MySQL, I get the same kind of error: `'causes': column not found`.

If I modify the `syncPivot` method in the create trait ([here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/Create.php#L77)) to change it so that I remove the fields that use pivot, like so:

    // pass &$data by reference
    public function syncPivot($model, &$data, $form = 'create')
    {
        $fields_with_relationships = $this->getRelationFields($form);

        foreach ($fields_with_relationships as $key => $field) {
            if (isset($field['pivot']) && $field['pivot']) {
                $values = isset($data[$field['name']]) ? $data[$field['name']] : [];
                $model->{$field['name']}()->sync($values);

                // the field has been updated in the pivot table, remove it from data
                unset($data[$field['name']]);
    ...

then it works fine - but I'm guessing it shouldn't be necessary?

**Comment by OwenMelbz** [comment]
Do you have 'causes' in your $fillable?

**Comment by robinmoisson** [comment]
I just had `$guarded= [ 'id' ];`, but explicitly listing the `$fillable` and including `causes` in it doesn't change the error thrown.

**Comment by OwenMelbz** [comment]
Ah I was hoping that removing causes from $fillable was going to help

**Comment by robinmoisson** [comment]
@OwenMelbz Thank you for your last comment: yep, either listing everything that's not a n-n relationship in $fillable, or setting `$guarded = [ 'id', 'causes' ];` finally solves it.

Thanks all for the help !

**Comment by Nobleless** [comment]
af
