### ISSUE TITLE
[Bug] 4.0.x -- Table field "suddenly" skipping mutator.

### ISSUE THREAD

**Issue by trip-somers** [Laravel-Backpack/CRUD#3215]
# Bug report

### What I did

Attempted to store a new value via `table` field.

### What I expected to happen

Value should have been stored as expected.

### What happened

Database field remains null as if the table field contained no values. Other fields saved correctly and a success message was generated.

(A similar issue happened a couple of months ago for a couple of hours in June or July, the Table field was not submitting properly and causing a validation error. It suddenly started working again after a while with no updates or releases as if an external Javascript dependency had broken and been fixed.)

### What I've already tried to fix it

* I have confirmed that my `getExternalIdTableAttribute` accessor is still working correctly for models with existing data.
* I have verified that the post contains the `external_id_table` field in the expected structure.
* I have confirmed that my `setExternalIdTableAttribute` setter is not being called. Neither CRUD nor the model has been updated since it was last working correctly.

### Backpack, Laravel, PHP, DB version

The only recent update I've made was an update from Laravel 6.18.34 to 6.18.40, which I don't think should have altered how mutators work.

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v6.18.40@e42450df0896b7130ccdb5290a114424e18887c9

### BACKPACK VERSION:
4.0.61@1977e0cc52fa7cf9547eaeadf03f5cd88402b574
```

**Comment by trip-somers** [comment]
UPDATE: It looks like that Laravel version update is responsible. See this issue -- https://github.com/laravel/framework/issues/33978

Leaving open for the moment in case someone wants to add thoughts. Can be closed at any time since this is not actually a CRUD issue.

**Comment by tabacitu** [comment]
Ugh. Sounds like trouble. Good luck making your case @trip-somers ! 🤞

**Comment by Khalid3bdallah** [comment]
I think I had the same issue, the mutator wan't working although the accessor method was working, after some time I figured out that the field names have to be appended to $fillable array.

Was working
```
public function getEnglishNameAttribute()
    {
        return ($this->getTranslation('name', 'en'));
    }
```
Wasn't working
```
public function setEnglishNameAttribute($value)
    {
        $this->setTranslation('name', 'en', $value);
    }
```

Both worked after added to fillable
`public $fillable = ['name', 'english_name', ... ];`
