### ISSUE TITLE
There are no commands defined in the "backpack" namespace.  

### ISSUE THREAD

**Issue by aledevil** [Laravel-Backpack/CRUD#3219]
When i try to run php artisan backpack:base:install, it says "There are no commands defined in the "backpack" namespace."

**What I did:**
I installed backpack/crud
and then I tried to run php artisan backpack:install

C:\Users\**\Desktop\xampp\htdocs\**>php artisan backpack:install
                                                              
  There are no commands defined in the "backpack" namespace.  
                                                              

**What I've already tried to fix it:**
Install manually with command:
php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag="minimum"
php artisan vendor:publish --provider="Prologue\Alerts\AlertsServiceProvider"
php artisan migrate
php artisan backpack:publish-user-model
php artisan backpack:publish-middleware

but obtain
C:\Users\*\Desktop\xampp\htdocs\*>php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag="minimum"
Unable to locate publishable resources.
Publishing complete.

**Version:**
Backpack: 4.1
Laravel: 7.28
PHP: 7.2.5

**Comment by tabacitu** [comment]
@aledevil what page are you looking at, for those instructions? Is it possible that you're trying to install Backpack 4.1, but are looking at the 3.x docs? What does your `composer.json` say about the Laravel and Backpack version?

Because in Backpack 4.x the command is NOT `backpack:base:install` but `backpack:install` (no base), see here - https://backpackforlaravel.com/docs/4.1/installation

**Comment by aledevil** [comment]
> @aledevil what page are you looking at, for those instructions? Is it possible that you're trying to install Backpack 4.1, but are looking at the 3.x docs? What does your `composer.json` say about the Laravel and Backpack version?
> 
> Because in Backpack 4.x the command is NOT `backpack:base:install` but `backpack:install` (no base), see here - https://backpackforlaravel.com/docs/4.1/installation

I was just wrong to write the command in the first sentence of my text.
Looking further down I pasted my command line with the right command and the error

**Comment by tabacitu** [comment]
Hmm maybe Laravel didn't see our ServiceProvider and register it?

After you run "composer update" there's a list of providers that Laravel finds and loads. Is Backpack one of them?

**Comment by aledevil** [comment]
@tabacitu in my config/app.php there isn't backpack as providers, i have to add it manually?

**Comment by tabacitu** [comment]
Glad you figured it out @aledevil . For the record, and for anybody else seeing this thread in the future, the most probable explanation is that your have your Laravel auto-discovery feature disabled - https://mcampbell508.github.io/2018/01/20/disable-laravel-autodiscovery/

There's really no reason to do that. But if you do need it disabled, you can manually add the `Backpack\CRUD\BackpackServiceProvider::class` provider to your `config/app.php`.

Cheers!
