### ISSUE TITLE
[Bug] Problem in show details datatable for custom route

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/CRUD#322]
I made new route like /myplugin/id to fetch custom entry from model.
And also active show details for datatable. It gives full url request and attach detailed record id to end of url request. It has problem to shoing details 404.

`/myplugin/id/detailedid`

I have changed list.blade.php from /backpack/crud as below:

this line:
`url: '{{ Request::url() }}/'+btn.data('entry-id')+'/details',`

to

`url: '{{ url($crud->route) }}/'+btn.data('entry-id')+'/details',`

and solved...

Also for set active css class to opened current tree menu base on uri I have change a line in layout:

`var current_url = "{{ url(Route::current()->getUri()) }}"; `

to

`var current_url = "{{ Request::url() }}";`

in file 

> backpack/base/layout.blade.php

it works for all routes that have any tails!

**Comment by tabacitu** [comment]
Thank for the report! Fixed it in master and it will be available for everyone on the next version. Cheers!
