### ISSUE TITLE
[Bug] browse_multiple set empty string on create

### ISSUE THREAD

**Issue by maganius** [Laravel-Backpack/CRUD#3220]
# Bug report

### What I did

I have a browse_multiple to store images in json format.

```
$this->crud->addField([
            'name' => 'galeria',
            'label' => 'Galería',
            'type' => 'browse_multiple',
            'multiple' => true, // enable/disable the multiple selection functionality
            'sortable' => true, // enable/disable the reordering with drag&drop
            'mime_types' => ['image'], // visible mime prefixes; ex. ['image'] or ['application/pdf']
            'wrapperAttributes' => ['class' => 'form-group col-md-4'],
        ]);
```

### What I expected to happen

The expected value is an empty string array `"[]"`.

### What happened
browse_multiple field type in create operation the hidden field has an empty string in its value. The expected value is an empty string array `"[]"` to be store, otherwise when I access to property in a foreach the view throw an exception because `foreach cannot parse the emtpy string`

the model have the cast as `array`

`protected $casts = ['galeria' => 'array']`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
v7.28.3@b0942c391975972b1a54b2dc983e33a239f169a9

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by pxpm** [comment]
Hello @maganius 

I agree with you, the browse_multiple casted as array, is expected that even empty you get an empty array. 

I am not sure why `browse_multiple` supports `multiple => false` and the file has some hacks to accomodate this scenario. 

My question is, why we support non multiple in a multiple field, we have `browser` that is the same for single select from elfinder.

I will discuss this with @tabacitu later and get back here.

Thanks,
Pedro

**Comment by tabacitu** [comment]
Thanks @maganius & @pxpm . I'm just now talking to Pedro about this. The only reason browse_multiple supports multiple is because we intend to merge browse & browse_multiple in the future - see https://github.com/Laravel-Backpack/CRUD/pull/2812

Anyway, yes, let's do this!

**Comment by pxpm** [comment]
Thanks again @maganius 

I'v just submited PR #3226 that addresses this issue.

I am bit concerned that this might be a breaking change depending on how users are using the current empty string value from database. Check my comment on PR and add your inputs if you think that there is something more we can account for. 

I will be closing this so we keep any further discussion in the PR thread. 

Best to you,
Pedro
