### ISSUE TITLE
Clean dependant select contents on change. Now only sets value to null.

### ISSUE THREAD

**Issue by aula2030** [Laravel-Backpack/CRUD#3225]
# Feature Request or enhancement or bug?

I don't know how to classify this, as it only allows unexpected behaviour from users :smile: 

### What I did

I was testing to have dependant selects, so when you select a value in one, the dependant one list of options gets refreshed with appropriate values.

### What I found out

Since my computer is not the fastest in the galaxy it happens that when I update the first select, the dependant one is set to null (correct), but the list of options is not cleared. So when I navigate to the dependant one **I can select an "old" value while new contents is loaded**. Here is a small demo:

![clean-dependant-select](https://user-images.githubusercontent.com/66673634/94418172-51d11d00-0181-11eb-9d42-72d87bea4e7e.gif)

After changing the first select to 'Venganza' I can still select old options while correct ones are loaded. This should not be possible.

### Bug or enhancement?

I know select2 has a method to clear contents ([https://select2.org/programmatic-control/add-select-clear-items#clearing-selections](https://select2.org/programmatic-control/add-select-clear-items#clearing-selections)). It also sets to null the value. Sorry, I ignore where this "set to null" is done in backpack....

I'm running this:

```
### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.24.0@71bfb1f2f89e4e31fba539d43fe287143e635e68

### BACKPACK VERSION:
4.1.16@4c2264f8dd52381aa891136edb61e8d4083a033d
```
Hope it helps!
Regards!

**Comment by pxpm** [comment]
Hello @aula2030 

Thanks for the bug report. I think you are right here, there is no sense in having the options laying around while they should be cleared when dependency changes.

I'v just submitted the PR #3301 that addresses this issue by removing the options from the select while setting the value to null. 

I am going to close this, let's keep any further discussion regarding this matter in the PR thread. 

Thanks again, best Pedro

**Comment by pista7** [comment]
Great! Thank you!! :+1:

**Comment by tabacitu** [comment]
Merged! Will be available with a `composer update` starting tomorrow, most likely. Thanks everyone!
