### ISSUE TITLE
Link on the column displaying an elfinder file?

### ISSUE THREAD

**Issue by madd86** [Laravel-Backpack/CRUD#323]
I'm using elfinder (better to organize attachments).

Some things that I do miss:

- Clickable link right on the field's respective column
- A "download" button added next to "Browse uploads" and "Clear"

Anyway to implement at least the clickable link during table view?

**Comment by madd86** [comment]
My progress:

Edit crud\src\resources\views\fields\browse.blade.php drop in this download button next to browse button:

```
	  <button type="button" data-inputid="{{ $field['name'] }}-filemanager" id="download_now" class="btn btn-default download_now">
		<i class="fa fa-cloud-download"></i> Download</button>
```

Insert javascript below @push('crud_fields_scripts'):

```
	<script type="text/javascript">
		$(document).ready(function(){
			toggleDownloadButtonAccess();

			var input = document.querySelector('#proofAttach-filemanager');

			$('#proofAttach-filemanager').change(toggleDownloadButtonAccess);

			function toggleDownloadButtonAccess(){

				var $btnDownload = $('#download_now');    
				if($('#proofAttach-filemanager').val().length !=0){
					$btnDownload.attr('disabled', false);
				}
				else
				{
					$btnDownload.attr('disabled', true);        
				}
			}
		});

		$(document).on('click','.download_now[data-inputid={{ $field['name'] }}-filemanager]',function (event) {
		    event.preventDefault();
			var loc = document.getElementById('proofAttach-filemanager').value;
			var base_url = window.location.origin;
			window.open(base_url + "/" + loc);

		});
	</script>
```

Now I'm trying to figure out how to make the each row of the column 'browse' display the 'Download' text with a link to the file.

**Comment by madd86** [comment]
Downloadable link on the column:
(Oops, it was right there [on the documentation v2.0](https://laravel-backpack.readme.io/v2.0/docs/crud))

On YourCrudController:

		$this->crud->addColumn([
								'name' => 'proofAttach', //replace with your field
								'label' => 'Attachment',
                                                                'type' => "model_function",
                                                                'function_name' => 'getDownloadableLink', // the method in your Model
		 					]);

On the model:

```
 public function getDownloadableLink() {
        return '<a href="'.url($this->proofAttach).'" target="_blank">Download</a>';
    }
```

**Comment by tabacitu** [comment]
Great stuff, I'm glad you worked it out.

One tip though: instead of modifying ```browse.blade.php``` inside the /vendor/ folder, you could create a file with a similar name and path in your project. That way:
- you'll keep the ability to do ```composer update```;
- Backpack will pick it up instead of the one in /vendor/

Your new file should be in ```/resources/views/vendor/backpack/crud/fields/browse.blade.php```. You can [read more about creating a custom field type here](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types).

Cheers!

**Comment by madd86** [comment]
Thanks for replying @tabacitu, funny, I was thinking just that after I did what I did. I guess I'll copy it and introduce the custom type.

I'm loving backpack for laravel, pretty awesome.

**Comment by tabacitu** [comment]
:-) great to hear that @madd86 . Cheers!
