### ISSUE TITLE
Timeout with large datasets

### ISSUE THREAD

**Issue by webbie** [Laravel-Backpack/CRUD#324]
I have a table with over 500k records and setting CRUD over that table causes PHP timeout (30 secs).  How can I fix it?

**Comment by tabacitu** [comment]
Hi! For large datasets it's recommended that you use ajax datatables instead of the standard ones. You can do that by calling this in your controller's setup method:

$this->crud->enableAjaxTable();

Cheers!

**Comment by webbie** [comment]
Thanks, that helped.. Unfortunatelly, date column is not sortable then

**Comment by tabacitu** [comment]
Yes, it's a known limitation of Ajax datatables...
