### ISSUE TITLE
[Bug] Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::initButtons does not exist.

### ISSUE THREAD

**Issue by dimitrijev** [Laravel-Backpack/CRUD#3244]
# Bug report

### What I did

When a  setRouteName method is used in crud controller.

### What I expected to happen

??

### What happened

BadMethodCallException

### What I've already tried to fix it

I deleted that line:
 $this->initButtons();

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### LARAVEL VERSION:
v7.28.3@b0942c391975972b1a54b2dc983e33a239f169a9

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by pxpm** [comment]
Hello @dimitrijev thanks for the report.

Totally `initButtons()` have been deprecated some time ago, this must have slipped the refactor process: https://github.com/Laravel-Backpack/CRUD/pull/2000

I'v just submitted a PR to address this issue. 

Thanks,
Pedro
