### ISSUE TITLE
Posibility to trigger CRUD action with ajax?

### ISSUE THREAD

**Issue by webbie** [Laravel-Backpack/CRUD#325]
Right now, I have a checkbox that represents a field in table, and it shows checked/unchecked state.
Is there a way to make checkbox clickable on main view, so clicking on it will make a proper ajax request, and update record in table? That should be faster instead of going to edit page for each record.

**Comment by OwenMelbz** [comment]
Sure, it's not built in functionality, however it's simple enough!

1. Just add a route which handles your Ajax call
2. Create a method in your controller/trait if you wanna use it multiple times e.g. HasStatus which handles the logic 
3. Create a custom column type which house speaker your view logic.
4. You'll need to decide where you want to store custom JavaScript for your admin - then add any JS logic you want there
