### ISSUE TITLE
[Bug] exportOnlyField does not seem to work

### ISSUE THREAD

**Issue by dnwjn** [Laravel-Backpack/CRUD#3252]
# Bug report

### What I did

Inside the `setupListOperation` method of my resource's CRUD controller I added a column with `'exportOnlyField' => true` as follows:

```
$this->crud->addColumn([
    'type' => 'number',
    'name' => 'max_uses',
    'exportOnlyField' => true,
]);
```

### What I expected to happen

The column to not be visible in the column visibility dropdown.

### What happened

The column remained visible in the column visibility dropdown.

### What I've already tried to fix it

1. Seeing if `visibleInExport` and `visibleInTable` work -> `true`.
1. Seeing if the data attributes get set correctly on the table header -> `true`.
1. Clearing the local storage.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  7 2020 19:23:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.28.3@b0942c391975972b1a54b2dc983e33a239f169a9

### BACKPACK VERSION:
4.0.61@1977e0cc52fa7cf9547eaeadf03f5cd88402b574
```

MySQL version is `8.0.21`.

**Comment by pxpm** [comment]
Thanks for the report and for the fix, I am going to close this in favor of keeping the discussion in the PR.

Best,
Pedro
