### ISSUE TITLE
[Bug] select2_from_ajax defaults a selection on null column

### ISSUE THREAD

**Issue by saquack** [Laravel-Backpack/CRUD#3254]
# Bug report

### What I did

I am using select2_from_ajax on a hasOneThrough relationship.  Using the 'include_all_form_fields' => true feature I have my ajax call be dependent on the value of another field.  That works fine.  That is not the bug.  The bug appears when I edit a record and the dependent select2_from_ajax is null in the table, but is populated with the first item in the database table.

### What I expected to happen

The select2_from_ajax field should not have selected value on the edit screen when the column in the table is null.

### What happened

The null column from the table had a selected value in the select2_from_ajax field.  Note that the drop down is blank, but there is a "ghost" vale selected.

### What I've already tried to fix it

I set the ajax function to return only an empty array and and an empty string, the issue was not resolved. I believe there must be a default action in the select2_from_ajax field that is getting data from the model when the edit screen loads and not from the ajax call.  The ajax call is not made during the initial load of the edit screen, but when the drop down is clicked on.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.28.3@b0942c391975972b1a54b2dc983e33a239f169a9

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

MySQL Version 8.0.17

**Comment by pxpm** [comment]
Hello @saquack 

Thanks for the bug report.

Could you please help here to reproduce the error ? I was not able to: https://recordit.co/raRpe6X0aL

Here is my field: 

```php
$this->crud->addField([
            'name' => 'select',
            'type' => 'select2_from_ajax',
            'entity' => 'article',
            'data_source' => url($this->crud->route.'/fetch/article'),
            'method' => 'post',
            'placeholder' => 'select article',
            'minimum_input_length' => 1,
            'include_all_form_fields' => true

        ]);
```

Thanks in advance,
Pedro

**Comment by saquack** [comment]
Hello @pxpm,

Thank you for responding and helping with this issue.

[https://recordit.co/hAxgDwLDKu](https://recordit.co/hAxgDwLDKu)

In the video I'm to showing that the program_area_id column is null in the database, but the edit screen is populating a value in the select2_from_ajax field.  When I save the pre-populated value, it does update the db column with that value.  If I clear the field and save, the column returns to null.  However, when I return to the edit screen again, the sneaky value back.  I then show that I have the same issues with other users.  The last thing I show that i have one user that is not having this issue.  Which I find even more odd.

Here is the field:
[
    'label'                => "Program Area",
    'type'                 => 'select2_from_ajax',
    'name'                 => 'user.UserProfile.ProgramArea.id',
    'entity'               => 'UserProgramArea',
    'attribute'            => 'name', 
    'data_source'          => url('userProgramAreaList'),
    'placeholder'          => 'Select a Program Area', 
    'include_all_form_fields' => true, 
    'minimum_input_length' => 0, 
],

You may be curious why the Program Area dropdown is empty.  That is the expected behavior for this user type (CampAdmin).  The list does populate for other user types.

Thank you,
Stuart

**Comment by pxpm** [comment]
This is just a guess, but might be worth trying, could you setup your field name not with dots `.` but with dashes `_` ?

Indeed it's strange why it would happen in some entries but not in all. Maybe some cache stuff ? Try also: `php artisan cache:clear`

Let me know the results,
Pedro

**Comment by saquack** [comment]
Pedro,

I have cleared the cache many times, but it has not been the issue.  However, switching from dots to dashes (or even slashes) worked!  Can you explain why that made the difference?  I'm fine not using dots, but I use them in others area of Laravel.  I'm curious.

Thank you so much for the help!

**Comment by pxpm** [comment]
In Backpack we do the assumption that if the field name have dots it is a relationship, for example setting up an `User -> HasOne -> Address` your field would be something like:

```php
CRUD::field('address.street')->type('text') ....
```

In Laravel majority of dots usage is for nested navigation like in config `config('file.key.second_key')` or in `view()` .

Can I close this issue or there is something you think we can better handle ? 

Best,
Pedro

**Comment by saquack** [comment]
Sounds good.  Thanks again.

**Comment by saquack** [comment]
Pedro,

There is a problem with dashes and not dots. When using dots, the field populates with the value ing the table.  When using dashes, it does not.  See the video.

[https://recordit.co/AM0uBRC698](https://recordit.co/AM0uBRC698)

Any ideas on that?

**Comment by pxpm** [comment]
Hello @saquack, the field name should match the field name in the database. 

Best,
Pedro

**Comment by saquack** [comment]
Hi @pxpm,

I am very confused by that comment. Are you suggesting that is should have 'name => 'id'?  That doesn't work at all.  I mean the field is nearly working, but it is not behaving consistently.  When 'name' => 'user.UserProfile.Camp.id' is used the field populates based on the value in the database column.  When  'name => 'id' is used it is not.

[ 
                'label'                => "Camp - All users", // Table column heading
                'type'                 => 'select2_from_ajax',
                'name'                 => 'user.UserProfile.Camp.id', // the column that contains the ID of that connected entity;
                'entity'               => 'UserCamp', // the method that defines the relationship in your Model
                'attribute'            => 'name', // foreign key attribute that is shown to user
                'data_source'          => url('userCampList'), // url to controller search function (with /{id} should return model)
                'placeholder'          => 'Select a Camp', // placeholder for the select
                'include_all_form_fields' => true, //sends the other form fields along with the request so it can be filtered.
                'minimum_input_length' => 0, // minimum characters to type before querying results
                'allows_null' => true,
]

Thanks.

**Comment by pxpm** [comment]
Sorry for confusion. 

So imagine, you are in `CampCrudController`, that has the `CampModel` in the model you have an column that is `user_id` in your database.

```php
[
'label' => "Camp - All users", // Table column heading
'type' => 'select2_from_ajax',
'name' => 'user_id', //NOTICE HERE THE CHANGE
'entity' => 'UserCamp', // the method that defines the relationship in your Model
'attribute' => 'name', // foreign key attribute that is shown to user
'data_source' => url('userCampList'), // url to controller search function (with /{id} should return model)
'placeholder' => 'Select a Camp', // placeholder for the select
'include_all_form_fields' => true, //sends the other form fields along with the request so it can be filtered.
'minimum_input_length' => 0, // minimum characters to type before querying results
'allows_null' => true,
]
```

Hope to have clarified your issues. 

Thanks,
Pedro

**Comment by pxpm** [comment]
Closing due inactivity. 

Please re-open if the problem persists.
