### ISSUE TITLE
[Bug] If checkIfUserIsAdmin method returns false, always redirect to /home URL

### ISSUE THREAD

**Issue by mahasadhu** [Laravel-Backpack/CRUD#3255]
# Bug report

### What I did

update `checkIfUserIsAdmin` method to actually check whether the currently logged in user should be able to access backpack dashboard.

### What I expected to happen

if the `$user` is not matched the criteria, redirected to homepage or backpack login page

### What happened

keeps redirect to `/home` URL, even though that URL is not set in route. 

### What I've already tried to fix it

Updating the `respondToUnauthorizedRequest` inside the same `CheckIfAdmin` middleware. 

However apparently all backpack-prefixed URL will always redirect to `/home` URL if `checkIfUserIsAdmin` method returns false **and** if there is actually a logged in user.

How can I change this `/home` redirection URL ?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.8.0@0bdd5c6f12cb7cb6644e484169656245af417735

### LARAVEL VERSION:
v7.16.1@dc9cd8338d222dec2d9962553639e08c4585fa5b

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by mahasadhu** [comment]
The easiest way to test is, to just log in normally from `admin/login` page, then after the log in successes, change the `checkIfUserIsAdmin` method body to just `return false;`

**Comment by mahasadhu** [comment]
Nevermind, rookie mistake. 🤕 It is in `RedirectIfAuthenticated`, I need to change the `RouteServiceProvider::HOME` to the actual URL that I want. Apparently it also follows / fallback to the Laravel default authentication flow.
```
    public function handle($request, Closure $next, ...$guards)
    {
        $guards = empty($guards) ? [null] : $guards;

        foreach ($guards as $guard) {
            if (Auth::guard($guard)->check()) {
                return redirect(RouteServiceProvider::HOME);
            }
        }

        return $next($request);
    }
```

Do you think this should be mentioned in the docs and/or in the code?

**Comment by pxpm** [comment]
Hello @mahasadhu I think we removed `home` from our codebase in 4.1.17, make sure you are not overriding any files that is needed in app auth: https://github.com/Laravel-Backpack/CRUD/pull/3111

Let me know if we are talking about different issues here.

Best,
Pedro

**Comment by mahasadhu** [comment]
Hi @pxpm thanks for checking.

I think we are talking a different issue here, pretty sure my issue here can be solved by just updating the docs or add some more comments in the `checkIfUserIsAdmin` method.

I'll make PRs to this repo and the docs repo when I have time later

**Comment by tabacitu** [comment]
@mahasadhu - I just checked and you're right. It looks like in Laravel 8 they changed this. 

Previously it was:

```php
class RedirectIfAuthenticated
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     * @param string|null              $guard
     *
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if (Auth::guard($guard)->check()) {
            return redirect('/');
        }

        return $next($request);
    }
}
```

but now by default it's:

```php
class RedirectIfAuthenticated
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  ...$guards
     * @return mixed
     */
    public function handle(Request $request, Closure $next, ...$guards)
    {
        $guards = empty($guards) ? [null] : $guards;

        foreach ($guards as $guard) {
            if (Auth::guard($guard)->check()) {
                return redirect(RouteServiceProvider::HOME);
            }
        }

        return $next($request);
    }
}

```

Which is a change for the better, I guess. But it does render this use case a little bit more complicated. I've [added a note in the installation docs](https://github.com/Laravel-Backpack/docs/commit/7e8893d619558af70a8756a7f37fce40df3ad976), hopefully that will help.

Also, if anybody stumbles upon this and knows a better way to do it, WITHOUT asking the developer to do something (but while still using the `guest` middleware), we're open to ideas! 😄 

Cheers! Thanks again @mahasadhu .

**Comment by tabacitu** [comment]
Also, [added comment in CheckIfAdmin](https://github.com/Laravel-Backpack/CRUD/commit/8ca5152d395962dfb1022762f65c1f485f418940) as you suggested. Good idea!

**Comment by mahasadhu** [comment]
Thank you @tabacitu , sorry I was really busy last week so did not have time to add those PR.

**Comment by iMokhles** [comment]
@tabacitu this issue is from Laravel 7+ not only for Laravel 8+ as you mention in the doc

**Comment by mahasadhu** [comment]
@iMokhles you're right, I've made PRs to both of those changes.

**Comment by pierluromani** [comment]
This actually saved my life, but how come, if I am a normal user after trying to access the admin panel and getting redirected away, I can't try to login again? Is this how it should be?

**Comment by mahasadhu** [comment]
@pierluromani 

If that normal user that you said does not have access to the admin panel, then yes I think that's how it should be

If that user wants to login again, they can always log out first, then access the login page again.

or am I misunderstood your question here? 😕
