### ISSUE TITLE
[Bug] jQuery.Deferred exception: Cannot read property 'top' of undefined TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/CRUD#3268]
# Bug report

### What I did
use type repeatable field have error
??

### What I expected to happen

??

### What happened
![error2](https://user-images.githubusercontent.com/676859/96211259-0484e600-0f9e-11eb-9a4c-fd3a31580248.jpg)
![error1](https://user-images.githubusercontent.com/676859/96211166-c687c200-0f9d-11eb-8184-de8653ed153d.jpg)

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.8 (cli) (built: Jul  9 2020 11:30:39) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.22.4@30e851a2b3a2af73fba0b7f4fa22b04260db98e7

### BACKPACK VERSION:
4.1.15@6c751de946a9c8511dd32eb7bfa3ca6a568849f5

**Comment by pxpm** [comment]
Hello @gumpon 

Thanks for opening your issue. I am inclined to say the this must be some misconfiguration from your side, or something very weird that escaped us. 

Can you please share your repeatable field definition ? 

What I would do to debug is commenting out all your repeatable fields and start uncommenting one by one (this would allow us to check if it's some specific field that is breaking repeatable).

Did this happen on both Create/Update forms ? 

Best,
Pedro

**Comment by gumpon** [comment]
I'm found my problem because use duplicate name. Thankyou for your support.

**Comment by pxpm** [comment]
Hello @gumpon thanks for sharing you findings, might help someone with the same error in future.

Wish you the best,
Pedro
