### ISSUE TITLE
can i update crud after installation?

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#327]
Hi!
i have installed crud package but after that i found new fixes , improvement and upgrades in that package
can i just update this package alone?

**Comment by tabacitu** [comment]
Hi @c1t1zen ,

Yes you can. You can find the upgrade guides in the documentation: https://laravel-backpack.readme.io/docs/upgrade-guides

Cheers!

**Comment by tabacitu** [comment]
Any other minor update can easily be done with ```composer update```.
