### ISSUE TITLE
Mutator not called with Repeatable field 

### ISSUE THREAD

**Issue by gregraab** [Laravel-Backpack/CRUD#3279]
# Bug report

### What I did
Updated backpack via composer update

### What I expected to happen
Was done to get a bug fix that was causing an issue.  I do not remember the exact issue I was getting 

### What happened

Mutators appear to be broken for repeatable fields.  I broke it down to the most simple case after coming to this conclusion and it appears that the Accessor is called on a repeatable but mutator is never fired.

Simple create operation:

`

// In CRUD, simple create to test

    protected function setupCreateOperation()
    {

        $this->crud->setValidation(GenderRequest::class);

        $this->crud->addField([
            'name' => 'name',
            'label' => 'Name',
            'type' => 'text',
            'wrapper' => ['class' => 'form-group col-md-6'],
        ]);

        $this->crud->addField( [
            'name' => 'repeatTest',
            'label' => 'Repeatable Test',
            'type' => 'repeatable',
            'fields' => [
                [
                    'name' => 'testfield',
                    'type' => 'text',
                ],
            ],
        ]);

    //.... On model:  setRepeatTestAttribute is never fired.  Other accessors and mutator are called.

    public function getNameAttribute($value) {
        $var = 1100;
    }

    public function setNameAttribute($value) {
        $var = 1200;
    }

    public function getRepeatTestAttribute($value) {
        $var = 1300;
    }

    public function setRepeatTestAttribute($value) {
        $var = 1400;
    }
`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.15 (cli) (built: Mar  9 2020 03:13:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.15, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.28.4@de187e9200948bab6975167e480950abcd5efdac

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by pxpm** [comment]
Hello @gregraab thanks for the report. 

I don't think there is a bug here, I just tested and mutator fires for repeatable field, so my guess is that is something you bad implemented here. 

So here is my guess: you are trying to setup a mutator for a repeatable field but that repeatable field is not an attribute in your model. 

What I mean with this ? Mutators will only fire when you try to set some model attribute. In your example your mutator would fire if your model has an attribute `repeatTest`. 

As an example, if your model has an attribute `my_model_attribute`:

```php
//mutator
public function setMyModelAttribute() {
    dd($this)
}

//this field would fire the mutator:
$this->crud->addField( [
        'name' => 'my_model_attribute', //notice here that the field name is an attribute in model
        'label' => 'Repeatable Test',
        'type' => 'repeatable',
        'fields' => [
            [
                'name' => 'testfield',
                'type' => 'text',
            ],
        ],
    ]);

//this would not fire the mutator because there is no `repeatTest` attribute in model. 
$this->crud->addField( [
        'name' => 'repeatTest',
        'label' => 'Repeatable Test',
        'type' => 'repeatable',
        'fields' => [
            [
                'name' => 'testfield',
                'type' => 'text',
            ],
        ],
    ]);
```

I am going to close this as I don't think this is a bug. I could be wrong, if that is the case please re-open.

Wish you the best,
Pedro

**Comment by AndresLealColon** [comment]
Same happened for me, my code was working good and after update stop calling mutator :S

**Comment by mahasadhu** [comment]
Just a small suggestion, maybe try to change the field name into a snake_case ? So instead of `repeatTest` change the field name to `repeat_test`. 

I was banging my head for a couple of days because of that small mistake

**Comment by mahasadhu** [comment]
And also, for this exact same case, I was not using any fake attribute for my field.
Note: `clients_json` field is not available in the table. And I also did not add it as a additional attribute in the eloquent model

Field:
```
CRUD::field('clients_json')
            ->label(trans('backpack::base.subjects'))
            ->type('repeatable')
            ->fields([
                [
                    'label'     => trans('backpack::base.client'),
                    'type'      => 'select2_from_ajax',
                    'name'      => 'client_id', 
                    'entity'    => 'clients', 
                    'attribute' => 'name', 
                    'data_source' => backpack_url('project/fetch/client'),
                    'wrapper' => ['class' => 'form-group col-md-6'],
                    'placeholder'             => trans('backpack::base.choose_client'), 
                    'minimum_input_length'    => 2, 
                    'method'                  => 'POST', 
                    'include_all_form_fields' => false,
                ],
                [
                    'name'    => 'pihak',
                    'type'    => 'text',
                    'label'   => 'Pihak',
                    'attributes' => [
                        'placeholder' => 'Pihak Pertama',
                    ],
                    'wrapper' => ['class' => 'form-group col-md-6'],
                ],
            ])
            ->new_item_label(trans('backpack::base.add_client'));
```

Model Accessor and Mutator:
```
    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    public function getClientsJsonAttribute()
    {
        return $this->getAttributeFromPivotToRepeatable($this->clients);
    }

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */

    public function setClientsJsonAttribute($data)
    {
        if ($this->id) {
            $this->clients()->sync($this->setAttributeFromRepeatableToPivot($data, 'client_id'));
        }
    }
```
