### ISSUE TITLE
select_from_array issue

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#328]
when i use:
        $this->crud->addField([ // select_from_array
    'name' => 'template',
    'label' => "Template",
    'type' => 'select_from_array',
    'options' => [ 'one' => 'one', 'one' => 'one'],
    'allows_null' => false,
    // 'allows_multiple' => true, // OPTIONAL; needs you to cast this to array in your model;
]);
      
i got the following error:
Undefined index: value (View: E:\xampp\htdocs\Laravel\elwaseet\vendor\backpack\crud\src\resources\views\fields\select_from_array.blade.php) (View: E:\xampp\htdocs\Laravel\elwaseet\vendor\backpack\crud\src\resources\views\fields\select_from_array.blade.php) (View: E:\xampp\htdocs\Laravel\elwaseet\vendor\backpack\crud\src\resources\views\fields\select_from_array.blade.php)

i idont want to change core files like :
http://stackoverflow.com/questions/41317503/how-to-add-select-from-array-in-backpack-for-laravel-page-create

**Comment by OwenMelbz** [comment]
Hi, Its always worth searching for previous issues :)

https://github.com/Laravel-Backpack/CRUD/issues?utf8=%E2%9C%93&q=Undefined%20index%3A%20value

**Comment by c1t1zen** [comment]
thank you it's bug 
hope will fix soon

**Comment by tabacitu** [comment]
Fixed! Please check out https://github.com/Laravel-Backpack/CRUD/issues/312. Cheers!
