### ISSUE TITLE
[Bug] custom_html does not allow to insert unclosed html tags

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#3283]
refs: #1819 

# Bug report

When we introduced wrappers to the fields we broken the ability to insert custom tags around a group of fields because they will self close when contained inside the wrapper element.

```php
 $this->crud->addField([   // CustomHTML
            'name' => 'fieldset_open',
            'type' => 'custom_html',
            'value' => '<fieldset>'
        ]);

//output

<div>
<fieldset>
</fieldset> //we are not adding this, it's auto closed because it's contained inside the field wrapper div
</div>
```

### What I did

Tried to create a fieldset inside a crud form.

```php
        $this->crud->addField([   // CustomHTML
            'name' => 'fieldset_open',
            'type' => 'custom_html',
            'value' => '<fieldset>'
        ]);
        $this->crud->addField([
            'name' => 'wysiwyg',
            'type' => 'tinymce'
        ]);
        $this->crud->addField([   // CustomHTML
            'name' => 'fieldset_close',
            'type' => 'custom_html',
            'value' => '</fieldset>',
        ]);
```

### What I expected to happen

My field beeing wrapped inside the fieldset.

### What happened

The fieldset element is autoclosed because it's contained inside the wrapper div.

### What I've already tried to fix it

Remove wrapper from `custom_html.blade.php`

I think when we first started working on wrapper we left `custom_html` out, and then put it back in to make all fields have the same functionality. 

If it's a custom_html, the wrapping of the field should be done by developer @tabacitu ?

I think we have two solutions:

1 - Remove wrapper from custom_html field. 

2 - Introduce `wrapper => false` to disable field wrapping.

I would vouche for the second as it would allow to disable wrapper in other fields too. 

Let me know @tabacitu ! o/

Best,
Pedro

**Comment by tabacitu** [comment]
I agree with your @pxpm .

For solution 1 (removing wrapper from `custom_html` field)... we don't actually know how that would impact existing apps, so we'd have to push that as a breaking change maybe.

But solution 2 - I think that's a pretty nifty one @pxpm ! And intuitive. Plus:
- if we introduce the functionality to do `wrapper => false`, we'd only need to change `wrapper_start` and `wrapper_end`; so the change would be pretty surgical;
- it would be backwards-compatible; so far nobody's been using `wrapper => false`, we know that; 

So I agree with you, `wrapper => false` sounds better!

**Comment by rabol** [comment]
Why do you not just let the custom_html be custom_html and output what ever is in value ?

**Comment by pxpm** [comment]
@rabol hey \o nice to see you here. 

I think we have 3 reasons for keeping the `wrapper` in custom_html field. I will try to rephrase what me and @tabacitu said so it might become clearer. 

1 - We need a way to disable wrapper anyway (in some field you might not want it to be wrapped).
2 - It is currently supported, so people might be using it.
3 - If 1 is going to be mandatory for Backpack, there is no sense in having all fields with wrapper, and custom_html without. Even if you create a custom field for your needs, and you don't want the wrapper, just disable it. 

I see your point of view, I have the same opinion when it comes to `real usability` of custom_html field, but as a developer, if you are aware of wrapper functionality (beeing a closure etc) it can `make your custom html clear`. What I mean by this is that if you want to switch your `custom_html` wrapping between a `span` and a `div`, using wrapper functionality would make the field SO, SO much cleaner. 

Let me know if you still feel we are overlooking something here.

Best,
Pedro

**Comment by rabol** [comment]
well.. I like to use a function for it's purpose :)

The custom_html is not called custom_html_with_wrapper

in my case I wanted to use it to add custom_html before some controls in a form but that does not work as it wrap my html in a div

I made my own 'custom_html' field.

There are many of these 'quirks' in Backpack and I hop v5 will be a re-write and cleanup

**Comment by pxpm** [comment]
None of backpack fields uses `field_wrapper` naming convention, but they all support it. 

In my understanding, the wording here is: `Backpack wraps your field with a custom wrapper that you can configure or disable`. 

Having this, there is no reason for customizing the field, just enable or disable some functionality based on your needs. 

Backpack is very extensible, that's why you find some `quirks`, we try to document them all, and not impose something (let it be configurable). We want the extensible part to be easily done when needed, but we want to reduce it the most possible. 

What have been happening in Backpack is that we try to identify the bootlenecks developer finds while using the software, or the expectations for an admin panel and improve those scenarios, like FetchOperation and InlineCreate, the plans we have for repeatable and relationships etc etc. 

What makes us improve is user feedback, that we much appreciate. If you find more of this `quirks` let us know if you think there is something we can do to improve developer experience 👍 

Best,
Pedro

**Comment by rabol** [comment]
so how do I avid that the custom_html add a <div> around my html ?

from the documentation:

https://backpackforlaravel.com/docs/4.1/crud-fields#custom_html


[   // CustomHTML
    'name'  => 'separator',
    'type'  => 'custom_html',
    'value' => '<hr>'
],

this wrap the <hr> in a <div> for no reason

**Comment by tabacitu** [comment]
> so how do I avoid that the custom_html add a <div> around my html ?

In Backpack 4.2 (after we fix this) you'll be able to do just that, and it won't wrap anything. The wrapping functionality will be there, but it would be false by default.

I think that's the best compromise in this case:
- we provide the wrapping functionality, because all fields have it;
- but for this particular field it would be disabled by default, because that's what makes more sense in the 80% use case;

But we really should consider this a breaking change, so we can only introduce it in 4.2 unfortunately. Until then, your custom custom_html field should do just fine! The upgrade guide will then tell you this changed 😉

**Comment by rabol** [comment]
We could also keep it 'on' as default, with the option to turn it off, then it will not be a breaking change

**Comment by CamusMX7** [comment]
I read all the messages but it is not clear to me. What is currently the best option for grouping fields?
I understand that it is an update that is not yet complete.
I think it is very common cases like the form in the attached image.
![ejemplo](https://user-images.githubusercontent.com/107073227/172472184-e11324b5-ea6c-49cc-b14f-802477af8833.JPG)

**Comment by pxpm** [comment]
I converted this into two PR's. 

https://github.com/Laravel-Backpack/PRO/pull/86 and https://github.com/Laravel-Backpack/CRUD/pull/4625

Closing in favor of keeping any discussion regarding this in https://github.com/Laravel-Backpack/CRUD/pull/4625
