### ISSUE TITLE
[Bug] checklist lost 'old' values if form submitted with validation errors

### ISSUE THREAD

**Issue by pkuzz** [Laravel-Backpack/CRUD#3291]
# Bug report

### What I did

I have a form with checklist and textfield with some validation rules. 
If I edit textfield to "wrong" value and try to submit form than checklist's checkboxes are cleared

### What I expected to happen

Old checkboxes values of checklist should remain in state when form is submitting

### What I've already tried to fix it

I've found that in `checklist.blade.php` *old* value of checklist (which is actually a string) not converted to array.
Possible fix: add following lines at line 19 of `checklist.blade.php` (but not sure if this is correct approach, as I'm not a php guru)
```
  if (is_string($field['value'])) {
      $field['value'] = array_map('intval', explode(',', str_replace(['[', ']'], ['', ''], $field['value'])));
  }
```

### Backpack, Laravel, PHP, DB version

Reproducible in [demo](https://demo.backpackforlaravel.com/).
* Edit some monster
* On Relationships tab check some Chechlist box and 'Save and edit this item'
* Go to Simple tab, clear Text field and try to save
* As validation fails, goto Relationships tab and see that Chechlist's boxes are clear

**Comment by pxpm** [comment]
Hello @pkuzz 

Thanks for submitting your report. 

I think this is related with #525 , #1816 and we are hopefully fixing it in #3054, but we can only do it in 4.2 as it is a BC.

I will leave this open until we can confirm that #3054 fixes this.

Best,
Pedro

**Comment by pkuzz** [comment]
Oh, I didn't find that issues, sorry :)
For now, I worked around it by overriding `checklist` with code from my comment, so will wait for 4.2 patiently, thanks!

**Comment by promatik** [comment]
https://github.com/Laravel-Backpack/CRUD/pull/3377 besides adding new capabilities to checklist field, also solved this

Thank you for submitting the issue @pkuzz, if you still have any problems using the field please reopen 👍
