### ISSUE TITLE
Entry not update with same model in column select

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/CRUD#3292]
I use **user** model to display two column with different **entity** , But in select column blade it did not update _entry_ and always return the first record.

**Comment by pxpm** [comment]
@bahman2216 hello and thanks for the report. 

I am sorry but I was unable to understand what you are trying to achieve, could you please clarify, maybe show some code?

Best,
Pedro

**Comment by bahman2216** [comment]
Sorry for bad explanation. Here is my code:
`        CRUD::addColumns([
            [
                'label' => trans('user'),
                'name' => 'user_id',
                'type' => 'select',
                'entity' => 'user',
                'attribute' => 'name',
                'model' => 'App\User',
            ],
            [
                'label' => trans('agent'),
                'name' => 'agent_id',
                'type' => 'select',
                'entity' => 'agent',
                'attribute' => 'name',
                'model' => 'App\User',
            ],`
]);

Imagine you have **User** model with two rules: **User** and **Agent**.
For Second column(Agent) it returns previous entity(User entity not Agent entity) in select blade.

**Comment by promatik** [comment]
Hi @bahman2216, I did a test myself and it worked as expected.

Can you please check if your `User.php` Model has the correct configuration?
Something like this;

```
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function agent()
    {
        return $this->belongsTo('App\User', 'agent_id');
    }
```

**Comment by bahman2216** [comment]
Hi @promatik , Yes my model is exactly same above. I mean the issue is in **$entry**.
If you log it in `select.blade you` can find the issue.
`Log::info($entry);`

**Comment by promatik** [comment]
@bahman2216 I tried to replicate the problem on backpack demo by creating 2 category columns on the Article CRUD. And it works as expected;

```php
// Model
public function category()
{
    return $this->belongsTo('Backpack\NewsCRUD\app\Models\Category', 'category_id');
}

public function category2()
{
    return $this->belongsTo('Backpack\NewsCRUD\app\Models\Category', 'category_id_2');
}
```
```php
// Controller
CRUD::addColumn([
    'label' => 'Category',
    'type' => 'select',
    'entity' => 'category',
]);

CRUD::addColumn([
    'label' => 'Category 2',
    'type' => 'select',
    'entity' => 'category2',
]);
```

> ![image](https://user-images.githubusercontent.com/1838187/97974536-a76f9980-1dbf-11eb-94a0-e6c24ed5ec54.png)

Does your user model has some special code? related with the agent?

**Comment by bahman2216** [comment]
Hi @promatik ,
It is my fault in `select.blade`. I used $entry with wrong way and just fix it. My model same as your and it works as expected.
Thanks for your reply.
