### ISSUE TITLE
Dynamically adding new items to the database via select2 

### ISSUE THREAD

**Issue by madd86** [Laravel-Backpack/CRUD#330]
The logic should be simple enough.

1. Route that calls a function on the controller. Perhaps something like category/create/{name}

2. Function on the controller will then add the new request to the database.

3. This is the complicated part. Instead of returning "No Matches Found" on select2 when you type something that doesn't exist, there should be a clickable link with something like, "Add new record" to add the typed text to the database. It'd be good to refresh only the view instead of the whole page, not sure how to do that.

I'm not proficient enough in Javascript to dab in select2.js, any help?

**Comment by OwenMelbz** [comment]
Hey,

There's already a feature request for this in the backlog.

Here's the other thread https://github.com/Laravel-Backpack/CRUD/issues/288

I'll close this for now :)

**Comment by madd86** [comment]
@OwenMelbz just wanted to tell you that I made it work, I can share it here if you wish.

It's far from perfect, but it works. The only drawback is that it reloads the whole form.

I did some tinkering on the javascript (copied it and created my own, just so I can update in the future).

this is the result
![add-new](https://cloud.githubusercontent.com/assets/23120598/21534082/049944ce-cd49-11e6-8438-b8b22d5639b2.PNG)

When I click add new it fires this function on the controller: 

```
    public function dynCreate(Request $request)
	{
        $category = new Category;

        $category->name = $request->name;

        $category->save();
        return back();
	}
```

Very crude, I know, but it works fine, couldn't be happier for now.

**Comment by tabacitu** [comment]
@madd86 , it sounds to me like a you've created a great starting point for this functionality. 

The actual feature implementation might suffer some changes and take some more time, but if you post your working code here (both the custom field and the method in the controller), I'm sure you're going to help a lot of people.

Thanks, cheers!

**Comment by cristianuibar** [comment]
@madd86 I am interested in this functionality if you care to share your implementation? 😄

**Comment by tabacitu** [comment]
I second that :-) 

**Note to self:** it might make more sense to start from the ```select2_from_ajax``` field, so that there's no need to reload the page after the entry has been added.

**Comment by virla01** [comment]
I'm interested! someone could pass the code, thank you very much!
