### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by potkot** [Laravel-Backpack/CRUD#3303]
# Bug report

In the controller method setupCreateOperation Field with the select2_nested type, the depth field is not updated on save.

### MYSQL VERSION
Mysql 5.7

### PHP VERSION:
PHP 7.3.2 (cli) (built: Feb  5 2019 22:55:35) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v8.12.3@6707480c5f0db7aa07537f9ad93255b64b65b85e

### BACKPACK VERSION:
4.1.26@ae68ca24844929ac38d2e792197551e823c43570

**Comment by pxpm** [comment]
Hello @potkot 

Thanks for raising this issue. 

From my understanding `select2_nested` is not intended to save the depth, it's intended to show you the items you can select with some depth ordering (that you should previously setup in your model: https://backpackforlaravel.com/docs/4.1/crud-fields#select2_nested)

I don't think there is a bug here, if I am wrong, please re-open.

Best,
Pedro
