### ISSUE TITLE
[Bug] Install backpack on new laravel 8.4 installation

### ISSUE THREAD

**Issue by slservice** [Laravel-Backpack/CRUD#3306]
# Bug report

Set up a develop environment with homestead and vagrant.
Created a new laravel project (laravel new lst)
Followed the installation manuel to install backpack
-> Execute composer require backpack/crud:"4.1.*"
-> I receive an error
-> After the error, I'm unable to follow the rest of the installation

Since I'm new to laravel, there is a high possibility that I missed something.
But creating new projects with other plugins like voyager, infyom, ... worked without any problems.

### What I expected to happen

That I could install laravel backpack

### What happened

Error message:

./composer.json has been updated
Running composer update backpack/crud
Loading composer repositories with package information
Updating dependencies
Lock file operations: 7 installs, 0 updates, 0 removals
  - Locking backpack/crud (4.1.26)
  - Locking composer/package-versions-deprecated (1.11.99)
  - Locking creativeorange/gravatar (v1.0.20)
  - Locking doctrine/cache (1.10.2)
  - Locking doctrine/dbal (2.12.0)
  - Locking doctrine/event-manager (1.1.1)
  - Locking prologue/alerts (0.4.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing composer/package-versions-deprecated (1.11.99): Extracting archive
Plugin initialization failed (include(/home/vagrant/projects/lst/vendor/composer/package-versions-deprecated/src/PackageVersions/Installer.php): failed to open stream: No such file or directory), uninstalling plugin
  - Removing composer/package-versions-deprecated (1.11.99)
    Install of composer/package-versions-deprecated failed

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

                                                              
  [RuntimeException]                                          
  Could not delete /home/vagrant/projects/lst/vendor/compose  
  r/package-versions-deprecated/src:                          
                                                              

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

### What I've already tried to fix it

Tried several new projects but all the same problem

**Comment by promatik** [comment]
Hi @slservice!
Welcome to backpack 🎉

Just to make sure, I tried myself to run all the steps and it worked as expected.
It appears the error was due to `composer/package-versions-deprecated`; "Plugin initialization failed", "No such file or directory".

Have you tried to run the installation one more time? The lack of the file may be because of a temporary loss of internet connection while installing, or some other composer error.

If it didn't work, try deleting the vendor folder, and run `composer install` once again.

**Comment by slservice** [comment]
Thanks for your help.

I'm new to laravel and I'm looking into backpack atm, since it has a lot of potential. I'm looking forward to explore it full features to create a new app.

I solved my issue by mapping the folders in my homstead configuration as nfs instead of the default
