### ISSUE TITLE
403 Forbidden. - On a custom function

### ISSUE THREAD

**Issue by madd86** [Laravel-Backpack/CRUD#331]
The route: 

`Route::get('admin/category/xdrop/{id}', 'Admin\CategoryCrudController@dynCreate');`

The function on the controller:

```
    public function dynCreate(Category $id)
	{
        dd($id);
	}
```

I'm not doing anything special yet, but I still get 403 permission denied. Probably because of the introduction of wildcards.

How can I allow wildcards to logged in individuals?

**Solved it**

*Still trying to figure out how lol*

**Comment by OwenMelbz** [comment]
What exactly are you trying to do? It may be that there's a better way to achieve what you want, as it looks like you might be trying to do something which backpack wasn't designed for which is why your having trouble.

**Comment by madd86** [comment]
The problem was the link created through javascript, changing it to href worked just fine.

You can close this topic, thanks.

**Comment by nguyenhiepvan** [comment]
> The route:
> 
> `Route::get('admin/category/xdrop/{id}', 'Admin\CategoryCrudController@dynCreate');`
> 
> The function on the controller:
> 
> ```
>     public function dynCreate(Category $id)
> 	{
>         dd($id);
> 	}
> ```
> 
> I'm not doing anything special yet, but I still get 403 permission denied. Probably because of the introduction of wildcards.
> 
> How can I allow wildcards to logged in individuals?
> 
> **Solved it**
> 
> _Still trying to figure out how lol_

how to solove? please
