### ISSUE TITLE
[Feature Request] PolyMorph support

### ISSUE THREAD

**Issue by lambasoft** [Laravel-Backpack/CRUD#3310]
# Feature Request

### What's the feature you think Backpack should have?

I don't know if this is possible, but I couldn't find it's documentation anywhere, nor it's code implementation. But it seems that it's not possible to add a polymorphic one-to-one crud field?

I have 3 models:

1. Business
2. User
3. Payment

Payments have a fromable column, which is a polymorph between Business and User. In other words, a payment can be either from a user or a business.

Do we have a crud field that would work on my fromable field? 

Any suggestions of a workaround to get it working?

**Comment by promatik** [comment]
Hi @lambasoft!
In a situation like this I would create two fields `user` and `business`, and make one of them mandatory on create/update.
For the column on the list, I would do an accessor;

Model:
```php
public function getFromableAttribute()
{
    return $this->user->name ?? $this->business->name;
}
```

Controller:
```php
CRUD::addColumn([
    'name' => 'fromable',
    'label' => __('Fromable'),
]);
```

Does this solves your problem?

Regards,

**Comment by lambasoft** [comment]
@promatik 

Thank you for answer, I think it placed me on the right track.

What about the create operation, is this the right field to add for From Business:

        $this->crud->addField([    // Select2Multiple = n-n relationship (with pivot table)
            'label'     => "From Business",
            'type'      => 'select2_multiple',
            'name'      => 'fromable', // the method that defines the relationship in your Model

            // optional
            'entity'    => 'fromable', // the method that defines the relationship in your Model
            'model'     => "App\Models\Business", // foreign key model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'morph'     => true, // on create&update, do you need to add/delete pivot table entries?
        ]);

In my Business model I have 

    public function payments_from(){
        return $this->morphMany(Payment::class, 'fromable');
    }

    public function payments_to(){
        return $this->morphMany(Payment::class, 'toable');
    }


Thank you for your help, really appreciated

**Comment by lambasoft** [comment]
To anyone having such problem in the future, I solved it by creating a custom field type called "select2_polymorph" that combines a dynamic number of morphs into 1 select, so in my case I have a select that combines all available Users and Businesses into 1 select (I didn't want to create 2 selects for each) and overwriting the store function.

My Store function:

```
public function store()
    {

        $morphableClass = $this->crud->getModel()->getMorphClass();
        $morphableClass = new $morphableClass();
        foreach ($this->crud->getRequest()->request as $input => $value) {
            if (method_exists($morphableClass, $input) && is_callable(array($morphableClass, $input))) {
                $callable = $morphableClass->{$input}();
                if ($callable instanceof MorphTo && Str::contains($value, ["[", "]"])) {
                    $morphClass = Str::before($value, "[");
                    $morphClassKey = Str::between($value, "[", "]");
                    if (class_exists($morphClass) && is_numeric($morphClassKey)) {
                        $this->crud->removeField($input);
                        $this->crud->getRequest()->request->remove($input);

                        $this->crud->getRequest()->request->add([
                            $callable->getMorphType() => $morphClass,
                            $callable->getForeignKeyName() => $morphClassKey
                        ]);
                        $this->crud->addField(['type' => 'hidden', 'name' => $callable->getMorphType(), 'value' => $morphClass]);
                        $this->crud->addField(['type' => 'hidden', 'name' => $callable->getForeignKeyName(), 'value' => $morphClassKey, 'entity' => False]);
                    }

                }
            }
        }

        $response = $this->traitStore();
        // do something after save
        return $response;
    }
```

Usage of the custom field:

        $this->crud->addField([   // Custom Field
            'name' => 'fromable',
            'label' => 'From',
            'type' => 'select2_polymorph',
            'hint' => 'HINT GOES HERE',
            'model' => \App\Models\Payment::class, // The main model
            'morphs' => [
                \App\Models\Business::class,
                \App\Models\User::class
            ], // The Models I'd like to combine in the select2
            'attribute' => 'OptionValue', // A mutator I created to append the model name in front of the value so user knows from which model the option is       
        ]);

My custom field:
```
<!-- select2_polymorph -->
@php
    $current_value = old($field['name']) ?? $field['value'] ?? $field['default'] ?? '';
    $entity_model = $crud->model;

    //if it's part of a relationship here we have the full related model, we want the key.
    if (is_object($current_value) && is_subclass_of(get_class($current_value), 'Illuminate\Database\Eloquent\Model') ) {
        $current_value = $current_value->getClassKey();
    }

    if (!isset($field['options'])) {
        $options = collect();
        foreach ($field['morphs'] as $morph) {
            $options = $options->merge($morph::all());
        }
    } else {
        $options = call_user_func($field['options'], $field['model']::query());
    }


    if(isset($field['morphs'])){
        $morphs = collect($field['morphs'])->filter(function($class){
            return is_subclass_of($class, 'Illuminate\Database\Eloquent\Model');
        });
        $morph_tables = collect($morphs)->map(function($item, $key){
            return $item::getTableName();
        })->toArray();
    }

@endphp

@include('crud::fields.inc.wrapper_start')

<label>{!! $field['label'] !!}</label>
@include('crud::fields.inc.translatable_icon')


<select
    name="{{ $field['name'] }}"
    style="width: 100%"
    data-init-function="bpFieldInitSelect2Element"
    @include('crud::fields.inc.attributes', ['default_class' =>  'form-control select2_field'])
>

    @if ($entity_model::isColumnNullable($field['name']))
        <option value="">-</option>
    @endif

    @if (count($options))
        @foreach ($options as $option)
            @if($current_value == $option->getClassKey())
                <option value="{{ $option->getClassKey() }}" selected>{{ $option->{$field['attribute']} }}</option>
            @else
                <option value="{{ $option->getClassKey() }}">{{ $option->{$field['attribute']} }}</option>
            @endif
        @endforeach
    @endif
</select>

{{-- HINT --}}
@if (isset($field['hint']))
    <p class="help-block">{!! $field['hint'] !!}</p>
@endif
@include('crud::fields.inc.wrapper_end')

{{-- ########################################## --}}
{{-- Extra CSS and JS for this particular field --}}
{{-- If a field type is shown multiple times on a form, the CSS and JS will only be loaded once --}}
@if ($crud->fieldTypeNotLoaded($field))
    @php
        $crud->markFieldTypeAsLoaded($field);
    @endphp

    {{-- FIELD CSS - will be loaded in the after_styles section --}}
    @push('crud_fields_styles')
        <!-- include select2 css-->
        <link href="{{ asset('packages/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('packages/select2-bootstrap-theme/dist/select2-bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    @endpush

    {{-- FIELD JS - will be loaded in the after_scripts section --}}
    @push('crud_fields_scripts')
        <!-- include select2 js-->
        <script src="{{ asset('packages/select2/dist/js/select2.full.min.js') }}"></script>
        @if (app()->getLocale() !== 'en')
            <script src="{{ asset('packages/select2/dist/js/i18n/' . app()->getLocale() . '.js') }}"></script>
        @endif
        <script>
            function bpFieldInitSelect2Element(element) {
                // element will be a jQuery wrapped DOM node
                if (!element.hasClass("select2-hidden-accessible")) {
                    element.select2({
                        theme: "bootstrap"
                    });
                }
            }
        </script>
    @endpush

@endif
{{-- End of Extra CSS and JS --}}
{{-- ########################################## --}}

```


@tabacitu @pxpm If you guys find this may be useful, I can create a PR for the custom field.

**Comment by promatik** [comment]
@pxpm you told me you've already made some progress on a PolyMorph field, can you take a look at @lambasoft code and check if it helps?

**Comment by tabacitu** [comment]
@pxpm would PR #3410 fix this use case too?

**Comment by tabacitu** [comment]
Hey guys,

Catching up on old issues and found this. @lambasoft - in Backpack v5 we have a built-in solution for polyorphic relationships... the `relationship` field. Take a look at this breakdown of [what field should I use for X type of relationship](https://backpackforlaravel.com/docs/5.x/crud-how-to#what-field-should-i-use-for-a-relationship-1), it'll explain what you can do for all types of polymorphic relationships.

Cheers!
