### ISSUE TITLE
[Bug/Feature] Auto-fill Field with entity option when the name is the same as function of the Model in Controller 

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/CRUD#3323]
# Bug report

### What I did

Added Crud field with the method `\Backpack\CRUD\app\Library\CrudPanel\Traits\Fields::addField` that has **name** option to be the same as the Model method and one of the basic **type**, in my case, it was **table**.

I have the model `\App\Models\User` it has the method `permissions`. In my case, I have to have custom permissions logic. By that, I've added a specific field called *permissions*. By that, I was not able to update my user, as I had an error with the Permissions entity model as by default my field was extended with the next options:

- entity => permissions
- relation_type => MorphToMany
- model => App\Models\Permission

### What I expected to happen

I don't expect my model to be extended with the entity details when data values are processed as the relation. I need to have it as the simple value expected for the table field type.

### What I've already tried to fix it

Looking into the code I found that it's possible to define the option `entity => false,` for the field and that will solve the issue.

This logic seems like is not described in the Documentation. 
Maybe don't have the auto definition of the **entity** field value, as this has appeared in the latest 4.1 version.

### LARAVEL VERSION:
v7.29.2@0fb15ae253c3a043f2c5cbf9641427a7646ea77a

### BACKPACK VERSION:
4.1.26@ae68ca24844929ac38d2e792197551e823c43570

**Comment by pxpm** [comment]
Hello @mialex 

Thanks for the report. 

I'v just submited an PR to the docs to add a note about it. https://github.com/Laravel-Backpack/docs/pull/199

Wish you the best,
Pedro
