### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cobreen** [Laravel-Backpack/CRUD#3328]
# Bug report

### What I did
I added scope to the boot method
??

### What I expected to happen
on edit I expected form
??

### What happened
Crud controller ignored scope and failed to find entry
??

### What I've already tried to fix it
Override Controller methods
??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
Command "backpack:version" is not defined.

composer.json
"backpack/backupmanager": "^1.4",
"backpack/crud": "^3.6",
 "backpack/logmanager": "^2.3",
 "backpack/menucrud": "^1.0",
 "backpack/settings": "^2.1",

**Comment by promatik** [comment]
Hi @cobreen, welcome to backpack!
Can you please add the relevant parts of your code? I've used a lot of "global" scopes on boot of my models, and it works as expected.

**Comment by pxpm** [comment]
Hello @cobreen 

I don't think this is a bug in Backpack and agree with @promatik , I too use lots of global and non-global scopes with backpack.

It's been 3 days without more information so I am going to close this. 

If I am wrong, and sometimes I am, please feel free to re-open or reply here even if closed.

Wish you the best,
Pedro
