### ISSUE TITLE
Upgrading to 3.2?

### ISSUE THREAD

**Issue by slickorange** [Laravel-Backpack/CRUD#333]
Hi, I followed the instructions to upgrade to 3.2 (https://laravel-backpack.readme.io/docs/whats-new-november-2016) - although I did not see the 3.2 release, but only the dev one.

I still get the old Save buttons. Any ideas?

**Comment by OwenMelbz** [comment]
Hey,

It's probably easier to update your composer.json to

'backpack/crud": "^3.2 as 3.1"'

To make sure other packages are happy.

Then run 'composer update' and paste us the output

You'll also need to make sure you republish any form related views like form_content etc

**Comment by tabacitu** [comment]
Hi @slickorange ,

Backpack\CRUD 3.2 is not officially released yet. We're waiting for Laravel to move to 5.4, so we can bump the version at the same time. This way, developers will only need to go through the upgrade process once, for both Laravel and Backpack.

If you want to be ahead of the curve and use Backpack 3.2 right now, you can use the process Owen has described above.

Cheers!
