### ISSUE TITLE
[Bug] Possible bug when try use $this->crud->removeAllSaveActions() method

### ISSUE THREAD

**Issue by icarojobs** [Laravel-Backpack/CRUD#3333]
# Bug report

### What I did

I just try hide action buttons with $this->crud->removeAllSaveActions() method and when I try see the resolve, one error is showed: "Trying to access array offset on value of type null"

### What I expected to happen

I expected not to see the save buttons after using this method.

### What happened

I guess in the SaveActions.php (line 265) you're probably trying to access a null array

### What I've already tried to fix it

I guess after return, you're to try check if array is null, like this:
if(is_null($currentAction)) {
            return;
        }

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.7.1@3fb29e904a152b3e1fe49581f66ba5e02fe991f2

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877
![backpack_error](https://user-images.githubusercontent.com/16943171/99266988-26be8d80-2802-11eb-9716-419bd4a70a2e.png)

**Comment by pxpm** [comment]
Hello @icarojobs 

From the error it seems you are trying to use save actions when you previously removed them. 

Removing save actions should give you something like this: 
![image](https://user-images.githubusercontent.com/7188159/99275683-b45ea500-2823-11eb-8209-2865ee97fe90.png)

Probably you are calling the default backpack `store()` method that uses save actions ?

```php
/**
     * Store a newly created resource in the database.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        $this->crud->hasAccessOrFail('create');

        // execute the FormRequest authorization and validation, if one is required
        $request = $this->crud->validateRequest();

        // insert item in the db
        $item = $this->crud->create($this->crud->getStrippedSaveRequest());
        $this->data['entry'] = $this->crud->entry = $item;

        // show a success message
        \Alert::success(trans('backpack::crud.insert_success'))->flash();

        // save the redirect choice for next time
        //$this->crud->setSaveAction();

        //return $this->crud->performSaveAction($item->getKey());
        
        return 'your stuff not save action stuff';

    }
```

Can you explain me why you are removing all the save actions ? You are setting up some ajax submit ? I am asking because I am thinkingi if that is the case we can and probably should do something, to allow to just call the stock backpack store function and have it working because technically the save actions does not make sense in ajax call, dev will handle it in js anyway. 

Let me know.

Best,
Pedro

**Comment by icarojobs** [comment]
> Hello @icarojobs
> 
> From the error it seems you are trying to use save actions when you previously removed them.
> 
> Removing save actions should give you something like this:
> ![image](https://user-images.githubusercontent.com/7188159/99275683-b45ea500-2823-11eb-8209-2865ee97fe90.png)
> 
> Probably you are calling the default backpack `store()` method that uses save actions ?
> 
> ```
> /**
>      * Store a newly created resource in the database.
>      *
>      * @return \Illuminate\Http\RedirectResponse
>      */
>     public function store()
>     {
>         $this->crud->hasAccessOrFail('create');
> 
>         // execute the FormRequest authorization and validation, if one is required
>         $request = $this->crud->validateRequest();
> 
>         // insert item in the db
>         $item = $this->crud->create($this->crud->getStrippedSaveRequest());
>         $this->data['entry'] = $this->crud->entry = $item;
> 
>         // show a success message
>         \Alert::success(trans('backpack::crud.insert_success'))->flash();
> 
>         // save the redirect choice for next time
>         //$this->crud->setSaveAction();
> 
>         //return $this->crud->performSaveAction($item->getKey());
>         
>         return 'your stuff not save action stuff';
> 
>     }
> ```
> 
> Can you explain me why you are removing all the save actions ? You are setting up some ajax submit ? I am asking because I am thinkingi if that is the case we can and probably should do something, to allow to just call the stock backpack store function and have it working because technically the save actions does not make sense in ajax call, dev will handle it in js anyway.
> 
> Let me know.
> 
> Best,
> Pedro

Hi Pedro!
First of all, thank you very much for your attention.

I am not working with ajax. The fact is that I needed to make a custom field that will be displayed in a "tab" type menu, however, this field will only list data from the database. So it doesn't make sense on that particular screen to display the save button.

One solution would be for the "tab" menu to work for Visualization, but from what I saw it works only when editing data.

I will attach an image for you to get an idea.
![response_backpack](https://user-images.githubusercontent.com/16943171/99544858-89935e80-2993-11eb-8862-3652644fd0ad.png)

**Comment by pxpm** [comment]
Hello @icarojobs 

Thanks for clarification it really helped to understand your issue. 

I think the easiest way to show the information the way you want is to create a new file `resources/views/your_show_view.blade.php` and then, override the `show()` method of the `ShowOperation` and add the data you want to display the way you want by setting up the view pointing to your new view. 

Have a look https://backpackforlaravel.com/docs/4.1/crud-operation-create#callbacks how to override a crud operation function.

We have plans to allow different displays and more features like related tables in the show view. Probably with 4.2.

If it does not make sense at all using the show operation just return your custom view from your custom controller function that you would call on your custom route. You can start from `show.blade.php` basically extending `@extends(backpack_view('blank'))` and create your custom view with your elements.

Edit was not meant to be used as a show page.

I don't think this is a bug, so I am closing it. If you think I am wrong feel free to re-open. 

Best,
Pedro
