### ISSUE TITLE
Add Save Button in List View (to update the text field value in DB)

### ISSUE THREAD

**Issue by sandeepchowdary7** [Laravel-Backpack/CRUD#3336]
Hi, I was trying to add the Save button in ListView. So that I can enter the value in the text field and click on Save Button and save it in DB. this is what I'm trying to achieve but it is not working as expected.

**Controller**
`$this->crud->addButtonFromModelFunction('line', 'Save', 'showSaveButton', 'beginning');`

**Model**
`public function showSaveButton()
    {

        return '<a href="'.backpack_url('/student/'.$this->id).'" title="Save"><i class="fas fa-desktop"></i> Save </a>';
    }`

**Route**
`Route::post('/student/{id}', 'StudentCrudController@update');`

**Controller-Update Method**
`public function update()
    {

        dd($this);

        return $this->traitUpdate();
    }`

_but getting the result is empty. how I can achieve this. any help or suggestions would be great. Thanks!_

**Comment by pxpm** [comment]
Hello @sandeepchowdary7 

What result is empty ? `dd($this)` ? 

Controller is not called ? Where is the field in list ? 

Pedro

**Comment by tabacitu** [comment]
@sandeepchowdary7 this doesn't look like a bug to me, more of an implementation issue, so I'll move it to discussions. That being said, there aren't that many people in Discussions so I'd recommend asking this kind of questions on StackOverflow - much more people there.

Cheers!
