### ISSUE TITLE
[Bug] Icon_Picker does not have line-awesome library?

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/CRUD#3339]
# Bug report

### What I did

Im using icon_picker field on my crudcontroller but it does not have line-awesome library in it.. In the upgrade guide we've been advised about line-awesome

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.29.3@93f6d565a07045baa0e4b941ae1f733cd5984d65

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

**Comment by promatik** [comment]
Hi @mpixelz! Just confirmed it's not supported, it should be easy to add it though.
I'll do some tests and feedback in a minute.

**Comment by mpixelz** [comment]
yeah i checked the blade file and it should be easy to implement but my point was.. maybe it was missed as 4.1 upgrade guide focuses on using line-awesome fonts for better compatibility but was not implemented in the icon_picker.

**Comment by promatik** [comment]
Sure @mpixelz, probably icon picker was forgotten. I managed a way to solve it, and pushed a PR to solve it #3342.
Thank you for your feedback, if you have the time please test the code on your side and let us know if it works.
I'll close this issue for now, lets move the conversation to #3342.
