### ISSUE TITLE
[Bug] Composer Update for backpack/crud cannot be update

### ISSUE THREAD

**Issue by vonsogt** [Laravel-Backpack/CRUD#3346]
# Bug report

### What I did
`composer update` or `composer install`

### What I expected to happen
updating like it should

### What happened
taking so long to downloading using composer 2.0.7
![image](https://user-images.githubusercontent.com/35516476/99892272-cf0e9f00-2ca5-11eb-847f-91d3ff2d6a83.png)
I already change the DNS or using VPN, still stuck like this
![image](https://user-images.githubusercontent.com/35516476/99892372-daae9580-2ca6-11eb-80a0-f524cac4d917.png)

### Backpack, Laravel, PHP, DB version
already removed

**Comment by vonsogt** [comment]
update the fail code
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]                
  The process "git clone --no-checkout "https://github.com/Laravel-Backpack/CRUD.git" "D:\Code\laravel\project_name\v
  endor\backpack\crud" && cd /D "D:\Code\laravel\project_name\vendor\backpack\crud" && git remote add composer "https
  ://github.com/Laravel-Backpack/CRUD.git" && git fetch composer && git remote set-url origin "https://github.com/Lar
  avel-Backpack/CRUD.git" && git remote set-url composer "https://github.com/Laravel-Backpack/CRUD.git"" exceeded the
   timeout of 300 seconds.  
```

**Comment by vonsogt** [comment]
after I realize, the problem is my internet got limited 1mbps, that's why I got this problem, when I update with no limit internet connection, it works sorry 😅

**Comment by tabacitu** [comment]
Pfiew 😌  Glad to hear it was the Internet @vonsogt 
Wouldn't even know where to look to fix that 🤣 

Cheers!

PS. For posterity, I'm going to write the error message in plain text too. Maybe one day someone with the same problem finds this, and we'll save them some frustration trying to debug it:

> Failed to download backpack/crud from dist: Operation timed out after 300021 milliseconds with 22388097 bytes received
> Now trying to download from source
