### ISSUE TITLE
addcolumn with user name

### ISSUE THREAD

**Issue by debock1984** [Laravel-Backpack/CRUD#335]
Hello

This might be a very small question, but i can't seem find it. So don't start laughing :)
I have a table/model with a user id column that corresponds to the user id from the built-in users table
I want to display the user name in a column in another crud.

I figured i'd use a addColumn of type "select" in the crud controller.
But i'm unsure as to what the model reference should be.

        $this->crud->addColumn([ // n-n relationship (with pivot table)
            'label'     => "User", // Table column heading
            'type'      => 'select',
            'name'      => 'orders_user_id', // the method that defines the relationship in your Model
            'entity'    => 'users', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            **'model'     => 'backpack.permissionmanager.user_model' // foreign key model**
        ]);

Or is this not the correct way to do it ?

**Comment by tabacitu** [comment]
Hi,

Sure, no problem, the model should me the path to your users model. If you have a relationship with the stock Laravel user model, it should be:

'App\User'

Hope it helps. Cheers!

**Comment by debock1984** [comment]
Thanks, that helped.

Using 'App\Model' and a $this->hasOne relation in the model did what i was looking for.

thnx!
