### ISSUE TITLE
[Bug] UUIDs Strings not working with Checkbox Form field

### ISSUE THREAD

**Issue by Thiritin** [Laravel-Backpack/CRUD#3350]
# Bug report

### What I did

- I created a n-m relationship with Users and Roles.
- I added the checkbox type to let an admin choose the roles
- I selected a few roles and clicked save

### What I expected to happen

- The save would be successful

### What happened

- The save returned an error

### What I've already tried to fix it

- Replaced "" in checklist.blade.php with '' for hidden input field otherwise the " from the uuid string will turn into problems.
- Replaced parseInt in Javascript Field Code with 
- It works now, I will propose a PR for the Change.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.10 (cli) (built: Sep  3 2020 19:59:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.13.0@37a0abd4f3dbc51e2256296b45f8be72c8fe2196

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

# Attatchments
![image](https://user-images.githubusercontent.com/6755282/100239441-b1ee0080-2f31-11eb-8032-bb83b45a7fd3.png)

**Comment by promatik** [comment]
Hello @Thiritin!
Can you add you field code here? (`CRUD::addField(...`) so it's easy for us to understand what arguments do you have on the field?

Thank you

**Comment by Thiritin** [comment]
> Hello @Thiritin!
> Can you add you field code here? (`CRUD::addField(...`) so it's easy for us to understand what arguments do you have on the field?
> 
> Are you using UUID as your primary key for roles?
> 
> Thank you.

Sure.
```
[
                'label' => __('roles'),
                'type' => 'checklist',
                'name' => 'roles',
                'entity' => 'roles',
                'model' => Role::class, // foreign key model
                'attribute' => 'name', // foreign key attribute that is shown to user
                'pivot' => true,
            ]
```

**Comment by promatik** [comment]
@Thiritin thank you for opening this issue, and for the PR 🙌
I've just review it, let's move the conversation there #3351.
