### ISSUE TITLE
[Bug] filters_navbar/dataTables does not work locally

### ISSUE THREAD

**Issue by makss** [Laravel-Backpack/CRUD#3354]
# Bug report

### What I did

When working locally without the Internet, `filters_navbar` does not work (data in the dataTable is not displayed).

### What happened

dataTable is empty.

### What I've already tried to fix it

`filters_navbar` uses external javascript which blocks data loading in my browser.

https://github.com/Laravel-Backpack/CRUD/blob/674cde8055d20a9e124a0a680fff67e9020531b7/src/resources/views/crud/inc/filters_navbar.blade.php#L21

I placed the `URI.min.js` script locally - that solved the problem.
It might be worth adding this script to `/public/packages` folder.

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 7.2.23 (cli) (built: Sep 25 2019 07:48:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.29.3@93f6d565a07045baa0e4b941ae1f733cd5984d65

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7
```

**Comment by martijnb92** [comment]
Known problem and will be fixed in the next version.
https://github.com/Laravel-Backpack/CRUD/pull/3061

**Comment by promatik** [comment]
@makss thank you for reporting the issue, gladly it's a known bug and it's expected to be solved on the next major release.
@martijnb92 thank you for your feedback on this! I'll close this issue for now 🙌
