### ISSUE TITLE
Add official PHP 8 support

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3359]
Let me add this issue, before anyone else 😄 

**Yes, Backpack will add support for PHP 8, now that it's out.**

When? Soon.
What version? Probably 4.1.
Will it be a breaking change? Probably not.

...that pretty much covers it, right? 🤣 

Let me know here if you're waiting for this feature, and we'll prioritise it accordingly.

Cheers!

**Comment by Read2uk** [comment]
Yes please, prioritise php 8 if possible please. Do you know how long? thanks

**Comment by ampedweb** [comment]
We quickly switched one of our Laravel 8 projects to PHP 8.0 just to see what broke and this was the first thing that came up. Looks like it might be an easy one? :-). Haven't gone much further with testing as of yet.

![image](https://user-images.githubusercontent.com/22029493/101152972-b09c9200-361b-11eb-909e-52c9f1b83f10.png)

**Comment by tabacitu** [comment]
Update: Moving this to 4.2, so that we work on it in February. 

However, if we can merge it in 4.1 (no breaking changes), we'll do that then. If not, we'll ask users to upgrade to 4.2 (which should be super-super simple).

**Comment by tabacitu** [comment]
Update: started working on adding PHP8 support and it's been... _surprisingly_ easy 😀 Actually it's been... _suspiciously_ easy 😂 Please see https://github.com/Laravel-Backpack/CRUD/pull/3516 - the test above is fixed there.

@ampedweb thanks for the heads-up. I wasn't able to replicate that - but I bet it's easily fixed by a `composer update` - I think I saw that exact thing getting fixed recently.

Let's close this issue in favour of PR https://github.com/Laravel-Backpack/CRUD/pull/3516 - looks like we might actually be able to merge it today and launch PHP8 support on Monday 😎
