### ISSUE TITLE
Do something on record deletion?

### ISSUE THREAD

**Issue by madd86** [Laravel-Backpack/CRUD#336]
Is there a feature to run a command when we click on the "delete" button?

**Comment by madd86** [comment]
The reason I need it is because I want to also delete the record from a related table.

**Comment by OwenMelbz** [comment]
Checkout laravels model observers. They can hook into events like deleting so you can do more

**Comment by zschuessler** [comment]
You can extend this method if you wish to do it in the controller:

https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php#L216

Or you have access to the Eloquent events (which is a better idea for most operations anyway):

https://laravel.com/docs/5.3/eloquent#observers

In the above, you have access to both `deleting` and `deleted` events, depending on when you want to tap into the delete action.

**Comment by madd86** [comment]
@zschuessler Thanks for that. How can I extend the method on my own controller? By calling it on my controller the same way?

```
    public function destroy()
    {
          //my code
    }
```

**Comment by OwenMelbz** [comment]
@madd86 you would create a function in your controller with the same name. 

Then after your custom code you can call parent::destroy()

However I'd recommend the Observer route as it's more universal and less hacky

**Comment by jhchnc** [comment]
The issue is that the deleting observer doesn't work because according to taylor "Yes, this is basically expected. In order to fire the events we would have to pull the models first and then call the events with the model instances. Then call the delete query."

https://github.com/laravel/framework/issues/2536
