### ISSUE TITLE
[Bug] Validation errors not shown in custom operation with laravel 8 and backpack 4.1

### ISSUE THREAD

**Issue by umtreiber** [Laravel-Backpack/CRUD#3370]
# Bug report

### What I did

i coded a custom operation according to the documentation with a form and a store method for a "bankaccount".
i use a form-request incl. validation. blade template is backpacks "create"
validation is working an the Log.debug shows the invalid fields incl messages. 
The redirect after a validation error is also working.

### What I expected to happen

validation is working but i dont get a error message in the blade template/form on my custom operation.
if i use the build-in "create" method with the same model and form-request (incl validation) i get the correct error messages incl form-field in red.

### What happened

validation errors in a custom operation are  not passed to the blade template.

### PHP VERSION:
PHP 7.4.10 (cli) (built: Sep  1 2020 16:52:39) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.17.1@7618102c4864ac1f1f791c966c0e9a86949d9b83

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

**Comment by pxpm** [comment]
@umtreiber thanks for the report. 

Indeed this is something we need to improve in our documentation, and I am sorry for the trouble you went for this. 

The default backpack create operation enables the errors by default, you might need to enable them also in your custom operation:

```php
$this->crud->enableGroupedErrors();
$this->crud->enableInlineErrors();
```

I don't think this is a bug, so I am going to close this. If I am wrong, and sometimes I am, please re-open and I will re-evaluate the question.

Wish you the best,
Pedro

**Comment by umtreiber** [comment]
Thx Pedro. It works :-)
