### ISSUE TITLE
[Bug] Filters selected in one CrudController effects in another one.

### ISSUE THREAD

**Issue by centerdevs** [Laravel-Backpack/CRUD#3375]
# Bug report

### What I did

When i select some of filters in some CrudController, Backpack save it as default to session, this is useful and cool. But when i open another CrudController, one of the filter which i selected in previous menu effects on this one.

Both controllers have filter with same name ex. "account_id"

### What I expected to happen

I expect that filter will effect only for the controller where it was selected.

### What happened

Backpack used a filter selected in other controller.

### What I've already tried to fix it

Nothing yet.

### PHP VERSION:
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.17.1@7618102c4864ac1f1f791c966c0e9a86949d9b83

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

**Comment by promatik** [comment]
Hi @centerdevs, welcome to backapack 🙌

I use persistent tables on a project and it works as expected for different entities with same name filters;

![image](https://user-images.githubusercontent.com/1838187/101153226-0cffb180-361c-11eb-83d5-869a6603b470.png)

![image](https://user-images.githubusercontent.com/1838187/101153492-6ec01b80-361c-11eb-8b8f-5541313904eb.png)

**Comment by pxpm** [comment]
Hello @centerdevs like @promatik said, I also use filters with same name in different cruds.

What Backpack stores in localstorage to retrieve the previous state is the name of the crud `room` and `device` in @promatik case.

Could you share your 2 crud urls ? 

Best,
Pedro

**Comment by pxpm** [comment]
I don't think there is a bug here. 

Going to close due to inactivity. 

IF you feel I am wrong, please re-open, I also make mistakes :)

Wish you guys the best,
Pedro
