### ISSUE TITLE
Missing some italian translations for datepicker

### ISSUE THREAD

**Issue by masetto** [Laravel-Backpack/CRUD#3384]
Hello, some italian translation are missing:
- filters language strings
- `apply` key.

```
    'remove_filters' => 'Rimuovi filtri',
    'apply' => 'Applica',

    //filters language strings
    'today' => 'Oggi',
    'yesterday' => 'Ieri',
    'last_7_days' => 'Ultimi 7 giorni',
    'last_30_days' => 'Ultimi 30 giorni',
    'this_month' => 'Questo mese',
    'last_month' => 'Mese precedente',
    'custom_range' => 'Personalizza',
    'weekLabel' => 'W',
```
Can you adjust please?
`Custom range` label is always in english, I do not know why.

**Comment by pxpm** [comment]
Thanks for the report @masetto .

About the `Custom Range` problem, i'v just submitted a PR #3385  that should address that issue in particular. 

The translation strings are very welcome, thank you. Would you like to submit a PR with the missing strings so you show up as a Contributor to the project ?

If you don't have time or are not willing to do it now, me or somebody else can pick it and add it, no problem 👍 

Wish you the best,
Pedro

**Comment by masetto** [comment]
@pxpm please can you help me to create a PR? What are the steps I have to do?

**Comment by tabacitu** [comment]
@masetto in this particular case it should be pretty easy - just:
- go to the file you want to modify on Github ([probably this](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/lang/it/crud.php))
- click on the Edit button in the top-right corner
- make the changes you want to the file
- then at the bottom of the file, save the changes; Github will ask you if you want to create a fork & PR for it (you do);

And that's pretty much it. Hope it helps!

**Comment by masetto** [comment]
Thanks @tabacitu for your instuctions. I have submitted a PR #3389.

**Comment by pxpm** [comment]
Just approved the PR. 

Let's move any further conversation on this to the PR thread. 

Thanks again @masetto 

Best to you,
Pedro
