### ISSUE TITLE
[Bug] Summernote Options are not taking affect.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/CRUD#3388]
# Bug report

### What I did

Implemented a CRUD field with a type of summernote and provided options. 

### What I expected to happen

Specific options to be set within the summernote editor according to the options I set.

### What happened

Nothing changed. The default options remain. 

### What I've already tried to fix it

```
'type' => 'summernote',
                'name' => 'description',
                'options' => [['toolbar', ['font', ['bold', 'underline', 'italic']]]],
                'wrapper' => [
                    'class' => 'form-group col-lg-12',
                ],
                'tab' => $general

```

```
'type' => 'summernote',
                'name' => 'description',
                'options' => [ ['font', ['bold', 'underline', 'italic']]],
                'wrapper' => [
                    'class' => 'form-group col-lg-12',
                ],
                'tab' => $general
```

```
 $this->crud->addField(
            [
                'type' => 'summernote',
                'name' => 'description',
                'options' => ['font', ['bold', 'underline', 'italic']],
                'wrapper' => [
                    'class' => 'form-group col-lg-12',
                ],
                'tab' => $general
            ]
        );
```

### PHP VERSION:
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.15-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.29.3@93f6d565a07045baa0e4b941ae1f733cd5984d65

### BACKPACK VERSION:
4.1.27@bd1bab5dde08df20eebd730ca3a2992e1bf334f7

For all I know this is just me entering the options incorrectly, in which case it would be nice if the documentation had an example of how this needs to be configured as I have no idea how this is being mapped.

**Comment by pxpm** [comment]
Indeed @selected-pixel-jameson 

Thanks for the report, I'v just added to documentation how to add summernote configuration. https://github.com/Laravel-Backpack/docs/pull/213

Sorry for the trouble and thank you very much for bringing this to our attention.

Going to close this, if you find any issue please let us know.

Wish you the best,
Pedro
