### ISSUE TITLE
Question about 1-N (One To Many) relation

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#339]
Hello,

I have a 1-N (One To Many) relation between two tables :

- a **personne** belongs to one **structure**
- in a **structure** there is many **personnes**

So i have a **personnes** table :
idPersonnes, name, firstname, idStructures
And a **structure** table :
idStructures, name, adress

In my personne Model i have :
```
public function structure()
{
     return $this->belongsTo('App\Models\Structure', 'idStructures', 'idStructures');
}
```

In my personne controller i have :

```
$this->crud->addField([
            'label' => 'Structure',
            'type' => 'select2',
            'name' => 'idStructures', // the db column for the foreign key
            'entity' => 'structure', // the method that defines the relationship in your Model
            'attribute' => 'nom', // foreign key attribute that is shown to user
            'model' => 'App\Models\Structure' // foreign key model
        ]);
```
This is working well. I have select2 dropdown when i edit a personne and i can choose and save a structure.

Now when i edit a structure i want to show all the personnes that belongs to that structure.
In my structure model i have :

```
public function personnes()
{
    return $this->hasMany('App\Models\Personne', 'idStructures', 'idStructures');
}
```

In my structure controller i have :

```
$this->crud->addField([
            'label' => 'Personnes',
            'type' => 'select2',
            'name' => 'idStructures', // the db column for the foreign key
            'entity' => 'personnes', // the method that defines the relationship in your Model
            'attribute' => 'nom', // foreign key attribute that is shown to user
            'model' => 'App\Models\Personne' // foreign key model
        ]);
```

It's not working.
Am i doing something wrong ?
Thanks for your help.

**Comment by tabacitu** [comment]
Hi @adbmdp ,

I don't see the "nom" column in your table. Maybe this should work:
```diff
$this->crud->addField([
            'label' => 'Personnes',
            'type' => 'select2',
            'name' => 'idStructures', // the db column for the foreign key
            'entity' => 'personnes', // the method that defines the relationship in your Model
-            'attribute' => 'nom', // foreign key attribute that is shown to user
+            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => 'App\Models\Personne' // foreign key model
        ]);
```

Cheers!

**Comment by adbmdp** [comment]
Thanks for your reply. 
I have a "nom" column in my table.
The problem does not comes from that.

Is it ok to use  _'type' => 'select2'_ in my addField ? I'm supposed to display multiple personnes here so it should be logic to use _select_multiple_  right ? But as it is supposed to be for N-N relation. I'm a bit confused.

I'm still discovering BackPack and i love your work ! That's really cool.

**Comment by tabacitu** [comment]
Hmm... I think it's a 1-N relationship. There's no pivot table, so it's not an N-N relationship.

I've looked more closely to your first post and I think I understand it better now. So what you want is:
- from the "Edit Structure" page, show all persons related to that structure;
- when saving, also edit all Persons you chose and make connect them to that structure;

Unfortunately, we have nothing that works that way, as it's a pretty peculiar use case. CRUDs usually only edit the entity you've opened, not connected entities too.

Solution:
- You should already be able to see and add Persons in the Edit Structure form (front-end), but it won't actually save them. 
- In order to save them, you need to edit the ```store()``` and ```update()``` methods in your controller, and include the logic for that. Something like:

```php

    public function store(StoreRequest $request)
    {
        $result =  parent::storeCrud();
        
        // TODO: go through all persons the admin chose and make sure they belong to the current structure

        return $result;
    }
```

Hope it helps.

Cheers!

**Comment by adbmdp** [comment]
OK i understand that CRUDs usually only edit the entity you've opened, not connected entities too.

But do you think it's possible in the edit form of a structure to just print out a list of all persons related to that structure and a link to their edit form ?

I found kind of a workaround by using your blog post here but that's not exactly what i want as it is from the list view : [https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud](https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud)

**Comment by tabacitu** [comment]
Sure, you can do that by creating a [custom field type](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types). It can look and work any way you need it. You'll find the entries inside the ```$entry``` variable and you can output them any way you want.

Cheers!

**Comment by adbmdp** [comment]
Thanks i'll do that!
Do I have to use an existing field type and modify it or can i create a brand new one. Like mynewfield.blade.php ?
And call it like that :
```
$this->crud->addField([
            ...
            'type' => 'mynewfield',
           ...
        ]);
```

**Comment by tabacitu** [comment]
Exactly - "mynewfield" will work if your field is mynewfield.blade.php

**Comment by adbmdp** [comment]
Thanks you for your replies! Much appreciated.

**Comment by adbmdp** [comment]
Sorry to bother you again. But i can't make my 1-N relation to work to get all personnes that belongs to a structure. I've tried everything. 
I got the same relations that on my first post.

I've created a new blade personnesliste.blade.php that just var_dump $entry and $field.

```
 $this->crud->addField([
            'label' => 'Personnes',
            'type' => 'personnesliste',
            'name' => 'idStructures', // the db column for the foreign key
            'entity' => 'personnes', // the method that defines the relationship in your Model
            'attribute' => 'nom', // foreign key attribute that is shown to user
            'model' => 'App\Models\Personne' // foreign key model
        ]);
```

All i got is  when i edit the structure that got id 1, look like the relation is not working properly, it's brings personne with id 1 ? 

` object(App\Models\Structure)#391 (23) { ["table":protected]=> string(10) "structures" ["primaryKey":protected]=> string(12) "idStructures" ["timestamps"]=> bool(true) ["fillable":protected]=> array(6) { [0]=> string(12) "idStructures" [1]=> string(3) "nom" [2]=> string(7) "adresse" [3]=> string(2) "cp" [4]=> string(5) "ville" [5]=> string(4) "pays" } ["connection":protected]=> NULL ["keyType":protected]=> string(3) "int" ["perPage":protected]=> int(15) ["incrementing"]=> bool(true) ["attributes":protected]=> array(8) { ["idStructures"]=> int(1) ["nom"]=> string(6) "SATEST" ["adresse"]=> string(14) "11 rue de Bois" ["cp"]=> int(75000) ["ville"]=> string(5) "Paris" ["pays"]=> string(6) "France" ["created_at"]=> NULL ["updated_at"]=> string(19) "2017-01-05 13:09:26" } ["original":protected]=> array(8) { ["idStructures"]=> int(1) ["nom"]=> string(6) "SATEST" ["adresse"]=> string(14) "11 rue de Bois" ["cp"]=> int(75000) ["ville"]=> string(5) "Paris" ["pays"]=> string(6) "France" ["created_at"]=> NULL ["updated_at"]=> string(19) "2017-01-05 13:09:26" } ["relations":protected]=> array(0) { } ["hidden":protected]=> array(0) { } ["visible":protected]=> array(0) { } ["appends":protected]=> array(0) { } ["guarded":protected]=> array(1) { [0]=> string(1) "*" } ["dates":protected]=> array(0) { } ["dateFormat":protected]=> NULL ["casts":protected]=> array(0) { } ["touches":protected]=> array(0) { } ["observables":protected]=> array(0) { } ["with":protected]=> array(0) { } ["exists"]=> bool(true) ["wasRecentlyCreated"]=> bool(false) }
`

`array(7) { ["label"]=> string(9) "Personnes" ["type"]=> string(14) "personnesliste" ["name"]=> string(12) "idStructures" ["entity"]=> string(9) "personnes" ["attribute"]=> string(3) "nom" ["model"]=> string(19) "App\Models\Personne" ["value"]=> int(1) } `

**Comment by tabacitu** [comment]
Hi @adbmdp ,

Hmm... then the problem must be with the way you've defined your relationship. You can try it elsewhere (in a blank controller, for example) and play there until the relationship is fully working.

Cheers!

P.S. Since this isn't a bug, I'll go ahead and close this issue so we don't clog the section. Feel free to comment if you have follow-ups.

**Comment by adbmdp** [comment]
Still can't get it to work :-(
I did everything like in this post :
[https://github.com/Laravel-Backpack/Base/issues/50](https://github.com/Laravel-Backpack/Base/issues/50)

**Comment by OwenMelbz** [comment]
@adbmdp 

Have you tried adding `'pivot' => true` to your `addField` calls? 

(I haven't read the whole thread)

**Comment by adbmdp** [comment]
I don't need it as it's not a many to many relation but a 1-N relation.
I don't have any pivot table for that relation.

**Comment by tabacitu** [comment]
Hi @adbmdp ,

As far as I can see, you were able to dump the structure in your field (```object(App\Models\Structure)#391 (23)```). If you [have the relationships defined on your Structure model](https://laravel.com/docs/5.3/eloquent-relationships) (one-to-many), you should be able to easily get the persons from a structure.

If you got the structure with $entry, and your relationship is calles "personnes", you should be able to do ```$entry->personnes```.

Hope it helps. Cheers!

**Comment by adbmdp** [comment]
OK it works.
Once again thanks you my friend!

**Comment by keselyoleren** [comment]
<form action="/" method="post">
	<input type="text" value=""> <br>
	<input type="text" value=""> <br>
	<input type="text" value=""> <br>

	<input type="submit" name="submit" class="btn btn-danger" value="update">

	

	<input type="hidden" name="_method" value="PUT">

**Comment by apudiu** [comment]
Please don't blame me as this is not directly related to this topic.

But I will be highly appreciating if someone can help me on this:
https://stackoverflow.com/questions/47114109/eloquent-using-wrong-key-for-some-tables

if you guys just cant tolerate this request here then delete it or let me know. I will do.
I seriously need help. So i posted here
