### ISSUE TITLE
Undefined index: value in dropdown filter

### ISSUE THREAD

**Issue by rasez** [Laravel-Backpack/CRUD#340]
Hi I have a dropdown filter that filter records by language 
`        $this->crud->addFilter([
          'name' => 'language',
          'type' => 'dropdown',
          'label'=> 'Language'
        ], [
          'en' => 'English',
          'ru' => 'Russian',
        ], function($value) { 
            $this->crud->addClause('where', 'language', $value);
        });`
but when i run it i got "Undefined index: value" error
what should i do?

**Comment by tabacitu** [comment]
Hi @rasez ,

I see you've closed the issue. What did you do to fix it? It might prove useful to others that have the same problem and stumble upon your question.

Thanks, cheers!

**Comment by rasez** [comment]
The error was from select_from_array field not filter
