### ISSUE TITLE
Double-check which columns support prefix and suffix

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3402]
It's been reported that we removed `prefix` and `suffix` for some columns. If that's true, it's definitely been done by mistake.

https://stackoverflow.com/questions/63364646/backpack-4-1-doesnt-have-prefix-option-for-columns

**Comment by promatik** [comment]
@tabacitu I took a look and there are many missing, quick question; Sometimes there is a space separating content from suffix, others don't.

`text.blade.php`
```php
$column['text'] = $column['prefix'].Str::limit($value, $column['limit'], '[...]').$column['suffix'];
```

`array_count.blade.php`
```php
$column['text'] = count($array).' '.$suffix;
```

I think this should follow a pattern, either add the space, or not. Maybe this should it be an extra argument on column defenition?

**Comment by tabacitu** [comment]
> I think this should follow a pattern, either add the space, or not.

Agreed - let's go with no-space as default, as it covers more use cases. 

> Maybe this should it be an extra argument on column defenition?

No extra argument needed - that would be overkill when it can be done with string concatenation which is easier to read for anyone.

IMPORTANT. Please create separate PRs, first non-breaking then breaking:
- non-breaking - adding no-space `prefix` and `suffix` to columns _where they make sense_; which begs the question - are there columns where the prefix/suffix don't make sense?
- breaking - making all prefixes no-space;

That'd allow us to merge the non-breaking into 4.1 to normalize prefix/suffix support across columns. Then in 4.2 to make all of the prefixes no-space.

**Comment by promatik** [comment]
I've just created the PRs;
- PR with **non** breaking changes for v4.1; https://github.com/Laravel-Backpack/CRUD/pull/3435.
- PR with breaking changes for v4.2; https://github.com/Laravel-Backpack/CRUD/pull/3436.

Let's move the conversation there 🙌
