### ISSUE TITLE
Use multiple DB on CRUD model

### ISSUE THREAD

**Issue by mohsensaeedi** [Laravel-Backpack/CRUD#342]
Hi

Is there any solution to use multiple database on our model extended from CrudController?

For example we can define two mysql database with different name in laravel .env file and then we use them in our model. 
Example:
protected $connection = 'mysql2';

I try some way to handle it but without any success. I integrate Laratrust as backend RBAC with permissionmanager and it works like a charm.

I'll will be appreciated for any help or recipe. 

Thanks

**Comment by mohsensaeedi** [comment]
I guess we should add protected $connection in App\Models\Model_name.php. 
is it true?

**Comment by tabacitu** [comment]
Hi @mohsensaeedi ,

For DB operations Backpack uses only Eloquent methods. So what works for Eloquent should work in Backpack:

![screen shot 2017-01-07 at 11 20 01](https://cloud.githubusercontent.com/assets/1032474/21740744/63c81f22-d4cb-11e6-9c87-69bcc6b2050d.png)

Never tried it myself, but:
- $connection should work just fine;
- if you then have different properties that are stored in a table in another database, you can probably use [Accessors & Mutators](https://laravel.com/docs/5.3/eloquent-mutators#accessors-and-mutators) as setters and getters, to make it look & work exactly like they were in one database;
- you'll then be able to use the Model anywherelike it were a model in the same db - you won't have to think about it;

Hope it makes sense and it helps. Cheers!

**Comment by mohsensaeedi** [comment]
Hi @tabacitu 

I checked it last night and it worked without any problem and I don't have any experience to use Accessors & Mutators. Thanks for your advice. I'll try it as soon as. 

Best regards,

**Comment by tabacitu** [comment]
Great to hear that. Cheers!

**Comment by mohsensaeedi** [comment]
Hi @tabacitu 

I checked multiple database with Backpack CRUD and i have a problem when crud tries to get DB columns name from information_schema database. As you know i want to use another database in my Model with defined $connection property but CRUD tries first database to get columns with where table_schema = 'backpack' statement. 

Note: I am know how to use multiple database in laravel without backpack and how to define second database connection on backpack as we discussed. 

And for your recommendation about to use Accessors & Mutators in Model, I can't implement on my Model. Can you give me a brief example to do that? I want to define another database and table on my Model.

Best regards,

**Comment by laragallassi** [comment]
Hi @mohsensaeedi , do you solved this? I had the same problem. I set the connection dinamically in index and works perfectly, but I don't know how to do this in edit, update, delete, etc...
