### ISSUE TITLE
[Bug] Disable default order by model key

### ISSUE THREAD

**Issue by phammanh029** [Laravel-Backpack/CRUD#3421]
# Bug report

### What I did

reading the list operation code

### What I expected to happen

code should be correct

### What happened

it seem variable not capture as reference

### What I've already tried to fix it

nothing

### Backpack, Laravel, PHP, DB version
not sure

in this file:https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/Operations/ListOperation.php
in search function:
```
collect($orderBy)->each(function ($item, $key) use ($hasOrderByPrimaryKey) {
            if (! isset($item['column'])) {
                return false;
            }

            if ($item['column'] == $this->crud->model->getKeyName()) {
                $hasOrderByPrimaryKey = true;

                return false;
            }
        });
```
i think variable `$hasOrderByPrimaryKey` should pass as reference `&$hasOrderByPrimaryKey` to work at ` $hasOrderByPrimaryKey = true;` command.

Btw, is there anyway to disable order by?

**Comment by pxpm** [comment]
Hello @phammanh029 

To remove the default backpack order by key you should add your own column that refer to the key, most likely 'id' and overwrite the `orderLogic` for that column.

Did I missed the point here?

Best,
Pedro

**Comment by phammanh029** [comment]
@pxpm  thank for your reply.
I think this line:       https://github.com/Laravel-Backpack/CRUD/blob/2551e6d85d7416f594e7b71dd20dde38dd1a515c/src/app/Http/Controllers/Operations/ListOperation.php#L123 has no affect on $hasOrderByPrimaryKey variable outside. Do we need to pass that variable as "**&$hasOrderByPrimaryKey**"

**Comment by phammanh029** [comment]
@pxpm  i mean this line of code:
![image](https://user-images.githubusercontent.com/3992023/103170893-728d3980-487a-11eb-86ba-60863ae2278e.png)

**Comment by promatik** [comment]
@phammanh029 I can confirm that line is incorrect, and it causes a minor bug, so I've pushed a PR fixing it; https://github.com/Laravel-Backpack/CRUD/pull/3451

**Comment by promatik** [comment]
@phammanh029 regarding your question (disable default order by ID) that PR doesn't solve it.

Can you please give us an example why you'd want to remove the default ordering by model primary key?
I'm finding it difficult to see a situation where it could be useful.

Anyway, if there are use cases, we may add an operation setting for that.

Please let me know 🙌

**Comment by phammanh029** [comment]
@promatik 
i think it works now. Thanks.
>Can you please give us an example why you'd want to remove the default ordering by model primary key?
I don't remember now. I will update latter on.
