### ISSUE TITLE
[Bug] Doesn't load icon image

### ISSUE THREAD

**Issue by adal6a** [Laravel-Backpack/CRUD#3423]
# Bug report

### What I did

Load icon image in dropdown user

### What I expected to happen

Load icon image in dropdown user

### What happened

Doesn't load icon image

### What I've already tried to fix it

I think domain for placehold is changed, so we need change it
from

https://placehold.it/160x160/00a65a/ffffff

to

https://place-hold.it/160x160/00a65a/ffffff

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v6.18.35@baec6c2d7f433594cb858c35c2a2946df7ecac13

### BACKPACK VERSION:
4.1.18@8109ca0d308e47fb24c8baa8bd9893e21a187214

where change it?

thanks

**Comment by pxpm** [comment]
Hello @adal6a 

Thanks for the report.

It seems that the first domain (without dash) has no certificate. Not sure if it is a temporary issue or they will permanently change to the new domain. 

I will investigate on their side what happened, if needed I will submit the PR to fix this in core.

Best,
Pedro

**Comment by tabacitu** [comment]
Update: @pxpm submitted a PR for this here - https://github.com/Laravel-Backpack/CRUD/pull/3425

So let's close this issue in favour of that PR. Thanks for bringing this up @adal6a !
