### ISSUE TITLE
[Bug] 500 (Internal Server Error) when searched on list screen

### ISSUE THREAD

**Issue by osieman1** [Laravel-Backpack/CRUD#3426]
# Bug report

On the standard list screen for one of my models I got an error.  Error loading page, please refresh. 
In the console, I found the following line `o.apply(e, arguments) `in bold below as saying failed to load resource.

;!function() {
    function e(t, e) {
        return "function" != typeof t || t.replaced ? t : (e.replaced = !0,
        e)
    }
    var n, r, o, u = 0;
    if ("undefined" != typeof CustomEvent && "function" == typeof window.dispatchEvent) {
        function s(t) {
            try {
                if ("object" == typeof t && (t = JSON.stringify(t)),
                "string" == typeof t)
                    return window.dispatchEvent(new CustomEvent("lprequeststart",{
                        detail: {
                            data: t,
                            requestID: ++u
                        }
                    })),
                    u
            } catch (t) {}
        }
        function c(t) {
            try {
                window.dispatchEvent(new CustomEvent("lprequestend",{
                    detail: t
                }))
            } catch (t) {}
        }
        "undefined" != typeof XMLHttpRequest && XMLHttpRequest.prototype && XMLHttpRequest.prototype.send && (XMLHttpRequest.prototype.send = e(XMLHttpRequest.prototype.send, (o = XMLHttpRequest.prototype.send,
        function(t) {
            var e = this
              , n = s(t);
            return n && e.addEventListener("loadend", function() {
                c({
                    requestID: n,
                    statusCode: e.status
                })
            }),
            **o.apply(e, arguments)**
        }
        ))),

### What I expected to happen

The search function filtering the records

### What happened

The error happened and the search failed

### What I've already tried to fix it

The error is due to this line in the crudcontroller which works fine(displays the fullname), but causes the error.
        $this->crud->addColumn(        
        [  // Select
           'label'     => "Customer",
           'type'      => 'select',
           'name'      => 'customer_id', // the db column for the foreign key
           'entity'    => 'customer', 
           'model'     => "App\Models\customer", // related model
           'attribute' => 'FullName'
        ]);

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.24 (cli) (built: Oct 27 2020 14:44:04) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.18.1@31747193c26ba0a9cb7929a912895d3cdefd10cf

### BACKPACK VERSION:
4.1.28@011e818304b3ebac28b673c1c91018590bdceb12

**Comment by pxpm** [comment]
@osieman1 thanks for the report. 

Could you check your `laravel.log` in `storage/logs` and share the error ? 

Wish you the best,
Pedro

**Comment by osieman1** [comment]
@pxpm Hello, Yes, I see the error now.
FullName is a nondb field created via an assessor.

So, I guess I can not have a 'select' fieldtype in the list screen with an attribute that refers to an assessor?
If so, I will just change it to a database field, unless there is an option to omit columns from the search routine.

Cheers


```
SELECT COUNT(*) AS AGGREGATE FROM `bookhdrs` 
	WHERE (`booking_no` LIKE '%12%' 
	OR EXISTS 
		(SELECT * FROM `customers` WHERE `bookhdrs`.`customer_id` = `customers`.`id` AND `FullName` LIKE '%12%')

```

**Comment by pxpm** [comment]
Hello, you could write your own searchLogic and/or orderLogic for any given column that you need to overwrite backpack functionality. 

https://backpackforlaravel.com/docs/4.1/crud-columns#custom-search-logic

Let me know if this fixes your issue. 

Best,
Pedro

**Comment by osieman1** [comment]
All is good... for now I am happy to just use surname as the attribute text.
Thanks for the heads up on looking in the log!
