### ISSUE TITLE
[Bug] Image field with sftp storage disk error: This driver does not support retrieving URLs

### ISSUE THREAD

**Issue by Sammi89** [Laravel-Backpack/CRUD#3427]
# Bug report

### What I did

Create an image field using SFTP storage disk.

**CrudController**
```php
$this->crud->addField([
    'name' => 'cover',
    'label' => trans('articles.fields.cover'),
    'type' => 'image',
    'upload' => true,
    'tab' => trans('articles.tabs.article'),
    'disk' => 'sftp',
    'prefix' => 'https://cdn.test'
]);
```

**filesystems.php**
```php
'sftp' => [
    'driver' => 'sftp',
    'host' => 'my-host.com',
    'username' => 'my-user',
    'password' => 'my-pass',
    'port' => 22,
    'root' => '/my/path/to/uploads'
],
```

The library used is the one indicated by [Laravel documentation](https://laravel.com/docs/7.x/filesystem#driver-prerequisites): `league/flysystem-sftp`.

### What I expected to happen

I expected to see the image preview in Create or Update operation form with URL: `https://cdn.test/my-image.jpg`.

### What happened

_Facade\Ignition\Exceptions\ViewException_
**This driver does not support retrieving URLs**. (View: _C:\laragon\www\across-blog\vendor\backpack\crud\src\resources\views\crud\fields\image.blade.php_)

### What I've already tried to fix it

In `src/resources/views/crud/fields/image.blade.php` file, before the line:
```php
Storage::disk($field['disk'])->url($prefix.$value)
```
need to check if the FileSystemAdapter implements a method to retrieve url.

I've overridden the `image.blade.php` file in my resource path `resources/views/vendor/backpack/crud/fields/image.blade.php` like this:
```php
@php
    $prefix = isset($field['prefix']) ? $field['prefix'] : '';
    $value = old(square_brackets_to_dots($field['name'])) ?? $field['value'] ?? $field['default'] ?? '';

    $valueFromStorageDisk = '';
    if (isset($field['disk'])) {
        try {
            $valueFromStorageDisk = Storage::disk($field['disk'])->url($prefix.$value);
        }
        catch (Exception $e) {
            $value = str_replace('\\', '/', $value);
            $valueFromStorageDisk = url($prefix.$value);
        }
    }

    $value = $value
        ? preg_match('/^data\:image\//', $value)
            ? $value
            : $valueFromStorageDisk
        :''; // if validation failed, tha value will be base64, so no need to create a URL for it
[...]
```

#### PHP VERSION:
PHP 7.2.9 (cli) (built: Aug 15 2018 23:10:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

#### LARAVEL VERSION:
v7.11.0@f4563bd2e0875c59a1f7967abdbe5cef7f240117

#### BACKPACK VERSION:
4.1.22@2c87086173c0c1b746d6f0fd49783f6eefa787e9

**Comment by pxpm** [comment]
Hello @Sammi89 

Thanks for the report. 

I'v never tested with a driver that does not support retriving urls. 

I took a look at your solution, I think it should be more like to don't break current functionality.

```php
    if(isset($field['disk'])) {
        try {
            $valueFromDisk = Storage::disk($field['disk'])->url($prefix.$value);
        }catch(Exception $e) {
            $value = str_replace('\\', '/', $value);
            $valueFromDisk = url($prefix.$value)
        }
    }
    $value = $value
        ? preg_match('/^data\:image\//', $value)
            ? $value
            : (isset($field['disk'])
                ? $valueFromDisk
                : url($prefix.$value))
        :''; // if validation failed, tha value will be base64, so no need to create a URL for it

```

What I don't get is why `str_replace` is needed? It's specific for SFTP or is it general for any drivers that don't support getting the url ? Because if no disk is provided in current code we just get the `url($prefix.$value))` of what is stored in database. 

Thanks for the report, I will take a better look at it installing the sftp package to test in my local.


Best,
Pedro

**Comment by promatik** [comment]
@pxpm I took this issue, hope you don't mind ✌

I've created a PR to fix this; https://github.com/Laravel-Backpack/CRUD/pull/3449, I think we can move the conversation there.
