### ISSUE TITLE
[Feature Request] Change of order icons in table header by request from code

### ISSUE THREAD

**Issue by pcipov** [Laravel-Backpack/CRUD#3429]
# Feature Request

### What's the feature you think Backpack should have?

When I insert this code to setupListOperation method:

```
$request = $this->crud->getRequest();
if (!$request->has('order')) {
    $request->merge(['order' => [
        ['column' => '0', 'dir' => 'desc',],
        ['column' => '1', 'dir' => 'asc',],
    ]]);
}

```
It orders columns from array, but doesn't change order icons in table header.

Is it possible to change Backpack code to change order icons in table header?
It is a visual issue, but it will be good to see the status.

Thank you.

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core

**Comment by pxpm** [comment]
@pcipov thanks for the report. 

This is kind of a minor bug (not functionality but visual like you said). 

I will discuss with @tabacitu and @promatik if we should address this a minor bug in 4.1 or postpone it as a feature to 4.2. 

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
Hmmm I think this happens because the AJAX request isn't actually made to the `index()` method (which loads the blade view with datatables) but to the `search()` method. So I'm not sure we can/should do anything to accomodate this.

But! I believe the same can be achieved in the same place, `setupListOperation`, by using `orderBy` directly on the query. So something like:

```diff
$this->crud->orderBy();
// or
$this->crud->query->orderBy();
```

**Comment by pxpm** [comment]
@tabacitu was rigth here. 

I think it should be applied in the crud query. 

I don't think there is much for us to do here, just write the query and order the results the way you need them. 

 Going to close this, please re-open if you feel this is not properly addressed.

Cheers
