### ISSUE TITLE
Two many to many relations between the two same tables

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#344]
Hello,

I have to set two N-N relations between the same two tables.
Both my relations are working independently. But when I have both at the same time i have a 500 error on my site. I'm lost, because everything in my code looks right.

Here is my tables :

table 1 | pivot table | table 2
------------ | -------------| -------------
personnes | personnes_relances | dates
personnes | personnes_relances_done | dates

date.php model
```
public function relances()
{
    return $this->belongsToMany('App\Models\Personne', 'personnes_relances', 'idDates', 'idPersonnes');
}
public function relancesdone()
{
    return $this->belongsToMany('App\Models\Personne', 'personnes_relances_done', 'idDates', 'idPersonnes');
}
```
personnes.php model
```
public function relances()
{
    return $this->belongsToMany('App\Models\Date', 'personnes_relances', 'idPersonnes', 
public function relancesdone()
{
    return $this->belongsToMany('App\Models\Date', 'personnes_relances_done', 'idPersonnes', 'idDates');
}
```

And in my DateCrudController.php i have
```
   $this->crud->addField([
            'label' => "Relance à faire",
            'type' => 'select2_multiple',
            'name' => 'relances',
            'entity' => 'relances',
            'attribute' => 'nom',
            'model' => "App\Models\Personne",
            'pivot' => true
        ]);
        $this->crud->addField([
            'label' => "Relance faites",
            'type' => 'select2_multiple',
            'name' => 'relancesdone',
            'entity' => 'relancesdone',
            'attribute' => 'nom',
            'model' => "App\Models\Personne",
            'pivot' => true
        ]);
```

**Comment by OwenMelbz** [comment]
Hi, are you able to post the actual error please? Should be able to look in your logs

**Comment by adbmdp** [comment]
Do you know where i can find it ? I'm working on Cloud9.

**Comment by adbmdp** [comment]
I don't have any error in my apache logs

**Comment by OwenMelbz** [comment]
Hey, sorry I dno where they'd be on Cloud9.

However if you check out https://laravel.com/docs/5.3/errors you should be able to confirm your configuration is correct for logging, and it should tell you where your laravel log file will be.

Once you've found the actual error will be much easier to diagnose! Very tricky to just guess at why it's not working :)

**Comment by adbmdp** [comment]
[:error] [pid 19246] [client 10.240.0.224:51334] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 978051 bytes) in /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php on line 49

[Sat Jan 07 16:44:58.989855 2017] [:error] [pid 19246] [client 10.240.0.224:51334] [2017-01-07 16:44:58] local.ERROR: exception'Symfony\\Component\\Debug\\Exception\\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 978051 bytes)' in /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/View/Engines/Phpes/PhpEngine.php:49\nStack trace:\n#0 {main}  \n

**Comment by OwenMelbz** [comment]
Well if you fix that problem it might help, or at least reveal the real issue! (if there is one) You'd need to find out how to adjust the memory limit for your hosting solution.

Different servers require you to do it in different ways. e.g some of them might allow you to do it via .htaccess - some might allow you to do it in php.

If you don't know how to do it for your server setup, its best just googling something like https://www.google.co.uk/search?q=php+adjust+memory+limit&oq=php+adjust+memory+limit&aqs=chrome..69i57.2544j0j7&sourceid=chrome&ie=UTF-8 and trying a few solutions until you've found one that works.

If you create a route like

```php
Route::get('/phpinfo', function () {
    phpinfo();
});
```

You'll be able to see what the memory limit is, then try increasing it and refreshing that page to see if it increases.

**Comment by adbmdp** [comment]
I've changed the memory_limit in my php.ini and it works.
My two tables were not so big (about 7000 rows)...
So be careful when you use select_multiple or select2_multiple as it loads into memory all the values when the page load.
Thanks a lot for your help OwenMelbz!

**Comment by OwenMelbz** [comment]
Ah brilliant :) Out of interest, what was your memory limit before? and what did you change it to?

**Comment by adbmdp** [comment]
I don't know the previous value. I'll have to check out how to view the php.ini of my host.
I've changed it to 256M in my own php.ini
