### ISSUE TITLE
Preview Button is not appearing i.e. ShowOpertaion is not working as expected in Backpack 4.0V 

### ISSUE THREAD

**Issue by sandeepchowdary7** [Laravel-Backpack/CRUD#3450]
# Bug report
The preview button is not showing. i.e. Show Functionality is not working in my CRUD Controller.
### What I did
I have added this to my controller class
```
use Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;

public function setupShowOperation()
    {
        $this->crud->addColumn([
            'name' => 'name',
            'label' => 'Name',
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhere('name', 'ilike', '%' . $searchTerm . '%');
            }
        ]);
    }
```
??

### What I expected to happen

I would like to see the preview button in ListView but it is not there.

### What happened

The preview button is not there. but If I add ```$this->crud->setFromDb();```
it is showing three-dot on the right side,  when you click on it is popping up all the columns. I wanna show only a few columns, not all the columns.

### What I've already tried to fix it

I have tried many including loading a custom show blade file still it is not working as expected.

### Backpack, Laravel, PHP, DB version
I'm in Backpack 4.0 Version

Thanks in Advance

**Comment by pxpm** [comment]
Hello @sandeepchowdary7 and thanks for the report.

`$this->crud->allowAccess('show')`, my guess is that in some other place you are doing `$this->crud->allowAccess('create/delete/wtv')` so only those are allowed.

Let me know. 

Pedro

**Comment by pxpm** [comment]
Closing due to incactivity. 

Please re-open if needed. 

Best,
Pedro
