### ISSUE TITLE
[Improvement] Consistent options for checklist with other relationship fields

### ISSUE THREAD

**Issue by o15a3d4l11s2** [Laravel-Backpack/CRUD#3455]
There is a slight difference between some of the fields, for example `checklist.blade.php` and `relationship_select.blade.php` in the way it works with user-provided `options`.

Checklist:
```php
  if (!isset($field['options'])) {
      $field['options'] = $field['model']::all()->pluck($identifiable_attribute, $key_attribute)->toArray();
  } else {
      $field['options'] = call_user_func($field['options'], $field['model']::query());
  }
```

Relationship_select:
```php
  if (!isset($field['options'])) {
    $field['options'] = $connected_entity::all()->pluck($field['attribute'],$connected_entity_key_name);
  } else {
    $field['options'] = call_user_func($field['options'], $field['model']::query())->pluck($field['attribute'],$connected_entity_key_name);
  }
```

Note the `call_user_func` behaviour - in the checklist only the user function is executed so the user should additionally pluck the id and value. In the relationship_select it executes the function and plucks based on the attribute.

I know this is a small detail, but since the `attribute` is required for the checklist field to work it would be better if it is used to pluck inside the field's logic.

Maybe you are already aware of this, but do not want to change it because it is a breaking change?

**Comment by pxpm** [comment]
Hello @o15a3d4l11s2 and thanks for the report. 

You are right here. Technically `checklist` is a `relationship`. But this concept of `relationships` was recently introduced and some bits of code slipped us.

Indeed, atm we cannot change it without a breaking change, but I will add this to be fixed in the next version where we could push BC. 

Wish you the best,
Pedro

**Comment by pxpm** [comment]
Hey @o15a3d4l11s2 hope you are doing well man 👍 

It seems I've missed a detail in my previous assessment of the issue. 😞 

We can make it non-breaking, in fact I already did in https://github.com/Laravel-Backpack/CRUD/pull/5562 🤷‍♂️ 

Thanks for the heads up 🙏 I will be closing this and move the conversation to the PR that should be merged shortly. 

If you give it a test, leave your thumbs up in the PR thread 👍

**Comment by o15a3d4l11s2** [comment]
Hi @pxpm, I am doing well, hope you are also doing well. I will try to give it a check and comment in the PR.
