### ISSUE TITLE
[Bug] backpack:crud TypeError in Symfony\Component\Process\Process::__construct() error

### ISSUE THREAD

**Issue by IoanAndrei97** [Laravel-Backpack/CRUD#3456]
# Bug report

### What I did
I used "php artisan backpack:crud SomeCrudName"

### What I expected to happen
Generate the all crud files.

### What happened
When I'm trying to generate a CRUD, this error occurs:  Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in Root_to_project\vendor\backpack\crud\src\app\Console\Commands\AddCustomRouteContent.php on line 73.

The exception is triggered after the controller, model and request are created ( this is the output in the console ).

### What I've already tried to fix it
Reinstalled the package on local & server, created a fresh laravel project with only 3 extra packages: backpack/crud, backpack/generators and laracasts/generators ( from documentation ).

When I run ```php artisan backpack:version``` the output is:
PHP Version: 7.4.3
Laravel Version: v8.21.0@a61cab167c35f465a923737ee6e6fb99cd5fde88
Backpack Version: 4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

**Comment by pxpm** [comment]
Hello @IoanAndrei97 

Can you post your `custom.php` routes ? Or make sure you have `}); // this should be the absolute last line of this file` as the last line in the file ? 

I just tested this myself and it's working afaik:

![image](https://user-images.githubusercontent.com/7188159/104183165-6fad4f80-5409-11eb-8d64-fa5d18e557be.png)

Best,
Pedro

**Comment by IoanAndrei97** [comment]
@pxpm 
Really sorry...I forgot to use "php artisan backpack:install" -.-

**Comment by pxpm** [comment]
No problem, I appreciate your coming back and close this issue. 

We have other mediums of comunication, usually we try to keep github only for bugs and/or features, if you use any of them, feel free to join us:

https://gitter.im/BackpackForLaravel/Lobby
https://www.reddit.com/r/BackpackForLaravel/
https://stackoverflow.com/questions/tagged/backpack-for-laravel

Best,
Pedro
