### ISSUE TITLE
Fields not marked as "fillable" do not get updated, no error generated

### ISSUE THREAD

**Issue by njbarrett** [Laravel-Backpack/CRUD#346]
Hey there, great work on this package.

I noticed that when testing a simple CRUD example, that unless I have the DB column inside the $fillable array within the Eloquent model, the CRUD controller wouldn't update the value.
Additionally, no error is generated, it returns a successfully updated message - not ideal.

**Comment by tabacitu** [comment]
Hi @njbarrett ,

Thanks for the report. I haven't gotten this myself, since I always prefer to use $fillable, but I'll investigate and get back to you.

Cheers!

**Comment by njbarrett** [comment]
Thanks - I just tried using `$guarded` instead and it's the same thing - it just silently fails. Ideally it would produce an error message do you think?

**Comment by OwenMelbz** [comment]
@njbarrett

Hey just to confirm, are you saying if nothing is inside $fillable it doesn't update anything?

**Comment by njbarrett** [comment]
@OwenMelbz that's also the case, but if an attribute is not in $fillable or is in $guarded then it fails to update that attribute and no error is generated to indicate that to the user.

**Comment by OwenMelbz** [comment]
Okay, sorry so I'm actually a bit confused lol

Isn't the whole point of laravels fillable and guarded to define what can be mass updated?

Therefore if you define nothing as fillable. It won't update anything? That is the expected result

There's no error here - just a developer doing something wrong?

**Comment by njbarrett** [comment]
I understand that's the expected behaviour but it confused the hell out of me why my model attributes weren't updated. If it produced an error to say "field xx couldnt be updated as it is not mass-assignable" that would make for a better experience IMO

**Comment by tabacitu** [comment]
I agree a notice/error would be helpful, but I'm not sure how we'd go about it.

The only way I see it possible is to have a "warning" notification bubble shown in addition to the "success" one, on local environment only. But I think it would annoy the hell out of me when testing, because most entities have non-editable columns...

What do you guys think, good/bad solution?

**Comment by OwenMelbz** [comment]
Personally I wouldn't change anything - I see it simply as a user error when developing - its how the underlying framework works, having the ability to learn to debug and understand things is more valuable so you won't do it in the future.

You wouldn't expect to see an error/notice message appearing telling you that you had not defined anything in your routes file, or that you have not defined all the columns/fields you want to see.

So personally I think its a waste of time, however if want to implement something then it should not be embedded into the templates - which adds bloat and mess to them, it should also be configurable.

So i would have something like a config item like `show_missing_fillables => true/false` 

Then in the CrudController do something like the below in the construct so it echos out before any real template data 

```php

if(config('backpack.crud.show_missing_fillables') && empty($this->model->fillable) && empty($this->model->guarded) && getenv('APP_ENV') == 'local') {
    echo '<div class="alert alert-warning" style="margin: 20px auto;">';
    echo '<h1>Warning: You have an empty $fillable or $guarded - to disable this message change 'backpack.crud.show_missing_fillables'</h1>';
    echo '</div>';
}
```

**Comment by tabacitu** [comment]
I the routes comparison is very apt and you make a very good point - Backpack is a framework, not an interface. I was leaning towards this anyway so I'm definitely biased, but your reply makes it a no-brainer for me :-)

For the time being, no warnings. If anybody disagrees, please leave a comment here. But I'll otherwise close the issue for now.

Cheers!

**Comment by Lzxe92** [comment]
This itself may have security flaw 

 

> **Mass Assignment**
> You may also use the create method to save a new model in a single line. The inserted model instance will be returned to you from the method. However, before doing so, you will need to specify either a fillable or guarded attribute on the model, as all Eloquent models protect against mass-assignment by default.
> 
> A mass-assignment vulnerability occurs when a user passes an unexpected HTTP parameter through a request, and that parameter changes a column in your database you did not expect. For example, a malicious user might send an is_admin parameter through an HTTP request, which is then passed into your model's create method, allowing the user to escalate themselves to an administrator.
> 
> So, to get started, you should define which model attributes you want to make mass assignable. You may do this using the $fillable property on the model. For example, let's make the name attribute of our Flight model mass assignable:


One of the solution i am doing right now is to remove the key in the request.

>   public function update(UpdateRequest $request)
>     {
>         $request->request->remove('important_data');
>         $redirect_location = parent::updateCrud($request);
>         return $redirect_location;
>     }

**Comment by tswonke** [comment]
You could define rules in your `UpdateRequest` (assuming that it's different to your `StoreRequest`) and use `$request->validated()` instead.

**Comment by tabacitu** [comment]
@Lzxe92 that's also a solution, if you're using guarded, I agree. Yes, you can also add/remove stuff from the request in the Validator, or use the validated request like @tswonke said (that will only pull the inputs that have been validated).

I personally prefer using ```$fillable```, not ```$guarder```. I think it's a more elegant way to fix all problems:
- you don't need to remove ```important_data``` from the request in the admin panel;
- you don't have to validate each and every input;
- you don't need to take this preventive approach _anywhere else_ inside your app, since prevention happens at the db-interaction level (the model);

**Comment by Lzxe92** [comment]
wow thanks @tabacitu  this is a great suggestion

**Comment by o5shorioush** [comment]
@tabacitu Why would the library use mass assignment in the first place? What if I wanted an attribute to be protected from mass assignment, but also I want to be able to create an item with such attribute through the panel? I mean I'm forced to create a vulnerability in the code so I can use the library?

**Comment by tabacitu** [comment]
> @tabacitu Why would the library use mass assignment in the first place? What if I wanted an attribute to be protected from mass assignment, but also I want to be able to create an item with such attribute through the panel? I mean I'm forced to create a vulnerability in the code so I can use the library? 

Nope - both Create and Update operations will only save the attributes that have fields. Attributes that have been specifically added by the developer, so he definitely wants them modified. Any other attributes will be ignored. Check the CreateOperation and UpdateOperation methods for a better insight into how it works. You'll see before saving it strips out any get/post parameter that doesn't have a field. You can change that behavior with a config though.

This thread is from many years ago 😉

**Comment by altayevrim** [comment]
I have some questions on this matter as well. So I have a group variable for users which I do not want any user to update but admins can update. If I remove `group` from `$fillable` Backpack cannot update it. If I put it, I am risking that in some point some user can change that variable in the future in case something goes wrong. What should I do about it? Is there a fix for that?

**Comment by tabacitu** [comment]
@altayevrim even if the `group` is fillable, if you don't have a field for it, people can't update it using the Backpack form. To make it clear, they a malicious actor _can_ add a `group` input to the form using DevTools. But Backpack will just ignore it. It will ONLY save what fields YOU have defined in PHP, ignores everything else. So it's safe to add with a conditional like:

```php
if ($blabla) {
    CRUD::field('group');
}
```
