### ISSUE TITLE
Problem with downloading with backpack/crud

### ISSUE THREAD

**Issue by kickball1214** [Laravel-Backpack/CRUD#3463]
# Bug report

### What I did
I want Create Admin panel in Laravel 8.* using Backpack , so in this directory of command prompt (C:\xampp\htdocs\exercises\fun>) I write this command composer require backpack/crud:"4.1.*"
??

### What I expected to happen

Package manifest generated successfully.

### What happened

 Failed to download backpack/crud from dist: curl error 28 while downloading https://codeload.github.com/Laravel-Backpack/CRUD/legacy.zip/62856b1f01fc3e05c80140fc22f85ea2aac8368c: Operation timed out after 300011 milliseconds with 26111768 out of 38096116 bytes received

### What I've already tried to fix it

I uninstall Xampp  and composer and tried several times but nothing happen.

**Comment by anandphulwani** [comment]
> 
> # Bug report
> ### What I did
> 
> I want Create Admin panel in Laravel 8.* using Backpack , so in this directory of command prompt (C:\xampp\htdocs\exercises\fun>) I write this command composer require backpack/crud:"4.1.*"
> ??
> ### What I expected to happen
> 
> Package manifest generated successfully.
> ### What happened
> 
> Failed to download backpack/crud from dist: curl error 28 while downloading https://codeload.github.com/Laravel-Backpack/CRUD/legacy.zip/62856b1f01fc3e05c80140fc22f85ea2aac8368c: Operation timed out after 300011 milliseconds with 26111768 out of 38096116 bytes received
> ### What I've already tried to fix it
> 
> I uninstall Xampp and composer and tried several times but nothing happen.

It's a connection timed out error, the file is getting downloaded successfully at my end, try again with a different internet, different computer and different project, if the problem persists try clearing cache, and if still you are unable to solved it come back again, also please describe the problem in "Subject" line, just typing "bug" doesn't help any and thus you should not expect much help, please be descriptive.

**Comment by kickball1214** [comment]
> > # Bug report
> > ### What I did
> > I want Create Admin panel in Laravel 8.* using Backpack , so in this directory of command prompt (C:\xampp\htdocs\exercises\fun>) I write this command composer require backpack/crud:"4.1.*"
> > ??
> > ### What I expected to happen
> > Package manifest generated successfully.
> > ### What happened
> > Failed to download backpack/crud from dist: curl error 28 while downloading https://codeload.github.com/Laravel-Backpack/CRUD/legacy.zip/62856b1f01fc3e05c80140fc22f85ea2aac8368c: Operation timed out after 300011 milliseconds with 26111768 out of 38096116 bytes received
> > ### What I've already tried to fix it
> > I uninstall Xampp and composer and tried several times but nothing happen.
> 
> It's a connection timed out error, the file is getting downloaded successfully at my end, try again with a different internet, different computer and different project, if the problem persists try clearing cache, and if still you are unable to solved it come back again, also please describe the problem in "Subject" line, just typing "bug" doesn't help any and thus you should not expect much help, please be descriptive.

**Comment by kickball1214** [comment]
> > # Bug report
> > ### What I did
> > I want Create Admin panel in Laravel 8.* using Backpack , so in this directory of command prompt (C:\xampp\htdocs\exercises\fun>) I write this command composer require backpack/crud:"4.1.*"
> > ??
> > ### What I expected to happen
> > Package manifest generated successfully.
> > ### What happened
> > Failed to download backpack/crud from dist: curl error 28 while downloading https://codeload.github.com/Laravel-Backpack/CRUD/legacy.zip/62856b1f01fc3e05c80140fc22f85ea2aac8368c: Operation timed out after 300011 milliseconds with 26111768 out of 38096116 bytes received
> > ### What I've already tried to fix it
> > I uninstall Xampp and composer and tried several times but nothing happen.
> 
> It's a connection timed out error, the file is getting downloaded successfully at my end, try again with a different internet, different computer and different project, if the problem persists try clearing cache, and if still you are unable to solved it come back again, also please describe the problem in "Subject" line, just typing "bug" doesn't help any and thus you should not expect much help, please be descriptive.



I don't have option to  use different internet or computer because I have only one  but I  don't think this is the problem because a month and a half ago everything was fine without giving me mistakes, because I needed this for a term paper at the university and then it didn't give me a mistake. But since I got a problem with phpMyAdmin and decided to start over by uninstalling everything (Xammp; Composer) and now when I try when I try the command "composer require backpack / crud:" 4.1. * "" My packages are installed except this backpack / crud as in cmd writes me first: Downloading backpack / crud (4.1.30) (this says it 4 times) and then :
Failed to download backpack/crud from dist: curl error 28 while downloading https://codeload.github.com/Laravel-Backpack/CRUD/legacy.zip/62856b1f01fc3e05c80140fc22f85ea2aac8368c: Operation timed out after 300000 milliseconds with 26327595 bytes received
    Now trying to download from source
  - Installing backpack/crud (4.1.30): Cloning 62856b1f01
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-KB26SQE+2021-01-18+1119
to retrieve a token. It will be stored in "C:/Users/chich/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden): 

I was clearing all cache on Windows too.
