### ISSUE TITLE
Radio field marks all radio options with red asterisk when required

### ISSUE THREAD

**Issue by zobay** [Laravel-Backpack/CRUD#3467]
# Bug report

### What I did
When I use radio buttons options for a required field, backpack adds asterisk to all options. 
![backpack](https://user-images.githubusercontent.com/35206101/104901179-3b0c3b80-59a7-11eb-8392-7d52cb705e41.png)

??

### What I expected to happen
It should add asterisk to the title only.
??

### What happened
But, It adds asterisk to all options along with title.
??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

backpack/crud": 4.1

**Comment by pxpm** [comment]
Thanks @zobay 

I could confirm the error.

I'v submited #3469 to fix it. 

Wish you the best,
Pedro

**Comment by pxpm** [comment]
@zobay the PR that fixes this have been merged into master and will soon be tagged. When it does, you need to update backpack and republish assets:

https://backpackforlaravel.com/articles/tips-and-tricks/once-in-a-while-re-publish-backpack-s-css-and-js-assets


Best,
Pedro
