### ISSUE TITLE
[BUG]Problem with downloading with backpack/crud

### ISSUE THREAD

**Issue by kickball1214** [Laravel-Backpack/CRUD#3468]
# Bug report

### What I did

I want Create Admin panel in Laravel 8.* using Backpack , so in this directory of command prompt (C:\xampp\htdocs\exercises\fun>) I write this command composer require backpack/crud:"4.1.*"
??

### What I expected to happen

Package manifest generated successfully.

### What happened
First they said me it was internet problem.
I don't have option to use different internet or computer because I have only one but I don't think this is the problem because a month and a half ago everything was fine without giving me mistakes, because I needed this for a term paper at the university and then it didn't give me a mistake. But since I got a problem with phpMyAdmin and decided to start over by uninstalling everything (Xammp; Composer) and now when I try when I try the command "composer require backpack / crud:" 4.1. * "" My packages are installed except this backpack / crud as in cmd writes me first: Downloading backpack / crud (4.1.30) (this says it 4 times) and then :
Failed to download backpack/crud from dist: curl error 28 while downloading https://codeload.github.com/Laravel-Backpack/CRUD/legacy.zip/62856b1f01fc3e05c80140fc22f85ea2aac8368c: Operation timed out after 300000 milliseconds with 26327595 bytes received
Now trying to download from source

Installing backpack/crud (4.1.30): Cloning 62856b1
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-KB26SQE+2021-01-18+1119
to retrieve a token. It will be stored in "C:/Users/chich/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

### What I've already tried to fix it

I uninstall Xampp and composer and tried several times but nothing happen. I was clearing all cache on Windows too. 

### Backpack, Laravel, PHP, DB version

Laravel v8.22.1 (PHP v7.4.10)

**Comment by pxpm** [comment]
Hello @kickball1214 

One of your users also reported the same problem on Friday I think. 

I think he solved his problem after I suggested him to `composer clear-cache` 

![image](https://user-images.githubusercontent.com/7188159/104905522-675d9300-597a-11eb-9729-7c9a6d817a3a.png)

But the cloning operation runned ok. Did you added your ssh key to composer like the issue describes ? 

Best,
Pedro

**Comment by kickball1214** [comment]
Hello Pedro ,

I tried what you suggest composer clear-cache but again same problem. But I didn't add ssh key to composer because I don't know how to do. Can you explain me how to do it ? 

> Hello @kickball1214
> 
> One of your users also reported the same problem on Friday I think.
> 
> I think he solved his problem after I suggested him to `composer clear-cache`
> 
> ![image](https://user-images.githubusercontent.com/7188159/104905522-675d9300-597a-11eb-9729-7c9a6d817a3a.png)
> 
> But the cloning operation runned ok. Did you added your ssh key to composer like the issue describes ?
> 
> Best,
> Pedro

Hello Pedro,
I tried what you  suggest `composer clear-cache` but again same problem. But I didn't add ssh key to composer because I don't know to do it . Can you explain me how to do it ? Thanks !

**Comment by pxpm** [comment]
Hello @kickball1214 

I think you just need to follow what is said to you in the command output:

```php
enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-KB26SQE+2021-01-18+1119
to retrieve a token. It will be stored in "C:/Users/chich/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):
```
After visiting the url, you will get a token that you should `copy` and `paste` into your command line after `Token(hidden)`. 

Please not that after `pasting`, the token will not be shown, just hit `Enter`.

I am going to close this, I am pretty sure that clearing composer cache and cloning works fine. 

If you have any errors please head up to https://gitter.im/BackpackForLaravel/Lobby we use github mainly for bugs/features.

Thanks in advance,
Pedro

**Comment by icarojobs** [comment]
Good morning guys,

Even running composer cache-clear it didn't work for me. Below are the settings of my project:

PHP: 8.0.1
Laravel: 8.22.1

What happens is that when installing backpack / crud (4.1.30) it locks on the progress bar and does not download the package.

**Comment by pxpm** [comment]
@icarojobs when it is stuck, let it be. Until it timeout. (it can take more than one minute stuck and then download/timeout)

If it timeout, make sure you are running the latest composer version (now 2.0 I think) `composer self-update`, then clear composer cache, and try again.

When the download fails, composer should directly clone the repository from the source (github). 

Let me know how it goes for you. 

Best,
Pedro

**Comment by icarojobs** [comment]
@pxpm solve my problem!

Perfect Pedro!

It worked fine here! Thank you so much!
