### ISSUE TITLE
[Feature] More methods for allowing access

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#347]
Since CRUD gives access by default to xxx and that's pretty hidden inside the source, some new methods should come in handy:
- ```$this->crud->denyAllAccess();``` 
- ```$this->crud->allowAccessOnlyTo()```;

Any thoughts on better naming?

**Comment by M0H3N** [comment]
thanks ... I think so  the naming is OK

**Comment by lloy0076** [comment]
Please feel free to re-open when there is a PR.

**Comment by pekka** [comment]
This would be great to have from a security viewpoint.

It would allow us to clear the plate first:

`$this->crud->denyAllAccess();`

and then incrementally enable rights one by one:

```
if (condition_a) $this->crud->allowAccess('create');
if (condition_b) $this->crud->allowAccess('update');
if (condition_c) $this->crud->allowAccess('delete');

```
As I understand it, the current way to remove all access is still  to call `denyAccess()` with each action that is activated by default:

`$this->crud->denyAccess(['create','update','delete','show']);`

but the set of default actions could change in the future, opening up a potential hole.

If there is already a way to deny all access that I haven't found yet, or if there's a flaw in my thinking, would like to hear it 👍

**Comment by tabacitu** [comment]
Yup, I also think we should revisit this idea. Thanks for resurfacing this @pekka !

**Comment by pxpm** [comment]
I've implemented a "proxy" between crud access and spatie permissions in a trait in a project sometime ago.

So that in any controller I use that trait, the spatie permissions for that user are mapped into crud access. 

Spatie permission is just an example, we should be able to also use Gates and other Laravel policy mechanisms. 

I also like this idea 👍

**Comment by promatik** [comment]
https://github.com/Laravel-Backpack/CRUD/pull/5383
https://github.com/Laravel-Backpack/CRUD/pull/5384

We have them now 🎉
