### ISSUE TITLE
[Bug] Video Course Cannot Display

### ISSUE THREAD

**Issue by abdfttysn** [Laravel-Backpack/CRUD#3479]
In Getting Started Videos Pages, the video cannot be displayed.
The error message was: "In Getting Started Videos Pages, the video cannot be displayed"

**Comment by promatik** [comment]
Hi @abdfttysn! Can you try again? I just tried on Chrome, Edge and Firefox, and all the videos are working.
Maybe vimeo was temporarily down?
Thanks!

**Comment by promatik** [comment]
@abdfttysn I'll close this for now, let me know if you still have problems watching the videos 🙌
