### ISSUE TITLE
[Feature Request]use the route_prefix as part of the name of the route

### ISSUE THREAD

**Issue by rabol** [Laravel-Backpack/CRUD#3481]
# Feature Request

### What's the feature you think Backpack should have?

There is named routes, however the name is not related to admin e.g. if you crud for Recipe, then one named route would be `recipe.show`, that mean that in the frontend of the app it is not possible to have a named route `recipe.show`

### Have you already implemented a prototype solution, for your own project?

yes, in the backpack/custom.php i have added

`'as' => config('backpack.base.route_prefix', 'admin') . '.'`

### Do you see this as a core feature or an add-on?

Core

**Comment by promatik** [comment]
Hi @rabol.
Totally agreed!
Once again, backpack can and should avoid possible conflicts with the frontend, having all it's route names prefixed with `'admin'` is the best approach.

I think this is a breaking change, developers on the current v4.1 may be relying on those names, gladly v4.2 is close to come 🙌

**Comment by tabacitu** [comment]
Totally agree with you guys. It's already on the roadmap for 4.2 - https://github.com/Laravel-Backpack/ideas/issues/2 so let's move the conversation there please 🙏 There's a discussion to be had, whether it's best to have `admin`, `backpack` or something else as the route name prefix.
