### ISSUE TITLE
[Bug] TabsType is not fetched correctly from config

### ISSUE THREAD

**Issue by dejury** [Laravel-Backpack/CRUD#3485]
# Bug report

### What I did

I set the tab type to "vertical" for operation type "update". In the backpack/crud.php config file.

### What I expected to happen

To show the tabs in vertical view.

### What happened

Still in horizontal view.

### What I've already tried to fix it

I looked it up in the code, the Tabs CrudPanel Trait is incorrect, it searches for:
"backpack.crud.{operationtype}.tabsType", should be:

"backpack.crud.operations.{operationtype}.tabsType".

### PHP VERSION:
PHP 7.4.14 (cli) (built: Jan  8 2021 13:20:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.31@e0c389acce2617099a69d0b6076dfad24385295f

I will try to make a PR for this one.

**Comment by pxpm** [comment]
Hello @dejury 

Thank you very much for spotting this, I think I never used vertical tabs in Backpack, so I assume this would be long time hidden from me. 🙃 

I'v just approved your PR, it should be merged to master by next monday atmost. Going to close this, let's keep any further conversation if needed in the PR thread. 

Thanks again,
Pedro
