### ISSUE TITLE
OrderBy on a cryptable data

### ISSUE THREAD

**Issue by eaziweb95** [Laravel-Backpack/CRUD#3488]
# Bug report

### What I did

I try to order a list of persons with their name. But this name is crypted in DB and the order is not right.
How can i do to order the list with the uncrypted name ?

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @eaziweb95 

You might be able to use `DB::` raw statements and do your checks/order in database or only the ordering with `orderByRaw()` (also like name implies, is raw sql commands). https://laravel.com/docs/8.x/queries#raw-expressions

Other than that just get all users unordered, decrypt the name, order by decrypted name, and return them.

I don't think there is any Backpack bug here, so I am going to close this. If I am wrong, and sometimes I am, please re-open.

Best,
Pedro
