### ISSUE TITLE
[Feature Request] Can it be possible to show related entries of specific model i.e cars have reviews in a table pannel on show / preview view ?

### ISSUE THREAD

**Issue by usman19977** [Laravel-Backpack/CRUD#3489]
# Feature Request

### What's the feature you think Backpack should have?

Can it be possible to show related entries of specific model i.e cars have reviews in a table pannel on show/preview view ?

### Have you already implemented a prototype solution, for your own project?

I had to implement soo far what I had achieved by modifying the core of backpack CrudPannel and CrudTraits I created my own trait of pannel and it is working but it only show car name maybe i am missing something I am attaching a photo i also created a custom field for it 
![Screenshot 2021-01-29 at 9 45 02 PM](https://user-images.githubusercontent.com/50178849/106303489-00928080-627c-11eb-8782-e7f948c59fce.png)
![Screenshot 2021-01-29 at 9 46 02 PM](https://user-images.githubusercontent.com/50178849/106303507-05efcb00-627c-11eb-92e3-ebc5679c93f6.png)

### Do you see this as a core feature or an add-on?

yes I go through them if you have anything prebuild tell me, i am new to backpack but senior on laravel ;-)

**Comment by usman19977** [comment]
Any hope ? @tabacitu sir or any expert opinion

**Comment by promatik** [comment]
Hi @usman19977!

I think there is and addon provided by @izica to do what you need.
It allows you to add Widgets with the entity relations.

https://github.com/izica/relations-widgets-for-backpack

Let me know if this is what you need 🙌

**Comment by usman19977** [comment]
> Hi @usman19977!
> 
> I think there is and addon provided by @izica to do what you need.
> It allows you to add Widgets with the entity relations.
> 
> https://github.com/izica/relations-widgets-for-backpack
> 
> Let me know if this is what you need 🙌

Where were you before bro ? :-D thanks you saved me ^_^ <3

**Comment by promatik** [comment]
@usman19977 perfect 👌
Sorry for the delay 😅 I'll close the issue for now.
