### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pcipov** [Laravel-Backpack/CRUD#3492]
# Bug report

### What I did

Use range filter

### What I expected to happen

Clear button in range filter has to clear filter.

### What happened

Clear button in range filter doesn't work.

### What I've already tried to fix it
FIX:
Change line 123 in file range.blade.php

from> $('li[filter-name={{ $filter->key }}]').trigger('filter:clear');
to> $('li[filter-key={{ $filter->key }}]').trigger('filter:clear');

### Backpack, Laravel, PHP, DB version
v8.24.0@d16e9f875e4d7609a05d5007393e22ba95efd1fc

When I run ```php artisan backpack:version``` the output is:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

**Comment by pxpm** [comment]
Thanks @pcipov for the time spent to bring this to our atention.

I'v just created a PR #3512 to fix it. It should soon be merged and tagged. 

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
Merged! Will be tagged later today 🥳 Thanks @pcipov & @pxpm .
