### ISSUE TITLE
A small spelling / grammar mistake in content

### ISSUE THREAD

**Issue by maurya03189** [Laravel-Backpack/CRUD#3493]
while referring to the documentation, I found a small spelling mistake in the content.
Link: https://backpackforlaravel.com/docs/4.1/crud-how-to#add-a-select2-field-that-depends-on-another-field
Please check the attached screenshot for your reference.
![screenshot-backpackforlaravel com-2021 02 01-07_52_42](https://user-images.githubusercontent.com/32223358/106407734-d0590680-6462-11eb-9c7a-0f7a381b25e3.png)

**Comment by pxpm** [comment]
Thanks @maurya03189 for taking time to report this issue.

I'v just submitted a PR to the docs with this correction.

Best,
Pedro
