### ISSUE TITLE
[Bug] Image field missing prefix inside repeatable

### ISSUE THREAD

**Issue by o15a3d4l11s2** [Laravel-Backpack/CRUD#3500]
# Bug report

### What I did

I created an image field inside repeatable. The image field contains `prefix`, as I manually save the image from the json data and store only the image name in the database as part the data. All this is in an `extras` column, because this whole form is used inside a page template.

```php
CRUD::addField([
    'name' => 'services',
    'label' => 'Services',
    'type' => 'repeatable',
    'fake' => true,
    'store_in' => 'extras',
    'fields' => [
        [
            'name' => 'title',
            'type' => 'text',
            'label' => 'Title',
        ],
        [
            'name' => 'image_name',
            'type' => 'image',
            'label' => 'Image',
            'prefix' => 'uploads/services/',
        ],
    ],

    'new_item_label' => 'Add service',
]);
```

### What I expected to happen

I expect that the actual image shows.

### What happened

The image is not displaying, as the image `src` contains only the image name and not the prefix.

### Some insight

The `repeatable.blade.php` fields use
```php
$(this).val(values[$(this).data('repeatable-input-name')]);
```
to set the value of the input field that later populate the image src.

Additionally, `image.blade.php` field prepends the prefix on the value:
```php
// if value isn't a base 64 image, generate URL
if($value && !preg_match('/^data\:image\//', $value)) {
    // make sure to append prefix once to value
    $value = Str::start($value, $field['prefix']);

    // generate URL
    $value = $field['disk']
        ? getDiskUrl($field['disk'], $value)
        : url($value);
}
```
but the value is not set here yet, it is later set through JS.

So because of these two the prefix cannot be applied on the image field.

The only workaround for the moment is to put the prefix as part of the image name. I cannot think of a clean solution to prepend the prefix from the repeatable field, without making it very specific.

**Comment by pxpm** [comment]
Hey @o15a3d4l11s2 

Sorry for taking some time to come back here. 

I'v thinkered a bit on how to make it work, I think if we make it more general, we can fix it in repeatable. 

That said, i'v submitted PR #3538 , it's open for discussion on what's the best way to deal with this. You are very welcome to give your inputs there, we really appreciate user feedback. 

Going to close this so we don't spare the conversation. 

Thanks for finding the issue and taking time to report it. 

Best,
Pedro
