### ISSUE TITLE
[Bug] Nested relations on select columns are broken

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/CRUD#3503]
# Bug report

### What I did

I have a model setup with categories; each category has many subjects; each subject has many skills. Conversely, each skill has one subject and each subject has one category.

On my SkillCrudController, I have a `type => select` column with `name => category` and `entity => 'subject.category'`. After this, I tried listing the skills.

### What I expected to happen

The category to appear in the resulting list.

### What happened

A `BadMethodCallException` was thrown.

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 4.1.31 (problem occured after upgrading from 4.1.27)

**Comment by jnoordsij** [comment]
See also https://github.com/Laravel-Backpack/CRUD/pull/3504

**Comment by pxpm** [comment]
Thanks for the report @jnoordsij 

I answered you in the PR #3504 thread. I will be closing this so we don't have split conversations on the same subject.

Thanks again,
Pedro
