### ISSUE TITLE
[Bug] Re-introduced Date Range field's endDate hidden input use a date format that is different than the startDate (javascript)

### ISSUE THREAD

**Issue by mamarmite** [Laravel-Backpack/CRUD#3506]
# Bug report

### What I did

Updated to 4.1 and working with the date_range.blade.php field.

### What I expected to happen

Date to be in the same format.

### What happened
The endDate miss an H in its format, so the result differ from startDate and endDate and validation, and date casting with format throw errors.

### What I've already tried to fix it

I updated the endDate format as the startDate format in fields/date_range.blade.php.
I created a branch and everything ready for a PR, but I re-search for an already issue and I found one. So I stop and change the narrative for letting the team know about this tiny issue.
@fakefakers already fix that in this commit : 3e8abeefef80a625d64ea6dc9de80747dde5e4d1 on april 1 2020. It's the commit on appril that return the tiny bug; if I follow the file history : https://github.com/Laravel-Backpack/CRUD/commits/master/src/resources/views/crud/fields/date_range.blade.php

After that, I'm out of clue, for what is the best way for fixing this kind of git history or juste remerging the fix ? I'll learn a lot from what you'll do :)

Anyhow, let me know what is the simplest way of fixing this ? A new PR or something. I'm not shure what is best for that kind of fix.

**Note:** The 4.2 branch have this issue too. 

#### PHP VERSION:
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

#### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

#### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

Thanks in advance and have a good day :)

**Comment by pxpm** [comment]
Hello @mamarmite thanks for the report.

Indeed, I think this slipped us. So sorry. The fix had been merged in 4.0.x branch, but was not carried over to 4.1. Dunno why exactly at the moment. 

But it's a bug for sure, so if you are willing to send a PR for it, I will review and merge it asap. Send the PR to 4.1 branch (master).

If you don't have time or some other reason don't allow you to do it, just let me know and I can do it, no worries.

Best,
Pedro

**Comment by mamarmite** [comment]
Yes, np :) The PR was already added in github. I wasn't shure if that would be the good way of fixing this issue.
It's added : #3509.

**Comment by pxpm** [comment]
Closed by PR #3509
