### ISSUE TITLE
[Bug] upload_multiple delete files not working when uploading

### ISSUE THREAD

**Issue by dejury** [Laravel-Backpack/CRUD#3510]
# Bug report

### What I did

I am using the upload_multiple field for uploading multiple files, you wouldn't expect that ;)

`[
    'name' => 'files',
    'label' => 'Bestanden',
    'type' => 'upload_multiple',
    'upload' => true
]`

I did some uploads and saved the page. Afterwards I am back to editing the page, and want to remove some files and then immediately attach some new files.

### What I expected to happen

Deleted files get deleted, new files get attached.

### What happened

Only the new files get attached, the clear_files array is empty.
When I first upload the files and then delete it is working.

### What I've already tried to fix it

There seems to be an issue in the JS implementation which is causing this issue, there is an hidden element that is being removed after a file is uploaded. The wrong hidden element is removed.

I will create an PR for this issue.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.14 (cli) (built: Jan  8 2021 13:20:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.32@1a65e15562989c8fda3d2941da7110ca4008e21e

**Comment by pxpm** [comment]
Totally @dejury 

Just replied to you in the PR thread. 

Going to close this, you know the deal already, let's keep the discussion about it in the PR thread. :)

Wish you the best,
Pedro
