### ISSUE TITLE
4.1.* install on Laravel 8 [Bug] 

### ISSUE THREAD

**Issue by jonnymholt** [Laravel-Backpack/CRUD#3515]
# Bug report

### What I did

`./vendor/bin/sail composer require backpack/crud:"4.1.*"`

### What I expected to happen

Install backpack

### What happened

Following output
 Problem 1
    - backpack/crud[4.1.22, ..., 4.1.x-dev] require doctrine/dbal ^2.5 -> found doctrine/dbal[v2.5.0-BETA2, ..., 2.12.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - backpack/crud[4.1.0, ..., 4.1.21] require laravel/framework ^7.0|^6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.12).
    - Root composer.json requires backpack/crud 4.1.* -> satisfiable by backpack/crud[4.1.0, ..., 4.1.x-dev].

### What I've already tried to fix it

Googled, from what I can tell it looks like an issue in dependecies and doctrine/dbal 3.0, as well as laravel/framework 8 not being supported? But documentation suggests this should not be so and that backpack should work on a fresh install.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

There are no commands defined in the "backpack" namespace.

PHP 8.0.1
Laravel Framework 8.25.0

**Comment by promatik** [comment]
Hi @jonnymholt!
Thank you for the report, this is known bug for now, unfortunately Backpack still doesn't support PHP 8

We have an open issue for that, https://github.com/Laravel-Backpack/CRUD/issues/3359.
I think @tabacitu was going to take a look on that this week, I'm not sure. But this is something we really want and I hope we can provide as soon as possible 🙌

**Comment by tabacitu** [comment]
**Update:** Backpack now supports PHP 8 🥳 However, we the error above doesn't seem to be about the PHP version, but about the DBAL v3 - which we don't yet support (see #3517 ), but we will. If you can downgrade your `composer.json` requirement for DBAL, it should work until then. Hope it helps someone.

Cheers!
