### ISSUE TITLE
[Bug] persistenTable doesn't seem to work with bulk actions 

### ISSUE THREAD

**Issue by gthu96** [Laravel-Backpack/CRUD#3524]
# Bug report

### What I did

I have set persistentTable to true under list operation in crud.php

### What I expected to happen

To stay in the same page after operations.

### What happened

It is working fine for edit & when moving to other pages. But it doesn't work on bulk actions & deletion.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.28.3@b0942c391975972b1a54b2dc983e33a239f169a9

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by splifted** [comment]
I agree

**Comment by promatik** [comment]
Hi @gthu96 can you provide more details on this?
I just tried Bulk Operations with persistent tables active, and everything is working as expected.
I'm able to delete and clone one or multiple itens.

@splifted, can you also provide your input?
Thank you 🙌

**Comment by gthu96** [comment]
Hi @promatik thanks for the reply.
whenever i do a bulk operation, delete or a custom one in say page 8. After the operation it is taking me to the first page always.
I want to stay in the same page!.
When you tried does it go back to the same page ?

**Comment by promatik** [comment]
Hi @gthu96!
Now I get it! it's changes the page when reloading, I tried only on the first page ...
Thanks, I'm on it 🙌

**Comment by promatik** [comment]
@gthu96 thank you for your feedback, I've just created a PR to fix this 🙌
Let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/3532.
