### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kpruhs** [Laravel-Backpack/CRUD#3528]
# Getting undefined index error when running backpack:build and backpack:crud commands

### What I did
Ran `php artisan backpack:build` or `php artisan backpack:crud <ModelName>`

### What I expected to happen
Generate models, controllers, requests, and tests without errors.

### What happened
Getting *undefined index* error when running: `php artisan backpack:build` or `php artisan backpack:crud <ModelName>`.

### What I've already tried to fix it
The error occurs in `vendor/backpack/crud/src/app/Console/Commands/AddCustomRouteContent.php:61`, when it tries to add the new route to `routes/backpack/custom.php`. I found it was failing in the `customRoutesFileEndLine()` method.

Essentially `customRoutesFileEndLine()` was not able to find the last line of the custom.php routes file. It is using `array_search()` but for some reason is always failing. I don't know if this is just my system or if others are having this issue too.

The code below fixes the problem, in a not-so-elegant way. But, it works and it can replace customRoutesFileEndLine method. Please let me know if others are having this issue or if it's unique to my situation. 

```php
private function customRoutesFileEndLine($file_lines) {
        $serachText = '});';
        $end_line_number = false;
        $lastLineNo = array_key_last($file_lines);
        
        while ($lastLineNo !== 0) {
            $lastLine = $file_lines[$lastLineNo];
            $end_line_number = (strpos($lastLine, $serachText)) ? $lastLineNo : false;
            $lastLineNo--;
    
            if ($end_line_number !== false) {
                break;
            }
        }
    
        return $end_line_number;
    }
```

### Backpack, Laravel, PHP, DB version

* MySQL 5.7.32
* PHP v7.4.14
* Laravel v8.27.0
* backpack/crud v4.1.33
* backpack/generators v3.1.7

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.14 (cli) (built: Jan  8 2021 13:20:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.14, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.27.0@a6680d98f9dadaa363aa7d5218517a08706cee64

### BACKPACK VERSION:
4.1.33@a8c27854f2d7fb326deef48e4cae112bfcd506ae

**Comment by promatik** [comment]
Hi @kpruhs, can you tell us more about the error?
Do you know why the functions is not working?

Perhaps your `custom.php` is  formatted like this;
```php
}
); // this should be the absolute last line of this file
```

or  with a space between `}` and `)`?
```php
} ); // this should be the absolute last line of this file
```

**Comment by promatik** [comment]
@kpruhs I just made this function more bullet proof.
It in this branch; https://github.com/Laravel-Backpack/CRUD/compare/fix-3528

If you have the time can you test it and tell me if it solves your problem?
Thanks!

**Comment by kpruhs** [comment]
I really don't have much more to add. I can paste in a copy of the custom.php file but it's basically a fresh iinstall. No changes. The closing symbols are exactly as they should be - });

It worked after I wrote the new code (included above). You'll see that I'm searching - and finding - the ending symbols successfully. 

I will download the fix. Thanks for your help on this.

**Comment by promatik** [comment]
I've just create #3567 with the proposed solution. We will deal with it on v4.2.
Thank you for submitting the issue @kpruhs 👍
