### ISSUE TITLE
restoreRevision error 500 with fake fields

### ISSUE THREAD

**Issue by kichetof** [Laravel-Backpack/CRUD#353]
Hi,
Thanks for your great Admin panel, really good!
I'm just starting with it and I already love it!!! <3

I encounter a bug when revision are enable and when I would like to restore one.
I found the bug (I hope), but don't know how to solve it.

When a revision POST are sended, in Page Model for example:
``` php
Route::post('page/{id}/revisions/{revisionId}/restore', 'Admin\PageCrudController@restoreRevision');
```

The function `restoreRevision` from `Backpack\CRUD\app\Http\Controllers\CrudFeatures\Revisions` is executed. The bug come from `$this->crud->restoreRevision($id, $revisionId); // do the update`

Bug appear when the entry will be saved on `restoreRevision` function from `Backpack\CRUD\PanelTraits\ViewsAndRestoresRevisions`

``` php
// file Backpack\CRUD\PanelTraits\ViewsAndRestoresRevisions.php

public function restoreRevision($id, $revisionId)
    {
        $entry = $this->getEntry($id);
        $revision = Revision::findOrFail($revisionId);

        // Update the revisioned field with the old value
        $entry->{$revision->fieldName()} = $revision->oldValue();
        //dd($entry); //return the object <-- OK
        $entry->save(); // <-- BUG

        // Reload the entry so we have the latest revisions
        $entry = $this->getEntry($id);
    }
```

This is my SQL data
``` SQL
INSERT INTO `pages` (`id`, `template`, `name`, `title`, `slug`, `content`, `extras`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'services', 'test1', 'Test1', 'test1', '<p>blablabla</p>\r\n\r\n<p>fdsajlkfdsa</p>\r\n\r\n<p>dsafsaf</p>\r\n', '{\"meta_title\":null,\"meta_description\":null,\"meta_keywords\":null}', '2017-01-10 12:59:12', '2017-01-10 14:12:17', NULL);
```

My object attributes
``` php
#attributes: array:13 [▼
    "id" => 1
    "template" => "services"
    "name" => "test1"
    "title" => "Test1"
    "slug" => "test1"
    "content" => "<p>blablabla</p>\r\n"
    "extras" => "{"meta_title":null,"meta_description":null,"meta_keywords":null}"
    "created_at" => "2017-01-10 13:59:12"
    "updated_at" => "2017-01-10 15:12:17"
    "deleted_at" => null
    "meta_title" => null // <-- fake field converted from extras
    "meta_description" => null // <-- fake field converted from extras
    "meta_keywords" => null // <-- fake field converted from extras
  ]
```
And my error log
`
[2017-01-10 15:39:07] local.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta_title' in 'field list' in /var/www/public/new/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
`

As you can see, my Page model has an extras field (fake fields) where data are stored in JSON. When `$this->getEntry($id);` obtain the object, the extras column seem to be deployed to attributes (`function getFakeColumnsAsArray` from `Backpack\CRUD\PanelTraits\FakeColumns` and when the `save()` function is called, these 3 columns doesn't exists in my table.

I think, before saving, it should be deleted fake attributes that doesn't exist on table, but how to do that properly ?

_Bug confirmed with revision on a model with fake fields. Without fake fields, revision works well._

I hope that my explanations are not so ambiguous :)
If you need anything else, don't hesitate to ask.
Big thanks for your great works
Bests
Tof

_My configuration is:
PHP 7.1.0
mysql Ver 15.1 Distrib 10.1.20-MariaDB
Fresh install of Laravel (v5.3.29)
Backpack CRUD 3.1_

**Comment by tabacitu** [comment]
Excellent bug report @kichetof , thanks a lot!

It's now fixed, a ```composer update``` should do it for you.

Cheers!

**Comment by dontfreakout** [comment]
Hello, 

the problem still exists in latest CRUD and Laravel. 
Eloquent updates model in **performUpdate()** and there it finds what to update using **getDirty()** method: 

_(in L5.3: `Illuminate\Database\Eloquent\Model` class, 
in L5.4: `Illuminate\Database\Eloquent\Concerns\HasAttributes` Trait)_

```php
    /**
     * Get the attributes that have been changed since last sync.
     *
     * @return array
     */
    public function getDirty()
    {
        $dirty = [];

        foreach ($this->attributes as $key => $value) {
            // Set to update values in attributes which are not in $originals array
            if (! array_key_exists($key, $this->original)) {
                $dirty[$key] = $value;
            } elseif ($value !== $this->original[$key] &&
                                 ! $this->originalIsNumericallyEquivalent($key)) {
                $dirty[$key] = $value;
            }
        }

        return $dirty;
    }
```
It select all attributes which are modified or are not in `$originals`, therefore all fake fields.
I tested it in Tinker and if you get the model with `withFakes()` and you try to update something, it fails with `Column not found` error as @kichetof posted. If you try the same model without fakes, it updates.

### My solution

Simplest solution for me was to modify **getEntry()** method in `Backpack\CRUD\PanelTraits\Read` trait to accept second param `$withFakes` to optionally not include fake fields. And **restoreRevision()** in `Backpack\CRUD\PanelTraits\ViewsAndRestoresRevisions` trait to call `getEntry($id, $withFakes = false)`

**Backpack\CRUD\PanelTraits\Read:**
```php
    /**
     * Find and retrieve an entry in the database or fail.
     *
     * @param  [int] The id of the row in the db to fetch.
     *
     * @return [Eloquent Collection] The row in the db.
     */
    public function getEntry($id, $withFakes = true)
    {
        $this->entry = $this->model->findOrFail($id);
        if ($withFakes === true) {
            $this->entry = $this->entry->withFakes();
        }

        return $this->entry;
    }
```

**Backpack\CRUD\PanelTraits\ViewsAndRestoresRevisions:**
```php
    /**
     * Restore a single revision.
     *
     * @param  [int] $id         The ID of the source CRUD Model instance to update
     * @param  [int] $revisionId The ID of the revision to use for the update
     */
    public function restoreRevision($id, $revisionId)
    {
       // Do not include fake fields
        $entry = $this->getEntry($id, false);
        $revision = Revision::findOrFail($revisionId);

        // Update the revisioned field with the old value
        $entry->update([$revision->key => $revision->old_value]);

        // Reload the entry so we have the latest revisions
        $entry = $this->getEntry($id);
    }
```

Thank you for this awesome CRUD package :+1:  
and i f you need anything from me, feel free to ask :)

Bests
Martin
