### ISSUE TITLE
[Bug] Reorder not working properly for large lists

### ISSUE THREAD

**Issue by skruzic** [Laravel-Backpack/CRUD#3531]
# Bug report

### What I did

I built an app which has Campaign model and related hasMany Question model. The Question model has reorder functionality, as follows (please note, in the example I set the depth of reorder at 2, but for now in the testing I only used a dataset of depth 1, i.e. flat list).

CRUD:
```
class QuestionCrudController extends CrudController
{
    use ListOperation, CreateOperation, UpdateOperation, DeleteOperation, ReorderOperation, FetchOperation;

    protected $campaign_id;

    public function setup()
    {
        $this->campaign_id = \Route::current()->parameter('campaign_id');
        CRUD::setModel('App\Models\Question');
        CRUD::setRoute('admin/campaign/'.$this->campaign_id.'/question');
        CRUD::setEntityNameStrings('question', 'questions');
        CRUD::addClause('where', 'campaign_id', $this->campaign_id);
        CRUD::orderBy('lft');

        CRUD::allowAccess('reorder');
        CRUD::enableReorder('question', 2);

        $this->data['breadcrumbs'] = [
            trans('backpack::crud.admin') => backpack_url('dashboard'),
            'Campaigns'                   => backpack_url('campaign'),
            'Questions'                   => backpack_url('campaign/'.$this->campaign_id.'/question'),
            trans('backpack::crud.list')  => true,
        ];
    }

    (...)

    public function setupReorderOperation()
    {
        CRUD::set('reorder.label', 'text');
        CRUD::set('reorder.max_level', 2);
    }

    (...)
}
```

Model:
```
class Question extends Model
{
    use HasFactory, CrudTrait;

    protected $fillable = [
        'campaign_id',
        'parent_id',
        'type',
        'code',
        'text',
        'panel',
        'conditions',
        'extras',
        'option_group_id',
    ];

    protected $fakeColumns = ['extras'];

    protected $casts = ['conditions' => 'array', 'extras' => 'array'];

    protected $touches = ['campaign'];

    public static function booted()
    {
        // This is used to put newly added questions to the end, which can then be adjusted using reorder functionality, if needed
        static::creating(function ($question) {
            $maxRgt = Question::where('campaign_id', $question->campaign_id)->max('rgt');

            if ( ! isset($question->attributes['lft'])) {
                $question->attributes['lft'] = $maxRgt + 1;
            }

            if ( ! isset($question->attributes['rgt'])) {
                $question->attributes['rgt'] = $maxRgt + 2;
            }

        });
    }

    /*
     * Relationships
     */

    (...)

    public function campaign()
    {
        return $this->belongsTo(Campaign::class);
    }

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

    public function hasChildren(): bool
    {
        return count($this->children) > 0;
    }

    public function hasParent(): bool
    {
        return count($this->parent) > 0;
    }

    public function withChildren()
    {
        return $this->children()->union($this);
    }

    /*
     * Scopes
     */

    public function scopeWithoutChildren($query)
    {
        return $query->where('parent_id', null);
    }
}
```

### What I expected to happen

I expected normally functioning reorder functionality, i.e. on clicking save after reordering that database is updated accordingly.

### What happened

While reorder works fine on smaller datasets, it seems that has some problems on larger. I tested with dataset of ~300 rows and with ~500 rows, both are not working, while small datasets, up to about 150 rows works OK. When it is not working correctly, upon clicking Save button in reorder view, an apparently random row pops at the top of dataset (I check in phpmyadmin, backpack has set parent_id, lft, rgt and depth values to 0 for the row in question),  while other rows are updated (reordered) normally (as illustrated by the following image).

![Screenshot from 2021-02-16 22-36-31](https://user-images.githubusercontent.com/2708773/108246870-3d9eb400-7152-11eb-93a8-eddd689fecd5.png)

### What I've already tried to fix it

I tried to see the Backpack CRUD code in charge for reorder functionality, however everything seems to be fine there. Am I missing something here, is there some constraint that doesn't allow large datasets to be reordered?

Any help is appreciated.

### PHP VERSION:
PHP 7.4.9 (cli) (built: Oct 26 2020 15:17:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.28.0@c0e07808606b591e9591d52f22552ebf257f399c

### BACKPACK VERSION:
4.1.34@d9ec59ab1f9fe03c7106911b5667d912c1cfe1f7

**Comment by pxpm** [comment]
Hello @skruzic 

I'v just tried myself with 468 items and it worked as expected (it takes a little bit more time but, so there might be space to some improvement)

I am just wondering if your `withChildren` is not having some kind of interference here because `withChildren` is how you'd load the `children` relationship and you are adding unions there. 

Or could be you `max_input_vars` php setting that not let the whole items be passed in the request? 

I don't think there is a problem here from Backpack side, if there is, is not related with the fact that 500 items are beeing reordered. 

I will be closing this for now. If you think I am wrong, and sometimes I am, please re-open and we will re-evaluate.

Wish you the best,
Pedro

**Comment by skruzic** [comment]
It turned out that increasing `max_input_vars` solved the problem. Thank you.

However, it may be a good idea to mention this in the documentation.

**Comment by pxpm** [comment]
Hello @skruzic 

Thanks for coming here and sharing the solution. I am sure it will help anyone that has the same problem. 

I will have a look at docs and maybe add a note there just for reference, although I don't think this is related to backpack, if you create a form with thousands of fields (not talking about backpack forms) you will hit the same barrier that's PHP/server concern, but if it can help our users and avoid countless hours debugging I am all-in for it. 

Thanks,
Pedro
