### ISSUE TITLE
[Question] How to disable model global scopes in a crud panel

### ISSUE THREAD

**Issue by abejenaru** [Laravel-Backpack/CRUD#3535]
# Bug report

### What I did

Use CRUD panel on Eloquent model with global scope applied

### What I expected to happen

See all records

### What happened

I only get the records filtered by the global scope

### What I've already tried to fix it

Nothing yet

### PHP VERSION:
PHP 7.4.15 (cli) (built: Feb 14 2021 14:19:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.28.1@73dd43d92fcde6c6abc00658ae33391397ca119d

### BACKPACK VERSION:
4.1.34@d9ec59ab1f9fe03c7106911b5667d912c1cfe1f7

**Comment by pxpm** [comment]
Hello @abejenaru 

I don't think that this is a bug, from what I see if Model has GLOBAL scopes, Backpack should respect them. Who set the global scope in model, wasn't developer? 👓 

What I think is that this is more of a question of `How can I disable model global scopes in a crud panel`. 

That said, in your setup: `$this->crud->query = $this->crud->model->newQueryWithoutScopes();`

Let me know if I missed the point here, and re-open if needed.

Best,
Pedro

**Comment by abejenaru** [comment]
> Hello @abejenaru
> 
> I don't think that this is a bug, from what I see if Model has GLOBAL scopes, Backpack should respect them. Who set the global scope in model, wasn't developer? 
> 
> What I think is that this is more of a question of `How can I disable model global scopes in a crud panel`.
> 
> That said, in your setup: `$this->crud->query = $this->crud->model->newQueryWithoutScopes();`
> 
> Let me know if I missed the point here, and re-open if needed.
> 
> Best,
> Pedro

Thanks Pedro, that indeed does the trick.
However !!! I didn't find it documented anywhere (CRUD API, CRUD list operation -> custom query, StackOverflow), that is why I opened the ticket (it might indeed have been a missing feature rather that a bug ;)

Cheers,
Andrei

**Comment by abejenaru** [comment]
Woops, I'm stuck again!

While your method works perfectly for the lists, it doesn't seem to be possible to manipulate (edit/delete/etc.) a record filtered out by the global scope; any suggestions ? Is there a way to overwrite getEntry() method ?

Thanks!
