### ISSUE TITLE
[Bug] Entries per page are not remembered (persistent table - true)

### ISSUE THREAD

**Issue by spajz** [Laravel-Backpack/CRUD#3545]
# Bug report

### What I did

Config persistentTable=true
I chose a different number of items per page than default on datatable. I edited some item and then chose save and back. 

### What I expected to happen

To return to items listing on the same page with same number of items per page.

### What happened

But I was returned to the first page with the default number of items per page.

### What I've already tried to fix it

```
let $dtCachedInfo = JSON.parse(localStorage.getItem('DataTables_crudTable_/{{$crud->getRoute()}}')) ?? [];
var $dtDefaultPageLength = {{ $crud->getDefaultPageLength() }};

if($dtCachedInfo.length !== 0 && $dtCachedInfo.length !== $dtDefaultPageLength) {
   //localStorage.removeItem('DataTables_crudTable_/{{$crud->getRoute()}}');
}
```
I commented the line above in datatables_logic.blade.php, and seems to be working well on this issue.
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.11 (cli) (built: Sep 29 2020 13:18:06) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.28.1@73dd43d92fcde6c6abc00658ae33391397ca119d

### BACKPACK VERSION:
4.1.34@d9ec59ab1f9fe03c7106911b5667d912c1cfe1f7

**Comment by pxpm** [comment]
Hello @spajz 

Thanks for the bug report and sorry for the trouble.

We introduce a few changes (lots of them) in paginator recently, this workaround was there to prevent datatables to sort data by unexistent pagination option. 

For example, you setup your paginator in controller. You go to crud, test it out, you go to controller and change all the numbers. Go back to the page and you will be paginating by an unexistent option. 

What I did in the PR, is adding the `user selected` pagination into a variable in localStorage. That way, if it was the user who changed pagination, we are not going to clear it anymore.

Once again, thank you. I am going to close this issue so we keep any relevant discussion in the PR thread. #3566 

Wish you the best,
Pedro
