### ISSUE TITLE
[Bug] Edit function on uniqe field

### ISSUE THREAD

**Issue by magsudhajiyev** [Laravel-Backpack/CRUD#3548]
# Bug report

I am using PHP 7.4 with Laravel 6.20.15 and I defined uniqe field in mysql table. When I try to edit the record with Backpack CRUD it gives an error even though I didn't touch the uniqe field.

### What I did

I tried to search te problem but on internet but couldn't find any solutions.

### What I expected to happen

The edit function work properly when there is no uniqe field rule validation.

### What happened

I get an error 

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version
DB version:  10.4.17-MariaDB
PHP: PHP 7.4
Laravel: 6.20.15
--

When I run ```php artisan backpack:version``` the output is: 4.1.31

**Comment by pxpm** [comment]
Hello @magsudhajiyev 

My guess is that your are not using the `unique` validation correctly but you didn't provide any code samples, and no error so I can't be of more help here.

Check Permission Manager, how we handle it:

https://github.com/Laravel-Backpack/PermissionManager/blob/f71b29a7785da119ed2c15838977470929a1ff5c/src/app/Http/Requests/UserUpdateCrudRequest.php#L30

I don't think there is a bug here, if I am wrong, and sometimes I am, please re-open.

Best,
Pedro

**Comment by magsudhajiyev** [comment]
OK then let me clearify it.

Here is my Model:

`
namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations;

class PromoCode extends Model
{
    use CrudTrait;
    use HasTranslations;

    protected $table = 'promo_codes';

    protected $fillable = [
        'company_id',      
        'user_id',      
        'customer_id',
        'staff',      
        'code',      
        'type',      
        'value',      
        'usage_limit',
        'used',
        'interval_number',
        'interval_limit',
        'interval_amount',      
        'price_limit',
        'start_date',
        'expire_date',      
        'services',
        'disabled'     
    ];
}
`

Here is CRUD method: 

`
    protected function setupCreateOperation()
    {
        CRUD::setValidation(PromoCodeRequest::class);

        $this->crud->addField([
            'label'       => 'Promo Kod',
            'name'        => 'code',
            'type'        => 'text',
        ]);
    

        $this->crud->addField([
            'label'       => 'Müştəri / Şirkət',  
            'name'        => 'disabled',
            'type'        => 'radio',
            'options'     => [
                0 => 'Müştəri',
                1 => 'Şirkət'
            ]
        ]);
`
And here is the rule method:
`
    public function rules()
    {
        return [
            'code'          => 'required|unique:promo_codes',
            'value'         => 'required',
            'type'          => 'required',
        ];
    }
`

**Comment by pxpm** [comment]
Hello @magsudhajiyev like I told you, you have an error in your `unique` definition. Please check Laravel docs on `unique` https://laravel.com/docs/8.x/validation#rule-unique or the sample code I provided you. You should use the `except, idColumn` described in docs to ignore if the ID is already set. 

I also found this: https://stackoverflow.com/questions/23587833/laravel-validation-unique-on-update it might give you a better example of what I am trying to say.

Best,
Pedro
