### ISSUE TITLE
[Bug] Export all lines

### ISSUE THREAD

**Issue by pcipov** [Laravel-Backpack/CRUD#3549]
# Bug report

### What I did

When I use export button to export all lines, have to select all lines first for Datatables to read all lines. When I have 1000+ lines it is too slow.

### What I expected to happen

I want to generate export file in php.

### What happened

??

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.7 (cli) (built: Jul  3 2019 14:34:10) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.28.1@73dd43d92fcde6c6abc00658ae33391397ca119d

### BACKPACK VERSION:
4.1.34@d9ec59ab1f9fe03c7106911b5667d912c1cfe1f7

**Comment by pcipov** [comment]
I have a solution.

I made new button:
```
<div class="text-center mt-2 mb-0"><a href="javascript:void(0)" onclick="exportToExcel(this)" data-route="" class="btn btn-xs btn-primary">Export</a></div>

@push('after_scripts')
<script>
    function exportToExcel()
    {
        var orders = [];
        crud.table.order().forEach(function(order, index) {
            orders[index] = {'column': order[0], 'dir': order[1]};
        });
        var filters = window.location.search;
        var search = crud.table.search();
        var url = '{{url($crud->route."/search")}}';

        $.ajax(
            url + filters,
            {
                type: 'POST',
                data: {
                    '_token': '{{ csrf_token() }}',
                    export: 'excel',
                    columns: {!! $crud->exportColumns !!},
                    order: orders,
                    search: {'value': search, 'regex': 'false'},
                },
                success: function(result) {
                    window.location.href = result;
                },
                error: function(result) {
                    console.log('ERROR');
                    console.log(result);
                }
            }
        );
    }
</script>
@endpush

```

I added this to controller/listOperation:
```
        $this->crud->exportColumns = json_encode([
            ['name' => 'name_of_db_column', 'title' => 'Title in Excel table', 'width' => desired_with_of_column_in_excel,],
        ]);
        $this->crud->addButtonFromView('bottom', 'export', 'export', 'end');
```
It is possible to add column of relationship table, e.g.:
`posts.title`

I added this to Operations/ListOperation:
```
    protected function exportToExcel($entries)
    {
        $columns = request()->input('columns');
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        foreach($columns as $key=>$column) {
            $sheet->getColumnDimensionByColumn($key+1)->setWidth($column['width']);
            $sheet->setCellValueByColumnAndRow($key+1, 1, $column['title']);
        }
        foreach($entries as $kEntry=>$entry) {
            $entry = $entry->toArray();
            foreach($columns as $kColumn=>$column) {
                $tmp = explode('.', $column['name']);
                $value = (count($tmp) == 1) ? $entry[$tmp[0]] : ( isset($entry[$tmp[0]][$tmp[1]]) ? $entry[$tmp[0]][$tmp[1]] : '' );
                $sheet->setCellValueByColumnAndRow($kColumn+1, $kEntry+2, $value);
            }
        }
        $this->pathPrefix = Storage::disk('public')->getDriver()->getAdapter()->getPathPrefix();
        if(!File::isDirectory($this->pathPrefix . '/export')) {
            File::makeDirectory($this->pathPrefix . '/export', 0777, true, true);
        }
        $fileName = '/export/export-' . date('YmdHis') . '.xlsx';
        $writer = new Xlsx($spreadsheet);
        $writer->save($this->pathPrefix . $fileName);
        return '/storage' . $fileName;
    }
```

And I changed line:
`        return $this->crud->getEntriesAsJsonForDatatables($entries, $totalRows, $filteredRows, $startIndex);`
to lines:
```
        if(request()->input('export') == 'excel') {
            return $this->exportToExcel($entries);
        }
        else {
            return $this->crud->getEntriesAsJsonForDatatables($entries, $totalRows, $filteredRows, $startIndex);
        }
``` 

Please, test it.

**Comment by pxpm** [comment]
@pcipov thanks for the report. 

We are aware that if you load THOUSANDS of entries with lot's of columns (and depending on how you setup your columns, the types, the eager loads of relations, etc etc) it can take some time to load everything.

I was able to make 2000+ entries export with proper column definition (only 5 columns), and it took like 3~5 secs. 

When I needed like 500 entries but with 20+ columns, and some of the columns need to do some calculations/fetch from db or any other more heavy task it could take up to 10+ seconds, in this scenarios I create a crud button in the list view, with a custom `Export`. 

When I click that button I hit a controller route with my export functionality. In that controller I get the URL parameters (the applied filters) to export the current filtered data without the need to show all entries on the same page. Take in mind that when you click the button you are creating a new request, so to get the applied filters you need to get the request refeerer. 

We expect to apply this technique when we move away from datatables to make the exports more functional.

For now that's the best advice I can give you. 

Going to close this as I think this is not a bug but rather a limitation of the time spend to fetch all the information that's beeing requested.

If you think I am wrong, please re-open. 

Best,
Pedro

**Comment by pcipov** [comment]
I wanted you to use my solution in your platform and give better features to your customers. I think it is nothing unusual to have 2000+ rows in database table.

**Comment by pxpm** [comment]
100% agree with you @pcipov it's not unusual, and a very desired feature. I find myself writting custom export to meet my needs too. 

Like I told you, I really, really plan to refactor this and allow users to export with best performance possible.

But it's not so simple like picking up your code and dumping into the application. There are alot of things to thinker, that for you are straightfoward, but when dealing with lots of users it gets more complicated. 

From your code I can't see, but I expect that you added another dependency, probably https://github.com/PHPOffice/phpspreadsheet/ ? Their licensing allow us to use it inside Backpack? I would rather use: https://github.com/Maatwebsite/Laravel-Excel for example. 

You are saving the exported file in disk, what If I want to download it directly ? What if I am in a legacy system and want `*.xls` and not `*.xlsx` ? json export? csv ? 

I think you did a great job here, one way that you can "re-use" your code in other cruds, and/or share with people that might want it too, is to create an Operation for the export. You can re-use that operation inside any of your cruds and use operation settings to manage the `per crud settings` and the `general settings`. If you make it a package and publish it anyone that "agree" with how you implemented it can use it. 

I can assure you 100% that this export limitation, bugs me like hell, I'v been in that rabbit hole for sooooo many time, I know it will be huge job to refactor, so I need to fix some more know crud bugs so I, and the rest of the team, can move into working on new features/refactors. 

I cannot just tell you "it's going to be in March" or any other date but it will for sure. 

Best,
Pedro

**Comment by pcipov** [comment]
Thank you for your answer.
Datatables is evil. I have experience with it in GroceryCrud (Codeigniter) too. I spent lot of time to refactor it.

I made exportOperation, but it did not work. When I have $entries array in listOperation, I have relationship columns too in it. But when I copy the code from listOperation to exportOperation, I have no relationship columns. I don't know why.

**Comment by pxpm** [comment]
@pcipov probably is because the fields are added to the `list` operation, and your operation is named something else. 

Maybe inside you `setupExportOperationDefaults` you can call `setupListOperation` to get the fields inside your `export` operation.

It's kind of the same we do to get the fields inside `InlineCreateOperation` https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/Operations/InlineCreateOperation.php

Best,
Pedro

**Comment by dimer47** [comment]
I know this issue is old, but since it keeps coming up and there's still no built-in solution — I built a package that does exactly what was requested here: generating the export file server-side in PHP, with no dependency on DataTables loading all rows in the browser.

<img width="919" height="282" alt="Image" src="https://github.com/user-attachments/assets/35f2baa5-6a5a-4cce-9286-e209f548b4a3" />

**[dimer47/backpack-server-export](https://github.com/dimer47/backpack-server-export)**

It respects the active Backpack filters, search, sort, and column visibility. For large datasets (the 1000+ rows scenario described here), it automatically offloads the export to a queue job so the request doesn't time out.

All standard Backpack column types are resolved automatically — relationships, selects, closures, model functions, booleans, formatted numbers/dates, etc.

Just `use ServerExportOperation;` in your controller and you get a "Full Export" dropdown in the toolbar.

Happy to hear feedback if anyone gives it a try.
