### ISSUE TITLE
Help to change 'DELETE' to 'POST'. How?

### ISSUE THREAD

**Issue by PolywickStudio** [Laravel-Backpack/CRUD#355]
I need help.

Is there a way to change or fix backback to not issue 'DELETE' and to use 'POST' instead? 

I can change 
   url: delete_url,
   type: 'DELETE', 

What else do I need to fix, so that 'DELETE' changes to 'POST' works?

It's a duplicate of:
https://github.com/Laravel-Backpack/BackupManager/issues/16
https://github.com/Laravel-Backpack/CRUD/issues/178

**Comment by tabacitu** [comment]
Hi @PolywickStudio ,

I think that's all you need to do. The route is created for a [resource controller](https://laravel.com/docs/5.3/controllers#resource-controllers), and as far as I know, the destroy() method also listens to POST (even though the docs don't say this). If it doesn't, you need to create new POST routes in your routes file:
```php
Route::post('product/{id}/delete', [
            'as' => 'crud.product.destroy',
            'uses' => 'ProductCrudController@destroy',
          ]);
```

AND use this new route in the javascript (```product/id/delete```).

Hope it helps. Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
