### ISSUE TITLE
Vimeo ceased working 

### ISSUE THREAD

**Issue by webdesign7** [Laravel-Backpack/CRUD#3552]
There seem to be an issue with  video  field type and specifically Vimeo. It was woking in the past but now one of my clients noticed that is no longer working and I wonder whether there has been any silent updates on Vimeo API ..  @tabacitu  could you please check and ensure this is still working or whether there  needs an update to be done ? Many thanks
Sergiu

**Comment by promatik** [comment]
Hi Segiu!
I can confirm it is not working, I'm on it 🙌
I'll submit a PR shortly.

**Comment by promatik** [comment]
@webdesign7 I've submitted the PR with the fix, if you have the time and maybe the need, you can copy the fix to your local project and let us know if it solves the problem for you.

Thank you for submitting the issue, let's move the conversation to #3553 👍

**Comment by webdesign7** [comment]
Thanks @promatik , I can confirm that it is working now :) many thanks
