### ISSUE TITLE
[Bug] Radio field on a boolean attribute interprets old value incorrectly

### ISSUE THREAD

**Issue by nbolender** [Laravel-Backpack/CRUD#3554]
# Bug report

### What I did

Field:
```php
[
	'name' => 'published',
	'label' => 'Published Status',
	'type' => 'radio',
	'options' => [
		true => 'Published',
		false => 'Draft',
	],
]
```

Attribute Cast:
```php
protected $casts = [
	'published' => 'boolean',
];
```

Fill out the CRUD form such that a validation error occurs and that 'published' is true. The radio field view casts `true` to `'1'`. So the old value will be `'1'` instead of `true`.

### What I expected to happen

`true` option is selected when form with validation errors appears.

### What happened

`false` option is selected.

This is because in the radio field, the old value is strictly checked against `true`, but the old value from the form is `1`, as automatically cast to a string by PHP:

```php
    // check if attribute is casted, if it is, we get back un-casted values
    if(Arr::get($crud->model->getCasts(), $field['name']) === 'boolean') {
        $optionValue = $optionValue === true ? 1 : 0;
    }
...
                <input  type="radio"
                        class="form-check-input"
                        value="{{$value}}"
                        @include('crud::fields.inc.attributes')
                        >
```

### What I've already tried to fix it

I've overridden the field locally with this change:

```php
$optionValue = (int) $optionValue;
```

While this seems to work for me, it seems like I have been battling this field with each of my 4.1 upgraded sites. So I don't know if it could impact someone who sets up their radio fields in a different way.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.26 (cli) (built: Jan  8 2021 13:03:03) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.26, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v6.20.12@49f9db00a754517f07d365ee5b0806df82e37029

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c

**Comment by promatik** [comment]
Hi @nbolender!
Thank you for rising the issue, and for providing your solution 🙌

I think that is actually the easiest way to solve this issue, so I created a PR with it (https://github.com/Laravel-Backpack/CRUD/pull/3573), it's on our review list, let's hope for a quick merge so you don't ever need to override the file for such a small fix 😅

I'll close this issue for now, so let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/3573.
