### ISSUE TITLE
[Bug] 4.1.35 breaks related text fields

### ISSUE THREAD

**Issue by alitak** [Laravel-Backpack/CRUD#3556]
# Bug report

### What I did

https://github.com/Laravel-Backpack/CRUD/compare/4.1.34...4.1.35
It works with 4.1.34, but it does not with 4.1.35
We have 2 models:
Workers, Departments
Workers have department_id, with belongsTo relation.
In the workers crud I defined a text type:
            [
                'name' => 'department.name',
                'label' => __('admin::workers.department'),
                'type' => 'text',
            ],
With 4.1.34 it works with no problem (Munkacsoport = Departmant, Név = Name) : 
![image](https://user-images.githubusercontent.com/6049721/108996540-ccee1f00-769e-11eb-91c0-b7dca41a6940.png)

With 4.1.35 it breaks:
{
    "message": "Call to undefined relationship [name] on model [App\\Models\\Department].",
    "exception": "Illuminate\\Database\\Eloquent\\RelationNotFoundException",
    "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/RelationNotFoundException.php",
    "line": 34,
    "trace": [
        {
If I change the name to department (with no .name on the end), the crud works and I can see the department object within the column:
![image](https://user-images.githubusercontent.com/6049721/108996757-13437e00-769f-11eb-9252-2c54101d958b.png)
As you can see, the name attribute is there, but it cannot read it, because it started to search for a relation.

Did something changed with 4.1.35 which can case this break? This is not the only system, which broke with this update (actually there are 4 systems locked to 4.1.34 at the moment, 2 of them are with the injection problem).

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.0.0 (cli) (built: Nov 29 2020 22:19:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.29.0@d2eba352b3b3a3c515b18c5726b373fe5026733e

### BACKPACK VERSION:
4.1.34@d9ec59ab1f9fe03c7106911b5667d912c1cfe1f7
OR
4.1.35@84ffcc6afa0d86a0339a736905a450480ab91ada

**Comment by robdex** [comment]
I found the same error updating to last version (4.1.36).
I don't know if is only a typo, but this resolves for me:

```
diff --git a/src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php b/src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
index 852b45e3..fbd73246 100644
--- a/src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
+++ b/src/app/Library/CrudPanel/Traits/ColumnsProtectedMethods.php
@@ -146,7 +146,7 @@ trait ColumnsProtectedMethods
             // if the first part of the string exists as method,
             // it is a relationship
             if (method_exists($this->model, $possibleMethodName)) {
-                $column['entity'] = $column['name'];
+                $column['entity'] = $possibleMethodName;
 
                 return $column;
             }
```

**Comment by pxpm** [comment]
Hello @robdex and @alitak  for the contribution

It's not a typo, it's intended. The problem relied ahead when we eager load the relations. 

If you try with `user.address.name` the `entity` would become `user` when the correct eager load in this scenario is `with('user.address')` so it eager load both relations. Atm it is trying to load `name` as a relation.

I'v submited PR #3558 that should address this problem. 

Your column would work with: `$this->crud->addColumn('department')` (`name` is an attribute that Backpack can automatically guess, if different you can specify in model the identifiable attribute https://backpackforlaravel.com/docs/4.1/crud-fields#identifiable-attribute). 

But as this is a minor version it should be non-breaking change. That PR aims to bring back that compatibility to backpack so you can update without having to change the code. 

I am going to close this issue so we keep any discussion on this regard in the PR thread. 

If you have time and are willing to, give a try to that PR and let us know your results, it could speed up the merging process.

Best,
Pedro

**Comment by alitak** [comment]
Hi @pxpm yes, i missed that, dunno why. Sry for that. Everything works, thank you for your work!
