### ISSUE TITLE
[Bug] Incompatible SluggableObserver class with new \Cviebrock\EloquentSluggable\SluggableObserver

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#3557]
# Bug report

### What I did

Upgrade EloquentSluggable to ^8.0

### What I expected to happen

Nothing

### What happened

Declaration of Backpack\CRUD\app\Models\Traits\SpatieTranslatable\SluggableObserver::generateSlug(Illuminate\Database\Eloquent\Model $model, string $event) must be compatible with Cviebrock\EloquentSluggable\SluggableObserver::generateSlug(Illuminate\Database\Eloquent\Model $model, string $event): void

### What I've already tried to fix it

Yes, i have fixed code.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.27 (cli) (built: Feb  2 2021 20:46:26) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.29.0@d2eba352b3b3a3c515b18c5726b373fe5026733e

### BACKPACK VERSION:
4.1.36@779364646e3b57258b981ff9f1bdcd9887143836

**Comment by bedoz** [comment]
My Fixed Code is:

`<?php

namespace Backpack\CRUD\app\Models\Traits\SpatieTranslatable;

use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Database\Eloquent\Model;

class SluggableObserver extends \Cviebrock\EloquentSluggable\SluggableObserver
{
    /**
     * @var \Cviebrock\EloquentSluggable\Services\SlugService
     */
    private $slugService;

    /**
     * @var \Illuminate\Contracts\Events\Dispatcher
     */
    private $events;

    /**
     * SluggableObserver constructor.
     *
     * @param \Cviebrock\EloquentSluggable\Services\SlugService $slugService
     * @param \Illuminate\Contracts\Events\Dispatcher           $events
     */
    public function __construct(SlugService $slugService, Dispatcher $events)
    {
        $this->slugService = $slugService;
        $this->events = $events;
    }

    /**
     * @param \Illuminate\Database\Eloquent\Model $model
     *
     * @return bool|null
     */
    public function saving(Model $model)
    {
        return $this->generateSlug($model, 'saving');
    }

    /**
     * @param \Illuminate\Database\Eloquent\Model $model
     * @param string                              $event
     *
     * @return bool|null
     */
    protected function generateSlug(Model $model, string $event): void
    {
        // If the "slugging" event returns a value, abort
        if ($this->fireSluggingEvent($model, $event) !== null) {
            return;
        }
        $wasSlugged = $this->slugService->slug($model);

        $this->fireSluggedEvent($model, $wasSlugged);
    }

    /**
     * Fire the namespaced validating event.
     *
     * @param \Illuminate\Database\Eloquent\Model $model
     * @param string                              $event
     *
     * @return mixed
     */
    protected function fireSluggingEvent(Model $model, string $event): ?array
    {
        return $this->events->until('eloquent.slugging: '.get_class($model), [$model, $event]);
    }

    /**
     * Fire the namespaced post-validation event.
     *
     * @param \Illuminate\Database\Eloquent\Model $model
     * @param string                              $status
     *
     * @return void
     */
    protected function fireSluggedEvent(Model $model, string $status): void
    {
        $this->events->dispatch('eloquent.slugged: '.get_class($model), [$model, $status]);
    }
}
`

**Comment by t-prod** [comment]
Hi,

Thanks I have the same problem. This is the diff by waiting for a fix in this package 😄 

![image](https://user-images.githubusercontent.com/1824638/109268235-1491b980-780b-11eb-8d19-fee7931cdeee.png)

**Comment by bedoz** [comment]
Yeah @t-prod i've made the same fixes in my code above. Waiting for a quick fix...

**Comment by promatik** [comment]
Hi @bedoz, hi @t-prod!
Thank you for rising the issue and provide the fix for it, I've just pushed a PR with the fix (https://github.com/Laravel-Backpack/CRUD/pull/3572), it's waiting for review and will soon be merged 🙌

I'll close this issue, let's move the conversation there.
