### ISSUE TITLE
[Bug] Missing translation in date_range filter - Premade date range strings in french

### ISSUE THREAD

**Issue by mamarmite** [Laravel-Backpack/CRUD#3559]
# Bug report

### What I did
Install a date_range filter into a CRUD view.

### What I expected to happen
Show UI in the current language

### What happened
UI range shortcuts was in english (default)

### What I've already tried to fix it
Translated the CRUD lang file : `fr`, `fr-CA`, `fr_CA` in ressource/lang/*/crud.php
PR is ready to be added.

#### PHP VERSION:
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:27) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

#### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

#### BACKPACK VERSION:
4.1.31@e0c389acce2617099a69d0b6076dfad24385295f

My local env, isn't updated to the lastest CRUD, but I verified that the strings wasn't added in current repo.

**Comment by mamarmite** [comment]
OK PR added : #3560

**Comment by promatik** [comment]
Hi @mamarmite your PR is ready to merge 🙌 it will be merged soon so I'll close the issue for now.
Thank you for the translations 👌
