### ISSUE TITLE
[Bug] Select2_from_ajax with dependencies resets on load

### ISSUE THREAD

**Issue by o15a3d4l11s2** [Laravel-Backpack/CRUD#3561]
# Bug report

### What I did

I have 2 elements that use `select2_from_ajax` (let's say Category and Product) inside `repeatable`. (I know, repeatable again 😊 )
The product field has `'dependencies' => ['category']`.
When I open the CRUD for editing, *sometimes* the product select2 is populated before the category select2 and then the `change` event of the category triggers, which sets the product one to `null`.
To reproduce this sometimes I have to refresh the page 5-6 times.

### What I expected to happen

Both the category and the product fields are populated (the information is existing inside the hidden fields that contain the corresponding data).

### What happened

The dependent fields are sometimes nulled.

### What I've already tried to fix it

Removing the dependencies solves this, but it leads to the issue that the two fields are not so "dependent" anymore.

According to me the only way to solve this is to not trigger the `change` event on the fields while the data is being populated.
So here is what I propose:
Example is from `select2_from_ajax.blade.php`, I have changed a single line (commented with <------ )
```php
            var optionsForSelect = [];
            select2AjaxFetchSelectedEntry(element).then(result => {
                result.forEach(function(item) {
                    $itemText = item[$fieldAttribute];
                    $itemValue = item[$connectedEntityKeyName];
                    //add current key to be selected later.
                    optionsForSelect.push($itemValue);

                    //create the option in the select
                    $(element).append('<option value="'+$itemValue+'">'+$itemText+'</option>');
                });

                // set the option keys as selected.
                $(element).val(optionsForSelect);
                // $(element).trigger('change'); // <----- Commented this row to suppres event trigger
            });
```

@pxpm , @promatik, @tabacitu, is this a reasonable solution according to you? This is a piece of code that is executed exclusively when the field is inside a `repeatable`.
I know it is a single line of code, but if you say, I can make a pull request.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```bash
### PHP VERSION:
PHP 8.0.1 (cli) (built: Jan 13 2021 08:22:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.29.0@d2eba352b3b3a3c515b18c5726b373fe5026733e

### BACKPACK VERSION:
4.1.36@779364646e3b57258b981ff9f1bdcd9887143836
```

**Comment by pxpm** [comment]
Hello @o15a3d4l11s2 

Thanks for the report. Indeed after 10+ tries I finally could reproduce it. Thanks for such a clean bug report that made me try until I got the same error. 

From my tests you proposed solution seems to work. We don't need the `change()` event there as it seems. If you have time and are willing to, can you submit the PR ? If you can't just let me know and I create it. 

Thanks again @o15a3d4l11s2 

Best,
Pedro

**Comment by o15a3d4l11s2** [comment]
@pxpm , pull request created: https://github.com/Laravel-Backpack/CRUD/pull/3591

**Comment by pxpm** [comment]
Thanks again @o15a3d4l11s2 

I will be closing this so we keep any discussion regarding this in the PR thread. 

Best,
Pedro
