### ISSUE TITLE
Installation Issue - Publish User Model

### ISSUE THREAD

**Issue by aerostah** [Laravel-Backpack/CRUD#3562]
Greetings,

As per the title of this issue, the automatic installation process stops on Step 2 of 5.   Creating users table (using Laravel's default migration).  The User table is indeed present, but it won't get past Step #2.

After moving to manual installation, this one particular command produces the following error:

**> php artisan backpack:publish-user-model**
> Command "backpack:publish-user-model" is not defined.

These are my environment details, your wisdom is greatly appreciated.

### PHP VERSION:
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.29.0@d2eba352b3b3a3c515b18c5726b373fe5026733e

### BACKPACK VERSION:
4.1.36@779364646e3b57258b981ff9f1bdcd9887143836

**Comment by promatik** [comment]
Hi @aerostah!
Thank you fr rising this, that's actually our fault, that command is no longer used.
That part of the documentation is outdated.

Sorry for the trouble, I've just pushed a PR to fix it.
For now you can just skip that command.

And if you wish we can help on the automatic installation process. It should work.
Let us know more details about the error.

**Comment by aerostah** [comment]
The problem is that when you go to create the user record in tinker, you get this error:

>>> $user = new App\User();
PHP Error:  Class 'App\User' not found in Psy Shell code on line 1

Both autoinstall and manual are not working. What command should i run to get the user model in place?

**Comment by promatik** [comment]
Hi @aerostah!
Laravel 8 now uses the `User` Model inside the `App\Models` folder.
Backpack supports this new approach since Laravel made the move.

I've never used Tinker, but make sure either you set it, or tinker knows the correct path of the User `App\Models\User`.

**Comment by aerostah** [comment]
Yes, I changed the command to:

$user = new App\Models\User();

This allowed me to run the other commands and create the account,

I appreciate the help.  Thank you.
