### ISSUE TITLE
[Bug] Red asterisk is not added in the label on array validation

### ISSUE THREAD

**Issue by IoanAndrei97** [Laravel-Backpack/CRUD#3568]
# Bug report
The red asterisk is not displayed on array validation rule.

### What I did
If I add a validation rule for array - `'shipment.name' => 'required'` - the validation will work so on submit I will get the following error: **The shipment.name field is required.** but the red asterisk will not be displayed, so the user will not know the field is required until he actually submit the form.
If I add the validation rule like this - `'shipment[name]' => 'required',` - the asterisk will be displayed, but the validation will not work because it will look after a "shipment[name] " field. I can't rename the field because I'm pulling the data from a relationship so it must be `shipment.name`. It's similar to the backpack demo monster - address logic.

### What I expected to happen
I expected the red asterisk to be displayed on `shipment.name => 'required'` rule.

### What happened
The red asterisk is displayed only on this rule `shipment[name]=> 'required'`.

### Temporary fix
I added the red asterisk manually in the label using this html: `Name <span style='color:red'>* </span>`

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
PHP version: 7.4.4
Laravel version: 8.25.0
Backpack version: 4.1.31

**Comment by promatik** [comment]
Hi @IoanAndrei97!
I just tested, and I can confirm the problem.

I've submitted a PR to fix this with what I think it is the best solution 🙌

Thank you for raising the issue, let's hope it to be solved soon 👌
Let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/3570
