### ISSUE TITLE
Maximum execution time exceeded for CRUD with more entries

### ISSUE THREAD

**Issue by AlinGhinoiu** [Laravel-Backpack/CRUD#358]
Hey!

There's a problem when trying to view admin pages for CRUD involving more entries. I have 20.000 entries, for example, but pagination should handle these.

```
FatalErrorException in FileViewFinder.php line 131:
Maximum execution time of 30 seconds exceeded
```

**Comment by AurelDragut** [comment]
Pagination has nothing to do with this issue, the number of records you display in the page is irrelevant. If you want to make it work you need to set it to load the whole list in smaller chunks (but there might appear some issues on AJAX/search) or change php configuration/server.

**Comment by AlinGhinoiu** [comment]
Shouldn't the default settings work with 20.000 records? I'm just trying to help here, I can manage.

**Comment by AurelDragut** [comment]
There is no default setting for this. Any server has an amount of records that it can load in those 30 seconds and that depends on the server's CPU, RAM memory, HDD...

**Comment by OwenMelbz** [comment]
@AurelDragut is correct in the sense that there are no default settings, it's  just whatever your server can handle or is configured to handle.

However 20k should be handled. You'd need to dig into your set up to find out where the bottle neck is.

But you should also use the Ajax for more than 100-200 results I'd say
