### ISSUE TITLE
[Bug] Displaying attribute from nested relationships not working

### ISSUE THREAD

**Issue by IoanAndrei97** [Laravel-Backpack/CRUD#3587]
# Bug report
I have this database structure: customer - belongs to - city, city - belongs to - country.
In the customer crud controller I'm trying to create a text field with this name: `city.country.name` that should render a text input with the value of the city's country name.
The "classic" select should be something like this: `$customer->city->country->name`.

### What I expected to happen
I expected to render a nested relationship attribute.

### What happened
Nothing was rendered.

### What I've already tried to fix it
I tried to use it like this and the attribute was rendered successfully:  `city.country[name]`, but I think this is a bug because if I'm trying to access the city's name using `city.name` it's working...so `city.country.name` should work as well.

### Backpack, Laravel, PHP, DB version
PHP version: 7.4.4
Laravel version: 8.24
Backpack version: 4.1.37

**Comment by patlamontagne** [comment]
I just had the same issue. 

Trying to access the `category.name` attribute gives me a relationship not found error.

I fixed it by reverting back to version 4.1.34.

**Comment by IoanAndrei97** [comment]
> I just had the same issue.
> 
> Trying to access the `category.name` attribute gives me a relationship not found error.
> 
> I fixed it by reverting back to version 4.1.34 since the bug seems to affect 4.1.35 and upwards.

I **think** reverting to that version will come with this issue [#3568](https://github.com/Laravel-Backpack/CRUD/issues/3568) and I really don't want that.

**Comment by pxpm** [comment]
Hello @IoanAndrei97 and @patlamontagne 

Thanks for raising the issue. 

Could you please check https://github.com/Laravel-Backpack/CRUD/pull/3558 if it fixes the problem for you? 

Thanks, and let me know.

Best,
Pedro

**Comment by IoanAndrei97** [comment]
Hello @pxpm 
Having in mind the structure I mentioned above, if I'm using your solution from #3558 I will get a select box with countries when I actually need only the country name from that relatioship in a simple text input. I need to mention that right now I'm in the `UserCrudController`.

```
$this->crud->addField([
'name' => 'city',
'key' => 'city.country-name',
'attribute' => 'country.name'
]);

```

**Comment by pxpm** [comment]
Hello @IoanAndrei97 , sorry, you guys were talking about display attributtes and I was looking at `columns` not fields.

I don't think it makes sense to try what you are trying here, but maybe I am missing something, let me write what I am thinking:

So you are in `UserModel` it has a `belongsTo` `CityModel` relation. That's fine. Then `CityModel` has a `belongsTo` relation with the `CountryModel`, and you are trying to edit the `country name` inside the `User` ? I don't think it should/could work that way.

What I mean is: `User1` goes and writes `US and A`, then `User2` writes `USA`. Both are editing the `same` country name. 

Also, there is no relationship at all when creating, so hypotetically it would only work in `Update` operation, but still ...

I think @patlamontagne is talking about `columns` and the PR I mentioned will fix it. But in your scenario I can't figure out why would you want a `text` edit for `country` name in `user` related with `city` ? It probably would make more sense if `user` have a direct relation with `country`. Maybe a `morphOne` if you need extra attrs.

Let me know,
Pedro

**Comment by IoanAndrei97** [comment]
I have a case where I have to create a new `Model` based on the `UserModel` details, but that details can be modified. Let's say they are the "starting details" for the new `Model`. If we can't find a way to do this I think I will resolve it using some `accessors`.

**Comment by pxpm** [comment]
@IoanAndrei97 I think that is the scenario for a `morphOne` or `morphMany` relations, I think by the way you have your relations setup. If changing database is not possible, maybe overriding the `create/update` methods or using acessors if it fits.

Directly editing non-related entities is discouraged like in the example I provided you, both users would endup changing the same `name` in the country model. 

Let me know,
Pedro

**Comment by IoanAndrei97** [comment]
Ok.
Thank you very much @pxpm . I will close this :)

Keep up the good work!
