### ISSUE TITLE
[Bug] Unable to modify the wrapper classes of upload field

### ISSUE THREAD

**Issue by IoanAndrei97** [Laravel-Backpack/CRUD#3593]
# Bug report

### What I did
I tried to modify the upload field width/col class with this: col-md-6 because I want it to be side-by-side with another field ( not upload ).
I'm using this code: 
```
[ 
  'name'   => 'upload',
  'label'  => 'Upload',
  'type'   => 'upload',
  'upload' => true,
  'disk'   => 'uploads',
  'tab'    => 'Uploads',
  'wrapperAttributes' => [
      'class' => 'form-group col-md-6'
  ]
]
```

Apparently no class is added to the wrapper.
I tested this on my app and on the demo project....Is the same result.

### What I expected to happen
I expected the upload field to be at 50% of the container.

### What happened
The upload field is still at 100% width. The parent( wrapper ) class is this: `col-sm-12` no matter what classes I add in the "class" attribute.

### Backpack, Laravel, PHP, DB version
PHP version: 7.4.4
Laravel version: 8.24
Backpack version: 4.1.37

**Comment by promatik** [comment]
Hi @IoanAndrei97, thank you for reporting this issue 🙌

I was able to replicate it on my side and fix it.
I've just pushed a PR with the fix; https://github.com/Laravel-Backpack/CRUD/pull/3595.

Let's close this issue and move conversation there.
