### ISSUE TITLE
[Bug] CrudControllers with setFromDb() don't work with DBAL v3

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3597]
# Bug report

### What I did

A simple CRUD that uses `setFromDb()`, for example Countries with:
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 2)->index();
            $table->string('name', 75);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('countries');
    }
}
```

### What I expected to happen

The default CountryCrudController to work if you do nothing. So this to work:

```php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CountryRequest as StoreRequest;
// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\CountryRequest as UpdateRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;

class CountryCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;

    public function setup()
    {
        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */
        $this->crud->setModel(\App\Models\Country::class);
        $this->crud->setRoute('admin/country');
        $this->crud->setEntityNameStrings('country', 'countries');

        /*
        |--------------------------------------------------------------------------
        | BASIC CRUD INFORMATION
        |--------------------------------------------------------------------------
        */

        $this->crud->setFromDb();
    }

    protected function setupCreateOperation()
    {
        $this->crud->setValidation(StoreRequest::class);
    }

    protected function setupUpdateOperation()
    {
        $this->crud->setValidation(UpdateRequest::class);
    }
}

```

### What happened

`“Class 'Doctrine\DBAL\Driver\\PDOMySql\Driver' not found”` error was thrown when going on the list page, so the ListOperation is unusable. [Click here for stack trace](http://flareapp.io/share/xPQ6LxD7). 

Screenshot below:
![Screenshot 2021-03-05 at 20 24 46](https://user-images.githubusercontent.com/1032474/110157537-f3276380-7df0-11eb-8364-77ff51f25a7b.png)

### What I've already tried to fix it

Gone through the [change history for `AutoSet.php`](https://github.com/Laravel-Backpack/CRUD/commits/master/src/app/Library/CrudPanel/Traits/AutoSet.php) but it doesn't _look like_ the last few changes are the one that pushed it over the edge...

I used a panel that uses `sstFromDb()` about ~4 days ago, it was working, then I ran a `composer update`, and... now it's not working. The problem is - we're just asking everyone to run a `composer update` for security issues this week. And the version everyone's going to get... will break CRUDs that use `setFromDb()`.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.2 (cli) (built: Feb  4 2021 18:57:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.37@f829c37501d2f015bc5a4c93ef6dbc4533354ba8
```

**Comment by martijnb92** [comment]
Might be the DBAL v3 update.
https://github.com/Laravel-Backpack/CRUD/pull/3517

**Comment by pxpm** [comment]
Indeed @tabacitu , I think it's conflict in your dbal version. 

My guess is that you are in PHP 8 and dbal 2.5. could you have version locked in your composer? 

I didn't try, but tomorrow I will test the update process. 

Best,
Pedro

**Comment by tabacitu** [comment]
@pxpm - I just reverted to PHP 7.4, but... same problem.

@martijnb92 - cha-ching 🎰🥳 Indeed if I go back to DBAL v2 it works again. So it looks like Backpack's still not working with DBAL v3 for now. We thought it was, but it's not - CrudControllers that use `setFromDb()` stop working with the error above. 

What's weird is that... the unit tests are passing just fine. Including `CrudPanelAutoSetTest.php`...

---

If anybody stumbles into this issue and wants a quick fix, do `composer require doctrine/dbal:^2.6`. This is a temporary fix until we figure out the Backpack + DBAL v3 problem. When that's done you can do `composer remove doctrine/dbal` and that's it, you'll go back to using v3 because it's a dependency of Backpack, Laravel and others.

**Comment by pxpm** [comment]
Hello @tabacitu It must be some other thing:

![image](https://user-images.githubusercontent.com/7188159/110203296-5521b080-7e65-11eb-9365-4e0616466c38.png)
(last item, dbal to 3.0)

```php
$ php artisan backpack:version
### PHP VERSION:
PHP 7.4.12 (cli) (built: Oct 27 2020 17:18:47) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.31.0@2aa5c2488d25178ebc097052c7897a0e463ddc35

### BACKPACK VERSION:
4.1.37@f829c37501d2f015bc5a4c93ef6dbc4533354ba8

```

![image](https://user-images.githubusercontent.com/7188159/110203346-8c905d00-7e65-11eb-9abf-85ee56e72e5b.png)

![image](https://user-images.githubusercontent.com/7188159/110203357-a29e1d80-7e65-11eb-9f5d-b34f455cef02.png)

Let me know,
Pedro

**Comment by pxpm** [comment]
I will change my bet to be L7 the problem here.

Can you reproduce the issue in the same environment as I am ? L8 @tabacitu  ?

**Comment by tabacitu** [comment]
I cannot... so indeed, it looks like it's not a Backpack problem, it's a Laravel problem. Basically... 

**THE PROBLEM: Laravel 7 does not work with DBAL v3, despite the fact that it's installable.** 

**THE SOLUTIONS:**

**A) Keep Laravel 7 but downgrade DBAL to version 2, by doing `composer require doctrine/dbal:2.*` as instructed [here](https://github.com/doctrine/dbal/issues/4439)**. This is a one-second solution, but it will add the dbal depenendecy to your project's `composer.json`. Remember to remove that line when you upgrade to Laravel 8 - you don't _actually_ need it. 

(or)

**B) Upgrade to Laravel 8**. That'll fix it, Laravel 8 properly supports DBAL v3.

-----

Unfortunately:
- neither we nor Laravel can retract support, since there are multiple tags supporting it;
- [starting Oct 2020, Laravel 7 is no longer receiving bug fixes](https://laravel.com/docs/8.x/releases#support-policy), so I'm pretty sure this problem will NOT get fixed in Laravel;
- I expect _everybody_ on L7 who runs `composer update` to run into this problem... and we've just asked a bunch of people to run `composer update`; so I expect a lot of people to run into this issue...

I'm not very happy with the solutions, but honestly... I don't see what we can do about it, other than document the solutions (above) and point people here. Open to ideas!
 
I'll close the issue. Please leave a reaction or comment if you've run into this problem... so that we at least know how many people got f*$#ed by this L7 issue.

Cheers!
