### ISSUE TITLE
Help Remove Search and Fix Number of records per page HOW?

### ISSUE THREAD

**Issue by ajamandre** [Laravel-Backpack/CRUD#360]
Hi im new to laravel backpack and crud

right now ive tested the "how to use (full example)" method and i want to customized the user interface. i would like to know if its possible to remove the search and records per page then limit the showing entries to maximum of 5 data only with a specific order?

**Comment by yingdongzhang** [comment]
@ajamandre 

To limit the entries per page you can change the config `default_page_length` in config/backpack/crud to the number you want.

In terms of removing the search function, I think this is a feature of [datatable](https://datatables.net/manual/options) and as far I as I see there is currently no way to easily disable this feature.

However, once you have published the view from backpack/crud to your application, you can do whatever you want to with those views.

**Comment by ajamandre** [comment]
@yingdongzhang 

thank you so much
