### ISSUE TITLE
[Bug] Table view, relation fields value error

### ISSUE THREAD

**Issue by izica** [Laravel-Backpack/CRUD#3604]
# Bug report

```php
protected function setupListOperation()
{
        CRUD::column('manufacturer.name');
}
```

### What I expected to happen

shows relation column value

### What happened

Shows empty table, ajax request getting error

### What I've already tried to fix it

downgrade version
<=4.1.34 works fine

\> 4.1.34 errors

4.1.35, 4.1.36, 4.1.37
`
error_description: "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/RelationNotFoundException.php:34"
error_message: "Call to undefined relationship [name] on model [App\Models\Manufacturer]."
`

4.1.38
`
error_description: "/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50"
error_message: "Call to undefined method App\Models\Manufacturer::name() (View: /var/www/html/vendor/backpack/crud/src/resources/views/crud/columns/select.blade.php)"
`

### Backpack, Laravel, PHP, DB version

laravel/framework 8.32.1

**Comment by izica** [comment]
Update:
`php
CRUD::column('manufacturer.name')->type('text');
`

fixed this

**Comment by pxpm** [comment]
Hello @izica 

Thanks for the report. 

Our aim is to try to avoid defining `type` when you would like the text attribute, like in your scenario `name`. 

I'v pushed a PR #3606 with examples for the relationships. 

Do you want to give it a try and let me know if we achieved our goal, and solved your problem ? 

Best,
Pedro
