### ISSUE TITLE
[Bug] Usage of non existing method Illuminate\Support\Str::of on Laravel 6

### ISSUE THREAD

**Issue by jargoud** [Laravel-Backpack/CRUD#3605]
# Bug report

[This commit](https://github.com/Laravel-Backpack/CRUD/commit/9a901f68c7dcca970f9a851a845de931cff95ee8#diff-733364a7146f6cbef7a364b5e6f327d48a979f365402bc0ffa742ebf0de6a1ef) introduced a breaking change for Laravel 6, since the method `Illuminate\Support\Str::of` doesn't exist yet.

### What I did

I created a validation request with array notation for some rules.

### What I expected to happen

The CRUD auto identifies the required fields.

### What happened

An exception is thrown.

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

````
### PHP VERSION:
PHP 7.4.16 (cli) (built: Mar  4 2021 20:52:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v6.20.18@784f8ff1469a0bb288600d2bb9e02541c8e38a8d

### BACKPACK VERSION:
4.1.38@90cf9d0613848144c1e5f3822892bf2a7afa860f
```

**Comment by pxpm** [comment]
Hello @jargoud 

Thanks for the report and sorry for that, it slipped us :|

I'v just submitted PR #3607 that should allow the same functionality but keep the compatibility with L6. 

Once again, sorry and thanks. I am going to close this so we keep any discussion regarding this in the PR thread. 

Best,
Pedro
