### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by shmuel-livshits** [Laravel-Backpack/CRUD#3621]
In config/backpack/crud/locales ukrainian languare has a key "uk". It's mistake. Ukrainian suppose to be "ua". 
I have to make additional check when I work with any User agent. And when I make a new project I have to fix it every time. Please, fix it

**Comment by promatik** [comment]
Hi @shmuel-livshits!
We use the standard `ISO 639-1` https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.

[The browsers use that standard too](https://www.metamodpro.com/browser-language-codes), Ukrainian code is `uk`, so `uk` should work.

I'll close this for now, if you have any further details please let me know.
