### ISSUE TITLE
[BUG] Ajax relationship field: error in route causing 404 on find when name contains '_'

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/CRUD#3628]
# Bug report

### What I did

I defined an [inline create](https://backpackforlaravel.com/docs/4.1/crud-operation-inline-create)

    [
        'name'    => 'parent_company',
        'type'    => 'relationship',
        'ajax'    => true,
        'attribute' => 'longName', // backpack undocumented ('name' used by default)
        'inline_create' => [
            'entity'       => 'company',
            'force_select' => true,
        ],
    ]

### What I expected to happen

when I type in the select box, the find method in the crudController returns the selection

### What happened

    404 on /company/fetch/parent_company

php artisan route:list shows URI

    /company/fetch/parent-company

### What I've already tried to fix it

    'data_source' =>  str_replace('_', '-', route('company.fetchParentCompany')), // backpack 404 

solves the issue, but it is not robust (since it replaces all underscores in the url)

### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.33.1@354c57b8cb457549114074c500944455a288d6cc

### BACKPACK VERSION:
4.1.40@ecbe7676535d3c9121227329d62cad9978d29fee

**Comment by pxpm** [comment]
@Polfo Thanks for raising the issue and sorry for the trouble.

Unfortunatelly it's something we are aware (was bad implemented from beginning), but at this moment we are unable to provide a fix without a breaking change. This PR is open for merge in 4.2 https://github.com/Laravel-Backpack/CRUD/pull/2905

What you could do is setup the `data_source` like you did, but you could use only: `backpack_url('company/fetch/parent-company')` without replacing nothing in the URL.

I will make sure to add this to the docs in the meanwhile. https://github.com/Laravel-Backpack/docs/pull/244

I am going to close this, if you think there is something more we can do here, please reply or re-open.

Best,
Pedro
