### ISSUE TITLE
[Bug] identifiableAttribute() doesn't show attributes from model

### ISSUE THREAD

**Issue by MeerKatDev** [Laravel-Backpack/CRUD#3630]
# Bug report

I don't understand what's the function if it works identically to the variable. I expect it be a composition utility, like where I could chain more attributes.

### What I did

```php
class User extends Authenticatable
{
    use CrudTrait, HasApiTokens;

    // protected $identifiableAttribute = 'company';
    public function identifiableAttribute(){
        return $this->username;
    }
```

### What I expected to happen

I expect it to be equivalent to 
```php
$identifiableAttribute = 'username';
```

### What happened

it gives empty strings

### What I've already tried to fix it

I keep

```php
$identifiableAttribute = 'username';
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.15 (cli) (built: Feb 27 2021 18:23:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.32.1@7c37b64f8153c16b6406f5c28cf37828ebbe8846

### BACKPACK VERSION:
4.1.38@90cf9d0613848144c1e5f3822892bf2a7afa860f
```

**Comment by pxpm** [comment]
Hello @MeerKatDev I think what you want to do is doable with Laravel Acessors https://laravel.com/docs/8.x/eloquent-mutators#accessors-and-mutators and then use that attribute to identify the _Model_. 

What you are doing there is telling Backpack that the `identifiableAttribute` should be the _username_ itself (like `jonh_doe858`) and backpack would try `$model->jonh_doe858` .

the `identifiableAttribute` function should return the `attribute` in the _Model_ that Backpack should get, and not the value of the attribute.

I do not think there is any bug here, just a misunderstanding, so I am going to close this. 

If you think I am wrong, and sometimes I am, please reply or re-open.

Best,
Pedro
