### ISSUE TITLE
[Bug] Select2_multiple with no pivot

### ISSUE THREAD

**Issue by MeerKatDev** [Laravel-Backpack/CRUD#3631]
# Bug report

I'm trying to define a multiple select on a form. I'm using Laravel 8.x, Backpack 4.1, on a mongo database.
I can visualize the multiple choice just fine, but I cannot seem to be able to save it on the db. I'm trying to save the field as a json array. This situation is totally undocumented and it's hard to understand what I should do. mutate to array or string don't work either way. With no mutators, it just doesn't save anything and gives no error.

### What I did

```php
   // warranty model
    public function product()
    {
        return $this->belongsTo(Product::class);
    }
```

```php
   // product model
    public function warranties()
    {
        return $this->hasMany(Warranty::class);
    }

    protected $casts = [
      ...
      'warranties' => 'array'
    ];
```

```php
        CRUD::addField([
            'label'     => "Warranty",
            'type'      => 'select2_multiple',
            'name'      => 'warranties', // the method that defines the relationship in your Model

            // optional
            'entity'    => 'warranties', // the method that defines the relationship in your Model
            'model'     => Warranty::class, // foreign key model
            'attribute' => 'code', // foreign key attribute that is shown to user
            'pivot'     => false
        ]);
```

### What I expected to happen

It should save the array a string in mongodb (as it does for `select_from_array` or `select`s)

### What happened

I get:
> json_decode() expects parameter 1 to be string, array given

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 7.4.15 (cli) (built: Feb 27 2021 18:23:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.32.1@7c37b64f8153c16b6406f5c28cf37828ebbe8846

### BACKPACK VERSION:
4.1.38@90cf9d0613848144c1e5f3822892bf2a7afa860f
```

**Comment by pxpm** [comment]
Hello @MeerKatDev did you tried with `pivot => true` ?

**Comment by MeerKatDev** [comment]
@pxpm I didn't, but in fact I don't want to use a pivot table, I don't need it. I need an array there.

**Comment by pxpm** [comment]
@MeerKatDev `pivot` is just an way of how under the hood the relation is handled. Can you setup 'pivot => true' ? I have other `hasMany` working with `pivot => true`, so I think it might be some documentation issue. (the part that `hasMany` technically does not have a `pivot` table is beeing addressed in other PR)

**Comment by MeerKatDev** [comment]
I get this when adding `pivot => true`: 

> Call to undefined method Jenssegers\Mongodb\Relations\HasMany::sync()

**Comment by MeerKatDev** [comment]
After all I created a new component.
