### ISSUE TITLE
[Bug]  Small problem with responsiveness of select2 when using for tags

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#3632]
# Bug report

### What I did

I simply used 

        $this->crud->addField([
            'type' => 'relationship',
            'name' => 'assignmentTypes',
            'label' => 'Incarichi',
            'placeholder' => 'Scegli uno o più incarichi'
        ]);

to generate a select2 for tags

### What I expected to happen

It works, it looks well also resizing screen

### What happened

At smaller screen, tags are not looking weel

![image](https://user-images.githubusercontent.com/1268699/112695708-d8428f00-8e84-11eb-9c4a-e8b2c97c5fbe.png)

### What I've already tried to fix it

Nothing, It is not a big problem

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.3 (cli) (built: Mar  2 2021 23:33:56) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.34.0@81892ca110795a9c46c7e198cba7763bfd2af0bf

### BACKPACK VERSION:
4.1.40@ecbe7676535d3c9121227329d62cad9978d29fee

**Comment by promatik** [comment]
Hi @realtebo, thank you for reporting the issue.
I've created a PR (https://github.com/Laravel-Backpack/CRUD/pull/3679) to fix this issue, let's close this one and move conversation there 🙌
