### ISSUE TITLE
[Bug] identifiableAttribute method expected even when options are explicitly defined

### ISSUE THREAD

**Issue by nbolender** [Laravel-Backpack/CRUD#3635]
# Bug report

### What I did

Added a `select2_from_array` field for a `BelongsTo` relationship where I wanted to control which options are available.

```php
// Models\Notification:
...
public function market() {
    return $this->belongsTo("App\Models\Market");
}
...

// NotificationCrudController:
$this->crud->addField([
[
    'label'	=>	'Market',
    'name'	=>	'market_id',
    'type' => 'select2_from_array',
    'options' => Market::whereIn("slug", $this->getAllowedMarkets())->get()->pluck("name", "id")->all(),
    'allows_null' => true,
]);
```

### What I expected to happen

Because this field is not explicitly a relationship field, I did not expect backpack to have any trouble with only defining the `options` and not the `entity`, `model`, and `attribute` options.

### What happened

Backpack automatically detects the relationship method and tries to call `identifiableAttribute` on the model, causing an exception.

### What I've already tried to fix it

I have added the `attribute` option, but this shouldn't be necessary for fields with explicit `options`.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.27 (cli) (built: Feb 27 2021 18:04:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v6.20.20@664a9432bcceb67871c5c9252f920d28f21dfc23

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472

**Comment by pxpm** [comment]
Hello @nbolender , thanks for the report.

Does `entity => false` solves your problem ? 

Best,
Pedro

**Comment by pxpm** [comment]
I'v tested with `entity => false` and it works.

But also I think there is no sense trying to call a function when it does not exist in the model so I'v submitted #3643 

I am going to close this, let's keep any discussion in the PR thread.

Thanks again,
Pedro
