### ISSUE TITLE
[Question] Multiple Reorder abilities

### ISSUE THREAD

**Issue by stevecrossuk** [Laravel-Backpack/CRUD#3638]
# Feature Request

### What's the feature you think Backpack should have?

The reorder function for a CRUD model works great. But often, I have clients who want to have two different orders implemented. They will use Backpack just for the admin side of managing their list of products, but then we will take that data through an API into the front end. So from within Backpack, we need to implement two custom ordering functions. So I would like to know how we can duplicate "Enable Reorder", and save that order to different fields on the model.

Please.

### Have you already implemented a prototype solution, for your own project?

I've made in excess of 50 applications utilising Backpack and customised so many of them. But this has left me stumped a little.

### Do you see this as a core feature or an add-on?

Probably an add-on. I'd be happy to contribute it, but would appreciate some guidance.

**Comment by tabacitu** [comment]
Hey @stevecrossuk ,

Sorry to be so late to reply - this must have slipped through the cracks. If I understand this correctly (and I'm not sure I do), a good solution would probably be to create an _alternative_ or _additional_ Reorder operation (say... `Nest`), that would use different DB columns to store the information. You could achieve that by copy-pasting [the ReorderOperation](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Library/CrudPanel/Traits/Reorder.php), renaming it and adapting it to use different column names.

Then you'd have:
- Reorder letting admins reorder like normal;
- Nest letting admins reorder a second time (for that different place you mentioned);

It shouldn't be any different from [how you normally create a custom operation](https://backpackforlaravel.com/docs/4.1/crud-operations#creating-a-custom-operation-1). I mean it would be a little different, in that you can copy-paste a lot of the code from ReorderOperation 😅

Let me know if I've misunderstood this. And if you still need it - I realise a lot of time has passed. I don't see this as a core feature, though - I think very few projects will need 2 reorders for one model. But it's an interesting problem to solve 😅

Hope it helps, or you've already cracked this.
Cheers!

**Comment by stevecrossuk** [comment]
Thanks Cristian,

Lewis Raggett and I have been able to figure out since, but thank you for sending through the message. I completely forgot about this!

Backpack has been remarkable for our work over the last six months, and a key driver in our business growth. It is really appreciated.

With Warmest Regards,

Steve

--

Steve Cross
MCIM | M IDM | BIMA
CEO



Office. 01962 670 190 | Mobile. 07876 668 747
***@***.*** | Web. www.sprechen.co.uk

Legal Disclaimer - This message and any attachments should only be read by those persons to whom it is addressed and be used by them for its intended purpose. Sprechen Ltd cannot accept liability for statements made which are clearly the sender's own and not made on behalf of Sprechen Ltd. Replies to this email address may be subject to interception or monitoring for operational reasons or for lawful business purposes.

**Comment by tabacitu** [comment]
Music to my ears, Steve. Thanks a lot for the kind words 🙏
We'll try to keep delivering for you guys - thanks for the help.
