### ISSUE TITLE
[Bug] Null coalescing operator error in Chrome 74

### ISSUE THREAD

**Issue by dandarie** [Laravel-Backpack/CRUD#3639]
# Bug report

### What I did

Loaded any CRUD page in Chrome 74.

### What I expected to happen

The page should have worked

### What happened

The CRUD page didn't load properly in Chrome 74. Additionally, a JavaScript error was shown in the developer console: `Uncaught SyntaxError: Unexpected token '?'`.

### What I've already tried to fix it

Replaced the null coalescing operator with ternary operator in the following files:

- vendor/backpack/crud/src/resources/views/base/inc/alerts.blade.php
- vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472

```

**Comment by pxpm** [comment]
Hello @dandarie 

Thanks for raising the issue and submitting a fix. I will add my comment in the PR and close this, so we keep any discussion about it there.

Wish you the best,
Pedro
