### ISSUE TITLE
[Bug] Select and Order Issue with decimals in the key

### ISSUE THREAD

**Issue by arb362** [Laravel-Backpack/CRUD#3644]
# Bug report

### What I did

Created a model with a select_and_order field where the values were key value pairs where the key contains a decimal.
Example:
<code>[
'1.12' => 'test1',
'2.24' => 'test2',
'1.3' => 'test3',
'4.5' => 'test4',
'1.21' => 'test5'
]</code>
The currently selected values were <code> ['1.12','1.3'] </code>
Creating the model worked fine. Editing the model caused an error when loading the page.
Upon loading the page there was an error in the console and the field did not initialize correctly.

<code>Uncaught Error: Syntax error, unrecognized expression: li[value=1.21]</code>

### What I expected to happen

Shouldn't have been an error and the field initialized without error

### What happened

Because the value is not wrapped in quotes "" it is throwing a syntax error. 
<code>Uncaught Error: Syntax error, unrecognized expression: li[value=1.13]</code>

### What I've already tried to fix it

Wrapping the selector with " fixes the problem on line 147 in select_and_order.blade.php
<code>$dragSource.find('li[value="'+value+'"]').remove();</code>

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.11 (cli) (built: Oct  1 2020 20:11:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.13.0@37a0abd4f3dbc51e2256296b45f8be72c8fe2196

### BACKPACK VERSION:
4.1.26@ae68ca24844929ac38d2e792197551e823c43570

**Comment by pxpm** [comment]
Hello @arb362 

Thanks for the report and sorry for taking so much time to look at it. I can confirm that is happening.

I've submitted the fix for this, it should be merged and tagged in the next few days, I will close this when we do it. 

Cheers

**Comment by tabacitu** [comment]
Merged! We'll tag a new patch release on Monday, so it'll be available Monday the latest with a `composer update`. Thanks @arb362

**Comment by tabacitu** [comment]
Update: We've launched a new version of `backpack/crud` and `backpack/pro`. @arb362 , after you run a `composer update` you should have it fixed. Let us know if that's not the case and we'll reopen.

Cheers!

**Comment by arb362** [comment]
Thanks for the fix!
