### ISSUE TITLE
[Bug] Reordering view throws cannot redeclare function exception

### ISSUE THREAD

**Issue by floristenhove** [Laravel-Backpack/CRUD#365]
I've just enabled the reorder functionality in one of my EntityCrudControllers. When I hit the reorder button this `FatalErrorException` gets thrown:

`Cannot redeclare tree_element() (previously declared in ../storage/framework/views/8ad5ef6d18902873dfc67dc071c53716e240a276.php:21)`

This is the compiled view of the `reorder.blade.php` template.

Because all views get compiled by Laravel (right?) the `tree_element()` function is already declared in the compiled view. I couldn't find any other issues on this topic so was wondering if I'm doing something wrong or this is a new bug.

Using laravel/framework `5.3.29` and backpack/crud `3.1.51`.

Would it be a solution to declare this `tree_element()` function somewhere else instead of in the view?

**Comment by tabacitu** [comment]
Hmm... Never got this before. Maybe a ```php artisan cache:clear``` would solve your issue?

Or do you define a custom tree_element() function yourself somewhere?

**Comment by floristenhove** [comment]
Updated to 3.2 and this issue is resolved.
