### ISSUE TITLE
[Feature Request] Live column values without refreshing page

### ISSUE THREAD

**Issue by fuxionlab** [Laravel-Backpack/CRUD#3650]
# Feature Request

### What's the feature you think Backpack should have?
Live column values without refreshing page in list view.
This is just my idea of adding dynamic view on the list bootstrap table.  
??

### Have you already implemented a prototype solution, for your own project?
None but I have idea of adding a record_id in table column id attribute on view making it targetable by ajax calls when loaded.  The record_id as column id attribute value can be pulled from the loop creating the table. Additional column options would be "live" boolean, "refresh_interval" integer.
??

### Do you see this as a core feature or an add-on?
Not everyone could benefit with this feature but its good to have more options.
??

**Comment by tabacitu** [comment]
Hey @fuxionlab ,

Sorry for taking so long to get back to you on this. We've considered this a number of times (without answering you) and decided **this is not something we want inside Backpack's core**. Actual "live" values with the currently-recommended stack can only be done with polling, and as soon as you do that the whole List page becomes slow and consumes bandwidth. 

I see where this might be useful, but for 99% of all admin panels I think this is NOT needed, so we're not going to invest time into this.

However, if you or anybody else [creates a Backpack addon](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial-using-the-addon-skeleton) with a column type that does that... we'll gladly promote it so more people use it.

But we think it's something that very few people need, so it's not worth investing the time to build and maintain this.

Thank you for understanding.
Cheers!

PS. If you or anybody else stumbles unto this and think I'm wrong and we should reconsider the decision - please reply. We're human, we make mistakes all the time so we're open to feedback.
