### ISSUE TITLE
[Bug] You cannot call the model's crud column like this "example_id" (I think only if it doesn't mean a relationship)

### ISSUE THREAD

**Issue by larowka** [Laravel-Backpack/CRUD#3651]
# Bug report

### What I did
I named a column in my crud table "update_id" and this does not mean a relationship. 
`php artisan make:migration:schema create_test_table --model=0 --schema="update_id:integer:unique"`
`php artisan migrate`
`php artisan backpack:crud test`

I'm trying to open the page of this crud

### What I expected to happen

The crud page should open without errors

### What happened

The page opens, in the upper right corner there is a warning that the page has not loaded and a request to refresh the page. Table elements were not loaded.

### What I've already tried to fix it

I have tried manually connecting the columns 

>     protected function setupListOperation()
>     {
>         //CRUD::setFromDb(); // columns
>         CRUD::addColumn(['name' => 'update_id', 'type' => 'number']);
>     }

Got error 

> Call to a member function getRelated () on bool
> Backpack\CRUD\app\Library\CrudPanel\CrudPanel::Backpack\CRUD\app\Library\CrudPanel\{closure}
> vendor/backpack/crud/src/app/Library/CrudPanel/CrudPanel.php:357

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

> ### PHP VERSION:
> PHP 8.0.3 (cli) (built: Mar 31 2021 10:09:09) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.3, Copyright (c) Zend Technologies
> 
> ### LARAVEL VERSION:
> v8.34.0@81892ca110795a9c46c7e198cba7763bfd2af0bf
> 
> ### BACKPACK VERSION:
> 4.1.40@ecbe7676535d3c9121227329d62cad9978d29fee
>

**Comment by pxpm** [comment]
Hello @larowka 

Thanks for the report. It's something we are aware of, unfortunatelly the model has an `update()` method, so for Backpack, the criteria to be a relationship (or a possible one) are meet. 

- Name contains someting`_id`
- There is a method in model that is `something()`.

Interestingly I had a conversation with @tabacitu about this a few days ago, and we definatelly don't like the way it is right now. 

So our plan for the next major version is to introduce a breaking change, that to work with `auto crud functionalities`, we will add to the checklist:

- Check the return type of `something()` to see if it is a relation.

So it will be mandatory for developers to setup the relations like:

```php
public something() : BelongsTo
{ 
return $this->belongsTo();
}
```

In the meanwhile, your solution is the only available we can provide. 

Sorry for the trouble, we expect to launch the next version in the next months. 

I am going to close this, let me know if I can help you with something else.

Best,
Pedro
