### ISSUE TITLE
[Bug] FetchOperation table prefix inconsistency

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3656]
FetchOperation also has this problem with laravel 8.

Backpack\CRUD\app\Models\Traits\HasRelationshipFields.php
![image](https://user-images.githubusercontent.com/402270/113653262-154e2300-96c8-11eb-9e40-38013b49f316.png)

_Originally posted by @orzcc in https://github.com/Laravel-Backpack/CRUD/issues/3633#issuecomment-813788397_

**Comment by pxpm** [comment]
Indeed @tabacitu 

I was able to reproduce it. 

We did not change nothing here in the last times, so my guess is that something changed in underlying Laravel packages, that now, if the prefix is in `database.php` config it will be auto-appended to the query (something that didn't happened before). 

I notice it's not appended in all places. For example:

https://github.com/Laravel-Backpack/CRUD/blob/5384ceb8c23b6cf16ef7057fb712758230de6d07/src/app/Models/Traits/HasRelationshipFields.php#L71

Here, if we don't add the prefix there, it will throw a `SchemaException` error, and fail to search for the correct table name. 

Same happen here, where manually prefixing table is necessary:

https://github.com/Laravel-Backpack/CRUD/blob/5384ceb8c23b6cf16ef7057fb712758230de6d07/src/app/Library/CrudPanel/Traits/Query.php#L156

I've created #3657 to handle it. 

Let's close this and move the conversation into that PR.

Thanks for the report!
