### ISSUE TITLE
HELP Dashboard-insert crud table

### ISSUE THREAD

**Issue by ajamandre** [Laravel-Backpack/CRUD#366]
goodday

how do you insert table in dashboard page?

im using the "How to use (full example)"-crud example. instead of adding a link to show tag table in tag page, i wanted it to be inserted in dashboard page inside a <div> instead. is that possible?

**Comment by tabacitu** [comment]
Sure. You can extend the DashboardController and turn it into an actual CRUD controller. Also take a look at https://github.com/Laravel-Backpack/Base/issues/32.

Cheers!
