### ISSUE TITLE
[Bug] Error while trying to edit a record with id = 0

### ISSUE THREAD

**Issue by valebar** [Laravel-Backpack/CRUD#3662]
# Bug report

### What I did

If I try to edit a record with id=0 (the model has to start with id=0 and increment by 1), I am getting an error saying :
Trying to get property 'id' of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object at /var/www/test-project/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Update.php:108)

### What I expected to happen

I should be able to edit this record.

### What happened

The problem was with the function
 public function getCurrentEntry()
while checking if (!$id)

Because $id is 0 it passes the if test, resulting in the error described.

### What I've already tried to fix it

If you add if (is_bool($id)) before the if(!$id), the problem is fixed.
The function now looks like this:
```
public function getCurrentEntry()
{
    $id = $this->getCurrentEntryId();

    if (is_bool($id)) {
        if (!$id) {
            return false;
        }
    }

    return $this->getEntry($id);
}
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.3.27-9+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:10:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-9+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.36.2@0debd8ad6b5aa1f61ccc73910adf049af4ca0444

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472
```

**Comment by tabacitu** [comment]
Huh, thanks for the report @valebar ! Do you want to create a quick PR with it, so you show up as the contributor?

PS. I think a slightly cleaner way to code this would be `if ($id !== false) {}` - that should do the exact same thing right?

Cheers!

**Comment by tabacitu** [comment]
Just saw your PR #3663 - let's close this in favour of that. 

Cheers!
