### ISSUE TITLE
Custom Select Column Type Erroring out 'Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::getModelAttributeFromRelation' [Upgrade 4.1 V]

### ISSUE THREAD

**Issue by sandeepchowdary7** [Laravel-Backpack/CRUD#3666]
Hello, I'm trying to upgrade to the 4.1 Version. After updating the composer.json file I'm able to login successfully. But when I hit the Users List page getting an error. Cause,  I'm loading a custom column in the UserListOperation. here is my custom column. 

```
//defining a custom_select column type in CRUD controller
  [
          'label' => 'Movies',
          'name' => 'movie_id',
          'type' => 'custom_select',
          'entity' => 'movies', // the method that defines the relationship in your Model
          'attribute' => "name", // foreign key attribute that is shown to user
          'model' => Movie::class,
          'include_all_form_fields' => true
    ],
```

```
//custom_select.blade.php
<div>
    <span>
        <?php
        $attributes = $crud->getModelAttributeFromRelation($entry, $column['entity'], $column['attribute']);
        if (count($attributes)) {
            echo e(implode(', ', $attributes));
        } else {
            echo '-';
        }
        ?>
    </span>
</div>
```

Error:
**### message: "Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::getModelAttributeFromRelation does not exist.**

### Backpack, Laravel, PHP, DB version
Upgrading to 4.1

Any help would be great. Thanks!

**Comment by sandeepchowdary7** [comment]
using `getRelatedEntriesAttributes` instead getModelAttributeFromRelation fixed my issue. Thanks!

**Comment by tabacitu** [comment]
Thanks for sharing your solution @sandeepchowdary7 !
