### ISSUE TITLE
[Bug]  select column only returning parent with id of 1

### ISSUE THREAD

**Issue by MikePageDev** [Laravel-Backpack/CRUD#3675]
# Bug report

### What I did
I added the following to `setupUpdateOperation()`

```
$this->crud->addColumn([
   'label'     => 'Parent', // Table column heading
   'type'      => 'select',
   'name'      => 'parent_id', // the column that contains the ID of that connected entity;
   'entity'    => 'parent', // the method that defines the relationship in your Model
   'attribute' => 'name', // foreign key attribute that is shown to user
   'model'     => "App\Models\Category", // foreign key model
   'attributes' => [
	'disabled' => 'disabled'
    ],
]);
```

### What I expected to happen

To see the name of the parent object for this item

### What happened

No matter parent_id is in the database for the item, it returns the name for the parent with id of 1

Select is working fine for addFiled() 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.13 (cli) (built: Dec 11 2020 08:31:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans

### LARAVEL VERSION:
v8.37.0@cf4082973abc796ec285190f0603380021f6d26f

### BACKPACK VERSION:
4.1.41@44770347b918e42c052d0a138c24535b43e32472

**Comment by tabacitu** [comment]
Hmm that's odd @MikePageDev - because that's exactly what we're doing in the demo for Categories, and it's working fine there - see [here](https://demo.backpackforlaravel.com/admin/category). And the `addField()` statement is very similar too - see [here](https://github.com/Laravel-Backpack/NewsCRUD/blob/master/src/app/Http/Controllers/Admin/CategoryCrudController.php#L66-L72).

So help me understand please:
- for Create it works fine, you can select Parent with id=33
- then when the Edit page loads, instead of id 33 being selected (like in the database), the parent with id=1 is selected?

Please confirm.

Also - what happens if you comment out the line with the `type => 'select'`?

Cheers!

**Comment by MikePageDev** [comment]
Hi, I have done some more testing. Here is some more information. I have a model that belongs to a parent the belongs to a grandparent.

If I run 
```
$this->crud->addColumn([
   'label'     => 'Parent', // Table column heading
   'type'      => 'select',
   'name'      => 'parent_id', // the column that contains the ID of that connected entity;
   'entity'    => 'parent', // the method that defines the relationship in your Model
   'attribute' => 'name', // foreign key attribute that is shown to user
   'model'     => "App\Models\Category", // foreign key model
   'attributes' => [
	'disabled' => 'disabled'
    ],
]);
```
I get the correct name however I wanted to display `{grandparentName}/{parentName}.

So I created an attribute in the parent model 
```
public function getNamesAttribute()
  {
    $grandparent = grandparent::where('id', $this->grandparent_id)->first();
    return "{$grandparent->grandparent_name}/{$this->parent_name}";
  }
```
I get the following error `Can not get grandparent_name from non-object`

When I display this attribute in the list view it works fine
```
$this->crud->addFiled([
   'label'     => 'Parent', // Table column heading
   'type'      => 'select',
   'name'      => 'parent_id', // the column that contains the ID of that connected entity;
   'entity'    => 'parent', // the method that defines the relationship in your Model
   'attribute' => 'names', // foreign key attribute that is shown to user
   'model'     => "App\Models\Category", // foreign key model
]);
```

This error has only come about after I have been doing some custom css and template files. But I have not changed anything to the edit view. I have gone over all my changes but can't seem to find what has caused this.

**Comment by tabacitu** [comment]
Hmmm no idea what you're doing wrong there @MikePageDev , sorry. Maybe [the `select_from_array` field](https://backpackforlaravel.com/docs/4.1/crud-columns#select_from_array-1) will serve you better then? At least you'll have the opportunity to construct the array yourself, so you have complete control of the options, including the shown text 🤷‍♂️

This still doesn't sound like a bug in Backpack though, but an implementation error. Since the exact same thing seems to be working in the demo, I'm going to close the issue. Let me know if I'm wrong and there is a bug in Backpack but I'm too blind to see it - it's happened before, we'll reopen.

Cheers!

**Comment by MikePageDev** [comment]
I have run into this problem again today in a different app where I haven't done any customisation. I have added a test route to a blade file and called a custom attribute and it worked fine.

**Comment by tabacitu** [comment]
Hmm that's odd. Ok, let's take a closer look then. 
@pxpm / @promatik could you give it a try too?

**Comment by pxpm** [comment]
@MikePageDev do a dd(grandparent::where('id', $this->grandparent_id)->first()) and check the returned results.

My guess is that is `null` there, `$this->grandparent_id` not yielding the expected value could be the case. (when they don't have `grandparent_id`).

Also what you are doing is very expensive in terms of performance N+1 queries. 

Probably is best to eager-load category parent on the category model, and the grandparent in the parent model and just return `$this->category->parent->grandparent->grandparent_name` to avoid a query for each entry. 

Is also worth check `if($this->grandparent_id)` is set or not null wtv.

I am going to close this, I don't think there is any Backpack issue here. it's rather a bad implementation. I might be wrong, if that is the case please re-open, sometimes I might miss something.

Wish you the best,
Pedro

**Comment by MikePageDev** [comment]
Hi @pxpm I am trying the erger load option, any chance you could provide me with an example I cant seem to get this to work. I know it will be something really simple I am doing wrong.

**Comment by pxpm** [comment]
Hello @MikePageDev 

Make it first work without eager loading anything, you can do that after. 

Did you make the grandparent part work ? What I meant there is that some entries might not have the "grandparent"/"parent" set, so when you try to show it fails with the error. 

1st fix that part, after you can fix the query. In the acessor `getNamesAttribute` you need to check `if(parent exists)` and `if(granparent exists in parent)` before trying to show them. 

The eager load part, just go to the models for example the `parent` and add: `protected $with = ['grandparent'];`, this means that everytime you fetch a `parent` model, it will fetch the associated grandparents. If you don't want to ALLWAYS fetch the grandparent, you can use it only in the model when needed: `Parent::with('grandparent')->get()`.

Best,
Pedro

**Comment by MikePageDev** [comment]
@pxpm Thank you. A model always has a parent and grandparent. How do I access say model->parent->grandparent->granbparent_name in addColumn()?

**Comment by pxpm** [comment]
@MikePageDev 

```php
$this->crud->addColumn(['name' => 'parent.grandparent.grandparent_name', 'type' => 'text']);
```

**Comment by MikePageDev** [comment]
@pxpm 

I did try that and got 
`Call to undefined method App\Models\Grandparent::grandparent()`

**Comment by MikePageDev** [comment]
@pxpm I have discovered that the issue is to do with soft deletes.

**Comment by pxpm** [comment]
@MikePageDev Sorry.

Please use the relationship: 

```
$this->crud->addColumn([
            'name' => 'parent.grandparent',
            'type' => 'relationship',
            'attribute' => 'grandparent_name'
        ]);
```

So the model in this crud has a `BelongsTo` relation called `parent`, Parent model has a `grandparent` BelongsTo relation with some GrandParentModel that has the attribute `grandparent_name` to show. 

Just tested this scenario and it works.

Let me know,
Pedro

**Comment by MikePageDev** [comment]
@ that worked perfectly thanks. Now I need to add a filter for the column

**Comment by pxpm** [comment]
If you are talking about the table search input you need to code the `searchLogic` in column definition. https://backpackforlaravel.com/docs/4.1/crud-columns#custom-search-logic or overwritte the `search` method in the crud. 

If you are refering to https://backpackforlaravel.com/docs/4.1/crud-filters#about-1 regular crud filters, they are just a way to manipulate the query that is done when the table load. 

Probably you would need to use `whereHas` and stuff to filter by underlaying relations. 

Best,
Pedro

**Comment by MikePageDev** [comment]
I need to had a curd filter to filter by grandparent. I just need to get my head around the query

**Comment by pxpm** [comment]
Something like: `$query->whereHas('parent', function($parent) use ($searchTerm) { $parent->whereHas('grandparent', function ($gp) use ($searchTerm) { $gp->where('grandparent_name', 'LIKE', '%'.$searchTerm.'%' })})`
