### ISSUE TITLE
[Bug] First Filter Appears and Won't Go Away When Selecting Any Other Filter

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/CRUD#3676]
# Bug report

### What I did

I added the following filters to my Crud Controller within the `setup()` method.

```
$this->crud->addFilter([
            'name'  => 'invite_state',
            'type'  => 'dropdown',
            'label' => 'State'
        ], [
            0 => 'Invite Sent',
            1 => 'Accepted Terms',
            2 => 'Payment Provided',
            3 => 'Approved',
        ], function ($value) { // if the filter is active
            $this->crud->addClause('where', 'invite_state', $value);
        });

        $this->crud->addFilter(
            [
                'name'  => 'event_description',
                'type'  => 'select2',
                'label' => 'Event Code'
            ],
            function () {
                return \App\Models\HTOEvent::select('code', 'id')
                    ->whereExists(function ($query) {
                        $query->select(DB::raw(1))->from('hto_event_sponsors')->whereRaw('hto_event_id = hto_events.id');
                    })
                    ->get()->pluck('code', 'id')->toArray();
            },
            function ($value) {
                $this->crud->addClause('where', 'hto_event_id', $value);
            }
        );

        $this->crud->addFilter(
            [
                'name'  => 'account_description',
                'type'  => 'select2',
                'label' => 'Account'
            ],
            function () {
                return \App\Models\HTOAccount::select('company', 'id')
                    ->whereExists(function ($query) {
                        $query->select(DB::raw(1))->from('hto_event_sponsors')->whereRaw('hto_account_id = hto_accounts.id');
                    })
                    ->get()->pluck('company', 'id')->toArray();
            },
            function ($value) {
                $this->crud->addClause('where', 'hto_account_id', $value);
            }
        );
        
```

### What I expected to happen

I expect to be able to use any of the filters without unwanted issues.

### What happened
 In this case if I select an option for the `Event Code` or the `Account` filter after I do so the `State` filters drop down list will show up. Once this happens I can not get the `States` drop down list to disappear without refreshing the page. Even if I clear the filters or select a `State` filter it will not go away. 

### What I've already tried to fix it

I've updated to the latest backpack version. 
I've removed the `State` filter to see if this problem then happens with the `Event Code` filter. It does. So it is not specific to a filter it's just the fact that there are multiple filters on this page. 

### PHP VERSION:
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.3.15-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.42@9338f9711a393f82ecb09d68c0756bf24c56eafe

![Screen Shot 2021-04-20 at 11 15 30 AM](https://user-images.githubusercontent.com/28204537/115431527-09378a80-a1cb-11eb-83a6-b3407b53d28d.png)

![Screen Shot 2021-04-20 at 11 15 34 AM](https://user-images.githubusercontent.com/28204537/115431507-03da4000-a1cb-11eb-84c4-194b3e7a12aa.png)

**Comment by selected-pixel-jameson** [comment]
FYI. Just in case it's not apparent there are no javascript errors being thrown. Also, this is a non-starter for production use for me. I can't release this and expect users to refresh the page constantly.

**Comment by selected-pixel-jameson** [comment]
@tabacitu This is a pretty significant bug if that is the case as it basically renders the ability to use multiple filters invalid. Is there any way this can be escalated?

**Comment by pxpm** [comment]
I am on it @selected-pixel-jameson !

**Comment by selected-pixel-jameson** [comment]
@pxpm Thank you sir! Appreciate it.

**Comment by tabacitu** [comment]
@selected-pixel-jameson sorry, didn't mean to look dismissive by assigning someone else - I didn't answer because I could not replicate the issue, filters seemed to work fine for me: the `dropdown` filter did not show up out of the blue, and when selecting a different filter it closed properly. Tried with select2 as the "trigger" an all other filters - everything seemed to behave as expected to me.

I tested in [our online demo](https://demo.backpackforlaravel.com/admin/monster), for Monsters. Does the same thing happen to you there? If so... do you have any custom JS onpage?

Cheers!

**Comment by pxpm** [comment]
@selected-pixel-jameson I am gonna need your help here. 

This are my filters:

```php
$this->crud->addFilter([
            'name'  => 'invite_state',
            'type'  => 'dropdown',
            'label' => 'State'
        ], [
            0 => 'Invite Sent',
            1 => 'Accepted Terms',
            2 => 'Payment Provided',
            3 => 'Approved',
        ], function ($value) { // if the filter is active
            $this->crud->addClause('where', 'select_from_array', $value);
        });

        $this->crud->addFilter([ // select2 filter
            'name' => 'select2',
            'type' => 'select2',
            'label'=> 'Select2',
        ], function () {
            return \Backpack\NewsCRUD\app\Models\Category::all()->keyBy('id')->pluck('name', 'id')->toArray();
        }, function ($value) { // if the filter is active
            $this->crud->addClause('where', 'select2', $value);
        });
```

https://recordit.co/ao77b7BSjW

I tried adding in `setupListOperation` and in `setup`. 

Are you customizing filter files, or do you added any custom JS to that page ? What browser are you using ? I tested with Chrome v89.

Thanks for your patiente, we will figure this out!

Best,
Pedro

**Comment by selected-pixel-jameson** [comment]
@tabacitu No problem at all. 

@pxpm Ok. So this did shed some light on the possible issue. 

I looked into the app.js file that we have setup for this project. This is what we use to inject our own JS and VueJS components. 

I found this.

```
// We need to figure out why these aren't getting initialized by default.
$('.dropdown-toggle').dropdown()

$('.dropdown').dropdown()
```


If I take this code out the dropdown's no longer work at all. So I'm assuming this is the actual root of the problem. Do you have any insight into what might be preventing that code from getting initialized correctly?

**Comment by selected-pixel-jameson** [comment]
Ok. Problem solved!

For some reason.

`require('./bootstrap')` 

Was in our app.js file. I'm not sure why as this was implemented by a different developer, but removing it seems to fix all of our problems. 

Not sure what it will break, but I'm assuming all that JS is loaded in a different spot anyway.

**Comment by pxpm** [comment]
@selected-pixel-jameson not 100% sure, but probably bootstrap is beeing overriden by your functions ? 

What I meant is, Backpack loads `bootstrap` (css and js), and I think inside `bootstrap.js` they already do those initializations, that's why in code we work only with `classes` and `data-attributes`. 

The problem might be in the order they are loaded ? BS vs app.js ?

Maybe conflicting versions of BS ? 

Not sure about the problem, but happy that you figured out, you usually bring us `tricky` problems, when I was unable to reproduce my legs started shaking 😄 😄 

I am going to close this, but you know the deal, if you need help, ask, we try our best 👍 

Thanks,
Pedro

**Comment by selected-pixel-jameson** [comment]
@pxpm As always really appreciate your help. It's very apparent that you care about your platform and are passionate about it. Thank you!

**Comment by selected-pixel-jameson** [comment]
Just to expand on this further in case someone else runs across a similar issue. 

Within the app.js file in our application we have this.

```
/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap')
...
```

The bootstrap file contains this code. 


```
window._ = require('lodash')

/**
 * We'll load jQuery and the Bootstrap jQuery plugin which provides support
 * for JavaScript based Bootstrap features such as modals and tabs. This
 * code may be modified to fit the specific needs of your application.
 */

try {
  window.Popper = require('popper.js').default
  window.$ = window.jQuery = require('jquery')

  require('bootstrap')
} catch (e) {}

/**
 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.
 */

window.axios = require('axios')

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'

/**
 * Echo exposes an expressive API for subscribing to channels and listening
 * for events that are broadcast by Laravel. Echo and event broadcasting
 * allows your team to easily build robust real-time web applications.
 */

// import Echo from 'laravel-echo';

// window.Pusher = require('pusher-js');

// window.Echo = new Echo({
//     broadcaster: 'pusher',
//     key: process.env.MIX_PUSHER_APP_KEY,
//     cluster: process.env.MIX_PUSHER_APP_CLUSTER,
//     forceTLS: true
// });
```

If I remove the boostrap code entirely we run into issues with our VueJS components.

However, if I remove
```
  window.$ = window.jQuery = require('jquery')
  require('bootstrap')
 ```

Everything seems to be running appropriately.

**Comment by selected-pixel-jameson** [comment]
@pxpm Thanks for the heads up. We are only using this app as an admin. There is no front-end so we are all good there.
