### ISSUE TITLE
email/username availability check via ajax 

### ISSUE THREAD

**Issue by sandeepchowdary7** [Laravel-Backpack/CRUD#3683]
Hello Mates,

Is there any way to check username/email availability check via ajax and I want to show availability status immediately to the. user? Any help/suggestions would be great. 

Thanks & Regards

**Comment by tabacitu** [comment]
Not by default in Backpack, no. But you should have no problem creating an API for yourself - all the user data in the database, in normal form. It's pure Laravel from there on 😀

Cheers!

**Comment by sandeepchowdary7** [comment]
@tabacitu Thanks for the quick reply.
