### ISSUE TITLE
[Bug] Use multiselect fields in repetable field

### ISSUE THREAD

**Issue by magnatiwe** [Laravel-Backpack/CRUD#3684]
# Bug report

### What I did

Use multiselect fields in repetable field

### What I expected to happen

Correct checking selected options after save when selected more then one value

### What happened

valuePrefix broke multiple selection. 

```
let valuePrefix = $(this).data('value-prefix') ?? '';
$(this).val(valuePrefix + values[$(this).data('repeatable-input-name')]);
```

if values is array, code above convert array to string, and .val() function don't set correct multiple values to select

### What I've already tried to fix it

My fix

```
let valuePrefix = $(this).data('value-prefix') ?? false;
$(this).val(valuePrefix ? valuePrefix+values[$(this).data('repeatable-input-name')] : values[$(this).data('repeatable-input-name')]);
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.10 (cli) (built: Oct 17 2019 15:09:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.1, Copyright (c) 2002-2019, by Derick Rethans

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.43@973e8ab33d42f02272f65e9688ea250fc9502d3d

**Comment by magnatiwe** [comment]
https://github.com/Laravel-Backpack/CRUD/blob/973e8ab33d42f02272f65e9688ea250fc9502d3d/src/resources/views/crud/fields/repeatable.blade.php#L227

**Comment by pxpm** [comment]
Hello @magnatiwe thanks for the report.

Sorry for the trouble to have to deal with this.

We are aware of the problem, PR to fix is here: https://github.com/Laravel-Backpack/CRUD/pull/3654

It's already approved it should be merged very soon. 

I will be closing this, if you try the code in that PR and it works for you let us know in the comments, it could speedup the merging process. 

Thanks in advance,
Pedro
