### ISSUE TITLE
filter by pivot table

### ISSUE THREAD

**Issue by rzaglinskij** [Laravel-Backpack/CRUD#370]
HI, could you please help me with this:
I have 3 tables: subscriber, category, subscriber_category. Third table is pivot table.
I need to have a filter by category.
I have:

```
$this->crud->addFilter([ // select2_multiple filter
            'name' => 'category',
            'type' => 'select2_multiple',
            'label'=> 'Category'
        ], function() {
            foreach(\App\Models\Category::get() AS $k=>$v){
                $res[$v->id] = $v->name;
            }
            return($res);
        }, function($values) {
            $values = json_decode($values);
            unset($values[0]);
             foreach ($values as $key => $value) {
                 $this->crud->addClause('with', ['category' => function ($query) use($value) {
                     $query->where('category_id', '=', $value);
                 }]);
             }
        });
```
and filter is not working.
Please help me.

**Comment by OwenMelbz** [comment]
Define not working?

**Comment by rzaglinskij** [comment]
this is not working
$this->crud->addClause('with', ['category' => function ($query) use($value) {
$query->where('category_id', '=', $value);
}]);

filtering.
I want to filter by category ID

**Comment by noxify** [comment]
Is there a error message or just an empty datatable after selecting the filter?

**Comment by rzaglinskij** [comment]
there are no errors. just the same results in the table

**Comment by OwenMelbz** [comment]
Can you paste your whole crud controller please

**Comment by rzaglinskij** [comment]
<?php
namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Http\Request;
use App\Models\Subscriber;

use App\Http\Requests\SubscribersStoreCrudRequest as StoreRequest;
// VALIDATION
use App\Http\Requests\SubscribersUpdateCrudRequest as UpdateRequest;

class SubscribersCrudController extends CrudController
{

    private function setupAccess(){
        $u = \Auth::user();
        $this->crud->denyAccess(['list', 'update', 'delete', 'create']);
        foreach($u->roles as $role) {
            foreach($role->permissions as $permission) {
                $this->crud->allowAccess($permission->name);
            }
        }
    }

    public function setup()
    {
        parent::__construct();
        $this->setupAccess();
        $this->crud->enableAjaxTable();
        $this->crud->enableDetailsRow();
        $this->crud->enableExportButtons();
        $this->crud->setModel("App\Models\Subscriber");
        $this->crud->setRoute("admin/subscribers");
        $this->crud->setEntityNameStrings('subscriber', 'subscribers');
        $this->crud->orderBy('id', 'desc');
        $this->crud->allowAccess('revisions');
        $this->crud->setColumns([
            ['name' => 'id', 'label' => 'Id'],
            ['name' => 'email', 'label' => 'Email'],
            ['name' => 'ip', 'label' => 'Ip'],
            //['name' => 'visibility', 'label' => 'visibility'],
            ['name' => 'active', 'label' => 'Subscribed', 'type'=>'boolean', 'options'=>[0=>'No', 1=>'yes']],
            ['name' => 'create_date', 'label' => 'Created'],
            ['label' => "Categories",
                'type' => 'select_multiple',
                'name' => 'category',
                'entity' => 'category',
                'attribute' => 'name',
                'model' => 'App\Models\Category',
                'pivot' => true],
            ['name' => 'place', 'label' => 'Place', 'type'=>'subscriberstatus'],
            ['name' => 'lon', 'label' => 'Lon', 'type'=>'subscriberstatus'],
            ['name' => 'lat', 'label' => 'Lat', 'type'=>'subscriberstatus'],
        ]);

        $this->crud->addField([
            'name' => 'email',
            'label' => "Email",
            'type' => 'text'
        ]);
        $this->crud->addField([
            'name' => 'place',
            'label' => "Place",
            'type' => 'text'
        ]);
        $this->crud->addField([
            'name' => 'lon',
            'label' => "lon",
            'type' => 'text'
        ]);
        $this->crud->addField([
            'name' => 'lat',
            'label' => "lat",
            'type' => 'text'
        ]);
//        $this->crud->addField([
//            'name' => 'visibility',
//            'label' => "Visibility",
//            'type' => 'checkbox'
//        ]);
        $this->crud->addField([
            'name' => 'active',
            'label' => "Subscribed",
            'type' => 'checkbox'
        ]);
        $this->crud->addField([
            'name'=>'encryptedemail',
            'label'=>'Encrypted email',
            'type'=>'encryptedemail'
        ]);
        $this->crud->addField([       // SelectMultiple = n-n relationship (with pivot table)
            'label' => "Reports",
            'type' => 'select2_multiple',
            'name' => 'reports', // the method that defines the relationship in your Model
            'entity' => 'reports', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => 'App\Models\Report', // foreign key model
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
        ]);
        $this->crud->addField([       // SelectMultiple = n-n relationship (with pivot table)
            'label' => "Categories",
            'type' => 'select2_multiple',
            'name' => 'category', // the method that defines the relationship in your Model
            'entity' => 'category', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => 'App\Models\Category', // foreign key model
            'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
        ]);

        $this->setupFilters();
    }

    private function setupFilters(){
        $this->crud->addFilter([
            'name' => 'active',
            'label' => 'Subscribed',
            'type' => 'dropdown'
        ],
            function() {
                return [
                    'no' => 'No',
                    'yes' => 'Yes',
                ];
            },
            function($value) {
                if($value == 'no') $value = 0; else $value = 1;
                $this->crud->addClause('where', 'active', $value);
            });
        $this->crud->addFilter([
            'name' => 'place',
            'label' => 'NULL Place',
            'type' => 'simple'
        ],
            false,
            function() {
                $this->crud->addClause('whereNull', 'place');
                $this->crud->addClause('where', 'place', 'NULL');
                $this->crud->addClause('where', 'place', '');
            });
        $this->crud->addFilter([
            'name' => 'lon',
            'label' => 'NULL Longitude',
            'type' => 'simple'
        ],
            false,
            function() {
                $this->crud->addClause('whereNull', 'lon');
            });
        $this->crud->addFilter([
            'name' => 'lat',
            'label' => 'NULL Latitude',
            'type' => 'simple'
        ],
            false,
            function() {
                $this->crud->addClause('whereNull', 'lat');
            });
        $this->crud->addFilter([ // select2_multiple filter
            'name' => 'category',
            'type' => 'select2_multiple',
            'label'=> 'Category'
        ], function() {
            foreach(\App\Models\Category::get() AS $k=>$v){
                $res[$v->id] = $v->name;
            }
            return($res);
            //return \App\Models\Category::get()->keyBy('id')->pluck('name');
        }, function($values) {
            $values = json_decode($values);
            unset($values[0]);
             foreach ($values as $key => $value) {
//                 $this->crud->addClause('with', ['category' => function ($query) use($value) {
//                     $query->where('category_id', '=', $value);
//                 }]);
                 $this->crud->with(['category' => function ($query) use ($value) {
                     $query->where('category_id', '=', $value);
                 }]);
             }
        });
    }

    public function edit($id)
    {
        $this->crud->hasAccessOrFail('update');
        // get the info for that entry
        $this->data['entry'] = $this->crud->getEntry($id);
        $this->data['crud'] = $this->crud;
        $this->data['fields'] = $this->crud->getUpdateFields($id);
        $this->data['title'] = trans('backpack::crud.edit') . ' ' . $this->crud->entity_name;
        $this->data['id'] = $id;
        $dbRow = \DB::table('options')->where('name', 'googleMapsApiKey')->first();
        $this->data['gApiKey'] = $dbRow->value;
        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view('admin.subscriber.edit', $this->data);
    }

    public function showDetailsRow($id)
    {
        $collection = Subscriber::findOrFail($id);
        return view('admin.subscriber.details', ['subscriber' => $collection]);
    }

    public function store(StoreRequest $request)
    {
        return parent::storeCrud();
    }

    public function update(UpdateRequest $request)
    {
        return parent::updateCrud();
    }
}

**Comment by OwenMelbz** [comment]
Ha erm, I think something went a little wrong there!

Could you paste the WHOLE thing, and make sure its in a readable format so people can see where the issue may lay :D

**Comment by rzaglinskij** [comment]
sorry...
edited

**Comment by OwenMelbz** [comment]
try removing `parent::__construct();`

**Comment by rzaglinskij** [comment]
the same results

**Comment by rzaglinskij** [comment]
subscriber model - http://pastebin.com/prDz6xU2
category model - http://pastebin.com/m39vA0C4
crud controller - http://pastebin.com/4seRUjqW

**Comment by rzaglinskij** [comment]
Any ideas ?
I really need this feature ASAP...

**Comment by OwenMelbz** [comment]
I can't replicate any issues in any similar project.

I suggest you strip out all the code from the fields and basic columns to just 1 filter and 1 name column.

Then you can isolate if there is a conflict, user error or bug

**Comment by rzaglinskij** [comment]
could you, please post here an example of howto create filter on pivot table ?

**Comment by OwenMelbz** [comment]
Scroll up ^

**Comment by OwenMelbz** [comment]
as this might be an ajax issue, i'll migrate into the other thread

**Comment by rzaglinskij** [comment]
also, still not working
 $this->crud->addFilter([ // select2 filter
            'name' => 'frontendtags',
            'type' => 'select2',
            'label'=> 'FE Tag'
        ], function() {
            return \App\Models\FrontendTags::all()->pluck('name', 'id')->toArray();
        }, function($value) {
            $this->crud->addClause('with', ['frontendtags' => function ($query) use ($value) {
                $query->where('tag_id', '=', $value)->toSql();
            }]);
        });
how can I debug this generated SQL ?

**Comment by darrena092** [comment]
Not sure if you're still having this issue - but there's an example in the docs on how to filter based on a select2_multiple filter using an n-n relationship which has worked for me in the past.

`$this->crud->addFilter([ // select2_multiple filter
  'name' => 'tags',
  'type' => 'select2_multiple',
  'label'=> 'Tags'
], function() { // the options that show up in the select2
    return Product::all()->pluck('name', 'id')->toArray();
}, function($values) { // if the filter is active
    foreach (json_decode($values) as $key => $value) {
        $this->crud->query = $this->crud->query->whereHas('tags', function ($query) use ($value) {
            $query->where('tag_id', $value);
        });
    }
});`

See: [https://laravel-backpack.readme.io/v3.0/docs/filters#section-extra-examples](https://laravel-backpack.readme.io/v3.0/docs/filters#section-extra-examples)

**Comment by maganius** [comment]
I have the same issue, in my case I have `items` and `order_item`, I need search in `orden_item.fecha` my CRUD model is set to `Item::class`.

How I can filter by `fecha` if its own pivot?

I can't make something like this:
`$this->crud->query = $this->crud->query->whereHas('item',` because `Item:item` relation doesnt exists.

Its my filter:

```
$this->crud->addFilter([
            'type' => 'date_range',
            'name' => 'fecha_pedido',
            'label' => 'Fecha',
        ],
            false,
            function ($value) { // if the filter is active, apply these constraints
                $dates = json_decode($value);
                // here I need the filter
                $this->crud->addClause(function($query) use($dates){
                    $query->where('fecha', '>=', $dates->from);
                    $query->where('where', 'fecha', '<=', $dates->to);
                });
            });
```

**Comment by seyacat** [comment]
This work for me


                
                

> $this->crud->addClause('orWhereHas', 'juego' , function ($query) use($permission) {
>                     $query->where('nombre', '=', $permission);
>                     });
