### ISSUE TITLE
[Feature Request] Add support reorder repeatable rows

### ISSUE THREAD

**Issue by bedoz** [Laravel-Backpack/CRUD#3702]
# Feature Request

Repeatable field are a block that i use a lot to manage n-n relationship with pivot table with additional fields.
I don't know if there is a better way to do this.
Saving data as json into field should be possible to reorder rows with a drag and drop.

Could be this feature implemented?

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core

**Comment by pxpm** [comment]
@bedoz totally. There is a PR open for it: https://github.com/Laravel-Backpack/CRUD/pull/3685

Give it a try, and let us know the results, it would help in the merging process :)

I am going to close this as there is already a PR for.

Wish you the best,
Pedro

**Comment by bedoz** [comment]
sorry my fault, I used the search to find tickets about it but I definitely used the wrong keys.
Glad to hear that there is a PR on it, i hope it will become soon an active feature.

Thank you and take care!
Alex
