### ISSUE TITLE
[Bug] select column limit for text

### ISSUE THREAD

**Issue by MeerKatDev** [Laravel-Backpack/CRUD#3703]
In line 10 there should be an ampersand:
```php
    foreach ($attributes as $key => &$text) {
        $text = Str::limit($text, $column['limit'], '[...]');
    }
```

**Comment by pxpm** [comment]
Hello @MeerKatDev 

We recently fixed something similar https://github.com/Laravel-Backpack/CRUD/pull/3648 , is there any other places ? 

Let me know what file are you talking about.

Best,
Pedro

**Comment by MeerKatDev** [comment]
as in the title, `crud/columns/select.blade.php`, I didn't find any other place for now. If there is already a PR you can close this

**Comment by pxpm** [comment]
Yes @MeerKatDev , the PR I mentioned is for select column and is already merged on master!

I will be closing this, thanks for raising the issue!

Best,
Pedro
