### ISSUE TITLE
[Bug] allow_null true and required false doesn't work

### ISSUE THREAD

**Issue by scwall** [Laravel-Backpack/CRUD#3706]
# Bug report

### What I did

added the required false field and added the allow_null field
```
            [
                'name' => 'location_id',
                'type' => 'select',
                'label' => 'Emplacement',
                'entity' => 'location',
                'attribute' => 'name',
                'required' => false,
                'allow_null' => true,
                'model' => 'App\Models\Location',
            ],

```
![](https://i.imgur.com/7VOLDei.png)
### What I expected to happen

That the field is not required 

### What happened

The field is required

![](https://i.imgur.com/uswAjTh.jpg)
### What I've already tried to fix it

To see if it was a cache problem to change the select method 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.43@973e8ab33d42f02272f65e9688ea250fc9502d3d

**Comment by pxpm** [comment]
Hello @scwall 

Hope you found the solution. I would just remove `required => false` from field. 

Also Backpack has a feature that "auto-selects" the required fields if you provide a `StoreRequest` in Controller. If you make it `required` in the «StoreRequest», Backpack will add the `red ( * ) astherisc` as required in the form. 

Best,
Pedro
