### ISSUE TITLE
remove Button undefined variable name.

### ISSUE THREAD

**Issue by Darival** [Laravel-Backpack/CRUD#371]
in Laravel 5.2
I have the same issue than
#180 

and I did the following to make it work:
```php
public function removeButton($name)
    {
        $this->buttons = $this->buttons->reject(function ($button) use (&$name){
            return $button->name == $name;
        });
    }
```

**Comment by Darival** [comment]
Oh i see this was solved already but my composer has this package fixed,

		"backpack/crud": "^3.0",

**Comment by tabacitu** [comment]
Hi @Darival ,

Yes, follow [this upgrade guide](https://laravel-backpack.readme.io/v3.0/docs/upgrade-guide-30-to-31) and you issue should be fixed.

Cheers!
