### ISSUE TITLE
[Feature Request] Add on / off button

### ISSUE THREAD

**Issue by Esh-network** [Laravel-Backpack/CRUD#3715]
What functionality do you think Backpack should have?

I think a multiselect feature to activate / deactivate elements would be welcome in backpack larevel (example for articles)

https://cdn.esh-dev.fr/upload/PhotoFiltre7_hnSgrSXi6r.png

The features can be useful for everyone.

I have not yet tested to add this functionality but if some have already made it known: D.

Thank you.

Cordially.

**Comment by nbolender** [comment]
I think you could do this by creating a custom action and button. Example here: https://backpackforlaravel.com/docs/4.1/crud-operations#creating-a-new-operation-with-a-bulk-action-no-interface

**Comment by tabacitu** [comment]
🎰 🎰 🎰  💰💰💰 Jackpot @nbolender ! 😀  Thanks!

@Esh-network this doesn't seem to me like something most projects would need, so we'd rather leave this one for each dev to do it. If you find yourself needing it across multiple entities or packages though, please: 
- consider taking a look at the link @nbolender gave you above
- think about creating a package for it, to re-use across multiple projects, and maybe even make it available to the community; it's easier than ever to create a Backpack addon nowadays, just [follow this tutorial](https://backpackforlaravel.com/docs/4.1/add-ons-tutorial-using-the-addon-skeleton);

Let us know if you do create a package for it, we'd love to get more eyeballs onto it.
Cheers!
