### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MohaMBS** [Laravel-Backpack/CRUD#3716]
# Bug report the crud does not work

### What I did

Just genereated the crud.

### What I expected to happen

The crud would have to come out correctly

### What happened

The crud just fail
![Captura de pantalla 2021-05-16 150926](https://user-images.githubusercontent.com/72398757/118398402-bc739200-b658-11eb-8e2e-09663e1e2b74.png)
what would be the solution?

### What I've already tried to fix it

Installing from scratch, modifying configuration files

### LARAVEL VERSION:
v8.41.0@05417155d886df8710e55c84e12622b52d83c47c
### BACKPACK VERSION:
4.1.44@42b837deb11870399e63310817b7e50b82570ed
###Mysql  
Ver 15.1 Distrib 10.4.18-MariaDB, for Win64 (AMD64), source revision 53123dfa3e365138591fd2f160c6057aca00a3e6
When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
@MohaMBS what does your Network tab look like, in your Chrome DevTools? That's where you can see the AJAX request being made to populate the table with actual information. And that's where you should see a failing request, and if you click it it will give more information about what went wrong.

**Comment by MohaMBS** [comment]
Now its working with out reason

**Comment by pxpm** [comment]
Nice to hear that it's working, it was probably some cache issue or something alike. 

I am going to close this, thanks!

Best,
Pedro

**Comment by MohaMBS** [comment]
The solution was just start the serve with the next command 
```php artisan serve```

**Comment by MohaMBS** [comment]
> Nice to hear that it's working, it was probably some cache issue or something alike.
> 
> I am going to close this, thanks!
> 
> Best,
> Pedro

It was my mistake, I needed to execute the following command but thanks!
´´´php artisan serve´´´
