### ISSUE TITLE
[Bug] laravel 8.43.0 introduces a new function name with colllides and breaks nested set

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#3729]
# Bug report

### What I did

I simply updated Laravel from 8.42.1 to 8.43

### What I expected to happen

Nothing of bad

### What happened

This

> Declaration of Kalnoy\Nestedset\BaseRelation::getRelationQuery(Illuminate\Database\Eloquent\Builder $query, Illuminate\Database\Eloquent\Builder $parent, $columns = Array) should be compatible with Illuminate\Database\Eloquent\Relations\Relation::getRelationQuery()

### What I've already tried to fix it

We can't fix. 

The problem is explained here on official laravel/framework repo:  https://github.com/laravel/framework/issues/37486 

I kindly asked to change the name to the new public api but they closed with "we won't be reverting this". 

and here on nestedset repo: https://github.com/lazychaser/laravel-nestedset/issues/509

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.14 (cli) (built: Jan  5 2021 15:12:29) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.43.0@3ec63771a07e251f4fb6c7ef2411a79a314bba65

### BACKPACK VERSION:
4.1.45@c9918581306bc4a8d605b87b4757893baa03fcc1
```

**Comment by pxpm** [comment]
Hello @realtebo 

I don't see backpack mentioned anywhere. The conflict is with `Kalnoy\Nestedset` with `Illuminate\Database\Eloquent\Relations\Relation`

The file in question is: https://github.com/lazychaser/laravel-nestedset/blob/789a70bce94a7c3bd206fb05fa4b747cf27acbe2/src/BaseRelation.php and the method name is mentioned in the errors.

I am closing this, as I don't think this relates to Backpack.

If I am wrong, and sometimes I am, please re-open. 

Best,
Pedro
