### ISSUE TITLE
[Question] How to enable custom input in select2_multiple

### ISSUE THREAD

**Issue by noxify** [Laravel-Backpack/CRUD#373]
Hi,

i'm using the rinvex/tag package to enable the tag support for my models.

I have added the `select2_multiple` field. Attribute `pivot` is set to `true`.
With the OOB CRUD Implementation I got everytime an exception.

Now i solved it with an workaround (for me) and did the following:

1. duplicate the `select2_multiple` template and renamed it to `select2_tags`
2. updated the select2 assets to 4.0.3 (with the select2 bootstrap theme)
3. changed the `select2_tags` template to the following: https://gist.github.com/noxify/d16118d791ee975d52836e9dbd2c2a4e
4. In the `setup` method, i updated the field definition to the following: 
```
		$this->crud->addField([
			'label' => "Tags",
			'type' => 'select2_tags',
			'name' => 'tags', // the method that defines the relationship in your Model
			'entity' => 'tags', // the method that defines the relationship in your Model
			'attribute' => [
				'key'   => 'slug',
				'value' => 'name'
			],
			'model' => \Rinvex\Tag\Tag::class, // foreign key model
			'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
		]);
```

5. Changed the `update` method inside my Crud Controller to the following: https://gist.github.com/noxify/f0ee130f6915e587c0bbfef0035f4636

Not sure if this is good/bad solution, but I didn't found another way to call the `retag` method.

With the latest version from select2 (4.0.3) it's now possible to use `tags: true` for select fields.

Some idea or something else?

Thanks.

**Comment by OwenMelbz** [comment]
Remember that backpack is just a mini framework to help you build admin panels.

It's a starting point for generic use cases.

If you need a custom field type then by all means create it :)

There's no right/wrong way to use it, as I say it's just a starting point for you!

However the thing to remember is that if you do create your iwn modified functions, you'll need to maintain these - so when new features come out they might not work as you have custom functions.

So you could try not replacing the whole function in your controller, just do your changes and still call the parent methods
