### ISSUE TITLE
[Bug] `repeatable` field loads in footer instead of panel if using the `address_google` field

### ISSUE THREAD

**Issue by GarrettU27** [Laravel-Backpack/CRUD#3730]
# Bug report

### What I did
Created a CRUD controller with an `address_google` field and a `repeatable` field, and the `repeatable` field showed up in the footer rather than the panel.

### What I expected to happen
I expected the `repeatable` field to show up in the panel, similar to this
![image](https://user-images.githubusercontent.com/80977616/119738591-88f9ea00-be46-11eb-980e-af404ba49160.png)

### What happened
The `repeatable` field ended up in the footer, like this
![image](https://user-images.githubusercontent.com/80977616/119738615-957e4280-be46-11eb-8e9e-511c62303e84.png)

### What I've already tried to fix it
I have attempted changing the `address_google` field. Changing `address_google` to `address_algolia` or `text` produced the *What I expected to happen* result

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:30) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c
```

### The Code
```
<?php

namespace App\Features\Location\Backpack\Screens\Location\Controllers;

use App\Features\Location\Backpack\Screens\Location\Requests\AddressRequest;
use App\Features\Location\Models\Address;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;

/**
 * Class AddressCrudController
 * @package App\Http\Controllers\Admin
 * @property-read \Backpack\CRUD\app\Library\CrudPanel\CrudPanel $crud
 */
class AddressCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;

    public function setup()
    {
        CRUD::setModel(Address::class);
        CRUD::setRoute(config('backpack.base.route_prefix') . '/address');
        CRUD::setEntityNameStrings('address', 'addresses');
    }

    protected function setupListOperation()
    {
        CRUD::setFromDb(); // columns
    }

    protected function setupCreateOperation($editNames = false)
    {
        CRUD::setValidation(AddressRequest::class);

        $this->crud->addFields(
            [
                [
                    'name' => 'street_address',
                    'label' => 'Street Address',
                    'type' => 'address_google',
                    'wrapper' => ['class' => 'form-group col-md-6']
                ],
            ]
        );

        $this->crud->addField([   // repeatable
            'name'  => 'field_',
            'label' => 'Fields',
            'type'  => 'repeatable',
            'fields' => [
                [
                    'name' => 'field1',
                    'label' => 'Field1',
                    'type' => 'text',
                    'wrapper' => ['class' => 'form-group col-md-4']
                ],

                [
                    'name' => 'field2',
                    'label' => 'Field2',
                    'type' => 'text',
                    'wrapper' => ['class' => 'form-group col-md-4']
                ],
                [
                    'name' => 'field3',
                    'label' => 'Field3',
                    'type' => 'text',
                    'wrapper' => ['class' => 'form-group col-md-4']
                ],
                [
                    'name' => 'field4',
                    'type' => 'checkbox',
                    'label' => 'Field4',
                    'wrapper' => ['class' => 'form-group col-md-4']
                ],
            ],

            // optional
            'new_item_label'  => 'Add Values', // customize the text of the button
            'init_rows' => 1, // number of empty rows to be initialized, by default ,
        ]);
    }

    protected function setupUpdateOperation()
    {
        $this->setupCreateOperation(true);
    }
}

```

**Comment by o15a3d4l11s2** [comment]
I just tested with your sample code and it works as expected for me (see the screenshot).
<img width="1525" alt="Screenshot 2021-05-27 at 12 11 46" src="https://user-images.githubusercontent.com/934385/119799626-eba1c300-bee4-11eb-864f-699368f62e1d.png">

@GarrettU27, could you please check your browser console for any errors and send them here?

**Comment by pxpm** [comment]
I could not reproduce this so I am going to close.

If you think I am wrong please feel free to re-open or keep the conversation going.

Wish you the best,
Pedro

**Comment by Garrett45** [comment]
Hey there! Sorry for the delay. I was off travelling for the Memorial Day holiday in the US. I did some more work on the error and it seems related to sub-dependencies. Updating `composer.lock` results in it working properly. Although, I'm also starting to see some contradictory data. I'm still working on analysis.

Attached are the Javascript errors I see when the screen display error presents
![image](https://user-images.githubusercontent.com/38052343/120386245-0497e300-c2ee-11eb-888c-b16d1ae5d004.png)

With a fresh composer update, and laravel mix build, I still get this error, but the screen display error is not present.
![image](https://user-images.githubusercontent.com/38052343/120386320-1bd6d080-c2ee-11eb-826a-8deae4399d12.png)

**Comment by o15a3d4l11s2** [comment]
The error itself (1st screen) makes sense to break the field - it is the Google Address field JS that breaks. But it is very strange **why** the error happens on the first place.

For me this "Unexpected token H..." error is caused by the data of the record in the database, that is not in the correct format. Could you please check your database for the exact same record (address with id 24) and see what the data looks like? If possible please share it here and we can check it together.

**Comment by Garrett45** [comment]
The data for the record id 24 is
`11160 Hillsboro Court North`

This is what happens when I run `JSON.parse()` on the data
![image](https://user-images.githubusercontent.com/38052343/120538870-99f9ac80-c3ac-11eb-8b00-cff6de4ff88a.png)

There is no error with `address_algolia` or `text`, but `address_google` does throw the error.

I have the `address_google` field configured like this:
```php
 [
    'name' => 'street_address',
    'label' => 'Street Address',
    'type' => 'address_google',
    'wrapper' => ['class' => 'form-group col-md-6'],
    'store_as_json' => false
 ]
```
but the error is thrown when `store_as_json` is true and when it is false

**Comment by o15a3d4l11s2** [comment]
Now I got the error :)

The problem is you are using an old version of Backpack. The latest version has
```js
if ($field.val().length) {
    console.log($field.val())
    try {
        var existingData = JSON.parse($field.val());
        element.val(existingData.value);
    } catch(error) {
        element.val($field.val());
    }
}
```

**Comment by pxpm** [comment]
Hello @o15a3d4l11s2 

Very nice job man! 😃 

Let me just add that the commit you referenced have one big big change: in the end, the script loading tag introduces `v=3` in the string, that will load google v3 api. 

Thanks again @o15a3d4l11s2 !

**Comment by Garrett45** [comment]
Thank you all so much for your help! I was able to fix the issue by updating.

**Comment by tabacitu** [comment]
Glad you found the solution @Garrett45 ! (no thanks to me 😅 )

Just wanted to say a big "_thank you_" to @o15a3d4l11s2 🙏.  @pxpm and I, we super-appreciate the help.

--

Team talk:

Personally, from this issue I've learnt/remembered that... we should _probably_ pay closer attention to the reported version 😅 If we can't reproduce the bug, our first instinct should be to ask people to do a `composer update`, chances are that the issue was fixed in an update 😅. But... I know... it's a super-easy thing to forget - the version. Both for us and for users. In fact, I've gone ahead and [updated the issue template in this repo](https://github.com/Laravel-Backpack/CRUD/commit/371d8e8123f7a6fb807c2861800fcaaea8676f17) to ask people if the update is still there after a `composer update`. Hopefully it'll save people some minutes/hours/days 🤞

**Comment by o15a3d4l11s2** [comment]
@tabacitu, I am trying to get more active here and also in Gitter :)

About the team talk - I totally agree. I felt stupid for a moment after I realised the issue was an outdated version and the issue was already fixed. Great that you took the extra step of updating the issue template!

**Comment by tabacitu** [comment]
Yeah I know, it's super-easy to forget to ask that. I probably would have forgotten too 😅
