### ISSUE TITLE
[Bug] Uncaught TypeError: crud is undefined

### ISSUE THREAD

**Issue by FaintlyRaiseIncome** [Laravel-Backpack/CRUD#3731]
# Bug report

### What I did

I installed the backpack-demo project

### What I expected to happen

I wanted to check for the same error as in the installation of the video course from backpack

### What happened

On pages:
/admin/article; /admin/category; /admin/tag;
It does not display the table in the proper image, creating new records in tables and displaying existing records on this very page does not work.

Console error: 
**Uncaught TypeError: crud is undefined**

Sntring in JS:
`crud.table = $("#crudTable").DataTable(crud.dataTableConfiguration);`

Page:
![изображение](https://user-images.githubusercontent.com/72858337/119971988-dd829e00-bfdb-11eb-93d9-fbeeb7e0337f.png)

### What I've already tried to fix it

I tried to find the page compilation file and find this line of code.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.40.0@a654897ad7f97aea9d7ef292803939798c4a02a4

### BACKPACK VERSION:
4.1.43@973e8ab33d42f02272f65e9688ea250fc9502d3d

**Comment by FaintlyRaiseIncome** [comment]
![изображение](https://user-images.githubusercontent.com/72858337/119971113-c2fbf500-bfda-11eb-8b61-b97b8fef31ed.png)

**Comment by tabacitu** [comment]
That's weird. Just tested and it works fine for me. 

What browser are you using @FaintlyRaiseIncome ? And what version?

**Comment by FaintlyRaiseIncome** [comment]
PHP VERSION:

PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
LARAVEL VERSION:

v8.40.0@a654897ad7f97aea9d7ef292803939798c4a02a4
BACKPACK VERSION:

4.1.43@973e8ab33d42f02272f65e9688ea250fc9502d3d


Firefox browser

**Comment by pxpm** [comment]
Hello @FaintlyRaiseIncome 

I could not get FF 88, but I got 89.

Everything seems to be ok here:

![image](https://user-images.githubusercontent.com/7188159/120677161-b53ce880-c48e-11eb-9405-66281305626a.png)
![image](https://user-images.githubusercontent.com/7188159/120677332-def60f80-c48e-11eb-8e1b-5619efb4bb05.png)

Can you reproduce your error in https://demo.backpackforlaravel.com ?

Let me know,
Pedro

**Comment by FaintlyRaiseIncome** [comment]
@tabacitu Thanks you, yes, it's all right 
![изображение](https://user-images.githubusercontent.com/72858337/120924322-5204bd80-c6fd-11eb-95be-bc629423bd64.png)
