### ISSUE TITLE
Default field doesn't work for 'select' field

### ISSUE THREAD

**Issue by nihadatakishiyev** [Laravel-Backpack/CRUD#3742]
# Bug report

The value of the default field is ignored when attribute type 'select' is selected. 

My code is given below: 

```
            [
                'label' => 'Project',
                'type' => 'select',
                'name' => 'project_id', //name to be referred by dependant
                'entity' => 'project', //method name in the model
                'attribute' => 'name', //attribute to be displayed, ex name, id
                'allows_null' => false,
                'default' => 'MyGov',
                'fake' => true,
                'wrapper' => ['class' => 'form-group col-md-6']
            ]
```

I was expecting the field to be set to 'MyGov' by default when I open Edit or Create view.

However, the value of the default field is ignored and the first value in the select list is displayed as the default value

Version info: 

PHP 8.0.3
Laravel 8.33.1
Backpack 4.1.40

**Comment by pxpm** [comment]
Hello @nihadatakishiyev, in default you should use `model key` (probably id) and not model attribute. So `default => 1` for id=1.

Let me know,
Pedro

**Comment by nihadatakishiyev** [comment]
@pxpm worked like a charm. It would have been nice if it was mentioned in the documentation @tabacitu. 

Thanks a lot!
