### ISSUE TITLE
[Bug] Mutator not called on repeatable field

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#3743]
Full report below:
I have a field in my ```UserCrudController``` like so:
```
CRUD::addField(['tab' => 'Unavailability', 'name' => 'unavailability_entries', 'type' => 'repeatable',
    'fields' => [
      ['name' => 'from', 'type' => 'date', 'label' => 'From', 'wrapper' => ['class' => 'form-group col-md-3']],
      ['name' => 'to', 'type' => 'date', 'label' => 'To', 'wrapper' => ['class' => 'form-group col-md-3']],
      ['name' => 'notes', 'type' => 'text', 'label' => 'Notes', 'wrapper' => ['class' => 'form-group col-md-6']],
    ],
    'new_item_label' => 'New Unavailability'
]);

```
The ```getUnavailabilityEntriesAttribute()``` function is called and loads my data perfectly, however, when saving, the ```set``` function is never called. It is called on every other attribute that I am testing, this is my only ```repeatable``` field

# Bug report

### What I did

Have a non-existent field in my model which I want to save to another table, via a ```repeatable``` field

### What I expected to happen

The ```setUnavailabilityEntriesAttribute()``` function gets called so I can save the data how I like

### What happened

The function is never called

### What I've already tried to fix it

Have read through the #3290 and #3279 discussions

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.6 (cli) (built: May 13 2021 05:36:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.6, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.44.0@7b3b27dc8911ab02a69731af2ba97b5130b2ddb8

### BACKPACK VERSION:
4.1.46@4bb96f8e34289b858e482ad9c9bf3ea51cb8b7c0
```

**Comment by pxpm** [comment]
Hello @olipayne.

As stated in those issues, mutators only fire when you `set` some model property. 

Since  `unavailability_entries` is not an attribute in your model, `$model->unavailability_entries` mutator is never fired. 

You can have a look at `creating / updating` model events, and do your saving process there. Or directly in the controller overriding backpack `store` / `update` method. 

Let me know,
Pedro

**Comment by olipayne** [comment]
Hey Pedro, thanks for the advice! Since I'm saving these entries in a separate table, I need to reference the ```user_id``` as part of the row, however that doesn't exist on ```creating``` event, if I remember correctly. 

How would you get around that?

**Comment by pxpm** [comment]
I would go check in `created` isn't that an option?

Best,
Pedro

**Comment by olipayne** [comment]
You're right, I ended up hooking into the ```saved``` model event, which always has the ID :)

```       
            // If we're saving a user, we might need to store their unavailability
            $raw = request()->get('unavailability_entries', false);
            if ($raw) {
                $entries = json_decode($raw);
                UserUnavailability::where('user_id', $user->id)->delete();
                foreach ($entries as $entry) {
                    if ($entry->from && $entry->to) {
                        $entry = UserUnavailability::create([
                        'user_id' => $user->id,
                        'from' => $entry->from,
                        'to' => $entry->to,
                        'notes' => $entry->notes ?? ''
                      ]);
                    }
                }
            }
```

Thanks for your help, @pxpm!
