### ISSUE TITLE
[Bug] WrapperAttributes class attribute will disable the frontend validation messages

### ISSUE THREAD

**Issue by IoanAndrei97** [Laravel-Backpack/CRUD#3752]
# Bug report

### What I did
I have this field:
`[
                'name'              => 'measurements.weight',
                'type'              => 'number',
                'label'             => 'Weight',
                'attributes'        => ['step' => 'any'],
                'suffix'            => 'g',
                'tab'               => 'Measurements',
                'wrapperAttributes' => [
                    'class' => 'col-md-3',
                ],
            ],`
and the following validation in the Request class: `'measurements.height'      => ['required'],`.

### What I expected to happen

I'm expecting to have the red * in the label, the input to have a red border on submit (if the rule is not followed) and the tab to be highlighted.

### What happened
The only validation message is on the top of the form. No red *, input message or red highlight is appearing on the page.

### What I've already tried to fix it
If I remove the 'class' attribute from WrapperAttributes, the things are normal.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes, the bug is still here.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: PHP 7.4.4, Laravel 8.36.2, Backpack 4.1.46

**Comment by pxpm** [comment]
Hello @IoanAndrei97 

I think there is a typo in your code. You have field name `weight` and validate for `height`. 

Is that the problem ? 

Also don't forget to add the `form-control` class into your class definition. 

Let me know,
Pedro

**Comment by IoanAndrei97** [comment]
@pxpm 
Sorry for the wrong validation, but that was not the problem.
The problem was the fact that I missed the `form-group` class into my class definition. ( Actually your message lead me to this, so thank you! )

Sorry for bothering you. I will close the this :)

**Comment by pxpm** [comment]
Yes, `form-group` not `form-control`. My bad on that one!

I didn't feel bothered, anytime 👍 

Best,
Pedro
