### ISSUE TITLE
[Bug] Datepicker invalid dates on mac os Safari browser

### ISSUE THREAD

**Issue by mobielbekeken-jan** [Laravel-Backpack/CRUD#3754]
# Bug report

### What I did

On a mac with the latest Safari browser use a date_range filter with a custom date, like today. Results are filtered correctly. Then a refresh of the page, and date show's 'invalid date' and a lot of NaN in de the datepicker.

### What I expected to happen

show the correct date and dates in the datepicker

### What happened

Date is invalid and datepicker show's NaN for all days.

### What I've already tried to fix it

ofcourse updated and tried different default code for the date_range filter but it's a browser problem i gues.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes still there
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.3.27 (cli) (built: Apr 25 2021 08:42:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v8.46.0@a18266c612e0e6aba5e0174b3c873d2d217dccfb

### BACKPACK VERSION:
4.1.47@b2325eedd661adb75c23683aa6ee1d291b3578e7

**Comment by mobielbekeken-jan** [comment]
Same thing happens on the demo website https://demo.backpackforlaravel.com/admin/dashboard
Go to 'monsters', and filter with the 'date_range' and refresh. Chrome works fine, Safari does not.

![Screenshot 2021-06-18 at 09 17 35](https://user-images.githubusercontent.com/64577444/122522396-39a67400-d016-11eb-869a-267c59777bb8.png)

**Comment by tabacitu** [comment]
Thanks for the excellent bug report @mobielbekeken-jan ! I've looked into it, you won't believe what the problem was... https://github.com/Laravel-Backpack/CRUD/pull/3756 One space 😅 Anyway... I've merged the fix into `master`, it'll be tagged and available with a `composer update` this Tuesday when we tag other things too.

Again, thanks a lot 🙏

**Comment by mobielbekeken-jan** [comment]
haha one space, unreal what an effect that can have 😆 Thank you for the fast fix, really happy with Backpack and the possibilities, keep up the good work!
