### ISSUE TITLE
[Bug] Can no longer use nested relationships in dot notation for a text column

### ISSUE THREAD

**Issue by byjl** [Laravel-Backpack/CRUD#3755]
# Bug report

### What I did

When I upgraded to 4.1, text columns that were previously set up with a nested relationship (e.g. 'model1.model2.name') now throw an exception.

### What I expected to happen

`[
    'name' => 'model1.model2.name',
    'label' => 'Name',
    'type' => 'text',
],`

I would expect the above configuration to output model2's name field in the column. 
The documentation says standard dot notation is accepted here:
https://backpackforlaravel.com/docs/4.1/crud-columns#text-1

### What happened

BadMethodCallException
Call to undefined method App\Models\Model2::model2()

### What I've already tried to fix it

I upgraded my patch version to 4.1.47
Read through the 4.1 upgrade guide to see if it mentioned changes to this
https://backpackforlaravel.com/docs/4.1/upgrade-guide

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.43.0@3ec63771a07e251f4fb6c7ef2411a79a314bba65

### BACKPACK VERSION:
4.1.47@b2325eedd661adb75c23683aa6ee1d291b3578e7

Thanks!

**Comment by tabacitu** [comment]
Hmm you're right @byjl - what you're saying _should_ be working. And it seems to be for me...

Can you please copy-paste the PHP code that isn't working for you? The `addField()` or `field()` statement?

Cheers.

**Comment by byjl** [comment]
@tabacitu Absolutely. It's neither of those functions, it's when adding the columns to the table using:

`$this->crud->addColumns([
            ['name' => 'model1.model2.name', 'label' => 'Name', 'type' => 'text'],
        ]);`

This is within the `setup()` function of my CrudController. 

For whatever reason, this tries invoking: **App\Models\Model2::model2()** which throws a **BadMethodCallException**
seemingly stemming from:
 **vendor\backpack\crud\src\app\Library\CrudPanel\Traits\Relationships.php:44**
`return $relation_model->{$related_method}();`

Thank you again for the help.

**Comment by tabacitu** [comment]
Hmm @pxpm could you please take a look? Relationships are your specialty.

**Comment by pxpm** [comment]
Hello @byjl 

Sorry for late reply and thanks for the detailed report. 

From my tests https://github.com/Laravel-Backpack/CRUD/pull/3606 is fixing this issue. 

But is not related with the line you described, that applies to fields. Can you check if that PR fixes it for you ? 

Thanks in advance,
Pedro

**Comment by byjl** [comment]
Thank you for getting back to me @pxpm.

I tried requiring "backpack/crud:dev-relationship-columns-definition" and I kept running into various dependency issues.
So I wasn't able to test the whole PR per se, but I did copy+paste these changes from `app\Library\CrudPanel\Traits\ColumnsProtectedMethods` and **it did fix the issue.**
![image](https://user-images.githubusercontent.com/22941968/124631573-8630e280-de51-11eb-8431-c825dca4c617.png)

Thanks again

**Comment by pxpm** [comment]
Thanks for the feedback @byjl and sorry for the mess up. 

I will make sure we review it properly and ping you when we merge it.

I will be closing this for now as it seems it's fixed by #3606 

Thanks for the report.

Pedro
