### ISSUE TITLE
[Bug] select_from_array field with 0 value resets if an request error

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#3761]
# Bug report
In a create/update operation if there is a select_from_array field with value 0 and if there is an error in request form validation, when return the select_from_array field is empty.
### What I did
In Monsters demo:
1 Go to MonsterCrudController.php 
2 In Select_from_array (no relationship, 1-1 or 1-n) create an option '0' => '0' and save the file.
![image](https://user-images.githubusercontent.com/8792209/122946263-9b851780-d34f-11eb-9e5a-311633e3b868.png)

3 In the panel go to Monsters entity
4 Go to Select tab an set option 0 in Select_from_array (no relationship, 1-1 or 1-n)
5 Click on Save and Back

### What I expected to happen
Show error that The Text field is required and Select_from_array (no relationship, 1-1 or 1-n) with 0 value.
![image](https://user-images.githubusercontent.com/8792209/122946428-ba83a980-d34f-11eb-8b45-807cd3041c3d.png)

### What happened

Show error that The Text field is required and Select_from_array (no relationship, 1-1 or 1-n) with no value.
![image](https://user-images.githubusercontent.com/8792209/122946614-e43cd080-d34f-11eb-82fa-d5e3d9cc05e2.png)

### What I've already tried to fix it

I think this issue is fixed modifying select_from_array blade.php

### Is it a bug in the latest version of Backpack?
Yes

**Comment by aberaldo** [comment]
Here a gif of the bug
![screenshot](https://user-images.githubusercontent.com/8792209/122947609-ab512b80-d350-11eb-92c8-0005870127ec.gif)

**Comment by pxpm** [comment]
Hello @aberaldo 

Thanks for the report and such a detailed explanation it helped alot in debugging and fixing it.

I've submitted #3816 that I think solves our problem here. 

If you have time, please give it a try and let me know the results, it could help to speedup the merging process.

Once again, thanks so much @aberaldo !

I will be closing this so we keep any discussion regarding this issue in the PR thread!

Wish you the best,
Pedro

**Comment by aberaldo** [comment]
@pxpm is working! Thanks!

**Comment by aberaldo** [comment]
@pxpm @tabacitu this also happen in select2_from_array
