### ISSUE TITLE
[Bug] Delete on preview page don't redirect to list

### ISSUE THREAD

**Issue by hanmuja-juango** [Laravel-Backpack/CRUD#3762]
# Bug report

### What I did

Delete from preview page

### What I expected to happen

Delete item and go back to list page with confirmation alert

### What happened

Confirmation delete appears and stay on preview of item deleted

### What I've already tried to fix it

I'm tried to edit the delete.blade.php file with not success

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.11 (cli) (built: Oct  6 2020 10:35:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.48.0@014443366257e4fa34071882e2b04217274a3ec9

### BACKPACK VERSION:
4.1.47@b2325eedd661adb75c23683aa6ee1d291b3578e7

**Comment by pxpm** [comment]
Hello @hanmuja-juango 

Thank you for the report. I could replicate your issue and it's indeed a nasty one. 

I've submitted #3780 that should address this issue. I am still not sure it's the best way to fix this, but it's a working one.

I am going to close this issue so we continue any discussion regarding this in the PR thread. 

Thanks again,
Pedro
