### ISSUE TITLE
[Bug] date_range floats below bottom of page, even when there is lots of space above

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#3776]
# Bug report

### What I did
Opened a ```date_range``` field a the bottom of a page

### What I expected to happen

```date_range``` field to popup on the most user-friendly side (above)

### What happened

```date_range``` field doesn't popup on the most user-friendly side (below)

### What I've already tried to fix it

Sending PR

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Thanks for raising the issue and the contributing with PR. Very appreciated. 

I will be closing this so we keep the discussion about anything related to this issue in the PR thread #3777 

🙏 @olipayne 

Pedro
