### ISSUE TITLE
afterField('license_image') not working

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#378]
$this->crud->addField([])->**afterField('license_image')**;

afterField() always adding Field on second position.

**Comment by tabacitu** [comment]
Hi @karandatwani92 ,

Took quite some time, but this is now fixed on the ```dev``` branch, and will be shortly available on the ```master``` branch, after other people get to test it.

Thanks a lot for reporting this and sorry for the long wait. 

Cheers!
