### ISSUE TITLE
[Bug] FormRequest merge data the chages not applied

### ISSUE THREAD

**Issue by lakuapik** [Laravel-Backpack/CRUD#3783]
# Bug report

### What I did

I made a custom FormRequest with prepareForValidation to change some request data

```php
// app/Http/Requests/TaskRequest.php
<?php
//...
    public function prepareForValidation()
    {
        $this->merge([
            'creator_id' => Auth::user()->id,
            'reference' => uniqid(),
        ]);
    }
//..
}


```

### What I expected to happen

When i make changes to the FormRequest data, the changes should be applied.

### What happened

When i make changes to the FormRequest data, the changes are not applied and got ignored.

### What I've already tried to fix it

Here `CreateOperation`

https://github.com/Laravel-Backpack/CRUD/blob/df9bcd2c96a5b58489aac6c2b249932e73d0c500/src/app/Http/Controllers/Operations/CreateOperation.php#L75-L80

and Here `UpdateOperation`

https://github.com/Laravel-Backpack/CRUD/blob/df9bcd2c96a5b58489aac6c2b249932e73d0c500/src/app/Http/Controllers/Operations/UpdateOperation.php#L91-L96

uses `$this->crud->validateRequest();` but in the `$this->crud->getStrippedSaveRequest()`, the request are the global request, not the FormRequest or the ValidatedRequest. turns out i can ovveride the global request with `$this->crud->setRequest()` method.

Set the request on the `CreateOperation` and `UpdateOperation` fixed the issue.

```php
//...
// execute the FormRequest authorization and validation, if one is required
$request = $this->crud->validateRequest();
$this->crud->setRequest($request);
//...
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

> Yes

but i dont know if this is a bug or the default behaviour?
if this is a bug, i would love to create a PR to fix this.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.8 (cli) (built: Jul  1 2021 16:12:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v8.49.0@855a919d08b45f93cb3cf709736528c3d1531884

### BACKPACK VERSION:
4.1.48@53bc6028f445f9b2ecfb8893283f6b6087539353

**Comment by promatik** [comment]
Hi @lakuapik, thank you for submitting this issue.

Now, backpack doesn't allow to modify the request on the Request class, probably no one has ever needed to do that, but I think it makes **total** sense.

I'm submitting a PR to fix this, #3789, let's move the conversation there 🙌
