### ISSUE TITLE
[Bug] LicenseCheck fails when you use a reverse proxy

### ISSUE THREAD

**Issue by Athuli7** [Laravel-Backpack/CRUD#3784]
# Bug report

### What I did

Run in production without a valid key

### What I expected to happen

See the alert saying it an unlicensed version.

### What happened

Nothing. No errors.

### What I've already tried to fix it

Checked the LicenseCheck trait.

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 7.4.9 (cli) (built: Aug  7 2020 19:23:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.45.1@dc2f0bb02c3eb4b27669d626bb3e810db8e7749d

### BACKPACK VERSION:
4.1.46@4bb96f8e34289b858e482ad9c9bf3ea51cb8b7c0

The issue is that the REMOTE_ADDR in my $_SERVER variable is 127.0.0.1. This is because I'm reverse proxying the application AFAIK and 127.0.0.1 is whitelisted as per line 22 of the LicenseCheck trait.

I use Cloudflare Argo Tunnels to host. This is what is reverse proxying my application.

**Comment by Athuli7** [comment]
Not sure if it is needed, but the value of $_SERVER variable is attached.
_Certain portions have been redacted and replaced with a " *** "_
[json.txt](https://github.com/Laravel-Backpack/CRUD/files/6766126/blue_label_info_json.txt)

**Comment by tabacitu** [comment]
Hey @Athuli7 - yup, it's a known issue. We just didn't do anything about it yet since it doesn't negatively affect the developers/users, only our bottom line 😅

Thanks for the report, I'll keep this open until we get the time to fix it.

Cheers!

**Comment by Athuli7** [comment]
@tabacitu, understood.

Btw why is the key not a SHA256 signature? It is slower (by my calculation it is 10 times slower) but it's all negligible. 10k executions of the current code took 39ms and 10k executions of openssl_verify with a 2048 bit key took 422ms. But these are 10K executions, a normal execution takes less than 1ms(0.0422ms by my calculation). Even if you estimate it for a resource-constrained environment like a 1vCPU VPS instance with 512MB RAM, it shouldn't cross 1ms on a reasonably modern system. And doesn't that make this a justifiable cost?

It doesn't even take 10 mins to reverse the existing solution.

**Comment by tabacitu** [comment]
> And doesn't that make this a justifiable cost?

That's the way I look at it, yes.

> It doesn't even take 10 mins to reverse the existing solution.

Yeah, you saw the comment above 😀  The truth is, the need for a license code is meant to be annoying, not uncrackable. No matter how hard you try, its source code is public, so someone someday will crack it or work around it. No use in putting that many resources into it. The idea is to nudges people into purchasing a license, instead of finding a way around it every time we push an update there.

**Comment by tabacitu** [comment]
Bam! This will be fixed in v12 (the version right after v4.2) by changing the licensing entirely 🎉 Thanks for taking the time to tell us about this @Athuli7 !
