### ISSUE TITLE
Change the way routes are registered

### ISSUE THREAD

**Issue by aaranmcguire** [Laravel-Backpack/CRUD#379]
After using soft delete and wanting to make it better I found #133 - It mentions about potentially changing the way routes are registered e.g:

```php
CRUD::routes('car', 'CarCrudController')->withTrash();
CRUD::routes('car', 'CarCrudController')->withReorder();
CRUD::routes('car', 'CarCrudController')->withRevisions();
CRUD::routes('car', 'CarCrudController')->withDetailsRow();
CRUD::routes('car', 'CarCrudController')->withTrash()->withReorder()->withRevisions();
```

This was so optional routes could be created for new features.

I've taken a look and I think the best way to do this is creating a new class (this would be created as a facade). 

Thoughts?

**Comment by tabacitu** [comment]
Completely agree. @OwenMelbz has already done that in the 3.2 branch, it's called CrudRouter. Take a look here: https://github.com/Laravel-Backpack/CRUD/blob/3.2/src/CrudRouter.php

**Comment by aaranmcguire** [comment]
Oh, never noticed that. I still think this could be improved upon as that commit only refactors the code to a new class, vs splitting out each of the route functions.

**Comment by aaranmcguire** [comment]
... If you want me to continue with this, the next thing I'm going to add is the ability for other packages to register types of routes, e.g. a package could create a `->withSoftDelete()`

**Comment by aaranmcguire** [comment]
@tabacitu What do you want me to do with this? want me to make a PR?

**Comment by lloy0076** [comment]
@tabacitu *ping*

**Comment by lloy0076** [comment]
I am on an issue closing rampage and I can't see any movement here - please reopen if it should be open.

**Comment by o15a3d4l11s2** [comment]
I just realised that we need something similar - possibility to list and "undelete" trashed items. As I see, a simple filter will enable the listing of the trashed items. But is there a ready-baked solution for the "undelete" functionality, or do we have to implement it ourselves?

**Comment by tabacitu** [comment]
Hi @o15a3d4l11s2 - no official solution yet. But implementing it yourself shouldn't be too difficult:
- a filter to list the trashed items;
- a button that only shows on trashed items, with a custom action (similar to the delete button, and the destroy functionality);

Hope it helps. Cheers!
