### ISSUE TITLE
[Bug] on official demo page

### ISSUE THREAD

**Issue by siberfx** [Laravel-Backpack/CRUD#3793]
# Bug report

### What I did

I filled with fake filler extension of chrome random Dummy data and stored it, it worked fine on saving.

### What I expected to happen

when I tried to preview data I've been just added.

### What happened

![image](https://user-images.githubusercontent.com/10257240/126326279-8c2d4dbc-d586-4018-ab41-7ae34b184f30.png)

### What I've already tried to fix it

the error is not well specified, so I dont even have any idea what was the exact reason of the error, but I think this can cause backpack users a critical issue.

### Is it a bug in the latest version of Backpack?

4.1 ( 20 July 2021 official demo page which run on your servers)

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @siberfx 

Thanks for the report, I've been able to reproduce the error. Although `editing` works fine. 

Demo is with `production` environment set, that's why the errors are not fully shown. 

I will investigate further in local dev. 

Once again, thanks!

Pedro

**Comment by pxpm** [comment]
Hey @siberfx 

Thanks again for the report! It was very helpfull with debugging! 

Just FYI it was a problem related with relationship fields that we allow to setup with only `->addField('name_of_the_relation')`, the `type` would be automagically infered but at the time we use them in dummy those scripts are not run yet. 

I've submited https://github.com/Laravel-Backpack/demo/pull/291 that would fix this. 

I will be closing this issue, if you think I missed something please reply on the PR thread or re-open this issue if you see it's needed.

Wish you the best,
Pedro
