### ISSUE TITLE
[Feature Request] CKEditor to have a validator or sanitizer for XSS Injection

### ISSUE THREAD

**Issue by raiika** [Laravel-Backpack/CRUD#3799]
# Feature Request

### What's the feature you think Backpack should have?

To validate/sanitize/purify the allowed ckeditor value/html_tags.

### Have you already implemented a prototype solution, for your own project?

For now my approach is integrating with other package such us https://github.com/mewebstudio/Purifier
and set the Purifier when setting the attribute (Model::setDesriptionAttribute())

### Do you see this as a core feature or an add-on?

Might be a core feature as applying directly to ckeditor validator field would be a good feature.

**Comment by raiika** [comment]
Just remember that Backpack validator is manually validated from Request class,
Sorry about this.

**Comment by tabacitu** [comment]
Hey @raiika - yup, exactly. At the moment, the validation is done manually by the developer, so it's up to them to purify it.

But we _could_ (or maybe _should_) think of a way to make this easier in the future, I agree...
