### ISSUE TITLE
No access to $this->crud->entry when running setupUpdateOperation ?

### ISSUE THREAD

**Issue by tonybyng** [Laravel-Backpack/CRUD#3810]
Hi

Im trying to access the selected model in the setupUpdateOperation by using the instructions referenced here

https://github.com/Laravel-Backpack/CRUD/issues/586#

i.e.

$this->crud->entry->id

except its not the id i need but another field on the record (im needing to show a different editor depending on the value of a field) but the $this->crud->entry is null at the point the setupUpdateOperation runs.

### What I did

```
        $this->crud->addField(
            ["name"=>"content",
                "label"=>"Snippet Content",
                "type" => ($this->crud->entry->snippettype==="HTML"?"wysiwyg":"textarea")
            ]
        );
```

### What I expected to happen

I expected to have access to the entry as per #586.   If I remove the reference to the existing entry and leave it as a textarea it all works. A dd() shows $this->crud->entry is null at the time the setupUpdateOperation runs. Has this functionality changed since April 2017 or have I misunderstood ?

Thanks

### PHP VERSION:
PHP 8.0.5 (cli) (built: May  3 2021 11:30:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.52.0@8fe9877d52e25f8aed36c51734e5a8510be967e6

### BACKPACK VERSION:
4.1.50@09cf360f2c1d1ad40d054c6c36e16c3c44f2e461

**Comment by tabacitu** [comment]
It's possible at the time of `setupUpdateOperation()` that is not set up yet, indeed. 
Can you try `$this->crud->getEntry()` or `$this->crud->getCurrentEntry()`?

**Comment by tonybyng** [comment]
@tabacitu getCurrentEntry() worked - many thanks for the fast response.
