### ISSUE TITLE
TinyMCE html image links are Elfinder protected url when uploading to Amazon S3 Server on local 

### ISSUE THREAD

**Issue by gillesboisson** [Laravel-Backpack/CRUD#3814]
# Bug report

### What I did 

I upload an image using elfinder and add to a richtinymce field content. In my case I use a S3 Server as storage

### What's expected

The link to my image working even if I'm disconnected

### What I have

Image link seems to not working when I'm off and is in elfinder protected link format

### What I've already tried to fix it

Un protect the route but

### Is it a bug in the latest version of Backpack?

Issue is similar has been created and closed
https://github.com/Laravel-Backpack/CRUD/issues/871

In my case only S3 storage seems to be different from old issue case.

### Backpack, Laravel, PHP, DB version

DB postgres 13
PHP 8.0.7

- Laravel/framework : 8.54.0
- backpack/crud : 4.1.50
- backpack/filemanager : 1.1.5

**Comment by pxpm** [comment]
@gillesboisson So you fixed it by using `s3` as the disk inside elfinder configuration, but you need to specify the URL there and not on `filesystem` config file ? 

If that is the case it may be worth to add that note to the Docs, I am pretty sure alot of people use s3 and may have already struggled with that. 

Let me know,
Pedro

**Comment by tabacitu** [comment]
@gillesboisson , thanks for posting your solution 🙏   I'm sure someone someday will stumble upon it and be grateful.

> If that is the case it may be worth to add that note to the Docs, I am pretty sure alot of people use s3 and may have already struggled with that.

I'm inclined to say that in this case it's just the way S3 needs to be configured in Laravel. I think it would be overkill for us to add docs on how to properly do something that's not Backpack-specific. I'm going to change the title of this issue though, to be more specific, so people who search for this can easily find it.

Thanks again for this @gillesboisson 
Cheers!
