### ISSUE TITLE
[Feature Request] Show AJAX errors in bubble notifications

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/CRUD#3830]
# Feature Request

### What's the feature you think Backpack should have?

Better error messages on CRUD table ajax errors.
As we did on DevTools, it could be done for the list view. Developers may open the Network panel and there are full details of the error, but, we could also give a preview of it.

Note, this would work on **local environment** only.

Should we?

![image](https://user-images.githubusercontent.com/1838187/133005249-b0731c1f-2b29-43a7-ac8a-bfe8bb9c3a4c.png)

### Have you already implemented a prototype solution, for your own project?

This was done on DevTools, and it works 🤷‍♂️

**Comment by tabacitu** [comment]
I think we definitely SHOULD do this. But go a step further than what we did in DevTools and show the entire error stack, in a modal. That should be possible right?

My reasoning for this is this:
- show general error message - tells you that _something_ went wrong; no idea what;
- show final error message - tells you _what_ went wrong in 80% use cases;
- show full error stack - tells your _what_ went wrong in 99% use cases;

Showing the full error stack in a modal would basically render the Network tab useless when dealing with AJAX errors in Backpack, which I think could be a huge developer experience improvement.

**Comment by promatik** [comment]
Yes, it should be possible, and I agree 👌

But I also think we shouldn't be reinventing the wheel 😅 it would be nice to use the default Laravel error page, maybe inside an iframe, exactly like Livewire does...

**Comment by promatik** [comment]
Since both are in the same project, let's move conversation about this to; #3836
