### ISSUE TITLE
[Bug] Column heading positioning is broken after toggling the sidebar

### ISSUE THREAD

**Issue by Cocker** [Laravel-Backpack/CRUD#3833]
# Bug report

### What I did

Opened the table with 25 results per page on a Full HD (1920x1080) resolution. Closed the sidebar and scrolled down until column headings positioning changed.

### What I expected to happen

Column headings correspond to the values in the table.

### What happened

Column headings are shifted to the right and therefore do not correspond to the rest of the table. 

![Screenshot from 2021-09-16 14-57-592](https://user-images.githubusercontent.com/3314103/133608973-d7c5f4cb-d3ca-4335-b7a1-55f91730b5f4.png)

### What I've already tried to fix it

I tried updating Backpack and publishing assets using command ```php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force```. I figured out the shift came from the sidebar, so it assumes that the sidebar is still open. Therefore there is a vice versa situation when the page is being loaded with sidebar closed and then sidebar being opened (the shift would be to the left as when the sidebar is closed).

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug is still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.1 (cli) (built: Jan 13 2021 07:32:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.60.0@44f16a31a1d4ac8a51605550d7796e2273984a48

### BACKPACK VERSION:
4.1.53@8698b8ed51e8b18e311f928f6f80a7161f1eb172

**Comment by pxpm** [comment]
Hello @Cocker ! Sorry for taking time to get to this, and thank you very much for the report. 

I could reproduce your issue, I will try to find a fix for it in the meanwhile!

Thanks,
Pedro

**Comment by pxpm** [comment]
Hey @Cocker ! I took a bit but I was able to find what was causing it. 

I think i've fixed it in #3846 ! If you want to add that code in your project to check if it fixes the problem for you, give us your feedback in the PR thread I mentioned. 

I am closing this so we keep any discussion in this regard in the open PR #3846 

Thanks for the report, I haven't noticed it yet!

Best,
Pedro
