### ISSUE TITLE
[Feature Request]  update Readonly text filed onchange  relationship  filed 

### ISSUE THREAD

**Issue by egyjs** [Laravel-Backpack/CRUD#3839]
# Feature Request
![image](https://user-images.githubusercontent.com/12745270/134369411-697d486c-e071-4fd3-9d79-17e77faac363.png)

### What's the feature you think Backpack should have?
`onchange` method that update certain fields and get values from the selected model

### Have you already implemented a prototype solution, for your own project?

??

### Do you see this as a core feature or an add-on?

core

**Comment by pxpm** [comment]
Hello @egyjs !

At the moment is only possible if you override the files in your project. 

I think this is a good idea, but I haven't think of a "global" solution yet, but I find myself needing it sometimes and I endup creating a custom field and adding the functionality needed. 

I am going to move this to 4.2 as I think this is a good idea, but it really needs some thinkering before having this as a core feature.

If in the meanwhile you find a solution that you think can be generalized to use in backpack, please share with us, it could help us to develop a core solution for this. 

Wish you the best,
Pedro

**Comment by tabacitu** [comment]
Hey @egyjs 

I don't think there's a clean way to achieve this at the moment, only with a custom field type. 

In the future (v12), you will be able to easily do this, by turning the form into a LiveWire component. Not as a direct feature, but as an indirect feature, how Livewire works. Until then, I'm going to close the issue, as it's not something we plan on supporting.

Cheers!
