### ISSUE TITLE
entry not available in edit form 

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#384]
Hi 
after update the package to 3.1 , $this->entry   not available in edit form . 
what is the problem ?

**Comment by OwenMelbz** [comment]
tried `$entry`?

**Comment by M0H3N** [comment]
yes ... not work

**Comment by OwenMelbz** [comment]
Can you please post some more code and describe the issue a little more then.

e.g Where are you trying this? in a template? if so which template? in a controller? in a model? in a bacon sandwich?

**Comment by M0H3N** [comment]
before version 3.1  $this->entry   in CrudController   return the entry  (actually when we  are in edit  form) 
but after update the package $this->package not available in crudcontroller  . when I want to use it , this error happens : 
`Undefined property: App\Http\Controllers\Admin\PostCrudController::$entry`

**Comment by OwenMelbz** [comment]
Sorry we still need to see code, cannot guess blind.

If you were to look inside `vendor/backpack/crud/src/app/Http/Controllers/CrudController.php`

You would see something like

```
public function edit($id)
    {
        $this->crud->hasAccessOrFail('update');

        // get the info for that entry
        $this->data['entry'] = $this->crud->getEntry($id);
        $this->data['crud'] = $this->crud;
        $this->data['saveAction'] = $this->getSaveAction();
        $this->data['fields'] = $this->crud->getUpdateFields($id);
        $this->data['title'] = trans('backpack::crud.edit').' '.$this->crud->entity_name;

        $this->data['id'] = $id;

        return view('crud::edit', $this->data);
    }
```

As you can see it does `$this->data['entry']` and passes it to the crud edit template - which will convert into `$entry`

If you have changed your `edit()` methods and/or templates and are no longer passing all the expected information to the templates, then it wont be able to see it.

I would recommend to never touch the `edit()` `create()` or other core functions as it makes it harder to maintain. Try find alternative ways to achieving things to keep better maintainability.
