### ISSUE TITLE
[Bug] Any button on the form triggers a save action

### ISSUE THREAD

**Issue by MeerKatDev** [Laravel-Backpack/CRUD#3848]
# Bug report

### What I did

I added a button to a CRUD edit form

### What I expected to happen

the button to work by itself, to start some javascript action

### What happened

the button triggers a save action

### What I've already tried to fix it

stopImmediatePropagation/return false

### Is it a bug in the latest version of Backpack? yes

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

the last version

**Comment by pxpm** [comment]
Hey @MeerKatDev 

Any button inside the form, if you don't specify `type="button"` will be assumed to be a submit button. 

That's general web rules, not backpack ones. I am pretty sure that you are missing that bit. https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element

Let me know,
Pedro

**Comment by MeerKatDev** [comment]
didn't know that - thanks!
