### ISSUE TITLE
DateTime Picker error when date deleted after being set

### ISSUE THREAD

**Issue by splodgeco** [Laravel-Backpack/CRUD#386]
Hello

In the datetime_picker view, there is a bug when the datetime is updated to a blank value i.e. Manually delete the date. I suggest a simple fix which I have implemented in my resource view.

From 
Line 75 in crud/fields/datetime_picker.blade.php 
```
$picker.on('dp.change', function(e){
    var sqlDate = e.date.format('YYYY-MM-DD HH:mm:ss');
    $field.val(sqlDate);
});
```

To
```
$picker.on('dp.change', function(e){
    var sqlDate = e.date ? e.date.format('YYYY-MM-DD HH:mm:ss') : null;
    $field.val(sqlDate);
});
```

**Comment by tabacitu** [comment]
Hi @splodgeco ,

Thanks for telling us. It's now fixed and it will be available in the next point update (3.1.58).

Cheers!
