### ISSUE TITLE
[Bug] Text columns with nested relationships 

### ISSUE THREAD

**Issue by axelzuzek** [Laravel-Backpack/CRUD#3877]
# Bug report

### What I did

Upgrading backpack/crud (4.1.9 => 4.1.55)
Text columns that were previously set up with a nested relationship (e.g. 'model1.model2.name') now throw an exception.

### What I expected to happen

Model Invoice
public function owner()
{
    return $this->belongsTo('App\Models\User', 'owner_id', 'id');
}
...
$this->crud->setColumns([
    ['name' => 'owner.firstname', 'label' => 'Firstname'],

Output of invoice.owner.firstname in column

### What happened

Exception: Call to undefined method App\\Models\\User::firstname() (View: C:\\dev\\projectname\\vendor\\backpack\\crud\\src\\resources\\views\\crud\\columns\\select.blade.php)

### Is it a bug in the latest version of Backpack?
Yes 4.1.55

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version
MySQL 8.0.20

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.6 (cli) (built: May 12 2020 11:38:54) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.55@ecb05f5cb18176faca41116144e82875098488b5

**Comment by pxpm** [comment]
Hello @axelzuzek !

Thanks for the report. It's something that we are aware of in #3755 and the PR to fix it: #3606 

Problem was that I tried to fix the problem and ended up with a BC that could only be merged in 4.2, at that time I could not figure out other way to do it. 

I today aproached the problem from other perspective and I think I've solved it in a non-breaking way. 

Please see updated pr #3606 . If you could give it a try and give your feedback it would help alot. 

I am going to close this so we don't have the same conversation in multiple places. 

Anything, please add in the PR thread 👍 

Best,
Pedro
