### ISSUE TITLE
Overide Edit View

### ISSUE THREAD

**Issue by CHOMNANP** [Laravel-Backpack/CRUD#388]
I'm looking to overide edit view for the CRUD.

My objective is to not redirect page to "List" after pressing save button on "Edit CRUD".

Thanks.

**Comment by OwenMelbz** [comment]
If you can wait until version 3.2 is released, the buttons will change.

**Comment by tabacitu** [comment]
Laravel 5.4 is out, Backpack\CRUD 3.2 should be out in a few days - waiting for some more of the dependencies to be compatible with L5.4 too.

Until then, you can achieve this by overwriting the store() and update() methods in your CrudControllers.

Hope it helps.

Cheers!
