### ISSUE TITLE
[Bug] Datetime picker translation

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#3887]
# Bug report

I have a detetime picker created in spanish but there are other strings that are not translated at all. Like Select time

![image](https://user-images.githubusercontent.com/8792209/138106755-8a2c7121-193b-4c22-be96-69a016b32847.png)

### What I expected to happen

Sting "Select time" in spanish

### What happened

??

### What I've already tried to fix it

![image](https://user-images.githubusercontent.com/8792209/138107379-63ad3420-5b29-4efe-81e6-1277fd1f5bde.png)

### Is it a bug in the latest version of Backpack?

yes

**Comment by pxpm** [comment]
@aberaldo does setting up `language => 'es'` solved the problem or the string is not translated to spanish when you set it ? 

What is your `\App::getLocale();` output ?

Best,
Pedro

**Comment by aberaldo** [comment]
Hello Pedro. Thanks for the response. the setting `language => 'es'` does not resolve the problem.

`\App::getLocale() `output is 'es'

Any suggestions?
Andrés
