### ISSUE TITLE
[Bug] select2_multiple fields allows selection of empty option "-"

### ISSUE THREAD

**Issue by WrdVdb** [Laravel-Backpack/CRUD#3898]
# Bug report

### What I did

Add a select2_multiple field

$this->crud->addField([
            'label' => "Contact types",
            'type' => 'select2_multiple',
            'name' => 'contactTypes',
            'entity' => 'contactTypes',
            'attribute' => 'Title',
            'model' => "App\Models\ContactType",
            'pivot' => true,
        ]);

### What happened

The element works fine, but adds a <option>-</option> to the element, which is selectable.

![image](https://user-images.githubusercontent.com/36230484/138659126-9807129f-6e58-48d9-b089-9e2d98ebcd74.png)

### What I've already tried to fix it

Adding 'allows_null' => false fixes the problem.
But this seems a behaviour that should not be possible even when this is not added.

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 7.4.21 (cli) (built: Jul  1 2021 16:09:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.4@9dd38140dc2924daa1a020a3d7a45f9ceff03df3

### BACKPACK VERSION:
4.1.56@13157e650fb0557eaad8e31b40b3963aeccf8d1d

**Comment by promatik** [comment]
Hi @WrdVdb.
Thank you so much for your report!

There is already an open issue regarding this; #3312.

We realized it's a breaking change so it's scheduled for the new v4.2, gladly, we are already working on it 🙌
Please follow #3312 for updates on this, or [subscribe the newsletter](https://backpackforlaravel.com/newsletter) for updates on v4.2 🙌
