### ISSUE TITLE
CRUD Break for Big Tables, Add Datatables Ajax server-side processing

### ISSUE THREAD

**Issue by zomax** [Laravel-Backpack/CRUD#390]
When to add Datatables server-side processing?
Right now all rows are queried even for ajax tables.

It's awesome CRUD but unfortunately it's unuseful for tables with thousands of rows.

Is this considered soon?
Thank You.

**Comment by MDEvo** [comment]
Read here: https://laravel-backpack.readme.io/docs/crud-full-api

Enable this on your controller
> $this->crud->enableAjaxTable();

**Comment by zomax** [comment]
Thanks @MDEvo 
Enabling ajax here means load all data after page loading. and that's break the CRUD for big tables (with >50 thousand record for example).

With big table without using Ajax page give Error 500!
With enabling Ajax Datatables give this massege
![untitled](https://cloud.githubusercontent.com/assets/17072336/22316542/7aa69886-e376-11e6-8f00-065792de7aed.jpg)

**Comment by tabacitu** [comment]
Hi there! The CRUD is regularly tested with a table with millions of rows, so it shouls work fine with thousants. 

Have you defines your primary key in the model? That should fix it for you.

**Comment by zomax** [comment]
Thanks @MDEvo . It's fixed now
