### ISSUE TITLE
Editable image with crop field 

### ISSUE THREAD

**Issue by Nks** [Laravel-Backpack/CRUD#391]
If you will have `image` field with crop in your form and want to add an image - all works fine. But if you want to edit existing image with crop ability - it's not works fine.
I found a solution but I'm not sure that this is correct solution. What do you think?

1st we need create accessor for image to get it from the storage:
```
public function getMediaAttribute($value)
    {
        if (\Storage::disk($this->disk)->exists($value)) {
            return preg_replace('#/+#', '/', \Storage::disk($this->disk)->url($value));
        }

        return null;
    }
```

After that you need add some items into `/views/vendor/backpack/crud/fields/image.blade.php` template. Find 

```
 if(crop){
                        $remove.click(function() {
```
and add somewhere in before `} else {` this code:

```
                        if($mainImage.attr('src') != ''){
                            $mainImage.cropper(options);
                            $rotateLeft.click(function() {
                                $mainImage.cropper("rotate", 90);
                            });
                            $rotateRight.click(function() {
                                $mainImage.cropper("rotate", -90);
                            });
                            $zoomIn.click(function() {
                                $mainImage.cropper("zoom", 0.1);
                            });
                            $zoomOut.click(function() {
                                $mainImage.cropper("zoom", -0.1);
                            });
                            $reset.click(function() {
                                $mainImage.cropper("reset");
                            });
                            $rotateLeft.show();
                            $rotateRight.show();
                            $zoomIn.show();
                            $zoomOut.show();
                            $reset.show();
                            $remove.show();
                       
```

Also is the best solution - move it to the function because this code already used.

Also if you want that the crop data send correct you need find and move this elsewhere in the `$('.form-group.image').each(function(index){` loop because if you will not do this crop data will not send to the controller:
```
$('form').submit(function() {
                        var imageURL = $mainImage.cropper('getCroppedCanvas').toDataURL();
                        $hiddenImage.val(imageURL);
                        return true; // return false to cancel form action
                    });
```

What do you think? Maybe create PR with this fix?

**Comment by lloy0076** [comment]
A PR or a gist of the differences to easily patch may make it easier to reproduce?

What do you mean by "an existing image" - do you mean an image that has already been uploaded and saved (such that you might be using an `update` form to edit it)?

**Comment by lloy0076** [comment]
Please reopen if:

* the bug is still valid; and/or
* a PR becomes available.
