### ISSUE TITLE
`pivotFields` functionality broken

### ISSUE THREAD

**Issue by dabernathy89** [Laravel-Backpack/CRUD#393]
So I saw that there is an undocumented feature for adding additional data to pivot columns here:

https://github.com/Laravel-Backpack/CRUD/blob/57666443a1c4db57a76470d0876dac9cbab6ced9/src/PanelTraits/Create.php#L86-L92

    if (isset($field['pivotFields'])) {
        foreach ($field['pivotFields'] as $pivotField) {
            foreach ($data[$pivotField] as $pivot_id =>  $field) {
                $model->{$field['name']}()->updateExistingPivot($pivot_id, [$pivotField => $field]);
            }
        }
    }

Looks like the reason for this is that you're referencing `$field['name']` on line 89, even though the `$field` variable has been overwritten inside of the current (nested) `foreach`.

**Comment by hewok** [comment]
Hi, I have the same problem.
I had to change the Trait:
`foreach ($data[$pivotField] as $pivot_id =>  $pivot_field) {
      $model->{$field['name']}()->updateExistingPivot($pivot_id, [$pivotField => $pivot_field]);
}`

@tabacitu what do you think about it?

Thanks

**Comment by lloy0076** [comment]
Is there a PR for this?

**Comment by tabacitu** [comment]
Hi guys. I think it's good feature, yes.

@hewok - what exactly is the change? They look the same to me...
@tumf87 - am I wrong or is this feature rendered obsolete by this PR?

Cheers!

**Comment by tabacitu** [comment]
Fixed on dev. Thank you @hewok for the PR! Cheers!
