### ISSUE TITLE
[Bug] Edit title and headline should put the entity name inside of the translation

### ISSUE THREAD

**Issue by kolaente** [Laravel-Backpack/CRUD#3931]
# Bug report

The default edit title and headline currently use the translation and put the entity name after it, concatenating both together. This might work well in English, it does not work well in German (and I'm sure there's other languages where this doesn't work great either). Precisely for use cases like this, Laravel has support for [parameters in translation keys](https://laravel.com/docs/8.x/localization#replacing-parameters-in-translation-strings), allowing translations to move the entity name where it makes sense for the language.

Relevant code parts are [here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/edit.blade.php#L18) and [here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/Operations/UpdateOperation.php#L73).

### What I did

Set the application language to german

### What I expected to happen

Correct translation

### What happened

Wrong translation

### Is it a bug in the latest version of Backpack?

Yes

##### PHP VERSION:
PHP 7.4.24 (cli) (built: Sep 23 2021 21:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies
    with blackfire v1.69.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire

##### LARAVEL VERSION:
v8.69.0@545181da688db64fed6d8427e55f630a90ca0d32

##### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee

**Comment by kolaente** [comment]
I also noticed that for "create" buttons and headline.

**Comment by tabacitu** [comment]
Got it, thank you @kolaente ! I've added the issue to 4.2.x project - we're now super focused on finishing a few MUST-DOs, to get 4.2 launched at the end of November.

Thanks again!

**Comment by pxpm** [comment]
Doing a cleanup of old issues. 

I don't think there is any issue here as we provide a sensible default, but users can configure it using the headings and title methods: https://backpackforlaravel.com/docs/6.x/crud-operations#titles-headings-and-subheadings

Let me know if that does not work for you and we can re-open if needed.

Cheers
