### ISSUE TITLE
[Bug] When remove "Reset button" in the list, you should avoid appending the trailing comma

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#3934]
# Bug report

### Prologue

It's a very small little stupid thing.... sorry..

### What I did

In `config/backpack/crud.php` we disabled the reset button

`'resetButton' => false,
`
### What I expected to happen

We expected that the trailing comma after list operation subheading will be removed

### What happened

It shows a trailing comma

![image](https://user-images.githubusercontent.com/1268699/141464842-45cfaec0-814d-4c84-aa56-48bfe0656ecd.png)

### What I've already tried to fix it

I searched around in the code where the js is appending the string but not found, yet.

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.25 (cli) (built: Oct 20 2021 09:29:27) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.70.2@dec9524cd0f9fa35a6eb8e25d0b40f8bbc8ec225

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee
```

**Comment by pxpm** [comment]
Hey @realtebo 

Sorry for late reply, I totally missed this issue. 

I was not able to see where that comma is comming from, I guess is something specific to your application ? Something you overrided ? 

I get a `dot`, automatically added by datatables that ends the sentence and I think it's correct:

![image](https://user-images.githubusercontent.com/7188159/142855760-88649943-bb96-4dd5-afeb-627465f73b58.png)

In the `crud.php` lang file you have the strings:

```php
'info'           => 'Showing _START_ to _END_ of _TOTAL_ entries',
    'infoEmpty'      => 'No entries',
    'infoFiltered'   => '(filtered from _MAX_ total entries)',
```
Let me know what you've found. 

### LARAVEL VERSION:
v8.73.1@36dfae9d9ef7f88e8f9489c484a0a0609592bc21

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee

Pedro

**Comment by realtebo** [comment]
I've no more the problem with last version. Probably already fixed? 
I close. 
If this rehappen, I'll rewrite. 
But we didn't any modifications to language files or to template about this specific magic comma :)

**Comment by realtebo** [comment]
Actually, having locale set to italian, in a fresh backpack project (so all at latest version (4.1, not 4.2-dev) the issue is come again

![image](https://user-images.githubusercontent.com/1268699/149953971-f507f46f-4b82-49b1-a509-1e95ead9d4bd.png)

But this time  I take time to understand where/what/when

The trailing comma is here

    vendor/backpack/crud/src/resources/lang/it/crud.php

    'infoPostFix'    => ',',  

Used in DataTable Library here

    vendor/backpack/crud/src/public/packages/datatables.net/js/jquery.dataTables.js

    #4737   out += lang.sInfoPostFix;

Used by packpack here:

    vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php

around line 217, when setting `language.infoPostFx`

**Comment by realtebo** [comment]
Easy workaround:

Create `resources/lang/vendor/backpack/it/crud.php` and add only this

```
<?php


return [

    // Override per togliere la virgola finale
    'infoPostFix'    => '',

];
```

**Comment by realtebo** [comment]
@pxpm , no problem. We actually have all italian-only projects so we have a workaround and all works for us.

**Comment by realtebo** [comment]
Thanks !
Suggestion for small improvement.
Introduce 2 postfix, a command and a dot, fix for each language.
If after first phrase there is a second, then add a comma, if not add a dot.

Anyway, both workaround and this fixes this small problems

**Comment by pxpm** [comment]
Hey @realtebo I think even with the second phrase the `.` (dot) is well placed and the sentence still make sense. 

I think adding both would be over-optimizing, time will tell us 🙏 

Cheers

**Comment by realtebo** [comment]
Yes yes, yes. I am already happy for this change :)
