### ISSUE TITLE
[Bug] We cannot remove 'saved_and_edit' actions

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#3937]
# Bug report

### What I did

In `setupCreateOperation` I need to remove ALL actions to add a new one for a specific single case.

I added the following code, to remove all 3 default asciont 

```
        $this->crud->removeSaveActions([
            'save_and_back', 'save_and_edit', 'save_and_new'
        ]);

        $this->crud->addSaveAction(
            [
                'name' => 'save_and_show',
                'visible' => function ($crud) {
                    return $crud->hasAccess('show');
                },
                'redirect' => function ($crud, $request, $itemId = null) {
                    $itemId = $itemId ?: $request->input('id');
                    $redirectUrl = $crud->route.'/'.$itemId.'/show';
                    if ($request->has('locale')) {
                        $redirectUrl .= '?locale='.$request->input('locale');
                    }
                    if ($request->has('current_tab')) {
                        $redirectUrl = $redirectUrl.'#'.$request->get('current_tab');
                    }

                    return $redirectUrl;
                },
                'referrer_url' => function ($crud, $request, $itemId) {
                    return url($crud->route.'/'.$itemId.'/create');
                },
                'button_text' => 'Salva e torna a questo elemento',
            ],
        );

```
### What I expected to happen

I expected save button to have only one kind of save, with no dropdown at all, and I expectred that 'save_and_edit' action was no more presente

### What happened
![image](https://user-images.githubusercontent.com/1268699/141762563-7881303b-8515-4d0f-8c84-5e0b964316c9.png)

Actually backpack added my custom save action, removed all default save action, except for 'save_and_edit'; this save action is still visible

### What I've already tried to fix it

Actually nothing

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
λ php artisan backpack:version
### PHP VERSION:
PHP 7.4.25 (cli) (built: Oct 20 2021 09:29:27) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.70.2@dec9524cd0f9fa35a6eb8e25d0b40f8bbc8ec225

### BACKPACK VERSION:
4.1.60@bec5cfa11f0cd0712c79256748acf5850080c0ee

```

**Comment by realtebo** [comment]
My fault, ignore this issue

But there is 'little missing thing'. We should avoid to se this option as new default

**Comment by promatik** [comment]
Hi @realtebo!

Regarding the order, you are able to setup the order of the Save actions by calling `orderSaveAction`.
In your case, this should do;

```php
$this->crud->orderSaveAction('save_and_preview', 1);
```

![image](https://user-images.githubusercontent.com/1838187/142787386-6bbc91c5-800e-49d6-88b0-3a515ca7da9e.png)

I'll close this one for now, let me know if it helps.
