### ISSUE TITLE
[Bug] Cant translate date filter

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#3938]
# Bug report
There is no way for translating date filter apart from overriding date.blade.php filter file
### What I did

Date filter always shows in English

### What I expected to happen

Date filter shows in some other language

### What happened

??

### What I've already tried to fix it

I fixed it overriding date.blade.php 
![image](https://user-images.githubusercontent.com/8792209/141785033-56b3d4ef-6c4c-4240-a76e-9ee7f371e298.png)

### Is it a bug in the latest version of Backpack?
Yes

**Comment by aberaldo** [comment]
It should be a more friendly way to translate the filter. Like passing language in the addFilter:

```
$this->crud->addFilter([
            'type'  => 'date',
            'name'  => 'start_date',
            'label' => trans('crud.logisticReservation.start_date'),
            'language'  => 'es',
        ],
        false,
        function ($value) {
            $this->crud->addClause('where', 'start_date', '>=', $value);
        });
```

**Comment by promatik** [comment]
Hi @aberaldo!

Thank you for your report, indeed this was an issue, this specific field could not be translated. I have just submitted a PR to fix it.

By the way, once this is merged, you don't even need to specify the language, it will be automatically assigned with the Laravel locale.

@aberaldo if you have the time, feel free to test if my PR fixes your issue ✌
Let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/3949
