### ISSUE TITLE
[4.2][Bug] Invisible first column is too wide

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3939]
# Bug report

### What I did

Played around in the 4.2 branch (after having published the new assets, but I think it happens without that too). Inside the ListOperation of CRUDs with just a few columns, where there is plenty of space, the first column (the invisible one we introduced) is waaay to wide:

### What I expected to happen

Look like v4.1:

<img width="1440" alt="Screenshot 2021-11-17 at 14 49 55" src="https://user-images.githubusercontent.com/1032474/142203770-5d6484c7-a0b9-4651-9ade-344b8a6bc43b.png">

### What happened

Looks like this in v4.2:

<img width="1440" alt="Screenshot 2021-11-17 at 14 50 04" src="https://user-images.githubusercontent.com/1032474/142203810-f5f0f9c1-3b2f-4d8d-a3d8-b62e73cf9ddb.png">

### What I've already tried to fix it

Nada 👀😅

**Comment by promatik** [comment]
https://github.com/DigitallyHappy/BackStrap/pull/100

**Comment by promatik** [comment]
@tabacitu I think we can close this one, since we now have https://github.com/Laravel-Backpack/CRUD/pull/3331. Please re-open if I am mistaken ✌
