### ISSUE TITLE
[Bug] Repeatable inside InlineCreate with same name as other repeatable already on page

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#3946]
# Bug report

### What I did

Added an `InlineCreate` that **has a repeatable field inside the modal** with the **same name** of one repeatable in the parent form.

### What I expected to happen

Repeatable in InlineCreate to show the repeatable fields of the connected entity.

### What happened

InlineCreate repeatable gets the "container" from the parent repeatable (they have the same name).

### What I've already tried to fix it

Nothing at all, just noticed, it's a very edgy case, but probably add something to the docs about it?

### Is it a bug in the latest version of Backpack?

sure it is.

**Comment by tabacitu** [comment]
Aaahhh! Does it happen in v4.2 too?

**Comment by pxpm** [comment]
Ahh sorry @tabacitu I should have tagged it. 

I only tested this in 4.2 while working on other stuff not related to this. I haven't tried this yet in 4.1.

**Comment by tabacitu** [comment]
@pxpm , just talked to @jorgetwgroup who's already created a PR for this, but hasn't submitted it. Please don't work on this until you talk with him, or he submits the PR. Let's not have two people working on the same PR.
