### ISSUE TITLE
Finish the `repeatable` field

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3953]
Gatherin here all we should do to consider the `repeatable` field _done_, so that we no longer need to take a look at https://github.com/Laravel-Backpack/CRUD/pull/2266 or https://github.com/Laravel-Backpack/CRUD/pull/3905 . After all of these are done, I think we can _truly_ consider this field _done_, and never touch it again 😅 (yeah right).

## MUST

Nada.

## SHOULD

Interface:
- [ ] click on the PLUS button should move the cursor to the first field in the new group (probably using the existing focusOnFirstField functionality)

Support:
- [ ] make `upload` field work inside `repeatable` - see https://github.com/Laravel-Backpack/CRUD/pull/3951
- [ ] make `upload_multiple` field work inside `repeatable`
- [ ] make `image` field work inside `repeatable` - see https://github.com/Laravel-Backpack/CRUD/pull/3948 and https://github.com/Laravel-Backpack/CRUD/pull/3928 and [example here](https://github.com/Laravel-Backpack/CRUD/pull/3905#issuecomment-974270979)
- [ ] make `checklist_dependency` field work inside `repeatable` - see https://github.com/Laravel-Backpack/CRUD/issues/2735
- [ ] make `page_or_link` field work inside `repeatable`

## COULD

Document the following advanced use cases (with examples):
- [ ] intercept the field in the controller, and store the values in a different way (something other than JSON in the db)
- [ ] intercept the field in the model (using a mutator and accessor) and store the values in a different way (something other than JSON in the db)

## WON'T

- [ ] ~~make `enum` field work inside `repeatable`~~ - doesn't make sense inside it;

**Comment by manfield** [comment]
Please update documentation

![image](https://github.com/user-attachments/assets/d416f9fc-b6e6-4cf5-a9a6-330738a09a88)
