### ISSUE TITLE
[Feature Request] PHP 8.1 support

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#3961]
It's out, so we need to provide official support for it.

In Backpack 4.1, ideally.

**Comment by promatik** [comment]
I tested Demo with PHP 8.1, and everything worked great 👌

**Comment by tabacitu** [comment]
I've created PR https://github.com/Laravel-Backpack/CRUD/pull/4022 which needs to be merged to "officially" support PHP 8.1.
