### ISSUE TITLE
Nested resources problem

### ISSUE THREAD

**Issue by lejubila** [Laravel-Backpack/CRUD#398]
Hallo,
I've following [this](https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud) tutorial for create a crud resources nested, but i encountered several problems.
The creation function is working properly but the cancellation and modification don't  work and they go in error.
After some research I found this:
as documented [here](https://laravel.com/docs/5.1/controllers#restful-nested-resources), laravel call the controller methods "edit" and "destroy"  with a number of variable parameters depending on how many resources are nested.
For example, in my case i've nested two resourses, then laravel calls the method's controller "edit" with two parameters: the "id" of the first resource and "id" of the second resource.
In the CrudController the signatures of methods "edit" and "destroy" have only one parameter. This cause the error in my case.
To solve the problem I have overloaded the "edit" and "destroy" the methods as follows, and I have to get the second missing parameter with "args" function

> public function edit($imagegallery_id)
{
	$args = func_get_args();
	$id = $args[1];
	$view = parent::edit($id);
	if($this->data['entry'] && $imagegallery_id != $this->data['entry']->imagegallery_id){
	    abort(403, 'Wrong imagegallery_id '.$imagegallery_id);
	}
	return $view;
}

> public function destroy($imagegallery_id)
{
	$args = func_get_args();
	$id = $args[1];
	return parent::destroy($id);
}

Get the second parameter with "get" function is really bad. 

You know you suggest a better way to implement nested resources with CRUD ?

**Comment by pavoltanuska** [comment]
Hi @lejubila ! Did you already solve this somehow?

If not, could you provide us with more details, so we can help you here? As for me, I'm not sure I understand your issue correctly.

What are your "parent" and "child" resources/models? Image and ImageGallery?

And the biggest question, do you *really* need to access the resources as nested ones? Each of your resources should have it's own ID, so you should be able to edit/destroy them directly, there should be no need to access them as "nested resources".

But of course, it totally depends on your use case, I may be wrong here.

More info would be definitely helpful here, so we can try to solve your issue.

**Comment by dereksdev** [comment]
@pavoltanuska I am having a similar issue. I have created nested resources and I access them via /parentResource/parentID/childResource. Therefore, when calling the destroy method from the delete button, the ID which is passed to the childResourceController destroy method is the parentID, where it should be the childID.

I've currently worked around this by overriding the destroy method to grab the id from the request URL, but this is certainly not the ideal solution.

```
// in childResourceController...
public function destroy($id)
{
	$id = basename(\Request::url());

	return parent::destroy($id);
}
```

**Comment by pavoltanuska** [comment]
@dereksdev I'd say your approach is completely valid, although I'd do it a little bit different:

```
public function edit($parent_id, $id = null)
{
    return parent::edit($id);
}
```
And the same for `destroy()` method.

If you'd add next level of nesting, you'd just add one more parameter, e.g. 
`edit($grandparent_id, $parent_id = null, $id = null)`

Basically, don't forget the default `null` value(s), to stay compatible with the parent method definition and you should be all set.

You can/should also do some sort of checking for whether the `$id` is really a child of `$parent_id`, but it all depends on your use case. (But I'd advise you to do that, because we don't generally trust our users, do we :) )
