### ISSUE TITLE
page templates with images fields

### ISSUE THREAD

**Issue by alexkb** [Laravel-Backpack/CRUD#400]
If I have a couple of different page templates for the 'Page' model, like:
* 'Standard' with a wysiwyg field and,
* 'Homepage', with wysiwyg and image(s),

I need to create my entries in PageTemplates, and define the fields there. I've seen the example for creating a [`SetImageAttribute()`](https://laravel-backpack.readme.io/docs/crud-fields#section-image) method on the model to handle storing the files, but this means two things:
 1. the field name needs to be 'image', otherwise the method name needs to match `set<Fieldname>Attribute` (this also means a new method for each image field), and
 2. the field needs to exist on the model (database).

You can get around the 2nd problem by setting the image field in the pagetemplate definition to be in the extra's column, but when you do that, it tries to store the base64 encoded image in the extra's column (which is not ideal for many reasons). Perhaps I could just store the path to the image in this extra's field somehow (when I do this, my `setImageAttribute()` call never gets fired).

This basically means all the standard pages are going to have this image field and functionality too, which doesn't feel right.

I was hoping I could have different Page templates with different models but have the same Pages backpack Admin UI. Does anyone have any suggestions for achieving this, or is this not how laravel-backpack should be used. Thanks.

Also, I see the [liberal use of traits a lot in laravel-backpack](https://github.com/Laravel-Backpack/CRUD/blob/master/src/CrudPanel.php). I was (perhaps wrongly) of the opinion that traits should be used sparingly, and instead use DI ([as discussed over on SO](http://stackoverflow.com/questions/7892749/traits-in-php-any-real-world-examples-best-practices)).

**Comment by OwenMelbz** [comment]
Hi Alex,

The `setImageAttribute` is just an example of how to use the uploader, you can call it `setBaconAtrribute` for all it matters if thats what your fields called. (this is just a normal way in laravel to use accessors/mutators)

If you had 3 different image columns in your database then you'd have 3 setters all with different names, allowing you access to different disks/file paths etc.

If you don't want a base64 image, then you can always use the `image` field type, not the `base64_image` field type.

If you're worried about your Page model having a "image" column when not all variations need a "image" column, you should consider having something like n - 1 relationship to something like "PageTemplate" model - then that model defines the functionality of the page?

-------

Regards to traits, I think it's more of a "laravel" thing, theres always been the `Laravel VS ` argument and the way it does things, e.g globals vs DI, Traits vs inheritance etc.

If you were worried about your "Page" model having extra fields that it doesn't need. Imagine if it was using an inheritance model for structures on your Page model, you'd end up with loads of redundant methods. Where as Traits lets you easily turn on/off functionality, so just depends on what you like to do and what is best for your project/team

**Comment by tabacitu** [comment]
Hi @alexkb 

Totally agree with you with the use of traits. It's been an architecture afterthought, when we started putting in A LOT more features than anticipated, and we didn't quite understand where all the pieces fit together. In Backpack\CRUD v4 we'll refactor to collections and stand-alone classes. It's something that's been pressing me for a while :-) It's turning into a god class. But then again, so do some people say about Laravel's Eloquent - that it's a god class. But in that case, haters gonna hate hate hate.

You can probably have just one method in your Page model that uploads files, but it would upload all files to the same folder. If you don't mind that, something like the pseudocode below should work, as long as all your fake fields have their names ending in "image" (ex: home_image, second_image, another_image):

```php
// Page model

public function __call($method, $parameters)
    {
        // if $method ends with ImageAttribute
        // $attribute_name = get the field name from the method name (anything that's between set and Attribute, camel case it)
            // $this->setImageAttribute($value, $attribute_name);
    }

public function setImageAttribute($value, $attribute_name = 'image')
    {
        $disk = "public_folder";
        $destination_path = "uploads/folder_1/subfolder_3";

        // if the image was erased
        if ($value==null) {
            // delete the image from disk
            \Storage::disk($disk)->delete($this->image);

            // set null in the database column
            $this->attributes[$attribute_name] = null;
        }

        // if a base64 was sent, store it in the db
        if (starts_with($value, 'data:image'))
        {
            // 0. Make the image
            $image = \Image::make($value);
            // 1. Generate a filename.
            $filename = md5($value.time()).'.jpg';
            // 2. Store the image on disk.
            \Storage::disk($disk)->put($destination_path.'/'.$filename, $image->stream());
            // 3. Save the path to the database
            $this->attributes[$attribute_name] = $destination_path.'/'.$filename;
        }
    }
```

Hope it helps.
Cheers!
