### ISSUE TITLE
Reporting and charts

### ISSUE THREAD

**Issue by avifatal** [Laravel-Backpack/CRUD#401]
Hi,
I need to build a mini CRM.
I need to do some aggregated reports for the admin. and maybe add some charts in the header of the report.
Is there built-in solution for that,l if not, is there external infrastructure that I can add support this?

Basic usage.
I want to define a custom query with UI filters and let the admin run this in the back-end. 

Thanks

**Comment by OwenMelbz** [comment]
Hi,

TL;RD


Backpack is effectively a CRUD framework.

So yes you can do all of this in backpack, however you'll need to code all this yourself.

We use AdminLTE (built on bootstrap) so that might contain some javascript components you can use, if you visit the AdminLTE website, you'll be able to see everything it can do.

However it just uses Laravel's Models/Controllers etc, so you'll just be able to use the models etc and do this yourself.

**Comment by avifatal** [comment]
This I can say the fastest technical response anyone ever got (-:

Since backpack understands relations and has UI features in context, can't i reuse this to build the reporting mechanism? im talking about UI filters and grid.

I did this once in a .net system where I have used the built-in UI abilities  and created controllers that actually operates them. and I got for free fully working grid + nice api to create fields for the filters. my custom code handled the server site query binding and execution.

As I understand there is no built in solution, so I'm looking hints if that worth trying to do.

Thanks!

**Comment by OwenMelbz** [comment]
Sure, although remember backpack does not handle relationships, Laravel handles the relationships. We just use them :)

And yes - as mentioned before, Backpack uses AdminLTE and Bootstrap for its UI. Which means you can use all the UI and CSS and Javascript from AdminLTE (built in)

As this is not a CRUD style module, you can just use default laravel, something like

1. Setup a new controller, that loads a template in.
2. Make sure the route is protected by the admin authentication
3. Make sure the template extends the backpack admin
4. Write the rest of your code, using both Laravel and AdminLTE documentation.

If you look at the "Dashboard" controller and template, this is a blank canvas, which you might get an idea from.

**Comment by avifatal** [comment]
Ok, ill dig into it and ask questions if I bump into problems, thanks.
BTW, the CRM needs to be in an RTL language is it supported? 
Thanks again

**Comment by OwenMelbz** [comment]
As mentioned before, the UI is controlled by AdminLTE and Bootstrap.

If they have RTL support, then you can read about it on their websites and use it. A quick google suggests this https://github.com/almasaeed2010/AdminLTE/issues/469

Regards to input fields, they are just normal HTML fields, so you can pass what ever properties to them and attach any CSS you like, which includes things like "direction: rtl" etc.
