### ISSUE TITLE
[Bug] Column with type 'relationship_count' auto eager load relationship

### ISSUE THREAD

**Issue by devpreview** [Laravel-Backpack/CRUD#4015]
# Bug report

### What I did

```
  $this->crud->addColumn([
    'name' => 'devices',
    'type' => 'relationship_count',
  ]);
```

### What I expected to happen

Entries without auto eager loaded 'devices' relationship.

### What happened

Entries with auto eager loaded 'devices' relationship.

### What I've already tried to fix it

Hotfix:

```
class CrudPanel extends \Backpack\CRUD\app\Library\CrudPanel\CrudPanel
{
    protected function makeSureColumnHasEntity($column): array
    {
        return empty($column['type']) || !in_array($column['type'], [
            'relationship',
        ]) ? $column : parent::makeSureColumnHasEntity($column);
    }
}
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.13 (cli) (built: Nov 22 2021 09:50:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.75.0@0bb91d3176357da232da69762a64b0e0a0988637

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409
```

**Comment by pxpm** [comment]
@tabacitu all the relationships used inside columns are `eager` loaded. https://github.com/Laravel-Backpack/CRUD/blob/370531d2fd637b6ce1872f2732438853b96ebc66/src/app/Library/CrudPanel/Traits/Read.php#L81

What you think would be the best approach if this is something that needs to be fixed ? Is there a good reason to don't auto-eager load some relations ? 

I recall we having some trouble with this column before I wonder? Not sure. 

Would a key: `eager_load` in the columns to allow developer to take control of this ? 

Let me know,
Pedro

**Comment by tabacitu** [comment]
Hmm... why would you like to NOT eager-load this @devpreview ?

@pxpm I'm not sure about the importance or granularity of that configuration. Not sure we should even do it, but if we did do it... perhaps on the entire List Operation would be enough (for all columns)? I think we need to understand WHEN someone would NOT want their relationships eager-loaded...

And to answer your question - this column isn't supposed to exist. In [its docs](https://backpackforlaravel.com/docs/4.1/crud-columns#relationship_count-1) we provide a way to use the `text` column for the same thing, which would work much better. But yeah... it _does_ exist, for convenience...

**Comment by pxpm** [comment]
Since this is inactive for long time, and I still can't find the reason to don't eagerLoad the data in this scenarios, I will be closing this. 

Please feel free to continue the discussion, we will re-open if needed. 👍 

Thanks
