### ISSUE TITLE
Concatenate two columns in list view

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#402]
I would like to concatenate two columns in my list view.
I want to have "firstname name".

So i did an accesor in my model:
```
public function getFullNomAttribute() {
    return $this->firstname . ' ' . $this->name;
}
```

And in my controller:
```
 $this->crud->addColumn([ 
            'label' => "concatened_name", 
            'type' => "model_function",
            'function_name' => 'getFullNomAttribute',
        ]);
```

It's working as long as i have the two columns defined with addColumn in my controller:
```
 $this->crud->addColumn([
            'name' => 'name',
            'label' => "name",
            'type' => 'text'
        ]);
        $this->crud->addColumn([
            'name' => 'firstname',
            'label' => "firstname",
            'type' => 'text'
        ]);
```

But i end up with three columns: firstname, name and concatened_name
And if i remove the two addColumn my accesor is not working anymore...
I want just concatened_name in my list.

Any idea ? Thanks!

**Comment by OwenMelbz** [comment]
Make sure you're **NOT** using `$this->crud->setFromDb();`

If that does not fix it, maybe try something like

*Your Model*
```php
public function getFullNomAttribute()
{
    return $this->concatenateNom();
}

private function concatenateNom()
{
    return trim($this->['attributes]['firstname'] . ' ' . $this->attributes['name']);
}

```

*Your Controller*
```php

 $this->crud->addColumn([ 
    'label' => "Full Nom", 
    'type' => "model_function",
    'function_name' => 'concatenateNom',
]);
```

Then make sure there is no "name" or "fullname" columns defined?

Also make sure you do NOT have

**Comment by adbmdp** [comment]
I'm not using $this->crud->setFromDb();

In your code above i guess i have to call getFullNomAttribute and not concatenateNom in my controller right ?

Are you sure about the syntax for $this->attributes['name']?
I have an "Undefined index: name" error.
In my model the fields are in protected $fillable

I'll keep trying.

**Comment by adbmdp** [comment]
I've tried everything. 

With $this->attributes['name'] instead of  $this->name and with a second function like you told me.
Each time I have an ErrorException in my model : Undefined index

But if i add the columns with addColumn in my controller it's working...
Looks like if the columns are not 'declared' with addColumn CRUD does not know it.

**Comment by OwenMelbz** [comment]
I think it's best to post your whole Model, whole Controller and the database schema for your user.

It is much easier to understand by seeing it than trying to explain

**Comment by adbmdp** [comment]
I think it's the same bug as here:
[https://github.com/Laravel-Backpack/CRUD/issues/306](https://github.com/Laravel-Backpack/CRUD/issues/306)
model_function Column does not work with enableAjaxTable...

**Comment by adbmdp** [comment]
My workaround idea is to make my own column types/blade.
But the $entry variable only contains fields declared with addColumn in the controller. So i in my case i need to have name and firstname. And i end-up displaying columns i don't want in the list.

Is there a way to get database fields value but not displaying it in the list? Maybe a "hidden" Column Types?
So they are available in $entry and we can work with this in blade files.

**Comment by adbmdp** [comment]
OK here is my "ugly" workaround. It may help others.
I've created a custom empty columns type : hidden.blade.php, displaying nothing.
In my controller i can declare:
```
$this->crud->addColumn([
            'name' => 'name',
            'label' => "Name",
            'type' => 'hidden'
]);

$this->crud->addColumn([
            'name' => 'firstname',
            'label' => "FirstName",
            'type' => 'hidden'
]);
```

Then I have another custom columns type displaying name and firstname:
 echo $entry->name . " " . $entry->firstname;

**Comment by adbmdp** [comment]
^
Sorry the solution above is not working as i still have the columns names displayed even with my "hidden" custom fields types.

**Comment by tabacitu** [comment]
Sorry for jumping in. If you already have the accessor, this should work for you:
```php
 $this->crud->addColumn([
            'name' => 'full_nom',
            'label' => "name",
            'type' => 'text'
        ]);
```

Eloquent makes this process invisible because of the mutator. It's just like you would have that column in the db.

Hope it helps. Cheers!

**Comment by adbmdp** [comment]
Thanks for the help but it's not working.

In my model:
public function getFullNomAttribute() {
        return $this->firstname . ' ' . $this->name;
}

In my controller:
```
$this->crud->addColumn([
            'name' => 'full_nom',
            'label' => "name",
            'type' => 'text'
]);
```

--> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_nom' in 'field list'

**Comment by adbmdp** [comment]
@tabacitu, it works when i disable enableAjaxTable()
With $this->crud->enableAjaxTable(); i have the error ...
_SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'field list'_
But i really need to enable ajax as my table is huge.

**Comment by OwenMelbz** [comment]
Use the above thread

**Comment by adbmdp** [comment]
Accessor or model_function still not working with enableAjaxTable()...
This is really blocking for me. Any news on that?

**Comment by viktorivanov** [comment]
Here's what you can do to make your attribute show when enableAjaxTable() is present on your CRUD:

1. Add your attribute on the model
```php
public function getFullnameAttribute() 
{
    return $this->first_name . ' ' . $this->last_name;
}
```
2. Make a 'helper' function that will return your accessor through a fresh instance of the current entry
```php
public function showFullname()
{
    return $this->fresh()->fullname; // make sure you call fresh instance or you'll get an error that fullname is not found or something like that...
}
```
3. On your CRUD controller in setUp add your column using the function from above
```php
$this->crud->addColumn([
    'label' => 'Full name',
    'type' => 'model_function',
    'function_name' => 'showFullname'
]);
```

That's it

**Comment by adbmdp** [comment]
It works!!
Thank you @viktorivanov

**Comment by jsiebach** [comment]
This is amazing.  Thank you @viktorivanov !!

**Comment by jsiebach** [comment]
I find myself having to give the column a real `name` attribute.  Otherwise my query adds `select "" as ""`.  I use a random other column which I don't need for the table in order to make this work.  For example, I don't use the referrer column in my table, so I can use it for my "phone" column (which is a function-derived column):

                [
	                'type' => 'model_function',
		        'label' => 'Phone',
		        'function_name' => 'showPhoneColumn',
		        'name' => 'referrer'
	        ],

**Comment by viktorivanov** [comment]
@jsiebach I've not encountered such a behavior :confused:
Please check You are using accessor for the phone field

**Comment by FrankAlwis24** [comment]
If its a one to many relationship and you want to concat fields from another table. For example you want to get user first name and last name into the list view of another view containing user id i did something like this.  Make a new file in the resources\views\vendor\backpack\crud\columns\ folder and do something like this:

{{-- single relationships (1-1, 1-n) --}}
@php
    $column['escaped'] = $column['escaped'] ?? true;
    $column['prefix'] = $column['prefix'] ?? '';
    $column['suffix'] = $column['suffix'] ?? '';
    $column['limit'] = $column['limit'] ?? 40;
    $column['attribute'] = $column['attribute'] ?? (new $column['model'])->identifiableAttribute();
    $attributes = [];
    $test=[];
    foreach (explode(',',$column['attribute']) as $key_value)
    {
        $column_values=[];
        $column_values=$crud->getRelatedEntriesAttributes($entry, $column['entity'], $key_value);
        $first_key=(string)array_key_first($column_values);

        if(array_key_exists($first_key,$attributes))
            {
                $attributes[  $first_key ] = $attributes[array_key_first($column_values)].' '.array_values($column_values)[0];
            }
        else{
     $attributes=$crud->getRelatedEntriesAttributes($entry, $column['entity'], $key_value);
     }
    }

    foreach ($attributes as $key => &$text) {
        $text = Str::limit($text ?? '', $column['limit'], '[...]');
    }

@endphp

<span>
    @if(count($attributes))
        {{ $column['prefix'] }}
        @foreach($attributes as $key => $text)
            @php
                $related_key = $key;
            @endphp

            <span class="d-inline-flex">
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_start')
                @if($column['escaped'])
                    {{ $text }}
                @else
                    {!! $text !!}
                @endif
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_end')

                @if(!$loop->last)
                    ,
                @endif
            </span>
        @endforeach
        {{ $column['suffix'] }}
    @else
        -
    @endif
</span>
 this will allow you to concat any number of fields from the user table.

Then you have to add this to the setupListOperation:
        $this->crud->addColumn([
            'label' => "Student",
            'type' => 'select_new_multi',
            'name' => 'student_id', // the db column for the foreign key
            'entity' => 'getStudentData', // the method that defines the relationship in your Model
            'attribute' => 'first_name,last_name',
            'model' => "App\User",
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhereHas('getStudentData', function ($q) use ($column, $searchTerm) {
                    $q->where('first_name', 'like', '%' . $searchTerm . '%')
                        ->orWhere('last_name', 'like', '%' . $searchTerm . '%');
                });
            }

        ]);

and add this function into the model:
    public function getStudentData()
    {
        return $this->belongsTo('App\User', 'student_id');
    }
Hope this helps

**Comment by FrankAlwis24** [comment]
If its a one to many relationship and you want to concat fields from another table. For example you want to get user first name and last name into the list view of another view containing user id i did something like this.  Make a new file in the resources\views\vendor\backpack\crud\columns\ folder and do something like this:
`@php
    $column['escaped'] = $column['escaped'] ?? true;
    $column['prefix'] = $column['prefix'] ?? '';
    $column['suffix'] = $column['suffix'] ?? '';
    $column['limit'] = $column['limit'] ?? 40;
    $column['attribute'] = $column['attribute'] ?? (new $column['model'])->identifiableAttribute();
    $attributes = [];
    $test=[];
    foreach (explode(',',$column['attribute']) as $key_value)
    {
        $column_values=[];
        $column_values=$crud->getRelatedEntriesAttributes($entry, $column['entity'], $key_value);
        $first_key=(string)array_key_first($column_values);

        if(array_key_exists($first_key,$attributes))
            {
                $attributes[  $first_key ] = $attributes[array_key_first($column_values)].' '.array_values($column_values)[0];
            }
        else{
     $attributes=$crud->getRelatedEntriesAttributes($entry, $column['entity'], $key_value);
     }
    }

    foreach ($attributes as $key => &$text) {
        $text = Str::limit($text ?? '', $column['limit'], '[...]');
    }

@endphp

<span>
    @if(count($attributes))
        {{ $column['prefix'] }}
        @foreach($attributes as $key => $text)
            @php
                $related_key = $key;
            @endphp

            <span class="d-inline-flex">
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_start')
                @if($column['escaped'])
                    {{ $text }}
                @else
                    {!! $text !!}
                @endif
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_end')

                @if(!$loop->last)
                    ,
                @endif
            </span>
        @endforeach
        {{ $column['suffix'] }}
    @else
        -
    @endif
</span>`
 this will allow you to concat any number of fields from the user table.

Then you have to add this to the setupListOperation:
`        $this->crud->addColumn([
            'label' => "Student",
            'type' => 'select_new_multi',
            'name' => 'student_id', // the db column for the foreign key
            'entity' => 'getStudentData', // the method that defines the relationship in your Model
            'attribute' => 'first_name,last_name',
            'model' => "App\User",
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhereHas('getStudentData', function ($q) use ($column, $searchTerm) {
                    $q->where('first_name', 'like', '%' . $searchTerm . '%')
                        ->orWhere('last_name', 'like', '%' . $searchTerm . '%');
                });
            }

        ]);
`
and add this function into the model:
`public function getStudentData()
    {
        return $this->belongsTo('App\User', 'student_id');
    }
`
Hope this helps

**Comment by FrankAlwis24** [comment]
If its a one to many relationship and you want to concat fields from another table. For example you want to get user first name and last name into the list view of another view containing user id i did something like this.  Make a new file in the resources\views\vendor\backpack\crud\columns\ folder and do something like this:

```
@php
    $column['escaped'] = $column['escaped'] ?? true;
    $column['prefix'] = $column['prefix'] ?? '';
    $column['suffix'] = $column['suffix'] ?? '';
    $column['limit'] = $column['limit'] ?? 40;
    $column['attribute'] = $column['attribute'] ?? (new $column['model'])->identifiableAttribute();
    $attributes = [];
    $test=[];
    foreach (explode(',',$column['attribute']) as $key_value)
    {
        $column_values=[];
        $column_values=$crud->getRelatedEntriesAttributes($entry, $column['entity'], $key_value);
        $first_key=(string)array_key_first($column_values);

        if(array_key_exists($first_key,$attributes))
            {
                $attributes[  $first_key ] = $attributes[array_key_first($column_values)].' '.array_values($column_values)[0];
            }
        else{
     $attributes=$crud->getRelatedEntriesAttributes($entry, $column['entity'], $key_value);
     }
    }

    foreach ($attributes as $key => &$text) {
        $text = Str::limit($text ?? '', $column['limit'], '[...]');
    }

@endphp

<span>
    @if(count($attributes))
        {{ $column['prefix'] }}
        @foreach($attributes as $key => $text)
            @php
                $related_key = $key;
            @endphp

            <span class="d-inline-flex">
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_start')
                @if($column['escaped'])
                    {{ $text }}
                @else
                    {!! $text !!}
                @endif
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_end')

                @if(!$loop->last)
                    ,
                @endif
            </span>
        @endforeach
        {{ $column['suffix'] }}
    @else
        -
    @endif
</span>
```

 this will allow you to concat any number of fields from the user table.

Then you have to add this to the setupListOperation:

   ```
     $this->crud->addColumn([
            'label' => "Student",
            'type' => 'select_new_multi',
            'name' => 'student_id', // the db column for the foreign key
            'entity' => 'getStudentData', // the method that defines the relationship in your Model
            'attribute' => 'first_name,last_name',
            'model' => "App\User",
            'searchLogic' => function ($query, $column, $searchTerm) {
                $query->orWhereHas('getStudentData', function ($q) use ($column, $searchTerm) {
                    $q->where('first_name', 'like', '%' . $searchTerm . '%')
                        ->orWhere('last_name', 'like', '%' . $searchTerm . '%');
                });
            } ]);
```

and add this function into the model:
   ```
 public function getStudentData()
    {
        return $this->belongsTo('App\User', 'student_id');
    }
```

Hope this helps
