### ISSUE TITLE
[Bug] Unable to produce the same look with CoreUI following instructions from docs

### ISSUE THREAD

**Issue by ajcastro** [Laravel-Backpack/CRUD#4021]
# Bug report

### What I did
I have a freshly installed Laravel 8 and install laravel backpack.
I am using PHP 8.0

I tried to produce the same CoreUI look based from https://backpackforlaravel.com/docs/4.1/base-how-to#inspired-by-coreui .
I copied the following config:
```php
    'header_class' => 'app-header navbar',
    'body_class' => 'app aside-menu-fixed sidebar-lg-show',
    'sidebar_class' => 'sidebar',
    'footer_class' => 'app-footer d-none',
```
Then I used the `blue-bundle.css`
```php
'styles' => [
        // 'packages/backpack/base/css/bundle.css', // has primary color electric purple (backpack default)
        'packages/backpack/base/css/blue-bundle.css', // has primary color blue
...
```

I expect the sidebar to be black but it looks like this instead (in the docs sidebar should be black/dark), 
![image](https://user-images.githubusercontent.com/4918318/146806700-d2973a1e-88e2-436f-88fd-08d3d2adaa2c.png)

I also noticed that the `sidebar_class` it does not have `sidebar-pills` unlike other theme examples. This seems to remove the left margin/padding and result to this:
**No sidebar-pills, when the sidebar is hidden**: Left padding/margin is missing
![image](https://user-images.githubusercontent.com/4918318/146805709-db5fb8ed-b6f7-4a52-8b42-a9aeeaf0e86a.png)
**No sidebar-pills, when the sidebar is visible**:
![image](https://user-images.githubusercontent.com/4918318/146805926-c6c5164d-856e-45c7-91cc-3ec1a0352d1b.png)

So I tried adding `sidebar-pills` but it didn't fix it.

**With sidebar-pills, when the sidebar is hidden**: the left padding/margin looks better
![image](https://user-images.githubusercontent.com/4918318/146806165-f07ef933-20ad-43e4-bf17-e234f1cdbdbc.png)
**With sidebar-pills, when the sidebar is visible**: The sidebar links become blue but it should be white
![image](https://user-images.githubusercontent.com/4918318/146806241-8390344d-4277-49b1-b3e1-b8e5f72715b8.png)

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version
Backpack: 4.1.62
Laravel: 8.76.2
PHP: 8.0
DB: MySQL 5.7

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.7 (cli) (built: Jun  2 2021 00:41:03) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.76.2@c67acfdc968f487b6235435080eef62a7e2ed055

### BACKPACK VERSION:
4.1.62@273c277e826c157ef0913962769a7ec9a44b6233
```

I'll also try to debug and see if I can solve it. But I also would like to report it first. 
This package is really great and would like to use it for my commercial projects. Thanks!

**Comment by pxpm** [comment]
I am doing a cleanup of old issues. Sorry this didn't get prioritized at that moment. 

We have revamped the whole theme system for Backpack v6 https://backpackforlaravel.com/docs/6.x/base-themes#about-1

Let us know if v6 themes brings the flexibility needed for your custom designs. 🙏 

Cheers
