### ISSUE TITLE
Add a scope to Select2 

### ISSUE THREAD

**Issue by mrvanwagoner** [Laravel-Backpack/CRUD#403]
In edit view, I only want to see certain records for a select2. Is there a way to  scope the dropdown list or identify a queried data source for a select2? I tried adding the scope to the relationship in the Model per Laravel documentation but that seems to do nothing. No matter what I have tried, all of the records for the related Model show up in the dropdown list.

**Comment by Fiftysven** [comment]
Hi mrvanwagoner,
I had exactly the same problem as you and after trying a lot of workarounds with select_from_array etc i found a pretty easy solution.
You can create a custome view and use it exactly like a select2_multiple field but in the view you change the following line of code:

@foreach ($field['model']::all() as $connected_entity_entry)

for example to:

@foreach ($field['model']::where('parent_id', 1)->get() as $connected_entity_entry)

I guess there are existing better ways to fix this, but i'm new to Backpack and thats what worked for me. A scope you can define in the CrudController would actually be a lot more comfortable.
I hope i could help.

**Comment by tabacitu** [comment]
Hi guys,

A custom field sounds like a good solution to me, so I'll close the issue. Feel free to continue the talk if you find better ones.

Cheers!

**Comment by jrpub** [comment]
Hi all,

I implemented a kind of generic solution with a custom field, not perfect but useful. 

You can now pass to select2_multiple directly the data you want, using a custom property called "models".

```
$groups = \Auth::user()->groups()->get();
$this->crud->addField([
            'label' => 'Groups',
            'type' => 'select2_multiple_filter',
            'name' => 'groups', 
            'entity' => 'groups', 
            'attribute' => 'name',
            'models' => $groups, // Your pass your data here. No need to include the legacy 'model' property.
            'pivot' => true // on create&update, do you need to add/delete pivot table entries?
]);
```
The best thing, is that the modified can still be used as usual. Just replace the property "models" by "model" with the usual string targeting the model. 

Modified custom field below. I called it "select2_multiple_filter", but change it according to your needs.

```
<!-- select2 multiple -->
<div @include('crud::inc.field_wrapper_attributes') >
    <label>{!! $field['label'] !!}</label>
    @include('crud::inc.field_translatable_icon')
    <select
            name="{{ $field['name'] }}[]"
            style="width: 100%"
            @include('crud::inc.field_attributes', ['default_class' =>  'form-control select2_multiple'])
            multiple>

        @if (isset($field['models']))
            @php
                $all = $field['models']
            @endphp
        @else
            @if (isset($field['models']))
                @php
                    $all = $field['model']::all()
                @endphp
            @endif
        @endif
        @if (isset($all))
            @foreach ($all as $connected_entity_entry)
                <option value="{{ $connected_entity_entry->getKey() }}"
                      [... remaining file of select2_multiple ...]
```
I didn't detect any bug yet, but I will update this if I find one.

**Comment by mrvanwagoner** [comment]
Thanks jrpub! I figured out how to use select2_from_ajax to accomplish the same thing before reading your solution. Your way is much simpler as it doesn't require routes and controllers. I created another custom field similar to yours based on the select2. I have called it "select2_filter": 

`
<div @include('crud::inc.field_wrapper_attributes') >
    <label>{!! $field['label'] !!}</label>
    @include('crud::inc.field_translatable_icon')
    <?php $entity_model = $crud->model; ?>
    <select
        name="{{ $field['name'] }}"
        style="width: 100%"
        @include('crud::inc.field_attributes', ['default_class' =>  'form-control select2_field'])
        >

        @if ($entity_model::isColumnNullable($field['name']))
            <option value="">-</option>
        @endif

        
        @if (isset($field['models']))
            @php
                $all = $field['models']
            @endphp
        @else
            @if (isset($field['models']))
                @php
                    $all = $field['model']::all()
                @endphp
            @endif
        @endif

        
        @if (isset($all))
            @foreach ($all as $connected_entity_entry)`

**Comment by mrvanwagoner** [comment]
Hmm... not sure what happened to the formatting of my code... I guess I am not sure how to use the editor to make comments...

**Comment by else** [comment]
I hate my username. You don’t believe how many issues I am getting subscribed to.

**Comment by lloy0076** [comment]
@mrvanwagoner Three back ticks 👍 

@else What else would you use? :trollface:

**Comment by mrvanwagoner** [comment]
This version allows using Scopes in the foreign model as a means of filtering select2 options:

`{{-- 
    CHANGED Select2. Add field options 'models' and 'scopes' for filtering dropdown options. See https://github.com/Laravel-Backpack/CRUD/issues/403
        OPTIONS:
            1) Model:
                a) Standard Backpack usage: Identify 'model' option in addFields() method of Controller ONLY: 
                    For example: 'model' => 'App\Models\Category',
                b) Add scope(s) to the model (if desired): Identify desired scope(s) from foreign model to apply: 
                    For example: 'scopes' => ['type', 'active], 
                    NOTE: scopeType() and scopeActive() must exist in 'App\Models\Category'
            2) Models: Create variable in Controller of dropdown options.
                a) In the Field Options identify the models:
                    For example: 'models' => $types,
                b) Within setup() add the variable:
                    For example: $types = \App\Models\Category::where('type', 'Fruit')->get();
--}}


<div @include('crud::inc.field_wrapper_attributes') >
    <label>{!! $field['label'] !!}</label>
    @include('crud::inc.field_translatable_icon')
    <?php $entity_model = $crud->getRelationModel($field['entity'],  - 1); ?>
    <select
        name="{{ $field['name'] }}"
        style="width: 100%"
        @include('crud::inc.field_attributes', ['default_class' =>  'form-control select2_field'])
        >

        @if ($entity_model::isColumnNullable($field['name']))
            <option value="">-</option>
        @endif

        {{-- CHANGED Add this so user can use either 'model' with or without 'scopes' OR 'models' option (eg. 'Apps\Users') or 'models' option  (eg. '$users') --}}
        @if (isset($field['models']))
            {{ $all = $field['models'] }}
        @else
            @if (isset($field['model']))
                @if (isset($field['scopes']))
                    {{ $scopes = null }}

                    @foreach ($field['scopes'] as $scope)
                        {{ $scopes = $scopes . '->' . $scope .'()' }}
                    @endforeach

                    {{ $scopes = preg_replace("/->/", "", $scopes, 1) }}
                    {{ $code = "\$field['model']::" . $scopes . "->get()" }}

                    {{ $all = eval("return $code;") }}
                @else
                    {{ $all = $field['model']::all() }}
                @endif
            @endif
        @endif

        @if (isset($all)) {{-- CHANGED Was $field['model'] --}}
            @foreach ($all as $connected_entity_entry)` {{-- CHANGED Was $field['model']::all'parenthesis' --}}
