### ISSUE TITLE
[4.2][Bug] Auto-detected column does not properly show value

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4040]
# Bug report

### What I did

Checked out the 4.2 branch. Went to Products CRUD, where all entries _definitely_ have names.

### What I expected to happen

See names in the names column.

### What happened

![Screenshot 2021-12-27 at 08 32 21](https://user-images.githubusercontent.com/1032474/147441796-5716677b-bae3-4410-a01f-d98269e8bd31.png)

From what I see this is because there is no exact type given to those columns. They're added using:
```php
        CRUD::addColumns(['name', 'description']); // add multiple columns, at the end of the stack
```

And if I do this afterwards...
```php
        CRUD::column('name')->type('text');
```

It'll show:

![Screenshot 2021-12-27 at 08 33 45](https://user-images.githubusercontent.com/1032474/147441898-a2c5e605-4d45-40b2-af2a-22f0e8e15bf5.png)

### What I've already tried to fix it

Nothing yet, but I notice the result of that `addColumns()` is that the type of the columns is `array`, which is obviously wrong, it should be `text`. I haven't put the time in to see if the bug is inside the "guessing" or inside the `addColumns()` function. If the problem is just limited to this or bigger.

**Comment by pxpm** [comment]
@tabacitu I think I found the culprit. 

After reading your statement I was pretty sure what was happening. 

I've submitted #4041 to fix this so I will be closing this one. 

Best,
Pedro
