### ISSUE TITLE
[Bug] select2_nested error after upgrading to 4.2

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4053]
# Bug report

### What I did

Tried to edit an entry that was created before the 4.2 upgrade in Monsters.

### What I expected to happen

Page load.

### What happened

<img width="1380" alt="Screenshot 2022-01-05 at 15 28 31" src="https://user-images.githubusercontent.com/1032474/148225269-98087991-c2e3-4b5e-8558-fea8be88aa48.png">

**Comment by pxpm** [comment]
Closing in favor of #4055
