### ISSUE TITLE
[Discussion] rename pivotFields and fields into `subfields`

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4065]
As discussed in https://github.com/Laravel-Backpack/CRUD/issues/4012#issuecomment-1007304376 I was about to rename pivotFields and fields into `subfields`. 

It happens that in Backpack core, there is some reference to `subfields` already, but the code don't perform what we expect from subfields in this particular scenario.

https://github.com/Laravel-Backpack/CRUD/blob/ed989fb9ae7130aeed2f4f2d14c96833dee5975d/src/app/Library/CrudPanel/Traits/Update.php#L56 and also https://github.com/Laravel-Backpack/CRUD/blob/ed989fb9ae7130aeed2f4f2d14c96833dee5975d/src/app/Library/CrudPanel/Traits/Create.php#L65

Those were left there for BC, I think they are there to specifically support https://backpackforlaravel.com/docs/4.1/crud-fields#checklist_dependency I got an hint from a previous changelog: 

![image](https://user-images.githubusercontent.com/7188159/148761551-eb408664-a150-40e5-a026-914710d30694.png)

Let me know what you think @tabacitu

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4069
