### ISSUE TITLE
access to all model attributes in button 

### ISSUE THREAD

**Issue by M0H3N** [Laravel-Backpack/CRUD#407]
Hi 
Is there anyway to access all  model attributes  in button view . yet we just access to columns that show in data table view .

**Comment by MDEvo** [comment]
From https://laravel-backpack.readme.io/docs/crud-buttons 
> The most useful variables you'll have in this file here are:
- $entry - the database entry you're showing (only inside the line stack);
- $crud

**Comment by M0H3N** [comment]
@MDEvo 
I know that ... but $entry just return database column we are showing in data table view  not all columns .

**Comment by adbmdp** [comment]
I have almost the same issue. I want to access some model attributes in a custom column view.
But i only have access to attributes declared with addColumn in the controller.
I not, they are they are not in $crud->getEntries();

**Comment by M0H3N** [comment]
I found that if ajax table view is enabled  , $entry just return database column we are showing in data table view not all model attributes  .

the problem is in this line : 
https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudFeatures/AjaxTable.php#L16

**Comment by adbmdp** [comment]
Yes enableAjaxTable changes a lot of things...
Also model_function and accessors are not working with enableAjaxTable.

**Comment by OwenMelbz** [comment]
Closing - https://github.com/Laravel-Backpack/CRUD/issues/411
