### ISSUE TITLE
[Bug] cannot clear `checklist_dependency` field

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4071]
# Bug report

### What I did

Went to Edit User on the `4.2` branch. Tried to remove all roles&permissions for a user. So I unchecked all boxes from the interface.

### What I expected to happen

After saving, all boxes are unchecked.

### What happened

After saving, the boxes that were checked are still checked. 

### What I've already tried to fix it

Nothing yet. I assume this is a problem with the way we use checkboxes and/or hidden inputs - when the admin unchecks all the checkboxes the inputs don't get sent anymore (or something like that). 

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes. Tried it on `4.2`, on `fix-checklist-old` and on https://github.com/Laravel-Backpack/CRUD/pull/4069

**Comment by pxpm** [comment]
Fixed in #4072
