### ISSUE TITLE
Hide "+ Add" button on `table` field when the `max` is reached

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4076]
# Bug report

### What I did

Reported in https://github.com/Laravel-Backpack/CRUD/issues/4074 . Added a field table with `max => 1`. 

### What I expected to happen

Hide the "+ Add" button once the MAX is reached. So I can't click it again.

### What happened

"+ Add" button is still visible.

### What I've already tried to fix it

Nothing yet.

### Is it a bug in the latest version of Backpack?

4.1.x

**Comment by pxpm** [comment]
Fixed in https://github.com/Laravel-Backpack/PRO/pull/94
