### ISSUE TITLE
When using dot notation in field name, throw custom error/exception if relationship not found

### ISSUE THREAD

**Issue by rroblik** [Laravel-Backpack/CRUD#4079]
# Bug report

### What I did

```php
protected function setupCreateOperation()
{
   Crud::field('example.dotted.name')->type('text');
}
```

### What I expected to happen

View a simple text field

### What happened

Fatal error :

```
ErrorException
get_class() expects parameter 1 to be object, null given

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Relationships.php:57
```

### What I've already tried to fix it

(nc)

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 7.4.19 (cli) (built: May  6 2021 22:27:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.19, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.76.2@c67acfdc968f487b6235435080eef62a7e2ed055

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409
```

### Why use *dot notation* in field name ?
Using dot notation allow to easily change/clean the final structure of the stored JSON string especially when used use `fake` field and `store_in` properties, and using Mutator (and Accessor).

Example : 
```php
# Model

class App extends Model
{
  use HasFactory;
  use \Backpack\CRUD\app\Models\Traits\CrudTrait;

  protected $fillable = [
    'ci_settings',
    # ...
  ];

  protected $casts = [
    'ci_settings' => 'array',
  ];

  protected $fakeColumns = [
    'ci_settings'
  ];

  # ...

  public function getCiSettingsAttribute($value)
  {
    $value = $this->castAttribute('ci_settings', $value);

    if (!empty($value)) {
      $value = Arr::dot($value);
    }

    return $value;
  }

  public function setCiSettingsAttribute($value)
  {
    if (!empty($value)) {
      $value = Arr::undot($value);
    }

    $this->attributes['ci_settings'] = json_encode($value);
  }
}
```

```php 
# CrudController

CRUD::field('git.src.pid')->type('text')->fake(true)->store_in('ci_settings');
CRUD::field('git.src.path')->type('text')->fake(true)->store_in('ci_settings');
CRUD::field('git.app.pid')->type('text')->fake(true)->store_in('ci_settings');
CRUD::field('git.app.pipeline_token')->type('text')->fake(true)->store_in('ci_settings');
```

Thanks to Mutator I can switch from dot notation to clean JSON : 

```
# raw value : 
 [
  "git.src.pid" => "0091"
  "git.src.path" => "lorem/ipsumeee"
  "git.app.pid" => "rezr"
  "git.app.pipeline_token" => "eztz"
]

# modified and stored value : 
"{"git":{"src":{"pid":"0091","path":"lorem\/ipsumeee"},"app":{"pid":"rezr","pipeline_token":"eztz"}}}"
```

(and thanks to Accessor I can switch back to "Backpack compatible" format)

### Workaround

My workaround was to define custom `dotCustom` / `undotCustom` `Str::macro` functions and use `::` as separator.

**Comment by tabacitu** [comment]
@rroblik ... you're not gonna like this 😅  But we can't really do anything to support dot notation inside field names, because that already has a purpose in Backpack. It's to quickly define a relationship. See [one-to-one relationship](https://backpackforlaravel.com/docs/4.1/crud-fields#hasone-1-1-relationship) for an example.

**Comment by tabacitu** [comment]
Can you use `/` or something else?

**Comment by tabacitu** [comment]
@pxpm we should probably throw a better error in this case, right? One that would indicate to the user what is _actually_ happening - that the dev is trying to use a relationship field but we can't find that relationship. I say let's leave this issue open for that purpose, throwing a custom exception.

**Comment by rroblik** [comment]
> @rroblik ... you're not gonna like this 😅 But we can't really do anything to support dot notation inside field names, because that already has a purpose in Backpack. It's to quickly define a relationship. See [one-to-one relationship](https://backpackforlaravel.com/docs/4.1/crud-fields#hasone-1-1-relationship) for an example. It's also mentioned in [the docs for the `text` column](https://backpackforlaravel.com/docs/4.1/crud-columns#text-1) which is the most widely-used column, so A LOT of people might be using it, no way we can ever change what dots do.

😛 oh okay... I missed this part of the documentation. That's why error is in relationship code ! 
For sure I'm not loving it, as dot notation is like a "standard" notation 😞  but okay I keep my workaround with `::` ! 

Maybe those notation exception must be highlighted in documentation, at top !
