### ISSUE TITLE
[Feature Request] add support for `morphTo` inside `relationship` field

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4090]
# Feature Request

### What's the feature you think Backpack should have?

Ability to define a `relationship` field for a `morphTo` relationship. Take the examples we've just added to the demo (Petshop). You can assign Comments to Pets and Owners... but if you create a CRUD for comments... the closest you can get (by default) is this:

<img width="801" alt="Screenshot 2022-01-18 at 11 34 39" src="https://user-images.githubusercontent.com/1032474/149910268-52cf964b-0c0d-4ab5-8fe9-9d91c0b2afee.png">

But this isn't really helpful to the admin. As a dev, you have to 
- manually create a select for `commentable_type`, showing "Pet" and "Owner"
- create a custom field `commentable_id` that will show either Pets or Owners, depending on what's selected in  `commentable_type`

I think we should add a new field to relationship, let's call it `relationship.morphTo` or something. This new field would show (on the same line):
- a select for the `commentable_type`
- a select2 for the `commentable_id` (when type is changed, the options inside this one are changed too)

**As a developer, how would you use this?** Most of the time you'd just need to define

```php
CRUD::field('commentable')->models([
            \App\Models\Pet::class,            
            \App\Models\Owner::class,
]);
```

Behind the scenes, it will use that `relationship.morphTo` field we talked about, which will setup two subfields:
- commentable_type (a simple select)
- commentable_id (a custom select2, let's call this one `relationship.morphTo_select` for now, for clarity)

So what it will ACTUALLY DO is the same thing as if the dev defined:

```php
CRUD::field('commentable')->morphTypeField([
        'name' => 'commentable_type',
        'type' => 'select',
        'options' => [
            'App\Models\Pet' => 'Pet',
            'App\Models\Owner' => 'Owner',
        ],
    ])->morphIdField([
        'name' => 'commentable_id',
        'type' => 'relationship.morphTo_select',
        'models' => [
            \App\Models\Pet::class,            
            \App\Models\Owner::class,
        ]
    ]);
```

The idea behind the above is to:
- [ ] make zero changes to the Backpack core;
- [ ] add `relationship.morphTo` and `relationship.morphToId` fields;
- [ ] when the `commentable_type` select is changed, `commentable_id` will have its options changed using JS that is stored inside the `relationship.morphTo_select` field;
- [ ] if the dev wants to make the second select work with AJAX, they can replace it with a `relationship.morphTo_fetch` field (which will switch the AJAX URL it points to); 

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core, but not urgent.

**Comment by tabacitu** [comment]
Before we do any of the above, we should talk more about this, think of all the implications and basically write the docs for it. It's a cool feature, but fewer than 1% of all devs will ever need this, so it's low-prio.

**Comment by stevebeyatte** [comment]
+1

**Comment by tabacitu** [comment]
Heads up @pxpm - we have a good description for what you're working on here. Please reference it in your PR so we check these ideas too.

**Comment by adrienne** [comment]
Any progress on this @tabacitu @pxpm ? It's a breaking problem for me!

**Comment by tabacitu** [comment]
Progress report: Pedro has created a PR for this, that adds this. But it only supports simple selects (non-AJAX):
- https://github.com/Laravel-Backpack/CRUD/pull/4330
- https://github.com/Laravel-Backpack/PRO/pull/18
- https://github.com/Laravel-Backpack/demo/pull/388

He's now working on adding AJAX support (and polishing the syntax). We expect to have a solution launched for this by the end of the month 🎉

**Comment by tsun424** [comment]
Hi team, I used to have this `relationship`, `morphTo` working on V4, currently working on upgrading to V5 and the page is broken with 500 error `The relationship field does not support MorphTo at the moment, nobody asked for it yet`, cannot go ahead for this V5 upgrade, so keen on getting this resolved/supported as soon as possible, thanks.

**Comment by pxpm** [comment]
Hello @tsun424 
Until we merge the core support for morph to you can use `entity => false` to disable backpack behavior. 
Cheers

**Comment by tsun424** [comment]
Hi @pxpm , thanks for your response. 

Adding `entity => false` triggered another error: `Undefined array key "relation_type"`.

Currently from V5, if a field is defined as `relationship` type in a CrudController and it is `morphTo` relationship in the model, just got 500 error, whereas, it was working on V4.1, I'm feeling this is a regression.

**Comment by tabacitu** [comment]
Let's close this in favor of https://github.com/Laravel-Backpack/CRUD/pull/4579 - moving the conversation there as we're suuuper close to merging it 🎉
