### ISSUE TITLE
[Feature Request] `repeatable` field should put cursor on the first input of a new row

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4091]
# Feature Request

### What's the feature you think Backpack should have?

Every time a new row is added inside `repeatable`, the cursor should move to the first input/select/etc of that new row. This is the last missing piece to make the `repeatable` field keyboard-friendly.

### Have you already implemented a prototype solution, for your own project?

No, but maybe we can use the JS we have for the main form.

### Do you see this as a core feature or an add-on?

Core, default.

**Comment by maurohmartinez** [comment]
@tabacitu @pxpm What you guys think of this? [PR](https://github.com/DigitallyHappy/backpack-pro/pull/64)

![repeatable-input-focus](https://user-images.githubusercontent.com/33960976/176435484-c5fbaf01-5758-4949-92df-c96d95cde464.gif)

**Comment by tabacitu** [comment]
Whoohoo! So glad to finally see a solution to this, been nagging me for YEARS. Let's move the conversation inside the PR please.
