### ISSUE TITLE
[Bug] `relationship` with `hasMany` and subfields (pivot fields) can't delete empty rows

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4093]
# Bug report

### What I did

Inside the new demo entries, we have Owner hasMany Pet (with `role` on the pivot table). I go edit an existing Owner with no pets. Add a Pet. Remove that pet... can't do it, I get a javascript error.

### What I expected to happen

No error.

### What happened

JS error:

![2022-01-18 12 31 44](https://user-images.githubusercontent.com/1032474/149920734-ae90526f-9eb3-48ec-be47-f89d1dc3b64b.gif)

### What I've already tried to fix it

Nothing.

### Is it a bug in the latest version of Backpack?

4.2

**Comment by pxpm** [comment]
I've submitted #4096 that should fix this. Closing in favor of that one.
