### ISSUE TITLE
Use FormField classes for better API and reduce redundant code

### ISSUE THREAD

**Issue by axyr** [Laravel-Backpack/CRUD#41]
Right now a lot of field types have the same template, but only the `type="text | date | email "` is different.

If you want to change the layout of the fields, you need to override a lot of templates (for example if you want a .form-horizontal).

What about something like this:

```php
$fields = new FieldList(
    new EmailField('email', 'Email'),
    new DropdownField('status', 'Status', ['yes', 'no']),
    new TextField('name', 'Name') // 'Name' optional, so it will be taken from 'name'
);
```
instead of

```php
$fields = [
    [
        'type'  => 'email',
        'label' => 'Email',
        'name'  => 'email',
    ],
    [
        'type'  => 'select',
        'label' => 'Status',
        'name'  => 'status',
        'options' => ['yes', 'no']
    ],
    [
        'type'  => 'text',
        'label' => 'Name',
        'name'  => 'name',
    ]

];
```

For the EmailField you don't need a seperate template and the API for the Dropdown Field is perfeclty clear without need to refer to documenation when you have something like this (quick boiler plating) : 

```php

class DropdownField extends FormField
{
    protected $options = [];

    protected $type = 'select';

    public function __construct($name, $label, $options)
    {
        $this->options = $options;

        parent::__construct($name, $label);
    }
}

class EmailField extends TextField
{
    protected $type = 'email';
}

class TextField extends FormField
{
    public function view()
    {
        return view('fields.' . $this->template, ['field' => $this]);
    }
}

abstract class FormField
{
    protected $name;

    protected $label;

    protected $attributes = [];

    protected $classes = [
        'holder' => ['form-group'],
        'label'  => ['control-label'],
        'field'  => ['form-control'],
    ];

    protected $template = 'text';

    protected $type = 'text';

    public function __construct($name, $label)
    {
        $this->name  = $name;
        $this->label = $label;
    }
    
    public function setAttribute($attr, $value)
    {
        $this->attributesp[$attr] = $value;
        return $this;
    }
    
    public function addClass($class, $target = 'field') // ? field and holder?
    {
        $this->classes[$target][] = $class;
        return $this;
    }
```

**Comment by axyr** [comment]
Maybe its an option to let the FormFieldClasses spit out the array that is needed now instead of a view.
In that way you can use both and not need to change the complete API as it is now.

**Comment by tabacitu** [comment]
Hmm... I really like how this looks:
```php
$fields = new FieldList(
    new EmailField('email', 'Email'),
    new DropdownField('status', 'Status', ['yes', 'no']),
    new TextField('name', 'Name') // 'Name' optional, so it will be taken from 'name'
);
```

So, the way I see it:

PROs:
- syntax is easier to type and read;
- it allows a separation of logic from the blade files;

CONs:
- creating a custom field type for your project will imply creating 2 files instead of 1: 
    - the blade file
    - the ```class CustomField extends FormField```
- very very few fields actually have enough logic to need a separate class;

--

I think you're trying to solve the same problem I am through the SublimeText snippets (#31), right? Be able to write CRUD code faster. Wouldn't an editor plugin that would allow you to write CRUDs emmet-style be faster, but without changing the API and without needing the 2 files for one field?

**Comment by axyr** [comment]
Well, I went another route that uses Adam Wathans BootForm and keep it as plain as possible. this seems to work fine.

Well you don't really need a blade file, but with a method renderField(); you could return just the html for the field or a blade template.

**Comment by tabacitu** [comment]
@axyr , you've got me thinking. Maybe the best way to write the CRUD code is the most familiar way. The Laravel way. So wouldn't it make sense to make it as close as possible to the Schema builder?

Ideally, you should be able to copy-paste your schema and make a few changes. So that:

```php
Schema::create('articles', function (Blueprint $table) {
    $table->increments('id');
    $table->integer('category_id')->unsigned();
    $table->string('title');
    $table->string('slug')->default('');
    $table->text('content');
    $table->string('image')->nullable();
    $table->enum('status', ['PUBLISHED', 'DRAFT'])->default('PUBLISHED');
    $table->date('date');
    $table->boolean('featured')->default(0);
    $table->timestamps();
    $table->softDeletes();
});
```

turns into:

```php
$this->crud->setModel("App\Models\Article");
$this->crud->setRoute('admin/article');
$this->crud->setEntityNameStrings('article', 'articles');

$this->crud->addFields('create', function (CrudForm $form) {
    $form->increments('id');
    $form->select('category_id', 'App\Models\Category');
    $form->string('title');
    $form->string('slug');
    $form->text('content');
    $form->browse('image');
    $form->enum('status');
    $form->date('date');
    $form->boolean('featured');
});
```

What do you think? 

@cristiantone @Ghitu - what do you guys think?

**Comment by axyr** [comment]
I like the syntax, but I wonder how easy it will be to add extra fields for special use cases.

It looks a lot how like how this package add form fields : 

https://github.com/z-song/laravel-admin

**Comment by tabacitu** [comment]
Yup, that's where I got the idea from, z-song's admin.

You're right. I think it's a top priority for custom fields to be added as easily as they are now. Judging by the feedback I've gotten so far, this is the number one feature that attracts people to Backpack\CRUD - its extensibility. I guess you're right - I don't see a way to achieve this right now - both keep the extensibility AND add a way better syntax. I guess we should table the discussion - maybe we'll come up with a solution for v4.

**Comment by OwenMelbz** [comment]
@tabacitu you happy to close this off?

**Comment by tabacitu** [comment]
Yup, thank you. We'll keep this in mind for v4 - the nearest term when we can consider a syntax change.
