### ISSUE TITLE
Image Cropper for Adding to slider in laravel backpack

### ISSUE THREAD

**Issue by usmanhafeez147** [Laravel-Backpack/CRUD#410]
**# Image Cropper for Adding to slider in laravel backpack.**
I'm using Laravel Backpack for admin panel and made "slider_photo" crud manager. I want to make a Image Cropper when uploading image in "slider_photo" table to giving them specific size.

**Comment by OwenMelbz** [comment]
That's what the docs are for 😊

https://laravel-backpack.readme.io/docs/crud-fields#section-image

Although if you need any extra image manipulations then you can do that using laravels accessors/mutators!
