### ISSUE TITLE
[Bug] Bulk checkboxes don't shift-select from the bottom-up

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4117]
# Bug report

### What I did

Tried to select multiple bulk checkboxes (by keeping the shift key pressed):

### What I expected to happen

- when I select row 1, then row 10, all rows between them will get selected (good)
- when I select row 10, then row 1, the rows between them do NOT get selected (bad)

### What happened

<a href="https://www.loom.com/share/3981fa334d644ef1a282317f8fdc442c">
    <p>Bulk Checkboxes multi-select does not work from the bottom up - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/3981fa334d644ef1a282317f8fdc442c-with-play.gif">
  </a>

### What I've already tried to fix it

Nothing, this is a small bug that we can fix in 4.2.x.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 

Yup

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.0.14 (cli) (built: Dec 17 2021 22:07:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.14, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.80.0@8949a2e46b0f274f39c61eee8d5de1dc6a1f686b

### BACKPACK VERSION:
4.2.x-dev@b6f6a623506d68726e22e014b9ab89a119c97428
```

**Comment by pxpm** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4557
