### ISSUE TITLE
[Bug] setupCreateOperation called on any operation

### ISSUE THREAD

**Issue by guleswine** [Laravel-Backpack/CRUD#4126]
# Bug report

setupCreateOperation called on any operation.

For example:
If i want set default value for my field for Update View
![image](https://user-images.githubusercontent.com/23197378/151691108-f1cb5076-184d-4140-9a76-48ee8a1ca6cd.png)
setupCreateOperation call later and override this field.
Or i want to show one field for create operation and dont want show for update, but if the field is defined in CreateOperation
it will also show in UpdateOperation

### What I've already tried to fix it

i fount just one solution, wrap code inside CreateOperation in this statement
if(\Route::current()->getAction()['operation']=='create') {
}

### PHP VERSION:
PHP 7.4.26 (cli) (built: Nov 22 2021 09:47:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.69.0@545181da688db64fed6d8427e55f630a90ca0d32

### BACKPACK VERSION:
4.1.58@4e88dcd9a77804ef280c87c7fa2905f9378516b7

**Comment by tabacitu** [comment]
Hey @guleswine ,

That definitely shouldn't be happening. You can even see that in [the code for the Update operation](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/Operations/UpdateOperation.php), there is absolutely no mention of the word "create" there.

So whatever's happening here, it must be happening in your CrudControllers. Are you sure you're not calling `$this->setupCreateOperation()` inside your `setupUpdateOperation()` later on? Or perhaps in your `setup()` method?

You should be able to comment out the `CreateOperation` trait and use only the Update operation. If you can't do that, it means you're calling it somewhere in your setup.

**Comment by guleswine** [comment]
> Hey @guleswine ,
> 
> That definitely shouldn't be happening. You can even see that in [the code for the Update operation](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/Operations/UpdateOperation.php), there is absolutely no mention of the word "create" there.
> 
> So whatever's happening here, it must be happening in your CrudControllers. Are you sure you're not calling `$this->setupCreateOperation()` inside your `setupUpdateOperation()` later on? Or perhaps in your `setup()` method?
> 
> You should be able to comment out the `CreateOperation` trait and use only the Update operation. If you can't do that, it means you're calling it somewhere in your setup.

i commented setupCreateOperation and his trait, and all works fine.


Btw i use in this trait in controller:
\Backpack\CRUD\app\Http\Controllers\Operations\InlineCreateOperation;

And via debug operation at the time of the call  CreateOperation i see, setupInlineCreate call CreateOperation on any events in this controller

![image](https://user-images.githubusercontent.com/23197378/151692040-42d06fc2-a7c2-49dc-b8e2-0c84d997aed2.png)


P.S. Sorry for my english :)

**Comment by guleswine** [comment]
so, this behavior normal or will  be fixed? :)

**Comment by guleswine** [comment]
@tabacitu so, Is this behavior normal or will it be fixed?  :)

**Comment by pxpm** [comment]
@guleswine sorry for the time it took to come back here.

I submitted today a PR that will fix this, it's indeed a bug on our side and should be fixed. I will update you here when it gets merged. 

Thanks

**Comment by tabacitu** [comment]
Confirmed! Reviewed, needs changes.
