### ISSUE TITLE
Getting Image from database stored by Backpack image field

### ISSUE THREAD

**Issue by usmanhafeez147** [Laravel-Backpack/CRUD#415]
How to get image file in user-end from database that is stored by backpack image field and is encrypted having cropped information

**Comment by usmanhafeez147** [comment]
I used Image and it stores encrypted in database as image file name

**Comment by usmanhafeez147** [comment]
I also tried adding Mutator setImgeAttribute($value){} in photo model. I thing is not working

**Comment by OwenMelbz** [comment]
When you say encrypted, do you mean you're encrypting it yourself?

What normally happens is when you crop the image on the frontend, it sends a base64 encoded string to the server.

When it saves you need to add a mutator for your field.

If your field is called `image` then use `setImageAttribute`if its called `photo` call it `setPhotoAttribute` - if you do not understand how mutators/accessors work read here -> https://laravel.com/docs/5.3/eloquent-mutators#accessors-and-mutators

If you do not define a mutator for your field which will convert it to a file and return a string, it will save the base64 encoded version to the database.

**Comment by usmanhafeez147** [comment]
can you please send me example project  with backpack image field and showing it on home.blade.php user-front-end

**Comment by OwenMelbz** [comment]
You got $$$ to pay somebody to create an example project?

The documentation gives a working example in the admin. You need to learn how laravel works.

If you share your controller, model and database table scheme we can point out your mistake.

The front end is up to you using laravel. Backpack is an Admin.

**Comment by usmanhafeez147** [comment]
![image](https://cloud.githubusercontent.com/assets/24206206/22591143/c9b7e23a-ea34-11e6-9748-a1c399c369a4.png)
is this encrypted of image file of backpack

**Comment by tabacitu** [comment]
Well that escalated quickly :-)

@usmanhafeez147 , please use [the example in the documentation](https://laravel-backpack.readme.io/docs/crud-fields#section-image). Just checked it and it works perfectly, so it's definitely not a bug. 

If you're getting a base64 encoded image in the database, you must have missed a step in the documentation or used the base64_image field instead.

For your next support question, please [post on StackOverflow](https://stackoverflow.com/questions/tagged/backpack-for-laravel), like it says in [CONTRIBUTING.md](https://github.com/Laravel-Backpack/CRUD/blob/master/CONTRIBUTING.md). Really important we keep Github issues only for bugs, as it helps us make a squash bugs and create features faster.

Cheers!
