### ISSUE TITLE
[Bug] select2_multiple field send value null

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#4151]
# Bug report
The select2_multiple field send option "-" as null
### What I did
Created this field:

```
$this->crud->addField([
            'label'     => trans('crud.familyProduct.familyProduct'),
            'type'      => 'select2_multiple',
            'name'      => 'familyProducts',
            'entity'    => 'familyProducts',
            'model'     => "App\Models\FamilyProduct",
            'attribute' => 'name',
            'pivot'     => true,
            'select_all' => true,
            'options'   => (function ($query) {
                return $query->orderBy('name', 'ASC')->get();
            }),
            'tab' => trans('crud.service.head'),
       ]);
```
Then the "-" option can be selected:
![image](https://user-images.githubusercontent.com/8792209/152401634-08423158-38e5-4498-b012-1acf788ddf88.png)

### What I expected to happen

The "-" option cannot be selected

### What happened

Select the "-" option and an array with null value is sent to the request 
```
"familyProducts" => array:2 [[▼]()
        0 => null
        1 => "13"
      ]
```

And when save:

![image](https://user-images.githubusercontent.com/8792209/152401792-cb28c259-d116-4d80-9f12-ad67ff944309.png)

### What I've already tried to fix it

Im trying to validate in the request or a mutator

### Is it a bug in the latest version of Backpack?

yes

**Comment by pxpm** [comment]
Hey @aberaldo, thanks for the report.

This is already fixed in v5 of Backpack, that happened to be lauched today. Please read the [upgrade guide](https://backpackforlaravel.com/docs/5.x/upgrade-guide) it has some breaking changes, but it should not take much time to upgrade.

I will be closing this, let me know if you have any problems with the upgrade. 

Thanks,
Pedro
