### ISSUE TITLE
[Feature] Add `switch` field to `backpack/pro`

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4157]
I think we should move the toggle field type from [a separate package](https://github.com/DigitallyHappy/toggle-field-for-backpack)... to the `backpack/pro` repo. But if we're doing that, it'll be a good time to also make the colors and stuff easy-to-customize, like @promatik did on the corresponding "editable column".

**Comment by rroblik** [comment]
Even with a customization update this must not live in the Pro version but stay here, a simple free add on. Not any valuable feature in it !

**Comment by tabacitu** [comment]
Hmm you're right @rroblik ... once it's free... we can't really make it un-free. Don't know how I missed that. So the free `toggle` package stays there, no way for us to close-source it at think point. Thanks for the observation.

---

Ok then... but I _still_ want a supercharged field that does that. I want to be able to add switches to my admin panel instead of checkboxes, because that alone will make the form prettier, I think. And I want them to be customizable, to support as many variations as possible from [what we offer in Backstrap](https://backstrap.net/base/switches.html):
- MUST: easily change color;
- SHOULD: easily choose the text on the switch (eg. ON / OFF);
- SHOULD: easily choose an icon to show on the switch (eg. `la la-warning`);
- SHOULD: easily make it small / medium / large;
- COULD: easily change style (3d / 2d / square);
- COULD: easily make it outline (so it doesn't stand out as much);

So here's what we _can_ do:
- keep the `digitallyhappy/toggle-field-for-backpack` as it is; free and open-source;
- create a new field for `backpack/pro`, that we call `switch`;
 
Then people can use whatever they want, either the free `toggle` or the premium `switch`. People who use Backpack\CRUD have to install this additional package, which adds it but is not-so-feature-packed. People who use Backpack\PRO have it at hand always, and it's feature-packed. Everybody wins.

**Comment by ziming** [comment]
Kind of second @rroblik 

Given that the original code for this is contributed by the community and not a Backpack employee, putting this in pro without asking the original author if they are fine with it may not be a good idea.

I may not mind my markdown column (My 1st PR!) going into backpack pro for example, but we can't assume the same for the other past contributors.

**Comment by pxpm** [comment]
I second @ziming here. Avoid PHP reserved keywords at any cost.

All of the rest are said and done and I agree with. 

Call it `switcher` or something.

**Comment by promatik** [comment]
This feature is now at https://github.com/Laravel-Backpack/CRUD/pull/4463 🎉
