### ISSUE TITLE
display translatable field in select2_from_ajax

### ISSUE THREAD

**Issue by Bekzhan99** [Laravel-Backpack/CRUD#4160]
# Bug report

### What I did
![image](https://user-images.githubusercontent.com/47516570/152747503-d1dc678b-a516-4bc4-b286-5f2d140393da.png)

### What happened
cannot get the json value it returns the entire record {"title": {"fr":"title fr"...

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
Hey @Bekzhan99 ,

The fields itself will only show what the API is returning. What do you have for you API?

**Comment by Bekzhan99** [comment]
hi 
![image](https://user-images.githubusercontent.com/47516570/152752449-d837888d-41a8-4dde-bdd4-1f44db5ae332.png)
This?

**Comment by Bekzhan99** [comment]
![image](https://user-images.githubusercontent.com/47516570/152752590-101fa9c0-e37b-4fbb-a693-126503bb2f68.png)
![image](https://user-images.githubusercontent.com/47516570/152752622-cd7ba79a-9334-48e6-b67a-faf72922b4ea.png)

**Comment by Bekzhan99** [comment]
What needs to be shown?

Name of the cities of the selected country

What comes with api?

![image](https://user-images.githubusercontent.com/47516570/152756948-b389fe8b-5174-4d5c-8c8f-0ed128b16e5a.png)

**Comment by Bekzhan99** [comment]
Am I using the "select2_from_ajax" type correctly?

**Comment by tabacitu** [comment]
You can loop over the options in the API and set the `title` attribute to the string translated in the current locale, if `spatie/laravel-translatable` doesn't do it automatically. You can probably use one of their methods like `$item->getTranslation('title', app()->getLocale());`

Hope it helps!

PS. It's curious that `spatie/laravel-translatable` doesn't do that automatically though... I would have expected it to do so...

**Comment by Bekzhan99** [comment]
@tabacitu  Does the API necessarily work with the Paginite method? and then with the get method you can’t see the answer at all. And with paginite it sees the object but displays it.

**Comment by Bekzhan99** [comment]
![image](https://user-images.githubusercontent.com/47516570/152763805-6ff48cc8-0196-4d62-9501-16652111cceb.png)
Model City

**Comment by pxpm** [comment]
Hey @Bekzhan99 

Does your crud model have a `city()` belongsTo relation, i assume it does with `city_id` as foreign ? 

If so, try using the relationship field instead of manually defining the attributes:

```php
$this->crud->addField([
'name' => 'city',
'ajax' => true,
'data_source' => url('api/city'),
'attribute' => 'name',
'placeholder' => 'Select City',
'include_all_form_fields' => true,
'minimum_input_length' => 0,
'dependencies' => 'country_id'
]);
```

Let me know how it goes.
Pedro

**Comment by Bekzhan99** [comment]
thank you. The code works with the type relationship

**Comment by pxpm** [comment]
Yeah, relationships have got some extra love in regards of functionality. I will leave this open and discuss with @tabacitu if we should do something about it in the select2_from_ajax field. 

In the meantime, I noticed that you are using `include_all_form_fields`, in this scenarios it's better to use the method `POST`. Maybe it works fine in this simple form with GET, but if you do the same in a HEAVY (lot's of fields) form, you will probably hit the limit of the GET parameters, so I think it's better if you get used to when including other form fields, use the method POST instead of GET. (you need to change API endpoint to accept POST ofc).

Just talking from experience, it happened to me, and lead to have the `method` configurable. 👍 

Cheers

**Comment by tabacitu** [comment]
@Bekzhan99 I've just merged @pxpm 's PR which brings "auto-translatable" functionality to the `select2_from_ajax` and `select2_from_ajax_multiple` fields. Assuming you're already running Backpack v5, after you do a `composer update backpack/crud` to get the latest version, it should "_just work_". No workarounds needed in your API.

Let us know if it doesn't. Thanks for submitting this.
Cheers!
