### ISSUE TITLE
[Bug] Implement some of Scrutinizer's suggestions

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4162]
After the v5 launch, our perceived code quality has dropped, from 9.08 to 8.64:

![Screenshot 2022-02-08 at 09 33 25](https://user-images.githubusercontent.com/1032474/152953000-8a179ab3-aa71-4507-941f-d98685cde7f1.png)

![Screenshot 2022-02-08 at 10 10 33](https://user-images.githubusercontent.com/1032474/152952993-eedcdc64-11e8-4faf-8b14-ddcc9c26e4c5.png)

We should take a look at what we've done to deserve this criticism from Scrutinizer 😅 and see what (if anything) we should do about it. I liked that we were over 9 before. And some of its suggestions are sensible.

**Comment by ziming** [comment]
I hardly see Scrutizner being used nowadays in PHP packages. Not sure how relevant it is now.

how about installing larastan and rector php in dev-develop and try to push for higher PHPStan levels in areas where possible? alternatively vimeo/psalm but their laravel plugin updates seem slower
