### ISSUE TITLE
After upgrade the table views have changed (for worse)

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/CRUD#4165]
# Bug report

### What I did

Upgraded to 5.0 from 4.1

### What I expected to happen

Table views to basically remain the same

### What happened

Table views have changed: the search box moved, details buttons appeared in place of the "three dots" and spacing in the page size selector has disappeared:
![image](https://user-images.githubusercontent.com/12016131/153035928-fc174bed-3bca-4d0e-a42b-2f42afeb276f.png)

### What I've already tried to fix it

Try to find an explanation in the docs, not found.

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.9 (cli) (built: Jul  5 2021 13:33:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.82.0@411d5243c58cbf12b0fc89cab1ceb50088968c27

### BACKPACK VERSION:
5.0.0@c4eb4aeb55dfaf29ecd3f5e0e35ba4321d9c004a

**Comment by malle-pietje** [comment]
The CSS for the "new" details button appears to be coming from this file:
``packages/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css``

**Comment by taenzerme** [comment]
Fixed it for me!, Thanks!

**Comment by malle-pietje** [comment]
Thanks @pxpm , I will try that first thing tomorrow. I did indeed publish the assets when troubleshooting some CSS earlier on.

**Comment by malle-pietje** [comment]
@pxpm fixed it for me as well. Thanks!
