### ISSUE TITLE
create states field depends on country field

### ISSUE THREAD

**Issue by mepawan** [Laravel-Backpack/CRUD#417]
Hi,

I have used your  backpack crud package. Its really fantastic package. Thanks for this wonderful thing.

I want to create an entity with add entity form like country field and states field but states list depends on country field. 

can you please guide me to achieve this. 

thanks,

**Comment by tabacitu** [comment]
Hi,

Thanks!

I think the best way to go would be to create a custom field type, which would include both fields and the javascript they need. Clean and easy to do.

Cheers!
