### ISSUE TITLE
[Bug] Cant store relationship (select 1-n) in 5.0.2 free version

### ISSUE THREAD

**Issue by busaku** [Laravel-Backpack/CRUD#4171]
# Bug report

### What I did

Add "select" field to create and update operation()

### What I expected to happen

I can save the data

### What happened

I cant save the data

### What I've already tried to fix it

Testing all addField([ // settings])

### Is it a bug in the latest version of Backpack?

yes 5.0.2

### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 26 2022 16:40:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.0.1@afeb58d019b203ecb1a1c4063a66a029ea6bea63

### BACKPACK VERSION:
5.0.2@a118a414770e6719732c7629f939d4f9337f5433

Soooo,
My relationship in Rescuer Model:
return $this->hasOne(RescuerType::class, 'id', 'rescuer_type_id');
(Worked in laravel only)

Settings to the field:
```
$this->crud->addField([
            'label' => 'Typ',
            'type' => 'select',
            'name' => 'rescuer_type_id',
            'entity' => 'rescuerType'
        ]);
```
        
What i got i try to save a new or an updated rescuer:
**_Call to undefined method App\Models\Rescuer::rescuer_type_id()_**

So, i ment out, that he try to use the "name" as the relation-ship function in Rescuer.
But the docs says:
```
[  // Select
   'label'     => "Category",
   'type'      => 'select',
   'name'      => 'category_id', // the db column for the foreign key

   // optional
   // 'entity' should point to the method that defines the relationship in your Model
   // defining entity will make Backpack guess 'model' and 'attribute'
   'entity'    => 'category',

   // optional - manually specify the related model and attribute
   'model'     => "App\Models\Category", // related model
   'attribute' => 'name', // foreign key attribute that is shown to user

   // optional - force the related options to be a custom query, instead of all();
   'options'   => (function ($query) {
        return $query->orderBy('name', 'ASC')->where('depth', 1)->get();
    }), //  you can use this to filter the results show in the select
]
```

So, name should be the foreignkey. And entoty should be the relation-ship model.

if i just use this settings:
```
$this->crud->addField([
            'label' => 'Typ',
            'type' => 'select',
            'name' => 'rescuerType',
        ]);
```

(Caus u think well, than i just use the relationship function.) i got:
_**array_key_exists(): Argument #2 ($array) must be of type array, string given**_
File: vendor/backpack/crud/src/app/Library/CrudPanel/Traits/FakeFields.php:59

In Backpack version 4.1 i works well.. anybody got an idea?

Edit: I forgot, the form works well. i got an selection-box with the correct relation-ship values from the RescuerType table. Only on store the data, i got the error

**Comment by pxpm** [comment]
Hello @busaku 

I don't think this is making sense to me. The relation you show is `hasOne` (1-1) and like the field says, it should be used in a `BelongsTo` (1-n).

So if you have `rescuer_type_id` in your `Rescuer` model, you sould be using:

```php
public function rescuerType() {
    return $this->belongsTo(RescuerType::class, 'rescuer_type_id');
}
```

Let me know if that relation was the problem.

Pedro

**Comment by busaku** [comment]
Hey @pxpm

so.. it works. but now it doesnt make sense to me :D
but thank you ;)

paD
