### ISSUE TITLE
[Bug] Too few arguments to function Illuminate\Database\Eloquent\Relations\HasOneOrMany

### ISSUE THREAD

**Issue by dilneiss** [Laravel-Backpack/CRUD#4178]
# Bug report

### What I did

Acessed create page from a crud having relation to another object

### What I expected to happen

Open the page

### What happened

Get this error: 
Too few arguments to function Illuminate\Database\Eloquent\Relations\HasOneOrMany::__construct(), 0 passed in D:\xampp\htdocs\backpack\vendor\backpack\crud\src\app\Library\CrudPanel\Traits\Relationships.php on line 345 and exactly 4 expected

### What I've already tried to fix it

Input an attribute named entity in my  array

### Is it a bug in the latest version of Backpack?
yes, backpack/crud 5.0.3 and backpack/pro 1.0.7

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version
backpack/crud 5.0.3
backpack/pro 1.0.7
Laravel 9.0.2
PHP 8.0.11
DB: Postgresql

When I run ```php artisan backpack:version``` the output is:
PHP 8.0.11 (cli) (built: Sep 21 2021 18:26:06) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.11, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.0.2@4c7cd8c4e95d161c0c6ada6efa0a5af4d0d487c9

### BACKPACK VERSION:
5.0.3@c14eaca0d10c3a37280786d65cebf735235850d6

![image](https://user-images.githubusercontent.com/4564667/153542126-5a779784-f947-4d67-902a-24fc2b211c22.png)
![image](https://user-images.githubusercontent.com/4564667/153542405-f940dd73-c285-4e56-ac51-e0b4636b9024.png)

**Comment by malle-pietje** [comment]
Exact same issue here when using a BelongsTo relationship when setting up custom searchLogic for a column.

**Comment by tabacitu** [comment]
Thanks guys! @pxpm Looks like our fix for fields in 5.0.3... broke the columns 😅 Could you please take a look?

**Comment by malle-pietje** [comment]
OK, let me share the relationship parts of the Models here.

Customer:
```php

    /**
     * all invoices for this customer
     *
     * @return HasMany
     */
    public function invoices(): HasMany
    {
        return $this->hasMany('App\Models\Invoice');
    }
```
Invoice:
```php
    /**
     * the customer this mandate belongs to
     *
     * @return BelongsTo
     */
    public function customer(): BelongsTo
    {
        return $this->belongsTo('App\Models\Customer');
    }
```
InvoiceCrudController->setupListOperation():
```php
        $this->crud->addColumn(
            [
                'name'     => 'customer_id',
                'label'    => __('invoices.customer'),
                'escaped'  => false,
                'type'     => 'closure',
                'function' => function($entry) {
                    $admin_id = Config::get('settings.xyz_administration_id');
                    return $entry->customer->moneybird_name . ' <a href="https://xyz.com/' . $admin_id . '/contacts/' . $entry->customer->xyz_customer_id . '" target="_blank"><i class="las la-external-link-alt"></i></a>';
                },

                'searchLogic' => function ($query, $column, $searchTerm) {
                    $query->orWhereHas('customer', function ($q) use ($column, $searchTerm) {
                        $q->where('xyz_name', 'like', '%'.$searchTerm.'%');
                    });
                }
            ],
        );

```

**Comment by malle-pietje** [comment]
@pxpm I manually patched the Relationships Trait per your PR and it fixes the issue. Thanks for the quick fix!

**Comment by tabacitu** [comment]
Pfiew! Merged & tagged https://github.com/Laravel-Backpack/CRUD/pull/4181. So a `composer update` should fix it for you guys.

Thanks again for submitting this 🙏

**Comment by dilneiss** [comment]
thanks, problem solved :)
