### ISSUE TITLE
How to use multi language feature

### ISSUE THREAD

**Issue by petyots** [Laravel-Backpack/CRUD#418]
Hello, i saw the multi language branch was merged in 3.2 today but i can't find any information how to enable it or how to use it. Can you please point me to some resources or idk something that is showing how to work with it. Thanks in advance

**Comment by c1t1zen** [comment]
is it possible to use multi language?
i can not see this feature?

**Comment by tabacitu** [comment]
Hi guys. For future reference / others that reach this thread, here are [the docs for multi-language CRUDs](https://laravel-backpack.readme.io/docs/advanced-features#section-translatable-models-and-multi-language-cruds).

Cheers!

**Comment by c1t1zen** [comment]
Thank you tabacitu
it does not support mysql 5.5 +
most shared hosting support mysql 5.5+ versions

**Comment by OwenMelbz** [comment]
@c1t1zen what makes you think it does not work with 5.5?

**Comment by c1t1zen** [comment]
i'm not sure if i can query local if my database does not support json object data type

all my fields are varchar,text
how can i query ?

**Comment by OwenMelbz** [comment]
Right okay, well the easiest recommendation would be to upgrade your databases as running old software will just make it hard to use new features. MySQL 5.5 was officially discontinued 2 years ago

The translations use the spatie translation system https://github.com/spatie/laravel-translatable/blob/master/README.md they also suggest MySQL 5.7 but you could read their documents about how to make it work with unsupported MySQL versions 

You would be best to find a work around if you can't upgrade, or create your own custom methods

**Comment by c1t1zen** [comment]
this feature only support mysql 5.7 and php 7
else you can not use this feature at all 
you can not insall spatie translatable

**Comment by OwenMelbz** [comment]
Yes, MySQL 5.5 OLD. No support. No help, no good.

MySQL 5.7 new, supported and good.

You cannot put new technology, on old technology. If you want to use it. Upgrade or make a work around.
