### ISSUE TITLE
[TYPO] Undefined variable $path

### ISSUE THREAD

**Issue by dickalexei** [Laravel-Backpack/CRUD#4183]
It's a tiny one and i think it's self-explained :)

https://github.com/Laravel-Backpack/CRUD/blob/c7c74166244f7995a07abb83f2a83e914e515c9f/src/app/Library/CrudPanel/Traits/Views.php#L295

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/4184 - will tag & merge in a few minutes.

Thank you @dickalexei !
