### ISSUE TITLE
Bulk actions in ListOperation not working when using Mobile Safari

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/CRUD#4188]
# Bug report

### What I did

Tested multi-select in the demo on an iPad running iOS 15.2.1

### What I expected to happen

For it to work like it does on Chrome, FF, and Edge on Windows 10/11. 

### What happened

Didn’t work. Selecting a checkbox in footer or headers only selects that checkbox.

### What I've already tried to fix it

Also Chrome on iOS has this issue.

### Is it a bug in the latest version of Backpack?

I’m not sure but believe this worked with BackPack version 4.1.

### Backpack, Laravel, PHP, DB version

See what the demo is running at.

**Comment by malle-pietje** [comment]
FYI: same behavior observed in a project I’m working that is at 5.0.6.

**Comment by pxpm** [comment]
@tabacitu I need your help here debugging this one and #4232 

**I can confirm that they are bugs** by testing with browserstack.com . But the free version have a 1minute cap that I can't do much to work with, it will probably be easier for you in a native machine.

I tested with safari 15.

**Comment by niladam** [comment]
hey @tabacitu - i'm being affected by this and it's not just on mobile Safari. It affects all versions of Safari for some reason. Can you maybe please have a look at this ?

**Comment by tabacitu** [comment]
Sorry for the delay @niladam - we're on it. We've tested and can confirm it's happening. 

It's one of those weird ones - apparently in `bulk_actions_checkbox.blade.php`: 

```js

    if (typeof addOrRemoveCrudCheckedItem !== 'function') {  // THIS ALWAYS RETURNS FALSE IN SAFARI 
        function addOrRemoveCrudCheckedItem(element) {
            crud.lastCheckedItem = false;

```

I've spent quite a bit of time trying to figure out WHY that is happening, but with no result. 

I'm currently putting out a big fire, will return to this later today.

Thank you for your patience.

**Comment by tabacitu** [comment]
Done! Fixed in 5.0.10 thanks to https://github.com/Laravel-Backpack/CRUD/pull/4255 

Please run a `composer update` and it should work fine for you in Safari. Let us know if it doesn't. Thanks for reporting this - and for the patience 🙏

**Comment by malle-pietje** [comment]
Thanks @tabacitu I will check this right away.

**Comment by niladam** [comment]
Thank you for this @tabacitu. I can confirm the issue no longer appears :)
