### ISSUE TITLE
[Bug] `select2_multiple` inside a tab doesn't render properly unless that tab is selected on page load

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#4194]
# Bug report

<img width="191" alt="image" src="https://user-images.githubusercontent.com/1346672/153919417-2a41e611-75a6-4d5d-a58c-72382ac59b84.png">

### What I've already tried to fix it

Will have a dig around and submit a PR if I can work it out.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.0.15 (cli) (built: Jan 21 2022 04:49:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.0.2@4c7cd8c4e95d161c0c6ada6efa0a5af4d0d487c9

### BACKPACK VERSION:
5.0.6@2be4ff8407259f528a3541f0569ce156bab63165
```

**Comment by pxpm** [comment]
Addressed in #4201 !

Thanks again @olipayne 🙏
