### ISSUE TITLE
[Bug] php artisan view:cache throws Symfony\Component\Finder\Exception\DirectoryNotFoundException 

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#4197]
# Bug report

### What I did

php artisan view:cache in my deploy script

### What I expected to happen

Everything to go smoothly like before

### What happened

Symfony\Component\Finder\Exception\DirectoryNotFoundException 

.../resources/views/vendor/backpack/pro directory does not exist

### What I've already tried to fix it

Didn't do anything

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 8.1.1 (cli) (built: Jan  8 2022 08:22:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.0@29bc8779103909ebc428478b339ee6fa8703e193

### BACKPACK VERSION:
5.0.6@2be4ff8407259f528a3541f0569ce156bab63165

**Comment by pxpm** [comment]
I got the same with devtools. 

![image](https://user-images.githubusercontent.com/7188159/154037892-ce124f89-752a-437f-8f12-4ae108cf6db0.png)

I am investigating. Thanks @ziming

**Comment by tabacitu** [comment]
And I got the same with `revise-operation`.

**Comment by tabacitu** [comment]
I could fix this by checking if the directory exists (for the published views) in the ServiceProvider - see https://github.com/Laravel-Backpack/revise-operation/pull/18/files for a public PR for this. What I don't understand is WHY this is needed now... what change in Laravel's inner workings to require this.

@pxpm let me know if you think it's ok to do that, for revise, pro and devtools.

Thanks @ziming for reporting it!

**Comment by tabacitu** [comment]
Here are all the PRs:
- `backpack\revise-operation` - https://github.com/Laravel-Backpack/revise-operation/pull/18
- `backpack\devtools` - https://github.com/Laravel-Backpack/DevTools/pull/273
- `backpack\pro` - https://github.com/DigitallyHappy/backpack-pro/pull/6

I'll let @pxpm take a look too, see if he finds a reason or a better solution, then merge them later today.

**Comment by pxpm** [comment]
Sure @tabacitu , please merge them all. I've found this solution too and tested it.

I was just about to create the last fix for revise when I saw your PR.

![image](https://user-images.githubusercontent.com/7188159/154042624-e03d06f3-51fc-48e9-ae73-1a99d1a7bf02.png)

Both worked on same thing 🙃 Just gona delete my local branches 👍 

Going to close this! Thanks @ziming

**Comment by tabacitu** [comment]
Ugh... sorry for that Pedro - my bad. Saw you put your face on it after having already created the PRs. Done - all merged and tagged.

**Comment by chaicai333** [comment]
the editable-columns package still appear to have this bugs

**Comment by chaicai333** [comment]
> the editable-columns package still appear to have this bugs

@tabacitu

**Comment by tabacitu** [comment]
Ouch! Done, it's fixed, a `composer update backpack/editable-columns` should do it for you now. 

Thanks for the bump @chaicai333 , it somehow slipped through the cracks.
