### ISSUE TITLE
Hidden Image doesn't update on crop event

### ISSUE THREAD

**Issue by spoyntersmith** [Laravel-Backpack/CRUD#4199]
https://github.com/Laravel-Backpack/CRUD/blob/0ad069c860ea8d34e3fd18317b68c4b98f432855/src/resources/views/crud/fields/image.blade.php#L283-L302

I believe `$mainImage.trigger('cropend');` could be added to trigger this behaviour

Current behaviour example: clicking zoomin/zoomout when crop is true doesn't update the hidden image value that will be posted.

**Comment by tabacitu** [comment]
Thank you @spoyntersmith ! We've just merged the PRs for both v4.2 and v5, and they'll be released on Monday with a few more bugfixes.

Thanks again for reporting this and finding the fix!
