### ISSUE TITLE
Add checkbox for multi-row selections

### ISSUE THREAD

**Issue by pushamaku** [Laravel-Backpack/CRUD#420]
Hi all,

Is there an easy way to add this functionality as in the link below?

http://www.gyrocode.com/projects/jquery-datatables-checkboxes/

I'd like to have that so I can run actions on multiple items instead of clicking the action on each row item.

Thanks for any input :)

**Comment by viktorivanov** [comment]
I am seeking for something similar, but looks like our beloved @tabacitu is working on it [#37](https://github.com/Laravel-Backpack/CRUD/issues/37)

**Comment by tabacitu** [comment]
Hi guys. Haven't made any progress on this yet. Just closing duplicate issues. Let's keep the entire discussion inside the thread @viktorivanov mentioned.

Cheers!
