### ISSUE TITLE
[Bug] Relationships have no order and can break model events in custom scenarios

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4206]
# Bug report

### What I did

I have two relations (relationA, relationB) in my model `MainModel`.

In `MainModel`, I have a model event setup in boot for creating:

```php
//pseudo code
static::creating(function($item) {
    if (!isset($item->relationB) {
        RelationBModel::create();
    }
}
```

My crud for MainModel have 3 fields:
```php
CRUD::field('name');
CRUD::field('relationA');
CRUD::field('relationB');
```

So I fill out the name, relationA, and leave relationB empty. 

When creating the model, checking if `isset($item->relationB)` would return null, as it was not filled in form and would create the relationB manually. 

But the `relationA` is saved first (and creates relationB), so after when crud save relationB (null) it will erase the previously created relationB in relationA creation. 

### What I expected to happen

I expected that relationB would not be deleted after beeing manually created. But CRUD can't be aware of that.

### What I've already tried to fix it

There are two solutions I think can solve this problem:

- change field order in crud panel definition (meehhh solution 🙅 )
```php
CRUD::field('name');
CRUD::field('relationB');
CRUD::field('relationA');
```
- introduce `createPriority` for `relationship` type fields, that way you could say to first handle relationB (it was empty, nothing will happen), then handle the relationA that will create the relationB as default.

```php
CRUD::field('name');
CRUD::field('relationA');
CRUD::field('relationB')->createPriority(1);
```

### Is it a bug in the latest version of Backpack?

yes it is ...

**Comment by tabacitu** [comment]
I don't think this is a bug, to be honest. It's just the way it is... when dealing with model events, you as a developer have to take into account the ORDER in which the relations are created. 

I think that order is already intuitive... they are created in is the order of the fields...

Your conditional in the pseudocode could just as well take account of this fact... right? Maybe something like this:

```php
//pseudo code
static::creating(function($item) {
    if (!isset($item->relationB && !request()->has('relationB')) {
        RelationBModel::create();
    }
}
```

I believe no solution will be perfect here - _even if_ you order B after A... then you cannot condition A depending on B. 

I think we should do nothing about this. The way I see it... it's a niche use case, where the developer should write a better condition, taking into consideration the order relations are saved in. I'd rather add documentation, than a feature for this - it's much more future-proof.

**Comment by pxpm** [comment]
@tabacitu As you can see, you can't do it like that either! Request will have `relationB => null` because the field is empty. That would do the same I described, It would create the `relationB` when not present in request, and then after backpack will try to create the `relationB` from the crud field (empty) and will delete the one you manually created. 

I agree that the field order is a very good base default, but in this scenario it will FORCE me to have the fields in a pre-determined order (read: **forcing UI change**, I don't really care about the order in the controller, but I do care about the order they are displayed). 

So I think our fields are more responsible (given that they represent the relationship and the interface) than what they should. 
- display the form fields with order (addField order)
- create the relationships with order (addField order)

It's two separate things but we have them tied together in the same order. I get your concerns about "the perfect" solution, but I don't think it makes sense not taking care of this.  It's inconsistent. Maybe we need to find the perfect solution then, that covers all use cases with minimal effort.

What about:
```php
//pseudo code
static::creating(function($item) {
    if(is_null($item->relationA) {
        RelationAModel::create();
        CRUD::removeRelationship('relationA'); // removes the relationship from subsquent parseInputs() so it would not be created
    }
    if (!isset($item->relationB && !request()->has('relationB')) {
        RelationBModel::create();
       CRUD::removeRelationship('relationB'); // removes the relationship from subsquent parseInputs() so it would not be created
    }
}
```
Does it make sense ? `CRUD::removeRelationship('relationB')` would add into a panel property, and we use that property to prevent some relations from creating, even if they are in request ? 

So basically we introduce a way to prevent backpack from creating relationships. When we go create `relationA` we check if it's not present in `removedRelationships` . 

This solution would cover all use cases in this scenario, and will open the possibility to some un-seen in future that required "ignoring" certain relations if certain conditions are met. 

PRO:
- We keep the order from addField.
- No need to change the field order. 

CON: (maybe?)
- dealing with "panel relations" in "raw model events", making model "aware" of crud (technically it already is by using CrudTrait).

This example I gave you is very common I think, I personally use alot of model events, **I think I did not get into this trouble because probably before v5, overriding the `store()` and `update()` was kind of mandatory if you wanted to do something more with relationships**. 

Let me know if you still think this shouldn't be looked at, I guess it will pop-up more now since people should not be required to override the backpack methods to create the relationships, so the fields order got a "promotion" from "some importance" (display the fields) to "very important" (display the fields and create complicated relationships). 

Pedro

**Comment by tabacitu** [comment]
All in all, I think this is overoptimization to be honest. We've lasted 4 years with workarounds needed for removing stuff some colums from the Show operation. So I think this issue is super-minor and can be postponed. I can't say the WON'T label is appropriate, but COULD... yeah, definitely, no more than that.

---

I feel like `CRUD::removeRelationship()` is pretty difficult to understand, and limited to this particular need. It doesn't fix the root cause - the impossible conditional.

This is a problem only inside model events so... how about using a different event? Is there one that would fix the problem? You used `Product::creating()` in your example, but you could have used `Product::created()`. That still doesn't fix the problem, I get it. But maybe what we _should_ do is have Backpack add some events along the saving process. Then people could use the backpack model events, instead of Laravel's... so maybe:
- `Product::creatingRelationships()`
- `Product::createdRelationships()`
- `Product::updatingRelationships()`
- `Product::updatedRelationships()`

Would that solve it? Using the `createdRelationship` event instead of `create`?

**Comment by pxpm** [comment]
Closing this, I don't see us doing this anytime soon or later.
