### ISSUE TITLE
[Bug] Cannot find 'image' field view in any of the regular locations.

### ISSUE THREAD

**Issue by 0x004d4m** [Laravel-Backpack/CRUD#4216]
# Bug report

### What I did

```php
class CarTypeController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;

    public function setup()
    {
        $this->crud->setModel("App\Models\CarType");
        $this->crud->setRoute("admin/CarTypes");
        $this->crud->setEntityNameStrings('Car Types', 'Car Types');
    }

    protected function setupListOperation()
    {
        $this->crud->setFromDb();

        $this->crud->setColumnDetails('image',[
            'label' => "image,
            'name' => "image",
            'type' => 'image'
        ]);
    }

    protected function setupCreateOperation()
    {
        $this->crud->setValidation(CreateRequest::class);
        $this->crud->addfield([
            'label' => "Image",
            'name' => "image",
            'type' => 'image'
        ]);
    }
}
```

### What I expected to happen

to find image upload filed in create form

### What happened
![Untitled](https://user-images.githubusercontent.com/47286140/154802573-3dead6ca-8a62-43d2-82a4-aaf67b100106.png)

Cannot find 'image' field view in any of the regular locations.
And image.blade.php is not found in fields folder

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.1@bddba117f8bce2f3c9875ca1ca375a96350d0f4d

### BACKPACK VERSION:
5.0.7@bf44be0ab24d2254bc266609ee697136f1a8bc4a

**Comment by tabacitu** [comment]
Hi @0x004d4m ,

This is because the `image` field is a PRO field. You need to [purchase and install `backpack/pro`](https://backpackforlaravel.com/pricing) in order to use it.

I've opened an issue so that we show clearer error message when a dev tries to do that - see https://github.com/Laravel-Backpack/CRUD/issues/4196. I'm not happy with the solution, but... is seems like it's something we gotta do, I imagine it was very frustrating to see this and have no idea how to fix it.

Cheers!

**Comment by 0x004d4m** [comment]
ok thanks for clarifying that.
