### ISSUE TITLE
[Feature Request] MorphTo relationship

### ISSUE THREAD

**Issue by KevinCassier** [Laravel-Backpack/CRUD#4223]
# Feature Request

### What's the feature you think Backpack should have?

A way to integrate the morphto relationship in list, update and create pages.

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core feature

Thanks for your amazing work !

**Comment by pxpm** [comment]
Hey @KevinCassier thanks for the suggestion.

We already talked about this, and definatelly we want a solution for this. I expect to finish working on previous bugs during this week, and could start working on this after, we will update when we have news 👍 

Thanks again 🙏

**Comment by KevinCassier** [comment]
Thanks @pxpm !

**Comment by tabacitu** [comment]
Totally! Let's close this in favor of https://github.com/Laravel-Backpack/CRUD/issues/4090 , to keep all conversation in one place.
