### ISSUE TITLE
in Tinymce is not present bullet list button[Bug] 

### ISSUE THREAD

**Issue by soluzione-software** [Laravel-Backpack/CRUD#4227]
# Bug report
in Tinymce is not present bullet list button
### What I did
i use this fields in crud:
[
                'name'  => 'description',
                'label' => __('description'),
                'type'  => 'tinymce',
                'options' => [ 'plugins' => 'image,link,media,anchor,lists,advlist'],
            ],
??

### What I expected to happen
as in the documentation i expected that appear bullet list button

When I run ```php artisan backpack:version``` the output is: 5.0.7 (PRO)

**Comment by pxpm** [comment]
Hello @soluzione-software . Thanks for the report. 

This is indeed a documentation issue. I've just submitted https://github.com/Laravel-Backpack/docs/pull/325 to update the documentation. I also added some aditional information that would help you in your specific scenario. 

Thanks again, and sorry for the bad experience, I've tested your bullet list scenario and it works with the updated documentation so I am just closing this. 

🙏
