### ISSUE TITLE
Set session expiration time

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#4228]
Is there a way to customize session expiration time?

Also i know that the session expire if the user click some button it is redirected to login. But what about redirecting automatically if the session expires? Despite of clicking or not a button. There is a way to achieve this?

Thanks

**Comment by pxpm** [comment]
@aberaldo have a look `config/session.php` to configure laravel session expiration time. Also there are some php settings in your `php.ini` that you migth want/need to tweak regarding php garbage collection for session based configs: 

`session.cookie_lifetime, session.gc_maxlifetime`

I think this is not related to Backpack, so I am going to close this, if you think I am wrong, and alot of times I am, please re-open 👍 

Pedro

**Comment by aberaldo** [comment]
@pxpm thanks. But what about when the expiration time is reached redirecting automatically to the login screen, despite of clicking or not any button?

Thanks
