### ISSUE TITLE
Bulk select not working on ListOperation in Safari

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/CRUD#4232]
# Bug report

### What I did

Using an application i'm developing i tried to bulk delete/clone in the demo application. Using Safari 15.3, macOS 12.2.1. This affects the DEMO version as well (https://demo.backpackforlaravel.com/admin/product) for example.

### What I expected to happen

Work

### What happened

Didn't work.

### What I've already tried to fix it

-

### Is it a bug in the latest version of Backpack?

I am currently on 5.0.6 and unable to test this on 5.0.7 or 5.0.8 but i assume that yes, this is still present as the demo is also affected.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 21 2022 04:47:46) (NTS)

### LARAVEL VERSION:
v9.1.0

### BACKPACK VERSION:
5.0.6

As a sidenote, there's [another issue similar to this](https://github.com/Laravel-Backpack/CRUD/issues/4188) (#4188), but that's apparently happening in Safari for iOS (and therefore Chrome and any other browser on iOS)

Here's a short recording about the issue. Please note the warning alert in the top right.

https://user-images.githubusercontent.com/4151765/155949388-4ea781ad-f685-43ba-9a0b-3c83973962cb.mov

**Comment by niladam** [comment]
@tabacitu can you please have a look at this as well ?

**Comment by pxpm** [comment]
Hey @niladam 

I've just tested and confirmed the bug. I pinged @tabacitu  here https://github.com/Laravel-Backpack/CRUD/issues/4188#issuecomment-1055529476

Thanks for the report.
