### ISSUE TITLE
[v5 Breaking Change] unable to store/update related field (one-to-one relationship)

### ISSUE THREAD

**Issue by kiddtang** [Laravel-Backpack/CRUD#4240]
# Bug report

### What I did

update from Backpack 4.1 to v5

### What I expected to happen

After the upgrade, this functionality breaks...

**My Models:**

Employee  --- hasOne `profile()` ---> EmployeeProfile
Employee  <--- belongsTo `employee()` --- EmployeeProfile 

**My CRUD field:**
```
$this->crud->addFields([
            [
                'name'  => 'profile.address_1',
                'label' => 'Address (Line 1)',
                'type'  => 'text',
                'tab'   => 'Profile',
                'wrapper' => ['class' => 'form-group col-md-12']
            ],
            [
                'name'  => 'profile.address_2',
                'label' => 'Address (Line 2)',
                'type'  => 'text',
                'tab'   => 'Profile',
                'wrapper' => ['class' => 'form-group col-md-12']
            ],
            [
                'name'  => 'profile.postal_code',
                'label' => 'Postal Code',
                'type'  => 'text',
                'tab'   => 'Profile',
                'wrapper' => ['class' => 'form-group col-md-4']
            ],
            [
                'name'  => 'profile.city',
                'label' => 'City',
                'type'  => 'text',
                'tab'   => 'Profile',
                'wrapper' => ['class' => 'form-group col-md-4']
            ],
]);
```

### What happened
**The Error:** `Call to undefined method App\Models\EmployeeProfile::getCastedAttributes()`

![image](https://user-images.githubusercontent.com/26017547/156539247-ab508fb4-b13c-47f5-873e-c9723018e500.png)

I guess it is confused with the `repeatable` field (i.e. `position` for my case, it is now `array` but not `json` string).

![image](https://user-images.githubusercontent.com/26017547/156539795-d2dabac0-40e2-4bcb-8c20-60cc88e75f73.png)

So, in v5...
I am unable to directly store the fields directly to another model anymore?

### What I've already tried to fix it

My workaround for now, in case it is a breaking change 
```
    public function store()
    {
        $profile = request('profile'); // extract the profile array

        $this->crud->setRequest($this->crud->validateRequest());
        $this->crud->setRequest($this->removeProfileInput($this->crud->getRequest()));   // remove profile array
        $this->crud->unsetValidation(); // validation has already been run

        $response = $this->traitStore();  // commit the employee

        $this->crud->entry->profile()->updateOrCreate($profile);  // create or update the employee's profile

        return $response;
    }
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.16 (cli) (built: Feb 21 2022 14:42:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.2@b91b3b5b39fbbdc763746f5714e08d50a4dd7857

### BACKPACK VERSION:
5.0.9@d995de2026b6fcb1b13b469f371c929c29d1c1cc

**Comment by olipayne** [comment]
Are you sure the `use CrudTrait` is still there on the your models?

**Comment by kiddtang** [comment]
> Are you sure the `use CrudTrait` is still there on the your models?

OMG! Why I've never thought of it! 
Interestingly, it is totally working fine in v4.1... 

I just add `use CrudTrait;` in `EmployeeProfile` everything back to normal!
thanks @olipayne for your help!

**Comment by kiddtang** [comment]
@pxpm 
I am not sure it is worth to be mentioned in the v5 upgrade guide.

btw... VERY awesome `relationship`... it becomes magically working out of the box!
I really overlooked this https://backpackforlaravel.com/docs/5.x/crud-how-to#hasone-1-1-relationship
Maybe `relationship` should really have its own menu link (& page) in the main sidebar.
for me, it is a MAJOR improvement to be well mentioned.
**good job Backpack Team**

**Comment by ThereSoftwareIEN** [comment]
@pxpm @kiddtang 
I have a slightly different problem.
The values are not loaded into the edit form, but only the Model id.
![ImmagineFields](https://user-images.githubusercontent.com/85872440/168053869-ccc34332-46ce-4a25-a905-dbe1bb4581ba.jpg)

$this->crud->addFields([
         [
            'name' => 'company_id',
            'type' => 'hidden',
         ],
         [
            'name' => 'company.companyName',
            'label' => __($this->getResourcesLang() . '.updateOperation.label.name'),
            'type' => 'text',
            'attributes' => [
               'placeholder' => __($this->getResourcesLang() . '.updateOperation.placeholder.name'),
            ]
         ],
         [
            'name' => 'company.city',
            'label' => __($this->getResourcesLang() . '.updateOperation.label.city'),
            'type' => 'text',
            'attributes' => [
               'placeholder' => __($this->getResourcesLang() . '.updateOperation.placeholder.city'),
            ]
         ],
         [
            'name' => 'company.address',
            'label' => __($this->getResourcesLang() . '.updateOperation.label.address'),
            'type' => 'text',
            'attributes' => [
               'placeholder' => __($this->getResourcesLang() . '.updateOperation.placeholder.address'),
            ]
         ]
      ]);

**Comment by olipayne** [comment]
@ThereSoftwareIEN this issue is closed, I suggest you start a new issue.

**Comment by cheadevit** [comment]
> @kiddtang nice to know you got it working! Indeed checking for model casts was introduced in v5, and that's a specific CrudTrait function. The only reason for it to exists is because of spatie-translatable. Totally unrelated I know, but that made us create the `getCastedAttributes` function to overcome the fact that spatie overwrittes the `getCasts()` model method, otherwise we would be using `getCasts` here, that is a Model function and not our custom function in CrudTrait.
> 
> If you are manually creating the models I agree that this comes with an added weight, but let me tell you if you didn't know yet, you don't need to manually save relations. if you are only doing it because it didn't properly work in 4.1, in v5 Backpack we did alot of improvements in this matter and Backpack can now take care of it for you, https://backpackforlaravel.com/docs/5.x/crud-how-to#hasone-1-1-relationship
> 
> Thanks @olipayne for pitching in 👏 🙏

I got an error when I try using the **relationship** field

BadMethodCallException
Call to undefined method App\Models\TimeTable::getCastedAttributes()

Here is the code in create operation 
```
protected function setupCreateOperation()
    {
        CRUD::setValidation(ShiftRequest::class);

        CRUD::field('code');
        CRUD::field('name');
        $this->crud->addField([
            'name'    => 'color',
            'label'   => 'Color',
            'type'    => 'color_picker',
            'default' => '#000000',
            'color_picker_options' => [
                'customClass' => 'custom-class',
                'horizontal' => true,
                'extensions' => [
                    [
                        'name' => 'swatches', // extension name to load
                        'options' => [ // extension options
                            'colors' => [
                                'primary' => '#337ab7',
                                'success' => '#5cb85c',
                                'info' => '#5bc0de',
                                'warning' => '#f0ad4e',
                                'danger' => '#d9534f'
                            ],
                            'namesAsValues' => false
                        ]
                    ]
                ]
             ],
        ]);
        CRUD::field('remark');

        $this->crud->addField([   // CustomHTML
            'name'  => 'relationship_direct_relationships_with_subfields',
            'type'  => 'custom_html',
            'value' => '<h5 class="mb-0 mt-4 text-primary">Direct Relationships + Subfields</h5>',
        ]);

        $this->crud->addField([
            'label'     => 'Timetable',
            'name' => 'timetable',
            'type' => 'relationship',
            'attribute' => 'shift_id',
            'subfields' => [
                [
                    'name' => 'time_clockin',
                    'type' => 'time'
                ],
                [
                    'name' => 'time_clockout',
                    'type' => 'time'
                ],
                [
                    'name' => 'remark',
                    'type' => 'textarea'
                ],
            ],
        ]);

        /**
         * Fields can be defined using the fluent syntax or array syntax:
         * - CRUD::field('price')->type('number');
         * - CRUD::addField(['name' => 'price', 'type' => 'number'])); 
         */
    }
```
