### ISSUE TITLE
[v5 Bug] loadOnce directive is not rendered on edit form after update to v5

### ISSUE THREAD

**Issue by preBit** [Laravel-Backpack/CRUD#4251]
# Bug report

### What I did

Updated from v4.1 to v5 following upgrade guide at: 
https://backpackforlaravel.com/docs/5.x/upgrade-guide.

### What happened

Most of the things went well after update but it seems like new @loadOnce directive is not rendered for form fields on edit form. On top of the page are css and on the bootom js stuff. Rest of the application works fine.

![backpack_loadOnce_error](https://user-images.githubusercontent.com/598483/156882743-f4edfd93-191d-472d-ba8f-d6fa687e213a.jpg)

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.3 (cli) (built: Mar  4 2022 17:38:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.3.1@c1c4404511b83fbf90ccbcdf864d4a85537f35e4

### BACKPACK VERSION:
5.0.9@d995de2026b6fcb1b13b469f371c929c29d1c1cc

**Comment by pxpm** [comment]
Hey @preBit thanks for the report.

Could you confirm you did `php artisan view:clear` ?

We already fixed something similar to that, so I guess you just need to update your dependencies https://github.com/DigitallyHappy/assets/pull/11#pullrequestreview-878670128

Let me know if I am wrong. 

Thanks

**Comment by olipayne** [comment]
Interesting, I've been debugging this exact same issue for the last few hours too!

**Comment by pxpm** [comment]
@olipayne L9 too?

**Comment by olipayne** [comment]
`
### PHP VERSION:
PHP 8.0.15 (cli) (built: Jan 21 2022 04:49:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.3.1@c1c4404511b83fbf90ccbcdf864d4a85537f35e4

### BACKPACK VERSION:
5.0.9@d995de2026b6fcb1b13b469f371c929c29d1c1cc
`

all dependencies at latest, `DigitallyHappy/assets` at `2.0.3`. It's a weird one!

**Comment by olipayne** [comment]
Also getting a load of printed `@loadScriptOnce($path)` at the bottom of my widgets page, so it doesn't seem to be `@loadOnce` specific

**Comment by preBit** [comment]
@pxpm I did the `php artisan view:clear` and it does not help. `DigitallyHappy/assets` is `2.0.3` and the rest of the dependencies are latest.

I installed everything on several other servers and the same problem remains with the loadOnce directive on the edit form.

**Comment by kiddtang** [comment]
i was on v5 a few days... somehow it break after `composer update`  and install the `htmlpurifier` today
i am not sure which package caused the issue... hope it helps...
i try checkout the commit before the `composer update` then the issue disappears (with `php artisan view:clear`) 


These are the updates...
```
Package operations: 2 installs, 20 updates, 0 removals
  - Upgrading symfony/polyfill-php80 (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-mbstring (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-ctype (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/var-dumper (v5.4.5 => v5.4.6): Extracting archive
  - Upgrading symfony/polyfill-php72 (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-intl-normalizer (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-intl-idn (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-php73 (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/http-foundation (v5.4.5 => v5.4.6): Extracting archive
  - Upgrading symfony/http-kernel (v5.4.5 => v5.4.6): Extracting archive
  - Upgrading symfony/polyfill-intl-grapheme (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-iconv (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/polyfill-php81 (v1.24.0 => v1.25.0): Extracting archive
  - Upgrading symfony/translation (v6.0.5 => v6.0.6): Extracting archive
  - Upgrading laravel/framework (v8.83.2 => v8.83.3): Extracting archive
  - Upgrading spatie/laravel-permission (5.5.0 => 5.5.1): Extracting archive
  - Upgrading laravel/horizon (v5.9.2 => v5.9.3): Extracting archive
  - Upgrading aws/aws-sdk-php (3.212.0 => 3.212.2): Extracting archive
  - Installing ezyang/htmlpurifier (v4.13.0): Extracting archive
  - Installing mews/purifier (3.3.7): Extracting archive
  - Upgrading myclabs/deep-copy (1.10.3 => 1.11.0): Extracting archive
  - Upgrading phpunit/phpunit (9.5.16 => 9.5.17): Extracting archive
```

**Comment by masrodjie** [comment]
I am facing the issue. Revert back digitallyhappy/assets to v2.0.1 should fix the problem

**Comment by preBit** [comment]
I confirm https://github.com/DigitallyHappy/assets/pull/12 PR resolves this issue. Didn't test @masrodjie solution but it looks like it could work also.

**Comment by preBit** [comment]
Reverting back `digitallyhappy/assets` to [v2.0.1](https://github.com/DigitallyHappy/assets/tree/2.0.1) doesn't work for laravel ^9.0

`composer update digitallyhappy/assets` returns problem:
`digitallyhappy/assets 2.0.1 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0)`

**Comment by pxpm** [comment]
@preBit you don't need to revert `digitallyhappy/assets`, you should revert `spatie/laravel-permission` from 5.5.1 to 5.5.0. 

We are in the process of fixing this and there is already a PR in https://github.com/DigitallyHappy/assets/pull/12 to fix this so I am going to close this to don't confuse anyone.

### WORKAROUND FOR NOW
- Lock `spatie/laravel-permission` in `5.5.0` version. 

Thanks

**Comment by tabacitu** [comment]
**Update:** This is a bug in that was introduced in `laravel/permission:5.5.1`, so we're trying to fix it there. Until https://github.com/spatie/laravel-permission/pull/2047 gets resolved, please lock your projects to `laravel/permission:5.5.0`

**Comment by erikn69** [comment]
https://github.com/erikn69/permission-issue/commit/5118f89811489dee0ac275af08b7d7b7339799dd 
I did test `digitallyhappy/assets 2.02, 2.0.3` with `spatie/laravel-permission 5.5.1`  and everything works as expected, look at the repository

**Comment by flamreal** [comment]
> [erikn69/permission-issue@5118f89](https://github.com/erikn69/permission-issue/commit/5118f89811489dee0ac275af08b7d7b7339799dd) I did test `digitallyhappy/assets 2.0.3` with `spatie/laravel-permission 5.5.1` and everything works as expected

Downgrade and even remove **PermissionManager** addon doesn't help to me, when I try to use **PageManager** or **NewsCRUD** backpack addons =\

**Comment by olipayne** [comment]
You need to pin `spatie/laravel-permission` to `5.5.0`, don't touch `backpack/permissionmanager`. Once you have pinned and installed, then you might want to `php artisan view:clear`.

**Comment by pxpm** [comment]
what @olipayne  said, or if you removed PermissionManager and continue to get the errors, you are probably using some other package that is conflicting with spatie/laravel-permission 5.5.1. There are alot of them at the moment, like the Impersonate package etc. 

Here is the discussion on this issue on spatie repository: https://github.com/spatie/laravel-permission/pull/2047

Thanks!

**Comment by tabacitu** [comment]
Solved in https://github.com/DigitallyHappy/assets/pull/13 and https://github.com/spatie/laravel-permission/pull/2048

No need to lock spatie/laravel-permission to 5.5.0 any more. A `composer update` should pull the latest `digitallyhappy/assets` and have this fixes 💪 Let us know if it doesn't.

Thanks for sticking with us guys. This has been such a painful one....
