### ISSUE TITLE
[Bug] Charts widget is not working in Backpack 5 Pro+ Laravel 9

### ISSUE THREAD

**Issue by hasanakhtar** [Laravel-Backpack/CRUD#4252]
# Bug report

### What I did

Following the steps in the doc (https://backpackforlaravel.com/docs/5.x/base-widgets#chart-pro).
1-Installed the Chart Library
2- Created the Chart controller and added a chart. Can see the jason at route: "admin/charts/weekly-users"
3- Added the widget in the dashboard blade page

### What I expected to happen

Chart was supposed to be drawn

### What happened

It blanked out without any error on the html.

The Dashboard page is emitting @loadScriptOnce($path) right at the bottom of the page.....and the console is saying "Chart is not defined"

### What I've already tried to fix it

Follow the docs

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:

PHP 8.1.3 (cli) (built: Feb 18 2022 09:24:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.0.2

### BACKPACK VERSION:
5.0.7

**Comment by tabacitu** [comment]
@hasanakhtar it's possible that the problem is not only with Charts, but with a lot of other stuff. Please see https://github.com/Laravel-Backpack/CRUD/issues/4251 - basically `laravel-permission` made a change 5 days ago that broke A LOT of other packages. 

Are you using `laravel-permission` in your project? If so, you should lock it to `5.5.0` until that gets resolved.

**Comment by hasanakhtar** [comment]
Thanks for the heads up. This was precisely the issue. Locked it to 5.5.0 and the issue seems to be resolved.
Many Thanks

**Comment by haniramadhan-kkp** [comment]
I use Backpack 6 Pro + Laravel 10, and I have installed spatie/laravel-permission version 5.10.2, and until now the chart is not loaded. Should I lock it to 5.5.0? How to do that?
