### ISSUE TITLE
[Bug] @loadScriptOnce($path) @loadScriptOnce($path) @loadScriptOnce($path) @loadScriptOnce($path) in the end of the page

### ISSUE THREAD

**Issue by dilneiss** [Laravel-Backpack/CRUD#4257]
# Bug report

### What I did

Opened dashboard

### What I expected to happen

Charts working and no message in the end of the page

### What happened

Just loaded my dashboard and the charts stoped working, opening console i get this error: 
Uncaught (in promise) ReferenceError: Chart is not defined
    at qvecwtglmobpyuriajfdxskzn_create (<anonymous>:7:48)
    at <anonymous>:38:33

And in the end of the page, there is something print this: @loadScriptOnce($path) @loadScriptOnce($path) @loadScriptOnce($path) @loadScriptOnce($path)

Searching on google, found another user with exacly same problem: https://stackoverflow.com/questions/71364229/charts-widget-is-not-working-in-backpack-5-pro-laravel-9

### What I've already tried to fix it

rollback 2 versions of the backpack

### Is it a bug in the latest version of Backpack?

I think yes, localhost is not happening, but in production is happening, but in production i am using laravel octane, maybe cold be this the problem.

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

backpack/crud 5.0.10
backpack/pro 1.0.10
PHP 8.0.11
DB: Postgresql
Laravel: 9.4.1

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.0.11 (cli) (built: Sep 21 2021 18:26:06) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.11, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.4.1@29f0aaade82eadd20ef881b4efb88b0dad4e9a5b

### BACKPACK VERSION:
5.0.10@f0c0c45914c39a9083e19f0c5c3d10ef0e142565

**Comment by tabacitu** [comment]
Hey @dilneiss ,

A `composer update digitallyhappy/assets` should fix it for you - let me know.

Background: there's a bug in `spatie/laravel-permission:5.5.1` that broke other packages using Blade directives, including one of ours. Waiting for [our PR](https://github.com/spatie/laravel-permission/pull/2048) to get merged. But we've also pushed a fix on our end, last night, that should prevent the interference. Hence my recommendation to get the latest version of `digitallyhappy/assets`. Alternatively, you can lock `spatie/laravel-permission` to 5.5.0.

Cheers!

**Comment by tabacitu** [comment]
Even if **this is now fixed**, we'll keep this issue open for some time, so it's more visible.

For anybody who wants more information, this has also been talked about in:
- https://github.com/spatie/laravel-permission/pull/2048
- https://github.com/spatie/laravel-permission/pull/2047
- https://github.com/DigitallyHappy/assets/pull/12
- https://github.com/DigitallyHappy/assets/pull/13
- https://github.com/Laravel-Backpack/CRUD/issues/4251
- https://github.com/Laravel-Backpack/CRUD/issues/4258

**Comment by dilneiss** [comment]
thanks, composer update that package works!

**Comment by tabacitu** [comment]
Ok so I think we're finally past this - people who get this error because they use a past version will probably Google and find this issue. So I'm going to close it.
