### ISSUE TITLE
[Bug] @loadOnce('packages/select2/dist/css/select2.min.css') appears on top of each create/update page

### ISSUE THREAD

**Issue by jfelixoptimiumnc** [Laravel-Backpack/CRUD#4258]
# Bug report

### What I did

Upgraded to V5

### What I expected to happen

Nothing broken ;)

### What happened

@loadOnce('packages/select2/dist/css/select2.min.css') appears on top of each create/update page or any other field type

### What I've already tried to fix it

Checked everything three times...

### Is it a bug in the latest version of Backpack?

Yep

After I run ```composer update backpack/crud``` the bug... is it still there?

Yep

### Backpack, Laravel, PHP, DB version
Laravel 9, backpack 5 PHP 80

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.4.1@29f0aaade82eadd20ef881b4efb88b0dad4e9a5b

### BACKPACK VERSION:
5.0.10@f0c0c45914c39a9083e19f0c5c3d10ef0e14256
![2022-03-09_20h51_24]

(https://user-images.githubusercontent.com/45578403/157417254-6c0dfc03-9226-4eee-9e27-e38ff6bb44e6.png)

**Comment by tabacitu** [comment]
There was a bug this week in `spatie/laravel-permission` which breaks other packages. Please see https://github.com/Laravel-Backpack/CRUD/issues/4257#issuecomment-1062595044

**Comment by pxpm** [comment]
@jfelixoptimiumnc also run `composer update digitallyhappy/assets` . The last version of that package should have the fix needed for you. 

Please also note that you need to do `php artisan view:clear` after updating to clear the view cache. 

Thanks

**Comment by jfelixoptimiumnc** [comment]
You rock guys, thx ;)
