### ISSUE TITLE
All repos support Laravel 9

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4263]

**Comment by remipou** [comment]
will backpack 4.1 support Laravel 9?

**Comment by tabacitu** [comment]
@remipou - no, we've only added Laravel 9 support to Backpack v5.

Backpack v4.1 already supports `^8.0|^7.0|^6.0` so it would have been extra-difficult to add L9 support to it, and keep maintaining it for another year too.

Since this issue has been added, all our repos have received L9 support so I'm going to close this.

Cheers!

**Comment by remipou** [comment]
ok, thanxs
