### ISSUE TITLE
[Bug] Invalid JSON in the alerts.blade.php

### ISSUE THREAD

**Issue by mrbig00** [Laravel-Backpack/CRUD#4278]
# Bug report

### What I did

```php
try {
    // throw an exception here
}
catch (\Exception $exception) {
    Alert::error($exception->getMessage())->flash();
    return redirect(route('order.edit.view', ['id' => $id]));
}
```

### What I expected to happen

Show an alert message

### What happened

Becuase the error message contained a ```"``` a JS parse error happened.

### What I've already tried to fix it

Replacing the 
```var $alerts_from_php = JSON.parse('@json(\Alert::getMessages())');```

with ``` var $alerts_from_php =   {{Js::from(\Alert::getMessages())}};```

in ```src/resources/views/base/inc/alerts.blade.php``` fixed the issue
### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

Laravel 9

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.0.7 (cli) (built: Jun 16 2021 00:42:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.7, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v9.4.1@29f0aaade82eadd20ef881b4efb88b0dad4e9a5b

### BACKPACK VERSION:
5.0.10@f0c0c45914c39a9083e19f0c5c3d10ef0e142565


```

**Comment by olipayne** [comment]
@mrbig00 you already did the work, if you submit a PR like I have above, then you can allow others to easily test your proposed solution and make it easier to bring into the next release (plus you get the credit you deserve!)

**Comment by pxpm** [comment]
Thanks for the report @mrbig00 and for the solution. 

I haven't got time to tackle this one, but I see that @olipayne did an amazing job and submitted the PR with your proposed change. 

I think I will review it tomorrow, so I will be closing this so we keep the discussion regarding this only in one place, the PR! 

Thank you both again @mrbig00 and @olipayne !

Cheers 👍
