### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ghena** [Laravel-Backpack/CRUD#4281]
# Bug report

### What I did

Add new Author with field related

### What I expected to happen

save normally

### What happened

SQLSTATE[HY000]: General error: 1364 Field 'book' doesn't have a default value (SQL: insert into authors (name, updated_at, created_at) values (prova, 2022-03-24 10:36:11, 2022-03-24 10:36:11))

### What I've already tried to fix it

set null as default value, but no id_book related as saved

### Is it a bug in the latest version of Backpack?

No, The same with 5.0.5

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version
Backpack 5.0.5
Laravel 8.75
7.4
5.7.24

When I run ```php artisan backpack:version``` the output is:
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.5@33b1b981266e3a19fbc826b60c4a6847e311ac95

### BACKPACK VERSION:
5.0.5@c7c74166244f7995a07abb83f2a83e914e515c9f

**Comment by pxpm** [comment]
Hello @ghena .

I already ansered you in https://gitter.im/BackpackForLaravel/Lobby . 

Please note that we use github specifically for bug reports, and when you report a bug **it needs to be "reproducible"** so we could think on how to solve it after we can identified the error, from your description it **would take me ages** to reproduce your error if it was an actual error. 🙃 

I don't think this is a bug in backpack code so I am going to close this. Let's keep this discussion on gitter, or create a stackoverflow post. 

Cheers
