### ISSUE TITLE
[Feature Request] add `validationRules()` and `validationMessages()` methods to CrudField

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4284]
# Feature Request

### What's the feature you think Backpack should have?

When you write out a field, the IDE won't autocomplete the `validationRules()` and `validationMessages()` methods because they're not on the `CrudField` class. If we add them, it'd be easier for developers to write this out, without looking at [the docs](https://backpackforlaravel.com/docs/5.x/crud-operation-create#validating-fields-using-field-attributes).

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Feature

**Comment by pxpm** [comment]
Done in #4287
