### ISSUE TITLE
Reseting new password redirects to /home

### ISSUE THREAD

**Issue by andresrl** [Laravel-Backpack/CRUD#4286]
I have v5.0.11

I tried to reset the password via the login page.

The email was received with this link:

https://www.domain.com/admin/password/reset/hashcodehascodehashcode?email=name%40domain.com

And if I click that link it redirects me to /home. So I can't reset my password.

**Comment by andresrl** [comment]
Please!

**Comment by pxpm** [comment]
@andresrl probably because you are logged in or something else, I've just tested this and it's working fine:

![image](https://user-images.githubusercontent.com/7188159/161061733-47478abf-37c1-4c11-8174-ca8c94a36cfc.png)

**Comment by tabacitu** [comment]
I also tested this and it redirect me to the dashboard. So it looks like we can't replicate this, sorry @andresrl . Are you sure you're not using your own ResetPasswordController.. or PasswordBroker or something like that?

**Comment by andresrl** [comment]
Yes, Cristian, thanks for your time in helping me

I was because I was logged in

I logged out, the try to recover my password and BOOM, the recovery password form was there

THANKS, again for your time and effort in supporting this GREAT PROJECT

Two weeks ago I purchased the Pro version for one single project

This week I'm going to start a new one

I'll purchase the Unilimited One.
