### ISSUE TITLE
BadMethodCallException on simple filter

### ISSUE THREAD

**Issue by b8ne** [Laravel-Backpack/CRUD#429]
Hi,
I have just tried implementing a simple filter, but am getting
```
BadMethodCallException in Builder.php line 2450:
Call to undefined method Illuminate\Database\Query\Builder::paid()

in Builder.php line 2450
at Builder->__call('paid', array())
at call_user_func_array(array(object(Builder), 'paid'), array()) in Builder.php line 1469
at Builder->__call('paid', array())
at call_user_func_array(array(object(Builder), 'paid'), array()) in Query.php line 27
at CrudPanel->addClause('paid') in SponsorInvoiceCrudController.php line 142
```

My filter
```
$this->crud->addFilter([
            'name' => 'paid',
            'type' => 'simple',
            'label' => 'Paid'
        ], false,
            function() {
                $this->crud->addClause('paid');
            }
        );
```

The model is also cast
```
protected $casts = [
        'paid' => 'boolean'
    ];
```

There are no relations influencing this field, and a filter on the same CRUD is working so im not sure what the issue could be.
Has anyone seen this before?

**Comment by tabacitu** [comment]
Hi @b8ne ,

```$this->crud->addClause();``` just adds a clause to the query. It binds whatever parameters you give it to the query. 

So if you write ```$this->crud->addClause('paid');``` your query will basically become ```$this->crud->query->paid()```. That could work, if you have [a local scope](https://laravel.com/docs/5.4/eloquent#local-scopes), like ```scopePaid($query)``` on your model. But from the error, I think you don't. 

If you're looking to match a value to your paid column, use ```$this->crud->addClause('paid', 1);```. This translates to ```$this->crud->query->where('paid', 1);```

Hope it helps.

Cheers!

**Comment by chriscalip** [comment]
@tabacitu 
The reason I came to this issue is because the documentation provides wrong information.
https://laravel-backpack.readme.io/docs/crud-full-api

Documentation recommends:
`$this->crud->addClause('type', 'car');`
when it should be:
`$this->crud->query->where('type', 'car');`

**Comment by tabacitu** [comment]
Hi @chriscalip ,

The docs assumed you were using [a query scope](https://laravel.com/docs/5.6/eloquent#query-scopes), and then a dynamic local scope, but didn't specify that. You're right, thank you, just updated it.

Cheers!
