### ISSUE TITLE
[Bug] Undefined array key "attribute" while filtering 

### ISSUE THREAD

**Issue by GoatFreezy** [Laravel-Backpack/CRUD#4293]
# Bug report

### What I did

This was working in Laravel 7 and backpack 4 after the upgrade this error apear when using basic filters
As i debugged i see that "attribute" isnt present in applySearchLogicForColumn function line 85

![image](https://user-images.githubusercontent.com/25383505/160471076-7114d4c8-466f-472e-bb59-0c1af61368ad.png)
The field in my controller is defined as following
```
        $this->crud->addField([
            'label' => 'Series', // Label for HTML form field
            'type'  => 'select',  // HTML element which displaying transactions
            'name'  => 'serie_id', // Table column which is FK for Customer table
            'entity' => 'serie', // Function (method) in Customer model which return transactions
            'attribute' => 'id', // Column which user see in select box
            'model' => 'Serie' // Model which contain FK
        ]);
```
### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://user-images.githubusercontent.com/25383505/160471419-e87abfe7-227b-4878-a88b-62691bc140a3.png)

**Comment by pxpm** [comment]
Hello @GoatFreezy . I think there migth be some confusion here. You are showing me a `field`, but the error you report is in `columns`, so you should have some `$this->crud->addColumn()` statement ? 

Thanks

**Comment by GoatFreezy** [comment]
Hello @pxpm. I've tried it already and it give me the exact same error as if it doesnt change anything. I've even tried to delete that part of the code and same errors happends. It seems that something break in the upgrade process tho i've read the upgrade guides and can't find anything related to my issue

**Comment by GoatFreezy** [comment]
Actually with only my fields defined for the List Operation the search bar doenst work.

```
protected function setupListOperation()
    {
        CRUD::column('name');
        CRUD::column('serie_id');
        CRUD::column('season_id');
        CRUD::column('number');
        CRUD::column('cover');
        CRUD::column('check');
        CRUD::column('path_fr');
        CRUD::column('path_jap');
        CRUD::column('duration');
    }
```

**Comment by pxpm** [comment]
@GoatFreezy what are you trying to search ? What does not work ? You talk filters, columns etc and I am a bit lost here. 

Some columns need you to do your own `searchLogic` https://backpackforlaravel.com/docs/5.x/crud-columns#custom-search-logic-for-columns is that the problem ?

**Comment by rommeA** [comment]
Hello! I'm getting the same error only for one of my models.
Columns:
![image](https://user-images.githubusercontent.com/62960969/162179035-7f7e8a10-6d2b-4487-a794-619f26b0e67f.png)
When I try to type smth in the 'search' field:
![image](https://user-images.githubusercontent.com/62960969/162179236-d850dc89-e9d5-460c-89cb-2ae12d69537b.png)

Model code:
```
class Vessel extends Model
{
    use \Backpack\CRUD\app\Models\Traits\CrudTrait;
    use HasFactory;
    use SoftDeletes;
    use Notifiable;

    protected $keyType = 'string';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'company_id'
    ];

    /**
     * The event map for the model.
     *
     * @var array
     */
    protected $dispatchesEvents = [
        'created' => VesselCreated::class,
    ];


    public function company(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Company::class, 'company_id', 'id');
    }
}
```

**Comment by rommeA** [comment]
UPD: when I commented definition of column '`company_id`' (uuid) the error didn't appear again. In the screenshot you can see my DB structure - column '`company_id`' surely exists.
![image](https://user-images.githubusercontent.com/62960969/162180040-d9c869c5-fd01-4356-a879-7c85d0ee07d1.png)

**Comment by GoatFreezy** [comment]
@pxpm Got the exacte same error as @rommeA described.
For me the error came after an upgrade of version and nothing in the code changed.
i actually have only the definition on my columns in my controllers et nothing special.
Im trying to filter on my relation ship via the search field in a list, do anything changer within the latest version ?  

@rommeA After commenting you fields you still are being able to filter on it ?

**Comment by rommeA** [comment]
@GoatFreezy I'm not using any filters (I didn't purchase a PRO version yet). 
Anyways, I found a solution. Rename your columns and remove the '`_id`' part. 
In my case I changed 
`CRUD::column('company_id')`
to 
`CRUD::column('company')`

After that change everything works fine.

**Comment by Nemachtilli** [comment]
@GoatFreezy Thanks it worked for me change service_id by service.

I don't understand why this happens
