### ISSUE TITLE
[FIELDS] New field type: address

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#43]
Use Algolia Places or Google Maps:

https://github.com/algolia/places

**Comment by tabacitu** [comment]
This is so far-fetched, its really not worth it :-)

Moved to pending, so it can die a peaceful death.

**Comment by OwenMelbz** [comment]
Sometimes people are not ready for death, and happen to be needed when least expected!

**Comment by tabacitu** [comment]
:-))
