### ISSUE TITLE
[Bug] issue with gravatar on empty email address

### ISSUE THREAD

**Issue by wanghanlin** [Laravel-Backpack/CRUD#4302]
# Bug report

### What I did

User database have email column, but it's optional, some part will break, eg. gravatar.

### What I expected to happen

in helpers.php backpack_users_have_email and backpack_avatar_url may need small adjustment

### What happened

login will throw 500 because of null email

### Options
1. We don't treat this as a bug
2. We add a config to mark email as optional
3. We check with $user->email directly instead of whether the column exists or not, this way also support mutator and accessor.

**Comment by jorgetwgroup** [comment]
Hi there @wanghanlin i hope you are ok.

I take this issue about working without email column as mandatory i do this to jump about 500 error:

On helper function backpack_avatar_url i check if there is gravatar option, but if email column doesnt exists or is empty i change default avatar_type from gravatar to placehold.

Meanwhile you can see this in action in this branch: https://github.com/Laravel-Backpack/CRUD/tree/avatar-without-email

Let me know if everything works as you expected.

Cheers.

**Comment by tabacitu** [comment]
Thanks for reporting it @wanghanlin and for the PR @wanghanlin . Let's move the conversation to the PR then, we can merge this real quick 💪🎉
