### ISSUE TITLE
[Bug] customize relationship field orderBy

### ISSUE THREAD

**Issue by lucaguindani** [Laravel-Backpack/CRUD#4316]
# Bug report

### What I did

Added a custom query in a **relationship** field to order the options by name.

```php
CRUD::addField([
    'label' => "Catégorie",
    'type' => "relationship",
    'name' => 'type_id',
    'attribute' => "name",
    'model'     => "App\Models\Type",
    'placeholder' => "Sélectionner une catégorie",
    'inline_create' => true,
    'tab' => 'Champs d\'administration',
    'options' => (function ($query) {
        return $query->orderBy('name', 'ASC')->get();
    })
]);
```

### What I expected to happen

The select2 options should be ordered by name.

### What happened

The select2 options are not ordered by name.

### What I've already tried to fix it

If I remove `'inline_create' => true`, the custom query is working as expected and the select2 options are ordered by name.

```php
CRUD::addField([
    'label' => "Catégorie",
    'type' => "relationship",
    'name' => 'type_id',
    'attribute' => "name",
    'model'     => "App\Models\Type",
    'placeholder' => "Sélectionner une catégorie",
    'tab' => 'Champs d\'administration',
    'options' => (function ($query) {
        return $query->orderBy('name', 'ASC')->get();
    })
]);
```

### Backpack, Laravel, PHP, DB version

PHP VERSION:
PHP 8.0.17 (cli) (built: Mar 29 2022 02:31:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies

LARAVEL VERSION:
v8.83.2@b91b3b5b39fbbdc763746f5714e08d50a4dd7857

BACKPACK VERSION:
5.0.13@d78f4263f5eef1e7761ba2d55d81959f4de559b6

**Comment by adriallongarriu** [comment]
I have a similar issue. 
I want to order the select options alphabetically.
My code:
```php
$this->crud->addField([
            'name'      => 'products',
            'label'     => 'Products',
            'type'      => "relationship",
            'subfields' => [
                [
                    'name' => 'quantity',
                    'label' => trans('stocks::stock_movment.quantity'),
                    'type' => 'number',
                ],
            ],
            'options'   => (function ($query) {
                return $query->orderBy('name', 'ASC')->get();
            }),
        ]);
```
I think the problem is with `repeatable`. When you use the 'inline_create' or 'subfields' the field is transform to `repeatable`.
In the file `vendor\backpack\pro\resources\views\fields\relationship.blade.php` the variable `$field` has 'options' and has two 'subfields'.
```php
array:11 [▼
  "name" => "products"
  "label" => "Productos"
  "type" => "relationship"
  "subfields" => array:2 [▶]
  "options" => Closure($query) {#2285 ▶}
  "entity" => "products"
  "relation_type" => "BelongsToMany"
  "model" => "App\Models\Product"
  "attribute" => "name"
  "multiple" => true
  "pivot" => true
]
```
But and in the select file `vendor\backpack\pro\resources\views\fields\relationship\select.blade.php` the variable `$field` don't have options. 
```php
array:16 [▼
  "name" => "products[-1][products]"
  "type" => "relationship"
  "is_pivot_select" => true
  "multiple" => false
  "entity" => "products"
  "relation_type" => "BelongsToMany"
  "model" => "App\Models\Product"
  "minimum_input_length" => 2
  "delay" => 500
  "placeholder" => "Selecciona un elemento"
  "label" => Illuminate\Support\Stringable {#2127 ▶}
  "validationRules" => "required"
  "validationMessages" => array:1 [▶]
  "ajax" => false
  "data_source" => "false"
  "showAsterisk" => true
]
```

**Comment by pxpm** [comment]
Ahhhhh

now I get it!!!

Thanks for clarification!!! It's the pivot field!!

I will have a look and get back to you guys. Thanks!

**Comment by lucaguindani** [comment]
> The first issue with @lucaguindani , is that the `inline_create` field does not use `options` since it's an ajax field. You should always provide the `fetchSomething` or configure the `data_source` yourself. There you actually return the results, so your query configuration should be done in the ajax endpoint: https://backpackforlaravel.com/docs/5.x/crud-operation-fetch#how-to-use-1

@pxpm Thanks for the tip! It's working as expected now that I've added the orderBy in the fetch function.

**Comment by adriallongarriu** [comment]
> You should configure the options inside the pivotSelect key.

I tried it and it works. @pxpm Thanks
Post the correct code in case someone needs it:
```php
 $this->crud->addField([
            'name'      => 'products',
            'label'     => 'Products',
            'type'      => "relationship",
            'subfields' => [
                [
                    'name' => 'quantity',
                    'label' => trans('stocks::stock_movment.quantity'),
                    'type' => 'number',
                ],
            ],
            'pivotSelect' => [
                'options'   => (function ($query) {
                    return $query->orderBy('name', 'ASC')->get();
                }),
            ]
        ]);
```
