### ISSUE TITLE
[Bug] Add MenuCRUD version bump to v5 upgrade docs?

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#4324]
# Bug report

### What I did

Upgrade to Backpack 5 and install the pro tools in our test environment

### What I expected to happen

Achieve the upgrade

### What happened

I get a dependency error:

  Problem 1
    - Conclusion: don't install backpack/crud 5.0.14
    - Conclusion: don't install backpack/crud 5.0.13
    - Conclusion: don't install backpack/crud 5.0.12
    - Conclusion: don't install backpack/crud 5.0.11
    - Conclusion: don't install backpack/crud 5.0.10
    - Conclusion: don't install backpack/crud 5.0.9
    - Conclusion: don't install backpack/crud 5.0.8
    - Conclusion: don't install backpack/crud 5.0.7
    - Conclusion: don't install backpack/crud 5.0.6
    - Conclusion: don't install backpack/crud 5.0.5
    - Conclusion: don't install backpack/crud 5.0.4
    - Conclusion: don't install backpack/crud 5.0.3
    - Conclusion: don't install backpack/crud 5.0.2
    - Conclusion: don't install backpack/crud 5.0.1
    - Conclusion: don't install backpack/crud 5.0.0
    - backpack/menucrud 2.0.5 requires backpack/crud ^4.1.0|^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - backpack/menucrud 2.0.0 requires backpack/crud ^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - backpack/menucrud 2.0.1 requires backpack/crud ^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - backpack/menucrud 2.0.2 requires backpack/crud ^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - backpack/menucrud 2.0.4 requires backpack/crud ^4.1.0|^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - backpack/menucrud 2.0.5 requires backpack/crud ^4.1.0|^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - backpack/menucrud v2.0.3 requires backpack/crud ^4.0.0 -> satisfiable by backpack/crud[4.0.x-dev, 4.1.x-dev].
    - Can only install one of: backpack/crud[v5.x-dev, 4.1.x-dev].
    - Can only install one of: backpack/crud[v5.x-dev, 4.0.x-dev].
    - Can only install one of: backpack/crud[v5.x-dev, 4.0.x-dev].
    - Installation request for backpack/crud ^5.0.0 -> satisfiable by backpack/crud[5.0.0, 5.0.1, 5.0.10, 5.0.11, 5.0.12, 5.0.13, 5.0.14, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, v5.x-dev].
    - Installation request for backpack/menucrud ^2.0 -> satisfiable by backpack/menucrud[2.0.0, 2.0.1, 2.0.2, 2.0.4, 2.0.5, v2.0.3].

### What I've already tried to fix it

We upgraded to 4.1.69 backpack, but still have the same error

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
YES

### Backpack, Laravel, PHP, DB version
Backpack: 4.1.69
php 7.4

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.8@cf430301ad17656b3d918995bcdd0454c3c119b9

### BACKPACK VERSION:
4.1.69@248e2e034cedcffe01732cdce01fb3d1ecad9ffa

**Comment by tabacitu** [comment]
Hey @miquelangeld ,

Can you please try bumping the "backpack/menucrud" version to  "^3.0.0" in your `composer.json`, then running `composer update` again? Does that fix it for you?

Cheers!

**Comment by tabacitu** [comment]
(we didn't mention that in the upgrade guide, but it looks to me like that's needed - so that might be our mistake)

**Comment by pxpm** [comment]
Hey @miquelangeld and @tabacitu 

I had answered this some days ago on gitter. I've reworded the text in https://github.com/Laravel-Backpack/docs/pull/339 to better reflect the backpack ecosystem (not all packages work without version bump). 

I don't think there is much more we can do here, going to close this!

Thanks guys, cheers!

**Comment by miquelangeld** [comment]
> Hey @miquelangeld ,
> 
> Can you please try bumping the "backpack/menucrud" version to "^3.0.0" in your `composer.json`, then running `composer update` again? Does that fix it for you?
> 
> Cheers!

Hi @tabacitu I will try , thanks

**Comment by miquelangeld** [comment]
Never mind, It was a composer version issue, using composer v2 worked like a charm. I just needed to bump backpack/menucrud and also backpack/langfilemanager
