### ISSUE TITLE
Tabbed Forms?

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#433]
I just noticed new additions to the documentation.
Several new things including "Tabbed Forms".
I've tried it but nothing happen.

Also i've noticed the button have changed? In the screenshot there is "Save and edit this item".
I just have a normal save button.
https://files.readme.io/da959e4-Screen_Shot_2017-02-12_at_12.44.43.png

I've done a composer update.
Removing backpack/crud (3.1.57)
Installing backpack/crud (3.1.59)
Removing backpack/base (0.7.15)
Installing backpack/base (0.7.16)

Do I have the latest version ? Am I missing a step ?

**Comment by adbmdp** [comment]
In my composer.json i have: 
```
"require": {
        "php": ">=5.6.4",
        "backpack/base": "^0.7.11",
        "backpack/crud": "^3.1",
        "backpack/permissionmanager": "^2.1",
        "laravel/framework": "5.3.*"
}
```
Also to upgade to Laravel 5.4 can i just change the composer.json to 5.4 and do a composer update?

**Comment by OwenMelbz** [comment]
Tabbed forms will be a feature in 3.2 - which is currently unreleased.
I assume the documentation is just getting updated gradually for the release, there will probably be a upgrade guide to get some of the new features working if you're published your views.

And yes for laravel 5.4 you should be able to just change it to `5.4.*` and do a `composer update`

**Comment by adbmdp** [comment]
Got it! Thanks you OwenMelbz!

**Comment by adbmdp** [comment]
Arggg ... i've changed to Laravel to 5.4.* and do a composer update. 
Broke everything.

**Comment by OwenMelbz** [comment]
Change back to 5.3 and do another composer update :)

**Comment by adbmdp** [comment]
ok. Ive tried that also:
https://laravel.com/docs/5.4/upgrade
But did not works

**Comment by OwenMelbz** [comment]
By any chance have you ever edited files inside the `/vendor` folder? - you can always delete the whole vendor folder, then do `composer install` again

**Comment by adbmdp** [comment]
I've deleted the whole vendor folder. And do a composer update.
I also changed:
"laracasts/generators": "dev-master as 1.1.4"
No errors messages on composer update but all my CRUDS list are empty. Very strange.

local.ERROR: exception 'Symfony\\Component\\Debug\\Exception\\FatalErrorException' with message 'Call to undefined method Illuminate\\Routing\\Route::getUri()' in /home/ubuntu/workspace/storage/framework/views/9ed5d691db11e039c09d5ee1f86d749bd18403d4.php:127\nStack trace:\n#0 {main}  \n

**Comment by adbmdp** [comment]
All my controllers that have $this->crud->enableAjaxTable() are not working.
The other ones are working...

**Comment by OwenMelbz** [comment]
Theres code in the templates that call `Route::getUri()` or something similar, these need to be updated to the latest versions.

You will need to make sure your code is compatible with laravel 5.4, it might not be a 1 click install.

You'll need to debug each issue and find the problem

**Comment by adbmdp** [comment]
Thanks for your help i got it.
It was /resources/views/vendor/backpack/base/layout.blade.php with a getUri() inside.
I don't know why i've place this file here...

**Comment by tabacitu** [comment]
@OwenMelbz , @adbmdp , yup - currently going through the last steps to officially launch 3.2. You'll receive a newsletter shortly.

Cheers!
