### ISSUE TITLE
CRUD 3.2 and multilangue

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#434]
Hello from Belgium,

For my end-studies project, I would like to create a project with backpack. Only, I would need the multilingual features of Backpack (to be able to translate my pages with the PageManager module).

I installed Backpack with Laravel 5.4, I tested several things and it is really good, simple and fast.

I read that the CRUD 3.2 had the multilingual functionality. Is it true ?

Can I upgrade to CRUD 3.2? Or is it better to wait?

If I update, my project will still work?

Thank you

**Comment by Jimmylet** [comment]
I just understood something, sorry.

I think it is already possible to translate models with Backpack?

But is it possible to translate pages of the PageManager module?

thank you very much

**Comment by tabacitu** [comment]
Hi @Jimmylet ,

Just launched CRUD 3.2, [here's the upgrade guide](https://laravel-backpack.readme.io/v3.0/docs/upgrade-from-31-to-32). Today I'll be gradually upgrading all other Backpack packages to this new version, too. So yes, you'll be able to use PageManager with translations. In a few hours.

Cheers!

**Comment by Jimmylet** [comment]
Oh yes ! Thank you very much for the work you do! Thank you
