### ISSUE TITLE
BackPack field type checklist data is not loading pivot table on creation and updation

### ISSUE THREAD

**Issue by zain534102** [Laravel-Backpack/CRUD#4345]
Hey team I want to assign permissions to users while creating or updating. So used checklist type data with the backpack permission manager. Follow is my code which I put for column type checklist.
```
CRUD::addColumn(
            [
                'label'     => 'Permissions',
                'type'      => 'checklist',
                'name'      => 'permissions',
                'entity'    => 'permissions',
                'attribute' => 'name',
                'model'     =>"Backpack\PermissionManager\app\Models\Permission",
                'pivot'     => true,
            ],
        );
```
This was working fine until I upgraded laravel backpack to v5 with backpack/pro.

**Comment by tabacitu** [comment]
Thanks for submitting this @zain534102 . Not sure if it's a bug in Backpack or user error - let's see. Also, heads-up, I notice you're saying the `checklist` field, but your field definition has the `select_multiple` field. That should work too, shouldn't be a problem, but I'm just saying, if it does you'll see the `select_multiple` field, not the `checklist` field like your title suggests.

1) I notice your field is called "permissions" but it's pointing towards the `Role` model - might that be the problem?
2) Does this work ok if in your field definition you just leave `label`, `type` and `name` and let Backpack figure out the rest?
3) When it doesn't work... what happens? What's the error?

Cheers!

**Comment by zain534102** [comment]
Thanks @tabacitu. I followed this field definition from [](https://backpackforlaravel.com/docs/5.x/crud-fields#checklist-1) and used this for getting permission. While posting i had issue of i put wrong model here thanks for telling but in my code i am using right model which is permission. The problem is that same code working fine in v4 but when i upgraded it to v5 it caused me error that pivot table is filled with user permissions but on the user edit form i am not getting user permissions as checked

**Comment by zain534102** [comment]
My UI requirements are to use checklist for showing permissions that's why i am strictly using checklist

**Comment by tabacitu** [comment]
Thanks @zain534102 so do I understand correctly that this is a UI problem? That:
- the entries are saved correctly in the db (in the pivot table)
- but after the page reload, the correct checkboxes are not checked?

If so, can you please 
- go to the `vendor/backpack/crud/src/resources/views/crud/fields/checkbox.blade.php` file
- do a `@dump($field)` as the very first line
- do a `@dump($field)` after the `@endphp` line 
- copy-paste the output for both here

Thanks!
