### ISSUE TITLE
[Bug] ListOperation modal no longer showing when ellipsis is clicked

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4352]
# Bug report

### What I did

Clicked the ellipsis (three dots `...`) in the table view.

### What I expected to happen

A modal to show up with all the columns for that entry, and the buttons, like it did in previous versions:

![CleanShot 2022-05-02 at 10 39 26](https://user-images.githubusercontent.com/1032474/166200743-094a4775-7145-4f1e-804b-e05e958386fb.png)

### What happened

The ellipsis shows up, but when clicked it triggers the details row, which sort of shows the same thing but not everything (the buttons for example aren't there), and in an ugly way:

![CleanShot 2022-05-02 at 10 40 50](https://user-images.githubusercontent.com/1032474/166200884-17d1aa40-3607-463c-9fd4-ba8708839b62.png)

### What I've already tried to fix it

Nothing yet. But I see the bug is also on [demo.backpackforlaravel.com](http://demo.backpackforlaravel.com) so I think it's been here for a few weeks at least 😔

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yup.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.0.16 (cli) (built: Feb 18 2022 09:11:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.6.0@47940a1a8774b96696ed57e6736ccea4a880c057

### BACKPACK VERSION:
5.0.13@d78f4263f5eef1e7761ba2d55d81959f4de559b6
```

**Comment by tabacitu** [comment]
Update: I used the [new asset commands in the demo](https://github.com/Laravel-Backpack/demo/pull/386), then I could switch between CRUD versions and their assets:

```bash
composer bp-assets-link
cd vendor/backpack/crud
git checkout 5.0.13 # the modal shows up
git checkout 5.0.14 # the modal does NOT show up
```

So it looks like the problem did originate in 5.0.14, which just happens to be when we fixed the responsive table header 😅 You can see the diff between the two versions here - https://github.com/Laravel-Backpack/CRUD/compare/5.0.13...5.0.14 - but other than the CSS... I really can't see anything else that might have caused this. There is no DataTables version bump in 5.0.14 (thank god!)

@promatik can you please take a look? I think it'll be easiest for you to get to the bottom of this.

I hope my findings above help.

**Comment by promatik** [comment]
Fix for this is here; https://github.com/Laravel-Backpack/CRUD/pull/4377 🙌
