### ISSUE TITLE
[Bug] Fake Field Attributes on Relation Entity

### ISSUE THREAD

**Issue by jordinbrouwer** [Laravel-Backpack/CRUD#4358]
# Bug report

### What I did
Tried to upgrade Laravel Backpack from version 4.1 to 5 and encountered issues on a relation entity field while using fake field attributes. It seems like the support for this feature has been dropped.

### What I expected to happen
I expect to be able to save fake field attributes on a relation entity.

### What happened
I've created a checkbox field to specify if the location does require a COVID entry pass, this specification is stored in the relation table called `LocationMeta`. This table has a field called `extras` which contains all the fake field attributes.
```php
$this->crud->addField([
    'name' => 'covid_entry_pass',
    'label' => __('Requirement for a COVID entry pass on location'),
    'type' => 'checkbox',
    'entity' => 'meta',
    'model' => LocationMeta::class,
    'fake' => true,
    'store_in' => 'extras',
    'wrapper' => [
        'class' => 'form-group col-md-4',
    ],
    'tab' => __('labels.general'),
]);
``` 
I'm not sure if the support for fake field attributes on a relation entity is dropped on purpose. Whenever I perform a create or update operation I get the following error:
![image](https://user-images.githubusercontent.com/18177037/166888440-7b35d01f-d368-4e53-a174-541d968545ef.png)

### What I've already tried to fix it
This is created by the dropped support since #4127 and is caused by line 99 of the app/Library/CrudPanel/Traits/Create.php file: `$relation = $item->{$relationMethod}();`. I have tried to update the `$relationMethod` to the entity specified on the item which did resolve the undefined method error, but that did create other issues. 

### Is it a bug in the latest version of Backpack?
Yes

### Backpack, Laravel, PHP and DB version
```
### PHP VERSION:
PHP 8.0.16 (cli) (built: Mar  3 2022 08:44:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.16, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.10.1@93414b1c7c0a56081d96c060bb850ac192d3d323

### BACKPACK VERSION:
5.0.15@ec24c10ff3ee69cf0aafef9f16ec1d90c9ba9d7a
```

**Comment by pxpm** [comment]
Hello @jordinbrouwer thanks for the report and sorry for the bad experience. 

Can you please provide me with: the `meta()` relation definition? is it a belongsTo ? 

If it is a belongsTo you should use the `inline_create` to create  the related entries. If it's an `hasOne` you should use either `dot.notation` or the new HasOne container for the relation. 

https://backpackforlaravel.com/docs/5.x/crud-how-to#what-field-should-i-use-for-a-relationship-1

Let me know, if there is some bug I want to kill it 🗡️ !! hehe 🙃 

Cheers

**Comment by jordinbrouwer** [comment]
Hello @pxpm,

Thanks for the quick response. It seems that I'm indeed using a `hasOne` relation. 
```php
public function meta(): HasOne
{
    return $this->hasOne(LocationMeta::class);
}
```

I've updated the name specification with the `dot.notation`.
```php
$this->crud->addField([
    'name' => 'meta.covid_entry_pass',
    'label' => __('Requirement for a COVID entry pass on location'),
    'type' => 'checkbox',
    'fake' => true,
    'store_in' => 'extras',
    'value' => isset($extras) && isset($extras->covid_entry_pass) ? $extras->covid_entry_pass : false,
    'wrapper' => [
        'class' => 'form-group col-md-4',
    ],
    'tab' => trans('labels.general'),
]);
```

Now the functionality seems to work as expected. Sorry for the inconvenience.
