### ISSUE TITLE
Bug with select2_from_ajax_multiple

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#436]
I've struggle to make select2_from_ajax_multiple working.
Once i have figure it out i had another bug coming from this file:
/src/resources/views/fields/select2_from_ajax_multiple.blade.php
line 84
`$.ajax("{{ $field['data_source'] }}" + '/' + "{{ $field['value']  ?? 0 }}", {`

I had to removed the "?? 0".
What is it for ?

**Comment by petyots** [comment]
Hello @adbmdp, So first of all you should not remove it now i think you are going to face another issue somewhere soon, second the " ?? " is [Null coalescing operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)

**Comment by adbmdp** [comment]
Yes i know i should not remove it.

**Comment by petyots** [comment]
Look at my reply please. Thanks :)

**Comment by adbmdp** [comment]
Yes i understand what it is. But i don't know why i'm getting an error.
_syntax error, unexpected '?'_
This is just one bug on a dozen i have...trying to make select2_from_ajax_multiple works.

**Comment by petyots** [comment]
@adbmdp Why you are asking if you know what is it ? Anyway I just tried and it's working fine for me, can you please paste your field/column ? Maybe you did not set it up correctly or the backend does not return proper response... I don't think it's Backpack issue

**Comment by adbmdp** [comment]
Sorry i'll try to debug that myself. At the beginning i just thought the ?? was a bug.
Thanks for your help.

**Comment by tabacitu** [comment]
Hi guys. Indeed, the coalescing operator is a PHP 7 feature. @adbmdp , that's why you're seeing the error.

That being said, it is an error, because we'll try to support any PHP version that the current Laravel supports. I'll go back to PHP 5.6.x and see if I've included PHP7 syntax anywhere else.

If you find any more issues that might be PHP7-related, please let me know.

Cheers!

**Comment by adbmdp** [comment]
Thanks tabacitu

**Comment by tabacitu** [comment]
Just pushed the 3.2.1 update that fixes it! Cheers!

**Comment by adbmdp** [comment]
@tabacitu there is the same problem with select2_from_ajax
It use PHP 7 "??" Null coalescing operator.
