### ISSUE TITLE
[Feature Request] Ability to add different types of repeatable

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#4361]
# Feature Request

### What's the feature you think Backpack should have?
I'm using the `repeatable` feature to plan a driving route with stops and waits. It'd be great to have the option to either 'Add a Stop' or 'Add a Wait', screenshot attached.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1346672/167003932-6dd56de2-082b-4b8d-98f9-2eb97a34ed82.png">

### Have you already implemented a prototype solution, for your own project?
Not yet, would prefer to discuss this to see how it would be best done, and then work on a PR/branch

### Do you see this as a core feature or an add-on?
Core, expansion of the `repeatable` field

**Comment by guleswine** [comment]
I honestly do not really understand the need for this (especially if it's just a repeatable, not relationship), you can simply add a new field, for example

[   // select2_from_array
    'name'        => 'type',
    'label'       => "Type",
    'type'        => 'select2_from_array',
    'options'     => ['stop' => 'Stop', 'wait' => 'Wait'],
    'allows_null' => false,
],

**Comment by pxpm** [comment]
I am tempeted to agree with with @guleswine here, but I am pretty sure that @olipayne probably thought about it and his use-case might be a little different. 
I think that probably they share the two fields (time and address) and then each has its own custom fields. Something like that. 

I think JS API could solve this together with @guleswine solution.

**Comment by olipayne** [comment]
Sleeping on a problem always helps ;) I've decided to go a completely different way, which sticks with the CRUD mentality much more. I appreciate the discussion and other points of view!
