### ISSUE TITLE
[Bug] Noty CSS ?

### ISSUE THREAD

**Issue by ale1981** [Laravel-Backpack/CRUD#4362]
# Bug report

### What I did

Changed the default CSS to blue-bundle.css in config/backpack/base.php

### What I expected to happen

Colours changed to blue

### What happened

Noty alerts lost style

### What I've already tried to fix it

Reverted back to bundle.css

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.18 (cli) (built: Apr 21 2022 10:14:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.18, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.11.0@598a8c84d452a66b90a3213b1d67189cc726c728

### BACKPACK VERSION:
5.0.15@ec24c10ff3ee69cf0aafef9f16ec1d90c9ba9d7a

**Comment by adrienne** [comment]
I can confirm that this problem exists for me with a custom Backstrap bundle as well.

**Comment by cyril-sleiman** [comment]
I have encountered the same bug in backpack version `4.1.69@248e2e034cedcffe01732cdce01fb3d1ecad9ffa`.

**Comment by millefh** [comment]
Same here.

**Comment by tabacitu** [comment]
@promatik can you please take a look at this one? We might need to do the same as https://github.com/Laravel-Backpack/docs/pull/354/files in `blue-bundle.scss`

**Comment by promatik** [comment]
Thank you @ale1981, this is now fixed by #4465, and will be merged soon 👌
