### ISSUE TITLE
[Bug] Repeatable does not work with image field types

### ISSUE THREAD

**Issue by maurohmartinez** [Laravel-Backpack/CRUD#4366]
# Bug report

### What I did
I am using a repeatable field with a subfield of type image.

### What I expected to happen
To display all my subfield images, as it did before upgrade :)

### What happened
I can see a javascript error in console.
`Uncaught ReferenceError: fieldName is not defined`

### What I've already tried to fix it
I see that the problem is in `vendor/backpack/pro/resources/views/fields/repeatable.blade.php:170`
When `getCleanNameArgFromInput` gets called, it assumes all inputs have a name. But field image has an input of type file which doesn't have any name, causing the problem.

### Is it a bug in the latest version of Backpack?
After I run ```composer update backpack/crud``` the bug... is it still there?
YES

### Backpack, Laravel, PHP, DB version
When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.5 (cli) (built: Apr 16 2022 00:03:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.11.0@598a8c84d452a66b90a3213b1d67189cc726c728

### BACKPACK VERSION:
5.0.15@ec24c10ff3ee69cf0aafef9f16ec1d90c9ba9d7a

**Comment by pxpm** [comment]
Hello @maurohmartinez . Thanks for the report and sorry for the bad experience. 
I could reproduce the issue and submitted a PR to fix it, should probably be tagged by tomorrow, I will keep this open until then.

Once again, thanks for the report. 

Cheers
