### ISSUE TITLE
[Bug] 5.0.16 breaks PermissionManager default field

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#4369]
# Bug report
Upgraded to 5.0.16, trying to edit a user with roles, with exactly the field defined here - https://github.com/Laravel-Backpack/PermissionManager/blob/master/src/app/Http/Controllers/UserCrudController.php#L172

Throws the error:
```
Array to string conversion
```

### What I've already tried to fix it
Reverting to 5.0.15 fixes the issue

**Comment by pxpm** [comment]
Hello @olipayne 

Sorry for the bad experience 🙃 that's on me! 

Just submitted the PR to fix it, it's a "technicality" about one of our fields that I completely forgot about! 

@tabacitu should tag it soon.

Cheers

**Comment by olipayne** [comment]
To be pedantic, I feel like this issue should stay open until there is a release published which fixes it. My concern is that others will come along and not find any similar issue in the "Open Issues" list, which was my first place to look before creating this one.

**Comment by pxpm** [comment]
You are right, it closed automatically when PR got merged. 

Cheers

**Comment by olipayne** [comment]
Oh I had no idea, thanks for reopening!

**Comment by tabacitu** [comment]
Merged & tagged. Thanks guys! 🙏

PS. How did nobody else notice and report this for 2 months?! Damn. Thanks again @olipayne .
