### ISSUE TITLE
[Bug] checkbox Field (possibly others) without pivot table doesn't work for create or update 

### ISSUE THREAD

**Issue by guleswine** [Laravel-Backpack/CRUD#4375]
# Bug report

### What I did
I had a code exactly working on backpack 4.1

Controller
```
CRUD::addField([   // Checklist
            'label'     => 'Sources',
            'type'      => 'checklist',
            'name'      => 'sources',
            'entity'    => 'sources',
            'attribute' => 'name',
            'model'     => "App\Models\Source",
            'pivot'     => false,
            'options'   => (function ($query) {
                return $query->where('accept_income_message', 1)->get()->pluck('name','id');
            }),
        ]);
```

Model
```
protected $casts = [
        'sources' => 'array',
    ];

public function sources()
    {
        return $this->hasMany(Source::class);
    }
```

### What happened
Today I tried to use it
### Create
$relationValues contains string -   **["2"]**
![image](https://user-images.githubusercontent.com/23197378/168478923-80991bea-d305-4a48-954e-d32f6e4baa34.png)

### Edit
$model contains string - **2**
![image](https://user-images.githubusercontent.com/23197378/168478885-0a599e5c-3396-40c9-9110-ecde986e03bf.png)

Value **2** In both cases, this is the entity ID of the model Source

### What I've already tried to fix it

perhaps this is partly due to

https://github.com/Laravel-Backpack/CRUD/commit/e647620bad7b70bfb33e8bbafb8f7ec334c06c2d

### Is it a bug in the latest version of Backpack?

last version

**Comment by tabacitu** [comment]
@pxpm could you please take a look?

**Comment by pxpm** [comment]
Hello @guleswine

Thanks for the report.

I think that if you don't want to save the relation you should use `entity=>false`, would that help you here ? 

But from my understanding if you are at this point, what you are probably looking at is a `belongsToMany` relation because it seems your `sources` table is partially static, and you store the selected `sources` in a `sources` column in the current table, am I rigth ? 

Let me know.

**Comment by guleswine** [comment]
Oh, I had an extra step, the relationship in the model is not needed. Probably for some reason this did not interfere with version 4.1.
