### ISSUE TITLE
FatalErrorException in CrudTrait.php line 224:

### ISSUE THREAD

**Issue by jdfx** [Laravel-Backpack/CRUD#438]
Package updated and this happened?

**Comment by jdfx** [comment]
syntax error, unexpected ':', expecting ';' or '{'

**Comment by jdfx** [comment]
```
    /**
     * Get the attributes that were casted in the model.
     * Used for translations because Spatie/Laravel-Translatable
     * overwrites the getCasts() method.
     *
     * @return [type] [description]
     */
    public function getCastedAttributes() : array // <- line 224
    {
        return parent::getCasts();
    }
```

**Comment by jdfx** [comment]
Ah, new PHP7 syntax.

This is a breaking change for older systems. My homestead box is still on 5.6.

Either need to roll it back to older syntax or stipulate in the readme this package only now works with PHP 7.

**Comment by jdfx** [comment]
For anyone else having this issue the break is in version 3.2.

Roll back to 3.1 for a quick fix.

"backpack/crud": "3.1",

I will look to upgrade my environment to PHP7 asap.

**Comment by tabacitu** [comment]
Hi @jdfx ,

Thanks a lot for the issue. It seems I included some PHP7 features in 3.2. I've just had a quick look through the project and removed the obvious. A ```composer update``` should fix it for you and you'll be able to use 3.2.

In the meantime I'll keep looking for PHP7 quirks and fix them. If you find any more issues like this, please let me know.

Cheers!

**Comment by jdfx** [comment]
Thanks for the super-fast response Cristian.

And for the great package!

**Comment by hananint** [comment]
Hi tabacitu,
File HasTranslation.php also has php 7 syntax which is breaking in my environment. 
Line 58 locale =  $attributes['locale'] ?? \App::getLocale();
and line 90.

**Comment by tabacitu** [comment]
@hananint unfortunately I think you won't be able to use HasTranslations unless you're on PHP 7. It uses a Spatie package, and they're pretty strict about using PHP 7. So _even if_ our trait worked, their package would not allow it...
