### ISSUE TITLE
[Bug] Data picker don't load default app locale automatically

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/CRUD#4380]
# Bug report
Field date_picker.blade.php don't load default app locale automatically.

### What I did
Use field date_picker without `date_picker_options` or without `language`.

### What I expected to happen

After seeing this line I expected it to detect the language automatically.

```php
$field_language = isset($field['date_picker_options']['language']) ? $field['date_picker_options']['language'] : \App::getLocale();
```

### What happened

Yes, this line wroks. Yes in my case loads(spanish) `packages/bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js)` but the datapicker don't use it. Only works if you specified a `language` in `date_picker_options`. 
The problems is related to this code don't specified the `language`.
```php
 $customConfig = $.extend({
                format: 'dd/mm/yyyy'
            }, $fake.data('bs-datepicker'));
```

### What I've already tried to fix it

I use `\App::getLocale()` in the config crud controller in field definition.

```php
'date_picker_options' => [
      'todayBtn' => 'linked',
      'format'   => 'dd-mm-yyyy',
      'language' => \App::getLocale()
],
```

### Is it a bug in the latest version of Backpack?

Yes. 
5.0.17 backpack/crud
1.0.16 backpack/pro

### Backpack, Laravel, PHP, DB version

PHP 8.1
Laravel v9.12.2

**Comment by adriallongarriu** [comment]
The field `datetime_picker.blade.php` has a similar error. If you don't set language in `datetime_picker_options` it's always show in english.

**Comment by pxpm** [comment]
Hello @adriallongarriu 

Thanks for spotting this issue and letting us know. 

I've just submitted a PR that should fix this, indeed is completely unintuitive that you need to re-define the app language in field definition for it to pick the correct one. 

I expect this to be merged along with some other stuff probably by next Monday if nothing urgent pops up that need some hotfix.

I will leave this open until then!

Cheers, thanks! 👏

**Comment by tabacitu** [comment]
Totally! I've just merged Pedro's PR, so it'll be launched with the next tag, which will be Monday the latest.

Thanks @adriallongarriu . Cheers!
