### ISSUE TITLE
[EDITION] select2 fields doesn't works on edit view

### ISSUE THREAD

**Issue by welcoMattic** [Laravel-Backpack/CRUD#44]
I have an Article model that have an author field (user_id).
In my ArticleCrudController, I add the followed field:

```php
$this->crud->addField([
        'label' => 'Author 
        'type' => 'select2',
        'name' => 'user_id',
        'entity' => 'user',
        'attribute' => 'name',
        'model' => User::class
    ], 'both');
```

It works fine on create view, but completely not on edit view.
Instead of my select2 field, I see a number field, and it's broken because of this error:

```
htmlentities() expects parameter 1 to be string, array given. 
```

Located in `number.blade.php`.

**Comment by tabacitu** [comment]
@welcoMattic , (1) have you found a way around this or is this still a problem?

From what I can see, you're missing a comma there, that might be the issue. Here's how I'd write it:

```php
$this->crud->addField([
        'label' => 'Author' 
        'type' => 'select2',
        'name' => 'user_id',
        'entity' => 'user',
        'attribute' => 'name',
        'model' => 'App\User'
    ], 'both');
```

(2) Does this work for you?
