### ISSUE TITLE
[Bug] Translate Repeatables Error "Cannot use object of type stdClass as array"

### ISSUE THREAD

**Issue by nikolai-nikolajevic** [Laravel-Backpack/CRUD#4405]
# Bug report

### What I did

I have the field "jobs" and its a translatable field stored as fake in the extras column

```
$this->crud->addField([
    'name'  => 'jobs',
    'label' => 'Jobs',
    'type'  => 'repeatable',
    'new_item_label'  => 'Job Hinzufügen',
    'subfields' => [
        [
            'name'    => 'job_title',
            'type'    => 'text',
            'label'   => 'Bezeichnung',
        ]
    ],
    'fake' => true,
    'store_in' => 'extras',
    'tab' => 'Jobs',
]);
```

https://user-images.githubusercontent.com/37556958/171162258-ed41b199-898a-41e1-bc9f-b546d054e7a9.mov

### What I expected to happen

Translation like other fields 😅 

### What happened

The data is stored in the database like
```
{
	"de": {
		"jobs": [
			{
				"job_title": "Koch"
			}
		]
	}
}
```
but after saving and when I want to edit the entry the error occurs

### What I've already tried to fix it

Hack around the line 66 in the file `app/Http/Middleware/CheckIfAdmin.php`

### Is it a bug in the latest version of Backpack?

Don't know. I'm using backpack since yesterday

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

#### PHP VERSION:
PHP 8.1.5 (cli) (built: Apr 16 2022 00:03:52) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies

#### LARAVEL VERSION:
v9.14.1@2ca86f96118635a79ee3389013ccab110ae14bea

#### BACKPACK VERSION:
5.0.19@a71715d51a0bd2827d535deb407761ee9252d044

**Comment by promatik** [comment]
Hi @nikolai-nikolajevic, sorry for taking so long to answer you!

Indeed there was an issue with the repeatable field, it was not ready for fake and translatable usage simultaneous.

I've open a PR to fix the issue, https://github.com/Laravel-Backpack/PRO/pull/76.
