### ISSUE TITLE
[Feature] Static field.

### ISSUE THREAD

**Issue by petyots** [Laravel-Backpack/CRUD#441]
Hi guys, i already made PR about this.The static field is very useful in update case for example where the user does not have enough permissions to update this fields or just the fields should not be edited in any way. You can make text type disabled but a user with some basic knowledge in web development will be able to change the value and submit it. You can make sure that this will not happen  with FormRequest, but i think will be easier just to make the field static so it does not get posted. Thanks

**Comment by dobromir-hristov** [comment]
Just today I needed a field to be read only after its saved once, and because it was Unique it was trying to save over it and giving me an error.

**Comment by OwenMelbz** [comment]
@dobromir-hristov

Readonly fields in HTML still post to the server.
Disabled fields do not. This is the HTML spec

You can try making it disabled to solve your issue, or remove it from the request before doing a mass update. Which could easily be done via this PR https://github.com/Laravel-Backpack/CRUD/pull/283 - so until that's merged you'll have to figure out a different way to handle it

**Comment by petyots** [comment]
@OwenMelbz I am sure that static fields does not post to the server

**Comment by OwenMelbz** [comment]
I'm talking about input fields with disabled or readonly attributes, I'm not sure what you mean by static fields tbh

**Comment by petyots** [comment]
`<p class="form-control-static">{{$field['value']}}</p>` from Twitter Bootstrap 3

**Comment by jsiebach** [comment]
I did it like this:

```
<!-- static input -->
<div @include('crud::inc.field_wrapper_attributes') >
    <label>{!! $field['label'] !!}</label>
    <br>
    <span>{{$entry->{$field['name']} }}</span>
</div>
```

Just copied the text input and changed `<input>` to `<span>`

**Comment by OwenMelbz** [comment]
Just incase you didnt know you can have something like 

$this->crud->addField([
     'name' => 'some field',
    'label' => 'some label',
    'attributes' = ['disabled' => 'disabled]
]);

this would create a field that displays the data but cannot be changed, that doesnt need any custom code/adjustments

**Comment by tabacitu** [comment]
Hmm... I have to agree with @OwenMelbz on this one. We already have the ```text``` and ```textarea``` field types that can do that, if you give them the ```disabled``` attribute, so I don't think separate field types are necessary for this.

Perhaps we should better document this feature, rather than add new fields. I'll see where I can include this in the docs.

Cheers!

**Comment by Rinaldi91** [comment]
how to disable field_name in laravel backpack?
$field_name = [
            'name' => 'name',
            'label' => 'City Name',
              'disabled' => 'disabled'
            ];
            $this->crud->addField($field_name,'both');

this is not work,,,

**Comment by OwenMelbz** [comment]
@Rinaldi91 read up ^^^

**Comment by Rinaldi91** [comment]
@OwenMelbz do you mean to use something like this?
$this->crud->addField([
     'name' => 'some field',
    'label' => 'some label',
    'attributes' = ['disabled' => 'disabled]
]);

i try to use this, but not work
