### ISSUE TITLE
Weird backslashes in JSON

### ISSUE THREAD

**Issue by mattiasstrubbe** [Laravel-Backpack/CRUD#442]
When making the 'extra' field translatable, some weird backslashes appearing in the database.

`{"en":"{\"meta_title\":\"Some text\",\"meta_description\":\"Some text\"}","fr":"{\"meta_title\":\"Some text\",\"meta_description\":\"Some text\"}"}`

Have not tried this with custom fake fields.
Might have something to do with being set encoded as JSON twice (fake field + translatable field).

**Comment by tabacitu** [comment]
Hi @mattiasstrubbe ,

You're right, it's now fixed. Your JSONs will get saved properly the next time someone edits the item. My assistant tells me you've actually reported this issue before, sorry for not getting to it sooner.

Cheers!

**Comment by tabacitu** [comment]
A ```composer update``` should do it for you.
