### ISSUE TITLE
[Bug]  After upgrading to pro cannot usa any pro fields

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4436]
# Bug report

### What I did

A previous 4.1 has b een upgraded to v5.0 
We have license for pro

### What I expected to happen

I expect for example to be able to use "select2_from_array" as field type

### What happened

Code crash because cannot find the view for "select2_from_array"

### What I've already tried to fix it

I've no idea on what to do.
I deleted composer.lock and vendor folder and reinstalled

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.16 (cli) (built: Feb 16 2022 09:37:01) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies
### LARAVEL VERSION:
v9.16.0@dbad869e737542734c48d36d4cb87ee90455c4b8
### BACKPACK VERSION:
5.0.20@a6b183978fc7c206ce9cd437e5c9b96f8fb6823f

**Comment by realtebo** [comment]
Resolved with an `opt:clear`

**Comment by siemike** [comment]
@realtebo 
I also experienced same like this. I've updated to backpack 5 from 4 and already repurchase the pro. but i found the error when use pro field
"View [fields.image] not found"

I run the php artisan backpack:version and here's the result

### PHP VERSION:
PHP 8.1.0 (cli) (built: Nov 26 2021 11:40:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.26@7411d9fa71c1b0fd73a33e225f14512b74e6c81e

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

and also running php artisan optimize:clear but is not working as well

**Comment by jrbecart** [comment]
I had the same issue.

I did without success:
```script
composer dump-autoload
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan optimize
```

BUT with clear it works perfectly:  (maybe add it in the doc ??)
```php artisan optimize:clear```
