### ISSUE TITLE
[Bug] Select2 keep showing "Searching" in ajax with pivot (n-n)

### ISSUE THREAD

**Issue by CamusMX7** [Laravel-Backpack/CRUD#4437]
# Bug report

### What I did

It's my first report. I upgrade backpack the last week and some Select's field stopped working, The problem is similar to that specified in [Select2 keep showing "Searching" in ajax with pivot (n-n) in Laravel Backpack 5 Pro](https://stackoverflow.com/questions/71768482/select2-keep-showing-searching-in-ajax-with-pivot-n-n-in-laravel-backpack-5/72536131)

My field was:

`        $this->crud->addField([
            'name'          => 'precios',
            'type'          => "relationship",
            'pivotSelect'  => [
                'ajax' => true,
                'inline_create' => [ 'entity' => 'precio' ],
                'data_source' => backpack_url('orden-trabajo/fetch/precio'),
                // 'placeholder' => 'Seleccione un elemento',
                'minimum_input_length' => 0,
                'wrapper' => [
                    'class' => 'col-md-3'
                ],
                'attributes' => [
                    'required'    => 'required',
                ],
                // 'events' => [
                //     'saving' => function ($entry) {
                //         dd($entry);
                //     },
                // ],
            ],
            'subfields'     => [
                [
                    'name' => 'costo',
                    'type' => 'text',
                    'label' => 'Costo',
                    'wrapper' => [
                        'class' => 'form-group col-md-2',
                    ],
                ],
                [
                    'name' => 'cantidad',
                    'type' => 'text',
                    'wrapper' => [
                        'class' => 'form-group col-md-1',
                    ],
                    // 'attributes' => [
                    //     'required'    => 'required',
                    // ],
                ],
                [
                    'name' => 'duracion',
                    'type' => 'text',
                    'wrapper' => [
                        'class' => 'form-group col-md-3',
                    ]
                ],
            ],
            'tab'           => "Precios",
            'force_delete'  => true
        ]);`

### What I expected to happen

I expected it to show the elements of "Precios". And this was working fine before updating last week.

### What happened

Now, the select keep showing "Searching" and don't show de result. 

### What I've already tried to fix it

I try the answer in:
[Select2 keep showing "Searching" in ajax with pivot (n-n) in Laravel Backpack 5 Pro](https://stackoverflow.com/questions/71768482/select2-keep-showing-searching-in-ajax-with-pivot-n-n-in-laravel-backpack-5/72536131)

"The problem seems to be related to the relationship field type inside the pivotSelect. Try to use select2_from_ajax instead and don't forget to set method to POST explicitly, that worked for me like a charm."

And for the moment that works for me but the bug is still there.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?  YES

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
v9.15.0@dc32641f5963578858fb71a9d2fbf995fe1e1ea3

### BACKPACK VERSION:
5.0.20@a6b183978fc7c206ce9cd437e5c9b96f8fb6823f

**Comment by pxpm** [comment]
Hello @CamusMX7 

Thanks again for the issue report. 🙏 

Just to let you know that it's merged and tagged. A composer update will do the trick. 

Let me know if you find something else. 

Cheers
