### ISSUE TITLE
[Feature Request] Allow in-same-form editing for HasOne relationships

### ISSUE THREAD

**Issue by adrienne** [Laravel-Backpack/CRUD#4449]
# Feature Request

### What's the feature you think Backpack should have?

Currently you can use this feature https://backpackforlaravel.com/docs/5.x/crud-fields#manage-related-entries-in-the-same-form-create-update-delete to manage related entries in the same form if you have a HasMany or MorphMany relationship, and I would really like that to also work for HasOne/MorphOne relationships. 

It would be basically identical to the existing functionality (specify the subfields and have it show up) but without being able to add a New Item after the first one is added. 

### Have you already implemented a prototype solution, for your own project?

No, I'm just using a clumsy workaround that involves fake fields and overriding the create/store traits.

### Do you see this as a core feature or an add-on?

Core feature (it should be able to detect the relationship type and behave accordingly)

**Comment by pxpm** [comment]
Hello @adrienne .

It should be fully supported. 

Have a look at: https://backpackforlaravel.com/docs/5.x/crud-how-to#hasone-1-1-relationship

Let me known,
Cheers

**Comment by pxpm** [comment]
Hello @adrienne 

I am closing this as I think both relationships are properly working as you describe.

Not sure if you tried and found any bug, if that is the case please comment your issue so I can re-open this. 

Thanks and cheers!
