### ISSUE TITLE
[Bug] Save Actions do not work on custom operations

### ISSUE THREAD

**Issue by adrienne** [Laravel-Backpack/CRUD#4450]
# Bug report

### What I did

I created a custom operation using a Trait as specified in https://backpackforlaravel.com/docs/5.x/crud-operations#creating-a-custom-operation-1

### What I expected to happen

I expect to get an otherwise normal CRUD panel with save operations, etc, that I can add stuff to

### What happened

It doesn't get any save actions, and using `$this->crud->addSaveAction([(stuff)]);` doesn't work. I can manually add a submit button to my form, but then I don't seem to get error handling or anything else. 

### Notes

It may be that the documentation for how to add a custom operation with a form isn't complete, or I may be doing something wrong, but the documentation doesn't give me any way to tell and the obvious things I am trying do not work.

**Comment by pxpm** [comment]
Hello @adrienne 

I think in the next day we will be lauching an Article that has that ability as an example. 

Basically the save actions are displayed in `create` and `update` operations views, you can have a look at them to know how to add the save actions into a custom view. 

What I usually do when I need an operation that is a "form", I usually do `php artisan backpack:publish crud/create`, it will publish the create view, rename it as you like and use it as the operation view. 
All should be fine ... Let me know if you have any issues.

Cheers

**Comment by tabacitu** [comment]
I think I understand what @adrienne 's expectations were here, that we weren't met. If devs expect to be able to create "_custom operations with custom forms_" we should make that easier. I've added https://github.com/Laravel-Backpack/ideas/issues/147 a little time ago - I think that better describes this problem (and the solution).

In short, @adrienne , what you'll be able to do is create a custom operation (like you already did) but that operation will already include a form (and the save actions). 

That's what you were looking for, correct? I think so, so let's close this issue in favor of continuing the conversation in https://github.com/Laravel-Backpack/ideas/issues/147 . If I'm wrong, of course, let us know and we'll reopen.

Cheers!

**Comment by tabacitu** [comment]
PS. That article got delayed. It's been split into 4 different articles, which will be coming one-by-one every week starting next week. This also proves my point - what @adrienne was trying to do was unnecessarily difficult to do / difficult to understand, that's why we had to split it into multiple articles. We can do better.
