### ISSUE TITLE
[Feature Request] Allow changing labels in new CRUD fields JS API

### ISSUE THREAD

**Issue by adrienne** [Laravel-Backpack/CRUD#4451]
# Feature Request

### What's the feature you think Backpack should have?

Hi, folks! I LOVE the new JS fields API, i'm already using it for some stuff I had hacked together before and it's magnificent! My one request is: can you allow us to change the *labels* on fields as well as other options?

For example, I've got a field `vendor`. In the database it's always the same field. But dependent on the value of another field, `type`, i would like to change the *label* to 'Payee' just for a better user experience.

### Have you already implemented a prototype solution, for your own project?

Currently I'm just labeling my fields in a way that is more generic ("Vendor or Payee", in the case of the above example.) 

### Do you see this as a core feature or an add-on?

Core feature. I would think it would be pretty easy to add to the existing API?

**Comment by pxpm** [comment]
Hello @adrienne I am not sure if that is something 90%+ of devs will use, that said I will try to make my point.

I get your use case, and you can totally find the label from the field wrapper (you have it available in the callback as `field.wrapper`) and manually change it to fit your scenario. 

I really don't think that "re-labeling" is something we should support in core as it is pretty easy to do for the people who need it, but I am pretty sure it's a niche use case and not something we should be maintaining in the future as I don't think alot of people need it. 

Something like `field.wrapper.find('label')` should give you the field label in most of fields, and you can easily change the html inside that element to be whatever you want. 

I will be closing this, let me know if you have any issue implementing the solution I described, it should be no more than one line. 

I've been wrong alot of times before, and I wouldn't be suprised if this is the case, please let me know if you think that I am wrong, and why. 

Thanks,

Cheers.
