### ISSUE TITLE
[Feature or Documentation Request] - CrudField JavaScript Library with relationship/subfield fields

### ISSUE THREAD

**Issue by singeryo** [Laravel-Backpack/CRUD#4452]
# Feature Request

### What's the feature you think Backpack should have?

I love the new CrudField JavaScript Library feature. However I coudn't get it to work with a relationship field with subfields. Is it because it is not possible yet ? If it is, maybe add some documentation for this ?

I can see the "repeatable" example in the docs and that was exactly what i wanted to achieve, but no way to make it work with a 1-n type field with subfields.

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core feature

**Comment by singeryo** [comment]
Hello @pxpm !

Sure, here we are:

In Crud controller :
```php
CRUD::field('payments')->label(__('Payments'))->fieldset(__('Sale'))
            ->type('relationship')
            ->subfields([
                [
                    'name' => 'paymentMethod',
                    'label' => __('Payment method'),
                    'wrapper' => [
                        'class' => 'col-md-4 payment-method',
                    ],
                ],
                [
                    'name' => 'amount',
                    'label' => __('Amount'),
                    'prefix'     => "€",
                    'type' => 'number',
                    'wrapper' => [
                        'class' => 'form-group col-md-4',
                    ],
                ],
                [
                    'name' => 'date',
                    'label' => __('Date'),
                    'type' => 'date',
                    'wrapper' => [
                        'class' => 'form-group col-md-4',
                    ],
                ],
                [
                    'name' => 'precisions',
                    'label' => __('Precisions'),
                    'wrapper' => [
                        'class' => 'form-group col-md-4 precisions',
                    ],
                ]
            ]);
```

The entity relationship definition:
```php
    public function payments(): HasMany
    {
        return $this->hasMany(Payment::class, 'transaction_id');
    }
```

The JS file:

```Javascript
crud.field('payments').subfield('paymentMethod').onChange(function(field) {
    // Note that the result is the same if I try another subfield that is a simple attribute such as "amount"
    console.log('something changed'); // This is never logged
    crud.field('payments').subfield('precisions', field.rowNumber).show(field.value == 14);
}).change();
```

**Comment by pxpm** [comment]
Hello @singeryo 

I was trying to reproduce your issue, unfortunatelly I was not able to do that. But it helped me to find another issue that I already sent a PR to fix. 
It's not related with your issue so I am still unable to reproduce your issue. 

You can see here I am using an `HasMany` relation as you describe: https://recordit.co/tHQ46tWXbH

This is my JS: 

```javacript
crud.field('postalboxes').subfield('postal_name').onChange(function(field) { 
  console.log('hey i am here on row: ' + field.rowNumber) 
  console.log(field)
})
```

Can you make sure you are not overriding some backpack fields ? Since there were changes in pretty much every field to accomodate this JS feature, if you are overriding any of them you don't get the updated versions. 

Let me know,
Cheers

**Comment by singeryo** [comment]
Hi @pxpm thanks for the update ! Now I know for sure it is intented to be achievable, something is probably wrong on my end.

I'll try to fish in to that today, what I can tell for now is that I'm not overring any existing backpack fields, although I am overriding the `resources/views/vendor/backpack/crud/inc/show_fields.blade.php` file to add a fieldset feature, maybe it has something to do with that.

I'll keep you posted,
Cheers

**Comment by pxpm** [comment]
@singeryo It probably has .. because we rely on dom structure to find the correct inputs and wrappers. 

You can have a look at `vendor/backpack/crud/src/resources/views/crud/inc/form_fields_script.blade.php` and `console.log()` there.

Let me know.

**Comment by singeryo** [comment]
Hello @pxpm, I finally figured it out, I only upgraded backpack/crud to 5.1 and didn't think to upgrade backpack/pro ... Just thought of that right now, upgraded the pro package + cleared cache views and it works !

Thank you for the support in any case and nice work on this feature !
Cheers

**Comment by maverjk** [comment]
I'm doing some test using something like that:
`        CRUD::addField([
            'name'  => 'Customer',
            //'label' => 'Customer',
            'type'  => 'relationship',
            'ajax' => true,
            'subfields'   => [
                [
                    'label' => 'Name',
                    'name' => 'NOM_CL',
                    'type' => 'text',
                    'wrapper' => [
                        'class' => 'form-group col-md-3',
                    ],
                ],
                [
                    'label' => 'Address',
                    'name' => 'IND_CL',
                    'type' => 'text',
                    'wrapper' => [
                        'class' => 'form-group col-md-9',
                    ],
                ],
            ],
        ]);`

and inside my JS:
`crud.field('Customer').subfield('NOM_CL').input.value = 'TEST-022';`

But it doesn't work. I don't know if there is anything that I'm doing wrong, from my analysis JS command is going to populate an hidden input field inside 'Customer' div:

`<div class="form-group col-sm-12 repeatable-group" element="div" bp-field-wrapper="true" bp-field-name="Customer" bp-field-type="repeatable">
<label>Customer</label>
<input type="hidden" name="Customer" data-init-function="bpFieldInitRepeatableElement" class="form-control" data-initialized="true" value="TEST-022">
...
`

**Comment by tabacitu** [comment]
@maverjk shouldn't you also specify the row number for that subfield? What I mean is... I think doing `subfield()` without a second parameter (row number) will select ALL subfields, so you probably want to:
- `console.log(crud.field('Customer').subfield('NOM_CL').input)` to see exactly what you're working with there;
- change the value on the subfield within the same row, so something like:

```php
crud.field('Customer').subfield('NOM_CL').onChange(function(field) {
    crud.field('Customer').subfield('IND_CL', field.rowNumber).input.value = 'TEST-022';
 });
```

Hope it helps!

**Comment by maverjk** [comment]
hi @tabacitu, I tried your solution but it doesn't work as I need. Basically, I need to change values in subfield "IND_CL", inside a method already triggered by another event. "field.rowNumber" in my case it's 1 so if I would like to use your protocol shall I write something like that?
`
 crud.field('Customer').subfield('IND_CL', 1).input.value = 'TEST-022';
`

By the way my working solution use simple nested jQuery selectors:
`
$('[bp-field-name="Customer"] input[type="text"][name*="NOM_CL"]').val('Test-022');
`

**Comment by pxpm** [comment]
Indeed @maverjk, you should target the input with the corresponding row so the value can be changed. 

See here: https://recordit.co/AN21h3ub9v

If you want to use a  default value in the field you can set `'default' => 'Test-022'` on the field definition.

Cheers
