### ISSUE TITLE
Class "Backpack\CRUD\App\Http\Controllers\CrudController" not found [Bug] 

### ISSUE THREAD

**Issue by ahmadms-dev** [Laravel-Backpack/CRUD#4454]
# Bug report
i used a tenancy for laravel package 
in windows every thing is working 
in the linux server i faced that error 
Class "Backpack\CRUD\App\Http\Controllers\CrudController" not found

![image](https://user-images.githubusercontent.com/80806155/174228043-23e6c62a-4f80-4039-b4de-142731c05fea.png)

**Comment by ahmadms-dev** [comment]
**solved**
i replaced `use Backpack\CRUD\App\Http\Controllers\CrudController` with
 `use Backpack\CRUD\app\Http\Controllers\CrudController`
it is linux case sensitivity

**Comment by pxpm** [comment]
Thanks for sharing the solution @ahmadms-dev 

I am sure it will help someone in future. 

Cheers
