### ISSUE TITLE
Problem with select2_from_ajax_multiple

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#446]
I have a field with a select2_multiple that is working well (but i have a lot a data so it's pretty slow).
I want to replace it with the new select2_from_ajax_multiple.

My select2_multiple:
```
$this->crud->addField([
            'label' => "Relance à faire",
            'type' => 'select2_multiple',
            'name' => 'relances',
            'entity' => 'relances',
            'attribute' => 'full_name',
            'model' => "App\Models\Personne",
            'pivot' => true
        ],'update');
```

My select2_from_ajax_multiple:
```
$this->crud->addField([
            'label' => "Relance à faire",
            'type' => "select2_from_ajax_multiple",
            'name' => 'idPersonnes',
            'entity' => 'relances', 
            'attribute' => "full_name", 
            'model' => "App\Models\Personne", 
            'data_source' => url("admin/relanceajax"),
            'placeholder' => "Selectionner une personne",
            'minimum_input_length' => 2,
            'pivot' => true
        ],'update');
```

It works as i can type in the fields, i have results and i can select many items. But when i save i have this error:
_BadMethodCallException in Builder.php line 2508:
Call to undefined method Illuminate\Database\Query\Builder::idPersonnes()_

I've try with 
```
'name' => 'relances',
'entity' => 'relances', 
```
But then i have this error:
_ErrorException in InteractsWithPivotTable.php line 132:
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::formatRecordsList() must be of the type array, string given, called in /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php on line 96 and defined_

Also i when open an edit view for a record that already have some data in the pivot table nothing is displayed.

If somebody can give me a clue... Thanks you.

**Comment by adbmdp** [comment]
Someone managed to make select2_from_ajax_multiple work ?
I still have this bug...

**Comment by webaction** [comment]
I am also having a problem just like the one mentioned in this issue.

I have managed to make changes that have resolved most of the bugs with the implementation of the select2_from_ajax_multiple field type.

Before I submit a patch, I would like to know if anyone else has been able to implement with-out changes?

**Comment by adbmdp** [comment]
@webaction can you submit your patch? So @tabacitu can review it.
Thanks.

**Comment by adbmdp** [comment]
@webaction can you post your code please?

**Comment by Muhammadinaam** [comment]
Please solve this issue

**Comment by Muhammadinaam** [comment]
I think following is the solution.

continuing with example above:

'name' is not **the column that contains the ID of that connected entity;** as stated in documentation. it is actually the method name of relation. as shown in following code.

```
'name' => 'relances',
'entity' => 'relances', 
```

After this. I added following line

`$values = is_array($values) ? $values : explode(',', $values);` (Line No. 6)

in following function in **trait Create** i.e. Backpack\CRUD\PanelTraits\Create.php

```
public function syncPivot($model, $data, $form = 'create')
    {
        $fields_with_relationships = $this->getRelationFields($form);

        foreach ($fields_with_relationships as $key => $field) {
            if (isset($field['pivot']) && $field['pivot']) {
                $values = isset($data[$field['name']]) ? $data[$field['name']] : [];
                $values = is_array($values) ? $values : explode(',', $values);
                $model->{$field['name']}()->sync($values);

                if (isset($field['pivotFields'])) {
                    foreach ($field['pivotFields'] as $pivotField) {
                        foreach ($data[$pivotField] as $pivot_id => $field) {
                            $model->{$field['name']}()->updateExistingPivot($pivot_id, [$pivotField => $field]);
                        }
                    }
                }
            }

            if (isset($field['morph']) && $field['morph']) {
                $values = isset($data[$field['name']]) ? $data[$field['name']] : [];
                if ($model->{$field['name']}) {
                    $model->{$field['name']}()->update($values);
                } else {
                    $model->{$field['name']}()->create($values);
                }
            }
        }
    }
```

**Comment by tabacitu** [comment]
Hi guys,

Just pushed an update on the ```dev``` branch - I've upgraded all select2 fields to the latest select2.js. That update also fixes this issue, I believe. If you can please test&confirm, that would be great. If not, you'll have access to these modifs next week, when they'll be on the ```master``` branch.

Cheers!

**Comment by adbmdp** [comment]
Still not working for me.

**Comment by Jitendernagar** [comment]
I have updated latest version, its working fine on save. But edit case this is not working. so please change on select2_from_ajax_multiple.blade.php.
 <select
        name="{{ $field['name'] }}[]"
        style="width: 100%"
        id="select2_ajax_multiple_{{ $field['name'] }}"
        @include('crud::inc.field_attributes', ['default_class' =>  'form-control'])
        multiple>

        @if ($old_value)
            @foreach ($old_value as $result_key)
                @php
                    $item = $connected_entity->find($result_key);
                @endphp
                @if ($item)
                <option value="{{ $item->getKey() }}" selected>
                    {{ $item->{$field['attribute']} }}
                </option>
                @endif
            @endforeach
        @endif
    </select>

to 

  <select
        name="{{ $field['name'] }}[]"
        style="width: 100%"
        id="select2_ajax_multiple_{{ $field['name'] }}"
        @include('crud::inc.field_attributes', ['default_class' =>  'form-control'])
        multiple>

        @if ($old_value)
            @foreach ($old_value as $result_key)
                <option value="{{ $result_key->id }}" selected>
                    {{ $result_key->name }}
                </option>
            @endforeach
        @endif
    </select>

Thanks,
Jitender Gurjar.
