### ISSUE TITLE
[Feature Request] ViewerJs Column

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#4467]
I think it will be really cool to have the ViewerJS Column

https://viewerjs.org/

https://viewerjs.org/examples/

https://github.com/webodf/ViewerJS_release

With this column, admins don't have to download the file to their computer for the most common document file types, they can just view it in their browser in the show view, excel, word, pdf, powerpoint & other open document formats.etc

If the file is in the S3 bucket instead of the same server, the user may need to configure their S3 bucket CORS settings.

Other alternatives including passing the online file path to Google Docs Viewer or Microsoft Online Viewer in an iframe, but that involves passing the file to Google & Microsoft which some people do not want.

As for other javascript libraries that does the same thing as ViewerJS, I'm not aware of any at the moment.

Behind the scenes ViewerJS use the below 2 libraries for most of the heavy lifting:

https://mozilla.github.io/pdf.js/

https://github.com/webodf/WebODF

**Comment by ziming** [comment]
Indeed, the last official release is somewhere in 2015 to my knowledge

I originally thought about trying to make a PR for it, but I came to the conclusion that you all might prefer it to be in pro instead, hence I did not try to make a PR.

I have not tried that library yet.

**Comment by pxpm** [comment]
Ok, thanks @ziming .
If you happen to need the library and test it, let me know if it still works and I should have a look at it.

About PRO/FREE it all depends on how the column is built, if it will be a "heavy" column that will probably require some maintenance regularly and/or takes some time to build, we should do it in PRO.

I really think it is an usefull usecase, like seeing an uploaded pdf to check if everything is fine and signed, without downloading the document to my computer. 👍 👍 

I will be moving this to 5.2 project as I don't think this is something we will be able to do this week 🙃 

Thanks again for sharing knowledge @ziming 

Cheers 🥂

**Comment by pxpm** [comment]
That one I know, I use it in some projects. 👍 It's a great tool.

**Comment by ziming** [comment]
Hey I saw this so I guess I can't proceed? Unless it means it is fine to be in backpack core but not pro

https://github.com/webodf/ViewerJS/commit/8aa33a9c4f390c8da5a4fb8178a2e915d511fde1

```markdown
ViewerJS is a Free Software project. All code is available under the AGPL.

If you are interested in using ViewerJS in your commercial product (and do not want to disclose your sources / obey AGPL), contact [license@viewerjs.org](mailto:license@viewerjs.org) for a commercial license.
```
