### ISSUE TITLE
[Bug] ReorderOperation - after dropping the item, all items expand

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4469]
# Bug report

### What I did

Reported by Andrej Elsukov on email.

When you move an item on top of a collapsed set of item, it expands (that's ok). But after you drop it, ALL items expand:

![CleanShot 2022-06-28 at 10 43 40](https://user-images.githubusercontent.com/1032474/176122995-015487f2-c1f9-4e95-b4c1-5cbc2881ab85.gif)

### What I expected to happen

Just the affected collection of items should expand.

### What I've already tried to fix it

Code from Andrej:

May be, this is not a bug, but that's the way it should be.
My fix: 
Do replace method "_clearEmpty" in 'public/packages/nestedSortable/jquery.mjs.nestedSortable2.js' 
to 

```
_clearEmpty: function (item) {
function replaceClass(elem, search, replace, swap) {
if (swap) {
search = [replace, replace = search][0];
}

$(elem).removeClass(search).addClass(replace);
}

var o = this.options,
childrenList = $(item).children(o.listType),
hasChildren = childrenList.has('li').length;

var doNotClear =
o.doNotClear ||
hasChildren ||
o.protectRoot && $(item)[0] === this.element[0];

if (o.isTree) {
replaceClass(item, o.branchClass, o.leafClass, doNotClear);
}

if (!doNotClear) {
childrenList.parent().removeClass(o.expandedClass);
childrenList.remove();
}
},
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

YES

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

LATEST, including our online demo.

**Comment by promatik** [comment]
Moving to https://github.com/Laravel-Backpack/CRUD/pull/4547 👌
