### ISSUE TITLE
[Bug] Incorrect CoreUI CDN link provided in config/backpack/base.php

### ISSUE THREAD

**Issue by viperet** [Laravel-Backpack/CRUD#4475]
# Bug report

### What I did

`config/backpack/base.php` contains instructions on how to switch from `packages/backpack/base/js/bundle.js` to a separate files loaded from CDN, and provides commented CDN links. You are supposed to comment `bundle.js` line and uncomment CDN lines and have the same result. But its not the same.

### What I expected to happen

I expected to have everything working as before after switching to CDN.

### What happened

After commenting out `bundle.js` line and switching to CDN, sidebar menu is broken, it didn't collapse when you click the "hamburger button".

### What I've already tried to fix it

It appears that provided CoreUI CDN link (`https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js`) now points to the most recent version, v4.1.6, but `bundle.js` includes older CoreUI v2.1.16.

If I replace CoreUI CDN link with correct version link - `https://unpkg.com/@coreui/coreui@2.1.16/dist/js/coreui.min.js` it works as expected.

### Is it a bug in the latest version of Backpack?

I'm using the latest version.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 23 2022 07:15:05) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.14.1@2ca86f96118635a79ee3389013ccab110ae14bea

### BACKPACK VERSION:
5.0.19@a71715d51a0bd2827d535deb407761ee9252d044
```

**Comment by tabacitu** [comment]
I assume your PR fixes this, correct @viperet ? If not, please let me know and we'll reopen.

Thanks again. Cheers!
