### ISSUE TITLE
[Bug] Can't add subfields callbacks after the page is loaded.

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4478]
# Bug report

### What I did

Tried to add a subfield callback after some action in page (after it loads et all)

### What I expected to happen

The callback to be registered and ready to work.

### What happened

The callback is registered but not available until the container is updated. See https://github.com/Laravel-Backpack/CRUD/pull/4455#pullrequestreview-1019968360

**Comment by promatik** [comment]
@pxpm finally pushed the PR for this 🙌

- https://github.com/Laravel-Backpack/CRUD/pull/4598 — **(CRUD)**
- https://github.com/Laravel-Backpack/PRO/pull/80 — **(PRO)**
