### ISSUE TITLE
[Bug] mb_strwidth(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/CRUD#4492]
# Bug report

### What I did

Open a backpack view

### What I expected to happen

See the rows.

### What happened

    "message": "mb_strwidth(): Passing null to parameter #1 ($string) of type string is deprecated (View: /home/polfo/www/lrvl/vendor/backpack/crud/src/resources/views/crud/columns/text.blade.php)",
    "exception": "Facade\\Ignition\\Exceptions\\ViewException",
    "file": "/home/polfo/www/lrvl/vendor/laravel/framework/src/Illuminate/Support/Str.php",
    "line": 363,
    "trace": [
        {
            "function": "handleError",
            "class": "Barryvdh\\Debugbar\\LaravelDebugbar",
            "type": "->"
        },
        {
            "file": "/home/polfo/www/lrvl/vendor/laravel/framework/src/Illuminate/Support/Str.php",
            "line": 363,
            "function": "mb_strwidth"
        },
        {
            "file": "/home/polfo/www/lrvl/vendor/backpack/crud/src/resources/views/crud/columns/text.blade.php",
            "line": 11,
            "function": "limit",
            "class": "Illuminate\\Support\\Str",
            "type": "::"
        },

### What I've already tried to fix it

In `vendor/backpack/crud/src/resources/views/crud/columns/text.blade.php:10` replace 

    $column['text'] = $column['prefix'].Str::limit($value , $column['limit'], '[...]').$column['suffix'];

by

    $column['text'] = $column['prefix'].Str::limit($value ?? '' , $column['limit'], '[...]').$column['suffix'];

solves the issue

### Is it a bug in the latest version of Backpack?

yes

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 25 2022 08:12:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v8.83.18@db8188e9cc8359a5c6706fa9d9f55aad7f235077

### BACKPACK VERSION:
4.1.69@248e2e034cedcffe01732cdce01fb3d1ecad9ffa

**Comment by Polfo** [comment]
That is indeed not an issue for backpack 5, but I am using backpack 4.
https://github.com/Laravel-Backpack/CRUD/blob/4.1/src/resources/views/crud/columns/text.blade.php

**Comment by promatik** [comment]
Moving this to https://github.com/Laravel-Backpack/CRUD/pull/4493 👌
