### ISSUE TITLE
[Bug] Only one column is shown, reload required to see all columns.

### ISSUE THREAD

**Issue by codereader21** [Laravel-Backpack/CRUD#4494]
# Bug report

### What I did

Backpack installed according to the documentation. Created some simple crud tags.

### What I expected to happen

That I immediately see all columns when I open a crud in the administrator panel.

### What happened

When I open a crud I see only one column. I have to reload the page every time to see all the columns.
<img width="1548" alt="Screenshot 2022-07-04 at 13 32 37" src="https://user-images.githubusercontent.com/13853027/177147086-ce02314c-bf92-47e5-9281-88b75e59ae6e.png">
<img width="1561" alt="Screenshot 2022-07-04 at 13 33 34" src="https://user-images.githubusercontent.com/13853027/177147099-fb1830c8-124c-49f6-baa3-17ae31dec652.png">
<img width="769" alt="Screenshot 2022-07-04 at 13 34 23" src="https://user-images.githubusercontent.com/13853027/177147725-6e463f1b-e88f-4452-bf8c-b65652c106c3.png">

### What I've already tried to fix it

Browser cache cleared, different user account, new crud created.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/13853027/177147167-0f176e38-30a0-48e9-bff6-00be9c0c258e.png">

**Comment by pxpm** [comment]
Hello @codereader21 I hope you already figured out by now what's happening as I don't see nothing wrong in your example neither I've experienced something similar myself.

I am going to close this, I think it's better if you open a stackoverflow post with your experience and any code/server setup etc that you can provide for someone to help you. The ideal is that you provide a github repository that someone could clone to replicate your issue. 

Please feel free to continue this discussion if you think I am wrong here, I've been alot of times, we re-open if need. 

Thanks and sorry I can't help more here.

Cheers
