### ISSUE TITLE
[Bug] Unselect checkbox when apply filters

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#4496]
# Bug report
When i want to apply a bulk operation and selecting some entries, if then i apply some filter, the previous selected items are still selected.
### What I did
In list view i have a bulk operation. I select 3 entries

![image](https://user-images.githubusercontent.com/8792209/177331835-3a526926-2e35-40a3-9bee-801ca257b836.png)

Then i realised that i have to apply some filter that those 3 items previously selected where not a result from appling that filter. I select 3 other entries:
![image](https://user-images.githubusercontent.com/8792209/177332392-6d362ef0-29ed-40b6-8fbf-5aa6912ba62f.png)

Finally i execute the bulk operation. In the alert appears that 6 entires where selected. The first 3 previous of being applied filter and the later. 

![image](https://user-images.githubusercontent.com/8792209/177332920-ad4305e9-1e1a-4138-aa0b-62cdda108ce1.png)

I think that when applying some filters, the selected entries should be cleared.

**Comment by pxpm** [comment]
Hello @aberaldo 

Sorry it took me so much time to get here, it seems this issue missed any project board and I missed it too 😞 

Your report is amazing, it was very easy for me to replicate the issue. Thanks for that 🙏 

I've submitted https://github.com/Laravel-Backpack/CRUD/pull/4556 that should fix this.

If you test the PR let me know there if it's working for you.

Thanks again, cheers!

**Comment by tabacitu** [comment]
Thanks @aberaldo  & @pxpm . Let's move the conversation to #4556 please 🙏
