### ISSUE TITLE
Relationship select not working

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#4498]
# Bug report

### What I did
Create a select2 dropdown to manage a one to many relationship

### What I expected to happen
To get a working dropdown

### What happened
The dropdown don't recognize de foreign key. The relationship is working, but the dropdown doesn't show the correct value, is showing "-"

I have two models: Employee and EmployeePosition. The Employee belongs to one EmployeePosition and an employeePosition hasmany employees

My relation in Employee is:
``` 
public function position(){
        return $this->belongsTo(EmployeePosition::class);
    }
```
And the relation in EmployeePosition is:

```
public function employees()
    {
        return $this->hasMany(Employee::class);
    }
```
if I do 
```
$pos = EmployeePosition::find(14);
        dd($pos->employees); 
```
I get all the employees which has the EmployeePosition with the ID 14
```
$emp = Employee::find(1);
        dd($emp->employeePosition);
```
I get the position for the employee with ID 1, so the relationship is working in both ways.

In the Employeecrudcontroller I have this
```
$position = [  // Select2
            'label'     => "Position",
            'type'      => 'select',
            'name'      => 'employee_position_id', // the db column for the foreign key
            // optional
            'entity'    => 'position', // the method that defines the relationship in your Model
            'model'     => "App\Models\EmployeePosition", // foreign key model
            'attribute' => 'name', // foreign key attribute that is shown to user
            //'default'   => 2, // set the default value of the select2
            // also optiona
            ///// force the related options to be a custom query, instead of all(); you can use this to filter the results show in the select
        ];
        $this->crud->addField($position)
```
The dropdown show correctly all the Employee positions list. But is not showing the right value. It's showing always "-"

### What I've already tried to fix it
tried between select and select 2 and test if the relationship is working.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? YES

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.18@db8188e9cc8359a5c6706fa9d9f55aad7f235077

### BACKPACK VERSION:
5.1.4@4539c787a2e052d2e2e2c00188c38432dc2a7ea9

**Comment by pxpm** [comment]
Hello @miquelangeld I guess there migth be some issue/confusion on your relations.

You say you get the position with:
```php
$emp = Employee::find(1);
        dd($emp->employeePosition); //returns position 1 as you said.
```

and your field uses entity `position` and not `employeePosition` why ? Shouldn't that be the relation ? 

You get the expected result with `$emp->position()->get()` ?

I think this kind of questions are better asked on StackOverflow or something similar, I tested a BelongsTo in a `select` field and it's working properly so I am going to close this as I don't think there is any bug in Backpack in this regard.

Please re-open if you think I am wrong. 

Cheers

**Comment by tabacitu** [comment]
@pxpm on that note - let's consider adding more error-throwing to the `relationship` field. It's a complex one, people can use it in a myriad of ways. The more we can help the dev know what went wrong, the faster it'll be for them to set it up. For example, to prevent the above we could throw an error if the relationship doesn't exist... correct? In 5.2+, let's consider adding these kind of hints for the dev 🙏

**Comment by miquelangeld** [comment]
> ```
> employeePosition
> ```

Sorry, that's because I changed the name of the relationship function while I was writing the issue here. I'm using employeeposition 

´´´
$position = [  // Select2
            'label'     => "Position",
            'type'      => 'select',
            'name'      => 'employee_position_id', // the db column for the foreign key
            // optional
            'entity'    => 'employeePosition', // the method that defines the relationship in your Model
            'model'     => "App\Models\EmployeePosition", // foreign key model
            'attribute' => 'name', // foreign key attribute that is shown to user
            //'default'   => 2, // set the default value of the select2
            // also optiona
            ///// force the related options to be a custom query, instead of all(); you can use this to filter the results show in the select
        ];
´´´

**Comment by pxpm** [comment]
Hello @miquelangeld 

That field is defined in EmployeeCrudController where you have `setModel(EmployeeModel::class)` ?

Can you `dd($this->crud->fields());` at the end of `setupCreateOperation` ? 

Cheers

**Comment by miquelangeld** [comment]
Hi @pxpm Now it's working. I had permissions issue, I detected yesterday that when I tried to do php artisan optimize I get an error, then I fixed  the permissions problems and deleted all the caches, etc. Someone in our team  made changes to the permissions when we had already started development

Very sorry guys!
