### ISSUE TITLE
Is setFromDB method will be kept in the future? 

### ISSUE THREAD

**Issue by welcoMattic** [Laravel-Backpack/crud#45]
I've some issues with `setFromDB` method, specially on edit views with relations fields.
I'm ok to try to fix them, but I want to know if the `setFromDB` method will be kept in the future, or if you want to delete it, in benefit to manually `addField` methods

**Comment by tabacitu** [comment]
Hi Mathieu,

I say the ```setFromDB``` method is here to stay. Sure, we're writing a lot of things manually now, but in the future, I can easily see setFromDB becoming a powerhouse, with smart defaults, figuring out the Model after the foreign key and appropriately setting the column and field types, etc. In time, I see two big uses for this method:
- for simple CRUD panels, ```setFromDB``` should be all you need;
- for complex CRUD panels, you could change the way you approach CRUD panels: have everything set automatically by ```setFromDB```, then just change a few columns/fields it got wrong;

I think that's feasible, on the long term. So yeah, if you can fix some of the issues, please do!

Cheers!

**Comment by welcoMattic** [comment]
Ref. #46
