### ISSUE TITLE
[BUG] Date_range start_name value always falls back to default

### ISSUE THREAD

**Issue by dobromir-hristov** [Laravel-Backpack/CRUD#450]
I tried using the `date_range` field but my `start_name` field always defaulted back to the `start_default`. 
I went to the template and dumped out the `$field['value']` as it was set to be used in the start value and I got nothing. Using the same method as the End value though, I got results, dont know if its me only, but here is what I did:
```php
if ( isset($entry) && ($entry->{$field['start_name']} instanceof \Carbon\Carbon || $entry->{$field['start_name']} instanceof \Jenssegers\Date\Date) ) {
    $start_name = $entry->{$field['start_name']}->format( 'Y-m-d H:i:s' );
} else {
    $start_name = null;
}
```
instead of the old seting of $field['value'], and then 
```php
    <input class="datepicker-range-start" type="hidden" name="{{ $field['start_name'] }}" value="{{ old($field['start_name']) ? old($field['start_name']) : (isset($start_name) ? $start_name : (isset($field['start_default']) ? $field['start_default'] : '' )) }}">
```
I can make a PR if it would help.

**Comment by sanchezpablo** [comment]
I had to do the same in order to make date_rage field type work, I use spanish locale (dd/mm/yyyy) format.

**Comment by lloy0076** [comment]
@dobromir-hristov - if you can make a PR that would be very helpful :)

**Comment by bouffekai** [comment]
Same issue ! Anyone found a solution ?

**Comment by sanchezpablo** [comment]
Do as dobromir-hristov said, I follow the steps described, in order to bypass the problem. Maybe you can wait to be merged the pull request of the issue #720

**Comment by bouffekai** [comment]
Great ! But can I override the field to keep these changes in production ? (vendor/ directory is in my gitignore) Thanks

**Comment by dobromir-hristov** [comment]
@bouffekai If you add that file to `/resources/views/vendor/backpack/crud/fields/date_range.blade.php` you  can overwrite.

**Comment by tabacitu** [comment]
Fixed by @dobromir-hristov 's PR - https://github.com/Laravel-Backpack/CRUD/pull/720.

Cheers!
