### ISSUE TITLE
[Bug] Can't cache config file because of `strippedRequest` closure

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4503]
Reported by @timbertens on Gitter, about Backpack 5.x:

![](https://cdn.discordapp.com/attachments/945282719246589993/994523091080319026/unknown.png)

And that's true, if you define a closure inside `strippedRequest` and try to run `php artisan cache:config` you'll get:

![CleanShot 2022-07-07 at 13 06 47](https://user-images.githubusercontent.com/1032474/177748810-26510596-053f-4436-8d86-a6cd32292570.png)

**Comment by tabacitu** [comment]
Until we find a way around this, devs can still:

A) **Define their custom `strippedRequest` inside each FormRequest**, using:
```php
    public function prepareForValidation()
    {
        \CRUD::setOperationSetting('strippedRequest', function ($request) {
            dd('got here');
            return $request->except('_token', '_method', '_http_referrer', '_current_tab', '_save_action');
        });
    }
```
Of course, devs can reuse this bit of logic, if they:
- (I) create an `AdminRequest` with the above, then extend that in all FormRequests;
- (II) create a trait with the above, then use that on all FormRequests;

B) **Define their custom `strippedRequest` inside each CrudController**`:
```php
        // for example in setup()
        $this->crud->operation(['create', 'update'], function () {
            \CRUD::setOperationSetting('strippedRequest', function ($request) {
                dd('got here');
                return $request->except('_token', '_method', '_http_referrer', '_current_tab', '_save_action');
            });
      });
```
Of course, devs can reuse this bit of logic, if they:
- (I) create an `AdminController` with the above, then extend that in all CrudControllers;
- (II) create a trait with the above in a method, then use that on all CrudControllers (and call it in `setup()`);

---

So we still have ways for devs to define a `strippedRequest` for all their CRUDs. And have their configs cacheable. BUT:
- [ ] the above is not as easy to do (it's not "_change in one place, that's it_")
- [ ] the above is not documented, at the moment
- [ ] the `create.php` and `update.php` config files now contain a bit of code (and instructions) that... don't actually work; I mean they work, but then caching the config won't work;

Hmm... let's see... what can we do about the above...

**Comment by tabacitu** [comment]
I think I've just figured out a good way to fix the above... can you guys please take a look at https://github.com/Laravel-Backpack/CRUD/pull/4505 ? Thanks!

I'm going to close this for now, so that we move the conversation in the PR.

**Comment by pxpm** [comment]
@tabacitu I think the best solution is to use ServiceProvider
```php
public function boot()
    {
        $crud = app('crud');
        $crud->operation(['create', 'update'], function () use ($crud) {
            $crud->setOperationSetting('strippedRequest', function ($request) {
                dd('got here');
                return $request->except('_token', '_method', '_http_referrer', '_current_tab', '_save_action');
            });
        });
    }
```

**Comment by tabacitu** [comment]
Damn! That's option number 3, yes 😅 See my PR too, please. That might be the best one.
