### ISSUE TITLE
select is not working in relationship

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#4510]
# Bug report

### What I did
Create a select2 dropdown to manage a one to many relationship (Reopened, I had a mistake in the previous one)

### What I expected to happen
To get a working dropdown

### What happened
The dropdown don't recognize de foreign key. The relationship is working, but the dropdown doesn't show the correct value, is showing "-"

I have two models: Employee and EmployeePosition. The Employee belongs to one EmployeePosition and an employeePosition hasmany employees

My relation in Employee is:
``` 
public function employeePosition(){
        return $this->belongsTo(EmployeePosition::class);
    }
```
And the relation in EmployeePosition is:

```
public function employees()
    {
        return $this->hasMany(Employee::class);
    }
```
if I do 
```
$pos = EmployeePosition::find(14);
        dd($pos->employees); 
```
I get all the employees which has the EmployeePosition with the ID 14
```
$emp = Employee::find(1);
        dd($emp->employeePosition);
```
I get the position for the employee with ID 1, so the relationship is working in both ways.

In the Employeecrudcontroller I have this
```
$position = [  // Select2
            'label'     => "Position",
            'type'      => 'select',
            'name'      => 'employee_position_id', // the db column for the foreign key
            // optional
            'entity'    => 'position', // the method that defines the relationship in your Model
            'model'     => "App\Models\EmployeePosition", // foreign key model
            'attribute' => 'name', // foreign key attribute that is shown to user
            //'default'   => 2, // set the default value of the select2
            // also optiona
            ///// force the related options to be a custom query, instead of all(); you can use this to filter the results show in the select
        ];
        $this->crud->addField($position)
```
The dropdown show correctly all the Employee positions list. But is not showing the right value. It's showing always "-"

### What I've already tried to fix it
tried between select and select 2 and test if the relationship is working.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? YES

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.18@db8188e9cc8359a5c6706fa9d9f55aad7f235077

### BACKPACK VERSION:
5.1.4@4539c787a2e052d2e2e2c00188c38432dc2a7ea9

**Comment by Pickeringwareltd** [comment]
Duplicate of what?

**Comment by pxpm** [comment]
Hey @Pickeringwareltd 
Duplicate of https://github.com/Laravel-Backpack/CRUD/issues/4498
Cheers
