### ISSUE TITLE
[Bug] Column visibility select disappears together with Export buttons

### ISSUE THREAD

**Issue by engel-m** [Laravel-Backpack/CRUD#4511]
# Bug report

### What I did

I want to disable export buttons for certain users without the proper permissions. So I call enableExportButtons() conditionally in my Crud Controller.

### What I expected to happen

For export buttons to not be enabled, but for the Column Visibility Selector to still be visible.

### What happened

Together with Export buttons, the Column Visibility Selector also disappears. This makes no sense logically because they are two different functionalities that can also be required seperately. Column Visibility is required to view Columns that are not visible by default. (Otherwise the list view table would get too messy) 

In my opinion, Column Visibility Select should be always enabled by default when there are Columns that start invisible.

### What I've already tried to fix it

Looked for a way to enable Column Visibility Selector seperately in Backpack's code but could not find it.

**Comment by pxpm** [comment]
@engel-m the only way to do it it's to always `enableExportButtons` but then hide the `export` button with css or remove it from page with JS. 

I don't think we can do much more here, sorry. 

I will be closing this, but feel free to re-open or keep the discussion if you don't agree with me or have any problems implementing the solution I gave you. 

Cheers
