### ISSUE TITLE
[Bug] deleted event not fired from a relationship field

### ISSUE THREAD

**Issue by lmout82** [Laravel-Backpack/CRUD#4517]
# Bug report

### What I did
I declared an image subfield inside a relationship field in a BoatCrudController:
 
        $this->crud->addField([
            'name' => 'boat_photos',
            'type' => "relationship",
            'subfields' => [
                [
                    'name' => 'image',
                    'type' => 'image'
                ]
            ],
            'tab' => 'Photos',
        ]);`

Inside my Boat model:

`
    public function boat_photos()
    {
        return $this->hasMany(BoatPhoto::class);
    }`

### What I expected to happen

The data is inserted/updated/deleted in the corresponding boat_photos table. That works fine.
The deleted event (BoatPhoto) is not fired when an image  is deleted inside a relationship field. I need it to delete the image file.

### What I've already tried to fix it

Despite all my attempts to listen to the deleted event (Observer, register a deleted model event in BoatPhoto and in addField), it seems that the event is not fired at all (unlike the created event).  

### Is it a bug in the latest version of Backpack?

Yes.

### Backpack, Laravel, PHP, DB version

PHP 8.0.20 (cli) (built: Jun 25 2022 08:11:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.20, Copyright (c), by Zend Technologies

#### LARAVEL VERSION:
v9.17.0@091e287678ac723c591509ca6374e4ded4a99b1c

#### BACKPACK VERSION:
5.1.1@71a5dca1a269a59913fa49e1989044164dd404a1
`
`

**Comment by lmout82** [comment]
Hello @pxpm 

Thank you for your quick response.
I wanted to say: `removing the entire row clicking on X on the left `.

**Comment by lmout82** [comment]
Ok, I think the problem is related to this ticket: https://github.com/laravel/framework/issues/2536#issuecomment-74557441

In handleManyRelationItemRemoval(), if I replace `$removedEntries->delete()` with `foreach ($removedEntries->get() as $removedEntry) $removedEntry->delete();`, the deleted event is fired.

**Comment by lmout82** [comment]
Hello everybody,
Could you give me your opinion about this issue ?
The freelance contract with my client ends next week and I would like to see this bug fixed by then.

**Comment by pxpm** [comment]
Hello @lmout82 

I've just confirmed that the events were not triggered because we were deleting on the database and not with model. 

I've submited https://github.com/Laravel-Backpack/CRUD/pull/4543 to address this. 

Can you test and confirm it works on your side too ? 

Cheers and sorry for the delay.

**Comment by lmout82** [comment]
Hello @pxpm 

Thanks a lot. It works great. :)
I think the same change should be applied in createManyEntries(), inside `if (! empty($relatedItemsSent)) `.

**Comment by pxpm** [comment]
You are right @lmout82 just updated the PR. 🥂 

Thanks again 🙏

**Comment by lmout82** [comment]
It's a [Ding Dong](https://media.giphy.com/media/uNIc7jWorhw7GsfKrh/giphy.gif) from me !
Thank you so much, my client will be happy. :)
