### ISSUE TITLE
[bug] translatable field in a relationship field display raw JSON

### ISSUE THREAD

**Issue by lmout82** [Laravel-Backpack/CRUD#4525]
# Bug report

### What I did

Config:
* In Laravel app config file : locale = fallback_locale = "en".
* In Backpack crud config file: locales are "en" and "fr".
* Spatie translatable with the default configuration (see https://spatie.be/docs/laravel-translatable/v6/basic-usage/handling-missing-translations).

A form contains a relationship field with a translatable text field in it.  

### What I expected to happen

1. Current locale is French: if I create a new record in French, let’s say “_Bonjour_”, then:
- the text will be “_Bonjour_” for an update operation in French (OK)
- the text will be `{“fr”:”Bonjour”}` for an update operation in English **(KO)**

2. Current locale is English: if I create a new record in English, let’s say “_Hello_”, then:
- the text will be “_Hello_” for an update operation in English (OK)
- the text will be “_Hello_” for an update operation in French (?)

For 1, I expected to see an empty field for an update operation in English.

3. If the translatable text field is not contained inside a relationship field, then `{“fr”:”Bonjour”}` is replaced by an empty string. Other cases are identical.   

### What happened

For 2: for both cases, `Spatie\Translatable\HasTranslations::normalizeLocale()` returns “en” as Laravel `app.fallback_locale` is en (OK).

For 3: `Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations::getTranslation()` return an empty string as the translation does not exist (`normalizeLocale()` returns "en") → OK.

For 1: it is more complicated. In `Backpack\CRUD\app\Library\CrudPanel\Traits\Update::getModelAttributeValueFromRelationship()`, for a HasMany relationship, the value of the given attribute results from an array merge between `Eloquent getAttributes()` and `getSubfieldsValues()`.
For the translatable field, `Eloquent getAttributes()` return the raw JSON value of the field (`{“fr”:”Bonjour”}`). But when a translation is missing, `getSubfieldsValues()` does not return the translatable field at all because of this condition `if ($relatedModel→{$name})`. So after the merge, it will remain only the raw JSON which will be displayed. 

### What I've already tried to fix it

Nothing so far.

### Is it a bug in the latest version of Backpack?

Yes

#### PHP VERSION:
PHP 8.0.20 (cli) (built: Jun 25 2022 08:11:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.20, Copyright (c), by Zend Technologies

#### LARAVEL VERSION:
v9.20.0@c99868f1c9bf2f5d250993121838db905591864f

#### BACKPACK VERSION:
5.1.4@4539c787a2e052d2e2e2c00188c38432dc2a7ea9

**Comment by lmout82** [comment]
Hello everybody,
Could you give me your opinion about this issue ?
The freelance contract with my client ends next week and I would like to see this bug fixed by then.

**Comment by lmout82** [comment]
> ### What happened
> For 1: it is more complicated. In `Backpack\CRUD\app\Library\CrudPanel\Traits\Update::getModelAttributeValueFromRelationship()`, for a HasMany relationship, the value of the given attribute results from an array merge between `Eloquent getAttributes()` and `getSubfieldsValues()`. For the translatable field, `Eloquent getAttributes()` return the raw JSON value of the field (`{“fr”:”Bonjour”}`). But when a translation is missing, `getSubfieldsValues()` does not return the translatable field at all because of this condition `if ($relatedModel→{$name})`. So after the merge, it will remain only the raw JSON which will be displayed.

A quick (and maybe dirty) fix would be to modify the _if_ condition :
```
if ($relatedModel->{$name} !== null) {
(...)
}
```
Or even delete it ?

**Comment by pxpm** [comment]
Hey @lmout82 I was working on this issue and I think this will be fixed by https://github.com/Laravel-Backpack/CRUD/pull/4267

I totally agree with you that opening a FR page to see text in english is ... not ok! 

I am going to give it a try and update that PR since it was created quite sometime ago and some stuff already changed. 

I will get back here later today when I have news and maybe ask you if you would like to test the PR in your scenario (but don't do it right now because the PR needs to be updated). 

Cheers

**Comment by pxpm** [comment]
Hello @lmout82 here I am again. ✋ 

I've fixed the conflicts in the PR, merged master and did some small fixes. 

Would you like to give it a try ? You can use that branch doing: `composer require backpack/crud:"dev-translatable-with-fallbacks as 5.2.99"`

I've tested your scenario and it seems to be working fine. 

Let me know,
Cheers

**Comment by guleswine** [comment]
> For 1, I expected to see an empty field for an update operation in English.
> 
> If the translatable text field is not contained inside a relationship field, then {“fr”:”Bonjour”} is replaced by an empty string. Other cases are identical.

I think this is the same problem I wrote about
https://github.com/Laravel-Backpack/CRUD/issues/4357

**Comment by pxpm** [comment]
Hey @guleswine 👍 

Not exactly the same, but related.

I've updated that PR to have this issue fixed too.

**Comment by lmout82** [comment]
Hi @pxpm , 
I'll take a look tomorrow morning. 
Cheers

**Comment by tabacitu** [comment]
@pxpm does https://github.com/Laravel-Backpack/CRUD/pull/4267 fix this issue? If so, let's please close this and move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/4267

**Comment by lmout82** [comment]
Hello @pxpm,

It seems to work fine. Thanks !

The possibility to load default values is a good addition. However in my case, app.fallback_locale is only relevant for the public website, not the intranet, as the form can be filled in french or english in a first place, depending on the native language of the person completing the form. So I might be a good idea to make the display of the link "Click to load defaults" configurable, or even better, set a way to configure the locale fallback.

Here are the french translations: 
* no_attributes_translated = 'Cette entrée n'est pas traduite.'
* no_attributes_translated_href_text ='Cliquez pour charger les valeurs par défaut.'

**Comment by pxpm** [comment]
Thanks for the review @lmout82 

I will take that into consideration in #4267 

Cheers
