### ISSUE TITLE
Disable table sorting functionality + paging

### ISSUE THREAD

**Issue by gilbertsmink** [Laravel-Backpack/CRUD#454]
I have a nested table with reordering enabled. I got this working fairly nicely. I want to display the nested view in the order that is set. Therefore, I do not want to allow for ordering of the table and paging of the table. How is this done?

**Comment by MarcosBL** [comment]
Quick and dirty: 

- No pages: set the crud "default_page_length" to something high enought: 10000 items
- No ordering: Copy the "list" view from vendor to your app, and remove JS needed

**Comment by tabacitu** [comment]
@MarcosBL 's solution should work just fine :-)

**Comment by nathanh0** [comment]
I know this is closed, but here's some additional info that might help. This might be in a new version of Backpack Crud, but the one I am using didn't have it, so hopefully it helps make it cleaner for  you:

1. When you do "addColumn" in your Controller, you need to add to each column you want to disable sorting the key+value of:       "sortable" => false     (note, if you do not include it, sorting will continue to work, and setting it to   "sortable" => true   is the same as not adding it to the addColumn.

2. Go to this file:  `resources/views/vendor/backpack/crud/list.blade.php`

Look for the following code:

``
                {{-- Table columns --}}
                @foreach ($crud->columns as $column)
                  <th>{{ $column['label'] }}</th>
                @endforeach
``

Make the following code updates:

``
                {{-- Table columns --}}
                @foreach ($crud->columns as $column)
                  <th{!! ! isset($column['sortable']) || $column['sortable'] ? '' : ' data-orderable="false"' !!}>{{ $column['label'] }}</th>
                @endforeach
``

After you do this, any column you set as sortable => false will hide the sort controls nicely, and hopefully it won't mess up anything else.

**Comment by tabacitu** [comment]
Quick update on this @nathanh0 we have implemented a solution for this a while back. As of CRUD 3.3.8 this definitely works. 

It's exactly the same as you suggested, but it's called ```orderable```. So basically the below should work, without modifying ```list.blade.php```:

```php
        $this->crud->addColumn([
            'name'     => 'shortcodes_html',
            'label'    => 'Shortcodes',
            'orderable' => false,
        ]);
```

Hope it helps someone. 
Cheers!
