### ISSUE TITLE
[Bug] Can't display more than 1 property of a given relationship using addColumn of type relationship

### ISSUE THREAD

**Issue by smile2day123** [Laravel-Backpack/CRUD#4551]
# Bug report

### What I did
I tried to add 2 columns with different data from the same relationship model like so:
CRUD::addColumn([
            'name' => 'listings',
            'label' => 'Store SKU',
            'type' => 'relationship',
            'attribute' => 'store_sku'
        ]);
CRUD::addColumn([
            'name' => 'listings',
            'label' => 'ASIN',
            'type' => 'relationship',
            'attribute' => 'url_id'
        ]);

### What I expected to happen

I expected it to display 2 columns with the data requested

### What happened

Only the first column showed up

### PHP VERSION:
PHP 8.1.3 (cli) (built: Feb 21 2022 14:48:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.20@aa5908e83fccb18b135ca31aa0342cf4bd6909a8

### BACKPACK VERSION:
4.1.70@6c335a8959b82c6a830f97d0c609a7584af98f46

**Comment by pxpm** [comment]
Hello @smile2day123 , can you add `key => 'some_key'` into your second colum ? Have a look at: https://backpackforlaravel.com/docs/5.x/crud-columns#multiple-columns-with-the-same-name-1

I think that was the problem, going to close, please re-open if I am wrong.

Cheers

**Comment by smile2day123** [comment]
hello @pxpm 
I didn't notice that in the docs. Thank you for directing me!
