### ISSUE TITLE
[Bug] consoletvs/charts can not be installed

### ISSUE THREAD

**Issue by BernhardK91** [Laravel-Backpack/CRUD#4573]
# Bug report

**This bug is not a bug in Laravel-Backpack. I add this issue here for other developers to get information. If I get information about it, I will update here in the comments.**

### What I did

I am using consoletvs/charts as described in the [documentation](https://backpackforlaravel.com/docs/5.x/base-widgets#chart-pro). Unfortunatly it is unable to install. The repository from GitHub is gone: https://github.com/ConsoleTVs/Charts It looks like it was set to private.

### What I expected to happen

Package should install normally. 

### What happened

New installation or CI/CD reports the following an fails installation:

```
Failed to download consoletvs/charts from dist: The "https://api.github.com/repos/Chartisan/Charts/zipball/fc73038a006ddc2d6b277b9567ee01c6272448b3" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#download-a-repository-archive"}
    Now trying to download from source
```

### What I've already tried to fix it

I have already tried to contact the developer Erik via Twitter.

**Comment by BernhardK91** [comment]
Erik has received a cease and desist notice and had to shut down the entire library to avoid legal actions against him.

We are trying to figure out how we can help here and avoid breaking pipelines and CIs. 

More details here: https://twitter.com/ErikCampobadal/status/1554859306973102087

**Comment by ziming** [comment]
That's unfortunate, I'm glad i made my last important deploy before this happened.

The letter states until 21 August 2022, so I'm kinda surprised it was taken down immediately

Hopefully it can be up again after a package name change I hope

**Comment by tabacitu** [comment]
Damn it! 😔 Thanks for reporting this @BernhardK91 .

Until the situation gets resolved, Backpack should run `composer remove consoletvs/charts && composer require tabacitu/consoletvs-charts-temp:"6.*"` to install our backup fork.

Let's keep this thread open, until it's behind us.

**Comment by BernhardK91** [comment]
@tabacitu Can we temporary add this to the [documentation](https://backpackforlaravel.com/docs/5.x/base-widgets#chart-pro)? Otherwise users could think the documentation is outdated. What do you think?

**Comment by tabacitu** [comment]
Yup - good catch @BernhardK91 . I was hoping it'd get resolved faster, so we don't need to add it to the docs but... looks like we do. Done:
<img width="818" alt="CleanShot 2022-08-08 at 11 47 02@2x" src="https://user-images.githubusercontent.com/1032474/183378310-2920f0b6-af4e-4cc9-b826-19cc3544a864.png">

**Comment by tabacitu** [comment]
Update - it's over! 🎉 Erik has put v6 back up, we can install and use it again. Links:
- repo: https://github.com/ConsoleTVs/Charts
- docs: https://charts.erik.cat/

I just tried it (after purging my composer cache) and it worked. If anybody's still having problems, let me know he'll and I'll reopen. But we should be fine now.

**Comment by realtebo** [comment]
@tabacitu , can you please remove the NOTE, if no more needed ?

**Comment by tabacitu** [comment]
Totally! Done, removed. Thanks Mirko!
