### ISSUE TITLE
[Bug] Translatable models using create method

### ISSUE THREAD

**Issue by lmout82** [Laravel-Backpack/CRUD#4580]
# Bug report

### What I did

According to spatie documentation, it is possible to create translatable entities in this way:
```
translatableItem::create([
   'name' => [
      'en' => 'Hello',
      'fr' => 'Bonjour'
   ],
]);
```

This is really useful for seeding a table for example.

### What I expected to happen

I expected to have this record in the relevant table: `{"en":"Hello","fr":"Bonjour"}`. 
I got `{"en":{"en":"Hello","fr":"Bonjour"}}` instead.

The bug does not occur if I replace `Backpack\CRUD\app\Models\Traits\SpatieTranslatable\HasTranslations` with `Spatie\Translatable\HasTranslations` in translatableItem.

### What happened

I think the problem comes from the overriding of the create method: in the foreach loop, `setTranslation` is always used. This method converts the value to JSON format.

Spatie provides a method to define multiple translations at once: `setTranslations`.

### What I've already tried to fix it

Nothing so far. I get around the bug by directly using `setTranslation` on the model.

More checks should be done on the value to choose between `setTranslation` / `setTranslations`:
- based on the type of the value (string/array)
- and if the value is an array, check that all keys correspond to locales ?

### PHP VERSION:
PHP 8.0.21 (cli) (built: Aug  1 2022 07:40:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.21, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v9.22.1@b3b3dd43b9899f23df6d1d3e5390bd4662947a46

### BACKPACK VERSION:
5.2.2@bea3042dceb2bd2a888f67d3782908bced33938a

**Comment by pxpm** [comment]
Hello @lmout82 

Thanks for the report. It's something we are aware and have already a PR for it, unfortunatelly some more important stuff came up and it got a bit delayed. 

You can follow/test the PR here: https://github.com/Laravel-Backpack/CRUD/pull/4271

If you happen to test it, let us know if it works for you in the PR thread. 

I will be closing this, please re-open if you think that PR does not solve your use-case. 

Cheers

**Comment by lmout82** [comment]
Hello @pxpm,

Thank you for your answer.
I will take a look at the mentioned PR tomorrow.

Cheers
