### ISSUE TITLE
[Bug] Function strftime() is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/CRUD#4583]
# Bug report

### What I did

Open a backpack create form containing datatime field

### What I expected to happen

See a form

### What happened

`Function strftime() is deprecated /vendor/backpack/crud/src/resources/views/crud/fields/datetime.blade.php:12`

### What I've already tried to fix it

In `/vendor/backpack/crud/src/resources/views/crud/fields/datetime.blade.php:12` replacing

    $value = $timestamp ? strftime('%Y-%m-%dT%H:%M:%S', $timestamp) : '';

by

    $value = $timestamp ? date('Y-m-d\TH:i:s', $timestamp) : '';

solves the issue.

### Is it a bug in the latest version of Backpack?

yes (within 4)

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.8 (cli) (built: Jul 11 2022 08:29:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v8.83.23@bdc707f8b9bcad289b24cd182d98ec7480ac4491

### BACKPACK VERSION:
4.1.70@6c335a8959b82c6a830f97d0c609a7584af98f46

**Comment by pxpm** [comment]
Hey @Polfo 

Thanks for the report. 

I've submitted the PR for v5 branch. https://github.com/Laravel-Backpack/CRUD/pull/4585
I see you are using 4.1. @tabacitu we should probably push it to 4.1 too rigth ? 

Let me know,
Cheers

**Comment by tabacitu** [comment]
Yup

**Comment by pxpm** [comment]
Already did. No more usage outside this field type. 

Will create the 4.1 PR too. 

Cheers

**Comment by pxpm** [comment]
Done. https://github.com/Laravel-Backpack/CRUD/pull/4586

Cheers
