### ISSUE TITLE
[Bug] Browser back button re-create deleted Alerts from LocalStorage

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4584]
We have an issue with browser Back button and the way we store the alerts.

- We store the alerts in LocalStorage.
- We display the Alert and then delete it.
- If user clicks on the back button, the browser will re-create the localStorage with the previous initialized state that contains the Alert before we deleted it. 

[screencast-backpack.test-2022.08.04-20_56_44.webm](https://user-images.githubusercontent.com/44643608/182979556-a13705dd-9a47-4d55-8763-ed83db6a1310.webm)

- a possible solution could be moving the Alert storage to the browser `session` instead of using localStorage, preventing the browser from re-creating it when back button is pressed.

**Comment by tabacitu** [comment]
Note - discovered in https://github.com/Laravel-Backpack/CRUD/pull/4558#issuecomment-1205925548

**Comment by pxpm** [comment]
I've tried to reproduce this and wasn't able. At least following the reproduction steps I taken previously the error does not happen. 

Tested on lastest chrome at time 126.
