### ISSUE TITLE
[Feature Request] Add `hint` text to show operation Columns

### ISSUE THREAD

**Issue by anwsonwsymous** [Laravel-Backpack/CRUD#4587]
# Feature Request

### What's the feature you think Backpack should have?

Show `hint` text under column name in show operation.

### Have you already implemented a prototype solution, for your own project?

✔ Pull request: #4588

### Do you see this as a core feature or an add-on?

As a core feature

**Comment by pxpm** [comment]
Hello @anwsonwsymous , thanks for the suggestion and the contribution.

I am going to close this issue, let's move the conversation over to the PR thread. #4588 

Cheers
