### ISSUE TITLE
[Bug] File upload results in "file not found" exception after processing

### ISSUE THREAD

**Issue by tibbsa** [Laravel-Backpack/CRUD#4593]
# Bug report

### What I did

I have a straightforward CRUD controller that accepts a title and a file upload ('upload' field). Using BP 4.1.55, this works fine.  Upgrading to BP 5.3.3, the upload seems to succeed in every meaningful way but then crashes with a 'file not found' error during the execution of the saveActions. The CRUD controller is minimal with only the basic setUp... functions. None of the internal functions have been overloaded. 

### What I expected to happen

A new entry would be created in my table; the file would be updated to the media library; and I would be redirected back to the CRUD table.

### What happened

When creating a new entry and uploading a file, all works as expected: the ``setAttachedFileAttribute()`` function on my model is called, the file is attached (via Spatie MediaLibrary), and at that point, there is no issue.  

However, before the request returns, a call to ``$request->has()`` as a part of the saveActions appears to trigger a check for the existence of the temporary file, and somehow it has disappeared by that point.

Stack trace:
```
Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException: The file "/tmp/phpqiiBJl" does not exist in file /var/www/html/vendor/symfony/http-foundation/File/File.php on line 36

#0 /var/www/html/vendor/symfony/http-foundation/File/UploadedFile.php(70): Symfony\Component\HttpFoundation\File\File->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php(127): Symfony\Component\HttpFoundation\File\UploadedFile->__construct()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(448): Illuminate\Http\UploadedFile::createFromBase()
#3 [internal function]: Illuminate\Http\Request->Illuminate\Http\Concerns\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(441): array_map()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(430): Illuminate\Http\Request->convertUploadedFiles()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(257): Illuminate\Http\Request->allFiles()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Concerns/InteractsWithInput.php(88): Illuminate\Http\Request->all()
#8 /var/www/html/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php(378): Illuminate\Http\Request->has()
#9 /var/www/html/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/SaveActions.php(336): Backpack\CRUD\app\Library\CrudPanel\CrudPanel->Backpack\CRUD\app\Library\CrudPanel\Traits\{closure}()
#10 /var/www/html/vendor/backpack/crud/src/app/Http/Controllers/Operations/CreateOperation.php(91): Backpack\CRUD\app\Library\CrudPanel\CrudPanel->performSaveAction()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Admin\ResourceLibraryItemCrudController->store()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 /var/www/html/vendor/backpack/crud/src/app/Http/Controllers/CrudController.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Backpack\CRUD\app\Http\Controllers\CrudController->Backpack\CRUD\app\Http\Controllers\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#22 /var/www/html/app/Http/Middleware/CheckIfAdmin.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckIfAdmin->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#54 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#56 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#61 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#62 /var/www/html/server.php(21): require_once('/var/www/html/p...')
#63 {main}
```

### What I've already tried to fix it

Reverting to 4.1.55 fixed the problem, but I need to get up to 5 for a Laravel 9 update.

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 7.4.29 (cli) (built: Apr 21 2022 10:16:36) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.29, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.23@bdc707f8b9bcad289b24cd182d98ec7480ac4491

### BACKPACK VERSION:
5.3.3@003d015d6622a78c27542a82e335911679392cdb
```

**Comment by pxpm** [comment]
Hello @tibbsa 

I think the problem migth that you are using MediaLibrary (or the implementation, not the package itself). 

I've just tested this: https://recordit.co/2rHKyDkbHx (not with media library)

It seems to be working fine. 

The mention you see to save actions as nothing to do with the upload, it's on this line:
`return $request->has('_http_referrer') ? $request->get('_http_referrer') : $crud->route;`

Check if you are properly return stuff from your saving function.

Let me know if I missed something.

Cheers

**Comment by tibbsa** [comment]
I have tracked this down to the behaviour of Spatie's addMedia() call, which not only adds the media to the database but also removes the original file from the disk.  This ordinarily should not be a problem -- presumably once Laravel has processed the incoming request and handed it off to the controller, it won't re-run all of the request processing code (`request->all() ... request->allFiles() ... request->convertUploadedFiles() ... UploadedFile::createFromBase` in the stack trace above).  

However, it seems that the call to `request->has()` results in Laravel re-doing this work, which now fails because `addMedia()` has already deleted the file. 

So there is some change in behaviour between backpack/crud 4.x and 5.x that causes this to happen. The only thing I've spotted that seems to be different between 4.x and 5.x is the renaming of http_referrer to _http_referrer.  Is the fact that _http_referrer is not the 'default' name causing the framework to do more processing on the `has()` call than it would otherwise?  Not sure.

I have "solved" this by preventing MediaLibrary from deleting the temporary file, and leaving that to PHP to do at the end of the request, but given that this does not occur with 4.x and does with 5.x, it really seems like some change in behaviour in 5.x is the real culprit.

My revised mutator:

```
    public function setAttachedFileAttribute($file)
    {
        $this->clearMediaCollection(self::MEDIA_COLLECTION);
        if ($file) {
            $this->addMedia($file)
                ->preservingOriginal()
                ->toMediaCollection(self::MEDIA_COLLECTION);
        }
    }
```

**Comment by pxpm** [comment]
Hello @tibbsa I've been spending some time in this issue as the future me have the desire to have core compatibility with Media Library 👍 

I am not sure how it worked before and not now. Sorry 🙃 

I've investigated a bit further to try to better understand the inner-works in this scenario. 
Laravel wraps the `InputBag` (the request inputs) in their custom `Illuminate\Http\Request` instance. It seems a little ineficiente to use `->has()` in a Laravel request instance since it will get all items from the collection, get files, create `FileUpload` wrapers for each of them etc etc. 
The attributes we want don't need any "wrapping" so I think we can get them directly from the `InputBag` instead of using the Laravel request.

I wonder if bypassing the "Laravel request" for the underlaying `Symfony InputBag` would fix your issue but also "improve" our code by avoiding all extra work: `return $request->request->has('_http_referrer') ? $request->request->get('_http_referrer') : $crud->route;`

From what I can see the file is deleted from the disk but not from the request, if you `dd(request())` it will have the uploaded file there, but will be missing from disk. The `performSaveAction` is done after the request has finished the process, so the file is deleted, db entry is updated, and we are going to perform the save action to redirect the user to the desired location.

It's just the way Laravel works, it found the File in request and will try to match it with a `FileUpload` instance, that's why I wonder how it worked before. Maybe spatie didn't deleted the files before ? Or you had configured it to be false in other projects and now it's true ? Dunno .. 

Can you give a try to the solution I proposed ? I think checking directly in the `InputBag` with `$request->request->has()` is the de-facto solution as it will not try to build the files etc like Laravel. 

Let me know,
Pedro

**Comment by tibbsa** [comment]
This is on the same project, no version difference on Spatie/MediaLibrary.  When upgrading/downgrading backpack, the only dependencies that are being changed are crud and generators.  

I can confirm that a downgrade to 4.1.71 works fine.  Upgrade again to 5.3 and the problem recurs.  

However, your idea of using `$request->request->...` does in fact resolve it.  That leaves the mystery as to what else has changed in the handling of the request in 5.x that would introduce a change in how `has()` behaves...

**Comment by pxpm** [comment]
@tibbsa hi there. 

Thanks for your help here. I've talked with @tabacitu about this and we decided to use the InputBag directly to avoid re-constructing the request, I will submitting the PR later today.

Just as a last mind settler, can you `dd(get_class($request))` both in your 4.1 project and in 5.3 project ? 

Thanks again! 🙏 

Cheers

**Comment by pxpm** [comment]
Hey @tibbsa 

We just fixed this internally in Backpack.

A `composer update` should pull the fix for you.

Thank you for your time and patience helping me here 🙏 

Cheers

**Comment by tibbsa** [comment]
Thanks - happy to help!
