### ISSUE TITLE
[Bug] unable to sort a column of a mongodb model primaryKey

### ISSUE THREAD

**Issue by Dalia-Gerguis** [Laravel-Backpack/CRUD#4601]
# Bug report
this part of the search() function in vendor\backpack\crud\src\app\Http\Controllers\Operations\ListOperation.php overwrites any primaryKey orderBy queries sent from the crudcontroller to make a column orderable
because of the different format of $orderBy, $hasOrderByPrimaryKey is always false.
>         $orderBy = $this->crud->query->toBase()->orders; 
>         $table = $this->crud->model->getTable(); 
>         $key = $this->crud->model->getKeyName(); 
>         $hasOrderByPrimaryKey = collect($orderBy)->some(function ($item) use ($key, $table) {
>             return (isset($item['column']) && $item['column'] === $key)
>                 || (isset($item['sql']) && str_contains($item['sql'], "$table.$key"));
>         }); 
>         if (! $hasOrderByPrimaryKey) {
>             $this->crud->orderByWithPrefix($this->crud->model->getKeyName(), 'DESC');
>         }
> 

### What I did
I have added orderable and orderLogic to the column of id ( a primary key for this model ).

### What I expected to happen

to be able to sort desc and asc as the rest of the columns

### What happened

the column is always ordered desc

### What I've already tried to fix it

I have overwrote the search() function within the controller to prevent the default behavior
### Is it a bug in the latest version of Backpack?
yes
After I run ```composer update backpack/crud``` the bug... is it still there?
yes .. same code is existing
### Backpack, Laravel, PHP, DB version
"backpack/crud": "4.1.*",
"laravel/framework": "^8.50",
"jenssegers/mongodb": "^3.8",

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.18@db8188e9cc8359a5c6706fa9d9f55aad7f235077

### BACKPACK VERSION:
4.1.71@03a0ad4a8d7182d6ee9cf9c86d784d171a942484

**Comment by pxpm** [comment]
Hello @Dalia-Gerguis thanks for the report.

We've already did some changes in our code to accomodate other dbms, especially MongoDB, can you provide me the difference in orderBy ? Maybe a query dump with `$this->crud->query->toBase()->toSql()` would help me here.

Cheers

**Comment by Dalia-Gerguis** [comment]
Hello @pxpm .. thank you for replying fast
`$this->crud->query->toBase()->toSql()` is causing an error 
![image](https://user-images.githubusercontent.com/35669500/185084085-c48e209f-54f7-4d85-b27a-afc65a739f0d.png)
but `$this->crud->query->toBase()->orders`  prints `array:1 [
  "id" => -1
]` and I believe this is the difference causing the issue

**Comment by pxpm** [comment]
You need a `dd($this->crud->query->toBase()->toSql())` to don't run the code ahead and just see the outputs.

**Comment by Dalia-Gerguis** [comment]
I did `dd($this->crud->query->toBase()->toSql()) `on crud with no orderBy queries prints `"select * from "collection_name""` but when I try to `dd($this->crud->query->toBase()->toSql())` on a crud with OrderBy query gives that error

I think ` toSql()` is calling a function which check on the orderBy query with the same difference format ( expecting it an array while it's an int ( 1 or -1 ) ): 
![image](https://user-images.githubusercontent.com/35669500/185088054-10d0f6c9-59c1-44d8-85b9-c7f48ae94f98.png)
that's the same issue I am facing in the `search()` function
`        $hasOrderByPrimaryKey = collect($orderBy)->some(function ($item) use ($key, $table) {
            return (isset($item['column']) && $item['column'] === $key)
                || (isset($item['sql']) && str_contains($item['sql'], "$table.$key"));
        });`

**Comment by pxpm** [comment]
Can you show me your `orderLogic/searchLogic` for the column ? Is that what is triggering the error?
From what I see we can't match your primary_key order defined in column, so we will try to `orderByWithPrefix` always rigth ? 

I think there were more people working with mongoDB with Backpack, I am not sure if they ever faced this issue, sorry I am not a MongoDB user myself, but I don't recall the issue here ... maybe they didn't try to use the `orderLogic`? 🤷‍♂️ 

Let's try to figure out .. not sure if there is something we can/should do here, but if we figure the root problem maybe we can try to work some fix or workaround here. 

Could it be because we use the `QueryBuilder` directly and not the `MongoDbModel` ?

**Comment by Dalia-Gerguis** [comment]
the orderLogic is very simple: `'orderLogic' => function ($query, $column, $columnDirection) {
                $query->orderBy('id', $columnDirection);
            }
        ])` this one doesn't trigger any errors but It's not working ( the id column is always sorted desc as the line I have mentioned in search function overwrites any orderBy coming from the controller )

the root problem is the check on the orderBy  format `$hasOrderByPrimaryKey = collect($orderBy)->some(function ($item) use ($key, $table) { return (isset($item['column']) && $item['column'] === $key) || (isset($item['sql']) && str_contains($item['sql'], "$table.$key")); });` as it checks for elements in an array while in the case of mongodb, it's just an integer 1 or -1

**Comment by pxpm** [comment]
Thanks @Dalia-Gerguis it was very helpfull I think I get the full issue now 🙏 

Let me try to come up with something that could solve this and I will get back here with news.

Cheers
