### ISSUE TITLE
Javascript error when focusing on repeatable

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4605]
![image](https://user-images.githubusercontent.com/21857693/185370137-85de0bc2-1bc0-442a-934e-26fcaca0bc96.png)
select2_from_ajax, number, textarea

![image](https://user-images.githubusercontent.com/21857693/185370236-90814d80-901d-48c8-9657-77e5553b81c1.png)
![image](https://user-images.githubusercontent.com/21857693/185370276-30904814-288f-4e8e-b892-29cbfd4c0453.png)

Hello @pxpm ,
here is the field types and error, the error happens after i click the select2_from_ajax in the repeatable

_Originally posted by @HeriDCLXVI in https://github.com/Laravel-Backpack/CRUD/issues/4491#issuecomment-1219303484_

**Comment by jorgetwgroup** [comment]
Hi @pxpm should be fixed by PR https://github.com/Laravel-Backpack/CRUD/pull/4612
