### ISSUE TITLE
[Bug] auto-focus on select2 have strange behavior

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4606]
@jorgetwgroup I am assigning you directly here because I know you are working on this focus part. 

So here it is how you can reproduce:
- Go to products, add a name an try to save.
- It will error because the `price` on the tab `Basic Info` is mandatory ✅ 
- you will be redirected back and automatically changed to the tab where the error happen ✅ 
- since the first field is a `select2` field, it will open automatically (even if it has no errors) ❌ 

I can't even see the error field because the selection covers it.
![image](https://user-images.githubusercontent.com/7188159/185614876-f17585ae-745b-477c-8752-276b42980d95.png)

I think the rule should be:
- If there are errors, focus on the first field you can find with an error.

What do you think @jorgetwgroup ?

**Comment by jorgetwgroup** [comment]
Hi @pxpm @tabacitu should be fixed by PR https://github.com/Laravel-Backpack/CRUD/pull/4612
