### ISSUE TITLE
[PRO] [bug] ajax pivot does not build the route the same as FetchOperation

### ISSUE THREAD

**Issue by skpr-repo** [Laravel-Backpack/CRUD#4617]
# Bug report

### What I did

I inserted two n-n relationship fields into the setupCreateOperation()

```
CRUD::field('accessories')->type('relationship')->ajax(true)->tab('fields');
CRUD::field('relatedCategories')->type('relationship')->ajax(true)->tab('fields');
```
### What happened

When I try to write something inside the second field to filter records, the focus always go to the first field, so I cannot write inside the second field. 

No error is shown into the console log.

This video shows the behaviour: https://www.awesomescreenshot.com/video/10661748?key=98de394213af3037baa7d5af44e9fac2

### Is it a bug in the latest version of Backpack?

yes

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 10 2022 12:22:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.25.1@e8af8c2212e3717757ea7f459a655a2e9e771109

### BACKPACK VERSION:
5.3.4@ca7f97e3c644e35f134596281192dd6628ab449a

### Operating System and Server Setup

I encountered the problem above on my Windows 10 machine, Google Chrome / Edge / Firefox latest and my web server is set up using Homestead. MySql 8. composer update to the latest versions. I have a license for backpack pro and devtools.

**Comment by pxpm** [comment]
Sent the PR to PRO.

Should be merged in tagged in the next days!

Thank you again @skpr-repo 

Cheers
