### ISSUE TITLE
[Bug] wrong attribute name created with chained notation

### ISSUE THREAD

**Issue by esterisk** [Laravel-Backpack/CRUD#4622]
# Bug report

### What I did

CRUD::field('xx')->allowsNull(true)

### What I expected to happen

$field['allows_null'] == true

### What happened

$field['allows_null'] == null // but: $field['allowsNull'] == true

### What I've already tried to fix it

in CrudField.php:

 public function __call($method, $parameters)
    {
        $this->setAttributeValue(Str::snake( $method ), $parameters[0]);
        //$this->setAttributeValue($method, $parameters[0]);

        return $this->save();
    }

### Is it a bug in the latest version of Backpack?

yes

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @esterisk , we are aware of some inconsistencies in this area, the `Str::snake` is a workaround to make some of the methods compatible, but then not all methods need to be snake cased.

We will improve on this regard on next major, it's on the roadmap and we intend to follow it.

For now, the rule shoud be: when you see it writte in `array => synthax`, you need to use the same key as in array: `->allows_null()` would work just fine. 

Not pretty, but it works. 

Snake all attributtes is something we can't do at this moment.

I will be closing this I belive there is already open issues (in the ideas repository) about this subject.

If you think that I am wrong please re-open, i've been wrong alot of times in the past 👍 

Cheers

**Comment by esterisk** [comment]
Thanks for the reply!
