### ISSUE TITLE
[Bug] Syntax error whith Checklist dependency blade

### ISSUE THREAD

**Issue by dauvray** [Laravel-Backpack/CRUD#4626]
# Bug report

### What I did

import checklist dependency field

### What I expected to happen

Display the field

### What happened

Syntax error

### What I've already tried to fix it

Line 114 and 165 : remove extra bracket at the end

**Comment by pxpm** [comment]
Hello @dauvray 

I see now there is an extra parenthesis there, thanks for let us know.

Haven't noticed it before, somehow the field is working fine, how did you raised the error ? 
![image](https://user-images.githubusercontent.com/7188159/187641409-a62b6a64-9210-42da-8c17-e1be028205b0.png)

I've submitting the PR to remove them anyway, thanks for the report. 🙏 

Cheers

**Comment by dauvray** [comment]
This error appears when using vuejs component in custom field.
