### ISSUE TITLE
[Bug] Namespace seems with wrong case

### ISSUE THREAD

**Issue by flamreal** [Laravel-Backpack/CRUD#4630]
# Bug report

### What I did
Just create clear new project by latest version laravel (v9) + backpack(v5) and generate new CRUD

### What I expected to happen
Want to see admin panel for my model items

### What happened
got error 
_Class "Backpack\Crud\ViewNamespaces" not found_

### What I've already tried to fix it
In file 
.../vendor/backpack/crud/src/app/Library/CrudPanel/CrudButton.php
here is string
_use Backpack\Crud\ViewNamespaces;_

Change it to
_use Backpack\CRUD\ViewNamespaces;_

and it helps to reset error

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version
When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.22 (cli) (built: Aug  4 2022 02:36:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.22, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.27.0@27572f45120fd3977d92651a71d8c711a9aaa790

### BACKPACK VERSION:
5.3.7@b1a35e804d752c5ccc724ce552ccf728c44c86ca

**Comment by karandatwani92** [comment]
@tabacitu, facing the same issue. I tried fresh installation as well

**Comment by tabacitu** [comment]
Hmm that's odd. Thanks guys - fixed in #4634 which will be merged and tagged soon. 🙏
