### ISSUE TITLE
[Bug] Wrong handling of localstorage key name when resetting datatable if resetButtons is true but home_link is empty

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4639]
Sorry, I'm not using standard bug report because doesn't fit my analysis needs.

in config\backpack\crud.php 

    'resetButton' => true,

in config\backpack\base,php

    'home_link' => '',

The datatable creates keyname like this

![image](https://user-images.githubusercontent.com/1268699/187956162-cea3d27c-5a65-44fe-bfdd-fb018083d125.png)

But when pressing ... 

![image](https://user-images.githubusercontent.com/1268699/187956222-3e7e31a0-7725-45d3-9f58-2928ce7263da.png)

.. (reset button) .. the file 

vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php

do this 

     localStorage.removeItem('DataTables_crudTable_/{{$crud->getRoute()}}');

But this don't works because 

    ('DataTables_crudTable_/{{$crud->getRoute()}}' 

contains 2 // 

![image](https://user-images.githubusercontent.com/1268699/187956427-7541fd7a-33b6-4426-873f-424005962df8.png)

This not happens if home_link is 'admin'.

We NEVER use resetButtons, so catched this for first time only today

In our controller: 

    CRUD::setRoute(config('backpack.base.route_prefix') . '/canali');

Normally, this creates datatables localstoreage keys like

    DataTables_crudTable_/admin/canali

In this situation, without admin prefix, it creates WELL the new key as

    DataTables_crudTable_/canali

but when it try to remove it try to delete 

    DataTables_crudTable_//canali

**Comment by realtebo** [comment]
Please note that changing pagelength creates the key as 

![image](https://user-images.githubusercontent.com/1268699/187958330-7ffe299c-8498-4776-8705-e8e108d82a6d.png)

**Comment by realtebo** [comment]
I suggest to simply trim initial "/" if present when executing setRoute or to document that route SHOULD NEVER start with a '/'.

**Comment by realtebo** [comment]
CrudPanel.php comments as is

```
* Can be defined in the CrudController with:
     * - $this->crud->setRoute(config('backpack.base.route_prefix').'/article')
```

This is right, because if we use 'admin' in home_link we MUST use / before article.

This is why i simply suggest to trim the initial "/", if present, when calling setRoute.

Also, when generating a new CrudControler, if possibile, check if 'home' is empty, if empty, never add "/" between the class name. For example, in  

vendor/backpack/generators/src/Console/stubs/crud-controller.stub

there is 

    CRUD::setRoute(config('backpack.base.route_prefix') . '/dummy-class');

this should be customized when creating a new crud controller. So if home_link is empty, no "/" is preprended to 'dummy-class'.

**Comment by pxpm** [comment]
Hello @realtebo 

I think there must be some confusion with the names here. `home_link` is for sidebar top link, I think you are talking about `route_prefix`, and that shouldn't be empty I guess ? 

I am just talking about the `setRoute` issue. In that regard I've submitted https://github.com/Laravel-Backpack/CRUD/pull/4643
It should be Non-BC. 

Fixing it there should fix it in every place. 

I am going to close this issue so we keep any conversation regarding this issue in the PR thread. 

Let me know if you give it a try and it works/still not fully working for you.

Cheers, and once again thanks for raising the issue 🙏

**Comment by realtebo** [comment]
Sorry for confusion. Next week we will try updated version

**Comment by realtebo** [comment]
Please, reopen.

The bug is still here

**Comment by pxpm** [comment]
Yes @realtebo this one is in the same situation, merged into master but needs to be tagged. 

We opted for not doing a release this week for other reasons, we will be tagging it atmost by next Monday. 

Sorry for any inconvenience 🙏
