### ISSUE TITLE
Problem with n-n relationship

### ISSUE THREAD

**Issue by lotarbo** [Laravel-Backpack/CRUD#464]
When I use field-type select2_multiple or select_multiple
```
        $this->crud->addField(
            [
                'label' => "Cities",
                'type' => 'select2_multiple',
                'name' => 'cities', 
                'entity' => 'cities', 
                'attribute' => 'name', 
                'model' => "App\Models\City", // foreign key model
                'pivot' => true,
            ],
            'update/create/both'
        );
In model Company
    protected $guarded = ['id',];
//     protected $fillable = [];

    public function cities()
    {
        return $this->belongsToMany('App\Models\City', 'city_company', 'company_id', 'city_id');
    }
```
and i have pivot table city_company
when i save company i have error 
```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cities' in 'field list' (SQL: update `companies` set `updated_at` = 2017-02-16 17:00:49, `cities` = 1 where `id` = 1)```

if i change $guarded to 
`protected $guarded = ['id', 'cities'];`
all work without problem
Bug or not?)

**Comment by njbarrett** [comment]
It looks OK to me. Could you confirm which version of Laravel and BackpackCRUD you are using?

**Comment by lotarbo** [comment]
laravel 5.4.9
crud 3.1.57

**Comment by njbarrett** [comment]
Yeah im not sure, Im using laravel `5.4.12` with crud `3.2.3` and a very similar relationship which is working.
Perhaps upgrading would work for you.

**Comment by lotarbo** [comment]
Yeah) i upgrade laravel and crud and all works fine)
