### ISSUE TITLE
[Bug] Extra spaces in relationship columns export

### ISSUE THREAD

**Issue by raffamasi** [Laravel-Backpack/CRUD#4666]
# Bug report

### What I did

I clicked on the "Export" button (PRO version) for a table containing a relationship column

### What I expected to happen

Since in HTML table, relationship elements are simply comma-separated, I expected they were the same in exported files

### What happened

Exportation added a big amount of white spaces before any commas, so in the resulting files (both PDF and excel) they had a very ugly format

### What I've already tried to fix it

I noticed that in HTML code every comma-separated value in a relationship column is inside a <span class="d-inline-flex></span> , that in HTML is ininfluent but surely causes the problem in exported files, I wasn't able to edit that

### Is it a bug in the latest version of Backpack?
![Prodotti-Agriconf-1-pdf](https://user-images.githubusercontent.com/104200574/190203652-9e43ef3b-e621-42b3-926b-9c4d7da16c32.png)

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes, I downloaded it recently

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

LARAVEL VERSION:
v8.83.23@bdc707f8b9bcad289b24cd182d98ec7480ac4491

BACKPACK VERSION:
5.3.12@883ff76f74bb4cdb70559990026b1130db5234f6

**Comment by pxpm** [comment]
Hello 👋
Thanks for the report.
We have already a PR to address this in review phase. 
It should be merged at least by next Monday release. 
I will be closing this one, since it were already reported.
 If you notice something else please open another issue.

Cheers

**Comment by pedja1982** [comment]
I have the same problem, is this bug fixed

**Comment by pxpm** [comment]
Hey @pedja1982 this was fixed long time ago. https://github.com/Laravel-Backpack/CRUD/pull/4659

If you are using the latest version and still experience the issue, or similar, please open a new issue so that we can take a look at it. 

If you upgraded from v5 to v6, make sure you are not overriding the `datatables.blade.php` file in your resources folder, if you are overwriting it you need to manually apply the fix yourself.

Cheers
