### ISSUE TITLE
[Bug] Crud add Clause Bug in combination with join

### ISSUE THREAD

**Issue by mintUI9976** [Laravel-Backpack/CRUD#4679]
# Bug report

### What I did

`add clause with join in other table`

```php
$this->crud->addClause(
            'join',
            'suppliers',
            function ($query) {
                $query->on('supplier-lists.supplier_id', '=', 'suppliers.id')
                    ->where('suppliers.trade', '=', TradeCalculationEnum::EK);
            }
        );
```
### What I expected to happen

That the table view is referenced to another db table view

### What happened

`
[2022-09-21 17:12:23] local.ERROR: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "supplier" does not exist
LINE 1: ...liers"."id" and "suppliers"."trade" = $1 order by supplier-l...
                                                             ^
HINT:  Perhaps you meant to reference the column "supplier-lists.supplier_id". (SQL: select "supplier-lists".* from "supplier-lists" inner join "suppliers" on "supplier-lists"."supplier_id" = "suppliers"."id" and "suppliers"."trade" = EK order by supplier-lists.id DESC limit 25) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERROR:  column \"supplier\" does not exist
LINE 1: ...liers\".\"id\" and \"suppliers\".\"trade\" = $1 order by supplier-l...
                                                             ^
HINT:  Perhaps you meant to reference the column \"supplier-lists.supplier_id\". (SQL: select \"supplier-lists\".* from \"supplier-lists\" inner join \"suppliers\" on \"supplier-lists\".\"supplier_id\" = \"suppliers\".\"id\" and \"suppliers\".\"trade\" = EK order by supplier-lists.id DESC limit 25) at /var/www/html/OutlayReckoning/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
`

In the php code stored above, I am trying to access the reference 'suppliers.id' within a join, but as you can see in the stored Laravel log, the function is trying to access an unstored db column called 'supplier' and therefore throws an error. Can anyone tell me if this is a bug or a problem in my code. I can hardly find any content on stackoverflow.

### What I've already tried to fix it

I had already tried string escaping, possibly thought this was an escape problem. primary key in model is also set.

### PHP VERSION:
PHP 7.4.3 (cli) (built: Mar  2 2022 15:36:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v7.30.6@ecdafad1dda3c790af186a6d18479ea4757ef9ee

### BACKPACK VERSION:
4.1.65@e7ab6b798262d847647238f91f88992b457927d9

**Comment by pxpm** [comment]
Hello @mintUI9976 
Thanks for the report ... I am just wondering what you want to achieve ? 

You can reference "related columns" by using `dot.notation` in your Column definition. Just make sure that your relation is eager loaded with `->with()` (alias for join), or join, does not matter. `$this->crud->query->with('supplier')`

But that will load the relationship in the query, if you use any column like `smt_id` from the joined table backpack would not know and try to get it from the "curren model table, not the joined one".
If you have a `supplier` relation, you can probably get that value with `supplier.supplier_id` (this will access the suplier relation that you eager loaded and get the `supplier_id` field.) 

Am I missing something here ? 

Cheers

**Comment by mintUI9976** [comment]
Thanks for answering my bug request, but I think I figured out the underscore is removed `"supplier_id"` once the query sends it to the database.

**Comment by mintUI9976** [comment]
Okay i found an other solution, thanks for helping me.

Cheers
