### ISSUE TITLE
[Feature Request] / [Bug] Make translatable Upload multiple field

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4682]
# Feature Request

### What's the feature you think Backpack should have?

When we have upload multiple field, it write an hardcoded string. 

See: https://github.com/Laravel-Backpack/CRUD/blob/main/src/resources/views/crud/fields/upload_multiple.blade.php#L165 

Where at today we have

    inputLabel.html("Files selected. After save, they will show up above.");

We need to be able to translate it into italian.

### Have you already implemented a prototype solution, for your own project?

Actually no. We could copy/paste and change the field but would avoid to do if fixed soon

### Do you see this as a core feature or an add-on?

Core

**Comment by pxpm** [comment]
Too late! 🙃  https://github.com/Laravel-Backpack/CRUD/pull/4681

Cheers 🥳
