### ISSUE TITLE
'Save' button translation broken in 'edit' pages

### ISSUE THREAD

**Issue by sebnyc** [Laravel-Backpack/CRUD#469]
With backpack/crud v3.2.3 it looks like the labels of the 'save' button in the 'edit' pages are not correctly translated.

The button reads 'backpack::crud.save_action_save_and_back' instead of 'Save and back' in English.

<img width="538" alt="screen shot 2017-02-16 at 4 19 03 pm" src="https://cloud.githubusercontent.com/assets/19838972/23041690/bc2a3b48-f463-11e6-8c4f-2d9a60de3d94.png">

**Comment by OwenMelbz** [comment]
Have you got up to date published language files?

**Comment by sebnyc** [comment]
My bad, I hadn't seen these old files had been copied in my resource directory.
Thank you !

**Comment by ihsanberahim** [comment]
i face this issue too. How to fix it?

**Comment by sebnyc** [comment]
You need to re-publish the lang files, they have been updated.

See [https://laravel-backpack.readme.io/docs/install-on-laravel-54]
Item 3.3:
`php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="lang" #publish CRUD lang files`

**Comment by ihsanberahim** [comment]
I done that but still not works.

```
bash-3.2$ php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider"
Copied Directory [/vendor/backpack/crud/src/resources/lang] To [/resources/lang/vendor/backpack]
Copied Directory [/vendor/backpack/crud/src/resources/views] To [/resources/views/vendor/backpack/crud]
Copied Directory [/vendor/backpack/crud/src/config] To [/config]
Copied Directory [/vendor/backpack/crud/src/public] To [/public/vendor/backpack]
Copied Directory [/vendor/backpack/crud/src/resources/views-elfinder] To [/resources/views/vendor/elfinder]
Publishing complete.
```

May something on my installed packages.
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.4.*",
        "backpack/base": "^0.7.0",
        "backpack/crud": "^3.1.0",
        "backpack/backupmanager": "^1.1",
        "backpack/logmanager": "^2.3",
        "backpack/settings": "^2.0",
        "backpack/pagemanager": "^1.1",
        "backpack/MenuCRUD": "^1.0",
        "backpack/newscrud": "^2.1",
        "backpack/permissionmanager": "^2.1",
        "darkaonline/l5-swagger": "~4.0",
        "laravel/lumen": "^5.4",
        "tymon/jwt-auth": "1.0.*@dev",
        "backpack/langfilemanager": "^1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "laracasts/generators": "dev-master as 1.1.4",
        "backpack/generators": "^1.1"
    },
```

**Comment by ihsanberahim** [comment]
After i do `grep -r 'save_action_save_and_back' vendor/backpack/crud/src/resources/lang/`
I found something wrong to my installed package. 

So, i just reinstall and publish again. and it works.
TQ @sebnyc
