### ISSUE TITLE
[Bug] Database field type JSON (casted as array) tries to use PRO TABLE component as default field

### ISSUE THREAD

**Issue by skpr-repo** [Laravel-Backpack/CRUD#4694]
# Bug report

### What I did

I created the mysql table with a json field.
Then I created the model and run backpack:build

### What happened

The controller has been created with default CRUD::fields, but when I go to the insert view I get this error:

**Cannot find the field view: table. Please check for typos. If you are trying to use a PRO field, please first purchase and install the backpack/pro addon from backpackforlaravel.com**

### What I've already tried to fix it

Removing the json crud::field works, so I'm quite sure the problem is the json field.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes, I just installed the latest version.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 10 2022 12:22:48) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.33.0@13665b7e15dbcbecb3651acc19ba8818da6fa0a9

### BACKPACK VERSION:
5.3.13@114b7d53b0569e6499375511ab39013a957e1903

thanks

**Comment by pxpm** [comment]
Hey @skpr-repo thanks for the report. 🙏 

I've submitted https://github.com/Laravel-Backpack/CRUD/pull/4713 to address this issue.

Cheers
