### ISSUE TITLE
Bulk checkbox pollutes first column in exported files 

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4698]
Moved @SennenHyorou 's report from https://github.com/Laravel-Backpack/CRUD/pull/4659#issuecomment-1267851806 because it looks like a bug we need to fix. Here's some copy-pasta:

---

 Hi @promatik , i just checked this fix today and seems like affected my current project, there is an issue now.

My project is using CRUD with $this->crud->enableBulkActions() feature for some mass operation,
When exporting via excel, my first column value become true/false instead of showing the text of the first column.

My project:
![image](https://user-images.githubusercontent.com/49132787/193973144-8cb5b255-a030-47d6-91e6-db0db8bd9608.png)

The one we've been using for years and the result was like this:
![image](https://user-images.githubusercontent.com/49132787/193973312-32f56fef-d3f6-45fe-9f75-bf79ed902d98.png)

But after the latest update, its become like this.
![image](https://user-images.githubusercontent.com/49132787/193973228-4335be84-cc40-4010-8653-50ff09d4f20a.png)

The first column supposed to be class of, but the value is become value of checkbox.

Is there any solution for my case? As my temporary solution is added another row number column as first column, but its not best solution i think because we need to remove the first column manually on excel.

This is my backpack version on my current project.
### PHP VERSION:
PHP 8.1.8 (cli) (built: Jul 11 2022 08:30:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.33.0@13665b7e15dbcbecb3651acc19ba8818da6fa0a9

### BACKPACK VERSION:
5.3.13@114b7d53b0569e6499375511ab39013a957e1903

_Originally posted by @SennenHyorou in https://github.com/Laravel-Backpack/CRUD/issues/4659#issuecomment-1267851806_

**Comment by promatik** [comment]
I've just pushed a fix for this one https://github.com/Laravel-Backpack/CRUD/pull/4701 🙌

@SennenHyorou sorry for the introduced issue, my bad ☝️
This fix will probably be merged in the next version, let's move the conversation there #4701.
