### ISSUE TITLE
Localize the filters navbar view

### ISSUE THREAD

**Issue by jsvini** [Laravel-Backpack/CRUD#470]
The filters navbar view have fixed english text, it should use the current app lang:

![image](https://cloud.githubusercontent.com/assets/4185886/23079899/f3e3d4c2-f535-11e6-8e6e-a3b4b13b4f70.png)

https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/inc/filters_navbar.blade.php#L11

**Comment by OwenMelbz** [comment]
Would you like to submit a PR to help out?

**Comment by tabacitu** [comment]
Thanks a lot for the PR. I'll close this issue, as the PR clearly fixes it. Cheers!
