### ISSUE TITLE
Order a computational column 

### ISSUE THREAD

**Issue by dimaAlj** [Laravel-Backpack/CRUD#4703]
# Bug report
We have a column of the type "closure" that shows a result returned by a function within the model and we want to order this column like this:
```
 [
                'name'     => 'recited_lecture_count',
                'label'    => trans('site.recited_lecture_count'),
                'orderable'  => true,
                'type'     => 'closure',
                'function' => function ($entry) use ($dates, $studentStatus) {
                    return $entry->totalRecitationCount($dates, $studentStatus);
                }
            ]
 ```
But it doesn't work

**Comment by tabacitu** [comment]
Hey @dimaAlj - for columns that SQL itself can't order, you can define your own `orderLogic`. Take a look here for more details - https://backpackforlaravel.com/docs/5.x/crud-columns#custom-order-logic-for-columns

Hope it helps!
