### ISSUE TITLE
[Bug] Backpack 5 failed to install through composer

### ISSUE THREAD

**Issue by faruoqi** [Laravel-Backpack/CRUD#4707]
# Bug report

### What I did
i have installed laravel 9 with sail development. starting sail. and then i opened sail shell.
then i require composer :
`composer require backpack/crud`

after that , got error from instalation : 
`In Filesystem.php line 314:`
`  Could not delete /var/www/html/vendor/composer/1c7fa9cd/Laravel-Backpack-CRUD-114b7d5/src/public/packages:`

### What I expected to happen

backpack composer package install successfully

### What happened
`Install of backpack/crud failed`

### What I've already tried to fix it
i tried to login to sail with root-shell command, to make sure composer has right to delete the files.

### Is it a bug in the latest version of Backpack?
i'ts latest version of backpack

After I run ```composer update backpack/crud``` the bug... is it still there?  backpack is not installed yet

### Backpack, Laravel, PHP, DB version
Backpack 5.3.13,laravel 9 with mysql inside sail development

When I run ```php artisan backpack:version``` the output is:    ` ERROR  There are no commands defined in the "backpack" namespace.`

**Comment by pxpm** [comment]
@faruoqi thanks for the report. 
Are you using the sail binary to send the commands ? `./vendor/bin/sail composer required backpack/crud` ? 

What if you try to install any other package, does it work ? 

I've just installed a new backpack sail app this morning, and no issues:

![image](https://user-images.githubusercontent.com/7188159/195107427-4fecd5af-acd7-44fe-a901-de22d77cda46.png)

Let me know how it goes.

Cheers

**Comment by faruoqi** [comment]
i guess maybe because i logged in to the sail bash with `sail shell` command , the error happened. i tried to install it through the sail binary and it works fine.
thank you!
