### ISSUE TITLE
[Display issue] Horizontal scrollbar appear when select2 open

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4710]
Like the title says, first I noticed that when the select2 opens the html slide up and down.
https://drive.google.com/uc?id=1xK2iPDXVHDc_6jhdPAjefL7ImwSQM77A

After I realized it was the horizontal scrollbar on the bottom that was appearing and disappearing.
https://drive.google.com/uc?id=1CuxKrZIrWYyDb8jTt8bv8fEA8YiLcRzM

I haven't investigated further, maybe it was the result of the last PR with the "glow" and focus that broke it ? @jorgetwgroup can you have a look please ? 

Cheers

**Comment by tabacitu** [comment]
Yup, I’m pretty sure that’s the one that introduced it. I remember noticing it then but forgot/ommited to say anything about it 👀😔

It’s a small thing, but it annoys me too.

**Comment by jorgetwgroup** [comment]
Hi @pxpm 

This is the code who create scrollbar

vendor/backpack/crud/src/resources/views/crud/inc/show_tabbed_fields.blade.php

`/*  
            when select2 is multiple and it's not on the first displayed tab the placeholder would
            not display correctly because the element was not "visible" on the page (hidden by tab)
            thus getting `0px` width. This makes sure that the placeholder element is always 100% width
            by preventing the select2 inline style (0px) from applying using !important
        */
        .select2-container, 
        .select2-container li:only-child,
        .select2-container input:placeholder-shown {
            width: 100% !important;
        }`

It was created by you around 8 months ago, please let me know if this is needed or we can delete.

Thanks

**Comment by pxpm** [comment]
Hello @jorgetwgroup .
It is required to be there due to the reasons explained in the comment. 
I think we need to find another way of doing what we want to do there, but without the side-effects that we are having now. 

Cheers

**Comment by tabacitu** [comment]
Good catch with the scrollbar @pxpm ... I would never have noticed that, on MacOS the scrollbar never shows anyway.

I don't think it's what @jorgetwgroup said - when I removed that bit of CSS and we've still got the 1px jump. But you guys please test this again too.

I really _really_ want this fixed. I wanted to launch `morphTo` today and... I can't... 😅 I know it's a small thing, but it really fucks up our whole presentation... we can't really brag about this new feature we created, and show a bug in the previews 😅 right? 

PS. This might have also been introduced when Mauro added the "autofocus on first field". Or... it might have been there for ever, we just never fixed it. That's an option too, you know 😅

**Comment by tabacitu** [comment]
Fixed in #4719 . I mean... the scrollbar still appears... but the 1px bump no longer exists.

**Comment by tabacitu** [comment]
@jorgetwgroup makes a good point. We still have to fix the scrollbar here.

**Comment by jorgetwgroup** [comment]
Fixed now in https://github.com/Laravel-Backpack/CRUD/pull/4724
