### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, ...

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#4716]
I did composer update right away upon seeing enum support but now I get

```sql
SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'users.id'; this is incompatible with sql_mode=only_full_group_by

SELECT
  `id`,
  COUNT(*) AS total_rows
FROM
  (
    SELECT
      `id`
    FROM
      `users`
    WHERE
      `users`.`deleted_at` IS NULL
  ) AS `users`
```

Only thing i did is composer update, have not change my code to use the new enum field or column yet.

**Comment by pxpm** [comment]
Fixed @ziming https://github.com/Laravel-Backpack/CRUD/pull/4717
sorry, I missed that option is on now by default.

**Comment by jainerry** [comment]
same here. i have the same issue:

SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'appointments.id'; this is incompatible with sql_mode=only_full_group_by
SELECT `id`, count(*) AS total_rows FROM (SELECT `id` FROM `appointments`) AS `appointments`

**Comment by pxpm** [comment]
@lieto-dk need to do nothing, this is a mistake on my side. This will be fixed in a few moments, we are going to release the fix. 

Sorry for the bad experience 🙏 

Cheers

**Comment by lieto-dk** [comment]
Hi,

Thanks for the quick feedback.
Please let me know when you release the fix so I can do a composer update.

/jens

**Comment by pxpm** [comment]
Thanks guys, this had been merged is going to be tagged in a few moments. 

Cheers and sorry for the bad experience once more 🙏
