### ISSUE TITLE
[Bug] multi-level nested where queries in crud models break the view

### ISSUE THREAD

**Issue by olipayne** [Laravel-Backpack/CRUD#4722]
# Bug report

### What I did
I have a complex crud view which has multiple ->where() eloquent statements as part of the base view. This is broken due to an incorrectly used `?:` which is setting `$whereColumns` to a boolean, which then throws an error when trying to `array_merge`.

PR incoming with a longhand fix.

### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 29 2022 19:44:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.36.1@584f7bbde1bc24c69c84afe44f16b4ec294f92ef

### BACKPACK VERSION:
5.4.2@da63612d0c9a674c79bd50f31d76ae9ada7eaac8

**Comment by tabacitu** [comment]
Thank you @olipayne 🙏 Let's close it in favor of #4723
