### ISSUE TITLE
[Bug] Some relationship fields don't properly detect the identifiableAttribute

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4726]
# Bug report

### What I did

Went to our demo, in Monsters > Create > Relationship: https://demo.backpackforlaravel.com/admin/monster/create#relationship 

Tried to use the HasOne > Country subfield.

### What I expected to happen

Properly show countries by their name, like it did before.

### What happened

Country names are blank in the select2 dropdown:

<img width="411" alt="CleanShot 2022-10-19 at 12 57 52@2x" src="https://user-images.githubusercontent.com/1032474/196660176-2521c184-b8f5-4f9c-899f-dc01d10410e9.png">

### What I've already tried to fix it

Nothing. But my intuition says that https://github.com/Laravel-Backpack/CRUD/pull/4621 might have broken it ... One of those few PRs I didn't test and just merged with "_I trust you guys_" 😅 Bad @jorgetwgroup & @pxpm ... bad! 😅

**Comment by jorgetwgroup** [comment]
I check this, if you set

`'name' => 'country.name',` everything work again, @pxpm is this needed by this change or something is not working on new implementation.

Cheers.

**Comment by tabacitu** [comment]
Fixed  by https://github.com/Laravel-Backpack/CRUD/pull/4728 - which looks to fix this in my tests. But Jorge, please free to look into it and understand WHY and challenge it if it isn't a good solution.
