### ISSUE TITLE
[Bug] disabling ConvertEmptyStringsToNull has side effects on listing pagination

### ISSUE THREAD

**Issue by basselhossam** [Laravel-Backpack/CRUD#4727]
# Bug report

### What I did

after updating to the latest version of backpack the pagination stopped working

### What I expected to happen

everything to work as usual

### What happened

now there is no pagination and the total number of records is always 0

### What I've already tried to fix it

after some investigation I found that the problem occurred because of this PR https://github.com/Laravel-Backpack/CRUD/pull/4502/files and I made a comment on the issue, it's related to `totalEntryCount` the field is sent as false (empty string) and I've disabled `ConvertEmptyStringsToNull` middleware so the value is still an empty string not null which causes the issue I've commented on the PR on this line

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.0 (cli) (built: Nov 23 2021 21:48:28) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.25@b77b908a9426efa41d6286a2ef4c3adbf5398ca1

### BACKPACK VERSION:
5.4.3@f1c257e10b8228e48916a7b99b325224e7415910

**Comment by pxpm** [comment]
I will be closing this since the PR will get merged soon.

Thanks again @basselhossam 🙏
