### ISSUE TITLE
[Bug]  Checklist old value is null

### ISSUE THREAD

**Issue by johncarlosacrosalazar** [Laravel-Backpack/CRUD#4744]
# Bug report

I created a checklist value and successfully save, I can see array value in database. but on update page the value is null and the old value is not showing. 
Database Value :'["1","3","5"]'

Update page checklist field  value:
array:13 [▼ // vendor\backpack\crud\src\resources\views\crud/fields/checklist.blade.php
  "label" => "Roof"
  "type" => "checklist"
  "name" => "roof"
  "entity" => "roofs"
  "attribute" => "name"
  "model" => "App\Models\StructuralRoofs"
  "pivot" => false
  "multiple" => true
  "tab" => "Structural Characteristic"
  "relation_type" => "BelongsTo"
  "value" => null
  "number_of_columns" => 3
  "options" => array:7 [▼
    1 => "Tiles"
    2 => "G.I Sheets"
    3 => "Aluminum"
    4 => "Asbestos"
    5 => "Long Span"
    6 => "Concrete Desk"
    7 => "Nipa/Anahaw/Cogon"
  ]
]

**Comment by johncarlosacrosalazar** [comment]
I casted it as array and this error shows
![image](https://user-images.githubusercontent.com/112707841/198240377-16819828-a725-4ede-bca1-4ab410e592c1.png)

**Comment by pxpm** [comment]
@johncarlosacrosalazar checklist is not done to work with a `BelongsTo` relation but with a `multiple` relation (eg: HasMany) or an array column. 
Checklist allows you to select `multiple` elements, while `belongsTo` relation only allow one element to be selected. 

Please use the select field for the `belongsTo` relation, or store the things you want in an json/text column while casting to array. 

I am going to close this, I don't think there is any bug here, just some wrong implementation. 

Please re-open if you think I am wrong. 

Cheers
