### ISSUE TITLE
[Minor Bug] first column before a "bigger" column doesn't get center aligned

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4746]
# Bug report

### What I did

Added a column that makes the row expand, imagine the new table column, or an textarea with some `br`:

![image](https://user-images.githubusercontent.com/7188159/198270644-08bdbde5-35d3-4b36-a254-4553d1e15319.png)

![image](https://user-images.githubusercontent.com/7188159/198267814-c8a7e2e4-0c71-408d-9eca-c0aa4b6f73c2.png)

The first column is never center aligned.

**Comment by tabacitu** [comment]
Confirmed:
<img width="1234" alt="CleanShot 2022-10-27 at 14 21 22@2x" src="https://user-images.githubusercontent.com/1032474/198271373-129ab2c4-6b45-4bf0-a185-95aa9bed1ebf.png">

Though... I'm not 100% sure we should align the first on to the middle... or the rest to the top...

**Comment by pxpm** [comment]
@tabacitu I am not sure either, but I would go with `middle`. 

I am going to assign @promatik here since I asked him to have a look at other issue we are having with non-responsive tables. 
(This one happens with responsive and non-responsive). 

Cheers

**Comment by promatik** [comment]
Finally fixed with https://github.com/Laravel-Backpack/CRUD/pull/4780 🙌
