### ISSUE TITLE
[Maybe Bug?] Not able to add field with relationship name as snake_case

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4747]
# Bug report

### What I did

I tried doing:

```php
        CRUD::field('rewarded_user')->type('relationship')->ajax(true); // notice it's snake_case
```

While in my model having:

```php
    public function rewardedUser()  // notice it's camelCase
    {
        return $this->belongsTo(\App\User::class, 'rewarded_user_id');
    }
```

### What I expected to happen

Field show up.

### What happened

Undefined array key "relation_type"

![CleanShot 2022-10-28 at 12 15 14](https://user-images.githubusercontent.com/1032474/198551549-18b4d3d4-28b5-48eb-88fc-fd04e2c0fb68.png)

### What I've already tried to fix it

Nothing yet. @pxpm didn't this work at some point? Did we remove support for snake_case relationships? Or did we never actually have it?

**Comment by pxpm** [comment]
Why would you try to do that @tabacitu ?

Your relation is called `someThing`, why would you use `some_thing` ? You don't call `$this->crud->setup_list_operation` right ? 

I think we already do alot of manbo-jamboo to infer relations, I don't think this use-case should ever be supported. 

I am sorry to bear the bad news! 🙃

**Comment by tabacitu** [comment]
I thought Laravel itself supports this. I mean:
```
TRUE $model->rewardedUser => relationship
TRUE $model->rewardedUser() => query builder
FALSE $model->rewarded_user => relationship
```

But no it doesn't. So we don't have to support that either. PHIEW!
