### ISSUE TITLE
Adding a ChartController route fails if custom route file was reformatted

### ISSUE THREAD

**Issue by mattsches** [Laravel-Backpack/CRUD#4748]
# Bug report

### What I did

I tried to create a new chart widget with `php artisan backpack:chart ChartWidget`

### What I expected to happen

I expected a new ChartController to be created (this was created successfully), and a new route to be added to `routes/backpack/custom.php` (this failed).

### What happened

```
Adding route to routes/backpack/custom.php .......................................................................... RUNNING
   ErrorException 

  Undefined array key ""

  at vendor/backpack/crud/src/app/Console/Commands/AddCustomRouteContent.php:72
     68▕             return;
     69▕         }
     70▕ 
     71▕         $end_line_number = $this->customRoutesFileEndLine($file_lines);
  ➜  72▕         $file_lines[$end_line_number + 1] = $file_lines[$end_line_number];
     73▕         $file_lines[$end_line_number] = '    '.$code;
     74▕         $new_file_content = implode(PHP_EOL, $file_lines);
     75▕ 
     76▕         if (! $disk->put($path, $new_file_content)) {

      +25 vendor frames 
  26  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### What I've already tried to fix it

The issue seems to be in `\Backpack\CRUD\app\Console\Commands\AddCustomRouteContent::customRoutesFileEndLine`:

`$end_line_number = array_search('}); // this should be the absolute last line of this file', $file_lines);` does not find a line because I (my IDE) reformatted the custom routes file `routes/backpack/custom.php`, resulting in a last line like this:

`); // this should be the absolute last line of this file`

This is probably what was reported in https://github.com/Laravel-Backpack/CRUD/issues/3569

Maybe it should be made clearer that the last line should not be indented/reformatted, or the check should also handle cases like mine. Not a top prio issue IMHO, but still …

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 29 2022 22:17:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
v9.37.0@0c9675abf6d966e834b2ebeca3319f524e07a330

### BACKPACK VERSION:
5.4.6@39876b312b1ef3d6faebba89a0220a6bed7f870c
```

**Comment by pxpm** [comment]
@mattsches thanks for the report. 🙏 

We are aware of that issue and we are going to fix it https://github.com/Laravel-Backpack/CRUD/pull/3567

Unfortunatelly we cannot do it without a BC 😞 

Going to close this since there is already the open PR to fix this. 

Once again, thanks 🙏
