### ISSUE TITLE
Error with beforeColumn and afterColumn methods.

### ISSUE THREAD

**Issue by gmedeiros** [Laravel-Backpack/CRUD#475]
**(A) what you did**

I wanted to add a column at the beginning of the table, so n my CustomCrudController I added a column like this:

`$this->crud->addColumn(['label' => "label", 'type' => "text", 'name' => 'name'])->beforeColumn('firstColumn');`

**(B) what you expected to happen**
I expected the Column "Name" to be shown at the beginning of the tabel, just before the "firstColumn" column.

**(C) what happened**
```
ErrorException in Columns.php line 92:
array_splice() expects parameter 2 to be long, string given
```

**(D) what have you already tried to fix it?**
I already submited a PR: https://github.com/Laravel-Backpack/CRUD/pull/472
Changed the beforeColumn and afterColumn methods on /CRUD/src/PanelTraits/Columns.php:

```
    /**
     * Moves the recently added column to 'before' the $target_col.
     *
     * @param $target_col
     */
    public function beforeColumn($target_col)
    {
        foreach ($this->columns as $column => $value) {
            if ($value['name'] == $target_col) {
                **$offset = array_search($column, array_keys($this->columns));**
                array_splice($this->columns, **$offset**, 0, [array_pop($this->columns)]);
                break;
            }
        }
    }

    /**
     * Moves the recently added column to 'after' the $target_col.
     *
     * @param $target
     */
    public function afterColumn($target_col)
    {
        foreach ($this->columns as $column => $value) {
            if ($value['name'] == $target_col) {
                **$offset = array_search($column, array_keys($this->columns));**
                array_splice($this->columns, **$offset + 1**, 0, [array_pop($this->columns)]);
                break;
            }
        }
    }
```

**Comment by zachweix** [comment]
I noticed the same bug just now as well

**Comment by eddilou** [comment]
It's not entirely clear when this problem will be fixed. I also faced the same problem, if I make changes, then update in the composer, then everything will disappear or am I wrong?

**Comment by lloy0076** [comment]
@eddilou - if you make changes in the vendor/backpack/ (wherever it is) file then any composer update / require or install might override them.

**Comment by eddilou** [comment]
ok, how to solve this problem? I understand they decided it if the status is closed, but I do not see any changes or updates and the problem arises

**Comment by lloy0076** [comment]
Override whatever you need to and just replace what functionality is necessary? This can get be messy but it works.

**Comment by eddilou** [comment]
How? It's not entirely clear, there are used treit Columns, which are defined in the CrudPanel and they are also in the vendor

**Comment by lloy0076** [comment]
It's a pain to do, TBH; one need to override the CrudController itself and then modify its constructor to construct your own panel - I've done it.

I think @tabacitu  is working on a way to make this slightly more easy :)

**Comment by eddilou** [comment]
I do not fully understand how to override it, but does the developer plan to fix this error?

**Comment by eddilou** [comment]
@tabacitu When this problem will be solved? In version 3.3.13? Every time I update, I have to make a patch

**Comment by tabacitu** [comment]
Hi @eddilou ,

Seems like the issue was somewhat more complicated - that's why I wasn't able to reproduce it myself. This issue only occurred when ```beforeColumn()``` or ```afterColumn()``` were used after ```setFromDb()```. Otherwise the error did not happen.

Thanks to @dmagur note, I've been able to merge @gmedeiros's PR today and fix the underlining issue: the column area had different keys, depending how it was created.

That being said, the fix is now on the ```dev``` branch and it will be officially available shortly, unless someone reports follow-up bugs. If you want to use it as-is, please use the ```dev``` branch in your project. It would be great if you can confirm it works for you too now.

Cheers!

**Comment by dmagur** [comment]
@tabacitu need to fix addColumn method also. It still add elements to $this->column by integer keys. So this
`$this->crud->addColumn('col1');`
`$this->crud->addColumn('col2')->beforeColumn('col1')`
will not work

**Comment by tabacitu** [comment]
Hi @gmedeiros ,

Yup, done in a different commit and issue. All works now, [take a look](https://cl.ly/3b000t0F3n2w).

Cheers!

**Comment by dmagur** [comment]
@tabacitu, cool, thanks!

**Comment by DaraniShri** [comment]
beforeColumn()
BUT afterColumn() is not working

**Comment by tabacitu** [comment]
@DaraniShri this is a very VERY old thread. If you've discovered a bug in the current version of Backpack, please open a different issue for it (feel free to link to this one too, if relevant). The version we had in 2017 when this issue was opened... is no longer actively maintained.

Thanks!
