### ISSUE TITLE
[Bug] Query builder not properly managing database table prefix

### ISSUE THREAD

**Issue by lzampieri** [Laravel-Backpack/CRUD#4753]
# Bug report

### Conditions

The bug appears when `prefix` is valued in `config/database.php`.

In that situation, trying to access the dashboard interface of a CRUD model, an error is obtained, similar to:
```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'prefix_prefix_tablename.id' in 'field list' (SQL: select count(*) as total_rows from (select `prefix_prefix_tablename`.`id` from `prefix_tablename`) as `prefix_prefix_users_aggregator`)```

Note the double prefix appearing in the column name, which cause the error.

### Fix

The bug seems to be solvable replacing the line 236 in `vendor\backpack\crud\src\app\Library\CrudPanel\Traits\Query.php`; in particular, inside `private function getCountFromQuery(Builder $query)`, one should replace:

```$modelTable = $this->model->getTableWithPrefix();```

with

```$modelTable = $this->model->getTable();```

However, tests should be carried out to confirm that there are no counter-effects.

### Versioning

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.3.33 (cli) (built: Nov 16 2021 14:49:44) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.83.25@b77b908a9426efa41d6286a2ef4c3adbf5398ca1

### BACKPACK VERSION:
5.4.6@39876b312b1ef3d6faebba89a0220a6bed7f870c
```

Thanks for the great work! Have a nice day.

**Comment by pxpm** [comment]
Thanks @lzampieri 

I can confirm the bug! `QueryBuilder` automatically adds the prefix in the table when doing the query we don't need to provide it. 

I've just submitted #4754 that fixes it, should be merged and tagged later today. 

Thanks for the report, and sorry for the bad experience! 🙏 

Closing this in favor of the PR. 

Cheers
