### ISSUE TITLE
Column headers got shifted. Again.

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#4755]
@pxpm It's the same issue this PR fixed previously, more detail is in #4479 

Basically with non-responsive table; when `CRUD::disableResponsiveTable()` has been called.
The header row doesn't match the data and footer rows, so the columns don't line up.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/9887246/195165040-25584a69-2728-4048-bce5-88f47b5a1779.png">

Screenshot is from https://demo.backpackforlaravel.com/admin/fluent-monster

As far as I could tell from testing a bunch of versions I think `5.3.5` is the last release that it worked correctly in, the only thing that jumps out at me is 5.3.6 upgraded npm packages (I had to skip that version because it was a broken release), so maybe there is some competing CSS somewhere, I spent sometime looking at it but I couldn't find what had changed.

Thanks

_Originally posted by @mnightingale in https://github.com/Laravel-Backpack/CRUD/issues/4490#issuecomment-1275078749_

**Comment by tabacitu** [comment]
Bump! 😀👀

**Comment by pxpm** [comment]
@promatik bump ⬆️

**Comment by promatik** [comment]
Finally fixed with https://github.com/Laravel-Backpack/CRUD/pull/4780 🙌
