### ISSUE TITLE
[Feature Request] Align backpack:field to what suggested in the documentation

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#4763]
# Feature Request

### What's the feature you think Backpack should have?

I'd like that file created from

    php artisan backpack:field new_field_name

command will be more near to what documented here 

    https://backpackforlaravel.com/docs/5.x/crud-fields#creating-a-custom-field-type-1 

For example, I think it's a mandatory need to wrap the following code

```
{{-- CUSTOM CSS --}}
@push('crud_fields_styles')
.....
@endpush

{{-- CUSTOM JS --}}
@push('crud_fields_scripts')
...
@endpush
```
 
with 

```
@if ($crud->fieldTypeNotLoaded($field))
    @php
        $crud->markFieldTypeAsLoaded($field);
    @endphp

    <insert the above code here>
@endif 
```

Also, I suggest to document _directly inside the generated code_ where to place, in which folders, the CSS and the JS files, because there is no doc about where they are searched

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core

**Comment by pxpm** [comment]
Hello @realtebo 

We really did some major changes in this regard in the last month. I guess you don't have generators updated yet, if you don't please update them. 

This is the current generated field stub: https://github.com/Laravel-Backpack/Generators/blob/main/src/Console/stubs/field.stub

It includes the `@loadOnce` directives that's what we use now to replace `fieldTypeNotLoaded` plus js init function etc. 👍 

I am going to close this, but I see your suggestion was inline with what we did I think, so win-win 😃 

Let me know if there is something more we should be doing in this regard!

Cheers
