### ISSUE TITLE
Method Backpack\CRUD\app\Library\CrudPanel\CrudPanel::getCleanFields does not exist.

### ISSUE THREAD

**Issue by dandarie** [Laravel-Backpack/CRUD#4765]
I believe it's a typo. There's a getCleanStateFields method in the same trait.

https://github.com/Laravel-Backpack/CRUD/blob/928434673e7751d44c262ef3541edca79c05c5cc/src/app/Library/CrudPanel/Traits/Fields.php#L165

### PHP VERSION:
PHP 8.1.3 (cli) (built: Feb 21 2022 14:48:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v9.38.0@abf198e443e06696af3f356b44de67c0fa516107

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

**Comment by pxpm** [comment]
Closing in favor of the PR. 

Thanks again @dandarie
