### ISSUE TITLE
[Bug] Ordering issue in inlinecreate n-n relationship with fetch ajax

### ISSUE THREAD

**Issue by agile-siddhi** [Laravel-Backpack/CRUD#4774]
Please refer below link :
[Screenshot](https://user-images.githubusercontent.com/118238131/201824701-195d48fe-faa1-4b74-a768-b3f57d838454.png)

Code : 
` $this->crud->addField([
            'type' => 'relationship',
            'importable' => false,
            'name' => 'Marriages',
            'label' => 'Marriage(s)',
            'ajax' => true,
            'method' => 'POST',
            'inline_create' => true,
            'data_source' => backpack_url('/deceased/fetch/marriages'),
            'tab' => 'BDM',
        ]);`

FetchOperation code:
`protected function fetchMarriages()
    {

        $data =  $this->fetch([
            'model' => \App\Models\Marriages::class,
            'query' => function ($model) {
                return $model->select('id','spouse_name')->orderBy('current_status', 'DESC');
            },
        ]);
        return $data;

    }`

My ordering is not working and I am not able to debug fetchMarriages() as the function is not called .

My backpack version : 4.1
laravel version : 8.*
php version :8.1

**Comment by pxpm** [comment]
Hello @agile-siddhi thanks for the report. 
You select only `id` and `spouse_name` and are ordering by `current_status`, that may be one of the problems. 

Also `fetchSomething` should be called, so something must be wrong either in the `data_source` (not pointing to that function). 

If nothing of this works I will need more code/examples from your side to try to figure out what's not working.  

Cheers

**Comment by agile-siddhi** [comment]
Hello @pxpm 

Thanks for the response.

Models:

1) In Deceased Model
`public function Marriages()
    {
        return $this->belongsToMany(Marriages::class, 'deceased_marriage', 'deceased_id', 'marriage_id');
    }`

2)In Marriages Model
`public function deceased()
    {
        return $this->belongsToMany(Deceased::class, 'deceased_marriage', 'marriage_id', 'deceased_id');
    }`

DeceasedCrudController:
![Screenshot from 2022-11-16 17-11-55](https://user-images.githubusercontent.com/118238131/202171682-f3855767-bce0-4891-9d2a-fbbcfeae1a07.png)


Request data in front:

 "Marriages" => array:15 [▼
        "type" => "relationship"
        "importable" => false
        "name" => "Marriages"
        "label" => "Marriage(s)"
        "ajax" => true
        "method" => "POST"
        "inline_create" => true
        "data_source" => "http://127.0.0.1:8002/admin/deceased/fetch/marriages"
        "tab" => "BDM"
        "entity" => "Marriages"
        "relation_type" => "BelongsToMany"
        "model" => "App\Models\Marriages"
        "attribute" => "spouse_name"
        "multiple" => true
        "pivot" => true
      ]

![Screenshot(3)](https://user-images.githubusercontent.com/118238131/202171306-7c8ab6d2-f73a-4294-bfe1-a511d3ccd14f.png)

**Comment by agile-siddhi** [comment]
Hello @pxpm,
Yes fetch function is not called. Actually I am using backpack v4.1 and in that fetch function is protected, even though I've checked with both public and protected but still same issue.
https://backpackforlaravel.com/docs/4.1/crud-operation-fetch.

even not getting anything in network related to fetch func ajax call.
![Screenshot from 2022-11-17 08-49-12](https://user-images.githubusercontent.com/118238131/202348586-f017baea-5acf-4ac9-940b-21e307b11e6f.png)

I think it might be due to version problem as I am using 4.1

**Comment by pxpm** [comment]
Sorry for late reply @agile-siddhi From what I recall fetch was working properly on 4.1. 

Do you have other fetch in other cruds working ? Or you are using it exclusively in this crud ?
