### ISSUE TITLE
[Bug] Display many - many inline create data in table structure instead of dropdown

### ISSUE THREAD

**Issue by agile-siddhi** [Laravel-Backpack/CRUD#4787]
Hello guys,

I am new to backpack.

I want to display more than one  attribute of inline create in table structure in main form instead of drop-down. 

Relationship type -: many - many incline create with ajax.

I want to display  all  attributes which are present in below  image instead of 1st attribute. 
![Screenshot from 2022-11-23 11-23-28](https://user-images.githubusercontent.com/118238131/203480565-824ed240-8d28-4d5b-8a26-b080ae1a379f.png)

only 1 attribute is displayed in dropdown but I need to show all attributes in table format.
![Screenshot from 2022-11-23 11-23-57](https://user-images.githubusercontent.com/118238131/203481069-ff803315-af0b-4197-af9c-f4e8a838bc26.png)

Backpack version : 4.1
PHP V : 8.0
Laravel V : 8

**Comment by pxpm** [comment]
Hello @agile-siddhi you can use the repeatable with the subfields representing the relationship. https://backpackforlaravel.com/docs/5.x/crud-how-to#belongstomany-n-n-relationship 

You can check how the fields look, and how to implement them in our demo: https://demo.backpackforlaravel.com/admin/monster/create#relationship

Closing this as I don't think there is a bug here, but feel free to continue the conversation if needed.

Cheers
