### ISSUE TITLE
ErrorException Undefined array key "subfields"

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/CRUD#4792]
# Bug report

### What I did

Open user crud edit page in admin.

### What I expected to happen

view edit page

### What happened

ErrorException
Undefined array key "subfields"

\src\app\Library\CrudPanel\Traits\Update.php:170

here

```
                if ($field['subfields']) {

                    return [$this->getSubfieldsValues($field['subfields'], $model)];

                }
```

### What I've already tried to fix it

no

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.25@b77b908a9426efa41d6286a2ef4c3adbf5398ca1

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

**Comment by tabacitu** [comment]
Huh that's weird @AlexKomMsk - can you please copy-paste your fields definition? We gotta see what you have in your `subfields` array there - you're probably doing something custom that overlaps with Backpack's features.

**Comment by AlexKomMsk** [comment]
I don't know which field is causing the error. I made in trait:
```
                if (!isset($field['subfields'])) {
                 dd($field);
                }
```
And it showed:
```
  "name" => "status_id"
  "label" => "Status"
  "value" => null
  "default" => "1"
  "type" => "number"
  "values" => []
  "attributes" => []
  "autoset" => true
  "entity" => "status"
  "relation_type" => "HasOne"
  "model" => "App\Models\Status"
  "multiple" => false
  "pivot" => false
```
In the method setupUpdateOperation I specify this
CRUD::setFromDb(); // fields

**Comment by pxpm** [comment]
Hello @AlexKomMsk 

Do you have a `status_id` field in your main model ? If you do, I think you are using the wrong relation, it should be something like:

```php
public function status()
{
    return $this->belongsTo('App\Models\Status', 'status_id');
}
```

I think you probably have `$this->hasOne`, and that's failing because the `HasOne` relations are handled either by using the `dot.notation` (eg: `status.name`) or by using `subfields` to deal with them as a group of inputs. 

Let me know if that's the case. 

Cheers

**Comment by AlexKomMsk** [comment]
Yes, this is my mistake. Thank you.
