### ISSUE TITLE
Class 'Composer\InstalledVersions' not found 

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/CRUD#4793]
# Bug report

### What I did

Deploy project to production

### What happened

Erorr in logs.

Class 'Composer\\InstalledVersions' not found at /vendor/backpack/crud/src/helpers.php:309

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.28 (cli) (built: Feb 17 2022 16:06:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.25@b77b908a9426efa41d6286a2ef4c3adbf5398ca1

### BACKPACK VERSION:
5.4.7@6e1bb116de9f3091530cb9b11edcceb4d252daa8

**Comment by pxpm** [comment]
@AlexKomMsk thanks for the report. 

I just created a new project in PHP 7.4 and L8 (hopefully the last I will be creating in those versions 🤞 ) Everything is working smooth, no errors. 

Are you using composer 2 ? You can run `composer self-update` to get to the latest versions of composer, I think that will fix your issue.
We will be removing the Deprecated Package Versions in a few months, so upgrading to composer 2 is a mandatory step in next versions, as we will also remove support for PHP 7.4 (security updates ended last few days). 

Let me know

**Comment by AlexKomMsk** [comment]
Hello. I updated the composer to the second version, but the error still appears. I see it by chance, on pages that are not related to the admin panel (just opening the pages of the site).

**Comment by AlexKomMsk** [comment]
After deployment, the error disappeared. Apparently, there were some updates or caches. Now there is no error.

**Comment by malikwaqasmustafa** [comment]
updating to composer 2+ version fixed the issue for me.
