### ISSUE TITLE
A little more complex setEntityNameStrings

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#48]
I was thinking maybe we can do a better version of this function to add two options. This feature seems to be necesary when:
- we translate the text in languages that have different terms for "all" depending on the gender of the term.
- we translate the articulated version of a keword that has more than one word.
Though i am not sure that there is another language, besides the romanian one, that needs this kind of features.

**Comment by tabacitu** [comment]
Yup, it's an issue that needs to be solved - in Romanian, at least.
