### ISSUE TITLE
select2_from_ajax mistakenly considers data tο be paginated

### ISSUE THREAD

**Issue by kritsot** [Laravel-Backpack/CRUD#4812]
# Bug report

### What I did

After upgrading to backpack 5, I noticed that select2_from_ajax fields, fetched the same data, multiple times

### What I expected to happen

I expected one ajax call to be made, per click (or search).

### What happened

Multiple ajax calls where made, each time

### What I've already tried to fix it

I found the culprit to be line 160
```
 paginate = data.next_page_url !== null;
```

If response data does not contain a **next_page_url**,  the code above evaluates to true 
(as **data.next_page_url** evaluates to undefined) and mistakenly considers data to be paginated.

This can be fixed with

```
 paginate = (data.next_page_url||null) !== null;
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes it still occurs. This did not happen in version 4

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.6 (cli) (built: May 12 2022 23:30:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.42.2@607d7867c93706eae20e28e46679f8a66e2a23ec

### BACKPACK VERSION:
5.4.10@050b288caf2f60c79313f2b0b7d4fefd25177f3f

**Comment by pxpm** [comment]
Hello @kritsot sorry it took me sometime to get here. 

I've tried to reproduce it the other day but I was not able to, I gave it another try today and still not able. 

So I think I need you help here to reproduce it. 

I've created a `select2_from_ajax` field, and tried returning paginated/non-paginated results. 

```php
public function fetchArticle()
    {
        return $this->fetch([
            'model'    => \App\Models\Article::class,
            'paginate' => false, // removed this to get paginated results
        ]);
    }
```

In paginate mode the field display a loading more, and loads more X entries when I reach the end of the scrollbar:

![image](https://user-images.githubusercontent.com/7188159/207063672-dab0bf19-216a-45dd-9aee-1c9700537889.png)

When I disable pagination, I get the total entries return by the query, as you can see from the size of scrollbar in the options.

![image](https://user-images.githubusercontent.com/7188159/207063351-b1da01e1-0bf4-4bfd-bec2-6dcc458c4201.png)

Please make sure you don't have your `select2_from_ajax` field overriden in your resources folder and is preventing you from getting the updated version from the package. 

Cheers
