### ISSUE TITLE
[Bug] With editable-columns got javascript error: registerMinorEditInputEvents is not defined 

### ISSUE THREAD

**Issue by jrbecart** [Laravel-Backpack/CRUD#4818]
# Bug report

### What I did

**I upgraded from BP 4.1 to BP 4.1 + PRO and editable-columns**

### What I expected to happen

When clicking a text column editable field (on focus), no javascript error should be raised, and after editing the field should ba saved.

### What happened

When entering the field (on focus) I got the following javascript error: 

```Uncaught ReferenceError: registerMinorEditInputEvents is not defined at HTMLInputElement.onfocus (room_area:1:1)```

### What I've already tried to fix it

Checked existing github issues, and monster template code.

### Is it a bug in the latest version of Backpack?

**Yes.**

After I run ```composer update backpack/crud``` the bug... is it still there?
**Yes.**

**backpack/editable-columns: * 2.1.1
backpack/pro:  * 1.4.0
backpack/crud: * 5.4.10**

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 29 2022 18:29:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

### LARAVEL VERSION:
v8.83.26@7411d9fa71c1b0fd73a33e225f14512b74e6c81e

### BACKPACK VERSION:
5.4.10@050b288caf2f60c79313f2b0b7d4fefd25177f3f

Thank you for your support.

**Comment by jrbecart** [comment]
My bad (kind of)
I didn't updated my `backpack::blank` layout. (It was overwritten in resources\views\vendor\backpack\base) 

It's in the doc but not in the Upgrade Guide, see in https://backpackforlaravel.com/docs/5.x/base-widgets#requirements-1

**Comment by JordanchoEftimov** [comment]
@jrbecart Having the same problem here. Can you tell me what exactly did you change/added in order to make it work?

**Comment by JordanchoEftimov** [comment]
I just solved it also, the thing was that i needed to copy the `blank.blade.php` file from the repo into mine overwritten file.
