### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by siberfx** [Laravel-Backpack/CRUD#4835]
# Bug report

### What I did

**I added prefix like ( [#] ) to crud field in chain way ( either way it doesnt reflect) and added validation on that field with validation message
- check images to understand the issue better;**

![image](https://user-images.githubusercontent.com/10257240/207075595-dfbaad3b-8c19-4436-9982-2d8012c438a2.png)

### What I expected to happen

**expected to see on validation error the field as red and at the bottom of the field like hint error message ( usually it is like that for other fields )**

### What happened

![image](https://user-images.githubusercontent.com/10257240/207075720-e18d75b5-8322-46a3-9719-b6486b58df20.png)

**as in the image at the very top of the form it gives the stack of all errors but it doesnt do the hint message and red covered input field**

### What I've already tried to fix it

yet I did not do nothing for the issue, I think anyway its covers a css way of solution too.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
**yes**

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**PHP 8.2.0 (cli) (built: Dec  6 2022 15:25:41) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.43.0@011f2e1d49a11c22519a7899b46ddf3bc5b0f40b

### BACKPACK VERSION:
5.4.11@ffbadcdb6478822646600b2cd763490caa927155**

**Comment by realtebo** [comment]
I add my 2 cents: it's related to digitally happy recent changes.

**Comment by pxpm** [comment]
Hey @siberfx thank you very much for the report. 🙏 

Sorry @realtebo you'r just 2 cent's lighter in you wallet 😄 

Unfortunately it's not related to recent changes on digitally happy repo (please revert those if you are having them), this seems to be here forever and me or anybody else ever noticed it yet. 

What happens is that our "required fields script" rely on jQuery `.parent()` to find the input wrapper to add the red asterisk, when we add `prefix => "smt"` to a field the whole input gets wrapped in a new `input-group`
```html
<div class="input-group">          
    <div class="input-group-prepend"><span class="input-group-text">#</span></div>         
    <input type="text" name="text" value="" class="form-control">
</div>
```

This makes our script unable to find the proper place to add the astherisc and/or make the field red bordered. 

I've submitted the PR https://github.com/Laravel-Backpack/CRUD/pull/4836 to address this. 

I am going to close this, let's move the conversation to the PR thread 👍 

Wish you all the best 🎅
