### ISSUE TITLE
Dependency injection - unable to get access to Auth::user

### ISSUE THREAD

**Issue by eescalante** [Laravel-Backpack/CRUD#484]
Hi,

I want to get access to other crud controller so i use DI in order to get it into my target controller.

```
class EmpresaCrudController extends CrudController
{
    use CrudTrait; 
    use HasRoles; 

    protected $personal;

   public function __construct(PersonaCrudController $personal)
   {
      // parent::__construct();
      $this->personal = $personal
   }
..
```

Everything looks fine until i want to get access to Auth::user(), i receive null as result. I reviewed the code and seems to be something related to ->setup() is not fired if i don't do it explicitly

I found some reported issues related to session and a how it was solved by using setup into the parent constructor. I tried calling parent::__construct() without success too.

If i create explicity the object every works correctly:

```
        $this->personal = new \App\Http\Controllers\Admin\PersonaCrudController();
        $this->personal->setup();
        ...
        ..
```

I would like to use DI but i don't know how :(

**Comment by tabacitu** [comment]
Hi @eescalante ,

Rename your ```__construct()``` to ```setup()```. That will let you access the session. It's a Laravel 5.3+ thing.

Cheers!

**Comment by eescalante** [comment]
Thanks for your quick reply but i need to keep open this issue.

I already have a setup() in my controller because it extends CrudController and i have that requested function there.

I can't just replace original 

`public function setup()`

 by  something like

`public function setup(PersonaCrudController $personal)`

But i need to use DI in my CrudController in order to use other CrudController's info.

I did read your post before in other post about the warning in L 5.3 but i was unable to get it work as expected by following your instructions.

**Comment by tabacitu** [comment]
Huh... I hope I understand your problem correctly. If so, you should be able to include everything that is now in your __construct() into the already existing __setup(), then.

Because setup() is already called in CrudController::__construct() ([see here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/app/Http/Controllers/CrudController.php#L39)), all that code would then be called inside the middleware, so you'd have access to the request.

Does it work that way?

**Comment by eescalante** [comment]
I saw that piece of code, i understand the need of using that middleware but i can't overload setup() to  setup(customCrudController $obj), the parent constructor call an existent setup() function, if i try to call something like setup(customCrudController $obj), i get an error.

Are you saying to just rename `setup(customCrudController $obj)` to `__setup(customCrudController $obj)`?

That doesn't work, that function never is called. I misunderstand something i guess, i can't see how to fix that.
