### ISSUE TITLE
Impossible to create color_picker fields with different configuration

### ISSUE THREAD

**Issue by greatsaltlake** [Laravel-Backpack/CRUD#4844]
# Bug report
color_picker.blade.php uses
```@loadOnce('bpFieldInitColorPickerElement')```

### What I did

CRUD::addField([
            'type'    => 'color_picker',
            'name'    => 'background_colour',
            'default' => 'rgba(0, 0, 0, 0)',
            'color_picker_options' => [
                'useAlpha'   => true,
                'format'     => null,
                'horizontal' => true,
            ]
        ]);
        CRUD::addField([
            'type'    => 'color_picker',
            'name'    => 'border_colour',
            'default' => 'rgba(0, 0, 0)',
            'color_picker_options' => [
                'useAlpha'   => false,
                'format'     => null,
                'horizontal' => true,
            ]
        ]);

### What I expected to happen

Have 1 field that allows transparency and 1 that doesn't.

### What happened

They both allow transparency.

### What I've already tried to fix it

Worked around it by overriding the default color_picker.blade.php file, remove the load once and give each init function a unique name. 

### Is it a bug in the latest version of Backpack? Yes

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version 5.4.11,8.x,8.1,mysql 5.7

When I run ```php artisan backpack:version``` the output is: 5.4.11@ffbadcdb6478822646600b2cd763490caa927155

**Comment by pxpm** [comment]
Thanks @greatsaltlake for the report 🙏 

You are totally right! At the moment that's not possible. 

I've submitted a PR to backpack PRO that will enable this to work. 

It's already merged and you can get it with a composer update. 💪 

Wish you the best 🎅
