### ISSUE TITLE
[Bug] Fresh installs don't run on Laravel 8

### ISSUE THREAD

**Issue by fabiopittol** [Laravel-Backpack/CRUD#4848]
# Bug report

### What I did

Backpack v5's installation guide says that...

> If you can run Laravel 8 or 9, you can install Backpack. Backpack does not have additional requirements. 

You can run the suggested commands to install via Composer like

```
composer require backpack/crud
php artisan backpack:install
```

### What happened

It installs fine, no errors on Composer's side, but if you try to access the `/admin` route it throws the following error:

> Error
> **Interface "Illuminate\Contracts\Session\Middleware\AuthenticatesSessions" not found** 

### What I've already tried to fix it

After some investigation I found that this middleware is [only available in Laravel 9](https://laravel.com/api/9.x/Illuminate/Contracts/Session.html), but [not 8](https://laravel.com/api/8.x/Illuminate/Contracts/Session.html). So for the later to work,, something has to be changed. 

Maybe force the install an older version of Backpack?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.27@e1afe088b4ca613fb96dc57e6d8dbcb8cc2c6b49

### BACKPACK VERSION:
5.4.11@ffbadcdb6478822646600b2cd763490caa927155
```

**Comment by pxpm** [comment]
Hey @fabiopittol thanks for the report. 🙏 

I've just submitted a PR to fix this issue https://github.com/Laravel-Backpack/CRUD/pull/4849

Sorry for the bad experience 😞 

Wish you the best 🎅
