### ISSUE TITLE
Plan password in case of user create crud[Bug] 

### ISSUE THREAD

**Issue by ghulammurtaza** [Laravel-Backpack/CRUD#4851]
# Bug report

### Created user crud while setting up, it registers users correctly but if I add new user after logging into admin panel, it saves plane password in db and of-course it will not in login form as login form encrypt and match password in db. 

??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hey @ghulammurtaza sorry I can't help you much here without proper information. 

Backpack already comes with authentication, and if you are using Backpack authentication you will have the password encrypted in the password field. 

You can have a look on how we do it and implement it yourself if you are building some custom auth controller. Have a look here: https://github.com/Laravel-Backpack/CRUD/blob/aff3509476dd0f8b236912e27ed79e120a9d7eb8/src/app/Http/Controllers/Auth/RegisterController.php#L77

I am going to close this as I don't think there is any bug in Backpack in this regard.

Wish you the best 🎅
