### ISSUE TITLE
[Bug] Unable to run PEST tests on versions 5.4.12 and up

### ISSUE THREAD

**Issue by TbishopP** [Laravel-Backpack/CRUD#4876]
# Bug report

### What I did

Ran vendor/bin/pest --coverage --parallel 

### What I expected to happen

My tests to execute

### What happened

The following errors are displayed and tests do not run 

![Screenshot 2023-01-03 at 15 36 34](https://user-images.githubusercontent.com/100126472/210389859-f82ef87b-7460-441b-889b-ec7971fe7c52.png)
                                                                     
### What I've already tried to fix it

Rolling back to 5.4.11 has allowed me to run the tests in the meantime, i'm yet to try and investigate a further fix

### Is it a bug in the latest version of Backpack?

Bug present in 5.4.12 and up

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is: 
### PHP VERSION:
PHP 8.1.6 (cli) (built: May 12 2022 23:30:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.46.0@62b05b6de5733d89378a279e40230a71e5ab5d92

### BACKPACK VERSION:
5.4.13@af521f3bfed6de5c41811289d901c6c66f8242e2

**Comment by BernhardK91** [comment]
That issue also occurs with PHPUnit on the following setup:

```
### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 28 2022 11:08:17) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v12.0.2, Copyright (c) 2002-2022, by ionCube Ltd.

### LARAVEL VERSION:
v9.46.0@62b05b6de5733d89378a279e40230a71e5ab5d92

### BACKPACK VERSION:
5.4.13@af521f3bfed6de5c41811289d901c6c66f8242e2
```

**Comment by BernhardK91** [comment]
@pxpm @tabacitu 

The file `testing.php` was introduced round about one month ago:
https://github.com/Laravel-Backpack/CRUD/blob/main/src/routes/backpack/testing.php

This file wants to load the class `Backpack\CRUD\Tests\Unit\Http\Controllers\UserCrudController` was it causing the issue. The class is autoloaded via the following definition in the composer.json file:
```
"autoload-dev": {
        "psr-4": {
            "Backpack\\CRUD\\Tests\\": "tests",
            "Backpack\\CRUD\\Tests81\\": "tests81"
        },
        [...]
    },
```

The problem is, that autoload-dev is only loaded, when the package that defines that autoload is the root package. (see documentation of composer [here](https://getcomposer.org/doc/04-schema.md#autoload-dev))

Because the file is loaded also when backpack is not the root package, this crashes all tests for all projects, when backpack is installed.

**Comment by BernhardK91** [comment]
**Workaround:** As this was introduced in 5.4.12, downgrading to 5.4.11 fixes this issue and my tests are working again for now.

**Attention: That is not a fix as downgrading is never recommended. This is only a workaround until a fixed version is provided!"

**Comment by danielwaghorn** [comment]
We can replicate this on our side too. Perfect diagnosis @BernhardK91 and looking at the Class Map generated by the composer autoloader this is absolutely the case.

For now we have pinned the version to 5.4.11.

**Comment by pxpm** [comment]
Hey guys. 

Sorry for the bad experience! I am on it, we should be good at most by tomorrow!! 

: 🙏

**Comment by remipou** [comment]
I am experimenting the same issue.
My package's TestCase loads BackpackServiceProvider and all my tests are failing, looking for UserCrudController

**Comment by tabacitu** [comment]
Pedro fixed it in https://github.com/Laravel-Backpack/CRUD/pull/4881 - so no need to lock it to `5.4.11` any more, a `composer update` should fix it for you.

Thanks for letting us know guys 🤦‍♂️ This is one of those times.

Cheers!

**Comment by BernhardK91** [comment]
@pxpm Nobody should be blamed for anything! There is no improvement without the risk of errors. And errors happen. 

Thank you very much for your afford and the fast fix!

**Comment by danielwaghorn** [comment]
Appreciate the quick resolution all, and no need to apologise! 🙏🏼
