### ISSUE TITLE
[Bug] Illuminate\Contracts\Container\BindingResolutionException : Target class [Backpack\CRUD\Tests\Unit\Http\Controllers\UserCrudController] does not exist.

### ISSUE THREAD

**Issue by bsh** [Laravel-Backpack/CRUD#4880]
# Bug report

### What I did

I've got that error running laravel's (latest) default tests. Namespace issue?

### Is it a bug in the latest version of Backpack?

yes

### Backpack, Laravel, PHP, DB version

PHP 8.1.6 (cli) (built: May 11 2022 08:55:59) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group                                            
Zend Engine v4.1.6, Copyright (c) Zend Technologies                    

### LARAVEL VERSION:
v9.45.1@faeb20d3fc61b69790068161ab42bcf2d5faccbc

### BACKPACK VERSION:
5.4.13@af521f3bfed6de5c41811289d901c6c66f8242e2

**Comment by BernhardK91** [comment]
This is a duplicate of #4876

**Comment by bsh** [comment]
This is a duplicate of https://github.com/Laravel-Backpack/CRUD/issues/4876
