### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by FAIYAZ181** [Laravel-Backpack/CRUD#4891]
How can I change the type of table column type from text to editable_text on button click using JavaScript?

**Comment by pxpm** [comment]
Hello @FAIYAZ181 I am sorry but I didn't understand your requirements. 

`editable_text` is already a text column that is converted to an input when user clicks it. 

Please describe your requirements, maybe some images of what you want to achieve would help me to better understand your use case. 

I will be closing this thread, but feel free to continue the conversation and I will try to help you the best I can.

Cheers
