### ISSUE TITLE
[Feature Request] Add support for Laravel 10

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/CRUD#4897]
# Feature Request

### What's the feature you think Backpack should have?

Add support for Laravel 10, which is [expected to be released at February 7th, 2023](https://laravel.com/docs/master/releases#support-policy).

A starting point could be to look at the upgrade to Laravel 9 (#4094) and tests for that (#4532) and model after that.

**Comment by pxpm** [comment]
Thanks for the heads up @jnoordsij 

I will add this to my todo list in the next days. 👍

**Comment by tabacitu** [comment]
Laravel 10 gets released next week, so... let's prioritize this for this week.

**Comment by pxpm** [comment]
- Need to bump assets packages https://github.com/DigitallyHappy/assets/pull/16
- Need to bump creativeorange/gravatar - on the way
- Need to bump prologue/alerts - on the way

**Comment by tabacitu** [comment]
Status report - all core dependencies have L10 support now, so [CRUD will soon have L10 support too](https://github.com/Laravel-Backpack/CRUD/pull/4914) 🎉. 

But let's try to also help these 3 vendors to add L10 support, a lot of Backpack devs are using them:
- https://github.com/VentureCraft/revisionable/pull/419
- https://github.com/laracasts/Laravel-5-Generators-Extended/pull/200
- https://github.com/cviebrock/eloquent-sluggable/pull/589

**Comment by jnoordsij** [comment]
Fixed now #4914 is merged and https://github.com/Laravel-Backpack/CRUD/releases/tag/5.5.0 has landed.

Thanks @pxpm!

**Comment by blondie63** [comment]
Hi, I've a project Laravel 9.5.4 and Backpack 5.5
Is there a guide to upgrade to Laravel 10.x ?

**Comment by tabacitu** [comment]
@blondie63 - no guide needed from Backpack's point of view, it supports L10 with no breaking changes. Just follow Laravel's standard upgrade guide - https://laravel.com/docs/10.x/upgrade

**Comment by blondie63** [comment]
@tabacitu I've tried but.. look:
https://github.com/Laravel-Backpack/community-forum/discussions/415
