### ISSUE TITLE
[Feature Request] Labels for checkboxes, radio buttons, and ranges should have `cursor: pointer` CSS property

### ISSUE THREAD

**Issue by pekka** [Laravel-Backpack/CRUD#4898]
Labels for checkboxes and radio buttons, and the `input type=range` element are clickable. 

The mouse cursor should reflect this by turning into a `pointer`:

<img src="https://user-images.githubusercontent.com/262464/212726443-ee855c4f-4453-4b7a-b6eb-67ad42c6978f.jpeg" width="250">

Got a pull request to do this. It's my first pull request ever, so be gentle if I screw it up 😄

**Comment by tabacitu** [comment]
Awesome! Thanks for the PR. Let's close this in favor of https://github.com/Laravel-Backpack/CRUD/pull/4899
