### ISSUE TITLE
[Feature Request] Add InlineCreate to relationship field when there are subfields 

### ISSUE THREAD

**Issue by chrisAlatorre** [Laravel-Backpack/CRUD#4900]
# Feature Request

### What's the feature you think Backpack should have?

Possibility to have the `InlineCreate` operation on the `relationship` field, including when the field has defined `subfields`.

For example, I have this field:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/56134113/213338901-eb1aed8f-c3f0-44d5-bab6-d237175086fd.png">

`
$this->crud->addField([
    'name'          => 'ingredients',
    'type'          => "relationship",
    'label'         => 'Ingredients',
    'inline_create' => ['entity' => 'ingredient'],
    'subfields'     => [
        [
            'name' => 'quantity',
            'type' => 'number',
            'wrapper' => [
                'class' => 'form-group col-md-6'
            ],
        ],
        [
            'name' => 'unit',
            'type' => 'text',
            'wrapper' => [
                'class' => 'form-group col-md-6'
            ],
        ]
    ]
]);
`

This gives me a field like this:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/56134113/213337922-f22e22f2-7018-4aea-ab19-408650e971d7.png">

But, as you can see, there is no `inlineCreate` operation available for the ingredient field. 

I can remove `subfields` and I'll get the `inlineCreate` operation but that removes the fields required for the pivot columns.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/56134113/213339022-c135756e-3e39-4026-9e09-26228f5f7b5e.png">

### Have you already implemented a prototype solution, for your own project?

I'm still struggling with the code, but I am on my way.

### Do you see this as a core feature or an add-on?

I'd to see it as a core feature.

**Comment by pxpm** [comment]
Hello @chrisAlatorre thanks 🙏 

To add the `InlineCreate` to the pivot field you should configure it using the `pivotSelect` key: https://backpackforlaravel.com/docs/5.x/crud-how-to#extra-saving-additional-attributes-to-the-pivot-table

Maybe we should make it more visible in the docs, I will submit a PR to highlight it. 

![image](https://user-images.githubusercontent.com/7188159/213593747-513a3647-8d53-4e56-988b-c202d5d6ef4a.png)

I will be closing this now, I think there is no bug, or other feature to build here. If I am wrong feel free to continue the conversation, I will get the notifications 👍 

Cheers
