### ISSUE TITLE
[Feature Request] "Create" and "edit" views should have current action as main title

### ISSUE THREAD

**Issue by pekka** [Laravel-Backpack/CRUD#4901]
When creating or editing an item, the current behaviour is that the page title is the model plural, and the name of the action we are currently taking is a subheading:

![image](https://user-images.githubusercontent.com/262464/213395644-a4f2381b-9af6-40d2-9cec-cdc32bd7b58b.jpeg)

This is arguably redundant and goes a bit against the minimalist beauty of Backpack. Also it makes it a tiny bit more difficult to quickly grasp what is going on on the page. Could be an issue especially for screen reader users and such. 

How about making the current action the heading, with no subheading set by default:

![image](https://user-images.githubusercontent.com/262464/213395944-4f381380-0fea-4628-a0f7-67abab69fd65.jpeg)

PR incoming

**Comment by pekka** [comment]
PR: https://github.com/Laravel-Backpack/CRUD/pull/4902
(is there something I can do to automatically connect a PR to the feature request?)

**Comment by pxpm** [comment]
Thank you @pekka 

I've just replied you in the PR thread. 

I will be closing this so that we keep the conversation regarding this issue in only one place. 

Cheers
