### ISSUE TITLE
select2_from_ajax with entity false not working

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#4907]
I'm using select2_from_ajax without  relations

I have a Crud controller named PayByLinkCrudController  and I have this field

```        $this->crud->addField([
            'label'       => "Booking", // Table column heading
            'type'        => "select2_from_ajax",
            'name'      => 'locator', 
            'entity'      => false, 
            'model'     => "App\Models\PayByLink",
            'data_source' => url('/admin/bookings/ajax-bookings-avalon-options')
        ]);
```
And it's working fine.

This week I created another model and another crud controller And I trying to use exactly the same field, so in the new crud controller I have this:

```
        $this->crud->addField([
            'label'       => "Reserva", // Table column heading
            'type'        => "select2_from_ajax",
            'name'        => 'locator',
            'entity'      => false, 
            'model'		  => "App\Models\CustomerCase",
            'data_source' => url('/admin/bookings/ajax-bookings-avalon-options')
        ]);
```
When I start to write, the select makes the call to the endpoint, and the endpoint return data, but the select is not showing the options. In both models exists the field 'locator', in both cases the call to the endpoint works, but the select only shows options with the first model.

### Is it a bug in the latest version of Backpack?
5.4.15 PRO

After I run ```composer update backpack/crud``` the bug is 

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.13 (cli) (built: Nov 26 2022 14:07:36) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.37.0@0c9675abf6d966e834b2ebeca3319f524e07a330

**Comment by miquelangeld** [comment]
Hi, any chance with this? I'm stuck on my project because of this and I can't understand why is failing when I have the same select input working with other model and I can't figure out why is failing. I think it shouldn't
I am well aware that you have a lot of work to do, excuse me

**Comment by pxpm** [comment]
Hey @miquelangeld sorry I let this one slip, I was attending Laracon last week and my backlog grew a bit, still trying to catch up with everything. 

In this case it would really help to see the returned data from the endpoint (atleast a bit of it to better understand). 

Also, what could be happening is that in the first case Backpack is able to pick the `attribute` automatically to display, and that could be failing somehow in your second example. 

Please confirm that you are using `CrudTrait` in your model, and manually specify an attribute in the field with `attribute => 'someModelAttributeToDisplay`. 

If nothing of this helps, please provide me as much info as you can so I can try to help you debug that, also check in browser dev console if you have any JS errors.

Cheers

**Comment by miquelangeld** [comment]
Hi Pedro! In both cases the data that the endpoint return is like this:
[{"id":"XXXR220000000-1","name":"MURR220039495-1 Localizador: XXX00000A"},{"id":"XXXR220000000-2","name":"MURR220039495-2 Localizador: XXX00000B"}]

In both cases I have a attribute named locator and in both cases I use CrudTrait and I don't get any error in console.

This is how I implemented that field in the controller which is not working (I tried with and without 'attribute':
```
$this->crud->addField([
            'label'       => "Booking",
            'type'        => "select2_from_ajax",
            'name'        => 'locator',
            'entity'      => false,
            'attribute'   => "locator",
            'model'		  => "App\Models\CustomerCase",
            'data_source' => url('/admin/bookings/ajax-bookings-avalon-options')
        ]);
```
And this is the reference model:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CustomerCase extends Model
{
    use \Backpack\CRUD\app\Models\Traits\CrudTrait;
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'locator',
        'casecode',
        'state',
        'casetype_id',
        'user_id',
        'description',
        'resolution',
        'customer_id',

    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'state' => 'integer',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function caseType()
    {
        return $this->belongsTo(CaseType::class);
    }
}

```

This is how I implemented that field in the controller which is working:
```
$this->crud->addField([
            'label'       => "Booking", 
            'type'        => "select2_from_ajax",
            'name'        => 'locator',
            'entity'      => false, 
            //'attribute'   => "locator",
        	'model'		  => "App\Models\PayByLink",
            'data_source' => url('/admin/bookings/ajax-bookings-avalon-options')
        ]);
```

This is the model:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PayByLink extends Model
{
    use \Backpack\CRUD\app\Models\Traits\CrudTrait;
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'locator',
        'amount',
        'name',
        'lastname',
        'comment',
        'email',
        'orderId',
        'language',
        'eco',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'amount' => 'decimal:2',
        'eco' => 'integer',
    ];
}

```

**Comment by pxpm** [comment]
Sorry @miquelangeld I don't see attribute `locator` from your example I only see returned `id` and `name`. 

If you change attribute to `attribute => 'name'` does it still don't work ?

**Comment by miquelangeld** [comment]
You're right Pedro.
What threw me off is that even if the attribute did not match in one of the two cases, it worked, although it should not work.
I changed name to locator in the endpoint results and now work in both controllers. Very sorry! It was my mistake.
