### ISSUE TITLE
[Bug] Reorder operation not working with MongoDB

### ISSUE THREAD

**Issue by patriksh** [Laravel-Backpack/CRUD#4909]
# Bug report

### What I did

Reorder operation is not working when using MongoDB as the database driver, with the [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) package.

The problem occurs here: https://github.com/Laravel-Backpack/CRUD/blob/5a7445bf2b5bb0b04f80694613c7789364bf7f1f/src/app/Library/CrudPanel/Traits/Reorder.php#L21

The method `beginTransaction` is called from `getPdo()` which is null for the MongoDB driver.

### What I expected to happen

`\DB::beginTransaction();` and `\DB::commit();` should only run for SQL database drivers.

### What happened

Currently they always run.

### What I've already tried to fix it

I temporarily fixed this by making a class alias and a class where I simply removed these lines.

### Is it a bug in the latest version of Backpack?

Yes.

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.46.0@62b05b6de5733d89378a279e40230a71e5ab5d92

### BACKPACK PACKAGE VERSIONS:
```

By the way, "backpack package versions" is indeed empty for me, I do have the version 5.4.15 installed.

**Comment by pxpm** [comment]
Hello @patriksh thanks for the report. 

I extracted two issues from here. The first one I already submitted a PR to fix, about the empty backpack versions in the `php artisan backpack:version`. https://github.com/Laravel-Backpack/CRUD/pull/4924

The second one about MongoDB, you already provided the solution, we need to wrap `DB::` calls into `CRUD::isDriverSql()` call. 

We have already some `if's` in the codebase checking for sql driver, and other open PR's to fix some issues that popped up when used with MongoDB, like https://github.com/Laravel-Backpack/CRUD/pull/4607

I don't like having the if's and else's all around the codebase to account for other db engines that we don't "officially" support.

I think if we plan on supporting other engines, MongoDB for example, we should think in a long-term maintainable solution that would provide that support, maybe even creating a child package like `backpack/crud-mongodb`, overwrite what's needed there, and remove the conditionals from the core codebase. 

That would also be a good exercise on making our "core" extensible/configurable. 

Unfortunately I don't think it's something that we are going to focus right way, maybe after we launch v6 we can revisit this.
At the moment our plate is full with the new Laravel version, our v6 and the planned packages to be launched this month. 

Sorry for not bringing the best news, I really like the idea of us supporting Mongo officially, I liked the few times I worked with it, so I hope in future we can give it some love. Right now I think your approach is perfectly fine and if you didn't know about the other issue I mentioned, feel free to apply it to your codebase too. 

Cheers

**Comment by pxpm** [comment]
Well, I had an "ahh ahh" moment and realized that we may be able to fix this in a non breaking way, and also improve our code to make it more performante. **win-win**

Let's move the conversation over to #5342 

Thanks for the report @patriksh 

Please don't tell me that upsert also doesn't work with the mongo package or I will be sad 😢 

Cheers
