### ISSUE TITLE
[Bug] Search not working when list has editable columns

### ISSUE THREAD

**Issue by JordanchoEftimov** [Laravel-Backpack/CRUD#4915]
# Bug report

### What I did

Added editable columns to the list operation in the CrudController.

### What I expected to happen

The search to work.

### What happened

Search does not work

### What I've already tried to fix it

When i remove the editable columns it works perfectly fine. With them the search does not work.

With this, it does not work:
```php
protected function setupListOperation()
    {
        $this->crud->addClause('whereDoesntHave', 'roles');
        CRUD::addColumn([
            'name' => 'name',
            'type' => 'editable_text',
            'label' => 'Име и презиме',
            'select_on_click' => true,
            'save_on_focusout' => true,
        ]);

        CRUD::addColumn([
            'name' => 'email',
            'type' => 'editable_text',
            'label' => trans('backpack::permissionmanager.email'),
            'select_on_click' => true,
            'save_on_focusout' => true,
        ]);

        CRUD::addColumn([
            'name' => 'comment',
            'type' => 'editable_text',
            'label' => 'Коментар',
            'select_on_click' => true,
            'save_on_focusout' => true,
        ]);

        CRUD::addColumn([
            'name' => 'phone',
            'type' => 'editable_text',
            'label' => 'Тел број',
            'select_on_click' => true,
            'save_on_focusout' => true,
        ]);

        $this->crud->addButtonFromModelFunction('line', 'show_addresses_button', 'show_addresses_button', 'beginning');
    }
```

With this, it works:
```php
protected function setupListOperation()
    {
        $this->crud->addClause('whereDoesntHave', 'roles');
        $this->crud->setColumns([
            [
                'name' => 'name',
                'label' => 'Име и презиме',
                'type' => 'text',
            ],
            [
                'name' => 'email',
                'label' => trans('backpack::permissionmanager.email'),
                'type' => 'email',
            ],
            [
                'name' => 'comment',
                'label' => 'Коментар',
                'type' => 'text',
            ],
            [
                'name' => 'phone',
                'label' => 'Тел број',
                'type' => 'text',
            ],
        ]);


        $this->crud->addButtonFromModelFunction('line', 'show_addresses_button', 'show_addresses_button', 'beginning');
    }
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes it is.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### LARAVEL VERSION:
v9.47.0@92810d88f9a4252095a56c05541b07940363367c

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.4.16
backpack/editable-columns: 2.1.1
backpack/logmanager: v4.0.9
backpack/pagemanager: 3.0.11
backpack/permissionmanager: 6.0.15
backpack/pro: 1.5.0
backpack/settings: 3.0.16
backpack/generators: v3.3.10
````

**Comment by pxpm** [comment]
Hello @JordanchoEftimov 

Thanks for the report, unfortunately the "automatic search" functionality works depending on the column type, and at the present moment `editable_text` is not the same as `text` in terms of column type as far as CRUD is concerned. 

You can manually define the search parameters for your editable columns, for example:
```php
CRUD::column('email')
            ->label('Email')
            ->type('editable_text')
            ->searchLogic(function ($query, $column, $searchTerm) {
                $query->orWhere('email', 'like', '%'.$searchTerm.'%');
            });
```

@tabacitu what we should do about this ? 
1 - mentioning `editable_text` in crud is out of question I guess.
2 - adding this to the editable column docs (inexpensive, but alot of work for devs/plus alot of boilerplate code in controller).
3 - create a custom solution for use cases like this, something like a concept of `Column Configurator` where you can register multiple configs for diverse column types (mainly from packages). 
    That way we could register a `SearchLogic` Column Configurator for `editable_` column types. 
    Backpack would run the stack of configurators registered for each column type before passing the columns to the views.
    (kind of ViewNamespaces, globally available)
4 - Anything I didn't think in this last 30m!

**Comment by tabacitu** [comment]
Hello @JordanchoEftimov ,

Pedro and I brainstormed on this, and it turns out... we already had a nice solution to this, we just didn't remember it 🤦‍♂️ Please do:

```php
CRUD::column('email')
            ->label('Email')
            ->type('editable_text')
            ->searchLogic('text');
```

This last bit will tell Backpack "_search this column as if it were a text column_". Unfortunately, for now, you'll have to do this for every editable column. We'll think of a way to automate this in the next version. Until then, I'll ask @pxpm to document this on EditableColumn - what default `searchLogic()` should be used for each editable column type.

Thank you for your patience 🙏
Cheers!

**Comment by JordanchoEftimov** [comment]
Oh, nice to hear that. I already solved this problem with the solution proposed above, but thanks anyway.
