### ISSUE TITLE
[DEV ERROR SQL] - Xampp - Apache + MariaDB (10.2) + Laravel 5.4 

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#492]
Hi there.

First of all, i have to say: @tabacitu thanks for this great work!

I'm having trouble using the new multilangue feature with the setup described in title.

I added the dependencies (spatie translatable and cviebrock sluggable)
I added the traits to my model. (extended backpack ones)

I try to create a new model instance and got the following error:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>'$."en"' = ? or `slug`->'$."en"' LIKE ?)' at line 1 (SQL: select `slug`, `companys`.`id` from `companys` where (`slug`->'$."en"' = fuck-you-bitchasss or `slug`->'$."en"' LIKE fuck-you-bitchasss-%))
```

It could be a problem using MariaDB ? Or is something wrong with my setup ?

Thanks in advance,
Pxpm

**Comment by tabacitu** [comment]
Thanks, @pxpm . But it's not just me, [it's a team effort](https://github.com/Laravel-Backpack/CRUD/graphs/contributors).

Hmm... I don't know. Does that version of MariaDB support JSON columns? That is an important requirement of spatie/laravel-translatable.

Cheers!

**Comment by pxpm** [comment]
@tabacitu as far as i found when googlin', mariadb does not support native json field.
But we can use text to store json, as i am actually doing. Or that will break spatie translatable from working properly ? If so, i will try to switch from MariaDB to Mysql (with support for json) and give you any feedback on that. 
Thanks

**Comment by tabacitu** [comment]
Yup, thought so. Well spatie/laravel-translatable breaks not when storing (as you said, you can just use text columns for storing), but when retrieving the information from the db. MySQL, for ex, allows you to search within JSON columns, with ```SELECT * FROM products WHERE extras->active=1```, where extras is a MySQL column, active is an attribute within that JSON array.

That operator for JSON columns (```->```) is pretty special, I think that's where MariaDB goes "wtf" :-)
