### ISSUE TITLE
[Bug] belongsTo relationship doesn't get automatically resolved

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#4920]
# Bug report

Adding a field related to a belongsTo relation doesn't get properly resolved.

### What I did

Added a field to a crud controller:
```php

[
    'name'       => 'music.bpm',
    'type'       => 'text',
    'label'      => 'BPM',
    'wrapper'    => ['class' => 'form-group col-md-3'],
    'attributes' => ['step' => '.01', 'min' => '1'],
    // possible temporary fix: 'value' => $musicVariant->music->bpm
],
```

Implemented this relationship in the model used in the CRUD:
```php
// fields: id, name, music_id...
class MusicVariant extends Model
{
    use CrudTrait;

    public function music(): BelongsTo
    {
        return $this->belongsTo(Music::class, 'music_id', 'id');
    }
}
```

Implemented the relation from the other side:

```php
// fields: id, title, subtitle, bpm, duration...
class Music extends Model
{
    use CrudTrait;
   
    public function music_variants(): HasMany
    {
        return $this->hasMany(MusicVariant::class, 'music_id', 'id');
    }
}
```

### What I expected to happen

It should show the related field value in the edit form and it should update it correctly when saving.

### What happened

The value that the form shows is the actual music_id field of the MusicVariant entry (the same Model used in the CRUD).

### What I've already tried to fix it

I tried to use the 'value' field by setting it with ```$this->crud->getCurrentEntry()->music->bpm``` and it works.
I also overwritten the update and create functions like this:
```php
   public function update()
    {
        $request = $this->crud->getRequest();

        $response = $this->_update();

        /** @var MusicVariant $musicVariant */
        $musicVariant = $this->crud->entry;

        if ($musicVariant) {
            $musicVariant->music->update([
                'bpm' => $request->get('music_bpm')
            ]);
        }

        // do something after save
        return $response;
    }
```

Note that changing the music() relation from a belongsTo to a hasOne and setting the right fk works perfectly fine.

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun 16 2022 12:46:39) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.50.2@39932773c09658ddea9045958f305e67f9304995

**Comment by pxpm** [comment]
Hello @EmanueleCoppola 

The `dot.notation` in fields is exclusive to `HasOne` and `MorphOne` relations at the moment.

To create a `BelongsTo` relation in the same form, developers should use the [InlineCreateOperation](https://backpackforlaravel.com/docs/5.x/crud-operation-inline-create#about-1) (PRO feature). 

I am going to close this as I don't think there is any bug here but feel free to continue the conversation or re-open if needed, I've been wrong before 💪 

Cheers
