### ISSUE TITLE
digitallyhappy/assets 2.0.1 requires laravel/framework ^8.0 

### ISSUE THREAD

**Issue by asifroyal** [Laravel-Backpack/CRUD#4928]
# Bug report

### What I did

Tried to update backpack/crud version 5.5.0 compatible with Laravel 10

### What happened
Resulted Following error:

` digitallyhappy/assets 2.0.1 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).
`

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
5.5.0

**Comment by pxpm** [comment]
Hello @asifroyal 

you should update `digitallyhappy/assets` to `2.1.0` where support for L10 was added https://github.com/DigitallyHappy/assets/releases/tag/2.1.0

Going to close this, feel free to continue the conversation or re-open if needed.

Cheers

**Comment by asifroyal** [comment]
@pxpm It looks like something internal dependency. Not installed the package in question. composer.json of the CRUD:5.5.0 package shows following entry "digitallyhappy/assets": "^2.0.1" [https://github.com/Laravel-Backpack/CRUD/blob/main/composer.json#L37](url)

**Comment by sylfel** [comment]
I have same problem 
```
Problem 1
    - digitallyhappy/assets 2.0.1 requires laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^v10.0).
    - digitallyhappy/assets[2.0.2, ..., 2.0.4] require laravel/framework ^9.0|^8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^v10.0).
    - Root composer.json requires backpack/crud ^5.5 -> satisfiable by backpack/crud[5.5.0].
    - digitallyhappy/assets 2.1.0 requires laravel/framework ^10|^9.0|^8.0 -> satisfiable by laravel/framework[v10.0.0, v10.0.1, v10.0.2, v10.0.3].
    - Only one of these can be installed: illuminate/pipeline[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0, v10.0.1, v10.0.2, v10.0.3], laravel/framework[v10.0.0, v10.0.1, v10.0.2, v10.0.3]. laravel/framework replaces illuminate/pipeline and thus cannot coexist with it.
    - spatie/laravel-medialibrary 10.7.2 requires illuminate/pipeline ^9.18 -> satisfiable by illuminate/pipeline[v9.18.0, ..., v9.52.0].
    - backpack/crud 5.5.0 requires digitallyhappy/assets ^2.0.1 -> satisfiable by digitallyhappy/assets[2.0.1, ..., 2.1.0].
    - Root composer.json requires spatie/laravel-medialibrary 10.7.2 -> satisfiable by spatie/laravel-medialibrary[10.7.2].
```
Can you update your dependency please ?
