### ISSUE TITLE
custom button

### ISSUE THREAD

**Issue by rzaglinskij** [Laravel-Backpack/CRUD#493]
what folder I need to use, if I want to add custom button
$this->crud->addButtonFromView('line', 'open', 'send', 'beginning');
in resources/view/admin/ ???

**Comment by tabacitu** [comment]
Hi @rzaglinskij ,

Try ```resources/views/vendor/backpack/crud/buttons```.

Cheers!

**Comment by rzaglinskij** [comment]
and when I will update the CRUD package, I will loose my button templates ?

**Comment by tabacitu** [comment]
Nope. Since it's in your folder, it stays there. Basically, composer works like this:
- ```vendor/*``` gets overwritten
- ```resources/views/vendor/*``` will never get overwritten;

**Comment by deeKodar** [comment]
I want to create a custom button on the Teacher CRUD at the beginning of the inline buttons. I am using this code $this->crud->addButton('line','Details','view','beginning'); but i am getting this error
ErrorException in FileViewFinder.php line 137:
View [beginning] not found. (View: /Applications/XAMPP/xamppfiles/htdocs/laravelprojects/tpt/tpas/vendor/backpack/crud/src/resources/views/inc/button_stack.blade.php).
Would much appreciate the help. Thank u in advance.

**Comment by MPTA** [comment]
hi , thanks for backpack .
i cannot find this root , resources/views/vendor/backpack/crud/buttons. 
actually in crud folder only folder name"field" is exist . i am using newer version of back pack.
i tried many time to add button to the list but no work.
please give me complete sample of that.

**Comment by AbbyJanke** [comment]
Hello, by default that folder does not exist, when you run the ‘backpack:base:install’ script it installs the bare minimum that you need. You simply just need to create that new folder called ‘buttons’.
