### ISSUE TITLE
Elfinder returns a backslash "\" when using the Browse field

### ISSUE THREAD

**Issue by dobromir-hristov** [Laravel-Backpack/CRUD#496]
I tried setting a "separator" property in the elfinder config's options property, but that didnt help. Problem is when I try to use the path, the browser tries to escape the backslash and things get weird. 
I could overwrite the browse field template and replace the backslash in the `processSelectedFile` file, but dont know if thats the best way to do it. 

OS: Windows
CRUD ver: Latest

**Comment by denbatte** [comment]
I have the same issue. Also on Windows.

![image](https://cloud.githubusercontent.com/assets/505196/24485213/162be62c-1503-11e7-9df8-76f4ac202d87.png)

I tried adding ``` 'separator' => "/" ``` to the elfinder config options but that did not seem to help.

**Comment by lloy0076** [comment]
Is this still an issue?

**Comment by tabacitu** [comment]
Hi guys, 

I don't quite understand. When\where is that backslash returned? When you clear the browse input?

Cheers!

**Comment by dkisdbest** [comment]
same issue, its returned after you select any image from elfinder

**Comment by tabacitu** [comment]
Huh... just tried it again it doesn't seem to be a problem on unix systems, so it sounds like an elfinder issue that's isolated on windows env. And I have no way of testing on windows... 

@dobromir-hristov did you happen to find a solution to this since you posted?

**Comment by dobromir-hristov** [comment]
@tabacitu Yeah, I extended the browse template and did a replace with javascript. 
```js
		function processSelectedFile(filePath, requestingField) {
		    $('#' + requestingField).val(filePath.replace(/\\/g,"/"));
		}
```

**Comment by dkisdbest** [comment]
yes, this issue only on windows system.

**Comment by tabacitu** [comment]
@dobromir-hristov awesome! Can you please help out with a PR when you have the time? I can test if it doesn't break things on mac & linux, and then merge it if not.

Thanks a lot!

**Comment by tabacitu** [comment]
Actually I took a harder look and understood where you made the change. It does nothing on unix systems so I merged it on ```dev```. It'll be available in the next patch release - today or tomorrow.

Thanks a lot guys!
