### ISSUE TITLE
[Bug] Reorder not working with uuid primary

### ISSUE THREAD

**Issue by masrodjie** [Laravel-Backpack/CRUD#4961]
# Bug report
When using uuid as primary key, reorder not working

### What I did
Migration:
`
Schema::create('categories', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('name', 32);
            $table->uuid('parent_id')->nullable()->default(0);
            $table->uuid('lft')->default(0);
            $table->uuid('rgt')->default(0);
            $table->unsignedInteger('depth')->default(0);
});
`

### What I expected to happen
Reorder should successfully saved

### What happened
Reorder not saved

### What I've already tried to fix it

It's looks like the problem in javascript selector can't get the id of item correctly. For example, the id is 989ce31a-4fc9-4849-a54d-c4c5caf287c7. The is of list is correct: list_989ce31a-4fc9-4849-a54d-c4c5caf287c7 but the payload only get c4c5caf287c7 ( "item_id":"c4c5caf287c7" ) . It's truncated. The problem is in jquery.mjs.nestedSortable2.js when it's try to get the data 
`
arraied = $('ol.sortable').nestedSortable('toArray', {startDepthCount: 0});
`
the item_id is truncated

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version
- Backpack 5.5.1 
- Laravel 9.52.4 
- MySQL 8

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.15 (cli) (built: Feb  9 2023 13:19:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.15, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.4@9239128cfb4d22afefb64060dfecf53e82987267

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.1
backpack/generators: v3.3.15
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.1

**Comment by karandatwani92** [comment]
Thanks @masrodjie  for reporting the issue, we have identified the bug and trying to come up with a patch in the upcoming update. You defined it well. Thanks a lot.

**Comment by karandatwani92** [comment]
Resolved #4967
