### ISSUE TITLE
[V6] Use dropdown for actions column on List operation

### ISSUE THREAD

**Issue by maurohmartinez** [Laravel-Backpack/CRUD#4963]
# Feature Request

### What's the feature you think Backpack should have?

As devs add more and more inline operations, the actions column gets crowded quickly. It would be great to have a dropdown button that groups all actions and displays them in a compact way.

### Have you already implemented a prototype solution, for your own project?

I did something for my projects, but I don't think it can be used here. Short answer, no :)

### Do you see this as a core feature or an add-on?

Just an improvement.

<img width="650" alt="Screenshot 2023-03-06 at 14 18 40" src="https://user-images.githubusercontent.com/33960976/223108458-a7eabb03-af57-48b4-9b1d-84287aab3af9.png">

**Comment by ziming** [comment]
this look amazing!

**Comment by tabacitu** [comment]
Mauro, let's please do this as a PR to `main`, so we can launch it in v5 💪

**Comment by maurohmartinez** [comment]
Close in favor of https://github.com/Laravel-Backpack/CRUD/pull/5005
