### ISSUE TITLE
Call to undefined method App\Models\ChangeRequest::changeable_id()

### ISSUE THREAD

**Issue by AlexKomMsk** [Laravel-Backpack/CRUD#4968]
# Bug report

### What I did

I am trying to open a model (setupShowOperation).

### What I expected to happen

See model fields.

### What happened

I get an error "Call to undefined method App\Models\ChangeRequest::changeable_id()"

Model App\Models\ChangeRequest

```
    use CrudTrait, Moderatable;

    public function changeable(): MorphTo
    {
        return $this->morphTo();
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
```

Migration

```
        Schema::create('change_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(User::class)->constrained()->cascadeOnDelete();
            $table->morphs('changeable');
            $table->string('new');
            $table->string('old');
            $table->string('reason');
            $table->string('field');
            $table->foreignIdFor(Status::class)->constrained()->cascadeOnDelete();
            $table->dateTime('mod_at')->nullable();
            $table->timestamps();
        });
```

Method setupShowOperation

```
    protected function setupShowOperation()
    {
        CRUD::field('changeable_type');
        CRUD::field('changeable_id');
        CRUD::field('old');
        CRUD::field('new');
        CRUD::field('reason');

        $this->crud
            ->column('status.name')
            ->type('relationship')
            ->label('Status')
            ->type('string');

        CRUD::column('created_at');
        CRUD::field('field');
    }
```

If I remove changeable fields

```
    protected function setupShowOperation()
    {
        CRUD::field('old');
        CRUD::field('new');
        CRUD::field('reason');
        CRUD::column('created_at');
        CRUD::field('field');
    }
```

I don't see any fields other than created at. There aren't any other fields ('old', 'new', 'reason', 'field' - missing).

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.52.4@9239128cfb4d22afefb64060dfecf53e82987267

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.2
backpack/generators: 3.3.16

**Comment by karandatwani92** [comment]
Hi @AlexKomMsk,
In Backpack, the fields which you want to show are known as **columns** and editable fields are known as **fields**.

- [Columns](https://backpackforlaravel.com/docs/5.x/crud-columns) are used in show and list operation to display the value; `CRUD::column()`
- [Fields](https://backpackforlaravel.com/docs/5.x/crud-fields) are used in create and update operation; `CRUD::field()`

That's why you they were not visible to you.

**Comment by AlexKomMsk** [comment]
Yes, that's right. Thank you.
