### ISSUE TITLE
Can't upload file on disk

### ISSUE THREAD

**Issue by jaublanc-bobbies** [Laravel-Backpack/CRUD#497]
Hello,

I'm trying to save a pdf file in my disk with an upload field

`[
                'name' => 'ticket',
                'label' => 'Billet Electronique (PDF)',
                'type' => 'upload',
                'upload' => true
            ]`

`public function setTicketAttribute($value)
    {
        $attribute_name = "ticket";
        $disk = "public";
        $destination_path = "uploads/billets";
        $this->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
    }`

I would like to save the file in the publi/uploads/billets folder. The new filename with correct path is saved in the database but not on the disk.

Any idea ?

**Comment by MarcosBL** [comment]
Look into your config if the "public" $disk is defined and you have correct permissions to access that folder. Look at php/laravel error logs for a cause, backpack seems to be working fine

**Comment by elfirasy** [comment]
I got the same problem then I try to change the $disk on mutator to "uploads" and work fine.
Make sure you set the destination path to subfolder of uploads folder.
