### ISSUE TITLE
Relations widgets for edit and view pages

### ISSUE THREAD

**Issue by azenot-dev** [Laravel-Backpack/CRUD#4970]
# Feature Request

### What's the feature you think Backpack should have?

Related tables in Edit, View page

### Have you already implemented a prototype solution, for your own project?

https://github.com/izica/relations-widgets-for-backpack

### Do you see this as a core feature or an add-on?

??

**Comment by tabacitu** [comment]
Totally agree, thanks @azenot-dev . It's one of the most requested features in Backpack, and we'll make sure to do it in Backpack v6! We just want to do it in a future-proof way, so we're taking our time. Until then, the package you referenced should help you have that feature right now.

**Comment by tabacitu** [comment]
Let's talk about this inside https://github.com/Laravel-Backpack/community-forum/issues/108 or https://github.com/Laravel-Backpack/community-forum/issues/100 please - both ask for the same thing, just slightly different, so no point in having yet another thread about this.
