### ISSUE TITLE
[Bug] Reorder stops working when depth > 2 and middle element is deleted

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#4982]
Reported here: https://github.com/Laravel-Backpack/CRUD/pull/4908

It has videos and such so no much explanation needed. Just need to find a better solution.

**Comment by karandatwani92** [comment]
Hey @pxpm
I solved here #5028 

This is the best solution as per my understanding. I tested in multiple ways, worked every way!
You too have a check! 🤞

**Comment by pxpm** [comment]
Closing this one. 

let's keep the conversation in the PR https://github.com/Laravel-Backpack/CRUD/pull/5028
