### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SalmaANegm** [Laravel-Backpack/CRUD#4987]
# Bug report

In the list page I am using **$this->crud->addClause()** to customize the list query. One of my pages must show 31 entries (4 pages 10 entry per page). Unfortunately, It's showing only one page. I used **$this->crud->setOperationSetting('showEntryCount', false)** to exceeds this issue. Unfortunately, the next button is working fine but the Prev button is always returning me to the first page.

Numbered pagination and total number of entries is not working fine when using custom queries  **$this->crud->addClause()** .

![image](https://user-images.githubusercontent.com/49648013/225706777-936af70c-e0b9-490c-af20-52e211f918de.png)
It must be **Showing 1 to 10 of 31 entries**

![image](https://user-images.githubusercontent.com/49648013/225707858-11afca11-450f-4194-a234-7eb9e6bd80ec.png)
There must be 4 pages, but it's showing only 1!

### Backpack, Laravel, PHP version

I am using "backpack/crud": "^5.3.11"

When I run ```php artisan backpack:version``` the output is:

**PHP VERSION:**
PHP 8.1.14 (cli) (built: Jan 13 2023 10:43:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.14, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

**LARAVEL VERSION:**
v8.83.27

**Comment by SalmaANegm** [comment]
I have fixed it by overriding the following methods:

public function search()
    {
        $this->crud->hasAccessOrFail('list');

        $this->crud->applyUnappliedFilters();

        $start = (int) request()->input('start');
        $length = (int) request()->input('length');
        $search = request()->input('search');

        // if a search term was present
        if ($search && $search['value'] ?? false) {
            // filter the results accordingly
            $this->crud->applySearchTerm($search['value']);
        }
        // start the results according to the datatables pagination
        if ($start) {
            $this->crud->skip($start);
        }
        // limit the number of results according to the datatables pagination
        if ($length) {
            $this->crud->take($length);
        }
        // overwrite any order set in the setup() method with the datatables order
        $this->crud->applyDatatableOrder();

        $entries = $this->crud->getEntries();

        // if show entry count is disabled we use the "simplePagination" technique to move between pages.
        if ($this->crud->getOperationSetting('showEntryCount')) {
            $totalEntryCount = $this->getFilteredQueryCount();

            $filteredEntryCount = $this->getFilteredQueryCount() ?? $totalEntryCount;
        } else {
            $totalEntryCount = $length;
            $filteredEntryCount = $entries->count() < $length ? 0 : $length + $start + 1;
        }

        // store the totalEntryCount in CrudPanel so that multiple blade files can access it
        $this->crud->setOperationSetting('totalEntryCount', $totalEntryCount);

        return $this->crud->getEntriesAsJsonForDatatables($entries, $totalEntryCount, $filteredEntryCount, $start);
    }

    public function getFilteredQueryCount()
    {
        // check if the filtered query is different from total query, in case they are the same, skip the count
        $filteredQuery = $this->crud->query->toBase()->cloneWithout(['orders', 'limit', 'offset']);
        return $filteredQuery->toSql() !== $this->crud->totalQuery->toSql() ? $filteredQuery->get()->count() : null;
    }

**Comment by promatik** [comment]
Glad you fixed @SalmaANegm 👌

I'll just ping @pxpm, because he has been working with the page filters.

Also, this was your diff;

![image](https://user-images.githubusercontent.com/1838187/225761473-81494735-4056-41b3-a7ce-f0a58c4ce02b.png)

![image](https://user-images.githubusercontent.com/1838187/225761603-f0c0b2ae-25e6-4951-8e66-a830ff56a08c.png)

@pxpm do you think this may be a bug?
