### ISSUE TITLE
inline create redirect url error

### ISSUE THREAD

**Issue by afagard** [Laravel-Backpack/CRUD#4994]
# Bug report

### What I did

Trying to use `inline_create` on `relationship` field

```
        CRUD::addField([
            'type' => 'relationship',
            'name' => 'provider_id',
            'entity' => 'provider',
            'attribute' => 'name',
            'ajax' => true,
            'inline_create' => [
                'entity' => 'providers'
            ]
        ]);
```

### What I expected to happen

User is able to inline create related rows and have that new item be added to the select2 box.

### What happened

Results in an error when inline creating "could not create related entity"

in console I was able to see the ajax request returning a 500:

ErrorException: Undefined variable $redirectUrl in file C:\xampp\htdocs\pathos\husa-middleman\vendor\backpack\crud\src\app\Library\CrudPanel\Traits\SaveActions.php on line 352

For references my `ProvidersCrudController` is pretty run-of-the-mill

```
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ProvidersRequest;
use App\Models\Provider;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;
use Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
use Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
use Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;
use Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanel;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;
use Backpack\Pro\Http\Controllers\Operations\InlineCreateOperation;

/**
 * Class ProvidersCrudController
 * @package App\Http\Controllers\Admin
 * @property-read CrudPanel $crud
 */
class ProvidersCrudController extends CrudController
{
    use InlineCreateOperation;
    use ListOperation;
    use CreateOperation;
    use UpdateOperation;
    use DeleteOperation;
    use ShowOperation;

    /**
     * Configure the CrudPanel object. Apply settings to all operations.
     *
     * @return void
     */
    public function setup()
    {
        CRUD::setModel(Provider::class);
        CRUD::setRoute(config('backpack.base.route_prefix') . '/providers');
        CRUD::setEntityNameStrings('providers', 'providers');
    }

    /**
     * Define what happens when the List operation is loaded.
     *
     * @see  https://backpackforlaravel.com/docs/crud-operation-list-entries
     * @return void
     */
    protected function setupListOperation()
    {
        CRUD::column('name');
        CRUD::column('code');
        CRUD::column('notes');
        CRUD::column('created_at');
        CRUD::column('updated_at');
    }

    /**
     * Define what happens when the Update operation is loaded.
     *
     * @see https://backpackforlaravel.com/docs/crud-operation-update
     * @return void
     */
    protected function setupUpdateOperation()
    {
        $this->setupCreateOperation();
    }

    /**
     * Define what happens when the Create operation is loaded.
     *
     * @see https://backpackforlaravel.com/docs/crud-operation-create
     * @return void
     */
    protected function setupCreateOperation()
    {
        CRUD::setValidation(ProvidersRequest::class);

        CRUD::field('name');
        CRUD::field('code')->hint('Example: B360 or HUSA-EX');
        CRUD::field('notes');
    }
}
```

### What I've already tried to fix it

unsure how to proceed

### Is it a bug in the latest version of Backpack?

Yes

### PHP VERSION:
PHP 8.1.6 (cli) (built: May 11 2022 08:55:59) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v10.1.3@12256504186326a9d02b2ab3b43a4031a59b52d1

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.2
backpack/generators: 3.3.16
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.3

**Comment by pxpm** [comment]
> It was the order of traits listed!
> 
> Should be like so, with create first, then inlinecreate:
> 
> ```
>     use ListOperation;
>     use CreateOperation;
>     use UpdateOperation;
>     use DeleteOperation;
>     use ShowOperation;
>     use InlineCreateOperation;
> ```

Thanks for getting back @afagard 🙏  Happy you found the solution.
Indeed, that's a requirement, I just went ahead and checked in the docs if we added it there, we could have missed that info 🤷 

![image](https://user-images.githubusercontent.com/7188159/226943524-95dc1b0d-d368-41df-a77d-4b8a0f7f9975.png)

It's there ... so we should be good !

Cheers
