### ISSUE TITLE
Navigation Menu Filter [Feature Request]

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#4997]
# Feature Request

### What's the feature you think Backpack should have?

![Screenshot 2023-03-23 at 4 35 54 PM](https://user-images.githubusercontent.com/8214221/227185766-176d40d6-0ef2-418f-99cc-dec7bc447f58.png)

### Have you already implemented a prototype solution, for your own project?
NO

### Do you see this as a core feature or an add-on?
Core

**Comment by tabacitu** [comment]
This would be super-difficult to implement (in a general way), because the menu is defined in a customizable blade file that developers publish. Soo.... no 👀

Rather than searching ONLY in the menu... I'd build an omni-search, that searches within pages AND items.
