### ISSUE TITLE
ShowOpeartion with soft delete not working

### ISSUE THREAD

**Issue by rickyviz** [Laravel-Backpack/CRUD#4998]
# Bug report
I use soft delete on a specific model, for trashed . on ShowOpeartion return query false, because id not found,

### What I expected to happen

??

### What happened
 can't correct query on show operation on deleted data (Soft deleted)

### What I've already tried to fix it
```
  function setupShowOperation()
    {
        // $this->crud->addClause('withTrashed');
        $this->setupListOperation();
        $this->crud->query = $this->crud->query->withTrashed();
   }
```
### Is it a bug in the latest version of Backpack?
Backpack 4

**Comment by phpfour** [comment]
Hello @rickyviz, please check if you have the below flag set to **true** in your config file at: `config/backpack/operations/show.php`: 

![CleanShot 2023-03-30-00 45 12](https://user-images.githubusercontent.com/171715/228637889-d750fe0b-3e54-4014-8408-9976e847be3a.png)

You wouldn't need to override the `setupShowOperation` if the above is set correctly.

**Comment by rickyviz** [comment]
@phpfour i can't find config/backpack/operations/show.php

**Comment by phpfour** [comment]
@rickyviz Can you please run ```php artisan backpack:version``` and share the output ? If that doesn't work, can you share your `composer.json` file?

**Comment by rickyviz** [comment]
@phpfour thanks for response  
### LARAVEL VERSION:
v8.83.23
### BACKPACK VERSION:
4.1.71
this composer.json
        "backpack/crud": "4.1.*",
        "backpack/filemanager": "^1.1",
        "backpack/permissionmanager": "^6.0",
        "barryvdh/laravel-dompdf": "^0.9.0",

**Comment by pxpm** [comment]
@rickyviz sorry it's not available in that version. 

We fixed it in v5 and left that bug behind because the fix was a breaking change, that we could only push on a new version (v5). 

You have [in this PR](https://github.com/Laravel-Backpack/CRUD/pull/3132) the logs of what changed, you may want to try to re-implement it in your application manually if updating is not possible.

Cheers
