### ISSUE TITLE
PDO support

### ISSUE THREAD

**Issue by ngutip** [Laravel-Backpack/CRUD#50]
> QueryException in Connection.php line 713:
> SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error (SQL: SHOW COLUMNS FROM tags)

change line DB::raw('SHOW COLUMNS FROM in
/vendor/backpack/crud/src/PanelTraits/AutoSet.php and /vendor/backpack/crud/src/CrudTrait.php with 
`Schema::hasColumn( string $table, string $column)`
all shema method please refer to documentation [/Illuminate/Database/Schema/Builder](https://laravel.com/api/5.2/Illuminate/Database/Schema/Builder.html)

thank you

**Comment by tabacitu** [comment]
Hi @ngutip ,

Something like this should solve it, yes:
```php
public function getDbColumnTypes()
    {
        $table_columns = Schema::getColumnListing($this->model->getTable());

        foreach ($table_columns as $key => $column) {
            $column_type = Schema::getColumnType($this->model->getTable(), $column);
            $this->field_types[$column]['type'] = trim(preg_replace('/\(\d+\)(.*)/i', '', $column_type));
            $this->field_types[$column]['default'] = ''; // no way to do this using DBAL?!
        }

        return $this->field_types;
    }
```

But we also set the default column value here, and I found no way to do that using DBAL. Do you know any other way?

**Comment by tabacitu** [comment]
@ngutip thanks for your input! I did NOT find a way to get the default value in PDO.
But I concluded that feature was less important than actually supporting multiple database types.

Thanks again. Cheers!
