### ISSUE TITLE
[Bug] Update Trait: bad array key checking $field['subfield']

### ISSUE THREAD

**Issue by EdersonRodrigues7** [Laravel-Backpack/CRUD#5002]
# Bug report

### What I did

I'm using a relation field inside one of the ModelCrudController on the setupCreateOperation, following the documentation:

`$this->crud->addField([
            'label' => 'Category',
            'type' => 'select',
            'name' => 'category_id',
            'entity' => 'category',
            'attribute' => 'category_name',
            'model' => 'App\Models\Category',
]);`

The Model has a method 'category()' returning a 'belongsTo' relation. Besides, the setupUpdateOperation uses the same form as the create operation:
`protected function setupUpdateOperation()
{
   $this->setupCreateOperation();
}`

### What I expected to happen

The expected behavior would be to show the form with all the fields. The create operation doesn't throw any exceptions.

### What happened

When I call the update operation (through the "edit" button), the following error is shown:

`Undefined array key "subfields"` at vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Update.php line 170 inside the method "getModelAttributeValueFromRelationship".

### What I've already tried to fix it
First, I tried to keep only the essential fields (label, name, type) to let Backpack guess the correct relation and method, but it didn't work. 
Finally, I've set the 'subfields' property to null inside my addField definition. This change avoids the error, but I guess this isn't the expected behavior, since the documentation doesn't cover this workaround:
`$this->crud->addField([
            'label' => 'Categoria',
            'type' => 'select',
            'name' => 'categoria_id',
            'entity' => 'categoria',
            'attribute' => 'categoria_nome',
            'model' => 'App\Models\Categoria',
            'subfields' => null
]);`

One solution that could be applied in the source code is to improve the verification at "Library/CrudPanel/Traits/Update.php" on line 170. Change this:

`if ($field['subfields'])`

to:
`if (isset($field['subfields']))`

That way the existence of the array key is verified correctly and the error is avoided. 

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 
Yes.

### Backpack, Laravel, PHP, DB version
When I run ```php artisan backpack:version``` the output is:
`### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 29 2022 22:28:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.4@9239128cfb4d22afefb64060dfecf53e82987267

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v3.0.9
backpack/crud: 5.5.4
backpack/filemanager: 2.0.0
backpack/generators: 3.3.14
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.1
backpack/revise-operation: 1.0.12`

**Comment by phpfour** [comment]
Hey @EdersonRodrigues7

Thanks for the bug report and for sharing your solution. I have opened a PR https://github.com/Laravel-Backpack/CRUD/pull/5006 to push this fix. 

Let's move the conversation about this issue to the PR thread, if you test it please let us know if it fixes your issue 🙌

Thanks
