### ISSUE TITLE
[Bug] Trait method 'setupFetchOperationDefaults' will not be applied because it collides with 'FetchOperation'

### ISSUE THREAD

**Issue by srd2010** [Laravel-Backpack/CRUD#5003]
# Bug report

### What I did

Implemented FetchOperation from PRO Module into a controller and received the warning from the IDE:
_Trait method 'setupFetchOperationDefaults' will not be applied because it collides with 'FetchOperation'_

### What I expected to happen

Work out of the box.

### What happened

Error Message from IDE (PHPStorm)
Code does work, so it's more of an aesthetic issue.

### What I've already tried to fix it

Fix is simple by renaming the function  "**setupFetchOperationDefaults**" to "**setupFetchDefaults**", following the pattern of the other Operations.

### Is it a bug in the latest version of Backpack?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

backpack/crud: 5.5.4
backpack/pro: 1.6.3

**Comment by maurohmartinez** [comment]
Hi @srd2010!
Thank you for reporting this!

We are aware of this as it was done as a temporary workaround to avoid breaking changes. We will get to clean it up in one of our next upgrades.

I am going to keep it open until we get to do it.

Thanks again!
Cheers.

**Comment by pxpm** [comment]
Hey @srd2010 

I am doing some cleanup on some old issues. 

I am not able to reproduce your issue in the latest version. If the issue still persist for you please comment with some example code that I can follow to reproduce it consistently. 

Like @maurohmartinez said the `FetchOperation` is poorly named, but shouldn't pose issues to use. 

Thanks for the report 🙏
