### ISSUE TITLE
Select(2) for grouped options

### ISSUE THREAD

**Issue by samsebastian** [Laravel-Backpack/CRUD#502]
This is just something I thought might come up for others but didn't see a pre-made option available.

I often have options that apply to a model that need to be grouped to avoid confusion. 

For example, a `Contact` might `belongTo` a `Subcategory`, which in turn `belongTo`'s a `Category`. Frequently, these subcategories have similar names making it impossible to identify which category they represent.

A field I find myself using regularly is a grouped select2 list, which needs to query the top level model (ie `Category`), and then display it's relations (ie `Subcategory`) as the actual options in `<optgroup>`s..

I'm absolutely certain other's might have a better way to implement this but this was how I did it for reference:

**Setup:**
```php
	$this->crud->addField([
                         'name'  => 'subcategory_id', 
                         'label' => "Subcategory",
		         'type'  => 'select2_grouped', 
                         'entity' => 'subcategory', // Child model entity related to active model (belongsTo) (as per normal use)
                         'attribute' => 'title', // Attribute on child model to use as option label
		         'model' => 'App\Models\Category',  // Parent model
                         'group_label_attribute' => 'title',     // Attribute from parent model to use as optgroup label
                         'group_entity' => 'subcategories' // Child entity from perspective of parent model used as the list <options> (hasMany)
                     ]);
```

**View:**
```php
// -- /resoruces/views/vendor/backpack/crud/fields/select2_grouped.blade.php
// -- Beginning and end of standard select2 option clipped...
<select
        name="{{ $field['name'] }}"
        @include('crud::inc.field_attributes', ['default_class' =>  'form-control select2'])
        >

            @if ($entity_model::isColumnNullable($field['name']))
                <option value="">-</option>
            @endif
             
            @if (isset($field['model']) && isset($field['group_entity']))
                @foreach ($field['model']::with($field['group_entity'])->get() as $connected_entity_entry)
                    <optgroup label="{{ $connected_entity_entry->{$field['group_label_attribute']} }}">
                        @foreach ($connected_entity_entry->{$field['group_entity']} as $subconnected_entity_entry)
                            <option value="{{ $subconnected_entity_entry->getKey() }}"
                                @if ( ( old($field['name']) && old($field['name']) == $subconnected_entity_entry->getKey() ) || (isset($field['value']) && $subconnected_entity_entry->getKey()==$field['value']))
                                     selected
                                @endif
                            >{{ $subconnected_entity_entry->{$field['attribute']} }}</option>
                        @endforeach
                    </optgroup>
                @endforeach
            @endif
    </select>

```

**Example:**
![image](https://cloud.githubusercontent.com/assets/9647970/23329466/ad38ece2-fb84-11e6-8c83-507f3b88a78e.png)

**Comment by tabacitu** [comment]
Hi @samsebastian ,

Thanks a lot for sharing this with the community. I think it's a bit specific to include in the core package (I'm afraid the select2 field might get very bloated if we keep adding features), but I'd love to see others use this solution too.

What do you think about writing about it, for others to see? I think eithere of these:
- writing a [gist](https://gist.github.com/)
- writing an article on your blog, medium, or any other blog

would be helpful for the community. And I could link to it from the [backpackforlaravel blog](https://backpackforlaravel.com/articles) so people can easily find it and your blog / profile gets a new external link.

What do you think? I'd hate for this solution to die now that I'm closing the issue.

Cheers!

**Comment by drmmr763** [comment]
It doesn't look like there is a generic select2 grouped field type. Is that something that would be accepted if it was PRed?

**Comment by AbbyJanke** [comment]
Hi,

PRs are always welcome however as @tabacitu said it is kind of a specific niche field. You could always add it as a custom field to your application and define it as usual

**Comment by drmmr763** [comment]
I guess I'm really talking about better support for optgroup which is all select2 grouped options would be. Is that still considered niche? It's a standard HTML field type.

**Comment by tabacitu** [comment]
Hi @samsebastian , @drmmr763 , @AbbyJanke ,

On second thought, I think @drmmr763 makes a very good point. From that point of view, we _should_ provide support for ```optgroup``` - it _is_ part of the HTML standard.

I’ve just created two new fields types for this - ```select_grouped``` and ```select2_grouped```. Their definition is a little different from yours @samsebastian , since they first get the Category, then Elements for each category. But the result should be the same - options grouped by another entity.

Let me know what you think here: https://github.com/Laravel-Backpack/CRUD/pull/1688
Will be released as part of the 3.5 update - later this week.

Cheers! Thanks for the feedback.

**Comment by elenadanevska** [comment]
Hello, I want to implement the same, but with possibility to select multiple options (like select grouped and multiple in one). Any ideas how can I do that? I added select multiple instead of select on the code, but selected options are not shown.

**Comment by pxpm** [comment]
Hello @elenadanevska 

I'v just added: https://github.com/Laravel-Backpack/CRUD/issues/3660 

I think it's something usefull to have. I think the main differences in the select is that the name that needs to be: `selectName[]`, and select needs the `multiple` attribute defined. 

If you in the meanwhile code a solution for this and are willing to share with others, please open a Pull Request, and we will review it. 

Thanks,
Pedro
