### ISSUE TITLE
[v6][Bug] Remove extra files from project root

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5020]
@promatik made a good point, that we have too many files in the root. 
They look like bloat, and a lot of them could be removed in v6:

![CleanShot 2023-04-03 at 13 22 42](https://user-images.githubusercontent.com/1032474/229483456-939745ff-0406-480b-a3f1-6f919e4ebe28.png)

**Comment by promatik** [comment]
Maybe `CONDUCT.md` is also unnecessary, and we're no longer updating `CHANGELOG.md` 🤷‍♂️

Maybe `CONTRIBUTING.md` can also be removed, since we use .github issue template?

**Comment by tabacitu** [comment]
Removed `CHANGELOG.md` - it's the only one I think we _can_ remove at this point. I think it's clean enough now (in v6).
