### ISSUE TITLE
[v6] Release v6-beta (public release)

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5024]
To allow all team members to use `v6-alpha` we MUST:

- [x] 🔴 add v6.x docs to our website, with installation instructions
- [x] 🔴 make `backpack:install` command pull the proper v6 versions of 
    - [x] Generators 
    - [x] PRO
    - [x] DevTools
    - [x] EditableColumns 
- [x] 🔴 add L10 support to our Demo
- [x] 🔴 make installation command publish a `sidebar_content` file again
- [x] 🔴 change Backpack commands to publish things inside the current theme's `sidebar_content` (or alternatively, a common file in `ui` directory)
- [x] 🔴 drop support for Laravel 9 in CRUD

To offer a decent UX, close to beta, we SHOULD: 

- [ ] 🟡 ~~add `php artisan basset:internalize` as the last step in the installation command~~
- [x] 🟡 change all v6 docs pages to talk about v6, not v5

Not really related to alpha/beta, but shouldn't forget about doing:
- [ ] 🔵 remove Gravatar package dependency
- [ ] 🔵 if we keep Gravatar dependency, at least use Basset to cache the image so we don't make a call to gravatar servers on each pageload
- [x] 🔵 no longer publish error views
- [x] 🔵 move error views to themes instead of CRUD
- [ ] 🔵 do we really need the `root_disk_name` in `config/backpack/base.php`? can't we just create one without letting the devs change it? or even better... do we actually need that disk at all?! can't we remove it?

**Comment by sudeep2525** [comment]
hiiiiiiiii

**Comment by tabacitu** [comment]
Moved the Gravatar issue to #5145 so let's close this.
