### ISSUE TITLE
wysiwyg field 

### ISSUE THREAD

**Issue by Mahdi-Ba** [Laravel-Backpack/CRUD#503]
wysiwyg best field.
i think one option need to complete  this field.
i want to upload picture without give link address just upload on time and store

**Comment by indra1** [comment]
Can you please describe your issue better?

**Comment by AurelDragut** [comment]
wysiwyg is based on tinymce, you may need to check on tinymce's site about that.

@indra1, i think @Mahdi-Ba says that he needs a button for uploading images in the tinymce toolbars

**Comment by Mahdi-Ba** [comment]
Thats right @AurelDragut yes id like to have button for upload pic

**Comment by tabacitu** [comment]
Hi @Mahdi-Ba ,

Thanks already possible, with the CKeditor - elFinder integration. Check it out using these buttons - it allows the admin to upload images, AND crop/resize/rotate (if the admin right-clicks on the file).

![screen_shot_2017-03-06_at_16_37_51](https://cloud.githubusercontent.com/assets/1032474/23614446/977080ba-028b-11e7-9d18-d0646693a87b.png)
![screen_shot_2017-03-06_at_16_38_17](https://cloud.githubusercontent.com/assets/1032474/23614447/990778ac-028b-11e7-8059-1e75e669b8c8.png)


Cheers!

**Comment by Mahdi-Ba** [comment]
Hi @tabacitu 
Thank you so much
