### ISSUE TITLE
[Bug] Actions Dropdown changes back to line buttons after editable switch is toggled

### ISSUE THREAD

**Issue by siddharth-bhansali** [Laravel-Backpack/CRUD#5039]
# Bug report

### What I did

- Have a `editable_switch` column on the list page. 
`CRUD::column('allow_self_scheduling')->type('editable_switch');`
- Toggle it.

![image](https://user-images.githubusercontent.com/26364312/233270962-7d730e29-6738-4e24-b158-23dbc28f71bc.png)

### What I expected to happen

- The toggle should work fine.
- The actions dropdown should remain as it is.

### What happened

- The toggle works fine.
- The actions dropdown changes back to a line layout.

### What I've already tried to fix it

- Nothing.

### Is it a bug in the latest version of Backpack?

- Yes.

After I run ```composer update backpack/crud``` the bug... is it still there?

- Yes.

### Backpack, Laravel, PHP, DB version

- Backpack: `5.5.7`
- Laravel: `9.52.5`
- PHP: `8.2.5`
- DB: `PostGres13`

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.2.5 (cli) (built: Apr 14 2023 04:27:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.5@e14d28c0f9403630d13f308bb43f3d3cb73d6d67

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.7
backpack/editable-columns: 2.1.3
backpack/generators: 3.3.16
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.4
backpack/revise-operation: 1.0.12
```

**Comment by maurohmartinez** [comment]
Hi @siddharth-bhansali
Thank you for reporting this one.

Sorry for that, but you are right! The action column does change back to the old design after using the switch column.
I am on my way to fix it. This will remain open until then.

Once again, thanks!
Cheers.

**Comment by siddharth-bhansali** [comment]
@maurohmartinez Thanks for the quick reply, looking forward to the fix!
