### ISSUE TITLE
SaveAction case spelling error

### ISSUE THREAD

**Issue by samsebastian** [Laravel-Backpack/CRUD#504]
Doesn't appear to be causing any issues because it's the default case, but: 

Located in `Backpack\CRUD\app\Http\Controllers\CrudFeatures\SaveActions` inside `getSaveAction()` at `line 30`

```php
switch ($saveAction) {
  ...
  case 'save_and_black': // Should be 'save_and_back'
  default:
  ...
}
```

**Comment by tabacitu** [comment]
:-)) Nice spotting, @samsebastian .

Just fixed it on the dev branch, and will be available in the next patch release (in a few days).

Thanks, cheers!
