### ISSUE TITLE
Installation problem. Trying to fetch pro package from git not from backpackforlaravel repository

### ISSUE THREAD

**Issue by scotchegg** [Laravel-Backpack/CRUD#5044]
# Bug report

### What I did

Fresh installation from your instructions for the pro version

### What I expected to happen

Instalation without any errors

### What happened

WE keep getting the following errors

In Git.php line 457:

  Failed to execute git clone --mirror -- 'https://ghp...7Ej:x-oauth-basic@github.com/Laravel-Backpack/PRO.git' '/home/ubuntu/.cache/composer/vcs/git-github.com-Laravel-Backpack-PRO.git/'

  Cloning into bare repository '/home/ubuntu/.cache/composer/vcs/git-github.com-Laravel-Backpack-PRO.git'...
  remote: Repository not found.
  fatal: repository 'https://github.com/Laravel-Backpack/PRO.git/' not found

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

PHP 8.1 & 8.2 Laravel 9.5.2
When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @scotchegg thanks for raising the issue.

Please make sure you have followed the installation instructions either by running the command `php artisan backpack:require:pro` or manually. 

In any case the problem seems to be with the repository, it shouldn't be trying the github repository (as you don't have access), but our own repository (where you have access). 

Check if your `composer.json` have the following, if not please add it and try again `composer require backpack/pro`
```json
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.backpackforlaravel.com/"
        }
    ],
```

Also make sure you already set the backpack auth user/token as described in docs. `composer config http-basic.backpackforlaravel.com [your-token-username] [your-token-password]`

Let me know if you have any issues.

**Comment by tabacitu** [comment]
Hey @scotchegg ,

I see you haven't answered yet, so I assume you fixed the problem. 
Let us know if you still have it and we'll reopen.

Cheers!

**Comment by hirenvjoshi** [comment]
I am still getting following error. I followed all the instructions but still facing the issue.

In Git.php line 471:

  Failed to execute git clone --mirror -- https://ghp...AXf:x-oauth-basic@github.com/Laravel-Backpack/PRO.git C:/Users/username/AppData/Local/Composer/vcs/git-github.com-Laravel-Backpack-PRO.git/

  Cloning into bare repository 'C:/Users/username/AppData/Local/Composer/vcs/git-github.com-Laravel-Backpack-PRO.git'...
  remote: Repository not found.
  fatal: repository 'https://github.com/Laravel-Backpack/PRO.git/' not found

Kindly let me know what is the issue?

**Comment by tabacitu** [comment]
Hi @hirenvjoshi ,

Sounds like you are trying to download PRO from source (from our Github). You cannot do that, you don't have access to that. What you have access to is our repository - `repo.backpackforlaravel.com`. That's where Git should try to download from.

Please check if you are doing `prefer-source` anywhere in your GIT. Either in the command you run manually, or in your `composer.json`. To clarify, you shouldn't do `prefer-source`, you should do `prefer-dist`. You don't have access to the PRO source. 

If you still can't find the culprit please take a screenshot of your entire terminal when you run this, with the command you ran and your entire error stack - that might show us more information about the problem.

Cheers!

**Comment by hirenvjoshi** [comment]
![backpro-error](https://github.com/Laravel-Backpack/CRUD/assets/7780304/7e6a43a1-47b6-46b2-9c2a-273f0229a651)
Kindly find attached the error I am getting even after using perfer-dist.

**Comment by hirenvjoshi** [comment]
Here is my composer.josn file:

`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^8.1",
        "backpack/backupmanager": "*",
        "backpack/crud": "^5.0.0",
        "backpack/langfilemanager": "*",
        "backpack/logmanager": "^4.0",
        "backpack/pagemanager": "^3.2",
        "backpack/permissionmanager": "*",
        "backpack/pro": "*",
        "backpack/settings": "*",
        "barryvdh/laravel-debugbar": "3.6.1",
        "cviebrock/eloquent-sluggable": "*",
        "facade/ignition": "^2.17",
        "fideloper/proxy": "4.4.1",
        "fruitcake/laravel-cors": "2.0.4",
        "guzzlehttp/guzzle": "7.3.0",
        "intervention/image": "2.5.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "2.6.1",
        "laravel/ui": "3.3.0",
        "maatwebsite/excel": "*",
        "madnest/madzipper": "*"
    },
    "require-dev": {		        
        "fakerphp/faker": "1.15.0",
        "mockery/mockery": "1.4.3",
        "nunomaduro/collision": "5.5.0",
        "phpunit/phpunit": "9.5.7",
		"backpack/generators": "3.3.17",
		"laracasts/generators": "1.2.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall"         
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate"          
        ],
		"post-autoload-dump": [
			"Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
			"@php artisan package:discover --ansi"
		]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
	"repositories": [
        {
            "type": "composer",
            "url": "https://repo.backpackforlaravel.com/"
        }
    ]
}
`

I have also added credentials and token in auth.js

**Comment by tabacitu** [comment]
I see you're getting a 402 error before that - `Could not be downloaded (HTTP/2 402)`.

402 error means "payment required" so most likely what happened is that you do not have access to the latest updates. When that happens, and you try to install: our system sends you an email detailing that you should do `composer require backpack/pro:"1.x.y"` (exactly the latest version you have access to) or to buy backpack/pro again to get 12 more months of updates.

**Please check your email, you should have an email from our system** with the exact last version you have access to, and the code you should run. You can also look inside your account, and [in your Tokens page](https://backpackforlaravel.com/user/tokens) you can see when your token access has expired.

To be clear, you DO still have access to the version you purchased, and 12 months of updates and upgrades after that. You just don't have access to updates after that point, unless you purchase `backpack/pro` again.

Hope it helps.
Cheers!

**Comment by hirenvjoshi** [comment]
I am not getting the exact version information from my token page. Here is the screen shot of token page.

![tokenpage](https://github.com/Laravel-Backpack/CRUD/assets/7780304/caaef0b4-2daf-4c87-9855-7a7ac452b622)

**Comment by tabacitu** [comment]
Hi @hirenvjoshi ,

I've just added a new Tab there, "Packages", which will show you the last version you have access to:
![image](https://github.com/Laravel-Backpack/CRUD/assets/1032474/ef5ba059-2fac-4ec4-9051-57e8a93714d4)

Hope it helps!
