### ISSUE TITLE
[Bug] No hint path defined for [backpack].

### ISSUE THREAD

**Issue by bmangilli** [Laravel-Backpack/CRUD#5048]
# Bug report

### What I did

I created a laravel 10 project from the beginning, I did all the commands that were asked in this DOC: https://backpackforlaravel.com/docs/6.x/installation

### What I expected to happen

I was hoping it would correctly initialize the backpack

### What happened

The screen just looks like this:
![image](https://user-images.githubusercontent.com/70036534/234978808-a331becb-9e3d-4ae6-8e13-4eaf5b7ed92a.png)
In chrome console log it shows this:
![image](https://user-images.githubusercontent.com/70036534/234978953-985c4f4b-e2e1-4e80-98e2-b9cf02de925a.png)
When I go to any of the urls it is giving error:
![image](https://user-images.githubusercontent.com/70036534/234979065-d87e8fe6-d53c-4c34-9ec7-ec694ba00094.png)

### Is it a bug in the latest version of Backpack?

YES, 'v6.x-dev'.

After I run ```composer update backpack/crud``` the bug... is it still there?

YES.

### Backpack, Laravel, PHP, DB version

"backpack/crud": "v6.x-dev";
"php": "^8.1";
"laravel/framework": "^10.8";

DB: SQLite

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.0.26 (cli) (built: Nov 22 2022 18:35:38) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.26, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.26, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v10.9.0@35078125f61ef0b125edf524de934f108d4b47fd

### BACKPACK PACKAGE VERSIONS:
backpack/basset: dev-main
backpack/crud: v6.x-dev
backpack/theme-tabler: dev-main

OBS:

The version that is running on the localhost82 route is PHP 8.2
![image](https://user-images.githubusercontent.com/70036534/234980100-ecd341e1-2130-40ce-bb76-05dec9b3696a.png)

**Comment by karandatwani92** [comment]
Hey @bmangilli
Thanks for posting the issue. we have acknowledged the problem

As you know V6 is currently in alpha and has major changes towards assets. We will try to cover this as soon as possible.

**Comment by munjaldevelopment** [comment]
Hey @bmangilli 
I faced the same issue with Backpack 6 with Laravel 10. Please run `php artisan storage:link` to resolve this issue. 

Keep us posted if that works for you.
Cheers..

**Comment by karandatwani92** [comment]
@munjaldevelopment . I tried your way but didn't work for me.

**Comment by munjaldevelopment** [comment]
Hi @karandatwani92, I have tried it again today & it works for me. Please make sure `storage`, `public` & `bootstrap` folder have proper permissions. Also please confirm if `php artisan backpack:install` executed. Please try that & revert me if issue still persists.

Cheers..

**Comment by munjaldevelopment** [comment]
Hi @bmangilli, I have understood issue at your end. Your server name is NOT `localhost` but `localhost82`, so please change your .env `APP_URL` to `http://localhost82/project/ai-music-generator` & issue will be resolved. Please revert if issue still persists or you face challenge.

Cheers..

**Comment by karandatwani92** [comment]
Hi @bmangilli 

V6 is not ready for installation yet but we are close to release the alpha and will notify people when we do it, including a proper installation guide.

As of now use @munjaldevelopment guide as a workaround, It took two extra steps and yes it worked.
- Update `APP_URL` including port no. http://localhost:8000
- run `php artisan storage:link`
