### ISSUE TITLE
[Bug] Select2 Filter Does Not Trigger a Change

### ISSUE THREAD

**Issue by rbzachary** [Laravel-Backpack/CRUD#5054]
# Bug report

### What I did

Unselected select2 filter

### What I expected to happen

The selection clears out and triggers a change

### What happened

It doesn't

### What I've already tried to fix it

In the select2 filter, there is a line `$('#filter_'+filterKey).val(null)` that I changed to `$('#filter_'+filterKey).val(null).trigger('change');`

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Backpack Pro, yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.33 (cli) (built: Nov 19 2022 00:22:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.83.27@e1afe088b4ca613fb96dc57e6d8dbcb8cc2c6b49

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.4.16
backpack/filemanager: 1.1.7
backpack/pro: 1.6.0
backpack/generators: v3.3.7
```

**Comment by zachweix** [comment]
I don't think it really matters, but I was trying to look for this in my email until I realized I used my work email address instead of my personal email 😄

**Comment by promatik** [comment]
Hi @rbzachary!
You're right, I was able to test it and check that the clear button on the field is not triggering the change event.

I'm opening a PR to fix that issue https://github.com/Laravel-Backpack/PRO/pull/152 👌

Thank you for your report.
