### ISSUE TITLE
[Feature Request][v6] Move script file to CRUD for cross-theme use

### ISSUE THREAD

**Issue by maurohmartinez** [Laravel-Backpack/CRUD#5057]
At the moment, `tabler-theme` uses the following sequence: `layout.blade.php` (which could be vertical, horizontal, etc), includes `scripts.blade.php`, which injects scripts, includes js packages, sets everything for ajax calls used in tables, etc. And that blade file includes `theme_scripts.blade.php`, the one devs will actually work on.

We need to move `scripts.blade.php` to CRUD which will include everything **Backpack** needs, and ask devs to include it in their layouts when creating themes (we provide an example file, so that should help). That way it becomes _cross-theme_. The sequence would be: `layout.blade.php` created by devs in their themes includes `scripts.blade.php` from **CRUD**, and then their `theme_scripts.blade.php`, with all the js for their themes.

**Comment by tabacitu** [comment]
I've just added the ability for CRUD to add blade files that are cross-theme... but theme-overridable. See https://github.com/Laravel-Backpack/CRUD/pull/5061

So what I propose is that:
- to CRUD, we add `resources/views/inc/scripts.blade.php`;
- in the themes, we load that file from CRUD, by doing `@include(backpack_view('inc.scripts'))`, like [here](https://github.com/Laravel-Backpack/theme-tabler/blob/main/resources/views/inc/sidebar_content.blade.php);

Would that work @maurohmartinez ?

**Comment by maurohmartinez** [comment]
> Would that work @maurohmartinez ?

Yes, that should work @tabacitu 
How can I test this? Let me know how I can continue it and finish it implementing it.
Thanks.

**Comment by maurohmartinez** [comment]
One more thing to consider from our discussion @tabacitu 

Now we load styles and scripts using `backpack_theme_config('styles/scrips')`, but while doing so, we skip values declared in config `ui.styles/scripts`.

We need to think how to address this. Are we going to load both `ui.styles/scripts` and the `current_theme.styles/scripts`?

**Comment by tabacitu** [comment]
It should probably be:

```php
// instead of
@include(backpack_view('inc.scripts'))
// we do
@include('crud::inc.scripts')
```

**Comment by maurohmartinez** [comment]
@tabacitu this one is done in:

- [crud](https://github.com/Laravel-Backpack/CRUD/pull/5075)
and...
- [theme-coreuiv2](https://github.com/Laravel-Backpack/theme-coreuiv2/pull/7)
- [theme-coreuiv4](https://github.com/Laravel-Backpack/theme-coreuiv4/pull/9)
- [theme-tabler](https://github.com/Laravel-Backpack/theme-tabler/pull/46)

**Comment by tabacitu** [comment]
Awesome! Thanks @maurohmartinez . Heads-up, I've moved the general `scripts` and `styles` files from `resources/views/crud/inc` to `resources/views/ui/inc`. I think it makes more sense there because:
- the files aren't really CRUD-specific, they're about the UI;
- that way each file can individually override that file, if needed;

I'll reply to each individual PR with inline comments.

**Comment by tabacitu** [comment]
Closing in favor of all PRs listed above.
