### ISSUE TITLE
[Feature Request][v6] Customizable CSS classes for tables

### ISSUE THREAD

**Issue by maurohmartinez** [Laravel-Backpack/CRUD#5058]
# Feature Request

### Backpack themes compatible with tables

V6 introduces themes to Backpack... yahoo! But we have to improve the way it works for tables. Here is why...

Most likely the theme a dev is implementing uses certain classes on its tables, and at the moment, this is not possible to implement since our Show operation uses its own table classes. In short, it's not theme-compatible unless devs duplicate the List blade... which is, UGLY.

@tabacitu says: Hmmm this is a difficult one. Because the more we change is this [Show] operation… the more difficult it would be for people to upgrade. But I guess we can make some small changes. Is it just one place where themes would need to add their own classes? In that case, we could add that one place to the config file, as “tableClasses” or something like that.

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/pull/5063 for CRUD and https://github.com/Laravel-Backpack/theme-tabler/pull/38 for theme-tabler. We should also consider adding those configs to theme-coreuiv4 and theme-coreuiv2 if it makes sense there.
