### ISSUE TITLE
Crud issue?

### ISSUE THREAD

**Issue by PolywickStudio** [Laravel-Backpack/CRUD#506]

**Comment by PolywickStudio** [comment]
[  // Select
   'label' => "Category",
   'type' => 'select',
   'name' => 'category_id', // the db column for the foreign key
   'entity' => 'category', // the method that defines the relationship in your Model
   'attribute' => 'name', // foreign key attribute that is shown to user
   'model' => "App\Models\Tag" // foreign key model
]

When using this,
https://laravel-backpack.readme.io/docs/crud-fields


Why doesn't the ID that matches the database become selected?

**Comment by tabacitu** [comment]
Hi @PolywickStudio . 

If the name is category_id, I think the model should be App\Models\Category, not Tag.
Maybe that's your problem.

Cheers!
