### ISSUE TITLE
[Bug] lineButtonsAsDropdown is not working in list.php config file

### ISSUE THREAD

**Issue by ioanandrei** [Laravel-Backpack/CRUD#5067]
# Bug report

### What I did

I want to use the new "lineButtonsAsDropdown" setting in all my CRUDs so I added this to my `config/backpack/operations/list.php` file: `'lineButtonsAsDropdown '  => true,`.
If I go CRUD by CRUD and I add `CRUD::setOperationSetting('lineButtonsAsDropdown', true)` to each list operation it will work, but I would love to have it globally declared.

### What I expected to happen
I expected to have the list actions in a dropdown, not inline.

### What happened
I don't have the list actions in a dropdown.

### What I've already tried to fix it
---

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? - Yes, I just updated my backpack version.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
backpack/crud: 5.6.0
backpack/generators: 3.3.16
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.4
backpack/revise-operation: 1.0.12

**Comment by pxpm** [comment]
Hello @ioanandrei 

I've just confirmed and it's working as expected. Did you try `php artisan config:clear` ?

**Comment by ioanandrei** [comment]
Hi @pxpm 
Yes, I tried. No changes.
This is my `config/backpack/operations/list.php` file:

```php
<?php

/**
 * Configurations for Backpack's ListOperation.
 *
 * @see https://backpackforlaravel.com/docs/crud-operation-list
 */

return [
    // Define the size/looks of the content div for all CRUDs
    // To override per view use $this->crud->setListContentClass('class-string')
    'contentClass'    => 'col-md-12',

    // enable the datatables-responsive plugin, which hides columns if they don't fit?
    // if not, a horizontal scrollbar will be shown instead
    'responsiveTable' => true,

    // stores pagination and filters in localStorage for two hours
    // whenever the user tries to see that page, backpack loads the previous pagination and filtration
    'persistentTable' => true,

    // show search bar in the top-right corner?
    'searchableTable' => true,

    // the time the table will be persisted in minutes
    // after this the table info is cleared from localStorage.
    // use false to never force localStorage clear. (default)
    // keep in mind: User can clear their localStorage whenever they want.

    'persistentTableDuration' => false,

    // How many items should be shown by default by the Datatable?
    // This value can be overwritten on a specific CRUD by calling
    // $this->crud->setDefaultPageLength(50);
    'defaultPageLength'       => 10,

    // A 1D array of options which will be used for both the displayed option and the value, or
    // A 2D array in which the first array is used to define the value options and the second array the displayed options
    // If a 2D array is used, strings in the right hand array will be automatically run through trans()
    'pageLengthMenu'          => [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'backpack::crud.all']],

    // How important is it for the action buttons to be visible?
    // - 0 - most important
    // - 1 - as important as bulk buttons
    // - 2-3 - more important than the rest of the columns
    // - 4 - less important than most columns
    'actionsColumnPriority'   => 1,

    // Show a "Reset" button next to the List operation subheading
    // (Showing 1 to 25 of 9999 entries. Reset)
    // that allows the user to erase local storage for that datatable,
    // thus clearing any searching, filtering or pagination that has been
    // remembered and persisted using persistentTable
    'resetButton'             => true,

    // The query operator that is used to search on the table.
    // If you are using PostgreSQL you might want to change
    // to `ilike` for case-insensitive search
    'searchOperator'          => 'like',

    // Display the `Showing X of XX entries (filtered  from X entries)`?
    // Setting this to false will improve performance on big datasets.
    'showEntryCount'          => true,

    // Display the action buttons in a dropdown
    'lineButtonsAsDropdown '  => true,
];
```

Am I missing something? :-s

**Comment by pxpm** [comment]
Hey @ioanandrei I've just tested this again and it's working as expected.

I copied your config file from your reply and found the issue.

You have written `'lineButtonsAsDropdown '` (space at the end)  instead of `'lineButtonsAsDropdown'` (no space at the end).

I am going to close as I am sure (99,9%) this is properly working.

Please let me know if I am the one missing something, and I will re-open. Sometimes it happens 🙃 

Cheers

**Comment by adrienne** [comment]
@tabacitu - this isn't working for me either, and i do not have a space in the setting. It doesn't work for me even if I set it on the specific controller with `CRUD::setOperationSetting('lineButtonsAsDropdown', true);`

**Comment by adrienne** [comment]
Never mind, this was because I had a messed up override file. It's fine now.
