### ISSUE TITLE
Updating Laravel 9->10 and error states that backpack CRUD is not supported by L10

### ISSUE THREAD

**Issue by eberteogam** [Laravel-Backpack/CRUD#5069]
My composer.json:
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0|^8.1",
        "backpack/crud": "^5.6.0",
        "backpack/generators": "^3.3.16",
        "backpack/logmanager": "^4.0.10",
        "doctrine/dbal": "^3.6.2",
        "fideloper/proxy": "^4.4.2",
        "guzzlehttp/guzzle": "^7.5.1",
        "jamesmills/laravel-timezone": "^1.13.0",
        "lab404/laravel-impersonate": "^1.7.4",
        "laravel/framework": "^9.52.7",
        "laravel/sanctum": "^3.2.5",
        "laravel/tinker": "^2.8.1",
        "mckenziearts/laravel-notify": "^2.4",
        "phpoffice/phpword": "^0.18.3",
        "venturecraft/revisionable": "1.*"
    },
    "require-dev": {
        "spatie/laravel-ignition": "^1.6.4",
        "fakerphp/faker": "^1.21.0",
        "laracasts/generators": "^2.0.2",
        "laravel/breeze": "^1.19.2",
        "laravel/sail": "^1.22.0",
        "mockery/mockery": "^1.5.1",
        "nunomaduro/collision": "^6.4.0",
        "phpunit/phpunit": "^9.6.7"
    },
    "config": {
        "cache-dir": "/home/initxcso/proactiveadvisor.danfs.co/cache",
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files" : [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

If I change :
"laravel/framework": "^9.0",
"spatie/laravel-ignition": "^1.0",
to
"laravel/framework": "^10.0",
"spatie/laravel-ignition": "^2.0",

I got all error coming from  backpack/crud

  Problem 1
    - backpack/crud[5.0.0, ..., 5.3.13] require laravel/framework ^9.0|^8.26 -> found laravel/framework[v8.26.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).
    - backpack/crud[5.4.0, ..., 5.4.16] require laravel/framework ^9.0|^8.69 -> found laravel/framework[v8.69.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).
    - illuminate/contracts[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.1.10) does not satisfy that requirement.
    - illuminate/contracts[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.10) does not satisfy that requirement.
    - illuminate/contracts[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.10) does not satisfy that requirement.
    - illuminate/contracts[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.10) does not satisfy that requirement.
    - Conclusion: don't install fideloper/proxy 4.4.2 (conflict analysis result)
    - Root composer.json requires backpack/crud ^5.0 -> satisfiable by backpack/crud[5.0.0, ..., 5.6.0].
    - Conclusion: don't install laravel/framework v10.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.1.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.3.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.6.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.7.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.9.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v10.10.0 (conflict analysis result)
    - Root composer.json requires fideloper/proxy ^4.4 -> satisfiable by fideloper/proxy[4.4.0, 4.4.1, 4.4.2].
    - fideloper/proxy 4.4.0 requires illuminate/contracts ^5.0|^6.0|^7.0|^8.0 -> satisfiable by illuminate/contracts[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/contracts[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev], laravel/framework[v10.0.0, ..., 10.x-dev]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - backpack/crud[5.5.0, ..., 5.6.0] require laravel/framework ^10.0|^9.0|^8.69 -> satisfiable by laravel/framework[v10.0.0, ..., 10.x-dev].
    - Conclusion: don't install laravel/framework v10.0.0 (conflict analysis result)

I would appreciate any advice or what I'm doing wrong. Can't figure it out. I have tried deleting my vendor and composer.lock unfortunately haven't succeed in neither way, this might be a bug

**Comment by jorgetwgroup** [comment]
Hi @eberteogam 

Im using Laravel 10, with Backpack 5 and PHP 8.1 (is mandatory for Laravel 10 have php 8.1)

Here is my composer versions:

"require": {
        "php": "^8.1",
        "laravel/framework": "^10.0",
        "backpack/crud": "^5.5",
        "backpack/logmanager": "^4.0",
        "backpack/settings": "^3.0",
        "backpack/permissionmanager": "^6.0",
        "spatie/laravel-translatable": "^6.0",
        "laravel/tinker": "^2.1",
        "spatie/laravel-ignition": "^2.0",
        "intervention/image": "^2.3",
        "consoletvs/charts": "6.*",
        "laravel/legacy-factories": "^1.0",
        "backpack/filemanager": "^2.0",
        "backpack/backupmanager": "^3.0",
        "backpack/editable-columns": "^2.0",
        "backpack/pro": "^1.6",
        "backpack/newscrud": "^4.0",
        "backpack/menucrud": "^3.0",
        "backpack/revise-operation": "^1.0",
        "mews/purifier": "dev-master"

    },
    "require-dev": {
        "fakerphp/faker": "~1.4",
        "mockery/mockery": "1.5.*",
        "phpunit/phpunit" : "^10.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "^5.0.2|3.0.*|2.8.*",
        "backpack/generators": "^3.1",
        "barryvdh/laravel-debugbar": "^3.2"
    },
    
    Let me know if you try a composer install or composer update, but first try to change your composer versions with the one i show you.

Cheers.

**Comment by eberteogam** [comment]
@jorgetwgroup I realized the main issue was coming from "fideloper/proxy" since L8->L9. Composer remove fideloper/proxy is mandatory. Attaching doc if anyone encounters same issue:
 https://laravel.com/docs/9.x/upgrade#the-assert-deleted-method
 Your json helped me a lot to get a better idea, appreciate the help.
