### ISSUE TITLE
Filter select2_ajax_multiple

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/CRUD#5077]
I have a relationship that 1 reservation has n dockets. 1-n relationship.
In the list view i want a filter that the user selects multiple reservations and lists all dockets of that reservations.

Im actually using select2_multiple

![image](https://github.com/Laravel-Backpack/CRUD/assets/8792209/337889b8-7652-4f80-84e7-78d65f2a66f8)

But the problem is that there are lots of reservations and they are loaded all thogether. 
![image](https://github.com/Laravel-Backpack/CRUD/assets/8792209/6919368c-a0c4-4fed-a033-efd87d86009e)

I need something like the select2_ajax but with multiple selection.
Its there a way to achieve this?

**Comment by tabacitu** [comment]
Hi @aberaldo ,

Yes, you can use [the `select2_from_ajax_multiple` field](https://backpackforlaravel.com/docs/5.x/crud-fields#select2_from_ajax_multiple-pro), that does exactly that. 

Hot tip though - in Backpack v5, it's much easier to use [the `relationship` field](https://backpackforlaravel.com/docs/5.x/crud-fields#relationship-pro) for all relationships. Then if you want them to load options with AJAX you:
- define `'ajax' => true,` on the field
- add this to your CrudController:

```php
    use \Backpack\CRUD\app\Http\Controllers\Operations\FetchOperation;

    public function fetchCategory()
    {
        return $this->fetch(\App\Models\Category::class);
    }
```

I find that's much easier than creating a route and Controller to return the results to `select2_from_ajax` or `select2_from_ajax_multiple`.

Hope it helps.
Cheers!

**Comment by aberaldo** [comment]
Hello @tabacitu yes i know that but im talking about filters no fields.
Im using filter [select2_multiple filter](https://backpackforlaravel.com/docs/5.x/crud-filters#select2_multiple-1) but i dont know how to implement that with ajax. 

All options of the filter are loaded when the page is loaded making it busy. I need a multiple select filter with ajax.
How can i do thtat?

Thanks!

**Comment by aberaldo** [comment]
> OOOOHHH! You're talking about FILTERS, that's right! I've just investigated and indeed, we seem to be missing the `multiple` option in the `select2_ajax` filter. I've just created https://github.com/Laravel-Backpack/PRO/pull/156 that adds that, and passed it to Pedro for testing, review and merge. It will probably be done and merge by next week. Note that you can't see that thread because the repo is closed-source, but we're on it, and will brief you here when done.
> 
> Thanks again @aberaldo !

Excellent @tabacitu let me know!!. 

Thanks

**Comment by aberaldo** [comment]
@tabacitu is there any news about this?

**Comment by tabacitu** [comment]
@aberaldo turns out it isn't as easy as I assumed 🤦‍♂️

<img width="990" alt="CleanShot 2023-06-05 at 18 38 34@2x" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/aed387a4-4db5-42e4-9657-806f1fab1cd1">

We're postponing this until after the v6 launch (1st of July 2023), sorry. Right now we're focusing on fixing the bugs there so we can launch, adding a feature to v5 would be a big distraction.

Totally agree to doing it. But we'll do it in July. 
Thank you for understanding 🙏

**Comment by aberaldo** [comment]
Hello @tabacitu Is there any progress on this?
