### ISSUE TITLE
Simple input textbox filter

### ISSUE THREAD

**Issue by ajamandre** [Laravel-Backpack/CRUD#508]
how do you filter with a simple textbox with a "like '%string%'" addClause ?

**Comment by NBZ4live** [comment]
Here is a gist with a simple text filter: https://gist.github.com/NBZ4live/a528a745b1b97135aec0ad8cb43f6ba7
Could require some more styling, but should work.

**Comment by tabacitu** [comment]
Hi guys,

I do think a text filter is necessary, and I think @NBZ4live 's gist is a good starting point. I haven't been able to get it working, though:
<img width="1440" alt="screen shot 2017-09-04 at 12 07 36" src="https://user-images.githubusercontent.com/1032474/30019587-ca2f040a-9169-11e7-8fc4-034c95586ea5.png">

So I created another one in this PR (https://github.com/Laravel-Backpack/CRUD/pull/922), which I'll merge shortly.

Cheers!
