### ISSUE TITLE
[Bug]  Getting Error on Create / Edit User

### ISSUE THREAD

**Issue by munjaldevelopment** [Laravel-Backpack/CRUD#5094]
# Bug report

### What I did

Editing / Creating New User

### What I expected to happen

User form Should Open

### What happened

Getting Error `(strpos(): Argument #1 ($haystack) must be of type string, array given)`

### What I've already tried to fix it

Checked Controller file & field

### Is it a bug in the latest version of Backpack?

Yes

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
10.13.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v4.0.2
backpack/basset: 0.15.0
backpack/crud: v6.x-dev
backpack/editable-columns: 2.1.4
backpack/filemanager: 2.0.1
backpack/generators: v6.x-dev
backpack/logmanager: v4.0.10
backpack/menucrud: v3.0.1
backpack/newscrud: 4.0.9
backpack/pagemanager: 3.0.12
backpack/permissionmanager: 6.0.16
backpack/pro: v6.x-dev
backpack/revise-operation: 1.0.12
backpack/settings: 3.0.16
backpack/theme-coreuiv2: dev-main
backpack/theme-coreuiv4: dev-main
backpack/theme-tabler: dev-main

**Comment by munjaldevelopment** [comment]
Please find attached image

![image](https://github.com/Laravel-Backpack/CRUD/assets/14837352/8578214e-2490-43dc-b03d-5e520bbf855a)

As I debug more, I found that error on "role / permission" field as that field name is `['roles', 'permissions']` which is NOT string in column name..

**Comment by pxpm** [comment]
@munjaldevelopment I think it's because you are trying to use an array as the field name. 

We removed arrayed names, so for example for the date_range, that previously was: `name => [start_date,end_date]` it now becomes `name => start_date,end_date` (a comma separated string).

Can you check if you are not using arrayed field names ? 

Cheers

**Comment by munjaldevelopment** [comment]
Thanks @pxpm, After change name to `role,permission` it works for me.

I have checked on `permission manager package` official file, it show array 

`https://github.com/Laravel-Backpack/PermissionManager/blob/main/src/app/Http/Controllers/UserCrudController.php`

![image](https://github.com/Laravel-Backpack/CRUD/assets/14837352/0defea14-9f2f-4226-a428-8ddba543b417)

I guess it will be resolved on next `composer update`. 

Anyway, Thanks for the help @pxpm  it's sorted now.

**Comment by pxpm** [comment]
Also there is the v6 branch for permission manager: https://github.com/Laravel-Backpack/PermissionManager/pull/326 that has that change already.

To get it you probably need to add to your composer: `"minimum-stability": "dev",`

Cheers
