### ISSUE TITLE
[V6][Bug] Incorrect info in V6 dashboard "Getting Started" panel

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/CRUD#5098]
# Bug report

I'm just testing a fresh install of Backpack v6 and noticed the dashboard docs for the getting started panel are incorrect.

In panel 4 - "Hide this notice", it says "Go to your config/backpack/base.php and change show_getting_started to false."
This is incorrect as that option is now in ui.php

Cheers

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.12-1ubuntu4 (cli) (built: Feb 22 2023 19:48:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12-1ubuntu4, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.13.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 0.15.0
backpack/crud: v6.x-dev
backpack/generators: v6.x-dev
backpack/pro: v6.x-dev
backpack/theme-tabler: dev-main

**Comment by karandatwani92** [comment]
@fronbow Thanks for reporting the issue and putting our attention there. Yes, I had noticed that too but forgot to report it.
We will correct this. Thanks again. Cheers

**Comment by tabacitu** [comment]
Corrected! Thank you @fronbow !
