### ISSUE TITLE
Tab Advanced Features

### ISSUE THREAD

**Issue by Mahdi-Ba** [Laravel-Backpack/CRUD#510]
In my project laravel verision is  5.3.* and crud is upgrading 3.2 but i dont know why tab feature Don't working and don't show  any tab in view 
$this->crud->addField([
'name' => 'select_from_array',
'label' => "Select",
'type' => 'select2_from_array',
'options' => ['one' => 'One', 'two' => 'Two', 'three' => 'Three'],
'allows_null' => false,
'allows_multiple' => true,
'tab' => 'FirstTab'
]);

**Comment by tabacitu** [comment]
Hi @Mahdi-Ba ,

Just tested the tabs functionality again and can confirm it's working as expected. So it should be an implementation issue, not a bug. Have you managed to solve this in the meantime?

Cheers!
