### ISSUE TITLE
Install & test Backpack v6 - report all bugs and quirks we find

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5101]
I want everybody in the team to do this. **Dedicate at least 1h to installing Backpack v6, playing around and opening issues about what you find.** Once you're done, you can tick the box below and unassign yourself from the issue:

- [x] @tabacitu 
- [ ] @pxpm 
- [ ] @promatik 
- [ ] ~~@maurohmartinez~~
- [x] @karandatwani92 
- [ ] @jorgetwgroup 
- [x] @phpfour

**Comment by munjaldevelopment** [comment]
@tabacitu I will be happy to help as well if you needed for the sake of make Backpack V6 more stable. 

Let me know if you need..

**Comment by tabacitu** [comment]
Thank you for getting the ball rolling @munjaldevelopment !

I have a big note with every issue I've found. I'll copy-paste them below, then create issues out of each one that matters. I invite you guys to do the same, or add issues individually, whatever works for you.

Let's do this! 💪 Let's have all bugs we know of, reported, then next week meet to prioritize and distribute them.

----

1. I’ve followed the docs to install a clean v6, which instruct me to do “php artisan basset:internalize” first, then “php artisan backpack:install”. That’s done in order for the last command to be actionable, to show the final URL people should click and get started with their admin panel. But there’s a problem… because theme-tabler is only installed on the install command, that means the theme assets never got internalized. No bueno. Perhaps we should run “php artisan basset:internalize” as part of the v6 installation command… right before we show all the final output?
2. I’ve installed a fresh L10 + BPv6. First thing I wanted to do was change the layout from vertical to horizontal, but… I couldn’t easily do that, because the config file wasn’t published for me. Nor did I find a publish command on Github to quickly do that 😔 What I did in the end was to run “php artisan vendor:publish” and choose the Backpack\ThemeTabler\AddonServiceProvider, but that published 3 things - config (good), views (very bad) and assets (bad). We must publish the theme config file on installation, and provide docs for publishing each of the publishable things alone.
3. After having installed theme-tabler and publishing the config, I can no longer run artisan commands. If I try to do that, even `php artisan optimize:clear`, I get a big fat error in the terminal, “In UrlGenerator.php line 121: Illuminate\Routing\UrlGenerator::__construct(): Argument #2 ($request) must be of type Illuminate\Http\Request, null given, called in /Users/tabacitu/Code/bp-v6b-fresh-2023-06-12/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67” which I’ve tracked down to be because of the theme-tabler config file, specifically line 59 where we use the url() helper. I don’t think we can do that. And we can’t use the backpack_url() helper either because then we’d get “Call to undefined function backpack_url()”. So the only thing we CAN do, I think, is to turn the “urlsUsingOverLapEffect” config in theme-tabler.php from a list of FULL urls to a list of URLs that we will pass to `url()`. That should allow us to do the same thing, without triggering this error.
4. I’m following the instructions in the Getting Started widget, but the code blocks look broken. A good chunk of text is yellow on white which is unreadable. Switching to dark mode doesn’t fix the problem either - quite the contrary, then it’s obvious the code blocks don’t cater to dark mode at all 😔
5. After doing “php artisan backpack:crud user” my UserCrudController has some comments in setupListOperation() and setupCreateOperation() about how to use both the fluent and array syntax… I don’t think we should have those any more.
6. I’ve created a new Users CRUD, and I’m looking at the ListOperation in Theme-Tabler and… the table looks a bit odd:
- The first heading row is not the same color as the last one
- The table uses 3 shades of grey (first heading row, odd rows, even rows)
- The heading texts don’t really stand out; the text is greyed out and yes it’s capitalized but… it’s smaller than the table body text;
- The “items per page” select looks unstyled;
- The next and previous buttons in pagination look like < and > texts, instead of carets (icons);
- The search bar isn’t rounded and has no search icon so it’s not super obvious it’s a search bar;
- The search bar, when clicked, has a blue hue (not purple); this is true for all inputs on theme-tabler, and it bothers me; it doesn’t look intentional, but an oversight;
7. The getting started widget is instructing me in step 4 to change the config in base.php file but it should be ui.php file. Then I noticed this widget is provided by the theme… which… is wrong. It should be provided by CRUD. I see more files in theme-tabler views/inc that should be moved to CRUD - alerts, widgets… maybe… I don’t know…
8. Went do DevTools on the UserCRUD that I created, to see the files. And the code block highlighting is weird. The syntax highlighting doesn’t work (text is all white) and the text is blurry (either has a text-shadow or bad anti-aliasing).
9. In DevTools when looking at the files (/related-files/model) in the tabler theme, the top “back to all models” link is black, so it doesn’t look like a link at all.
10. In DevTools when using the Tabler theme, if I go to dark mode, in DevTools’ dark menu bar, the DevTools logo stays the same shade of yellow, but the Models, Migrations and Backpack menu items change to a purple.
11. In DevTools + Tabler + Dark Mode, the sidebar items /related-files/model have a blue hue instead of purple.
12. In Tabler dark mode, in CRUDs, on the List Operation, the Add button is blue instead of purple. Same with pagination links, they’re blue not purple.
13. In Tabler theme (both light and dark), when using the horizontal layout (but others should have the same), the top-right corner shows the user image and name. The user image is square with rounded corners right now… but I think circles are much better to represent user profile images. First, faces look good in circles because both faces and circles are round. Second, to me at least, if I see a circle image, I assume that’s a user profile pic, because that’s what social media has gotten me used to think. So having it as circle might be a small intuitive clue that the image is for the user.
14. When using the Tabler theme, perhaps we should default to using the horizontal layout, out-of-the-box. That’s what we want new projects to use, right? And “doubleTopBarInHorizontalLayouts” set to false by default.
15. In Tabler theme, when using the horizontal layout with “doubleTopBarInHorizontalLayouts” set to false, the menubar logo gets smaller and squished when it’s a text, so it’s no longer aligned with the menu items. I don’t know if I mind it being smaller, that might actually be better. But it should be aligned with the menu items (vertically), otherwise it looks like a bug.
16. In DevTools when using Tabler theme, when looking at the ListOperation in Models, some buttons don’t have any space between the button icon and the button text. Perhaps we should implement a margin for icons in buttons, across all buttons. See the Build All CRUDs top button and the See Files line button.

18. I’ve used DevTools to create a new operation, with a Line button that points to a Backpack form, and used it on the UserCrudController. When I click the line button, I get a big fat error Class “Assets” not found. https://flareapp.io/share/xmNr2l8m We have to update the stubs to work with Backpack v6.

**Comment by pxpm** [comment]
I will start my comment and then I will be editing it so that I can capture pictures, save them here and keep working on other stuff. 

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/e315d92f-548c-4cc3-9c14-2317f0d865c0)

**Comment by tabacitu** [comment]
I've created issues out of all of the above. Thanks everyone 🙏
