### ISSUE TITLE
[Bug] Undefined array key "datetime_picker_options" using date_picker field

### ISSUE THREAD

**Issue by emogeekface** [Laravel-Backpack/CRUD#5106]
# Bug report

### What I did

Used `date_picker` type field in crud controller, and then updated to latest versions of crud and pro.

### What I expected to happen

date_picker field would work correctly and page would load

### What happened

Error: `Undefined array key "datetime_picker_options"`

### What I've already tried to fix it

It looks like the code in `pro/resources/views/fields/date_picker.blade.php` has been changed to use `$field['date_picker_options']['language']` on line 14, but then still references `$field['datetime_picker_options']['language']` on line 53.

If you change either of these to match the other, then this resolves the issue.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.1
backpack/filemanager: 2.0.1
backpack/generators: v3.3.10
backpack/pagemanager: 3.0.12
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.5
backpack/settings: 3.0.16
```

**Comment by pxpm** [comment]
Thanks for the heads up @emogeekface ! 🙏 

Fixed, is as it should be: `date_picker_options`.

Will release a new version in a moment, sorry for the bad experience 🙏 

Cheers

**Comment by emogeekface** [comment]
@pxpm no probs, thanks for jumping on this so quickly 😄

**Comment by pxpm** [comment]
I was around, and I was the one responsible for the mess 🙃

Released PRO 1.6.6 that fixed this! 

Cheers

**Comment by emogeekface** [comment]
Hi @pxpm according to the changelog on Pro this has been added to 1.6.5 and not 1.6.6, which means when I run composer update it says there's nothing to update - sorry!

**Comment by pxpm** [comment]
Hey @emogeekface it's on 1.6.6

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/db47f7c7-f55a-4f2d-b7d7-9acf723e1c7d)

Our private repository should pick the change in a few moments and make that version available to the users. If the problem persists please let me know 🙏 

Cheers

**Comment by emogeekface** [comment]
@pxpm when I check here: https://backpackforlaravel.com/products/pro-for-unlimited-projects/CHANGELOG.md I see:

![pro-versioning](https://github.com/Laravel-Backpack/CRUD/assets/13798688/5ca3fd0e-2d99-45df-9d4e-6060d47ca1cd)

Is '[BUG] date picker language config key has wrong name' referencing something different?

When I run `composer update` I get:

 `Nothing to install, update or remove`

When I run `sail artisan backpack:version` I get:

```
backpack/crud: 5.6.1
backpack/filemanager: 2.0.1
backpack/generators: v3.3.10
backpack/pagemanager: 3.0.12
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.5
backpack/settings: 3.0.16
```

Apologies if I'm missing something, I can wait and see if it gets pulled through by tomorrow and let you know if not if you think I should be seeing 1.6.6

Thanks!

**Comment by pxpm** [comment]
You should definitely be seeing 1.6.6. 

We will check if there is some issue with the private repo. 

Thanks for the heads up 🙏

**Comment by emogeekface** [comment]
@pxpm have checked this morning and this is now working 🥳
