### ISSUE TITLE
[Bug] Extra margin found on V6 layout.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5108]
![Screenshot 2023-06-09 at 8 27 15 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/a15f6f5f-8445-4644-a5ff-05b3f1e60a47)

Need to find and remove the extra element causing a margin on the layout of V6.

**Comment by tabacitu** [comment]
Totally bothers me too. This issue is a duplicate of https://github.com/Laravel-Backpack/theme-tabler/issues/31 so let's move the conversation there.
