### ISSUE TITLE
[Bug] In Brand new installation with v6 the sidebar menu collapse function doesn't work

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#5112]
# Bug report

### What I did

I installed a new project with backpack V6 and the permission manager plugin, I added the sidebar menú items

```
<li class="nav-item nav-dropdown">
    <a class="nav-link nav-dropdown-toggle" href="#"><i class="nav-icon la la-users"></i> Authentication</a>
    <ul class="nav-dropdown-items">
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('user') }}"><i class="nav-icon la la-user"></i> <span>Users</span></a></li>
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('role') }}"><i class="nav-icon la la-id-badge"></i> <span>Roles</span></a></li>
        <li class="nav-item"><a class="nav-link" href="{{ backpack_url('permission') }}"><i class="nav-icon la la-key"></i> <span>Permissions</span></a></li>
    </ul>
</li>
```

### What I expected to happen

The menu should appear collapsed and be displayed with a click.

### What happened

The menu appear already opened

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/a795419d-5ee4-48a6-81c2-0ff4fc090f8e)

### PHP VERSION:
PHP 8.2.7 (cli) (built: Jun  8 2023 15:27:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.13.5.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 0.16.0
backpack/crud: v6.x-dev
backpack/devtools: v6.x-dev
backpack/editable-columns: v6.x-dev
backpack/generators: v6.x-dev
backpack/permissionmanager: v6.x-dev
backpack/pro: v6.x-dev
backpack/theme-tabler: dev-main

**Comment by pxpm** [comment]
Thanks for the heads up @miquelangeld 🙏 

I've sent a PR to update the docs, can you test if the updated docs are working as expected ? 

https://github.com/Laravel-Backpack/PermissionManager/pull/328

Going to close this, we will re-open if needed 🙏 

Cheers
