### ISSUE TITLE
[Bug] Loading state bar keeps going after everything is loaded.

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#5116]
I noticed this on the login page. 

Even after the page finish loading, the `loading bar` on top keeps going forever. 

![image](https://user-images.githubusercontent.com/7188159/234546957-27cb2f9e-c4e1-4b32-a1ed-6b30b277b630.png)

**Comment by tabacitu** [comment]
Fixed by removing pace.js in https://github.com/Laravel-Backpack/CRUD/pull/5115
