### ISSUE TITLE
Bug in creating database record with NN relationship 

### ISSUE THREAD

**Issue by splodgeco** [Laravel-Backpack/CRUD#512]
If using a NN relationship on create only (not update or both) the create will fail.

Issue with file 
`PanelTraits/Create.php`
Line 26
`$nn_relationships = array_pluck($this->getRelationFieldsWithPivot('update'), 'name');`

Should be 
`$nn_relationships = array_pluck($this->getRelationFieldsWithPivot('create'), 'name');`

Notice the change from **update** to **create** on the `getRelationFieldsWithPivot` method

**Comment by tabacitu** [comment]
Hi @splodgeco ,

I wasn't able to replicate your error, but I agree with you, it should definitely read CREATE fields, not UPDATE. So I've just pushed the fix on the ```dev``` branch. It will be available to you via ```composer update``` today or tomorrow, at the next patch release.

Thanks for the contribution and sorry if it caused you any stress :-)

Cheers!

**Comment by splodgeco** [comment]
Hi @tabacitu 

Thanks for the fix. It didn't cause any stress, just a few hours of debugging trying to find out why it wasn't working in one situation!

Glad I can help.
