### ISSUE TITLE
[Bug] No hint path defined for [backpack].

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5126]
# Bug report

### What I did

Tried to use a view, but it was missing from both UI and the theme.

### What I expected to happen

Show an error message that says exactly that.

### What happened

<img width="1280" alt="CleanShot 2023-06-16 at 14 02 09@2x" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/ed6c3b92-327d-42a8-a76b-8c30e861dbe6">

My error message reads `No hint path defined for [backpack].` which doesn't really tell me anything. I have to dig into the error stack - https://flareapp.io/share/KPgzRVgm - to understand what went wrong.

### What I've already tried to fix it

Nothing. But we probably should, because this error will happen a lot now that we have themes.

### Is it a bug in the latest version of Backpack?

In Backpack v6

**Comment by pxpm** [comment]
This is related with the errors issue we are fixing: https://github.com/Laravel-Backpack/CRUD/pull/5125
