### ISSUE TITLE
[Bug] Backpack Assets 404 if APP_URL is set and doesn't match to actual URL 

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5127]
Every laravel installation comes with APP_URL=http://localhost config in env.
Unfortunately, Backpackv6 is unable to load assets if APP_URL is there and it's not the actual address.

**ISSUE:**
Assets are dependent on APP_URL

#### 1) Default case: Doesn't WORKS
With the default APP_URL=http://localhost and executing `php artisan serve`;
The application will run on `http://localhost:8000` and this wouldn't load assets.

#### 4) SAME ON LARAVEL VALET
if APP_URL is there and it doesn't match the link. It's **404**

![Screenshot 2023-06-17 at 8 14 14 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/3cc9c821-e84d-4106-9a1d-dd2a9f8ae3c6)

**Comment by soymgomez** [comment]
Hello,

we have just upgraded a project to version 6 and the same thing happened to us. Locally we use Laravel Sail and we don't use the default port(:80) but we use a custom one.

It seems that Basset ignores the environment variable:  `APP_PORT`

We temporarily solved the problem in the same way you did.

Best regards

**Comment by tabacitu** [comment]
This is rapidly becoming a MUST. 

@promatik any idea how we can fix this? Does `@basset()` absolutely need APP_URL... when Laravel's `asset()` does not?

**Comment by karandatwani92** [comment]
This also causes👇https://github.com/Laravel-Backpack/CRUD/issues/5180#issuecomment-1621304594
![Screenshot 2023-07-21 at 1 50 13 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/95906e20-f633-4b64-9931-709fa57c2a55)

**Comment by stephanus-tantiono** [comment]
also happend to me, but set APP_URL not fix my issue

**Comment by karandatwani92** [comment]
@stephanus-tantiono remove `APP_URL` from .env as a workaround for now. It will work

**Comment by stephanus-tantiono** [comment]
> @stephanus-tantiono remove `APP_URL` from .env as a workaround for now. It will work

also not work for me,still got the  419

**Comment by promatik** [comment]
Hey everyone, pushed a fix for this one here; https://github.com/Laravel-Backpack/basset/pull/68
