### ISSUE TITLE
Show actual URL to the user after installation.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5128]
![Screenshot 2023-06-09 at 8 19 31 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/23a62128-a347-45e1-b101-19cf8d70e150)

After installation, it always says goto  `http://localhost/admin`

Shouldn't we display the actual URL?
Example: `APP_URL(value)+'/admin'` OR include the port no. to make it work 100% if clicked by user?

**Comment by tabacitu** [comment]
This is probably because you didn't have your ENV's variable properly configured. We can only get the URL from there... if that is misconfigured... I don't think we can do anything to "guess" the URL.
