### ISSUE TITLE
[V6][Bug] Possible script widget not loading

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/CRUD#5132]
# Bug report

### What I did

Trying to get some JS CRUD API functionality working as on v5

### What I expected to happen

My scripts to work

### What happened

Nothing. I'm not even sure if the JS CRUD API is being loaded or if the actual widget is being loaded (putting some html comments in the published script.blade file doesn't yield any output in the page source.

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

In V6, yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.12-1ubuntu4 (cli) (built: Feb 22 2023 19:48:21) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12-1ubuntu4, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.13.5.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 0.16.0
backpack/crud: v6.x-dev
backpack/generators: v6.x-dev
backpack/permissionmanager: v6.x-dev
backpack/pro: v6.x-dev
backpack/theme-tabler: dev-main

Cheers

**Comment by fronbow** [comment]
Hi @pxpm thanks for that, so the js api is being loaded but it appears as though the script widget isn't being loaded. Still no mention of my html comment or a link to my script in the html source.
Is there a chance that widgets should be loading from a different place now? 
`php artisan backpack:widget --from=script` published the file to 
`resources/views/vendor/backpack/base/widgets`

**Comment by fronbow** [comment]
On further investigation I moved the widget to `resources/views/vendor/backpack/ui/widgets/script.blade.php` and the html comments show, but still no reference to my js script in the source, does bassett intervene in the view building process?

**Comment by fronbow** [comment]
Further inspection:
I dumped the path via the widget and got `http://ben10.test/js/admin/forms/client_assessments` so I tried to view the url and got the No hint path error as covered elsewhere?

**Comment by fronbow** [comment]
Cheers @pxpm, I published the widget so that I could see what was happening and whether the widget was getting loaded!

Looking in Chrome DevTools I can't find any mention of my js script being loaded, so I'm wondering if there's a hidden "No hint path" error being thrown or something else?

:)

**Comment by pxpm** [comment]
It may be some error yes, but not hidden I think. That `No hint path` error is being handled here https://github.com/Laravel-Backpack/CRUD/pull/5125, it's related to error views. I think we've come up with a solution we are happy to implement and maintain and should merge the fix in the next days. 

Back in the widget problem, you did the process mentioned in docs and the widget is not in your page ? Can you try with a different widget? Say `card` or something ?

Do you have "core" (list, create, update) blade files overwritten and maybe didn't added the `stacks` to where widgets get loaded ? 

Also since v6 was launched we changed the widgets from themes back to crud. Do you have everything updated ? In v6 you are working in a dev branch, is important to always get the latest updates with a `composer update`. 

Cheers

**Comment by fronbow** [comment]
When I set up my v6 test, I purposefully did it from scratch and just moved my classes, controllers, and custom field/column/widgets across - I didn't touch any of the core stuff as I want to be able to test that too!
Also, every morning when I get to my machine I do a composer update so I'm fresh for testing in my downtime ;)

I added a card widget to my page and it loaded okay, still no luck on my script appearing to load :( hopefully it will correct itself when #5125 appears, if not then I'll keep digging away at it!!

Cheers

**Comment by pxpm** [comment]
Do you have the widget `script` published on your `resources/` folder ? 

If it is, it should be in `resources/vendor/backpack/ui/widgets` the new widget directory https://backpackforlaravel.com/docs/6.x/upgrade-guide#step-19

What happens ? Your page loads but the script is not in the source of the page ? 

If no error is thrown #5125 will not fix it for sure. 

Let me try other route here. 

Are you rebuilding the asset cache after adding the script or using `BASSET_DEV_MODE=true` in your .env file ? If not, can you add it, and run `php artisan basset:clear` ?

Cheers

**Comment by fronbow** [comment]
If I try to load the js script with the url `http://ben10.test/resources/views/vendor/backpack/ui/widgets/script.blade.php` then I get the "No hint path" error.
Whereas if I load it in the setupCreateOperation with `Widget::add()->type('script')->content('/js/admin/forms/client_assessments.js?ver=1.1');` I can see the widget is loaded but still no mention of the script url anywhere in the source.

Just out of interest, in the upgrade guide it says something about running `php artisan basset:cache` which gives me an error 'command not defined'.

When I run `php artisan basset:clear` it tells says
`Clearing basset '/storage/app/public/basset'`
I think this might be wrong as this directory doesn't exist in either `/public/storage` or `/storage/app`

I am curious now if this is an error solely for me, or more devs?!


Cheers @pxpm

**Comment by fronbow** [comment]
Excellent, cheers for this, yes it's the version that throws it off

Cheers Sir :)

**Comment by tabacitu** [comment]
Fixed last week. Thanks @fronbow !
