### ISSUE TITLE
Can we remove the Gravatar dependency in v6?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5145]
In Backpack v5, we're using `creativeorange/gravatar` to show the admin's profile image, in the top-right corner. This is a good feature, because MOST people identify with their profile image - there are studies showing that alone makes the interface more pleasurable (seeing their face or familiar image).

However... there are a number of problems with using this package:
- (1) it makes a call to a third-party endpoint, on every pageload; so even though we have removed all CDNs, we still have one URL that pings 3rd parties;
- (2) this adds `creativeorange/gravatar` as a dependency for CRUD; we've had no issues with them so far, the package has been SUPER well maintained; every time there was a new Laravel version they were quick to add support; they did not introduce any bugs or breaking changes; but it's one dependency to our core package... that we can _probably_ do without;

So here's a crazy idea... What if we bring in [the `Gravatar.php` file](https://github.com/creativeorange/gravatar/blob/1.0/src/Gravatar.php) into Backpack? 👀 

That would allow us to:
- use Basset in it; Basset gets the profile image ONCE, then caches it, so we no longer do a 3rd party ping on each pageload (fixes problem no 1);
- remove the `creativeorange/gravatar` dependency;

It feel a little off doing this... but after all the whole package is just this one class. And rather than extending it... I think we get more benefit out of copy-pasting it...

What do you think @pxpm ? Do you think we should do this? Or am I missing something here?

**Comment by tabacitu** [comment]
Note that currently Gravatar is CRUD dependency. But it's not _actually_ used in CRUD. It's used in each theme individually, in the `menu_user_dropdown.blade.php` files. It is however mentioned (and the default) in `config/backpack/base.php` 🤦‍♂️

**Comment by pxpm** [comment]
Remove it completely is my opinion. 

Developer can easily add it if they want. We can have a tutorial for it. 

This is not something that CRUD should be responsible for. 

Even pinging only once (it will only work if you have internet connection) requires us to have the "css fallback" we have in place now. 

The thing is, if you want to install backpack on an **intranet** you can do a `php artisan basset:internalize` and move the stuff to the local server. 
After that there is no more internet connection, and basset is not able to internalize stuff that's generated dynamically (gravatar from user emails).
 
I think this is a feature very prone to fail, heavy to maintain (we spent already a couple (lot's) of hours) debugging/fixing/creating workarounds for this avatar stuff. 

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/0f9f20ce-41f9-4ee4-9ec7-abd174c18d95)

I say, **no mas**.

**Comment by tabacitu** [comment]
But but but... I like it... 😔 I like this feature 😔 I think it's good to see your face first thing when you login somewhere. So I don't think we should remove it entirely...

I've fixed problem no 1 in https://github.com/Laravel-Backpack/CRUD/pull/5151 - which was the MUST-DO here: no more browser calls to 3rd parties, thanks to Basset.

I think we should still consider removing the `creativeorange/gravatar` dependency... but right now that feel ichy. Plus we can always do that later, as a non-breaking change, if they don't maintain it or something.

So I say let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/5151
