### ISSUE TITLE
Edit fields on list view

### ISSUE THREAD

**Issue by ElabsConsulting** [Laravel-Backpack/CRUD#515]
Hi, 

It is possible to edit fields in the list view? If not witch could be the best aproach to have that functionallity?

Thanks

**Comment by MarcosBL** [comment]
Columns you mean ? https://laravel-backpack.readme.io/docs/crud-columns-types

**Comment by indra1** [comment]
Hi, 
You can create your own custom fields in resources/vies/vendor/backpack/crud/fields
If you want to edit things directly inside a column you can load a custom view. Backpack supports that.

**Comment by tabacitu** [comment]
Hi @ElabsConsulting ,

I think the guys (and gals) have answered your question, by directing you to the columns documentation, so I'll go ahead and close this issue. Also check out "[roll your own](https://laravel-backpack.readme.io/docs/crud-columns-types#section-roll-your-own)" - it will help you create custom columns.

Cheers!
