### ISSUE TITLE
Preserve list filter on edit a product

### ISSUE THREAD

**Issue by ElabsConsulting** [Laravel-Backpack/CRUD#516]
Hi,

There is an option to preserve the applied filters, when an item is edited and the user it's returned to the list?

Thanks

**Comment by MarcosBL** [comment]
Save the filters in the user session, and re-aply them on load of the list

**Comment by NBZ4live** [comment]
Hi,

+1.

Sometimes it is useful to have a filter that will be preserved on all actions and not only list and search without doing extra implementation in the controller logic.

For example if your filter changes the database connection or a table for sharding or any other reason, it would break on show or details row.

I would suggest to add an extra option to check if the filter logic should be preserved.

**Comment by lloy0076** [comment]
Closing in favour of #521.

**Comment by lloy0076** [comment]
Actually that may have been premature - if someone can see which one of these issues is the "one issue to fix them all" can they close the other ones?

**Comment by NBZ4live** [comment]
#521 is a pull request for solving this one

**Comment by tabacitu** [comment]
I don't think I understand the problem it's trying to solve, but I'm open to anything. Let's move the conversation to this PR #521 

Cheers!

**Comment by lloy0076** [comment]
@tabacitu - if you edit a product, and then use the default `save and back` button, you'll lose all your setup filters; which is somewhat annoying.
