### ISSUE TITLE
[Bug] Theme config files do not get published

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5166]
# Bug report

### What I did

Ran `php artisan backpack:require:theme-tabler`

### What I expected to happen

Tabler's config file to get published. Especially since one of the progress steps say exactly that.

### What happened

It said it published the config file. But it didn't.

### What I've already tried to fix it

Nothing yet. On a spree to launch.

---

Note - this functionality was added here - https://github.com/Laravel-Backpack/CRUD/pull/5153/files#diff-9e4c74723ee727155dedd6d0cf8a4c96a4964fe15736c207be98b3285e27e43cR84-R88 - I thought it was working but... I guess it's not? 🤷‍♂️

**Comment by realtebo** [comment]
Side question: where is `backpack:require:theme-tabler` documented at all?

**Comment by tabacitu** [comment]
> Suggest a workaround please.

@realtebo until this gets resolved you can do 
- `php artisan vendor:publish --tag="theme-tabler-config"` for Tabler
- `php artisan vendor:publish --tag="theme-coreuiv2-config"` for CoreUIv2
- `php artisan vendor:publish --tag="theme-coreuiv4-config"` for CoreUIv4

> Side question: where is backpack:require:theme-tabler documented at all?

It isn't 😀 Good catch. That was intentional - we might move these commands from CRUD to the ThemeServiceProvider. That way each theme basically has its own installation process. In case we do that, the command might change - so better not to document it for now. But the manual installation process for each theme is documented on each theme README - you can see it there.
