### ISSUE TITLE
[Bug] Why does v6 provide a Source Sans Pro CSS file?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5168]
I'm doing the final v6 review before launch and here's I've found we have this file in CRUD - https://github.com/Laravel-Backpack/CRUD/pull/4860/files#diff-b8497ece9029a90ddf503d37dc19006c79c9e5319d193354f82cdcd942b40ce3

Afaik:
- CoreUIv2 uses Source Sans Pro
- CoreUIv4 _might use_ Source Sans Pro
- Tabler uses Inter

But any way you take it... it shouldn't be CRUD providing the Source Sans Pro CSS file... it should be the theme that uses it... right?

**Comment by pxpm** [comment]
I could not replicate this issue. I couldn't find source sans pro in crud repository. 

Closing, re-open if needed.
