### ISSUE TITLE
[Bug] Class "PackageVersions\Versions" not found while upgrading from 5x to 6 - with Fix

### ISSUE THREAD

**Issue by FuviTeam** [Laravel-Backpack/CRUD#5170]
# Bug report

### What I did

Following the Upgrade guide. Then composer update

### What I expected to happen

Upate Backpack from 5x  to 6
Generating optimized autoload files

### What happened

Class "PackageVersions\Versions" not found

### What I've already tried to fix it

composer require ocramius/package-versions

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Runnig composer require ocramius/package-versions fixed it and i was able to install backpack

**Comment by pxpm** [comment]
Hello @FuviTeam 

thanks for the report 🙏 

We remove that dependency on backpack v6. https://github.com/Laravel-Backpack/CRUD/pull/5052https://github.com/Laravel-Backpack/CRUD/pull/5052 

You shouldn't be requiring it again. 

Can you provide me the error report ? Where did the error trigger ? 

Did we forget to remove it in some place, or we need to add some more info in the upgrade guide ? 

Cheers

**Comment by FuviTeam** [comment]
It happened when upgrading from v5 to V6, during "composer update". So maybe it's a rest of code of the V5 calling this missig package somewhere.

**Comment by pxpm** [comment]
Can you see in the error logs where is the error triggering ? 

I tried to search the code but didn't find any results, so I am guessing we may need to add some step **before** we tell users to ran `composer update`. 

Thanks for the response 🙏

**Comment by srd2010** [comment]
Hi,

this is connected to the this entry in 

**config/backpack/base.php**

https://github.com/Laravel-Backpack/CRUD/blob/1b67f8efdbaa48842e0d31995068b44b8fc5c66d/src/config/backpack/base.php#L171

**Comment by pxpm** [comment]
Thanks @srd2010

I've submitted https://github.com/Laravel-Backpack/docs/pull/451 from our interaction here. 

It will help someone in the future 100%! 

🙏 Cheers
