### ISSUE TITLE
[Bug] Editable Columns - Bulk Function Buttons not activating after editing

### ISSUE THREAD

**Issue by srd2010** [Laravel-Backpack/CRUD#5175]
# Bug report

### What I did

Edited a row and then selected the row (checkbox) for a bulk function to be called.

### What I expected to happen

Bulk Buttons should become active upon selection of at least one row (through checkbox)

### What happened

Bulk Buttons do not become active. 

### What I've already tried to fix it

This can be solved by reloading the page, which is not user friendly. 
Probably a matter of reapplying the trigger after editing.

### Is it a bug in the latest version of Backpack?

No, it already happened in prior versions. Just waited with the report to see if it was fixed with the new release.

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.17 (cli) (built: Mar 16 2023 14:38:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.0
backpack/devtools: 2.0.2
backpack/editable-columns: 3.0.0
backpack/generators: v4.0.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.4
backpack/theme-coreuiv2: 1.1.0
backpack/theme-tabler: 1.0.1

**Comment by pxpm** [comment]
Thanks for the report @srd2010 

I can confirm the bug is present, and I already submitted a PR to fix it, should be merged and tagged soon 🙏 

Sorry for the bad experience 😞 

Cheers

**Comment by karandatwani92** [comment]
OK TESTED. PR ready to merge
https://github.com/Laravel-Backpack/editable-columns/pull/83

**Comment by pxpm** [comment]
Fixed, merged and tagged.

Thanks @srd2010 🙏 you should be able to get the fix with a `composer update`.

Cheers
