### ISSUE TITLE
Customisable timestamp fields

### ISSUE THREAD

**Issue by Spodnet** [Laravel-Backpack/CRUD#518]
To ease migration the project I'm working on uses created and modified field names instead of created_at and modified_at fields.

In PanelTraits/Autoset.php getDbColumnNames, the fields are hard coded as created_at and modified_at:

`return array_values(array_diff($columns, [$this->model->getKeyName(), 'created_at', 'updated_at', 'deleted_at']));`

This can be changed to:

`return array_values(array_diff($columns, [$this->model->getKeyName(), $this->model::CREATED_AT, $this->model::UPDATED_AT, 'deleted_at']));`

This will allow users to define their own timestamp fields, rather than assuming the defaults which may not be the case

**Comment by indra1** [comment]
This is a very corner case. You could just overwrite that file in your project.

**Comment by Spodnet** [comment]
Do you mean overwrite AutoSet.php?

That would be very bad coding practice, there could be incompatibilities introduced if AutoSeet was changed in the future, or introduce maintenance overhead.

What I'm suggesting is that the code should use the defined constants that already exist rather than assuming the fields are called created_at and updated_at, the eloquent model allows you to redefine the fields, the AutoSet code should use the eloquent way of using the fields.

You could argue that like getKeyName() you should use getCreatedAtColumn() and getUpdatedAtColumn(), although as the constants are accessible to the model so either method would work.

**Comment by indra1** [comment]
You could overwrite just that method. Why use laravel if you don't keep the standard? 
I mean just use created_at and updated_at, so that the next developer that comes after you will find it easy to pick up where you left of and not  spend hours looking through the code. I get your point, but I don't think this is a priority for backpack. 
Just my 2 cents

**Comment by Spodnet** [comment]
It's a 15 second change, to keep within the eloquent standard, the standard method for finding what those fields are named, should be to call the methods or use the constant much the same as you do for primary key name, otherwise why not hard code 'id' which by your argument is "standard"

The next developer or other developers in the team, can quite easily see the const definition in the models (all several hundred of them) at the top of the model class, and they can refer to the documentation for the project, so wouldn't spend hours looking at code.

A crud library needs to be as flexible as possible, I see this as an improvement by keeping to standard methods, and would not cause unexpected issues if another user comes along using different field names for whatever reason.

**Comment by tabacitu** [comment]
:-)) well this got a little steamy. Guys, please, relax. We all want the same thing here - Backpack to be as useful as possible, for all of us. It's normal to have different opinions, but in the end - we want the same thing.

@indra1 - in this case I think @Spodnet is right. 

@Spodnet - I wasn't aware of those constants - I never used different column names for created_at and updated_at in Laravel. But if Laravel supports changing them, so should Backpack, I agree. And it's such a simple change, and backwards-compatible. No reason not to do it. It's done, just pushed it on the dev branch. It will be available in the next patch release (today or tomorrow), bundled with other backward-compatible updates.

Cheers!
