### ISSUE TITLE
[IP] Check if array is associative when creating field

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5181]
> Huh. Maybe the fact that I didn't catch this from the error message... means we should throw better error messages? If we encounter this again, let's think about throwing a custom error message there. I'm thinking we can analyze the array a little bit and if doesn't "_look like a field definition array_" we can say that. I don't know what that would be... maybe it's not an associative array? That'd be a simple fix.

_Originally posted by @tabacitu in https://github.com/Laravel-Backpack/demo/issues/546#issuecomment-1621278330_

**Comment by pxpm** [comment]
Fixed in #5614
