### ISSUE TITLE
Error pages not rendered using theme layout when logged in

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/CRUD#5183]
# Bug report

### What I did

Trigger a 404 error when logged to the admin panel of the app

### What I expected to happen

Show the 404 error message using a layout like before with version 5.x:
![image](https://github.com/Laravel-Backpack/CRUD/assets/12016131/560397c0-80fc-46f9-9c93-00e6ddadfa0f)

### What happened

This "ugly" and uninformative error is rendered:
![image](https://github.com/Laravel-Backpack/CRUD/assets/12016131/fde9a1df-6a4c-46cf-9c40-5d3bb192a21c)

### What I've already tried to fix it

Nothing

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug is still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.3 (cli) (built: Feb 14 2023 16:58:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.0.0
backpack/crud: 6.0.1
backpack/devtools: 2.0.2
backpack/editable-columns: 3.0.0
backpack/filemanager: 3.0.1
backpack/generators: v4.0.0
backpack/logmanager: v5.0.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.4
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.1.0
backpack/theme-coreuiv4: 1.0.0
backpack/theme-tabler: 1.0.1

**Comment by pxpm** [comment]
@malle-pietje the error pages was removed from userland. You should remove the `resources/views/errors`, or style those accordingly to your application. It will eventually fallback to Laravel default error pages.

We intercept the http errors in `/admin` namespace. If you are logged in you should see the error message with the logged in layout. 

The 404 to any page happen before sessions are started, so there is no logged in user. 
Depending on the theme you are using there may be missing the `layout` key in config. 

We added that key for example in coreui-v2 here https://github.com/Laravel-Backpack/theme-coreuiv2/pull/20

It's not tagged yet, but you can manually add it in advance. 

Let me know how it works.

**Comment by malle-pietje** [comment]
I had indeed noticed that and removed the error blade files already to clean things up.

Regarding 404, that makes complete sense and is obviously a bad test case 😉 

I'm using the Table theme and the key does exist:
```
'layout' => 'horizontal_overlap',
```
