### ISSUE TITLE
[Bug] Could not find config key: classes.tableWrapper, classes.table

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/CRUD#5184]
# Bug report

When i go to any list page I get:

Could not find config key: classes.tableWrapper errors Neither in the Backpack theme, nor in the fallback theme, nor in ui.

Could not find config key: classes.table errors Neither in the Backpack theme, nor in the fallback theme, nor in ui.

The page loads but there is no styling at all

### What I did

Upgrade to backpack 6
remain on CORE UI 2 theme for now
Works locally
deploy to staging & production

clear view, app, config cache as instructed

go production & staging, dashboard is fine, but when i go to any of the resources list page, it is unstyled and Flare give the above earlier mentioned errors to me

### What I expected to happen

Admin to look fine like it did locally

### What happened

go production & staging, dashboard is fine, but when i go to any of the resources list page, it is unstyled and Flare give the above earlier mentioned errors to me

### What I've already tried to fix it

Clear the various caches but it didn't work

composer update too for 6.0.1

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

This is my production below

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.1
backpack/pro: 2.0.4
backpack/theme-coreuiv2: 1.1.0

**Comment by ziming** [comment]
I think a screenshot would make this clearer

![CleanShot 2023-07-06 at 23 14 14@2x](https://github.com/Laravel-Backpack/CRUD/assets/679513/de8a27b4-583c-460f-b370-7e20624b8112)

**Comment by andymush** [comment]
I got the same issue but now mine doesnt work locally

**Comment by pxpm** [comment]
@ziming @andymush sorry only now getting back into this. 

@ziming did you solved it ? 

A few tips: 
- make sure you have correctly set the `APP_URL` (including https). 
- run `php artisan optimize`
- run `php artisan basset:fresh`

Before all that a `composer update` to get the latest versions as they are a bit outdated now. 

Let me know how it goes.

**Comment by fronbow** [comment]
I've had this a few times, and I'm not sure if it is related but in the tabler config file `config/backpack/theme-tabler.php` in the `classes` section there is this block
`        /**
         * Use this to pass classes to the table displayed in List Operation
         * It defaults to: "table table-striped table-hover nowrap rounded card-table table-vcenter card-table shadow-xs border-xs"
         */
        'table' => null,

        /**
         * Use this to pass classes to the table wrapper component displayed in List Operation
         */
        'tableWrapper' => null,


I've duplicated these vars to the relevant theme configs as they were missing, just not sure how to force-check that the error is still there! as it seems to disappear when I clear the view cache and rebuild basset on the live server.

**Comment by ziming** [comment]
added table and tableWrapper key to the config of core ui 2 & 4 theme and the error dissapeared

perhaps the config file of those 2 theme repos should be updated to include these 2 keys or maybe these 2 keys config should be ignored if not using tabler theme

**Comment by andymush** [comment]
> * php artisan basset:fresh

Nope, not yet. I had to downgrade my Laravel version and use an older version of Backpack. I'll try it

**Comment by karandatwani92** [comment]
Duplicate: https://github.com/Laravel-Backpack/theme-coreuiv4/issues/38
Solved: PR https://github.com/Laravel-Backpack/CRUD/pull/5230

hey @andymush  @ziming . Sorry for the trouble.
Fix has been submitted. It will be merged & tagged in the next minor update.  `composer update` will let you have it by next week. Thanks for reporting the issue.
