### ISSUE TITLE
[Bug] Setting 'setup_password_recovery_routes` requires an override of the theme. Suggest a simple wrapper

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#5188]
# Bug report

### What I did

I modified the file `config/backpack/base.php` 

I changed this to `false`

` 'setup_password_recovery_routes' => false`

### What I expected to happen

Simply that we cannot see a link to user profile

### What happened

We got a `RouteNotFoundException`

    Route [backpack.account.info] not defined.

Caused by  `vendor/backpack/theme-tabler/resources/views/inc/menu_user_dropdown.blade.php`

### What I've already tried to fix it

I exported the file as `resources/views/vendor/backpack/ui/inc/menu_user_dropdown.blade.php`
I wrapped the incriminated line into a check for existenct of the route

```
@if(Illuminate\Support\Facades\Route::has('backpack.account.info'))
            <a href="{{ route('backpack.account.info') }}" class="dropdown-item"><i class="la la-user me-2"></i>{{ trans('backpack::base.my_account') }}</a>
@endif
```

I suggest to wrap by default use of the route with a test for its existence

Anyway, probably it's not the right location for my custom file, because laravel/backpack is ignoring it

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

λ php artisan backpack:version
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:13:52) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.1
backpack/generators: v4.0.0
backpack/pro: 2.0.5
backpack/theme-tabler: 1.0.1

**Comment by realtebo** [comment]
Found until now these 2 files need this small fix:

- inc/menu_user_dropdown.blade.php
- /layouts/_vertical/sidebar_content_top.blade.php

**Comment by pxpm** [comment]
Thanks @realtebo for the report. 🙏 

I've submitted PR's to both three themes to address this issue 
https://github.com/Laravel-Backpack/theme-coreuiv4/pull/36
https://github.com/Laravel-Backpack/theme-coreuiv2/pull/22
https://github.com/Laravel-Backpack/theme-tabler/pull/100

I will be releasing a new version in a few hours after I look up some other issues. 

Thanks 🙏
