### ISSUE TITLE
[Bug] No lineawesome avaiable for icon_picker field

### ISSUE THREAD

**Issue by malek77z** [Laravel-Backpack/CRUD#5196]
# Bug report

When suppling lineawsome to the icon_picker field type
https://backpackforlaravel.com/docs/6.x/crud-fields#icon_picker-pro
font awesome is shown (I guess as the fallback)

I checked the field blade file and there seem to one be only ionicon, weathericon, mapicon, octicon, typicon, elusiveicon, meterialdesign

Has this been removed?

### What I expected to happen

Lineawesome icons to be available

**Comment by pxpm** [comment]
Hey @malek77z 

Lineawesome was never available via `icon_picker`. It's a mistake in our documentation, sorry about that.

I've just updated the docs to reflect that: https://github.com/Laravel-Backpack/docs/pull/460

Feel free to submit a feature request, but to be honest I don't see us working on adding more fonts to this icon picker.
As of now we have to maintain our own fork of the library to make it work with BS5, and we are probably going to try to find a replacement library that we don't need to maintain. 

Thanks for the heads up, and sorry for the bad experience 🙏 

Cheers
