### ISSUE TITLE
[Bug] standard backpack install doesn't load css files properly

### ISSUE THREAD

**Issue by ruttydm** [Laravel-Backpack/CRUD#5197]
# Bug report

### What I did

I have a standard laravel installation with some models, I installed backpack using all the recommended steps, I generated CRUDS for all models using the command.

### What I expected to happen

I was expected to have a functional install by default.

### What happened

When opening the admin panel the styling doesn't load properly and I get 419 errors. The console outputs following messages:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (source-sans-pro.css, line 0)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (coreui4.css, line 0)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (common.css, line 0)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (color-adjustments.css, line 0)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (colors.css, line 0)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (common.js, line 0)

### What I've already tried to fix it

I tried installing and doublechecking all npm and composer packages, I tried reinstalling backpack, updating everything etc.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes, nothing changes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.7 (cli) (built: Jun 20 2023 20:52:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.3
backpack/generators: v4.0.0
backpack/theme-coreuiv4: 1.0.1
backpack/theme-tabler: 1.0.2

**Comment by pxpm** [comment]
Hey  @ruttydm we don't use npm in backpack v6. 

Actually we use Basset https://github.com/Laravel-Backpack/basset

Please make sure you have set your `APP_URL` correctly in your `.env` file. 

Let me know how it goes.

Cheers

**Comment by ruttydm** [comment]
The app url was indeed set wrong.  Was hard to track the issue but it’s solved now. On 10 Jul 2023, at 10:49, Pedro Martins ***@***.***> wrote:﻿
Hey  @ruttydm we don't use npm in backpack v6.
Actually we use Basset https://github.com/Laravel-Backpack/basset
Please make sure you have set your APP_URL correctly in your .env file.
Let me know how it goes.
Cheers

**Comment by pxpm** [comment]
We will try to come up with a solution that can detect that error before developers spent time trying to debug it. 

Thanks 🙏
