### ISSUE TITLE
[Bug] Upgrade BackPack v5 to v6

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#5199]
# Bug report

### What I did

Upgrade Backpack v5 to v6 and use the new theme tabler. Login is OK but nothing after.

### What I expected to happen

That is working

### What happened

![image](https://github.com/Laravel-Backpack/CRUD/assets/1824638/9261420a-cd9f-4d99-95db-e74a3b1e3e89)
![image](https://github.com/Laravel-Backpack/CRUD/assets/1824638/ea2fc8ed-05b7-42f0-9773-55f7e4c12c8f)

### What I've already tried to fix it

Delete cache, comment middleware

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.9 (cli) (built: Aug  2 2022 14:17:26) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.3
backpack/generators: v4.0.0
backpack/pro: 2.0.5
backpack/theme-tabler: 1.0.2

**Comment by pxpm** [comment]
@t-prod from the error I would say that it is related with some field with name defined as array. `name => [array]`. 

We removed array names, so you should replace the array with `comma,separated,values`. 

Please have a look at https://backpackforlaravel.com/docs/6.x/upgrade-guide#step-14

Let me know how it goes.

Cheers

**Comment by tabacitu** [comment]
In addition, as noted in the upgrade guide, we heavily recommend keeping the CoreUIv2 theme during the upgrade process. Only after everything is working fine with CoreUIv2... install the new Tabler theme. Hope it helps!

Let us know if Pedro's suggestion doesn't fix the problem, and we'll reopen.
Cheers!

**Comment by t-prod** [comment]
Unfortunately, nothing works. I made an instalkl with CoreUIV2 and I have this error :

![image](https://github.com/Laravel-Backpack/CRUD/assets/1824638/bc6ac42a-2430-435a-9c23-4093ae850aa9)

I'm stucked :( Any ideas ?

**Comment by t-prod** [comment]
![image](https://github.com/Laravel-Backpack/CRUD/assets/1824638/4a72caf5-1b11-49b8-86b1-6db040ed8103)

In the index.php so I believe is linked with routes

**Comment by t-prod** [comment]
Ok I figured it out, it's something related with config files.
So all is working fine sorry.
Thanks for your awesome support guys
