### ISSUE TITLE
How can i make image file on insert or update with rename and make thumb files?

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#52]
hello!
How can i make image file on insert or update with rename and make thumb files?

**Comment by c1t1zen** [comment]
Hey!

any help int that ?
i dont know if i can resize and rename image on upload or not with this package?

thank you in advance

**Comment by tabacitu** [comment]
Hi!

Sure, you can use the "browse" field type and, on your model, use a mutator
to crop/resize/whatever you want to do with your image.

function setImageAttribute($value) {
   // use Intervention image or whatever you want to process that image
   $this->attribute['image'] = $value;
}


On Sunday, 10 July 2016, c1t1zen <notifications@github.com> wrote:

> Hey!
>
> any help int that ?
> i dont know if i can resize and rename image on upload or not with this
> package?
>
> thank you in advance
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Laravel-Backpack/crud/issues/52#issuecomment-231582798>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA_BGuhkh_geIcJvr0QJQAIxqhHEo09Xks5qUM-WgaJpZM4JFUMG>
> .
>


-- 

[image: photo]
*Cristian Tăbăcitu*
Managing Partner UPDIVISION
<http://s.wisestamp.com/links?url=http%3A%2F%2Fupdivision.com&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>
<http://s.wisestamp.com/links?url=http%3A%2F%2Falternopedia.ro&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>Board
Member Ideo Ideis
<http://s.wisestamp.com/links?url=http%3A%2F%2Fideoideis.ro&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>
| mobile: +4 0752 233 319 | website: http://tabacitu.ro/
<http://s.wisestamp.com/links?url=http%3A%2F%2Ftabacitu.ro&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>
[image: Facebook]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fwww.facebook.com%2Ftabacitu&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fro.linkedin.com%2Fin%2Ftabacitu&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>
 [image: Google Plus]
<http://s.wisestamp.com/links?url=http%3A%2F%2Fplus.google.com%2F111602517732305461201&sn=Y3Jpc3RpdGFiYWNpdHVAZ21haWwuY29t>
 Video conference: [image: Google Talk] cristitabacitu [image: Skype]
 cristitabacitu

**Comment by c1t1zen** [comment]
hey

i did like you said

i got this error:

ErrorException in Article.php line 127: Indirect modification of overloaded property App\Models\Article::$attribute has no effect

first in ArticleCrudController (news system)
i made this code 
        $this->crud->addField([    // Image
            'name' => 'image',
            'label' => 'Image',
            'type' => 'browse',
            'function_name' => 'setImageAttribute'            

        ]);

it was :

//         $this->crud->addField([    // Image
//            'name' => 'image',
//            'label' => 'Image',
//            'type' => 'browse_file_manager'
//        ]);


/////////
in Article model 
#######
i add this function

    // my own functions
	function setImageAttribute($value) {
	   // use Intervention image or whatever you want to process that image
 		 $value = Image::make($value)->resize(300, 200);		
	   $this->attribute['image'] =  'test'; // just test if i can make any change in filed in db	   
	}

**Comment by c1t1zen** [comment]
Thank you alot
i did make it in this link for other people so they can do it if they need

https://github.com/Laravel-Backpack/crud/issues/57

**Comment by c1t1zen** [comment]
can i get last  inserted id in modal in ?

function setImageAttribute($value) {
   // use Intervention image or whatever you want to process that image
   $this->attribute['image'] = $value;
}

thank you again

**Comment by tabacitu** [comment]
Sure, just get the current id using $this->id

**Comment by c1t1zen** [comment]
yes i did put $this->id in method but did not work i got null

function setImageAttribute($value) {
// use Intervention image or whatever you want to process that image
$this->attribute['image'] = $this->id.'_'.$value;
}
when i checked table it does not print the id as id_$value

**Comment by tabacitu** [comment]
That's odd. I have quite a few mutators working this way.

1) Are you sure you have your ```image``` in your ```$fillable``` array, on your model? The CRUD will only save what's in the fillable array.
```php
protected $fillable = ['name', 'image'];
```

2) Try looking at the [Laravel documentation on Mutators](https://laravel.com/docs/5.2/eloquent-mutators#accessors-and-mutators), maybe you've missed something. Doing a ```dd($this->id);``` in your ```setImageAttribute()``` method should dump the correct ID.

**Comment by c1t1zen** [comment]
it was
`	protected $fillable = ['slug', 'title', 'content', 'image', 'status', 'category_id', 'featured', 'date'];`
i can save image name after rename it with no problem but when i try to add
id_imageName.jpg it just save as _imageName.jpg in the db table

**Comment by tabacitu** [comment]
Does ```$this->getKey()``` work, instead of ```$this->id```?

**Comment by tabacitu** [comment]
@c1t1zen,

Did this work for you? Can I close the issue?

Cheers!

**Comment by c1t1zen** [comment]
yes Close it thank you
