### ISSUE TITLE
[Bug] Login page cannot be overridden

### ISSUE THREAD

**Issue by benwright9400** [Laravel-Backpack/CRUD#5203]
# Bug report

### What I did

I am working on a Backpack project and would like to add a logo to the login screen. I have tried overriding the login.blade.php file by placing it in the appropriate directories.

### What I expected to happen

I expected the login page to change.

### What happened

The login page has not changed

### What I've already tried to fix it

I have tried:
 - refreshing the cache
 - multiple alternative routes to the file, including:
    - Vendor/Backpack/UI/auth/login.blade.php
    - Vendor/Backpack/Base/auth/login.blade.php
    - Vendor/Backpack/auth/login.blade.php
    - The same with 'Auth' instead of 'auth'

### Is it a bug in the latest version of Backpack?

Yes, I am using the latest version of Backpack.

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes, it is still there.

### Backpack, Laravel, PHP, DB version

Backpack - ^6.0
PHP - ^8.2
DB - MYSQL 8.0.27

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.5 (cli) (built: Apr 13 2023 17:59:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.3
backpack/generators: v4.0.0
backpack/pro: 2.0.5
backpack/theme-coreuiv2: 1.1.1

Thank you very much for your help.

**Comment by pxpm** [comment]
Hello @benwright9400 

If the theme you are using already provide a customized `login.blade.php` file you should add it into the theme folder: `resources/views/vendor/backpack/theme-coreuiv2/auth/login.blade.php`

We have an example of it in our demo: https://github.com/Laravel-Backpack/demo/tree/main/resources/views/vendor/backpack/theme-coreuiv2/auth

Let me know if that helps. 👍 

I am going to close this as I don't think there is a bug here. We will re-open if that's not the case.

Cheers
