### ISSUE TITLE
[Bug] Incomplete PhpDoc definition for  denyAccess

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#5206]
# Bug report

### What I did

As documented [here](https://backpackforlaravel.com/docs/6.x/crud-api#access) , I added  this in a crud controller

    $this->crud->denyAccess('delete');

### What I expected to happen

I expected to see no warnings from my IDE

### What happened

My IDE warned me about signature of denyAccess. 
It tolds me 

> Expected parameter of type 'array', 'string' provided

This is because  `vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Access.php` has the function defined as 

```
/**
     * Disable the access to a certain operation, or the current one.
     *
     * @param  array  $operation  [description]
     * @return [type] [description]
     */
    public function denyAccess($operation)
    {
        foreach ((array) $operation as $op) {
            $this->set($op.'.access', false);
        }

        return ! $this->hasAccessToAny($operation);
    }
```
### What I've already tried to fix it

Nothing

I suggest to change php doc into

`* @param  array|string $operation  [description]`

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.2.8 (cli) (built: Jul  4 2023 15:53:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.15.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.4
backpack/generators: v4.0.0
backpack/pro: 2.0.6
backpack/theme-tabler: 1.0.2
```

**Comment by tabacitu** [comment]
Sure - done in https://github.com/Laravel-Backpack/CRUD/pull/5207

Hopefully we'll get to add types to that, soon enough.

Cheers!
