### ISSUE TITLE
[Bug] FormRequest rules validation sometimes + required does not show asterisk

### ISSUE THREAD

**Issue by WrdVdb** [Laravel-Backpack/CRUD#5208]
# Bug report

### What I did

My validation rules were for example:

`'Firstname' => 'sometimes|required|min:1|max:150',`

In some cases the firstname field is disabled, hence the sometimes in added

In this case the required asterisk will not be shown in the crud.

### What I expected to happen

The required asterisk should be shown when sometimes is before the required

### What happened

The required asterisk is not shown. (In backpack v5 the asterisk was shown)

### What I've already tried to fix it

When I use 

`'Firstname' => 'required|sometimes|min:1|max:150',`

The asterisk is shown, so required before the sometimes.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.20 (cli) (built: Jun  8 2023 15:25:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.20, Copyright (c), by Zend Technologies
    with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.4
backpack/generators: v4.0.0
backpack/pro: 2.0.4
backpack/theme-coreuiv4: 1.0.0
backpack/theme-tabler: 1.0.1

**Comment by pxpm** [comment]
Hey @WrdVdb thanks for the question.

I think that is the expected behavior ? If it is "sometimes required", it's not " * mandatory required". We have no way to know "when it's required" and when it's not. 

You can force the asterisk in the field by defining `'showAsterisk' => true` in your field definition. 

Closing, let me know if you have any issue and we can re-open!

Cheers

**Comment by WrdVdb** [comment]
Is it not when a required input is not on the request (when the field is disabled or not shown) that the sometimes is needed? But the field remains required, thus the asterisk should be visible?

I don't think there is a case when the asterisk should not be shown. Or the field is disabled or the field is not shown at all, when disabled, the asterisk should be shown, when the field is not visible, it is no problem.

When the rules is `sometimes|required` the asterisk is not shown, but when the rule is `required|sometimes` the asterisk is shown. Both rules are the same, so the asterisk behavior should not change, which is the case now.

The behavior alse has changed between v5 and v6. In v5 the asterisk was shown for both rules.
