### ISSUE TITLE
[Bug] Upgrade no CRUD update and no login

### ISSUE THREAD

**Issue by t-prod** [Laravel-Backpack/CRUD#5211]
# Bug report

### What I did

Just upgrade by steps as mentioned in the documentatyion

### What happened

![image](https://github.com/Laravel-Backpack/CRUD/assets/1824638/67121e8c-518c-4080-ad48-3aa2d869b757)

Login included dashboard
CRUD update does not change anything

### What I've already tried to fix it

Try to follow steps again, looking at routes 

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by tabacitu** [comment]
I'm sorry @t-prod - I don't understand. Could you please rephrase what happened?

**Comment by t-prod** [comment]
For the 2.  I figured it out that I have this :
```
[
    'name' => 'field',
    'label' => 'Label,
    'validationRules' => 'nullable|numeric|max:0',
    'wrapper' => [
        'class' => 'col-md-6'
    ]
],
```
And the validation error message does no appear so update can be done cause I do not have the warning rule, any ideas ?

The 1. is still a problem

**Comment by fronbow** [comment]
Hi @t-prod , it might help to do the instructions in the "Hide this notice" so bp might be able to give you a better error display?
(Just a thought)

**Comment by t-prod** [comment]
Hi @fronbow no errors in console. Maybe there's a new way to include auth. I've upgraded to Laravel 10 also. We have basset assets now so everything is included.
I think it's more a middleware or a template issue
Any ideas ?

**Comment by t-prod** [comment]
It was difficult be I figured it out don't know why but I have a missing Middleware here in base.php :

![image](https://github.com/Laravel-Backpack/CRUD/assets/1824638/323ed16b-cc54-4397-b91b-70ea5406a22f)

I do not have display errors even if I have validationRules in any CRUD. Maybe something change for this I check and compare all operations config files and that's OK.
Any ideas ?

**Comment by t-prod** [comment]
Even if I make a Request or ValidationRules I'm stucked on the screen. We can see all errors with groupedErrors but inlineErrors does not display with select (relationship) or other fields.
The solution is to use groupedErrors  for create and update

**Comment by pxpm** [comment]
@t-prod what do you have in your `config/backpack/operations/create.php` ?

**Comment by t-prod** [comment]
Hi pxpm, I have this code nothing fancy :
It's simply that only required validation rule display something when inlineErrors = true.
I try with a select (relationship) field but nothing is displayed and we stay on CRUD create screen without messages. My solution was to activate only grouped errors but it's not fantastic in terms of display ;)

```
<?php

/**
 * Configurations for Backpack's CreateOperation.
 *
 * @see https://backpackforlaravel.com/docs/crud-operation-create
 */

return [
    // Define the size/looks of the content div for all CRUDs
    // To override per view use $this->crud->setCreateContentClass('class-string')
    'contentClass' => 'col-md-8 bold-labels',

    // When using tabbed forms (create & update), what kind of tabs would you like?
    'tabsType' => 'horizontal', //options: horizontal, vertical

    // How would you like the validation errors to be shown?
    'groupedErrors' => true,
    'inlineErrors'  => true,

    // when the page loads, put the cursor on the first input?
    'autoFocusOnFirstField' => true,

    // Where do you want to redirect the user by default, save?
    // options: save_and_back, save_and_edit, save_and_new
    'defaultSaveAction' => 'save_and_back',

    // When the user chooses "save and back" or "save and new", show a bubble
    // for the fact that the default save action has been changed?
    'showSaveActionChange' => true, //options: true, false

    // Should we show a cancel button to the user?
    'showCancelButton' => true,

    // Should we warn a user before leaving the page with unsaved changes?
    'warnBeforeLeaving' => false,

    // Before saving the entry, how would you like the request to be stripped?
    //  - false - use Backpack's default (ONLY save inputs that have fields)
    //  - invokable class - custom stripping (the return should be an array with input names)
    // 'strippedRequest' => App\Http\Requests\StripBackpackRequest::class,
];

```

Thanks for your help

**Comment by pxpm** [comment]
- What's your relationship type?
- What's your relationship field definition?
- What's your rules definition for that field ?

Cheers

**Comment by t-prod** [comment]
Hi,

[
      'name' => 'value',
      'label' => 'Value',
      'type' => 'select',
      'validationRules' => 'required',
      'wrapper' => [
          'class' => 'col-md-4'
      ]
  ],

The field is in fact value_id and have a belongTo relationship on values table.

**Comment by t-prod** [comment]
Hmm OK I think I understand. Grouped errors everything is fine. 
The problem is with inlineErrors. 
Only the last field declared with validationRules displays an error and NOT the others :
I have several fields (without type but it's input type text) with :

`'validationRules' => 'nullable|numeric|min:0',`

Only the last field displays something

**Comment by tabacitu** [comment]
Glad you figured out no 2 @t-prod .

For no 1:
> I did not have anymore the login Page I'm redirected to the DashBoard with the 2 links connexion and inscription on the right top of my screenshot. I've just updated CoreUIV2 Theme and follow upgrading steps carefully

From what I understand... you had a custom dashboard. And that dashboard is no longer shown in login, you see the "standard" Backpack dashboard with the Getting Started widget. Is that correct? 

If that's the case... the problem might be that you have not moved your `dashboard.blade.php` from `base` to `ui` or `theme-coreuiv2` as instructed in [Step 20](https://backpackforlaravel.com/docs/6.x/upgrade-guide#step-20). That instructs you to rename `base` to `ui` which should be the same thing. Do you have the `resources/views/vendor/backpack/ui/dashboard.blade.php` file that you want shown? If you move it to `backpack/theme-coreuiv2` will it show then?

**Comment by t-prod** [comment]
Hi @tabacitu,

The 1. was my mistake. The checkIfAdmin middleware was missing. So the consequence was this weird bug ;)
2. Still a problem cause onyl the last field displays an error when you activate inlineErrors = true

**Comment by tabacitu** [comment]
Hi @t-prod ,

Glad you managed to solve your initial issue. I see the conversation has moved to a different issue you're having. Please open a different issue for each problem you have. Otherwise it's very difficult for us to keep up. And difficult for others that might have the same issue to find it. This conversation already is long and difficult to follow, so let's close it and move to another one.

But just to be clear... for your inline error problem, I can't seem to replicate it. So it must be something you've configured or overridden. In my tests and [in our online demo](https://demo.backpackforlaravel.com/admin/article/create) all inline errors are showing ok:
<img width="1494" alt="CleanShot 2023-08-11 at 15 46 02@2x" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/6199e8e9-f2d6-480c-9eeb-016aeba52d11">

If you're still having this problem, please open a different issue so we can help. In there, please also include what customizations you have made to your panel that might interfere (eg. configs, custom views, custom CrudControllers etc).

Cheers!
