### ISSUE TITLE
Column `row_number` hides the expand icon of DetailsRow

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5215]
While adding the `row_number` column to the demo I found, it conflicts with DetailsRow by hiding the expand icon.

BEFORE:
![Screenshot 2023-07-16 at 5 35 25 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/859ddcba-f7ec-4162-b525-55e8855ec1fe)

AFTER
![Screenshot 2023-07-16 at 5 34 44 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/04d0aa14-1931-417c-aa66-f33bfe358dbd)

```php
$this->crud->enableDetailsRow();
$this->crud->setDetailsRowView('vendor.backpack.crud.details_row.monster');
```

```php
$this->crud->addColumn([
    'name'      => 'row_number',
    'type'      => 'row_number',
    'label'     => '#',
    'orderable' => false,
])->makeFirstColumn();
```

### TODO:
- [ ] Fix the bug
- [ ] Add column to demo monster

**Comment by pxpm** [comment]
fixed in #5615 let's move the conversation over there. 👍
