### ISSUE TITLE
elfinder js and css files not found

### ISSUE THREAD

**Issue by DelightedD0D** [Laravel-Backpack/CRUD#522]
I have followed the steps at https://laravel-backpack.readme.io/docs/installation-on-laravel-53#section-3-install-backpackcrud. Everything seems fine but when I go to /admin/elfinder the page loads but the file manager panel does not. In the console, I see: 

![image](https://cloud.githubusercontent.com/assets/8271955/23614321/25ad54fa-0248-11e7-97f0-ef36d3a4a6d5.png)

What am I doing wrong here?

**Comment by tabacitu** [comment]
Hi @DelightedD0D ,

Are you sure you ran
```
php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="elfinder"
```

**Comment by DelightedD0D** [comment]
Hi @tabacitu  yup:

![image](https://cloud.githubusercontent.com/assets/8271955/23614611/25b97d92-0249-11e7-8e85-99f6265609f2.png)

**Comment by DelightedD0D** [comment]
Hu @tabacitu  I just ran`php artisan elfinder:publish` and it published the packages folder and all of the assets. Something definitely seems hinky with the `CrudServiceProvider` but that fixed the issue for me

**Comment by DelightedD0D** [comment]
@tabacitu While I was able to fix this on my end, I'm not sure that this should be closed. The steps provided dont seem to work properly. I clearly ran the required command yet the resources were not published. I had to go to the dependancy's install page and manually publish the files through their command. Shouldn't those files have been generated via the backpack command?
