### ISSUE TITLE
[Bug][6.x] `relationship` column ignores attribute

### ISSUE THREAD

**Issue by marechenok** [Laravel-Backpack/CRUD#5220]
# Bug report

### What I did

I've used in V5 relationship field like this:

```php
[
    'name' => 'referralSource', // name of relationship method in the model
    'type' => 'relationship',
    'label' => trans('Ref'),
    'orderable' => true,
    'orderLogic' => function ($query, $column, $column_direction) {
        return $query->leftJoin('referral_sources', 'users.id', '=', 'referral_sources.user_id')
            ->select('users.*', 'referral_sources.source')
            ->orderBy('referral_sources.source', $column_direction);
    },
    'model' => ReferralSource::class,
    'attribute' => 'source', // foreign key attribute that is shown to user
]
```            
### What I expected to happen

Expected to see only `source` field of ReferralSource model.

### What happened

It shows entire related model as json 
![image](https://github.com/Laravel-Backpack/CRUD/assets/26778514/4cf648e0-cbb2-4da5-beae-3ba666ef03df)

### Is it a bug in the latest version of Backpack?

Latest v6 backpack after migration from v5

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.12 (cli) (built: Oct 28 2022 17:39:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.15.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.6
backpack/filemanager: 3.0.2
backpack/generators: v4.0.1
backpack/newscrud: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.8
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.1.3

**Comment by marechenok** [comment]
Tiny update regarding this issue:
looks like it fails only on hasOne relationship. BelongsTo works as it should be.

**Comment by Astriel** [comment]
Hello there ! 
I've got the exact same problem and created an issue. I'm also facing the problem on a "belongsToMany" n-n relationship.

**Comment by tabacitu** [comment]
@pxpm can you take this over please?

**Comment by pxpm** [comment]
I think I've already fixed this in PRO 2.0.10 https://backpackforlaravel.com/products/pro-for-unlimited-projects/CHANGELOG.md

Please run a `composer update` and make sure you got the latest versions installed with `php artisan backpack:version`.

If the error persist please let me know and we can re-open this! 🙏 

Cheers

**Comment by marechenok** [comment]
btw, my mistake. The problem in relationship column, not field

**Comment by pxpm** [comment]
Hey @marechenok 

From the description you gave you are using a `HasOne` relation that's not aware of the `attribute`. That's a "select" thing. (BelongsTo, BelongsToMany etc). HasOne is not a selectable relation. 

You can display the value of your relation with: `CRUD::column('referralSource.source')` assuming your relation is called `referralSource`. If you want to display more fields in the same column, you can define the `subfields` (name is correct, subfields works for columns and fields) and the column will display similar to a table. 

Let me know how it goes.

**Comment by marechenok** [comment]
```php
$this->crud->addColumn('referralSource');
```
![image](https://github.com/Laravel-Backpack/CRUD/assets/26778514/2b2caec7-2bcb-45e8-8975-fde4ac6ea08e)

```php
$this->crud->addColumn('referralSource.source');
```
![image](https://github.com/Laravel-Backpack/CRUD/assets/26778514/da9cf543-d569-4f95-b988-ba6b12b4d0b9)

**Comment by marechenok** [comment]
Made it works like this:

```php
[
    'name' => 'referralSource.source', // name of relationship.attribute 
    'type' => 'relationship',
    'label' => trans('Ref'),
    'orderable' => true,
    'orderLogic' => function ($query, $column, $column_direction) {
        return $query->leftJoin('referral_sources', 'users.id', '=', 'referral_sources.user_id')
            ->select('users.*', 'referral_sources.source')
            ->orderBy('referral_sources.source', $column_direction);
    },
],
```
