### ISSUE TITLE
[Bug] V6 date_range with FakeFields

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/CRUD#5221]
# Bug report

### What I did

Create a date_range with FakeFields

```php
CRUD::field([
            'name'  => ["start", "end"],
            'label' => 'Event Date Range',
            'type'  => 'date_range',
            'date_range_options' => [
                'locale' => ["firstDay" => 1]
            ],
            "fake" => true,
            "store_in" => "extras"
        ]);
```

### What I expected to happen

Store the value in a json `{"start":"2023-07-01 00:00:00","end":"2023-07-31 23:59:59"}`

### What happened

Value not sotred

### What I've already tried to fix it

The error is releted to the change in name from `['start', 'end']` to `start,end` i debug the code is from the function:
**compactFakeFields** in `vendor\backpack\crud\src\app\Library\CrudPanel\Traits\FakeFields.php`
Only tested on `date_range`  but it is likely that `checklist_dependency`  fail too.

For now i created two date_picker with  `"fake" => true`

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/0d21dafa-d2d7-45be-b026-0bc043c33e0b)

**Comment by pxpm** [comment]
Hey @adriallongarriu did you tried defining your field with: `name => 'start,end'` ?

**Comment by adriallongarriu** [comment]
> Hey @adriallongarriu did you tried defining your field with: `name => 'start,end'` ?

Yes, i copy the old value in v5, sorry. I tested with `name => 'start,end'` If you use array with v6 throw an error
`strpos(): Argument #1 ($haystack) must be of type string, array given`
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/96f62ef8-de7e-4df0-8d53-9c5641572052)

**Comment by pxpm** [comment]
Thanks for the report @adriallongarriu 🙏 

I've just tagged https://github.com/Laravel-Backpack/CRUD/releases/tag/6.1.4 with the fix. 

Let me know if you are still experiencing issues 🙏 

Cheers

**Comment by adriallongarriu** [comment]
thanks @pxpm i tested and it works 😁👍 

I used fake fields with https://github.com/Laravel-Backpack/Settings to store the value of a date_range with no need to override or modify any controller or model. 

Field value:
`{"name":"start,end","label":"Dates","type":"date_range","fake":true,"store_in":"value"}`
