### ISSUE TITLE
[Bug] 419 - Token Mismatch at ListOperation

### ISSUE THREAD

**Issue by JoacinB** [Laravel-Backpack/CRUD#5222]
# Bug report

### What I did

Tried to list users crud

### What I expected to happen

Show the CRUD table

### What happened

Error 419 - token mismatch

### What I've already tried to fix it

Add headers to ajax configuration

### Is it a bug in the latest version of Backpack?

Yes

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

All of them are last version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.4 (cli) (built: Mar 14 2023 17:54:25) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.15.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.6
backpack/generators: v4.0.1
backpack/theme-coreuiv2: 1.1.3

**Comment by JoacinB** [comment]
PR: https://github.com/Laravel-Backpack/CRUD/pull/5223

**Comment by tabacitu** [comment]
Thanks @JoacinB - let's move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/5223
