### ISSUE TITLE
[Bug] inconsistency look field Color

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/CRUD#5227]
# Bug report

### What I did

Create multiple color picker in the same page.

```php
            [
                'name'    => 'color',
                'label'   => trans('backpack.color'),
                'type'    => 'color',
                'default' => '#df5f52',
            ],
            [
                'name'    => 'color1',
                'label'   => trans('backpack.color'),
                'type'    => 'color',
                'default' => '#df5f52',
            ],
            [
                'name'    => 'text_color',
                'label'   => trans('backpack.color'),
                'type'    => 'color',
                'default' => '#df5f52',
            ],
            [
                'name'    => 'background_color',
                'label'   => trans('backpack.color'),
                'type'    => 'color',
                'default' => '#df5f52',
            ],
```

### What I expected to happen

That all color picker work and display the same

### What happened

![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/92bb5028-ef5d-4b71-8c65-0d9fbee26d24)

### What I've already tried to fix it

I don't know the reason but if the input is has the name "color" is applying extra styles.
The extra styles are on the `resources/views/crud/fields/color.blade.php`
https://github.com/Laravel-Backpack/CRUD/blob/79449aec5a2affd2bf6b08c0842459045cbab0f4/src/resources/views/crud/fields/color.blade.php#L40C4-L50C13

### Is it a bug in the latest version of Backpack? Yes

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/8380a35e-ae25-4dd5-887d-82893024bb32)

**Comment by jorgetwgroup** [comment]
hi @adriallongarriu thanks for reporting this issue we will check and fix as is needed.

Cheers.

**Comment by adriallongarriu** [comment]
@jorgetwgroup i creted a pull request with a fix.
