### ISSUE TITLE
[Feature] Support for NativePHP

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5228]
We DEFINITELY should support it. Can't wait to use this for clients - https://nativephp.com/

Status: @phpfour has tried it:

<img width="708" alt="CleanShot 2023-07-24 at 12 09 12@2x" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/6edbed17-75c4-4c8a-9166-77c76fa3cb55">

**Comment by pxpm** [comment]
Hey guys. 

Doing a quick cleanup here. 

Thanks for your effort @phpfour I think it could be something nice to have, let's see how things evolve in the future. 1 year after this PR and NativePHP still in alpha. 

But realistically, even if they launched the stable version today, I don't think we would be spending resources on something nobody ever asked for.

I am going to close this, but if you work on this and there is something we can/need to do in Backpack to support it, let us know, you know where to find me ;)

Cheers
