### ISSUE TITLE
[Bug] Backpack V6 - Theme Tabler - Could not find config key: classes.body. Neither in the Backpack theme...

### ISSUE THREAD

**Issue by munjaldevelopment** [Laravel-Backpack/CRUD#5229]
# Bug report

"Could not find config key: classes.body. Neither in the Backpack theme, nor in the fallback theme, nor in ui."

### What I did

This error appear on every page

### What I expected to happen

No Error in log. Log file increase to MBs

### What happened

Continue error showing in Log

### What I've already tried to fix it

N/A

### Is it a bug in the latest version of Backpack?

Yes.

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.7 (cli) (built: Jun  7 2022 21:45:53) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7, Copyright (c), by Zend Technologies
    with Xdebug v3.1.6, Copyright (c) 2002-2022, by Derick Rethans

### LARAVEL VERSION:
10.15.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.0.0
backpack/crud: 6.0.6
backpack/editable-columns: 3.0.1
backpack/filemanager: 3.0.2
backpack/generators: v6.x-dev
backpack/logmanager: v5.0.0
backpack/medialibrary-uploaders: 1.0.1
backpack/menucrud: v4.0.1
backpack/newscrud: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.8
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.1.3
backpack/theme-coreuiv4: 1.0.4
backpack/theme-tabler: 1.0.5

Attached screenshot

![image](https://github.com/Laravel-Backpack/CRUD/assets/14837352/fad56dd3-e34f-4e5e-bf38-11a0b76fcf6b)

**Comment by pxpm** [comment]
Hey @munjaldevelopment thanks for the report 🙏 

We are working on the solution described here: https://github.com/Laravel-Backpack/theme-coreuiv4/issues/38#issuecomment-1648359007

We should lunch the new versions with the fixes soon.

I the meanwhile I am going to close this as we have already other issue opened regarding the same subject.

Cheers

**Comment by de-raaf-media** [comment]
I have a similar issue. Just noticed in the logs:

" Could not find config key: options.showPasswordVisibilityToggler. Neither in the Backpack theme ... "

Regards,
Mark

**Comment by de-raaf-media** [comment]
> Hey @de-raaf-media I think that is a different issue. I could not reproduce your error.
> 
> `showPasswordVisibilityToggler` only exists in theme-tabler, and it is in the options for that theme: https://github.com/search?q=org%3ALaravel-Backpack%20showPasswordVisibilityToggler&type=code
> 
> Any chance you are using tabler files with other theme ? If that's the case, just create it in the theme config:
> 
> ```
> 'options' => [
>     'showPasswordVisibilityToggler' => true
> ]
> ```
> 
> We only have that functionality in theme-tabler, so I don't think it makes sense to add it to the `config/ui` like the other config keys described here that are used by all the themes.
> 
> Let me know, 🙏

It seems this was not present in my theme-tabler.php config file:
"showPasswordVisibilityToggler" => false,
