### ISSUE TITLE
Support for UUID

### ISSUE THREAD

**Issue by XanManZA** [Laravel-Backpack/CRUD#523]
Hey there.   
So I am wondering and cannot find information anywhere.   
If I have a table and the route to edit is defined as   
`http://timutech.localhost/admin/timu-user/0/edit`   
How do I get that `0` parameter in the url to translate to my real ID used in the database? As I am using UUIDs.   
Following `http://timutech.localhost/admin/timu-user/0/edit` gives a "404 No query results for model [App\Models\TimuUser] 0" page.

**Comment by XanManZA** [comment]
Sigh! Just solved it by including the same Trait for UUIDs as the other project. This basically just calls
public function getCasts() { return $this->casts; }
to fix it. My bad!

**Comment by tabacitu** [comment]
Glad to hear you fixed it! An alternative, I think, would have been to define the $primaryKey attribute on your model. Cheers!

**Comment by XanManZA** [comment]
tabacitu thanks but I also tried that :D did not help!

**Comment by ProVibe** [comment]
I can't understand how to add UUID management instead of integer ID. Can someone explain me? Thanks

**Comment by lloy0076** [comment]
@XanManZA - using UUIDs for primary keys really isn't a Backpack specific question; I haven't used this particular package but you could consider:

* https://packagist.org/packages/alsofronie/eloquent-uuid

Or:

* https://duckduckgo.com/?q=uuid+as+primary+key+laravel+eloquent&atb=v18&ia=qa
* https://www.google.com/#q=uuid+as+primary+key+laravel+eloquent&spf=1497614686885

**Comment by ProVibe** [comment]
Thank you, I've resolved setting up a new Trait for creation event, generating a new UUID.
I'm new on Backpack and I was thinking this was an out-of-the-box feature. So sorry for out-of-context question ;)

**Comment by digitaltim-de** [comment]
Same Issue..

**Comment by tabacitu** [comment]
@digitaltim-de what's the issue you're having more specifically? If you think there's a bug in Backpack please open a new issue - it'll also ask you for some stuff like the version of PHP and Backpack you're running.

For reference, I've just created a CRUD for a model that uses UUIDs and it seems to work perfectly, I had no problems. The problem first reported here is a very old one (2017), nowadays I see the UUID is used in the URL so there's no reason UUIDs wouldn't work out-of-the-box with Backpack:

![2021-02-12 13 32 39](https://user-images.githubusercontent.com/1032474/107763264-046fd980-6d37-11eb-8288-2ab7d66e48f6.gif)
