### ISSUE TITLE
[Bug] The upload field contains the wrong url

### ISSUE THREAD

**Issue by CamusMX7** [Laravel-Backpack/CRUD#5232]
# Bug report

### What I did

I added the "withFiles" property that includes the path in a subfield of the repeatable field.

`
[  
                    'name'      => 'audioc',
                    'label'     => 'Audio mp3 menor a 4MB',
                    'type'      => 'upload',
                    'withFiles' => [
                        'disk' => 'public', // the disk where file will be stored
                        'path' => 'castings', // the path inside the disk where file will be stored
                    ],
                    'wrapper' => [
                        'class' => 'form-group col-md-2',
                    ]
                ]
`

### What I expected to happen

It will upload the file and show the correct path to the file.

### What happened

In the "href" it repeats the name of the path declared in "withFiles" and therefore the path is incorrect when clicking the link.

### What I've already tried to fix it

Nothing yet

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

backpack/basset: 1.0.0        
backpack/crud: 6.0.6
backpack/generators: v4.0.1   
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.8
backpack/theme-coreuiv2: 1.1.3
backpack/theme-tabler: 1.0.5

![repite path](https://github.com/Laravel-Backpack/CRUD/assets/107073227/9de30a1c-a87d-46bf-b281-3c7bfc94a9f4)

**Comment by pxpm** [comment]
Thanks for the report @CamusMX7 

I fixed a similar issue for "non-repeatable" uploaders last week I guess I missed this usecase. 

I will have a look at it ASAP 👍 

Cheers

**Comment by pxpm** [comment]
Fixed the issue in: https://github.com/Laravel-Backpack/CRUD/pull/5233

Just tagged https://github.com/Laravel-Backpack/CRUD/releases/tag/6.0.7 along with some other fixes. 

Let me know if it still does not work for you @CamusMX7 🙏 

Thanks

**Comment by CamusMX7** [comment]
@pxpm  I keep seeing the same problem with the URL I already had saved (castings/1-1-tSzR.mp3). "The path (castings)" continues to be duplicated.
I tried to generate a new file, but after the upgrade to 6.0.7 two more problems came up.

1) I was retrieving the data in my function `setLocutoresAttribute($value)` because I need to insert the records that can be duplicated in a pivot table. In version 6.0.6 I was receiving a JSON with the corresponding values, now it seems that I am receiving an ARRAY and it does not contain the URL of the UPLOAD field, so I cannot insert the URL into the Database. How should I now retrieve the URL to register in the database? because the value of the field that should have the URL arrives empty. And why the change of how the values of the form are sent from JSON to ARRAY?

2) When I was going to do tests, it sent me a validation message, that a field was missing. The field of a relation, which does have a value but for some reason isn't displaying it:

Controller
```
CRUD::field('customer')->allows_null(true)->wrapper([
             'class' => 'form-group col-md-12 pl-0 pr-0',
         ]);
```

model
```
public function client(): BelongsTo
     {
         return $this->belongsTo(Customer::class);
     }
```

Even in the list it is displayed correctly, but in the form it is not.

![listado](https://github.com/Laravel-Backpack/CRUD/assets/107073227/bb1eb814-dcdf-49c2-bca3-d5507577653d)
![form](https://github.com/Laravel-Backpack/CRUD/assets/107073227/78e7e0ab-190f-44ce-b341-88d876096815)

**Comment by pxpm** [comment]
Hey @CamusMX7 thanks for the report.

But let's not mix issues or it gets very difficult to me to keep up with what you report. 

If needed always open a new issue with a different topic, we don't charge by issues opened 😄 

Let's focus on the upload issue here.

I've just reverted my last PR. And I wasn't able to get json on the setter. 

```php
// the model
protected $fillable = ['name', 'extras', 'meta'];

protected $casts = ['meta' => 'json'];

public function setMetaAttribute($value) {
    dd($value, $this);
}

// the controller
CRUD::field('name')->type('upload')->withFiles(['path' => 'olanina']);
        CRUD::field('meta')->type('repeatable')->subfields([
            [
                'name' => 'test',
                'type' => 'text'
            ],
            [
                'name' => 'test_upload',
                'type' => 'upload_multiple',
                'withFiles' => [
                    'path' => 'testpath'
                ],
            ],
        ]);
``` 
And when I submit the form and `dd()` in `setMetasAttribute` I always get an array:
![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/0f6bce15-b1d0-489f-b8a6-6e6ffa7717f2)

What I am missing @CamusMX7 ?

**Comment by CamusMX7** [comment]
Sorry for mixing issues, but since the update I've been suffering a bit.

Concentrating on the upload field in repeatable. If I use it by saving the json in a field of my database, EVERYTHING works fine, the data is saved, the URL and it shows the url correctly in the form.

But if I try to store in a pivot table now nothing related to the upload field works fine.

DB
```
- castings: id, others
- locutores: id, others
- casting_locutor: id, casting_id, locutor_id, audioc
```

If I insert the url of the file directly into the database, for example in the "audioc" field: "castings/file.mp3" when it is displayed in the form it keeps repeating "castings/castings/file.mp3" which was my initial problem.

Now, with your example trying to replicate the situation, can you delete the url of your file and try getting the new file?
Because the fields are received in the setter, but they are the values that are stored in the database, they are not the new values that are sent from the form. That is, if I try to add a new file, I receive the value that is in the database, not the value that the form sends me. So now I can't save the new file name.

To be clearer, could you print what you receive with the following? and could you confirm that you receive the new value of the upload field and not the value stored in the database?

```
// the model
protected $fillable = ['meta'];

protected $casts = ['meta' => 'json'];

public function setMetaAttribute($value) {
    dd($value, $this);
}

// the controller
CRUD::field('meta')->type('repeatable')->subfields([
    [
        'name' => 'test',
        'type' => 'text'
    ],
    [
        'name' => 'test_upload',
        'type' => 'upload',
        'withFiles' => [
            'path' => 'testpath'
        ],
    ],
]);
```

**Comment by pxpm** [comment]
Hey @CamusMX7 thanks for getting back.

I could reproduce your issue and I am working on the fix. https://github.com/Laravel-Backpack/CRUD/pull/5243

The previous fix I made like you said, only accounted for `repeatables` not `relations`. You are working with a BelongsToMany relationship, and that needs some special handling.

I am almost done, If I have a little time during this weekend I may be able to finish it, otherwise I finish it at the beginning of next week. 

Thanks again 🙏

**Comment by CamusMX7** [comment]
Hello @pxpm , Is there any news about this? I see that it is marked as closed, but I never found a solution.
I even changed my implementation for other themes. I neutralized the `setMetaAttribute` and now save the relationship fields from

```
Casting::saved(function($entry) {
             $request = $this->crud->getRequest()->request->all();
             dd($request);
}
```


But I still can't get the URL to store it in the database.
In other words, the file is still being sent correctly to the specified path, but I can't link to it because I can't get that URL to store in the database.

Thanks.
