### ISSUE TITLE
[Bug] Class "Assets" not found Backpack V5 Laravel 9

### ISSUE THREAD

**Issue by Esh-network** [Laravel-Backpack/CRUD#5240]
# Bug report

### What I did

I only add the intervention/image package & continue to work on my front, after having been on my back and in the list of users I have the error which indicates: Class "Assets" not found, I also wanted to go directly to the user edition & same error

### What I expected to happen

I just wanted to go modify a user

### What happened

<a href="https://ibb.co/CWFtt0G"><img src="https://i.ibb.co/mS7BBzW/chrome-3lbq-TFQ7ug.png" alt="chrome-3lbq-TFQ7ug" border="0"></a>

<a href="https://ibb.co/qstR4qJ"><img src="https://i.ibb.co/Wybcd8V/chrome-i7-OWBz-N0ca.png" alt="chrome-i7-OWBz-N0ca" border="0"></a><br /><a target='_blank' href='https://usefulwebtool.com/fr/clavier-russe'>alphabet russe cursive</a><br />

### What I've already tried to fix it

I updated the composer, & I added the digitallyhappy/assets package which already exists

### Is it a bug in the latest version of Backpack?

I don't know

### PHP VERSION:
PHP 8.1.9 (cli) (built: Aug  2 2022 14:17:33) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.52.12@8bfd22be79f437fa335e70692e4e91ff40ce561d

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.1
backpack/devtools: 1.3.5
backpack/editable-columns: 2.1.5
backpack/generators: v3.3.17
backpack/permissionmanager: 6.0.17
backpack/pro: 1.6.6

Accuracy :

 "digitallyhappy/assets": "^2.0.1", Composer.lock
 "digitallyhappy/assets": "^2.1", composer.json

**Comment by Esh-network** [comment]
I actually upgraded the package to version 2.0.4 and it works.

THANKS

**Comment by pxpm** [comment]
Hey @dauvray 

You maybe using a mix of incompatible packages. 

@bassetBlock was introduced only in basset package: https://github.com/Laravel-Backpack/basset that came along with Backpack v6. 

This is a v5 issue, we no longer use the `digitally-happy/assets` package. 

If you are experience a similar issue, please feel free to open a new issue, and provide your package versions with: `php artisan backpack:version`

Cheers

**Comment by dauvray** [comment]
so we can't use backpack/pro v5 with backpack V6 ?
