### ISSUE TITLE
[Bug] Error 'The name is already used' on crud update 

### ISSUE THREAD

**Issue by AndreNeny** [Laravel-Backpack/CRUD#5241]
# Bug report

### What I did

my model has two keys :
primary key Id
unique key chantiers_nom_unique (firm_code + chantier_name) 
nothing special on standard crud, no implementation of the save method.

### What I expected to happen
standard crud update () when another field (not firm_code or chantier_name) is modified in the model
and message "item has been updated with success"

### What happened
Error "The name already used" 

### What I've already tried to fix it
/
### Is it a bug in the latest version of Backpack?
I don't think so but my double key is recent.

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version
        "backpack/crud": "5.1.2",
        "backpack/logmanager": "^4.0",
        "backpack/permissionmanager": "^6.0",
        "backpack/pro": "^1.0",

        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "laravel/ui": "^3.4",

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.20 (cli) (built: Jun  7 2023 08:21:17) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.17.0@091e287678ac723c591509ca6374e4ded4a99b1c

### BACKPACK VERSION:
5.1.2@a15f93a784e8d130f5ea5c3341fb7bca1f3c25e3

Thank's to look at this !

**Comment by AndreNeny** [comment]
my rules on ChantiersRequest  
public function rules()
    {
        return [
            'nom'       => [
                'required',
                'min:3',
                'max:40',
                Rule::unique('chantiers')->where(function ($query) {        // Clé unique composée : societe_id + nom
                    return $query->where('societe_id', $this->societe_id);
                }),
            ],
            'image'     => 'max:65535',
            'latitude'  => 'required|numeric',
            'longitude' => 'required|numeric'
        ];
    }

**Comment by jorgetwgroup** [comment]
Hello @AndreNeny i dont think this is a backpack bug because is about rules, Backpack didnt handle it:

if i see your rules did you try with ignore?

```
public function rules()
{
return [
  'nom' => [
  'required',
  'min:3',
  'max:40',
  Rule::unique('chantiers')->where(function ($query) { // Clé unique composée : societe_id + nom
  return $query->where('societe_id', $this->societe_id)->ignore([here_the_current_id]);
  }),
  ],
  'image' => 'max:65535',
  'latitude' => 'required|numeric',
  'longitude' => 'required|numeric'
  ];
}
```

Cheers.

**Comment by pxpm** [comment]
Doing a cleanup of stalled issues. 

Please @AndreNeny report back if you were not able to fix it and we can re-open this.

Cheers

**Comment by AndreNeny** [comment]
Hello Jorge,
Thanks a lot for your response. I will try - ignore as soon as possible.

Cheers,
André Nény

**Comment by AndreNeny** [comment]
Hello Jorge, That's good with your advice. Thank's a lot !
