### ISSUE TITLE
[Bug] Specifying columns in setupListOperation breaks search unless searchLogic is explicitly set

### ISSUE THREAD

**Issue by colincameron** [Laravel-Backpack/CRUD#5251]
# Bug report

### What I did

When setting up my CRUDs, I found they aren't searchable - typing in the search field just returns all entries.

As a minimal example:

With a fresh installation, run `php artisan backpack:crud user` - the columns are set from DB and search works as expected.

Change `setupListOperation()` to contain the single line:

    CRUD::column('email')->type('string');

### What I expected to happen

The table shows just email addresses for all users, and typing in the search field will filter this list by email.

### What happened

No matter what I type, all entries are shown.

### What I've already tried to fix it

Explicitly specifying `searchType` fixes this, and the search works as expected.

    CRUD::column('email')->type('string')->searchLogic('text');

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.5 (cli) (built: Apr 13 2023 18:27:51) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.13.5.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.2
backpack/crud: 6.1.2
backpack/generators: v4.0.2
backpack/pro: 2.0.9
backpack/theme-tabler: 1.0.6

**Comment by pxpm** [comment]
Hey there @colincameron 

We don't have any column `type => 'string'`. That's why the `searchLogic` is not being applied. (we don't know that column type).

Change it to text, and the `text` `searchLogic` would apply. 

I don't think there is any bug here. Please re-open if I am wrong. 

Cheers

**Comment by colincameron** [comment]
Thanks. That's embarrassing, I've no idea how I got the wrong column type sorry.

**Comment by pxpm** [comment]
> Thanks. That's embarrassing, I've no idea how I got the wrong column type sorry.

No issues. I've done worst things than that. It happens. 🙃 

Let us know if we can help you with something else 🙏
