### ISSUE TITLE
[Bug] Can't change the model attribute when using "relationship" crud field on create crud

### ISSUE THREAD

**Issue by Astriel** [Laravel-Backpack/CRUD#5252]
# Bug report

### What I did

I've generated a CrudController with the `php artisan backpack:build` command
On the CrudController, in the `setupCreateOperation` method, I've set a "relationship" field which is corresponding to a many to many relation. This works fine and I'm able to select it on the screen, but when I want to change the "attribute" to showcase another value from my model it's not working.

        CRUD::field([
            'name'        => 'myrelation',
            'type'          => 'relationship',
            'tab'           => __('backpack.ats'),
            'model'         => 'App\Models\V0\Mymodel',
            'label'         => __('backpack.firsttab'),
            'attribute'     => 'version', // The problem is that here, whatever I try to type, it's always fetching for the name attribute on my model
             'pivot'         => true,
            'subfields'   => [
                [
                    'name' => 'first_field',
                    'label'      => __('backpack.first_field'),
                    'type'       => 'text',
                    'tab'        => __('backpack.firsttab'),
                    'hint'       => __('backpack.first_field_hint'),
                    'wrapper' => [
                        'class' => 'form-group col-md-6',
                    ],
                ],
            ],
        ]);

### What I expected to happen

With the following code and the following field define, I would expect to have the "version" attribute used into the select input generated with the crud.

### What happened

Whatever I try, the CRUD field is always going to fetch for the "name" attribute of my model.

### What I've already tried to fix it

I've already tried to switch to other fields such as 

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
**Yes**

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.16.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.2
backpack/crud: 6.1.1
backpack/devtools: 2.0.3
backpack/generators: v4.0.2
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.10
backpack/theme-coreuiv4: 1.0.5
```

**Comment by Astriel** [comment]
Sounds like it's really similar to the following issue [https://github.com/Laravel-Backpack/CRUD/issues/5220](url)

**Comment by pxpm** [comment]
Like I said to you, and pointed in the last comment. In a n-n relationship, you should configure the attribute in your `pivotSelect` field. What I am missing, did you tried it ? 

```php
CRUD::field([
        // adding here for clarity:
        'pivotSelect' => [
            'attribute' => 'version'
        ]
        'name'        => 'myrelation',
        'type'          => 'relationship',
        'tab'           => __('backpack.ats'),
        'model'         => 'App\Models\V0\Mymodel',
        'label'         => __('backpack.firsttab'),
         'pivot'         => true,
        'subfields'   => [
            [
                'name' => 'first_field',
                'label'      => __('backpack.first_field'),
                'type'       => 'text',
                'tab'        => __('backpack.firsttab'),
                'hint'       => __('backpack.first_field_hint'),
                'wrapper' => [
                    'class' => 'form-group col-md-6',
                ],
            ],
        ],
    ]);
```
Let me know if that doesn't help. 

Thanks 🙏

**Comment by pxpm** [comment]
Can you provide a screenshot or something of what you mean ? 

My guess is that when you `setEntityNameStrings` (single/plural) we use the Laravel singular/plural helpers and it converts the singular of `ats` to `at`. 

Let me know! 🙏
