### ISSUE TITLE
[Bug] Tabs on hebrew not working

### ISSUE THREAD

**Issue by delfinn55** [Laravel-Backpack/CRUD#5256]
# Bug report

### What I did

I created some fields with different 'tab' values in setupCreateOperation() method:
```php
CRUD::addField([
    'tab' => __('admin.auctions.tabs.first'),
    'name' => 'user',
    'label' => __('admin.auctions.fields.user'),
]);
CRUD::addField([
    'tab' => __('admin.auctions.tabs.second'),
    'name' => 'status',
    'label' => __('admin.auctions.fields.status'),
]);
```

It use lang files 
```php
'tabs' => [
    'first' => 'ראשון',
    'second' => 'שני',
],

```

### What I expected to happen

I expected tabs to work the same as when using English.

### What happened

The content of the first tab opens. When clicking on other tabs, the content does not change.

### What I've already tried to fix it

I fixed it, but it doesn't look like the best solution. I copied "crud/inc/show_tabbed_fields.blade.php" to app resources folder and move translation wrapper to this file:
```html
<a href="#tab_{{ Str::slug($tab) }}"
    aria-controls="tab_{{ Str::slug($tab) }}"
    role="tab"
    tab_name="{{ Str::slug($tab) }}"
    data-toggle="tab"
    class="nav-link {{ isset($tabWithError) && $tabWithError ? ($tab == $tabWithError ? 'active' : '') : ($k == 0 ? 'active' : '') }}"
    >{{ __('admin.auctions.tabs.' . $tab) }}</a>
```

### Is it a bug in the latest version of Backpack?

Still doesn't work.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.4 (cli) (built: Apr  3 2023 12:58:01) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v9.52.7@675ea868fe36b18c8303e954aac540e6b1caa677

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.1
backpack/devtools: 1.3.5
backpack/filemanager: 2.0.1
backpack/generators: 3.3.16
backpack/langfilemanager: 4.1.0
backpack/logmanager: v4.0.10
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.4
backpack/settings: 3.0.16

**Comment by pxpm** [comment]
I've investigated this a bit. 

This may require a rework on tabs to fully support some more exotic languages. 

The only way I found was with a BC by introducing the `tab_hash` mentioned in previous comment. 

I created a branch with some tests I've been doing, I am not sure we can find a non-breaking way of supporting this. 

https://github.com/Laravel-Backpack/CRUD/tree/revamp-tabs

**Comment by delfinn55** [comment]
> I've investigated this a bit.
> 
> This may require a rework on tabs to fully support some more exotic languages.
> 
> The only way I found was with a BC by introducing the `tab_hash` mentioned in previous comment.
> 
> I created a branch with some tests I've been doing, I am not sure we can find a non-breaking way of supporting this.
> 
> https://github.com/Laravel-Backpack/CRUD/tree/revamp-tabs

Hello!
`tab_hash` is great solution and it will resolve the issue of course.

**Comment by pxpm** [comment]
We've talked about this in our team meeting. 

We talked about making the tabs "indexed" when they can't be parsed by `Str::slug()`. So we would generated the tab #hash from the tab index in the array of tabs.

That way we keep the ability to use the url to navigate to specific tabs and may introduce this fix without any BC.

**Comment by pxpm** [comment]
Thanks for the report @delfinn55 I've just released a new CRUD version that address this issue. https://github.com/Laravel-Backpack/CRUD/releases/tag/6.1.7

Do a `composer update` to get the latest version and let me know if your problem is fixed 🙏 

Cheers
