### ISSUE TITLE
[Bug] Fresh install on Ubuntu 22.04 LTS makes 500 Error

### ISSUE THREAD

**Issue by lebedynskyi** [Laravel-Backpack/CRUD#5257]
# Bug report

### What I did

I just create a project via 
`composer create-project laravel/laravel lessons-app`

Configured DB settings in .env

installed Backpack CRUD via
```
composer require backpack/crud
php artisan backpack:install
```

Thats IT
Here is ouput with red arrow meaning that php artisan finished with error
![image](https://github.com/Laravel-Backpack/CRUD/assets/58213750/a2c77e5f-0471-463c-aa2c-22ff2b0b844c)

### What I expected to happen

During installation Backpack should ask for user creation Default admin user.

### What happened

The installation is fininshed with Step1 and thats it. We see red arrow- it measn process finished with error

### What I've already tried to fix it

- Check logs in storage/logs/* -it is empty
- Created new empty project - no luck
- Removed and created DB in mysql

### Backpack, Laravel, PHP, DB version

I have a vps on Digital Ocean running Ubuntu 22.04 LTS with next installed soft:
php 8.1
Node 18.17
Composer version 2.5.8 2023-06-09 17:13:21

**All commands was run under root user** via SSH

### PHP VERSION:
PHP 8.1.2-1ubuntu2.13 (cli) (built: Jun 28 2023 14:01:49) (NTS)
Copyright (c) The PHP Group                                                  
Zend Engine v4.1.2, Copyright (c) Zend Technologies                          
    with Zend OPcache v8.1.2-1ubuntu2.13, Copyright (c), by Zend Technologies
                                                                             
### LARAVEL VERSION:                                                         
10.17.0.0                                                                    

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.0
backpack/crud: 6.1.2
backpack/generators: v4.0.2

**Comment by pxpm** [comment]
Hello @lebedynskyi 
I've released a new basset and crud versions with the fix. 

Thank you so much for the report, and sorry for the bad experience. 

Let me know if you still experiencing problems regarding this and we can re-open. 

Cheers
