### ISSUE TITLE
Upload multiple not save the file 

### ISSUE THREAD

**Issue by divanski** [Laravel-Backpack/CRUD#526]
I need to create page template whit upload_multiple field type but something not Ok.

In my PageTemplate.php I use this:
```php
$this->crud->addField([
                        'name' => 'photos',
                        'label' => 'Photos',
                        'type' => 'upload_multiple',
                        'upload' => true,
                        'disk' => 'uploads',
                        'fake' => true,
                        'store_in' => 'extras',
                    ]);
```

In my model Page.php I use this:
```php

protected $casts = [
        'photos' => 'array'
    ];

```
And Mutator:
```php
public function setPhotosAttribute($value)
    {
        $attribute_name = "photos";
        $disk = "uploads";
        $destination_path = "page/gallery";
    
        $this->uploadMultipleFilesToDisk($value, $attribute_name, $disk, $destination_path);
    }
```

When I try to create new page the image file can't upload in the folder and in DB table "page" in column 'extras' the data is like this:
```json
{
"photos":[
               {},
               {}
           ]
}
```

I can't understand where I wrong?

**Comment by MarcosBL** [comment]
Not sure if [upload_multiple](https://laravel-backpack.readme.io/docs/crud-fields#section-upload_multiple) supports **fake** fields and **store_in**, at least for the docs, can only point (just in case you didn't try yourself) that using a regular field, upload_multiple works like a charm

**Comment by MarcosBL** [comment]
Maybe related to https://github.com/Laravel-Backpack/CRUD/pull/520 ?

**Comment by divanski** [comment]
I try without 'fake' and 'store_in' but in this case noting to save in database. I can't understand - may be for first time I use uploads whit Laravel 5.4 or may be PageTemplate can't use this type of field :(

**Comment by lloy0076** [comment]
Not sure if this is a bug or question so now it's BOTH!

**Comment by lloy0076** [comment]
Closing due to lack of info - tracked elsewhere as well.
