### ISSUE TITLE
[Bug][v6.x] https error 

### ISSUE THREAD

**Issue by rezahmady** [Laravel-Backpack/CRUD#5260]
When I put the project on the server, there is no problem with http. But when it becomes https, the cruds don't load properly, like search, which is called in the list operation, it is called with http route, the address gives an error, and as soon as I active 'force redirect http to https ' server doesn't come up.
I set the address value in .env correctly.

**Comment by pxpm** [comment]
Hey @rezahmady thanks for the report.

Please can you run `php artisan basset:check` and follow the instructions if there is any issue ? 

If nothing works, please provide me:
- `php artisan backpack:version` output
- your `.env` APP_URL config
- a screenshot/copy past of any errors you got in browser console.

Cheers

**Comment by rezahmady** [comment]
![image](https://github.com/Laravel-Backpack/CRUD/assets/24762569/c49e5fcc-c41a-4778-8827-956e4c815800)

**Comment by rezahmady** [comment]
APP_URL=https://dev.ghadirtv.com

admin:
0912000000
password

**Comment by pxpm** [comment]
Hello @rezahmady 

I am not able to reproduce your issue.

I changed APP_URL to serve via `https://agromanger.test` (it was http://agromanager.test before).

Did a `php artisan basset:fresh`
´
The search endpoint is being fetched with https: 
![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/9fefa5be-d42e-41ce-b9ea-2ac87e4457d5)

I didn't add the `Url::forceScheme` or anything similar. 

What am I missing here? 

Cheers

**Comment by rezahmady** [comment]
when I open first time 
This error occurs :
`cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://unpkg.com/@coreui/coreui@2.1.16/dist/js/coreui.js`
When you refresh the page, it no longer shows the error
whene run `php artisan basset:fresh` in cli:
![image](https://github.com/Laravel-Backpack/CRUD/assets/24762569/7a7a1c57-f33d-43c8-8618-53712870b7a3)

**Comment by tabacitu** [comment]
@rezahmady 

1. From your browser screenshot it looks to me like you have a lot of custom HTML & CSS in your interface. Right? Is it possible that you've loaded jQuery or something else from an HTTP link and not an HTTPS one? That would explain your error message in Chrome DevTools. 

2. It also looks to me like the app URLs themselves use HTTP, not HTTPS. So it seems like your Laravel app is not properly configured to serve HTTPS. Please google it, many solutions online.

3. About the timeout, please run `php artisan basset:check` and copy-paste the output here.

**Comment by pxpm** [comment]
Doing a clean up. 

Please report back if you are still experiencing the issue. 🙏 

Cheers
