### ISSUE TITLE
[Bug] When  backpack fires an abort, the message isn't showed !

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#5263]
# Bug report

### What I did

I caused a server error using this wrong code

```
        Crud::field([
           'name' => 'address_annuality_pairs',
           'entity' => 'address_annuality_pairs',
           'type' => 'relationship',
           'pivotSelect' => [
               'attribute' => 'entry_composite_label',
           ],
           'subfields' => [
              
                'name' => 'skills',
                'type' => 'textarea',
         
           ],
        ]);
```

### What I expected to happen

I expected a NORMAL laravel error page, because in development we NEED to see stacktrace.

Anyway, I kindly suggest to check if 'subfields' contains an _array of array and, if not, throw an Exception, and not an abort, with an usefull infos.

I kindly suggest to switch from abort to Throwable if we are in local environment. an abort is useless.

### What happened

I can see  [in local environment with debug activated] only this

![image](https://github.com/Laravel-Backpack/CRUD/assets/1268699/33ac4b6a-1a79-4ca7-a477-be2d6b160c85)

This is thrown by `vendor/backpack/crud/src/app/Library/CrudPanel/Traits/FieldsProtectedMethods.php`, in the method `makeSureFieldHasName`, at firs check 
```

        if (empty($field)) {
            abort(500, 'Field name can\'t be empty');
        }

```

As you can see, the error could be [a little] usefull to understand what is happening, but the theme is ignoring the abort message at all.

### What I've already tried to fix it

I followed the code to see what's the problem, than fixed the syntax.

### Is it a bug in the latest version of Backpack?

Yes

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.2.8 (cli) (built: Jul  4 2023 15:53:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.17.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.1
backpack/crud: 6.1.4
backpack/generators: v4.0.2
backpack/pro: 2.0.10
backpack/theme-tabler: 1.0.6
```

**Comment by karandatwani92** [comment]
Thanks for reporting the issue you found, I agree with you. 
We will come up with a fix soon

**Comment by tabacitu** [comment]
@karandatwani92 what's the plan here?

**Comment by karandatwani92** [comment]
@tabacitu 
The message which comes with abort() is pretty straight But a user needs the line no & the file path with it in debug env. 

@pxpm recently added the same info on an abort() in a [recent PR.](https://github.com/Laravel-Backpack/CRUD/pull/5212) I think we should do the same thing here.

**Comment by tabacitu** [comment]
Update: we've decided to check if `subfields` is an array of arrays, and if not, throw an abort for that particular user error. @pxpm is on it. That way the abort will be useful.

> I kindly suggest to switch from abort to Throwable if we are in local environment. an abort is useless.

Regarding this, we do plan to change all aborts to a custom exception in the future, thanks for the feedback.

**Comment by pxpm** [comment]
I've added better debug messages to subfields in #5279 

We will revisit it when we change it to exceptions. 

Cheers
