### ISSUE TITLE
Only show field when another field value is true

### ISSUE THREAD

**Issue by baj84** [Laravel-Backpack/CRUD#527]
When adding a new item, i'd like to only show input field 'X' when 'Y' has been selected.

Is this currently possible via the addField() method? Or would the only way be with my own custom javascript injected in?

Thanks!

**Comment by MarcosBL** [comment]
There is a "toggle" field just for that, developed by @OwenMelbz in https://github.com/Laravel-Backpack/CRUD/pull/165 , but is not merged yet

I just copied [the file](https://raw.githubusercontent.com/Laravel-Backpack/CRUD/0396774764df4adc3a87cd2d7fc46fd7fb21475f/src/resources/views/fields/toggle.blade.php) proposed (as a custom template) in my own backpack space at **resources/views/vendor/backpack/crud/fields/toggle.blade.php** and started using it as per Owen instructions, worked great. 

Usage: (**angry** is a boolean, **why** and **what_can_we_do** are varchar in my example)

````php
$this->crud->addField(
[
	'label' => 'Are you angry?',
	'name' => 'angry',
	'type' => 'toggle',
	'inline' => true,
	'options' => [
		0 => 'No',
		1 => 'Si'
	],
	'hide_when' => [
		0 => ['why', 'what_can_we_do'],
		],
	'default' => 0
]);

$this->crud->addField([ 'label' => "Why?", 'type' => 'text', 'name' => 'why', 'both');

$this->crud->addField([ 'label' => "What can we do?", 'type' => 'text', 'name' => 'what_can_we_do', 'both');

````

**Comment by baj84** [comment]
That's perfect - thanks for your help

**Comment by oscarmlage** [comment]
+1 Worked here too, just keep in mind that if you're using iCheck you need to add 165#issuecomment-281473011 in your document.ready

**Comment by conandor** [comment]
The 'default' setting not working. can someone verify?

**Comment by OwenMelbz** [comment]
@conandor been working for a while, so most likely a usage problem, can you share the code your using and show us the html its generated (not the whole document, just around the problem area)

**Comment by conandor** [comment]
The CRUD:

[image: Inline image 1]


The HTML:

[image: Inline image 2]

**Comment by OwenMelbz** [comment]
@conandor that didnt work :)

**Comment by conandor** [comment]
What method can I use to set the default choice.
