### ISSUE TITLE
[Inconsistency]  - Installing Backpack without a theme breaks it.

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/CRUD#5274]
# Bug report

### What I did

A user reported in https://github.com/Laravel-Backpack/community-forum/discussions/616#discussioncomment-6691214 and I tried to reproduce it.

Created a new Backpack project, and didn't select any theme. 
Tried to access the admin panel and was greeted with a 500 error.

Backpack should not break if no theme is installed, or we should force at least one theme to be installed. 

Allowing no theme and breaking is not correct I think.

**Comment by tabacitu** [comment]
I guess we could:
- (a) in the installation wizard, do not let people choose nothing; force them to choose a theme;
- (b) throw an error if `config('backpack.ui.view_namespace')` is chosen, but that view namespace hasn't actually been registered; something like "_The Backpack theme you are using has not been installed. Please run `php artisan backpack:install` and choose a theme to install_"

I would be ok with (a) alone, to be honest.

**Comment by pxpm** [comment]
> I guess we could:
> 
> * (a) in the installation wizard, do not let people choose nothing; force them to choose a theme;
> * (b) throw an error if `config('backpack.ui.view_namespace')` is chosen, but that view namespace hasn't actually been registered; something like "_The Backpack theme you are using has not been installed. Please run `php artisan backpack:install` and choose a theme to install_"
> 
> I would be ok with (a) alone, to be honest.

I was thinking about 1 too, we are on the same boat here 🙏 

Will do the changes accordingly.
