### ISSUE TITLE
Saving doesn't work.

### ISSUE THREAD

**Issue by christopher-wilson** [Laravel-Backpack/CRUD#528]
I believe it is this line in `src/app/Http/Controllers/CrudController.php:117`.

`$item = $this->crud->create($request->except(['save_action', '_token', '_method']));`

The error message is as follows:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'redirect_after_save' in 'field list' (SQL: insert into...`

There is nothing that removes `redirect_after_save` from the create method. It does remove a `save_action` field, but there is none in my crud page, even after running a `composer update`

**Comment by RedocTsuj** [comment]
Why was this issue closed ?
