### ISSUE TITLE
[Bug] Base table or view not found: 1146 Table 'backend.users' doesn't exist

### ISSUE THREAD

**Issue by gleb-svitelskiy** [Laravel-Backpack/CRUD#5281]
# Bug report

### What I did

I changed the default Backpack user model in the `config/backpack/permissionmanager.php` file.

### What I expected to happen

When I create a new user, I expect a new record to be created in the users' table. The table must be obtained from the configuration.

### What happened

An error occurs: `Base table or view not found: 1146 Table 'backend.users' doesn't exist`.

### What I've already tried to fix it

Yes, here is [the pull request](https://github.com/Laravel-Backpack/PermissionManager/pull/337).

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
```
### PHP VERSION:
PHP 8.2.9 (cli) (built: Aug 16 2023 19:49:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.9, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.19.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.1
backpack/crud: 6.1.9
backpack/generators: v4.0.2
backpack/permissionmanager: 7.0.0
backpack/theme-tabler: 1.0.11
```

**Comment by pxpm** [comment]
Thanks for the PR and the report @gleb-svitelskiy 

Unfortunately I can not merge it as it does not address your issue. 

You should change the table names in the config file `permission.php` (the one from spatie package). If you don't have that file you can publish it with: `php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="permission-config"` as stated in the docs. 

Hope it helps.

Cheers

**Comment by gleb-svitelskiy** [comment]
Thanks for the advice, @pxpm. This will really help.

But now `spatie/laravel-permission` package is not limited to one specific model for assigning permissions or roles. The package uses polymorphic relationships to assign permissions or roles.

And `permission.table_names.users` configuration key has been [removed from the config file](https://github.com/spatie/laravel-permission/commit/ad04972659615de6c2cdf7a4c99195ed155dcf66#diff-ca8aa0052ae124a1ec04dd8d7e2bb45a7bc9b57bf836afc5d8fda81e44297e3dL38).

According to `backpack/permissionmanager` package documentation, there is a configuration key that sets the Backpack user model (`backpack.permissionmanager.models.user`).
`backpack.permissionmanager.models.user` configuration key is set by `backpack.base.user_model_fqn` configuration key.
`backpack.base.user_model_fqn` configuration key is set by `auth.providers.users.model`.

If `Backpack\PermissionManager` add-on is designed to create (manage) Backpack users. And assigning (managing) the permissions and roles of these users. It is perfectly logical to use `backpack.permissionmanager.models.user` configuration key to define the Backpack user model.

Unless, of course, you have some plans to refactor configuration keys that I don't know about.

**Comment by pxpm** [comment]
Hey @gleb-svitelskiy thanks for the details. I was not aware of that change in spatie.

I will re-open and re-investigate this better tomorrow. 

Cheers

**Comment by pxpm** [comment]
re-opened PR https://github.com/Laravel-Backpack/PermissionManager/pull/337

Let's keep any conversation about this over there 🙏
