### ISSUE TITLE
[Bug] visibleInModal not working anymore 

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#5282]
# Bug report
The `visibleInModal` parameter is not working anymore with v6.
It seems that the modal is not there anymore.

https://backpackforlaravel.com/docs/6.x/crud-columns#choose-where-columns-are-visible
### What I did

Just upgraded from v5 to v6.

### What I expected to happen

I expected it to work like the previous version.

### What I've already tried to fix it

--

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.19.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.1
backpack/crud: 6.1.10
backpack/generators: v4.0.2
backpack/pro: 2.0.11
backpack/theme-tabler: 1.0.11
```

**Comment by pxpm** [comment]
Hey @EmanueleCoppola thanks for the question. 

Can you provide a little bit more info ? Maybe the column definition, and/or some screenshots of what's missing/broken ?

I've tested this with: 
```php
 $this->crud->addColumn([
            [
                'name'  => 'text',
                'tab'   => 'Simple',
                'visibleInModal' => false,
            ],
]);
```
![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/4b31871c-048b-4ad9-825a-517981cf3c43)

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/856bbd6c-8f9f-4d37-9485-cd3953c1e5e7)


Let me know how it goes. 

Cheers

**Comment by pxpm** [comment]
Closing this. We've found a bug while testing this #5284 that we are fixing in #5287 so thanks @EmanueleCoppola 🙏 

Let me know if it still don't work for you, post some more details about your project so that I can help you better. 
Overwritten views is a good starting point to check for.

Cheers
