### ISSUE TITLE
[Bug] showDeleteButton is gone

### ISSUE THREAD

**Issue by malek77z** [Laravel-Backpack/CRUD#5285]
# Bug report

This is 6.1.10

It seems like the code to enable deleting on the forms i.e. showDeleteButton  is gone.

I've not seen how deep it goes but:
vendor\backpack\crud\src\resources\views\crud\inc\form_save_buttons.blade.php

does not have the code in it anymore for the button or the script.

This seems simple to fix as put it back in from 5.6.1 and seems to work.
https://github.com/Laravel-Backpack/CRUD/blob/5.6.1/src/resources/views/crud/inc/form_save_buttons.blade.php

**Comment by pxpm** [comment]
Hey @malek77z for me the code still there in the main branch: https://github.com/Laravel-Backpack/CRUD/blob/96ac869f152a763a6956c10f9f7e1e164e613a4b/src/resources/views/crud/inc/form_save_buttons.blade.php#L27

what do you mean ? 

Cheers

**Comment by malek77z** [comment]
If you see this ( 5.6.1 https://github.com/Laravel-Backpack/CRUD/blob/5.6.1/src/resources/views/crud/inc/form_save_buttons.blade.php ), line 33 to 35, and 118 onwards

**Comment by pxpm** [comment]
Thanks @malek77z I get it now, the delete button on the entry update. 🙏 

I am on it! 

We should have this fixed in a few moments! 

Cheers
