### ISSUE TITLE
[Bug] Undefined array key 1 when trying to display a decimal column

### ISSUE THREAD

**Issue by surajabc** [Laravel-Backpack/CRUD#5288]
# Bug report

### What I did

I am not sure if this is a bug or whether I did something wrong. I have a model Price, which has a field named price. This is the $casts array in the model file:

`protected $casts = [
        'id' => 'integer',
        'price' => 'decimal',
        'season_id' => 'integer',
        'rentalPeriod_id' => 'integer',
        'boat_id' => 'integer',
    ];`

In the setupCreateOperation in the controller file I have added the field as:

`CRUD::field([
            'name'          => 'price',
            'label'         => __('price'),
            'prefix'        => '€',
        ]);`

And in the setupListOperation as:

CRUD::column('price');

### What I expected to happen

When I go to the list with prices, I expect to see the price I just created.

### What happened

I receive an error telling me that **Undefined array key 1**. The issue is, is that it crashes at **app/Http/Middleware/CheckIfAdmin.php: 66** and it is unclear to me which array it is trying to access. I have also shared the error on flareapp.io - https://flareapp.io/share/oPR0XXK5#debug

This only happens when I add the price column in the setupListOperation function. Any other column is displayed without any issues.

### What I've already tried to fix it

I have tried to trace the error, but it sent to through so many Backpack and Laravel files that I'm not sure where to look and it this is an error on my part or a bug in Backpack or Laravel. With dd() I have tried to see if I could see anything strange in price column itself, but  it seems fine as far as I can see.

### Is it a bug in the latest version of Backpack?

I am running the latest version of Backpack.

### Backpack, Laravel, PHP, DB version

**Backpack packages**

- backpack/basset: 1.1.1
- backpack/crud: 6.1.12
- backpack/generators: v4.0.2
- backpack/theme-tabler: 1.0.12

Laravel 10.19.0.0

PHP 8.1.18

MySQL server version 5.7.29

**Comment by surajabc** [comment]
Hi @tabacitu ,

Thank you for answering my question.

I have renamed the column price to rental_price in the table Price and recreated a new version of the application with Blueprint and Backpack. So I basically have a clean install.

In the setupCreateOperation function in the Price controller, I have defined the rental_price field as:

`
CRUD::field([
            'name'          => 'rental_price',
            'label'         => __('price'),
            'type'          => 'number',
            'attributes'    => ['step' => 'any'],
            'prefix'        => '€',
        ]);
`

And the column in the setupListOperation function as:

`CRUD::column('rental_price')->type('number');`

Unfortunately I still get the same error: https://flareapp.io/share/NPGpy897

I now also noticed that when I try to edit the entry, I receive the same error. So I only receive the error after I have given the field a value. Creating a new entry works as expected and I can see the entry in the database:

+----+--------------+-----------+-----------------+---------+---------------------+---------------------+
| id | rental_price | season_id | rentalPeriod_id | boat_id | created_at          | updated_at          |
+----+--------------+-----------+-----------------+---------+---------------------+---------------------+
|  1 |        50.00 |         1 |               1 |       1 | 2023-08-25 11:15:57 | 2023-08-25 11:15:57 |
+----+--------------+-----------+-----------------+---------+---------------------+---------------------+

Would you perhaps have any other suggestions?

**Comment by surajabc** [comment]
@tabacitu , I just wanted to let you know that I made it work. I rebuild my application again, but I edited my draft.yml where I specified that the column rental_price of type decimal, had a precision of 8 and 2 decimals. Before I only defined the type. And now it works.

**Comment by pxpm** [comment]
Thanks for reporting back @surajabc with the fix. 

I am sure it will help more people in the future 🙏 

Cheers
