### ISSUE TITLE
[Feature Request] set `$segment` for fetchOperations

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/CRUD#5291]
# Feature Request

### What's the feature you think Backpack should have?

I try to explain my situation.

Our admin panel is huge and complex and so we grouped routes.
Every controller group has a prefix and a name
So we have routes like users/activity/create
instead of activity/create
and names of users.activity.create
instead of activity.create

So in un activity controller we have 

```
CRUD::setRoute(config('backpack.base.route_prefix') . 'users/activity');
```

But when we use fetchOperations, we loose the name.

we have `users/activity/fetch/students` named only as `activity.fetchStudents`

The problem is: we have also an ActivityController under `manager` (name and prefix). 
In this 2nd controller, in a different folder and namespace, we CANNOT have another specific `fetchStudents` function because this will always create a route named `activity.fetchStudents` 

So i think that 
1. setupFetchOperation should take in care what setRoute has already setup instead of using only singular entity name as segment
2. a documented way to workarounde this

### Have you already implemented a prototype solution, for your own project?

I actually workaround overriding `setupFetchOperationRoutes`

### Do you see this as a core feature or an add-on?

fetch it's already part of pro addon

**Comment by pxpm** [comment]
Hey @realtebo I've been investigating the possibility you proposed and it's not feasible. We already pass the `$segment` into fetch operation route setup: 
```php
protected function setupFetchOperationRoutes($segment, $routeName, $controller)
    {
        // get all method names on the current model that start with "fetch" (ex: fetchCategory)
        // if a method that looks like that is present, it means we need to add the routes that fetch that entity
        preg_match_all('/(?<=^|;)fetch([^;]+?)(;|$)/', implode(';', get_class_methods($this)), $matches);

        if (count($matches[1])) {
            foreach ($matches[1] as $methodName) {
                Route::post($segment.'/fetch/'.Str::kebab($methodName), [
                    'as'        => $segment.'.fetch'.Str::studly($methodName),
                    'uses'      => $controller.'@fetch'.$methodName,
                    'operation' => 'FetchOperation',
                ]);
            }
        }
    }
```
At the time the routes are setup the `setRoute()` in `setup()` hasn't run yet. 

I think the "easy" workaround is to name your fetch methods differently. `fetchUserStudents` and `fetchManagerStudents`. That way you will have the distinction and non-conflicting names. 

Another solution is like you did, overwrite the setup of the routes and customize the generated names as needed.

Sorry can't provide much more help here. 

Cheers
