### ISSUE TITLE
[Feature Request] Pass `$entry` variable to subfields

### ISSUE THREAD

**Issue by delfinn55** [Laravel-Backpack/CRUD#5298]
# Feature Request

### What's the feature you think Backpack should have?

**How it was**
I used 'relationship' field for entity and within subfields used 'view' field. I expected that inside the template the $entry variable would give the child model, but it was parent.

There are some variables available in field of 'view' type: 
- $crud
- $entry
- $field

It would be convenient if the variable $subEntry was also available.

### Have you already implemented a prototype solution, for your own project?

No, I added 'hidden' field with ID value in subfields and catch it in JS.

### Do you see this as a core feature or an add-on?

This as a core feature

**Comment by pxpm** [comment]
Hey @delfinn55 just to let you know I am doing a clean up and we may be able to have this before this issues makes 1 year birthday 🥳 

I am already experimenting with the concept, we should be able to have something by tomorrow or similar time frame if everything goes well. 

Cheers
