### ISSUE TITLE
Upload field type has gone from request

### ISSUE THREAD

**Issue by codeartmk** [Laravel-Backpack/CRUD#530]
Hey there,

I have this in my CrudController

`$this->crud->addField([
	'label' => 'Course featured image',
	'name' => 'featured_image',
	'type' => 'upload',
	'upload' => true,
	'disk' => 's3'
]);`

And If I dump **$request->all()** in CrudRequest, my _upload_ field is gone.
If I change the type to _image_, it is there.

So the request rules doesn't work for that field, cuz it is not in the request. :(

What may be the problem?

Thank you in advance

**Comment by codeartmk** [comment]
I'm so sorry,

I read this on the documentation

> The field sends the file, through a Request, to the Controller. The Controller then tries to create/update the Model. That's when the mutator on your model will run. That also means we can do any **file validation** (file, image, mimetypes, mimes) in the Request, before the file is stored on the disk.

That was actually my problem.
Thank you anyway.

**Comment by tabacitu** [comment]
No problem, glad you found your solution. Cheers!
