### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by haniramadhan-kkp** [Laravel-Backpack/CRUD#5300]
# Bug report

### What I did

I copy /var/www/mandat/vendor/backpack/crud/src/resources/views/crud/show.blade.php 
to /var/www/mandat/resources/views/vendor/backpack/crud/article/show.blade.php 

to create my own custom show page. Then, I want to add my own custom css to /var/www/mandat/public/packages/myname/mycustomthemename/css/styles.css and register it in /var/www/mandat/config/backpack/ui.php as below:

// CSS files that are loaded in all pages, using Laravel's asset() helper
    'styles' => [
        // 'styles/example.css',
        // 'https://some-cdn.com/example.css',
        'packages/myname/mycustomthemename/css/styles.css',
    ],

### What I expected to happen

I expected the css file take the effect on my custom page.

### What happened

The CSS file did not work.

### What I've already tried to fix it

I copy the css code to /var/www/mandat/vendor/backpack/crud/src/resources/assets/css/common.css, and it works, but I prefer not to do this.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
10.20.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.1
backpack/crud: 6.1.15
backpack/generators: v4.0.2
backpack/pro: 2.0.11
backpack/theme-tabler: 1.0.12

**Comment by karandatwani92** [comment]
Hey @haniramadhan-kkp,

Thanks for reporting the bug.

For now, you can achieve the same via theme config.

Let's suppose you are using theme-tabler.
1) Publish the theme config `php artisan vendor:publish --tag="theme-tabler-config"`
2) Add CSS to the `styles` array in **published theme config**:
```php
'styles' => [
        'https://some-cdn.com/example.css',
        base_path('vendor/backpack/theme-tabler/resources/assets/css/color-adjustments.css'),
        base_path('vendor/backpack/theme-tabler/resources/assets/css/colors.css'),
    ],
```
