### ISSUE TITLE
[Bug] Wrong Bootstrap class override

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#5305]
# Bug report

### What I did

Every time I try to use the `.align-content-center` css class I have some troubles because of its overwritten height [here](https://github.com/Laravel-Backpack/CRUD/blob/7e33bbd704891b5ef4bddaa95e6592c1e8821ae2/src/resources/assets/css/common.css#L514C4-L514C24).

Can we move this override in a specific class?

### What I expected to happen

The `.align-content-center` class should work as in Bootstrap without unpredictable results.

### What happened

I just tried to use this class in some of my components in the admin area, and it ruined them.

### What I've already tried to fix it

Removing the override.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.2.4 (cli) (built: Apr 13 2023 11:34:06) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.21.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.0
backpack/crud: 6.1.16
backpack/editable-columns: 3.0.2
backpack/generators: v4.0.2
backpack/pro: 2.0.11
backpack/theme-tabler: 1.0.12
```

**Comment by karandatwani92** [comment]
Thanks, @EmanueleCoppola for reporting. PR submitted https://github.com/Laravel-Backpack/CRUD/pull/5306
