### ISSUE TITLE
[Bug] `Error` key is present twice in the `base.php` lang file

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5314]
# Bug report

### What I did

Generated an operatino with a button using DevTools. Inside it, it was using `trans('backpack::base.error')` which we have been providing for a long time.

### What I expected to happen

Werk.

### What happened

No werk, because:
![CleanShot 2023-09-12 at 10 48 40](https://github.com/Laravel-Backpack/CRUD/assets/1032474/18a47320-b343-4bc2-861a-fea245f344d5)

Basically, before https://github.com/Laravel-Backpack/CRUD/commit/1f734e447d3816810e2b1485f19fdb5c4ffb1b62 we already had an `error` key which translated to `Error`. Now, that's being overridden by the `error` key that @promatik added, which provides an array 🤦‍♂️

So when you do `trans('backpack::base.error')` and expect a string... no bueno... you get an array now. So we've pretty much introduced a bug with that PR. We didn't notice that the string already existed.

### What I've already tried to fix it

Nothing it. Because the problem is... we have to choose one to keep. Tbh since this one is newer, I would keep the old one as `error` and rename the new array as `error_page` or something. But we have to do that inside all themes 🤦‍♂️

**Comment by promatik** [comment]
Ouch! I didn't know about that error key ...
I'll rename `error` to `error_page` 👌

**Comment by promatik** [comment]
Fixed here; https://github.com/Laravel-Backpack/CRUD/pull/5316
