### ISSUE TITLE
[Bug] column 'row_number'

### ISSUE THREAD

**Issue by smart4you** [Laravel-Backpack/CRUD#5319]
# Bug report

### What I did

`$this->crud->addColumn(
[
     'name' => 'row_number',
     'type' => 'row_number',
     'label' => '#',
     'orderable' => false,
     'priority' => 1,
]);`

### What I expected to happen

Adding a special column with numbers

### What happened

The column is added but the first line breaks the standard layout for the `list.blade.php` template in the **mobile version**
![Screenshot 2023-09-19 103246](https://github.com/Laravel-Backpack/CRUD/assets/59228744/7ec08613-34d0-4a20-991b-f2033c5c0c3b)

### What I've already tried to fix it

temporarily abandoned this column, better wait for corrections for styles

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.23 (cli) (built: Sep  1 2023 17:27:48) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.23, Copyright (c) Zend Technologies
    with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.23.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/generators: v4.0.2
backpack/langfilemanager: 5.0.0
backpack/logmanager: v5.0.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/settings: 3.1.0
backpack/theme-tabler: 1.1.0

**Comment by karandatwani92** [comment]
Hey @smart4you 
I'm also using [row_number](https://backpackforlaravel.com/docs/6.x/crud-columns#row_number-1) in a project. The following **screenshot confirms it's not a bug.**
```php
CRUD::addColumn([
 'name'      => 'row_number',
 'type'      => 'row_number',
 'label'     => '#',
 'orderable' => false,
])->makeFirstColumn();
```
![image](https://github.com/Laravel-Backpack/CRUD/assets/8214221/450894da-c496-4779-b72d-e81875e0ec2d)

### LARAVEL VERSION:
10.23.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/devtools: 2.0.3
backpack/editable-columns: 3.0.2
backpack/filemanager: 3.0.3
backpack/generators: v4.0.2
backpack/logmanager: v5.0.0
backpack/menucrud: v4.0.1
backpack/newscrud: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/settings: 3.1.0
backpack/theme-tabler: 1.1.0

### Try
`php artisan optimize:clear` & `php artisan basset:fresh`

and Your other posted [issue](https://github.com/Laravel-Backpack/CRUD/issues/5318) says you have overridden `list.blade.php`. Compare it with the CRUD package `list.blade.php`. See if you find something there.

and if you want to use a custom list view for a particular CRUD, use `$this->crud->setListView('path.to.your.view');`.
More info [here](https://backpackforlaravel.com/docs/6.x/crud-api#custom-views)

**Comment by smart4you** [comment]
Thanks for the quick answer, today I will create a new and clean project to confirm that the problem is on my side

**Comment by smart4you** [comment]
It looks like I broke something in my project that gives this effect((
Thanks for your time
