### ISSUE TITLE
[Bug] dropzone field doesn't properly honor maxFiles on update / doesn't display error

### ISSUE THREAD

**Issue by btrumsey** [Laravel-Backpack/CRUD#5322]
# Bug report

### What I did

Instantiated a dropzone field in my CrudControl setupUpdateOperation() function:

```
CRUD::field([
      'name' => 'image',
      'type' => 'dropzone',
      'label' => 'Image',
      'configuration' => [
        'thumbnailWidth' => null,
        'thumbnailHeight' => null,
        'maxFiles' => 1,
        'acceptedFiles' => '.jpg,.jpeg,.png',
        'dictInvalidFileType' => 'Only .jpg, .jpeg and .png files are allowed',
        'dictMaxFilesExceeded' => 'Only one image is allowed per stamp'
      ]
]);
```

### What I expected to happen

If there is an existing image in place, the user should not be able to add a new image if maxFiles is set to 1.

### What happened

The user is allowed to drop an image, resulting in two images in the dropbox, although maxFiles is set to 1.  In addition to incorrectly allowing the file, when a second image is dropped, resulting in the error signal being emitted, no error message is displayed.

### What I've already tried to fix it

I have a local dropzone.blade.php that addresses these issues:

__i) Missing error message__
The error signal simply sends a string containing the error message, which causes the line

```
let errorMessages = response.errors[errorBagName].join('<br/>');
```

to fail.

Updating this to 

```
let errorMessages = (typeof response.errors !== 'undefined') ? response.errors[errorBagName].join('<br/>') : response + '<br/>';
```

resolves the issue

__ii) Allowing extra files__
During the init() function, existing files are added by emitting the 'addedfile' signal.  However, this simply adds the image to the dropbox and does not add it to the accepted files array.  I've added code to accept the file during the `files.forEach` loop to take care of this.

```
files.forEach((file) => {
  this.files.push(file);                  // add the existing files to the dropzone.files array
  this.emit('addedfile', file);
  if (file.url && file.mime?.startsWith('image')) {
    this.emit('thumbnail', file, file.url);
  }
  file.accepted = true;                   // after the file is added, mark it as accepted
  this._updateMaxFilesReachedClass();     // check the accepted count against the maxFiles setting
  file.previewElement.querySelector('.dz-progress').style.visibility = 'hidden';
  file.previewElement.style.visibility = 'visible';
});
```

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

```
### PHP VERSION:
PHP 8.2.10 (cli) (built: Sep  2 2023 06:59:22) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.10, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.10, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.24.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.2.1
backpack/devtools: 2.0.3
backpack/generators: v4.0.2
backpack/logmanager: v5.0.0
backpack/medialibrary-uploaders: 1.0.1
backpack/menucrud: v4.0.1
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.12
backpack/settings: 3.1.0
backpack/theme-tabler: 1.1.1

```

**Comment by karandatwani92** [comment]
Hey @btrumsey
Thanks for pointing it out. **This needs a fix.**

```php
'configuration' => [
  'maxFiles' => 1,
]
```
### ISSUES:
**On create/update(if null) - shows a blank bar.**
![Screenshot 2023-09-23 at 8 18 49 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/9f039af5-9562-44ee-8ac2-b255fb2e73bf)
**On update(if already has attachment) - doesn't counts previous attachments**
![Screenshot 2023-09-23 at 8 21 15 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/ee6e1f0f-bd86-4771-87c3-660a38a5c649)
