### ISSUE TITLE
[Bug] CKEditor 5 upload image + compatibility

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/CRUD#5323]
# Bug report

### What I did
There are two problems:

- Try to upload an image using CKEditor or aka field 'wysiwyg' 
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/5aa13477-217a-4c17-ab0c-c2705d4e7f1b)

- It is not possible to see server folders has old versions and select and image. 

In old version you can see this button to select image from server. Old version use elfinder.
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/471fb874-7fa7-43e9-97de-3508f8c23e22)

### What I expected to happen

Somehow be able to upload an image to the server.

### What happened

Image not showing in the editor. 

### What I've already tried to fix it

After research i found:
The console show error: filerepository-no-upload-adapter
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/62840a4a-678f-426f-af6e-80dea651a0b9)
You need to enable an upload adapter in order to be able to upload files. But no adapter is configured by defauld.

The parameter `filebrowserBrowseUrl` use in old version is not present in v5
https://ckeditor.com/docs/ckeditor5/latest/updating/ckeditor4/ckeditor4-configuration-compatibility.html
First column V4 second colum equivalent v5
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/6159e1c0-afc0-499a-9c0b-9cfcef6d47d9)

### Is it a bug in the latest version of Backpack?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/CRUD/assets/20278289/94cc84bb-4192-4092-9542-e5cebda920b7)

**Comment by karandatwani92** [comment]
Hey @promatik, **Need your help here.** 

It seems like our **build is missing the adapter for file handling**
and [CKEditor](https://backpackforlaravel.com/docs/6.x/crud-fields#ckeditor-pro) doc has outdated instructions for file manager integration.

Error guide:
https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-filerepository-no-upload-adapter

A simple upload adapter is available here [Simple upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/images/image-upload/simple-upload-adapter.html) plugin.

**Comment by tabacitu** [comment]
Heads-up - might be same issue as https://github.com/Laravel-Backpack/community-forum/issues/641

**Comment by promatik** [comment]
> _Heads-up - might be same issue as [Laravel-Backpack/community-forum#641](https://github.com/Laravel-Backpack/community-forum/issues/641)_

True, it's the same 👌 let's move the conversation there.
