### ISSUE TITLE
[Bug] no setFromDB columns at all, and no sorting nor searching on manual columns

### ISSUE THREAD

**Issue by francescverdu** [Laravel-Backpack/CRUD#5325]
The method setFromDB does'nt add any column/field, and manual columns can't be sorted nor searched if you have a composite name on the $table property of your model. This is a bug, I think.

I had my models declarations like 

`$table = "my_schema.my_table";  `

and finally I discovered that this was causing the backpack's database_schema functions not to identify the table, so I removed the schema part and all worked fine.

I think this can't be a feature, beacause I have some apps that are multi-schema, and with a single connection I must specify each table with his corresponding schema.

**Comment by tabacitu** [comment]
Hi @francescverdu ,

Actually we highly discourage using `setFromDb()`. That method is no longer documented on our website, and we might even remove it in future versions 🤞 It was a bad idea to have it in the first place from a maintainer perspective - a method that does so much magic is IMPOSSIBLE to maintain. If we make even small changes to it, we risk introducing breaking changes in a lot of admin panels. So the method is useful for those who use it as-is, sure, but we can't make changes to it... And that makes it a pain in the ass, for both users and maintainers. Which is why we recommend against using it.

Please define your FIELDS/COLUMN individually, inside the operations. That will 100% work better, and give you control over what's happening. We've created [DevTools](https://backpackforlaravel.com/products/devtools) to make writing those columns/fields as easy as using `setFromDb()`.

Let me know if you have thoughts on this.
Cheers!

**Comment by francescverdu** [comment]
Ok, I understand that setFromDB is discouraged, in fact I'm not using it. But the problem goes forward, beacuse if tou specify schema in the $table attribute, even MANUAL COLUMNS are not orderable nor searchable, and this is the true problem.

**Comment by francescverdu** [comment]
It's simple to test: take any working crud and just change 

$table = "your_table";

for this other form

$table = "your_schema.your_table";

and then try to order by any column, and try to search any text pattern.

**Comment by tabacitu** [comment]
Ooooh. I understand now, thank you @francescverdu . I've opened a different issue for it then, rephrasing this and assigning Pedro, so he can take a closer look. Let's move the conversation there please 🙏

https://github.com/Laravel-Backpack/CRUD/issues/5326

Cheers!

**Comment by nulele** [comment]
> Hi @francescverdu ,
> 
> Actually we highly discourage using `setFromDb()`. That method is no longer documented on our website, and we might even remove it in future versions 🤞 It was a bad idea to have it in the first place from a maintainer perspective - a method that does so much magic is IMPOSSIBLE to maintain. If we make even small changes to it, we risk introducing breaking changes in a lot of admin panels. So the method is useful for those who use it as-is, sure, but we can't make changes to it... And that makes it a pain in the ass, for both users and maintainers. Which is why we recommend against using it.
> 
> Please define your FIELDS/COLUMN individually, inside the operations. That will 100% work better, and give you control over what's happening. We've created [DevTools](https://backpackforlaravel.com/products/devtools) to make writing those columns/fields as easy as using `setFromDb()`.
> 
> Let me know if you have thoughts on this. Cheers!

Excuse me @tabacitu if I re-open this old post but I was comparing the `UserCrudController` generated by `php artisan backpack:crud user` command with the "Getting Started" page when I first open the admin dashboard and I found a discrepancy about  `setFromDb`.

Well, the documentation says:

1. **When Listing, let's remove the "password" column** - no point in showing the hash. To do that, go to `UserCrudController::setupListOperation()` and remove the line saying `CRUD::column('password');` - easy-peasy, right?

but the method of the controller is

```
    /**
     * Define what happens when the List operation is loaded.
     * 
     * @see  https://backpackforlaravel.com/docs/crud-operation-list-entries
     * @return void
     */
    protected function setupListOperation()
    {
        CRUD::setFromDb(); // set columns from db columns.

        /**
         * Columns can be defined using the fluent syntax:
         * - CRUD::column('price')->type('number');
         */
    }
```

I'va purchased the pro version and the packages versions are:
- backpack/pro: 2.2.4
- backpack/generators: 4.0.5

Maybe do I need to set some configuration parameter?

Thanks
