### ISSUE TITLE
[Bug]  broken base.php Italian translation file

### ISSUE THREAD

**Issue by massimocolella** [Laravel-Backpack/CRUD#5332]
# Bug report

### What I did

update the package via composer

### What happened

got syntax error, unexpected identifier "username", expecting "]" in [vendor/backpack/crud/src/resources/lang/it/base.php ]

### What I've already tried to fix it

fix manually the translation file. Missing apices on line 24 of file vendor/backpack/crud/src/resources/lang/it/base.php.

**Comment by jorgetwgroup** [comment]
Hello @massimocolella thanks for reporting this issue i see the error and will be fixed ASAP.

Cheers.

**Comment by jorgetwgroup** [comment]
Fix is pushed here https://github.com/Laravel-Backpack/CRUD/pull/5334

**Comment by massimocolella** [comment]
thanks!
