### ISSUE TITLE
[Feature Request] Do not unset autoset values after setFromDb call

### ISSUE THREAD

**Issue by daPhantom** [Laravel-Backpack/CRUD#5344]
# Feature Request

### What's the feature you think Backpack should have?

Unsure if it's a new feature or a bug.

Currently the `$this->crud->setFromDb()` performs an `unset($this->autoset);` as last statement. Unfortunately this also leads to custom set labellers being nulled and not being used anymore.

I was trying to localize field and column labels by setting a custom labeller which performs the default backpack label magic and wraps it with a `__()` call. This does work for the `setFromDb` fields but for example not for the `created_at` and `updated_at` timestamps which follow in a separate block.

This leads to inconsequent behaviour when working with a labeller and it took me a while to figure this out.

### Have you already implemented a prototype solution, for your own project?

No this breaks my translation currently but I do not really consider this as a bug... or just some kind of bug.

### Do you see this as a core feature or an add-on?

Core

**Comment by promatik** [comment]
Hi @daPhantom 🙌

Thank you for the suggestion, but we're actually deprecating the `setFromDb` 😬

**tabacitu** [said this 3 weeks ago](https://github.com/Laravel-Backpack/CRUD/issues/5325#issuecomment-1733253734);

> _Actually we highly discourage using `setFromDb()`. That method is no longer documented on our website, and we might even remove it in future versions 🤞 It was a bad idea to have it in the first place from a maintainer perspective - a method that does so much magic is IMPOSSIBLE to maintain. If we make even small changes to it, we risk introducing breaking changes in a lot of admin panels. So the method is useful for those who use it as-is, sure, but we can't make changes to it... And that makes it a pain in the ass, for both users and maintainers. Which is why we recommend against using it._
> 
> _Please define your FIELDS/COLUMN individually, inside the operations. That will 100% work better, and give you control over what's happening. We've created [DevTools](https://backpackforlaravel.com/products/devtools) to make writing those columns/fields as easy as using `setFromDb()`._

So, that being said, we do not plan to support/add new features to `setFromDb()`, and we cannot make any changes to it because it may break other admin panels.

Please define your fields and columns manually, and by the way, if you use [DevTools](https://backpackforlaravel.com/products/devtools) half of the work will be done for you 👌

**Comment by daPhantom** [comment]
Hey @promatik,

oh good to know. Why is the `setFromDb()` then used by the CrudController and even by the DevTools? That feels odd if you plan to deprecate it.

I am already using DevTools and it's quite convenient but I still have to define fields, columns and relationships manual and take care of translations that way anyway - true.
