### ISSUE TITLE
[Bug] `easymde` is not using basset

### ISSUE THREAD

**Issue by BernhardK91** [Laravel-Backpack/CRUD#5349]
# Bug report

### What I did

I use `easymde` in my CrudController. I am also using a Content-Security-Policy.

### What I expected to happen

I expect the editor to be loaded properly.

### What happened

The editor does not load properly because the asset is blocked by content security policy. So it looks like the assets of the editor are not properly loaded via Backpack Basset.

### What I've already tried to fix it

I figured out that it was loaded from the following file:

![image](https://github.com/Laravel-Backpack/CRUD/assets/5526334/f5bda30b-4795-4d0f-ba70-d3479a6690c5)

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? => Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.11 (cli) (built: Sep 28 2022 11:08:17) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.27.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.1
backpack/crud: 6.2.3
backpack/generators: v4.0.2
backpack/pro: 2.0.15
backpack/theme-tabler: 1.1.1
```

**Comment by pxpm** [comment]
Hey @BernhardK91 thanks for the report. 🙏 

I've just tagged Backpack/PRO 2.0.18 that fixes this. Our repository should pick the new version in the next couple hours and you will be able to get the fix with a `composer update backpack/pro`. 

Cheers
