### ISSUE TITLE
SimpleMDE Copy Paste Upload

### ISSUE THREAD

**Issue by samsebastian** [Laravel-Backpack/CRUD#535]
This is something I thought might be useful for anyone using SimpleMDE that wants Ghost / GitHub style copy paste / drag image functionality.. Would be cool to get this (or something similar baked in one day 😁 )

Then copy the source up for `vendor/crud/fields/simplemde.blade.php`

https://github.com/Rovak/InlineAttachment is the CodeMirror plugin: 
Include both `dist/inline-attachment.min.js` and then `dist/codemirror-4.inline-attachment.min.js` in your `simplemde.blade.php` section `@push('crud_fields_scripts')` **after** the original `simplemde.min.js`.

(note you will need to make sure you have added the Laravel csrf_token to your `layout.blade.php` header.)

```php
-- layout.blade.php
 <script>
        window.csrf_token = {!! json_encode(csrf_token()) !!};
 </script>
```

Second, overwrite the `@push('crud_fields_scripts')` section to the below 

```php
-- simplemde.blade.php

@push('crud_fields_scripts')
<script>

     var simplemde = new SimpleMDE({
         element: $("#simplemde-{{ $field['name'] }}")[0],
         spellChecker: false,
         placeholder: "Copy / paste and draggable image upload supported...",
    });

    inlineAttachment.editors.codemirror4.attach(simplemde.codemirror, {
        uploadUrl: "/admin/YOUR_IMAGE_UPLOAD_PATH",
        extraParams: {
            '_token': window.csrf_token
        }
    });

</script>
@endpush
```

You will obviously need a controller that picks up the image, uploads, and returns the path.

Example:

```php
	public
	function store(ImageRequest $request) {

		$field = 'file';

		if ($request->hasFile($field)) {
			if ($request->file($field)->isValid()) {
				$filename = sprintf('%s.%s', md5($request->file($field)->getFilename() . time()), $request->file($field)->extension());
				$filename = strtolower($filename);
				$name     = str_slug($request->file($field)->getFilename());

				$request->file($field)->storeAs('public/images/uploads/', $filename);

				$model = Image::create(['name'           => $name,
				                        'filename'       => $filename,
				                        'size'           => $request->file($field)->getSize()
				]);

				return response()->json(['filename' => sprintf('/images/%s/uploads/%s', 'post', $model->filename)]);
			}
		}

		return response()->json('fail', 400);
	}

```

The result..

**1. Open**
![image](https://cloud.githubusercontent.com/assets/9647970/23831186/a0e77cda-0767-11e7-82fd-a622d1667dd9.png)

**2. Paste**
![image](https://cloud.githubusercontent.com/assets/9647970/23831188/c4abe71e-0767-11e7-8329-096765e4b18b.png)

**3. Image!**
![image](https://cloud.githubusercontent.com/assets/9647970/23831234/f963ac48-0768-11e7-8d46-9e4d4148df41.png)

**Comment by lloy0076** [comment]
Not sure what this does but it looks like it might be a good idea - a PR would help to understand the needed code changes more though :)

**Comment by samsebastian** [comment]
Sorry, I don't know how to do a PR.. 

Basically it allows you to copy paste an image from the clipboard to the simplemde editor from the clipboard (similar to how Gmail works)..

It adds InlineAttachment simplemde plugin to handle it which sends the clipboard data to a controller, saves it to disk, and returns the URL.

**Comment by tabacitu** [comment]
Hi @samsebastian ,

This looks really cool, good work. I think it's too niche to be included in the core package though, since it requires a controller and everything, would be too difficult for people to set up.

I'd hate for this solution to die in obscurity once I close the issue. What do you say about writing on your blog, medium, stackoverflow or whatever you want about this solution? I'd happily link to it from the [backpackforlaravel blog](https://backpackforlaravel.com/blog) so that people can more easily find it.

Thanks, cheers!

**Comment by chemisax** [comment]
Hello @samsebastian!

Thank you for your solution!!!
It doesn't have anything to do with this repository,
but I was able to use it in my project, which is using Laravel.
