### ISSUE TITLE
[Bug] Frontend issue in the filter

### ISSUE THREAD

**Issue by drserhii** [Laravel-Backpack/CRUD#5354]
# Bug report

### What I did

**I open and close the filter by date on the list page**

### What I expected to happen

**I expect that when I close the filter by date, it will be closed**

### What happened

**When opening and closing the date filter, sometimes a datapicker window appears in the top corner of the screen instead of closing.**

**The bug is reproduced both logically and on the demo site, please see the screenshot:** 

![Screenshot from 2023-10-13 18-00-14](https://github.com/Laravel-Backpack/CRUD/assets/22273976/ff15b983-ec91-45f0-a273-ed8394ce84c2)

**Comment by karandatwani92** [comment]
Hey @pxpm 

I tried to find the cause of it, but couldn't find it. Can you please check?

This happens only when we dismiss the calendar **twice** via close(X) button and this happens for both **date & date_range** filters:
![image](https://github.com/Laravel-Backpack/CRUD/assets/8214221/0e93d754-efb8-4aec-8f74-ec4290790dd2)

**Comment by pxpm** [comment]
Thanks @drserhii , sorry for the delay on this one. 

I've just merged the fix in backpack/pro. A `composer update` should get you the updated version: 2.2.9.

Cheers
