### ISSUE TITLE
FatalErrorException in AutoSet.php line 156

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#536]
Hi,

Fresh install on LAravel 5.4 and followed the docs. Then  I got:

FatalErrorException in AutoSet.php line 156
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']'

Seems need to change:

$this->model::CREATED_AT, $this->model::UPDATED_AT

with

$this->model->CREATED_AT, $this->model->UPDATED_AT

And then it's works.

**Comment by tabacitu** [comment]
Hi @MickaelTH ,

Thanks a lot for reporting this. Just pushed an update, so a ```composer update``` should fix it for you.

Actually it's meant to retrieve the name of the created_at and updated_at columns (some people change them), so it would be ```$this->model->getCreatedAtColumn()``` and ```$this->model->getUpdatedAtColumn()``` - little documented Laravel methods. This is what the fix does.

Please tell me if you're still having the issue after updating.

Cheers!

**Comment by MickaelTH** [comment]
Confirming 3.2.6 fixed the issue

**Comment by tabacitu** [comment]
Pfiew. Thanks :-)

**Comment by jhivan** [comment]
Confirming 3.2.6. Fixed. Thanks a lot.

**Comment by tabacitu** [comment]
Thanks for confirming @MickaelTH and @jhivan . Cheers!
