### ISSUE TITLE
[Bug] Save Buttons without text-white class

### ISSUE THREAD

**Issue by mrinaldidfs** [Laravel-Backpack/CRUD#5362]
# Bug report

### What I did
I removed all save actions except one 

### What I expected to happen
In _create_ and in _update_ operation the save button must has the label colored white and the background colored green

### What happened

The save button has the label colored black and the background colored green.

### What I've already tried to fix it

Customize the vendor\backpack\crud\src\resources\views\crud\inc\form_save_buttons.blade.php layout modifing this:

```
@if(empty($saveAction['options']))
            <button type="submit" class="btn btn-success text-white">
                <span class="la la-save" role="presentation" aria-hidden="true"></span> &nbsp;
                <span data-value="{{ $saveAction['active']['value'] }}">{{ $saveAction['active']['label'] }}</span>
            </button>
        @else
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-success text-white">
                    <span class="la la-save" role="presentation" aria-hidden="true"></span> &nbsp;
                    <span data-value="{{ $saveAction['active']['value'] }}">{{ $saveAction['active']['label'] }}</span>
                </button>
                <button id="bpSaveButtonsGroup" type="button" class="btn btn-success text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="d-none visually-hidden">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="bpSaveButtonsGroup">
                    @foreach( $saveAction['options'] as $value => $label)
                        <li><button class="dropdown-item" type="button" data-value="{{ $value }}">{{ $label }}</button></li>
                    @endforeach
                </ul>
            </div>
        @endif
```

The `text-white` class present in the first submit button is added from me, because there isn't in the default backpack view.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:                                                       
PHP 8.1.2 (cli) (built: Jan 19 2022 10:13:52) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
### LARAVEL VERSION:
10.29.0.0
### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.1
backpack/crud: 6.3.0
backpack/generators: v4.0.2
backpack/pro: 2.0.18

**Comment by phpfour** [comment]
Hey @mrinaldidfs,

Thanks for reporting this. After some investigation, I've found that it only impacts the CoreUI v4 theme. Nevertheless, it should be fixed in an upcoming release.

PR: https://github.com/Laravel-Backpack/CRUD/pull/5365

Cheers
