### ISSUE TITLE
T_PAAMAYIM_NEKUDOTAYIM after updating to 3.2.5 from 3.2.4

### ISSUE THREAD

**Issue by jhivan** [Laravel-Backpack/CRUD#537]
I get:

`
FatalErrorException in AutoSet.php line 156: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']'
`

after update. All i know is this error is relate to double colon static class usage. Anybody knows what's wrong?

**Edit**
Rolled back to 3.2.4 and it's working fine.

**Comment by tabacitu** [comment]
Hmm... Thanks for reporting this. What PHP version are you running?

**Comment by jhivan** [comment]
@tabacitu You're welcome. I'm using PHP 5.6.30-7.

**Comment by MickaelTH** [comment]
Seems related to my previous issue #536

**Comment by tabacitu** [comment]
Thanks a lot. Solved, check out https://github.com/Laravel-Backpack/CRUD/issues/536

Cheers!
