### ISSUE TITLE
[Bug] Black Friday Discount

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5372]
Ok this is not a bug. I just wanted to upload this image somewhere, so I can use it in [a blog post](https://backpackforlaravel.com/articles/news/many-many-discounts-black-week-black-friday-cyber-monday-and-more).

<img width="1396" alt="Xnapper-2023-11-16-20 08 18" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/05502147-1ecc-42a7-9881-3b657da8e212">

**Comment by abraaoz** [comment]
Thank you @tabacitu 
It was really difficult to find it!!
