### ISSUE TITLE
Applying join and group by on list query results in duplicate column error

### ISSUE THREAD

**Issue by YosraHamza** [Laravel-Backpack/CRUD#5373]
# Bug report

### What I did

Applying join and group by clauses on list action

### What I expected to happen

I expected the list counts to work normally

### What happened

An error ocurrend  `SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id'`

### What I've already tried to fix it

Disabling list counts fixes the issue.
Enabling it will trigger the issue, the root cause is from the file
`vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php` at line `261`, as in case of group by all the results are selected `"*"`
```
 $minimumColumns = ($crudQuery->groups || $crudQuery->havings) ? '*' : $modelTable.'.'.$this->model->getKeyName();
```
I checked Backpack 6 and this line was updated and is working in this case.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
backpack/crud: 5.6.1
backpack/generators: v3.3.17
backpack/logmanager: v4.0.11
backpack/pro: 1.6.6
backpack/settings: 3.1.0

PHP 8.1.18 (cli)
Mysql 8

**Comment by jorgetwgroup** [comment]
Hello @YosraHamza, we no longer provide support for Backpack 5, if you have already verified that this situation is resolved in version 6, our recommendation is that you update it.

Thanks.

P.D.: i will close this issue because we will not update Backpack v5, but you are free to re-open or create new is needed.
