### ISSUE TITLE
Scrollbar appears bottom of table

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#538]
A scrollbar is appearing at the bottom of the table with Laravel 5.4 and Backpack 3.2.6
![2017-03-13 001296](https://cloud.githubusercontent.com/assets/26375917/23865667/f7b4b0aa-0848-11e7-9a3f-2e367f065ddb.png)

It disappears when using $this->crud->enableExportButtons();
![2017-03-13 001297](https://cloud.githubusercontent.com/assets/26375917/23865668/f7b724e8-0848-11e7-8f10-62ebecb52972.png)

**Comment by votintsev** [comment]
Just add to your css:
`.box-body.table-responsive {
    padding-left: 15px;
    padding-right: 15px;
}`

**Comment by MickaelTH** [comment]
That's a work around yes, but out of the box it should be handled no?

**Comment by votintsev** [comment]
This problem occurs through the fault of the AdminLTE (.box-body has padding 10px, but inner bootstrap grid styles has padding -15px). But original AdminLTE use table-wrap without .table-responsive style for DataTables: https://almsaeedstudio.com/themes/AdminLTE/pages/tables/data.html and the bug does not appear.

But BackPack use .table-responsive which has css-style "overflow-x: auto" and a bug appears.

**Comment by tabacitu** [comment]
@MickaelTH - thanks for reporting it.
@votintsev - thanks for the fix, just merged [your PR](https://github.com/Laravel-Backpack/CRUD/pull/539) into the ```dev``` branch, with the solution you mentioned above.

It will be available in the master branch later this week, with the next patch update. Until then, @MickaelTH , you can place this in your ```list.css``` file:
```css
.box-body.table-responsive { padding-left: 15px; padding-right: 15px; }
```
That's actually what the fix does :-)

Cheers guys!

**Comment by MickaelTH** [comment]
Guys,

Thanks you for the quick answer and fix.

@tabacitu I'm ok waiting for the update to confirm the fix is well implemented. That's part of my QA responsibility when I reported the issue ;)

**Comment by tabacitu** [comment]
@MickaelTH - sure. It's now up-and-running. A ```composer update``` should pull in Backpack\CRUD 3.2.7, which fixes it.

Cheers!

**Comment by MickaelTH** [comment]
@tabacitu Alright, just tested but it seems it is not fixed, am I missing a step?

![2017-03-17 001297](https://cloud.githubusercontent.com/assets/26375917/24031380/e9b5dbae-0b14-11e7-9cd9-bb94de2de18d.png)
![2017-03-17 001298](https://cloud.githubusercontent.com/assets/26375917/24031381/e9ba9cca-0b14-11e7-970a-4c5468e41783.png)

**Comment by tabacitu** [comment]
Oups. Yes, sorry for the wrong instructions. You should also republish your assets (or at least list.css)

Cheers!

**Comment by votintsev** [comment]
@MickaelTH The update replaces the file in the vendor folder (/vendor/backpack/crud/src/public/crud/css/list.css), but you most likely already have it as an published copy in the folder (/public/vendor/backpack/crud/css/list.css). This copy is not replaced. You must either re-publish the files or just make the changes manually (probably the more safety way).

**Comment by MickaelTH** [comment]
@tabacitu How to do that with command line?

@votintsev I would prefer to avoid doing manual change otherwise how to be sure to get latest version of Backpack? Assumption of course is that no Backpack asset has been changed in the public folder.

I'm still new here, so I innocently tried php artisan vendor:publish but still same issue as this may not be correct command :)

![2017-03-17 001299](https://cloud.githubusercontent.com/assets/26375917/24034212/0b0db142-0b23-11e7-92b7-15fdf188ca56.png)

**Comment by tabacitu** [comment]
Hi @MickaelTH - I think it's best to:
- manually delete ```/vendor/backpack/crud/src/public/crud/css/list.css```
- ```composer update```
- ```php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="public"```

Hope it helps. Cheers!
