### ISSUE TITLE
[Bug] withFiles() Uploader doesn't work with a custom field.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5394]
### What I did
**withFiles()  Uploader doesn't work with a custom field.**

A user reported this on [StackOverflow](https://stackoverflow.com/questions/77568585/how-to-save-a-custom-upload-field-in-the-public-disk)

So, I did the following steps:

Created a custom upload field, no changes made!

`php artisan backpack:field custom_upload --from=upload`

Works ✅
```
$fields[] = [   // Upload
            'name'   => 'upload',
            'type'   => 'upload',
            'withFiles' => true
        ];
```

Doesn't Works ❌
```
$fields[] = [   // Upload
            'name'   => 'upload',
            'type'   => 'custom_upload',
            'withFiles' => true
        ];
```

**Comment by pxpm** [comment]
thanks @karandatwani92 for raising the issue. I've just added a section to the docs explaining how the developer can add the uploaders to custom fields:
https://backpackforlaravel.com/docs/6.x/crud-uploaders#configuring-uploaders-in-custom-fields

Cheers
