### ISSUE TITLE
[Bug] Details row endpoints/URL lacks access control

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5395]
A user reported this here https://github.com/Laravel-Backpack/community-forum/discussions/774 

Details row endpoints/URL lacks access control.

https://backpackforlaravel.com/docs/6.x/crud-api#details-row

I tested the following, No API is available to disable them. Endpoints (URL) are always open!🚨

```php
$this->crud->disableDetailsRow(); // hides it from UI only

// I doubt the following are working.
$this->crud->allowAccess('details_row');
$this->crud->denyAccess('details_row');
```

**Comment by pxpm** [comment]
Thanks for bringing this to my attention @karandatwani92 

I've just submitted the PR #5397 that addresses this. 

Cheers

**Comment by pxpm** [comment]
Updated docs for details row here: https://backpackforlaravel.com/docs/6.x/crud-operation-list-entries#details-row-1
