### ISSUE TITLE
[Bug] Admin User Not Working On New Laravel 10 Install

### ISSUE THREAD

**Issue by ocbrianh** [Laravel-Backpack/CRUD#5396]
# Bug report

I created a new Laravel 10 install using the command:
```curl -s "https://laravel.build/example-app?with=mysql,redis" | bash```
After the install finished, I ran ```sail up``` command so the container could be created. Afterwards I ran: ```sail composer require backpack/crud -W``` during the setup, I created an admin user. I also created another admin user by running ```sail artisan backpack:user```

All the steps worked and I verified that the User table had entries for both users.
When I go to http://localhost/admin/ and try to login, I get  "These credentials do not match our records." Same thing happens for everyone of the admin users that I create via the command line.

When I run ```php artisan backpack:version``` the output is:
PHP 8.2.13 (cli) (built: Nov 24 2023 08:47:18) (NTS)

### LARAVEL VERSION:
10.34.2.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.2
backpack/crud: 6.4.0
backpack/generators: v4.0.2
backpack/theme-tabler: 1.1.2

**Comment by pxpm** [comment]
Hey @ocbrianh sorry it took me a little longer to get back here. 

I've identified the issue and fixed it in `backpack/crud` 6.5.5. A `composer update` should get you the fix. 

Cheers
