### ISSUE TITLE
[Bug]  After change settings get 500 error

### ISSUE THREAD

**Issue by amigolj** [Laravel-Backpack/CRUD#5399]
# Bug report

### What I did

Change ui.php set false for 

  'show_getting_started' => env('APP_ENV') == 'local',
changed to 
  'show_getting_started' => false,

### What I expected to happen

Hide dashboard 

### What happened
![Screenshot_4](https://github.com/Laravel-Backpack/CRUD/assets/10392966/b27a3e7e-5878-43ff-b248-aee29c375041)
Get 500 error

### What I've already tried to fix it

need to remove from composer and directory and reinstall backpack

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yeah

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.13 (cli) (built: Nov 23 2023 17:19:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.35.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.2
backpack/crud: 6.4.1
backpack/generators: v4.0.2
backpack/theme-tabler: 1.1.2

**Comment by phpfour** [comment]
Hi @amigolj

Thanks for posting the issue. I can see that Backpack is trying to load the view from CoreUIv2 theme in your screenshot:

![CleanShot 2023-12-09 at 19 18 42](https://github.com/Laravel-Backpack/CRUD/assets/171715/ae0ed91e-7760-4e90-a680-735b12e00942)

...but in your result from the `backpack:version` command you have Tabler theme installed: 

![CleanShot 2023-12-09 at 19 19 42](https://github.com/Laravel-Backpack/CRUD/assets/171715/1d4a771c-437b-4f72-9bb7-f5ff30747676)

You may check if you have the `tabler` theme specified in the `ui.php` file and not the `coreuiv2`: 

![CleanShot 2023-12-09 at 19 20 22](https://github.com/Laravel-Backpack/CRUD/assets/171715/23f5a560-d9a4-4a10-b928-3f614519d3b5)

Let me know if this helps.

**Comment by amigolj** [comment]
Thanks @phpfour  It's helped, but why it's have wrong values, theme in these lines
