### ISSUE TITLE
AddColumn Error

### ISSUE THREAD

**Issue by ajamandre** [Laravel-Backpack/CRUD#540]
$this->crud->addColumn([  // Select
			   'label' => "Account",
			   'type' => 'select',
			   'name' => 'acct_id', // the db column for the foreign key
			   'entity' => 'account', // the method that defines the relationship in your Model
			   'attribute' => 'acct_desc', // foreign key attribute that is shown to user
			   'model' => 'App\Models\account' // foreign key model
			]);

im getting error

1/3 ErrorException in 4c4c1eddd3e75f8f3aa8a796c57e84e8d5588d3d.php line 5: Trying to get property of non-object

2/3 ErrorException in 4c4c1eddd3e75f8f3aa8a796c57e84e8d5588d3d.php line 5: Trying to get property of non-object (View: C:\xampp\htdocs\it_dtr\vendor\backpack\crud\src\resources\views\columns\select.blade.php)

3/3  ErrorException in 4c4c1eddd3e75f8f3aa8a796c57e84e8d5588d3d.php line 5: Trying to get property of non-object (View: C:\xampp\htdocs\it_dtr\vendor\backpack\crud\src\resources\views\columns\select.blade.php) (View: C:\xampp\htdocs\it_dtr\vendor\backpack\crud\src\resources\views\columns\select.blade.php)

**Comment by bahman2216** [comment]
It is related to your **blade** file. Check you object is empty or put **@** before your value call in blade/

**Comment by tabacitu** [comment]
Hi @ajamandre ,

Make sure you have the ```account``` relationship on your model. After that, I'm pretty sure you just need to tweak those variables a little. For example, I think your model name probably starts with a capital letter.

My wording may not be the best in explaining what each variable is - I tried my best - but once you understand them and get them right once, you'll be up-and-running in no time.

Cheers!

**Comment by tabacitu** [comment]
P.S. Closed this issue because I checked and the "select" field works.

**Comment by kumangkumeng** [comment]
Hi @tabacitu , i have similar problem, not sure where i did wrong,

controller file
```
$this->crud->addColumn([
            'name'  => 'category',
            'label' => 'Kategori',
            'type'  => 'select',
            'entity' => 'category',
            'attribute' => 'name',
            'model' => 'App\Models\Category'
        ]);
```

Model
```
public function category()
{
	return $this->belongsTo('App\Models\Category', 'category');
}
```

pelayanan table
```
+-----+
id
-----
name
----
category
+-----+
```

categories table
```
+------+
id
------
name
+------+
```

not sure where i did wrong, but it says "Trying to get property of non object"
please help

**Comment by tabacitu** [comment]
Hi @kumangkumeng ,

You db seems a bit atypical. It's good practice to use the "_id" suffix when what you store is an ID. Make it easier to debug later. Your DB structure and addField() syntax seem correct to me.

I suggest you [use Tinker](https://scotch.io/tutorials/tinker-with-the-data-in-your-laravel-apps-with-php-artisan-tinker) to try getting the relationships from some rows in the db - it will help you see more detailed errors about the relationships. That can also be done in any controller, if it's easier for you.

Hope it helps. Cheers!
