### ISSUE TITLE
[Bug] InlineCreate doesnt work

### ISSUE THREAD

**Issue by k-wiese** [Laravel-Backpack/CRUD#5405]
# Bug report

### What I did

I've set up inlineCreate operation in my OfficeCrudController (secondary), and also in my VisitCrudController ive setup the field for inlinecreate, the relationships are working fine.

```
VisitCrudController setupCreateOperation:
    protected function setupCreateOperation()
    {
        CRUD::setValidation(VisitRequest::class);
        CRUD::addField([
            'label' => 'Office',
            'type' => 'select2_from_ajax',
            'name' => 'office_id',
            'entity' => 'office',
            'model' => "App\Models\Office",
            'attribute' => 'name',
            'attributes' => [
                'data-placeholder' => 'Select office',
            ],
            'minimum_input_length' => 3,
            'data_source' => route('visit.office-search-data'),
            'inline_create' => ['entity' => 'office'], // Enable inline create
            'relationship' => [
                'name' => 'office',
                'entity' => 'office', 
            ],
        ]);
    }
    
    //Visit relationship:
    
        public function office(): BelongsTo
    {
        return $this->belongsTo(Office::class);
    }
```
Office crud controller:

 */
class OfficeCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\InlineCreateOperation;

//relationship:

    public function visits(): HasMany
    {
        return $this->hasMany(Visit::class);
    }
### What I expected to happen

I expected the +Add inline create button to show up.

### What happened

The button doesnt show up.

### What I've already tried to fix it

I've checked if everything was setup fine, and consulted gpt in many aspects.

### Is it a bug in the latest version of Backpack?

Yes.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.37.3.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.1
backpack/basset: 1.2.2
backpack/crud: 6.4.2
backpack/filemanager: 3.0.6
backpack/generators: v4.0.2
backpack/permissionmanager: 7.1.1
backpack/pro: 2.0.20
backpack/theme-tabler: 1.1.2

**Comment by k-wiese** [comment]
nevermind, sorry the type should be:

`            'type' => "relationship",`

**Comment by jorgetwgroup** [comment]
Hello @k-wiese as i understand is working for you now, right?

Cheers.

**Comment by jorgetwgroup** [comment]
Hello @k-wiese given your response and due to lack of activity I will close this issue. If the problem persists, you can reopen it or create a new one. 

Cheers.
