### ISSUE TITLE
Command "backpack:button" is not defined. 

### ISSUE THREAD

**Issue by amigolj** [Laravel-Backpack/CRUD#5407]
# Bug report

### What I did

Try to create custom button

### What I expected to happen

Created custom buttom

### What happened

I got next error
![image](https://github.com/Laravel-Backpack/CRUD/assets/10392966/07020916-bae8-4782-af32-e69222d65f34)

### What I've already tried to fix it

Googled

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yeah

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.2.13 (cli) (built: Nov 23 2023 17:19:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.26.2.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.2
backpack/crud: 6.4.2
backpack/pro: 2.0.20
backpack/theme-tabler: 1.1.2

**Comment by smart4you** [comment]
Hi, I had a similar problem due to missing package "backpack/generators". I just installed it manually and the missing console commands appeared

**Comment by jorgetwgroup** [comment]
Hi @smart4you i noticed you are working on a server.

Did you active the production mode or install packages as

```
composer install --no-dev
```

Maybe that is why you don't install "generators" from the start.

I will close this issue because I understand you solved the problem, but if this is still there, you can reopen or create a new one.

Cheers.

**Comment by smart4you** [comment]
Hi, I didn’t open this ticket or issue, it was done by the user @amigolj. I just wrote a comment that I had a similar problem
