### ISSUE TITLE
Issue when deleting record from MySQL

### ISSUE THREAD

**Issue by soliduskodas** [Laravel-Backpack/CRUD#542]
Hello, 

I have a problem with deleting record. When I click button "Delete" I get an error: http://prntscr.com/ejpmmu

I'm using CRUD::resource(): http://prntscr.com/ejpnbz

Console: 
http://prntscr.com/ejpnq9

Headers: 
http://prntscr.com/ejpnx5

Where is the problem?

Thanks.

**Comment by tabacitu** [comment]
Hi @soliduskodas ,

Your server might not have "DELETE requests" enabled. Does the delete process work on your local environment?

Cheers!

**Comment by soliduskodas** [comment]
Thanks for your answes @tabacitu 

If I working on localhost - everything ok. 
How can I enable "DELETE request" in the server? Can I do this using Direct Admin?

**Comment by tabacitu** [comment]
Hmm... No idea, haven't used DirectAdmin before. Best to ask your hosting company, they'll definitely be able to enable it for you.

Cheers!
