### ISSUE TITLE
[Bug] Creating a New Operation With a Form not work

### ISSUE THREAD

**Issue by lionalex** [Laravel-Backpack/CRUD#5421]
# Bug report

### What I did

Installed a blank project with laravel 10.40 and backpack 6.5. I crate a custom operation with command
`php artisan backpack:crud-form-operation Comment`
Add 
`use \App\Http\Controllers\Admin\Operations\CommentOperation;`
in
`Http/Controllers/Admin/UserCrudController.php`
Add
```
$this->crud->operation('comment', function () {
        $this->crud->field('message')->type('textarea');
    });
```
in function
`setupCommentDefaults`

### What I expected to happen
In USERS list the action link to "comment" form

### What happened

In the list not show any additional action link

### What I've already tried to fix it

Change laravel version or backpack version

### Is it a bug in the latest version of Backpack?
I don't know if the bug was in all version's of backpack

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.14 (cli) (built: Dec 23 2023 10:48:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.14, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.40.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.2
backpack/crud: 6.5.2
backpack/generators: v4.0.2
backpack/permissionmanager: 7.1.1
backpack/theme-coreuiv4: 1.1.1

**Comment by jorgetwgroup** [comment]
hello @lionalex our team is working to fix this issue.

Soon we will have news for this.

Cheers.

**Comment by pxpm** [comment]
This was fixed in https://github.com/Laravel-Backpack/CRUD/releases/tag/6.5.3

Thanks for the report @lionalex 🙏 

Thanks @jorgetwgroup for confirming 👍 

Cheers
