### ISSUE TITLE
crud.js, form.js, create.js not showing in the page

### ISSUE THREAD

**Issue by ihsanberahim** [Laravel-Backpack/CRUD#543]
I saw `../myproject/vendor/backpack/crud/src/resources/views/create.blade.php` got `@section('after_scripts')` with:

```
@section('after_scripts')
	<script src="{{ asset('vendor/backpack/crud/js/crud.js') }}"></script>
	<script src="{{ asset('vendor/backpack/crud/js/form.js') }}"></script>
	<script src="{{ asset('vendor/backpack/crud/js/create.js') }}"></script>
@endsection
```

I saw `../myproject/resources/views/vendor/backpack/base/layout.blade.php` got `@yield('after_scripts')`.

But when i view source code in my crud those scripts files not in the page document? 

Is it a bug or i did mistakes?

**Comment by tabacitu** [comment]
Hi @ihsanberahim ,

Just pushed a fix for this. It's the same bug as this one - https://github.com/Laravel-Backpack/CRUD/issues/541 - right? 

Cheers!
