### ISSUE TITLE
[Bug] nestedSortable is not a function

### ISSUE THREAD

**Issue by gaborfarkas0211** [Laravel-Backpack/CRUD#5436]
# Bug report

### What I did

Use ReorderOperation trait, and set up the required fields ('label' and 'max_level').
Opening the /reorder route from the list operation to reorder tree elements with drag and drop.

### What I expected to happen

Could reorder the tree elements with drag and drop.

### What happened

Console error on page load:
Uncaught TypeError: $(...).nestedSortable is not a function
at HTMLDocument.<anonymous> (reorder:656:28)

### What I've already tried to fix it

I've made several attempts with the basset to import the lib, but none of the versions succeeded. In the end, I copied the content of the file "jquery.mjs.nestedSortable2.js" from "vendor/backpack/crud/src/resources/assets/libs" and pasted it between the script tags in the "after_scripts" section of the "reorder.blade.php" file, and that's how the ordering worked.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

- backpack/basset: 1.2.2
- backpack/crud: 6.6.1
- Laravel 10.41.0.0
- PHP 8.3.2

**Comment by jcastroa87** [comment]
Hello @gaborfarkas0211 did you try with a clean installation?

I tested with our demo :

```
use \Backpack\CRUD\app\Http\Controllers\Operations\ReorderOperation;

public function setup()
{
    CRUD::setModel(\App\Models\PetShop\Owner::class);
    CRUD::setRoute(config('backpack.base.route_prefix').'/pet-shop/owner');
    CRUD::setEntityNameStrings('owner', 'owners');

    $this->crud->enableReorder('name', 2);
}
```

And is working as expected (no console log)

<img width="1599" alt="Screenshot 2024-02-01 at 14 54 09" src="https://github.com/Laravel-Backpack/CRUD/assets/44643608/c1e61659-96af-4596-919f-7364695fb959">

Here is tested versions:

```
### PHP VERSION:
PHP 8.2.11 (cli) (built: Oct  6 2023 09:46:55) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.31.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.0
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.1
backpack/crud: 6.3.0
backpack/demo: dev-main
backpack/editable-columns: 3.0.2
backpack/filemanager: 3.0.5
backpack/generators: v4.0.2
backpack/language-switcher: 1.0.1
backpack/logmanager: v5.0.1
backpack/medialibrary-uploaders: 1.0.1
backpack/menucrud: v4.0.1
backpack/newscrud: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.1.1
backpack/pro: 2.0.18
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.2.2
backpack/theme-coreuiv4: 1.1.1
backpack/theme-tabler: 1.1.1
```

If you have a problem with basset, did you try to clean cache:
```
php artisan basset:clear
```

Or follow the instructions [here](https://github.com/Laravel-Backpack/basset)

Cheers

**Comment by gaborfarkas0211** [comment]
Thank you for your help, basset did not work properly because the APP_URL was not set correctly - php artisan basset:check command helped from the documentation.
