### ISSUE TITLE
[Bug] Missing CustomViewOperation

### ISSUE THREAD

**Issue by Metalchocobo** [Laravel-Backpack/CRUD#5449]
# Bug report

### What I did

`class YourCrudController extends CrudController
{
    ...
    use \Backpack\Pro\Http\Controllers\Operations\CustomViewOperation;`

### What I expected to happen

I expect to use Custom View.

### What happened

I take error:
`Trait "Backpack\Pro\Http\Controllers\Operations\CustomViewOperation" not found`

### What I've already tried to fix it

I tried to looking for the correct operation file in the vendor folder, but found nothing.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug is it still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.3.2 (cli) (built: Jan 16 2024 13:46:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.35.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.2
backpack/crud: 6.6.3
backpack/devtools: 3.0.4
backpack/generators: v4.0.2
backpack/logmanager: v5.0.1
backpack/permissionmanager: 7.1.1
backpack/pro: 2.0.20
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-tabler: 1.1.2

**Comment by karandatwani92** [comment]
Hey @Metalchocobo 

CustomViewOperation is a part of the PRO package, which was released on [2.1.0](https://github.com/Laravel-Backpack/PRO/releases/tag/2.1.0).

You have `backpack/pro: 2.0.20` installed, try updating the PRO package `composer update backpack/pro`. You will have it.

**Comment by Metalchocobo** [comment]
Thank you very much! 
Thanks for fixing fix custom view route identification quickly!  (yesterday was broken and today works!
