### ISSUE TITLE
[Bug] Installation freezes on SQLite

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#5456]
# Bug report

### What I did

Installed a fresh Laravel, then Backpack on top:
```
laravel new installation-failes-on-sql
# chose no starter kit
# chose SQLite as the DB when asked

composer require backpack/crud
php artisan backpack:install
```

### What I expected to happen

Work.

### What happened

Installation got stuck here:
![CleanShot 2024-02-27 at 18 01 10@2x](https://github.com/Laravel-Backpack/CRUD/assets/1032474/ff5fb30b-7f62-4109-baaa-83776bfd4ae8)

### What I've already tried to fix it

Ran the [manual installation process](https://backpackforlaravel.com/docs/6.x/crud-how-to#how-to-manually-install-backpack). During it... 
- I found the first step gives an error 🤦‍♂️ but that's a different problem;
- I found when running `php artisan migrate` that it will ask me if I want to create the database (because it doesn't exist);
- if after that step I run `php artisan backpack:install`, all works great;

I don't know what we should do in this case... but we should do something, I do think people are going to use SQLite more and more nowadays that it's the default in Laravel 11.

### Is it a bug in the latest version of Backpack?

Yes, this would try to install the latest version of Backpack.

**Comment by pxpm** [comment]
Hey @tabacitu is it possible that you don't have sqlite extension enabled/installed ? 

I've just did a new project, using Laravel 11, ran `php artisan backpack:install`, created admin users and logged it, using sqlite:

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/f175ad62-75d2-4cc9-8f76-a72be2756c51)

![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/648a3bb5-8144-42b5-a05f-ae51b519c3f4)

Cheers

**Comment by pxpm** [comment]
Hey Cristian, I couldn't reproduce this again. 

I've just installed a fresh app, tried migrating first and after run the install, tried without migrations just run the install and everything went smooth. 

Please reopen and provide steps to reproduce if possible. 

Cheers
