### ISSUE TITLE
Calendar operation doesn't support getters

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#5461]
Hi, I'm trying to use calendar operation with a getter defined in my model.

```
protected $appends = [
        'caption'
    ];

public function getCaptionAttribute(): string
    {
       return $this['title'].' - '.$this['comments'];
    }
```
In my controller  i mapped the title field:

```
protected function getCalendarFieldsMap(): array
    {
        return ['title' => 'caption'];
    }
```

In the list view I can use the getter, no problem there, but if I toggle to calendar view the cells doesn't show the entries

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/653f7283-6b09-4528-bdee-57786039ff01)

backpack/backupmanager: v5.0.0
backpack/basset: 1.2.2
backpack/calendar-operation: 1.0.0
backpack/crud: 6.6.3
backpack/devtools: 3.0.4
backpack/editable-columns: 3.0.5
backpack/generators: v4.0.3
backpack/logmanager: v5.0.1
backpack/permissionmanager: 7.1.1
backpack/pro: 2.1.3
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.2.3
backpack/theme-coreuiv4: 1.1.1
backpack/theme-tabler: 1.2.0

**Comment by pxpm** [comment]
Thanks @miquelangeld . It makes sense to use it that way. 

I've already created the PR for it. @promatik should review it shortly 🙏 

Thanks

**Comment by pxpm** [comment]
Hey @miquelangeld it's done in version 1.0.3 of Calendar Operation that I just released. 

You may allow some time for our private repo to pick it up and a `composer update` should get you the fix 🙏 

Let us know if you find any other issue 🙏

**Comment by miquelangeld** [comment]
Thanks @pxpm @promatik !!

**Comment by miquelangeld** [comment]
Hi I just tested and doesn't seems to work, now I get a number instead.

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/68207117-dcd0-496b-9ebc-20015a435291)

**Comment by miquelangeld** [comment]
This is the same getter in list view 
![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/6f3152a7-0c4b-45bd-9244-3c3c59be7ff0)

**Comment by pxpm** [comment]
Hum .. something wrong then, I've just tested and it seems to be working as expected:
![image](https://github.com/Laravel-Backpack/CRUD/assets/7188159/ec60b99e-28d4-46bb-bada-91b6a74ad331)

```php
protected $appends = [
        'caption'
    ];

    public function getCaptionAttribute(): string
    {
       return $this->title.' - test accessor';
    }
```
Can you reproduce it in a clean project ?

**Comment by miquelangeld** [comment]
Ok, I cleared the view cache and now it works.

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/ba81a390-c12b-4d99-b289-a549656b166f)

 Still shows the number first, which now I see it's the hour but for some reason not shows the full hour (hour and minutes) and just show the hour. But this is another issue, so I will dig in to it. Thanks Pedro and sorry for the inconvenience.

**Comment by pxpm** [comment]
Not inconvenient at all. If it had an issue I would have liked to know. 👍 

Glad it's working! Thanks @miquelangeld 🙏
