### ISSUE TITLE
[Bug] Add support for Laravel 11

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/CRUD#5464]
# Bug report

### What I did

Try to update my application to Laravel 11 to test for the upcoming release.

### What I expected to happen

Everything working perfectly fine (you know, one can hope ;) )

### What happened

Some dependencies not allowing Laravel 11 yet, including this one.

### Further notes

Laravel 11 is scheduled to be released at March 12th, 2024. See also https://laravel.com/docs/master/releases for the release date estimate and the list of new features and https://laravel.com/docs/master/upgrade for the upgrade guide.

**Comment by karandatwani92** [comment]
Hey @jnoordsij

We are already on it. We will be pushing the support update after the launch of Laravel 11.

Thanks

**Comment by jnoordsij** [comment]
Ah I see I didn't check the MR's properly; let's just point out https://github.com/Laravel-Backpack/CRUD/pull/5457 here to people looking for it.

Keep up the great work!
