### ISSUE TITLE
Wrong date in calendar operations new entry

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#5465]
Creating a new entry using Calendar Operations the date in the form is always today's date, not the one selected in the calendar.

I removed the default value in my Create Operation but same result

```
CRUD::addField([   // date_range
            'name' => 'start,end', // db columns for start_date & end_date
            'label' => 'Fechas de reserva',
            'type' => 'date_range',
            //'default' => [Carbon::now()->startOfDay(), Carbon::now()->endOfDay()],
            'date_range_options' => [
                'drops' => 'down', // can be one of [down/up/auto]
                'timePicker' => true,
                'locale' => ['format' => 'DD/MM/YYYY HH:mm'],
            ],
        ]);

```
I expected that the date on the form is the same as the day from which I created the entry.

**Comment by miquelangeld** [comment]
Hi @karandatwani92 if you select for example day 13th in calendar and try to create an entry from there in the form the date selector use the 13th? or 11th

**Comment by karandatwani92** [comment]
Yes I choose different dates & time
![image](https://github.com/Laravel-Backpack/CRUD/assets/8214221/315b7854-669a-46dd-a281-f6f1b20b3676)

**Comment by miquelangeld** [comment]
I think maybe I didn't make myself clear, I mean if in the form the date that appears by default is the same as the day in the calendar.

If I try to create a new entry from calendar

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/1c89ffd0-dfbc-4998-86a1-e3f30fedab35)

I expect the default date in the select to be the same as in the calendar cell from I create the entry.

But the default is always "now" and not  20/03/2024
![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/b8e7b383-ecc3-4526-b022-c1ba74f80bde)

**Comment by karandatwani92** [comment]
Hey @miquelangeld 

I just noticed this feature was always there. Use the following to get the selected date & time:
```php
CRUD::field('start')->value(request()->start);
CRUD::field('end')->value(request()->end);
```

I also found a bug with the `start` value on the month view, which I have already reported. I'll update the status on this thread once it's solved.

Feel free to reopen the issue if it still needs to be solved!
