### ISSUE TITLE
[Bug] Not translated uploder column in translatable model error on update

### ISSUE THREAD

**Issue by ablunier** [Laravel-Backpack/CRUD#5466]
# Bug report

### What I did

Install Backpack 6, configure translatable models with translated columns but a not translated uploader column.

### What I expected to happen

To be able to create and update translatable models with translated columns but a not translated uploader column.

### What happened

On create it works as expected but on update I get a "Integrity constraint violation column cannot be null" on the uploader not translated column even when the validation and content are ok.

### What I've already tried to fix it

I debugged the Backpack source code and found out that the problem is with the `Backpack\CRUD\app\Library\Uploaders\Uploader::getOriginalValue` method. It checks if the model is translatable and the translation is enabled but it doesn't check if the attribute is translatable. I will submit a PR with my fix.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.12 (cli) (built: Oct 26 2023 17:33:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.43.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.2
backpack/crud: 6.6.1
backpack/filemanager: 3.0.7
backpack/generators: v4.0.3
backpack/pro: 2.0.23
backpack/settings: 3.1.0
backpack/theme-tabler: 1.2.0

**Comment by jcastroa87** [comment]
Hello @ablunier 

Thanks for reporting this issue, I will check about it and let you know the results; in case you push a PR, I will try to check it too.

Thanks again.

**Comment by jcastroa87** [comment]
I will close this issue due https://github.com/Laravel-Backpack/CRUD/pull/5467 is merged.

Thanks.
