### ISSUE TITLE
In o'clock hours calendar operations doesn't show minutes in calendar view

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/CRUD#5468]
Hi. 
Using Calendar operations if I create an entry with  o'clock hour in the from field, for example 10:00, in calendar doesn't show the minutes, only the hour. 

an example of two entries, one at 10:00 and another at 10:01

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/058b697b-f679-4852-8679-507be304b8eb)

I think it should always show the time in the same format "h:i" instead

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/19ce9246-ca14-4a45-bd25-a378b71ea3b5)

**Comment by miquelangeld** [comment]
By the way, this new calendar feature has saved me many hours of work, thank you!

**Comment by pxpm** [comment]
Hello @miquelangeld 

You should be able to configure that using `slotLabelFormat` property: https://fullcalendar.io/docs/slotLabelFormat

You should be able to change that configuration using: `CRUD::setOperationSetting('javascript-configuration', []);`

Let me know if that helps. 

Cheers

**Comment by miquelangeld** [comment]
Hello @pxpm thanks!!   sorry I should have read the documentation more carefully.

I think  slotLabelFormat   only affect  the slots in the day view:

![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/3865d5d7-24ca-4d66-9699-a3556d629f31)


I have achieved it with this configuration:

```
CRUD::setOperationSetting('javascript-configuration', [
            'views' => [
                'dayGridMonth' => [
                    'eventTimeFormat' => [
                        'hour' => 'numeric',
                        'minute' => '2-digit'
                    ]
                ]
            ]
        ]);
```
![image](https://github.com/Laravel-Backpack/CRUD/assets/6650266/2d09d6f6-9631-4c5c-9862-582637a14e3d)

**Comment by miquelangeld** [comment]
I close the issue
