### ISSUE TITLE
select2_multiple field styles not appearing correctly

### ISSUE THREAD

**Issue by scottgrayson** [Laravel-Backpack/CRUD#549]
![image](https://cloud.githubusercontent.com/assets/7796074/23958613/09efca6c-0979-11e7-92c0-e9deedb3abfa.png)

```
            [       // Select2Multiple = n-n relationship (with pivot table)
                'label' => "Venues",
                'type' => 'select2_multiple',
                'name' => 'venues', // the method that defines the relationship in your Model
                'entity' => 'venues', // the method that defines the relationship in your Model
                'attribute' => 'title', // foreign key attribute that is shown to user
                'model' => "App\Venue", // foreign key model
                'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
            ],
```

- no console errors
- options and selected venues are appearing correctly
- I am also using some select2_from_ajax fields that appear styled correctly

![image](https://cloud.githubusercontent.com/assets/7796074/23958905/f9f08bfa-0979-11e7-8929-d621f1dc2648.png)
looks like not all of the select 2 classes are being added

**Comment by tabacitu** [comment]
Hmm... this is a tricky one. 

If you comment out the declaration of the ```select2_from_ajax``` field (or any other fields, for that matter), does it show the select2 correctly?

Cheers!
