### ISSUE TITLE
[Bug] Call to undefined method Backpack\Basset\BassetManager::echoJs() 

### ISSUE THREAD

**Issue by bartjuh4** [Laravel-Backpack/CRUD#5493]
# Bug report

### What I did

Updated dependency backpack/crud to v6.7.6

### What I expected to happen

No errors

### What happened

Call to undefined method Backpack\Basset\BassetManager::echoJs() when calling @loadScriptOnce() blade directive in a template.

### What I've already tried to fix it

Switched loadScriptOnce to @basset(), this fixed the issue, but this should not break right?

### Is it a bug in the latest version of Backpack?

**Yes**

### PHP VERSION:
8.3.4

### LARAVEL VERSION:
11.3.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.1
backpack/crud: 6.7.6
backpack/generators: v4.0.5
backpack/permissionmanager: 7.2.0
backpack/pro: 2.1.12
backpack/theme-coreuiv2: 1.2.3

**Comment by bartjuh4** [comment]
echoJs was removed here: https://github.com/Laravel-Backpack/basset/commit/3f2e7c9427e8c5f5c07a39c600d8955978f7a53d but references to this method are not removed or updated.

**Comment by bartjuh4** [comment]
It also show a huge spinner below datatables since the package update. 

vendor/backpack/crud/src/resources/views/crud/inc/datatables_logic.blade.php line 16 outputs an image since the last version.

![Uploading Scherm­afbeelding 2024-04-13 om 08.59.48.png…]()

**Comment by jcastroa87** [comment]
Hi @bartjuh4 

Pedro will take this issue to check and fix it as needed.

Thanks for reporting this issue.

Cheers.

**Comment by pxpm** [comment]
Hey @jcastroa87 sorry my bad on this one. 

I already merged and released the fixed version. 

I saw @bartjuh4 gave an 👍 on the PR when I merged it so I didn't came back here to reply to him. 

I think by this time we can close this issue. 

Please @bartjuh4 let us know if you still experiencing issue 🙏 

Cheers
