### ISSUE TITLE
[Feature] column "year"

### ISSUE THREAD

**Issue by JayAhrDe** [Laravel-Backpack/CRUD#550]
I needed a column to show just the "year" from (year-)mysql-column.

Existing date-column just showed the year formatted as "1. January 2016", so I created a yopy using fixed format "Y".

If you want to add, do so. If I just missed the correct way of creating a year column, thanks for pointing out to me! :)

`year.blade.php`
```php
<td data-order="{{ $entry->{$column['name']} }}">
    @if (!empty($entry->{$column['name']}))
	{{ Date::parse($entry->{$column['name']})->format('Y') }}
    @endif
</td>```

**Comment by tabacitu** [comment]
Hi @JayAhrDE ,

Thanks for writing here how you managed to do it - might be helpful to others who search.

Cheers!
