### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LeMingon** [Laravel-Backpack/CRUD#5506]
# Bug report

jalalnabiyev@MacBook-Air-Jalal mashinbazari % php artisan backpack:install

   STEP 1  Installing Backpack CRUD.

  Publishing configs, views, routes and assets ........................................................................... DONE
  Creating users table ................................................................................................... DONE
  Creating CheckIfAdmin middleware ....................................................................................... DONE
  Installing Generators .................................................................................................. DONE
  Installing Basset ................................................................................................... RUNNING%                                       jalalnabiyev@MacBook-Air-Jalal mashinbazari % 

as you see terminal is stopped his work, but installing the basset is still in running status

??

### What I expected to happen

to finish step 1 and go to the 2 steps to create admin like in backpack documentation

### What happened

it happened when I tried this command: php artisan backpack: install

### What I've already tried to fix it

I tried try install it again, but it wouldn't help

### Is it a bug in the latest version of Backpack?
yes

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

PHP 8.3.3 (cli) (built: Feb 13 2024 15:41:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.48.8.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.3  -> Does it mean this is installed already, if yes why I am not able to go to step 2?
backpack/crud: v6.x-dev
backpack/generators: v4.0.5

**Comment by jcastroa87** [comment]
Hello @LeMingon can you share with me the content of composer.json please.

Did you try to install manually https://backpackforlaravel.com/docs/6.x/crud-how-to#how-to-manually-install-backpack

Cheers.

**Comment by LeMingon** [comment]
> Hello @LeMingon can you share with me the content of composer.json please.
> 
> Did you try to install manually https://backpackforlaravel.com/docs/6.x/crud-how-to#how-to-manually-install-backpack
> 
> Cheers.

Hello : )

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "backpack/crud": "v6.x-dev",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "backpack/generators": "^4.0",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}




I will try manually

**Comment by jcastroa87** [comment]
Could you try to set backpack to:

```
"backpack/crud": "^6.7",
```

And let me know how manually install work for you.

Cheers.

**Comment by LeMingon** [comment]
The issue was with step 2, I created an admin user manually regarding documentation and add theme [](https://github.com/Laravel-Backpack/theme-coreuiv2) from here because login page(route) gave me this error: 
"Could not find Backpack view [backpack.ui::auth.login] in theme namespace, fallback namespace nor UI namespace." // vendor/backpack/crud/src/helpers.php:259

Thank you for your help. : )
Cheers.

**Comment by LeMingon** [comment]
Was solved
