### ISSUE TITLE
Date field allow nullable save

### ISSUE THREAD

**Issue by raviroshanmehta** [Laravel-Backpack/CRUD#5515]
### I have a column in database which is nullable in migration definition. Until I don't save value it's working as expected but after saving value i don't have any option to save it NULL again. 

`CRUD::field('expiry')->type('date')->allows_null(true);`

#### I was expecting by passing allows_null(true) it should allow me to save null again in database but it's neither throwing any error nor allowing me to empty pre filled value.

Please let me know how can i do this ?

**Comment by karandatwani92** [comment]
Hey @raviroshanmehta 

The `Date` field uses the browser's date picker. Some browsers give clear options, while some don't.
For example, Google Chrome:
![Screenshot 2024-05-02 at 4 01 33 PM](https://github.com/Laravel-Backpack/CRUD/assets/8214221/60560ee2-d869-4928-b714-e4c3e28156c8)
