### ISSUE TITLE
[Bug] Pro: date_range filter undefined array key from

### ISSUE THREAD

**Issue by gaborfarkas0211** [Laravel-Backpack/CRUD#5519]
# Bug report

### What I did

I used the Pro package's date_range filter type. When I select a range, the filter works properly, but when I modify the query params to make a mistake in the json structure.

### What I expected to happen

The filter handle the json encoding properly and handle the from - to keys in the array.

### What happened

I have got an error: undefined array key "from".

### What I've already tried to fix it

There is no way for me to fix it unless I override the filter in my project.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
8.3.4
### LARAVEL VERSION:
11.7.0.0
### BACKPACK PACKAGE VERSIONS:
backpack/pro: 2.2.0

**Comment by gaborfarkas0211** [comment]
Hi @karandatwani92,

Thanks for your reply. It's not about the code itself, use the above code, set a filter, and then modify the URL's query of this filter.
e.g. the filtered URL query looks like this:
created_at=%7B"from"%3A"2024-05-16+13%3A50%3A54"%2C"to"%3A"2024-05-16+13%3A50%3A54"%7D

If I remove the %7B before "from", it will be an invalid JSON. After hitting enter, the json_decode($filter->currentValue) result will be an empty array.
created_at="from"%3A"2024-05-16+13%3A50%3A54"%2C"to"%3A"2024-05-16+13%3A50%3A54"%7D

This will cause this error: Undefined array key "from".

**Comment by karandatwani92** [comment]
So you want to throw an exception if the sent JSON is invalid?

**Comment by gaborfarkas0211** [comment]
No, I just want to handle the invalid JSON $dates result and set a default value e.g. null when the json_decode result is an empty array.

`$dates['from'] ?? null`
`$dates['to'] ?? null`

So the user can't make a 500 server error, and the filter will not work either.

The issue is the same with the simple range filter.

**Comment by karandatwani92** [comment]
OK, can you do `Try Catch` the block inside the closure? and Trigger [alert](https://backpackforlaravel.com/docs/6.x/base-alerts#triggering-alerts-in-php) if invalid

**Comment by karandatwani92** [comment]
Hey @pxpm @tabacitu

Need your two cents here.
