### ISSUE TITLE
3.2.7 issue ?

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#552]
I just upgrade to 3.2.7 and i have this error:

`Undefined variable: action (View: /home/ubuntu/workspace/vendor/backpack/crud/src/resources/views/form_content.blade.php) `

**Comment by OwenMelbz** [comment]
Hey I'm gonna close this for the time being as I dont think its a bug, I think its just custom views/methods.

As you can see the file here -> https://github.com/Laravel-Backpack/CRUD/blob/c9d599ec8ede008f4059961d4a418bf071695faa/src/resources/views/create.blade.php

Passes $action to the view, which would suggestion you have a custom create.blade.php or edit.blade.php etc, can you check all your published backpack views to make sure they pass the $action var to the form_content template please :)

**Comment by adbmdp** [comment]
Sorry i forgot about my custom edit.blade.php.
Thank you!

**Comment by isaacperaza** [comment]
@OwenMelbz I see this was solved, but this fix is not published to packagist.org. I still getting the same error even with ``` "backpack/crud": "3.2.11" ```.  **Note:** I do not custom views.

```
ErrorException in e415878ae0699e649aace55f03fcdc3b699d658e.php line 17:
Undefined variable: action (View: /var/www/vendor/backpack/crud/src/resources/views/form_content.blade.php)
```

#### form_content.blade.php
```php
<?php

...

{{-- Define blade stacks so css and js can be pushed from the fields to these sections. --}}

@section('after_styles')
    <link rel="stylesheet" href="{{ asset('vendor/backpack/crud/css/crud.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/backpack/crud/css/form.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/backpack/crud/css/'.$action.'.css') }}">

    <!-- CRUD FORM CONTENT - crud_fields_styles stack -->
    @stack('crud_fields_styles')
@endsection


...

```
