### ISSUE TITLE
[Bug] Getting started not readable in dark mode

### ISSUE THREAD

**Issue by Krisseck** [Laravel-Backpack/CRUD#5524]
# Bug report

### What I did

- Installed Backpack
- Logged in
- Was greeted with unreadable Getting started section

### What I expected to happen

Being able to read the text on the different steps

### What happened

The steps were white text on white background

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

Yes, fresh install

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
8.1.27

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, uploadprogress, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, Zend OPcache

### LARAVEL VERSION:
10.48.10.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.4
backpack/crud: 6.7.13
backpack/generators: v4.0.5
backpack/permissionmanager: 7.2.1
backpack/theme-tabler: 1.2.10
```

![Screenshot 2024-05-19 at 13-01-42 Dashboard Backpack Admin Panel](https://github.com/Laravel-Backpack/CRUD/assets/471887/5c4e0ead-f05e-41b0-94e5-7125a9baa5d1)

**Comment by karandatwani92** [comment]
Hey @Krisseck 

Getting started is fine:
![image](https://github.com/Laravel-Backpack/CRUD/assets/8214221/af9a5b8c-fa89-40d6-aef2-896695faa08f)

It seems the theme is not properly configured at your end. The following files are not loaded:
```
// vendor/backpack/theme-tabler/config/theme-tabler.php
'styles' => [
        base_path('vendor/backpack/theme-tabler/resources/assets/css/color-adjustments.css'),
        base_path('vendor/backpack/theme-tabler/resources/assets/css/colors.css'),
    ],
```
Please retry and let me know if you still face it.
