### ISSUE TITLE
Backpack laravel multiple file upload - preview/download is not working

### ISSUE THREAD

**Issue by blessen131** [Laravel-Backpack/CRUD#5546]
I am trying to upload/view multiple files with Backpack:5.x

Code for the file upload
```
Controller

 $this->crud->addfield([
            'name'    => 'files',
            'label'   => 'Files',
            'upload'    => true,
            'type'    => 'upload_multiple',
        ]);

Model

public function setFilesAttribute($value)
    {
        $attribute_name = "files";
        $disk = "uploads";
        $destination_path = "notes";

        $this->uploadMultipleFilesToDisk($value, $attribute_name, $disk, $destination_path);
    }

config/filessystems.php

'uploads' => [
            'driver' => 'local',
            'url' => env('APP_URL').'/uploads',
            'root' => public_path('uploads'),
        ],
```

Problem 1: Files saved in public/uploads/notes directory but when I edit an item, the url for the uploaded file is www.test.com/notes/file.txt getting 404(missing the /**uploads**/notes/file.txt).

Problem 2: When I am trying to add in list view, I am getting this error - count(): Parameter must be an array or an object that implements Countable (View: /vendor/backpack/crud/src/resources/views/crud/columns/upload_multiple.blade.php)

``` 
$this->crud->addColumn([
            'name'    => 'files',
            'label'   => 'Files',
            'type'    => 'upload_multiple',
        ]);

**Comment by karandatwani92** [comment]
Hey @blessen131 

I'm assuming you have an `upload` disk defined in `config/filesystems.php`. 

From your code, I can see that:
1. You are saving the file to `$disk = "uploads";` but you have not defined the same disk in the column or field for reading. Please add `'disk' => 'upload'` to the column & field definition.
2. You need to cast the field to the array in your model:
```
protected $casts = [
   'files' => 'array',
];
```

I hope this helps. I recommend you upgrade to v6. It comes with automatic file handling/uploading/deletion features and many other valuable features. Support for v5 has been discontinued, and [Community-forum](https://github.com/Laravel-Backpack/community-forum) would be the right place for queries like this.

See you around. Have a great day.
