### ISSUE TITLE
Hidden field type fills vertical space on the form.

### ISSUE THREAD

**Issue by Alexgmin** [Laravel-Backpack/CRUD#555]
Since input type hidden are still wrapped by `<div class="form-group col-md-12"></div>`, and the form group class has `.form-group {
    margin-bottom: 15px;
}`, these inputs still fill some space. For example this is with 4 hidden inputs.
![image](https://cloud.githubusercontent.com/assets/8340441/24055236/98cdbae2-0b3f-11e7-8799-8db448dcb8e6.png)

As far as I can see, making this view `crud/src/resources/views/inc/field_wrapper_attributes.blade.php` check if it's a hidden input before returning the class styles should be enough.

**Comment by MarcosBL** [comment]
You can specify wrapper attributes, maybe something like this could help

````php
$this->crud->addField([
    'name'  => 'xxxx',
    'label' => 'xxxx',
    'type'  => 'hidden',
    'attributes' => [
       'class' => 'form-control hidden'
     ],
     'wrapperAttributes' => [
       'class' => 'form-group col-md-12 hidden'
     ]
]);

**Comment by Alexgmin** [comment]
Yeah, that works as a temporal fix, but i don't think this behavior should be the right one. 
A hidden field should be fully hidden.

**Comment by tabacitu** [comment]
Damn! Thanks, @Alexgmin , I completely agree - hidden should be hidden all the way. Should fix, so let's leave this open until we do.

Cheers!

**Comment by tabacitu** [comment]
Fixed in https://github.com/Laravel-Backpack/CRUD/commit/c72708cfa630c64dcc6faaa5d26cf0bf23e30d49 that's just been merged into DEV. Will be in production shortly.

Cheers, thanks a lot for the bug report and solution!
