### ISSUE TITLE
Set access for each item

### ISSUE THREAD

**Issue by alashow** [Laravel-Backpack/CRUD#557]
Seems like there is no option for setting access for each item individually.

For example, I wanted to limit updating/editing/deleting access to the user who has created the post (or to users that have certain permissions).

I implemented backend verification like this:
```php
public function update(UpdateRequest $request)
    {
        $this->denyIfNotParent($request->get('id'));
        //...
    }

public function edit($id)
    {
        $this->denyIfNotParent($id);

        return parent::edit($id);
    }

public function destroy($id)
    {
        $this->denyIfNotParent($id);

        return parent::destroy($id);
    }
public function denyIfNotParent($id)
    {
        if(accessLogicHere()){
            abort(403);
        }
    }
```

But I couldn't hide buttons (Edit, Delete).

Any suggestions?

Thanks.

**Comment by MarcosBL** [comment]
In the CRUD controller:

````php
// ------ ACCESS
$this->crud->allowAccess('list');
$this->crud->allowAccess(['list', 'create', 'delete']);
$this->crud->denyAccess('list');
$this->crud->denyAccess(['list', 'create', 'delete']);

$this->crud->hasAccess('add'); // returns true/false
$this->crud->hasAccessOrFail('add'); // throws 403 error
$this->crud->hasAccessToAll(['create', 'update']); // returns true/false
$this->crud->hasAccessToAny(['create', 'update']); // returns true/false

**Comment by alashow** [comment]
@MarcosBL I know about this API, but it's not what I want. This API is intended for all items.
> no option for setting access for **_each item individually_**

Another example:
All users have access to PostsCrud. User **A** creates a post. User **B** can see it (e.g in listing), but cannot edit it or delete it.

**Comment by OwenMelbz** [comment]
Sounds like you'll have to roll that functionality yourself.

Backpack is a great starting point for admin panels. If your making something that's not really an admin panel but allows editing of user created content, then that will be custom, you'll need to maybe have 2 methods which setup the crud differently depending on the users permissions.

As this isn't a bug, I will just close it to keep the area bugs only. But feel free to keep replying

**Comment by alashow** [comment]
Maybe you misunderstood my issue, but I only wanted to get some help/suggestions from creators or maybe from others that faced this issue.

Thanks!

**Comment by OwenMelbz** [comment]
I suggested you'd have 2 different crud methods, one for people who can edit, one for people who cannot edit.

In the setup method you can detect the user, then based off what ever you want you can send them to a different methods, which configures the form differently

**Comment by alashow** [comment]
To achieve what I need from setup, I would need "item" instance.

But even if I could access instance of the item, that would not solve my issue of hiding buttons.

**Comment by MarcosBL** [comment]
You can remove the whole items not available to an user in the Model:

````php
	public static function boot()
	{
	    parent::boot();
	    static::addGlobalScope('userfilter', function (Builder $builder) {
	        $builder->where('user', $GetYourUserIdHere);
	    });
	}
````
Then, all calls to that model will be automagically filtered by user.  If you need to get the Model without that scope in other parts of the app, you can:

````php
MyModel::withoutGlobalScope('userfilter')->get()

**Comment by Athuli7** [comment]
I had 2 instances where I needed this.

I did a poor implementation both times that hid the entries, but the entries could always be edited by manually entering the URL. entity/{id}/edit.

1. Lock the cases from certain users.
> $this->crud->addClause( The rule you want )

2.Lock the edit permission from some.
> $this->crud->removeButton('edit');
> $this->crud->addButtonFromModelFunction ( function in the model that does the validation )

Both are stupid hacks that I used because I wanted a quick fix without touching the vendor code and because I knew the user would never try and go around the system.

Btw, It is also possible to implement this using Eloquent events. Haven't tried it though.

**Comment by Librasulus** [comment]
I am looking for that functionality too. I understand it is not something expected of Backpack, but perhaps it has been implemented somehow?

**Comment by tabacitu** [comment]
@Librasulus - not implemented in Backpack per-se. I think your best bet is using a global scope on the model, like @MarcosBL has suggested here - https://github.com/Laravel-Backpack/CRUD/issues/557#issuecomment-287796737 . Seems like the cleanest solution to me.

**Comment by Librasulus** [comment]
@tabacitu what @MarcosBL suggested was about filtering the whole model. I just want to remove the edit button and route for the users that do not have ownership of the record in the list, as @alashow had asked at first. I suspect it requires some heavy overriding in the setup method of the controller.

**Comment by MarcosBL** [comment]
Hidding the edit button is easy (even if ugly), just extend the list with a custom edit button and hardcode your needs in a custom edit button view; not registering the route seems a bit harder... maybe is it posible to extend the edit controller (even having the route) and inject your logic also there ?

Maybe you can setup a custom `CanEdit` accesor in the model that checks for permissions, and call it from both from the edit button + from the edit controller, I know it's not perfect, but maybe can give you some direction.

**Comment by Librasulus** [comment]
@MarcosBL Indeed, I was thinking something like that. About the edit route, for now I can just restrict access by just having an authorization check in the edit method. About the view, I have no idea how to extend the list and override the edit button, I will figure it out somehow.

Thank you for your time and for confirming my suspicions!

**Comment by MarcosBL** [comment]
Just place a `update.blade.php` in `resources/views/vendor/backpack/crud/buttons/update.blade.php` copying the content of the vendor folder, and that's all.

It starts with something like (mine is heavily modified):

````php
@if ($crud->hasAccess('update'))
	@if (!$crud->model->translationEnabled())

...
````

As you can see, you can easily add there your own checks, maybe you don't even need to extend the list :+1:

**Comment by Librasulus** [comment]
I managed permission for each record by doing the following steps:

1) Restricting access to edit records for all users except administrator by adding to the setup method of the task controller:
    
        $this->crud->denyAccess('update');            
        if(auth()->user()->hasRole('admin')){
          $this->crud->allowAccess('update');
        }

2) Opening access to the owner of the record by overriding the edit and update methods:
```
public function edit($id)
    {
      $task = $this->crud->getEntry($id);
      if (auth()->id() == $task->owner->id) {
      $this->crud->allowAccess('update');
    }
      return parent::edit($id);
    }

public function update(UpdateRequest $request)
    {
      $task = $this->crud->getEntry($request->id);
      if ( auth()->id() == $task->owner->id ){
      $this->crud->allowAccess('update');
    }
      $redirect_location = parent::updateCrud($request);
        
      return $redirect_location;
    }
````

3) Adding a permission check on the edit button (update.blade.php) for the owner:
```
@if (auth()->user()->id==$entry->owner->id || $crud->hasAccess('update'))  
	@if (!$crud->model->translationEnabled())
	<!-- Single edit button -->
	<a href="{{ url($crud->route.'/'.$entry->getKey().'/edit') }}" class="btn btn-xs btn-default"><i class="fa fa-edit"></i> {{ trans('backpack::crud.edit') }}</a>
...

```
In this way only the records of the logged user have an edit button, unless the user has the appropriate permissions. Also the routes are protected.

**Comment by MarcosBL** [comment]
Clever solution @Librasulus !

Just one doubt, as you don't set the access to the edit route to those not having permission, and the default edit button already checks for that, do you really need to override the default `edit.blade.php` file ?

Otherwise, that would give us a **pure Backpack way** of doing it

**Comment by Librasulus** [comment]
Thank you @MarcosBL , you were really helpful.

The access to the edit route was restricted in the setup method, which doesn't take into account the information of each record. That means that the default result for the normal user was the edit button not appearing, as the $crud->hasAccess('update') condition in the blade file returned false. I had to provide an alternative record-based condition, so after the setup methods only the blade file was left as an option. 

Perhaps I misunderstand something, I am grateful for any more elegant solutions.

**Comment by MarcosBL** [comment]
You are absolutely right, even if the `update.blade.php` have access to the `$entry` var, of course it doesn't check for an `entry->hasAccess('update')` so you must override with your own; anyway, at least the most elegant solution I think we have for this kind of situation, so great work :+1: this will surely help others

**Comment by lborrazas** [comment]
```
@if(($entry instanceof Simulation && ($entry->checkOwner(backpack_user()->id))) || !$entry instanceof  \App\Models\Simulation )
    @if ($crud->hasAccess('update') )
        @if (!$crud->model->translationEnabled())
```

I had only one model that needed this and I fixed it this way at update.blade.php anyway i think it shouldnt be hard to make a way to set up a callback access function at controlller so it checks whatever u put there.

(Desirable Solution at Controller)
`Setup(){
setAccessForEntry ('update', function(){return  entry->user_id == backpack_user->id})
}`

**Comment by aula2030** [comment]
Hi! I was looking for the same behaviour. In version 4.1, I had to do:

0. I'm NOT denying access to all.
1. Overwrite button view and add condition to show/hide.
2. Overwrite edit() and update() functions to check/allow/deny access:

```
use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation { edit as protected editTrait; update as protected updateTrait; }

....
protected function edit($id)
{
    $element = $this->crud->getEntry($id);
    if (condition) {
        $this->crud->allowAccess('update');
    } else {
        $this->crud->denyAccess('update');
    }
    return $this->editTrait($id);
}

protected function update()
{
    $element = $this->crud->entry;
    if (condition) {
        $this->crud->allowAccess('update');
    } else {
        $this->crud->denyAccess('update');
    }
    return $this->updateTrait();
}
```

Denying to all and allowing just when condition is true was not working. Sorry, my knowledge of the package is not so deep yet to explain why :)

Regards!

**Comment by tabacitu** [comment]
Thanks for sharing your solution @aula2030 !
