### ISSUE TITLE
[Bug] Saving reorder results in error

### ISSUE THREAD

**Issue by eleven59** [Laravel-Backpack/CRUD#5571]
# Bug report

### What I did

Click reorder items, click save on the reorder page

### What I expected to happen

Order saved

### What happened

Error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'`

### What I've already tried to fix it

Created an entirely new project, then a new model + crud, exactly followed the instructions for Reorder at [https://backpackforlaravel.com/docs/6.x/crud-operation-reorder](https://backpackforlaravel.com/docs/6.x/crud-operation-reorder). Same error.

I fixed it by editing `vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Reorder.php` and commenting the following lines (36-37):

```php
//            $item['name'] = '';
//            $item['slug'] = '';
```

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
8.3.9

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, FFI, fileinfo, filter, ftp, gd, gmp, json, iconv, SPL, session, standard, mbstring, igbinary, imagick, imap, intl, ldap, exif, mysqlnd, mysqli, pcntl, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, random, readline, redis, Reflection, shmop, SimpleXML, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zstd, Zend OPcache

### LARAVEL VERSION:
11.16.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.20
backpack/generators: v4.0.5
backpack/pro: 2.2.8
backpack/settings: 3.1.1
backpack/theme-tabler: 1.2.11
```

**Comment by pxpm** [comment]
may be related with #5342 

Thanks for the report @eleven59 , I will investigate.

**Comment by pxpm** [comment]
Thanks @eleven59 for the report. 🙏  I've just released a fix for the issue. 

Let me know if you are still experiencing issues. 

Cheers
