### ISSUE TITLE
DigitallyHappy\Toggle-Field-For-Backpack Installation failed

### ISSUE THREAD

**Issue by blessen131** [Laravel-Backpack/CRUD#5573]
Trying to install DigitallyHappy\Toggle-Field-For-Backpack on backpack/crud 6.7 

Problem 1
- digitallyhappy/toggle-field-for-backpack[1.0.0, ..., 1.0.2] require backpack/crud ^4.0.0 -> found backpack/crud[4.0.0, ..., 4.1.71] but it conflicts with your root composer.json require (^6.7).
- digitallyhappy/toggle-field-for-backpack 2.0.0 requires backpack/crud ^4.1.0 -> found backpack/crud[4.1.0, ..., 4.1.71] but it conflicts with your root composer.json require (^6.7).
- digitallyhappy/toggle-field-for-backpack 2.0.1 requires backpack/crud ^4.1|^5.0 -> found backpack/crud[4.1.0, ..., 4.1.71, 5.0.0, ..., 5.6.1] but it conflicts with your root composer.json require (^6.7).
- Root composer.json requires digitallyhappy/toggle-field-for-backpack * -> satisfiable by digitallyhappy/toggle-field-for-backpack[1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1].

**Comment by karandatwani92** [comment]
Hey @blessen131 

That repo is outdated and no longer compatible. The newer toggle field is available [here](https://backpackforlaravel.com/docs/6.x/crud-fields#switch-1)
