### ISSUE TITLE
How can I retrieve a list of all available field types defined in Backpack?

### ISSUE THREAD

**Issue by axlot** [Laravel-Backpack/CRUD#558]
I am creating a poll generator app, my idea is to use the field types and allow the user to create a poll by selecting the field types for the questions and type of answers.

That is why I will need to retrieve a list of field types.

After the user created the poll, my idea is to create a specific crud for that poll so I can present that to the users that will  complete the poll.

Thanks in advance, and sorry if its not the correct place to ask this questions.

**Comment by MarcosBL** [comment]
All available fields are listed in `/src/resources/views/fields/` but some of them will not be adecuate for that usage (upload, base64_image, custom_html, date...), you better create an array of options, it will allow you to define your custom fields as well.

**Comment by OwenMelbz** [comment]
You could of course glob the vendor dir to pull out all the fields you want, then merge with your resource folder. 

But as @marcosBL said not everything will be appropriate, and if we ever change the directory structure your application will break.

I as well would just suggest hardcode a config item with all the field types you need in it, which will be more deployable, easier to monitor and track file changes using a VCS and it won't add a performance overhead either as reading files is slow
