### ISSUE TITLE
[Bug] File Deletion Error on Create Operation in Dropzone Integration

### ISSUE THREAD

**Issue by netskycz** [Laravel-Backpack/CRUD#5585]
**Description:**

We have encountered an issue with the Dropzone file upload feature in our Laravel Backpack integration. The problem occurs specifically during the "Create" operation, while the "Update" operation works as expected.

**Issue Details:**

- **Error Occurrence:** The error arises when attempting to delete temporary files after they have been moved to the designated storage location.
- **Error Message:** The error log records the following message:
`local.ERROR: League\Flysystem\Filesystem::write(): Argument #2 ($contents) must be of type string, null given
`
- **Environment:** The issue occurs consistently on our staging and production environments.
- **Temporary Disk:** The issue is related to the `Storage::disk($temporaryDisk)->delete($value);` line in the `DropzoneOperation` trait. Specifically, the `$value` appears to be `null` or improperly formatted, leading to the deletion failure.
- **Additional Observations:** The problem does not manifest when updating existing records, suggesting it is related to the initial file upload and handling process during creation.

We need to investigate the file handling and deletion logic, particularly the differences between the Create and Update operations, and why the `$value` might be `null` or incorrect only in the Create operation. Further logs and testing will be necessary to isolate and resolve the issue.

### PHP VERSION:
8.3.6

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, exif, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

### LARAVEL VERSION:
10.48.14.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.23
backpack/devtools: 3.1.5
backpack/generators: v4.0.5
backpack/pro: 2.2.11
backpack/theme-tabler: 1.2.11

**Comment by jcastroa87** [comment]
Hello @netskycz can you please share the field and controller configuration to replicate the error.

Thanks.

Cheers.

**Comment by jcastroa87** [comment]
Hello @netskycz 

I try to replicate the error, but I could, everything work as expected.

<img width="858" alt="Screenshot 2024-08-01 at 3 09 50 PM" src="https://github.com/user-attachments/assets/fefb3ab1-c713-4b15-9125-bb79853ac6e8">

i see all the values to operate normally.

Could you please share more information to replicate this issue, did you try this field and config in a clean install.

Thanks.

**Comment by jcastroa87** [comment]
Due to not activity i will close this issue, but please feel free to re-open or create a new one if needed.

Cheers.
