### ISSUE TITLE
[Bug] select2_from_array in allows_multiple mode closes with each selection

### ISSUE THREAD

**Issue by rezahmady** [Laravel-Backpack/CRUD#5597]
# Bug report

### What happen

![Untitled Project](https://github.com/user-attachments/assets/84d203a5-ee2d-4df5-be01-ab408cd572f6)

When using the select2_from_array field in the allows_multiple mode, it closes with each selection of an item, and you have to open it again and make the next selection.

### What I expected to happen

It should not be closed in allows_multiple mode by selecting any option until it is clicked outside

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
8.3.6

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, xmlreader, xmlwriter, curl, ftp, fileinfo, gd, intl, mbstring, exif, mysqli, Phar, pdo_mysql, xsl, zip

### LARAVEL VERSION:
10.48.15.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.4
backpack/crud: 6.7.24
backpack/editable-columns: 3.0.9
backpack/filemanager: 3.0.8
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/pro: 2.2.4
backpack/revise-operation: 2.0.0
backpack/theme-coreuiv2: 1.2.4

```

**Comment by pxpm** [comment]
Hello @rezahmady thanks for the heads up. 🙏 

I've just added the option `closeOnSelect` to all out select2 fields that accept multiple selections. This will be the default behavior (not close select multiples by default), in my opinion that's what make more sense. 

I've just released backpack/pro 2.2.12 with the changes, please allow sometime for our private repository to pick the changes and you can then do a `composer update` to get the updated version 👍 

Let me know if you are still experiencing issues after the update. 

Cheers
