### ISSUE TITLE
[Bug] MorphOne workaround relation is not saved despite online demo example

### ISSUE THREAD

**Issue by manfield** [Laravel-Backpack/CRUD#5620]
# Bug report

### What I did

What I'm trying to do is having a polymorphic one to one (MorphOne)  dropdown selection on my CRUD model.
It seems the only way to do this, without subfields and with a select, is a sort of workaround, copied from your demo code on the Monster Panel (the one running as online demo, because I cannot try your demo code in local 'cause I don't have all the necessary subscription).
Here your demo schema and mine:

![image](https://github.com/user-attachments/assets/ff61876c-dcc4-4147-82cf-a45946e5b3f2)

The goal would be have a one to one relation (polymorphic because I will use with different models) between Articles and Topics.
I want to have a select box on the CRUDPanel of the main model (Article), to pick one Topic.

According to the documentation this is not doable with the standard MorphOne relationship (because it only supports a subform, or separate fields, but I need a select dropdown).
Looking around I saw you use a workaround on your demo, that follows the schema I copied before.

These are the methods of the models (they follow what you did on your demo, only naming is different):

**Article**

```
    public function topic_pivot()
    {
        return $this->morphOne(TopicPivot::class, 'topic_pivotable');
    }
```

**TopicPivot**

```
    protected $fillable = [
        'topic_id',
    ];

    public function topic()
    {
        return $this->belongsTo(Topic::class);
    }

    public function topic_pivotable()
    {
        return $this->morphTo();
    }
```

And this the field in the ArticleCrudController

```
        $this->crud->addField(
            [
                'label'     => "Topic",
                'name'  => 'topic_pivot.topic',
            ]);

```

### What I expected to happen

Relations are built up correctly on the CRUDPanel

![image](https://github.com/user-attachments/assets/c9cd024a-2d8e-4758-86af-e7ce762d780b)

Though they are not saved.

### What happened

I don't know exactly what's going on.
The strange thing is that debugging  `Backpack/CRUD/tree/main/src/app/Library/CrudPanel/Traits/Create.php` every `if ` statements is bypassed, because `$formattedRelations` is an array with a single element (topic_pivot) whose `$relation_type='belongsTo'` that does not match any of the  `case`  statements in the Trait's `createRelationsForItem()`.

![image](https://github.com/user-attachments/assets/9291aae3-828e-4345-85ec-d2ab8cebebfa)

```
private function createRelationsForItem($item, $formattedRelations)
    {
        // no relations to create
        if (empty($formattedRelations)) {
            return false;
        }

        foreach ($formattedRelations as $relationMethod => $relationDetails) {
            $relation = $item->{$relationMethod}();
            $relationType = $relationDetails['relation_type'];

            switch ($relationType) {
                case 'HasOne':
                case 'MorphOne':
                    $this->createUpdateOrDeleteOneToOneRelation($relation, $relationMethod, $relationDetails);
                    break;
                case 'HasMany':
                case 'MorphMany':
                    $relationValues = $relationDetails['values'][$relationMethod];
                    // if relation values are null we can only attach, also we check if we sent
                    // - a single dimensional array: [1,2,3]
                    // - an array of arrays: [[1][2][3]]
                    // if is as single dimensional array we can only attach.
                    if ($relationValues === null || ! is_multidimensional_array($relationValues)) {
                        $this->attachManyRelation($item, $relation, $relationDetails, $relationValues);
                    } else {
                        $this->createManyEntries($item, $relation, $relationMethod, $relationDetails);
                    }
                    break;
                case 'BelongsToMany':
                case 'MorphToMany':
                    $values = $relationDetails['values'][$relationMethod] ?? [];
                    $values = is_string($values) ? (json_decode($values, true) ?? []) : $values;
                    $field = $relationDetails['crudFields'][0] ?? [];

                    // if the values are multidimensional, we have additional pivot data.
                    if (is_array($values) && is_multidimensional_array($values)) {
                        // if the field allow duplicated pivots, we can't use sync or attach from laravel, we need to manually handle the pivot data.
                        if ($field['allow_duplicate_pivots'] ?? false) {
                            $keyName = $field['pivot_key_name'] ?? 'id';
                            $sentIds = array_filter(array_column($values, $keyName));
                            $dbValues = $relation->newPivotQuery()->pluck($keyName)->toArray();

                            $toDelete = array_diff($dbValues, $sentIds);

                            if (! empty($toDelete)) {
                                foreach ($toDelete as $id) {
                                    $relation->newPivot()->where($keyName, $id)->delete();
                                }
                            }
                            foreach ($values as $value) {
                                // if it's an existing pivot, update it
                                $attributes = $this->preparePivotAttributesForSave($value, $relation, $item->getKey(), $keyName);
                                if (isset($value[$keyName])) {
                                    $relation->newPivot()->where($keyName, $value[$keyName])->update($attributes);
                                } else {
                                    $relation->newPivot()->create($attributes);
                                }
                            }
                            break;
                        }

                        $relationToManyValues = [];

                        foreach ($values as $value) {
                            if (isset($value[$relationMethod])) {
                                $relationToManyValues[$value[$relationMethod]] = Arr::except($value, $relationMethod);
                            }
                        }

                        $item->{$relationMethod}()->sync($relationToManyValues);
                        unset($relationToManyValues);
                        break;
                    }

                    // if there is no relation data, and the values array is single dimensional we have
                    // an array of keys with no additional pivot data. sync those.
                    if (empty($relationToManyValues)) {
                        $relationToManyValues = array_values($values);
                    }
                    $item->{$relationMethod}()->sync($relationToManyValues);
                    unset($relationToManyValues);
                    break;
            }
        }
    }
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
# PHP VERSION:
8.3.9

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, ast, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache, xdebug

### LARAVEL VERSION:
11.20.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.25
backpack/devtools: 3.1.5
backpack/generators: v4.0.5
backpack/language-switcher: 2.0.0
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.12
backpack/theme-tabler: 1.2.11
backpack/translation-manager: 1.0.3
```

**Comment by manfield** [comment]
I think I found the issue.
Create Trait is ok. The problem is the createdRelationForItem($item, $formattedRelations) is called  with

$item = App\Models\Article
$formattedRelations = [
  'topic_pivot' => [
    ...
    $relationType = 'BelongsTo'
    ...
   ]
]

Instead topic_pivot method (in Article) is a MorphOne relation type.

![image](https://github.com/user-attachments/assets/7bb8d817-c2b7-4675-b16b-9400355bd466)

If I manually set the correct value in the debugger everything works correctly.

**Comment by tabacitu** [comment]
Hi @manfield ,

Ugh... this will be a b*$tch to debug, since it's working in our example but not in your code 🤦‍♂️ But let's try! 💪 

Sounds like you've narrowed it down to being the relation type that Backpack is detecting... vs what your actual relationship type. 

1) This usually happens because of naming... If you don't follow the EXACT Laravel naming conventions, or have models with two words (and underscore), I highly recommended you define EVERYTHING in that relationship. I see you've called this `topic_pivot` instead of the conventional `article_topic`. Can you try specifying all parameters here and here:

```php
// Article model
    public function topic_pivot()
    {
        return $this->morphOne(TopicPivot::class, 'topic_pivotable');
    }

// TopicPivot model
    public function topic_pivotable()
    {
        return $this->morphTo();
    }
```

2) If you are 100% sure your relationship is well-defined... and you can use it just fine from the front-end/custom-code/tinker... then afaik that can also be overridden. Have you tried doing this?
```php
        $this->crud->addField([
                'label'          => "Topic",
                'name'           => 'topic_pivot.topic',
                'relation_type'  => 'MorphOne',
        ]);
```

Cheers!

**Comment by manfield** [comment]
Hi, thank you for your answer.

Relations works. I tried via Tinker:

```
> Article::where('id',220)->get()->first()->topic_pivot->topic
= App\Models\Topic {#7177
    id: 1,
    label: "{"it":"Allevamento","en":"Farm"}",
    slug: "{"it":"allevamento","en":"farm"}",
    parent_id: 2,
    depth: 2,
    lft: 3,
    rgt: 4,
    created_at: "2024-08-12 18:24:53",
    updated_at: "2024-08-12 18:25:11",
  }
```

Relations, though they don't follow the exact naming, they're well described in the definition and Laravel detect them.
I also tried to specify `MorphOne` as `relation_type` in `CRUD::field`, but the topic field then is rendered as a simple input text.

**Comment by manfield** [comment]
Also saving works properly on Tinker:

```
> Article::find(219)->topic_pivot()->create(['topic_id' => 3])
= App\Models\TopicPivot {#7345
    topic_id: 3,
    topic_pivotable_id: 219,
    topic_pivotable_type: "App\Models\Article",
    updated_at: "2024-08-27 09:22:37",
    created_at: "2024-08-27 09:22:37",
    id: 4,
  }
```

**Comment by karandatwani92** [comment]
Hey @manfield

Can you share both your Models & CRUD's code? So I can try to find the issue and fix it.

**Comment by manfield** [comment]
Sure, I invited you to the repo

**Comment by pxpm** [comment]
Hey @manfield thanks for providing the code we could look out to try to reproduce the issue. 

The good thing about Backpack is that you can "take control" of the stuff without relying on Backpack when it fails somehow. For example, you could have manually defined your field without relying on Backpack guessing the relation_type etc and it would work:
```php
[
    'label'     => 'Topic',
    'name'      => 'topic.topic_id',
    'type'      => 'select2',
    'options'    => fn() => \App\Models\Topic::select('label', 'id')->get(),
    'attribute' => 'label',
    'tab'       => 'Main',
],
```

But indeed, as you noticed we have a similar relation in demo, but similar is not exactly the same. And your use case was not covered by our code. 
You can reproduce your issue in our demo if you remove the `sentiment.text` field from our demo, you will face the same issue, and `sentiment.user` wouldn't be saved into the database. 

I've tagged a new version of Backpack/CRUD 6.7.31 with a fix for it, that should also fix your scenario so you can keep your field "guessing abilities" and it should work.
```
[
    'name' => 'topic_pivot.topic',
]
```

Let me know if you are still experiencing issues after the update. 👍

**Comment by manfield** [comment]
It works like a charm! 
thanks a lot

**Comment by karandatwani92** [comment]
If you like Backpack so far, please give it a star on the [Github repo](https://github.com/Laravel-Backpack/CRUD). Thanks
