### ISSUE TITLE
[Bug] Multiple Upload does not select images after deleting all previous selected

### ISSUE THREAD

**Issue by manfield** [Laravel-Backpack/CRUD#5623]
# Bug report

### What I did

When deleting all previous uploaded files, through multiple uploader new files won't be added

https://github.com/user-attachments/assets/6135e07b-a6e7-4e0e-b11e-bd6c5d99ac08

### What I expected to happen

Files should be added even after complete deletion of the list

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
8.3.9

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, ast, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache, xdebug

### LARAVEL VERSION:
11.20.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.25
backpack/devtools: 3.1.5
backpack/generators: v4.0.5
backpack/language-switcher: 2.0.0
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.12
backpack/theme-tabler: 1.2.11
backpack/translation-manager: 1.0.3

**Comment by manfield** [comment]
Just to know: I bought the pro package and devtools because I'm on a project that needs the things I notified.
Do you have a scheduled release for the issues I opened?

**Comment by pxpm** [comment]
Thanks @manfield for the report 🙏 

I've just merged the fix and will tag a new version later today after I merge some other stuff 👍 

Let us know if you experience issues after the update!

Cheers
