### ISSUE TITLE
How can I download all dependency?

### ISSUE THREAD

**Issue by dvjunior** [Laravel-Backpack/CRUD#563]
I realized that if the project / application is running as an intranet, without internet access, the load is very slow due to external libs requests (css, fonts, js, etc). How to solve?

I use here, how do I customize the file upload, would like to be able to save the files to the bank and even convert some at the time of upload, is there any example for this?

**Comment by tabacitu** [comment]
Hi @dvjunior ,

I'm afraid your only option is to replace the CSS/JS requirements yourself, in the blade files - from CDNs to your local files. Check out ```layout.blade.php``` and all field types.

For uploading use the [upload or upload_multiple fields](https://laravel-backpack.readme.io/docs/crud-fields#section-upload).

Cheers!
