### ISSUE TITLE
[Feature Request] select2_json_from_api - Allow callback for attribute

### ISSUE THREAD

**Issue by rroblik** [Laravel-Backpack/CRUD#5636]
Hi,

I'm using the new `select2_json_from_api` field and it's working great !

It should be cool 🆒 to allow a callable callback in the `attribute` option, for example to concatenate 2 attributes of the json data in the drop down list , something like that : 

```php
'attribute' => function ($item) {
  return $item['name'] . ' (' . $item['id'] . ')';
}
```

Thanks

**Comment by karandatwani92** [comment]
Hey @rroblik 

Good idea, but I doubt the possibility. 
**How can one write custom logic for the client side(JS) from the server side(PHP)?**

--

So, for such cases:
I prefer to create a new [custom field](https://backpackforlaravel.com/docs/6.x/crud-fields#creating-a-custom-field-type-1) from the existing `select2_json_from_api`, customize and use it.

```
php artisan backpack:field new_field_name --from= select2_json_from_api
```

And... To run custom logic on the server side,  [events](https://backpackforlaravel.com/docs/6.x/crud-fields#storing-only-one-the-id-in-the-database) such as **retrieving** and **saving**  are already available.
