### ISSUE TITLE
[Bug] Repeatable js error no input

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/CRUD#5643]
# Bug report
Repeatable can crahs js if some subfield is not and input

### What I did
I need to show a alert to the user with instructions to take into account when filling out the form. Is a dynamic form and with CrudField JS Library i show or hide sections.

Only with adding the custom_html inside the subfields the js crash and some fields not work properly. One tinymce otuside of the repatable was not initializing.
![image](https://github.com/user-attachments/assets/cf18c1ca-037c-42c0-8592-eb713672c89d)
```php
 [
     'name'  => 'alert_files',
     'type'  => 'custom_html',
     'value' => '<div class="alert alert-primary" role="alert">This is a primary alert—check it out!</div>',
     'wrapper'   => [
            'class' => 'col-md-12'
      ]
]
```

![image](https://github.com/user-attachments/assets/3b70ae18-e637-4af4-a72d-fc3da53270c6)

### What I expected to happen

All fields to load

### What happened

Other fields were not initialized correctly.

### What I've already tried to fix it

Yes, in the file `vendor\backpack\pro\resources\views\fields\repeatable.blade.php` i add a conditional operator `subfield.input?.` if the input is no present.
```js
 let callbacksApplied = JSON.parse(subfield.input?.dataset.callbacks ?? '[]');

....

 subfield.input?.dataset.callbacks = JSON.stringify(callbacksApplied);
```

For now i override the repeatable blade.

### Is it a bug in the latest version of Backpack?

I'm not sure but the version I have is:
backpack/crud: 6.7.32
backpack/pro: 2.2.8

**Comment by pxpm** [comment]
Hey @adriallongarriu you will be happy to know that we have that fixed. Please update your `backpack/pro` and you should be able to remove your overrrides ;)

I will be closing this, but please re-open if I am wrong 🙏 

Cheers
