### ISSUE TITLE
[Bug] Advanced use case issue for column type text

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/CRUD#5645]
# Bug report

For columns type `text` we can use 1-to-1 relation.
```
[
    'name'  => 'parent.title',
    'label' => 'Title',
    'type'  => 'text'
],
```
In my case I have a user model with the `email` field. For the email field, I have a mutator
```
    protected function email(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => mb_convert_case($value, MB_CASE_LOWER, 'UTF-8'),
        );
    }
```

### What I expected to happen

I would expect to get my email value when I show the column 

### What happened

Instead, I get an error `Call to undefined method ...Models\User::email()`

### What I've already tried to fix it

The issue is here
```
public function getOnlyRelationEntity($field)
    {
        $entity = isset($field['baseEntity']) ? $field['baseEntity'].'.'.$field['entity'] : $field['entity'];
        $model = $this->getRelationModel($entity, -1);
        $lastSegmentAfterDot = Str::of($field['entity'])->afterLast('.');

        if (! method_exists($model, $lastSegmentAfterDot)) {
            return (string) Str::of($field['entity'])->beforeLast('.');
        }

        return $field['entity'];
    }
```
Particularly in tuis, please
`if (! method_exists($model, $lastSegmentAfterDot)) {`

I would say that you need to use reflection to define is this is the Attribute method or no. 
See: https://laravel.com/docs/11.x/eloquent-mutators#defining-a-mutator

### PHP VERSION:
8.3.10

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, amqp, apcu, bcmath, Phar, calendar, exif, gd, gettext, intl, mysqli, pcntl, pdo_mysql, redis, shmop, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, xsl, zip, Zend OPcache, xdebug

### LARAVEL VERSION:
11.21.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.33
backpack/generators: v4.0.5
backpack/menucrud: v4.0.1
backpack/pagemanager: 3.3.0
backpack/permissionmanager: 7.2.1
backpack/settings: 3.1.1
backpack/theme-coreuiv4: 1.1.2

**Comment by pxpm** [comment]
Hello @mialex 

I don't get where `parent.title` relates to `email` 🤷 Care to provide some more details ? 

Thanks

**Comment by karandatwani92** [comment]
Hey @pxpm

He came up with`parent.title` as the same example we gave in our [docs](https://backpackforlaravel.com/docs/6.x/crud-columns#text-1).

Anyway, I was able to reproduce the [BUG](https://flareapp.io/share/47qyBbz7). Here's how it goes:
- Add a column `CRUD::addColumn(['name' => 'owner.name']);` in our Demo's InvoiceCRUD.
- Above works fine until I add the following accessor to the `Owner` model.
```php
protected function name(): Attribute
 {
     return Attribute::make(
         get: fn(string $value) => ucfirst($value),
         set: fn(string $value) => strtolower($value),
     );
}
```

**Comment by mialex** [comment]
Yes, sorry, I copied wrong original column
