### ISSUE TITLE
[Concern] Advanced use case for fields as for columns

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/CRUD#5649]
### What I did

For columns, it's possible to define the column name as `'name'  => 'relation.title',` and show the title of the relation. For the field it works, after debugging the code, but in another way and only in a specific case.

### What I expected to happen

When I define in the field `'name'  => 'relation.title',` I would like to show the title of the relation.

### What happened

Let review the example from Laravel https://laravel.com/docs/11.x/eloquent-relationships#one-to-one with `User` and `Phone`. I have a page with my Phone details and on this page, I want to show the name of the User to whom this phone belongs to.
In this case, I need to define the field in the next way.
```php
[
    'name'  => 'anything... value does not matter. It just can not be empty,
    'label' => 'Name',
    'type' => 'text',
    'entity' => 'user.name',
]
```

And it will not work if we make the user related in the `Phone` model as `BelonsTo`, as it should be.
```php
public function user(): BelongsTo
{
    return $this->belongsTo(User::class, 'user_id', 'id');
}
```
It will not work because of the logic in `\Backpack\CRUD\app\Library\CrudPanel\Traits\Update::getModelAttributeValueFromRelationship`
```php
...
case 'BelongsTo':
    if ($relatedModel->{$relationMethod}) {
        return $relatedModel->{$relationMethod}->getKey();
    }
...
```

If we change it to `HasOne`, then it works, as HasOne has another behavior under the
```php
public function user(): HasOne
{
    return $this->hasOne(User::class, 'id', 'user_id');
}
```

### Questions

1. Why does `BelongsTo` work differently and return just a key `return $relatedModel->{$relationMethod}->getKey();`?
2. What is the sense to keep `'name' => 'bla bla'` if we define it in as `'entity' => 'user.name',`?
3. Could it be consistent with the column logic? 

I didn't investigate dipper, but I assume that it might be related to the `select` like fields... Not sure...

### PHP VERSION:
8.3.10

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, amqp, apcu, bcmath, Phar, calendar, exif, gd, gettext, intl, mysqli, pcntl, pdo_mysql, redis, shmop, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, xsl, zip, Zend OPcache, xdebug

### LARAVEL VERSION:
11.21.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.34
backpack/generators: v4.0.5
backpack/menucrud: v4.0.1
backpack/pagemanager: 3.3.0
backpack/permissionmanager: 7.2.1
backpack/settings: 3.1.1
backpack/theme-coreuiv4: 1.1.2

**Comment by jcastroa87** [comment]
Hi @mialex 

I want to understand what you are asking for. From what I understand, it seems that you ignore the field name and set the entity, but the guess functions work the other way around: you define the field name and we guess the entity, etc.
The only fields that can use name.attribute or name.relation are when HasOne or MorphOne is defined. The other relationships must be defined using subfields.

Please let me know in detail what you hope to achieve, as I indicated above, the guess functions work from the field name.

Cheers.
