### ISSUE TITLE
[Bug] Phone field not working in Inline Create

### ISSUE THREAD

**Issue by GregaUNK** [Laravel-Backpack/CRUD#5654]
# Bug report

### What I did

Added Phone field into setupCreateOperation and then use Inline create.
  ```
CRUD::field([
            'label' => 'Phone number',
            'name' => 'contact_phone',
            'type' => 'phone',
            'config' => [
                'onlyCountries' => ['si', 'hr', 'in', 'lv', 'pt', 'ro', 'rs', 'sr'],
                'initialCountry' => 'si' // this needs to be in the allowed country list, either in `onlyCountries` or NOT in `excludeCountries`

            ],
            'validationRules' => 'required',
            'wrapper' => [
                'class'       => 'form-group col-lg-12',
            ]
        ]);
```
### What I expected to happen

Field to work :)

### What happened

At first input field is streched thru whole screen. When you click it it shrinks, but even if you enter the value, validation shows error that contact_phone is empty.

### Is it a bug in the latest version of Backpack?

Yes.

### PHP VERSION:
8.3.7

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, FFI, fileinfo, filter, ftp, gd, gettext, gmp, json, iconv, intl, SPL, ldap, mbstring, session, standard, odbc, pcntl, exif, mysqlnd, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, random, readline, Reflection, mysqli, shmop, SimpleXML, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, Zend OPcache

### LARAVEL VERSION:
10.48.20.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.34
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.1.7
backpack/revise-operation: 2.0.0
backpack/theme-coreuiv2: 1.2.5
backpack/theme-coreuiv4: 1.1.2
backpack/theme-tabler: 1.2.11

**Comment by jcastroa87** [comment]
Hello @GregaUNK 

Can you please share a video, i try on my side and is working normal.

![Screenshot 2024-09-05 at 4 53 26 PM](https://github.com/user-attachments/assets/f70fa794-e4af-4e55-b0ec-27ca9adb2f09)

And the data is save with no errors.

![Screenshot 2024-09-05 at 4 59 03 PM](https://github.com/user-attachments/assets/fa353b3c-989e-4e6f-a496-cc52d8bcd866)

![Screenshot 2024-09-05 at 4 59 20 PM](https://github.com/user-attachments/assets/a1c9fbfd-f799-4e94-bb1c-f2576b1fe90e)

Please give me more information to catch if there is an issue.

Cheers.

**Comment by GregaUNK** [comment]
Hi,

I saw you are using Tabler template, but I think its not the case. I tried to switch it and the same happens. I am using CoreUI v4.

![Screenshot 2024-09-06 at 08 17 21](https://github.com/user-attachments/assets/40ade85a-3873-4bab-a3ca-4684e1fa2f15)

![Screenshot 2024-09-06 at 08 26 09](https://github.com/user-attachments/assets/caed9930-90b0-415c-91d4-9ece144e41d8)

It looks like its not posting hidden field of contact_phone if type is phone. If I change type to text it works.

This is my CreateOperation in PartnerContactCrudController.php

 ```
 protected function setupCreateOperation()
    {
        // for inline create
        if (request('main_form_fields') != null) {

            foreach (request('main_form_fields') as $field) {

                if ($field['name'] == 'partner_id') {
                    $partnerId = $field['value'];
                }
            }
        }

        CRUD::field([   // 1-n relationship
            'label'       => "Partner", // Table column heading
            'type'        => "select2_from_ajax",
            'name'        => 'partner_id', // the column that contains the ID of that connected entity
            'entity'      => 'partner', // the method that defines the relationship in your Model
            'attribute'   => "partner_name", // foreign key attribute that is shown to user
            'data_source' => backpack_url('partner-contact/fetch/partner'), // url to controller search function (with /{id} should return model)
            'method' => 'POST',
            'validationRules' => 'required',
            'value' => $partnerId ?? null
        ]);
        CRUD::field(['label' => 'Ime kontakta', 'name' => 'contact_name', 'type' => 'text', 'validationRules' => 'required']);
        CRUD::field([
            'label' => 'Telefonska številka',
            'name' => 'contact_phone',
            'type' => 'phone',
            'config' => [
                'onlyCountries' => ['si', 'hr', 'in', 'lv', 'pt', 'ro', 'rs', 'sr'],
                'initialCountry' => 'si' // this needs to be in the allowed country list, either in `onlyCountries` or NOT in `excludeCountries`

            ],
            'validationRules' => 'required',
            'wrapper' => [
                'class'       => 'form-group col-lg-12',
            ]
        ]);

    }
```

And this is my field in JobOrderCrudController.php
```

 CRUD::field([   // 1-n relationship
            'label'       => "Contact", // Table column heading
            'type'        => "relationship",
            'name'        => 'partner_contact_id', // the column that contains the ID of that connected entity
            'entity'      => 'partnerContact', // the method that defines the relationship in your Model
            'attribute'   => "full_contact_name", // foreign key attribute that is shown to user
            'data_source' => backpack_url('job-order/fetch/partner-contact'), // url to controller search function (with /{id} should return model)
            'method' => 'POST',
            'ajax' => true,
            'inline_create' => [
                'entity' => 'partner-contact',
                'include_main_form_fields' => ['partner_id'], 
            ],
            'validationRules' => 'required',
            'tab' => 'Order',
            'dependencies' => ['partner_id'],
            'wrapper' => [
                'class'       => 'form-group d-none col-lg-4',
            ],
            'minimum_input_length' => 0
        ]);
```

**Comment by GregaUNK** [comment]
Any help would be appreciated.

**Comment by jcastroa87** [comment]
Hello @GregaUNK 

I can not reproduce this issue, but we receive other issue about phone field: https://github.com/Laravel-Backpack/community-forum/issues/1148 so I update the library, this is in a PR, when this PR will be merged I will back to you so we can check if updated library fix this too.

Cheers.

**Comment by GregaUNK** [comment]
Hi,

ok, thanks.

BTW: this issue is only in InlineCreate. When Iam using PartnerContact CRUD directly, it works as expected.

**Comment by jcastroa87** [comment]
Is merged.

Could you try running:
```
composer update
php artisan basset:clear
php artisan basset:cache
```

Let me know if the library is update after this and you still have the issue.

Cheers.

**Comment by GregaUNK** [comment]
Hi @jcastroa87 ,

I don’t see any difference.

All the mentioned errors are still present.

Wherever the phone field is loaded, I get the following error:
“Unhandled Promise Rejection: Error: No country data for ‘us’”.

Additionally, during inline creation, it says that contact_phone is null.

**Comment by pxpm** [comment]
Hey @GregaUNK thanks for the report. I could reproduce the issue you mentioned and released a new backpack/pro version with the fix. Please allow some moments for our private repository to pick the changes and then a `composer update` should get you the fixed version. 

Please let us know if you still experiencing issues 👍 

Cheers
