### ISSUE TITLE
[Bug] Field type upload convert .gltf files to .txt

### ISSUE THREAD

**Issue by MohammedHijazi** [Laravel-Backpack/CRUD#5682]
# Bug report

I'm using backpack V6 and I have a filed type upload as follows:
![image](https://github.com/user-attachments/assets/7fe4ff54-6d01-44d2-a206-cf201dc5fba3)

        
For this, I want files of type .gltf to be stored

So I expect the file being stored as it is with the same file type

but the issue is I find the file being stored as .txt, after hours of debugging I removed `'withFiles' => true,` attribute that let's backpack handle file uploads automatically, and I used the old fashioned way of storing the file using the mutator as menioned in the docs like this:

![image](https://github.com/user-attachments/assets/8e0aff26-f342-4a5b-a35c-c70bbcca5082)
        
and in the model:
![image](https://github.com/user-attachments/assets/0c75aee3-87fc-46bc-9d28-30ddc09b1d4c)

and this worked out just fine

I think there is something in `\Backpack\CRUD\app\Library\Uploaders\SingleFile::class` needs to be fixed to prevent that issue:

**Comment by jcastroa87** [comment]
Hello @MohammedHijazi 

This dont look like something Backpack upload is doing.

Here is Laravel who declare "The file's extension will be determined by examining the file's MIME type".

You can check something similar to this [here](https://stackoverflow.com/questions/71011861/laravel-saving-certain-files-as-a-bin-file) so you can try to customize the process in thats cases.

Cheers.
