### ISSUE TITLE
[Bug] Fluent Syntax Issue

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/CRUD#5684]
# Bug report

### What I did
```php
CRUD::column('meetings_done_count') // This creates two columns
    ->name('meetings_done')
    ->label('Meetings Done1');
    
CRUD::column([ // This works as expected
    'key' => 'meetings_done_count',
    'name' => 'meetings_done',
    'label' => 'Meetings Done'
]);
```

**Comment by pxpm** [comment]
Not an issue. 
`CRUD::column($name)` it's the definition. 

If you want to replicate the same column you do: `CRUD::column('meetings_done')->key('meetings_done_count')`. 

Cheers

**Comment by karandatwani92** [comment]
Hey @pxpm

I don't want to replicate it. The syntax seems:
```
CRUD::column('meetings_done_count') // for key
    ->name('meetings_done') // for name
    ->label('Meetings Done1'); // label
```
But it creates two columns. Let me know what I'm missing here.

**Comment by pxpm** [comment]
Hey @karandatwani92 , the syntax is: `CRUD::column($name)`, not `CRUD::column($key)`. https://backpackforlaravel.com/docs/6.x/crud-fluent-syntax#general-1
