### ISSUE TITLE
[Bug] Errors for relationship subfields are not detected to set the active tab correctly

### ISSUE THREAD

**Issue by krjohnston** [Laravel-Backpack/CRUD#5686]
# Bug report

### What I did

Added tabbed panels for relationship with subfields in setupUpdateOperation

    CRUD::field('inspectorAllocations')
        ->type('relationship')
        ->subfields([
            [
                'name' => 'inspector'
                'ajax' => true,
                'attribute' => 'reverse_full_name',
            ],
            [
                'name' => 'valid_date',
                'type' => 'date',
        ])
        ->tab('Inspector Allocations');

### What I expected to happen

When the first error is on a relationship subfield, I expect that tab to be the active tab

### What happened

The subfield was not recognised because the crud field in the array returned from `$crud->getCurrentFields()` is `inspectorAllocations` but the `$fieldName` under test is `inspectorAllocations.0.name`.

### What I've already tried to fix it

I published `show_tabbed_fields.blade.php` and added a `preg_split` to obtain the parent name of any subfields before checking the array of available `$fieldName`s
This works for my case and does not have any adverse effect on standard format fieldNames

    @php
        $horizontalTabs = $crud->getTabsType()=='horizontal' ? true : false;
        $tabWithError = (function() use ($crud) {
            if(! session()->get('errors')) {
                return false;
            }
            foreach(session()->get('errors')->getBags() as $bag => $errorMessages) {
                foreach($errorMessages->getMessages() as $fieldName => $messages) {

                    # Transform subfield $fieldNames into the correct CRUD fieldName format 
                    # preg_split by the array separator .digits. and take only the first element
                    $fieldName = preg_split('/\.\d+\./',$fieldName)[0];

                    if(array_key_exists($fieldName, $crud->getCurrentFields()) && array_key_exists('tab', $crud->getCurrentFields()[$fieldName])) {
                        return $crud->getCurrentFields()[$fieldName]['tab'];
                    }
                }
            }
            return false;
        })();
    @endphp

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud```  I am on 6.7.39 and the bug is still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
8.2.18

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, swoole, Zend OPcache, xdebug

### LARAVEL VERSION:
10.48.3.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.0
backpack/crud: 6.7.39
backpack/devtools: 3.1.0
backpack/editable-columns: 3.0.8
backpack/generators: v4.0.4
backpack/permissionmanager: 7.2.1
backpack/pro: 2.1.11
backpack/theme-tabler: 1.2.8

**Comment by karandatwani92** [comment]
Hey @krjohnston 

Yes, It does not take to the error field tab, but it highlights the tab where the error is with the details on top:

![Screenshot 2024-10-13 at 8 35 28 PM](https://github.com/user-attachments/assets/4024d9dc-2b96-46d3-a17f-335ae4d7d372)

**Comment by krjohnston** [comment]
I agree the error is shown, but this is inconsistent behaviour compared to
all other fields. My client insisted that I rectify this which I did,
however I believe this is a bug that ought to be addressed in the core.

**Comment by pxpm** [comment]
Hey @krjohnston totally agree. 

It's a simple change, are you willing to submit the PR for it, so you show up as a contributor since you already did all the work ? 
If you don't have time/desire to do it, just let me know and I create the PR myself. 👍 

Thanks for the heads up, and for providing the solution 🙏

**Comment by krjohnston** [comment]
I don’t mind submitting the pull request.
Am I able to branch your repo or do I need to fork?

Thanks
Kev

From: Pedro Martins ***@***.***>
Date: Monday, 14 October 2024 at 10:11
To: Laravel-Backpack/CRUD ***@***.***>
Cc: krjohnston ***@***.***>, Mention ***@***.***>
Subject: Re: [Laravel-Backpack/CRUD] [Bug] Errors for relationship subfields are not detected to set the active tab correctly (Issue #5686)

Hey @krjohnston<https://github.com/krjohnston> totally agree.

It's a simple change, are you willing to submit the PR for it, so you show up as a contributor since you already did all the work ?
If you don't have time/desire to do it, just let me know and I create the PR myself. 👍

Thanks for the heads up, and for providing the solution 🙏

**Comment by pxpm** [comment]
Hey @krjohnston thanks 🙏  
You need to create a fork and pull the changes. 👍

**Comment by karandatwani92** [comment]
Fixed here https://github.com/Laravel-Backpack/CRUD/pull/5690

Thanks @krjohnston
