### ISSUE TITLE
[Bug] Undefined array key "relation_type"

### ISSUE THREAD

**Issue by cod3rshotout** [Laravel-Backpack/CRUD#5692]
# Bug report

### What I did

I'm trying to create a repeater that has as its only field a select that displays all the "Attachment" entities. Each row of the repeater must allow the inline creation of an Attachment.
Within ArticleCrudController I've added:

    CRUD::field([
        'name' => 'attachments',
        'label' => "Attachments",
        'type' => 'repeatable',
        'fields' => [
            [
                'name' => 'attachment_id',
                'type' => 'relationship',
                'label' => 'Select attachment',
                'entity' => 'attachments',
                'attribute' => 'title',
                'model' => 'App\Models\Attachment',
                'inline_create' => [
                    'entity' => 'attachment',
                    'modal_class' => 'modal-lg',
                    'force_select' => true
                ],
            ],
        ],
        'new_item_label' => "Add new attachment",
        'init_rows' => 1,
        'min_rows' => 1,
        'tab' => "Attachments"
    ]);

Then I wrote the following relation with Article model:

    public function attachments()
    {
        return $this->belongsToMany(Attachment::class, 'article_attachment');
    }

and this is from Attachment model:

    public function articles()
    {
        return $this->belongsToMany(Article::class, 'article_attachment');
    }

### What I expected to happen

Backpack should display a repeatable with a select field and a inline create button.

### What happened

I get: Undefined array key "relation_type".

### What I've already tried to fix it

If I switch to "select2" instead of "relationship" all works well but I cannot use the inline create operation then.

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? Yes.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
8.2.4

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, readline, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, bcmath, exif, gd, gmp, imagick, intl, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, soap, sodium, zip

### LARAVEL VERSION:
11.28.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.41
backpack/filemanager: 3.0.8
backpack/generators: v4.0.7
backpack/logmanager: v5.0.2
backpack/medialibrary-uploaders: 1.2.1
backpack/newscrud: 5.1.0
backpack/pagemanager: 3.3.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.21
backpack/settings: 3.1.1
backpack/theme-tabler: 1.2.13

**Comment by pxpm** [comment]
Hey @cod3rshotout thanks for the question.

I think you are approaching this from the wrong angle. If it's a relationship (`attachments`) you shouldn't be using `repeatable`. 

```php
CRUD::field([
    'name' => 'attachments',
    'label' => "Attachments",
    'type' => 'relationship',
    'subfields' => [],
    'pivotSelect' => [
        'inline_create' =>[
            'entity' => 'attachment',
            'modal_class' => 'modal-lg',
            'force_select' => true
        ],
    ],
    'new_item_label' => "Add new attachment",
    'init_rows' => 1,
    'min_rows' => 1,
    'tab' => "Attachments"
]);
```
It should work. Let us know 👍

**Comment by cod3rshotout** [comment]
> Hey @cod3rshotout thanks for the question.
> 
> I think you are approaching this from the wrong angle. If it's a relationship (`attachments`) you shouldn't be using `repeatable`.
> 
> ```
> CRUD::field([
>     'name' => 'attachments',
>     'label' => "Attachments",
>     'type' => 'relationship',
>     'subfields' => [],
>     'pivotSelect' => [
>         'inline_create' =>[
>             'entity' => 'attachment',
>             'modal_class' => 'modal-lg',
>             'force_select' => true
>         ],
>     ],
>     'new_item_label' => "Add new attachment",
>     'init_rows' => 1,
>     'min_rows' => 1,
>     'tab' => "Attachments"
> ]);
> ```
> 
> It should work. Let us know 👍

Thank you! It's working now
