### ISSUE TITLE
[Bug] Call to undefined function views_path() WHEN STTING NEW CUSTOM THEME

### ISSUE THREAD

**Issue by azeddine-hf** [Laravel-Backpack/CRUD#5694]
in documentation :
The my-cool-theme/inc/theme_styles.blade.php file should hold all custom CSS that your theme needs. For example:

{{-- You can load files directly from CDNs, they will get cached and loaded from local --}}
@basset('https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css')

{{-- You can also load files from any place in your application directories --}}
@basset(views_path('my-cool-theme/assets/css/extra.css'))

{{-- You can also write inline CSS blocks --}}
@bassetBlock('my-cool-theme/custom-styling')
<style>
.something {
    border: 1px solid red;
}
</style>
@endBassetBlock
but in usage shows an error : Call to undefined function views_path()

**Comment by pxpm** [comment]
yeah, you right @azeddine-hf, thanks for the heads up 🙏 

please use `resource_path('assets/css/my-cool-theme/whatever.css')`. (need to put the `whatever.css` in `resources/assets/css/my-cool-theme/` directory. 

I will send a PR to fix the docs 👍

**Comment by azeddine-hf** [comment]
how can i set it on blade file : 
{{ resource_path('assets/css/my-cool-theme/whatever.css') }} LIKE THIS or inside <link ... />
??

**Comment by pxpm** [comment]
On blade you use `@basset()` directive 👍 Basset will output the correct import tag for it, either link, script etc. eg: https://github.com/Laravel-Backpack/CRUD/blob/ac35070c94c3db7ceb7680b5eb7307cac56eea74/src/resources/views/crud/reorder.blade.php#L233

**Comment by azeddine-hf** [comment]
@pxpm please theme_scripts.blade.php doesn't load why ?

**Comment by pxpm** [comment]
> @pxpm please theme_scripts.blade.php doesn't load why ?

No clue, where do you have the file ? How are you including it ? 

It's just a blade file, it should just load as any other blade file in the application 🤷

**Comment by azeddine-hf** [comment]
@pxpm the `theme_styles `it included automaticly but the `theme_scripts ` does not 
i have include it in `default.blade.php `file manually thank you @pxpm

**Comment by pxpm** [comment]
Yes, in the layout it's where we include them: https://github.com/Laravel-Backpack/theme-coreuiv2/blob/11ec0cbaecefd3272601a7fb0d32457533a09ce6/resources/views/layouts/top_left.blade.php#L50

**Comment by azeddine-hf** [comment]
@pxpm where data didn't load after set my custom them and i set fallback_theme core_ui2 

![image](https://github.com/user-attachments/assets/f52d8e48-e9eb-402c-9801-b88b8a4d4dd9)

styles of datatable also not loaded ??
i'm i missed something !
