### ISSUE TITLE
[Bug] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by cod3rshotout** [Laravel-Backpack/CRUD#5695]
When I create a new crud (this happen also in official backpack crud) I see an error in console:

    module?intranet=0:582  Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at document.onreadystatechange (module?intranet=0:582:20)

If I inspect the error is related to the alerts.blade.php file located in theme-tabler, in particular this line:

    Object.entries($alerts_from_php).forEach(function(type) {
        if (typeof $alerts_from_localstorage[type[0]] !== 'undefined') {
            type[1].forEach(function(msg) {
                $alerts_from_localstorage[type[0]].push(msg);
            });
        } else {
            $alerts_from_localstorage[type[0]] = type[1];
        }
    });

Weird thing is that I doesn't seems to find this error in the backpack demo, maybe there is a missing configuration or something that I can't see?

Thanks.

**Comment by jcastroa87** [comment]
Hello @cod3rshotout 

Could you provide more information, please?

Can you send screenshots of errors and share versions?

```
php artisan backpack:version
```

Thanks.

Cheers.

**Comment by cod3rshotout** [comment]
> alerts_from_php

The version is the latest, I fixed updating as:

    if ($alerts_from_php && typeof $alerts_from_php === 'object') {
        Object.entries($alerts_from_php).forEach(function(type) {
            if (typeof $alerts_from_localstorage[type[0]] !== 'undefined') {
                type[1].forEach(function(msg) {
                    $alerts_from_localstorage[type[0]].push(msg);
                });
            } else {
                $alerts_from_localstorage[type[0]] = type[1];
            }
        });
    }

but I don't know if this is a correct solution though.

**Comment by pxpm** [comment]
I've reproduced the error, will work on the fix 👍 

Thanks @cod3rshotout

**Comment by pxpm** [comment]
Thanks again @cod3rshotout 

I've released the fix in our 3 themes, you should be able to get the fix with a `composer update` 👍 

Cheers
