### ISSUE TITLE
can i use crud to upload image ?

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#57]
Hello
i need to make input file to upload image file and save file name to database table

i need to rename file name before save the file name in DB

any suggestions?

Thank you in advance

**Comment by c1t1zen** [comment]
Hey!
Thank you for help this is my code to do that

first step create new field type
====================
file_image.blade.php
in laravel_app_root/resources\views\vendor\backpack\crud\fields
`

  <div class="form-group">
    <label>{{ $field['label'] }}</label>
    <input
        type="file"
        class="form-control"

        @foreach ($field as $attribute => $value)
            @if (is_string($attribute) && is_string($value))
               @if($attribute != 'value' && $attribute != 'type')
                    {{ $attribute }}="{{ $value }}"
                @endif
            @endif
        @endforeach

        value="{{ old($field['name']) ? old($field['name']) : (isset($field['value'])?$field['value']:'') }}"
        >
    @if (isset($field['hint']))
        <p class="help-block">{!! $field['hint'] !!}</p>
    @endif
  </div>

second step:
=========
in ArticleCrudController in news system or whatever you use

        $this->crud->addField([    // Image
            'name' => 'image',
            'label' => 'Image',
            'type' => 'file_image'//,           
        ]);`
`
`
third step
========
install this package
[image lib](http://image.intervention.io/getting_started/installation)

four step
========
load lib image and function to the Article model

`
use Image;



// my own functions
	public function setImageAttribute($value) {
	   // use Intervention image or whatever you want to process that image

     	$image=$value;
        $input['imagename'] = time().'.'.$image->getClientOriginalExtension();
        $img = Image::make($image->getRealPath());

        $destinationPath = public_path('/uploads/news');
        $img->resize(750, 450, function ($constraint) {
		    $constraint->aspectRatio();
		})->save($destinationPath.'/'.$input['imagename']);

        $destinationPath = public_path('/uploads/news/thumb');

        $img->resize(100, 100, function ($constraint) {
		    $constraint->aspectRatio();
		})->save($destinationPath.'/'.$input['imagename']);

 		//  $image->move($destinationPath, $input['imagename']); // for no resize

	   $this->attributes['image'] =   strtolower($input['imagename']);	  
 
 
	}    
`


Thank you tabacitu
i was going to rebuild the article module from scratch if i couldnt use image file upload

**Comment by BIGITIMI** [comment]
i try to make image upload as you write, and it's failed at this line:
$input['imagename'] = time().'.'.$image->getClientOriginalExtension();

i guess its happened becuase the form has not have the enctype="multipart/form-data"
do you know how can i solve it?

**Comment by tabacitu** [comment]
@BIGITIMI , if that's the case, you can use a overwrite the ```create.blade.php``` and ```edit.blade.php``` files (where the form is instantiated) with your own files, by placing them in ```resources/views/vendor/backpack/crud```. Does this work for you?

**Comment by BIGITIMI** [comment]
@tabacitu Hi, i change the form to use  enctype="multipart/form-data" and it work good,
but i think the "file upload" field must build-in in the backpack, this is a basic field to work with

thanks for your reply.

**Comment by tabacitu** [comment]
@BIGITIMI completely agree with you. That's why this issue is still open. Cheers!

**Comment by tabacitu** [comment]
Hi guys,

I've just pushed the ```upload``` field type, in ```Backpack\CRUD v3.1.5```. Would love to have your feedback and tests. Here's [how it works](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#upload). And here's [the commit](https://github.com/Laravel-Backpack/CRUD/commit/57a311f227bed3ccd9a03d5601781ee25b8ac0dd): 

And here's my question to you: **should we also automatically delete the file from disk when the entry is deleted? How about if it has soft deletes?** This might cause confusion, because I'm pretty sure if somewhere in your app you use batch operations to delete, that won't trigger the "deleted" event on the model.

Thanks, cheers!

**Comment by OwenMelbz** [comment]
@tabacitu I've been having a play around with this feature and have come across 2 bugs

Firstly - When trying to remove files form the multi_uploader, it fails to do this (might be linked to the second bug)

Secondly - When it gives you the preview url - it doesnt take into account the disk path e.g my path was /uploads/folder_1/subfolder_1 - so the file uploaded there correctly, however it doesnt return the preview field with the disk location included.

I've created a video demonstrating

https://drive.google.com/file/d/0Bxqca2RsGkfTd2FiVE9FNzlQcGM/view

**Comment by tabacitu** [comment]
Hi @OwenMelbz , thank you for the video - it was perfect to debug the issue. 

Let's tackle the first issue first - not removing the files.

1) My first try would be to use attribute casting on the Model - if you cast "image" to "array" does that still happen? It's now also [in the docs, as Step 3](https://laravel-backpack.readme.io/docs/crud-fields#upload_multiple).

```php
    protected $casts = [
        'image' => 'array'
    ];
```

2) Also, I didn't quite understand the way you used the models. In ```TeamCrudController``` I see you're using the ```Team``` model, but then you put the mutator on the ```AdminModule``` model?

Cheers!

**Comment by OwenMelbz** [comment]
As it happens, I've refactored a lot of what I had, so will need to try out the casting again later to see what happens, although I'm pretty sure I did cast it.

Regards to the `AdminModule` - that was because all my models extend `AdminModule`, I just happened to have accidently recorded the video while not in the sub class, so in that instance it was because my `Team` model was extending it anyway so didn't overly matter, but will do it properly for when I look into casting it again.

**Comment by tabacitu** [comment]
Great. Tell me when you see if it is.

For the second issue, I've just pushed an update:
- if on your field you don't specify a "disk", the file URL will be generated using asset($your_db_entry);
- if you DO specify a disk, the file URL will be generated using the Storage facade;

This way, everyone can use it:
- if you store your uploads in the /public folder, you don't need to specify the disk;
- if you store your uploads is the /storage folder or in the cloud (S3, etc), you need to specify the disk;

Here's how that looks:
```php
$this->crud->addField([
            'type' => 'upload_multiple',
            'name' => 'photos',
            'label' => 'Photos',
            'upload' => true,
            'disk' => 'public' // <- this line is new
        ]);
```

This _should_ solve that one. Please confirm though :-)

Cheers!

**Comment by tabacitu** [comment]
I've just tried it again and it seems to work for most use cases. If there's still a bug for it, it's most likely something very particular. @OwenMelbz , if you're still having issues, we'll track it down and squash it :-)

I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you have follow-ups.

**Comment by aamirkhan37557** [comment]
i have install the laravel backpack but i don,t have crud folder in resource/view/vendor/backpack i have only two folder in backupmenager and base i want to display image and my other question is that

how can i resize image in laravel backback and how how i change its design kindly help 

reply me on aamirkhan3757@gmail.com iam waiting for your response

**Comment by tabacitu** [comment]
Hi @aamirkhan37557 ,

You can use any library you want to resize images. The cleanest way would be to [use a Mutator in your Model](https://laravel.com/docs/5.4/eloquent-mutators#defining-a-mutator). If you're uploading an image, you have probably already defined that. Just add your resize logic using a library like [Intervention Image](http://image.intervention.io/).

Hope it helps. Cheers!
