### ISSUE TITLE
thousand separator not working in a number field within Laravel Backpack

### ISSUE THREAD

**Issue by haniramadhan-kkp** [Laravel-Backpack/CRUD#5701]
# Bug report

Could you help me review my code to ensure that the thousand separator is correctly applied to the number input field in Backpack for Laravel

CRUD::field([
            'label' => 'Nilai Tagihan',
            'type'  => 'number',
            'name'  => 'nilai',
            'thousands_sep' => '.',
        ]);

Has anyone experienced issues with the thousand separator not working in a number field within Laravel Backpack?

**Comment by karandatwani92** [comment]
Hey @haniramadhan-kkp 

The `thousands_sep` is an attribute of a `number` [column](https://backpackforlaravel.com/docs/6.x/crud-columns#number-1) type, not a `number` [field](https://backpackforlaravel.com/docs/6.x/crud-fields#number-1).

Why? HTML [number](https://www.w3schools.com/tags/att_input_type_number.asp) input doesn't support it.
