### ISSUE TITLE
Repeater fields with any content ?

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#571]
Hello,

I like to add a repeater field. I'm trying to use table field, It works, but for text only. It's normal ?

I would like to use it to be able to give a title, an image to uploader and a link, with the corresponding fields type.

I'd like to do something like this

```
[ // Repeater field
    'name' => 'skills',
    'label' => 'Skills',
    'type' => 'table',
    'entity_singular' => 'skills', 
    'columns' => [
        'Your title' => 'text',
        'Your link' => 'link',
        'Your image' => 'image'
    ],
    'max' => 10
    'min' => 1 
],
```

thank you very much for your help

**Comment by tabacitu** [comment]
Hi @Jimmylet,

Unfortunately yes - the table field only supports text fields. The kind of field you want IS planned, but has no deadline right now.

I think the best course of action for you right now is to create a custom field type, starting from "table".

Cheers!
