### ISSUE TITLE
[Bug] Field Address Google with Javascript error

### ISSUE THREAD

**Issue by mrinaldidfs** [Laravel-Backpack/CRUD#5721]
# Bug report

By inserting the address_google field inside a crud all the other fields that use javascript (such as select2) stop working and in the console I find the following error:
```
Uncaught TypeError: google.maps.places is undefined
    bpFieldInitAddressGoogleElement http://domain.test/admin/organization/create:958
    initializeFieldsWithJavascript http://domain.test/admin/organization/create:1041
    jQuery 2
    initializeFieldsWithJavascript http://domain.test/admin/organization/create:1036
    <anonymous> http://domain.test/admin/organization/create:1097
    jQuery 13
```
The address Google Field work, but all other fields not

### What I did

I inserted the address_google type field into a crud
```
CRUD::addField([
            'name' => 'google_address',
            'type' => 'address_google',
            'label' => 'Address',
            'wrapper' => ['class' => 'form-group col-md-12'],
            'store_as_json' => true
]);
```

### What I expected to happen

to have the Google autocomplete suggestion in the field as soon as it is inserted

### What happened

Google's suggestion works correctly but, following javascript errors, all the other fields are not displayed correctly

### What I've already tried to fix it

I customized the field by placing it in the `vendor/backpack/crud/fields` folder
I added below the line with
`if(typeof google === "undefined") { return; }` 
the following line
`if(typeof google.maps.places === "undefined") { return; }`

I also had to remove from the basset the part of the javascript script that contains the init of the field by removing it from the baset block
@bassetBlock('backpack/pro/fields/address-google-field.js')

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
8.2.19

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, xmlreader, xmlwriter, openssl, curl, ftp, fileinfo, gd, intl, imap, mbstring, exif, mysqli, Phar, pdo_mysql, sodium, xsl, zip, redis, imagick, mongodb

### LARAVEL VERSION:
11.33.2.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.42
backpack/editable-columns: 3.0.10
backpack/generators: v4.0.7
backpack/pro: 2.2.25
backpack/theme-tabler: 1.2.15

**Comment by pxpm** [comment]
Hello @mrinaldidfs thanks for the question. 

Make sure your API key has access to the following google API's: 
```md
Maps Javascript API
Places API
Geocoding API
```

I've just tested it, without any changes and everything is working as expected as long as my API has access to those 3 services. 
![image](https://github.com/user-attachments/assets/7c91766a-2bd0-44f5-a0d5-4e5298ae1034)

I've just added it to the docs to make it more clear: https://backpackforlaravel.com/docs/6.x/crud-fields#address_google-pro

I am going to close this, please feel free to ping @karandatwani92 if you still experiencing issues and he can re-open this and help you out. 👍

**Comment by karandatwani92** [comment]
![Screenshot 2024-11-22 at 6 32 24 PM](https://github.com/user-attachments/assets/427f2218-28a4-466f-9fcd-a9e5452f52cb)

**Comment by nrodriguezm** [comment]
Updated versions but same problem:

php artisan backpack:version
### PHP VERSION:
8.2.15

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, grpc, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, Zend OPcache

### LARAVEL VERSION:
10.48.29.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.8
backpack/crud: 6.8.1
backpack/generators: v4.0.7
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.34
backpack/settings: 3.1.2
backpack/theme-coreuiv4: 1.1.6

**Comment by Kubitini** [comment]
Please reopen this, as this is still an issue in the newest version.

**Comment by AdamovicBoban** [comment]
### PHP VERSION:
8.3.14

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, xmlreader, xmlwriter, ldap, curl, com_dotnet, fileinfo, gd, gettext, gmp, intl, imap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, xsl, zip, Zend OPcache, xdebug

### LARAVEL VERSION:
12.17.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.7
backpack/backupmanager: v5.0.6
backpack/basset: 1.3.9
backpack/crud: 6.8.4
backpack/devtools: 3.1.7
backpack/editable-columns: 3.0.11
backpack/generators: v4.0.7
backpack/logmanager: 5.0.3
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.35
backpack/settings: 3.1.2
backpack/theme-coreuiv4: 1.1.6


Hi, I just want to confirm that I'm experiencing the same issue with the address_google field.

The following error appears in the console on page load:

```
Uncaught TypeError: google.maps.places is undefined
    at ...
    var $autocomplete = new google.maps.places.Autocomplete(...)
```

Although the address_google field does eventually work after loading, this error blocks all other JavaScript functionality, such as select2_from_ajax fields with dependencies. This is causing serious usability issues across the form.

Please prioritize this fix or provide a recommended workaround using the new PlaceAutocompleteElement as suggested by Google.

Thanks!
