### ISSUE TITLE
Delete and Observables

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/CRUD#573]
Delete has the following trait (https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/Delete.php):

```
    /**
     * Delete a row from the database.
     *
     * @param  [int] The id of the item to be deleted.
     * @param int $id
     *
     * @return [bool] Deletion confirmation.
     *
     * TODO: should this delete items with relations to it too?
     */
    public function delete($id)
    {
        return (string) $this->model->find($id)->delete();
    }
```

If one forces that (string) cast out to make this an actual PHP bool (i.e. `true` && `false`) then the AJAX table always figures there is an issue.

I would note that Laravel's Eloquent returns **false** if an observable returns false, e.g:

```
(Illuminate\Database\Eloquent\Model - Laravel:~5.4)

 616     /**
 617      * Perform a model insert operation.
 618      *
 619      * @param  \Illuminate\Database\Eloquent\Builder  $query
 620      * @return bool
 621      */
 622     protected function performInsert(Builder $query)
 623     {
 624         if ($this->fireModelEvent('creating') === false) {
 625             return false;
 626         }
```

Might it be better to return whatever the underlying `create` operation returned rather than cast it to a string?

**Comment by lloy0076** [comment]
Actually it seems that the return for this must be something that a controller would return, i.e. removing the (string) part led me to:

```
[2017-03-24 16:15:09] local.ERROR: UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given. in C:\laragon\www\drakes-auth\vendor\symfony\http-foundation\Response.php:444
```

So, we're not REALLY returning a 'bool' at all - _are_ returning a string which seems to be something that Laravel (or Symfony) accept as a response.

**Comment by lloy0076** [comment]
I overrode the 'delete' method like this:

```
<?php

namespace App\Crud;

use Backpack\CRUD\CrudPanel as OriginalCrudPanel;

use Illuminate\Support\Facades\Log as Log;
use Illuminate\Database\Eloquent\ModelNotFoundException as ModelNotFoundException;

class CrudPanel extends OriginalCrudPanel
{
    /**
     * Deletes the request row.
     *
     * @param  [mixed] $id The ID.
     *
     * @return [mixed] $response An appropriate response.
     */
    function delete($id) {
        if (! isset($id)) {
            return response('Invalid ID', 422);
        }

        try {
            $model  = $this->model->findOrFail($id);
            $result = $model->delete();
        } catch (ModelNotFoundException $e) {
            return response('Not Found', 404);
        } catch (\Exception $e) {
            return response($e->getMessage(), 500);
        }

        if (isset($result) && $result === true) {
            return response('OK', 204);
        }

        return response('Not Found', 404);
    }
}
```

Obviously that's not going to work for everyone - were it to become a pull request, the following would need consideration:

1. Wording of the messages;
2. Whether the status codes are correct;
3. Changes to the UI if needed.

**Comment by tabacitu** [comment]
@lloy0076 this seems like a sensible change to me, and I think the wording can be easily fixed ("Entry not found"). If you submitted a working PR, I'd be happy to merge it, looks like it brings some stability to the delete functionality.

@tumf87 you're good at thinking of all possible use cases/problems. What do you think? Anything you'd change in @lloy0076 's approach above?

**Comment by tumf87** [comment]
Hi guys,

Writing the unit tests got me looking a bit more thoroughly through the code and it seems to me that the original intention for the CrudPanel was that it should act as a sort of 'service' layer.

I think this was a good approach, which lead to the moving of all the business logic stuff away from the controller and to higher decoupling and easier testing of some classes and traits.

Having said that, not all the classes/traits followed this principle and things like HTTP exceptions and requests made their way through different methods of the Crud Panel (which is making writing some tests a hassle).

If you agree with me on this, I think we should struggle to keep the Crud Panel as free from having to deal with HTTP/View logic as possible. Intercepting requests and issuing responses is the controller's job. 

The delete method should take a model, delete it and respond with a boolean. Converting it to a string should also be the controller's job.

What's your view on this?

**Comment by lloy0076** [comment]
So long as the front end can figure out what happened:

1. Did it fail because the row wasn't found?
2. Did it fail because of some permission error at the DB level?
3. Did it fail becuase Laravel itself flubbed out?

**Comment by tumf87** [comment]
As far as the front-end is concerned, I see two scenarios:
1. the row wasn't found -> the method returns false
2. an error happened -> the method throws an exception, which is caught by the exception handler or by the controller in a try-catch
In both cases, the appropriate message is shown to the user.

On the developer's side, in the case of an exception, the error along with any appropriate details are logged and debugging can start from there.

**Comment by lloy0076** [comment]
@tumf87 - I'm not sure we disagree with each other (and in fact, one just substitutes `whatever` in the various `return response(...)` to boot).

I should turn it into a PR I suppose.

**Comment by tabacitu** [comment]
Totally. Nice collaboration here.

**Comment by opannapo** [comment]
Check on your tables relations.
I've same problems, i am found the record has relation to some data on other tables.
Solved by delete table relations. (in my case)

**Comment by lloy0076** [comment]
This is not really broken (and no-one is screaming, including the OP).

Closing due to (my own) inactivity.

**Comment by lloy0076** [comment]
Ok, this just got noticed again - reopening.
