### ISSUE TITLE
[Bug] addButtonFromView($stack, $name, $view, $position = false) without 'meta'

### ISSUE THREAD

**Issue by zivarg** [Laravel-Backpack/CRUD#5741]
# Bug report

Why method addButtonFromView without meta?

**Comment by jcastroa87** [comment]
Hello @zivarg 

As Kapa says, if you check [our docs](https://backpackforlaravel.com/docs/6.x/crud-buttons#creating-a-custom-button-1) you can use meta for that's method.

I will close this issue, but please feel free to re-open or create a new one if needed.

Cheers.
