### ISSUE TITLE
Auth::check() returns false on ElFinder

### ISSUE THREAD

**Issue by codeartmk** [Laravel-Backpack/CRUD#575]
The config files seems to be okay, and It is actually working, I can upload without problem, but the Views are messed up on this route.

My sidebar is not rendered and as you can see, in the top menu it asks me to login and reggister.

![image](https://cloud.githubusercontent.com/assets/6769547/24350489/b3ac8294-12e2-11e7-9f74-b4d6a81bf264.png)

If I return to the **/admin** route, it is all fine :)

**Comment by codeartmk** [comment]
Anyone? I still have this problem

**Comment by tabacitu** [comment]
Hi @codeartmk ,

I think you might have missed a step in the installation process. You might have [published the elFinder files before the Backpack ones](https://laravel-backpack.readme.io/docs/install-on-laravel-54#section-3-install-backpackcrud). Take a look at your config file for elfinder. Your:
- config/elfinder.php
- vendor/backpack/crud/src/config/elfinder.php
should be the same. I'm mostly concerned about this part:
```php

    /*
    |--------------------------------------------------------------------------
    | Routes group config
    |--------------------------------------------------------------------------
    |
    | The default group settings for the elFinder routes.
    |
    */

    'route' => [
        'prefix'     => config('backpack.base.route_prefix').'/elfinder',
        'middleware' => ['web', 'admin'], //Set to null to disable middleware filter
    ],

    /*
    |--------------------------------------------------------------------------
    | Access filter
    |--------------------------------------------------------------------------
    |
    | Filter callback to check the files
    |
    */

    'access' => 'Barryvdh\Elfinder\Elfinder::checkAccess',
```

Hope it helps.

Cheers!

**Comment by codeartmk** [comment]
Yeah, the only difference I had was in the **route** array, my middleware was set to null.
Now it is all working.

Thank you
