### ISSUE TITLE
enableReorder() doesn't work with parent_id with constraint?

### ISSUE THREAD

**Issue by mysticzero** [Laravel-Backpack/CRUD#580]
My reordering menu only displays items that have parent_id set to null?

My parent_id field inside my **menu_items** table has a constraint with the id field from **menu_categories** table
Relationship:
Menu Items
`return $this->hasOne('App\Models\MenuCategory', 'id', 'parent_id');`
Menu Categories:
`return $this->hasMany('App\Models\MenuItem', 'parent_id', 'id');`

These 2 relationships work just for the backpack select2 field and I already enabled reorder and set it to 5. No error messages both for js and php.

**Comment by tabacitu** [comment]
Hi @mysticzero . I'm afraid I don't understand. Can you please rephrase? This structure helps everything be clear:

(A) what you did
(B) what you expected to happen
(C) what happened
(D) what have you already tried to fix it?

Cheers!
