### ISSUE TITLE
Can i build crud controller depending on 2 joining tables?

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/CRUD#582]
hey
i think about building crud controller depending on 2 joining tables. 
so the crud controller i build will get list of all data from the 2 joining tables 
and when i insert it will insert in 2 joining table 
and even when i update it will update in 2 joining table.

Thank you in advance

**Comment by tabacitu** [comment]
Hi @c1t1zen ,

You should be able to do that:
- using ```$this->crud->with('second_entity')``` for READ;
- using custom code in the ```store()``` and ```update()``` methods for CREATE and UPDATE (before or after calling the parent method);
- using custom code in the ```destroy()``` method for DELETE (if you also need to delete the entry from the second table);

Hope it helps.

Cheers!
