### ISSUE TITLE
Accessing ID from setUp() when updating an item

### ISSUE THREAD

**Issue by baj84** [Laravel-Backpack/CRUD#586]
Hi,

One of my crudFields requires data that is derived from the item I am updating. How can I access the Id of the Crud item when the page is rendered.

Example:
On page: /admin/bundle/3/edit

My BundleCrudController:
public function setUp() {
        $this->Study = new Study();

        $this->crud->addField([
            'name' => 'studies',
            'label' => 'Studies',
            'type' => 'select2_from_array',
            'options' => $this->Study->getUnallocatedStudies($bundleId),
            'allows_null' => false,
            'hint' => 'Search for the studies you would like to add to this bundle',
            'tab' => 'Info',
            'allows_multiple' => true
        ]);
}

How can I get the bundle ID (which should be 3)? The only way I can find is by getting it directly from the URL, but this seems hacky. I'm unable to use the select2_multiple as I require custom logic.

Thanks!

**Comment by tabacitu** [comment]
Hi @baj84 ,

I think these are the best two options:
1) Using ```$this->crud->entry->id``` (check if the entry property exists first, it should only be there for some operations).
2) Using ```\Route::current()->parameter('bundle')``` or ```\Route::current()->parameter('id')```.

Hope it helps. I'd personally do smth like this:
```php
if ($this->crud->entry) {
    $this->crud->addField([
        'name' => 'studies',
        'label' => 'Studies',
        'type' => 'select2_from_array',
        'options' => $this->Study->getUnallocatedStudies($this->crud->entry->id),
        'allows_null' => false,
        'hint' => 'Search for the studies you would like to add to this bundle',
        'tab' => 'Info',
        'allows_multiple' => true
    ]);
}
```

Cheers!

**Comment by simplusgroup** [comment]
I'm having the same issue here and I have not been able to find a solution. entry is a non-object. bundle returns nothing. Neither does parameter id.

**Comment by tabacitu** [comment]
@simplusgroup if all else fails, you should be able to use ```$this->crud->request```, which should have your ID parameter.

**Comment by simplusgroup** [comment]
@tabacitu Thanks for the reply! For some reason I wasn't able to get that to work either... I ended up using dd() for $this and didn't find it in any of the child variables, which is strange. I really haven't changed anything major with this backpack installation, either. 

Fortunately, I did find it using my route... $team_id = \Route::current()->parameter('team'); 

My model here is Team. 

Is that the cleanest way to retrieve that? Should/could that be added to documentation?

**Comment by tabacitu** [comment]
@simplusgroup thanks for sharing your solution. Sounds like a clean one to me! :-)

**Comment by jrpub** [comment]
Hi all

I think this is a frequent question/need. Why not include and document two relevant methods in CrudController.php, such as:

**$this->getMode()**
Will return "list", "edit", or "create" based on the value of $this->request->path() and other criteria.

**$this->getEditId()**
Will return **intval(\Route::current()->parameter(model))** or null if we are not in the edit mode. 

I think this would ease the work of many people and clarify the code in setup functions. 

```
if ($this->getMode() == 'edit') {

    $currentModel = Model::find($this->getEditId());

   // remaining code
}
```

**Comment by simplusgroup** [comment]
Thanks @jrpub I agree, that would be helpful... will take down to use moving forward :-)

**Comment by jrpub** [comment]
Ok, as I need it also, I made a Trait that you can easily insert in any of your Crud Controllers. I don't think the quality of code is good enough to propose a pull request of CrudController, so I put here. Feel free to use it.

```
<?php

namespace App\Http\Controllers\Admin\Traits;

trait CRUDControllerHelperTrait
{
    /**
     * Get the mode of CRUD (edit, add, view, index, etc.)
     *
     * @return void|string
     */
    public function getMode()
    {
        $path = \Route::currentRouteName();
        $entity = strtolower($this->crud->entity_name);
        if (preg_match('/^crud\.'.$entity.'\.(.+?)$/', $path, $out)) {
            return $out[1];
        }
        return null;
    }

    /**
     * Get the ID - if any (eg. only in edit/view mode)
     *
     * @return void|int
     */
    public function getId()
    {
        $parameters = \Route::current()->parameters();
        if (array_key_exists(strtolower($this->crud->entity_name), $parameters)) {
            return intval($parameters[strtolower($this->crud->entity_name)]);
        }
        return null;
    }
}
```
