### ISSUE TITLE
Localizing the package

### ISSUE THREAD

**Issue by v01061374** [Laravel-Backpack/CRUD#587]
Hi
I want to localize your package by making the views RTL and translating the whole panel to Persian so that people with similar requirements can use it.(It will be my delight)
Would you please tell me which files I should edit??

**Comment by tabacitu** [comment]
Hi @v01061374 ,

It shouldn't be too difficult to achieve for your own project. You could use [the CSS this package provides for RTL support in AdminLTE](https://github.com/mmdsharifi/AdminLTE-RTL) and you'd only need to make small modifications in layout.blade.php.

I don't know how possible it is to achieve in the main package, though - might make it a lot more difficult for LTR users. Could you please follow-up with the modifications you made, and we'll decide together the best way to instruct others to achieve LTR functionality?

Cheers!

**Comment by v01061374** [comment]
Hi Again
The last time I asked this question.
I couldn't get the desired result using your way, so that time i ignored to make your package rtl, but now I have to do so.
How can I completely replace Admin-LTE-rtl with the version you are using?
Why don't you add an rtl feature to your package, It is surely a delight for a lot of people.

**Comment by tabacitu** [comment]
Hi @v01061374 ,

Thanks for stressing the issue. RTL support would be great, but since AdminLTE doesn't provide it itself it would be very difficult for us to do it. We do plan to offer "themes" in Backpack, so that anyone can use AdminLTE, AdminLTE-rtl , Tabler or any other HTML template for the interface.

I'm afraid that's the best moment to provide RTL support, and do it sustainably. And it's a few months away. Until then, you should be able to do it yourself for you project, as I mentioned above, or (of course) whatever way you see fit.

Cheers!

**Comment by v01061374** [comment]
You know 
I'm not a laravel expert and I don't know how to implement your suggestion
Actually i tried to replace the adminLTE-rtl css but the result was not the desired one.

**Comment by tabacitu** [comment]
Sorry to hear that. We'll think of adding LTR support faster, if more people request it. Cheers!

**Comment by yaroodf2** [comment]
hi
How much time will be added rtl?

**Comment by tabacitu** [comment]
@yaroodf2 sorry to say this isn't a priority - very few people have requested RTL support, as you can see in this thread. We have no plans at this time.

**Comment by tifaahmed** [comment]
I planing to buy the  backpack package but is there hope for change from ltr to rtl

**Comment by tabacitu** [comment]
Thanks for the heads-up @tifaahmed - almost forgot about this one.

Yes, we've added RTL/LTR support in Backpack v4. You can change the direction inside ```config/backpack/base.php```. Change ```html_direction``` from ```ltr``` to ```rtl```.

Here's a quick preview ;-)

![Screenshot 2019-09-19 at 13 52 20](https://user-images.githubusercontent.com/1032474/65238554-92657780-dae5-11e9-9d09-466fabe80556.png)

Let me know if you find anything out-of-the-ordinary. It's very difficult for us LTR people to spot inconsistencies in RTL adaptations.

Cheers!

**Comment by tifaahmed** [comment]
i can't find html_direction in config. backpack.base  in the free demo

في الخميس، ١٩ سبتمبر، ٢٠١٩ ١:٠٠ م Cristian Tabacitu <
notifications@github.com> كتب:

**Comment by Mu9tafa-Online** [comment]
@tifaahmed , I Don't think it's ready yet on "Demo" Repo.

**Comment by tabacitu** [comment]
You'll have to be running version 4, which is still in beta. You can install the beta using [the 4.0 docs](https://backpackforlaravel.com/docs/4.0/installation) - those are pretty much done.

**Comment by thaifani** [comment]
yes it is worked perfectly 
but the columns order fa images stile on the left even when change to rtl 
and the row count  pointer stile in the left 
almost ,Thank you

**Comment by ahmad-ms96** [comment]
@tabacitu  what if  i have to  change the direction from controller when user want to use other lang ?

**Comment by waliddev147** [comment]
This is website solve problem 
https://rtlcss.com/

**Comment by tabacitu** [comment]
@raviroshanmehta so what you want... is for everything to stay LTR... but only the inputs to be aligned RTL? I mean the text in them? That's... unusual. Sounds like a job for custom CSS. You can add custom CSS to all Backpack pages by creating your own file, and then mentioning it in `config/backpack/base.php` (in Backpack v5) or `config/backpack/ui.php` (in Backpack v6).

**Comment by msalehi-d** [comment]
@tabacitu thanks.
is there a way to replace ccs files? i need to use my own version of bootstrap 5 (RTL) not the default one included with Backpack.
