### ISSUE TITLE
Call boot method from model parent in local boot method.

### ISSUE THREAD

**Issue by de-raaf-media** [Laravel-Backpack/CRUD#588]
In the documentation the boot method is called to delete the image which was added to the model. Can you update the documentation so parent::boot(); is called? Otherwise this will lead to unexpected behavior (f.i. the sluggable method in my model was never called).

public static function boot()
    {
        parent::boot(); // <== call the parent boot method

        static::deleting(function($obj) {
            \Storage::disk('public_folder')->delete($obj->image);
        });
    }

**Comment by tswonke** [comment]
Another approach is to extract the whole logic to a trait using Lavarels magic boot{traitname}() method. A parent::boot() isn't necessary any more:

`trait ImageableTrait
{
    public static function bootImageableTrait()
    {
        static::deleting(function ($obj) {
            \Storage::disk('uploads')->delete($obj->image);
        });
    }

    public function setImageAttribute($value)
    {
        //
    }
}`

**Comment by tabacitu** [comment]
Hi @de-raaf-media ,

Thanks, just updated the docs. Cheers!

**Comment by de-raaf-media** [comment]
Thanks @tabacitu !
