### ISSUE TITLE
Custom Primary Keys?

### ISSUE THREAD

**Issue by rgreer4** [Laravel-Backpack/CRUD#59]
I may be missing something, but it looks like the crud library does not take in to account a defined $primaryKey = 'my_id'; in your models?

Looking in list.blade.php and some other areas I see items like {{ Request::url().'/'.$entry->id }} that seem fixed to the 'id' convention.

**Comment by tabacitu** [comment]
Yes, I'm afraid quite a lot of the code does NOT account for the ```$primaryKey``` variable right now, but it definitely should.

This might be a showstopper for a lot of models, so I'll go ahead and make this issue "urgent" and will find time to do it ASAP. If you are in a hurry and willing to contribute to the project, you're free to submit a pull request, I'd be more than happy to merge.

Cheers!

**Comment by tabacitu** [comment]
Looks like there are just a few mentions.

I've taken a stab at it in 6da0f929920bbf711491f560aed8665fa7eb0896, and it SEEMS to work, but I need another confirmation before I can merge it in the master branch.

Could you try it out an see if I missed anything, please?

**Comment by rgreer4** [comment]
Awsome, thanks! It's almost working:

1. need to also update src/resources/views/fields/select.blade.php

2. in src/app/Http/Controllers/CrudController.php -> updateCrud() doesn't work:

`$this->crud->update($request->get('id'), $request->except('redirect_after_save'));`

changing it to:

`$this->crud->update($request->get($this->crud->model->getKeyName()), $request->except('redirect_after_save'));`

...seems to work, but not sure if that is the most elegant method.

**Comment by tabacitu** [comment]
Ok, great. It's now on master, v2.0.23

Yeah... the updateCrud() change is a bit ugly, but I see no other way, really.

Cheers, thanks for the help!
