### ISSUE TITLE
Model hasMany Media::class

### ISSUE THREAD

**Issue by physio** [Laravel-Backpack/CRUD#595]
I want to insert in an Article model some images. How you suggest to develop? Is it possible to integrate spatie/medialibrary for example?

**Comment by tabacitu** [comment]
Hi @physio ,

You should be able to integrate spatie/medialibrary, yes, but I think it will be easier to use the ```upload_multiple``` field type: https://laravel-backpack.readme.io/docs/crud-fields#section-upload_multiple

Hope it helps. Cheers!
