### ISSUE TITLE
entity in addField does not use the method in the model

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#597]
I have a App\User with a hasOne relation to App\Models\Center. I use PermissionManager.

```
    public function center()
    {
        return $this->hasOne('App\Models\Center')->hasRole('Center Admin');//return only Center Admins.
    }

```

So App\Models\Center has belogsTo relation to App\User.

```

    public function user()
    {
        return $this->belongsTo('App\User');
    }

```

In app/Http/Controllers/Admin/CenterController.php.

```
        $this->crud->addField([
            'name' => 'user_id',
            'label' => 'Center Admin',
            'type'=>'select',
            'tab' => 'GENERAL',
            'entity' => 'center', 
            'attribute' => 'name',
            'model'=>'App\User',
        ]);
```

Problem 1. This displays all users.
Problem 2. I can comment out  `'entity' => 'center', ` and it still displays all users.

How can I display uses who has a certain role?

**Comment by tabacitu** [comment]
Hi @shinokada ,

You can:
1) use [select_from_array](https://laravel-backpack.readme.io/docs/crud-fields#section-select_from_array) and populate it with the options you want;
2) create a new User model that has the center as a [global scope](https://laravel.com/docs/5.4/eloquent#query-scopes) and use that in your select field;

Hope it helps.
Cheers!
