### ISSUE TITLE
enableAjaxTable and Column model_function type don't goes well together

### ISSUE THREAD

**Issue by iMokhles** [Laravel-Backpack/CRUD#598]
Hey i really enjoying this package, but i faced the following issue
i'm using [laravel-countries](https://github.com/webpatser/laravel-countries)
and created a Model, Request and Controller for it using 
```php artisan backpack:crud Country```
so everything goes well till i decided to use `model_function` with `enableAjaxTable` inside my `CountryCrudController`
i added the following
```
$this->crud->addColumns([
            [
                'name' => "id",
                'label' => "ID"
            ],
            [
                'name' => "name",
                'label' => "Name"
            ],
            [
                'name' => "citizenship",
                'label' => "Citizenship"
            ],
            [
                'name' => "currency",
                'label' => "Currency"
            ],
            [
                'name' => "capital",
                'label' => "Capital"
            ],
            [
                'label' => "Flag", // Table column heading
                'type' => "model_function",
                'function_name' => 'getFlagFromName', // the method in your Model
            ],
        ]);
```

and in my Model the following
```
public function getFlagFromName() {

        return '<center><img src="'. asset('assets/flags'.'/'. $this->flag) .'"></center>';
    }
```
so if i comment ```$this->crud->enableAjaxTable();``` the flags images works fine
but if i uncomment it ```$this->flag``` from the Model function goes empty

any advise or tip to make it works fine with `enableAjaxTable` ?
thanks in advance

**Comment by iMokhles** [comment]
Okey after some research i was able to fix this issue i will post my solution here so i hope it could help someone else 

from this line [CrudFeatures/AjaxTable.php#L22 and #L23](https://github.com/Laravel-Backpack/CRUD/blob/c9d599ec8ede008f4059961d4a418bf071695faa/src/app/Http/Controllers/CrudFeatures/AjaxTable.php#L23) i understood that the ajax tables get the primary key while listing rows so i fixed my issue by using the following code in my model

```
public function getFlagFromName() {
        // get country object using it's primary key from the database
        $country = DB::table('countries')->where('id', $this->id)->first();
       // then show the flag after using the following code to get flag column value
        return '<center><img src="'. asset('assets/flags'.'/'. $country->flag) .'"></center>';
    }
```

now flags images appear and work fine with `$this->crud->enableAjaxTable();`

Closing it now.

**Comment by danielfaulknor** [comment]
@iMokhles thank you!!

**Comment by iMokhles** [comment]
@danielfaulknor you are welcome hope this was helpful for you
