### ISSUE TITLE
Set text input name and additional class to Table field

### ISSUE THREAD

**Issue by cyberfly** [Laravel-Backpack/CRUD#599]
Hi how do I add text input name and additional class to table field? It will be much easier to style and data manipulation with jquery.

Thanks

![backpacktablefields](https://cloud.githubusercontent.com/assets/1756170/24843802/be7696d2-1dd8-11e7-9902-d27e8cbf57db.png)

**Comment by lloy0076** [comment]
```
131              [
132                 'name'  => 'email',
133                 'label' => 'Email',
134                 'type'  => 'text',
135                 'attributes' => [
136                     'placeholder' => 'customer@example.com.au',
137                 ],
138                 'tab'   => 'Required Details',
139             ],
```

You can add any "random" attributes you like using the 'attributes' as shown above.

Is this, maybe, what you are seeking?

**Comment by cyberfly** [comment]
@lloy0076 Hi i am aware of the example code that you posted, works well on normal field.

However what I need is how to set class or input name to the Table field so I can manipulate individual data on each field.

https://laravel-backpack.readme.io/docs/crud-fields#section-table

**Comment by tabacitu** [comment]
Hi @cyberfly ,

There's currently no way to pass attributes to the ```table``` field. I think you'd best achieve it using [a custom field](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types), starting from ```table```. 

The "attributes" option would have been very ambiguous here. Where would the attributes be placed?
- on the hidden input?
- on the table?
- on each input[type=text]?
- would it also be placed on the button?

As I said - I think it's best if you roll your own, if you need custom data manipulation.

Cheers!

**Comment by cyberfly** [comment]
Thanks your answer point me to the right direction

Here is the final code for those who want to achieve the same thing:

/resources/views/vendor/backpack/crud/fields/table.blade.php line 53, I add additional class based on column_name

`<input class="form-control input-sm {{ $prop }}" type="text" ng-model="item.{{ $prop }}">`
