### ISSUE TITLE
Elfinder working great in local but not in server 

### ISSUE THREAD

**Issue by DrudgeRajen** [Laravel-Backpack/CRUD#60]
I am getting **404 error** with below message when clicked on browse option to upload image. What's the reason ?

> The requested URL /admin/elfinder/popup/image-filemanager was not found on this server.

**Comment by tabacitu** [comment]
Hmm... are you sure you've followed [all the steps in the installation process](https://github.com/Laravel-Backpack/CRUD)?

I'm thinking mainly of:
4) ```php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="elfinder" #publish overwritten elFinder assets```

**Comment by DrudgeRajen** [comment]
Yeah it is working now . It was due to mine silly mistake .

**Comment by tabacitu** [comment]
Great! Cheers!
