### ISSUE TITLE
Bootstrap error classes and validation message not displaying on array field names

### ISSUE THREAD

**Issue by splodgeco** [Laravel-Backpack/CRUD#600]
As the subject indicates. The bootstrap errors classes and validation messages are not displaying when there is a validation error on array fields. I have tracked this down to the following view and included a fix. I'm sure there is a more elegant solution than this, but it works!

File `form_content.blade.php` line `89`
From 
```
var field = $('[name="' + property + '"]'),
    container = field.parents('.form-group');

container.addClass('has-error');
```
To
```
var field = $('[name="' + property + '[]"]').length ?
    $('[name="' + property + '[]"]') :
    $('[name="' + property + '"]'),
    container = field.parents('.form-group');

container.addClass('has-error');
```

**Comment by tabacitu** [comment]
Hi @splodgeco ,

You're totally right, thank you, haven't noticed that. I'm just now workind on a "monster entry" with all features in the Demo, so this kind of bugs will be more visible.

I've applied your fix to the ```dev``` branch and it will be available to everyone next week. Thanks a lot, cheers!
