### ISSUE TITLE
Responsive issue on list view when enableAjaxTable on

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#601]
Without enableAjaxTable():
`<table id="crudTable" class="table table-bordered table-striped display dataTable" role="grid" aria-describedby="crudTable_info">`

With enableAjaxTable():
`<table id="crudTable" class="table table-bordered table-striped display dataTable" role="grid" aria-describedby="crudTable_info" style="width: 1390px;">`

enableAjaxTable() add a _style="width: 1390px;"_ to the table and the table is not responsive anymore.

![withajax](https://cloud.githubusercontent.com/assets/24914102/24868595/d188c7ee-1e10-11e7-94ff-bc0b4f1311ac.jpeg)
![withoutajax](https://cloud.githubusercontent.com/assets/24914102/24868596/d1886772-1e10-11e7-8cdf-8079b49f45fa.jpeg)

**Comment by tabacitu** [comment]
@adbmdp I haven't been able to verify this, so I'll close it. Might have been fixed in the meantime... Let me know if you're still having the issue with the latest Backpack.

Cheers!
