### ISSUE TITLE
addField: Hide If..

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#602]
This idea mostly comes from working with PageManager as well. A lot of times pages may have a "featured image" or a "featured video" I want to be able to show the option for both but if one is selected then hide the other one and maybe automatically replace it with a line of text/link that says something along the line of `Remove your image to display the video field` 'image' would be replaced with video depending on selected.

Thinking the key for the array could be `hide` so it would check if a field with the name of whatever is in that value gets any input. I am happy to work on this but wanted to get it in the list and have some feedback.

**Comment by MarcosBL** [comment]
Maybe this could help @AbbyJanke ? https://github.com/Laravel-Backpack/CRUD/issues/527#issuecomment-285239343

**Comment by AbbyJanke** [comment]
Well that works perfectly :) 

Thank you @MarcosBL
