### ISSUE TITLE
Shouldn't it  $active_pages = $page_model::all(); in resources/views/fields/page_or_link.blade.php be in Controller?

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#606]
HI, 
I want to add a model function in MenuItemCrudController.php so that it will show pages with the same center_id.
However resources/views/fields/page_or_link.blade.php has `$active_pages = $page_model::all();` to display all pages.

Shouldn't it be in MenuItemCrudController.php what you want to show? 
PageCrudController.php does it,  `$this->data['entry'] = $model::findOrFail($id);` so that you can control what you want to show.

If you add `$active_pages = $page_model::all();`  in a view, how can I change it? 
Do I have to overwrite all files up to this file?

```
//form_content.blade.php

    $field['options'] = ['page_link' => trans('backpack::crud.page_link'), 'internal_link' => trans('backpack::crud.internal_link'), 'external_link' => trans('backpack::crud.external_link')];
    $field['allows_null'] = false;
    $page_model = $field['page_model'];
    $active_pages = $page_model::all();
?>
```

**Comment by tabacitu** [comment]
Hi @shinokada ,

You can overwrite those blade files, by having files with the same name in your ```resources/views/vendor/backpack/crud```

Hope it helps. Cheers!
