### ISSUE TITLE
Table cell validation on table field type

### ISSUE THREAD

**Issue by novocent** [Laravel-Backpack/CRUD#607]
Does the existing table field type have any built in validation for their cells? For example, if I wanted any cell to be a required field. 

I can't seem to find any reference to table cell validation in the documentation or the issues.

If there isn't something built in, I'm curious how you would consider approaching this.

Thanks!

<img width="973" alt="screen shot 2017-04-12 at 11 21 29 am" src="https://cloud.githubusercontent.com/assets/3177296/24965586/79d8da12-1f72-11e7-9331-0ff0a9e2ad5c.png">

**Comment by MarcosBL** [comment]
Take a look at this https://github.com/Laravel-Backpack/CRUD/issues/463 for nested table fields, you can create any type of field in a custom way using that info, and you can use client HTML5 validation on them using the "type" (email, url, number, etc...)

If you prefer/want to add (and you should) backend validation, you can always include a validation in the `store(StoreRequest $request)` and `update(UpdateRequest $request)`, prior to `parent::storeCrud();` and `parent::updateCrud();`

````php
... 

public function store(StoreRequest $request)
{
	if (!$this->your_custom_validate_function()) { 
	  return \Redirect::back()->withErrors("Incorrect table fields")->withInput();
	}
	$redirect_location = parent::storeCrud();
	return $redirect_location;
}

public function update(StoreRequest $request)
{
	if (!$this->your_custom_validate_function()) { 
	  return \Redirect::back()->withErrors("Incorrect table fields")->withInput();
	}
	$redirect_location = parent::updateCrud();
	return $redirect_location;
}

public function your_custom_validate_function() {
	check_whatever_you_want_from_the_table_fields();
	return true; /* or false if any error */
}

...
