### ISSUE TITLE
Enable or Disable Operation in Backpack Admin Panel

### ISSUE THREAD

**Issue by usmanhafeez147** [Laravel-Backpack/CRUD#608]
Hello to dears, First of all thanks to Backpack team. It is really great package ever in **Laravel** for me for Admin Panel. It provides to customize easily and everything for specific requirements
I have a bit question regarding the admin Feature.
Is there a feature in **laravel backpack** to store just **one record** only with updating permission from admin panel?
For Example, I want to make a "**enable/disable**" button on admin dashboard to "**show/hide**" some user module, is there any way to handle regarding this situation?
please! hint me with an example.

**Comment by tabacitu** [comment]
Hi @usmanhafeez147 ,

I think [Backpack\Settings](https://github.com/Laravel-Backpack/Settings) might be what you're looking for. Do notice it stores global settings, though, not per-user.

If you're looking for per-user settings, I'm afraid there's nothing pre-built. But it should be easy to build using regular Laravel (no CRUD needed here).

Hope it helps. Cheers!

**Comment by usmanhafeez147** [comment]
cheers

On Tue, Apr 18, 2017 at 2:10 AM, Cristian Tabacitu <notifications@github.com
