### ISSUE TITLE
HELP - User edit own posts

### ISSUE THREAD

**Issue by adnanfajr** [Laravel-Backpack/CRUD#610]
does anyone know how to restrict user to edit post another user?

**Comment by iMokhles** [comment]
hi @adnanfajr you have to assigne user for your post using user_id and check if the editor_id equal to the current logged in user_id or not :)

**Comment by adnanfajr** [comment]
@iMokhles i have assigned user_id to posts table, and then how do I set controller or router so can restrict user? :)

**Comment by iMokhles** [comment]
Here's example of how you do it if there are logged in user and you get the post using find() method

``` 
if (Auth::check()) {
    // user already logged in
    $id = Auth::id(); // get current logged in user's id
    $post = Post::find(POST_ID);  // get the post you want from id 
    // ( you can use get your post the way you want )
    $postUserId = $post->user_id;
    if ($postUserId == $id) {
        // User authorized to perform this action
    } else {
        // User not authorized to perform this action
    }
} else {
    // guest and not logged in
}
```

**Comment by tabacitu** [comment]
Great answer, @iMokhles . 

I think it pretty much sums it up AND has comments to explain everything that's going on, so I'll close the issue.

Cheers!
