### ISSUE TITLE
Translatable fake fields.

### ISSUE THREAD

**Issue by gotrecillo** [Laravel-Backpack/CRUD#614]
At the moment i dont think there is a way to make a fake field translatable.
It is something that is being developed ?

The PageManager is very multilingual unfriendly because of this.

**Comment by AurelDragut** [comment]
The fake field doesn't have its own field in the db table. To get his value you must parse the json string that is saved in the db table, that is why i told you on Gitter that you might need to add that field (that stores the values) as text (along with the fake ones, if that wasn't clear enough) and make the translations there.

The Page model has an "extras" field that contains all those fake fields (description, keywords, etc.). For example, if you wanna translate those two (description, keywords) at the moment you have to add the "extras" as text in the PageCrudController. I can't figure out a way to do this in a different manner.

**Comment by gotrecillo** [comment]
![image](https://cloud.githubusercontent.com/assets/9203112/25090474/b3846834-2383-11e7-866c-404d7a6a64e3.png)


You mean editing it like this ?

**Comment by AurelDragut** [comment]
Yeah, did that work? Or it's still gettin' errors?

**Comment by gotrecillo** [comment]
it works that way, will have to hide the extras field somehow and show the translatable flag in the fake fields.

Thanks

**Comment by AurelDragut** [comment]
Good luck on that

**Comment by tabacitu** [comment]
@gotrecillo there's quick solution to this - just have a separate column in the db where you store the translatable extras. Check out this comment https://github.com/Laravel-Backpack/CRUD/issues/617#issuecomment-311133974.

Cheers!
