### ISSUE TITLE
[Question] Fake field and translations

### ISSUE THREAD

**Issue by chancezeus** [Laravel-Backpack/CRUD#617]
I wonder about translatable and the fake field functionality. Currently to create a translatable fake field you have to mark the entire column as translatable. This makes it impossible for a fake column to contain both translated and untranslated content. For example SEO/OpenGraph meta information: `meta_title`,`meta_description` and `meta_keywords` should all be translatable, but `meta_image` is (almost always) the same for any language. From a practical standpoint (also looking at potential overhead when using a mixed translatable/non translatable fake field situation) it would be more logical if a fake field would store it's "faked" translated information per field inside the fake column (maybe through a configuration property)... Combining this with the "withFakes" option and a slightly modified "HasTranslations" should provide enough flexibility to mix-and-match translated/untranslated fields inside a single fake column...

**Comment by promatik** [comment]
Hi @chancezeus!
Have you solved this problem? I'm facing it now because I have a CRUD entity with exactly 18 entries. Some entries have some exclusive fields, which are saved in extras, but some may be translatable and others may not.

**Comment by lloy0076** [comment]
Whilst this isn't a proper fix, is it possible to specify to backing database columns (e.g. `extras_untranslated` and `extras_translated`)?

**Comment by promatik** [comment]
Great ideia @lloy0076!
But how am I going to distinguish the fake fields when storing/updating?

	$this->crud->addField([
		'fake' => true,
		'name' => 'title',
		'label' => 'Title',
		'type' => 'text',
	]);

**Comment by lloy0076** [comment]
I don't think you need to distinguish them depending on what you're doing, see the FakeFields trait at https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/FakeFields.php.

**Comment by promatik** [comment]
@lloy0076 you were right, I solved it without any coding, just by adding `'extras_translatable'` to `$fillable`, `$fakeColumns` and `$translatable `, and cast `'extras_translatable'` to `array`.

```js
protected $fillable = ['title', 'description', 'extras', 'extras_translatable'];
protected $fakeColumns = ['extras', 'extras_translatable'];	
protected $translatable = ['title', 'extras_translatable'];
protected $casts = ['extras_translatable' => 'array'];
```
Also, when adding field, store the field in `extras_translatable`.

```js
$this->crud->addField([
	'fake' => true,
	'store_in' => 'extras_translatable',
	...
]);
```
And it's done!

**Comment by tabacitu** [comment]
Hi guys,

Sorry for coming so late to the party. Yes, the though behind translatable extras was exactly what @promatik ended up using - a separate db column to store the translatable extras.

Cheers!

**Comment by diakosavvasn** [comment]
Hello guys, 

[This comment](https://github.com/Laravel-Backpack/CRUD/issues/617#issuecomment-311133974) doesn't work on **backpack/crud `4.0.23`,  Laravel `6.6.0`**
The only think you should change is that you don't have to cast` 'extras_translatable' `to `array`. Everything else works just fine. 
Thank @promatik for your answer. I just mention that because it took me hours to realize that.
