### ISSUE TITLE
CRUD Controller Does not Exist

### ISSUE THREAD

**Issue by AbbyJanke** [Laravel-Backpack/CRUD#622]
Hey, was following the instructions on the website exactly and even created a brand new project that is still having the same issue. I looked to try and fix it to send a PR but can't find any source code for it o.O

When trying to create a new CRUD based Controller and add it to the routes file I am getting this.

```
ReflectionException in Container.php line 719:
Class Admin\NewsCommentCrudController does not exist
in Container.php line 719
at ReflectionClass->__construct('Admin\\NewsCommentCrudController') in Container.php line 719
at Container->build('Admin\\NewsCommentCrudController') in Container.php line 598
at Container->resolve('Admin\\NewsCommentCrudController') in Container.php line 567
at Container->make('Admin\\NewsCommentCrudController') in Application.php line 708
at Application->make('Admin\\NewsCommentCrudController') in Route.php line 217
at Route->getController() in Route.php line 736

```

**Note:** `Admin\\NewsCommentCrudController`

It seems to be adding double '\' lines. I have tried be doing a group with a namespace, and directly coding the slash into the controller info.

**Comment by iMokhles** [comment]
add this to your app\Provider\RouteServiceProvider.php



```
public function map()
    {
    $this->mapAdminRoutes();
    ........
}
protected function mapAdminRoutes()
    {
        Route::middleware('admin')
            ->namespace($this->namespace.'\Admin')
            ->prefix('admin')
            ->group(base_path('routes/admin.php'));
    }
```

**Comment by tabacitu** [comment]
@AbbyJanke ,

Hmm... I can't seem to get the same result, it worked for me with ```Backpack\Generators 1.1.8```:
![screen shot 2017-04-21 at 07 43 47](https://cloud.githubusercontent.com/assets/1032474/25263177/56966dee-2666-11e7-9610-39966db47c65.png)

I wonder - what's your setup?
- operating system
- server software
- php version
?

**Comment by AbbyJanke** [comment]
I am not using the generators myself and doing it the longway. I prefer to
do that as it lets me see more of what is going on. I have yet to take a
look at my service provider as @IMokhles has suggested. As for what I am
running:

- MacOS (10.12.4 beta)
- Valet (with MySQL)
- PHP 7

I can take a look further to see if the service provider is the isshe in a
few hours as I am just getting ready to head to work.

**Comment by tabacitu** [comment]
Oh, ok. So you've manually created the controller and route? In this case, please copy-paste the route and controller when you get to work. Cheers!

**Comment by AbbyJanke** [comment]
Update on this, been busy so sorry for taking forever. Adding the Namespace to the service provider map function like @iMokhles suggested worked.

Thanks.
