### ISSUE TITLE
Read image in CRUD

### ISSUE THREAD

**Issue by anthonyRV** [Laravel-Backpack/CRUD#626]
Hi, the image upload works very well, i use the mutator to save the path of the image, uploaded in uploads disk. My question is how to show this image in read part??

I have tried adding a custom column by adding the following line in custom blade file:
{{-- regular object attribute --}}
<!img src="{{ $entry->{$column['name']} }}" height="42" width="42"!>

**The exclamations point are to show the code  instead of editor take it as html tag**

and using it in the same way other columns are used.

Then I tried to use the column_row_details, i try to read the like that:
<!img src="{{ $model->pathToFile }}!"> 

But sadly, none of this work for me.

I think could be for references to uploads folder in the blade file. But i cant solve the problem yet.

Waiting for help, Thanks

**Comment by tabacitu** [comment]
Hi @anthonyRV - I see you've closed the issue. What was your problem and the solution that worked for you? It could help other people that run into the same problem.

Cheers!

**Comment by anthonyRV** [comment]
Hi, I created a new column type with the next code: 
`{{-- regular object attribute --}}
<td><img src="{{ asset($entry->{$column['name']}) }}" width="100" height="100"></td>`

And its used like normally column type of Backpack.
I set that dimensions cause its work for me, i show the image in its original size in that column_details_row.

Cheers!

**Comment by MarcosBL** [comment]
I think this will be soon available thanks to @oscarmlage https://github.com/Laravel-Backpack/CRUD/pull/570

**Comment by anthonyRV** [comment]
I only found that asset() function is required to access to uploads disk, in public folder, in order to work with image field upload and saving the path to DB. Hope helps someone.
