### ISSUE TITLE
filenames on uploaded images

### ISSUE THREAD

**Issue by alexkb** [Laravel-Backpack/CRUD#628]
I'm using the image field type as per the [instructions](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#section-image), but rather than generate a hash for the filename, I would like to retain the filename for use, as it's good for SEO. I've already tried inspecting what's in `\Request::instance();` but nothings in there, so I'm guessing it's a setting on the front end JS widget that collects the image contents but only sends the base64 data.

**Comment by tabacitu** [comment]
Hi @alexkb ,

Yes, unfortunately the submitted image is in Base64, so no filename information there...

Cheers!
