### ISSUE TITLE
[QUESTION] Is it possible to use your admin panel without Eloquent?

### ISSUE THREAD

**Issue by Shandur** [Laravel-Backpack/CRUD#632]
Hello. I'm currently developing project and decided using Doctrine instead of Eloquent.
And I wonder is it possible to use your admin panel without Eloquent at all? Is your internal logic tightly coupled to it or it's possible with some class extending get rid of Eloquent model logic?

Thanks! Hope you'll reply asap :)

**Comment by tabacitu** [comment]
Hi @Shandur ,

In short, no. Backpack depends on Eloquent to do all database operations.

Cheers!
