### ISSUE TITLE
Concate Two Columns

### ISSUE THREAD

**Issue by krunaltasolglobal** [Laravel-Backpack/CRUD#633]
Hello,

I am facing one issue with backpack.
I have database with user table with `first_name` and `last_name`.
I want to display in list view as merge of this two columns. I was trying using `model_function` and make one function in model too. but in this solution `first_name` and `last_name` columns display separately too. If I removed this two columns then I am not able to get two columns using merge too.

**Comment by smitshah81** [comment]
I am facing the same issue, I was trying to merge columns and display as a single column in the grid but I am not able to manage then same.I would really appreciate if someone shares how to implement this.
I have also checked StackOverflow and GitHub and tried to implement but it is not working. 
@krunaltasolglobal  can you please share code which you have implemented?

**Comment by krunaltasolglobal** [comment]
In My Controller 

```
[
   'label' => trans('backpack::contact.first_name'),
   'type' => 'model_function',
   'function_name' => 'showFullname',
   'name' => 'referrer'
],
[
   'label' => trans('backpack::contact.first_name'),
   'name' => 'first_name',
   'type' => 'hidden'
],
[
   'label' => trans('backpack::contact.last_name'),
   'name' => 'last_name',
   'type' => 'hidden'
],
```

In my model 

```
public function showFullname() {
    return $this->salutation . ' ' . $this->first_name . ' ' . $this->last_name;
}
```

**Comment by smitshah81** [comment]
This case is not working with me too... :( . Can Anyone please help with this?

**Comment by lloy0076** [comment]
If you're using an Ajax table it may not work (actually probably **won't** work).

**Comment by tabacitu** [comment]
Hi @krunaltasolglobal , @smitshah81 ,

I think I've got a sexier solution for you. Why not use a [Laravel Accessor](https://laravel.com/docs/5.4/eloquent-mutators#defining-an-accessor)?

In your model:
```php
public function getFullNameAttribute() {
    return $this->salutation . ' ' . $this->first_name . ' ' . $this->last_name;
}
```

In your CrudController:
```php
$this->crud->addColumn('first_name'); // this is a shorthand for the text column
```

This should work both with standard AND ajax datatables. 
Hope it helps. Cheers!

**Comment by alashow** [comment]
@tabacitu this would raise an SQL exception trying to find 'full_name' field in the table, no?

I have a similar situation. I have a field named 'expires' in my table. I want to show something like 'isExpired' status in format `Yes/No (date)`. When I use `model_function`, and try to access `expires` field in the model, it shows null. Because the expires field doesn't get selected with sql query.

Is there any way to ask backpack to select the field when querying entries? I pass `expires` as `name` options but it doesn't select it.

**Comment by lloy0076** [comment]
@alashow If you add an accessor, don't forget to add the field name in `$fillable` otherwise things may not work as expected.

(This advice also goes for when one adds a real column afterwards, e.g. because one forgot to add a 'middle_name' column in the db for example. It's bitten me before).
