### ISSUE TITLE
accessing relationship from a child model?

### ISSUE THREAD

**Issue by elsodev** [Laravel-Backpack/CRUD#634]
Hi, i have encountered a problem, i have no idea how this can be achieved. 

Is there a functionality to handle multiple inheritance
My models:
1. Projects
2. Project Owner
3. User

Projects -> Project Owner -> User

A Project can have many owners
Every Owner is a User

I am working on the CRUD for Project model.
How do i add a column and field which displays the user's name? since Project Owner is the intermediate table, i need to access ProjectOwner's user() relationship method to able to get the name.

**Comment by tabacitu** [comment]
Hi @elsodev ,

You should be able to easily do that with a [Laravel accessor](https://laravel.com/docs/5.4/eloquent-mutators#defining-an-accessor). Here's how I would do it:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProjectOwner extends Model
{
    // define the relationship between project owner and user
    public function user()
    {
        return $this->hasOne('App\User');
    }
   
    // accessor to get the user's name like it was the owner's
    public function getNameAttribute($value)
    {
        return $this->user->name;
    }
}
```

This way, you'll be able to use ```$owner->name``` just like it had that attribute in the database. Not only in Backpack, but anywhere in your app.

Hope it helps.
Cheers!

**Comment by lloy0076** [comment]
@tabacitu - @elsodev It should be noted that if you use the AJAX style tables, the accessors (and any model_function) won't work with the list columns.

They do work in the edit (update) / create (store) forms.

**Comment by tabacitu** [comment]
YET! :-) I plan on thoroughly testing and merging [this PR](https://github.com/Laravel-Backpack/CRUD/pull/445) this week, which promises to solve all our ajax problems :D

**Comment by elsodev** [comment]
@tabacitu yes i did tried that, but what about the field in create/edit?

**Comment by lloy0076** [comment]
@elsodev 

```
protected $fillable = [
  // Other fields
 $example,
];

public function getExampleAttribute()
{
  return $this->example;
}

public function setExampleAttribute($value)
{
  $this->atributes['example'] = $value;
  // see https://laravel.com/docs/5.4/eloquent-mutators#defining-a-mutator
}
```

You'll need to set the add/update fields yourself as the underlying CRUD controller checks the database itself to see what fields to populate when you call `$this->crud->setFromDb()`.
