### ISSUE TITLE
[QUESTION] CRUD 1-1 relationship

### ISSUE THREAD

**Issue by ivanmart** [Laravel-Backpack/CRUD#637]
I have 3 models: **Product**, **Type1** and **Type2**. The product can be one of two types, that have different set of attributes. A **Product** model has one-to-one relations with both **Type1** and **Type2** models. What I need - is a single edit page for **Product** model in Backpack, where **Type1** or **Type2** model fields should appear, depend on product's type. I have two questions:

1.- What could be the best way to integrate it in Backpack?

2.- How do I add a field from related model **Type1**, for example?
I've tried (in ProductCrudController.php):

```
$this->crud->addField([
    'name'  => 'type1->field1', // it works in Tinker: $p->type1->field1
    'label' => 'Field1',
    'type' => 'text',
]);
```
doesn't work.

**Comment by lloy0076** [comment]
@ivanmart - there's request for support of one-to-one relationships at https://github.com/Laravel-Backpack/CRUD/issues/250

Depending on what you need, the way I've implemented such functionality is the following:

1. Define an _accessor_ and _mutator_ for the field (see https://laravel.com/docs/5.4/eloquent-mutators) on the model
2. Add the name to the `$fillable` array on the model
3. Then stop using `$this->crud->createFromDb()` because it only looks at the DB for columns to make the list view, edit fields and create fields and defined all the columns/edit/update fields manually.

At the moment, if you're using the Ajax Table support, the field can't/won't be shown in the list view (i.e. what you get at `/admin/test`) but there's support coming soon that I think will solve that issue.

**Comment by ivanmart** [comment]
@lloy0076 thank you, doing by this I'm able to add fields to form at least.

But is it possible to show certain fields depending on model's attribute value? E.g. if we have **Product** of type1, we show first set of fields, if not - we show another set. For now I cannot see any way to do that inside the `setUp` method.

**Comment by ivanmart** [comment]
BTW, how the mutator should look like? I've tried this:

```
public function setFooAttribute($value)
{
    $this->type1->foo = $value;
    $this->type1->save();
}
```
It works, but it seems a bad idea to save the related model in each mutator. Where would it be better to call this save() method?

**Comment by lloy0076** [comment]
```
    /**
     * Sets the status attribute.
     *
     *
     * @param  $status The status (0 or 1) however true/false will also be
     *                 accepted.
     */
    public function setStatusAttribute($status = 0) {
        $master = $this->masterCustomers()->first();

        if (isset($master)) {
            $master->status = $status ? 1 : 0;
            $result = $master->save();

            return $result;
        } else {
            Log::warning('Unable to find master record.');
        }

        return;
    }
```

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/CRUD/pull/165 - this pull request allows you to hide/show fields depending on a value.

**Comment by ivanmart** [comment]
@lloy0076 thank you again, your answers are very helpful. Could you explain though two things in your mutator example:
1.- what you mean by `if (isset($master))`? The condition will always be true, even if `$this->masterCustomers()->first();` return `false`
2.- so you call `->save()` in mutator, but what if I have about 40 fields and so about 40 mutators? Am I right that each of them will result in separate sql-query like 'update table ... set ... = ..."? It doesn't seem to be the right behavior

**Comment by lloy0076** [comment]
If the model has **not** been saved, `first` returns something that causes `isset` to be true; first seems to be in the BuildsQuery trait and is this:

```
 63     /**
 64      * Execute the query and get the first result.
 65      *
 66      * @param  array  $columns
 67      * @return mixed
 68      */
 69     public function first($columns = ['*'])
 70     {
 71         return $this->take(1)->get($columns)->first();
 72     }
```

Line 71 returns something not defined which makes Laravel itself blow up with a 'using undefined variable' error IIRC.

As for your second point, you are correct.

**Comment by ivanmart** [comment]
@lloy0076 I'm having trouble creating a new record. The mutator fires before the parent model is saved, which results in error "Indirect modification of overloaded property". In your mutator, you only prevent this situation, but how do you actually save the value of a related model when creating a new record?

**Comment by lloy0076** [comment]
@ivanmart - I override the `store` method in the controller instead:

```
        DB::transaction(function() use ($request, &$redirect_location) {
            $redirect_location = parent::storeCrud();

            /*
             * Both these methods morph the model.
             */
            $this->storeMaster($request);
        });

       return $redirect_location;
    }

    /**
     * Stores the master record.
     *
     * @param  $request The request.
     * @return The result of the save.
     */
    protected function storeMaster($request)
    {
        if (! (isset($this->crud->entry) && isset($this->crud->entry->cust_id))) {
            return;
        }

        $master = new Master();

        $data   = [
           // various data values
        ];

        foreach ($data as $check => $default) {
            $value = $request->has($check) 
                ? $request->input($check)
                : $default;

            $master->$check = $value;
        }
        return $this->crud->entry->master()->save($master);
    }
```
