### ISSUE TITLE
Inline error 'destroy' the form design

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#638]
Hi,

When you are using a form with columns, when get error with "show_inline_errors" then it moving the next bottom column from the error message to the right. This is likely because there is no clear: both or no new row.

![2017-04-26 001471](https://cloud.githubusercontent.com/assets/26375917/25422571/8142edbe-2a8b-11e7-9b69-17c2c0fb0ac5.png)

Why I want to keep the 'show_inline_errors' is because of the highlight of the error in the input in red, very convenient mixed with the grouped error at the top.

Right now, I'm forcing use of show_inline_errors but added display none on help-block, to achieve what I want. Very dirty.

Maybe create an option in config crud 'show_grouped_errors_with_highlight' that will remove the inline error but keep errored input highlighte.

![2017-04-26 001472](https://cloud.githubusercontent.com/assets/26375917/25422626/ba6c41ee-2a8b-11e7-8ca9-61df104cbd60.png)

**Comment by MickaelTH** [comment]
@tabacitu That makes sense. Thank you for taking time resolving this issue!

**Comment by MickaelTH** [comment]
@tabacity Sorry closed wrong ticket as you saw ;)

**Comment by tabacitu** [comment]
I think you closed the wrong issue :-) This working on this one, let's leave it open.

Cheers!

**Comment by tabacitu** [comment]
Update: ```show_grouped_errors_with_highlight``` sounds like a reasonable solution to this, so I'll add this to the todo list. If anybody needs this faster and is willing to provide a PR, that would be awesome.

Cheers!

**Comment by tabacitu** [comment]
Let's close this in favour of #1207, which sounds like a cleaner solution.
