### ISSUE TITLE
Undefined variable: action in /resources/views/form_content.blade.php

### ISSUE THREAD

**Issue by isaacperaza** [Laravel-Backpack/CRUD#639]
This bug still happened after version 3.2.7

Was reported in this issue: https://github.com/Laravel-Backpack/CRUD/issues/552

```
Undefined variable: action (View: /home/ubuntu/workspace/vendor/backpack/crud/src/resources/views/form_content.blade.php)

```

I tested with version 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.2.11

I remove laravel views cache, composer cache and I delete vendor/backpack/crud folder before each composer update to test each version.

**Comment by tabacitu** [comment]
Hi @isaacperaza ,

Thanks for the heads-up. But I still think it's a customization issue - nobody else seems to be having the issue. Do you have custom code in your EntityCrudController's ```store()``` or ```update()``` methods? If so, that is definitely where the problem is.

Cheers!
