### ISSUE TITLE
Column type: image

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#64]
An image thumbnail colum should be easy to do. 

Allow developer to customize:
- max width
- max height
(Aspect ratio should be kept)

Click on image should open image in a new tab.

We could make thumbs using Glide: https://packagist.org/packages/league/glide

Any alternatives in mind?

**Comment by OSDDQD** [comment]
Why not Intervention Image?

**Comment by tabacitu** [comment]
Hmm... I may be mistaken, but I think they do separate things:
- You can use Intervention to create thumbnails and store them in your filesystem;
- You can use Glide for on-demand image processing;

In fact, I believe Glide uses Intervention to do all its processing. It's just an API for it, in the form or URL parameters.

**Comment by OSDDQD** [comment]
@tabacitu yeah, my fault.
I read more carefully the documentation package, very cool. Waiting for the new version. My implementation of file fields is not very flexible, have a lot to configure the model class.
- field name
- type (image or file)
- storage dir (or Storage disk)
- size & weight
- field and size for thumb

**Comment by tabacitu** [comment]
Done! Added in https://github.com/Laravel-Backpack/CRUD/commit/f4051759c5e97f46785c7b90cc9627a0b57ad40d. [Documentation here](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#image).
