### ISSUE TITLE
Remove underscores from column names in setFromDb()

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/CRUD#642]
I find myself having to re-write the fields and columns for very basic crud models, just because the titles of the columns have underscores in them.  For instance, this is a model that simply has text fields, so the `setFromDb()` function would be entirely sufficient, but I will need to write all the `addColumns()` and `addFields()` functions in order to remove the underscores:

![screen shot 2017-04-27 at 10 18 30 am](https://cloud.githubusercontent.com/assets/9845442/25490683/2adda65a-2b33-11e7-8646-10a566043d64.png)

Would there be any issues caused by labeling these columns and fields with removed underscores?

**Comment by lloy0076** [comment]
@jsiebach - not for _me_ as such however I wonder if it would be better to refactor the naming of columns and such in `$this->crud->setFromDb()` to something the user could override somehow.

Maybe:

```
public function setFromDb(Callable $name_them = null)
{
  if (! isset($name_them)) {
    // Do what it does now.
    return;
  }

  $name_them(/* whatever parameters would be needed*/);
}
```

@tabacitu might know if there would be issues in other / his own projects.

**Comment by AbbyJanke** [comment]
I use the setFromDB() as is and think changing it all togethervwould be
unhelpful, perhaps add the param like setFromDb($removeUnderscores = false)

**Comment by lloy0076** [comment]
Aye, making a _breaking_ change would be unhelpful however I sense that some will want to keep underscores, some will not want to, others may want to Title Case the columns, others would prefer to have only the first word capitalised and some may want to change every occurrence of "id" to "ID".

Thus, by allowing the user to setup their own callable they can do whatever they want; however by allowing it to be set to `null` (i.e. not set at all) with the default behaviour as it _currently_ stands, avoids breaking all the current deployed code when it upgrades.

**Comment by jsiebach** [comment]
I really like the idea of passing a callable to the function that takes `$columnName` as a parameter and returns the label that should be used for the column and field.  So I could say, for instance:

```
$this->setFromDb(function($columnName){
  return ucwords(str_replace("_", " ", $columnName));
});
```

**Comment by tabacitu** [comment]
I think it's a quick sensible change that will make setFromDb() more useful, yes. Wouldn't a quick change [in this line](https://github.com/Laravel-Backpack/CRUD/blob/master/src/PanelTraits/AutoSet.php#L36) solve it?

I mean:
```diff
-                    'label' => ucfirst($field),
+                    'label' => ucwords(str_replace("_", " ", $field)),
```

I would stay away from replacing id with ID... to prevent converting a column like ```bid``` to ```bID```. Does anybody see a reason not to implement this right now? 

Thanks, cheers!

**Comment by jsiebach** [comment]
@tabacitu I think that would be non breaking and be a good change.  I do however like @lloy0076 solution better - a callable function would let me customize the names of all of my columns, without having to re-write all of the fields and columns.

**Comment by lloy0076** [comment]
Personally I don't think it would have been difficult to implement any of these proposed changes, I see no progress here.

@jsiebach Please re-open if this is important to you.

#688 could fix this.

**Comment by tabacitu** [comment]
Yup, I think #688 is a good fix for this.
