### ISSUE TITLE
Remove "text-lowercase" from content-header

### ISSUE THREAD

**Issue by tswonke** [Laravel-Backpack/CRUD#643]
Please consider removing the "text-lowercase" class from entity name in crud blades.

In German nouns are always written upper case, but I can't define the entity name in CrudController this way because it is changed in the blades.

Creating individual blades for this seems to be too much.

Is the "text-lowercase" necessary? Am I missing something?

**Comment by imcodingideas** [comment]
You can remove it with JavaScript?

**Comment by tswonke** [comment]
I'm sorry, but I don't understand your solution. How am I supposed to use JavaScript for this without defining individual blades?

**Comment by OliverZiegler** [comment]
Is there any concerns removing it?
Any language where we could run into Problems?

I only know german where this is really an issue.
`text-uppercase` for the beginning of the sentences (etc. ) would still be there and make lowercase entity names uppercase. but making uppercase defined names lowercase seems odd to me.

**Comment by tabacitu** [comment]
Totally agreed - I had to recreate the blade files myself a few times, because of this.
@OliverZiegler 's PR fixes this, and I've just merged it into dev - #667 

Cheers!
