### ISSUE TITLE
addField datepicker not working properly

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#644]
Hi,

Not sure if issue with Backpack or AdminLTE but when try to add a date_picker I got this error:

![2017-04-28 001478](https://cloud.githubusercontent.com/assets/26375917/25514666/c23fb6b6-2c08-11e7-881a-53df326d4f1f.png)
![2017-04-28 001477](https://cloud.githubusercontent.com/assets/26375917/25514675/c5f0a446-2c08-11e7-8034-1002a32f0ad8.png)
![2017-04-28 001479](https://cloud.githubusercontent.com/assets/26375917/25514718/fbf008ac-2c08-11e7-9cb9-546ac03e1152.png)

**Comment by lloy0076** [comment]
IIRC you have to include some other JavaScript library - but I've forgotten which one.

**Comment by MickaelTH** [comment]
Ok you saved me. Problem was that I followed doc using "date_picker" type instead of "datetime_picker".

https://laravel-backpack.readme.io/docs/crud-fields#section-date_picker

I changed to "'type' => 'datetime_picker'," and now it's working.

![2017-05-08 001515](https://cloud.githubusercontent.com/assets/26375917/25795782/1d9eadbe-3401-11e7-801a-0c14baf75df9.png)

Thank you
