### ISSUE TITLE
Default value not used when insert in db ?

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#645]
Hi,

I think this is issue with Backpack as I have no problem when insert new object in DB.

The default value is not read when Backpack is inserting in the db and this is throwing error as it cannot be null.
![2017-04-28 001480](https://cloud.githubusercontent.com/assets/26375917/25516154/081e0638-2c13-11e7-87e3-9b6c4a974c10.png)
![2017-04-28 001481](https://cloud.githubusercontent.com/assets/26375917/25516160/0ff3eecc-2c13-11e7-95c8-90a353d873cc.png)
![2017-04-28 001482](https://cloud.githubusercontent.com/assets/26375917/25516161/0ff6f59a-2c13-11e7-9509-86353c6f2596.png)
![2017-04-28 001483](https://cloud.githubusercontent.com/assets/26375917/25516162/0ff7795c-2c13-11e7-8377-d94a7bb479eb.png)
![2017-04-28 001484](https://cloud.githubusercontent.com/assets/26375917/25516163/0ffb4db6-2c13-11e7-8a69-0f95010b0503.png)

**Comment by lloy0076** [comment]
What's the DB SQL's default value got to do with Backpack?

**Comment by lloy0076** [comment]
(and no - the database's view of what is default is irrelevant here - if there **is** a bug it would be that backpack or crud is overriding that with something you don't expect)

**Comment by victorlap** [comment]
The default value from SQL is used only when you don't specify the column in the insert statement. When you try to set it to null, you do specify a value.

**Comment by MickaelTH** [comment]
Ok guys be patient with me here lol.

When I insert with tinker it's working fine, but when I use the CRUD edit view then I got this error which based on @victorlap is normal because Backpack does not check is a default value exist and just but empty.

So I assume Backpack should check if default value is set then either not add it in the SQL INSERT or add it with the default value?

**Comment by lloy0076** [comment]
@MickaelTH - is this still happening?

**Comment by MickaelTH** [comment]
@lloy0076 Yes it is still happenning but after 4 months playing with Backpack I do understand your previous comments.

So I will close this issue because, yes when a field is declared with no value it is set to null. To avoid this, just make sure the validations rules request are set accordingly, or in my case overwrite the request value just before save/update in the CRUD controller.
