### ISSUE TITLE
Entities name in table instead of id

### ISSUE THREAD

**Issue by bretanac93** [Laravel-Backpack/CRUD#648]
Hey guys, I have an issue here, I have an entity that contains relationships only, and I need to show in the table generated by backpack crud another field of the entity instead of the id, check it out in the picture below:

![18176222_871440352996069_849503416_o](https://cloud.githubusercontent.com/assets/3768876/25541685/9d69b4d0-2c1d-11e7-9e61-83c8d76aef93.png)

See how it shows the id in the columns instead of the name which is the field I want to show there, is there any way to do that?, thanks in advanced.

Cheers

**Comment by tswonke** [comment]
You can use a select column, see https://laravel-backpack.readme.io/v3.0/docs/crud-columns-types

**Comment by vekost** [comment]
@tswonke, I did what you suggested without luck. I added a field entry in my Controller which successfully lists all the records of a column containing names, during the creation of a new item or the edit of an existing one through Backpack's CRUD. However, after choosing one and saving, I receive the same functionality as described in @bretanac93 post, which is the automated display of this record's id and not its selected name. I then added a column entry in my Controller pointing to a function inside my Model, which is used to retrieve the name of this column using the Query Builder of Laravel without success...Any further help would be appreciated.

@bretanac93, may you have found a solution to this problem?

**Comment by tabacitu** [comment]
Hi @bretanac93 ,

I'm afraid you can only create CRUD panels when your main table has an ID (or other type of primary column). Hope it helps.

Cheers!

**Comment by Butthry-GDNT** [comment]
Can you just give us a small example?

**Comment by tabacitu** [comment]
@Butthry-GDNT this example should take you through the core Backpack features: https://laravel-backpack.readme.io/docs

**Comment by johnlewissims** [comment]
Any updates on this? I'm experiencing the same iss as @bretanac93 on this project.  I've also tried adding the column type with no luck.

**Comment by tabacitu** [comment]
@johnlewissims I can confirm [the "select" column type](https://backpackforlaravel.com/docs/3.6/crud-columns#select) correctly shows an attribute on a related Eloquent model. You must not be using it correctly. Make sure that your relationships are correctly defined, and use the column according to the documentation.
