### ISSUE TITLE
enum field type doesn't work with non-default database connection

### ISSUE THREAD

**Issue by DelightedD0D** [Laravel-Backpack/CRUD#649]
**Migration setup**
 _note that this uses my `maestro` connection which is NOT my default connection:_
```
Schema::connection('maestro')->create('automated_report', function (Blueprint $table) {
        $table->increments('id')->comment('A unique Id to identify this row.');
        $table->enum('status',['active','inactive']);
});

```
**Crud controller:**

```
class AutomatedReportCrudController extends CrudController
{
    public function setup()
    { 
        $this->crud->setModel(AutomatedReport::class);
        $this->crud->setEntityNameStrings('Automated Report', 'Automated Reports');
        $this->crud->setRoute(config('backpack.base.route_prefix').'/automated_report');


        $columns = [
            [
                'name'  => 'status',
                'label' => 'Status',
                'type'  => 'text',
            ]
        ];
        $this->crud->addColumns($columns);

        $fields = [
            [
                'name'  => 'status',
                'label' => 'Status',
                'type' => 'enum'
            ]
        ];
        $this->crud->addFields($fields);

    }

    public function store(StoreRequest $request)
    {
        return parent::storeCrud();
    }

    public function update(UpdateRequest $request)
    {
        return parent::updateCrud();
    }
}
```

When I attempt to add or edit a record, I get the below error:

>PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asapps.automated_report' doesn't exist 

The error shows the it's trying to use my default connection, `asapps.automated_report` instead of the proper `maestro.automated_report`

I was able to fix this by updating `getPossibleEnumValues()` to use `$instance->getConnectionName()`

Pull request to follow.

**Comment by DelightedD0D** [comment]
I'm not sure how to make a pull request, but this is how I fixed the issue:

In `CrudTrait` I updated this function:

```
    public static function getPossibleEnumValues($field_name)
    {
        $instance = new static(); // create an instance of the model to be able to get the table name
        $type = DB::select(DB::raw('SHOW COLUMNS FROM `'.$instance->getConnectionName().'`.`'.Config::get('database.connections.'.env('DB_CONNECTION').'.prefix').$instance->getTable().'` WHERE Field = "'.$field_name.'"'))[0]->Type;
        preg_match('/^enum\((.*)\)$/', $type, $matches);
        $enum = [];
        foreach (explode(',', $matches[1]) as $value) {
            $enum[] = trim($value, "'");
        }

        return $enum;
    }
```

**Comment by lloy0076** [comment]
@DelightedD0D - to make a pull request:

- Navigate to the file you want to change
- Click on the file's name so that you can see the contents of the file in your browser history
- Click on the "Pen" or "Edit" icon (it's to the left of the trash can)

Make whatever change you'd like to suggest and refer to this issue in the description (just copy paste the link https://github.com/Laravel-Backpack/CRUD/issues/649).

**Comment by DelightedD0D** [comment]
@lloy0076  Perfect, thank you!

https://github.com/Laravel-Backpack/CRUD/pull/650

**Comment by tabacitu** [comment]
Hi @DelightedD0D ,

Thanks for the PR. Let's continue the conversation there.

Cheers!
