### ISSUE TITLE
Fake field not loading when stored in a field not called extras

### ISSUE THREAD

**Issue by mariavilaro** [Laravel-Backpack/CRUD#651]
Fake fields are saving ok in database, but if the field is called anything other than "extras", the info is not loaded when showing the form. This is the code that is not working ok:

    $this->crud->addFields([
        [
            'name'  => 'name',
            'label' => 'Name',
        ],
        [
            'name'      => 'validation',
            'label'     => 'Validation rules',
            'type'      => 'radio',
            'options'   => [ 
                                '4_digits' => '4 digits',
                                'cif' => 'CIF',
                                'email' => 'Email',
                                'date' => 'Date'
                            ],
            'fake'      => true,
            'store_in'  => 'extra'
        ],
        [
            'name'      => 'limit',
            'label'     => 'Character limit',
            'fake'      => true,
            'store_in'  => 'extra'
        ]
    ]);

**Comment by AurelDragut** [comment]
Add the second fake field here:
```
protected $fakeColumns = ['extras','second_field'];
```
