### ISSUE TITLE
How to add actions under Actions

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#652]
In admin/page shows open, edit and delete under Actions.
I am wondering how I can add a new action button which link to another admin page.

Currently I am overriding resources/views/vendor/backpack/crud/list.blade.php. But I think there must be a better way. 

![screen shot 2017-04-30 at 10 36 14 am](https://cloud.githubusercontent.com/assets/147320/25560513/e89b426a-2d90-11e7-9208-5ec768f21ddc.png)

**Comment by iMokhles** [comment]
i'm using this in my project
[Documentation](https://laravel-backpack.readme.io/docs/crud-buttons) 

```
In My DocumentCrudController
        $this->crud->addButtonFromModelFunction('line','approve_document', 'getApproveButtonHtml', 'beginning');
        $this->crud->addButtonFromModelFunction('line','review_document', 'getReviewButtonHtml', 'beginning');
```

```
In My DocumentModel
public function getReviewButtonHtml()
    {
        return '<a data-button-type="review" title="Review" href="'. url('admin\document\review?document_hash='. $this->document_hash) .'" class="btn btn-xs btn-danger"><i class="fa fa-flag-checkered"></i> review</a>';
    }
    public function getApproveButtonHtml()
    {
        return '<a data-button-type="approve" title="Approve" href="'. url('admin\document\approve?document_hash='. $this->document_hash) .'" class="btn btn-xs btn-success"><i class="fa fa-check-circle"></i> approve</a>';
    }
```

in my example i use a simple action to verify and review documents,
so you can use the same for your needs also

**Comment by shinokada** [comment]
@iMokhles: Thanks.
