### ISSUE TITLE
Rewrite eloquent-sluggable adaptor and fake fields

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#654]
I knew there must be a better way to handle JSON columns. [This looks like a really good one](http://www.laragle.com/2017/04/laravel-mysql-json-manager.html?utm_campaign=digest&utm_medium=email&utm_source=app&m=1).

We could use it to simplify the way JSON columns are used in:
- fake fields
- translatable fields usong eloquent-sluggable
- fake translatable fields

**Comment by tabacitu** [comment]
test

**Comment by lloy0076** [comment]
Is that MySQL specific?

**Comment by tabacitu** [comment]
Doesn't look like it. It's called MySQLManager, but it uses Eloquent everywhere - so it should work for PosgreSQL and others too.

**Comment by lloy0076** [comment]
Please re-open if this is still relevant.

**Comment by tabacitu** [comment]
I think this is an important refactoring, but yes, it's not urgent so I agree to closing it.

/remind me to open this issue again in 2 months

**Comment by tabacitu** [comment]
Also:

/remind me to check if reminders work in 5 minutes

:-)
