### ISSUE TITLE
Add Laravel Events support

### ISSUE THREAD

**Issue by jsvini** [Laravel-Backpack/CRUD#660]
Would be very nice if the CRUD fired events like the [Auth](https://laravel.com/docs/5.4/authentication#events) module, so we could attach listeners to do extra work after creating/updating/deleting an item, that we don't want to mix in the CrudController.

ie: when you run `php artisan backpack:crud order` the following events would be created:

> OrderCreatedEvent.php
> OrderUpdatedEvent.php
> OrderRemovedEvent.php

and the constructor of those events would receive the item `id` from `$model->getKey()`

just a proposal :)

**Comment by OliverZiegler** [comment]
You could just fire your events in your CRUDControllers store/update/destroy method as you like. I don't think this is really necessary for every model. And additionally you could have pre- and post- create/update/delete events.

See also [#51](https://github.com/Laravel-Backpack/CRUD/issues/51#issuecomment-230521706)

```PHP
public function store(StoreRequest $request)
    {
        // <---------  here is where a before_insert callback logic would be
        $response = parent::storeCrud();
        // <---------  here is where a after_insert callback logic would be
        return $response;
    }

    public function update(UpdateRequest $request)
    {
        // <---------  here is where a before_update callback logic would be
        $response = parent::updateCrud();
        // <---------  here is where a after_update callback logic would be
         return $response;
    }
```

**Comment by tabacitu** [comment]
Hi @jsvini ,

I think I agree more with @OliverZiegler on this one. My thoughts:

PROs:
- more laravely

CONs:
- it would create many files
- there are already 2 ways to do this (using the existing events on the model, and in the controller)

Anyone else - thoughts on this?

**Comment by lloy0076** [comment]
Were something like this to be made, I'd take a look at how Eloquent models already implement their 'generic' events see (the source)[https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php].

Were it implemented like this, we'd not have to generate all the Event classes unless the developer wanted to.
