### ISSUE TITLE
How to customize forms and views?

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/CRUD#661]
How to make a very custom form?

Is it possible to override some views?

Is it possible to use fields outside the crud?

**Comment by AbbyJanke** [comment]
I am unsure what you are looking for in regards to making a very custom form? You are able to define all aspects of the fields when adding them via your controller; including wrappers which could be used to "pull-left" etc.

As for overriding views, This is something I was just looking into myself and found that as of last month it is possible with v3.2 like so pull #334:

```
$this->crud->setListView('your-view')
$this->crud->setEditView('your-view')
$this->crud->setCreateView('your-view')
$this->crud->setShowView('your-view')
$this->crud->setReorderView('your-view')
$this->crud->setRevisionsView('your-view')
$this->crud->setRevisionsTimelineView('your-view')
$this->crud->setDetailsRowView('your-view')
```

Also with those being the main one there are a few aliases:


```
setPreviewView() -> setShowView()
setUpdateView() -> setEditView()
```

You are able to define those within the `setup()` or `__construct()` function depending on how you choose to set your model, route name, etc.

Using the fields outside of CRUD is from my understanding not likely as it is built into the core of the CRUD functionality. But you may have luck if you look into the `CrudPanel.php` file.

**Comment by eduardoarandah** [comment]
@AbbyJanke I have this in mind:

Example: I want to CRUD a cities table. 
Everything is fine, except for the list view, I need to customize it (more than it is allowed via controller parameters)

it would be great to do something like this:

`php artisan backpack:view cities list`

and it would copy the built-in list template to resources/cities/list 

Then, all it takes is to customize that file and that's it!

**Comment by AbbyJanke** [comment]
Hi @eduardoarandah that's where `$this->crud->setListView('your-view')` comes in handy, you can make your view file, while its not automatic its not too hard to make a file, put the `setListView` in your `setup()` and you just customize that file. If you want to use the default list view as a starter base you can grab it from `src/resources/views/list.blade.php` in the repository. That's what I am doing as I want to do have a tabbed list view.

**Comment by eduardoarandah** [comment]
@AbbyJanke ok thanks, I'll try and maybe share source code for happy copypasting

**Comment by sdebarun** [comment]
@AbbyJanke Thanks for the heads up, it really worked like charm. Though I have not used all of them but setListView works perfect.
