### ISSUE TITLE
Search button option

### ISSUE THREAD

**Issue by eescalante** [Laravel-Backpack/CRUD#663]
I like the filter solution implemented in the backpack, but some users tell me that when multiple filters are applied the page is frozen with each selected filter or when it is typing a search.

Are there any way to fire search action by a search button for example?

That is: clicking all the requested filters and/or search term and fire the search after that.

Best regards.

**Comment by tabacitu** [comment]
Hi @eescalante ,

Seems like there are solutions to do that in DataTables. Check out this [stackoverflow reply](https://stackoverflow.com/questions/33271512/remove-auto-search-from-text-box-and-search-upon-search-button).

I'm very interested in the "frozen page" issue - how did that happen? Were you able to replicate it? How many rows are in that CRUD? Did you use ajaxDataTables?

Cheers!
