### ISSUE TITLE
BUG : Fake fields optional in model translatable

### ISSUE THREAD

**Issue by Jimmylet** [Laravel-Backpack/CRUD#664]
Hello,

I just noticed a rather annoying bug with Backpack and I would like to know what to do to remedy it.
I define fake fields in my controller.

```php
$this->crud->addField
        ([
            'name' => 'facebook',
            'label' => 'Facebook',
            'type' => 'url',
            'fake' => true,
            'store_in' => 'extras',
            'tab' => 'Réseaux sociaux'
        ]);
        $this->crud->addField
        ([
            'name' => 'twitter',
            'label' => 'Twitter',
            'type' => 'url',
            'fake' => true,
            'store_in' => 'extras',
            'tab' => 'Réseaux sociaux'
        ]);
```

I create my model file

```php
class Teacher extends Model
{
    use CrudTrait;
    use Sluggable;
    use HasTranslations;
    
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */
    
    protected $table = 'teachers';
    protected $primaryKey = 'id';
    public $timestamps = true;
    // protected $guarded = ['id'];
    protected $fillable = [
        'slug',
        'lastname',
        'firstname',
        'title',
        'role',
        'description',
        'picture',
        'email',
        'social',
        'status',
        'extras'
    ];
    // protected $hidden = [];
    // protected $dates = [];
    protected $fakeColumns = ['extras'];
    protected $translatable = ['role', 'description'];
```

And when I save without filling fake fields, I have a SQL error.
<img width="963" alt="capture d ecran 2017-05-07 a 18 45 47" src="https://cloud.githubusercontent.com/assets/17065517/25783032/75a15d4c-3355-11e7-9d4b-6d5134175259.png">

It works when I remove the translation functionality on the model.

Can you help me ? Thank you

**Comment by tabacitu** [comment]
Hi @Jimmylet ,

What version of Backpack\CRUD are you running on? Does a ```composer update``` fix it?

Thanks!

**Comment by Jimmylet** [comment]
Hello @tabacitu , Thank you for taking the time to answer me :)

I use Backpack/CRUD 3.2.0. 

I made a composer update, but nothing changes. I still have the same mistake.

I have a false field non-translatable (links to social networks) but as soon as I send a blank, it puts me a SQL error.

**Comment by AurelDragut** [comment]
@Jimmylet, if i got it right, you wanna translate a fake field, which is not posible yet as far as i know, and it seems that when you set the `twitter` field as translatable it looks for it in the columns list instead of decoding it's value from the `extras` field.

**Comment by Jimmylet** [comment]
@AurelDragut, thank you for your response. But no, I don't want my extras field to be translatable. This is what I did in my model, but if I do not send any value, it puts an error. (The template is translatable, but not the extras field)

**Comment by AurelDragut** [comment]
Well the fields after the `updated_at` (in the SQL error) should not have appear in the query that way (they weren't considered fake). Something is quite strange there.

**Comment by Jimmylet** [comment]
@AurelDragut , Yes, it's really when I do not fill the field, if I fill it up, it works.

**Comment by AurelDragut** [comment]
Where does it save the field value when you fill it up?

**Comment by Jimmylet** [comment]
@AurelDragut , The value is saved in the "extras" column in my DB, as it should be. But if I do not fill in anything, that bug.

**Comment by petert0th** [comment]
Hey,
Facing the same problem, and i also think that the "translation handler stuff" messes up the extra fields when empty, double checked, and thats the only difference between the backpack pages demo and our code.

**Comment by Jimmylet** [comment]
Hello @tabacitu , have you been able to reproduce the problem? I like the idea of being able to store a lot of fields in a single column (notably those related to SEO).

**Comment by dinghua** [comment]
@Jimmylet I meet the same problem, if I use HasTranslations trait, the create and update function will be overwrite, and the new function does not handle guarded and fillable property.

**Comment by tabacitu** [comment]
Hi guys. Just fixes this on ```dev```. It will be available on ```master``` shortly. I'll close the issue, please let me know it this doesn't fix it for you.

Cheers!
