### ISSUE TITLE
Which file to modify in order to display image under name or title column

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#670]
Hi,

I'd like to display images rather than file name or title.

But I am not sure which file to modify.

**Comment by AbbyJanke** [comment]
Your best option is going to be create a mutator within your Model. 

[Defining A Mutator](https://laravel.com/docs/5.4/eloquent-mutators#defining-a-mutator)

I would do something like `getImageDisplayAttribute` then you can call `$model->image_display` but still have the filename/title available if you need it elsewhere.

Within the mutator you can just have it return the full url string.

Example (if you store them within the public path):

```
public function getImageDisplayAttribute() {
   $fileName = $this->attributes['image'];
   $pathway = public_path().'/uploads/'; // change this line based on where its stored

   $before = '<img src="';
   $after = "' alt="'.$fileName.'" />

   return $before.$pathway.$filename.$after;
}
```

It should come out looking something like this `<img src="path_to_image" alt="filename" />`

**Comment by shinokada** [comment]
Thanks Abby,

When I add any html in return, I get nothing returned.

**Comment by shinokada** [comment]
I ended up like this.

Creating a mutator suggested by Abby;

```
    public function getNameAttribute() {
        $fileName = $this->attributes['name'];
        $pathway = Storage::url($this->center_id.'/'.$fileName); 
        $before = '<img src="';
        $after = '" alt="'.$fileName.'" style="width:128px;" />';
        return $before.$pathway.$after;
    }

```

In my controller index using my view.

 `       return view('crud::myview', $this->data);`


I created resources/views/vendor/backpack/crud/myview.blade.php and copied [list.blade.php](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/list.blade.php) and modified around line 54.

```
            <tbody>
                @foreach ($entries as $k => $entry)
                <tr data-entry-id="{{ $entry->getKey() }}">

                  @if ($crud->details_row)
                    @include('crud::columns.details_row_button')
                  @endif

                  {{-- load the view from the application if it exists, otherwise load the one in the package --}}
                  @foreach ($crud->columns as $column)
                    @if (!isset($column['type']))
                       @if($column['name'] == 'name')
                         @include('crud::columns.image')
                       @else  
                        @include('crud::columns.text')
                       @endif
                    @else

```


resources/views/vendor/backpack/crud/columns/image.blade.php

{{-- regular object attribute --}}
<td>{!! $entry->{$column['name']} !!}</td>

**Comment by shinokada** [comment]
Well my solution was not useful at the end. Whenever I use name attribute, it returns with img tag etc.

So I delete the mutator and modified the Creating a resources/views/vendor/backpack/crud/columns/image.blade.php.

```
{{-- regular object attribute --}}
<td><img src="{!! Storage::url($entry->center_id.'/gallery/'. $entry->name) !!}" alt="{{ $entry->name  }}" style="width:128px" /></td>

```
