### ISSUE TITLE
[Request] IMBaaS ( is open source Backend as a service ) built with laravel

### ISSUE THREAD

**Issue by iMokhles** [Laravel-Backpack/CRUD#672]
hi all, i'm building this project and wanna know if anyone interesting to help me developing this project 

here's the link
https://github.com/IMBaaS/IMBaaS

i'm planing to make the dashboard / admin panel using Laravel-Backpack packages.
 don't have a lot to say just need to make parse alternative in PHP with more advanced options

thanks in advance

**Comment by tabacitu** [comment]
Hi @iMokhles ,

The link doesn't seem to work for me. What do you mean, could you please expand?

Cheers!

**Comment by iMokhles** [comment]
sorry here's the new link
https://github.com/iMokhles/IMBaaS
