### ISSUE TITLE
table field last row standing

### ISSUE THREAD

**Issue by antverse** [Laravel-Backpack/CRUD#673]
Hi, I added a table field to my crud. it works okay but I can not remove last line. It says modified succesfully but not. how can i fix this. Codes I am using exact copy of documentation.

**Comment by antverse** [comment]
I fixed the problem by adding by adding 1 line to removeItem function in my custom table field' s view
`$scope.removeItem = function (item) {
                var index = $scope.items.indexOf(item);
                $scope.items.splice(index, 1);
                $scope.field.val(angular.toJson($scope.items));
            }`

**Comment by lloy0076** [comment]
I can't tell if there is still an issue here - if there is please reopen?
