### ISSUE TITLE
Pagination page size issues

### ISSUE THREAD

**Issue by jsiebach** [Laravel-Backpack/CRUD#674]
When I load the index view, the page size says "Showing 1 to 025 of XX".  Then when I click the next page button, it shows me 25-XXX (all of them on one page).  In order for the page size to actually show 25, I have to toggle the dropdown to 10 and then back.

I have tried adding `setDefaultPageLength` but it didn't help.  When i set default to 10, it showed "Showing pages 1 to 010" and did the same thing.

![screen shot 2017-05-10 at 4 32 00 pm](https://cloud.githubusercontent.com/assets/9845442/25923697/5ddfff96-35a4-11e7-8194-6f475f40bce5.png)

![screen shot 2017-05-10 at 4 32 10 pm](https://cloud.githubusercontent.com/assets/9845442/25923704/60834a5a-35a4-11e7-8ea1-9c8c32c8db04.png)

**Comment by tabacitu** [comment]
Damn. I think it might be related to this PR I merged: https://github.com/Laravel-Backpack/CRUD/pull/596/files . 

Can you please confirm that removing the quotes from your ```layout.blade.php``` fixes it for you too?

**Comment by jsiebach** [comment]
Yep, this fixed it.  I'll close the issue and over-ride this file for now until it's merged

**Comment by lloy0076** [comment]
I got thumped by this just then too :(

**Comment by tabacitu** [comment]
Hi guys,

Just published the fix - Backpack 3.3.12 has this solved, so a ```composer update``` should fix it. 

I'll try to turn this into a learning moment for Backpack: _even small code changes can have an impact you can't fully predict or test by yourself_. I'll try to ask for a few reviews before I merge anything into ```master```, from now on.

Cheers!
