### ISSUE TITLE
Field type: array

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#68]
- The value is stored as a json in the db: ```{"a":1,"b":2,"c":3,"d":4,"e":5}```;
- The user can add/edit/remove multiple array entries; 
- The entries are stored in a hidden input, then saved to the db;
- The field should probably look something like this:

================= [ - remove ]
================= [ - remove ]
================= [ - remove ]
[ + add new item ]

It would work GREAT with the new 'array' column type.

Possible issues:
- what if the user only edits this, then does not focus out of the field and just clicks "save"? maybe the hidden input should be saved on each key stroke...

**Comment by OwenMelbz** [comment]
I've done some bits like this before, so should be able to pick it up, I'm thinking maybe to get angularjs packaged with the app, which will allow us to write cleaner field/column code, especially things like this

**Comment by tabacitu** [comment]
Ehm... I don't know... right now Backpack doesn't require you to know any JS frameworks to completely understand and customize it. And I personally think that's a plus. Because:
- other people might prefer Vue.js;
- [a lot of Backpack users are beginners/intermediates in Laravel](https://infinit.io/_/eMQtbt8); I assume most don't know Angular either and if they also need to learn that, the learning curve would be even bigger;

I say, let's wait for more stuff to need Angular before we decide we need it. The functionality above can be done using jQuery too, but I do understand what you're saying - it definitely won't be as clean...

**Comment by OwenMelbz** [comment]
I would expect the users to have to know angular, they would still configure it via the attributes within the crud controller, they wouldn't ever know what was under the hood unless they dived in.

The main reason for this suggestion for this request is the repeatable functionality you'd get very easily and quickly

**Comment by tabacitu** [comment]
Yeah, I understand, but I don't find this a complex functionality at all to code using jQuery, it's just a "clone". Let me sleep on it, I may be oversimplifying it in my head now :-)

We also need to take [this future functionality](https://github.com/Laravel-Backpack/CRUD/issues/131) into account when making a decision about this.

**Comment by OwenMelbz** [comment]
I've added a pull request in for this as I needed the functionality today anyway :) https://github.com/Laravel-Backpack/CRUD/pull/132
