### ISSUE TITLE
remove column and not fetch field 

### ISSUE THREAD

**Issue by aliromero** [Laravel-Backpack/CRUD#681]
hi , im used : 
` 
$this->crud->removeColumn('latitude'); 
`
then, not fetch query field **latitude** from my model for showing to list: 

**my Controller** 

`
$this->crud->removeColumn('latitude');
$this->crud->addButtonFromModelFunction('line', 'map', 'getMapButton', 'beginning');
`

**my Model**

`
 public function getMapButton()
    {
        return '<a class="btn btn-default btn-xs" href="http://maps.google.com/maps?q='.$this->latitude.','.$this->longitude.'" target="_blank"><i class="fa fa-map-marker"></i> show location</a>';
    }
`

$this->latitude = return null

**Comment by iMokhles** [comment]
here's my answer on my issue, it should work for you to get latitude value

https://github.com/Laravel-Backpack/CRUD/issues/598#issuecomment-292815100

**Comment by aliromero** [comment]
thank you for help 👍
