### ISSUE TITLE
How to add new size for thumbnails

### ISSUE THREAD

**Issue by DimasOdessa** [Laravel-Backpack/CRUD#682]
Hi there!
I need upload images with 3 different thumbnails sizes.
For example I upload image and now I get one thumbnail (48x48px), and I want to have 3 sizes:
100x100px, 300x300px, 600x600px. 
How can I do this? Help me please.

**Comment by tabacitu** [comment]
Hi there!

Sure, backpack doesn't do that by default, but you should be able to easily do that. If you're using the UPLOAD or UPLOAD_MULTIPLE field types, you should have a mutator on your model that _actually stores_ the filename in the db and file on the disk. You can add your thumbnail logic there. I suggest you use the Intervention/Image package for creating the thumbnails, I find it excellent.

Hope it helps. Cheers!

**Comment by DimasOdessa** [comment]
Thank you!
