### ISSUE TITLE
Problems with AddField in getting a record with condition

### ISSUE THREAD

**Issue by eddilou** [Laravel-Backpack/CRUD#686]
You need additional options for the AddField, for example, an option where
The problem is this: there is a table
Category
-id
-name
-parent_id
This table will also be used for subcategories
The model already specifies the conditions of the parent and children
I can not get to addField all categories with parent_id = 0 for select
Instead, it issues ALL entries

**Comment by lloy0076** [comment]
Apologies, @eddilou , but I honestly can't quite figure out what you mean.

Which field type are you commenting on, if any field type at all?

Do you mean you can't alter the query for the entire model (I don't think you do?).

**Comment by AurelDragut** [comment]
@eddilou you need to make another relationship by extending the current one
`
public function parentCategories() {
    return $this->categories()->where('parent_id',0);
`
or something like this... and use that relationship in the select

**Comment by eddilou** [comment]
@lloy0076, @AurelDragut  In AddField does not work type model_function like for example in columns 
`[
   // run a function on the CRUD model and show its return value
   'label' => "URL", // Table column heading
   'type' => "model_function",
   'function_name' => 'getSlugWithLink', // the method in your Model
]`
When I set the select type, I can not specify the conditions for this select or specify which function to use, because in the template select.blade.php specifies the receipt of all records of the specified model
` @foreach ($field['model']::all() as $connected_entity_entry)`

**Comment by AurelDragut** [comment]
No, i think you got it all wrong, the 'select' field type requires a relationship based on which it generates its options. If you add a select with 'categories' as relationship where 
`public function categories() {
    return $this->belongsToMany(App\Models\Categories::class);
}`
it will return to you all the categories, but if you add 
`public function categories() {
    return $this->belongsToMany(App\Models\Categories::class);
}
public function parentCategories() { 
    return $this->categories()->where('parent_id',0);
}`
and set 'parentCategories' in the 'select' you will get only the categories with parent_id = 0.

**Comment by eddilou** [comment]
@AurelDragut Well, I'll try tomorrow, I tried on Friday, but there were some difficulties, maybe not so indicated relationship

**Comment by lloy0076** [comment]
Ah, yes - there's nothing stopping one from adding extra where, select and other clauses to a relationship to a plain old Eloquent model :)

**Comment by eddilou** [comment]
@AurelDragut I checked, and still does not work, here look in the model Categories have functions
```
public function parent()
    {
        return $this->belongsTo('App\Models\Category', 'parent_id')->where('parent_id',0);
    }
    public function children()
    {
        return $this->hasMany('App\Models\Category', 'parent_id')->where('parent_id','<>', '0');
    }
```
In addField I write
```
         $this->crud->addField(
             [  // Select2
                 'label' => "Category",
                 'type' => 'select',
                 'name' => 'parent_id', // the db column for the foreign key
                 'entity' => 'parent', // the method that defines the relationship in your Model
                 'attribute' => 'name', // foreign key attribute that is shown to user
                 'model' => "App\Models\Category", // foreign key model
             ], 'update/create/both')->beforeField('name');
```
at the input of editing shows ALL records and not only parent
In the AddColumnI write also all works

**Comment by osantelices** [comment]
I have the same problem
any solution?

**Comment by osantelices** [comment]
@eddilou I go write on spanish my solution for this problem

He creado una nueva vista en resources/views/vendor/backpack/crud/fields y en mi caso la he llamado contacts

luego al crear el addField lo hice de esta manera 
$this->crud->addField(
			 [
			   // 1-n relationship
			   'label' => "Contacts", // Table column heading
			   'type' => "contacts",
			   'name' => 'contacts', // the column that contains the ID of that connected entity;
			   'entity' => 'contacts', // the method that defines the relationship in your Model
			   'attribute' => "name", // foreign key attribute that is shown to user
			   'model' => "App\Models\Contact", // foreign key model
			   'pivot' => true,
			]
		);
y luego en la vista he tomado los datos de la vista llamada select2_multiple.blade.php y he cambiado los datos desde ahi en la linea 12

 @foreach ($field['model']::all() as $connected_entity_entry)
a
 @foreach ($field['model']::where('type_contact_id', 3)->get() as $connected_entity_entry)

y listo ha funcionado para mi, espero también funcione para ti

**Comment by eddilou** [comment]
@osantelices Hi, I decided to abandon this idea and did it, but with the flags, because this select has some problems

**Comment by tabacitu** [comment]
Hi @eddilou . I think if we add scopes to the relation fields, you use case will be covered. Right?

Please check out https://github.com/Laravel-Backpack/CRUD/issues/806 and tell me if this is what you're looking for. If so, we can close this issue and move the conversation there, towards how to implement it.

Cheers!
