### ISSUE TITLE
How to remove pagination

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#690]
In [this doc](https://laravel-backpack.readme.io/docs/crud-full-api), I am not able to find how to remove pagination. 

Is there any way to remove the pagination?

![screen shot 2017-05-21 at 8 35 42 am](https://cloud.githubusercontent.com/assets/147320/26280021/8cfabe60-3e00-11e7-929e-703b2bcd86d6.png)

**Comment by AurelDragut** [comment]
` $(document).ready( function () {
     $('#example').dataTable( {
       "bPaginate": false
     } );
   } );`

**Comment by shinokada** [comment]
@AurelDragut Thanks. 

It will be nice to have `$this->crud->removePagination()` or `$this->crud->disablePagination()` method.

**Comment by AurelDragut** [comment]
I don't know if it's worth making a trait for it. You can just add a condition in the list.blade.php file to filter when to use pagination or not.

**Comment by tabacitu** [comment]
Hi guys,

This is the first time I hear about someone wanting to remove pagination. And since it's such a simple modification, I don't think there should be an official method for this. I'll leave the thread empty in case public opinion is different.

Cheers!

**Comment by Spodnet** [comment]
I disable pagination for lists I want to see the whole tree for. An example are pages, I want the list to represent the whole navigation, the pages are indented to indicate depth, so having paged lists looks odd, as some are indented and some not, if you can't see the parent it looks broken.

I simply added a property to crud called disablePagination, and set it to true when I need to, in the list blade, it then does:

`
@if ($crud->disablePagination)
        	  "bPaginate": false,
 @endif
`

99% of the time I don't see a need for it though, but possibly useful to have.

**Comment by AurelDragut** [comment]
Right now we have 10, 25, 50, 100 as options for the number of items on a page and what you need seems to be an option to set an 'all' as default on custom lists.

**Comment by lloy0076** [comment]
This:

> Right now we have 10, 25, 50, 100 as options for the number of items on a page and what you need seems to be an option to set an 'all' as default on custom lists.
> And while 'all' is selected the pagination div should be hidden

...seems to be a new feature :).

**Comment by raiika** [comment]
come across to this,
and applied @Spodnet and @AurelDragut solution which is awesome

datatables_logic.blade.php

               "<'row mt-2 d-print-none '<'col-sm-12 col-md-4'l><'col-sm-0 col-md-4 text-center'B><'col-sm-12 col-md-4 'p>>",
    +      @if ($crud->getDefaultPageLength() === -1)
    +      bPaginate: false,
    +      @endif
       }    

       
        
and you could do something like this in the Controller::setupListOperation()

        CRUD::setDefaultPageLength(-1);
