### ISSUE TITLE
Delete image when post deleted

### ISSUE THREAD

**Issue by adnanfajr** [Laravel-Backpack/CRUD#692]
How to delete image file from server when post is deleted?
Where to use function : File::delete($filename)

**Comment by lloy0076** [comment]
@adnanfajr - you've seen the docs here:

https://laravel-backpack.readme.io/docs/crud-fields#section-image

??

**Comment by tabacitu** [comment]
Hi there,

I trust @lloy0076 's link will solve your issue. Take a closer look at the documentation for this field ;-) happens to all of us.

Cheers!

**Comment by adnanfajr** [comment]
Wow thanks, sorry I do not see that documentations :)
@lloy0076 @tabacitu
