### ISSUE TITLE
Integrate custom view in laravel's backpack crud

### ISSUE THREAD

**Issue by amipax** [Laravel-Backpack/CRUD#693]
I want to integrate a custom view to be able to use the Crud package Api, for example, $this->crud->enableExportButtons();

In ReportCrudController every function use different Models, each function is called through custom routes. but the Crud Api is not available. 

Controller

```php
      <?php

    namespace App\Http\Controllers\Admin;

    use Backpack\CRUD\app\Http\Controllers\CrudController;
    // VALIDATION: change the requests to match your own file names if you need form validation
    use App\Http\Requests\TagCrudRequest as StoreRequest;
    use App\Http\Requests\TagCrudRequest as UpdateRequest;

    use Illuminate\Http\Request;
    use App\Http\Controllers\Controller;
    use App\Estacion;
    use App\Importacion;
    use App\Equipo;
    use App\Parametro;
    use App\InventarioParametro;

     class ReportesCrudController extends CrudController
    {
    public function setup(){
    $this->crud->setModel("App\Importacion");
    $this->crud->setRoute("admin/listado_importacion");
    $this->crud->setEntityNameStrings('importacion', 'importaciones');
    $this->crud->enableExportButtons();  <--- Api function
  }
  public function listado_parametro_estacion(){

     $result =  InventarioParametro::paginate(10); 
     // dd($result);
     return view('reportes.listado_estacion_equipo',compact('result'));
  } 

     public function listado_importacion(){
 
     $this->crud->setColumns(['id','nombre_documento','responsable','created_at']);
     // $this->crud->enableAjaxTable();
    $importaciones = Importacion::orderBy('id','DES')->paginate(10);
    return view('reportes.listado_importacion',compact('importaciones'));  
  }
```
  
Routes: 
        
        Route::get('reportes/listado_parametro_estacion', ['as'=>'crud.reportes.listado_parametro_estacion', 'uses'=>'ReportesCrudController@listado_parametro_estacion']);

        Route::get('reportes/listado_importacion',['as'=>'crud.reportes.listado_importacion', 'uses'=>'ReportesCrudController@listado_importacion']);

        Route::get('reportes/listado_equipo_parametro',    ['as'=>'crud.reportes.listado_equipo_parametro', 'uses'=>'ReportesCrudController@listado_equipo_parametro']);

**Comment by tabacitu** [comment]
Hi @amipax ,

I'm sorry, I don't think I understand your problem. What are you trying to achieve and isn't working? If your problem is that you can't use the CRUD api inside your views, that should be because you're sending ```compact('importaciones')``` to them, instead of ```$this->crud```.

This doesn't sound like a bug in the software, so please post on [StackOverflow's backpack-for-laravel tag](stackoverflow.com/questions/tagged/backpack-for-laravel), detailing the above.

Cheers!
