### ISSUE TITLE
Revisions and date

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#695]
When I use [Revisions](https://laravel-backpack.readme.io/v3.0/docs/advanced-features#section-revisions), it shows date changes even I didn't change it.  `00:00:00` after the date is added to "Change to".

<img width="858" alt="screen shot 2017-05-24 at 1 13 17 pm" src="https://cloud.githubusercontent.com/assets/147320/26386721/68ab69bc-4083-11e7-828e-d5b52be8c48f.png">

The followings are input image and controller `addField`s. 

<img width="688" alt="screen shot 2017-05-24 at 1 14 49 pm" src="https://cloud.githubusercontent.com/assets/147320/26386724/6d0d56b4-4083-11e7-93d6-0a004b71916a.png">

        $this->crud->addField([   
            'name' => 'date',
            'label' => 'Date',
            'type' => 'date',
            'value' => date('Y-m-d'),
        ], 'create');
        $this->crud->addField([  
            'name' => 'date',
            'label' => 'Date',
            'type' => 'date',
        ], 'update');

What is the best way to avoid this problem?

**Comment by lloy0076** [comment]
I'm not sure that's a bug in Backpack - Backpack simply uses https://github.com/VentureCraft/revisionable.

As a test can you intercept the **actual** update and **dump** what the date is/isn't being changed to?

(You could do this easily enough in the generated `update` function):

```
public function update(StoreRequest $request) {
   dd($request->all();
   // Rest of code.
}
```

**Comment by shinokada** [comment]
Returned as `"date" => "2017-04-13"`.

```
array:17 [▼
  "_method" => "PUT"
  "_token" => "m0AYUQ6L9DuPgimL9YVkUiEemhr39JHtjE1ZAY3e"
  "title" => "New Article"
  "user_id" => "1"
...
  "slug" => "article-1"
  "date" => "2017-04-13"
  "content" => "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio.</p>"
  "category_id" => "1"
  "tags" => array:1 [▶]
  "status" => "PUBLISHED"
  "featured" => "0"
...
  "id" => "1"
  "save_action" => "save_and_back"
```

**Comment by lloy0076** [comment]
Let me dig further:

* It could be storing the full date/time with the 00:00:00
* It could be displaying the 00:00:00 but not storing that

(you can actually open something like the MySQL client, phpMyAdmin (icck) or such to peek at the revision db itself).

**Comment by shinokada** [comment]
Ok, thanks.

I was using [NewsCRUD](https://github.com/Laravel-Backpack/NewsCRUD), so I changed from date to timestamp for [date](https://github.com/Laravel-Backpack/NewsCRUD/blob/master/src/database/migrations/2015_08_04_130520_create_articles_table.php#L23).
