### ISSUE TITLE
View [fields.select2_ajax] not found

### ISSUE THREAD

**Issue by imannms** [Laravel-Backpack/CRUD#696]
Hello, Backpack is great package.

I have some issue here,

Other fields worked, including **select** and **select2**, but **select2_from_array**, **select2_from_ajax**, and **select2_from_ajax_multiple** didn't work.

This is error log when using **select2_from_ajax** :

Log:
`[2017-05-24 01:49:15] production.ERROR: exception 'InvalidArgumentException' with message 'View [fields.select2_ajax] not found.' in /public_html/private/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137`

**Comment by tabacitu** [comment]
Hi @imannms,

I'm pretty sure you're running an old version of Backpack then - since before those fields were created. A ```composer update``` should fix it for you.

Cheers!
