### ISSUE TITLE
HasMany and table?

### ISSUE THREAD

**Issue by kanashin** [Laravel-Backpack/CRUD#697]
Hello! I love Backpack.

Do you know if there is any option out of the box to achieve the following situation?

Imagine a model with a hasMany relation (a user with many contracts), and the possiblity to add them using a table but also then the possibility to edit the contracts in order to add some more fields (even other hasMany relation)?

I know I can do a select field from the Contract model to the User, but I want the other way round: from the user add many contracts. I think an option is override the controller and catch the field table and then sync with the contracts relation and also add an edit button into the table but I want to know if there already exists something already developed.

Thank you!

![imagen](https://cloud.githubusercontent.com/assets/567547/26400485/591b0518-4081-11e7-9270-dc3a1b92f447.png)

**Comment by lloy0076** [comment]
There's thoughts about it in https://github.com/Laravel-Backpack/CRUD/issues/591 if this is what you're referencing?

**Comment by kanashin** [comment]
Yes, it something like that or even a simplier thing. However I see that one is not solved so I will close this one.

**Comment by kanashin** [comment]
To clarify, the field needed is a n-1 relation (the inverse of select and select2 fields) and it could be implemented as a table I think
