### ISSUE TITLE
[QUESTION] Gallery of Images

### ISSUE THREAD

**Issue by eullercdr** [Laravel-Backpack/CRUD#698]
Dears, 

I have a doubt. I have events and photos by events. I would like that photos be store in the folder of the with name id of event. Backpack possibilite that?

How can i do that?

Can you help me?

**Comment by lloy0076** [comment]
@eullercdr - you can store your photos anywhere that PHP and your server can store files.

If you use the image uploader for CRUD see the answer to:

* https://laravel-backpack.readme.io/docs/crud-fields#section-image

If you want to use Laravel's file system storage then see:

* https://laravel.com/docs/5.4/filesystem

And there's nothing stopping you from storing your files in whatever structure that makes sense for your file system abstraction at all.

You can, of course, just use plain old PHP file handlers.

**Comment by eullercdr** [comment]
@lloy0076 And for the list the images, with option of edit and delete? Is there a component for grid of images or other resource?

**Comment by lloy0076** [comment]
@eullercdr - no, just a component to upload an image and then give the data to the application.

**Comment by tabacitu** [comment]
@eullercdr - you [could find this useful](https://github.com/Laravel-Backpack/CRUD/issues/427#issuecomment-278877491).

**Comment by seandowney** [comment]
You might be interested in this - it's not perfect either but is another option.
https://github.com/seandowney/laravel-backpack-gallery-crud

**Comment by tabacitu** [comment]
@seandowney I totally forgot about your package - just added it to the community extensions here -https://backpackforlaravel.com/docs/3.4/add-ons-community

Let me know if there are more you want included there.

**Comment by seandowney** [comment]
@tabacitu cool thanks.
