### ISSUE TITLE
[FIELDS] If "required" show asterisk.

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#7]
1. In all fields, if the "required" attribute is true, show an asterisk to let the user know the field is mandatory.
2. In Crud.php, the following functions should be completed:
   - $this->crud->setRequiredFields(['field_1', 'field_2'], 'update/create/both');
   - $this->crud->setRequiredField('field_1', 'update/create/both');
   - $this->crud->getRequiredFields()

**Comment by tabacitu** [comment]
On second thought, this is not a critical function and would only add complexity to the library, when a way simpler solution is present:

```php
$this->addField([
  'name' => 'name',
  'label' => 'Name *',
  'type' => 'text'
]);
```

As such, I propose we remove the ```requiredFields``` functionality from the core, before it's completely implemented.

@cristiantone do you agree?

**Comment by jim1506** [comment]
This may be of use to anyone as this works fine:

     'label' => "<span style='color:red'>* </span> Name"

![27-11-2018 09-58-08](https://user-images.githubusercontent.com/123184/49073801-24388700-f22b-11e8-81e1-df9987621c15.png)

**Comment by tabacitu** [comment]
@jim1506 I can confirm that works. But you can also let the FormRequest do it for you, if you do this in your ```setup()``` method:

```php
$this->crud->setRequiredFields(StoreRequest::class, 'create');
$this->crud->setRequiredFields(UpdateRequest::class, 'edit');
```

This will look inside your form requests and put asterisks before the ones that are "required". 

CrudControllers generated after a certain point should have these two lines already in the ```setup()``` method, but old ones do not.
