### ISSUE TITLE
crud 3.0.0 update errors

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#70]
I have the followings in my composer.json

    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "backpack/base": "^0.6.6",
        "backpack/crud": "^3.0.0",
        "backpack/generators": "^1.1",
        "backpack/langfilemanager": "^1.0",
        "backpack/backupmanager": "^1.1",
        "backpack/settings": "^2.0",
        "backpack/pagemanager": "^1.0"
    },

And I run `composer update`, then I get the following errors.

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - backpack/settings 2.0.5 requires backpack/crud 2.* -> satisfiable by backpack/crud[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, v2.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/settings 2.0.4 requires backpack/crud 2.* -> satisfiable by backpack/crud[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, v2.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/settings 2.0.3 requires backpack/crud 2.* -> satisfiable by backpack/crud[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, v2.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/settings 2.0.2 requires backpack/crud 2.* -> satisfiable by backpack/crud[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, v2.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/settings 2.0.1 requires backpack/crud 2.* -> satisfiable by backpack/crud[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, v2.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/settings 2.0.0 requires backpack/crud 0.* -> satisfiable by backpack/crud[0.4.1, 0.5.0, 0.5.1, 0.5.10, 0.5.9, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.1, 0.8.10, 0.8.11, 0.8.12, 0.8.13, 0.8.14, 0.8.15, 0.8.16, 0.8.17, 0.8.18, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.10, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9] but these conflict with your requirements or minimum-stability.
    - backpack/settings 2.0.4 requires backpack/crud 2.* -> satisfiable by backpack/crud[2.0.0, 2.0.1, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0.24, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, v2.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for backpack/settings ^2.0 -> satisfiable by backpack/settings[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].

**Comment by tabacitu** [comment]
Wooow. Damn. You're right, I forgot to update all other packages to accomodate for the CRUD 3.0 version.

On mobile now, I'll fix this first thing tomorrow morning when i get to a computer (in about 9h).

Sorry for this.

**Comment by tabacitu** [comment]
Hi! Apparently it wasn't THAT difficult to make the fix on mobile, the github interface is pretty good. 
I did do the fix, but I have no way to test if it's working until 9 hours from now.

If you try it until then, please tell me if all goes well. Otherwise, I'll make sure I test in in 9 hours.

Cheers and sorry again.

**Comment by c1t1zen** [comment]
what's new in crud 3.0.0?

**Comment by shinokada** [comment]
It worked well. Thanks.
I just get this warning.

    Package prologue/alerts is abandoned, you should avoid using it. No replacement was suggested.

**Comment by tabacitu** [comment]
Yup, it's a known issue. We'll either replace it, or just take up to maintaining it ourselves.

It's a very good package and very very little things can go wrong with it - so far it works great, despite the fact it was abandoned.

I also tested everything and seems to work. I'll close this issue.

Cheers and thanks!
