### ISSUE TITLE
editing ckeditor/config.js does not produce changes

### ISSUE THREAD

**Issue by scottgrayson** [Laravel-Backpack/CRUD#700]
I'm trying to do the same thing as #96 

Editing the config.js seems to have no effect.
```
                //{ name: 'styles' },
		{ name: 'colors' },
		{ name: 'about' }
```
commenting out the styles toolbar doesnt remove it on the wysiwyg field.
![image](https://cloud.githubusercontent.com/assets/7796074/26464343/7799169a-4155-11e7-889b-f426122e748b.png)
Intentionally making a syntax error does not produce an effect either. Where does the config.js get loaded?

Also getting this error. Have not been able to figure out the source.
![image](https://cloud.githubusercontent.com/assets/7796074/26464321/5f3e43e0-4155-11e7-8fce-ed73c1fa88e1.png)

**Comment by lloy0076** [comment]
Using Chrome Developer tools, it seems that the `config.js` may be being taken from:

`https://A_URL/vendor/backpack/ckeditor/config.js` - it may have a `?t=XXX` appended which I suspect is elixir or some sort of cache busting mechanism.

Check what is returned by that (where `A_URL` is relevant to your setup)?

**Comment by tabacitu** [comment]
Also, Chrome caching might have changed in the past months - it's been particularly painful lately to do hard refreshes. Try seeing if your ```config.js``` changes appear in an incognito window. Just a thought.

**Comment by scottgrayson** [comment]
I switched to summernote because the default settings where what i wanted. I did not think about the cache thing. That was most likely my problem

**Comment by brynnb** [comment]
I had the same issue - config was being cached and couldn't figure out how to make it refresh. Opening the config file in the browser and hard refreshing then reloading my admin page worked. https://stackoverflow.com/a/40129371/5623108
