### ISSUE TITLE
Error in translatable models.

### ISSUE THREAD

**Issue by morcano** [Laravel-Backpack/CRUD#705]
I use HasTranslations trait with a few translatable fields in my Page model:

`protected $fakeColumns = ['extras'];
 protected $translatable = ['title', 'content'];`

When I submit form to add new page I get error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta_title' in 'field list' ...

This error occurs if I didn't fill fake fields: 'meta_title', 'meta_description'... etc..
If I fill some data in these fields everything ok..

UPD.

I installed **mcamara/laravel-localization** to display the translation on the page.
After editing the categories in the admin panel instead of the name, I get something like this
![capture image](https://cloud.githubusercontent.com/assets/17854141/26524794/58280f56-4348-11e7-9eca-0f5cd601c3d6.png)

**Comment by lloy0076** [comment]
@morcano - did the update **fix** the problem, i.e. did the SQLSTATE error go away and you see what is expected?

**Comment by tabacitu** [comment]
Hi @morcano ,

Did you use ```$fillable``` on your model or ```$guarded```?

Cheers!

**Comment by gotrecillo** [comment]
I have been hit by this too.
Had my Pagemanager working with fake fields and translatable fields, even fake fields where translatable. Now i get the same error.

All of this is in my model.

```php
use Backpack\CRUD\CrudTrait;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\Sluggable;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    use CrudTrait;
    use Sluggable;
    use SluggableScopeHelpers;
    use HasTranslations;


    protected $fillable = ['template', 'name', 'title', 'slug', 'extras', 'content'];
    protected $fakeColumns = ['extras'];
    protected $translatable = ['title', 'slug', 'extras', 'content'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_or_title',
            ],
        ];
    }

}
```

To get it working I had to do some hacking to PageCrudController:
- Created a hidden input with the name ' extras'
- Prepared the $request before saving it

All this in the controller
```php
public function store(PageRequest $request)
{
    $this->prepareRequestForSaving($request);
    return parent::storeCrud($request);
}

public function update(PageRequest $request)
{
    $this->prepareRequestForSaving($request);
    return parent::updateCrud($request);
}

private function addDefaultPageFields($template = false)
{
    $this->crud->addField([
        'name' => 'template',
        'label' => trans('gotrecillo::PagesCrud.template'),
        'type' => 'select_page_template',
        'options' => $this->getTemplatesOptions(),
        'value' => $template,
        'allows_null' => false,
        'wrapperAttributes' => [
            'class' => 'form-group col-md-6',
        ],
    ]);

     $this->crud->addField([
        'name' => 'name',
        'label' => trans('gotrecillo::PagesCrud.name'),
        'type' => 'text',
        'wrapperAttributes' => [
            'class' => 'form-group col-md-6',
        ],
    ]);

     $this->crud->addField([
        'name' => 'title',
        'label' => trans('gotrecillo::PagesCrud.title'),
        'type' => 'text',
    ]);

    $this->crud->addField([
        'name' => 'slug',
        'label' => trans('gotrecillo::PagesCrud.url'),
        'type' => 'text',
        'hint' => trans('gotrecillo::PagesCrud.url_hint'),
    ]);

    $this->crud->addField([
        'name' => 'extras',
        'type' => 'hidden',
    ]);
}

private function prepareRequestForSaving(PageRequest $request)
{
    $request->request->remove('extras');
    $template = $request->get('template');
    $this->addCrudFields($template);
}

private function addCrudFields($template)
{
    $this->addDefaultPageFields($template);
    $this->useTemplate($template);
}

```

I think updating Backpack/CRUD has made it not work anymore.

This is what i have in my composer.json

```
    "backpack/crud": "^3.2",
```

I think that when i was using backpack/crud 3.2.7 it was working from what I can read in my composer.lock. Tomorrow i will try with different tags to narrow it.

I could check tomorrow versions in my composer.lock to see
I hope this is useful tracking down this bug.

**Comment by tabacitu** [comment]
Hi guys. Is this still an issue for you?

**Comment by morcano** [comment]
solved thx

**Comment by tabacitu** [comment]
Totally agree with your change @gotrecillo . Merging now, thank you!
