### ISSUE TITLE
Error using "composer require anything" after using revision

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#708]
I started using [Revisions](https://laravel-backpack.readme.io/docs/advanced-features#section-revisions).

Now when I run `composer require anything-here`, I get the following error. What is the best way to resolve this?

> Warning: Ambiguous class resolution, "CreateRevisionsTable" was found in both "$baseDir . '/database/migrations/2013_04_09_062329_create_revisions_table.php" and "/Users/myname/Code/myweb/vendor/venturecraft/revisionable/src/migrations/2013_04_09_062329_create_revisions_table.php", the first will be used.

**Comment by shinokada** [comment]
I just deleted `'/database/migrations/2013_04_09_062329_create_revisions_table.php`. But it shouldn't be.

**Comment by AbbyJanke** [comment]
What is the error you are getting? Generally having a file like that shouldn't cause any issues with composer

**Comment by shinokada** [comment]
> backpack-aktiv git:(google-calendar) ✗ composer require spatie/laravel-google-calendar
> Using version ^1.1 for spatie/laravel-google-calendar
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 0 installs, 0 updates, 0 removals
> Generating autoload files
> Warning: Ambiguous class resolution, "CreateRevisionsTable" was found in both "$baseDir . '/database/migrations/2013_04_09_062329_create_revisions_table.php" and "/Users/myname/Code/myweb/vendor/venturecraft/revisionable/src/migrations/2013_04_09_062329_create_revisions_table.php", the first will be used.
> > Illuminate\Foundation\ComposerScripts::postUpdate
> > php artisan optimize
> Generating optimized class loader
> The compiled services file has been removed.

**Comment by AbbyJanke** [comment]
Run 'composer dump-autoload'

If that doesnt work then 'php artisan clear-compiled'

**Comment by shinokada** [comment]
Both didn't work. It gives back the same error. 
Unfortunately for now, deleting the migration file works.

**Comment by shinokada** [comment]
It seems [5.4 Laravel supports loading migrations from any directory](https://stackoverflow.com/questions/42790431/is-laravel-5-4-running-migrations-from-vendor-folders-now).

**Comment by victorlap** [comment]
See also: https://github.com/VentureCraft/revisionable/blob/master/readme.md

> If you're going to be migrating up and down completely a lot (using migrate:refresh), one thing you can do instead is to copy the migration file from the package to your app/database folder, and change the classname from CreateRevisionsTable to something like CreateRevisionTable (without the 's', otherwise you'll get an error saying there's a duplicate class)
