### ISSUE TITLE
Have there any way to refresh the table without lose filters or searches?

### ISSUE THREAD

**Issue by eescalante** [Laravel-Backpack/CRUD#711]
Sometimes, i need to redraw the table with the last search/filters but if i reload the page or if i redraw the table all these parameters will be lost.

I have an application where i fire operations by custom buttons and i need to show the changes in the table but i don't want to lose the result set that i have because i need to keep working with the other rows.

Is this possible?

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/CRUD/issues/516#issuecomment-283755231 might be relevant here.

**Comment by tabacitu** [comment]
Hmm... there isn't an official way to do this, no. But in your buttons javascript you might be able to refresh the DataTables object, if you using AjaxDataTables.

Hope it helps. Cheers!
