### ISSUE TITLE
Select dependent on another select

### ISSUE THREAD

**Issue by eddilou** [Laravel-Backpack/CRUD#712]
Hello everyone, how to implement the filtering functionality?
There is a solutions table:
-id
-title
....

There is a categories table
-id
-name

There is a subcategories table
-id
-name
-category_id

There is a table solution_subcategory
-solution_id
-subcategory_id

On the edit solution page I need 2 dropdown:
Which when selecting the first will load the second, or how to implement one?
Select Subcategory must be multiselect

**Comment by eddilou** [comment]
```PHP
   [
                'name' => 'subcategory_id',
                'label' => 'Subcategory',
                'type' => 'select',
                'entity' => 'subcategory',
                'attribute' => 'name', 
                'pivot' => true,
                'tab' => 'Filters'
            ],
```
When you enter this code, an exception is thrown "There is no column with name 'subcategory_id' on table 'solutions'"
How to make 2 dropdowns, which the second will depend on the first and save in the solution_subcategory table

**Comment by lloy0076** [comment]
I "borrowed" this example from the Permission Manager:

```
            // two interconnected entities

            'label'             => trans('backpack::permissionmanager.user_role_permission'),

            'field_unique_name' => 'user_role_permission',

            'type'              => 'checklist_dependency',

            'name'              => 'roles_and_permissions', // the methods that defines the relationship in your Model

            'subfields'         => [

                    'primary' => [

                        'label'            => trans('backpack::permissionmanager.roles'),

                        'name'             => 'roles', // the method that defines the relationship in your Model

                        'entity'           => 'roles', // the method that defines the relationship in your Model

                        'entity_secondary' => 'permissions', // the method that defines the relationship in your Model

                        'attribute'        => 'name', // foreign key attribute that is shown to user

                        'model'            => "Backpack\PermissionManager\app\Models\Role", // foreign key model

                        'pivot'            => true, // on create&update, do you need to add/delete pivot table entries?]

                        'number_columns'   => 3, //can be 1,2,3,4,6

                    ],

                    'secondary' => [

                        'label'          => ucfirst(trans('backpack::permissionmanager.permission_singular')),

                        'name'           => 'permissions', // the method that defines the relationship in your Model

                        'entity'         => 'permissions', // the method that defines the relationship in your Model

                        'entity_primary' => 'roles', // the method that defines the relationship in your Model

                        'attribute'      => 'name', // foreign key attribute that is shown to user

                        'model'          => "Backpack\PermissionManager\app\Models\Permission", // foreign key model

                        'pivot'          => true, // on create&update, do you need to add/delete pivot table entries?]

                        'number_columns' => 3, //can be 1,2,3,4,6

                    ],

                ],
```

https://github.com/Laravel-Backpack/PermissionManager/blob/master/src/app/Http/Controllers/UserCrudController.php#L74

The attached is a copy of what it might look like with some roles/permission populated [obviously everyone else's may have differing outputs depending on the values in the tables].

Is this what you were looking for? (e.g. if I click fuel-seller then a bunch of related permissions get set and the tick boxes do too).

![image](https://cloud.githubusercontent.com/assets/1174532/26681045/ab3c0382-46a9-11e7-9fab-825d5a3d51e5.png)

**Comment by eddilou** [comment]
@lloy0076 Did not help, the error remained the same,
```php
            [
                'label'             => 'Filter',
                'field_unique_name' => 'solution_subcategory',
                'type'              => 'select',
                'name'              => 'subcategories', // the methods that defines the relationship in your Model
                'subfields'         => [
                    'primary' => [
                        'label'            => 'Category',
                        'name'             => 'name', // the method that defines the relationship in your Model
                        'entity'           => 'category', // the method that defines the relationship in your Mode
                        'entity_secondary' => 'children', // the method that defines the relationship in your Model
                        'attribute'        => 'name', // foreign key attribute that is shown to user
                        'model'            => "App\Models\Category", // foreign key model
                        'pivot'            => true, // on create&update, do you need to add/delete pivot table entries?]
                    ],
                    'secondary' => [
                        'label'          => 'Subcategory',
                        'name'           => 'subcategory', // the method that defines the relationship in your Model
                        'entity'         => 'subcategory', // the method that defines the relationship in your Model
                        'entity_primary' => 'parent', // the method that defines the relationship in your Model
                        'attribute'      => 'name', // foreign key attribute that is shown to user
                        'model'          => "App\Models\Subcategory", // foreign key model
                        'pivot'          => true, // on create&update, do you need to add/delete pivot table entries?]
                    ],
                ],

            ],
```
Category model
```PHP
```
Subcategory model

**Comment by eddilou** [comment]
@lloy0076 Changed the type to checklist_dependency, now the error does not drop out, but the page is not loaded completely, the styles are lost, that is, the white background and the content without the connected styles

**Comment by eddilou** [comment]
@tabacitu  can you tell me what the problem is, and what's my mistake?

**Comment by lloy0076** [comment]
Looking a bit more closely there's two separate issues here:

1. The checklist dependency isn't working as expected; and
2. Even if it were, it would probably not be saving/doing what you'd expect.

The first part is relatively easy. There are a few reports that the select styling is somehow broken by something but I haven't verified if this is the case for myself.

However, even if this did work it's not going to save as you'd expect. In fact, you'd have to intercept what it provided to the CRUD controllers and save it properly into the `solution_subcategory` table. There's no "select IDs somehow from these things and then save it into an entirely different table" edit field...

It may be easier to work with a custom field type but this would mean you'd have to set the select for part (1) up yourself.

Failing that, IF one got the `checklist_dependency` working, one would have to intercept the method(s) that save that dependency to correctly store the daa into the `solution_subcategory` table.

**Comment by amipax** [comment]
if you mean chained selects, it can be done using routes, when you click on a select dropdown, you get the value through Jquery, then you pass the value to the route .  

    Route::get('estaciones/get_comunas', function()
    {    
      $id = Input::get('id');
      return App\Region::with('comunas')->where('region.id',$id)->get();
    });

**Comment by eddilou** [comment]
@lloy0076 The problem is this instruction vendor\backpack\crud\src\resources\views\fields\checklist_dependency.blade.php
```PHP
$primary_dependency['model']::with($primary_dependency['entity_secondary'])->get()
```
This code does not work further than this code
It is because of this breaks the style and further fields are not shown

**Comment by eddilou** [comment]
@lloy0076 ontent.com/15788938/26872147-bed314c6-4b9f-11e7-9a15-d2786fdd1fe7.JPG)
pdated - I have the latest laravel and the crud
![screen_nozj](https://user-images.githubusercontent.com/15788938/26872166-cd04dee4-4b9f-11e7-9325-5402415fef81.JPG)

**Comment by lloy0076** [comment]
![image](https://user-images.githubusercontent.com/1174532/26879154-09d9bc32-4b5e-11e7-96f9-96b1593b5558.png)

**Comment by eddilou** [comment]
@lloy0076 Thank you Very strange, what could be the problem? At me even the permission manager does not work

**Comment by eddilou** [comment]
@lloy0076 Here is my composer.json, try, I do not understand what can interfere
[composer.zip](https://github.com/Laravel-Backpack/CRUD/files/1060013/composer.zip)

**Comment by tabacitu** [comment]
Hi @eddilou - I'm sure you have this figured out by now, so I'll close the issue. This was more of a [StackOverflow question](https://stackoverflow.com/questions/tagged/backpack-for-laravel) anyway, IMHO.

Cheers!

**Comment by marko89kv** [comment]
Sorry for popping in here now, but how was this solved, the chained selects?
since, if it has to be done like @amipax proposed, there would have to be a listener on the first dropdown, for picking up the value, passing it to the controller, and then populating the second dropdown, and I'm not sure how would that work with the whole CRUD system (I don't know actually, I'm still getting used to Backpack).

**Comment by eddilou** [comment]
Hello everyone, I had a problem due to the fact that some vendor demanded php7 and because of this the crud was broken

**Comment by amipax** [comment]
@marko89kv  it works like a charm, note you have to make the select fields nullable, so the first select value is - .

**Comment by marko89kv** [comment]
@amipax where would you put javascript for a listener and the ajax call for the first field, and where for the second field? The second field, the one that receives that should probably be of "select2_from_ajax" type. I'm just missing the first part.

**Comment by tva3777** [comment]
does anyone solved this?
how to use dependent selects ?

**Comment by tabacitu** [comment]
@tva3777 there's a PR with a complete solution here https://github.com/Laravel-Backpack/CRUD/pull/1484 - might get merged soon. Until then you can use the code there in your own project, as a custom field type.

**Comment by emrancu** [comment]
Hi @eddilou 
I have created a package. It may help you.
 This package provides a 'dependantFieldOptions' field type for the Backpack for the Laravel administration panel. The 'dependantFieldOptions' field allows admins to load options from provided source through provided method depending on change in the parent/specific field.

The GitHub link: [Here](https://github.com/OgrooSoft/onchange-load-dependant-field-data)
