### ISSUE TITLE
customize pdf download

### ISSUE THREAD

**Issue by dj-fiorex** [Laravel-Backpack/CRUD#714]
Hi all, first of all thanks for this magic package :) i want to know if i can customize the action of the button inserted in datatable via `$this->crud->enableExportButton()`, for example i don't want to print the action column in the pdf. How can i archieve this? 
Thanks!

**Comment by AbbyJanke** [comment]
Hello @dj-fiorex the Export functionality as actually handled by DataTables. Looking at the code for the view it is exporting any tables that are "visible."

```
              exportOptions: {
              columns: [':visible']
              }
```

What you are probably going to have to do is overwrite that view file and change it to a custom attribute that you set for each column within your controller.

The file is `list.blade.php` line 166. My suggestion is add a class or custom attribute to  called "exportable" and just not add it to the actions column.

**Comment by dj-fiorex** [comment]
first of all thanks for the reply :) i looked at the code but i don't understand how the `:visible` selector act, i tried to add a custom class to my columns in the CrudController
 ```
$this->crud->addColumn([
        // 1-n relationship
        'label' => "MSRP", // Table column heading
        'type' => "select",
        'name' => 'id', // the column that contains the ID of that connected entity;
        'entity' => 'price', // the method that defines the relationship in your Model
        'attribute' => "msrp", // foreign key attribute that is shown to user
        'model' => "App\Models\ProductPrice", // foreign key model
        'wrapperAttributes' => [
           'class' => 'toPdf'
         ]
      ]);
```
and then change `:visible` with `:toPdf` but seems not to work :( 
Can you help me? 
Thanks

**Comment by AbbyJanke** [comment]
Hi, so the `:visible` Selector is checking for any columns/rows that are not hidden meaning you can see them in the web browser. I believe if you change jt to `.toPdf` It will work. 

There is more documentation on how DatsTables selects columns here: https://datatables.net/reference/type/column-selector

**Comment by dj-fiorex** [comment]
i have read the documentation about datatable, i also try to modify my select.blade.php to add a class on td element
```
<?php
echo '<td class="toPdf">';

		if ($entry->{$column['entity']}) {
	    	echo $entry->{$column['entity']}->{$column['attribute']};
	    }

echo '</td>';
?>
```
and then add a `'class' => 'toPdf',` in my columns in crud controller but didn't work :(
in my opinion the DataTables column selector act on th element so i need to add the class to the th element, maybe!

**Comment by dj-fiorex** [comment]
Ok i found how to do it! 
Modify list.blade.php line 47 
```
<th class="{{ $column['class'] }}">{{ $column['label'] }}</th>
```
and line 166
```
columns: ['.exportable']
```
finally add to your columns definition in crudcontroller
```
$this->crud->addColumn([
       [ .... ]
        'class' => 'exportable'
      ]); 
```
Thanks for the help!

**Comment by AbbyJanke** [comment]
Glad you got it working. Sorry i couldnt help more have been at work the entire time and only have my phone.

**Comment by dj-fiorex** [comment]
don't worry! you give me the input to start coding ahahah.
But there are any news about 1-1 relationship? because i try [this](https://gist.github.com/ChrisThompsonTLDR/c83b21a6f7c9041b680be880c2a21ff0) solution but i can't figure out how to do this

**Comment by niladam** [comment]
I think adding a reference to #960 in here should also help future users that need this..
