### ISSUE TITLE
Force https

### ISSUE THREAD

**Issue by giovannylemay** [Laravel-Backpack/CRUD#716]
I use backpack for a study project.

But I need to force https for admin panel.

Can I have some help ? 

Ty

**Comment by AbbyJanke** [comment]
Implenting HTTPS would be the same way as any Laravel application. I would create a middleware and apply it to any routes using the web group.

https://laracasts.com/discuss/channels/laravel/force-ssl-secure-routes-in-laravel-52?page=1

**Comment by OwenMelbz** [comment]
https://packagist.org/packages/owenmelbz/https-enforcement ennnjoy :D

**Comment by OwenMelbz** [comment]
I'm going to close this as its not backpack specific.

But as @AbbyJanke said - its typically done at apache/nginx level or via some middleware.

**Comment by MickaelTH** [comment]
Using https://packagist.org/packages/owenmelbz/https-enforcement from @OwenMelbz on Laravel 5.4 thanks for this!
