### ISSUE TITLE
Problem with select2 with the last update

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#717]
Since the last update i have this error:
```
select2.js
Uncaught Error: Option 'multiple' is not allowed for Select2 when attached to a <select> element.
```
I think the Select2 files where not update to the latest version in  /public/vendor/backpack/select2

I did a php artisan vendor:publish before but it as not updated.

Am i missing something?

**Comment by adbmdp** [comment]
Sorry i think it's my fault...
Let me check it out and i'll close the issue.

**Comment by adbmdp** [comment]
I fixed the problem. But now all select2 styles have changed. Does not look like before.

**Comment by lloy0076** [comment]
Sadly, a hobbit stole my seeing stone - do you have a before and now shot of what happened?

**Comment by egolife** [comment]
Hello, thx for your great work guys.

Concerning this issue - I have style problems with select2 as well.
Here are two screenshots: from 3.2.11 and 3.2.12 (no other changes except composer update).
*FYI I have republished vendor files - it doesn't affect this problem.

before: http://joxi.ru/8Anz9YYTbR9MAO
after: http://joxi.ru/zANejXXTEZLM29

**Comment by adbmdp** [comment]
Same problem for me. Sorry @lloy0076 i was about to post screenshots but had connexions problems just before.

**Comment by capripio** [comment]
The same issue any fixed yet?

**Comment by jkudish** [comment]
Same issue here 😞

**Comment by splodgeco** [comment]
I am having the same issue and I fixed this by the following method.

Create a custom view to override the select2_multiple and place this in ``resources/views/vendor/backpack/crud/fields``. This file has to be called the same as the one we are overriding ``select2_multiple.blade.php``

Replace lines 37 - 38
```
<link href="{{ asset('vendor/adminlte/plugins/select2/select2.min.css') }}" rel="stylesheet" type="text/css" />
{{-- <link href="{{ asset('vendor/backpack/select2/select2-bootstrap-dick.css') }}" rel="stylesheet" type="text/css" /> --}}
```
With
```
<link href="{{ asset('vendor/backpack/select2/select2.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendor/backpack/select2/select2-bootstrap-dick.css') }}" rel="stylesheet" type="text/css" />
```

Replace line 4
```
<script src="{{ asset('vendor/adminlte/plugins/select2/select2.min.js') }}"></script>
```
With
```
<script src="{{ asset('vendor/backpack/select2/select2.js') }}"></script>
```

I now have the select 2 working correctly.

Hope this helps.

**Comment by lloy0076** [comment]
[composer.zip](https://github.com/Laravel-Backpack/CRUD/files/1068105/composer.zip)
Standard Select2:

![image](https://user-images.githubusercontent.com/1174532/27033714-91d8115e-4f48-11e7-9765-60c634beefa7.png)

**Comment by lloy0076** [comment]
Ok, got it on the select2_multiple:

![image](https://user-images.githubusercontent.com/1174532/27034430-b69c98e0-4f4b-11e7-83a7-8124898cbcf5.png)

**Comment by lloy0076** [comment]
The original issue here was found but the style issue seems to be separate - I've opened https://github.com/Laravel-Backpack/CRUD/issues/740 to track that.

**Comment by marconett** [comment]
@adbmdp: how did you fix the initial issue `Uncaught Error: Option 'multiple' is not allowed for Select2 when attached to a <select> element.` ? having the same problem.

**Comment by adbmdp** [comment]
I did not fix it. Didn't had time to investigate so i've decided to downgrade version.
