### ISSUE TITLE
Custom attributes in radio field

### ISSUE THREAD

**Issue by jsvini** [Laravel-Backpack/CRUD#718]
I want to add the "required" attribute to a radio field, but it is not possible because this field doesn't include the "crud::inc.field_attributes" view.

**Comment by tabacitu** [comment]
Hi @jsvini ,

You're right, thanks for spotting it. [Just fixed it](https://github.com/Laravel-Backpack/CRUD/commit/5cd919f41bc8124c3732e2d63d4143adb3be2356) on ```dev```, it will be available on master later this week.

Cheers!
