### ISSUE TITLE
Controller Naming Convention

### ISSUE THREAD

**Issue by bloggervista** [Laravel-Backpack/CRUD#719]
Isn't controller naming should be done in plural?

When i read the docs i found convention was:
EntityCrudController.php

Where where should i change to follow convention like EntititiesCrudController.php??

**Comment by AbbyJanke** [comment]
I believe plural was an older way laravel did it, if my memory serves me right, however singular is the correct form for controllers. If you look at the base comtrollers for Auth, User and such they are singular along with the Controller Documentation:

https://laravel.com/docs/5.4/controllers

**Comment by bloggervista** [comment]
@AbbyJanke although new version uses singular many people like me  still uses plural one and i am not forcing to use plural one but i am just asking if there is any problem with using plural one and what should i change to make it work without any problem :)

Thx .

**Comment by AbbyJanke** [comment]
The controllers you could simply overwrite them, or if you just want the routes to be plural you can disable the automatic generation of then within the base settings and then manually register them as plural formats.

**Comment by tabacitu** [comment]
IMHO - whatever floats your boat :-) It's just a name. It's best to use a convention, whatever that convention is. Backpack follows the Laravel & Laracasts best practices, but whatever convention is a good alternative too :-)
