### ISSUE TITLE
In column template, access a value from another column that is not displayed

### ISSUE THREAD

**Issue by DelightedD0D** [Laravel-Backpack/CRUD#721]
I want to access a property for an `entry` in a column template without displaying that property in the table.

For example. Say I have a model that has  the columns `phone_number` and `blacklisted_number_id`.

In my table, I want to only show the  `phone_number` column, so I set my columns as such:

```

        $columns = [
            [
                'name'  => 'phone_number',
                'label' => 'Phone Number',
                'type'  => 'interaction-phone-number',
            ], 
        ];
        $this->crud->addColumns($columns);
```

Now, I want to access `$entry->blacklisted_number_id` in the column template for `$entry->phone_number`

So in my view I tried to do:

```
<td style="max-width: {{ isset($column['max_width']) ? $column['max_width'] : 'auto' }}">
@if(isset($entry->blacklisted_number_id))
    // add some other content
@endif
    {{ strip_tags($entry->{$column['name']}) }} 
</td>
```
But I found this doesnt work because it seems only the columns specifically listed in the `columns` for the CRUD controller are selected in the DB query.

If I add the column to the table, it works as expected:

        $columns = [
            [
                'name'  => 'phone_number',
                'label' => 'Phone Number',
                'type'  => 'interaction-phone-number',
            ],
            [
                'name'  => 'blacklisted_number_id',
                'label' => 'Blacklisted number id',
                'type'  => 'text',
            ],
        ]; 

How can I access `$entry->blacklisted_number_id` in the column template for `$entry->phone_number` without explicitly displaying `$entry->blacklisted_number_id`

**Comment by DelightedD0D** [comment]
I was able to work around this issue by doing this:

I set my columns up as:

```
    $columns = [
        [
            'name'  => 'phone_number',
            'label' => 'Phone Number',
            'type'  => 'interaction-phone-number',
        ],
        [
            'name'  => 'blacklisted_number_id',
            'label' => 'Blacklisted number id',
            'column_hide_index'  => 1, // make sure to add 1 if you use $this->crud->enableDetailsRow();
            'type'  => 'hidden',
        ],
    ]; 

```

Then I added a `hidden.blade.php` template:

```
<td>
    <script>
        $("#crudTable").DataTable().column( {{$column['column_hide_index']}} ).visible( false );
    </script>
</td>
```

Adding it here in case someone else needs it or someone wants to add it to the project.

**Comment by scottgrayson** [comment]
I'm about to do the same thing.  I need a `uuid` for one of the row's buttons but I dont want to display that in the table.

@DelightedD0D you are using enableAjaxTable() correct? As far as i can tell, this is only an issue when ajax table is enabled

**Comment by DelightedD0D** [comment]
@scottgrayson That's correct, I'm working with a table that generates about 90K rows per month so ajax is a must.

**Comment by tabacitu** [comment]
Glad you found a solution. Cheers!
