### ISSUE TITLE
Maybe this is better practice?

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/CRUD#723]
This instructions:
https://laravel-backpack.readme.io/docs/crud-fields#section-image

Tells you to create an accessor for image field. 

Problem is, when you want to set field directly, like this:

$model->image="hola_amigos.jpg"

it fails. It becomes a little hard to create something like an "ImageSeeder"

 Maybe it would be better practice to have two fields always:

- image (real database field)
- image_data field (doesn't exist)

Create accessor and mutator for **image_data** 

Accessor and mutator saves data and then sets path in the real field. 

When you want to save the path directly: 
set image field

When you want to upload an image:
set image_data field

example: 

```
    public function getImageDataAttribute(){ <-- image_data doesn't exist in DB
        return $this->image; // <--this is the real field
    }

    public function setImageDataAttribute($value) // <-- image_data doesn't exist in DB
    {
        $attribute_name = "image";

        // if the image was erased
        if ($value == null) {
            // delete the image from disk
            \Storage::disk($this->disk)->delete($this->image);

            // set null in the database column
            $this->attributes[$attribute_name] = null;
        }

        // if a base64 was sent, store it in the db
        elseif (starts_with($value, 'data:image')) {
            // 0. Make the image
            $image = \Image::make($value);
            // 1. Generate a filename.
            $filename = md5($value . time()) . '.jpg';
            // 2. Store the image on disk.
            \Storage::disk($this->disk)->put($filename, $image->stream());
            // 3. Save the path to the database
            $this->attributes[$attribute_name] = $filename;
        }
       
    }

```

**Comment by victorlap** [comment]
Or you could remove the else from the elseif and have just one field:

    public function setImageAttribute($value)
    {
        $attribute_name = "image";

        // if the image was erased
        if ($value == null) {
            // delete the image from disk
            \Storage::disk($this->disk)->delete($this->image);
        }

        // if a base64 was sent, store it in the db
        if (starts_with($value, 'data:image')) {
            // 0. Make the image
            $image = \Image::make($value);
            // 1. Generate a filename.
            $filename = md5($value . time()) . '.jpg';
            // 2. Store the image on disk.
            \Storage::disk($this->disk)->put($filename, $image->stream());
            // 3. Save the path so it can be stored in the database
            $value = $filename;
        }
       
        // set value in the database column
        $this->attributes[$attribute_name] = $value;
    }

**Comment by eduardoarandah** [comment]
@victorlap yes! that works perfect

Why not suggesting that code in docs?

https://laravel-backpack.readme.io/docs/crud-fields#section-image

With original example you can't do

`$model->image="cat_sandwich.jpg"`
