### ISSUE TITLE
URL button (edit, delete)

### ISSUE THREAD

**Issue by giovannylemay** [Laravel-Backpack/CRUD#725]
How to change the href of button edit and delete ? 

I use backpack for study project for https website.
But the href is "http://" .

Thank you

**Comment by lloy0076** [comment]
These are hardcoded into the various prebuilt blade templates, e.g. see:

* https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/buttons/create.blade.php

That said you may publish these templates (instructions can be found [here](https://laravel-backpack.readme.io/docs/install-on-laravel-54#section-2-install-backpackbase)) and override these as you wish.

Depending on your setup you might get away with having the web server (via `.htaccess` or various `nginx` rules or so forth) changing the `http` to `https`.

**Comment by giovannylemay** [comment]
Can you tell me, where is define the path of url()?
<a href="{{ url($crud->route.'/create') }}">

In the file .env or config/app.php ?

**Comment by lloy0076** [comment]
`url()` is one of Laravel's helpers; see https://laravel.com/docs/5.4/helpers#method-url

**Comment by tabacitu** [comment]
Hi @giovannylemay ,

If you use HTTPS on your Laravel app, the buttons will use HTTPS too. Here's a great thread on how to use HTTPS in Laravel: https://laracasts.com/discuss/channels/servers/implementing-https-for-laravel-5?page=1

Hope it helps.

Cheers!
