### ISSUE TITLE
Uploading Image & storing Image name to database 

### ISSUE THREAD

**Issue by warisarain** [Laravel-Backpack/CRUD#726]
Hi, I am using laravel backpack Crud, Laravel 5.4
I've this issue! neither uploading image nor storing correct name of image to database

storing like :  C:\xampp\tmp\php672C.tmp
please help me to solve this issue

MyController
  $this->crud->addField([ // image
            'label' => "Profile Image",
            'name' => "images",
            'type' => 'upload',
            'upload' => true,
            ]);

Model
protected $fillable = [
    'id',
    'name',
    'images',
    'created_at',
    'updated_at',
    'categorytproduct_id'
];
// my own functions
public function setImageAttribute($value) {
// use Intervention image or whatever you want to process that image

$image=$value;
$input['imagename'] = time().'.'.$image->getClientOriginalExtension();
$img = \Image::make($image->getRealPath());

$destinationPath = public_path('/uploads/product');
$img->resize(750, 450, function ($constraint) {
    $constraint->aspectRatio();
})->save($destinationPath.'/'.$input['imagename']);

$destinationPath = public_path('/uploads/product');

$img->resize(100, 100, function ($constraint) {
    $constraint->aspectRatio();
})->save($destinationPath.'/'.$input['imagename']);

//  $image->move($destinationPath, $input['imagename']); // for no resize
$this->attributes['image'] = strtolower($input['imagename']);

}

string in database like that
image
![image](https://cloud.githubusercontent.com/assets/17407050/26816813/12e6a422-4aad-11e7-8971-d6ed79bc89d0.png)

**Comment by AurelDragut** [comment]
the problem seems to be that you use ``` $input['imagename'] ``` instead of  ``` $image->getClientOriginalName ``` in the save().

**Comment by warisarain** [comment]
@AurelDragut did that but still not saving correct name

**Comment by AurelDragut** [comment]
yeah, i missed that ``` $this->attributes['image'] = strtolower($input['imagename']); ``` 
you need to also change here

**Comment by warisarain** [comment]
@AurelDragut did there as well but not working it for me 
I think setImageAttribute($value) is not firing (working)

**Comment by AurelDragut** [comment]
Now that i look again i see you have ```images``` in the ```$fillable``` and not ```image```. what's the name of that column in the db?

**Comment by warisarain** [comment]
In Db the column name is images

**Comment by warisarain** [comment]
Oh, great!
Done thank you so much sir :) @AurelDragut
