### ISSUE TITLE
Have there any way to insert records from CSV in laravel-Backpack CRUD

### ISSUE THREAD

**Issue by warisarain** [Laravel-Backpack/CRUD#727]
Hi,
I want to store data in to more than one table from CSV file, using laravel backpack crud.
is there any way to do it?

**Comment by lloy0076** [comment]
It depends on the structure of your data:

1. Reading from the CSV file is a PHP issue not really related to Backpack (I use [this package](http://csv.thephpleague.com/) in another project but you can use whatever you like);
2. Storing the data really depends on your schema.

We can't answer the **backpack** specific questions without knowing a little more about the second part.

**Comment by tabacitu** [comment]
Hi @warisarain ,

In short, no, there's no way to import data into a Backpack CRUD Panel. It depends so much on your db schema that I'm afraid it's impossible.

Cheers!

**Comment by gumpon** [comment]
Please visit :
https://gist.github.com/harishrkpatel/de7eb03c2e47aa0fd54e1355b6e33b01

**Comment by tabacitu** [comment]
Wow - thanks for pointing to that @gumpon . Related to this - we should probably have an Import Operation add-on at some point in the near future - https://github.com/Laravel-Backpack/addons/issues/13
