### ISSUE TITLE
Multilanguage slugs on page

### ISSUE THREAD

**Issue by justijndepover** [Laravel-Backpack/CRUD#728]
Hi all,

I've created a custom Page Model so i can make my pages multilingual using the [laravel-translatable](https://github.com/spatie/laravel-translatable) package from Spatie. 

This is the beginning of my model.

```php
namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\Sluggable; // was added
use Backpack\CRUD\ModelTraits\SpatieTranslatable\SluggableScopeHelpers; // was added
use Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations; // was added

class Page extends Model
{
    use CrudTrait;
    use Sluggable; // was added
    use SluggableScopeHelpers; // was added
    use HasTranslations; // was added

    protected $table = 'pages';
    protected $primaryKey = 'id';
    public $timestamps = true;
    // protected $guarded = ['id'];
    protected $fillable = ['template', 'name', 'title', 'slug', 'content', 'extras', 'image'];
    protected $translatable = ['slug', 'title', 'content']; // was added
    // protected $hidden = [];
    // protected $dates = [];
    protected $fakeColumns = ['extras'];
```

This seems to be working just fine. I can add / edit pages in multiple languages. However I'm struggling with my implementation on the front-end of my application.

I have a PageController to handle my pages. 

```php
public function index($slug)
{
    $page = Page::findBySlug($slug);
```

This gives me a QueryException: 
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '>'$."en"' = ? limit 1' at line 1 (SQL: select * from `pages` where `slug`->'$."en"' = homepage limit 1)
```

I'm guessing that the error is because my slug is now stored as json.

What am I doing wrong here?

**Comment by lloy0076** [comment]
On a quick glance that:

```
where `slug`->'$."en"' = homepage
```

...is suspect.

What is `$slug`? (i.e. if you did `dd($slug)` or `dump(get_class($slug))` or looked at in a debug bar/debug session, what is it actually)?

**Comment by justijndepover** [comment]
It's `homepage`. But I think the reason is the version of mysql running on my local environment. The Spatie plugin tells us to use either `JSON` or `TEXT` as a data type for all the translatable fields. I use `TEXT` since my version 5.5.49 isn't supporting `JSON` yet.

Since mysql 5.7.8 things like this are supported:
```sql
SELECT
  name,
  tags->"$[0]" AS `tag1`
FROM `book`;
```

Haven't updated my mysql version just yet but I think that's the reason.

**Comment by lloy0076** [comment]
@justijndepover  Ah - so you suspect that the backpack code is using syntax that the version of MySQL doesn't understand?

**Comment by justijndepover** [comment]
I guess yeah. 
Maybe the docs should specify that if you use translatable slugs, you have to use JSON datatypes along with at least mysql 5.7.8.

**Comment by lloy0076** [comment]
@justijndepover - from what I can see this is most likely the case.

@tabacitu - are you able to test?

**Comment by tabacitu** [comment]
Hi guys,

Sounds like it. [This is actually already stated in the documentation](https://laravel-backpack.readme.io/docs/advanced-features#section-translatable-models-and-multi-language-cruds) - do you guys see a better way to mention this?

<img width="632" alt="screen shot 2017-07-18 at 19 33 15" src="https://user-images.githubusercontent.com/1032474/28328696-029aadfc-6bf0-11e7-83af-b2d0b1361767.png">


Cheers!
