### ISSUE TITLE
Admin pages not working (404)

### ISSUE THREAD

**Issue by rohan2812** [Laravel-Backpack/CRUD#730]
Hi there,

Sorry if this issue has already been mentiond before or is already solved somewhere, but I can not find a right solution for the problem i'm encountering right now.

I've tried to install the latest version of Laravel (5.4) and the latest versions of Backpack/Base and Backpack/CRUD. I followed the installation steps exactly from the installation page. But everytime I try, nothing wil work. I can't register an user, login page isn't showing, admin pages are not showing. It's really frustrating cause I'm thinking I am doing something horribly wrong. I've installed it before and worked just fine!

Now I'm trying to install on Windows 10, using WAMP Server v3.0.6 (64bit) with PHP v7.0.10, Apache v2.4.23 and mysql v5.7.14.

Please help.

**Comment by rohan2812** [comment]
So I tried to install Xampp instead of Wamp and that works! I don't know why the Laravel/Backpack combination with Wamp doesn't work though. Maybe this is a known problem already.

**Comment by lloy0076** [comment]
Good to hear that it is fixed, for some definition of "fixed".

Without any further logs - especially anything that might indicate the rewrites for Laravel's default `.htaccess` in the `public/` folder were working - I'd be inclined to claim this is an upstream, Wamp issue and _not_ one to do with backpack.

**Comment by tabacitu** [comment]
Totally agree with @lloy0076 . Anybody else having the issue with Wamp, please bump this. Until then, let's keep it closed.

Cheers!

**Comment by dkisdbest** [comment]
facing same problem with wamp :/
