### ISSUE TITLE
Use bower or npm for dependencies

### ISSUE THREAD

**Issue by AndresOchoaS** [Laravel-Backpack/CRUD#736]
Hi,

You will think that using **npm** or **bower** for manage dependencies is possible be implemented? This is really necessary for quickly and simply update CRUD front-end dependencies.

**Comment by alashow** [comment]
Check out #148

**Comment by OwenMelbz** [comment]
Hi @AndresOchoaS 

Backpack uses AdminLTE which means that the frontend dependencies are fairly tightly coupled with that.

Additionally there are also backpack overrides to make sure things work as expected.

As Backpack is a backend starter, its not really necessary to be running bleeding edge versions as the public would never see it.

Additionally if we introduced npm style management it would require more steps for users, they would even need to integrate any existing gulp/npm/etc to working with backpack.

Overall its much more simple that if you want to update a library, simply download the version you want, put it into the public folder somewhere, and update the template to link to the new version.
