### ISSUE TITLE
Checklist for days of week

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/CRUD#738]
What is the best way to create a checklist field for days of week.

According [to the doc](https://laravel-backpack.readme.io/docs/crud-fields#section-checklist), I need to use a model. Is there any way not using model to create a checklist for days of week?

**Comment by lloy0076** [comment]
At the moment there isn't (but a PR for such a beast wouldn't go astray).

If you only need to select a **single** day of the week you might be able to use a [select2](https://laravel-backpack.readme.io/docs/crud-fields#section-select2_from_ajax).

**Comment by lloy0076** [comment]
(PS. I suspect a `checklist_from_array` would almost be a copy paste of a `select_from_array` [here](https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/fields/select_from_array.blade.php)).
