### ISSUE TITLE
Select2 Multiple - Style Issues

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/CRUD#740]
Select2 Multiple seems to have some style issues, see:

Before: http://joxi.ru/8Anz9YYTbR9MAO
After: http://joxi.ru/zANejXXTEZLM29

(See https://github.com/Laravel-Backpack/CRUD/issues/717#issuecomment-305993723)

@splodgeco reports this fix (see https://github.com/Laravel-Backpack/CRUD/issues/717#issuecomment-307745595).

**Comment by jkudish** [comment]
#746 fixes this

**Comment by tabacitu** [comment]
Merged, it's now on dev, thank you!
