### ISSUE TITLE
[Question] Add other CrudController fields to form via AJAX

### ISSUE THREAD

**Issue by leoortiz** [Laravel-Backpack/CRUD#742]
Hi guys,

I have a select field that decides on change what fields will be shown next. 
I already did the AJAX stuff. 
I created a CrudController class, with the required addFields in setup() method. How can I extract the HTML from this CrudController class, so I can append it to the actual form via AJAX?

**Comment by lloy0076** [comment]
This isn't the same as https://github.com/Laravel-Backpack/CRUD/issues/591 but it needs the same sort of functionality (i.e. get some/all of the HTML generated by the CRUD panel [via the traits]). The only difference is that you'd prefer to get the HTML and append it into the current page whereas 591 wants to put it into a modal dialog.

At the moment it isn't particularly easy to do what you're request _if_ I've understood what you want.
