### ISSUE TITLE
[Support] How I can pass variable by URL?

### ISSUE THREAD

**Issue by kwankongmancalvin** [Laravel-Backpack/CRUD#744]
I am having this in my admin.php

CRUD::resource('xmlfile', 'XmlfileCrudController');

and I changed to this:

CRUD::get('xmlfile/{filetype?}', 'XmlfileCrudController');

but it will collapse the login process...

and some routes with duplicate variable will be created.

|        | DELETE                         | admin/xmlfile/{filetype}/{{filetype}}                        | crud.xmlfile/{filetype}.destroy         | App\Http\Controllers\Admin\XmlfileCrudController@destroy                             | web,admin,Closure |

Please advise!

**Comment by AbbyJanke** [comment]
That is because by using the `CRUD::resource()` it automatically defines all of those routes, my best recommendation would be to pick a new URL as you can't really overwrite it unless you disable the automatic URL generation.

My recommendation would be:

```php
CRUD::resource('xmlfile', 'XmlfileCrudController')->with(function() {
    Route::post('export/{type}', 'XmlfileCrudController@export');
});
```
