### ISSUE TITLE
calling env() functions can cause bugs when we do php artisan config:cache in production

### ISSUE THREAD

**Issue by gotrecillo** [Laravel-Backpack/CRUD#753]
We are using env() to retreive possible enum values from database.
It should be changed to use config and work when we run php artisan config:cache.

It is pretty hidden in the documentation:

https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0

> Configuration
> Environment Value
> 
> Add an env configuration option to your app.php configuration file that looks like the following:
> 
> 'env' => env('APP_ENV', 'production'),
> Caching And Env
> 
> 
> 
> I f you are using the config:cache command during deployment, you must make sure that you are only calling the env function from within your configuration files, and not from anywhere else in your application.
>  
>  If you are calling env from within your application, it is strongly recommended you add proper configuration values to your configuration files and call env from that location instead, allowing you to convert your env calls to config calls.
> 

I have changed it in my fork in a this commit. I have a pending pull request so i will leave the commit here.
https://github.com/gotrecillo/CRUD/commit/24140a495dba5661e32c058a4a336f999f1d43ec

**Comment by AbbyJanke** [comment]
Submitted a PR request for this minor change.

**Comment by lloy0076** [comment]
That's in https://github.com/Laravel-Backpack/CRUD/pull/783 which is currently blocked on review.

**Comment by tabacitu** [comment]
Totally agree - simple solution for simple problem. And we can't consider this a breaking change since it's been available since Laravel 5.2. Let's close this issue and move the conversation inside @AbbyJanke 's PR - #783.

Cheers!
