### ISSUE TITLE
Bootstrap fonts loaded from /vendor instead of /public/vendor

### ISSUE THREAD

**Issue by mklahorst** [Laravel-Backpack/CRUD#755]
The path for the bootstrap fonts is attempting to load directly from the /vendor folder instead of the /public/vendor folder. This is what I see in my console:

`Failed to decode downloaded font: http://sitename.dev/vendor/adminlte/bootstrap/fonts/glyphicons-halflings-regular.woff2`
`Failed to decode downloaded font: http://sitename.dev/vendor/adminlte/bootstrap/fonts/glyphicons-halflings-regular.woff`
`Failed to decode downloaded font: http://sitename.dev/vendor/adminlte/bootstrap/fonts/glyphicons-halflings-regular.ttf`
`Failed to decode downloaded font: http://sitename.dev/vendor/adminlte/bootstrap/fonts/glyphicons-halflings-regular.woff2`
`Failed to decode downloaded font: http://sitename.dev/vendor/adminlte/bootstrap/fonts/glyphicons-halflings-regular.woff`
`Failed to decode downloaded font: http://sitename.dev/vendor/adminlte/bootstrap/fonts/glyphicons-halflings-regular.ttf`

**Comment by OwenMelbz** [comment]
Hi @mklahorst 

This is correct, the "public" folder is never shown in the URL as it's the document root of the web site.

Your error is more likely due to a misconfiguration on the server, missing or corrupt files.

You could try downloading the bootstrap glyphs again and dropping them over the top.

--

As the issue you're having is not directly Backpack related, I'll close this issue to keep the place tidy. Others are still free to try help out :)

**Comment by AbbyJanke** [comment]
I had this issue for a few moments as I had recently changed the URL of my development issue. Check to make sure your URL config is correct depending on if you use `.env` or `/config/app.php`

**Comment by mklahorst** [comment]
Thanks @AbbyJanke  and @OwenMelbz !

Yeah, def a noob question and realized all my paths were correct and indeed, my font files were (in the correct spot).

So, I found this thread: https://stackoverflow.com/questions/18369036/bootstrap-3-glyphicons-are-not-working  and just re-downloaded the files from Bootstrap and replaced them.

That did the trick - not really sure what caused the issue with the original files, but fresh files made the console errors go away and the icons appear.

Thanks again!
