### ISSUE TITLE
select field works, select column not

### ISSUE THREAD

**Issue by salgua** [Laravel-Backpack/CRUD#757]
Hi,
I'm working on last stable release of Laravel-Backpack/CRUD (3.2)
I have a CatalogProduct model, with working relation n-1 to CatalogType model with a standard foreign key "catalog_type_id"

    public function type()
    {
        return $this->belongsTo(CatalogType::class);
    }

the relationship is working fine on Laravel 5.4

I try to display the column with this code:

    $this->crud->addColumns(['catalog_type_id']);
    $this->crud->setColumnDetails('catalog_type_id', [
            'label' => 'Type',
            'type' => 'select',
            'entity' => 'type', // the method that defines the relationship in your Model
            'attribute' => 'code', // foreign key attribute that is shown to user
            'model' => CatalogType::class // foreign key model
        ]);

column is always empty. if I remove the setColumnDetails block it displays the catalog_type_id correctly (but I want to display the attribute code from the catalog_types table).
Using the same syntax to add the field, it works fine. 
I did an SQL debug, it do a strange query:

    select * from `catalog_products`
    select * from `catalog_types` where `catalog_types`.`id` in ('0')

I think the second query has to eager load the relationship, but it returns an empty array.
I also tried to force eager load adding

   $this->crud->with('type'); 

but without success. Any help is very appreciated!

**Comment by lloy0076** [comment]
Is an n-1 relationship simply another way to say 1-n relationship (or do you mean something subtly different)?

**Comment by salgua** [comment]
It's a simply 1-n relationship (1 product belongs to 1 type, 1 type has many products). Relationship is managed by "catalog_type_id" column and defined in both eloquent models (belongsTo and hasMany).

**Comment by salgua** [comment]
Hi guys, any news? I'm encountering this problem on different installation with different model relationship. Same code works for field but it doesn't work for column.

**Comment by tabacitu** [comment]
Hi @salgua ,

Try passing the full path to the class:

```
[
   // 1-n relationship
   'label' => "Type", // Table column heading
   'type' => "select",
   'entity' => 'type', // the method that defines the relationship in your Model
   'attribute' => "code", // foreign key attribute that is shown to user
   'model' => "App\Models\CatalogType", // foreign key model
]
```

**Comment by salgua** [comment]
Hi @tabacitu,
thank you for your attention. I already tried that, but without success. 
Thank you
Salvatore

**Comment by tabacitu** [comment]
Hi @salgua ,

I'm pretty sure it's a problem with your code, not Backpack. Otherwise the issues section would have EXPLODED by now, but so far you seem to be the only one with this issue.

All I can say is that the problem definitely lies where you define the column, or within the relationship. Sorry I can't be of more help.

Cheers!

**Comment by tarmo1979** [comment]
Hi @salgua,

did You found solution?

I am getting similar error:

There is no column with name 'customer_id' on table 'objects'.

$this->crud->addField([
            'label' => 'Customer',
            'type' => 'select2',
            'name' => 'customer_id',
            'entity' => 'Customer',
            'attribute' => 'name',
            'model' => "App\Models\Customer",
        ]);

**Comment by kevuno** [comment]
I too encountered the same error. All my other columns with relationships work, but this one is different somehow. Did anyone find a solution yet?

**Comment by tabacitu** [comment]
**Pro tip:** When debugging a select field/column (or the relationships they need), you can skip the ```model``` attribute altogether. Backpack should be able to get it automatically if from "entity" (which should be the same as the relationship on your model, which should include the connected model in the hasOne, hasMany etc statement). Sometimes NOT defining the ```model``` attribute actually helps debugging, because it makes it easier to spot where the misconfiguration is.
