### ISSUE TITLE
Call to a member function pluck() on array select_multiple

### ISSUE THREAD

**Issue by jkirkby91-2** [Laravel-Backpack/CRUD#762]
I've added a field to my crud controller to pick from another entity named 'staff' like this

		$this->crud->addField([
			'label' => "Staff",
			'fake' => true,
			'type' => 'select2_multiple',
			'name' => 'Staff',
			'entity' => 'Staff',
			'attribute' => 'name',
			'model' => "App\Models\Staff",
			'pivot' => false,
		]);

when creating content it shows the associated entities, I can select them and store them.
But when i go to edit the piece of content, i get this error

Call to a member function pluck() on array (View: /srv/clients/you/vendor/backpack/crud/src/resources/views/fields/select_multiple.blade.php) 

The offending line is

					@if ( (isset($field['value']) && in_array($connected_entity_entry->getKey(), $field['value']->pluck($connected_entity_entry->getKeyName(), $connected_entity_entry->getKeyName())->toArray())) || ( old( $field["name"] ) && in_array($connected_entity_entry->getKey(), old( $field["name"])) ) )

Any idea how to fix?

Thanks

**Comment by lloy0076** [comment]
It's assuming that `$fields->['value']` is some sort of object (probably an `Illuminate\Support\Collection`) that has the `pluck` method.

As a temporary fix (to see if I'm right) you could change the $field['value'] into a collection using the `collect()` helper or the Façade (which I think should be available in a view).

```
# instead of $field['value']->pluck...
# collect($field['value'])->pluck..
```

**Comment by tabacitu** [comment]
@jkirkby91-2 I believe specifying ```		'pivot' => true,``` will fix it for you. Let me know if it doesn't.

Cheers!
