### ISSUE TITLE
Image field: 'prefix' doesn't work

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/CRUD#763]
I don't see the image when clicking "update" 

Prefix doesn't seem to work

I save image in:
/public/uploads/avatars/logo1.jpg

In database:
logo1.jpg

In controller
```

$this->crud->addField([ // image
            'label' => "Imagen",
            'name' => "imagen",
            'type' => 'image',
            'upload' => true,
            'crop' => true, // set to true to allow cropping, false to disable
            'prefix' => 'uploads/avatars/'
        ]);
```

**Comment by AurelDragut** [comment]
how does your setImageAttribute() looks?

**Comment by eduardoarandah** [comment]
mutator:

```
public function setImagenAttribute($value)
    {
        $attribute_name = "imagen";
        $disk           = "anuncio-imagen";

        // if the image was erased
        if ($value == null) {
            // delete the image from disk
            \Storage::disk($disk)->delete($this->image);

            // set null in the database column
            $this->attributes[$attribute_name] = null;
        }

        // if a base64 was sent, store it in the db
        if (starts_with($value, 'data:image')) {
            // 0. Make the image
            $image = \Image::make($value);
            // 1. Generate a filename.
            $filename = md5($value . time()) . '.jpg';

            // 2. Store the image on disk.
            \Storage::disk($disk)->put($filename, $image->stream());

            // 3. Save the path to the database
            $this->attributes[$attribute_name] = $filename;
        }
    }
```

config.filesystems
```

    'disks' => [
...
        'anuncio-imagen' => [
            'driver'     => 'local',
            'root'       => public_path('uploads/anuncio-imagen'),
            'url' => env('APP_URL').'/uploads/anuncio-imagen',
            'visibility' => 'public',
        ],

    ],
```

- creation works perfect
- when updating, image is there, but not visible because prefix is ignored

![abc](https://user-images.githubusercontent.com/4065733/27654070-b8e51c22-5c06-11e7-9692-f8a50824d453.png)

**Comment by AurelDragut** [comment]
Yes, that is right: the prefix is ignored because it is not used in the mutator. I am not even sure you can do this trick, so i think 'prefix' attribute is useless at the moment, that means you have to store the path also in the database field.

**Comment by eduardoarandah** [comment]
I don't think that's convenient

Because there would be two places responsible for the path: the disk and the field

- The disk must be responsible for the first part of the path
- The field for the second part

That way, storing is easy: 

`$this->uploadFileToDisk($value,$fieldname,$disk,"");`

Getting file to make thumbnails:
```

$image=Image::make(Storage::disk($disk)->get($this->imagen));
        //http://image.intervention.io/api/resize        
        $image->resize(326, null, function ($constraint) {
            $constraint->aspectRatio();
        });
        Storage::disk($disk)->put('cuadrado/'.$this->imagen,$image->stream());
```

Generating url to use in front

`Storage::disk($disk)->url($this->imagen);`


What do you think?

**Comment by AurelDragut** [comment]
Yeah, you are right. You just have to figure out why the prefix is not working. I haven't used yet ``` Storage ``` to get the image urls, i just figured that out now :).

Did you add that dump command?

**Comment by eduardoarandah** [comment]
found it!

vendor/backpack/crud/src/resources/views/fields/image.blade.php

Line 9 should be: 

`<img id="mainImage" src="{{ url((isset($field['prefix']) ? $field['prefix'] : '') . (old($field['name']) ? old($field['name']) : (isset($field['value']) ? $field['value'] : (isset($field['default']) ? $field['default'] : '') ))) }}">
`

Sorry, I didn't see it was **fixed** in this commit: 

**18 Apr 2017**
https://github.com/Laravel-Backpack/CRUD/commit/394ae862080f16dcad02e3a47a210fe919c5b42b
