### ISSUE TITLE
Initial value of date picker can be a day off

### ISSUE THREAD

**Issue by gluxon** [Laravel-Backpack/CRUD#768]
**(A) what you did**: I created a `date` type in MySQL and added a field of the type `date_picker`
```php
$this->crud->addFilter([ 'name' => 'publish_date', 'type' => 'date_picker']);
```

**(B) what you expected to happen**: The date stored in MySQL is `2017-07-01`, so I expected the date picker to show `07/01/2017`

**(C) what happened**: The date picker showed me `06/30/2017`

**(D): what have you already tried to fix it?**: Open merge request available here: https://github.com/Laravel-Backpack/CRUD/pull/767

I believe this only happens for users on Firefox with a negative UTC offset.

**Comment by ethanclevenger91** [comment]
Also experiencing this problem in Google Chrome. More details available if needed.

**Comment by tabacitu** [comment]
Thank you for the PR @gluxon ! Let's continue the conversation there. Cheers!
