### ISSUE TITLE
Manage output of the column or add custom css/js to main table

### ISSUE THREAD

**Issue by fencer-md** [Laravel-Backpack/CRUD#77]
Salutare!

I have a question, I'm dealing with a CRUD for slideshow and I would like to see thumbnails of images in table of entries. At the moment I have path of the files I have uploaded I would like to have possibility to build custom types of column output or at least a possibility to add custom JS.

Multumesc

**Comment by tabacitu** [comment]
Hi @fencer-md ,

If you're using CRUD 3.0+, you can do that using a [custom column type](https://laravel-backpack.readme.io/docs/crud-columns-types#roll-your-own).

If you're using CRUD 2.x, you can do the same thing by overwriting the ```list.blade.php``` file (just place one with the same name in your ```app/views/vendor/backpack/crud``` folder) and  adding your own column type along the existing ones.

--

Image thumb column type is a pretty common usage, so we'll include it in the core pretty soon. I have [some thoughs about this column type](https://github.com/Laravel-Backpack/CRUD/issues/64), if you create something similar [or better :-) ] and would like to contribute with it, I'd be more than happy to merge your pull request.

Cheers!

**Comment by tabacitu** [comment]
Hi @fencer-md ,

Have you got this figured out? Can I close the issue?

Cheers!

**Comment by tabacitu** [comment]
I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
