### ISSUE TITLE
Hide action buttons of entry

### ISSUE THREAD

**Issue by mounssif** [Laravel-Backpack/CRUD#773]
Is it possible to hide the action buttons of a entry? I am doing it this way

```
<?php
foreach ($this->crud->getEntries() as $entry) {

                $voucher = Voucher::where('id', (int)$entry->id)->first();
                if($voucher['status'])
                {
                    if ($voucher['status'] == 'scanned') {
                       echo '<style>tr[data-entry-id="'.$entry->id.'"] > td:last-child { display: none; }</style>';
                    }
                }

        }
?>
```

And protected with middleware
```
<?php
 if ($request->is('admin/voucher/*')) {
            $id = $request->route('voucher');
            if (Voucher::where('id', (int)$id)) {
                $voucher = Voucher::where('id', (int)$id)->first();

                if ($voucher['status']) {
                    if ($voucher['status'] == 'scanned') {
                        abort(403);
                    }
                }
            }
        }
?>
```

It works fine
Result:

![image](https://user-images.githubusercontent.com/17242991/27864599-81f111f6-618f-11e7-9511-8ddee92f31e9.png)

Now the problem is if you open your element inspector and you select the action button element you can change 'display:none;' to display:block; and you can view the buttons again, somebody a safer solution?

**Comment by lloy0076** [comment]
@mounssif - even if the buttons weren't even *there* the end users could use (postman)[www.getpostman.com/] and send the actions.

To be more secure:

1. Hide the buttons (or figure a way to remove them from the DOM which I think you probably can if you can figure out how to hide them using CSS :P)
2. Also protect the actions (think Guards, other authorisation methods)

Whatever you do, remember security is about *allowing* authorised users to do what they need to do, as easily as you can make it and if something is *so secure* it's *unusable* it's **not** secure it's **unusable** :)

**Comment by tabacitu** [comment]
@mounssif - consider creating custom buttons that do the same, but have your authorization logic inside them too. This way you'll make sure the button HTML isn't echoed.

Also take into consideration you need this authorization logic inside your controller, too, to prevent users from doing this if they manually type the URL, just like @lloy0076 said.

Cheers!
