### ISSUE TITLE
datetime picker keyboard edition

### ISSUE THREAD

**Issue by gabva** [Laravel-Backpack/CRUD#780]
Hi,

I have a little problem with the datetime picker. 
The demo shows that it is possible to edit the date directly with the keyboard. (or delete a picked date)
When i'm using it on backpack, i'm not able to use it in a normal way and i must use the picker. Looks like a read only input

I have looked inside the codebut did not see something about that

Anyone can help me ? :)

Thanks in advance

**Comment by AbbyJanke** [comment]
Hi @gabva,

Can you include the code you are using for your view? Are you using `date` or `date_picker`? The example uses `date`. If you are using `date_picker` it forces the use of the picker.

**Comment by lloy0076** [comment]
@gabva - also what browser / browser combinations are you using? I only ask because "different standards invite implementers to implement them in different and surprising ways."

**Comment by tabacitu** [comment]
Long time no follow-up. Let's close this :-)

Cheers!
