### ISSUE TITLE
latest update 3.2.13 breaks the model_function column

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#784]
Just updated to CRUD 3.2.13 and now it requires to have 'name' for column model_function.

This was working fine previously and doc doesn't mention this new requirement.

![2017-07-11 001776](https://user-images.githubusercontent.com/26375917/28065891-d5032706-6664-11e7-94e4-b3da7ba1216e.png)
![2017-07-11 001775](https://user-images.githubusercontent.com/26375917/28065900-db3aab3a-6664-11e7-877f-0749a57e81d3.png)

**Comment by adbmdp** [comment]
I agree. I've spend some time looking for this bug...

**Comment by deepslam** [comment]
Yes, I agree with it too.
model_function columns do not work.

**Comment by nlubello** [comment]
Up, same problem downgraded to 3.2.12 works ok

**Comment by MickaelTH** [comment]
You don't need to downgrade, just add

'name' => 'whatever_name',

in your CRUD Controller and it will work. But pretty surprised this wasn't backwards compatible.

**Comment by deepslam** [comment]
But if you have many controllers which use  model_function it can be big work :)
That's why this issue has to decide in the near future.

**Comment by MickaelTH** [comment]
Of course this is why I'vve opened this issue. For me fix is simple, if 'name' doesn't exist then create a fake one.

**Comment by splodgeco** [comment]
I have the same issue and as I use a custom CrudController and CrudPanel I was able to fix this in my custom CrudPanel class.

I have commented on the commit (https://github.com/Laravel-Backpack/CRUD/commit/1003c9984b0062f9466a2843c541c17e02017dfd) that caused this issue.

**Comment by tabacitu** [comment]
Damn. So sorry guys. This did not come up in my testing at all. This is why the PRs get so long to merge - it's always super-tricky to test everything, every time. 

I've just pushed @splodgeco 's fix on ```dev``` - thanks a lot. Could you guys please confirm this fixes it for you? Just use ```dev-dev``` for Backpack\CRUD in your ```composer.json``` file and run ```composer install```. It should pick it up right away.

I guess in the future there should be more of us using the ```dev``` branch during development, so we can spot these earlier on? Would be a big help, if any of you can do it.

**Comment by MickaelTH** [comment]
Thanks for the fix, I looked at the code and this is exactly what we wanted ;)

**Comment by alashow** [comment]
@tabacitu the fix doesn't cover my case:
I have a custom column type. I used it 3 times in my controller. I had to add `name` attribute to column even I didn't need it, because it was throwing an exception If I don't add it. 
So I was using `id` as `name` attribute. It was working okay. But now, only one of them shows in columns (the last one only).

**Comment by alashow** [comment]
@tabacitu Apparently, the "random column name" fix doesn't work on AjaxTables. We need to exclude it from column names.
