### ISSUE TITLE
How to add links to crud controllers on main admin section route?

### ISSUE THREAD

**Issue by przemoli** [Laravel-Backpack/CRUD#786]
Hi. So I've added new crud controllers, and they work fine.
Just can't find where to add some entries so that those controllers show up on main admin page.
(One You get redirected to if You log into Backpack CRUD admin section)

Please help.

**Comment by lloy0076** [comment]
When you say "on" what do you mean:

1. In the menu (usually to the left)?
2. On the big white space where you'd expect there to be content?
3. Something else entirely?

**Comment by jsiebach** [comment]
You need to edit `sidebar.blade.php` if I'm reading your question right.

**Comment by tabacitu** [comment]
Or overwrite the ```dashboard.blade.php``` file if I'm reading your question right :-)

**Comment by przemoli** [comment]
Thx! Needed to change sidebar template.

PS Where are docs? I think it's omitted from then, but I can send pull request.
