### ISSUE TITLE
Image name is not store, it store path instead of name. 

### ISSUE THREAD

**Issue by anand007pandey** [Laravel-Backpack/CRUD#789]
```php
public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'details' => 'required',
            'userpic' => 'required',
        ]);
   
        $userpic = time().'.'.$request->userpic->getClientOriginalExtension();
        $request->userpic->move(public_path('avatars'), $userpic);
        Product::create($request->all());
        return redirect()->route('productCRUD.index')->with('success','Product created successfully');
    }
```

**Comment by anand007pandey** [comment]
Its look the saved column like this:
C:\xampp\tmp\php4BDC.tmp

**Comment by anand007pandey** [comment]
![image](https://user-images.githubusercontent.com/25679795/28167387-1f0aceb8-67f9-11e7-89bb-272d48e34eae.png)

**Comment by tabacitu** [comment]
Hi @anand007pandey ,

This looks like custom code, not Backpack, so I'm afraid I can't help you debug it.

Cheers!

**Comment by anand007pandey** [comment]
Hi tabacitu,

Thanks for your reply. I solved the problem. I have upload the code here for future reference for someone who stuck.

public function store(Request $request)
    {
        $this->validate($request, [
            'name'        => 'required',
            'details'     => 'required',
            'userpic'     => 'required'
        ]);
        $fileName = time().'.'.$request->userpic->getClientOriginalName();
        $request->userpic->move(public_path('avatars'), $fileName);
        $input = $request->all();     //Here its object of all input value
        $input['userpic'] = $fileName;     //Assign file name here  
        Product::create($input);  
        return redirect()->route('productCRUD.index')->with('success','Product created successfully');
    }
