### ISSUE TITLE
Error: No hint path defined for [backpack]

### ISSUE THREAD

**Issue by dennisc1** [Laravel-Backpack/CRUD#79]
I'm getting the following error

> No hint path defined for [backpack]. (View: /var/www/laravel/vendor/backpack/crud/src/resources/views/list.blade.php)

it seems when laravel is trying to load the view, it can't find the _backspace_ hint when trying to load layout trough `@extends('backpack::layout')`
I tried to debug the process. There I found it did find the _crud_ hint. So some hints do get loaded, except for backspace.

I found some stackoverflow issues related to similar problems, which stated the hints are declared in the ServiceProvider. I tried clearing the config:cache to avoid conflicts. However, I couldn't find the issue

I'm installing Backpack/CRUD on an existing project. I tried to reïnstalling CRUD and made sure I completed all the steps, including publishing all the files as remmended in #32. 

Laravel 5.2.41
I'm on Docker for Windows with Laradock as container
PHP-FPM 7.0
NGINX

**Comment by dennisc1** [comment]
So I found the issue. 
The _backpack_ hint and the blade templates it is calling, are from backpack/base. I only installed the CRUD, so I was missing the files and the necessary service provider.

So the instructions for the crud [install guide](https://github.com/Laravel-Backpack/CRUD#install) are incorrect. The steps are explained how to only install CRUD. So you miss the backpack/base layout files it is calling.

So in my opninion there are two options:

- one should edit the view files, to use their own layout. This should be documented for the crud-only users
- one has to install and publish the base files. this should also be documented

**Comment by tabacitu** [comment]
Damn... you're totally right @dennisc1 , if you're only looking at Backpack\CRUD and not the [online documentation](https://laravel-backpack.readme.io/docs/installation), you have no idea you need to do the steps in Backpack\Base too, for it to work.

I've updated the documentation to mention that. Thanks a lot! I think this might have been turning a lot of people down.

Cheers!

**Comment by dennisc1** [comment]
@tabacitu thanks for the quick reply and update of the docs.
However, does this mean the Backpack\CRUD package should always be used in combinations with Backpack\Base. I love the combination of the two for my current project. However, the Backpack\CRUD package is a very useful and powerful package on itself. In my opinion people should be able to use this package without having to use the Backpack\Base. The CRUD package can already of great use without the AdminLTE etc. of the Base package.
I think it is still possible to change the published view files, so it doesn't use the _backpack:layout_ but your own layout. However, this isn't very clear for the users.
So my advice. Either somehow decouple the packages, or document how the CRUD package can be used as standalone package..

Anyway, great package. Well maintained and you can clearly see progress in this repository. Keep up the good work!

**Comment by tabacitu** [comment]
Hi @dennisc1 ,

I'm not gonna lie - the only reason it's not decoupled is because the packages have gotten a lot more attention than I expected. So now I'm rushing to deliver all major features, to please the users that are already using it, rather than appeal to new users that would like to use it without the AdminLTE front-end. But in a few months things will probably settle and we'll have time to think this through. And yes, decoupling is on the roadmap, it's just not anywhere close right now.

I'm sorry if this lets you down, but I don't want you to use it in the hope that it gets decoupled anytime soon and then be disappointed.

Thank you for your contribution. Cheers!

**Comment by dennisc1** [comment]
No problem. I can see the work your putting in to it right now and it's becoming a great package. So I  understand that you put on the roadmap for later.

**Comment by poseso** [comment]
I'd love to see it as a standalone package, I don't really like AdminLTE

**Comment by tabacitu** [comment]
@poseso , themes will come in a few months. You'll be able to use different premium themes on ThemeForest & similar, by just dragging&dropping some folders in your package. [Subscribe to the newsletter](https://laravelbackpack.us13.list-manage.com/subscribe?u=481cc18afdb1e440e3dbfc3a4&id=fc930b1077) if you haven't already, and you'll find out as soon as it's launched.

Cheers!
