### ISSUE TITLE
Possibility to have detail screen

### ISSUE THREAD

**Issue by nielvrom** [Laravel-Backpack/CRUD#790]
I now have an overview of users in my backoffice (created with backpack). In my database I also have a many to many between my users table and my teams table. 

I don't want to show this information in my table. Is it possible to have a show page (= detail page) where the relation items are shown? So that the user has to click on the name in the row and then goes to a detail page.

![table overview][logo]

[logo]: https://preview.ibb.co/jHoMua/Schermafbeelding_2017_07_14_om_09_55_06.png "Table overview"

**Comment by lloy0076** [comment]
Two ways:

1. Add a custom button to the actions (which are the Edit/Delete buttons in the image shown);
2. Make a custom field for 'name' that wraps the 'name' text in a link or something.

Personally I'd just do (1) because that avoids a custom field.

**Comment by nielvrom** [comment]
And how can I add a custom button?

**Comment by lloy0076** [comment]
@nielvrom - you're aware there is documentation for Backpack [here](https://laravel-backpack.readme.io/docs/features) are you not?

You'd want https://laravel-backpack.readme.io/docs/crud-buttons.

Be aware that when it says `$stack` it means the values: `top`, `bottom` or `$line`.

**Comment by tabacitu** [comment]
@nielvrom - also, you can use the ```show()``` method inside your controller for previewing the information. Already has the route. 

Hope it helps. Cheers!
