### ISSUE TITLE
enableAjaxTable is Not Working in My CrudController

### ISSUE THREAD

**Issue by usmanhafeez147** [Laravel-Backpack/CRUD#792]
My data is **increased** out of 1000 **records** now when I request for the **crudController** it gave an error **"too many time to respond"** so I read document guide and about **$this->crud->enableAjaxTable();** method to **server side pagination**. It is giving an error. I could not find proper solution for that. please help me regard this.
![image](https://user-images.githubusercontent.com/24206206/28238380-1f82cbf2-6907-11e7-8044-6b833447783c.png)

**Comment by lloy0076** [comment]
@usmanhafeez147 - what is in your `storage/logs/laravel.log` - this happens when an unexpected server side error occurs.

**Comment by usmanhafeez147** [comment]
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function enableAjaxTable() on null in F:\wamp64\www\profinder_dubai\app\Http\Controllers\Admin\CompanyCrudController.php:15
this error log is showing

**Comment by tabacitu** [comment]
Hi @usmanhafeez147 - well where and how did you call ```$this->crud->enableAjaxTable()```?

**Comment by lloy0076** [comment]
@tabacitu - probably line 15 in `\www\profinder_dubai\app\Http\Controllers\Admin\CompanyCrudController.php:15` 👿 

@usmanhafeez147 - what's the content of that file? I'd suspect that `$this->crud` is `null` because that's what PHP is complaining about.  Is it extending the Backpack CRUD controller properly?

**Comment by usmanhafeez147** [comment]
@tabacitu, Yes it's giving the error-log on line No 15. I declared public function **setUp()** there in my **CompanyCrudController**
My CrudController name is CompanyCrudController with model and request. and My controller is extending with CrudController class.
thanks for appreciating as well. I am waiting for Solution. Cheers

**Comment by lloy0076** [comment]
Try renaming `setUp()` to `setup()` although I don't think that will help.

And are you able to post up to and including line 15 (in a code block!) of the controller?

**Comment by usmanhafeez147** [comment]
File Name **CompanyCrudController** and public method **setUp()**
`public function setUp()
    {

        $this->crud->setModel('App\Models\Company');
        $this->crud->setRoute(config('backpack.base.route_prefix') . '/company');
        $this->crud->setEntityNameStrings('Company', 'Companies');
        
        //$this->crud->enableAjaxTable();

        $this->crud->setDefaultPageLength(10);
        
        $this->crud->addFilter([ // add a "simple" filter called Draft 
                              'type' => 'dropdown',
                              'name' => 'city_id',
                              'label'=> 'Cities'
                                ],
                                function() {
                                        $results= \App\Models\City::all(['id','name']);
                                        $values;
                                        foreach($results as $result){
                                            $values[$result->id]=$result->name;
                                        }
                                        return $values;
                                    }, 
                                function($value) { // if the filter is active (the GET parameter "draft" exits)
                                    $this->crud->addClause('where', 'city_id', $value);    
                                });

        $this->crud->addFilter([ // add a "simple" filter called Draft 
                      'type' => 'dropdown',
                      'name' => 'category_id',
                      'label'=> 'Categories'
                    ],
                    function() {
                            $results= \Backpack\NewsCRUD\app\Models\Category::all(['id','name']);
                            $values;
                            foreach($results as $result){
                                $values[$result->id]=$result->name;
                            }

                            return $values;
                           
                        }, 
                    function($value) { // if the filter is active (the GET parameter "draft" exits)
                        $this->crud->addClause('where', 'category_id', $value);    
                    });
                    
                    $this->crud->addColumn(['name'=>'id',
            'label'=>'Company Id',
            'type'=>'number',
            ]);
        $this->crud->addColumn(
            [
            'label' => "Category",
            'type' => 'select',
            'name' => 'category_id',
            'entity' => 'category',
            'attribute' => 'name',
            'model' => "Backpack\NewsCRUD\app\Models\Category"
             ]);

        $this->crud->addColumn(['name'=>'name',
            'label'=>'Merchant Name',
            'type'=>'text',
            ]);
/*
        $this->crud->addColumn(
            [
            'label' => "Username",
            'type' => 'text',
            'name' => 'username',
            
             ]);*/

        /*$this->crud->addColumn(
            [
            'label' => "Short Description",
            'type' => 'textarea',
            'name' => 'short_desc',
            
             ]);*/

        $this->crud->addColumn(
            [
            'label' => "Description",
            'type' => 'ckeditor',
            'name' => 'description',
             ]);

        $this->crud->addColumn(['name'=>'email',
            'label'=>'Merchant Email',
            'type'=>'email',
            ]);


        $this->crud->addColumn(['name'=>'phone',
            'label'=>'Phone No',
            'type'=>'text',
            ]);

        /*
        $this->crud->addColumn(
            [
            'label' => "City",
            'type' => 'select',
            'name' => 'city_id',
            'entity' => 'city',
            'attribute' => 'name',
            'model' => "App\Models\City"
             ]);*/

        $this->crud->addColumn(['name'=>'address',
            'label'=>'Address',
            'type'=>'address',
            ]);

        $this->crud->addColumn(['name'=>'zipcode',
            'label'=>'Zip Code',
            'type'=>'text']);

        $this->crud->addColumn(
            ['name'=>'featured',
            'label'=>'is Featured',
            'type'=>'check'
            ]);

        $this->crud->addColumn(['name'=>'image',
            'label'=>'Merchant Image',
            'type'=>'merchant_image',
            ]);

        $this->crud->addColumn(['name'=>'weblink',
            'label'=>'Web Link',
            'type'=>'url']);

        $this->crud->addColumn(['name'=>'status',
            'label'=>'Status',
            'type'=>'text']);


        // fields
        
        /* $this->crud->addField(['name'=>'business_id',
            'label'=>'Business Id',
            'type'=>'text',
            ]);*/

         $this->crud->addField(
            [
            'label' => "Category",
            'type' => 'select',
            'name' => 'category_id',
            'entity' => 'category',
            'attribute' => 'name',
            'model' => "Backpack\NewsCRUD\app\Models\Category"
             ]);

        $this->crud->addField(['name'=>'name',
            'label'=>'Merchant Name',
            'type'=>'text',
            ]);

        /*$this->crud->addField([
            'label' => "Username",
            'type' => 'text',
            'name' => 'username',
            
             ]);*/
    

        $this->crud->addField(
            [
            'label' => "Description",
            'type' => 'ckeditor',
            'name' => 'description',
             ]);

        $this->crud->addField(['name'=>'email',
            'label'=>'Merchant Email',
            'type'=>'email',
            ]);

       /* $this->crud->addField(['name'=>'password',
            'label'=>'Merchant password',
            'type'=>'password',
            ]);*/

        $this->crud->addField(['name'=>'phone',
            'label'=>'Phone No',
            'type'=>'text',
            ]);

         $this->crud->addField(
            [
            'label' => "City",
            'type' => 'select',
            'name' => 'city_id',
            'entity' => 'city',
            'attribute' => 'name',
            'model' => "App\Models\City"
             ]);

        $this->crud->addField(['name'=>'address',
            'label'=>'Address',
            'type'=>'text',
            ]);

        $this->crud->addField(['name'=>'zipcode',
            'label'=>'Zip Code',
            'type'=>'text']);

        $this->crud->addField(
            ['name'=>'featured',
            'label'=>'is Featured',
            'type'=>'checkbox'
            ]);

        $this->crud->addField([ // base64_image
            'label' => "Merchant Image",
            'name' => "image",
            'filename' => "image_filename", // set to null if not needed
            'type' => 'base64_image',
            'aspect_ratio' => 1, // set to 0 to allow any aspect ratio
            'crop' => true, // set to true to allow cropping, false to disable
        ]);

        $this->crud->addField(['name'=>'weblink',
            'label'=>'Weblink',
            'type'=>'url']);
        
    
    }

    public function store(StoreRequest $request)
    {
        $this->validate($request,[
           
            'name' => 'required',
             'description'=>'required',
             'address'=>'required',
             'zipcode'=>'required',
             'phone'=>'required'
            ]);
        
        if ($request->input('password')) {
    
            $item = $this->crud->create(\Request::except(['redirect_after_save']));
  
            $item->password = bcrypt($request->input('password'));
  
            $item->save();
            
            \Alert::success(trans('backpack::crud.insert_success'))->flash();
            return redirect('admin/company');  
        } else {   
            $item = $this->crud->create(\Request::except(['redirect_after_save', 'password'])); 
             \Alert::success(trans('backpack::crud.insert_success'))->flash();
            return redirect('admin/company');
        }
  
       
    }`

**Comment by lloy0076** [comment]
The above doesn't seem to be up to and including line 15 (line 1 should start with `<?php` or `<?` if you evilly use short opening tags).
