### ISSUE TITLE
[Support] How can I deploy to Heroku?

### ISSUE THREAD

**Issue by NicolasBonet** [Laravel-Backpack/CRUD#794]
Hello all,

I've followed most guides available to deploy a Backpack app to heroku, but so far I've not being able to load the CSS/JS files from the public/vendor folder. My procfile is the following:

web: vendor/bin/heroku-php-apache2 public/

I already have both nodejs and php buildpacks in Heroku, but I don't know what else should I be doing to get this done. I checked manually using heroku bash and in the public folder I don't have any vendor directory.

I would really appreciate if you can help me with this!

**Comment by tabacitu** [comment]
Hi @NicolasBonet ,

Sorry, don't have enough experience in using Heroku - only used it once 2-3 years ago. Maybe someone else in the community does. 

Cheers!

P.S. I am, however, very interested in having a "deploy to heroku" button for Backpack\Demo, so maybe if you figure it out you might want to help with that?

**Comment by Athuli7** [comment]
The procfile should work. From what I can gather, it's the missing vendor folder.
What's the package that is using it? elfinder is under the _packages_ folder.
@NicolasBonet, are there any routes under public being defined in Backpack? I don't remember any.

**Comment by NicolasBonet** [comment]
You guys can close this now, the problem was simply that the vendor folder wasn't generated with Heroku directly, so I simply had to generate it in my local environment and then push the changes to Heroku with a little modification to the .gitignore I had.

About the button, I never used one before, but I do can share how I did it (which was quite simple actually!) if it helps 👍
