### ISSUE TITLE
Set table value before insert

### ISSUE THREAD

**Issue by nielvrom** [Laravel-Backpack/CRUD#795]
I have a database table **sporthalls** with the following fields:

- id
- name
- address
- city
- latitude
- longitude

My form contains **name, address and city**. I would like to get the **latitude** and **longitude** and save them in my database table. I now have the following:

```
public function store(StoreRequest $request)
{
    $address = trim($request->request->get('address'));
    $city = trim($request->request->get('city'));

    $addressObj = app('geocoder')->geocode($address . ', ' . $city)->get()->first();

    if($addressObj)
    {
        $this->data['latitude'] = $addressObj->getCoordinates()->getLatitude();
        $this->data['longitude'] = $addressObj->getCoordinates()->getLongitude();

        $request->request->set('latitude', $addressObj->getCoordinates()->getLatitude());
        $request->request->set('longitude', $addressObj->getCoordinates()->getLongitude());
    }
    
    // your additional operations before save here
    $redirect_location = parent::storeCrud();
    // your additional operations after save here
    // use $this->data['entry'] or $this->crud->entry
    return $redirect_location;
}
```
But the code in my if statement isn't working. Latitude and longitude are still not saved. What am I doing wrong?

**Comment by tabacitu** [comment]
Hi @nielvrom ,

Sounds like it's a problem using using Geocoder, not Backpack. Ask there.

Cheers!

**Comment by nielvrom** [comment]
The problem is not that I'm not getting any values back. The code `$addressObj->getCoordinates()->getLatitude()` works with no problem. Only saving it to my database doesn't work. It looks like I'm doing something wrong in my if statement. How can I set a value before `parent::storeCrud();`?

**Comment by tabacitu** [comment]
Well one way is the way you have - modifying the request. But you should also pass the request as a parameter to the ```storeCrud()``` method:
```php
    $redirect_location = parent::storeCrud($request);
```

Another would be to [use a Mutator on your model](https://laravel.com/docs/5.4/eloquent-mutators) - basically overwriting how Eloquent stores the information in the db for that column.
