### ISSUE TITLE
Ading CSS class to column

### ISSUE THREAD

**Issue by tpresing** [Laravel-Backpack/CRUD#796]
Hi all,

Is it possible without creating a new view?

**Comment by tabacitu** [comment]
Hi @tpresing ,

There is, but not much better. For small CSS, like color status or things like that, I sometimes return the "formatted status" from the model and I use the ```model_function_attribute``` column.

Something like this:
```
<?php

class Product  extends Model
{

public function getFormattedStatus() {
   return "<span class='".$this->status."'>".$this->name."</span>";
}

}
```

But I can't say I'm very proud of including CSS in PHP :-)

Cheers!
