### ISSUE TITLE
Button model_function usage

### ISSUE THREAD

**Issue by adnanfajr** [Laravel-Backpack/CRUD#797]
How to get "id" value in Model Function when custom button is clicked?

or you have another solutions to get id when custom button is clicked, please.

**Comment by iMokhles** [comment]
you can do something like that :)

https://github.com/Laravel-Backpack/CRUD/issues/598#issuecomment-292815100

**Comment by tabacitu** [comment]
Hi @adnanfajr ,

I'll illustrate this using the example from the Backpack demo, the Monster entity:

Inside MonsterCrudController:
```php
        $this->crud->addButtonFromModelFunction('line', 'open_google', 'openGoogle', 'beginning'); // add a button whose HTML is returned by a method in the CRUD model
```

Inside the Monster model:
```php
    public function openGoogle($crud = false)
    {
        return '<a class="btn btn-xs btn-default" target="_blank" href="http://google.com?q='.urlencode($this->text).'" data-toggle="tooltip" title="Just a demo custom button."><i class="fa fa-search"></i> Google it</a>';
    }
```

In the ```openGoogle()``` method you can do anything that you can do inside a regular method. You'll notice the above uses ```$this->text```. Well you can also use ```$this->id``` ;-)

Hope it helps.
Cheers!
