### ISSUE TITLE
[COLUMNS] setColumnOrder()

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#8]
Make this work:
$this->crud->setColumnOrder(['column_1', 'column_2', 'column_3']);

The sorting functionality in the Crud.php file does not work.
Also, I don't think the $crud->sort property makes no sense now.
The sorting should just shuffle the arrays where they are, without storing the order anywhere.

**Comment by tabacitu** [comment]
On second thought, the order is self-evident. You type the columns/fields in an order and that's the order they're shown.

I say... drop it like it's hot.

**Comment by tjventurini** [comment]
Just want to add, you can remove the `$this->crud->setFromDb();` in the Crud Controller and then manually add the columns with `$this->crud->addColumns([...`. Set the order of your columns as you want in `addColumns()`.
