### ISSUE TITLE
How to customize CRUD templates ?

### ISSUE THREAD

**Issue by rzaglinskij** [Laravel-Backpack/CRUD#80]
How to customize CRUD templates  with my own custom buttons ?

**Comment by tabacitu** [comment]
In CRUD 3.x, just place a file in ```resources\views\vendor\backpack\crud\buttons```. See [the docs](https://laravel-backpack.readme.io/docs/crud-buttons).

**Comment by tabacitu** [comment]
Sorry for being so dismissive earlier. It's been a tough week. Does this fix you issue? Ok to leave it closed?
