### ISSUE TITLE
Include extra attributes for $entry in views, not only the ones from columns[]

### ISSUE THREAD

**Issue by Frondor** [Laravel-Backpack/CRUD#800]
Basically, I'm trying to replace both Edit/Delete buttons for Restore/Force delete when an entry is trashed (soft deleted).

I tried using `$this->crud->query->addSelect('deleted_at')` but that will never work, since the datatable package won't take those params.
I want to do `$entry->trashed()` when using SoftDeletes, but I can't because `$entry` doesn't have `deleted_at` attribute in `views/.../crud/buttons/update.blade.php`

If I add a new column with `'name' => 'deleted_at'` then  `$entry->trashed()` works, but I don't want that column to show up in the ajax datatable.

**Comment by tabacitu** [comment]
@Frondor I think there's a solution here for you, but... it won't be pretty... https://github.com/Laravel-Backpack/CRUD/issues/721
