### ISSUE TITLE
select2_from_ajax and allowClear

### ISSUE THREAD

**Issue by adbmdp** [Laravel-Backpack/CRUD#804]
I have a modified select2_from_ajax in which i've add an **allowClear** option. So a user can clear the selection and save.
It was working well but with the last upgrade it's not working anymore. The UI part is working, i have a small cross to remove selection that is working. But when i save, the selected value is still there.
Maybe it's a good idea to have this option by default? Because how to remove the selection without this option ?

```
$("#select2_ajax_{{ $field['name'] }}").each(function (i, obj) {
            if (!$(obj).hasClass("select2-hidden-accessible"))
            {
                $(obj).select2({
                    theme: 'bootstrap',
                    multiple: false,
                    allowClear: true,
                    placeholder: "{{ $field['placeholder'] }}",
                    minimumInputLength: "{{ $field['minimum_input_length'] }}",
                     ....
```

**Comment by lloy0076** [comment]
If you made a PR against the version that worked (perhaps provide an appropriately versioned `composer.json` to help us test), it might be considered an addition?

DSL

**Comment by tabacitu** [comment]
Hi guys. Let's collaborate in the other issue then, see what we can do. Cheers!
