### ISSUE TITLE
How add a custom to Save Action

### ISSUE THREAD

**Issue by niltonmeloba** [Laravel-Backpack/CRUD#805]
Hi Team,
Thanks so much for the fantastic Backpack. Please, I need to know how add (display) a custom action option on Button Save, ex: 'Save and Send' 
I need save and send um mail after it.
Thanks

**Comment by rzaglinskij** [comment]
you can
1) add custom button(functionality already provided by backpack crud)
2) create custom route, like `CRUD::resource('subscribers', 'Admin\SubscribersCrudController')->with(function(){
        Route::get('subscribers/export', 'Admin\SubscribersCrudController@export');
        Route::any('subscribers/{id}/edit/', ['as' => 'subscriber.edit', 'uses' => 'Admin\SubscribersCrudController@edit']);
    });`
3) copy/paste vendor saving functionality into your controller and add functionality you want

- OR - 
if you want just to send email(or have some custom functionality), you can do this using Laravel basic functionality. Inside AppServiceProvider -> boot method -> Incident::updated(function ($incident) {. this will triggered when model updated.

**Comment by webdesign7** [comment]
@nathanielks hey did you find a solution to your problem as I need to do same thing ?
