### ISSUE TITLE
[4.0][Bug] Multiple TinyMCEs across different tabs causes issues

### ISSUE THREAD

**Issue by baj84** [Laravel-Backpack/CRUD#808]
Hey,

I have multiple tabs, with 3 tinymce fields on the first tab and then another on the second tab.

There are no javascript errors, but when I change the text of the tinymce on the second tab and click save it does not get updated or saved. In fact the request for that field is empty, so it seems like tinymce isn't properly registering that instance and keeping it up to date.

I thought it may be some sort of race condition where the first instances are being loaded and then the second tab instance gets ignored. When I change the fields to all be on the same tab it works fine.

Has anyone had any similar issues? Thanks!

**Comment by lloy0076** [comment]
@baj84 - have you seen a TinyMCE field (with backpack) work without a tab? I do believe that it may have issues with multiple tabs but I'm just wary of trying to differentiate between tabs, TinyMCE and backpack issues.

**Comment by baj84** [comment]
I have fixed this issue by applying the tab name (if there is one) to the tinymce selector and textarea class, e.g:
`selector: "textarea.tinymce_{{$tab}}"
<textarea
        	id="tinymce-{{ $field['name'] }}"
            name="{{ $field['name'] }}"
            @include('crud::inc.field_attributes', ['default_class' =>  'form-control tinymce_' . $tab])`

**Comment by lloy0076** [comment]
@baj84 - so that's in the `resources/views/vendor/backpack/crud/` (and whatever the rest would be)?

(or the one in vendor if you overrode it directly)

??

**Comment by baj84** [comment]
Yeah, that's right - the one in the resources folder. I'm not sure why that bug occurs, but adding the tab name to the class does fix it.

**Comment by lloy0076** [comment]
If I recall, multiple tabs probably has all the tabs in the DOM but some hidden; Bootstrap would have to know of the other tabs somehow. So, if they all have the same ID (which is bad HTML but most HTML renderers will allow it to display) then odd things can happen...

**Comment by lloy0076** [comment]
There is a fix [here](https://github.com/Laravel-Backpack/CRUD/issues/808#issuecomment-320504138).

Closing - if a PR turns up, please reopen.

**Comment by pxpm** [comment]
I tried this out. With more than 20 tinymce in multiple tabs. Everything works as expected.

Closing this, as no further complains arised for long time.
