### ISSUE TITLE
A Field's Value is Automatically Filled W.R.T First Field's Value is Selected

### ISSUE THREAD

**Issue by usmanhafeez147** [Laravel-Backpack/CRUD#809]
## A Field's Value is Automatically Filled With Respect To First Field's Value is Selected
Hello to all, Hope you all are well!

I am using **Laravel Backpack** for Admin Panel that is seemed fully functional.
A want to implement some functionality on My **OrderCrudController** Fields.
I have one Field named **project_id** and type is **select** and other field named **price** type is **number**.

I want that price field should automatically fill with respect to which project I have selected from projects table. project table has price attribute

**Comment by lloy0076** [comment]
If I understand you correctly there isn't any default functionality for what you describe; essentially you'd need to implement something like:

1. A listener to detect when the select field has changed;
2. A way to insert the correct price into the price field.

Both would be in JavaScript.  Obviously, the precise code depends on how one would implement this (e.g. would one pass all the possible values, including the prices OR would the code that inserts the price be an AJAX like call).

One might even consider using Vue or React but that would be overkill for what you're describing.

You'd also have to consider what should happen on "edit/update" (e.g. can the project_id change and if so, if someone has updated the price field, should it keep the old price or gain the new "default" price).
