### ISSUE TITLE
Add html attributes to the Fields arrays

### ISSUE THREAD

**Issue by dennisc1** [Laravel-Backpack/CRUD#81]
Besides defining things like _name_ and _label_ it should be possible to define html attributes in the Field array. By adding a parameter _attributes_ or _htmlAttributes_ (to avoid conflicting naming with the _attribute_ parameter), one can pass data to the input element. In this way one can 

- pass an id attribute to the element, so it can easily be selected by javascript DOM
- pass a class attribute, for custom styling
- pass the disabled attribute, for only showing a field the user is not allowed to edit (id field for example)

In my opinion the best way to declare it is as follows
`'attributes' => [
'id' => 'field-id',
'disabled' => true
]`

sadly I won't be able to contribute to the project for the next month, so I cannot pick this up myself. Hopefully somebody can look into it, it should be a difficult addition

**Comment by tabacitu** [comment]
Hi! 

We got that covered already! All fields have:
- attributes
- wrapperAttributes

Check out the docs. I will too - they're probably not clear enough.

Cheers!

**Comment by tabacitu** [comment]
Sorry for being so dismissive earlier. It's been a tough week. Does this fix you issue? Ok to leave it closed?

**Comment by dennisc1** [comment]
Yes, this is what I was looking for. Guess I missed it in the docs. 
No problem for 'dismissive' comments, you're doing great work on the project

**Comment by tabacitu** [comment]
Great to hear that. Yes, the docs need an overhaul in order to be easily read and understood. I'm currently trying to find a way to do that but it's more difficult than anticipated. I'll get it right eventually though, I'm sure :-)
