### ISSUE TITLE
[QUESTION] Datetime icon click

### ISSUE THREAD

**Issue by MickaelTH** [Laravel-Backpack/CRUD#810]
Hi,

How to make the button clickable on the datetime please? Tried stuff from https://eonasdan.github.io/bootstrap-datetimepicker/ but no result so far.

**Comment by tabacitu** [comment]
Ugh. I'd also like that. It's low-prio, of course, but my OCD won't let me be :-)

Have spent a reasonable amount of time on this when creating/merging the datetime field and no solution seemed to work. I said I'd come back to it with a clear head, but never did. Let's keep this open until we find a solution.

Cheers!

**Comment by MickaelTH** [comment]
@tabacitu Thank you for confirming this. I did spent few hours on it too but can't make it works either.

**Comment by ihsanberahim** [comment]
It works for me.

https://github.com/Laravel-Backpack/CRUD/pull/1097
