### ISSUE TITLE
[Question] Table element with base64_image

### ISSUE THREAD

**Issue by lavodka** [Laravel-Backpack/CRUD#811]
How I can create a custom element like a "table" with "base64_image"?

**Comment by tabacitu** [comment]
Hi @lavodka ,

I'd say start from the ```table``` field type and [roll your own](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types). Will be a lot of work, though, and if the user adds a lot of images, and big ones too, your request might end up being very VERY large, and it would take A LOT of time after clicking the submit button. So I wouldn't use base64_image if I were you... Maybe use "browse" fields instead?

Hope it helps.
Cheers!
