### ISSUE TITLE
Number field decimal shows wrong value

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [Laravel-Backpack/CRUD#814]
Hi all,

When i use a number field like in the example, the field shows 2100 but the html value is 21,00
it's a float in the database and in PHP perhaps it has something to do with browsers in other languages wich have a , in stead of a .

```
[   // Number
    'name' => 'number',
    'label' => 'Number',
    'type' => 'number',
    // optionals
    // 'attributes' => ["step" => "any"], // allow decimals
    // 'prefix' => "$",
    // 'suffix' => ".00",
],
```

**Comment by tabacitu** [comment]
Hmm... What if you uncomment the attributes above, to allow decimals?

**Comment by lloy0076** [comment]
What is `21,000` - is that twenty-one point zero zero OR twenty-one hundred (or something else)?

**Comment by tabacitu** [comment]
Hi guys. Just tested, with the allow decimals above it works: https://cl.ly/111y3i2R3A0V

Cheers!
