### ISSUE TITLE
Update single field before storing on database

### ISSUE THREAD

**Issue by inquisitive-stha** [Laravel-Backpack/CRUD#815]
$request->request->set('added_date',date('Y-m-d H:i:s'));
      //  p($request->request);
       // exit();
        $redirect_location = parent::storeCrud();
        return $redirect_location;

At this moment $request->request holds as

[name] => kkk
 [address_id] => 1
 [image] => uploads\tpm15e_pn1e.jpg
 [description] => hh
 [status] => 1
 [save_action] => save_and_back
 [added_date] => 2017-08-02 11:22:36

But still, it is storing 0000-00-00 00:00:00 on the database. What is the problem? Is it because added_date is below the save action? How can I edit a single field like this before storing?

**Comment by victorlap** [comment]
You need to do 

```$redirect_location = parent::storeCrud($request);```

Otherwise crud cannot see your changes to the `$request`
