### ISSUE TITLE
There are problems with button the remove filters and type date_range

### ISSUE THREAD

**Issue by eddilou** [Laravel-Backpack/CRUD#816]
By clicking on the delete filters button, the query goes to infinity
The problem lies in this code
```javascript
// mark this filter as active in the navbar-filters
if (URI(new_url).hasQuery('{{ $filter->name }}', true)) {
	$('li[filter-name={{ $filter->name }}]').removeClass('active').addClass('active');
} else {
	$('li[filter-name={{ $filter->name }}]').trigger('filter:clear');
}
```
The controller has a filter
```php
 $this->crud->addFilter([
            'name' => 'date',
            'type' => 'date_range',
            'label' => 'Date Range',
        ],[],
            function($value) {
                $dates = json_decode($value);
                    $start = Carbon::parse($dates->from)->format('Y/m/d');
                    $end = Carbon::parse($dates->to)->format('Y/m/d');
                    $this->crud->addClause('where', 'date', '>=', $start);
                    $this->crud->addClause('where', 'date', '<=', $end);
            });
````
Still there is a problem with the fact that initially the button of the filter shows active at the start page load

**Comment by tabacitu** [comment]
Hmm... @eddilou how can I replicate the problem? Are you using AjaxDatatables? I can't seem to get the same thing.

Cheers!

**Comment by SandHani45** [comment]
im also getting same problem can u plz help this problem

**Comment by lloy0076** [comment]
`The controller goes to infinity` describes the cause but not the symptom.

What is actually meant to happen here? @eddilou @SandHani45

**Comment by tabacitu** [comment]
The problem has since been fixed. A ```composer update``` should do it for you guys. Thanks, cheers!

**Comment by SandHani45** [comment]
thq

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
