### ISSUE TITLE
How to create an list.blade 

### ISSUE THREAD

**Issue by YeyeMorales** [Laravel-Backpack/CRUD#818]
Hello,
How can I create a field of type list that shows a list with the data of another model, is it possible?

I have a form in which it shows the list but of the reference data of the registry.

**Comment by promatik** [comment]
Hi @YeyeMorales you should take a look at `select2` ([documentation](https://laravel-backpack.readme.io/v3.0/docs/crud-fields#section-select2-1-n-relationship)) it allows you have a list based on another model.

Also, if you have any questions you should use Stackoverflow. You'd get appropriate and fastest help there.
Use the tag `backpack-for-laravel`.
https://stackoverflow.com/questions/tagged/backpack-for-laravel
