### ISSUE TITLE
Issue with Controller inheritance

### ISSUE THREAD

**Issue by dennisc1** [Laravel-Backpack/CRUD#82]
So now a new controller extends the CrudController and inherits the index(), edit(), store() etc. methods. If I want to modify the behaviour I extend the methods of the parent CrudController in my new controller (so called [Callbacks](https://laravel-backpack.readme.io/docs/crud#callbacks)). 
I love the idea of this system, because it makes CRUD easily customizable. However, the current implementation disabled the use of [implicit route binding](https://laravel.com/docs/5.2/routing#route-model-binding). Because the parent methods don't accept any parameters, so the child methods can't accept any either.

For example. In my database I have users and posts. So I will have a UserCrudController and a PostCrudController both extending CrudController. Now I would like to able to have a crud interface for all the posts of a certain user. Normally I would route like this
`/users/{user}/posts/index`
and have a method in de PostCrudController
```php
index (User $user) {  
  // index users
}
```
however, because the index() method in the PostCrudController extends the CrudController index() method, it isn't allowed to accept the $user parameter.

So I think the extensibility and customizability of the package will become better, if you can accept your own parameters in each method. One way of solving this would be renaming the parent methods. 
So every chilcontroller should implement all the crud methods, and call their parent method. It would look something like this

```php
index(User $user) {
  $this->crud->addClause('where', 'user_id', '=', $user->id);
  parent::indexCrud()
}
```

**Comment by tabacitu** [comment]
Hmm... I agree, we should consider this. 

I have to test to make sure, but one problem I foresee with this is that the dependency injection will force us to place a lot of empty functions in all EntityCrudControllers, which just call their parents.

Right now entityCrudControllers look somethink like this:
```php
<?php namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\CarRequest as StoreRequest;
use App\Http\Requests\CarRequest as UpdateRequest;

class CarCrudController extends CrudController {

public function __construct()
{ 
  // a lot of lines
}

public function store(StoreRequest $request)
{
	return parent::storeCrud();
}

public function update(UpdateRequest $request)
{
	return parent::updateCrud();
}
```

Which to me already looks a bit sketchy - I really don't like we need the ```store``` and ```update``` methods there.

Implicit router binding would also mean we need to add the ```index```, ```create```, ```edit``` methods and maybe```show```, ```destroy``` and ```showDetailsRow```.

I'm not sure if this is good or bad, though. One one hand, it's a lot of code that does nothing. On the other hand, it makes the EntityCrudController more intuitive - it clearly states what you need to do in order to customize it and it allows you to easily do so.

Others, opinions? @Ghitu @cristiantone ?

**Comment by dennisc1** [comment]
I got an idea/proposal  for this. It requires a rewrite of the `CrudController` class. It might be a breaking change, but I'm not sure yet.

By introducing the `__call` magic method, the `CrudController` can catch all calls to undefined methods. This way it isn't necessary to define all the methods in the `EntityCrudController`. If methods are defined, they will be called. The defined methods in the `EntityCrudController` can accept custom parameters from implicit route binding. If the methods are not defined in the `EntityCrudController`, the magic method will call the correct method in the `CrudController`.

```php
public function __call($method, $arguments) {
         call_user_func( $method . 'Crud', $arguments);
}
```

This means in the `CrudController` methods like `index` and `edit` have to be renamed to `indexCrud` and `editCrud`.

**Comment by dennisc1** [comment]
I think my above comment will largely solve the problem. Although it seems there is going to be some unnecessary repeated code. For example: if I want to CRUD all records belonging to a certain user, all the methods in my `EntityCrudController` will have to look like this (example)

```php

public function index(User $user)
{
    $this->crud->addClause('user_id', $user->id);   
    return parent::indexCrud();
}

public function edit(User $user)
{
    $this->crud->addClause('user_id', $user->id);     
    return parent::editCrud();
}

public function store(StoreRequest $request, User $user)
{
    $this->crud->addClause('user_id', $user->id);      
    return parent::storeCrud();
}

public function update(UpdateRequest $request, User $user)
{
    $this->crud->addClause('user_id', $user->id);   
   return parent::updateCrud();
}
```

I've also thought of a possible solution for this problem. Although this will require a breaking rewrite, I think it could benefit the overall usability and flexibility of the package. Instead of calling methods in the `EntityCrudController` we could catch all incoming method requests with the `__call()` magic method. To do this, none of the methods should be named their 'usual' names (like `index`, `store` etc).
This magic method afterwards 'dispenses' every request to the correct method. This means the methods would have to change to callbacks (which in my opinion is no problem, a lot of frameworks etc use it, so people are used to it)
It would look like this

```php
class EntityCrudController extends CrudController {

    public function __construct()
    { 
      // a lot of lines
    }

    public function beforeUpdate ()
    {
        // maniuplate request before update
    }

    public function afterUpdate ()
    {
        // maniuplate request after update
    }

    public function useRouteParameters(User $user)
    {
        $this->crud->addClause('user_id', $user->id);      
    }
}
```

```php
class CrudController extends BaseController {
    public function __call($method, $arguments) 
    {
        // if the method is defined, use the arguments from the route parameters
        if (method_exists($this->controller, 'useRouteParameters') && is_callable(array($this->controller, 'useRouteParameters')))
        {
            $this->useRouteParameters($arguments);
        }     

        // before method callback (like beforeUpdate)
        call_user_func( 'before' . ucfirst($method) , $arguments);

         // method call (like updateCrud)
         call_user_func( $method . 'Crud', $arguments);

        // after method callback (like afterUpdate)
        call_user_func( 'after' . ucfirst($method) , $arguments);
     }
```

**Comment by tabacitu** [comment]
Hmmm... This would indeed solve the method model binding issue, but the change would be quite big (and indeed, a breaking change) so I'm wondering wether a change this big is worth if for such a small addition. This needs further thinking. Fortunately we have time for that, because this breaking change can't be introduced until Backpack/CRUD v4 :-)

What I like about your solution is:
- that the methods would be clearer (all default Crud methods have Crud in their names);
- that we CAN use use regular callback (though i personally am a fan of method overwriting, i think it's simpler and more OOP, but i'm sure others don't);

What I don't like about it is:
- it isn't backwords-compatible (big breaking change);
- an option like addClause will need to be added in each and every method (a lot of code that does the same thing);
- it adds another later of complexity to the CrudController, which i personally have a rule about: always think twice before doing that (literally - think once, make a decision then come back in a few days with a fresh mind; if you still agree it's not overengineering, only then code it);

In the meantime, I think your UserPosts issue could be solved using a UserPostsCrudController which:
- has custom routes, like you've specified above (you can manually place everything that's generated by CRUD::resource in CrudServiceProvider);
- extends your PostController;
- has something like this in the __construct($user_id)
   - $user = User::findOrFail($user_id);
   - $this->crud->addClause("user_id", $user->id);

If you need to redo everything you've done in the PostCrudController's constructor, you can just move all of that in a method like PostCrudController::customizePanel(), thencall it from both PostCrudController::__construct() and UserPostCrudController::__construct();

I think this is a pretty simple solution that solves your problem, but NO, it does not use method model binding. Is it feasible?

Sorry for the rough sketch, writing on mobile.

Cheers!

**Comment by dennisc1** [comment]
I've tried a couple of changes to the `CrudController`. However, because the `__call ` magic method [isn't supported anymore](https://github.com/laravel/framework/issues/11812) in a Laravel controller, I couldn't find any clean solution for this.

Now I'm getting the URL parameters with 
```php
$user_id = Route::current()->parameter($user_id);
$user = User::findOrFail($user_id);
```
 However, this isn't an optimal solution either. In general, statements like that don't belong in the controller constructor
For example, when executing the CLI command `artisan route:list`, all the controllers constructors are being called. Since from the CLI there are no route parameters, the constructor will fail. 
This forced me to add 
```php
if ( ! \App::runningInConsole()) {
            /// CRUD code
}
```
to make sure that the code won't be executed from the console.

**Comment by dennisc1** [comment]
So in general, it is possible. However, I've had to apply multiple hacks/workarounds to make it work.
I'll think about it some more. But I'll be glad to see anybody come up with an elegant solution to this. Im working on a large project and I encounter a lot of these parent - child relationships where I want a CRUD for all the child records belonging to a certain parent.

**Comment by tabacitu** [comment]
Hmm... So you've tried my suggestion above? I've just tried it and it works like a charm. Here's the code for it:

The routes file (```routes/web.php```):
```php
// Admin Interface Routes
Route::group(['prefix' => 'admin', 'middleware' => ['web', 'auth'], 'namespace' => 'Admin'], function()
{
    CRUD::resource('post', 'PostCrudController');
    CRUD::resource('user', 'UserCrudController');

	// !!! DIFFERENT ADMIN PANEL FOR USER POSTS
	Route::group(['prefix' => 'user/{user_id}'], function()
	{
	    CRUD::resource('post', 'UserPostCrudController');
	});
});
```

The controller (```app/Http/Controllers/Admin/UserPostController.php```):
```php
<?php namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;
use App\Http\Controllers\Admin\PostCrudController;

// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\PostRequest as StoreRequest;
use App\Http\Requests\PostRequest as UpdateRequest;

class UserPostCrudController extends PostCrudController {

	public function __construct() {
        parent::__construct();

        // get the user_id parameter
        $user_id = \Route::current()->parameter('user_id');

        // set a different route for the admin panel buttons
        $this->crud->setRoute("admin/user/".$user_id."/post");

        // show only that user's posts
        $this->crud->addClause('where', 'user_id', '==', $user_id); 
    }

    public function store(StoreRequest $request)
    {
        return parent::storeCrud();
    }

    public function update(UpdateRequest $request)
    {
        return parent::updateCrud();
    }
}

```

Notes: I don't think you need to do User::findOrFail(); if the user does not exist it will just show an empty table; that way, you're constructor can also work in the CLI.

What do you think?

Cheers!

**Comment by tabacitu** [comment]
@dennisc1 any updates? Can I close the issue? Cheers!

**Comment by dennisc1** [comment]
Hi @tabacitu. I'm sorry for the late reply. Your solution above works. Indeed the only tradeoff is not being able to use `findOrFail()`, but this is no big problem.
I did encounter another problem. In the `CrudController` the method `Edit` accepts the parameter `$id`, ,as follows:
```php
public function edit($id)
{
   /// edit stuff
}
````
In our example above, this should be the id of the post. However, when using the CRUD as described above, not the id of the post is being used, but of the user. This is caused by the way the routes are defined.
I added a route as follows

```php
Route::group([ 'prefix' => 'user/{user}', 'as' => 'user.' ], function () {
   CRUD::resource('post', 'PostCrudController');
}
```
this results in the following route for the editing of a post (which is correct)
`/user/{user}/post/{post}/edit`

However, the Laravel `Illuminate\Routing\ControllerDispatcher` class will call the `edit` method with the following parameters (for example):

```php
$parameters = [
  'user' => 1,
  'post' => 3, 
```

because non of the parameters has the name 'id', it will pick the first one, in this case 'user'.

So this results in the `edit($id)` method being called with the $id of the user in stead of the post. So when visiting `/user/1/post/3/edit` you will be editinf the post with id=1 in stead of id=3

Hope this is clearly explained

**Comment by dennisc1** [comment]
ps: my current workaround would be
```php
public function __construct() {
        parent::__construct();

        // get the user_id parameter
        $user_id = \Route::current()->parameter('user');

        // set a different route for the admin panel buttons
        $this->crud->setRoute("admin/user/".$user_id."/post");

        // show only that user's posts
        $this->crud->addClause('where', 'user_id', '==', $user_id); 
        
        // forget the user parameter
        Route::current()->forgetParameter('user');
    }

```

**Comment by OwenMelbz** [comment]
@dennisc1 using @tabacitu solution, have you tried renaming your `__construct` to `setUp` and removing the `parent::__construct()` call? then trying to use the findOrFail?

**Comment by tabacitu** [comment]
How about having both parameters for the edit() method?

```php
public function edit($user_id, $post_id)
{
   /// edit stuff
}
```

If there are 2 parameters, that should work in Laravel. Wouldn't that fix it for you?

**Comment by dennisc1** [comment]
@tabacitu so I tried your solution by overwriting the edit() method in my PostCrudController. However this is not allowed because both the parent and child edit() function should accept the same arguments. PHP throws an error
`
...\PostCrudController::edit($user_id, $post_id) should be compatible with Backpack\CRUD\app\Http\Controllers\CrudController::edit($id)
 `

**Comment by dennisc1** [comment]
@OwenMelbz I'm still using Laravel 5.2, so I haven't been able to upgrade the CRUD package yet. So the setup() function isn't implemented yet in my version of CRUD.
However, I'm planning to make a pull request to merge all the commits for CRUD since the adoption of laravel 5.3 into a branch for laravel 5.2

**Comment by tabacitu** [comment]
Damn. Then I guess the only way to get those is using something like this.

routes/web.php:
```php
// different admin panel for user posts
	Route::group(['prefix' => 'user/{user_id}'], function()
	{
	    CRUD::resource('post', 'UserPostCrudController');
	});
```

UserPostCrudController.php:
```php
public function setup() {
  $user_id = \Route::current()->parameter('user_id');
  $post_id = \Route::current()->parameter('id');
}
```

**Comment by dennisc1** [comment]
I'm not sure if I understand if that would be a solution. So to be clear about the problem, when defining a route:

```php
// different admin panel for user posts
    Route::group(['prefix' => 'user/{user_id}'], function()
    {
        CRUD::resource('post', 'UserPostCrudController');
    });
```

the default route for (for example) the edit function would be:

`/user/{user_id}/post/{post}/edit`

this route will call the `edit($id)` method in the parent `CrudController`. Laravel calls this method trough ```php call_user_func_array([$this, $method], $parameters)```. Because of this it will always use the _first_ parameter as the `$id` parameter when calling the `edit($id)` method, no matter the naming of the parameters. So in our example the parameters will be:
```php
$parameters = [
  'user_id' => 1,
  'post' => 3, 
];
```
so the method will always be called using the first parameter. In this case the wrong parameter, namely `'user_id'`

This was to be clear about the problem. So far I've found two solutions
1. mentioned above: removing the `user_id` parameter, so the `post` parameter becomes the first parameter. However, this is a ugly solution.
2. overwrite the `edit()` method as follows in your own controller
```php
public function edit($id) {
    $post_id = Route::current()->parameter('post');
     parent::edit($post_id);
}
```

**Comment by tabacitu** [comment]
You're totally right. What I was suggesting above was more pseudocode than actual code, sorry :-)

I just tested your second solution - it works and I think it's pretty elegant, as long as it's only needed for nested resources. Right?
```php
public function edit($id) {
    parent::edit(\Route::current()->parameter('post'));
}
```

I guess you need to do the same for ```destroy()``` and any of these that you use:
- show($id)
- showDetailsRow($id)
- listRevisions($id)
- restoreRevision($id)

Any other problems you've faced while doing this?

**Comment by dennisc1** [comment]
Nope. So to sum it up. Nested CrudControllers in general work really well. But there are 2 issues

- findOrFail causes CLI to fail. (Although I don't know if this is still the case after the L5.3 update when defining the CRUD in the setup() function). Solution

 1. don't use find or fail
 2. use
  ```php 
  if ( ! \App::runningInConsole()) {
          
  }
  ```

- Thefirst parameter of the route is being used as $id. 
 1. overwrite the affected methods as follows
  ```php
  public function edit($id) {
      return parent::edit(\Route::current()->parameter('post'));
  }
  ```
 2. make the desired parameter the first parameter by adjusting the route (dirty solution, but quick)
  ```php
  Route::current()->forgetParameter('user');
  ```

**Comment by tabacitu** [comment]
As there is no longer an issue with this, because we found a solution (_yeeey, go team!_), I'm going to close the issue.

Mental note: create a tutorial on how to do this and post it on the BackpackBlog ([coming soon](https://cdn.meme.am/instances/55274061.jpg)). If any of you want to create a tutorial about this as a "guest post" on a the new blog, let me know. The SEO towards your blog/website won't be much, but hopefully in the future...

Cheers!

**Comment by anish-adm** [comment]
I believe this is bit late to reply, but I found below quick fix until we have implementation of controller inheritance with nested resources.
We can create new function in controller, let's say **agentCompanies** in my case and implement where clues of crud with the use of parameters passed. Lastly simply call according parent methods (**index in my case**).

```php
public function agentCompanies($salesPersonId = '') {
        if($salesPersonId){
            $this->crud->addClause('where', 'user_id', '=', $salesPersonId);
        }
        return parent::index();
}
```

**Comment by mrvanwagoner** [comment]
This sounds like exactly what I need but am having a hard time figuring out the end result. Any progress on a tutorial on this?

**Comment by mrvanwagoner** [comment]
I would also like to look at it using many-to-many relations.

**Comment by tabacitu** [comment]
Hi @mrvanwagoner ,

This tutorial might help: [Nested Resources in Backpack CRUD](https://backpackforlaravel.com/articles/tutorials/nested-resources-in-backpack-crud).

Cheers!
