### ISSUE TITLE
"select_multiple" additional pivot parameters

### ISSUE THREAD

**Issue by VilmantasSaulys** [Laravel-Backpack/CRUD#821]
Hello, 

I have a table http://prntscr.com/g48995 

In my controller the logic of this table is here: http://prntscr.com/g489ne

How can I pass additional parameters to this table? For example I want to append Poll to my article, and I need that the type of this poll will be "article".

**Comment by tabacitu** [comment]
Hi @VilmantasSaulys ,

There's no solution for this already built, sorry.

Cheers!

**Comment by juanvillegas** [comment]
@tabacitu Wondering if this ever got implemented?
