### ISSUE TITLE
[QUESTION] Possible to show additional parameters in `select` list?

### ISSUE THREAD

**Issue by matcartmill** [Laravel-Backpack/CRUD#822]
Hello,

I have a need for multiple parameters in a select list. In this job board that I'm developing anyone people can create a `company` and the company name is not unique. In the `job` CRUD panel I have a  `select` box for choosing a new `company` to assign it to. Given that there could be an infinite amount of `Apple Inc` or `ABC & Co.`, I'd like to also include the `id` of the company in the `select` list.

So instead of:

```
ABC & Co
Apple Inc
Burger King
etc
```

I want to know if it's possible to do:

```
13962 - ABC & Co
253 - Apple Inc
295820 - Burger King
```
etc.

Anyone know if this is possible?

**Comment by osantelices** [comment]
Hello @matcartmill  it´s you can use custom fields 
and in the view you can do what you need

**Comment by lloy0076** [comment]
You might be able to setup a customer mutator/accessor (see https://laravel.com/docs/5.4/eloquent-mutators).

**Comment by lloy0076** [comment]
@matcartmill - are either of the above suggsetions helpful?

**Comment by matcartmill** [comment]
Hey @lloy0076, I don't fully understand @osantelices' suggestion, but the custom accessor sounds promising. I'll give that a shot tomorrow and let you know. I kind of back-burnered this for the last week or two. I'll report back.

Thanks for reaching out.

**Comment by lloy0076** [comment]
I think that he means the same thing as me (unless I"m mistaken).

**Comment by tabacitu** [comment]
Yup, I think accessor is the way to go. Just pass your accessor (```nameAndId```) instead of ```name``` to your select list. Hope it helps.

Cheers!
