### ISSUE TITLE
Two Fields on same Model

### ISSUE THREAD

**Issue by osantelices** [Laravel-Backpack/CRUD#825]
I have two Fields inside my view but to save is my problem this two Fields whit Pivot have same Model

               `$this->crud->addField(
			 [
			   // 1-n relationship
			   'label' => "Contacts Business", 
			   'type' => "contacts",
			   'name' => 'contactsbusiness',
			   'entity' => 'contactsbusiness',  
			   'attribute' => "name", 
			   'idcontact' => '1',
			   'model' => "App\Models\Contact", 
			   'pivot' => true,
			]
		);`

		`$this->crud->addField(
			 [
			   // 1-n relationship
			   'label' => "Contacts IS+T", 
			   'type' => "contacts",
			   'name' => 'contactsist', 
			   'entity' => 'contactsist', 
			   'attribute' => "name",
			   'idcontact' => '2',
			   'model' => "App\Models\Contact", 
			   'pivot' => true,
			]
		);`

So when saving, only the last field is saved in my table
This are my relationship

   `public function contactsbusiness()
    {       
        return $this->belongsToMany('App\Models\Contact','applications_contacts')
         ->withPivot('application_id','contact_id')
         ->where('type_contact_id', 1)
         ->using(ContactPivot::class);
    }
   public function contactsist()
    {       
        return $this->belongsToMany('App\Models\Contact','applications_contacts')
    	 ->withPivot('application_id','contact_id')
         ->where('type_contact_id', 2)
    	 ->using(ContactPivot::class);
    }`

Please your help is welcome!!!

**Comment by osantelices** [comment]
I have solved my problem differently ... 
If anyone needs a help with this same comment and I write the solution. 
Thanks for Read

**Comment by iMokhles** [comment]
great 👍  will be appreciated if you post the solution.

**Comment by osantelices** [comment]
ok @iMokhles 

My problem was save two fields in same field on bd in one Model

View Crud
`                [
        		'label'=>'Contacts Business', 'name'=>'contacts', 'attribute'=>'name','type'=>'select_multiple_callback','entity'=>'contactsbusiness', 'type_contact_id' => '1', 'model' => "App\Models\Contact", 'pivot' => true,
        		
		    
        	],
        	[
        		'label'=>'Contacts IS+T', 'name'=>'contacts2', 'attribute'=>'name','type'=>'select_multiple_callback','entity'=>'contactsist', 'type_contact_id' => '2', 'model' => "App\Models\Contact", 'pivot' => true,
        		
		    
        	],`

and I merge two actions in one Field 
`$this->crud->addField(
			 [
			   // 1-n relationship
			   'label' => "Contacts IS+T", // Table column heading
			   'type' => "contacts2",
			   'name' => 'contactsist', // the column that contains the ID of that connected entity;
			   'entity' => 'contactsist', // the method that defines the relationship in your Model
			   'attribute' => "name", // foreign key attribute that is shown to user
			   'idcontact' => '3',
			   'model' => "App\Models\Contact", // foreign key model
			   'pivot' => true,
			]
		);`

all contacts but not the contacts whit 'type_contact_id' = 3

And this allows to save without any problems all the data in my pivote table

**Comment by tabacitu** [comment]
Thanks for sharing your solution!

**Comment by bahman2216** [comment]
Thanks for solution, But what is your 

> select_multiple_callback.blade.php
content?
