### ISSUE TITLE
A date_range type field does not take values from the database

### ISSUE THREAD

**Issue by eddilou** [Laravel-Backpack/CRUD#831]
Hello everyone, why in the variable value = null? How to make sure that the date was extended from the database when editing
```php
[
             'name' => 'interval_date_range', // a unique name for this field
             'start_name' => 'start_date', // the db column that holds the start_date
             'end_name' => 'end_date', // the db column that holds the end_date
             'label' => 'Date Range',
             'type' => 'date_range',
             // OPTIONALS
             'start_default' => \Carbon\Carbon::now()->format('Y-m-d'), // default value for start_date
             'end_default' => \Carbon\Carbon::now()->format('Y-m-d'), // default value for end_date
             'date_range_options' => [ // options sent to daterangepicker.js
                 'timePicker' => false,
                 'locale' => ['format' => 'YYYY-MM-DD'],
]
```
In the database there are values at the start _date and the end_date,
result in template
```php
dd($fields['value']);
"value" => null
```

**How to solve this problem with the assignment of dates from the database?**

**Comment by mamarmite** [comment]
When you are editing, the date_range field_type have a bug #450 that may fix the problem that you've shared : Where the date_range field doesn't take the start_date and end_date value from your DB.

Anyhow, when you tried to access `$fields["value"]`, it seem that the fields array is construct like `"type"=>$field`.

Hope it lights your problem.

**Comment by tumf87** [comment]
@tabacitu, this doesn't seem to work for me either. 
Tried it in the Backpack Demo with the dev version of backpack CRUD and the date range always shows defaults for both start and end dates.
I'll get working on a PR.

**Comment by tabacitu** [comment]
@tumf87 great, thank you. That you're working on a PR, not that it's not working. That's not great at all :-)

**Comment by tabacitu** [comment]
Fixed, merged and launched! Thanks guys!
