### ISSUE TITLE
ElFinder stuck at "Open folder..."

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#834]
Hello, i set exactly as documentated, that's my config

```php
'uploads' => [
     'driver' => 'local',
     'root' => public_path('uploads'),
],

```
and everything seems perfect, but i get stuck in "Open folder..." small modal.

Is this a bug? Or where am I wrong?

Edit: 
when connecting to "/elfinder/connector?_token=..." i get a FatalErrorException because of 30 secs of execution.

**Comment by lloy0076** [comment]
Do you see anything at all in `storage/logs/laravel.log` or the relevant web server error logs?

**Comment by EmanueleCoppola** [comment]
I just switched php version from 5.6.28 to 7.x on my MAMP Pro and now seems to be fine, I also switched back to 5.6.28 and seems fine too 🤔
