### ISSUE TITLE
Problem  with upload image

### ISSUE THREAD

**Issue by grupaoem** [Laravel-Backpack/CRUD#837]
Hi, when I have Add image display error: 

![image](https://user-images.githubusercontent.com/3195513/29208984-87933c82-7e8c-11e7-8cc7-d54ea815d978.png)

**Comment by lloy0076** [comment]
Did you follow the setup in the docs?

**Comment by tabacitu** [comment]
Hmm... Sounds to me like you have a different folder configured in your config file? Are you sure you ran the installation steps in the correct order?
