### ISSUE TITLE
Is there a way to automatically select default selected item in select field

### ISSUE THREAD

**Issue by goranljubas** [Laravel-Backpack/CRUD#84]
Hi I would like to have default selected item in select field, is that possible? Also I don't know how to insert a button, I saw there is $this->crud->addButton($stack, $name, $type, $content, $position); function but I don't know what do the parameters mean (except name)? Can you give me an example? Thanks...

**Comment by tabacitu** [comment]
Hi @goranljubas ,

Use ```default```:
```php
$this->crud->addField([  // Select
   'label' => "Category",
   'type' => 'select',
   'name' => 'category_id', // the db column for the foreign key
   'entity' => 'category', // the method that defines the relationship in your Model
   'attribute' => 'name', // foreign key attribute that is shown to user
   'model' => "App\Models\Tag", // foreign key model

   'default' => '25'
]);
```

For buttons please read [their documentation](https://laravel-backpack.readme.io/docs/crud-buttons).

Cheers!

**Comment by tabacitu** [comment]
Sorry for being so dismissive earlier. It's been a tough week. Does this fix you issue? Ok to leave it closed?

**Comment by goranljubas** [comment]
Dont worry its been a though week for me too. However backpack cannot solve my problem unfortunately :(. Im gonna have to write my app from scratch. Its still a good plugin you are very good programmer :)

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Aug 5, 2016 at 7:24 PM +0200, "Cristian Tabacitu" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for being so dismissive earlier. It's been a tough week. Does this fix you issue? Ok to leave it closed?

-

**Comment by tabacitu** [comment]
:-)) thank you. I understand that, I never aimed Backpack to be the proverbial hammer. There are certainly cases where coding from scratch is better.

Cheers, good luck!
