### ISSUE TITLE
Case-sensitivity problems on Windows (or other case-insensitive OS)

### ISSUE THREAD

**Issue by dimitriadisg** [Laravel-Backpack/CRUD#849]
Hello,

this package is impossible to install "properly" on case-insensitive OS, in my case Windows. The reason is that these two directories have the same case-insensitive name :

`CRUD/src/resources/lang/zh-cn/`
`CRUD/src/resources/lang/zh-CN/`

Everything seems to work fine if I manually delete zh-cn for example and keep the other one. But I guess that's a hacky workaround.

Thanks for noticing, I hope this is not a big issue.

EDIT:
By "everything works fine" I mean about default behaviour. I haven't tested to switch language for this matter.

**Comment by lloy0076** [comment]
Ouch - what a pain.

@tabacitu - *this* package's directory should be made lower case unless you see any other reason?

**Comment by dimitriadisg** [comment]
In fact, the two directories are identical. They both include the exact same crud.php file. What is weird is that they are edited on different commits though.

**Comment by tabacitu** [comment]
That's... odd... there's only one folder that I see, zh-CN:

<img width="243" alt="screen shot 2017-09-04 at 15 21 54" src="https://user-images.githubusercontent.com/1032474/30026285-dff6bb78-9184-11e7-8e3c-af600855a860.png">

What version did you try to install?

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/Base/commit/5a7a56715ca63cd46bafe984dfeb5c6d4791d77d has `cn`
https://github.com/Laravel-Backpack/CRUD/commit/4ed669412d0ebff132c0da94cb327dfabfa212b8 has `CN`.

**Comment by dimitriadisg** [comment]
Sorry I don't remember which version I was trying to install (I switched CMS, not for this reason though).

But the [latest commit on master](c168e8742dde4ca2425ea58c48afca5707bc42cd) has this bug, check [this link](https://github.com/Laravel-Backpack/CRUD/tree/master/src/resources/lang)

**Comment by tabacitu** [comment]
Thank you @dimitriadisg . Fixed on dev!
