### ISSUE TITLE
filters, order and search not persisting to url

### ISSUE THREAD

**Issue by scottgrayson** [Laravel-Backpack/CRUD#852]
I created some custom filters based on the backpack select2 from ajax filter that adds this to the query string.
`?status=offline&city_id=488&city_id_text=New+Haven`

But i would like to have the sort_by, sort_order and search text in the url also. They do not get appended currently
![image](https://user-images.githubusercontent.com/7796074/29320728-30960816-81a6-11e7-93ec-741ad4c01a9d.png)
the filters applied in the image do not appear in the url

**Comment by lloy0076** [comment]
@scottgrayson - this isn't an exact duplication of one of the https://github.com/Laravel-Backpack/CRUD/issues/516#issuecomment-283755231 issues, is there a reason you'd like those values in the URL **specifically**?

**Comment by scottgrayson** [comment]
@lloy0076 
- search: If admin searches for `bob` in the users table, clicks on `bob1` and realized they wanted `bob2` the back button retains the results. Admin does not have to type `bob` again
- sort: similar to search. If admin wants to edit mulitiple items starting with `z` and uses sort to accomplish this. it will be useful to retain the results

**Comment by AurelDragut** [comment]
@scottgrayson the sort part can be done with global scopes based on the filters that you add

**Comment by lloy0076** [comment]
I might need to think on this a little more but I think this is highlighting an issue (that sorting, filtering, etc is not maintained) that is discussed in a few other tickets/issues; and I'm not convinced putting everything as in the URL (i.e. to be sent to `$_GET` and its Laravel/Symfony request equivalent) is the only solution.

I'm not saying the OP is wrong (or that the proposed solution is "bad") just that I sense there's an underlying issue / deficiency waiting to be solved [but I can't quite figure out what it is precisely].

**Comment by DelightedD0D** [comment]
I would personally prefer a solution that utilizes the url for shareability purposes. ie, a user can then copy the url and paste it in Slack or an email or notepad for later use or to share with other users. AFAIK, there is no way to achieve shareability without get params.

**Comment by tabacitu** [comment]
Hi guys,

I'm afraid there's no way to do that - sort by, sort order and search text are all DataTable things. We couldn't achieve that without overwriting this major functionality for DataTables. At which point, it wouldn't make much sense to use DataTables anymore, because we've overwritten most of its functionality.

So right now, I say we can't. But I do expect to get rid of the DataTables dependency sometime in the future, so maybe we can revisit this issue then. I dream of writing a Vue.JS component that does the same thing but... hey ho.

Cheers!

**Comment by DelightedD0D** [comment]
@tabacitu I feel like we could do this using the current DataTables APIs without too much trouble really.  

I'm thinking something like this:

https://datatables.net/reference/event/stateSaveParams
Use the stateSaveParams event to modify the url when state changes occur
```

var table = $('#example')
    .dataTable()
    .on( 'stateSaveParams.dt', function (e, settings, data) {
        var state = table.state(); 
        // serialize object with something like https://stackoverflow.com/questions/1714786/query-string-encoding-of-a-javascript-object
        // modify the url / page history object to add the state like ?dtState=...
    } );

```

https://datatables.net/reference/option/stateLoadCallback
Use the stateLoadCallback function to load the state from the url if present

```
 $('#example').DataTable( {
    stateSave: true,
    stateLoadCallback: function (settings, callback) {  
         var state = "";    // parse url, de-serialize state object if found
         callback( state);
    }
} );
```

Obviously, we'd put those together into the one call to DataTables, this was just to illustrate the concept.

Thoughts?
