### ISSUE TITLE
[Bug] tinymce elfinder link not working

### ISSUE THREAD

**Issue by packytagliaferro** [Laravel-Backpack/CRUD#871]
Right now if I choose to add a link to the text I have the option to link it to a file. So when I do so I can see all my files fine, upload fine, but when I add the link its a jibersh path. The files are all stored using local storage:

```
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

```
But the link I get is:
` elfinder/connector?_token=cf15xM4AWQUbROs0nVFpHLrluQtYdn4A9pYQYGOJ&cmd=file&target=fls2_dXBsb2Fkcy9QREZzL0Jhbmstb2YtQW1lcmljYS1FRlQtQXBwbGljYXRpb24ucGRm`

I can find the actual file here: 
`uploads/PDFs/Application.pdf`

Everything else works fine with my uploads and file systems, its just that odd link value.

**Comment by lloy0076** [comment]
At the moment I think this is a question, but it might be a bug - when you say you can find the file, assuming that your APP_URL is (say) `/myapp/` you can find that file *physically* at `/myapp/public/uploads/PDFs/Application.pdf`?

**Comment by packytagliaferro** [comment]
@lloy0076 I can find the file physically there but the link it gives me is that `efinder/connector` link. It should just be `/uploads/PDFs/Application.pdf` . If I go to that link I can find the file so I assume the link should be based upon the driver configuration.

**Comment by packytagliaferro** [comment]
Anyone else had this? Having to put in my own link to is getting hectic.

**Comment by packytagliaferro** [comment]
I just changed my input type to `wysisyg` and it works now. Still not working with `tinymce`

**Comment by packytagliaferro** [comment]
So I just checked and the link works (displays the image on my website) but only if I am logged in. I think the link should return the absolute path and not:

`elfinder/connector?_token=cf15xM4AWQUbROs0nVFpHLrluQtYdn4A9pYQYGOJ&cmd=file&target=fls2_dXBsb2Fkcy9QREZzL0Jhbmstb2YtQW1lcmljYS1FRlQtQXBwbGljYXRpb24ucGRm`

I can post a video of whats going on if that helps.

**Comment by lloy0076** [comment]
I don't believe this is a bug.

**Comment by tabacitu** [comment]
Checked, I'm able to replicate the issue. The stored URL includes the connector file, which is behind the ```admin``` middleware. Bad ```elfinder```. Bad!

**Comment by lloy0076** [comment]
So it would seem it's a bug and not a question, right? 😄

**Comment by robertotcestari** [comment]
Did anyone come with a solution? Having the same problem here.

**Comment by fede91it** [comment]
Any news here?

**Comment by pxpm** [comment]
@tabacitu i tried this out. The links are setup just fine. 

Is there an edge case this would fail ?

**Comment by brynnb** [comment]
I am having the same issue - these links only work when logged in, meaning all the public content I have set up has broken images. Investigating alternatives now but not sure what to do yet. I am not able to find where the connector URL is established and the admin middleware is applied to see if that's something I can remove.

**Comment by pxpm** [comment]
Hello everyone who pitched in here.

Thank you very much for your help on debugging this. I'v just submitted PR #3281 that will solve this problem. 

I am going to close this, anything else should be addressed in the PR thread. 👍 

Wish you guys the best,
Pedro
