### ISSUE TITLE
Upload img url problem with path

### ISSUE THREAD

**Issue by grupaoem** [Laravel-Backpack/CRUD#873]
Hi I have problem with backslash in url img in filemanager.
![image](https://user-images.githubusercontent.com/3195513/29488709-cf395b90-8510-11e7-9578-31bb91673488.png)

How change backslash \ to slash / ?

**Comment by tabacitu** [comment]
This is very odd and it's been reported before. Can you please detail your system (OS, server, PHP version, etc)?
