### ISSUE TITLE
route_prefix is not dynamic in views

### ISSUE THREAD

**Issue by neverend92** [Laravel-Backpack/CRUD#88]
All URLs in the views a static at the moment (i.e. {{ url('admin/dashboard') }}), this doesn't allow us to change the route_prefix in the config file.
This should be changed to {{ url(config('backpack.base.route_prefix'),'dashboard') }}.

[Effects also all other projetcts, like base, etc.]

**Comment by tabacitu** [comment]
You're right. Fixed in 3.0.12. Thanks!
