### ISSUE TITLE
Remove CSV Button

### ISSUE THREAD

**Issue by osantelices** [Laravel-Backpack/CRUD#880]
Hello everyone

I have my button here, but there are some that I want to remove from the view, one of them for example is the CSV button

![botones](https://user-images.githubusercontent.com/508141/29626004-cd6a4e50-8803-11e7-878a-5c349615015c.PNG)

I've tried it in the following ways

$this->crud->removeButton('top', 'csv');

$this->crud->removeButton('csv');

What am I doing wrong?

**Comment by lloy0076** [comment]
Tried `CSV` -> note caps?

**Comment by osantelices** [comment]
nothing my friend
non-object error :(

**Comment by niladam** [comment]
You need to edit `list.blade.php` and remove **csvHtml5** from the `dtButtons` array.

So, instead of:

```
// show the export datatable buttons
dom: '<"p-l-0 col-md-6"l>B<"p-r-0 col-md-6"f>rt<"col-md-6 p-l-0"i><"col-md-6 p-r-0"p>',
buttons: dtButtons([
  'copyHtml5',
  'excelHtml5',
  'csvHtml5',
  'pdfHtml5',
  'print',
  'colvis'
]),
```

You should have:

```
// show the export datatable buttons
dom: '<"p-l-0 col-md-6"l>B<"p-r-0 col-md-6"f>rt<"col-md-6 p-l-0"i><"col-md-6 p-r-0"p>',
buttons: dtButtons([
  'copyHtml5',
  'excelHtml5',
  // 'csvHtml5', -- This is now commented.
  'pdfHtml5',
  'print',
  'colvis'
]),
```

**Comment by osantelices** [comment]
@niladam 

Yes, I have solved it that way, but I was wondering if there is a way for these buttons to be removed or displayed depending on the view in a simpler way

But I have solved it as shown in the code
thanks ;)

**Comment by niladam** [comment]
@osantelices well, not that i can see. However, you could create your own template by copying `list.blade.php` to say, `my-list.blade.php` and use that with:

```php
$this->crud->setListView('your-view');
```

**Comment by osantelices** [comment]
I will do what you say... 

thank you very much
