### ISSUE TITLE
Included select2 version is really old

### ISSUE THREAD

**Issue by niladam** [Laravel-Backpack/CRUD#884]
Hello,

Is there any reason why the select2 included is an older version ? The currently included version is (as per `public/vendor/backpack/select2/`) is `3.5.2` when the latest version of https://github.com/select2/select2/releases is `4.0.3` -- which was released on 27th of May 2016 and according to the releases page `3.5.3` (i **can't** even find `3.5.2`) was released on 30 August 2015.

I'm asking because i'd manually update it but i'm afraid it might break something..

**Comment by lloy0076** [comment]
They haven't been updated yet - that's all; feel free to update them but you *might* find issues that we haven't seen yet.

**Comment by niladam** [comment]
Just a quick heads-up. Upgrading select2 will break, as some methods were removed from the latest version. It appears that using the **full** select2 MIGHT sort out some issues, but there's no actual plug&play solution for this.

I think this is something that should also be taken care in this package..

**Comment by tabacitu** [comment]
Hi @niladam - the latest Backpack uses select2 4.0.3 (the one provided by AdminLTE). I recommend you upgrade Backpack to the latest version and republish your assets.

Cheers!
