### ISSUE TITLE
`create.blade.php` not sure, but may be issue...

### ISSUE THREAD

**Issue by BinaryBlock** [Laravel-Backpack/CRUD#89]
Hey,

I was getting some exceptions and was debugging a `/CRUD` create request. I noticed that there are actually two `_token` POST parameters being sent. Perhaps one of them needs to be removed from the Blade file?

1. First `<input` is automatically being generated by the `{{ Form::open(...`
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/create.blade.php#L24
```PHP
{!! Form::open(array('url' => $crud->route, 'method' => 'post')) !!}
```

2. Second `<input` is explicitly being stated here:
https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/create.blade.php#L61
```PHP
<input type="hidden" name="_token" value="{{{ csrf_token() }}}" />
```

I would suggest removing line: https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/create.blade.php#L61

Hope that helps. If I'm off-base... just say so... just trying to help. 😄

**Comment by tabacitu** [comment]
Damn. You're right, of course :-) I'll remove the hidden input, it's no loger necessary.

Cheers!

**Comment by tabacitu** [comment]
Done, thanks again. Cheers!
