### ISSUE TITLE
Accessing the current crud model in a crud menu?

### ISSUE THREAD

**Issue by aligholamee** [Laravel-Backpack/CRUD#891]
I'm trying to add a new button to one of my crud tables. I have "edit" and "delete" buttons there by default but, I wan't to have another button for another functionality. The problem is that if i add the button explicitly in the "update.blade.php", all of the crud models will be affected. So i need to check for the current model i'm in, and decide whether to show that button or not. This can be done easily by specifying a simple if phrase in the blade file. How can i access the model name to check the condition?

**Comment by aligholamee** [comment]
This was done by adding a {{ dd($crud) }} to the blade file i was trying to add condition to and watching the variables inside the crud global variable. There is also another variable called "$entity" which provides the data inside our tables.

**Comment by iMokhles** [comment]
I guess you can get what you want easily without editing blades through

https://laravel-backpack.readme.io/docs/crud-buttons

in your controller

```
 $this->crud->addButtonFromModelFunction('line', 'open_google', 'openGoogle', 'beginning'); // add a button whose HTML is returned by a method in the CRUD model
```

in your model

```
public function openGoogle($crud = false)
    {
        return '<a class="btn btn-xs btn-default" target="_blank" href="http://google.com?q='.urlencode($this->text).'" data-toggle="tooltip" title="Just a demo custom button."><i class="fa fa-search"></i> Google it</a>';
    }
```
