### ISSUE TITLE
I having troblue with the field type select

### ISSUE THREAD

**Issue by jllopiz90** [Laravel-Backpack/CRUD#900]
Hi,
          I'm starting to use backpack and i'm trying to use the select field type without success. I have a model Message with these 2 relationships to User  model:

public function sender(){
        return $this->belongsTo('App\User','sender_id');
}

public function recipient(){
        return $this->belongsTo('App\User','recipient_id');
}

In my MessageCrudController I have this:

$this->crud->addField([
            'label' => 'Sender',
            'type' => 'select',
            'name' => 'sender_id', // the db column for the foreign key
            'entity' => 'sender', // the method that defines the relationship in your Model
            'attribute' => 'name', // foreign key attribute that is shown to user
            'model' => 'App\User' // foreign key model
]);

But when i go to the create view '/admin/message/create'   I got this:

(7/7) ErrorException
An exception occurred while executing 'SELECT
a.attnum,
quote_ident(a.attname) AS field,
t.typname AS type,
format_type(a.atttypid, a.atttypmod) AS complete_type, (SELECT tc.collcollate FROM pg_catalog.pg_collation tc WHERE tc.oid = a.attcollation) AS collation,
(SELECT t1.typname FROM pg_catalog.pg_type t1 WHERE t1.oid = t.typbasetype) AS domain_type,
(SELECT format_type(t2.typbasetype, t2.typtypmod) FROM
pg_catalog.pg_type t2 WHERE t2.typtype = 'd' AND t2.oid = a.atttypid) AS domain_complete_type,
a.attnotnull AS isnotnull,
(SELECT 't'
FROM pg_index
WHERE c.oid = pg_index.indrelid
AND pg_index.indkey[0] = a.attnum
AND pg_index.indisprimary = 't'
) AS pri,
(SELECT pg_get_expr(adbin, adrelid)
FROM pg_attrdef
WHERE c.oid = pg_attrdef.adrelid
AND pg_attrdef.adnum=a.attnum
) AS default,
(SELECT pg_description.description
FROM pg_description WHERE pg_description.objoid = c.oid AND a.attnum = pg_description.objsubid
) AS comment
FROM pg_attribute a, pg_class c, pg_type t, pg_namespace n
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') AND c.relname = 'messages' AND n.nspname = ANY(string_to_array((select replace(replace(setting,'"$user"',user),' ','') from pg_catalog.pg_settings where name = 'search_path'),','))
AND a.attnum > 0
AND a.attrelid = c.oid
AND a.atttypid = t.oid
AND n.oid = c.relnamespace
ORDER BY a.attnum':

SQLSTATE[XX000]: Internal error: 7 ERROR: unimplemented at or near "user"
SELECT
a.attnum,
quote_ident(a.attname) AS field,
t.typname AS type,
format_type(a.atttypid, a.atttypmod) AS complete_type, (SELECT tc.collcollate FROM pg_catalog.pg_collation tc WHERE tc.oid = a.attcollation) AS collation,
(SELECT t1.typname FROM pg_catalog.pg_type t1 WHERE t1.oid = t.typbasetype) AS domain_type,
(SELECT format_type(t2.typbasetype, t2.typtypmod) FROM
pg_catalog.pg_type t2 WHERE t2.typtype = 'd' AND t2.oid = a.atttypid) AS domain_complete_type,
a.attnotnull AS isnotnull,
(SELECT 't'
FROM pg_index
WHERE c.oid = pg_index.indrelid
AND pg_index.indkey[0] = a.attnum
AND pg_index.indisprimary = 't'
) AS pri,
(SELECT pg_get_expr(adbin, adrelid)
FROM pg_attrdef
WHERE c.oid = pg_attrdef.adrelid
AND pg_attrdef.adnum=a.attnum
) AS default,
(SELECT pg_description.description
FROM pg_description WHERE pg_description.objoid = c.oid AND a.attnum = pg_description.objsubid
) AS comment
FROM pg_attribute a, pg_class c, pg_type t, pg_namespace n
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') AND c.relname = 'messages' AND n.nspname = ANY(string_to_array((select replace(replace(setting,'"$user"',user),' ','') from pg_catalog.pg_settings where name = 'search_path'),','))
^ (View: /var/www/html/vendor/backpack/crud/src/resources/views/fields/select.blade.php) (View: /var/www/html/vendor/backpack/crud/src/resources/views/fields/select.blade.php) (View: /var/www/html/vendor/backpack/crud/src/resources/views/fields/select.blade.php) (View: /var/www/html/vendor/backpack/crud/src/resources/views/fields/select.blade.php)

Any idea what I'm doing wrong? Thanks in advance.

**Comment by OwenMelbz** [comment]
Hi @jllopiz90 

Github is for package bugs not support - Your best off asking in stackoverflow for support.

I'm going to close this to keep the area tidy - although everybody is free to reply if they want.

I would say those queries run look like nothing to do with backpack, the convention used is 100% not traditional laravel, so the issue may lay with a custom way of doing things.

I would suggest stepping through the code, removing line by line until it works, then you identify what breaks it, then investigate that.

If its a specific relationship that doesnt work, try a differnt one to test with

**Comment by jllopiz90** [comment]
You are right, it seems to be something with the relationship.
