### ISSUE TITLE
[My Experience] i was able to change the current AdminLTE theme, how it looks like now & how i achieved that

### ISSUE THREAD

**Issue by iMokhles** [Laravel-Backpack/CRUD#903]
# Here's my current theme

Login Page
<p align="center">
  <img width="640" src="http://i.imgur.com/duV8FpU.png"/>
</p>

Dashboard
<p align="center">
  <img width="640" src="http://i.imgur.com/IDd5icg.png"/>
</p>

DataTable, Actions etc
<p align="center">
  <img width="640" src="http://i.imgur.com/A0bVXvU.png"/>
</p>

# How i changed current AdminLTE theme by another admin panel theme to works well with every feature

### How i setup Dashboard and Navigation Menu

1. got another admin panel theme which has HTML version
2. created new layout file and added all `@yields` as in the [original layout file](m/Laravel-Backpack/Base/blob/master/src/resources/views/layout.blade.php)
3. created new separated `header.blade` file ( which contains title and authenticated user info in my case it has ( user image with dropdown menu with other options ) put there new code and changed the title values to get the title values from` base.php` config file
4. my new theme has horizontal navigation menu class so i created new separated `menu.blade` file and put there the basic code from my new theme
5. created new separated `breadcrumb` file called it  `breadcrumb.blade` and put there my theme `custom breadcrumb code` [ this wasn't need as i did exactly the same as `base package` i reduplicate the same `breadcrumb` code in each `header section` [header yeild](https://github.com/Laravel-Backpack/Base/blob/master/src/resources/views/layout.blade.php#L86)
6. created new separated `dashboard.blade` to extends the new layout 

after that i was able to get an empty dashboard page and menu waiting my custom setup
## Note: 
you can replace original `layout.blade` styles links and scripts links ( so all you have to do editing current files and changing `classes` so you will get the same result.

### How i setup Crud list ( hadn't time to finish edit and preview but it won't take a lot of time after finishing the list [dataTable] )

1. replaced datatable css and js files with thee custom datatable css/js files from my new admin panel theme then put/replaced necessary class names   ( i guess that's all ) i hadn't done a lot of stuff here
2. list actions buttons inside `buttons folder ` i have replaced create/delete/update/preview `<a> tag` classes ( and that's all )

that's what i have done and the result as you see above, it took almost 2H to achieve what i have done, hope we can see easier way to done changing themes..

**Comment by lloy0076** [comment]
@OwenMelbz - IMHO this isn't a question but it's useful information to know.

@tabacitu - something like this could fit into a 'snippets' or maybe 'tutorial' section on the web-site itself (with the caveat that unless it's posted by an official team member and marked as such, it's not guaranteed to work etc etc). I thought there was such a place but I can't find it at the moment.

**Comment by tabacitu** [comment]
@iMokhles this is great, thank you for sharing it with everyone. I'm 100% sure someone will want to do this and your steps will help them. 

I see you have a nice website and a well-crafted personal brand, what do you think about creating a [medium](http://medium.com/) profile or other type of blog, where you can post stuff? You could polish these steps a little bit and create your first article, and I'd be happy to include a link to it in the Backpack blog. I think it's a win-win: 
- you get more visitors on your website and an increased personal brand
- the Backpack community gets to find out about how to do this

What say you?
![giphy](https://user-images.githubusercontent.com/1032474/30055540-78a38f3c-9238-11e7-8dd7-19e233b70cf0.gif)

**Comment by iMokhles** [comment]
Haha thanks I tried my best as my English isn't my first language.
here's my medium post
https://medium.com/p/how-to-change-laravel-backpack-admin-panel-theme-c52a6b28d66b

**Comment by tabacitu** [comment]
Awesome! Thank you @iMokhles  - I'll promote this in this month's newsletter.

Cheers!
