### ISSUE TITLE
Laravel 5.5 update results in bindShared() and getToken() errors originating from laravelcollective package

### ISSUE THREAD

**Issue by pjhartin** [Laravel-Backpack/CRUD#907]
**What you did**
Upgraded from L5.4 to 5.5

**What you expected to happen**
For the admin panel to continue working.

**What happened**
Received numerous errors upon `composer install` or `update` relating to `bindShared()` method call. 
Once this is fixed by doing the steps below, then issues relating to the use of `getToken()` appear when navigating to any `/create` template due to the form builder.

**What have you already tried to fix it?**
Both issues are the result of methods being called in `vendor/laravelcollective/html/src/HtmlServiceProvider`

- Replaced the `$this->app->bindShared` method calls with `$this->app->singleton` to fix the `bindShared` errors.
- Replaced `getToken()` method calls with simple `token()` method calls.

---

It seems the latest version of the `laravelcollective/html` package has the relevant changes:
https://github.com/LaravelCollective/html/commit/b91158bae58a6e9d90e74f87f5a91fe77c518c85

I would request that this package version be added into the composer.json of this CRUD library

**Comment by tabacitu** [comment]
Hi @pjhartin ,

Thanks for the detailed report. This error has been reported before and it's a serious one but damn it... I haven't been able to replicate it...

Can you please check something for me? If you include this in you project's ```composer.json``` file, does it pull in this different project, with the hotfix?

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cmizzi/html"
        }
    ]
```

Thanks a lot, cheers!

**Comment by shadowbane** [comment]
Hi @tabacitu, 

I can use the repositories that you suggested, but I need to manually requiring it before pulling backpack/crud with:
`composer require laravelcollective/html "dev-master as 5.0.5"`

Thanks!

**Comment by LordRathan1** [comment]
It seems that an update for laravelcollective/html to the actual versioin 5.4 fix the problem.

**Comment by tabacitu** [comment]
Thank you @shadowbane . I've just tested and added your instructions to [the L5.5 installation docs](https://laravel-backpack.readme.io/docs/install-on-laravel-55#section-3-install-backpackcrud) so that everybody knows. I found no way to include this fix in the package - it kept triggering "required stability" errors.

This is pretty uncomfortable though. Let's leave this issue open until laravelcollective fixes it and we have a permanent solution.

**Comment by ajnozari** [comment]
I believe laravel collective/html has been updated with the appropriate changes as of the push a few hours ago.

**Comment by tabacitu** [comment]
Thanks for the update @ajnozari . I've just checked and you're right, the latest update brings L5.5 compatibility and installing backpack/crud now works normally, no temporary package needed. Thanks a lot for helping on this, you guys.

---

## How to go back

If you've used the ```cmizzi/html``` repository in this 24-hour window, you can now remove it from your project's ```composer.json``` file , by removing it from:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cmizzi/html"
        }
    ]
```
and from you ```require``` array, then running ```composer update```.

---

This matter is now officially closed. Pfiew :-) 
Thanks, cheers!
