### ISSUE TITLE
[Proposal] Remove laravelcollective/html dependency

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/CRUD#910]
This package might be unnecessary. 

Since every dependency makes us less agile, I propose we remove it entirely. We should not depend on their updates for our updates (context: see https://github.com/Laravel-Backpack/CRUD/issues/907; we provided L5.5 support before them, we're now waiting for them to update too; in the meantime we're forced to use a fork and have an extra step in the backpack/crud installation process; bleah).

There are very few places where it's used, mainly to open and close forms:
- create.blade.php
- edit.blade.php
- revision_timeline.blade.php
- language_inputs.blade.php
- translations.blade.php

What do you guys think? Any other places I missed?

**Comment by lloy0076** [comment]
I'd be inclined to remove it.

**Comment by Sobak** [comment]
Definitely agreed. This package only brings some helpers (and backpack uses just few of them) which can be easily replaced

**Comment by tabacitu** [comment]
Update: now that we're trying to provide L5.6 support we're facing the same problem - everything's ready for L5.6, minus laravelcollective/html. Definitely needs to be removed. I've done so for CRUD in PR #1226.
