### ISSUE TITLE
Some new fields and columns

### ISSUE THREAD

**Issue by bul-ikana** [Laravel-Backpack/CRUD#914]
Some custom fields and columns I made for a pet project. I thought they could be useful:

 * Read-only text field: A field that is enabled when creating a model, but disabled when updating it. It is really set as readonly, so the value will be still sent with the form. Useful for values that should only be set when creating and never updated, or when users have no permission to update that field but must be able to see their value.  PR #912

* Image-url column: A column showing a thumbnail of an image loaded by its url. The image is loaded in another tab when the thumbnail is clicked. If the model has no image, a simple dash will be shown. Image thumbnails by default have 25px heigth and auto width, but this can be overriden passing `width` and `height` when defining the column. PR #913

**Comment by tabacitu** [comment]
Thank you @bul-ikana ! I'll reply inside each PR, so let's close this issue.

Thanks again for the contribution. Cheers!
