### ISSUE TITLE
Cleaning up the HTML

### ISSUE THREAD

**Issue by BinaryBlock** [Laravel-Backpack/CRUD#92]
Hey... I'm noticing a lot of these comments in the HTML of the `/CRUD`:
`<!-- load the view from the application if it exists, otherwise load the one in the package -->`
![image](https://cloud.githubusercontent.com/assets/8375856/17907929/0f56203c-694c-11e6-83a5-24bf3bc82201.png)

(one page I found 280 of these)
I believe the list view it is located here:
https://github.com/Laravel-Backpack/CRUD/blob/502486a6b63479f003cc870130891c82e428e529/src/resources/views/list.blade.php#L60

Would it be better to remove this... or am I doing something wrong?

What's your thoughts.

**Comment by tabacitu** [comment]
Yes, you're right, of course. Fixed in [3.0.16](https://github.com/Laravel-Backpack/CRUD/commit/e26efef5a099b5cb3a83ee7e223c617b5fe5f221). ```composer update``` should fix it for you.

Cheers!

**Comment by BinaryBlock** [comment]
Thanks @tabacitu . I'm sure these Issues seem lame, but I'm still fairly new to Laravel. I want to try to contribute to your awesome work in any way I can (that is helpful), because it has been über-useful to my project. This has single-handedly save me 100's of man hours of coding CRUD, ADMIN UI, and much more. Man... even the included AJAX pagination is a mind-blowing time saver.

**Comment by tabacitu** [comment]
No, thank YOU :-) All help is appreciated.
