### ISSUE TITLE
Unable to add field during creation for fields that require the model id.

### ISSUE THREAD

**Issue by michaellindahl** [Laravel-Backpack/CRUD#924]
I've overridden a field in my model so that the user can create this model relationship when the user creates the parent model. Instead of using an image directly on the model, I have an Image model that allows me to attach multiple images to the model. The only problem with this is when the user creates the model with the image it fails with the SQL error on the child object as the parent model_id has not yet been created. This is fine when the parent model already exists but fails when the user is creating the parent model.

**Comment by tabacitu** [comment]
I think this is a good feature. Since there's already a PR for this, I say let's move the entire conversation there - #925
