### ISSUE TITLE
Multiple browse field

### ISSUE THREAD

**Issue by chancezeus** [Laravel-Backpack/CRUD#931]
For a project I wanted a browse field with support for multiple files, looking at the various sources  (`browse.blade.php` and elFinder views/js) I found that neither really support multiple select. For a previous project I made a quick and dirty workaround but this time I wanted a more stable variant. Starting from the `browse.blade.php` I made a custom field and modified it as required.
I created a gist of the file and welcome any comments, if interested I can create a pull request for it.

[browse_multiple.blade.php](https://gist.github.com/chancezeus/47f19a12a0e35caf63946fd4a72bf7bd)

**Comment by lloy0076** [comment]
Looks interesting - @tabacitu is there a way to handle snippets/suggestions and such that won't clutter up github issues? And also is this worth turning into a PR?

**Comment by tabacitu** [comment]
OMG. I love this. @chancezeus , do you mind creating a PR with this, so that you bump your number of contributions in the stats? :-)

@lloy0076 - thanks for surfacing this. Definitely worth including in the core if it's plug-and-play, I agree.

**Comment by chancezeus** [comment]
Just created the pull request.

It is definitely plug-and-play since it uses the same functionality as the regular browse field.

Difference between the two is that the original browse field uses the elfinder popup url provided by the elfinder package and this one instead creates a (new) div element and attaches that inside the colorbox.

By using a div element we are able to directly access all of elfinder configuration properties. For now I only included mime filtering (onlyMimes) and multiple select mode, but more can be added.

**Comment by lloy0076** [comment]
This is #1034.

Closing in favour of the PR.
