### ISSUE TITLE
Reorder fails in Laravel v 5.3 and MySQL 5.7

### ISSUE THREAD

**Issue by vishalbhide** [Laravel-Backpack/CRUD#94]
In Laravel v 5.3 and MySQL 5.7, reorder fails. 

A] Bug Description -

1. Prior to v 5.3, MySQL strict mode was not strict (I am too lazy to lookup the exact MySQL behavior, so just mentioning that MySQL mode was not strict, just to give you an idea)
2. Because of this, when we try to reorder the 'parent_id, depth, left, right' fields, even if these fields are blank (e.g. ''), these were automatically converted to null by MySQL, and hence they didn't cause issues. 
3. But in v 5.3, the strict mode is enabled by default (see 'strict' => true entry for MySQL in config/database.php). Because of this, MySQL does not auto convert empty fields to null, and throws an error when trying to update the database.

B] Fix - 
The bug is in the Reorder::updateTreeOrder method. The right fix for MySQL, is to add a null and empty check below assigning the fields to the model. i.e. to change the below code from 

> $item->parent_id = $entry['parent_id'];
> $item->depth = $entry['depth'];
> $item->lft = $entry['left'];
> $item->rgt = $entry['right'];

to

> if(isset($entry['parent_id']) && !empty($entry['parent_id'])) {
>   $item->parent_id = $entry['parent_id'];
> }
> 
> if(isset($entry['depth']) && !empty($entry['depth'])) {
>   $item->depth = $entry['depth'];
> }
> 
> if(isset($entry['left']) && !empty($entry['left'])) {
>   $item->lft = $entry['left'];
> }
> 
> if(isset($entry['right']) && !empty($entry['right'])) {
>   $item->rgt = $entry['right'];
> }

Note: I have tested this only on MySQL, and not on other databases, but I don't think this should cause issues.

C] Workaround - Until the bug is fixed, other 5.3 users can switch off the strict mode (just set strict to false in database.php)

**Comment by tabacitu** [comment]
Thanks for the bug report and suggestion, @vishalbhide . It's now fixed at CRUD-level, no need for tweaks in your controllers. MySQL strict mode can remain on.

Cheers!
