### ISSUE TITLE
Installing CRUD package have [ Failed to execute unzip ] issue with 5.5

### ISSUE THREAD

**Issue by iMokhles** [Laravel-Backpack/CRUD#948]
I attached image has exactly the error message I got 

![capture d ecran 2017-09-09 a 17 19 25](https://user-images.githubusercontent.com/1247248/30241413-3881bf70-9583-11e7-8b55-89ce8e6b88e3.png)

**Comment by niladam** [comment]
Does it ask for interaction ? Because if it does, entering "**A**" ([*A*]ll) will allow you to pass this step.

If it doesn't then the problem lies elsewhere and maybe someone more experienced than me might be able to help :)

**Comment by iMokhles** [comment]
no it doesn't but setup done well and the issue I figure that there are two `zh-CN` folders one with `CN` capital letters and other `cn`

[CRUD/resources/lang](https://github.com/Laravel-Backpack/CRUD/tree/master/src/resources/lang)
![capture d ecran 2017-09-11 a 12 59 01](https://user-images.githubusercontent.com/1247248/30271546-0047b8d4-96f1-11e7-840c-604bbffa15fc.png)

so the issue is identified we need just a simple remove for one of those folders

**Comment by lloy0076** [comment]
Yes, this is the `two zh-CN/zh-cn` folder problem - I believe it's fixed upstream.

**Comment by tabacitu** [comment]
Fixed! Thank you. Please let me know if you still have this issue.
