### ISSUE TITLE
Cannot access current user in controller

### ISSUE THREAD

**Issue by swilla** [Laravel-Backpack/CRUD#95]
I've tried the following: 

```
auth()->user();
```

```
Auth::user();
```

All of them are returning null.  I've tried to add some middleware to the  route group: 
```
Route::group([
    'prefix' => 'admin',
    'middleware' => [
        'auth',
        'role:admin,access_backend'
    ]
], function () {
    CRUD::resource('brands', 'Admin\BrandCrudController');
});
```

Am I missing something?

**Comment by axyr** [comment]
https://github.com/laravel/framework/issues/15072

And a shitload of other tickets regarding this issue...

**Comment by tabacitu** [comment]
Apparently this is a know breaking change in Laravel 5.3, just like @axyr said. I've found this solution:
```php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;

class ProjectController extends Controller
{
    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->projects = Auth::user()->projects;

            return $next($request);
        });
    }
}
```
from [this article](https://laravel-news.com/2016/08/controller-construct-session-changes-in-laravel-5-3/), but... it doesn't look very sexy to me.

**Comment by tabacitu** [comment]
We've included a simpler solution into ```Backpack\CRUD 3.1.20``` - that middleware closure is run automatically inside a new ```CrudController::setup()``` method, so you can define your CRUD there and use session variables.

So: **If you want to use ```Auth```, you only need to rename your ```__construct()``` into ```setup()```**. _Magic_, I know :-)

Note: This change is backwards-compatible. You can still define everything inside ```__construct()``` if you want.

**Comment by iwillhappy1314** [comment]
Awesome! test ok!

**Comment by Slaycaster** [comment]
Tried it, works like magic! Thanks!
