### ISSUE TITLE
Wrong translation insert

### ISSUE THREAD

**Issue by microdesign** [Laravel-Backpack/CRUD#950]
I use your recommendation for a translation package but when I use the crud I have these in my DB records 

{"bg":"\u0442\u0435\u0442\u0441 \u0431\u0433 3"}

which make searches on this impossible.

What is your suggestion about this problem?

**Comment by lloy0076** [comment]
This question might best be asked at https://stackoverflow.com/search?q=laravel+backpack.

That's obviously unicode escaped values and you might start at https://stackoverflow.com/questions/13287145/mysql-querying-for-unicode-entities#13327605 maybe?
