### ISSUE TITLE
Pass variables to a non line button

### ISSUE THREAD

**Issue by glorand** [Laravel-Backpack/CRUD#951]
How we can pass variables to a non line button view. 
In the definition of the "addButton" (* @param string $content  The HTML for the button)
the $content is the HTML content but this isn't true. The $content is the name of the view file.

**Comment by glorand** [comment]
> The most useful variables you'll have in this file here are:
> 
> $entry - the database entry you're showing (only inside the line stack);
> $crud

The crud variable is not available on the top or bottom type buttons

**Comment by jsiebach** [comment]
You can use a model function instead of a view:

    // add a button whose HTML is returned by a method in the CRUD model
    $this->crud->addButtonFromModelFunction($stack, $name, $model_function_name, $position);

**Comment by lloy0076** [comment]
Answered.
