### ISSUE TITLE
select2_from_array without pivot table this is possible?

### ISSUE THREAD

**Issue by osantelices** [Laravel-Backpack/CRUD#957]
Hello Everyone good morning

I have on my controller this code
`[ // select_from_array
			    'name' => 'forma_int',
			    'label' => "Forma de Integración",
			    'type' => 'select2_from_array',
			    'options' => ['WEBSERVICE' => 'WEBSERVICE', 'BIZTALK' => 'BIZTALK'],
			    'allows_null' => false,
			    'allows_multiple' => true, // OPTIONAL; needs you to cast this to array in your model;
			    'pivot' => true
			]`

I dont have a pivot table
and I have this error message send to me for SQL

**"Array to string conversion "**

select2_from_array without pivot table this is possible?

thanks for all

**Comment by lloy0076** [comment]
I don't think what you're doing is possible (obviously) but a hunch says to me that if you rethink what you are doing maybe the AJAX versions may work?

https://laravel-backpack.readme.io/docs/crud-fields#section-select2_from_ajax_multiple

**Comment by lloy0076** [comment]
I'd suggest trying with AJAX.
