### ISSUE TITLE
Select2Multiple = n-n relationship (with pivot table) with filtering

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/CRUD#959]
Is possible to add a filtering features, so, show only some records with some scopes?

**Comment by lloy0076** [comment]
I would assume yes - are you *really* asking are there example(s) of this out there or is it implemented by default?

1. There may be examples;
2. I'm not sure that it's implemented by default but even I miss things in the documentation sometimes :)

**Comment by EmanueleCoppola** [comment]
It's more like a "wouldn't be cool if we can have a flag like scope to specify a custom local scope" for the relationships?

**Comment by tabacitu** [comment]
Yup, agree. It's planned but it might take some time. In the meantime you can create a new model, that extends your old model and adds a global scope. Then just use this scoped model wherever you need.

Hope it helps. Cheers!
