### ISSUE TITLE
wysiwyg/ckeditor allowedContent

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/CRUD#96]
I didn't find where do i modify ckeditor config to allow more html tags. Can anyone help with this?

I am interested in adding some html5 tags like video, source...

**Comment by tabacitu** [comment]
Hi @AurelDragut ,

You should checkout out ```public/vendor/backpack/ckeditor```. That's where the ckeditor we us is stored. Checkout out the [config.js](http://docs.ckeditor.com/#!/api/CKEDITOR.config) file and the plugins folder.

Cheers!

**Comment by AurelDragut** [comment]
Sorry, i forgot to close this issue after i got the solution. Also i modified the wysiwyg field file instead of the config.js.

**Comment by kappafix** [comment]
@AurelDragut I have a similar problem, I have to enable iframe tag on ckeditor, how do you solved the problem to enable more tags? When I save the data, everything works, but when I reopen it, all the extra tags are "cleaned/stripped" away.
Tks in advance
