### ISSUE TITLE
Compatibility with Base 0.8.0

### ISSUE THREAD

**Issue by RedAB** [Laravel-Backpack/CRUD#965]
Hi, is the CRUD package compatible with the incoming 0.8.0 version of Base ? As I am already using it with the `dev-upgrade` branch, is it possible to update the dependencies to make the CRUD package compatible with it ? Thanks !

**Comment by tabacitu** [comment]
Thanks for closing the issue. Very glad to hear you're using the upgrade branch. Please let us know if you find any bugs. Cheers!
