### ISSUE TITLE
The CrudPanel hasAccessOrFail method from in the Access trait should not throw an HTTP error

### ISSUE THREAD

**Issue by tumf87** [Laravel-Backpack/CRUD#968]
Currently, the `Access#hasAccessOrFail` method calls the Laravel `abort` function, which, in turn, throws a HTTPException.

Since it's a CrudPanel method, it should fail with a `AccessDeniedException`.

The documented return type of the method is `bool|null`, but in case of success, the method doesn't return anything.

**Comment by tabacitu** [comment]
Agreed! Merged.
