### ISSUE TITLE
Allow HTML in field labels

### ISSUE THREAD

**Issue by se1exin** [Laravel-Backpack/CRUD#97]
During development of a project today I noticed that some fields allow HTML in field labels (e.g. `text.blade.php`) whilst others do not (e.g. `textarea.blade.php`).

I find the ability to use HTML in the label very useful for adding custom 'required' statements to the label. For example:

```php
$this->crud->addField([
            'name' => 'overlay_title',
            'label' => 'Overlay Title <em><small>required</small></em>',
            'type' => 'text'
            ]);
```

The only thing that needs to change is the `<label>` line in each template to change from:
`<label>{{ $field['label'] }}</label>`
to:
`<label>{!! $field['label'] !!}</label>`

I'm putting a PR together for this right now, but any other feedback on the pros/cons of implementing this are welcomed.

**Comment by tabacitu** [comment]
You're totally right, that SHOULD be available for all field types. Thanks for the PR!
Cheers!

**Comment by wtime** [comment]
For escape the label of the checklist you need to do this:

CRUD/src/resources/views/fields/checklist.blade.php

#17                      @endif > {!! $connected_entity_entry->{$field['attribute']} !!}

**Comment by tabacitu** [comment]
Sorry @wtime , I didn't get that. Could you please rephrase it? Cheers!

**Comment by wtime** [comment]
change
 {{ $connected_entity_entry->{$field['attribute']} }}

to

 {!! $connected_entity_entry->{$field['attribute']} !!}

for correct HTML unescaping of the label of the checklist field.

PATH: CRUD/src/resources/views/fields/checklist.blade.php

**Comment by tabacitu** [comment]
Thank you @wtime . It's now fixed! 
Cheers!

**Comment by wtime** [comment]
Thank you for your great work!
