### ISSUE TITLE
Setting column order is not implemented

### ISSUE THREAD

**Issue by tumf87** [Laravel-Backpack/CRUD#971]
The CrudPanel `setColumnOrder` method in the Columns trait is exposed in the public API but is not implemented.

There is also an `orderColumns` method in the same trait (which also does not work).

@tabacitu, my proposal would be to just remove the `setColumnOrder` method and then fix the `orderColumns` method.

**Comment by tabacitu** [comment]
Hmm... I wonder if people have already used one or the other. I say we keep both methods, with one just an alias to the other. I don't see how they should do different things...

**Comment by tumf87** [comment]
@tabacitu, I've made a [PR](https://github.com/Laravel-Backpack/CRUD/pull/1011) for this.
