### ISSUE TITLE
Compacting fake fields fails when a fake field has the same value for 'name' and 'store_in'

### ISSUE THREAD

**Issue by tumf87** [Laravel-Backpack/CRUD#975]
The CrudPanel `compactFakeFields` method fails when given fields that have the same value for the 'name' and 'store_in' attributes:

Example:
```
[
    'name' => 'tags',
    'label' => 'Tags',
    'fake' => true,
    'store_in' => 'tags',
]
```

**Comment by tabacitu** [comment]
Completely agree. It should be stored as ```tags.tags``` in that case. Just merged your PR into dev, thanks!
