### ISSUE TITLE
The beforeField and afterField methods should contain an extra optional parameter

### ISSUE THREAD

**Issue by tumf87** [Laravel-Backpack/CRUD#977]
The CrudPanel `beforeField` and `afterField` methods in the Fields trait should contain an optional parameter in which we can specify the form in case the create/update forms contain different fields.

For backwards compatibility, it should default to 'both', which will keep the current functionality.

**Comment by tabacitu** [comment]
As we talked, completely agree. Merged your PR into dev. Cheers!
