### ISSUE TITLE
Setting a new model class to the crud panel should set the entry to null

### ISSUE THREAD

**Issue by tumf87** [Laravel-Backpack/CRUD#979]
When setting a model to the CrudPanel and calling the `getEntry` method from the Read trait, the entry gets cached.

Changing the model of the CrudPanel should invalidate the cache (setting the entry to null), otherwise it will return the old entry.

**Comment by tabacitu** [comment]
Fixed by your above PR on dev, so let's close this issue. Cheers, thanks!
