### ISSUE TITLE
The removeFields method asks for array of keys but works with array of fields

### ISSUE THREAD

**Issue by tumf87** [Laravel-Backpack/CRUD#983]
The CrudPanel `removeFields` in the Fields trait specifies that an array of field names should be passed, but works with an array of fields. 

All the attributes of a field in that array are then passed to the `removeField` method which calls an `array_forget` that might lead to undesired consequences (e.g.: when one of our fields has the same name as a backpack attribute).

**Comment by tabacitu** [comment]
Wow. Ok, I say we:

1) modify the docblock to specify you can pass:
- an array of field names
- an array of fields

2) fix the bug where it passes through the attributes, if a field has been passed
