### ISSUE TITLE
inline validation with nested fields

### ISSUE THREAD

**Issue by gotrecillo** [Laravel-Backpack/CRUD#986]
Right now the inline validation does not show when we do something like this to validate the laravel request.

```
[
    'db.database' => 'required',
    'db.username' => 'required',
    'db.password' => 'required',
    'filesystem.config.host' => 'required',
    'filesystem.config.user' => 'required',
    'filesystem.config.password' => 'required',
];
```

Because or names should be called like this.
```
[
    [
        'label' => trans('labels.db_name'),
        'name' => 'db[database]',
        'type' => 'text',
    ],
    [
        'label' => trans('labels.db_username'),
        'name' => 'db[username]',
        'type' => 'text',
    ],
    [
        'label' => trans('labels.db_password'),
        'name' => 'db[password]',
        'type' => 'password_revealer',
    ],
    [
        'label' => trans('labels.ftp_host'),
        'name' => 'filesystem[config][host]',
        'type' => 'text',
    ],
    [
        'label' => trans('labels.ftp_user'),
        'name' => 'filesystem[config][user]',
        'type' => 'text',
    ],
    [
        'label' => trans('labels.ftp_password'),
        'name' => 'filesystem[config][password]',
        'type' => 'password_revealer',
    ],
];
```

![image](https://user-images.githubusercontent.com/9203112/30597516-7d6b8b12-9d57-11e7-9060-2ac5a5e3563f.png)

**Comment by lloy0076** [comment]
* Do they work at all?
* Do they only work when the fields are named appropriately?
* If they don't work at all, is there a known fix (even if you don't have a PR)?
* Or what should the naming scheme be?

**Comment by gotrecillo** [comment]
Inline valdiation is working. But no when we validate nested attributes.

Top level validation works fine with nested attributes, the only issue is with the inline validation.
 
Our nested attributes looks like this
```
filesystem[config][host]
```

Laravel validations look like this
```
filesystem.config.host
```

Changing our schema to be like laravel validation can have breaking changes.

I submited a pull request fixing it only changing a view:
https://github.com/Laravel-Backpack/CRUD/pull/987

**Comment by tabacitu** [comment]
Hi @gotrecillo , thanks a lot for the PR. Just merged it into ```dev```.

Cheers!
