### ISSUE TITLE
Config CRUD

### ISSUE THREAD

**Issue by guillermohaad** [Laravel-Backpack/CRUD#99]
hi, 

I already have everything ready but when I try to enter the CRUD tells me that page not found
look:
![crud](https://cloud.githubusercontent.com/assets/12921805/18301852/0d9a4b7a-749a-11e6-8d60-ef9d5ad2176b.png)

***file routes.php****
<?php

// Admin Interface Routes
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard', 'Admin\AdminController@index');

    // [...] other routes

    // Dick CRUD: Define the resources for the entities you want to CRUD.
    CRUD::resource('tag', 'Admin\TagCrudController');
});

**Comment by tabacitu** [comment]
Hi @guillermohaad ,

Are you sure you have ```app\Http\Controllers\Admin\TagCrudController.php``` and its namespace is correct? It sounds exactly like a controller misconfiguration.

Cheers!

Cheers!

**Comment by guillermohaad** [comment]
Hello friend, nice to talk to you again
attached image file structure and controller file, thank you
![controler](https://cloud.githubusercontent.com/assets/12921805/18321136/572583a6-74f2-11e6-9f78-b818161f9e10.png)
----- TagCrudController.php ----------------

<?php namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

// VALIDATION: change the requests to match your own file names if you need form validation
use App\Http\Requests\StoreTagRequest as StoreRequest;
use App\Http\Requests\UpdateTagRequest as UpdateRequest;

class TagCrudController extends CrudController {

  public function __construct() {
        parent::__construct();

        $this->crud->setModel("App\Models\Tag");
        $this->crud->setRoute("admin/tag");
        $this->crud->setEntityNameStrings('tag', 'tags');

        $this->crud->setColumns(['name']);
        $this->crud->addField([
                    'name' => 'name',
                    'label' => "Tag name"
                    ]);
    }

  public function store(StoreRequest $request)
  {
    return parent::storeCrud();
  }

  public function update(UpdateRequest $request)
  {
    return parent::updateCrud();
  }
}

-----------

**Comment by guillermohaad** [comment]
Friends all packages work great except this CRUD, which can be?

**Comment by tabacitu** [comment]
Are you using Laravel 5.3? If so, [the route file has changed](https://laravel.com/docs/5.3/routing#basic-routing) - it is now no longer ```app/Http/routes.php```, but ```routes/web.php``` and/or ```routes/api.php```. 

Was this the issue, I wonder?

**Comment by guillermohaad** [comment]
everything works great, you're an angel friend, thanks for teaching.
as I can donarte something thanks to this wonderful package?

excuse my English, we'll be in touch

**Comment by tabacitu** [comment]
Glad it's fixed! 

Sure, I've just setup the Patreon page, where you can [donate as little as $1/month](https://www.patreon.com/tabacitu) to help me spend more time on Backpack.

Contributing with bug reports and bug fixes is also very useful :-)

Cheers, thanks!

**Comment by guillermohaad** [comment]
ok, friend, I will proceed to donate,
Friend another question? me I can bring data from a database of SQL Server for a list control?

**Comment by tabacitu** [comment]
Great :-) I'm not pushing.

Theoretically, CRUDs work perfectly with SQL Server, because everything is done through Eloquent. I haven't tested it myself, but others are using it this way.

**Comment by guillermohaad** [comment]
thanks friend, you're great
